packages/fxa-admin-server/pm2.config.js
packages/fxa-admin-server/src/config/index.ts
packages/fxa-admin-server/src/subscriptions/stripe.service.spec.ts
packages/fxa-admin-server/src/subscriptions/stripe.service.ts
packages/fxa-admin-server/src/subscriptions/subscriptions.service.spec.ts
packages/fxa-admin-server/src/subscriptions/subscriptions.service.ts

- The link to the customer portal session was unnecessary.
- We can link directly to the customer dashboard instead.
- Switches link to point directly at the stripe customer dashboard.
- Updates tests.
- Fixes issue loading the current env's .json config file.
Closes: #13245

fix(admin-panel): Fix link to 'Manage Subscriptions' 

---

_dev/.stylelintrc
packages/fxa-content-server/app/styles/_mixins.scss
packages/fxa-content-server/app/styles/_state.scss
packages/fxa-content-server/app/styles/modules/_branding.scss
packages/fxa-payments-server/src/index.scss
packages/fxa-settings/src/styles/drop-down-menu.scss

- Stylelint had some errors/warnings. Now it doesn't.
- Ignores generated Tailwind files. FACT.
- Unignores fxa-content-server files. FACT.
- Fixes existing errors/warnings. FACT.
- Temporarily [famous last words] the `selector-max-id` rule by letting us have two ID selectors. FACT.
- Gets us closer to solving all the world's issues; one linter at a time. FACT-_ish_.
- Enforce additional stylelint rules, per https://github.com/mozilla/fxa/issues/11762#issuecomment-1023447957, although I'm still strongly in "Team Let's Do That in the Future" camp.
Closes: #13239 

fix(lint): Tweak some stylelint configs and fix content-server issues

---

packages/fxa-auth-server/lib/payments/paypal/client.ts
packages/fxa-auth-server/lib/payments/paypal/helper.ts
packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
packages/fxa-auth-server/test/local/payments/paypal.js
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
packages/fxa-shared/payments/stripe-firestore.ts

Because:
* We need to retain the user name on our billing records.
This commit:
* Copies the first/laast name into the Stripe billing record for PayPal
users.

feat(auth): copy paypal name into stripe record

---

packages/fxa-settings/src/components/BentoMenu/index.test.tsx
packages/fxa-settings/src/components/BentoMenu/index.tsx
packages/fxa-settings/src/components/DropDownAvatarMenu/index.test.tsx
packages/fxa-settings/src/components/DropDownAvatarMenu/index.tsx

- We want to ensure all user interactions meet accessibility standards
- Adds aria-label along with title for increased screen reader support
- Replaces aria-controls with aria-haspopup for increased a11y support
Closes: #12915

fix(a11y): updates a11y on dropdown bento menu

---

packages/fxa-content-server/server/lib/configuration.js

- A bug report was filed where the invalid redirectTo error was triggered
- Adds *.mozgcp.net to the default white list
Closes: #12108

fix(content): Allow list missing mozgcp.net

---

packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml
packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.txt
packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountFinishSetup/index.stories.ts

- the `subscriptionAccountFinishSetup` email encourages users to create a password, but has "Cancel subscription" and "Update billing information" links in the footer, which redirects users to a Sign In page when they do not have a password yet and causes an Invalid redirectTo alert.
- removes the footer links in the HTML and TXT emails, per confirmation from Legal
Closes: #12108
Before 
After

fix(email): Revise footer to add conditional for account finish setup

---

packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/includes.json
packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/index.stories.ts
packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts

- we are updating email copy
- updates the email copy for cadReminderSecond:
```
Don’t forget to sync!
[image]
Sync your bookmarks, passwords, open tabs and more – everywhere you use Firefox.
Plus, your data is always encrypted. Only you and devices you approve can see it.
```
Closes: #13041 
Before
After

refactor(email): Revise cadReminderSecond email

---

_dev/.stylelintrc
package.json
packages/123done/static/components/normalize.css
packages/123done/static/css/main.css
packages/fxa-content-server/app/styles/_base.scss
packages/fxa-content-server/app/styles/_mixins.scss
packages/fxa-content-server/app/styles/modules/_avatar_spinner.scss
packages/fxa-content-server/app/styles/modules/_branding.scss
packages/fxa-content-server/app/styles/modules/_custom-rows.scss
packages/fxa-content-server/app/styles/sync.scss
packages/fxa-settings/src/styles/slider.scss
yarn.lock

- Stylelint doesn't lint many styles.
- Extends "stylelint-config-recommended-scss"
Closes: #13306

fix(lint): Add more stylelint rules

---

packages/fxa-payments-server/src/lib/formats.ts
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionIapItem/SubscriptionIapItem.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionIapItem/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx

Because:
* We want to be able to view apple app store subs on the subs management page
This commit:
* Adds Apple IAP subscription items to sub management page
Closes #11940

feat(payments): add Apple App Store Subscriptions to Subscription Management Page

---

packages/fxa-auth-server/lib/routes/validators.js
packages/fxa-auth-server/test/local/routes/validators.js

Because:
* The fxa-auth-server was returning 500s for the support-panel route due to a response validation error.
This commit:
* Allows unknown properties on the web and Google Play subscription objects returned in the response.
* Adds the missing 'price_id' property as an optional property for Play subscriptions returned by the endpoint.
Closes #12055

fix(auth): make unknown properties valid for support-panel route

---

packages/fortress/package.json

- Stylelint was failing in fortress and blocking release.
- Temporarily removes lint:style from the lint script.

fix(fortress): Fix CI tests by temporarily disabling stylelint

---

packages/fxa-payments-server/src/components/AppLayout/index.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

* We want to ensure that our pages meet accessibility standards
* Adds landmarks to the following areas:
1. Breadcrumbs
2. Subscriptions/Contact Support row
3. Payment information row
4. Subscription item row(s)
5. Pocket external row
Closes: #12920

fix(a11y): add missing landmarks to Subscriptions page

---

packages/fxa-auth-server/lib/routes/subscriptions/paypal-notifications.ts
packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js

Because:
* We don't want to flag Sentry on every IPN message we intentionally
don't handle.
* Without seeing full payloads, it's hard to determine whether we should
handle a message or not.
This commit:
* Removes the sentry flagging of unhandled message types.
* Changes logging of the event to record them in production.
Closes FXA-4976.

feat(auth): log unhandled paypal ipn

---

packages/fxa-content-server/app/scripts/views/mixins/third-party-auth-mixin.js
packages/fxa-content-server/app/tests/spec/views/mixins/third-party-auth-mixin.js

- We were dropping the third party complete flow events when it redirected
- Flushes those metrics so that it gets logged correctly
- Only logs the top of funnel `enter-email.thirdPartyAuth` if user is in experiment
Closes: https://github.com/mozilla/fxa/issues/13379

fix(metrics): Flush metrics before completing sign-in

---

packages/fxa-profile-server/package.json
packages/fxa-profile-server/scripts/mocha-coverage.js
yarn.lock

- We want to update mocha to the latest version!
- Updates mocha to ^10.0.0, and updates the name of the executable accordingly (see [this](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#boom-breaking-changes))
Closes: #13435 
All tests passing.
Pull down this branch and make sure everything is working via a `yarn start`.
Verify that the mocha version is `^10.0.0` and that we reference `mocha.js` (not `mocha`) in making the `MOCHA_BIN` var on line 12 of `scripts/mocha-coverage.js`.
Run `yarn workspace fxa-profile-server test`
All tests should both run and pass.

chore(fxa-profile-server): upgrade mocha

---

packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/test/local/senders/emails.ts

- QA reported that the "Cancel subscription" and "Update billing information" footer links still appeared in stage
- revises subscriptionAccountFinishSetupEmail to include `isFinishSetup: true`
- adds tests that checks those footer links are not included in this email
Closes: #12108
I also ran `yarn write-emails` to check that the footer links are not included in this email

fix(email): Remove footer links from subscriptionAccountFinishSetup

---

packages/fxa-content-server/app/scripts/templates/pair/auth_allow.mustache
packages/fxa-content-server/app/scripts/views/pair/auth_allow.js
packages/fxa-content-server/app/tests/spec/views/pair/auth_allow.js

- The change password button did not redirect
- The way our current backbone app is setup we have to do the redirecting from within the controller and not view
- Instead of using an href, we perform redirect in controller for view
Closes: #13449 
Note that this is targetd on branc train-235 and will be a point release.

fix(bug): Fix change password not redirecting on pairing allow page

---

packages/fxa-profile-server/package.json
yarn.lock

- We're updating dependencies and sinon is behind on the profile server
- Updates the yarn.lock and sinon
Closes: #13438 
The sinon packages is used for testing. To make sure that updating it doesn't break anything, I ran tests before introducing changes, updated the package, and then ran tests again after rebuilding. All tests passed.

chore(deps): upgrade sinon on profile server

---

packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js

Because:
* We can safely ignore the account not existing for customer updates that
we trigger via API calls.
This commit:
* Updates the webhook handling code to not report sentry errors if the
webhook event is a result of our API call.
Closes #12996

feat(auth): ignore missing account for api calls

---

packages/fxa-auth-server/package.json
yarn.lock

Reverts mozilla/fxa#13511 - failed `deploy-packages`

Revert "chore(deps): bump i18n-iso-countries from 7.4.0 to 7.5.0"

---

packages/fxa-auth-server/config/index.ts
packages/fxa-payments-server/server/config/index.js

- we want a feature flag to control whether or not stripe should
automatically calculate tax for a customer and subscriptions
- add a feature flag to configs in auth and payment servers
Closes: #13315

feat(subscriptions): add feature flag for Stripe Tax

---

packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts

- lib/routes/subscriptions/stripe-webhook.ts(478,22): error TS2531: Object is possibly 'null', which is causing PRs to fail `deploy-packages`

fix(deps): Fix error - Object is possibly null

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx

- "Expires Invalid Date" appears as we no longer pull `customer.sources` due to Stripe changes. We should be looking at `customer.default_source` and then pulling that payment method to get the card.
- checks `customer.default_source` for card information
Closes: #10150

fix(auth-server): Fix "Expires Invalid Date" for cc info on Subscription Management

---

packages/fxa-content-server/app/scripts/lib/channels/web.js
packages/fxa-content-server/app/scripts/templates/pair/auth_complete.mustache
packages/fxa-content-server/app/scripts/views/pair/auth_complete.js
packages/fxa-content-server/app/tests/spec/lib/channels/web.js
packages/fxa-content-server/app/tests/spec/views/pair/auth_complete.js
packages/fxa-content-server/tests/functional/pairing.js
packages/fxa-content-server/tests/tools/firefox_profile_creator.js
packages/fxa-dev-launcher/profile.mjs

- Firefox View wants to be integrated into the pairing flow
- At the end of the pairing flow, the user is shown a button to continue to Firefox view
Closes: https://mozilla-hub.atlassian.net/browse/FXA-5321
To test this you need to be running the latest FF Nightly build and set the pref `browser.tabs.firefox-view=true`. It is kind of difficult to test but you should be able to run the `yarn test-pairing` from content-server directory.

feat(pair): Add button to open Firefox View after completing pairing

---

packages/fxa-auth-server/lib/payments/stripe.ts

Because:
* A StripeHelper method that had its retun type used elsewhere became
an async method and the ReturnType became a Promise. This caused a
different methods type checking to fail as a Promise cannot be
embedded in a Promise being returned.
This commit:
* Updates the type declaration to handle the method signature change.

fix(auth): update existing type

---

packages/fxa-payments-server/src/App.tsx
packages/fxa-payments-server/src/components/AlertBar/index.stories.tsx
packages/fxa-payments-server/src/components/AlertBar/index.test.tsx
packages/fxa-payments-server/src/components/AlertBar/index.tsx
packages/fxa-payments-server/src/components/DialogMessage/index.stories.tsx
packages/fxa-payments-server/src/components/DialogMessage/index.test.tsx
packages/fxa-payments-server/src/components/DialogMessage/index.tsx
packages/fxa-payments-server/src/components/FetchErrorDialogMessage.tsx
packages/fxa-payments-server/src/components/PlanErrorDialog/index.tsx
packages/fxa-payments-server/src/routes/Checkout/index.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/SuccessDialog.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx
packages/fxa-react/components/Portal/index.test.tsx
packages/fxa-react/components/Portal/index.tsx
packages/fxa-settings/src/components/Modal/index.test.tsx
packages/fxa-settings/src/components/Modal/index.tsx

- we are missing ARIA attributes within `<div class="portal" id="dialogs" role="dialog">` DOM elements
Closes: #12922
- `id` set to `dialogs`
- `id` set to `modal`
- `id` set to `top-bar`

fix(a11y): ARIA nodes should have an accessible name

---

packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
packages/fxa-auth-server/test/local/payments/stripe-firestore.js
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
packages/fxa-shared/payments/stripe-firestore.ts
packages/fxa-shared/payments/stripe.ts

Because:
* We've had a variety of bugs related to expandResource behavior
changing after Firestore caching was added. New errors were thrown
that calling code did not expect.
This commit:
* Restores the prior expandResource behavior, and if the object cannot
be cached, instead returns it as it previously did.
Closes #12380

feat(auth): restore expandResource prior behavior

---

packages/fxa-auth-server/lib/routes/account.ts
packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/scripts/verification-reminders.js
packages/fxa-auth-server/test/local/routes/account.js
packages/fxa-auth-server/test/local/senders/index.js

Because:
* users are receiving unnecessary emails after creating a password (likely due to an error occuring after their account is verified but before their reminder is removed OR an issue with not dropping the key from redis)
This commit:
* adds an additional attempt to drop the key from redis if an error occurs after the account is verified and adds a check to see if the account is verified before sending the email
Closes #12802
I was not able to reproduce this locally but I think was I able to narrow it down to 2 possible issues that COULD occur: the first that there is an error when the user is finishing setting up their account between where the account is verified and where we drop the key from redis to send out a reminder email OR the second …

fix(auth): user Sent Unnecessary Finish Setting Up Account Reminder Email

---

packages/fxa-auth-server/lib/push.js

Because:
* We want to debug push failures using additional information.
This commit:
* Adds status code and the body of the message to the logged
message.

feat(auth): add body logging for push fail

---

packages/fxa-shared/subscriptions/metadata.ts
packages/fxa-shared/test/subscriptions/metadata.ts

- Need to update the subscription support form to use the firestore
product configuration if the feature flag is enabled.
- Uses product configuration if plan has configuration set, otherwise it
continues to use the product metadata.
Closes: #10359

feat(content): update support form for product config

---

packages/fxa-content-server/app/scripts/views/pair/auth_complete.js

Because:
* We guessed on a version for when to show Firefox View and we've been
asked to change to 106
This commit:
* Changes the version to 106
Closes FXA-5460

feat(pair): Show Fx View when version >= 106

---

packages/fxa-auth-server/lib/routes/attached-clients.js
packages/fxa-auth-server/lib/routes/devices-and-sessions.js
packages/fxa-auth-server/test/local/routes/devices-and-sessions.js

- We want to be able to filter idle/outdated send tab targets, and those are returned from the `/devices` api
- Adds the same `filterIdleDevicesTimestamp` query parameter that was added in #12879 to the GET `/devices` api

feat(devices): adds filter query parameter to get_devices api

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe.js

Because:
* The firestore processor failed to find existing records for deleted
customers nor could it create them as we don't store deleted
customers.
This commit:
* Catches both the stripe customer deleted error and the lack of a
firestore record from the same error case.
Closes #13591

fix(auth): firestore processor didnt ignore proper errors

---

packages/fxa-admin-panel/CHANGELOG.md
packages/fxa-admin-server/CHANGELOG.md
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-content-server/CHANGELOG.md
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-event-broker/CHANGELOG.md
packages/fxa-geodb/CHANGELOG.md
packages/fxa-graphql-api/CHANGELOG.md
packages/fxa-payments-server/CHANGELOG.md
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-react/CHANGELOG.md
packages/fxa-settings/CHANGELOG.md
packages/fxa-shared/CHANGELOG.md
packages/fxa-support-panel/CHANGELOG.md
release.sh

Because:
* We're leveraging Github's release infrastructure to track release
notes now
This commit:
* Changes the release script to point to Github
Closes FXA-5496

chore(build): Point at the Github changelog

---

packages/fxa-content-server/app/styles/modules/_custom-rows.scss

- There was an (unexpected) blank space in the page after we added an image to the pairing confirmation page. This removes that space.
- Removes the top padding from the "device being paired" element, since there's an image there now. 
Closes: #13448 
Before:
After:
What it would look like in a view without an image:
To test:
Testing these changes is legitimately difficult, since we have no known way to see this view in local. To test these changes, go through the sync flow until you reach the appropriate page (either in stage or prod.)Then, open the dev tools, and select the "device being paired" element (with the information about your IP address etc.) Go through the css styles in the dev tools until you find `.pair-auth .client`, and change the …

fix(fxa-content-server): remove blank space

---

packages/fxa-payments-server/src/components/AppLayout/index.tsx

- The firefox breadcrumb menu should be left aligned instead of center.
- Left aligns the breadcrumb to match the design and other pages.
Closes: #13557

fix(payments): sub management breadcrumb alignment

---

packages/functional-tests/pages/settings/components/unitRow.ts
packages/fxa-content-server/tests/functional/lib/selectors.js
packages/fxa-content-server/tests/functional/settings/connected_services_oauth_clients.js
packages/fxa-settings/src/components/ConnectedServices/Service.tsx

- We want to ensure we are standards-compliant with both the web and a11y
- An id is an element's unique identifier and should not be duplicated
- Removes the id attribute and adds an additional class
- Updates tests to target the class
Closes: #12916

fix(a11y): remove duplicate ids in Connected Services

---

packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
packages/fxa-auth-server/lib/senders/emails/templates/cadReminderFirst/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/cadReminderFirst/includes.json
packages/fxa-auth-server/lib/senders/emails/templates/cadReminderFirst/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/cadReminderFirst/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts

- we are updating email copy
- updates the email copy for cadReminderFirst in HTML and TXT:
```
[Image](https://accounts-static.cdn.mozilla.net/other/graphic-laptop-mobile.png)
Take your tabs across all your devices. Get your bookmarks, passwords, and other data everywhere you use Firefox. It’s like having magic in your Firefox account! 
It only takes a sec to sync. 
Button: [Sync another device](http://localhost:3030/connect_another_device)
Install Firefox Component
<Footer Component>
``` 
Closes: #13040

fix(auth): Update cadReminderFirst email copy

---

packages/fxa-auth-server/lib/routes/validators.js
packages/fxa-auth-server/test/local/routes/validators.js

Because:
* The error 'invalid parameter redirectTo' is occuring due to the domain and needed URL/campaign parameters for subscription purchases exceeding the 512 length
This commit:
* Increases the max length from 768 to 2048. A previous commit increased this to 768 but we determined we should increase it further.

fix(redirect): Increase redirectTo validator max length

---

packages/fxa-content-server/app/scripts/templates/pair/index.mustache
packages/fxa-content-server/app/scripts/views/mixins/pairing-graphics-mixin.js
packages/fxa-content-server/app/scripts/views/pair/index.js
packages/fxa-content-server/app/tests/spec/views/mixins/pairing-graphics-mixin.js
packages/fxa-content-server/app/tests/spec/views/pair/index.js

- We only want to show the download qr code if the entrypoint query param is fxa_app_menu.
- Hides the QR code in favor of the default pair graphic when the entrypoint query parameter is not fxa_app_menu.
Closes: #13488
There was some discussion in the initial ticket surrounding whether or not the _entrypoint=fxa_app_menu_ would be set when coming from Firefox View. I am moving forward with the assumption that this will be set in firefox view.

FXA-5452-create-two-versions-of-the-pair-screen-based-on-entry-point

---

packages/fxa-auth-server/lib/routes/subscriptions/apple.ts
packages/fxa-auth-server/test/local/payments/iap/apple-app-store/purchase-manager.js
packages/fxa-auth-server/test/local/routes/subscriptions/apple.js
packages/fxa-shared/payments/iap/apple-app-store/purchase-manager.ts

Because:
The auth server is erroring on App Store Server notifications for several reasons:
1. App Store Server notification request payloads are larger than our default request payload max size.
2. Request payload validation was failing.
3. decodeNotificationPayload was being passed request.payload (object) instead of request.payload.signedPayload (string).
4. undefined is not a valid data type to store in Firestore.
This commit:
Fixes the route configuration and handler to ensure we respond with a 200:
1. Increases maxBytes on this endpoint to be 2x as large as the expected payload.
2. Updates Hapi request payload validation for the endpoint to reflect the expected payload structure.
3. Passes in the signed payload to decodeNotificationPayload.
4. Only adds latestNotificationSubtype to …

fix(auth): ensure /app-store-notification endpoint returns 200s

---

packages/functional-tests/tests/misc.spec.ts
packages/functional-tests/tests/settings/misc.spec.ts

These two tests : `change email and unblock`,  `delete account` were the flakiest and failed every now and then with a timeout error.
I increased the default timeout value from 30s to 90s using `test.slow()`. I am going to monitor these tests and if the issue reoccurs I will do another fix then. But for now, looks like this will resolve the issue.
Resolves the timeout error for these two tests
Closes: #13324  
@mozilla/fxa-devs please review! Thanks! :)

test(functional_tests): increase default timeout value for flaky tests

---

packages/fxa-content-server/app/scripts/models/account.js
packages/fxa-content-server/app/scripts/views/mixins/connect-another-device-mixin.js
packages/fxa-content-server/tests/functional/lib/selectors.js
packages/fxa-content-server/tests/functional/pairing.js

- After signing in from the browser's hamburger menu, we were not seeing the Download Firefox mobile page.
- Removes the `showSuccessMesssage: true` on navigation. This flag was causing the pairing success page to be displayed instead of the download firefox page.
Closes: #13447

fix(content): Show the download firefox page after sign in from browser menu

---

packages/fxa-auth-server/package.json
yarn.lock

Reverts mozilla/fxa#13652 as we suspect it's breaking Firestore emulator related tests.

Revert "chore(deps): bump @google-cloud/translate from 6.3.1 to 7.0.0"

---

packages/fxa-auth-server/lib/routes/subscriptions/play-pubsub.ts
packages/fxa-auth-server/test/local/routes/subscriptions/play-pubsub.js

Because:
* We can get RTDN messages for purchases that were replaced by newer
purchases.
This commit:
* Ignores purchases that were replaced as they're no longer active.
Closes #13656

fix(auth): ignore replaced purchases

---

packages/fxa-content-server/app/scripts/models/reliers/oauth.js
packages/fxa-content-server/app/scripts/templates/force_auth.mustache
packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache
packages/fxa-content-server/app/tests/spec/models/reliers/oauth.js
packages/fxa-content-server/app/tests/spec/views/force_auth.js
packages/fxa-content-server/app/tests/spec/views/mixins/service-mixin.js
packages/fxa-content-server/tests/functional/lib/selectors.js

Because:
* New Sync copy was not displayed on the force_auth page, or when tapping 'Sign in to Sync' through mobile FF browser
This commit:
* Updates force_auth mustache accordingly
* Tweaks the service mixin to also check for serviceName
* Places 'Enter your password for your Firefox account' in one string for l10n on sign_in_password
fixes #13424
fixes #13425

fix(sign-in/up): Display new Sync copy on force_auth and Sync mobile

---

packages/fxa-content-server/app/scripts/templates/connect_another_device.mustache

- A decorative image needs appropriate A11y attributes

fix(a11y): update a11y attrs on check img

---

packages/fxa-customs-server/.eslintrc
packages/fxa-customs-server/docs/swagger/customs-server-api.js
packages/fxa-customs-server/docs/swagger/descriptions.js
packages/fxa-customs-server/docs/swagger/swagger-options.js
packages/fxa-customs-server/lib/server.js
packages/fxa-customs-server/package.json
yarn.lock

- we want to auto-generate the [current Customs Server API doc](https://github.com/mozilla/fxa/blob/main/packages/fxa-customs-server/docs/api.md)
- generates the Swagger JSON file that will later be added to Ecosystem Platform
- start FxA stack
- `npm start` fxa-customs-server
- Go to [http://localhost:7000/swagger.json](http://localhost:7000/swagger.json)
Closes: #12963
- While this PR only generates the JSON file that will be added to Ecosystem Platform, when the JSON file is added to Ecosystem Platform, the generated API documentation will look as follows:

docs(customs): Implement Swagger for API documentation

---

packages/fxa-content-server/tests/server/helpers/routesHelpers.js
packages/fxa-content-server/tests/server/l10n-entrained.js
yarn.lock

- Tests that were testing the URLs on the signin page were failing,
because the fetch on URL https://www.mozilla.org/about/ was missing
the accept-language header.
- Adds the accept-lanugage header to the failing tests.

fix(content): failing tests checking page url

---

.dockerignore

Because:
- customs was failing to start due to missing swagger docs
This commit:
- let the docs in

fix(docker): pull swagger docs in for customs

---

packages/fxa-admin-server/src/gql/model/moz-subscription.model.ts
packages/fxa-admin-server/src/graphql.ts
packages/fxa-admin-server/src/schema.gql

Because:
- the manage subscription link is optional
This commit:
- make the management subscription link optional for the GraphQL
response

fix(admin-server): make subscription mgmt link optional

---

packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
yarn.lock

- List of connected services can be really long, and support mostly cares about connected services.
- Places the subscription section above the connected services section.
Closes: #13304

task(admin-panel): Move subscriptions above connected services

---

packages/fxa-shared/db/models/auth/prune-tokens.ts
packages/fxa-shared/test/db/models/auth/prune-token.spec.ts

- The prune-tokens.complete metric wasn't being recorded.
- Records individual stats for each result type as opposed to using an increment with a 'Tag'
- Renames metrics to prune-tokens. This casing is more inline with the way other metrics are recorded.
Closes: #13718

bug(auth-server): Fix token-pruner.complete metric

---

packages/fxa-content-server/app/scripts/views/index.js

- Fix for [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1773161)
- See discussion and proposed solution [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1777876) 
- Adds a check to ensure all characters are lowercase in email validation
Closes: #13690
Before (logging in with *@firefox.com)
Before (logging in with *@FiReFoX.com)
(successfully lets you into the password step): 
After (logging in with *@firefox.com) 
(shows desired behavior remains after changes):
After (logging in with *@FiReFoX.com)
(does not pass thru to password step):

fix(fxa-content-server): strict casing for email validation

---

packages/fxa-admin-panel/src/components/AccountSearch/Account/index.test.tsx
packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
packages/fxa-admin-panel/src/components/AccountSearch/index.test.tsx
packages/fxa-admin-panel/src/components/AccountSearch/index.tsx
packages/fxa-admin-server/src/gql/account/account.resolver.ts
packages/fxa-admin-server/src/gql/model/account.model.ts
packages/fxa-admin-server/src/graphql.ts
packages/fxa-admin-server/src/schema.gql
yarn.lock

- Knowing if an account is locked is useful for support.
- Pulls the lockedAccount field from the database, and shows when an account is locked in the UI.

task(admin-panel): Add info about locked accounts

---

packages/fxa-admin-server/src/database/database.service.spec.ts
yarn.lock

- On a fresh startup, the fxa-admin-server tests would fail the first time they were run.
- Ensures the database is setup prior to running the tests in database.service.spec.ts
Closes: #13711
This can be validated by dropping the fxa.testAdmin database on your local mysql db. Then run the admin server tests. Without this patch, the tests will pretty consistently fail. With this patch, the issue is resolved.

bug(fxa-admin-server): Tests weren't running on the first invocation.

---

_scripts/mysql.sh

Because:
- we want to upgrade to mysql 8
This commit:
- upgrade mysql for local dev
- start mysqld with default auth set to native password for backwards
compat with the 'mysql' module
Closes: FXA-5583

chore(db): upgrade to mysql 8 for local dev

---

packages/fxa-payments-server/src/components/CouponForm/index.test.tsx
packages/fxa-payments-server/src/components/CouponForm/index.tsx
packages/fxa-payments-server/src/lib/types.tsx

- We want to streamline the coupon payment flow and improve UX
- Parses the provided URL for a coupon parameter
- Authenticates and applies discount code on load if valid
Closes: #13550

feat(payments): autofill coupon when valid query string parameter is provided

---

_scripts/clone-l10n.sh
packages/fxa-content-server/grunttasks/replace.js
packages/fxa-content-server/locale/README.md
packages/fxa-shared/l10n/determineLocale.ts

* The fxa-content-server-l10n is still using master as default branch, and we want to update it to main.
* Updates references from master to main in automation
* Fixes or removes master references in docs
* Fixes a few typos
Landing for this pull request needs to be coordinated (so, early morning US time). Once ready to merge, I'll need to:

chore(l10n): replace references to master with main in l10n automation

---

packages/fxa-auth-server/package.json
yarn.lock

Reverts mozilla/fxa#13751 because our storybook for Payments isn't loading and this could be the change that caused it.

Revert "chore(deps-dev): bump @storybook/html from 6.4.13 to 6.5.9"

---

packages/fxa-payments-server/src/components/PaymentErrorView/index.scss
packages/fxa-payments-server/src/components/PaymentErrorView/index.stories.tsx
packages/fxa-payments-server/src/components/PaymentErrorView/index.test.tsx
packages/fxa-payments-server/src/components/PaymentErrorView/index.tsx

- We want to convert to Tailwind across fxa for consistency and to improve overall maintenance
- We want to improve responsiveness and UI/UX
- We want to improve accessibility
- Replaces all CSS/SCSS with Tailwind utility classes with the exception of:
- `.subscription-title` + `.payment-processing` which uses the mixin `checkout-title()`
-  `.payment-processing` which uses the mixin `checkout-view()`
- Removes the style from `.scss` file that is specific to the `PaymentErrorView` component with the exception of classes mentioned above
- Reworks Storybook files
Closes: #13583

refactor(payments): update PaymentErrorView to utilize Tailwind

---

packages/fxa-auth-server/lib/oauth/db/index.js
packages/fxa-auth-server/lib/oauth/db/mysql/index.js
packages/fxa-auth-server/scripts/prune-oauth-authorization-codes.ts
packages/fxa-auth-server/test/oauth/db/index.js
packages/fxa-auth-server/test/scripts/prune-oauth-authorization-codes.js

Because:
- we should prune the expired OAuth authorization codes from the OAuth
database
This commit:
- add a script that calls a pruning function that deletes up to 10,000
expired OAuth authorization code

feat(scripts): add script to prune oauth codes

---

packages/fxa-auth-server/README.md
packages/fxa-auth-server/docs/api.md
packages/fxa-auth-server/docs/swagger/account-api.ts
packages/fxa-auth-server/docs/swagger/auth-server-api.ts
packages/fxa-auth-server/docs/swagger/devices-and-sessions-api.ts
packages/fxa-auth-server/docs/swagger/emails-api.ts
packages/fxa-auth-server/docs/swagger/oauth-api.ts
packages/fxa-auth-server/docs/swagger/oauth-server-api.ts
packages/fxa-auth-server/docs/swagger/password-api.ts
packages/fxa-auth-server/docs/swagger/recovery-key-api.ts
packages/fxa-auth-server/docs/swagger/session-api.ts
packages/fxa-auth-server/docs/swagger/sign-api.ts
packages/fxa-auth-server/docs/swagger/swagger-options.ts
packages/fxa-auth-server/lib/routes/oauth/index.js
packages/fxa-auth-server/lib/server.js
packages/fxa-auth-server/package.json
yarn.lock

- we are only utilizing hapi-swagger to auto-generate the JSON file, which is then added to Ecosystem Platform. Since we are not using hapi-swagger's UI to display the documentation page, we can remove `@hapi/inert` and `@hapi/vision` dependencies.
- we had examples in the initial OAuth Server API doc that were not included in the current API doc
- the list of errno's for responses in Auth Server API were not spaced out correctly
Closes: #13667
- OAuth Server
- Updated list of errno in Auth Server API

docs(swagger): Follow-up Swagger items

---

packages/fxa-payments-server/src/routes/Product/AcceptedCards/index.tsx

- margin-bottom (16px) was miscalculated when converting to Tailwind
- fixes margin-bottom to mb-4
- adds `gap-2` in place of individual padding
Original
Before
After

fix(payments): Revise style in AcceptedCards component

---

packages/fxa-payments-server/src/components/CouponForm/index.scss
packages/fxa-payments-server/src/components/CouponForm/index.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.stories.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.tsx
packages/fxa-payments-server/src/components/fields/index.test.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
packages/fxa-payments-server/src/routes/Subscriptions/ActionButton.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ManagementPanel.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/SuccessDialog.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionIapItem/SubscriptionIapItem.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

- Changes in button styling that are shared across FxA were not made in payments
- `button` element selector was removed from stylesheets in a separate commit, making all buttons and button-styled CTAs require `.button` class for styles to take effect
- Adds `.button` class to all button and button-styled CTAs
- Updates `index.scss` to target `.button` class and not `button` element
- Updates test to include `.button` class in submit button
Follow up to #13739 where `button` element was removed from shared stylesheets.

 fix(payments): add missing class for button styles to take effect

---

packages/fxa-content-server/pm2.config.js
packages/fxa-payments-server/pm2.config.js
packages/fxa-settings/pm2.config.js

Because:
- we should rebuild the styles in content, payments, and settings when
the styles in fxa-react change
This commit:
- watch the styles dir in fxa-react for the css "app" PM2 configs in
content, payments, and settings

chore(pm2): watch styles in fxa-react

---

packages/fxa-settings/src/components/PageSettings/index.test.tsx
packages/fxa-settings/src/components/PageSettings/index.tsx

Because:
* We want to make an informed decision when it comes to keeping or removing fallback text
This commit:
* Adds a temporary 'test' in PageSettings around l10n.getString() by sending different metrics events (test.fallback.start plus test.fallback.text-not-needed vs test.fallback.text-needed) for when a translation pulls from an ftl bundle successfully vs when it relies on fallback text
Closes #13213
---
To get translated strings, we either use a `Localized` wrapper or we use `useLocalization` and get them with `l10n.getString`. I hoped I could test for both of these, however, any variation of the following that I tried...
```
const FallbackTextTest = () => {
Metrics.logViewEvent(
Metrics.settingsViewName,
'fallback.test.Localized.start'
);
return (
<Localized …
```

feat(l10n): Add temporary fallback text test in Settings

---

.circleci/config.yml
packages/fxa-auth-server/test/oauth/db/index.js

Because:
- we want to upgrade to MySQL 8
This commit:
- use MySQL 8 on CircleCI

Upgrade CircleCI's MySQL version to 8.x

---

packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
packages/fxa-admin-panel/src/components/AccountSearch/index.test.tsx
packages/fxa-admin-panel/src/components/AccountSearch/index.tsx

- Some tests were skipped due to being flaky
- There were anti patterns surrounding the usage of act
- Removes unneeded act() calls
- Addresses warnings surrounding missing act() wrappers... Note this warning is a bit misleading.
- Enables skipped tests.
- General clean up, and DRY out .
Closes: #10135
Some of these issue came to light while working on #13644. PR feedback caused a deeper investigation into the use of `act()` wrappers, and it came to light that the warnings about `not wrapped in act()` were in fact misleading. I can only assume this warning prompted previous developers to wrapper certain blocks of code with act and introduce timeouts. Once this was done in one place the anti pattern started being used in other places. Ultimately this …

task(admin-panel): Clean up and fix flaky tests

---

packages/fxa-content-server/server/bin/fxa-content-server.js
packages/fxa-content-server/server/lib/routes/post-csp.js
packages/fxa-content-server/server/lib/sentry.js
packages/fxa-content-server/server/lib/validation.js
packages/fxa-content-server/tests/server/routes/post-csp.js
packages/fxa-content-server/tests/server/sentry.js
packages/fxa-shared/metrics/navigation-timing.ts

- Sentry is seeing lots of validation issues.
- We would like to correct some of these.
- We would like to get a better understanding of why some of these are happening.
- Makes a best effort to correct issues on the /navigation-timing endpoint
- Makes a best effort to correct issues on the /metrics endpoint
- Improves the error message reported sentry when a validation error occurs, which hopefully gives us more insight in the future.
Closes: #13493 
Example validation error in sentry:
For /metrics and /csp-report the request body is not reported. As a result, knowing exactly what caused the issue is difficult. It is likely that it's due to long URLs so the URL length limit has been increased in some cases. The improved errors in sentry should also …

bug(content): Address validation issues showing up in sentry with high rates

---

packages/fxa-content-server/app/scripts/templates/sign_in_token_code.mustache
packages/fxa-content-server/app/styles/_layout.scss
packages/fxa-content-server/app/styles/modules/_avatar.scss
packages/fxa-content-server/app/styles/modules/_button-row.scss
packages/fxa-content-server/app/styles/modules/_settings.scss
packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx

Because:
* Aint nobody got time for UI regressions
This commit:
* Removes the ID main-content from an already TW-ified file which allowed TW styles to take precedence
* Adds back a couple of styles that were removed but, only applicable to elements falling under #main-content to not affect TW styles
--
Decided to poke through some content-server pages I didn't test as thoroughly and found a couple regressions. Good thing I looked 😅 
Before:
After:
TW-ified UI remain unaffected because these styles only affect `#main-content` styles, an ID that was removed on TW-ified files.

fix(css): Fix a couple of regressions from TW Sync flow changes

---

packages/fxa-payments-server/src/components/NewUserEmailForm/index.scss
packages/fxa-payments-server/src/components/NewUserEmailForm/index.stories.tsx
packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
packages/fxa-payments-server/src/components/fields/index.test.tsx
packages/fxa-payments-server/src/components/fields/index.tsx

- We want to convert to Tailwind across fxa for consistency and to improve overall maintenance
- We want to improve responsiveness and UI/UX
- We want to improve accessibility
* Replaces all CSS/SCSS with Tailwind utility classes with the exception of:
* `.input-row--checkbox` and `label input[type="checkbox"]`, which are custom style settings and apply to elements found in the `fields` component
* Removes the styles from `.scss` file that are specific to the `NewUserEmailForm` component with the exception of classes mentioned above
* Reworks Storybook files
Closes: #13585
Tweaks made to `fields` component to use Tailwind (applies to all of `fxa-payments-server`), namely `.label-text` on text input and applicable tests.

refactor(payments): update NewUserEmailForm to utilize Tailwind

---

packages/fxa-auth-server/scripts/stripe-products-and-plans-to-firestore-documents/stripe-products-and-plans-converter.ts
packages/fxa-auth-server/test/scripts/stripe-products-and-plans-converter.js

Because:
* We want easier to locate metadata in github for loading to firestore.
This commit:
* Updates the name saving convention to be more descriptive.
Closes FXA-5577

feat(auth): update firestore saving structure

---

packages/fxa-payments-server/src/routes/Checkout/index.scss
packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.scss

- Husky pre-commit hook returns an error on stylelint of scss files
informing that no duplicate selectors are allowed.
- Removes duplicate selectors and moves all logic into one.
Closes: #

fix(payments): remove duplicate css selectors

---

packages/fxa-content-server/app/scripts/templates/partial/coppa-age-input.mustache

Because:
- coppa input was too close to cwts
This commit:
- add more whitespace

chore(style): add more space between coppa & cwts

---

packages/fxa-content-server/app/scripts/templates/pair/index.mustache
packages/fxa-content-server/app/tests/spec/views/pair/index.js

Because:
- language on downloading mobile Firefox on the pairing screen was
confusing
This commit:
- update copy for downloading mobile Firefox

chore(copy): update get Firefox message

---

packages/fxa-content-server/app/scripts/models/sync-engines.js

Because:
- too many words in "Logins and Passwords"
This commit:
- change to just "Passwords"

chore(content): update sync option to just "Passwords"

---

packages/fxa-content-server/app/scripts/templates/sign_in_token_code.mustache

Because:
- sentences are generally ended with a period (dot symbol)
- a single space should be between words
This commit:
- add a period and a space

fix(punctuation): add period and space

---

packages/fxa-content-server/app/styles/tailwind/flows.css
packages/fxa-react/configs/tailwind.js

Because:
- we want more space between top of viewport and the Firefox logo image
This commit:
- add 12px worth of space

chore(styles): move Firefox logo down a bit

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/test/local/payments/fixtures/stripe/event_customer_subscription_updated.json
packages/fxa-auth-server/test/local/payments/stripe.js

- In certain scenarios when a customer upgrades their subscription, the
subscriptionDowngrade email template is sent instead of
subscriptionUpgrade
- Parse the productOrder from string to int before doing the comparison
to determine if the downgrade or upgrade email should be sent.
Closes: #13851

fix(subscriptions): wrong upgrade emails

---

packages/fxa-content-server/server/lib/sentry.js

- The `npx grunt l10n-extract` was breaking due to optional chaining syntax present in sentry.js
- The l10n-extract uses the acorn parser under the hood, which doesn't appear to like optional chaining syntax.
- Ensures there is no optional chaining syntax present in the sentry.js file.
Closes: #13893

FXA-5679-l-10-n-export-is-broken-fatal-error-unexpected-token-93-10

---

packages/fxa-auth-server/config/index.ts
packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
packages/fxa-auth-server/lib/senders/emails/templates/postAddAccountRecovery/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/postAddAccountRecovery/includes.json
packages/fxa-auth-server/lib/senders/emails/templates/postAddAccountRecovery/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/postAddAccountRecovery/index.stories.ts
packages/fxa-auth-server/lib/senders/emails/templates/postAddAccountRecovery/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts

Because:
- new copy for the post add recovery key email
This commit:
- update email templates for post add recovery key email

feat(emails): update post add recovery key email

---

packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/includes.json
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts

- We're updating language in emails
- Updates email copy strings and their corresponding localization IDs
Closes: # n/a

copy(fxa-auth-server): update email copy verificationReminderFirst

---

packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
packages/fxa-auth-server/lib/senders/emails/templates/verifyShortCode/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/verifyShortCode/includes.json
packages/fxa-auth-server/lib/senders/emails/templates/verifyShortCode/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/verifyShortCode/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts

- We want to update copy for verification/confirmation emails
- Updates strings and adds a new translation string to match the new given copy
Closes: # n/a
To see the changes, `cd` into the fxa-auth-server directory and run `yarn storybook`.
This PR actually only has one commit, but is on top of my prior copy PR (and will be rebased onto main once that's merged.)

copy(fxa-auth-server): update copy for verifyShortCode email

---

packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/includes.json
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts

- We're updating copy for emails
- Updates copy, localization ids, and tests for the verificationReminderSecond email
Closes: # n/a

Fxa 5207 verification reminder second copy

---

packages/fxa-auth-server/lib/senders/emails/templates/verifyLogin/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts

- I forgot to add this fix in before merging the last PR
- Matches up the MJML and TXT footers

fix(fxa-auth-server): switch out partial to make mjml and txt consistent

---

packages/fxa-payments-server/src/components/PlanDetails/index.scss
packages/fxa-payments-server/src/components/PlanDetails/index.stories.tsx
packages/fxa-payments-server/src/components/PlanDetails/index.tsx
packages/fxa-payments-server/src/routes/Checkout/index.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx
packages/fxa-payments-server/src/styles/tailwind.css
packages/fxa-react/configs/tailwind.js

- we are converting to Tailwind
Note:
- Font sizes were revised to match `PaymentConfirmation`
- While shared styles were updated in `PlanUpgradeDetails`, this component still has a stylesheet. However, it will be handled in the `SubscriptionUpgrade` flow phase.
Closes: #13676
**PlanDetails**
Default
Localized to Pirate
With Expanded Button
With Coupon Type Forever
With Coupon Type Once
With Coupon Type Repeating Plan Interval is Greater Than Coupon Duration
With Coupon Type Repeating
**PlanUpgradeDetails**

refactor(payments): update PlanDetails component to utilize Tailwind

---

packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
packages/fxa-auth-server/lib/senders/emails/templates/verify/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/verify/includes.json
packages/fxa-auth-server/lib/senders/emails/templates/verify/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/verify/index.stories.ts
packages/fxa-auth-server/lib/senders/emails/templates/verify/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts
packages/fxa-auth-server/test/remote/account_create_tests.js
packages/fxa-auth-server/test/scripts/bulk-mailer.js

- We're updating copy for emails!
- Updates copy, localization IDs, and tests for the `verify` email, and also adds the `date` and `time` variables so as to display the date and time within the `userInfo` partial
Closes: # n/a

chore(fxa-auth-server) update copy for verify email, add date/time

---

packages/functional-tests/lib/email.ts
packages/fxa-auth-server/config/dev.json
packages/fxa-auth-server/config/index.ts
packages/fxa-auth-server/docs/metrics-events.md
packages/fxa-auth-server/lib/metrics/amplitude.js
packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFinal/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFinal/includes.json
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFinal/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFinal/index.stories.ts
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFinal/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts
packages/fxa-auth-server/test/mocks.js

- We want to add a new email to alert users that their account will be deleted if they do not confirm it
- Adds on a new email template, and all associated tests and documentation
- Was originally [this PR](https://github.com/mozilla/fxa/pull/13938) but I messed up the PR and ended up just moving the changes onto a new branch

feat(fxa-auth-server): add new verification reminder email

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe.js

Because:
* We want to optionally update a users Stripe location based on ip
address.
This commit:
* Adds an ipAddress option to uppdateCustomerBillingAddress to update
their address based on the IP address for tax handling.
Closes FXA-5670

feat(auth): use ipAddress for customer updates

---

packages/fxa-content-server/app/scripts/views/mixins/session-verification-poll-mixin.js
packages/fxa-content-server/app/tests/spec/views/mixins/session-verification-poll-mixin.js
packages/fxa-content-server/tests/functional/oauth_sign_in_token_code.js

- It was possible to ended up on the signin_bounced page, even though no email bounce actually happened.
- Handles the invalid token state separately for the sign in bounced email state.
Closes: #13806
It turns out that with two tabs open at the same time this is fairly easy to reproduce. This all ultimately has to do with the fact that the https://accounts.firefox.com/signin page is always polling sessionTokenStatus, which immediately [checks local storage for the sessionToken](https://github.com/mozilla/fxa/blob/7f3b9994a93e1c0486f0819e031e5b8462771e5b/packages/fxa-content-server/app/scripts/models/account.js#L321). Because local storage is shared between tabs, a …

fix(content): Fix erroneous signin_bounced redirect

---

packages/fxa-auth-server/docs/swagger/account-api.ts
packages/fxa-auth-server/docs/swagger/misc-api.ts
packages/fxa-auth-server/docs/swagger/shared/descriptions.ts
packages/fxa-auth-server/lib/payments/capability.ts
packages/fxa-auth-server/lib/routes/account.ts
packages/fxa-auth-server/test/local/routes/account.js

Because:
* To reduce app switching in the mobile subscription process, we want new users to set their account password and verify their email after subscribing -- in that order.
This commit:
* Creates a new account/set_password route that requires an access token and sets a password for an unverified, stub account, optionally sending a verification email.
Closes #13646

feat(auth): add /account/set_password route

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/payments/utils.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
packages/fxa-payments-server/src/components/PayPalButton/index.tsx
packages/fxa-payments-server/src/lib/apiClient.test.ts
packages/fxa-payments-server/src/lib/apiClient.ts
packages/fxa-payments-server/src/lib/stripe.ts
packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx

- Users are able to create duplicate subscriptions when losing network
connectivity shortly after hitting the Pay Now button, trying again
and selecting Pay Now again.
- Create a hash of the uid and optionally the priceId of the
subscription, to use as the idempotency key when creating the Stripe
customer and subscription.
Closes: #13755

fix(auth): duplicate sub on refresh

---

packages/fxa-auth-server/lib/payments/stripe.ts

- Function does not allow undefined or null types.
- Add default string value in case of undefined.

fix(auth): provide default string if undefined

---

_scripts/compile-backend-ts-services.sh

Because:
- Some affected packages were not being compiled
This pull request
- Includes the first line output by 'yarn workspaces list', so that the package is included in subsequent checks.
For context, see https://app.circleci.com/pipelines/github/mozilla/fxa/33070/workflows/929a0641-6cff-48da-8b17-4c59fbb7de41/jobs/360331?invite=true#step-105-6 -- this patch modified the auth-server, yet the script erroneously said it was not modified.

fix(scripts): don't remove first line of 'yarn workspaces list' output

---

packages/fxa-content-server/app/scripts/templates/partial/support-form-success.mustache
packages/fxa-content-server/app/scripts/templates/security_events.mustache
packages/fxa-content-server/app/scripts/templates/support.mustache

- After recent tailwind changes the contact support form had some
display and layout issues.
- Add temporary fixes for display and layout.
Please note that these are only temporary changes to fix the display and layout issues. These pages will be overhauled as part of the SubPlat teams tailwind conversion project https://mozilla-hub.atlassian.net/browse/FXA-5080
To show the success screen after hitting the "Send" button, you'll need to make the following change to `fxa-auth-server/lib/routes/subscriptions/support.ts` lines 198 to 205.
```
} catch (err) {
return { success: true };
// throw error.backendServiceFailure(
//   'zendesk',
//   operation,
//   { uid, email },
//   err
// );
}
```

fix(subscriptions): support form tailwind regression

---

.github/dependabot.yml

Because:
* we have too much dependabot traffic
This commit:
* ignores patch releases
Closes FXA-5684

chore(dependabot): ignore patch releases

---

packages/fxa-auth-server/lib/senders/emails/templates/postVerify/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/postVerify/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/postVerify/index.txt
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.txt
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts

* A few inconsistencies were identified when reviewing strings before exposing them for localization in https://github.com/mozilla/fxa-content-server-l10n/pull/636
* Removes inconsistencies and fix typography (space after ellipsis)
Extracting new strings is currently blocked on this, since we want to avoid unnecessary churn for both localizers and devs.

fix(l10n): fix inconsistencies and typography in reminder email strings

---

packages/fxa-auth-server/README.md

It's somewhat unclear how to get to the PayPal dashboard if you're unfamiliar.
Adds a link directly to the relevant dashboard section.

chore(fxa-auth-server): add link to PayPal dashboard in fxa-auth-server-readme

---

packages/fxa-content-server/app/scripts/templates/pair/supp_allow.mustache
packages/fxa-content-server/app/scripts/templates/pair/supp_wait_for_auth.mustache
packages/fxa-content-server/app/scripts/templates/partial/device-being-paired.mustache
packages/fxa-content-server/app/styles/modules/_custom-rows.scss
packages/fxa-content-server/app/tests/spec/views/pair/auth_allow.js
packages/fxa-content-server/app/tests/spec/views/pair/auth_wait_for_supp.js
packages/fxa-content-server/app/tests/spec/views/pair/supp_allow.js
packages/fxa-content-server/app/tests/spec/views/pair/supp_wait_for_auth.js

Because:
* We want to use Tailwind throughout the codebase for styling
This commit:
* Uses Tailwind styles for 'supp_allow.mustache' and 'device-being-paired.mustache'
Closes [FXA-5747](https://mozilla-hub.atlassian.net/browse/FXA-5747)
---
You can't test this locally unfortunately. I ended up hard-coding values into `pair/unsupported` to view the page that way.
<details>
<summary>click for code if you want to copy and paste this into pair/unsupported</summary>
```
<div class="card">
<header>
<h1 id="fxa-pair-supp-allow-header" class="card-header">
{{#unsafeTranslate}}Confirm pairing <span class="card-subheader">for <span class="break-all">hackystuff@mozilla.com</span></span>{{/unsafeTranslate}}
</h1>
</header>
<section>
<div class="error"></div>
<div class="success"></div>
<form …
```

refactor(css): Tailwindify 'supp_allow' page

---

packages/fxa-shared/metrics/navigation-timing.ts

- After more discussion, we will not attempt to modify any navigation timing data.
- Undoes the part of the change made in #13493, so navigation timings aren't coerced into valid values.

fix(content): Undo modifications to navigation timings.

---

packages/fxa-content-server/server/bin/fxa-content-server.js
packages/fxa-content-server/server/lib/sentry.js
packages/fxa-content-server/tests/server/sentry.js

- The content server appeared to be capturing errors more than once.
- Ensures if the validation error is modified and captured, then the initial error is not reported.
- Adds a tag so that validation errors can be easily filtered for.
Closes: FXA-5792

fix(content): Fixes double capture of validation errors.

---

.github/dependabot.yml

- CI test failed :(
- revises .yml file to include missing line
Screenshot:
Source: [https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates)

fix(dependabot): fix ignore patch releases

---

packages/fxa-auth-server/test/local/senders/renderer.ts

- verifyShortCode email copy was updated
- updates the test that causes failing CI test in auth-server

fix(auth-server): Fix failing test due to updated email copy strings

---

packages/fxa-settings/src/components/ConnectedServices/Service.tsx

- @pdehaan noticed that in the list of connected services visible when signed in to fxa-settings, linked connected services (such as Firefox Monitors) are a different font-size from unlinked connected services (such as a browser version).  We want the text to appear uniform.
- Matches the font-sizes across linked and unlinked services. The two sizes were "text-sm" and "text-xs" -- I have opted to change "text-xs" to "text-sm". There are other instances of "text-xs" within the services (such as location, if the location is provided, and the text within the button), so there are grounds for going in the other direction if anyone feels strongly about it.
Closes: #13899
Before: 
After:

fix(fxa-settings): make copy sizes in connected services uniform

---

packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-content-server/tests/server/amplitude.js
packages/fxa-settings/src/components/ConnectedServices/index.test.tsx
packages/fxa-settings/src/components/ConnectedServices/index.tsx

Because:
* Many settings events weren't being properly stored because they weren't mapped to an 'amplitude' event group/name which we currently require for validation and property capturing (uid, flowId etc.)
This commit:
* Combs through our Settings pages for event names and adds ones that were missing, and tweaks a connected-devices event to match regex
* Updates current recovery key events to be in the 'activity' group, since they were not for settings pages
* Adds tests
Fixes [FXA-5762](https://mozilla-hub.atlassian.net/browse/FXA-5762)
---
Reviewer: you might be interested in the comments in that issue and sheets link Wil provided.
Essentially what I did here was search in `fxa-settings` for when we're calling `usePageViewEvent` and `logViewEvent` and checked `amplitude.js` in …

fix(metrics): Add many 'amplitude' event mappings for Settings events

---

packages/fxa-admin-panel/package.json
packages/fxa-admin-server/package.json
packages/fxa-auth-client/package.json
packages/fxa-auth-client/server.ts
packages/fxa-auth-server/package.json
packages/fxa-auth-server/scripts/paypal-processor.ts
packages/fxa-auth-server/scripts/prune-oauth-authorization-codes.ts
packages/fxa-auth-server/scripts/prune-tokens.ts
packages/fxa-auth-server/scripts/subscription-reminders.ts
packages/fxa-content-server/package.json
packages/fxa-event-broker/package.json
packages/fxa-graphql-api/package.json
packages/fxa-payments-server/package.json
packages/fxa-react/package.json
packages/fxa-settings/package.json
packages/fxa-shared/package.json
packages/fxa-support-panel/package.json
yarn.lock

Because:
* We want faster compilation and inferencing of TS 4.8.2.
This commit:
* Updates TS to 4.8.2. across the fxa workspace.

chore: upgrade typescript to 4.8.2

---

packages/fxa-content-server/server/lib/routes/post-csp.js
packages/fxa-content-server/server/lib/validation.js

- Many csp reports are being rejected due to value sent in for blocked-uri
- The spec doesn't limit URLs to http(s)
- Moves from LONG_URL validator to LONG_URI validator that doesn't have scheme restrictions
- Denies telnet scheme because there's a test explicitly checking this. Perhaps there are historical reasons to block this case
Closes: FXA-5756

fix(content): Be more lenient with blocked uri values

---

packages/functional-tests/pages/settings/deleteAccount.ts
packages/functional-tests/pages/settings/displayName.ts
packages/functional-tests/tests/settings/deleteAccount.spec.ts
packages/functional-tests/tests/settings/displayName.spec.ts
packages/functional-tests/tests/settings/misc.spec.ts

As part of the Playwright Migration epic, rewrote the 'Settings - Display Name' and 'Delete account' tests (previously found in `tests/functional/settings/display_name.js` and `tests/functional/settings/delete_account.js` files) using playwright.
Contains tests for Settings - Display name and Delete account
Closes: #13855  
@mozilla/fxa-devs @pdehaan please review!

test(functional): rewrite display name and delete account tests in playwright

---

packages/fxa-payments-server/server/lib/amplitude.js
packages/fxa-payments-server/server/lib/routes/post-metrics.js
packages/fxa-payments-server/src/lib/amplitude.ts
packages/fxa-payments-server/src/lib/apiClient.test.ts
packages/fxa-payments-server/src/lib/apiClient.ts
packages/fxa-payments-server/src/lib/types.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
packages/fxa-payments-server/src/store/actions/api.ts
packages/fxa-payments-server/src/store/sequences.test.ts
packages/fxa-payments-server/src/store/sequences.ts
packages/fxa-shared/metrics/amplitude.js
packages/fxa-shared/test/metrics/amplitude.js

- the product and price change when upgrading products, we need to add `previous_plan_id`, `previous_product_id`, and `utm_referrer` to metrics
- revises `updateSubscriptionPlanAndRefresh` to also pass through the current plan (which will become the previous plan), so that `updateSubscriptionPlan` can extract its `plan_id` and `product_id` into `apiUpdateSubscriptionPlan`, as it was initially only extracting the `plan_id` and `product_id` from the new plan
- adds `utm_referrer` within other utm parameters

feat(metrics): Expand the metrics that are stored during upgrades

---

packages/fxa-content-server/app/scripts/lib/app-start.js
packages/fxa-content-server/app/scripts/lib/metrics.js
packages/fxa-content-server/app/tests/spec/lib/metrics.js
packages/fxa-content-server/server/lib/routes/get-index.js
packages/fxa-content-server/server/lib/routes/post-metrics.js
packages/fxa-shared/metrics/metric-errors.ts
packages/fxa-shared/metrics/validate.ts
packages/fxa-shared/test/metrics/validate.ts

- In the previous sprint changes were made to expose reasons for validation failure to Sentry
- We want to address as many of these validation errors as possible.
- Adds more sanitization to metrics data gathered on the client side.
- Reports issues encountered during sanitization directly, instead of waiting for 400 on server side and losing track of call stack that result in issue.
Closes: #13493
Invalid values that are detected on the client side will now be reported with the following extra data:

fix(content-server): Follow up to broken metrics requests

---

packages/fxa-content-server/app/scripts/lib/constants.js
packages/fxa-content-server/app/scripts/views/mixins/pairing-graphics-mixin.js
packages/fxa-content-server/app/tests/spec/views/mixins/pairing-graphics-mixin.js

- Fx Desktop requested to show QR code when coming from `fx-view` entrypoint
- Adds the entrypoint
Closes: https://mozilla-hub.atlassian.net/browse/FXA-5729

feat(pair): Add new entrypoint `fx-view` for showing QR code

---

packages/fxa-auth-server/docs/swagger/auth-server-api.ts
packages/fxa-auth-server/lib/error.js
packages/fxa-auth-server/lib/oauth/assertion.js
packages/fxa-auth-server/lib/oauth/error.js
packages/fxa-auth-server/test/local/sentry.js
packages/fxa-auth-server/test/local/server.js
packages/fxa-content-server/app/scripts/lib/oauth-errors.js
packages/fxa-content-server/app/scripts/models/account.js
packages/fxa-content-server/app/scripts/models/reliers/oauth.js
packages/fxa-content-server/docs/architecture.md

- links no longer work as API docs are now in Ecosystem Platform
- updates links to API docs in Ecosystem Platform

fix(docs): Updated links to API docs

---

.slugignore
package.json
packages/123done/package.json
yarn.lock

- 123Done needed to be updated so that it could be deployed to heroku
- Removes fxa-shared as a dependency
- Adds a slug ignore file so that heroku slug stays below max [500mb](https://devcenter.heroku.com/articles/slug-compiler)
Closes: https://mozilla-hub.atlassian.net/browse/FXA-5692
Main branch has been deployed to https://stage-123done.herokuapp.com/
Something we can consider in the future is to have this automatically deploy when 123Done changes are merged to main.

feat(pair): Updates for 123Done to support Heroku

---

packages/fxa-auth-server/lib/metrics/amplitude.js
packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-payments-server/server/lib/amplitude.js

- We've been getting this issue in Sentry about [this spot in code](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/server/lib/amplitude.js#L491)
```TypeError: Cannot read properties of undefined (reading 'user-agent')
File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/metrics/amplitude.js", line 305, in receiveEvent
userAgent: request.headers['user-agent']
```
We want this to fail gracefully.
- My interpretation of the above is that the headers sometimes come back as undefined, and when they do, we error out when we try to read `user-agent` off of undefined. So instead of just reading it directly, I use optional chaining to check the truthiness of `headers` before trying to access `user-agent` and return undefined if `headers` is a falsy value. I think that …

fix(fxa-content-server): prevent error if headers absent

---

packages/fxa-auth-server/lib/payments/iap/apple-app-store/purchase-manager.ts
packages/fxa-auth-server/lib/routes/subscriptions/apple.ts
packages/fxa-auth-server/test/local/payments/iap/apple-app-store/purchase-manager.js
packages/fxa-auth-server/test/local/routes/subscriptions/apple.js
packages/fxa-shared/payments/iap/apple-app-store/purchase-manager.ts

Because:
* Apple doesn't keep logs of notifications it sends, and neither do we.
* When we get a Firestore error for our Apple IAP subscription purchase collection, we don't know which purchase the error is from.
This commit:
* Log App Store Server notifications at the debug level (enabled in Stage only for Apple's Sandbox environment only).
* Add the originalTransactionId to the Sentry scope for all Firetore PurchaseQueryErrors and PurchaseUpdateErrors.
Closes #FXA-5817
Example Sentry error with additional App Store IDs context:

chore(auth): improve Apple IAP error and notification logging

---

packages/fxa-auth-server/lib/routes/subscriptions/apple.ts
packages/fxa-auth-server/test/local/routes/subscriptions/apple.js

Because:
* The VPN team needs to migrate existing Apple IAP users to SubPlat.
* They only have the 'profile' scope in this context.
This commit:
* Allows the 'profile:subscriptions' scope, which is a subset of the 'profile' scope, in the App Store registration route.
Notes:
* This is a temporary change that should be reverted once the migrations are completed successfully (see FXA-5848).
Closes #FXA-5833

chore(auth): allow profile scope on App Store registration route

---

packages/fxa-auth-server/lib/sentry.js
packages/fxa-customs-server/lib/sentry.js
packages/fxa-profile-server/lib/server/web.js

- We removed the @sentry/tracing module so sentry.transactions is now undefined.
- Removes references to sentry.transaction. They are no longer useful or supported.
Closes: FXA-5852

fix(customs,auth,profile): Remove references sentry.transaction

---

packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.txt

- QA caught that copy wasn't updating in the verificationReminderFirst email -- closer examination showed that I had not updated the string ID in all places in the email. (per comments on [this ticket](https://mozilla-hub.atlassian.net/browse/FXA-5206))
- Updates the string id consistently.
Closes: # https://mozilla-hub.atlassian.net/browse/FXA-5859
Updated copy:

fix(fxa-auth-server): update string id

---

packages/fxa-auth-server/lib/pushbox/db.ts
packages/fxa-auth-server/lib/pushbox/index.ts
packages/fxa-auth-server/lib/routes/index.js
packages/fxa-auth-server/test/local/pushbox.js
packages/fxa-auth-server/test/remote/pushbox/db.ts

Because:
- we need to retrieve records from the pushbox db directly
This commit:
- add a retrieve method to the pushbox db module
- convert pushbox api module from js to ts
closes #fxa-5769

feat(pushbox): add retrieval to pushbox db api

---

packages/fxa-payments-server/src/routes/Checkout/index.tsx

- during QA, it was discovered after returning from the “Error confirming subscription..” page:
-  fields were no longer filled in 
- subscription can be finalized without selecting the required checkbox
- keeps Tailwind updates, but reverts the changes that removed the use of `classNames` 
- Reference: [PR that converted Checkout component to utilize Tailwind](https://github.com/mozilla/fxa/pull/14000)
- [FXA-5872](https://mozilla-hub.atlassian.net/browse/FXA-5872)
- [FXA-5873](https://mozilla-hub.atlassian.net/browse/FXA-5873)

fix(payments): Fix Checkout component

---

packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.scss

- checkbox does not display as expected
- fixes checkbox UI issue on Subscription Management page
- [FXA-5862](https://mozilla-hub.atlassian.net/browse/FXA-5862)

fix(payments): Fix checkbox issue on Subscription Management page

---

packages/fxa-payments-server/src/lib/hooks.test.tsx

- intermittent coupon test failure
- slices on 7 digits instead of 8
- [FXA-5858](https://mozilla-hub.atlassian.net/browse/FXA-5858)

fix(payments): Intermittent coupon test failure

---

packages/fxa-content-server/server/lib/amplitude.js

- l10n is breaking due to the optional chaining changes 
- Removes optional chaining from the content server
Closes: # https://mozilla-hub.atlassian.net/browse/FXA-5865

fix(fxa-content-server): remove optional chaining from content server

---

packages/fxa-content-server/app/scripts/views/elements/password-input.js
packages/fxa-content-server/app/scripts/views/mixins/password-mixin.js
packages/fxa-content-server/app/tests/spec/views/force_auth.js
packages/fxa-content-server/app/tests/spec/views/mixins/password-mixin.js

because:
* "valid password required" message shown after selecting "show password"
this commit:
* adjust password selector bc the password eye (hide/show password) was included unintentionally
Co-authored-by: Lauren Zugai <lauren@zugai.com>
Closes: # https://mozilla-hub.atlassian.net/browse/FXA-5857

fix(fxa-content-server): fix selectors for password

---

packages/functional-tests/tests/settings/misc.spec.ts
packages/fxa-settings/src/components/DataBlock/index.test.tsx
packages/fxa-settings/src/components/DataBlock/index.tsx
packages/fxa-settings/src/components/GetDataTrio/en-US.ftl
packages/fxa-settings/src/components/GetDataTrio/index.test.tsx
packages/fxa-settings/src/components/GetDataTrio/index.tsx
packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.test.tsx
packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.tsx
packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx
packages/fxa-settings/src/components/PageTwoStepAuthentication/index.test.tsx
packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx

- We want to improve the UX for saving recovery keys and backup verification codes (2FA backup codes)
- Adds a parameter to GetDataTrio called contentType to indicate the content displayed.
- Applies the this contentType parameter to file download names.
- Applies the this contentType parameter to the page title of printed documents.
- Updates the DataBlock component with a contentType parameter than can be passed through to GetDataTrio.
- Uses the 'Firefox recovery key' contentType in PageRecoveryKeyAdd's DataBlock component.
- Uses the 'Firefox backup verification codes' contentType in PageTwoStepAuthentication and Page2faReplaceRecoveryCode components.
Closes: FXA-3817
Download names:
Print Titles

task(settings): Improve UX when saving account recovery keys and backup verification codes

---

_dev/pm2/infrastructure.config.js
_scripts/jaeger.sh

- When not enabled, Jaeger was exiting with an 'error' status which was confusing.
- Adjust infrastructure.config.js so that Jaeger exists cleanly with a 'stopped' status.
- Reports a better log message so that it's clear Jaeger is not required to run FxA.
Closes: FXA-5886

fix(infrastructure): Improve jaeger startup behavior

---

package.json
packages/fxa-auth-server/lib/routes/account.ts
packages/fxa-auth-server/lib/routes/totp.js
packages/fxa-auth-server/lib/senders/emails/templates/newDeviceLogin/index.stories.ts
packages/fxa-auth-server/test/local/routes/account.js
packages/fxa-auth-server/test/local/routes/totp.js
packages/fxa-auth-server/test/remote/account_signin_verification_tests.js
packages/fxa-auth-server/test/remote/recovery_email_resend_code_tests.js
packages/fxa-auth-server/test/remote/session_tests.js
packages/fxa-content-server/tests/functional/oauth_reset_password.js
packages/fxa-content-server/tests/functional/oauth_sync_sign_in.js
packages/fxa-content-server/tests/functional/settings/recovery_key.js
packages/fxa-content-server/tests/functional/settings/two_step_auth.js
packages/fxa-content-server/tests/functional/sign_in_blocked.js
packages/fxa-content-server/tests/functional/sign_in_cached.js

- We currently only send the new device emails for relying parties that request encryption keys (ie Sync), we now want to send it for all new logins
- I considered renaming the term `New Device Login` to something a bit more generic since this could now include services, but differed since that would  increase the scope alot
- Updates the code to send on all new logins
Closes:  https://mozilla-hub.atlassian.net/browse/FXA-5754

feat(emails): Send `New Device Login` email on all new logins

---

packages/fxa-admin-panel/src/components/AccountSearch/Account/index.test.tsx
packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
packages/fxa-admin-panel/src/components/AccountSearch/index.tsx

- We show `Unknown` value in devices and apps tables, which isn't help because not all have those values set
- Does not show unknown or null values in the admin panel devices table
Closes: https://mozilla-hub.atlassian.net/browse/FXA-4594
Created this PR for consideration. It doesn't really fix https://mozilla-hub.atlassian.net/browse/FXA-4594 since user agent information is not avaible on oauth tokens, however I think it does provide some small improvement to the UX. Ideally I think we should close that bug and open a new bug to show the estimated location of the oauth token. This would provide the user with some additional security context around the oauth token in leiu of storing user agent information.

fix(admin): Don't show unknown values in devices and apps table

---

packages/fxa-content-server/app/scripts/templates/connect_another_device.mustache
packages/fxa-content-server/app/scripts/templates/pair/index.mustache
packages/fxa-content-server/app/scripts/views/pair/auth_allow.js
packages/fxa-content-server/app/scripts/views/pair/auth_complete.js
packages/fxa-content-server/app/scripts/views/pair/index.js
packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-content-server/tests/server/amplitude.js
packages/fxa-shared/metrics/amplitude.js

Because:
- we want to know about user interactions during the Connect Another Device and pairing process
This commit:
- capture new events on CAD/pairing pages
Fixes FXA-5751

feat(metrics): add CAD/pairing events

---

packages/fxa-auth-server/lib/payments/capability.ts
packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/payments/utils.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/scripts/stripe-products-and-plans-to-firestore-documents/stripe-products-and-plans-converter.ts
packages/fxa-auth-server/test/scripts/stripe-products-and-plans-converter.js
packages/fxa-payments-server/src/lib/test-utils.tsx
packages/fxa-shared/lib/utils.ts
packages/fxa-shared/subscriptions/configuration/base.ts
packages/fxa-shared/subscriptions/configuration/plan.ts
packages/fxa-shared/subscriptions/configuration/product.ts
packages/fxa-shared/subscriptions/metadata.ts
packages/fxa-shared/subscriptions/stripe.ts
packages/fxa-shared/subscriptions/types.ts
packages/fxa-shared/test/subscriptions/configuration/helpers.ts
packages/fxa-shared/test/subscriptions/configuration/utils.ts
packages/fxa-shared/test/subscriptions/metadata.ts
packages/fxa-shared/test/subscriptions/stripe.ts

Because:
* We want to support multiple values on productSet to determine which plans can be upgraded to different plans or different bundles
This commit:
* Changes the productSet property to by an array of strings that is comma delimited. RP can then specify in stripe metadata the possible productSets a product or price
can be belong to along with an order field. Upgrade eligibility is determined by having at least 1 overlapping productSet element and the correct order.
Closes #[FXA-5739](https://mozilla-hub.atlassian.net/browse/FXA-5739)

feat(shared): make productSet Comma Separated Field

---

packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/includes.ts
packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/index.stories.ts
packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts

- We're updating copy for the lowRecoveryCode emails. 
- Updates the copy for the lowRecoveryCode emails, and makes the copy for the emails branch more based on the number of remaining recovery codes (as represented by `numberRemaining`.)
- Adds the `zero recovery codes` email to storybook
Closes: # https://mozilla-hub.atlassian.net/browse/FXA-5188
The fact that the `txt` file references `locals.numberRemaining` and the mjml file references `numberRemaining` directly seems odd to me, but...it looks like it's working properly in storybook?

Fxa 5188 low recovery codes copy

---

packages/fxa-admin-panel/src/components/AccountSearch/Account/index.test.tsx
packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
packages/fxa-admin-panel/src/components/AccountSearch/index.test.tsx
packages/fxa-admin-panel/src/components/AccountSearch/index.tsx
packages/fxa-admin-server/src/event-logging/event-logging.service.ts
packages/fxa-admin-server/src/gql/account/account.resolver.spec.ts
packages/fxa-admin-server/src/gql/account/account.resolver.ts
packages/fxa-admin-server/src/gql/model/account.model.ts
packages/fxa-admin-server/src/graphql.ts
packages/fxa-admin-server/src/schema.gql
packages/fxa-shared/guards/AdminPanelGuard.ts

- Support needed ability to change user's current locale
- Allows viewing of user locale
- Allows editing of user locale
- Adds guard requiring 'support' level to edit user locale
Closes: FXA-5736

task(admin-panel): Allow editing user's locale

---

packages/fxa-admin-server/src/subscriptions/stripe.service.spec.ts
packages/fxa-auth-server/lib/routes/validators.js
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/validators.js
packages/fxa-payments-server/src/components/PaymentConfirmation/index.stories.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.stories.tsx
packages/fxa-payments-server/src/components/PaymentMethodHeader/index.stories.tsx
packages/fxa-payments-server/src/components/PlanDetails/index.stories.tsx
packages/fxa-payments-server/src/lib/mock-data.tsx
packages/fxa-payments-server/src/lib/test-utils.tsx
packages/fxa-payments-server/src/routes/Product/index.stories.tsx
packages/fxa-payments-server/src/routes/Product/index.test.tsx
packages/fxa-payments-server/src/routes/Product/index.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx
packages/fxa-shared/payments/stripe.ts
packages/fxa-shared/subscriptions/types.ts
packages/fxa-shared/test/subscriptions/configuration/helpers.ts
packages/fxa-shared/test/subscriptions/configuration/utils.ts
packages/fxa-shared/test/subscriptions/metadata.ts

The plans endpoint previously did not return inactive plans. This caused
issues with users who are subscribed to a plan which was then
subsequently marked inactive.
Returns inactive plans from the plans endpoint, along with the active
flag. The payments frontend now checks to see if a plan is inactive
before allowing the user to proceed through the payment flow.
Closes: FXA-5599

fix(payments-server): return inactive plans

---

packages/fxa-admin-panel/src/components/AccountSearch/index.test.tsx
packages/fxa-admin-panel/src/components/AccountSearch/index.tsx
packages/fxa-admin-panel/src/components/ErrorAlert/index.test.tsx
packages/fxa-admin-panel/src/components/ErrorAlert/index.tsx
packages/fxa-admin-panel/src/components/ErrorAlert/mocks.tsx
packages/fxa-admin-panel/src/components/PageRelyingParties/index.tsx

- The admin panel doesn't give devs much details on any error
- Reuses the alert in https://github.com/mozilla/experimenter/tree/c9f568e53af26f7a548b2542d7259345a3c4b26e/app/experimenter/nimbus-ui/src/components/ApolloErrorAlert
- Doesn't use `react-bootstrap` since it seemed overkill, opted to style with tailwind
Closes: https://mozilla-hub.atlassian.net/browse/FXA-5249

fix(admin): Add error alert in admin panel

---

packages/fxa-auth-server/lib/error.js
packages/fxa-auth-server/lib/routes/subscriptions/apple.ts
packages/fxa-auth-server/test/local/routes/subscriptions/apple.js

Because:
* Our default error message, "IAP Internal Error" is not very helpful to RPs in the case that a subscription purchase is already registered to another user.
This commit:
* Updates the error code and message to be more descriptive.
Closes #FXA-5876

chore(auth): improve error message for Apple IAP purchase conflict

---

packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.stories.ts
packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts

- Our existing `subscriptionUpgrade` template was written to only handle upgrades in the same billing cycle
- We want to properly communicate what the user should expect when they upgrade to a different billing cycle
- Updates `subscriptionUpgrade` email template for different billing cycle
- Updates `subscriptionUpgrade` email template for stories and plaintext
- Updates and adds tests for same and different billing cycles
Closes: FXA-5734

fix(emails): update subscriptionUpgrade email copy

---

packages/fxa-auth-server/scripts/prune-tokens.ts
packages/fxa-auth-server/test/scripts/prune-tokens.js

- We observed the token pruner exiting with a non-success error code.
- It was initially thought this was possible this is due to an OOM error.
- Stop querying all session ids for an account, as this could return a large number of sessions.
- Query Redis first, and use that as the basis for cleaning up orphaned tokens. Because there are a limited number of sessions in Redis, this should result in lighter weight operation.
- Improve logging of errors encountered during pruning.
- Removes recursive call that deletes sessions and uses a simple for loop instead. This could prevent a stack overflow in extreme cases.
- Makes tests names more consistent.
Closes: FXA-5945
We don't have any hard evidence that there is an OOM error at the moment; however, during …

bug(auth-server): Fix potential for high memory usage in auth server.

---

packages/fxa-auth-server/lib/senders/emails/templates/postRemoveAccountRecovery/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/postRemoveAccountRecovery/includes.json
packages/fxa-auth-server/lib/senders/emails/templates/postRemoveAccountRecovery/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/postRemoveAccountRecovery/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts

Because:
* We're updating copy and Storybook for emails
This commit:
* updates tests, copy, and storybook for postRemoveAccountRecovery
Closes # https://mozilla-hub.atlassian.net/browse/FXA-5199

copy(fxa-auth-server): update copy for postRemoveAccountRecovery

---

packages/fxa-admin-server/src/subscriptions/subscriptions.service.spec.ts
packages/fxa-admin-server/src/subscriptions/subscriptions.service.ts

Due to some typecasting and improper typing, the admin server would try to return null for some properties which were declared as non-null in the schema if there existed an IAP subscription with no matching stripe plan. This would cause GraphQL to throw a "cannot return null for non-nullable field" error.
Throws an error when the user has an IAP subscription with no matching stripe plan.
There is further work to do in this area of the codebase, however. The underlying issue at play here is the improper typing and typecasting of many of the fields assembled to serve these requests. A followup ticket will be made to solve these issues.
Closes FXA-5820

fix(fxa-admin-server): throw error when iap sub has no matching stripe plan

---

packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
packages/fxa-auth-server/lib/senders/emails/templates/postNewRecoveryCodes/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/postNewRecoveryCodes/includes.json
packages/fxa-auth-server/lib/senders/emails/templates/postNewRecoveryCodes/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/postNewRecoveryCodes/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts

Because:
* We have updated copy and storybook text the for postNewRecoveryCodes email
This commit:
* Updates the copy, and updates the storybook condition
Closes: # https://mozilla-hub.atlassian.net/browse/FXA-5198

copy(fxa-auth-server) copy updates for postNewRecoveryCodes

---

packages/fxa-content-server/app/scripts/views/mixins/connect-another-device-mixin.js
packages/fxa-content-server/app/scripts/views/mixins/pairing-graphics-mixin.js
packages/fxa-content-server/app/tests/spec/views/connect_another_device.js
packages/fxa-content-server/app/tests/spec/views/mixins/pairing-graphics-mixin.js

Because:
* We were redirecting users to /pair when they should be shown the connect another device screen and were showing users the wrong graphic at another entrypoint
This commit:
* Adds a check for 'action=email' and doesn't redirect if present with 'entrypoint=fxa_app_menu'
* Removes other, new entrypoint checks for the redirect
* Adds an entrypoint check to show the QR code graphic
Closes [FXA-5850](https://mozilla-hub.atlassian.net/browse/FXA-5850), closes [FXA-5947](https://mozilla-hub.atlassian.net/browse/FXA-5947)
---
See ticket and see [this comment](https://mozilla-hub.atlassian.net/browse/FXA-5452?focusedCommentId=573894). I tested most of the flows laid out, but there's a lot, so feel free to poke around.

fix(CAD): Update entrypoint checks causing unwanted redirects/wrong graphic

---

packages/fxa-admin-panel/src/components/AccountSearch/Account/index.test.tsx
packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
packages/fxa-admin-server/package.json
packages/fxa-admin-server/src/app.module.ts
packages/fxa-admin-server/src/backend/auth-client.service.ts
packages/fxa-admin-server/src/backend/backend.module.ts
packages/fxa-admin-server/src/config/index.ts
packages/fxa-admin-server/src/gql/account/account.resolver.spec.ts
packages/fxa-admin-server/src/gql/account/account.resolver.ts
packages/fxa-admin-server/src/gql/gql.module.ts
packages/fxa-admin-server/src/graphql.ts
packages/fxa-admin-server/src/schema.gql
packages/fxa-shared/guards/AdminPanelGuard.ts
yarn.lock

- This feature was requested by our support team
- Allows a support agent to iniitate the password reset flow for a user
- Reuses the fxa-auth-client to call FxA api
- Adds nestjs backend module (looking to refactor this since it exisits in fxa-graphql-api project too)
- Adds guards for the feature
Closes: https://mozilla-hub.atlassian.net/browse/FXA-5716

feat(admin): Allow support agents to send password reset email

---

packages/fxa-auth-server/lib/error.js
packages/fxa-auth-server/lib/payments/iap/iap-config.ts
packages/fxa-auth-server/test/local/payments/iap/iap-config.js

- we should throw a 404 error instead of a 500 for unknown app name
- updates to use error `unknownAppName` in all three methods (plans, packageName and getBundleId) in the IAPConfig class
Closes: [FXA-5244](https://mozilla-hub.atlassian.net/browse/FXA-5244)

fix(auth): Throw a 404 instead of a 500 for unknown app name

---

packages/fxa-admin-panel/interfaces/index.ts
packages/fxa-admin-panel/server/config/index.ts
packages/fxa-admin-panel/server/lib/client-config/index.test.ts
packages/fxa-admin-panel/server/lib/client-config/index.ts
packages/fxa-admin-panel/server/lib/server.ts
packages/fxa-admin-panel/src/index.test.tsx
packages/fxa-admin-panel/src/index.tsx
packages/fxa-admin-panel/src/lib/config.ts
packages/fxa-payments-server/src/lib/config.ts

Because:
* Admin-panel was missing AppErrorBoundary and Sentry hook up
This commit:
* Adds AppErrorBoundary from fxa-react, adds Sentry config options, and updates tests
Closes [FXA-5256](https://mozilla-hub.atlassian.net/browse/FXA-5256) (sorry for branch number confusion, I must've been looking at the wrong number)

feat(sentry): Add AppErrorBoundary to admin-panel and enable Sentry

---

packages/fxa-auth-server/package.json
yarn.lock

This version has a ESM requirement.
Reverts mozilla/fxa#14066

Revert "chore(deps): bump emittery from 0.13.1 to 1.0.0"

---

packages/fxa-admin-panel/src/index.tsx

- All gql queries were being directed to 8091 instead of 8095 where the graphql api lives.
- A recent refactor changed when readConfigFromMeta was being called.
- Makes sure the config is parsed right away by calling readConfigFromMeta first.
Closes: FXA-5961

bug(admin-panel): Fix broken requests to admin-server

---

packages/fxa-auth-server/lib/senders/emails/templates/postRemoveAccountRecovery/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/postRemoveAccountRecovery/index.mjml

Because:
* A string was missing from storybook and an mjml email due to a missing ">" in a span tag. Credit to @xlisachan for finding it!
This commit:
* Correctly closes the span tag.
Closes # https://mozilla-hub.atlassian.net/browse/FXA-5199

fix(fxa-auth-server): close broken span tag in email

---

packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/lib/senders/emails/partials/appBadges/index.mjml
packages/fxa-auth-server/test/local/senders/emails.ts

Because:
* A word was missing from the template, and the template was receiving incorrectly named variables for some reason. I searched in the template for the (original) variable names but did not find them, so it must have just been an error?
This commit:
* Fixes the var names to match the appBadges partial, and adds the missing word
Closes # https://mozilla-hub.atlassian.net/browse/FXA-5193
- [] If applicable, I have modified or added tests which pass locally.
Since the errors were not showing up in Storybook (so I can't show meaningful changes), I've included screenshots of the amended plaintext and .html files as output by `yarn write-emails`. 
Here you can see the populated links as required:
Here you can see the added preposition ("Install `on` …

fix(fxa-auth-server): correct local var names and add missing word

---

packages/fxa-shared/README.md
packages/fxa-shared/test/tracing/node-tracing.ts
packages/fxa-shared/tracing/config.ts
packages/fxa-shared/tracing/node-tracing.ts

- We don't need to capture all open telemetry traces.
- We want to control the rate at which traces are captured.
- Introduces a tracer config setting 'sampleRate'
- Adds a ParentBasedSampler with TraceIdRatioSampling to our NodeTracerProvider
Closes: FXA-5861
To see this see the effect of this config setting, do the following:
- In the your .env file set `TRACING_JAEGER_EXPORTER_ENABLED=true` and set `TRACING_SAMPLE_RATE=0.05`
- Make sure pm2 is stopped and start it fresh with `dotenv -- yarn start` (note, dotenv-cli npm package must be installed)
- Conduct a typical sign up flow.
- Check Jaeger running on localhost:16686, select fxa-auth-server from the services drop down, click `find traces` and see that very few traces were captured.
- Now set …

FXA-5861-add-trace-sample-rate

---

packages/fxa-content-server/pm2.config.js
packages/fxa-content-server/server/bin/fxa-content-server.js
packages/fxa-content-server/server/lib/configuration.js

- We want to see traces
- Adds tracing to the content server. Note this is limited to tracing on server side, and does not include the client side.
Closes: FXA-5970
Compared to other services, I don't see this trace info being terribly useful. It might not even be worth capturing these traces in production; however, we may as well have the instrumentation ready to go in the event we need it to troubleshoot something.

task(content-server): Add tracing to content server

---

packages/fxa-payments-server/pm2.config.js
packages/fxa-payments-server/server/config/index.js
packages/fxa-payments-server/server/lib/server.js

- We want to be able to see traces
- Adds trace support
Closes: FXA-5971
Compared to other services, I don't see this trace info being terribly useful. It might not even be worth capturing these traces in production; however, we may as well have the instrumentation ready to go in the event we need it to troubleshoot something.

task(payments): Add tracing to payments

---

packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-content-server/tests/server/amplitude.js
packages/fxa-settings/src/components/PageSettings/index.test.tsx
packages/fxa-settings/src/components/PageSettings/index.tsx

Because:
* We've gotten some preliminary data from this test and no longer need it around
This commit:
* Removes all references to fallback text needed/not needed metrics events in PageSettings and Amplitude mapping
closes [FXA-5932](https://mozilla-hub.atlassian.net/browse/FXA-5932)

chore(settings): Remove temp fallback text test

---

packages/fxa-customs-server/bin/customs_server.js
packages/fxa-customs-server/lib/config/config.js
packages/fxa-customs-server/pm2.config.js

- We want to see traces
- Adds tracing to the customs server
Note that we can auth-server calls going to customs server with this addition. 
In order to see customs server traces locally, you will need to make sure the customs server is enabled. This can be done by setting `customsUrl` in fxa-auth-server/config/dev.json to http://localhost:7000.

task(customs): Add tracing to customs server

---

packages/fxa-content-server/app/scripts/templates/connect_another_device.mustache

Because:
- the CAD page was changed a couple times recently and an event was dropped between those changes somehow
The change was previously approved in https://github.com/mozilla/fxa/pull/14078, specifically https://github.com/mozilla/fxa/pull/14078/files#diff-ffde16ed75a1413c6306b919b2e700495620eaa75a15fc9e17ae13a7e996a683R46 but when the CAD was updated again it was merged out of existence I think.

fix(metrics): restore nav to /pair click event

---

packages/fxa-auth-server/lib/routes/subscriptions/paypal-notifications.ts
packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js

- PayPal NVP returned a non-success ACK - billing agreement was cancelled, as we are not capturing the error
- logs error when the billing agreement's status is `Canceled`
Closes: [FXA-5936](https://mozilla-hub.atlassian.net/browse/FXA-5936)
Source: [PayPal](https://developer.paypal.com/api/nvp-soap/ba-update-soap/#link-baupdaterequestmessage)

fix(auth): Capture error if billing agreement is cancelled

---

packages/fxa-payments-server/src/index.scss
packages/fxa-payments-server/src/routes/Subscriptions/index.scss
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

- The checkbox is still displayed differently, depending on the used browser: 
- on Safari browser: the checkbox is smaller than usual and it is not centered;
- on Firefox browser: the checkbox is correctly displayed and centered;
- on Chrome browser: the outline of the checkbox is thinner - attaching a ss as well.
- Checkbox
- Removes unnecessary flex-direction, position, and top properties, and adds align-items: center to actually center checkbox and text
- Adds `transform: scale(1.5)` as checkbox in Safari browser appeared smaller
- Remove duplicate stylesheet for checkbox
- Duplicate `payment-update.header.h2` style - reassigned to 600
- Replaced `profile-image` class with correct style in TW
Closes: [FXA-5862](https://mozilla-hub.atlassian.net/browse/FXA-5862)
_Put an `x` in the …

fix(payments): Fix checkbox UI issue

---

packages/fxa-profile-server/bin/server.js
packages/fxa-profile-server/lib/config.js
packages/fxa-profile-server/lib/server/_static.js
packages/fxa-profile-server/lib/server/web.js
packages/fxa-profile-server/lib/server/worker.js
packages/fxa-profile-server/pm2.config.js

* We're replacing the sentry tracing library/configuration with OpenTelemetry (per the auth server)
* Removes sentry tracing and replaces it with OpenTelemetry, modelled on the work already done in the auth server
Closes # https://mozilla-hub.atlassian.net/browse/FXA-5720

feat(fxa-profile-server): add OpenTelemetry library to profile server

---

packages/functional-tests/pages/login.ts
packages/functional-tests/pages/settings/changePassword.ts
packages/functional-tests/pages/settings/layout.ts
packages/functional-tests/tests/settings/changeEmail.spec.ts
packages/functional-tests/tests/settings/changePassword.spec.ts
packages/functional-tests/tests/settings/password.spec.ts

`- As part of the playwright test migration, the [change password tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/settings/change_password.js) have been rewritten in this PR. The only tests not covered here are the last 2 'unnormalized email' tests present in the file linked above. Those two tests will be covered as part of a different PR`
`- Contains tests for all the scenarios related to change password present in the [file](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/settings/change_password.js) except the last 2 tests related to unnormalized email. Those two tests will be covered as part of a different PR`
Closes: [FXA-5903](https://mozilla-hub.atlassian.net/browse/FXA-5903)
_Put an `x` in the boxes …

Rewrite change password using playwright

---

packages/fxa-auth-server/lib/routes/account.ts
packages/fxa-auth-server/lib/routes/index.js
packages/fxa-auth-server/lib/types.ts
packages/fxa-shared/tracing/node-tracing.ts

- Users that opted out of metrics don't want their traces sampled
- I looked at several different ways to accomplish this and landed on adding a parent context that suppresses telemetry
- Options considered
- Add attributes to span to specfic excluding it from tracing, Add a custom sampler to filter out these spans
- This approach was not the intended use of span attributes and could have costly lookups
- Update node auto instrumentation to exclude urls
- If we did this we would have to manually add urls to exclude from tracing
- Wrap trace supported routes with a new parent context that suppresses tracing
- Read a custom request header and filter out request if it is set
- This approach would be great and very straightforward however, it requires knowing the metrics status of a user. …

feat(admin): Ignore traces from users that have opted out of metrics

---

packages/fxa-content-server/app/styles/tailwind/inputs.css

Because:
* The PW eye was rendering underneath the edge of the PW input in Safari, including FF on iOS
This commit:
* Adds 'top-0' to the PW eye to address the bug, then targets Safari's native PW helper to scoot it over to prevent overlap with the PW eye
Fixes [FXA-5871](https://mozilla-hub.atlassian.net/browse/FXA-5871)
--
I took a few different approaches to fixing this before landing here. The fix for the bug is easy (adding `top-0`, which fixes the problem in Safari and has no visual change in other browsers) but we needed to account for Safari's native PW helper because the eye would overlap it.
At first I used a [pretty hacky media query](https://github.com/mozilla/fxa/compare/FXA-5871?expand=1#diff-0223815a40e5acf034c88d92557eaf7515f57583e57ecdb3694a993cc388e5a5R51), TLDR is it …

fix(safari): Tweak content-server input and PW eye styles for Safari rendering bug

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe.js

- The wrong proration amount was being displayed in subscription upgrade emails for both same and different billings cycles
- Updates the proration amount so the proper one-time fee is being displayed in both same and different billing cycles
- Updates tests to compare against current invoice amount as opposed to upcoming invoice amount (i.e., next cycle)
Closes: FXA-5734

fix(emails): update SubscriptionUpgrade proration amount in emails

---

packages/fxa-auth-server/docs/swagger/subscriptions-api.ts
packages/fxa-auth-server/lib/payments/capability.ts
packages/fxa-auth-server/lib/routes/subscriptions/mozilla.ts
packages/fxa-auth-server/test/local/payments/capability.js
packages/fxa-auth-server/test/local/routes/subscriptions/mozilla.js
packages/fxa-shared/subscriptions/stripe.ts

There isn't a great way to currently get your eligibility for a given plan outside of a 1-to-1 upgrade from plan A to B.
This endpoint provides a way to check your eligibility path for a given plan, and will return an eligibility status of:
- create (user can create a brand new subscription to this plan)
- upgrade (user is subscribed to a plan that can be upgraded to this plan)
- downgrade (user is subscribed to a plan that can be downgraded to this plan
- blocked_iap (user is subscribed to a plan via IAP that includes a productSet that conflicts with this plan and therefore cannot subscribe to this plan)
- invalid (configuration issue)
Closes: FXA-5479

feat(auth): get plan eligibility

---

packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.test.tsx
packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx

Because:
* Users can't see our additional secondary email info because Fluent is replacing the entire section with header text
This commit:
* Sends localized text into the 'header' prop for UnitRow, rather than using a Localized wrapper that was replacing the entire DOM output
fixes [FXA-2984](https://mozilla-hub.atlassian.net/browse/FXA-2984)
---
Before:
After:
Testing in Italian for good measure:

fix(settings): Fix secondary email 'Not Set' state

---

packages/fxa-auth-server/bin/key_server.js
packages/fxa-auth-server/lib/log.js
packages/fxa-auth-server/test/local/log.js
packages/fxa-content-server/server/lib/logging/route_logging.js
packages/fxa-shared/tracing/node-tracing.ts

- We want to capture `traceId` in our log statements
- Adds `traceId` to auth server info, debug, error logs
Closes: https://mozilla-hub.atlassian.net/browse/FXA-5086
I'm not sure how we intend to use the traceId in logs, but I added it to the auth-server since that seems most valuable?

feat(admin): Add `traceId` to log statements

---

packages/fxa-auth-server/lib/routes/subscriptions/mozilla.ts

It looks like importing from package names does not resolve correctly once we go to STG.
Swaps a package name based import to a relative one.
Closes: [FXA-6023](https://mozilla-hub.atlassian.net/browse/FXA-6023)

fix(auth-server): swap import style for mozilla.ts

---

.github/workflows/l10n-gettext-extract.yml

- Certain JavaScript syntax such as chaining operator breaks the gettext string extraction workflow, blocking l10n.
- Introduces a GitHub action that runs the build process and string extraction workflow on a pull_request, failing if the string extraction workflow encounters an error.
Closes: #14057

chore(l10n): check if PR breaks build, flag gettext reviews

---

packages/fxa-shared/test/tracing/node-tracing.ts
packages/fxa-shared/tracing/node-tracing.ts

- With default configs, we'd see lots of warning messages in Circle CI logs.
- Checks if any exporters are enabled before initializing the tracer.
- If no tracers are enabled, initialization is skipped, which prevents the error state from being triggered.
Closes: FXA-6062

FXA-6026-trace-noise-in-circle-ci

---

packages/fxa-auth-server/bin/key_server.js
packages/fxa-auth-server/lib/log.js

- Logs were being emitted twice
- Provides a name to the logger instance sent into node-tracing
- Adds a fail hard fail fast check to prevent this from happening in the future.
Closes: FXA-6000

bug(auth): Fix double log scenario

---

packages/fxa-shared/sentry/pii-filter-actions.ts
packages/fxa-shared/test/sentry/pii-filter-actions.ts
packages/fxa-shared/test/tracing/node-tracing.ts
packages/fxa-shared/tracing/config.ts
packages/fxa-shared/tracing/node-tracing.ts
packages/fxa-shared/tracing/pii-filters.ts

- We want to scrub PII from span attributes in trace data.
- Piggy backs for sentry PII scrubbing to scrub traces before they exported to jaeger/gcp.
- Makes minor improvements to email and token scrubbing actions.
Closes: FXA-5883

task(shared): Scrub PII from tracing data

---

.github/workflows/l10n-gettext-extract.yml

* Action fails under certain conditions when it tries to checkout the base SHA but it cannot be found
* Adds an explicit fetch for the base SHA to ensure it can be checked out
* Also removes the redundant repository call-out (which would cause issues for forks)

chore(l10n): Revise workflow to fetch base commit

---

packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
packages/fxa-auth-server/lib/senders/emails/templates/postRemoveTwoStepAuthentication/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/postRemoveTwoStepAuthentication/includes.json
packages/fxa-auth-server/lib/senders/emails/templates/postRemoveTwoStepAuthentication/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/postRemoveTwoStepAuthentication/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts

* We're updating copy for emails
* Updates copy and tests for the postRemoveTwoStepAuthentication email
Please attach the screenshot
s of the changes made in case of change in user interface.

copy(fxa-auth-server): update postRemoveTwoStepAuthentication email

---

packages/fxa-auth-server/lib/senders/emails/global.scss
packages/fxa-auth-server/lib/senders/emails/partials/button/index.scss

* We want our color values to match across emails + services
* Updates the color variable from equalling TW blue-400 to blue-500.
Closes #https://mozilla-hub.atlassian.net/browse/FXA-5851
Before:
After:

fix(fxa-auth-server) match email colors to fxa-react colors

---

packages/functional-tests/pages/login.ts
packages/functional-tests/pages/settings/recoveryKey.ts
packages/functional-tests/tests/settings/recoveryKey.spec.ts

`-As part of the playwright test migration, the [recovery key tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/settings/recovery_key.js) have been rewritten in this PR. The only tests not covered here are the last 'unnormalized email' tests present in the file linked above. Those test will be covered as part of a different PR`
`-Contains tests for all the scenarios related to recovery key present in the [file](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/settings/recovery_key.js) except the last test related to unnormalized email. This test will be covered as part of a different PR`
Closes: [FXA-5893](https://mozilla-hub.atlassian.net/browse/FXA-5893)
Please attach the …

test(functional): rewrite recovery tests using playwright

---

packages/fxa-payments-server/src/components/CouponForm/index.scss

- Coupon error message has no bottom padding for certain screen sizes
- Removes padding, and changes parents overflow to hidden, so that
child margins are not collapsed.
- This is a temporary fix and will be reworked by Tailwind changes
Closes: #FXA-6027
Before change
After change

fix(payments): add padding to coupon error

---

packages/123done/oauth.js
packages/123done/server.js
packages/123done/static/index.html
packages/123done/static/js/123done.js
packages/fxa-auth-server/config/dev.json
packages/fxa-content-server/server/lib/configuration.js

- We currently don't have any accesible view/flows to test scope keys
- Adds support to 123done to request scope key
- Adds new scope `https://identity.mozilla.com/apps/123done`
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6038
To test, goto `http://localhost:8080` and click on the `Sign in (scopeKeys)` button. Once this PR lands, I'll have to do a manual push to our 123done environment so that it picks up the changes.

fix(scope): Add support for 123done to request a scope key

---

packages/fxa-content-server/app/scripts/views/support.js

- Support form can be sent even if not all mandatory fields are filled
- Removes productPrefix if productName is empty
Closes: #FXA-3640
Before
After

fix(support): support frm required field check fix

---

packages/fxa-payments-server/src/components/PlanDetails/index.test.tsx
packages/fxa-payments-server/src/components/PlanDetails/index.tsx
packages/fxa-payments-server/src/lib/test-utils.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx
packages/fxa-shared/subscriptions/configuration/base.ts
packages/fxa-shared/subscriptions/configuration/utils.ts
packages/fxa-shared/subscriptions/types.ts
packages/fxa-shared/test/subscriptions/configuration/utils.ts

Other teams have requested the ability to add specific names to individual prices and have those appear in place of the product name.
Displays the 'name' field from the plan_metadata if it's present, otherwise falls back to the product name when not present.
Closes: FXA-5959

feat(payments): surface plan_metadata name when present

---

packages/fxa-settings/src/components/ConnectAnotherDevicePromo/storeImageLoader.tsx

- Badges text not translated for zh-cn locale
- Fix spelling mistake in map to return translated badge for zh-cn

fix(settings): fix zh-cn locale store badges

---

packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/includes.json
packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/index.stories.ts
packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/index.txt
packages/fxa-auth-server/test/local/senders/emails.ts

* We're updating email copy
* Update copy, tests, and fluent files for postAddTwoStepAuthentication email

copy(fxa-auth-server): update postAddTwoStepAuthentication email copy

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe.js

- We only use the interval (day/week/month/year), which does not indicate the period (ex 2 weeks) in which the user is billed.
- Adds the interval_count when the interval_count is not 1.
Closes FXA-5975
There are two important notes with regard to the functionality in this PR:
1. The interval_count+interval combined string is not pluralized.
2. The interval is not localized (it was also not localized before).
Both of the above expand the scope of this bugfix and would require changing non-insignificant number of different files to introduce that support. We have a ticket (https://mozilla-hub.atlassian.net/browse/FXA-3645) that covers doing that work, but this bugfix is considered high enough priority to be merged prior to that support.
With the above …

fix(auth-server): support billing period interval_counts in upgrade emails

---

packages/fxa-content-server/app/styles/tailwind/ctas.css

Because:
- a link that's styled like a button with cta-primary has the same font and background color when it's focused
This commit:
- update the :focus color of the link
Fixes FXA-5972

fix(styles): update :focus color of link dressed as a button

---

packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-content-server/tests/server/amplitude.js

Because:
- the event for pairing authority "approval" was misleading
- it was based on the post-approval view where it's waiting for the supplicant's confirmation, a view that is not displayed if the supplicant confirmed before the authority's approval
This commit:
- rename the wait for supplicant view event
- add an event for the authority approval submission
Fixes FXA-6024

fix(metrics): update pair authority events

---

packages/fxa-auth-server/lib/routes/oauth/token.js
packages/fxa-auth-server/test/lib/oauth-test.json
packages/fxa-auth-server/test/oauth/api.js

- To provide a better user experience we want trusted RPs to be able to increase the scope of access token
- Allows trusted RPs to request additional scopes during the refresh token grant
- Only scopes in the client's `allowedScopes` property can be requested.
Closes: https://mozilla-hub.atlassian.net/browse/FXA-5880

feat(scopes): Allow trusted reliers to increase scope of token when using refresh token

---

packages/fxa-content-server/app/scripts/templates/partial/coppa-age-input.mustache
packages/fxa-content-server/app/tests/spec/views/sign_up_password.js
packages/fxa-content-server/tests/functional/lib/selectors.js

Because:
- feedback from legal
This commit:
- link to an explanation on FTC's web site for COPPA
- update the input's label to refer to the new link
Fixes FXA-6011

chore(signup): add FTC COPPA link

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.test.tsx
packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.tsx
packages/fxa-payments-server/src/components/PaymentMethodHeader/index.test.tsx

Because:
* Displaying the correct, localized amount and interval in more than one place is a source of discrepancies.
* This information is already shown in the PlanDetails component.
This commit:
* Removes localized amount and interval from the PaymentConsentCheckbox copy and updates the copy to reference the information in the PlanDetails component.
Closes #FXA-6049

chore(payments): remove plan info and update PaymentConsentCheckbox copy

---

_dev/pm2/infrastructure.config.js
_scripts/configs/otel-collector-config.yaml
_scripts/jaeger.sh
_scripts/otel-collector.sh
packages/fxa-content-server/app/scripts/app.js
packages/fxa-content-server/server/lib/beta-settings.js
packages/fxa-content-server/server/lib/csp/blocking.js
packages/fxa-settings/src/index.tsx
packages/fxa-shared/README.md
packages/fxa-shared/test/tracing/browser-tracing.ts
packages/fxa-shared/test/tracing/exporters.ts
packages/fxa-shared/test/tracing/node-tracing.ts
packages/fxa-shared/tracing/browser-tracing.ts
packages/fxa-shared/tracing/config.ts
packages/fxa-shared/tracing/exporters/exporters.ts
packages/fxa-shared/tracing/exporters/fxa-otlp.ts
packages/fxa-shared/tracing/node-tracing.ts
yarn.lock

- We want to start trace capture at client side
- We can't report trace data directly to cloud trace
- Adds an open telemetry collector service (otel-collector)
- Configures service to export to jaeger and gcp
- Ability to uses otel-collector service for all trace capture
- Rename 'jaeger' in config to 'otel' since export is no longer jaeger specific.
- Adds flow id to trace id headers so traces can be validated
Closes: FXA-6021
Closes: FXA-6022
_GCP trace view captured from local host_
Make sure the default application credentials are fresh
```
gcloud auth application-default login
```
Set the following envs in the .env file in fxa root.
```
TRACING_SAMPLE_RATE=1
TRACING_BATCH_PROCESSING=false
TRACING_OTEL_EXPORTER_ENABLED = true …
```

task(shared) - Add service to capture client side traces

---

packages/fxa-auth-server/lib/payments/capability.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
packages/fxa-shared/subscriptions/types.ts

* Only the frontend enforces that you should not be able to create duplicate subscriptions.
* Checks to see if the subscription you're creating is a duplicate.
Closes FXA-6035

fix(auth-server): check for duplicate subs when creating subscription

---

packages/fxa-admin-server/package.json
packages/fxa-auth-server/package.json
packages/fxa-event-broker/package.json
yarn.lock

Because:
* We want to use the latest version of firestore.
This commit:
* Updates firestore to 6.3.0.

chore(deps): bump @google-cloud/firestore from 5.0.2 to 6.3.0

---

packages/fxa-auth-server/docs/swagger/auth-server-api.ts

- wrong error message was mapped to the error code in the documentation
- corrected the error message and updated the list as well
Closes: [FXA-6047](https://mozilla-hub.atlassian.net/browse/FXA-6047)

docs(auth-server): Wrong error code mapping in fxa-auth-server

---

.github/workflows/l10n-gettext-extract.yml

- Reviewer requests will be issued to fxa-l10n team every time a pull request is updated (for PRs where new gettext strings are found).
- Adds some additional checks (Is fxa-l10n already assigned as reviewer?, Has someone from l10n team already approved this PR?). This reduces the amount of times fxa-l10n is issued a request for review.

chore(l10n): reduce redundant gettext review requests

---

docs/adr/0032-l10n-i18n-improvements.md

Because:
* We've had discussions over l10n improvements that should be made and want to capture major decisions in an ADR
This commit:
* Creates said ADR
Closes [FXA-5884](https://mozilla-hub.atlassian.net/browse/FXA-5884)
---
I added everyone in fxa-devs that commented in the RFC doc to the deciders list.
All of these decisions have been made except for the last decision regarding submodules/subtree pros/cons, so I'll probably merge this fairly soon after 1-2 approvals.

chore(docs): Add ADR summarizing l10n / i18n improvements RFC

---

packages/fxa-auth-server/package.json
packages/fxa-auth-server/scripts/create-mock-iap-subscriptions.ts
packages/fxa-auth-server/scripts/create-mock-iap-subscriptions/mock-iap-subscription-manager.ts
packages/fxa-auth-server/scripts/create-mock-iap-subscriptions/mock-iap-subscriptions.json

* It's hard to test IAP locally since the emulator resets every time you restart local services
* Adds a util for easily creating IAP subscriptions locally
Closes FXA-5381

feat(auth-server): mock iap subscriptions util

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/payments/paypal-processor.js
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js
packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
packages/fxa-auth-server/test/remote/account_create_tests.js
packages/fxa-auth-server/test/remote/subscription_tests.js
packages/fxa-shared/payments/stripe.ts

Because:
* We want to switch to Stripe Tax calculations for taxing new
Stripe subscriptions.
This commit:
* Adds the IP for Stripe Tax to calculate appropriate tax for further
subscriptions and enables it for a new Stripe subscription if the
user is in a taxable location.
Closes: FXA-5649
- [] If applicable, I have modified or added tests which pass locally.

feat(auth): add tax via ip for new stripe subscriptions

---

packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/index.tsx
packages/fxa-shared/lib/sentry.ts
packages/fxa-shared/test/lib/sentry.ts

- When a user opts out of metrics they also want to opt out of telemetry
- Disables/Enables sentry based on the user's metrics preferences
Closes: https://mozilla-hub.atlassian.net/browse/FXA-5475
Note that Sentry is disabled in the settings app because in our login pages we don't know their metrics status until after they log in.

fix(sentry): Don't report to sentry when user disables metrics

---

_scripts/mysql.sh

Because:
* We updated the local mysql to a version that doesn't pass auth-server tests.
This commit:
* Bumps the mysql version and updates the test to pass.
Closes #FXA-6068.

fix(auth): test for proper mysql response

---

packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts

Because:
* There's some discrepancy in how imports work between local and stage (FXA-6051).
This commit:
* Fixes the immediate error (long term fix is in FXA-6051).
Closes #FXA-6070

fix(auth): use relative import on fxa-auth-server modules

---

packages/fxa-auth-server/lib/payments/paypal/client.ts
packages/fxa-auth-server/lib/payments/paypal/helper.ts
packages/fxa-auth-server/test/local/payments/paypal-client.js
packages/fxa-auth-server/test/local/payments/paypal.js

Because:
* We want to charge users sales tax and ensure it shows up on PayPal invoices.
This commit:
* Includes the tax amount as an optional argument into DoReferenceTransaction. *
Closes #FXA-5764

feat(auth): allow including tax amounts for PayPal DoReferenceTransaction

---

packages/fxa-settings/src/components/Security/index.test.tsx

Because:
* Translating a numerical value into a system local time is inconsistent depending on timezone.
This commit:
* Gets the local systems day of the month for the password render test so that it passes regardless of the systems timezone.
Closes #FXA-6080.

fix(settings): test relies on system timezone

---

packages/fxa-settings/src/components/PageSettings/index.stories.tsx
packages/fxa-settings/src/components/Profile/index.stories.tsx
packages/fxa-settings/src/components/Profile/mocks.tsx
packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.stories.tsx
packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.test.tsx
packages/fxa-settings/src/models/mocks.tsx

Because:
* We need to update our components to use the new Storybook format and want components to contain their own mocks
This commit:
* Refactors 'Profile' stories to new SB format
* Creates mocks.tsx for Profile and adds these mocks, used in SB, and to be used in tests in another PR
* Updates mockEmail to use a mocked email address without arguments
---
I'm working on FXA-5999 and I'm adding the wrapper to strings within the `Profile` component. Since that ticket warrants test creation, I wanted some states to test, which prompted me to create `mocks.tsx`, and I figured I'd go ahead and update the SB format to show these states, which also lead me to also update `mockEmail`, and I figured it made sense for this to go in a separate PR so when I do get the PR up for FXA-9999 the diff …

refactor(storybook): Reformat 'Profile' stories to new SB format, add/update mocks

---

packages/fxa-shared/db/mysql.ts

- Adding the stack made the log message confusing and look like an error.
- Removes the 'stack' field from the log message.

task(shared): Remove stack trace from init log in mysql.ts

---

packages/fxa-settings/src/components/Avatar/index.stories.tsx
packages/fxa-settings/src/components/Avatar/index.test.tsx
packages/fxa-settings/src/components/Avatar/mocks.tsx

- We want to standardize all component stories to the new Storybook format
- Refactor the 'Avatar' component story to the new SB format
Closes: # [14248](https://github.com/mozilla/fxa/issues/14248)

refactor(fxa-settings): update avatar story to new SB format

---

packages/functional-tests/pages/login.ts
packages/functional-tests/pages/relier.ts
packages/functional-tests/tests/misc.spec.ts
packages/functional-tests/tests/oauth/forceAuth.spec.ts
packages/functional-tests/tests/oauth/handshake.spec.ts
packages/functional-tests/tests/settings/changeEmail.spec.ts
packages/fxa-content-server/tests/functional.js

- We are migrating functional tests overs to playwright
-Migrates `oauth_handshake` and `oauth_force_auth` tests
Closes: https://mozilla-hub.atlassian.net/browse/FXA-5896
Closes: https://mozilla-hub.atlassian.net/browse/FXA-5908
To test, from `functional-tests` directory run `yarn test-local --grep="OAuth"`

feat(tests): Migrate oauth handshake and force auth tests to playwright

---

packages/fxa-auth-server/config/index.ts
packages/fxa-auth-server/lib/getRemoteAddressChain.ts
packages/fxa-auth-server/lib/server.js
packages/fxa-auth-server/test/local/getRemoteAddressChain.js

- We need an easy way to change users IP address in localdev for testing tax and other things.
- Adds an environment variable that overrides the remote address chain.
Closes FXA-6072

feat(auth-server): env var to override client ip address chain

---

packages/fxa-settings/src/components/UnitRowRecoveryKey/en-US.ftl
packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx

Because:
- it's confusing to mention data loss from password change on the account recovery key section of Settings
This commit:
- remove the link

chore(settings): remove a confusing link

---

packages/fxa-auth-server/test/local/l10n/index.ts
packages/fxa-auth-server/test/local/server.js
packages/fxa-shared/l10n/parseAcceptLanguage.ts
packages/fxa-shared/test/l10n/determineLocale.ts
packages/fxa-shared/test/l10n/parseAcceptLanguage.ts

Because:
* We previously set our negotiateLanguages strategy to 'matching' to address a bug where users with 'en' locales were showing 'en-GB' bundles since we didn't copy 'en' bundles into the l10n repo, as it was our intent that English users could see fallback text instead. We now deploy 'en' bundles for various reasons. Since we can't guarantee a bundle with all dialects will exist, like 'en-US' and others, we want to rely on Fluent's default 'filtering' strategy to provide us with similar locales as options, e.g. so 'en-US' will give us all dialects as options to load first, rather than a more strict check, which is what the 'matching' strategy gave us. TLDR, this ensures an 'en-US' locale will load the 'en' bundle we deploy.
This commit:
* Updates our negotiateLanguages call to go …

fix(l10n): Update Fluent negotiateLanguages strategy to default (filtering)

---

packages/fxa-auth-server/config/index.ts
packages/fxa-auth-server/lib/metrics/amplitude.js
packages/fxa-auth-server/lib/metrics/context.js
packages/fxa-auth-server/test/local/metrics/amplitude.js
packages/fxa-auth-server/test/local/metrics/events.js
packages/fxa-auth-server/test/mocks.js
packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-content-server/server/lib/configuration.js
packages/fxa-content-server/server/lib/flow-event.js
packages/fxa-content-server/tests/server/amplitude.js
packages/fxa-content-server/tests/server/flow-event.js
packages/fxa-payments-server/server/config/index.js
packages/fxa-payments-server/server/lib/amplitude.js
packages/fxa-payments-server/server/lib/amplitude.test.js
packages/fxa-shared/index.ts
packages/fxa-shared/metrics/dnt.ts
packages/fxa-shared/test/metrics/dnt.ts

Because:
- Do Not Track was inconsistently applied to flow metrics
- dnt handling was missing in "Amplitude" metrics
This commit:
- apply the same dnt filter to flow and "Amplitude" metrics in multiple
packages
- delete old code for logging "raw" (untransformed) "Amplitude" events,
which we never used in production
Fixes FXA-3647

fix(dnt): apply dnt filtering to more metrics

---

packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js
packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-webchannel-v1.js
packages/fxa-content-server/app/tests/spec/models/auth_brokers/oauth-webchannel-v1.js
packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-content-server/tests/server/amplitude.js

- We were double counting our complete events for login
- This bug was introduced by adding pairing metrics
- Gives pairing complete a new metric `fxa_login - complete_pairing` to signify that a user has finished the pairing flow and connected a device
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6015
Before PR metrics
```
fxa-content-server.amplitudeEvent: {"op":"amplitudeEvent","event_type":"fxa_email_first - view","time":1666203872167,"device_id":"c9cbd29630424f3c85fe81b35f236cc0","session_id":1666203868717,"app_version":"243.2","language":"en-US","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"123done","oauth_client_id":"dcdb5ae7add825d2"},"user_properties":{"flow_id":"849cbcb042499599e8a7fe41cb96405ebad85560f596221b5c59826d6bcd9cfe","ua_browser":"Firef …
```

fix(metrics): Remove duplicate `fxa_login - complete` events

---

packages/fxa-auth-server/lib/payments/paypal/client.ts
packages/fxa-auth-server/lib/payments/paypal/helper.ts
packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
packages/fxa-auth-server/test/local/payments/paypal-client.js
packages/fxa-auth-server/test/local/payments/paypal.js

Because:
* We want to charge users sales tax and ensure it shows up on PayPal invoices.
This commit:
* Passes the optional tax amount argument into DoReferenceTransaction along with other amounts now required by PayPal when tax is added.
Closes #FXA-5765
DRYed up the `processInvoice` describe block while I was at it.

feat(auth): pass tax amount into PayPal DoReferenceTransaction

---

.github/workflows/pull-legal-docs.yml
.gitignore
_scripts/.eslintrc
_scripts/pull-legal-docs.js

- We need to pull the latest pdfs from legal-docs into the fxa assets folder.
- Create a script to copy the latest pdfs into assets/legal.
- Create a Github Action to automatically pull in the pdfs from legal-docs, and open a pull request to move pdfs into assets/legal.
Closes: #fxa-5100

feat(scripts): pull pdfs from legal-docs

---

packages/db-migrations/databases/pushbox/patches/patch-001-002.sql

Because:
- some self-hosters might already have the pushbox db up and running
This commit:
- move the CREATE INDEXs into the CREATE TABLE to avoid conflicts

chore(migrations): combine pushbox create table and indexes DDL

---

packages/fxa-content-server/app/scripts/models/auth_brokers/base.js

- When a user has TOTP enabled and signs in from the subscription page, it redirects them to settings instead of subscription
- I didn't add an explicit test because this is covered by https://github.com/mozilla/fxa/blob/37f41dbc54c25e189305dbe72b9edcc727be96ed/packages/fxa-content-server/app/tests/spec/views/mixins/signin-mixin.js#L166
- Currently redirects to the subscription page
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6052
To test
1. Create an account and enable TOTP
2. Launch private browser and goto `http://localhost:8080` or product page
3. Click `Sign in`
4. Enter password and 2FA code

fix(totp): Redirect to product page after signing in with 2FA

---

packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js

- We're moving to Stripe automatic tax.
- Adds automatic tax to Paypal checkout when enabled by feature flag.
Closes FXA-5650

feat(auth-server): stripe automatic tax on paypal endpoint

---

.circleci/config.yml
.circleci/test-package.sh
packages/fxa-auth-server/lib/routes/index.js

- We want to exercise tracing code paths in CI to spot potential errors
- Configures CI to turn basic tracing
- Configures a sample rate of 0, so as not execute code paths but not output traces
- Fixes a bug found in the suppress tracing code in fxa shared. Not all arguments were getting propagated.
Closes: FXA-6069
Enabling these tests uncovered at least one defect. See changes in [packages/fxa-auth-server/lib/routes/index.js](https://github.com/mozilla/fxa/pull/14262/files#diff-a4c2724b23c40ac94cedc61b73c4cbdc9ee44bda6b5b873d7bab85badd4d49eb)

task(ci): Activate tracing in CI to uncover potential issues

---

packages/fxa-admin-panel/src/components/AccountSearch/Account/index.test.tsx
packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
packages/fxa-admin-panel/src/components/AccountSearch/index.test.tsx
packages/fxa-admin-panel/src/components/AccountSearch/index.tsx
packages/fxa-admin-server/src/gql/account/account.resolver.spec.ts
packages/fxa-admin-server/src/gql/account/account.resolver.ts

- We want to be able to locate a user by the email they signed up with.
- A user that swapped primary / secondary email, and then deleted the secondary email, could not be found by the admin panel.
- Adds the user's 'sign-up' email to the account section
- Falls back to the accounts.normalized email, if an email cannot be found in the emails table.
Closes: FXA-5866

task(admin-panel): Locate account by sign-up email

---

packages/functional-tests/playwright.config.ts

- Playwright runs with default of 2 workers and completes tests in roughly 9 mins, lets see what happens when increased to 4
- Increases workers to 4 
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6149
Looks like we have a 30 second improvement in https://app.circleci.com/pipelines/github/mozilla/fxa/34838/workflows/e88224e8-4b49-404c-aef3-bb49a40b4467/jobs/377215 vs https://app.circleci.com/pipelines/github/mozilla/fxa/34865/workflows/19d3ed37-c408-4729-b7b9-a60a2c227fc1/jobs/377426. Seems like a win to me 😅

fix(tests): Increase playwright ci worker to 4

---

packages/fxa-content-server/app/scripts/lib/experiment.js
packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/generalized-react-app.js
packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/index.js
packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/generalized-react-app.js
packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/index.js

* The existing Settings React app can only house routes under /settings. We want to create another version of it, which we can progressively add new routes to from the content server. This is a temporary experiment which will be removed after we've successfully and safely rolled out the new React app to users (and before we start adding new major routes, such as reset_password etc)
* Creates a new experiment and checks the experiment status before passing a prop of "showNewReactApp" into the Settings app.
Closes # https://mozilla-hub.atlassian.net/browse/FXA-6061
In `functional/mocha.js` it's choking when it tries to split the test output, and then to trim a part of that output. I dunno!

feat(fxa-content-server): add experiment to wrap new React app

---

packages/fxa-settings/src/lib/auth-errors/auth-errors.ts

* Our new strategy for allowing localization of error messages relies on the (existing) assumption that all auth UI errors are present in the auth-errors object. Since this error was not included in the object, it threw an error when trying to generate a localization ID. We don't want that error to be thrown, and we do want the error to localized if it's visible to users. (See Sentry error [FXA-CONTENT-60F](https://sentry.io/organizations/mozilla/issues/3610017696/?referrer=jira_integration))
* Adds the new error into the dictionary of localized errors.
Closes:  # https://mozilla-hub.atlassian.net/browse/FXA-6054

fix(fxa-settings): add missing error to auth-errors obj

---

.gitignore
packages/fxa-react/lib/test-utils/index.test.tsx
packages/fxa-react/lib/test-utils/index.ts
packages/fxa-react/lib/test-utils/test.ftl
packages/fxa-react/lib/utils.tsx
packages/fxa-settings/.rescriptsrc.js
packages/fxa-settings/Gruntfile.js
packages/fxa-settings/package.json
packages/fxa-settings/pm2.config.js
packages/fxa-settings/src/components/BentoMenu/index.test.tsx
packages/fxa-settings/src/components/BentoMenu/index.tsx
packages/fxa-settings/src/components/Profile/index.test.tsx
packages/fxa-settings/src/components/Profile/index.tsx
packages/fxa-settings/src/components/Security/index.test.tsx
packages/fxa-settings/src/components/Security/index.tsx
packages/fxa-settings/src/setupTests.tsx
yarn.lock

Because:
* We want better l10n testing across the codebase
This commit:
* Creates a Localized wrapper to use in place of Localized that requires children (fallback text)
* Adds a mock for the Localized wrapper in Jest's setupTests to avoid copying and pasting this into every test file
* Creates test-utils in `fxa-react` and exports functions to use for testing the mock that all IDs exist in the 'en' bundle, that fallback text matches the message in the bundle, and that the message doesn't contain straight apostrophes or quotes
* Adds tests and a test.ftl file for the test-utils l10n functions to ensure they test what we think they do
* Moves concatenating settings.ftl out of webpack and into grunt due to 1) needing a test version of settings.ftl at a different path, else tests may fail in …

feat(l10n): Create Localized wrapper and React l10n test setup

---

packages/fxa-auth-server/lib/payments/stripe-formatter.ts
packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe-formatter.js
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/components/PlanDetails/index.stories.tsx
packages/fxa-payments-server/src/components/PlanDetails/index.test.tsx
packages/fxa-payments-server/src/components/PlanDetails/index.tsx
packages/fxa-payments-server/src/routes/Checkout/index.tsx
packages/fxa-payments-server/src/store/selectors.ts
packages/fxa-payments-server/src/store/sequences.ts
packages/fxa-shared/dto/auth/payments/invoice.ts

Because:
* we want to display the amount of tax charged or included if applicable
This commit:
* updates an api endpoint to fetch automatic tax amount and displays it on the plan details component
Closes #FXA-5539, #FXA-5651

feat(payments): display Tax Amount If Applicable

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/components/PaymentErrorView/index.scss
packages/fxa-payments-server/src/components/PaymentErrorView/index.stories.tsx
packages/fxa-payments-server/src/components/PaymentErrorView/index.tsx
packages/fxa-payments-server/src/components/SubscriptionTitle/index.stories.tsx
packages/fxa-payments-server/src/components/SubscriptionTitle/index.tsx
packages/fxa-payments-server/src/lib/apiClient.test.ts
packages/fxa-payments-server/src/lib/apiClient.ts
packages/fxa-payments-server/src/lib/errors.ts
packages/fxa-payments-server/src/routes/Product/IapRoadblock/index.stories.tsx
packages/fxa-payments-server/src/routes/Product/IapRoadblock/index.test.tsx
packages/fxa-payments-server/src/routes/Product/IapRoadblock/index.tsx
packages/fxa-payments-server/src/routes/Product/index.test.tsx
packages/fxa-payments-server/src/routes/Product/index.tsx

- With the current setup, users either create a second subscription or don't know why their upgrade didn't go through
- We need clearer error messaging for all of our iap subscription upgrade roadblock scenarios
- Stops the upgrade and sends user to error page
- Provides appropriate error message detailing the specific issue
- Provides a link to our support team for users who want help or more information
Closes: FXA-5480

fix(subscriptions): stop upgrade of IAP subscriptions on same product set

---

packages/fxa-admin-panel/README.md

- With the addition of subscriptions, admin-panel now requires a stripe test key to be added to admin-server, but this change is not documented in admin-panel docs.
- Running the admin-panel without a valid stripe test key results in an error when retrieving account details.
- Add instructions in the admin-panel readme about adding a stripe test key or disabling feature flags in the admin-server
Closes: #FXA-6154

docs(admin-panel): Add instructions to set up stripe test key

---

packages/fxa-payments-server/src/routes/Checkout/index.tsx

- the style for newsletter error alerts were not being applied to `NewsletterErrorAlert`
- corrects the className that applies the style for newsletter error alerts to `NewsletterErrorAlert`

fix(payments-server): Revise className for NewsletterErrorAlertBar

---

packages/functional-tests/README.md
packages/functional-tests/lib/ua-strings.ts
packages/functional-tests/pages/connectAnotherDevice.ts
packages/functional-tests/pages/forceAuth/fxDesktopV3.ts
packages/functional-tests/pages/forceAuth/index.ts
packages/functional-tests/pages/index.ts
packages/functional-tests/pages/layout.ts
packages/functional-tests/pages/login.ts
packages/functional-tests/pages/signinTokenCode.ts
packages/functional-tests/playwright.config.ts
packages/functional-tests/tests/signin/fxDesktopV3ForceAuth.spec.ts
packages/fxa-content-server/tests/functional.js

Because:
- we want convert the desktop Sync V3 force auth tests from the Intern to Playwright
This commit:
- add Playwright tests for desktop Sync V3 force auth flows

test(force auth): add functional tests for Sync V3 force auth

---

packages/fxa-auth-server/test/local/payments/iap/apple-app-store/subscription-purchase.js
packages/fxa-shared/payments/iap/apple-app-store/subscription-purchase.ts

Because:
* The Data Science/Engineering team has requested the [purchaseDate](https://developer.apple.com/documentation/appstoreservernotifications/purchasedate) field for analysis purposes, and it wasn't included in the original implementation.
This commit:
* Includes the purchaseDate field.
Closes #FXA-6109

chore(auth): add purchaseDate to AppStoreSubscriptionPurchase

---

packages/fxa-payments-server/src/lib/mock-data.tsx
packages/fxa-payments-server/src/routes/Checkout/index.test.tsx
packages/fxa-payments-server/src/routes/Checkout/index.tsx

Because:
* we want to show more specific error information
This commit:
* checks the properties of the error object to pass in the right object, error vs error.error
Closes #FXA-4051

fix(payments): detailed Error Message Not Displayed

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/index.txt
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/senders/emails.ts

- The wrong amount is displayed on a subscription change between two prices with the same interval, since an invoice isn't immediately generated by Stripe.
- Cancellation emails do not inform the customer when they still have an oustanding amount at the end of their subscription.
- Checks if there are any pending invoice items, and if there are, retrieves the upcoming invoice.
- For upgrade emails, the upcoming invoice is used to get the proration amounts only.
- For cancellation emails the upcoming invoice is used in favor of the currently latest invoice.
Closes: #FXA-6170

fix(subscriptions): fix amounts for same interval

---

packages/fxa-payments-server/src/routes/Product/IapRoadblock/index.stories.tsx
packages/fxa-payments-server/src/routes/Product/IapRoadblock/index.test.tsx
packages/fxa-payments-server/src/routes/Product/IapRoadblock/index.tsx
packages/fxa-payments-server/src/routes/Product/index.tsx

- Previous copy said you were already subscribed to the new plan (different from current but on same product set)
- Updates error copy to show the current plan name and not the new one
- Updates tests
- Updates stories
- Fixes some other nits/DRY/cleanups that were found while reviewing #14118 
Closes: FXA-5480

fix(subscriptions): fix copy in IAP roadblock for subscription upgrades

---

packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
packages/fxa-admin-panel/src/styles/tailwind.css

- We want to fix a tailwind lint error (tailwindcss/enforces-shorthand) caused by redundant (or conflicting) classes being applied to the same component (e.g., mt-0 my-0 mb-1 applied to the same class or element)
- Remove my-0 where mt and mb are explicitely set to different values
- Remove redundant use of text-lg where account-header class is also applied (already includes text-lg)
Closes: #FXA-5621
CSS updates applied to account headers in fxa-admin-panel, account search
`yarn test:frontend` tested and passed locally

fix(fxa-admin-panel): Update CSS in Account Search to remove conflicting classes

---

packages/fxa-payments-server/server/jest.config.js

```sh
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------
Test Suites: 7 passed, 7 total
Tests:       44 passed, 44 total
Snapshots:   0 total
Time:        3.62 s, estimated 10 s
Ran all test suites.
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
```
```sh
-------------------------|---------|----------|---------|---------|------------------------------------------------------------
File                     | % Stmts …
```

chore(tests): Remove coveragePathIgnorePatterns from fxa-payments-server

---

packages/functional-tests/lib/targets/remote.ts

- Functional tests are failing with error `TypeError: Found non-callable @@iterator`.
- Options added to createAccount should be passed to auth.signUp.
- Assign options parameter to auth.signUp.

fix(tests): assign options to auth signUp

---

.circleci/config.yml

`Updating functional tests to FF 102.4.0esr as ESR 91 is not supported anymore`
`Will update the FF to ESR 102.4.0`
Closes: #[FXA-4579](https://mozilla-hub.atlassian.net/browse/FXA-4579)

test(functional): update the FF ESR and geckodriver version to latest

---

packages/fxa-payments-server/src/components/PaymentConfirmation/index.scss
packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx
packages/fxa-payments-server/src/components/PaymentErrorView/index.scss
packages/fxa-payments-server/src/components/PaymentErrorView/index.tsx
packages/fxa-payments-server/src/components/PaymentProcessing/index.tsx
packages/fxa-payments-server/src/components/PlanDetails/index.tsx
packages/fxa-payments-server/src/components/TermsAndPrivacy/index.tsx
packages/fxa-payments-server/src/routes/Checkout/index.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
packages/fxa-payments-server/src/styles/_mixins.scss
packages/fxa-payments-server/src/styles/tailwind.css

- the footers were not consistent and also need to be updated to use Tailwind in the following components:
- Checkout
- PaymentConfirmation
- PaymentErrorView
- PaymentProcessing
- SubscriptionCreate
- SubscriptionUpgrade
- provides the footers with consistent styling
Closes: [FXA-5678](https://mozilla-hub.atlassian.net/browse/FXA-5678)
Checkout
PaymentConfirmation
PaymentErrorView
PaymentProcessing
SubscriptionCreate
SubscriptionUpgrade
`PlanDetails` - `footer` class was not defined/applied to this component and therefore was removed - no display changes.

refactor(payments-server): Convert footers to utilize Tailwind

---

packages/fxa-auth-server/lib/devices.js
packages/fxa-auth-server/lib/pushbox/db.ts
packages/fxa-auth-server/lib/pushbox/index.ts
packages/fxa-auth-server/lib/routes/index.js
packages/fxa-auth-server/test/local/devices.js
packages/fxa-auth-server/test/local/pushbox.js
packages/fxa-auth-server/test/mocks.js
packages/fxa-auth-server/test/remote/pushbox/db.ts

Because:
- we want to delete a device's records from the Pushbox DB when the device is disconnected
This commit:
- add a Pushbox call to the device's `destroy` function to delete the records from the Pushbox DB

feat(pushbox): delete a device's records on device destroy

---

packages/fxa-auth-server/package.json
packages/fxa-content-server/package.json
packages/fxa-react/package.json
packages/fxa-settings/package.json
yarn.lock

Reverts mozilla/fxa#14372
This seems to be breaking out Storybook builds. Seems after this bump, storybook builds fail with a bunch of console errors.

Revert "chore(deps): bump babel-loader from 8.2.2 to 9.0.0"

---

packages/fxa-auth-server/lib/pushbox/db.ts
packages/fxa-auth-server/lib/pushbox/index.ts
packages/fxa-auth-server/lib/routes/account.ts
packages/fxa-auth-server/lib/routes/index.js
packages/fxa-auth-server/test/local/pushbox.js
packages/fxa-auth-server/test/local/routes/account.js
packages/fxa-auth-server/test/remote/pushbox/db.ts

Because:
- we should delete the remaining pushbox records for an account when the account is deleted
This commit:
- delete the pushbox db records of an account

feat(pushbox): delete all db records on account delete

---

packages/fxa-admin-server/src/subscriptions/subscriptions.service.spec.ts
packages/fxa-admin-server/src/subscriptions/subscriptions.service.ts
packages/fxa-auth-server/test/local/payments/stripe-firestore.js
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-shared/payments/stripe-firestore.ts
packages/fxa-shared/payments/stripe.ts

- Support needs to see all of a customer's potential subscriptions, not just active ones.
- Adds an optional status filter to StripeFirestore.retrieveCustomerSubscriptions
- Applies a filter that includes all subscription statuses in the admin server’s SubscriptionsService and ensures this filter is passed down the call chain.
Closes: FXA-5594
The following stripe subscription statuses, which should be all subscriptions, are now visible in the admin panel:
- active
- canceled
- incomplete
- incomplete_expired
- past_due
- trialing
- unpaid

task(admin-panel): Add ability to see canceled/inactive subscriptions

---

packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
packages/fxa-admin-panel/src/components/AccountSearch/Account/mocks.tsx
packages/fxa-admin-panel/src/components/AccountSearch/index.test.tsx
packages/fxa-admin-panel/src/components/AccountSearch/index.tsx
packages/fxa-admin-server/src/app.module.ts
packages/fxa-admin-server/src/config/index.ts
packages/fxa-admin-server/src/event-logging/event-logging.service.ts
packages/fxa-admin-server/src/gql/account/account.resolver.spec.ts
packages/fxa-admin-server/src/gql/account/account.resolver.ts
packages/fxa-admin-server/src/gql/gql.module.ts
packages/fxa-admin-server/src/graphql.ts
packages/fxa-admin-server/src/newsletters/basket.service.spec.ts
packages/fxa-admin-server/src/newsletters/basket.service.ts
packages/fxa-admin-server/src/newsletters/newsletters.module.ts
packages/fxa-admin-server/src/schema.gql
packages/fxa-shared/guards/AdminPanelGuard.ts

- We want support to be able to unsubscribe users from newsletters
- Adds newsletter module
- Adds service for basket api
- Adds graphql mutation for unsubscribing users
- Adds button to admin panel that unsubscribed users
Closes: FXA-5358
Manually testing this requires an api key for basket. This will need to be added to a secrets.json file in the admin server.

task(admin-panel): Unsubcribe users from newsletters

---

packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js

Because:
* we don't want to use 127.0.0.1 to try to look up tax locations in stripe
This commit:
* uses the forwarded IP address from the client
Closes #

fix(tax): wrong Request IP Address Sent to Stripe

---

packages/fxa-auth-server/lib/payments/stripe-formatter.ts
packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ManagementPanel.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx
packages/fxa-shared/dto/auth/payments/invoice.ts

Because:
* we want to dispaly tax information on subsequent invoice preview which is used on the subscription management page
This commit:
* updates the preview-subsequent endpoint to include stripe tax when enabled and updates the manage subscription page to use the total from the subsequent invoice when able to
Closes #FXA-6192

feat(tax): update Subsequent Invoice Endpoint to Use Stripe Tax

---

_dev/pm2/create-docker-net.sh
_dev/pm2/start.sh
_scripts/configs/otel-collector-config.yaml
_scripts/firestore.sh
_scripts/jaeger.sh
_scripts/memcached.sh
_scripts/otel-collector.sh
_scripts/pushbox-db.sh
_scripts/redis.sh
_scripts/syncserver.sh

- When starting tracing with open telemetry the network name would sometimes collide and result in error.
- Sets an 'fxa' network name
- Applies this network to services
- Allows services to communicate by their names

task(shared): Fix docker network error with otel

---

packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/components/Settings/index.test.tsx
packages/fxa-settings/src/components/Settings/index.tsx
packages/fxa-settings/src/index.tsx
packages/fxa-settings/src/lib/metrics.ts
packages/fxa-settings/src/models/FlowContext.ts
packages/fxa-settings/src/models/mocks.tsx
packages/fxa-settings/src/react-app-env.d.ts

Because:
* We should only need flowQueryParams in a few components and since using Context isn't free, we can just pass it directly
This commit:
* Refactors out the new Context provider and mocks in favor of passing these values directly into the components that need them
* Moves AppErrorBoundary up the tree
* Moves a couple types out of react-app-env.d.ts
Closes FXA-6163

refactor(context): Remove new Context for flow query params

---

packages/fxa-auth-server/.eslintrc.json
packages/fxa-auth-server/scripts/create-mock-iap-subscriptions/mock-iap-subscription-manager.ts
packages/fxa-auth-server/scripts/paypal-refund-fixer.ts

* Self-absolute imports currently break deploy since we build with TSC and run with JS which no longer has baseUrl to help out with resolution.
* Bans self-absolute imports with the no-restricted-imports rule. The hope is that we'll move to esbuild soon or if nothing else, implement this rule in other packages when they actually solve their lint issues.
Closes FXA-6138

chore(auth-server): ban self-absolute imports

---

packages/fxa-auth-server/lib/payments/paypal/helper.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
packages/fxa-auth-server/test/local/payments/paypal.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js

- PayPalClientError reports error due to billing agreement being cancelled
- captures error in `updateStripeNameFromBA` if billing agreement was cancelled
Closes: [FXA-5936](https://mozilla-hub.atlassian.net/browse/FXA-5936)

fix(auth-server): Capture error in updateStripeNameFromBA if billing agreement was cancelled

---

packages/fxa-auth-server/docs/swagger/subscriptions-api.ts

- `/oauth/subscriptions/plans` is an open endpoint, but the documentation noted it needed authentication.
- Removes comment in `/oauth/subscriptions/plans` about needing authentication
- Other updates:
- Fixed descriptions as it should be the path for:
- `OAUTH_SUBSCRIPTIONS_IAP_APP_STORE_TRANSACTION_POST`
- `OAUTH_SUBSCRIPTIONS_IAP_APP_STORE_NOTIFICATION_POST`
- Adds comment about needing authentication for the following endpoints:
1. [`/oauth/subscriptions/clients`](https://api.accounts.firefox.com/v1/oauth/subscriptions/clients) <-- link
2. [`/oauth/subscriptions/invoice/preview-subsequent`](https://api.accounts.firefox.com/v1/oauth/subscriptions/invoice/preview-subsequent) <-- link
Closes: [FXA-6169](https://mozilla-hub.atlassian.net/browse/FXA-6169)
_Put an `x` in the boxes that …

docs(auth): Fix doc - open endpoint was marked as needing authentication

---

packages/fxa-auth-server/scripts/audit-tokens.ts
packages/fxa-auth-server/test/scripts/audit-tokens.js
packages/fxa-auth-server/test/scripts/db-helpers/index.js

- We want to spot check db state
- We want to be able to measure changes in db state
- Adds script that can track of row counts, ages of rows, and orphaned rows
- Can be used to generate raw sql script
- Can be used as a cron job to periodically emit statistics.
Closes: FXA-6156
There is an option to control how many rows are processed when generating metrics. This was added to reduce the total overhead of the queries. Row count audits use internal sql table stats and are not affected by this. However, age audits and orphaned row audits are both impacted by this argument. Since the IDs on our tables are random, it seems as though we should get a random distribution by simply limiting the number of rows in the query. Given that the number of rows …

task(auth): Audit db state around tokens

---

packages/fxa-auth-server/lib/routes/devices-and-sessions.js
packages/fxa-auth-server/test/local/routes/devices-and-sessions.js

- The Id of a refresh token is called `tokenId` when retrieved from the oauth db and redis store, however, in here there was a bug where we used a `refreshTokenId`, which is the name in the device records not the tokens themselves.
- The above caused us to be unable to match any devices with their refreshTokens, therefore we were also unable to correctly keep the lastAccessTime up to date as we return that to users.
- Downstream this causes the send tab list to display devices with incorrect last access times, and prevents us from being able to filter on that list properly
- Uses the correct name of the id :) It's a simple change
Closes: # (issue number) TODO: @tarikeshaq to find issue
- I should go back and add tests for this if it's feasible
Please …

Fixes incorrect name for the id of refreshToken

---

packages/fxa-auth-server/lib/routes/devices-and-sessions.js
packages/fxa-auth-server/test/local/routes/devices-and-sessions.js

running CI for https://github.com/mozilla/fxa/pull/14433

[CI ONLY] Fixes incorrect name for the id of refreshToken

---

packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js

* There was a typo in the original implementation that caused automatic tax not be applied to any subscription created with automatic tax enabled.
* Fixes the typo.
Closes FXA-6277

fix(auth-server): rename automatic_tax to automaticTax

---

packages/fxa-auth-server/scripts/audit-tokens.ts
packages/fxa-auth-server/test/scripts/audit-tokens.js

- In prod the fxa_oauth and fxa databases are in separate instances.
- Queries conducting audits across fxa and fxa_oauth databases therefore wouldn't work.
- Removes fxa_oauth audits for now
This is a quick follow up PR that resulted from a discussion with SRE about the feasibility of some of these audits.

task(auth): Only audit fxa db for now

---

packages/fxa-settings/src/components/Settings/UnitRow/index.tsx

* Currently, very long words (such as in German) are following standard rendering behavior in breaking out past their element containers in the Security panel of the Settings page. This is considered a preferred default because it prevents data loss (for example, from hiding the overflow.) It is undesirable in our situation because the words are currently overlapping with, and obscuring, other elements.
* Applies "break-all", the tailwind class which corresponds to "word-break: break-all", to the h3 label in all UnitRow components. This means that if a label (even a single-word label) exceeds the horizontal bounds of its container, it will wrap, keeping all text within the element visible and non-overlapping.
Closes #https://mozilla-hub.atlassian.net/browse/FXA-6089
_Put an `x` in the …

fix(fxa-settings): wrap overflowing words to prevent overlapping text

---

packages/fxa-payments-server/src/en.ftl
packages/fxa-react/components/LoadingSpinner/index.tsx
packages/fxa-settings/src/components/Settings/index.test.tsx

Because:
* According to mozilla l10n guidelines strings should use a unicode ellipsis (…) instead of three periods (...)
This commit:
* Fixes a missing ellipsis in fxa-payments-server/src/en.ftl
---
Cherry-picked from #14446 since Bryan (l10n) cannot approve his own PR

chore(l10n): fix ellipsis

---

package.json
yarn.lock

Because:
- older versions of moment are causing security alerts
This commit:
- resolve moment 2.x to a >= a patched version

chore(deps): resolve moment to a patched version

---

packages/fxa-admin-server/src/subscriptions/stripe.service.spec.ts
packages/fxa-admin-server/src/subscriptions/stripe.service.ts

Because:
* Mappings were failing due to the case of the identifiers.
This commit:
* Ensures the comparisons are case-insensitive.
Closes #FXA-6224

fix(admin-server): ignore case for IAP to Stripe plan mappings

---

packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ManagementPanel.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx

Because:
* we want to reflect the accurate amount a user will be charged for reactivation
This commit:
* makes sure we use the amount from preview invoice in the reactivation modal
Closes #FXA-6258

fix(payments): subscription Reactivation Showing Incorrect Amount

---

.github/workflows/pull-legal-docs.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

packages/fxa-auth-server/docs/overview.md

Because:
* We didn't have docs for device_id
This commit:
* Adds them

docs(metrics): added details for device_id

---

package.json
yarn.lock

Because:
- some older versions of protobufjs 6.x are causing a security alert
This issue:
- resolve protobufjs 6.x to a fixed version or newer

chore(dep): resolve protobufjs to a newer version

---

package.json
yarn.lock

Because:
- older versions of underscore is causing security alerts
This commit:
- resolve underscore to patched versions

chore(deps): resolve underscore to newer versions

---

package.json
yarn.lock

Because:
- security alerts
This commit:
- resolve node-forge to >= the min fixed version

chore(deps): resolve node-forge to >=1.3.0

---

yarn.lock

Because:
- security alerts
This commit:
- force ansi-regex 3.x and 4.x to respective fixed versions

chore(deps): resolve ansi-regex 3.x and 4.x to newer versions

---

package.json
yarn.lock

Because:
- elliptic is in the browserid-verifier's dependency tree and it's causing security warnings
This commit:
- resolve elliptic to >= a patched version

chore(deps): update elliptic

---

packages/123done/oauth.js
packages/123done/static/index.html
packages/123done/static/js/123done.js
packages/functional-tests/tests/settings/totp.spec.ts
packages/fxa-auth-server/lib/oauth/grant.js
packages/fxa-auth-server/lib/routes/oauth/authorization.js
packages/fxa-auth-server/test/oauth/grant.js
packages/fxa-content-server/app/scripts/lib/oauth-prompt.ts
packages/fxa-content-server/app/scripts/lib/validate.js
packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js
packages/fxa-content-server/app/scripts/models/reliers/oauth.js
packages/fxa-content-server/app/scripts/views/mixins/cached-credentials-mixin.js
packages/fxa-content-server/app/tests/spec/models/reliers/oauth.js
packages/fxa-content-server/app/tests/spec/views/mixins/cached-credentials-mixin.js
packages/fxa-content-server/docs/query-params.md

- RPs need to be able to request a user reauthenticate
- RPs should be able to verify that a user did reauthenticate via the `auth_time` claim
- Adds support for `prompt=login`
- The spec says that `auth_time` is OPTIONAL and only required when `max_age` is set, however this update always returns it in the id token
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6272
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6273
To test, create and account and sign in. Then goto 123Done and click `Sign In (prompt=login)`. You should be prompted for your password.

feat(oauth): Add support for `prompt=login` and return the `auth_time` in id token

---

packages/fxa-payments-server/l10n.toml

- Using a config file is not beneficial for the FxA project which uses a separate l10n repo. Fluent configuration files are useful when the same repository needs to support different locales for different files (e.g. https://github.com/mozilla-l10n/android-l10n), or complex paths, but this is not the case for FxA.
- Removes the l10n configuration file in fxa-payments-server
Closes: #FXA-6002

refactor(l10n): Remove l10n configuration file in fxa-payments-server

---

packages/fxa-payments-server/Gruntfile.js
packages/fxa-react/components/Footer/en.ftl
packages/fxa-react/components/Head/en.ftl
packages/fxa-settings/Gruntfile.js
packages/fxa-settings/src/components/en.ftl

- L10n strings used in fxa-react components were stored in other packages (e.g., fxa-settings) and we want to bring them closer to the component where they are used for easier maintenance.
- Create an en.ftl file for each fxa-react component with exisiting l10n
- Move the the FTL IDs and messages contained in other packages to these new files
- Update fxa-settings' merge task to concat all fxa-react FTL files into settings.ftl
- Update fxa-payments-server's merge task to concat all fxa-react FTl files into payments.ftl
Closes: #FXA-5997

refactor(fxa-react): Create FTL files in fxa-react and concat to settings, payments

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js

Because:
* we do not want to use the current ipAddress/location of a customer who may be in a different locale or using a VPN when they are trying to subscribe to another product
This commit:
* changes the preview invoice endpoint to optionally/try to use the request credentials to load the customer from stripe, and then tries to use what IP address we may have recorded for them to display tax information for the new subscription
Closes #FXA-6278

fix(auth): use Recorded IP of Signed In Customer For Tax On Preview Invoice

---

packages/fxa-payments-server/src/components/AppLayout/index.tsx
packages/fxa-payments-server/src/index.scss

- Minor regression caused by #14500 where a class was not removed in payments AppLayout template
- Removes class `card` from payments `AppLayout` template
- Removes unnecessary selector in payments `index.scss` file
Closes: FXA-6316

fix(payments): remove class causing layout issues in Payment pages

---

packages/fxa-react/styles/ctas.css
packages/fxa-settings/src/components/Settings/GetDataTrio/index.tsx

- The focus style applied to caution CTA and GetDataTrio buttons (black dotted outline) did not match the style used for other buttons (solid blue). The discrepancy may have become more obvious with the upgrade to Tailwind v3. We would like all button focus styles to be consistent.
- Replace the focus and active styles used for fxa-settings' caution cta and GetDataTrio buttons.
Closes: #FXA-5507
Before:
After:

feat(fxa-settings): Update focus border on CTA and GetDataTrio

---

packages/fxa-payments-server/src/components/AppLayout/index.scss
packages/fxa-payments-server/src/components/CouponForm/index.tsx
packages/fxa-payments-server/src/components/NewUserEmailForm/index.scss
packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
packages/fxa-payments-server/src/components/PaymentProviderDetails/index.scss
packages/fxa-payments-server/src/components/fields/index.tsx
packages/fxa-payments-server/src/index.scss
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.scss
packages/fxa-payments-server/src/routes/Subscriptions/index.scss
packages/fxa-payments-server/src/styles/tailwind.css
packages/fxa-settings/src/components/Settings/ConnectAnotherDevicePromo/index.tsx
packages/fxa-settings/src/components/Settings/ConnectedServices/index.tsx
packages/fxa-settings/src/components/Settings/Nav/index.tsx
packages/fxa-settings/src/styles/switch.css

- Localizable components must support both LTR and RTL text-directions. Using text-start will align text based on the layout direction(to the left for LTR, to the right for RTL) and eliminates the need to include specific tailwind properties to support LTR/RTL.
- Replace instances of text-left and text-right with either text-start or text-end to maintain intended alignment as tested in Storybook.
- Where component styling included 'ltr:text-left rtl:text-right', replace with only 'text-start'.
- Apply changes to localizable components only in fxa-payments-server and fxa-settings.
Closes #FXA-5738

fix(tailwind): Update settings and payment to improve LTR/RTL support

---

packages/fxa-payments-server/src/en.ftl
packages/fxa-react/components/AppErrorDialog/en.ftl
packages/fxa-react/components/AppErrorDialog/index.tsx
packages/fxa-react/components/LinkExternal/en.ftl
packages/fxa-react/components/LinkExternal/index.tsx
packages/fxa-react/components/LoadingSpinner/en.ftl
packages/fxa-react/components/LogoLockup/en.ftl
packages/fxa-react/components/LogoLockup/index.tsx

- All messages served to the user should be localized, including screen reader messages. Fxa-react components were partially localized, but some messages were missed.
- Add l10n to AppErrorDialog, LinkExternal, LoadingSpinner and LogoLockup for all messages, including alt text, aria labels and screen-reader only messages.
- Create en.ftl for each component, when needed.
Closes: #FXA-5998

feat(fxa-react): Add missing l10n to fxa-react

---

packages/functional-tests/pages/login.ts
packages/functional-tests/tests/settings/password.spec.ts

`As part of the playwright test migration, the [password strength tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/password_strength.js) have been rewritten in this PR.`
`contains the [password strength tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/password_strength.js)`
Closes: #[FXA-5898](https://mozilla-hub.atlassian.net/browse/FXA-5898)

test(functional): rewrite password tests using playwright

---

.circleci/config.yml
_dev/docker/ci/Dockerfile

- We are in the process of experimenting with CI pipeline optimizations
- Creates a new docker image that can be used in other CI jobs.
- This base image comes pre-populated with node_modules, dist folders, and l10n repos.
Closes: FXA-660
There will be follow up PRs to apply this across image to our CI jobs and see if there any performance gains.

task(ci): Create docker image for CI

---

packages/fxa-auth-server/bin/key_server.js
packages/fxa-shared/tracing/node-tracing.ts

- During a previous refactor the ability to add traceIds to logs broke.
- Uses TracingProvider.getCurrent() instead of trying to directly access TracingProvider.nodeTracing which is private.

bug(auth): Fix missing traceids in logs

---

packages/fxa-payments-server/src/components/PaymentForm/index.stories.tsx
packages/fxa-react/components/LoadingSpinner/index.stories.tsx
packages/fxa-react/configs/storybooks.js

- As part of tailwind conversion we are updating storybook as well.
- Updates PaymentForm and LoadingSpinner storybooks.
- Update webpack config not to remove viewbox from SVGs.
Closes: #FXA-6302

feat(payments): update PaymentForm storybook

---

docs/adr/0033-content-server-upgrade-to-react.md

* As we plan work for migrating the remaining content-server routes to React, we need to nail down decisions regarding gql usage, where to house the new routes, and how to plan for an incremental rollout
* Adds an ADR summarizing the decision processes
Co-authored-by: @LZoog 
Closes #https://mozilla-hub.atlassian.net/browse/FXA-6271

docs(adr): upgrade content server to react adr

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/en.ftl
packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/index.mjml
packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/index.txt
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
packages/fxa-auth-server/test/local/senders/emails.ts

- When a subscription is cancelled immediately, an failed payments email is sent to the customer, even when no failed payments ocurred.
- Update the customer.subscription.deletion event handler, to send subscriptionCancellation emails when a subscription is cancelled immediately
- Update subscriptionCancellation email copy to support immediate cancellation.
Closes: #FXA-6165

feat(subscription): immediate sub cancel email

---

.circleci/config.yml
packages/functional-tests/scripts/test-ci.sh

- Added `parallelism` var to the `circleci/config.yml` for playwright test job.
- Made use of CircleCi Split functionality and used it in the `test-ci.sh` file.
- Will now run 5 machines parallelly and split the tests running in each machine. It improved the run time by 1min in most cases and 2mins in some. Tried running the playwright test job thrice and each time it took around 8mins to finish.
Closes: [FXA-6321](https://mozilla-hub.atlassian.net/browse/FXA-6321)

test(functional): add parallelism and circleci split to functional tests

---

packages/fxa-content-server/app/scripts/lib/metrics.js
packages/fxa-content-server/app/tests/spec/lib/metrics.js

- FxiOS appears to not always emit metrics properly when using beacon api
- Uses `visibilitychange` and `pagehide`
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6259
I'm not sure if this will 100% fix the issue but it won't hurt anything if the metrics were correctly flushed before.

fix(metrics): Use `visibilitychange` and `pagehide` to emit metrics in iOS

---

_scripts/clone-l10n.sh

Because:
- `realpath` is now in macOS but it does not have a `-m` option
This commit:
- add minimal extra check for the `-m`

chore(l10n): fix clone script for masOS post-Ventura

---

.circleci/config.yml

- We want to speed up build times
- Adds docker_layer_caching directive
- Makes sure buildkit is enabled where possible

task(ci): Enable docker layer caching

---

packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js

Because:
* We should always check if there's a tax id for the currency used and add it.
This commit:
* Updates the tax id code to always check if a tax id is needed for the current currency.
Closes FXA-6386.

feat: always run tax id code

---

.github/workflows/close-stale-prs.yml

Because:
- people can always re-open their PRs
This commit:
- use a GH action to auto-close "stale" PRs

chore(GH Actions): auto-close stale PRs

---

packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts

- When a customer, who uses PayPal as their payment method and who's tax location could be determined by Stripe from their IP, subscribes for their 2nd subscription, the `subscriptions/new-paypal` endpoint returns with a 500 error code.
- After the 500 error code, in Sentry, an issue is shown with message `ValidationError: "sourceCountry" is required`.
- First tries to retrieve the sourceCountry from the tax location, before using the customer address.
Closes: #FXA-6378

fix(subscription): return sourceCountry for valid tax location status

---

packages/fxa-payments-server/src/App.tsx
packages/fxa-payments-server/src/components/CouponForm/index.test.tsx
packages/fxa-payments-server/src/components/CouponForm/index.tsx
packages/fxa-payments-server/src/components/PaymentErrorView/index.tsx
packages/fxa-payments-server/src/lib/errors.test.tsx
packages/fxa-payments-server/src/lib/errors.ts
packages/fxa-payments-server/src/routes/Checkout/index.test.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx

- We want to ensure users know what the error is by providing clear fallback text instead of error ids, in the event that localization fails
- Adds a dictionary for fallback error messages in `errors.ts`.
- Adds a function in `errors.ts` that takes in a fluent id and returns corresponding text from aforementioned dictionary. Returns basic error message if id is undefined or not in dictionary.
- Updates templates that use the id with the text returned from the aforementioned function.
- Updates and includes some new tests
Closes: #13045
As per comment threads below, also updates variable and function names to remove confusion as to whether they return the error id or message.

fix(l10n): add fallback text for payment and subscription errors

---

packages/fxa-settings/src/components/Settings/ConnectedServices/Service.tsx
packages/fxa-settings/src/components/Settings/ConnectedServices/index.test.tsx

Because:
* This link is broken
This commit:
* Updates to the correct link
Closes https://bugzilla.mozilla.org/show_bug.cgi?id=1800568

fix(settings): fix broken link

---

packages/fxa-payments-server/src/components/SubscriptionTitle/index.tsx
packages/fxa-payments-server/src/styles/tailwind.css
packages/fxa-react/configs/tailwind.js
packages/fxa-settings/src/components/Settings/BentoMenu/index.tsx

- Tailwind v3 provides more classes by default, so many custom variations included in our Tailwind config are no longer needed.
- Tailwind v3 enables JIT engine by default, and purges all unused utilities from the css build. While this reduces file size, it also becomes difficult to debug styling with browser dev tools.
- Removes custom variations in fxa-react's tailwind.js when they are included by default in Tailwind v3.
- Removes custom variations that are no longer in use in fxa packages (zIndex, backgroundOpacity, outline-dotted-black)
- Tested build-css to ensure output css compiles with no errors.
- Does not remove fontSize definitions even though provided by Tailwind v3, as explicit declaration is currently needed for fxa-settings's design guide.
- Safelist all tailwind patterns …

feat(tailwind): Remove custom Tailwind variations provided by v3

---

packages/fxa-payments-server/src/components/SubscriptionTitle/index.tsx
packages/fxa-payments-server/src/styles/tailwind.css
packages/fxa-react/configs/tailwind.js
packages/fxa-settings/src/components/Settings/BentoMenu/index.tsx

Checking CI tests...
---
Because:
- Tailwind v3 provides more classes by default, so many custom variations included in our Tailwind config are no longer needed.
- Tailwind v3 enables JIT engine by default, and purges all unused utilites from the css build. While this reduces file size, it also becomes difficult to debug styling with browser dev tools.
This commit:
- Removes custom variations in fxa-react's tailwind.js when they are included by default in Tailwind v3.
- Removes custom variations that are no longer in use in fxa packages.
- Updates bento menu component to use default TW inset class.
- Tested build-css to ensure output css compiles with no errors.
- Does not remove fontSize definitions even though provided by Tailwind v3, as explicit declaration is currently needed for …

[DO NOT MERGE] feat(tailwind): Update Tailwind config for Tailwind v3

---

packages/functional-tests/pages/products/index.ts
packages/functional-tests/pages/settings/avatar.ts
packages/functional-tests/pages/settings/components/dataTrio.ts
packages/functional-tests/pages/settings/index.ts
packages/functional-tests/pages/settings/layout.ts
packages/fxa-auth-client/lib/client.ts
packages/fxa-auth-server/test/mail_helper.js
packages/fxa-graphql-api/src/decorators.ts
packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
packages/fxa-graphql-api/src/gql/account.resolver.ts
packages/fxa-graphql-api/src/gql/dto/input/index.ts
packages/fxa-graphql-api/src/gql/dto/input/password-forgot.ts
packages/fxa-graphql-api/src/gql/dto/payload/index.ts
packages/fxa-graphql-api/src/gql/dto/payload/password-forgot.ts
packages/fxa-settings/src/lib/metrics.ts

- We need a way for a user to initate the the password forgot flow from the gql-api
- Adds an account resolver that can be used to reset a users password
- `passwordForgotSendCode` sends an email password reset link (password forgot token and code are in url params of link
- `passwordForgotVerifyCode` uses the password forgot token and code and returns account reset token
- `passwordForgotCodeStatus` checks to see if password forgot token is still good
- `accountReset` uses the account reset token to set a new password
- Propagates headers from the original request to the auth-server, this is needed to that auth-server can determine the correct ip address for email
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6326
Some additional context, our password reset flows were created …

feat(gql): Add gql resolver for password forgot send code

---

packages/functional-tests/tests/oauth/forceAuth.spec.ts
packages/functional-tests/tests/oauth/loginHint.spec.ts

- 2 oauth tests were failing in prod because 123done.org (prod site) was shut down : [oauthForceAuth](https://github.com/mozilla/fxa/blob/main/packages/functional-tests/tests/oauth/forceAuth.spec.ts) , [loginHint](https://github.com/mozilla/fxa/blob/main/packages/functional-tests/tests/oauth/loginHint.spec.ts)
- Disables the tests until the prod 123done site is set up again
Closes: [FXA-6399](https://mozilla-hub.atlassian.net/browse/FXA-6399)

test(functional): disable oauth tests until 123done is set up in prod

---

packages/fxa-auth-server/lib/routes/index.js
packages/fxa-auth-server/lib/routes/oauth/index.js
packages/fxa-auth-server/lib/routes/oauth/key_data.js
packages/fxa-auth-server/test/local/routes/oauth.js

Because:
- we want to be certain what RPs are using the scoped keys endpoint
This commit:
- add statsd to the endpoint to learn what RPs are using it

chore(keys): add statsd metrics to scoped keys metadata endpoint

---

packages/fxa-payments-server/src/components/PlanDetails/index.stories.tsx
packages/fxa-payments-server/src/components/PlanDetails/index.tsx

- Taxes were not being shown in stories
- Adds Context so Stripe Tax feature flag can be updated to show taxes in `PlanDetails` stories (where applicable).
- Changes `isMobile` to optional with default set to false so it does not have to be explicitly set in each story.
- Cleans up stories and format by removing redundant and/or unnecessary code.
Closes: FXA-6320

fix(payments): update stories for PlanDetails to include tax

---

packages/fxa-auth-server/.eslintrc.json
packages/fxa-auth-server/lib/routes/account.ts
packages/fxa-auth-server/lib/routes/subscriptions/apple.ts
packages/fxa-auth-server/lib/routes/subscriptions/utils.ts
packages/fxa-auth-server/lib/types.ts

* The initial PR (#14508) did not include the changes made in #14547 which included some non-null assertions.
* Fixes those non-null assertions plus upgrades the non-null assertion lint to an error rather than a warning.
Closes FXA-6137

chore(auth-server): cleanup lint warnings from non-null assertions

---

packages/123done/static/js/123done.js
packages/functional-tests/lib/targets/production.ts
packages/functional-tests/tests/misc.spec.ts
packages/functional-tests/tests/signin/relyingParties.spec.ts

- We now have 123Done in production env
- Updates urls to point to that
- Enables test that use it
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6301
@ashrivastava-qa I tested this and it is working as expected. The production 123Done client is https://production-123done.herokuapp.com/
I am fairly certain that the subplat tests will fail since the product info might not be valid? But maybe we can enable those later once ready.

fix(test): Update 123Done production urls

---

packages/fxa-auth-server/test/local/payments/iap/apple-app-store/subscription-purchase.js
packages/fxa-shared/payments/iap/apple-app-store/subscription-purchase.ts

Because:
* offerType and offerIdentifier can exist on both transactionInfo and/or renewalInfo.
* We were only recording these properties on renewalInfo.
This commit:
* Records offerType and offerIdentifier on both transactionInfo and renewalInfo and differentiates them.
Closes #FXA-6108

chore(auth/shared): differentiate free trials in AppStoreSubscriptionPurchases

---

packages/functional-tests/pages/index.ts
packages/functional-tests/pages/login.ts
packages/functional-tests/pages/products/index.ts
packages/functional-tests/pages/products/subscriptionManagement.ts
packages/functional-tests/pages/settings/index.ts
packages/functional-tests/tests/subscription-tests/coupons-ui-tests/coupon.spec.ts

- In efforts to reduce the manual testing on Subplat coupon, added automated tests for the [Manual Test](https://testrail.stage.mozaws.net/index.php?/cases/view/1716624&group_by=cases:section_id&group_id=252171&group_order=asc)
- The test is to re-subscribe with the same coupon after canceling the subscription.
- Contains test for re-subscription with the same coupon after canceling the subscription.
Closes: #[FXA-6159](https://mozilla-hub.atlassian.net/browse/FXA-6159)

[subplat] test(subplat): resubscribe with same coupon after canceling

---

packages/fxa-auth-server/lib/payments/paypal/client.ts
packages/fxa-auth-server/lib/payments/paypal/helper.ts
packages/fxa-auth-server/lib/routes/subscriptions/paypal-notifications.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
packages/fxa-auth-server/scripts/paypal-refund-fixer.ts
packages/fxa-auth-server/test/local/payments/paypal-client.js
packages/fxa-auth-server/test/local/payments/paypal.js
packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js

Because:
* we want to be able to issue partial refunds for customers that pay with paypal
This commit:
* adds the necessary name-value pairs to the paypal request to issue partial refunds
Closes #FXA-3757

feat(auth): allow Partial Refunds For PayPal

---

packages/fxa-auth-client/lib/client.ts
packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
packages/fxa-graphql-api/src/gql/account.resolver.ts
packages/fxa-graphql-api/src/gql/dto/input/index.ts
packages/fxa-graphql-api/src/gql/dto/input/sign-in.ts
packages/fxa-graphql-api/src/gql/dto/payload/index.ts
packages/fxa-graphql-api/src/gql/dto/payload/signed-in-account.ts

Because:
- we might want to sign in through the gql-api instead of auth-server
This commit:
- add a mutation to proxy a sign in request to the auth-server

feat(gql): add acct sign in thru gql-api

---

packages/fxa-payments-server/src/lib/test-utils.tsx
packages/fxa-react/lib/test-utils/index.test.tsx
packages/fxa-react/lib/test-utils/index.ts
packages/fxa-react/lib/test-utils/test.ftl
packages/fxa-react/lib/utils.tsx
packages/fxa-settings/src/components/Settings/BentoMenu/index.tsx
packages/fxa-settings/src/components/Settings/index.test.tsx
packages/fxa-settings/src/lib/config.ts
packages/fxa-settings/src/models/hooks.ts
packages/fxa-settings/src/setupTests.tsx

- We want to ensure that calls to l10n.getString are safe
- We want to catch errors preemptively
- Adds a new class for resolving l10n strings. Resolving strings through this class:
- Ensures there are no straight quotes
- Ensures l10n id exists in the 'en' bundle
- Ensures fallback text matches text in 'en' bundle
- Ensures there are no errors resolving parameters in the l10n string
- Adds a hook for easy access to the FtlMsgResolver.
- Adds config that controls whether or not we run in strict mode. Note, that run time errors will result if a violation is detected when `strict=true`.
- Applies mechanism to one component in settings, the bento box.
Closes: FXA-6001
Note that by default config.l10n.strict will be set to true. This means any …

task(fxa-react): Create l10n.getString wrapper

---

packages/fxa-settings/src/lib/config.ts

- This was throwing an error on stage.
- Disables strict mode by default.
Note this PR was due to an error encountered on stage. The error looked like this:
Note, this mode should still be manually enabled during testing, and when developing locally. A follow up PR will be issued for this.

fix(settings): Disable 'strict' mode by default

---

packages/functional-tests/pages/login.ts
packages/functional-tests/tests/settings/passwordVisibility.spec.ts

- As part of the playwright test migration, the [password visibility tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/password_visibility.js) have been rewritten in this PR.
- contains the [password visibility tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/password_visibility.js)
Closes: #[FXA-5910](https://mozilla-hub.atlassian.net/browse/FXA-5910)

test(functional): rewrite password visibility test using playwright

---

packages/fxa-graphql-api/src/gql/model/session.ts
packages/fxa-graphql-api/src/gql/session.resolver.spec.ts
packages/fxa-graphql-api/src/gql/session.resolver.ts
packages/fxa-shared/db/models/auth/session-token.ts

Because:
- a front end client should able to query the status of a session
This commit:
- add the sessionStatus query to the Session resolver

feat(gql): add session status query

---

packages/fxa-auth-client/lib/client.ts
packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
packages/fxa-graphql-api/src/gql/account.resolver.ts
packages/fxa-graphql-api/src/gql/dto/input/sign-up.ts
packages/fxa-graphql-api/src/gql/dto/payload/signed-up-account.ts

Because:
- we want to allow front end clients to sign up a user through the gql-api
This commit:
- add the signUp mutation to the Account resolver

feat(gql): add acct sign up mutation to gql-api

---

packages/fxa-auth-server/test/mail_helper.js
packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
packages/fxa-graphql-api/src/gql/account.resolver.ts
packages/fxa-graphql-api/src/gql/dto/input/account-status.ts
packages/fxa-graphql-api/src/gql/dto/input/index.ts
packages/fxa-graphql-api/src/gql/dto/payload/account-status.ts
packages/fxa-graphql-api/src/gql/dto/payload/index.ts
packages/fxa-graphql-api/test/helpers.ts
packages/fxa-graphql-api/test/sessions.sql

- We want to expose this functionality in graphql
- Adds the eqalivent `GET /account/status` endpoint in graphql
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6332

feat(api): Add accountStatus check in graphql api

---

packages/fxa-auth-server/scripts/delete-account.js

Because:
- we delete from the pushbox db directly when deleting an account now
This commit:
- add the pushbox module to the account routes when used from the delete account script

fix(scripts): add pushbox dep to delete acct script

---

packages/functional-tests/tests/oauth/loginHint.spec.ts
packages/functional-tests/tests/oauth/scopeKeys.spec.ts
packages/functional-tests/tests/oauth/signin.spec.ts
packages/fxa-content-server/tests/functional.js

- The `preverified` option is disabled in prod, which allows account to be created and verified at once
- Uses `target.createAccount` which goes through the process of checking email, getting code and verifying account

fix(tests): Tweaks playwright tests to not use `preverified`

---

packages/fxa-content-server/app/scripts/templates/partial/account-suggestion.mustache
packages/fxa-content-server/app/scripts/templates/partial/sync-suggestion.mustache
packages/fxa-content-server/app/scripts/views/tooltip.js
packages/fxa-content-server/app/styles/tailwind/state.css
packages/fxa-content-server/tailwind.config.js

This commit:
* Reverts a recent change that updated a bg-image to use an img src and uses TW to load the image. We may have a bug in content-server around updating img src image hashes in at the build step unless it's intentional to always use bg-images, and this commit inlines the SVGs instead as they are tiny and keeps a11y wins
* Adjusts bottom-padding slightly for more consistency with prod
Because:
* The close SVGs are not loading on the build step due to 'img src' path hashes not being updated in the outputted HTML
Closes: FXA-6453
---
This is a similar issue to #14549 where the image loads locally but in staging the image fails to load. You can see in staging on FF, it looks like the image properly loads (but is strangely a few pixels pushed down vs local), but actually it's …

fix(content): Fix path reference for close.svg rendering issue

---

packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
packages/fxa-graphql-api/src/gql/account.resolver.ts
packages/fxa-graphql-api/src/gql/dto/input/reject-unblock-code.ts

Because:
- gql-api should be able to consume an unblock code
This commit:
- enable the gql-api to consume an unblock code by calling a db sproc

feat(gql): consume unblock code

---

packages/fxa-auth-server/config/index.ts
packages/fxa-shared/db/config.ts
packages/fxa-shared/db/mysql.ts
packages/fxa-shared/test/db/mysql.ts

Because:
- the mysql module's connection pool never close any of its connections
This commit:
- close a connection after it idles for a configurable amount of time

feat(mysql): close idling connections in pool

---

packages/functional-tests/pages/products/subscriptionManagement.ts
packages/fxa-auth-server/lib/payments/stripe-formatter.ts
packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-payments-server/.storybook/addons.js
packages/fxa-payments-server/.storybook/main.js
packages/fxa-payments-server/Gruntfile.js
packages/fxa-payments-server/package.json
packages/fxa-payments-server/src/components/PaymentErrorView/index.test.tsx
packages/fxa-payments-server/src/components/PlanDetails/index.stories.tsx
packages/fxa-payments-server/src/components/PriceDetails/en.ftl
packages/fxa-payments-server/src/components/PriceDetails/index.stories.tsx
packages/fxa-payments-server/src/components/PriceDetails/index.test.tsx
packages/fxa-payments-server/src/components/PriceDetails/index.tsx
packages/fxa-payments-server/src/lib/apiClient.ts
packages/fxa-payments-server/src/lib/format.test.ts
packages/fxa-payments-server/src/lib/formats.ts
packages/fxa-payments-server/src/lib/mock-data.tsx
packages/fxa-payments-server/src/lib/test-utils.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Cancel/en.ftl
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx
packages/fxa-payments-server/src/routes/Subscriptions/en.ftl
packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx
packages/fxa-shared/dto/auth/payments/invoice.ts
yarn.lock

- For exclusive tax, display the tax amount in subscription management
- Adds a new component, PriceDetails, that can be used to display the
price with/out tax, and price intervals with/out tax.
- Adds PriceDetails component to Subscription Management, and updates
the copy used.
Closes: #FXA-6187

fix(Subscriptions): add tax to sub management

---

packages/fxa-payments-server/src/components/PlanDetails/index.test.tsx
packages/fxa-payments-server/src/components/PlanDetails/index.tsx
packages/fxa-payments-server/src/lib/mock-data.tsx

- we want to hide the Taxes & Fees for countries with inclusive tax.
- updates the PlanDetails component to hide Taxes & Fees when tax is inclusive.
- adds basic tests for Taxes & Fees.
Closes: #FXA-6391
Inclusive Tax
Exclusive Tax

feat(payments): hide taxes for inclusive tax

---

packages/functional-tests/pages/products/subscriptionManagement.ts
packages/functional-tests/tests/subscription-tests/coupons-ui-tests/coupon.spec.ts
packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts

In efforts to increase test coverage for coupon and Subplat regression , added automated tests for:
- Resubscribing after cancellation with same coupon for Stripe
- Resubscribing after cancellation with same coupon for Paypal
- Update mode of payment for Stripe
- Contains test for:
- Resubscribing after cancellation with same coupon for Stripe
- Resubscribing after cancellation with same coupon for Paypal
- Update mode of payment for Stripe
Closes: #[FXA-6157](https://mozilla-hub.atlassian.net/browse/FXA-6157) [FXA-6246](https://mozilla-hub.atlassian.net/browse/FXA-6246) [FXA-6249](https://mozilla-hub.atlassian.net/browse/FXA-6249) 
Any other information that is …

[subplat] test(subplat): add test for resubscription and update mode of payment

---

packages/fxa-content-server/app/scripts/lib/metrics.js
packages/fxa-content-server/app/tests/spec/lib/metrics.js
packages/fxa-shared/speed-trap/events.js
packages/fxa-shared/speed-trap/index.js
packages/fxa-shared/speed-trap/navigation-timing.js
packages/fxa-shared/speed-trap/performance-factory.js
packages/fxa-shared/speed-trap/speed-trap.js
packages/fxa-shared/speed-trap/timers.js
packages/fxa-shared/speed-trap/timing-fields.js

- We could see in Sentry that various times provided to metrics endpoint were consistently off.
- Creates an abstraction around the performance API to isolate some of its complexities.
- Tries to use the performance API where possible.
- Address discrepancies between performance API timestamps and system time.. The assumption that the clock used by Date and the clock used by the performance API  are somehow in sync is likely the reason for the generation of erroneous data.  It is very likely that there is a significant clock skew found between the monotonic clock used by the performance API and current state of the system clock. There appears to be a lot of nuance here, and the exact way this plays out depends on the OS, browser, and browser version, and if the machine has been put into …

fix(content): Fix buggy timing metrics

---

packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-content-server/tests/server/amplitude.js
packages/fxa-settings/src/components/Ready/index.test.tsx
packages/fxa-settings/src/components/Ready/index.tsx
packages/fxa-settings/src/pages/ResetPasswordConfirmed/index.test.tsx
packages/fxa-settings/src/pages/ResetPasswordConfirmed/index.tsx
packages/fxa-settings/src/pages/ResetPasswordWithRecoveryKeyVerified/en.ftl
packages/fxa-settings/src/pages/ResetPasswordWithRecoveryKeyVerified/index.stories.tsx
packages/fxa-settings/src/pages/ResetPasswordWithRecoveryKeyVerified/index.test.tsx
packages/fxa-settings/src/pages/ResetPasswordWithRecoveryKeyVerified/index.tsx

* We're recreating the remaining content-server views in React and moving them into Storybook before they go live
* Recreates reset_password_with_recovery_key_verified in React with metrics, tests, and l10n

storybook(fxa-settings): recreate ResetPasswordWithRecoveryKeyVerified

---

.circleci/config.yml
_dev/docker/ci-browsers/Dockerfile

- Playwright tests weren't running
- Switches from to an npx install to setup the playwright browsers
Closes: FXA-6467

bug(CI): Fixes the playwright install in the base image

---

packages/fxa-content-server/server/lib/flow-event.js
packages/fxa-content-server/tests/server/flow-event.js

Because:
* Our timestamps are being recorded as from `1970-01-01` for some reason but only from the content server.  We hypothesize the downstream mozlog is failing to convert this timestamp properly.  Since content server is the only server that is specifying a timestamp we think if we remove it things might start working for free.  Let's find out!
This commit:
* removes the timestamp
Closes FXA-6472

fix(metrics): remove specific timestamp from log

---

packages/fxa-auth-client/lib/client.ts
packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
packages/fxa-graphql-api/src/gql/account.resolver.ts
packages/fxa-graphql-api/src/gql/dto/input/finish-setup.ts
packages/fxa-graphql-api/src/gql/dto/payload/finished-setup-account.ts

Because:
- we want gql-api to finish setting up a stub account for the user
This commit:
- proxy an account finish setup request to the auth-server

feat(gql): add proxy to acct finish setup

---

packages/fxa-auth-client/lib/client.ts
packages/fxa-graphql-api/src/gql/dto/input/session-reauth.ts
packages/fxa-graphql-api/src/gql/dto/payload/signed-in-account.ts
packages/fxa-graphql-api/src/gql/session.resolver.spec.ts
packages/fxa-graphql-api/src/gql/session.resolver.ts

Because:
- we want to re-auth an existing session through the gql-api
This commit:
- proxy a session reauth request through the gql-api to the auth-server

feat(gql): re-auth an existing session

---

.circleci/config.yml
packages/functional-tests/lib/fixtures/README.md
packages/fxa-content-server/scripts/test-ci-remote.sh
packages/fxa-content-server/tests/intern.js

- We want decrease the time it takes to deploy
- Adds ability to divide smoke tests
- Creates jobs that divide content server smoke tests into three parts
- Jobs can be run in parallel
- Creates a new executor for running smoke tests
- Removes mozinstall command (found in test-ci-remote.sh) since there is already a firefox browser installed in the base image
- Removes internjs argument --firefoxBinary, because there is now a firefox binary available in /usr/local/bin/firefox.
Closes: FXA-6264
- Playwright tests run pretty quickly so they were not split
- The remote content server tests seem to have some flake. I am still trying to determine if it is worse when they run in parallel.

task(ci): Run content server smoke tests in parallel

---

.circleci/config.yml

- The graphql-api didn't startup properly. It appears down stream packages were not built.
- Ensures common packages are built.

fix(CI): Fix failing tests due to missing types

---

.circleci/config.yml

Because:
- The graphql api didn't startup properly. It appears down stream packages were not built.
This Commit:
- Ensures common packages are built.

Train 248 uplift 1 -> Train 248

---

.circleci/config.yml
_scripts/compile-backend-ts-services.sh
packages/fxa-auth-client/package.json

- We cannot add parameters to job triggered through circleci's API
- An issue was detected when compiling back end services that relied on fxa-auth-client.
- Removes parameters from the `test-content-server-remote` job
- Fixes an issue that was recently uncovered in the compile-backend-services step

bug(CI): Remove parameters from test-content-server-remote and fix issue compiling backend services

---

.circleci/config.yml
_scripts/compile-backend-ts-services.sh
packages/fxa-auth-client/package.json

Because:
- We cannot add parameters to job triggered through circleci's API
This Commit:
- Removes parameters from the `test-content-server-remote` job
-
-

Train 248 uplift 2 -> Train 248

---

packages/fxa-auth-server/lib/routes/auth-schemes/refresh-token.js
packages/fxa-auth-server/test/local/routes/auth-schemes/refresh-token.js

Authored by @tarikeshaq in https://github.com/mozilla/fxa/pull/14454
- The operating system information of the requesting device is parsed from the user-agent header
- For session tokens, the operating system is a part of the token object. (When we create the tokens, we read the user agent at the time, and persist data from it, like the operating system with the tokens)
- For refresh tokens, the information we get from the user-agent is not there.
- [There is at least one API that assumes that the credentials object always has the `uaOS` (the operating system)](https://github.com/mozilla/fxa/blob/7cdd496834e0355e1f909f65f606b82eca3fbb2f/packages/fxa-auth-server/lib/routes/devices-and-sessions.js#L348)
- Downstream, this causes our metrics to have **many** null "sender operating systems" …

fix(metrics): Adds user agent information to refresh token credentials

---

packages/fxa-auth-client/lib/client.ts
packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
packages/fxa-graphql-api/src/gql/account.resolver.ts
packages/fxa-graphql-api/src/gql/dto/input/index.ts
packages/fxa-graphql-api/src/gql/dto/input/verify-email.ts

- We need to be able to verify an email via a code since its used in our frontend routes
- Adds gql mutation to verify an email via code
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6333

feat(gql): Add verify email code gql

---

packages/fxa-auth-client/lib/client.ts
packages/fxa-graphql-api/src/gql/dto/input/basic-mutation.ts
packages/fxa-graphql-api/src/gql/dto/input/delete-recovery-key.ts
packages/fxa-graphql-api/src/gql/dto/input/delete-totp.ts
packages/fxa-graphql-api/src/gql/dto/input/destroy-session.ts
packages/fxa-graphql-api/src/gql/dto/input/send-session-verification.ts
packages/fxa-graphql-api/src/gql/session.resolver.spec.ts
packages/fxa-graphql-api/src/gql/session.resolver.ts

Because:
- gql-api should be able to handle a resend verify code request
This commit:
- proxy to auth-server to resend a verify code

feat(gql): resend verify code

---

packages/fxa-auth-client/lib/client.ts
packages/fxa-graphql-api/src/gql/dto/input/session-verify-code.ts
packages/fxa-graphql-api/src/gql/session.resolver.spec.ts
packages/fxa-graphql-api/src/gql/session.resolver.ts

Because:
- gql-api should be able to verify an OTP code
This commit:
- proxy to the auth-server to verify an OTP code

feat(gql): add session mutation to verify OTP codes

---

packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js

- For the invoice preview endpoint, for logged in users, do not perform the customs.checkIpOnly.
- Only performs the customs.checkIpOnly check if auth credentials are not provided.
Closes: # FXA-6543

fix(payments): only checkIpOnly if no credentials

---

packages/fxa-payments-server/src/components/PriceDetails/index.tsx
packages/fxa-payments-server/src/lib/hooks.test.tsx
packages/fxa-payments-server/src/lib/hooks.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.stories.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
packages/fxa-payments-server/src/routes/Product/en.ftl
packages/fxa-payments-server/src/routes/Product/index.test.tsx
packages/fxa-payments-server/src/routes/Product/index.tsx

- We want to display the amount of tax charged or included on upgrades
(if applicable)
- Updates PlanUpgradeDetails to include tax details
- Updates SubscriptionUpgrade to pass tax details to PlanUpgradeDetails
- Updates tests for both
- Updates StoryBook for SubscriptionUpgrade to CSF and adds inclusive
and exclusive tax stories
- Adds custom hook to fetch invoicePreview and added to `routes/Product`
Closes FXA-6376
This can be tested by subscribing to 123Pro Plans listed below.
- [Subscribe to Pro (USD)](http://localhost:3030/subscriptions/products/prod_GqM9ToKK62qjkK?plan=plan_GqM9N6qyhvxaVk)
- Upgrade to [Subscribe to Pro 12m (USD)](http://localhost:3030/subscriptions/products/prod_GqM9ToKK62qjkK?plan=price_1KbomlBVqmGyQTMaa0Tq7UaW)

fix(payments): display tax amount on subscription upgrades

---

packages/fxa-settings/src/pages/AccountRecoveryResetPassword/en.ftl
packages/fxa-settings/src/pages/AccountRecoveryResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/AccountRecoveryResetPassword/index.test.tsx
packages/fxa-settings/src/pages/AccountRecoveryResetPassword/index.tsx

* We're making React versions of content server's remaining backbone pages, and moving them first into Storybook.
* Sets up the page view metric, basic tests, and storybook stories for the account_recovery_reset_password page.
Closes #https://mozilla-hub.atlassian.net/browse/FXA-6343
There are a number of remaining TO-DOs noted in the PR. They fall outside of the scope of this ticket. 
There are also some small variations from the original pages (for example, the `Remembered password?` link is now, `Remembered your password? Sign in`.) This is to match already-established precedent in the Settings app.

fxa-settings(storybook): add account_recovery_reset_password

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/payments/utils.ts
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/payments/utils.js

- Error is displayed on the Subscription Management page after attempt to resubscribe after cancelling a subscription via Stripe Dashboard
- adds time when idempotency key is generated, as the idempotency key was previously generated using customer id, price id, and payment method fingerprint. This caused Stripe to treat subscribing to the same subscription (after the subscription was cancelled via Stripe) as a duplicate request.
Closes: [FXA-6413](https://mozilla-hub.atlassian.net/browse/FXA-6413)

fix(auth): Add time when idempotency key is generated

---

packages/fxa-auth-server/docs/swagger/swagger-options.ts

- we don't need this as a disclaimer
- removes disclaimer
- also re-alphabetizes tags as their sections were renamed (see `fxa-auth-server/docs/swagger/swagger-tags.ts`)
Closes: [FXA-6552](https://mozilla-hub.atlassian.net/browse/FXA-6552)

chore(docs): Remove Disclaimer in Auth Server API doc

---

packages/fxa-content-server/app/scripts/lib/app-start.js
packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/generalized-react-app.js
packages/fxa-content-server/app/scripts/lib/generalized-react-app-experiment-mixin.js
packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/bin/fxa-content-server.js
packages/fxa-content-server/server/lib/beta-settings.js
packages/fxa-content-server/server/lib/configuration.js
packages/fxa-content-server/server/lib/routes.js
packages/fxa-content-server/server/lib/routes/get-frontend.js
packages/fxa-content-server/server/lib/routes/get-index.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-content-server/server/lib/routes/react-app/route-definitions.js
packages/fxa-content-server/server/lib/routes/react-app/types.ts
packages/fxa-content-server/tests/functional/oauth_permissions.js
packages/fxa-content-server/tests/server/routes/get-index.js
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/index.tsx
packages/fxa-settings/src/pages/CannotCreateAccount/index.tsx
packages/fxa-shared/express/routing.ts

Because:
* We want to be able to access the React version of content-server pages at the same URL when users are actively in our 'generalizedReactApp' experiment and feature flag groups containing these routes are on
This commit:
* Creates new files in content-server routes directory to house feature flag group objects containing new React page routes (for now, simpleRoutes), route definitions (for now, definitions from 'getFrontEnd'), and functions that conditionally allow content-server to serve the route if the feature flag (for now, simpleRoutes) is on and the request contains 'showReactApp'
* Implements these conditional functions in `fxa-content-server.js`, where content-server handles its routing based on env
* Adds feature flags to content-server config
* Modifies the Backbone …

feat(content/react): Conditionally serve React version of Backbone routes

---

packages/fxa-settings/src/pages/SigninReported/en.ftl
packages/fxa-settings/src/pages/SigninReported/index.stories.tsx
packages/fxa-settings/src/pages/SigninReported/index.test.tsx
packages/fxa-settings/src/pages/SigninReported/index.tsx

* We're going through the remaining fxa-content-server Backbone views and adding React versions of them into Storybook as a first step to moving them into the React app.
* Adds basic l10n, metrics, tests, and a React version for the `signin_reported` view
Closes #https://mozilla-hub.atlassian.net/browse/FXA-6418
[FXA-6418]: https://mozilla-hub.atlassian.net/browse/FXA-6418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

storybook(fxa-settings): add signin_reported to storybook

---

packages/fxa-auth-server/lib/payments/stripe-formatter.ts
packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/test/local/payments/fixtures/stripe/invoice_preview_tax.json
packages/fxa-auth-server/test/local/payments/stripe-formatter.js
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-payments-server/src/components/PlanDetails/index.stories.tsx
packages/fxa-payments-server/src/components/PlanDetails/index.test.tsx
packages/fxa-payments-server/src/components/PlanDetails/index.tsx
packages/fxa-payments-server/src/lib/mock-data.tsx
packages/fxa-payments-server/src/lib/test-utils.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx
packages/fxa-shared/dto/auth/payments/invoice.ts

* Multiple tax rates in Canada were not reflected in the invoice preview.
* Multiple tax rates in Canada were not reflected on the subscription management page.
* Adds support for showing multiple tax rates within the invoice preview.
* Fixes total displayed on subscription management page for subscriptions with multiple tax rates.
Closes FXA-6439
[FXA-6439]: https://mozilla-hub.atlassian.net/browse/FXA-6439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(auth/payments): canada tax not reflecting multiple tax rates

---

packages/fxa-content-server/scripts/test-ci.sh
packages/fxa-content-server/tests/functional_pairing.js

- The pairing tests were being flaky for quite sometime. Currently disabling it and created a ticket [FXA-6558](https://mozilla-hub.atlassian.net/browse/FXA-6558) to later address the issue.
- Removed the pairing suite out of the test runs for Content-server-2
[FXA-6558]: https://mozilla-hub.atlassian.net/browse/FXA-6558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FXA-6558]: https://mozilla-hub.atlassian.net/browse/FXA-6558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(functional): remove flaky pairing test

---

packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.stories.tsx

* A few SubscriptionUpgrade stories had incorrect typings caused by #14684. Strangely #14684 did not fail CI which is something that will need to be investigated separately.
* Because of the above, SubscriptionUpgrade hadn't been updated to support multiple tax rates.
* Fixes the typings.
* Adds support for multiple tax rates to SubscriptionUpgrade.
Closes: FXA-6439
[FXA-6439]: https://mozilla-hub.atlassian.net/browse/FXA-6439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(payments): support for multiple tax rates in subscription upgrade

---

packages/fxa-settings/src/pages/CompleteResetPassword/en.ftl

- FTL ids need to be unique, and one ID had not been updated for the CompleteResetPassword page and reused an ID from ResetPassword (but with different messages).
- Fix the FTL ID name

fix(l10n): Duplicated FTL id in CompleteResetPassword

---

packages/fxa-content-server/app/scripts/lib/app-start.js
packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/generalized-react-app.js
packages/fxa-content-server/app/scripts/lib/generalized-react-app-experiment-mixin.js
packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/bin/fxa-content-server.js
packages/fxa-content-server/server/lib/beta-settings.js
packages/fxa-content-server/server/lib/configuration.js
packages/fxa-content-server/server/lib/routes.js
packages/fxa-content-server/server/lib/routes/get-frontend.js
packages/fxa-content-server/server/lib/routes/get-index.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-content-server/server/lib/routes/react-app/route-definitions.js
packages/fxa-content-server/server/lib/routes/react-app/types.ts
packages/fxa-content-server/tests/functional/oauth_permissions.js
packages/fxa-content-server/tests/server/routes/get-index.js
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/index.tsx
packages/fxa-settings/src/pages/CannotCreateAccount/index.tsx
packages/fxa-shared/express/routing.ts

Includes the already r+'d commit from #14579 (see for a lot more detail) and a fix for FXA-6566.
To test this, check into the commit before the fix (`2da883`), start all services after modifying the config as described in the other PR, and see `localhost:3030/cannot_create_account` shows the content-server version of the page while `localhost:3030/cannot_create_account?showReactApp=true` displays the React version of the page (inspect and see `div id="root"` or that the margin on the link differs). Dev version works as expected. Now, run `pm2 stop content`, then in `packages/fxa-content-server`, run `yarn start-production`. Observe the issue described in staging, with the files shown having the incorrect MIME type. This wasn't caught before since I wasn't correctly testing prod - you can …

fix(content-server): Revert previous revert around conditional route serving, include fix

---

packages/fxa-auth-server/lib/routes/validators.js
packages/fxa-auth-server/scripts/stripe-products-and-plans-to-firestore-documents/stripe-products-and-plans-converter.ts
packages/fxa-auth-server/test/local/payments/capability.js
packages/fxa-auth-server/test/local/payments/configuration/manager.js
packages/fxa-auth-server/test/local/routes/validators.js
packages/fxa-auth-server/test/scripts/stripe-products-and-plans-converter.js
packages/fxa-shared/subscriptions/configuration/base.ts
packages/fxa-shared/subscriptions/configuration/plan.ts
packages/fxa-shared/subscriptions/configuration/product.ts
packages/fxa-shared/subscriptions/metadata.ts
packages/fxa-shared/subscriptions/types.ts
packages/fxa-shared/subscriptions/validation.ts
packages/fxa-shared/test/subscriptions/configuration/plan.ts
packages/fxa-shared/test/subscriptions/configuration/product.ts
packages/fxa-shared/test/subscriptions/configuration/utils.ts
packages/fxa-shared/test/subscriptions/metadata.ts

- productSet should be required
- updates productSet from optional to required
Closes: [FXA-6228](https://mozilla-hub.atlassian.net/browse/FXA-6228)
[FXA-6228]: https://mozilla-hub.atlassian.net/browse/FXA-6228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FXA-6228]: https://mozilla-hub.atlassian.net/browse/FXA-6228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(auth, shared): Update productSet from optional to required

---

packages/fxa-shared/l10n/supportedLanguages.json

-  Kazakh locale (kk) raised their threshold from 30% to above threshold of 70%
- Enables kk locale in the supportedLanguages.json

chore(l10n): Add kk locale

---

packages/fxa-settings/src/components/Settings/Checkbox/index.tsx

- We want to standardize spelling to the standard "focused"
- Change setFocussed to setFocused in Checkbox component
Closes: #FXA-6475

fix(fxa-settings): change focussed to focused in Checkbox component

---

packages/functional-tests/pages/products/index.ts
packages/functional-tests/pages/products/subscriptionManagement.ts
packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts
packages/functional-tests/tests/subscription-tests/coupons-ui-tests/ui-tests.spec.ts

In efforts to increase test coverage for coupon and Subplat regression , added automated tests for:
- [Verify that the discount isn't displayed in the manage subscription page](https://testrail.stage.mozaws.net/index.php?/cases/view/1614025&group_by=cases:section_id&group_id=252172&group_order=asc)
- [Verify that couponing feature isn't available while trying to change the subscription plan](https://testrail.stage.mozaws.net/index.php?/cases/view/1614011&group_by=cases:section_id&group_id=252172&group_order=asc)
Contains tests for: 
- Verifying that the discount isn't displayed in the manage subscription page
- Verify that couponing feature isn't available while trying to change the subscription plan
Closes: #[FXA-6577](https://mozilla-hub.atlassian.net/browse/FXA-6577) …

test(coupon): write tests for coupon section not displayed when changing plans

---

packages/fxa-auth-server/scripts/test-ci.sh

- A few tests were not being run that should be.
- In general remote and oauth tests are most integration tests, however, it is possible these suites contain a small number of unit tests.
- Runs all tests suites for both unit and integration tests since there maybe unit or integration tests in any of these suites.
This is just a small follow up PR trailing FXA-6266.

task(CI): Fix auth server test coverage for unit / integration tests

---

packages/fxa-settings/src/components/PasswordStrengthBalloon/en.ftl

- Change was accidentally reverted before merging PR-14738 (reported by @bcolsson)
- Fix the em dash in PasswordStrengthBalloon ftl

fix(l10n): Replace unicode with regular em dash

---

packages/fxa-auth-server/lib/routes/devices-and-sessions.js
packages/fxa-auth-server/test/local/routes/devices-and-sessions.js

- A request to the `/devices` should update the session token last access time
- Updates the last access time using `db.touchSessionToken` which is designed to be used in frequenlty hit routes
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6595

fix(api): update last access time when `/account/devices` route is hit

---

packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
packages/fxa-graphql-api/src/gql/account.resolver.ts
packages/fxa-graphql-api/src/gql/dto/input/index.ts
packages/fxa-graphql-api/src/gql/dto/input/recovery-key.ts
packages/fxa-graphql-api/src/gql/dto/payload/index.ts
packages/fxa-graphql-api/src/gql/dto/payload/recovery-key.ts

- During password reset, a user should be able to get a recovery bundle that contains their sync key. This is used to during the password reset process to ensure their keys dont change
- Adds gql query to retrieve recovery bundle
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6328

feat(api): Add gql resolvers for recovery key bundle

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/app/tests/spec/lib/router.js
packages/fxa-content-server/server/bin/fxa-content-server.js
packages/fxa-content-server/server/lib/routes.js
packages/fxa-content-server/server/lib/routes/get-frontend-pairing.js
packages/fxa-content-server/server/lib/routes/get-frontend.js
packages/fxa-content-server/server/lib/routes/get-oauth-success.js
packages/fxa-content-server/server/lib/routes/react-app/add-routes.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-content-server/server/lib/routes/react-app/react-route.js
packages/fxa-content-server/server/lib/routes/react-app/route-definitions.js
packages/fxa-content-server/server/lib/routes/react-app/types.ts
packages/fxa-content-server/tests/server/routes/react-app.js
packages/fxa-content-server/tests/tests_server.js

This commit:
* Refactors route-related files and creates helper functions so we can more easily add routes ready to be served on the React side instead of the Backbone side
Because:
* As we refactor to React, we need to be able to easily add route names to be served by fxa-settings
Closes FXA-6538
--
I'll write this in tickets, but when we want to show the React version of a page, we'll add the route in Settings, identify the feature flag the route should go under, and then in `routes/react-app/index.js`, we can add the route with either `reactRoute.getRoute('whatever')` or `reactRoute.getRoutes(['hello', 'world'])`. Then, in `router.js`, we'll use the new `createReactOrBackboneViewHandler` method, and (after your `local.json` file is updated to set the feature flags) whabam! This method …

refactor(content-server): Prep for easier addition of Reactified routes

---

packages/fxa-auth-server/lib/log.js

- We want better visibility into what happens when a response to the session/verify_code endpoint returns a 400
- Adds some logging around this scenario
- Logging won't be done on production
This is just a temporary change. It will be reverted once we can observe an invalid state and correlate it with our logs.

bug(auth): Debugging missing response body on verify_code calls

---

packages/fxa-auth-client/lib/client.ts
packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
packages/fxa-graphql-api/src/gql/account.resolver.ts
packages/fxa-graphql-api/src/gql/dto/input/index.ts
packages/fxa-graphql-api/src/gql/dto/input/password-change.ts
packages/fxa-graphql-api/src/gql/dto/payload/index.ts
packages/fxa-graphql-api/src/gql/dto/payload/password-change.ts

- We want to expose the change password api in gql
- Adds gql resolvers to change a users password
- The client will still need to generate the authPW for old and new password since we don't want to send the clear password to FxA server
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6334

feat(api): Add gql resolvers for change password

---

packages/fxa-content-server/app/styles/tailwind/tooltips.css
packages/fxa-react/styles/index.css
packages/fxa-react/styles/tooltips.css
packages/fxa-settings/src/components/FormResetPasswordWithBalloon/en.ftl
packages/fxa-settings/src/components/FormResetPasswordWithBalloon/index.tsx
packages/fxa-settings/src/components/FormResetPasswordWithBalloon/mocks.tsx
packages/fxa-settings/src/components/InputPassword/index.tsx
packages/fxa-settings/src/components/PasswordStrengthBalloon/index.stories.tsx
packages/fxa-settings/src/pages/AccountRecoveryResetPassword/en.ftl
packages/fxa-settings/src/pages/AccountRecoveryResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/AccountRecoveryResetPassword/index.test.tsx
packages/fxa-settings/src/pages/AccountRecoveryResetPassword/index.tsx
packages/fxa-settings/src/pages/AccountRecoveryResetPassword/mocks.tsx
packages/fxa-settings/src/pages/CompleteResetPassword/en.ftl
packages/fxa-settings/src/pages/CompleteResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/CompleteResetPassword/index.test.tsx
packages/fxa-settings/src/pages/CompleteResetPassword/index.tsx
packages/fxa-settings/src/pages/CompleteResetPassword/mocks.tsx
packages/fxa-settings/src/styles/tailwind.css

- We want to include the PasswordStrengthBalloon component in CompleteResetPassword and AccountRecoveryResetPassword pages to match parity with the content-server views.
* Move tooltips styling to fxa-react
* Update FormResetPasswordWithBalloon to include error feedback when passwords do not match
* Replace FormPassword with FormResetPasswordWithBalloon in CompleteResetPassword
* Replace custom password form in AccountRecoveryResetPassword with FormResetPasswordWithBalloon
* Update l10n, tests for CompleteResetPassword, AccountRecoveryResetPassword
* Review and standardize both pages
Closes: #FXA-6591
AccountRecoveryResetPassword:
CompleteResetPassword:

storybook(fxa-settings): Implement PasswordStrengthBalloon in reset password flow pages

---

packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx
packages/fxa-payments-server/src/lib/hooks.test.tsx
packages/fxa-payments-server/src/lib/hooks.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx

Because:
* once a subscription is cancelled we cannot retrieve a subsequent invoice and were other wise defaulting to the plan amount unless a coupon was originally used in the resubcribe modal hook
This commit:
* removes the logic that tests for a promotion code/coupon and always queries the api for the invoice amount if the subscription were to be re-activated
Closes #FXA-6377

fix(payments): resubscribe Modal Not Reflecting Invoice Amount

---

packages/fxa-auth-server/scripts/refund-unverified-accounts.ts

- Need to refund subscriptions of accounts that are unverified.
- Creates a one time script to identify accounts that created a
subscription in a specified date range.
- The script outputs separate csv files for unverified accounts,
verified accounts, and accounts with unexpected errors.
- The script has the option to refund unverified accounts.
- The script can be run with a file specifying uids or emails to skip
unverified accounts.
Closes: # FXA-6551
[FXA-6551]: https://mozilla-hub.atlassian.net/browse/FXA-6551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(auth): refund unverified accounts

---

packages/fxa-admin-server/package.json
packages/fxa-auth-client/package.json
packages/fxa-auth-server/package.json
packages/fxa-content-server/package.json
packages/fxa-event-broker/package.json
packages/fxa-graphql-api/package.json
packages/fxa-shared/package.json
packages/fxa-shared/speed-trap/events.js
packages/fxa-shared/speed-trap/navigation-timing.js
packages/fxa-shared/speed-trap/speed-trap.js
packages/fxa-support-panel/package.json
yarn.lock

- Our API expects integer values for all timing related metrics, but chrome can produce floats.
- Ensures that all timing metrics coming from speed strap are integers.
- Reverts the esbuild package upgrade, which appeared to cause a regression and slip through the cracks.
Closes: FXA-6600
This is a follow up to FXA-6600. That PR addressed an issue where the performance API might produce an erroneous value when called. This takes the change a step further and addresses a scenario where the timing API is producing floats instead of integer values. Integers are required by our metrics endpoint. Apparently this effects  webkit based browsers.

fix(content): Another metrics fix for invalid timing values

---

.circleci/config.yml

- We've been seeing some odd behavior were 'stale' images are getting used in some cases.
- Disables docker layer caching for now. This seems like the safest thing to do until we fully understand what's happening in FXA-6624

fix(ci): Disable docker layer caching

---

packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
packages/fxa-graphql-api/src/gql/account.resolver.ts
packages/fxa-graphql-api/src/gql/model/account.ts
packages/fxa-graphql-api/src/gql/model/securityEvent.ts
packages/fxa-graphql-api/test/helpers.ts
packages/fxa-graphql-api/test/security-events-names.sql
packages/fxa-graphql-api/test/security-events.sql
packages/fxa-shared/db/models/auth/account.ts

- In order to view security events we need to add them to account resolver
- Adds gql account resolver to retrieve security events
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6112
We still need to add react views for security events

feat(api): Add gql resolvers for security events

---

packages/fxa-settings/src/pages/SigninBounced/en.ftl

- An FTL contains a brand reference but does not use a brand placeable.
- Replaces the hard coded reference with the brand placeable.
Closes: #14753 

chore(l10n): Fix brand reference

---

.github/dependabot.yml

Because:
* We were seeing some [CI failures](https://app.circleci.com/pipelines/github/mozilla/fxa/37435/workflows/dfd7a914-a054-4ee8-aa13-ba2fce454788/jobs/399571) after https://github.com/mozilla/fxa/pull/14748 was merged and had to [revert the update](https://github.com/mozilla/fxa/pull/14766).
* Additionally, per FXA-5948, prior updates have caused other issues.
This commit:
* Temporarily ignores esbuild updates.
Closes #No issue

chore(deps): temporarily ignore esbuild updates

---

.circleci/run-list-parallel.sh

- Code would error out if the operations list was empty.
- Code should gracefully exit if asked to run an empty list of operations.
- Gracefully exists when operations list is empty
Closes: FXA-6681
This was discovered when merging a train branch back to main. As a result it was a PR which had 0 changes, thereby causing an empty .lists file.

task(CI): Fix case when test list is empty

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/pages/Clear/index.stories.tsx
packages/fxa-settings/src/pages/Clear/index.test.tsx
packages/fxa-settings/src/pages/Clear/index.tsx

Because:
* We're converting content-server routes into React routes by extending fxa-settings
This commit:
* Creates the React version of the '/clear' page, including tests, stories, and functionality
* Adds this route to the simpleRoutes list to be served by the React app
closes FXA-6113
---
To test this, after enabling the feature flag (see routing doc linked in partner work) create an account under 13. Observe how `/` redirects to `/cannot_create_account`. Now hit ~`cannot_create_account?showReactApp=true`~ `/clear?showReactApp=true` and then hit `/` and see it doesn't redirect you.
I don't **think** we want any metrics data on this page, but I'm going to make a note in the spreadsheet about this page so we can double check with Product.

feat(react): Recreate '/clear' page + functionality in React

---

packages/fxa-shared/speed-trap/navigation-timing.js

- `this` @ line 76 in `diffL1` in `diff` may be undefined rather than the class instance object since `diffL1` is a `function`.
- Replaces `function diffL{1,2} ()` with `const diffL{1, 2} = () =>`.
Thanks @ionathanch

fix(speed-trap): replace `function` with `=>`

---

packages/fxa-settings/src/components/Ready/en.ftl
packages/fxa-settings/src/components/Ready/index.test.tsx
packages/fxa-settings/src/components/Ready/index.tsx
packages/fxa-settings/src/pages/CompleteSignin/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordConfirmed/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.test.tsx
packages/fxa-settings/src/pages/Signup/SignupConfirmed/index.stories.tsx
packages/fxa-settings/src/pages/Signup/SignupConfirmed/index.test.tsx
packages/fxa-settings/src/pages/Signup/SignupConfirmed/index.tsx

* We're converting the remaining content-server Backbone views to React. The first step in doing so is to recreate each view in React and house it in storybook.
* Recreates the signup_confirmed/signup_verified views in React, adds basic tests, and adds the view to views accepted by the Ready component.
Closes #https://mozilla-hub.atlassian.net/browse/FXA-6433
Before:
After:
Still needs all events added to the metrics excel doc

storybook(fxa-settings): add signup_confirmed to storybook

---

.circleci/create-lists.sh

- There is logic to gracefully exit when an operations list is empty.
- Creates an empty file when operations lists are created.
Closes: #FXA-6701

fix(CI): initialize empty lists

---

packages/fxa-react/lib/test-utils/index.ts
packages/fxa-settings/src/components/Ready/en.ftl
packages/fxa-settings/src/components/Ready/index.test.tsx
packages/fxa-settings/src/components/Ready/index.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.test.tsx
packages/fxa-settings/src/pages/SigninBounced/index.test.tsx
packages/fxa-settings/src/pages/SigninBounced/mocks.tsx
packages/fxa-settings/src/pages/SigninConfirmed/index.test.tsx
packages/fxa-settings/src/pages/SigninReported/index.test.tsx
packages/fxa-settings/src/pages/Signup/PrimaryEmailVerified/index.stories.tsx
packages/fxa-settings/src/pages/Signup/PrimaryEmailVerified/index.test.tsx
packages/fxa-settings/src/pages/Signup/PrimaryEmailVerified/index.tsx
packages/fxa-settings/src/pages/Signup/PrimaryEmailVerified/mocks.tsx

* We are converting existing content-server routes to React by extending fxa-settings
* Create the React version of the `/primary_email_verified` page, with initial metrics, tests and l10n
* Modify the Ready component to render the primary_email_verified strings, and add l10n for default (no serviceName)
* Update TestAllL10n function to support ftl vars
* Replace instances of TestL10n with TestAllL10n in all pages that use the Ready component (excluding components that have strings with embedded tags, not yet supported by TestAllL10n) to ensure all ftl strings are tested
Closes: #FXA-6431

feat(react): Recreate PrimaryEmailVerified in React

---

packages/fxa-payments-server/src/components/PaymentForm/index.tsx

- Loading spinner does not show when changing payment method and hitting submit
- Removes loading spinner from Localized component, so that it is rendered separately from localization.
Closes: #FXA-6257

fix(payments): show loading spinner on pay change

---

packages/fxa-settings/src/pages/Signin/en.ftl

* brand-pocket was recently changed to -brand-pocket brand term
* Update Signin's ftl file to use -brand-pocket (issue spotted by @bcolsson)

fix(l10n): Pocket brand term

---

packages/fxa-payments-server/src/lib/hooks.tsx
packages/fxa-payments-server/src/routes/Product/index.test.tsx
packages/fxa-payments-server/src/routes/Product/index.tsx

- When a customer was signed in and the product page was refreshed, the verified signin url was appended to the existing url instead of replacing it, breaking the page and affecting customer experience
- replaces navigate with navigateToUrl
Closes: FXA-6147

fix(payments): update signin redirect to replace url

---

.circleci/run-list-parallel.sh

- When there was just a single integration test suite to run, the second integration test suite in the CI would fail.
- Checks to make sure the split file exists before running it.
Addresses this scenario:

bug(CI): Fix edge case where there are fewer operations than groups

---

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/third-party-auth.js
packages/fxa-content-server/app/scripts/views/mixins/third-party-auth-experiment-mixin.js
packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/third-party-auth.js

- We want to enable third party auth in stage to let QA test
- This enables third party auth for all non-sync services
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6592
To test this, you will need to force the experiment via `http://localhost:3030/signin?forceExperiment=thirdPartyAuth&forceExperimentGroup=treatment`. In stage/prod we still want the rollout to be 0%.

feat(auth): Enable third party auth for non-sync service (used only in stage)

---

packages/fxa-payments-server/src/components/PlanDetails/index.test.tsx
packages/fxa-payments-server/src/components/PlanDetails/index.tsx

Because:
* we do not want to show any 0.00 tax amounts in plan details
This commit:
* adds a check for both single or multiple tax amounts that the amount is not zero
Closes #FXA-6574

fix(payments): do Not Display Zero Tax Amounts In Plan Details

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/test/local/payments/fixtures/stripe/payment_method.json
packages/fxa-auth-server/test/local/payments/stripe.js

- payment_method.attached is processed when the payment method in stripe no longer has a customer attached.
- In some circumstances, such as seen during blocking many fraudulent payments, it is possible that the payment_method.detached event is processed before the payment_method.attached method. In this scenario, the payment method customer field would already be null.
- Return early if the customer field is null on the payment method.
Closes: #FXA-6564

fix(payments): payment method customer null

---

docs/adr/0034-use-structurizr-diagrams.md

Because:
* We want to use Structurizr to generate diagrams for our software architecture.
This commit:
* Adds an ADR for using Structurizr to generate diagrams for our software architecture.
Issue FXA-6627

docs(adr): add structurizr diagrams adr

---

packages/fxa-payments-server/src/components/PaymentConfirmation/index.stories.tsx
packages/fxa-payments-server/src/components/PaymentConfirmation/index.test.tsx
packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx
packages/fxa-payments-server/src/components/PlanDetails/index.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionSuccess/index.tsx

Because:
* we were only taking into account the plan amount and potential discount amount in the payment confirmation component, we were displaying the wrong price if taxes are applied
This commit:
* passes in the invoice fetched from the plan details component rather than the coupon, this will take into account the plan price, potential discount amount, and applicable taxes
Closes #FXA-6364

fix(payments): display Invoice Amount In Payment Confirmation

---

.circleci/run-list-parallel.sh
packages/functional-tests/pages/login.ts
packages/functional-tests/pages/signinTokenCode.ts
packages/functional-tests/tests/signUp/signUpWithCode.spec.ts
packages/functional-tests/tests/syncV3/signUp.spec.ts
packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts
packages/fxa-content-server/tests/functional.js

- As part of the playwright test migration, the [sync v3 email first tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sync_v3_email_first.js)  and [Sign up with code tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sign_up_with_code.js) have been rewritten in this PR.
- contains [sync v3 email first tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sync_v3_email_first.js) split into 2 files.
- [Sign up with code tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sign_up_with_code.js)
Closes: #[FXA-5905](https://mozilla-hub.atlassian.net/browse/FXA-5905) [FXA-5916](https://mozilla-hub.atlassian.net/browse/FXA-5916)
_Put …

test(functional): rewrite sync v3 email first and sign up tests

---

packages/fxa-auth-server/docs/swagger/misc-api.ts
packages/fxa-auth-server/docs/swagger/shared/descriptions.ts
packages/fxa-auth-server/docs/swagger/subscriptions-api.ts
packages/fxa-auth-server/lib/routes/subscriptions/mozilla.ts
packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/lib/routes/validators.js

- we need to add details to the subscription endpoints in our API docs.
- adds what each subscription endpoint returns
Closes: [FXA-4902](https://mozilla-hub.atlassian.net/browse/FXA-4902)
[FXA-4902]: https://mozilla-hub.atlassian.net/browse/FXA-4902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(auth-server): Add details to subscription endpoints

---

packages/fxa-settings/src/pages/InlineTotpSetup/en.ftl
packages/fxa-settings/src/pages/InlineTotpSetup/index.stories.tsx
packages/fxa-settings/src/pages/InlineTotpSetup/index.test.tsx
packages/fxa-settings/src/pages/InlineTotpSetup/index.tsx
packages/fxa-settings/src/pages/InlineTotpSetup/mocks.ts

* We're converting the remaining Backbone views to React. The first step in doing so is to recreate them in React and house the React versions in the fxa settings storybook.
* Recreates the UI elements of inline_totp_setup in React, with localization and tests.
Closes #https://mozilla-hub.atlassian.net/browse/FXA-6629
I still need to add events into the metrics doc!
Also, this does *not* implement either getting the code needed, or getting the QR code, so there is no display of either.

storybook(fxa-settings): add inline_totp_setup to storybook

---

.circleci/config.yml

- Not all jobs were running in the test_and_deploy_tag
- Adds filter configs to each job. This typically isn't necessary, but apparently when we ignore all branches it is.
- Fixes a clobbered fix in the Checkout Branch job
Example Broken State:
Example Corrected State:

bug(ci): Fix test_and_deploy_tag workflow

---

packages/functional-tests/pages/products/index.ts
packages/functional-tests/pages/products/subscriptionManagement.ts
packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts
packages/functional-tests/tests/subscription-tests/coupons-ui-tests/ui-tests.spec.ts

In efforts to increase test coverage for Subplat regression , added automated tests for:
- Update mode of payment for Paypal
- Edit existing subscription
Contains test for:
- Updating mode of payment for Paypal
- Editing existing subscription
Closes: #[FXA-6247](https://mozilla-hub.atlassian.net/browse/FXA-6247) [FXA-6245](https://mozilla-hub.atlassian.net/browse/FXA-6245)
[FXA-6247]: https://mozilla-hub.atlassian.net/browse/FXA-6247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FXA-6245]: https://mozilla-hub.atlassian.net/browse/FXA-6245?atlOrigin=eyJpIjoiNWR …

test(subplat): create  update payment for paypal test

---

packages/fxa-settings/src/components/ChooseNewsletters/en.ftl

- Mozilla and Firefox should use the term instead of string
- Replaces strings with term reference

chore(l10n): Fix brand references in ftl message

---

.circleci/config.yml

- Storybook was removed from the test pr workflow and needs to be restored.
- Adds storybook back into the the test pr workflow.

Add back in build story book

---

packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-settings/src/components/CardHeader/index.stories.tsx
packages/fxa-settings/src/components/CardHeader/index.test.tsx
packages/fxa-settings/src/components/CardHeader/index.tsx
packages/fxa-settings/src/components/CardHeader/mocks.tsx
packages/fxa-settings/src/components/DeviceInfoBlock/en.ftl
packages/fxa-settings/src/components/DeviceInfoBlock/index.stories.tsx
packages/fxa-settings/src/components/DeviceInfoBlock/index.test.tsx
packages/fxa-settings/src/components/DeviceInfoBlock/index.tsx
packages/fxa-settings/src/components/DeviceInfoBlock/mocks.tsx
packages/fxa-settings/src/lib/types.ts
packages/fxa-settings/src/pages/Pair/Auth/WaitForSupp/en.ftl
packages/fxa-settings/src/pages/Pair/Auth/WaitForSupp/index.stories.tsx
packages/fxa-settings/src/pages/Pair/Auth/WaitForSupp/index.test.tsx
packages/fxa-settings/src/pages/Pair/Auth/WaitForSupp/index.tsx
packages/fxa-settings/src/pages/Pair/Auth/WaitForSupp/mocks.tsx
packages/fxa-settings/src/pages/Pair/Supp/WaitForAuth/en.ftl
packages/fxa-settings/src/pages/Pair/Supp/WaitForAuth/index.stories.tsx
packages/fxa-settings/src/pages/Pair/Supp/WaitForAuth/index.test.tsx
packages/fxa-settings/src/pages/Pair/Supp/WaitForAuth/index.tsx
packages/fxa-settings/src/pages/Pair/Supp/WaitForAuth/mocks.tsx

* We are converting content-server views to React, and are starting by building out the front-end in Storybook with initial tests, metrics, l10n.
* Create a new DeviceInfoBlock component with initial storybook, tests and l10n.
* Create the PairWaitForAuth and PairWaitForSupp pages in React, with initial tests, metrics, l10n.
* Update CardHeader component to include elems in FtlMsg and allow subheadingText.
Closes: #FXA-6633
With minimal metadata:
With complete metadata and error banner:
The WaitForSupp and WaitForAuth pages are the same visually, but are endpoints for different routes and have different metric events. I've kept them separate to allow for individual control/changes to each of these routes, and because the functional follow-up ticket may …

storybook(fxa-settings): Recreate WaitForAuth and WaitForSupp

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe.js

- When a new payment method is attached, and subscriptions have automatic tax enabled, do not add tax rates.
- Updates payment_method.attached webhook logic to skip updating subscription taxes when automatic tax is enabled for that subscription
Closes: #FXA-6587
To easily reproduce this bug follow these listed steps.
1. Create a new FxA account and subscribe to a European price. (e.g. [123 Done Pro - EU](http://localhost:3030/subscriptions/products/prod_GqM9ToKK62qjkK?plan=price_1H8NnnBVqmGyQTMaLwLRKbF3))
2. Navigate to Subscription Management page and add new Payment Method. (Can be same as before)
3. Note response from webhook event `payment_method.attached`
- Before fix: Webhook returns with status code 500, and there are attempts to update the …

fix(subscription): on pm.attached skip tax where automatic tax enabled

---

packages/fxa-auth-server/lib/error.js
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js

- Even though the /preview/invoice api returns with a 500 Internal Server Error, the error is not reported to Sentry.
- Explicitly throw a 500 error, with relevant data.
- Previous logic would catch the Stripe error and re-throw it. However, since the error received from Stripe is a 400 error, the auth server Sentry reporting logic ignores these errors and does not report it to Sentry.
Closes: #FXA-6693

fix(sub): invoice preview error not in Sentry

---

packages/fxa-shared/package.json

Reverts mozilla/fxa#14820
Looks like this is causing some build errors in main.

Revert "chore(deps): bump @opentelemetry/sdk-trace-web from 1.7.0 to 1.9.1"

---

packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.tsx
packages/fxa-payments-server/src/components/PaymentMethodHeader/index.test.tsx

- Links to Terms of Service or Privacy Notice docs in the payment consent box would open on the same page, instead of opening a new tab.
- The HTML a tags were replaced with the LinkExternal component and now open in a new tab.
Closes: #FXA-6753

fix(payments): some checkout links do not open a new tab

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-react/lib/utils.tsx
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/components/LinkRememberPassword/index.tsx
packages/fxa-settings/src/components/Settings/PageRecentActivity/index.tsx
packages/fxa-settings/src/lib/auth-errors/en.ftl
packages/fxa-settings/src/models/Account.ts
packages/fxa-settings/src/pages/ResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/index.tsx

- We need to add the functionality to initate password reset
- Adds the gql resolver to password reset react view
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6123
This PR also removes the `canGoBack` logic from password reset. Using the browser back navigation does the same.

feat(react): Update reset password react view to use gql

---

packages/functional-tests/pages/products/index.ts
packages/functional-tests/pages/products/subscriptionManagement.ts
packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts

- Paypal subscription tests were failing in CircleCi very consistently and upon looking closer it was found that it was happening mostly because paypal sandbox site was taking alot of time to load or was not loading properly.
- Adds 'state' to the load statements where ever the issue was found. 
- Made sure that now all the tests passes in CircleCi (ran the workflow thrice and it passed each time)
Closes: #[FXA-6780](https://mozilla-hub.atlassian.net/browse/FXA-6780)
[FXA-6780]: https://mozilla-hub.atlassian.net/browse/FXA-6780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …

Fix(test): fix failing subscription test

---

packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts
packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts

- The Paypal sanbox is having load issues and because of which tests are failing. Currently disabling the current tests until I have a fix ready.
- Diasbles paypal subscription tests
Closes: #[FXA-6786](https://mozilla-hub.atlassian.net/browse/FXA-6786)
[FXA-6786]: https://mozilla-hub.atlassian.net/browse/FXA-6786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(functional): disable flaky paypal test

---

packages/fxa-settings/src/pages/Pair/Unsupported/en.ftl
packages/fxa-settings/src/pages/Pair/Unsupported/index.stories.tsx
packages/fxa-settings/src/pages/Pair/Unsupported/index.test.tsx
packages/fxa-settings/src/pages/Pair/Unsupported/index.tsx
packages/fxa-settings/src/pages/Pair/Unsupported/mock.ts

* As we convert all Backbone views to React, the first step is to recreate all views, using React, in storybook
* Recreates the pair/unsupported view with page view metrics, l10n and a11y
Closes #https://mozilla-hub.atlassian.net/browse/FXA-6428
Before:
After:
I also added the images to Storybook, let me know if you want me to remove that!

storybook(fxa-settings): add pair/unsupported to React storybook

---

packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-settings/src/pages/Pair/Supp/index.stories.tsx
packages/fxa-settings/src/pages/Pair/Supp/index.test.tsx
packages/fxa-settings/src/pages/Pair/Supp/index.tsx
packages/fxa-settings/src/pages/Pair/Supp/mocks.ts

* We are converting content-server views to React, and are starting by documenting the front-end in storybook
* Create a new Supp component in React, with initial tests and metrics.
* Add new metrics event for page view.
Closes: #FXA-6427

storybook(fxa-settings): Recreate pair/supp view in React

---

packages/functional-tests/tests/subscription-tests/coupons-ui-tests/coupon.spec.ts
packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts
packages/functional-tests/tests/subscription-tests/subscription.spec.ts

- The Paypal sanbox is having load issues and because of which tests are failing. Currently disabling the current tests until I have a fix ready.
- Created bug [FXA - 6788](https://mozilla-hub.atlassian.net/browse/FXA-6788 )to track the issue 
- Diasbles paypal subscription tests

test(functional): disable all paypal tests

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/test/local/payments/stripe.js

- the SubscriptionUpgrade email displayed prices without tax. The totals should match their respective invoices.
- updates so that SubscriptionUpgrade uses the totals from the invoices, if applicable.
Closes: [FXA-6375](https://mozilla-hub.atlassian.net/browse/FXA-6375)
[FXA-6375]: https://mozilla-hub.atlassian.net/browse/FXA-6375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(email): Revise SubscriptionUpgrade email to reflect invoice total

---

packages/fxa-settings/src/constants/index.tsx
packages/fxa-settings/src/pages/Pair/Index/en.ftl
packages/fxa-settings/src/pages/Pair/Index/index.stories.tsx
packages/fxa-settings/src/pages/Pair/Index/index.test.tsx
packages/fxa-settings/src/pages/Pair/Index/index.tsx
packages/fxa-settings/src/pages/Pair/Index/mocks.ts
packages/fxa-settings/src/pages/Pair/Success/index.test.tsx
packages/fxa-settings/src/pages/Pair/Success/index.tsx

* The first step in rebuilding all of the Backbone views in react, is adding a react version to Storybook
* Adds the pair view, with l10n, a11y, and basic tests into Storybook
Closes #FXA-6424
Before:
After:
I need to enter metrics into the doc, and also need to create a ticket specifically for the QR code logic

storybook(fxa-settings): adding pair view to storybook

---

packages/fxa-settings/src/components/DeviceInfoBlock/index.stories.tsx
packages/fxa-settings/src/components/DeviceInfoBlock/index.test.tsx
packages/fxa-settings/src/components/DeviceInfoBlock/index.tsx
packages/fxa-settings/src/components/DeviceInfoBlock/mocks.tsx
packages/fxa-settings/src/lib/types.ts
packages/fxa-settings/src/pages/Pair/AuthAllow/index.stories.tsx
packages/fxa-settings/src/pages/Pair/AuthAllow/index.test.tsx
packages/fxa-settings/src/pages/Pair/AuthAllow/index.tsx
packages/fxa-settings/src/pages/Pair/AuthComplete/en.ftl
packages/fxa-settings/src/pages/Pair/AuthComplete/indes.stories.tsx
packages/fxa-settings/src/pages/Pair/AuthComplete/index.test.tsx
packages/fxa-settings/src/pages/Pair/AuthComplete/index.tsx
packages/fxa-settings/src/pages/Pair/AuthComplete/mocks.tsx
packages/fxa-settings/src/pages/Pair/AuthWaitForSupp/index.tsx
packages/fxa-settings/src/pages/Pair/SuppAllow/index.tsx
packages/fxa-settings/src/pages/Pair/SuppWaitForAuth/index.tsx

* We are converting content-server to React, and are starting by building out the front-end views in Storybook.
* Creates a new AuthComplete page in react, with initial storybook, tests, metrics and l10n.
* Clean up props in DeviceInfoBlock component
* Small error fixes in AuthWaitForSupp, SuppWaitForAuth
Closes: #FXA-6636

storybook(fxa-settings): Recreate Pair/AuthComplete in React

---

packages/fxa-auth-server/lib/error.js
packages/fxa-auth-server/lib/routes/account.ts
packages/fxa-auth-server/test/local/routes/account.js
packages/fxa-content-server/app/scripts/lib/auth-errors.js
packages/fxa-content-server/app/scripts/views/sign_in_password.js

- Third party auth account don't have a password set and won't be able to login to Sync
- When a users attempts to login using email/password, prompt them to reset their password
Closes: https://mozilla-hub.atlassian.net/browse/FXA-5164

feat(auth): Prompt users to set password during login if none present

---

packages/functional-tests/tests/syncV3/signIn.spec.ts

As part of the playwright test migration, the [sync v3 Sign in tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sync_v3_sign_in.js) have been rewritten in this PR.
contains [sync v3 Sign in tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sync_v3_sign_in.js)
Closes: #[FXA-5924](https://mozilla-hub.atlassian.net/browse/FXA-5924)
[FXA-5924]: https://mozilla-hub.atlassian.net/browse/FXA-5924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(functional): rewrite sync v3 sign in tests using playwright

---

packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-settings/src/pages/Pair/AuthTotp/index.stories.tsx
packages/fxa-settings/src/pages/Pair/AuthTotp/index.test.tsx
packages/fxa-settings/src/pages/Pair/AuthTotp/index.tsx

* We're recreating the remaining backbone views in React in storybook as a preliminary step to replacing the backbone views. This recreates `pair/auth/totp`. In backbone, this view uses the same template as signin_totp_code. The two main differences are 1. the action which happens on submit, and 2. this view hides the alternatives to totp. I've opted to create a new component since so many of our components have ended up being a bit unwieldy due to reuse, but I'm on the fence as to whether that was the right choice. Let me know your opinions! Happy to change it.
* Copies the `signin_totp_code` code with the needed changes. Since we reuse strings, it doesn't involve any new strings. It does involve slightly different metrics.
Closes #FXA-6751
Before: …

storybook(fxa-settings): add pair/auth/totp view to storybook

---

packages/fxa-auth-server/lib/geodb.js
packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/lib/types.ts
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
packages/fxa-geodb/lib/location.js

* Stripe IP address based taxation has several problems related to placing customers in taxable locations
* We can make our decision about whether to tax a user based on their country/zip resolvability prior to enabling Stripe tax
* Utilizes Maxmind GeoIP2 to place a user in a taxable location
Closes: FXA-6787

fix(auth): Use maxmind for Stripe tax

---

packages/fxa-auth-server/package.json
packages/fxa-auth-server/scripts/audit-orphaned-customers.ts

- there are Stripe customers whose UID do not exist in FxA records and, therefore, are orphaned customers as FxA is required to access/utilize the subscription.
Closes: [FXA-6310](https://mozilla-hub.atlassian.net/browse/FXA-6310)
[FXA-6310]: https://mozilla-hub.atlassian.net/browse/FXA-6310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(payments): Add script to audit orphaned accounts

---

packages/fxa-auth-client/lib/client.ts
packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-graphql-api/src/gql/account.resolver.ts
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/models/Account.ts
packages/fxa-settings/src/models/hooks.ts
packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/en.ftl
packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.tsx
packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/mocks.tsx
packages/fxa-settings/src/pages/ResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/index.tsx

- We need to poll the status of password reset state
- Adds `useInterval` hook to setup polling
- Adds gql query to get password forgot status
- Updates password reset page to navigate to confirm password reset page
- Passes token via `state` params in `useNavigate`, maybe a better way to do this?
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6121
This still needs some tests

feat(react): Add password reset confirm page functionality

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/components/AppLayout/index.tsx
packages/fxa-settings/src/components/Ready/en.ftl
packages/fxa-settings/src/components/Ready/index.stories.tsx
packages/fxa-settings/src/components/Ready/index.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/en.ftl
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.tsx

* We want to activate the ResetPasswordWithRecoveryKeyVerified page behind a feature flag
* Activate React version of ResetPasswordWithRecoveryKeyVerified behind showReactApp flag
* Add isSync variation and optional error Banner to the Ready component
* Move Head component from App to AppLayout to pass in page title prop
* Fix ResetPasswordWithRecoveryKeyVerified metrics tests
Closes: #FXA-6128
Current (default) content-server view:
New React default page:
New React isSync page:

feat(react): Add functionality to ResetPasswordWithRecoveryKeyVerified

---

packages/fxa-settings/src/components/ChooseWhatToSync/en.ftl
packages/fxa-settings/src/components/GetDataTrio/en.ftl
packages/fxa-settings/src/components/GetDataTrio/index.tsx
packages/fxa-settings/src/components/Settings/ConnectedServices/en.ftl
packages/fxa-settings/src/components/Settings/ConnectedServices/index.tsx
packages/fxa-settings/src/components/Settings/ModalVerifySession/index.tsx
packages/fxa-settings/src/components/Settings/PageSecondaryEmailVerify/index.tsx
packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.tsx
packages/fxa-settings/src/components/images/index.tsx
packages/fxa-settings/src/pages/InlineTotpSetup/en.ftl
packages/fxa-settings/src/pages/InlineTotpSetup/index.tsx
packages/fxa-settings/src/pages/Pair/AuthWaitForSupp/index.tsx
packages/fxa-settings/src/pages/Pair/Success/en.ftl
packages/fxa-settings/src/pages/Pair/Success/index.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx
packages/fxa-settings/src/pages/Signin/SigninBounced/index.tsx
packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx
packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx

* Localized messages will not render correctly if `elems`, `vars`, `attrs` attributes are omitted from the FtlMsg element.
* Audit fxa-settings ftl files for `</`, `{ $`, and ` .` and correct any corresponding FtlMsg elements that are missing required attributes.
* Correct ftl strings that contain misnamed elements
* Correct ftl id that had not been updated to match new string.
Closes: #FXA-6749

fix(fxa-settings): Add elems and vars to FtlMsg when missing

---

packages/fxa-settings/src/pages/ConnectAnotherDevice/en.ftl
packages/fxa-settings/src/pages/ConnectAnotherDevice/index.tsx

* We have two different ftl strings with the same ftl id
* Changes one of the ftl ids in the tsx and also in the ftl file so that all ids are unique
Closes #N/A (Change is so small that I don't think it justifies a ticket -- was requested over slack and also in the original PR for FXA-6752 after the PR was closed.)

fix(fxa-settings): change duplicate ftl id to a unique id

---

.circleci/config.yml

- Flaky integration tests are a drag
- Flaky integration tests are resulting in functional test job cancellations make it hard to validate changes
- Disables the fail-fast step, so that functional tests run despite integration test failures.
This is a temporary change. Hopefully, FXA-6781 uncovers the actual issue.

task(CI): Disable fail-fast step for integration tests

---

packages/fxa-admin-server/scripts/gen_keys.ts
packages/fxa-auth-server/scripts/gen_keys.js

- Gen keys script fails during pem2jwk conversion due to new pem format used by openssl 3.0
- If pem2jwk conversion fails due to the pem format error, then generate a new pem key using the --traditional flag
Closes: #FXA-5690

fix(auth): gen keys workaround for openssl 3.0

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe.js

* Generating subscription email would throw an error if latest_invoice was not present.
* Falls back to the old behavior in instances where latest_invoice is not present.
Closes FXA-6817

fix(auth): errors when generating subscription email

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-graphql-api/src/gql/account.resolver.ts
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/components/LinkRememberPassword/index.tsx
packages/fxa-settings/src/components/Settings/PageRecentActivity/index.test.tsx
packages/fxa-settings/src/models/Account.ts
packages/fxa-settings/src/models/hooks.ts
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx
packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordConfirmed/index.tsx

- We need to wire in the logic to finish password reset flow
- Updates account model to add functions to complete password reset
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6125
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6122

feat(react): Add password reset confirm page

---

packages/fxa-settings/package.json

- Memory is spiking in CI
- Adds `--runInBand` to the integration test commands
It appeared that most the jest tests have `--runInBand` applied. Settings uses jest, but does so through rescripts so I am guessing that this just got overlooked.

task(settings): Add --runInBand option

---

packages/fxa-settings/.storybook/decorators.tsx
packages/fxa-settings/src/components/FormVerifyCode/index.tsx

* Branding terms were displayed as variables in the fxa-settings storybook.
* FormVerifyCode's label l10n was getting added as child instead of a label attribute.
* Add 'branding' to fxa-settings' storybook l10n bundle.
* Update FormVerifyCode to use ftlMsgResolver instead of wrapping the input in an FtlMsg.
Issue #FXA-6299
Before - Branding not loading:
After - branding now loading:
Before - label incorrectly applied:
After - label correctly applied

fix(storybook): Add missing branding package in settings storybook

---

packages/fxa-shared/test/scripts/feature-flags.js

- There wasn't much headroom on feature flag tests that used cp.exec in lower resource scenarios
- Increases test timeout for feature flags to 5s
This is part of FXA-6781. Not the silver bullet, but definitely a potential source of random flakiness.

task(CI): Increase test timeout on feature flag tests

---

.circleci/run-list-parallel.sh

- Bash warnings were being printed out in the CI.
- Changes syntax to address warnings.

task(CI): Fix bash warnings coming from run-list-parallel

---

packages/fxa-settings/src/lib/reliers/relier-factory.test.ts
packages/fxa-settings/src/lib/reliers/relier-factory.ts
packages/fxa-settings/src/models/hooks.ts
packages/fxa-settings/src/models/reliers/base-relier.test.ts
packages/fxa-settings/src/models/reliers/base-relier.ts
packages/fxa-settings/src/models/reliers/browser-relier.ts
packages/fxa-settings/src/models/reliers/oauth-relier.ts

- The async nature of the relier factory was causing some problems
- Updates BaseRelier model so that async operations aren't necessary for creation.
- Adds async clientInfo and subscriptionInfo properties.
- Kicks off resolution of clientInfo and subscriptionInfo properties in factory, but doesn't await them.
- Controls should now ensure async properties have been resolved. This can be done with useEffect.
This is a nice to have for some of the react conversion work such as FXA-6127.

task(settings): Make relier factory synchronous

---

packages/functional-tests/pages/relier.ts
packages/functional-tests/tests/oauth/syncSignIn.spec.ts
packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts

As part of the playwright test migration, the [Oauth sync sign in](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/oauth_sync_sign_in.js) have been rewritten in this PR.
contains [Oauth sync sign in](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/oauth_sync_sign_in.js)
Closes: #[FXA-5895](https://mozilla-hub.atlassian.net/browse/FXA-5895)
[FXA-5895]: https://mozilla-hub.atlassian.net/browse/FXA-5895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(functional): rewrite oauth sync tests using playwright

---

packages/functional-tests/pages/login.ts
packages/functional-tests/tests/signUp/signUp.spec.ts

As part of the playwright test migration, the [sign up tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sign_up.js) have been rewritten in this PR.
contains [sign up tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sign_up.js) 
Closes: #[FXA-5922](https://mozilla-hub.atlassian.net/browse/FXA-5922)
[FXA-5922]: https://mozilla-hub.atlassian.net/browse/FXA-5922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Rewrite sign up tests using Playwright

---

packages/fxa-auth-server/lib/payments/stripe-formatter.ts
packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/routes/validators.js
packages/fxa-auth-server/test/local/payments/fixtures/stripe/invoice_open.json
packages/fxa-auth-server/test/local/payments/fixtures/stripe/invoice_paid.json
packages/fxa-auth-server/test/local/payments/fixtures/stripe/invoice_paid_subscription_create.json
packages/fxa-auth-server/test/local/payments/fixtures/stripe/invoice_paid_subscription_create_tax.json
packages/fxa-auth-server/test/local/payments/stripe-formatter.js
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/validators.js
packages/fxa-auth-server/test/remote/subscription_tests.js
packages/fxa-payments-server/src/components/PaymentConfirmation/index.stories.tsx
packages/fxa-payments-server/src/components/PaymentConfirmation/index.test.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.stories.tsx
packages/fxa-payments-server/src/lib/mock-data.tsx
packages/fxa-payments-server/src/lib/test-utils.tsx
packages/fxa-payments-server/src/routes/Product/index.stories.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx
packages/fxa-shared/dto/auth/payments/invoice.ts
packages/fxa-shared/subscriptions/types.ts
packages/fxa-shared/test/subscriptions/metadata.ts

- Need to return certain fields from the latest invoice associated with the customers subscriptions.
- Adds latest_invoice_items which returns the same values as the invoice preview api.
- Does not change latest_invoice, which remains the latest_invoice.number
Closes: #FXA-6831

task(subscriptions): add invoice to billing subs api

---

packages/fxa-payments-server/src/components/PlanDetails/index.test.tsx
packages/fxa-payments-server/src/components/PlanDetails/index.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx

- Total price should still be displayed when total price is zero.
- This could happen when a 100% promotion is applied.
- Show total for zero price.
Closes: #FXA-6871
Local testing:
- Price: Any price from Product `123Done Pro` (e.g. [plan_GqM9N6qyhvxaVk](localhost:3031/checkout/prod_GqM9ToKK62qjkK?plan=plan_GqM9N6qyhvxaVk))
- Promotion code: `EVERYTHING`
Checkout
Success screen

fix(subscriptions): show total for zero price

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/components/PageWithLoggedInStatusState/index.test.tsx
packages/fxa-settings/src/components/PageWithLoggedInStatusState/index.tsx
packages/fxa-settings/src/components/PageWithLoggedInStatusState/mocks.tsx
packages/fxa-settings/src/components/Ready/index.stories.tsx
packages/fxa-settings/src/components/Ready/index.test.tsx
packages/fxa-settings/src/components/Ready/index.tsx
packages/fxa-settings/src/components/images/index.test.tsx
packages/fxa-settings/src/components/images/index.tsx
packages/fxa-settings/src/lib/gql.test.ts
packages/fxa-settings/src/lib/gql.ts
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordConfirmed/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordConfirmed/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordConfirmed/index.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.tsx
packages/fxa-settings/src/pages/Signin/SigninConfirmed/index.stories.tsx
packages/fxa-settings/src/pages/Signin/SigninConfirmed/index.test.tsx
packages/fxa-settings/src/pages/Signin/SigninConfirmed/index.tsx
packages/fxa-settings/src/pages/Signup/PrimaryEmailVerified/index.stories.tsx
packages/fxa-settings/src/pages/Signup/PrimaryEmailVerified/index.test.tsx
packages/fxa-settings/src/pages/Signup/PrimaryEmailVerified/index.tsx
packages/fxa-settings/src/pages/Signup/SignupConfirmed/index.stories.tsx
packages/fxa-settings/src/pages/Signup/SignupConfirmed/index.test.tsx
packages/fxa-settings/src/pages/Signup/SignupConfirmed/index.tsx

* We want to move the primary_email_verified React page into the React app behind a flag
* Allows us to check if a user is logged in without being redirected to the signin page if we are at a URL outside of the Settings app
* Makes the `primary_email_verified` page visible to both logged in and logged out users behind a feature flag
* Shows different copy in the Ready view based on a user's logged-in status
* Create a new wrapper component to check if the user is logged in or logged out, and keep the state handling out of presentation component
Closes #FXA-6494
Before:
After:
The way that the Settings app keeps track of whether or not a user is signed in is actually in the way we set up graphql. In `packages/fxa-settings/src/lib/gql.ts`, we listen to …

feature(fxa-settings): add functionality to primary_email_verified

---

packages/fxa-auth-server/lib/routes/emails.js
packages/fxa-auth-server/lib/routes/password.js
packages/fxa-auth-server/lib/routes/recovery-key.js
packages/fxa-auth-server/lib/routes/totp.js
packages/fxa-auth-server/lib/routes/utils/security-event.js
packages/fxa-auth-server/test/local/account-events.js
packages/fxa-auth-server/test/local/email/utils.js
packages/fxa-auth-server/test/local/routes/emails.js
packages/fxa-auth-server/test/local/routes/password.js
packages/fxa-auth-server/test/local/routes/recovery-keys.js
packages/fxa-auth-server/test/local/routes/totp.js
packages/fxa-auth-server/test/mocks.js

- We are increasing the security events we record
- Adds a wrapper function to simplify security events being recorded from route handlers
- Fixes a couple issues with mocks in unit tests
- Adds:
- account.secondary_email_-ed
- account.secondary_email_removed
- account.primary_secondary_swapped
- account.recovery_key_-ed
- account.recovery_key_challenge_failure
- account.recovery_key_challenge_success
- account.recovery_key_removed
- account.password_reset_requested
- account.password_reset_success
- account.password_-ed
- account.password_changed
Closes: 
FXA-4923
FXA-4939
FXA-4940
FXA-4932
FXA-4933
FXA-4934
FXA-4935
FXA-4930
FXA-4931
FXA-4936
FXA-4937
This commit is based on top of fxa-4924
Here's a mapping between event names and issues:
FXA-4923 - …

Fxa 4924.2

---

package.json
packages/fxa-auth-server/scripts/convert-customers-to-stripe-automatic-tax.ts
packages/fxa-auth-server/scripts/convert-customers-to-stripe-automatic-tax/convert-customers-to-stripe-automatic-tax.ts
packages/fxa-auth-server/scripts/convert-customers-to-stripe-automatic-tax/helpers.ts
packages/fxa-auth-server/test/scripts/convert-customers-to-stripe-automatic-tax-helpers.ts
packages/fxa-auth-server/test/scripts/convert-customers-to-stripe-automatic-tax.ts
yarn.lock

* We need to geoip before saving the customer rather than using their IP address with Stripe directly.
* Parallelization speeds up the conversion process significantly
* Geocodes IP addresses prior to saving using fxa-geodb.
* Adds parallelization with rate limiting.
* Writes results to output CSV.
Closes FXA-6581
Closes FXA-6810

feat(auth): geoip, parallelization for automatic tax

---

packages/fxa-payments-server/src/lib/hooks.test.tsx
packages/fxa-payments-server/src/lib/hooks.tsx
packages/fxa-payments-server/src/lib/test-utils.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

- To support archived prices, the subscription management pages currently using the invoice preview api need to be refactored to use the invoice on the customer instead.
- In Subscription Management use invoice_latest_items instead of the invoice preview.
- Remove invoice preview logic from Subscription Management where its no longer used.
Closes: #FXA-6832
To test this locally you can use the following product and price.
- Product: prod_GqM9ToKK62qjkK
- Price: price_1MYuLZBVqmGyQTMa4pIWatVi
- URL: [link](http://localhost:3031/products/prod_GqM9ToKK62qjkK?plan=price_1MYuLZBVqmGyQTMa4pIWatVi)

task(subscriptions): in sub manage use invoice from customer

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/lib/gql.ts
packages/fxa-settings/src/pages/Signup/SignupConfirmed/index.stories.tsx
packages/fxa-settings/src/pages/Signup/SignupConfirmed/index.test.tsx
packages/fxa-settings/src/pages/Signup/SignupConfirmed/index.tsx

* We're moving the React components into the React app, to be conditionally shown behind a feature flag
* Moves the signup_confirmed/signup_verified view into the App and adds in the necessary metrics
Closes #FXA-6498, FXA-6496
Before:
After:
Metrics have been added to amplitude and to the spreadsheet.

feat(fxa-settings): setup signup_confirmed in react app

---

packages/fxa-auth-server/scripts/convert-customers-to-stripe-automatic-tax/convert-customers-to-stripe-automatic-tax.ts
packages/fxa-auth-server/test/scripts/convert-customers-to-stripe-automatic-tax.ts

- Do not update FPN subscriptions to Stripe automatic tax.
- Adds isEligibleSubscriptionProduct method to check if the product of a subscription is eligible to update automatic 
Closes: #FXA-6811

task(subscription): exclude fpn subs from tax enablement

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/components/FormVerifyCode/en.ftl
packages/fxa-settings/src/components/FormVerifyCode/index.stories.tsx
packages/fxa-settings/src/components/FormVerifyCode/index.tsx
packages/fxa-settings/src/components/FormVerifyCode/mocks.tsx
packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/en.ftl
packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.tsx
packages/fxa-settings/src/constants/index.tsx
packages/fxa-settings/src/pages/InlineTotpSetup/index.tsx
packages/fxa-settings/src/pages/Pair/AuthTotp/en.ftl
packages/fxa-settings/src/pages/Pair/AuthTotp/index.test.tsx
packages/fxa-settings/src/pages/Pair/AuthTotp/index.tsx
packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/en.ftl
packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.tsx
packages/fxa-settings/src/pages/Signin/SigninTokenCode/en.ftl
packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx
packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.test.tsx
packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.tsx
packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/en.ftl
packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.stories.tsx
packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.test.tsx
packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx
packages/fxa-settings/src/pages/Signup/index.tsx

* We want to make the page created in Storybook fully functional to match parity with the content-server page.
* Activate React route for ConfirmSignupCode.
* Add functionality to verify confirmation code
* Add functionality to resend a new code
* Clean up FormVerifyCode to remove unnecessary props
* Update FormVerifyCode and pages that use it to display an error tooltip when the form is submitted without a code
* Replaces instances of 'security code' with 'authentication code'
Closes #FXA-6493, FXA-6799
1. Modify `fxa-content-server/server/config/local.json` to enable the showReactApp feature flag for the signUpRoutes (see this doc: https://docs.google.com/document/d/1VZLh7vnUfKsAHNoZla-p7SfYwmwPdmjPUjAeiYe0qfw/edit?usp=sharing).
2. Create a new …

feat(fxa-settings): Functional ConfirmSignupCode in React

---

packages/functional-tests/tests/react-conversion/resetPassword.spec.ts
packages/fxa-graphql-api/src/decorators.ts
packages/fxa-graphql-api/src/gql/account.resolver.ts
packages/fxa-settings/src/pages/ResetPassword/index.tsx

- This fixes some critical bugs
- Fixes location in reset password email
- Fixes bugs
- Adds basic playwright test for react reset password
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6828
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6858
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6859
It was easier to write the playwright test than to manually go through the steps over and over to replicate the bug 😅

fix(auth): Fix multiple reset emails, location, add playwright test

---

packages/fxa-content-server/app/scripts/templates/partial/support-form-success.mustache
packages/fxa-content-server/app/styles/modules/support.scss

- The "Back to Subscriptions" text is not centered within the button
- There should be more space between the title and message of the confirmation modal
- Centers the text within the button
- Increases the margin above the message of the confirmation modal
- Decreases the margin below the message of the confirmation modal
Closes: [FXA-6678](https://mozilla-hub.atlassian.net/browse/FXA-6678)
Before
After
[FXA-6678]: https://mozilla-hub.atlassian.net/browse/FXA-6678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(content-server): Revise Contact Support confirmation modal

---

packages/fxa-auth-server/lib/routes/oauth/index.js
packages/fxa-auth-server/lib/routes/oauth/token.js
packages/fxa-auth-server/test/oauth/routes/token.js

Because:
- we want to quantify scoped keys usage
This commit:
- add statsd metrics to count the RPs getting scoped keys

chore(metrics): count RPs fetching scoped keys

---

packages/fxa-auth-client/lib/crypto.ts
packages/fxa-auth-client/package.json
packages/fxa-content-server/package.json
yarn.lock

Because:
- we don't need to use our own fork and branch of webcrypto-liner now that it implements hkdf
- we will continue to polyfill since node's webcrypto module is still experimental as of v18
This commit:
- uses mainline webcrypto-liner

chore(deps): use mainline webcrypto-liner

---

_dev/docker/ci/Dockerfile.dockerignore

- Deploy CI images is failing because fxa-shared now references the test folder during build.
- Removes tests directories from the docker ignore list.
Closes: FXA-6977
Error encountered:
This change was a regression introduced by [this](https://github.com/mozilla/fxa/pull/14814/files#r1093437748) change.

bug(CI): Fix deploy-ci-images job

---

.circleci/config.yml
packages/functional-tests/scripts/test-ci.sh
packages/functional-tests/tests/oauth/signin.spec.ts
packages/functional-tests/tests/signin/resetPassword.spec.ts
packages/functional-tests/tests/subscription-tests/coupons-ui-tests/ui-tests.spec.ts
packages/functional-tests/tests/syncV3/fxDesktopV3ForceAuth.spec.ts
packages/functional-tests/tests/syncV3/signIn.spec.ts
packages/functional-tests/tests/syncV3/signUp.spec.ts
packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts
packages/functional-tests/tests/syncV3/syncV3ResetPassword.spec.ts

- See this [comment](https://github.com/mozilla/fxa/blob/2fcfd881cb130eff6b1ee2228ad161aa408b8dd9/packages/functional-tests/lib/fixtures/standard.ts#L121) why we could potentially run into flaky tests that utilize Sync
- Use `newPagesForSync` that guaranttes the test is isolated
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6936

fix(test): Use `newPagesForSync` in flaky tests and disable coppa

---

packages/fxa-content-server/app/robots.txt

Because:
- FxA is just a login page for someone who's not authenticated
This commit:
- stops archive.org from indexing FxA into the wayback machine

chore(robots.txt): block the archive.org bot from indexing

---

packages/functional-tests/tests/react-conversion/legal.spec.ts

Because:
* "Privacy Notice" is visible on the page if there is an error and isn't useful to test for if the external Markdown files are rendering properly. "Firefox Privacy Policy" is in the Markdown from the legal-docs repository however.
This commit:
* Changes the text from "Privacy Notice" to "Firefox Privacy Notice"
* Removes related CSS class selectors and unneeded expect/toBeTruthys
--
See [this comment](https://github.com/mozilla/fxa/pull/14931/files#r1121921674).

fix(test): Update playwright legal header text test

---

.circleci/README.md
.circleci/config.yml

- We want to run smoke tests in parallel for faster deployments.
- Adds pipeline flags required to support remote execution of pipelines
- Updates readme
Currently being vetted by pending PR in cloudops deployement.

task(CI): Updates to better support parallel smoke tests

---

packages/fxa-auth-server/scripts/convert-customers-to-stripe-automatic-tax/convert-customers-to-stripe-automatic-tax.ts
packages/fxa-auth-server/test/scripts/convert-customers-to-stripe-automatic-tax.ts

* Stripe tax conversion script does not currently escape CSV commas present in the nickname field.
* Escapes commas in the nickname field, as well as the email and product name fields just in case.
Closes FXA-7034

fix(auth): tax conversion script does not escape CSV commas

---

packages/fxa-auth-server/README.md
packages/fxa-auth-server/config/index.ts
packages/fxa-auth-server/lib/geodb.js
packages/fxa-auth-server/test/local/geodb.js

Because:
* we moved away from having stripe resolve IPs to geolocations, and need a way to override our own geodb service during local testing
This commit:
* adds a config/environment variable that foces the geodb to resolve the geolocation of the request to the configured value
Closes #FXA-6883

feat(auth): add GeoDB Location Override

---

packages/fxa-auth-server/lib/oauth/util.js
packages/fxa-shared/auth/encrypt.ts

- To be more spec compliant, we need to calulate the `at_hash` from the ascii represenation of access token and not hex form (which we were doing)
- Using `oidc-client-js` it would complain that the hash was not correct, this fixes that
- Generates `at_hash` from ascii 
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6827
Some historical context: https://github.com/mozilla/fxa/pull/1681/

fix(oauth): Update `at_hash` claims calulation

---

packages/fxa-settings/src/models/Account.ts
packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.tsx
packages/fxa-settings/src/pages/ResetPassword/index.tsx

* Requesting a new link from /confirm_reset_password in the React app should send a new link and stay on the same page. (Should not redirect to signin)
* Stores the currentPasswordForgotToken in React state so it can be updated when requesting a new link.
* Corrects issue where polling would check against the previous (replaced) token.
Closes: #FXA-6893

fix(fxa-settings): resending reset password link redirects to signin

---

packages/fxa-payments-server/src/lib/mock-data.tsx
packages/fxa-payments-server/src/lib/test-utils.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx

- Some pages and components do not have tests for archived plans.
- Updates pages and components, where necessary, to include a test with an archived plan.
Closes: #FXA-6835

task(subscriptions): update tests for archived plans

---

packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/validators.js
packages/fxa-payments-server/src/components/PaymentConfirmation/index.stories.tsx
packages/fxa-shared/dto/auth/payments/invoice.ts

- The invoice in Firestore is not guarenteed to have properties `total_excluding_tax` and `subtotal_excluding_tax`
- Updates the types and joi schemas for latestInvoiceItems to allow for undefined values for `total_excluding_tax` and `subtotal_excluding_tax`.
Closes: #FXA-7040

fix(subscriptions): allow for missing tax fields on invoice

---

packages/fxa-settings/src/components/LinkDamaged/index.tsx
packages/fxa-settings/src/components/LinkExpired/index.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx

- For consistency, all banners should be placed below CardHeader.
* Use an enum for error type in CompleteResetPassword to ensure only one banner can be displayed at a time
* Move Banner below CardHeader in CompleteResetPassword
* Fix test for Submit error in CompleteResetPassword (add function mock for hasRecoveryKey)
* Fix FTL ids for LinkDamaged, LinkExpired (ids in code did not match up with FTL ids)
Closes: #FXA-7019
Before:
After:
Banner also needs to be moved in `ConfirmResetPassword` and `AccountRecovery` pages, but I've included those fixes with FXA-6891 (in progress)

fix(fxa-settings): Reposition Banner below CardHeader in CompleteResetPassword

---

packages/fxa-auth-server/lib/log.js
packages/fxa-auth-server/test/local/log.js
packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-content-server/tests/server/amplitude-schema-validation.js
packages/fxa-payments-server/server/lib/amplitude.js
packages/fxa-payments-server/server/lib/amplitude.test.js
packages/fxa-shared/metrics/amplitude.ts

Because:
* ajv was configured to error on the first validation error, we were missing info if there were multiple ajv errors
This commit:
* configures ajv to report all validation errors, updates tests accordingly
Closes #FXA-6995
See below how to force multiple validation errors for testing.
And the validation errors should be visible in sentry and logs:

feat(auth): report All AJV Validation Errors

---

packages/fxa-auth-server/scripts/convert-customers-to-stripe-automatic-tax.ts
packages/fxa-auth-server/scripts/convert-customers-to-stripe-automatic-tax/convert-customers-to-stripe-automatic-tax.ts
packages/fxa-auth-server/test/scripts/convert-customers-to-stripe-automatic-tax.ts

* Marketing cannot pull locale via their contact database
* Marketing cannot filter out unchanged total sub amounts when looking at sub totals
* Adds locale to the CSV output
* Filters any subs who's totals are unchanged before/after the update
Closes FXA-7037

feat(auth): tax conv locale, logging, filter unchanged totals

---

packages/fxa-settings/src/lib/auth-errors/en.ftl
packages/fxa-settings/src/pages/ResetPassword/en.ftl
packages/fxa-settings/src/pages/ResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/index.tsx

* We want to show a localized time instead of {$retryAfter} variable in "You've tried too many times. Please try again {$retryAfter}" error message for the ResetPassword page.
* Adjust localized error message to include localized time.
* Fix test to reflect the actual auth errors that are now rendered instead of a generic error.
Edited to add:
* Adjust l10n comment for error string - some misunderstandings were identified in existing translations.
* Add missing FTL string for input label.
Closes: #FXA-6875

fix (fxa-settings) : render localized {$retryAfter} variable

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/components/PageWithLoggedInStatusState/index.test.tsx
packages/fxa-settings/src/components/PageWithLoggedInStatusState/index.tsx
packages/fxa-settings/src/components/Ready/index.test.tsx
packages/fxa-settings/src/components/Ready/index.tsx
packages/fxa-settings/src/lib/gql.ts
packages/fxa-settings/src/lib/reliers/relier-factory.ts
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordConfirmed/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordConfirmed/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordConfirmed/index.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.tsx
packages/fxa-settings/src/pages/Signin/SigninConfirmed/index.stories.tsx
packages/fxa-settings/src/pages/Signin/SigninConfirmed/index.test.tsx
packages/fxa-settings/src/pages/Signin/SigninConfirmed/index.tsx
packages/fxa-settings/src/pages/Signup/PrimaryEmailVerified/index.stories.tsx
packages/fxa-settings/src/pages/Signup/PrimaryEmailVerified/index.test.tsx
packages/fxa-settings/src/pages/Signup/PrimaryEmailVerified/index.tsx
packages/fxa-settings/src/pages/Signup/SignupConfirmed/index.stories.tsx
packages/fxa-settings/src/pages/Signup/SignupConfirmed/index.test.tsx
packages/fxa-settings/src/pages/Signup/SignupConfirmed/index.tsx

* We're moving the `signin` routes into the main app behind a feature flag
* Adds the `signin_confirmed`/`signin_verified` routes into the React app behind a feature flag, with basic metrics, tests and localization.
* Also uses the new `useRelier` hook to read relier data for the `Ready` component. I move the logic fetching the data out of the relier into the wrapper component that supplies the `isLoggedIn` prop -- this prevents us from having to rewrite the tests for all the components that consume the Ready component. Since here we assume that we're getting this data out of the url params, I wrap the relier reads in a `try/catch`. If the query params are there, we'll read them -- if they aren't, we won't throw a general application error.
* Tests for the component that gets data out of …

feat(fxa-settings): set up functionality for signin_confirmed

---

packages/fxa-payments-server/server/config/index.js
packages/fxa-payments-server/server/lib/amplitude.js
packages/fxa-payments-server/server/lib/amplitude.test.js
packages/fxa-payments-server/server/lib/routes/post-metrics.js

Because:
* We want to record the country code for all payments server user events.
This commit:
* Includes the existing fxa-geodb package, config and some shared helpers in the payments server.
* Adds some new helpers to obtain the user's geolocation and country code for events.
Closes #FXA-6947
* We already had the `fxa-geodb` package as a dependency on the payments server; it just wasn't being used anywhere and didn't have any config.
* As discussed earlier with Julian, ideally, the `clientAddress` would be decorated on the request as part of Express' middleware, but that's not how it is implemented in its current usage in `fxa-shared` (and `fxa-content-server`). Since we will no longer be using Express in SubPlat 3.0 (we will be using NextJS), I am …

chore(payments): set up fxa-geodb for metrics

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/components/LinkExpired/index.test.tsx
packages/fxa-settings/src/components/LinkExpired/index.tsx
packages/fxa-settings/src/lib/context/implementations/base-context.ts
packages/fxa-settings/src/lib/context/implementations/url-context.ts
packages/fxa-settings/src/lib/context/implementations/url-hash-context.ts
packages/fxa-settings/src/lib/context/implementations/url-search-context.ts
packages/fxa-settings/src/lib/context/model-validation.ts
packages/fxa-settings/src/lib/metrics.test.ts
packages/fxa-settings/src/lib/metrics.ts
packages/fxa-settings/src/models/Account.ts
packages/fxa-settings/src/models/AppContext.ts
packages/fxa-settings/src/models/hooks.ts
packages/fxa-settings/src/models/index.ts
packages/fxa-settings/src/models/reliers/base-relier.ts
packages/fxa-settings/src/models/verification/account-recovery-key-info.ts
packages/fxa-settings/src/models/verification/index.ts
packages/fxa-settings/src/models/verification/verification-info.ts
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/en.ftl
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/mocks.tsx

- We are migrating content server to react
- Supports account_recovery_reset_password route in settings.
- Ports logic from complete_password_reset for account recovery key in AccountRecoveryResetPassword
- Adds more test coverage
- Gets storybooks working with new logic
- Adds missing metrics function logErrorEvent
- Adds verification-info model
- Adds account-recovery-key-info-model
- Uses AppContext.Provider in storybook so that hooks function properly.
- Fixes warning in CompleteResetPassword about act
- Extracts AccountRecoveryResetPassword mocks into a separate mocks.ts file
- Provides a UrlContextWindow for UrlContext classes in order to narrow access to the window object
- Hooks up the the resend link action.
- Provides empty dummy methods for Notifier.onAccountSignIn
- Provides …

task(settings): Implement AccountRecoveryResetPassword in settings

---

packages/fxa-payments-server/.vscode/launch.json
packages/fxa-payments-server/README.md

Because:
* we do not have an easy way to debug payments server tests through vs code
This commit:
* adds a launch config for vscode to debug the payments server tests
Closes #FXA-7049

feat(payments): vscode Launch Config For Debugging Payments Server Tests

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ManagementPanel.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx

- The total amount does not include tax.
- Fetch subsequent invoice for canceled subscription.
- Updates Reactivate subscription model to use subsequent invoice.
Closes: #FXA-6996

task(subscriptions): subsequent invoice for canceled sub

---

packages/fxa-settings/src/components/App/index.test.tsx
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/components/Settings/index.test.tsx
packages/fxa-settings/src/components/Settings/index.tsx

* Currently, Sentry is only enabled for Settings pages
* Wraps the other pages in Sentry as well
Closes #FXA-6933
(Shows errors still coming in over local from Settings page, and also from new React conversion pages)
Previously, since only logged in users could interact with the Settings app, we would only enable sentry for users who had opted in to enabling their metrics. Since we are now sharing a Sentry configuration between signed in and signed out pages, we instead enable Sentry conditionally, requiring a user to be EITHER logged out, OR logged in with metrics enabled.

fix(fxa-settings): enable Sentry for new React pages

---

packages/fxa-auth-server/lib/senders/emails/templates/subscriptionRenewalReminder/en.ftl
packages/fxa-payments-server/src/components/PaymentForm/en.ftl

- Updates to the l10n linter caught issues with ftl placeables (required spaces before and after placeable name missing)
- Adds the missing spaces in the variables
- Does not require updating the string ID

chore(l10n): fix linter issues around ftl placeables

---

.circleci/config.yml
package.json

- Deploy was failing
- Runs the create lists command after base-install, so diffparser module should be present.
- Only run the clone l10n operation once and remove the operation from the post install step.

fix(ci): Don't clone on postinstall & create lists after base install.

---

packages/fxa-auth-server/package.json
yarn.lock

* Failing builds due to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51408 and not pinned within auth-server
* Pins @types/convict to 5.2.2

fix(auth): pin @types/convict to 5.2.2

---

_dev/docker/ci/Dockerfile

Because:
- we need to clone l10n repo so that packages can be built
This commit:
- explicitly call `l10n:clone` in the Dockerfile for CI images

fix(CI): clone l10n repo

---

.circleci/config.yml

Because:
- we should install packages before requiring them in scripts
This commit:
- run base install first
- originally part of commit 0d82821

fix(CI): install deps before requiring in script

---

packages/fxa-settings/src/lib/gql.test.ts
packages/fxa-settings/src/lib/gql.ts

Because:
* Setting up Sentry logging for the new React conversion pages meant that all pages are in a component tree which pings GQL. Previously, many of those pages did not ping GQL. This change meant that unauthenticated users on those pages were forcibly navigated out to the /signin page. While the behavior itself is not a bug, I failed to include all necessary pages into the `pageNotRequiringAuthentication` exclusion list, which would have addressed this issue.
This commit:
* Now, instead of having an exclusion list which listed off all pages excluded from the redirect rule (which navigated users out to the /signin page), I created an inclusion list (which currently only includes /settings.) This should make it easier to maintain.
Closes #FXA-7062 …

bug(fxa-settings): fix bug enforcing authentication on new pages

---

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/generalized-react-app.js

Because:
* We want to turn on the React experiment for sets of pages that have their feature flag on in production, and we're now at the point where the 'simple routes' feature flag  will be turned on in prod
This commit:
* Hard-codes the rollout rate to 15% per discussions. When we're ready to rollout to 100% we'll remove the experiment logic around these routes.
Closes FXA-7053
--
We want to cherry-pick this into a release after #15029 is done and cherry-picked, which is the last PR left to unblock our first set of pages (simple routes) from going out.
After this is merged, we can get [this PR on the SRE side](https://github.com/mozilla-services/cloudops-deployment/pull/4802) merged.

feat(experiments): Turn on rollout rate (15%) for React pages

---

.circleci/config.yml
packages/functional-tests/pages/login.ts
packages/functional-tests/tests/react-conversion/recoveryKey.spec.ts
packages/functional-tests/tests/react-conversion/resetPassword.spec.ts
packages/functional-tests/tests/settings/recoveryKey.spec.ts
packages/functional-tests/tests/syncV3/signIn.spec.ts
packages/functional-tests/tests/syncV3/signUp.spec.ts
packages/fxa-auth-client/lib/crypto.ts
packages/fxa-auth-client/lib/recoveryKey.ts
packages/fxa-auth-client/lib/utils.ts
packages/fxa-auth-client/test/crypto.ts
packages/fxa-auth-client/test/recoveryKey.ts
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.tsx

- We need to maintain the users encryption key if they reset their password using a recovery key
- Adds ability to decrypt their recovery key and use that as part of the reset password process
- Reenables react password reset test
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7065
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7044

feat(password): Add ability to decrypt a user's `recoveryKeyData` 

---

packages/functional-tests/pages/resetPassword.ts
packages/functional-tests/tests/reset-password/resetPassword.spec.ts
packages/fxa-settings/src/lib/firefox.ts
packages/fxa-settings/src/models/AppContext.ts

- We need to be able to send and recieve the `fxa_status` webchannel event
- Adds support for this message
Closes: https://mozilla-hub.atlassian.net/browse/FXA-3362

feat(webchannels): Add initial support for `fxa_status` webchannel event

---

packages/fxa-payments-server/src/components/PaymentForm/index.tsx
packages/fxa-payments-server/src/lib/hooks.tsx
packages/fxa-payments-server/src/routes/Product/index.test.tsx

- The total amount displayed for existing customer subscribing to new plan omitted applied promo code and/or tax
- Updates the total to include promo code and/or tax if applied
- Fixes a failing test that returns an error for invalid product (and therefore no invoice preview)
Closes: FXA-7007

fix(payments): correct total amount displayed in PaymentForm

---

_dev/eslint-plugin-fxa/README.md
_dev/eslint-plugin-fxa/lib/configs/client.js
_dev/eslint-plugin-fxa/lib/configs/default.js
_dev/eslint-plugin-fxa/lib/configs/index.js
_dev/eslint-plugin-fxa/lib/configs/recommended.js
_dev/eslint-plugin-fxa/lib/configs/server.js
_dev/eslint-plugin-fxa/lib/index.js
_dev/eslint-plugin-fxa/lib/rules/async-crypto-random.js
_dev/eslint-plugin-fxa/lib/rules/index.js
_dev/eslint-plugin-fxa/lib/rules/no-exclusive-tests.js
_dev/eslint-plugin-fxa/lib/rules/no-new-buffer.js
_dev/eslint-plugin-fxa/lib/util/ast.js
_dev/eslint-plugin-fxa/lib/util/settings.js
_dev/eslint-plugin-fxa/package.json
_dev/eslint-plugin-fxa/test/async-crypto-random.js
_dev/eslint-plugin-fxa/test/no-exclusive-tests.js
_dev/eslint-plugin-fxa/test/no-new-buffer.js
package.json
packages/123done/package.json
packages/browserid-verifier/package.json
packages/fortress/package.json
packages/fxa-auth-server/package.json
packages/fxa-content-server/package.json
packages/fxa-customs-server/package.json
packages/fxa-geodb/package.json
packages/fxa-payments-server/package.json
packages/fxa-profile-server/package.json
packages/fxa-settings/package.json
packages/fxa-shared/package.json
yarn.lock

Because:
- we don't want to maintain the fxa eslint plugin in another repo
This commit:
- move the plugin into the monorepo

chore(lint): move eslint-plugin-fxa into the monorepo

---

packages/fxa-auth-server/scripts/convert-customers-to-stripe-automatic-tax.ts
packages/fxa-auth-server/scripts/convert-customers-to-stripe-automatic-tax/convert-customers-to-stripe-automatic-tax.ts
packages/fxa-auth-server/scripts/convert-customers-to-stripe-automatic-tax/helpers.ts
packages/fxa-auth-server/test/scripts/convert-customers-to-stripe-automatic-tax-helpers.ts
packages/fxa-auth-server/test/scripts/convert-customers-to-stripe-automatic-tax.ts

* The script could move customers between tax exclusive/inclusive regions.
* Checks customer's currency against mapped IP address country.
* Considers not_collecting as an eligible stripe autotax status.
Closes FXA-7061

fix(auth): automatic tax check IP addr before converting customers

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/payments/subscription-reminders.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/payments/subscription-reminders.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js

* Our subscription renewal emails do not contain tax
* Includes tax in renewal email by fetching an invoice preview, rather than taking the base cost of the plan. This is done via the previewInvoiceBySubscriptionId, such that it gets the next billed amount direct to the customer.
* Removes the automaticTax flag from previewInvoiceBySubscriptionId. Having automaticTax as a flag isn't necessary here, since you're previewing a subscription by ID which already inherits the subscription's automaticTax status, and could also be misunderstood/misused since it actually behaves as an override.
Closes FXA-7082

fix(auth): include tax in renewal notice emails

---

packages/fxa-auth-server/test/local/payments/iap/apple-app-store/subscription-purchase.js
packages/fxa-shared/payments/iap/apple-app-store/subscription-purchase.ts

- Currently for Apple subscriptions the `originalTransactionId` is included, but not the `transactionId`.
- Including `transactionId` would provide an important indicator whether it's the initial transaction or a restore/renewal.
- Adds `transactionId` to Apple subscriptions in Firestore.
Closes: FXA-6987

chore(auth/shared): add `transactionId` to Apple subscriptions in Firestore

---

docs/adr/0019-use-workspace-dependencies.md
docs/adr/0037-use-nx-for-monorepo.md

Because:
* We want to use nx for our monorepo to get faster builds and better tooling for our libraries.
This commit:
* Adds an ADR for using nx for our monorepo.
Closes FXA-7016.

chore(docs): add adr for nx

---

.circleci/config.yml

- Smoke tests could be triggered on branches but not on tags
- Generally we only run smoke tests on tags
- Applies filters such that smoke tests can be run on tags.
- Applies filters such that smoke tests cannot be run on branches.

task(ci): Allow smoke tests on tags

---

packages/fxa-graphql-api/src/backend/legal.service.spec.ts
packages/fxa-settings/src/lib/reliers/relier-factory.test.ts

- A .only was left in place accidentally and this was preventing all relier factory tests from running
- Removes .only
- Fixes a small issue surfaced where async call to isSync was not being awaited.
Closes: FXA-7103

task(settings): Remove .only from PairingSupplicantRelier test

---

packages/fxa-payments-server/src/components/PaymentConsentCheckbox/en.ftl
packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.test.tsx
packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.tsx
packages/fxa-payments-server/src/components/PaymentMethodHeader/en.ftl
packages/fxa-payments-server/src/components/PaymentMethodHeader/index.test.tsx
packages/fxa-payments-server/src/components/PaymentMethodHeader/index.tsx
packages/fxa-payments-server/src/routes/Checkout/index.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
packages/fxa-payments-server/src/routes/en.ftl

Because:
* the confirmation checkbox looks like it applies to just the paypal payment option and confuses users since the submit payment is disabled until checked
This Commit:
* moves the checkbox, adds info about the price and product the user is committing to
Closes: FXA-4260
Ticket assets are out of date, figma has current designs https://www.figma.com/file/XqeVmcXail0yJfWytiShkc/%5BProposed%5D-Subplat-Desktop-Payment-page-UI-updates?node-id=222-289&t=6XsPgE8XQCLm6rCr-0

feat(payments): move The Confirmation Checkbox

---

_dev/docker/builder/Dockerfile
_dev/docker/mono/Dockerfile

- The jq command line utility was missing from docker images based on node:18 slim
- Installs jq
This was discovered in the train-255 deploy.

task(ci): Add jq to docker

---

packages/fxa-payments-server/src/components/PaymentMethodHeader/en.ftl
packages/fxa-payments-server/src/components/PaymentMethodHeader/index.test.tsx
packages/fxa-payments-server/src/components/PaymentMethodHeader/index.tsx

Because:
* this change accidentally got reverted and uses the wrong single quotation marks
This commit:
* Puts back the correct ones

fix(payments): update Single Quotation Marks

---

packages/fxa-admin-server/src/subscriptions/subscriptions.service.spec.ts
packages/fxa-admin-server/src/subscriptions/subscriptions.service.ts

Because:
* Support was seeing FxA users' subscriptions list the wrong plan ID in the FxA Admin Panel relative to Stripe.
* We were picking the first cached plan whose product ID matched the subscription product ID rather than matching the plan ID.
This commit:
* Matches by the plan ID instead.
Closes #FXA-7039

fix(admin): filter plans by plan id rather than product id

---

.circleci/config.yml
packages/fxa-content-server/app/scripts/models/subscription.ts
packages/fxa-content-server/tsconfig.json
packages/fxa-payments-server/tsconfig.json

- We want to start tracking build errors on all packages
- We should create urgency around fixing typescript build errors
- Removes any typescript compile exclusions
- Disabled the 'fail-fast' step for compile jobs
Closes: FXA-7133, FXA-7194
This will result in failures, but it won't block the pipeline or merging. Hopefully we can be proactive about fixing these typescript errors.

task(ci): Build all packages but don't fail fast

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.test.tsx
packages/fxa-settings/src/constants/index.tsx
packages/fxa-settings/src/models/Account.ts
packages/fxa-settings/src/models/mocks.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/mocks.tsx
packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.tsx
packages/fxa-settings/src/pages/Signup/Confirm/index.stories.tsx
packages/fxa-settings/src/pages/Signup/Confirm/index.test.tsx
packages/fxa-settings/src/pages/Signup/Confirm/index.tsx
packages/fxa-settings/src/pages/Signup/Confirm/mocks.tsx

* We're converting our views from backbone to React
* Serves the React version of the 'confirm' page if the feature flag is on
* Adds page functionality to Confirm, including adding needed methods to the Account model and a ProfileInfo mock
* Implements one functionality change to the React version of the Confirm page: asking to resend the email sends a confirmation code instead of a confirmation link, and redirects to the 'confirm_signup_code' page
* Adds React import to CompleteResetPassword mocks (missing import was breaking the stories for this page)
Closes: #[FXA-6492](https://mozilla-hub.atlassian.net/browse/FXA-6492)
- We are keeping this page to preserve …

feat(react): Implement functionality for React /confirm page

---

.circleci/config.yml
packages/functional-tests/pages/login.ts
packages/functional-tests/pages/products/index.ts
packages/functional-tests/pages/relier.ts
packages/functional-tests/pages/resetPassword.ts
packages/functional-tests/pages/settings/layout.ts
packages/functional-tests/pages/settings/recoveryKey.ts
packages/functional-tests/playwright.config.ts
packages/functional-tests/scripts/test-ci.sh
packages/functional-tests/tests/oauth/forceAuth.spec.ts
packages/functional-tests/tests/oauth/totp.spec.ts
packages/functional-tests/tests/react-conversion/resetPassword.spec.ts
packages/functional-tests/tests/settings/password.spec.ts
packages/functional-tests/tests/settings/recoveryKey.spec.ts
packages/functional-tests/tests/settings/totp.spec.ts
packages/functional-tests/tests/signUp/signUp.spec.ts
packages/functional-tests/tests/signUp/signUpWithCode.spec.ts
packages/functional-tests/tests/signin/redirect.spec.ts
packages/functional-tests/tests/signin/relyingParties.spec.ts
packages/functional-tests/tests/subscription-tests/coupons-ui-tests/coupon.spec.ts
packages/functional-tests/tests/syncV3/signIn.spec.ts
packages/functional-tests/tests/syncV3/signUp.spec.ts
packages/functional-tests/tests/syncV3/syncV3ResetPassword.spec.ts
packages/fxa-auth-server/test/scripts/bulk-mailer.js
packages/fxa-auth-server/test/scripts/dump-users.js
packages/fxa-auth-server/test/scripts/must-reset.js

- Playwright tests are still flaky
- Uses new function `.waitForUrl` instead of deprecated `.waitForNavigation` in several places
- Increases flaky test retry to 3

fix(tests): Add some tweaks to reduce flaky playwright tests

---

packages/fxa-content-server/app/scripts/lib/experiment.js

- This experiment needs to be a start experiment to automatically enroll the user in the experiment, ref https://mozilla.github.io/ecosystem-platform/reference/experiments-ab-testing
- Adds as startup experiment
Closes: #
We will need a point release for this.

fix(react): Add react experiment to as a startup experiment

---

packages/fxa-settings/src/components/FormPasswordWithBalloons/index.tsx
packages/fxa-settings/src/components/InputPassword/index.tsx
packages/fxa-settings/src/components/InputPassword/mocks.tsx

* We want the password inputs to toggle visibility independent of each other. In other words, if you click on the "eye" icon next to either input, we want to change the visibility of only that input, and not the neighboring input.
* Removes the logic which linked the visibility status for the two inputs.
Closes #FXA-7150
Separated visibility toggle functionality:

bug(fxa-settings): unlink password input visibility toggle

---

packages/fxa-settings/src/components/LinkExpired/index.stories.tsx
packages/fxa-settings/src/components/LinkExpired/index.tsx
packages/fxa-settings/src/components/LinkExpiredResetPassword/index.test.tsx
packages/fxa-settings/src/components/LinkExpiredResetPassword/index.tsx
packages/fxa-settings/src/components/LinkExpiredSignin/index.test.tsx
packages/fxa-settings/src/components/LinkExpiredSignin/index.tsx
packages/fxa-settings/src/components/LinkValidator/index.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.tsx
packages/fxa-settings/src/pages/Signin/CompleteSignin/index.stories.tsx
packages/fxa-settings/src/pages/Signin/CompleteSignin/index.test.tsx
packages/fxa-settings/src/pages/Signin/CompleteSignin/index.tsx

* 'Receive new link' button on Link Expired pages were not working on Stage
* Fix error with button click handler
* Pass in email from params to link expired page
* Add a few more tests to LinkExpired components
Closes: #FXA-6891
Success banner should now be displayed when resending a link is successful (tested on localhost)
- On local, a new link is received with `yarn pm2 logs inbox` when clicking on the link.
- Link should now be enabled for all LinkExpired instances in the ResetPassword flow. 
- Link won't be active yet for Signin pages (functionality not enabled yet)

fix(fxa-settings): Receive new link button inactive

---

packages/fxa-payments-server/server/lib/amplitude.js
packages/fxa-payments-server/server/lib/amplitude.test.js
packages/fxa-shared/metrics/amplitude-event.1.schema.json
packages/fxa-shared/test/metrics/amplitude.js

- Payments metrics should include the users language
- Adds language field to events for event_type fxa_pay_setup - * and fxa_pay_subscription_change - *
Closes: #FXA-6951

feat(metrics): send language on payments metrics

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-settings/src/components/App/index.test.tsx
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/models/Account.ts
packages/fxa-settings/src/pages/Signin/SigninBounced/en.ftl
packages/fxa-settings/src/pages/Signin/SigninBounced/index.stories.tsx
packages/fxa-settings/src/pages/Signin/SigninBounced/index.test.tsx
packages/fxa-settings/src/pages/Signin/SigninBounced/index.tsx

* We're moving the React components to their real routes and wiring them up to receive data
* Adds signin_bounced into the React app
* Adds a check for the user's email (via localStorage) in the App root file
Closes #FXA-6489
Still needs metrics!!

feat(fxa-settings): setup signin_bounced in React

---

packages/fxa-payments-server/src/lib/flow-event.test.ts
packages/fxa-payments-server/src/lib/flow-event.ts
packages/fxa-payments-server/src/lib/sentry.js

Because:
* we want to report to sentry when we will not be able to capture flow events for a checkout flow
This commit:
* Adds a method to sentryMetrics and calls it from flow-events if initialized is false in shouldSend
Closes #FXA-6963
Note about screenshots below: I've updated the message to include that flow metrics are not captured for the checkout flow and the referrer is blank because I entered the url into address bar (was not directed to the checkout page)
To test this, remove one of the following from the query params:  `device_id`, `flow_begin_time`, `flow_id`

feat(metrics): report A Warning To Sentry If Flow Initialization Fails

---

packages/fxa-auth-server/lib/sentry.js
packages/fxa-auth-server/test/local/sentry.js

- We want to ignore known app errors, but we do not want to ignore internal errors
- We noticed a scenario where sentry did not captured a failed API call
- Adjusts the logic in the `ignoreErrors` function to allow nested errors through
- Add function for finding the root cause of an error
- Adds more tests around `ignoreErrors`
Closes: FXA-7042

bug(auth): Sentry would ignore inner errors

---

.github/workflows/tag-release.yml

Because:
* We could encourage more consistent builds by using an environment built in an action instead of on developer machines
This commit:
* Creates a github action that tags our releases
This script is compatible with our current release script (as far as names of trains and tags and such).  This script does not file any bugs or have that big chunk of output to copy/paste at the end.
This script cannot handle patch releases because it wouldn't know what you wanted to patch but we could add good documentation for how to handle that.  
This will only fire if someone pushes the button on github so it's safe to land if it's something we want.

chore: create release github action

---

.circleci/config.yml
packages/fxa-auth-server/README.md
packages/fxa-auth-server/config/dev.json
packages/fxa-customs-server/pm2.config.js
packages/fxa-graphql-api/src/gql/lib/error.ts
packages/fxa-settings/src/models/Account.ts
packages/fxa-settings/src/pages/ResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/index.tsx
packages/fxa-settings/src/pages/ResetPassword/mocks.tsx

* We want to show the retryAfterLocalized value in localized error messages when ResetPassword requests are throttled (maxEmails reached)
* Add retryAfter and retryAfterLocalized from Auth server errors to GraphQl errors
* Make this value available to the localized throttled error message for the ResetPassword page.
* Add ResetPassword stories to show error examples.
* Enable rate-limiting in dev environment by default to test rate-limiting errors.
* Use ipv4 for the customs-server localhost (prevent from using ipv6, favoured by Node18)
Closes: #FXA-6875
MAX_EMAILS is set to 3 by default - on 4 consecutive and incomplete attempts to reset the password (submitting the email 4 times at http://localhost:3030/reset_password?showReactApp=true without …

fix(fxa-settings): Show localizedRetryAfter when resetPassword is throttled

---

docs/adr/0038-use-esbuild-in-production.md

- We want to move forwards with using esbuild in production
- Adds an ADR for using esbuild in production
Closes: FXA-5960

task(many): Use esbuild in production

---

packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx

* Currently in the new React version of the account_recovery_confirm_key view, if the user hammers the `submit` button with an incorrect key typed into the input (or, basically with anything other than an empty input or a value that isn't the correct key) the user will eventually see a "link expired" message. This is not how the page currently behaves in Backbone and it is not desired behavior.
* Debounces the submit button
Closes #FXA-7152
I would SUPER appreciate people going through this and seeing if they see the error on main, and then don't see the error with these changes in place -- I think this is a simple throttling issue but my understanding of what was causing this specific error is very surface level, so having other eyes on it would be a …

bug(fxa-settings): fix 'link expired' error in reset password

---

packages/fxa-content-server/app/scripts/lib/experiment.js

- Type typo in the experiment name caused the experiment not to be turned on
- Fixes name

feat(auth): Update experiment name for generalized react app

---

.circleci/build-all.sh
.circleci/build.sh
.circleci/config.yml
.circleci/deploy-all.sh
.circleci/deploy.sh
_scripts/build-fxa-mono.sh

- We can build the docker image while tests are running
- This will cut down on deploy time
- Builds the deployed docker images in parallel to tests
- Pushes temporary image to docker up
- Once tests finish re-tags temporary image and pushes to docker hub
- Removes temporary build image from docker hub
Closes: FXA-7141

task(ci): Allow docker build phase to happen in parallel

---

.circleci/config.yml
packages/functional-tests/lib/fixtures/standard.ts
packages/functional-tests/lib/targets/firefoxUserPrefs.ts
packages/functional-tests/pages/settings/components/unitRow.ts
packages/functional-tests/pages/settings/secondaryEmail.ts
packages/functional-tests/playwright.config.ts
packages/functional-tests/tests/misc.spec.ts
packages/functional-tests/tests/oauth/signin.spec.ts
packages/functional-tests/tests/oauth/syncSignIn.spec.ts
packages/functional-tests/tests/react-conversion/legal.spec.ts
packages/functional-tests/tests/react-conversion/recoveryKey.spec.ts
packages/functional-tests/tests/reset-password/resetPassword.spec.ts
packages/functional-tests/tests/settings/changePassword.spec.ts
packages/functional-tests/tests/settings/password.spec.ts
packages/functional-tests/tests/settings/recoveryKey.spec.ts
packages/functional-tests/tests/settings/totp.spec.ts
packages/functional-tests/tests/signin/connectAnotherDevice.spec.ts
packages/functional-tests/tests/signin/relyingParties.spec.ts
packages/functional-tests/tests/syncV3/fxDesktopV3ForceAuth.spec.ts
packages/functional-tests/tests/syncV3/signIn.spec.ts
packages/functional-tests/tests/syncV3/signUp.spec.ts
packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts
packages/functional-tests/tests/syncV3/syncV3ResetPassword.spec.ts
packages/fxa-auth-server/config/dev.json
packages/fxa-settings/src/pages/ResetPassword/index.tsx

- We want to use a smaller instance size to run our playwright test 
- Updates our `newPagesForSync` to return the browser instance as well. When we use this function, we need to ensure that we call, `browser.close()` to ensure that the browser gets closed properly.
- Adds logic so that experiments are not loaded when running playwright tests, this makes them indetermistic
- Updates a few tests to use the now prefered way to use `.waitForNavigation`
- Updates a few selectors to use the recommended `.locator` and then `.click`
- Updates CI workers to 1
- Adds a delay before running playwright mocha tests since this would fail before the tests run
- Appends `showReactApp=false` to links from emails, not sure why this was bypassing the experiment logic
- Moved `add TOTP and confrim sync …

fix(test): Playwright with large instance but less workers

---

.yarnrc.yml

- We are cleaning up yarn warnings.
- We want to address YN0068 errors
- Removes `react-document-title@*:` from the packageExtensions defined in `.yarnrc.yml`
- It appears this extension was no longer needed / referenced.
Closes: FXA-6536

task(many): Fix YN0068 warnings

---

packages/fxa-admin-server/package.json
packages/fxa-admin-server/src/config/index.ts
packages/fxa-admin-server/src/scripts/audit-tokens.spec.ts
packages/fxa-admin-server/src/scripts/audit-tokens.ts
packages/fxa-admin-server/src/scripts/db-helpers.ts
packages/fxa-content-server/server/lib/sentry.js
packages/fxa-shared/db/index.ts

- We want to audit table row counts in oauth DB
- We want to audit table row counts in profile DB
- Audits a couple more tables in oauth DB
- Audits a couple more tables in profile DB
- Configures oauth connection independently
- Configures profile db connection independently
- Fixes bad reference to gen_keys.ts file in package.json
Closes: FXA-7153
The logic for auditing more tables was essentially already supported; however, the code wasn't configured in a way that would connect to multiple database instances. During local development all database instances live on the same instance, but in staging/prod we have dedicated database instances for oauth data, which was the impetus for these changes.

task(admin-server): Audit oauth and profile DB tables

---

packages/fxa-content-server/app/scripts/templates/post_verify/newsletters/add_newsletters.mustache
packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache
packages/fxa-content-server/app/scripts/views/mixins/email-opt-in-mixin.js
packages/fxa-content-server/app/scripts/views/post_verify/newsletters/add_newsletters.js
packages/fxa-content-server/app/tests/spec/views/mixins/email-opt-in-mixin.js

Because:
* Newsletters aren't being passed to Basket
This commit:
* Updates the selector used to grab the inputs
Fixes FXA-7306
---
We removed this class when converting some flows to Tailwind classes and didn't update the selector. The changes in `add_newsletter` aren't necessary to fix the bug but were updated for consistency.
You can test this by logging `options` in [sessionVerifyCode](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-client/lib/client.ts#L747) before the patch and seeing `newsletters` is not present in the object after verifying an account with newsletters selected, vs it being present in that object with this patch. (you can probably alternatively check the network tab)

fix(newsletters): Update newsletter input selector

---

packages/fxa-settings/src/components/Settings/ProgressBar/en.ftl
packages/fxa-settings/src/components/Settings/ProgressBar/index.stories.tsx
packages/fxa-settings/src/components/Settings/ProgressBar/index.test.tsx
packages/fxa-settings/src/components/Settings/ProgressBar/index.tsx
packages/fxa-settings/src/styles/tailwind.css

* We need a simple progress bar to track the user's progress through the account recovery flow
* Adds in a simple progress bar
Closes #FXA-7229
Firefox:
Safari:
Chrome:

feat(fxa-settings): add a simple progress bar for the recovery flow

---

packages/fxa-auth-server/bin/email_notifications.js
packages/fxa-auth-server/bin/profile_server_messaging.js

Because:
- These didn't get changed with the esbuild upgrade
This commit:
- Updates these require statements
Closes # FXA-7309

fix(build): some containers are crashing

---

packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/en.ftl
packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/index.stories.tsx
packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/index.test.tsx
packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/index.tsx

* We want to treat the key as a precious artifact that should be handled with care
* Create a ButtonDownloadRecoveryKey component with initial storybook and tests
* Adds new copy for the textfile
* Adds localization for the text file
Closes: #FXA-7266
Screenshot of generated text file with additional localized string for testing:
Localization of text in generated text file was tested with an existing localized string in:
- Traditional Chinese zh-TW (extended character set/ double byte language)
- Hebrew (right-to-left)
- Icelandic (extended latin)
- Belarusian (Cyrillic)

feat(fxa-settings): Recovery key download file with localization

---

packages/fxa-settings/src/components/FormPasswordWithBalloons/index.tsx
packages/fxa-settings/src/components/FormPasswordWithBalloons/mocks.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx
packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.tsx
packages/fxa-settings/src/pages/ResetPassword/en.ftl
packages/fxa-settings/src/pages/ResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/index.tsx
packages/fxa-settings/src/pages/Signup/index.tsx

- We want to reduce form-related re-rendering to a minimum in the new react flows and only emit screen events once on initial load.
* Reduce form-related re-renders to a minimum (previously re-rendered on every input change, now re-renders if inputs have errors that are displayed in adjacent components - there is no `useWatch` equivalent for `formState errors`)
* Update ResetPassword form to use the `useWatch` hook to isolate re-rendering, remove `trigger`
* Replace `logPageViewEvent` with `usePageViewEvent` hook
* Move some state from pages to the `FormPasswordWithBalloons` component
* Update tests for submit error on `ResetPassword`
* Displays a tooltip error if the ResetPassword form is submitted without an email
Closes: # FXA-7100, #FXA-7160
Please …

fix(fxa-settings): Reduce form-related re-renders in new React flows

---

packages/fxa-content-server/server/lib/beta-settings.js
packages/fxa-content-server/server/lib/configuration.js
packages/fxa-settings/src/components/Settings/PageRecoveryKeyAdd/index.tsx
packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.tsx
packages/fxa-settings/src/components/Settings/index.tsx
packages/fxa-settings/src/lib/config.ts

* We want to wait until the entire flow is finalized before shipping, but want to enable testing on stage.
* Creates a copy of the current `UnitRowRecoveryKey`, and add a new `PageRecoveryKeyCreate` to house the changes to `PageRecoveryKeyAdd`
* Adds an environment variable (`showRecoveryKeyV2`) to conditionally display the new flow
Closes: #FXA-7287
Currently, it's necessary to complete stop/start the stack to change the env variable. Not sure if this is an issue with my local install.
Here's what currently works to activate the new flow locally:
- `yarn stop`
- Set `"showRecoveryKeyV2":true` in `local.json` OR add `SHOW_RECOVERY_KEY_V2=true` to `.env`
- `yarn …

feat(fxa-settings): Conditionally render new RecoveryKey flow

---

packages/fxa-settings/src/components/Settings/FlowContainer/index.stories.tsx
packages/fxa-settings/src/components/Settings/FlowContainer/index.tsx
packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.stories.tsx
packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.test.tsx
packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.tsx

* We want to manage the longer flow of views using a wizard component
* While this ticket originally asked for us to create a new flow container, revisions to the designs made a new Flow Container unnecessary. Instead, this PR builds out a simple Wizard to contain all of the UI for the PageRecoveryKeyAdd wizard, allowing us to somewhat separate the logic of the individual steps (views) of the wizard, and also separate the UI from the page logic.
Closes #FXA-7228

feat(fxa-settings): create new flow container for account recovery

---

packages/fxa-auth-client/lib/client.ts
packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/server/lib/beta-settings.js
packages/fxa-content-server/server/lib/routes/react-app/add-routes.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-content-server/server/lib/routes/react-app/types.ts
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/components/ThirdPartyAuth/index.test.tsx
packages/fxa-settings/src/components/ThirdPartyAuth/index.tsx
packages/fxa-settings/src/components/ThirdPartyAuth/mocks.tsx
packages/fxa-settings/src/lib/config.ts
packages/fxa-settings/src/models/Account.ts
packages/fxa-settings/src/models/mocks.tsx
packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/en.ftl
packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.stories.tsx
packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.test.tsx
packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.tsx

- To have feature parity with content-server, we need to port over this logic
- Adds the logic to sign-in with Apple/Google
- Adds Apple/Google config to settings-server
- Adds form submission logic to Third party auth component
- Adds the loading screen after a successful third party auth is completed
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7127
This PR is dependent on https://github.com/mozilla/fxa/pull/15149

Port over third party auth logic to react

---

packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/en.ftl
packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/index.tsx

- The arrow bullet that was previously used may not be well supported for RTL languages
- Replace arrow bullet with unidirectional circle bullet
Closes: #FXA-7331

fix(fxa-settings): Replace bullet used in recovery key download

---

packages/fxa-auth-server/config/index.ts
packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/payments/paypal-processor.js
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js
packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
packages/fxa-auth-server/test/remote/account_create_tests.js
packages/fxa-auth-server/test/remote/subscription_tests.js

* Stripe automatic tax is now rolled out for all customers
* We want to remove all Stripe tax rate behavior
* Removes the Stripe automatic tax feature flag
* Removes Stripe tax rate code
* Restructures some internal utilities such as previewInvoice now that Stripe automatic tax is always on.
Closes FXA-6091

chore(auth): remove stripe automatic tax feature flag

---

packages/functional-tests/tests/react-conversion/recoveryKey.spec.ts
packages/fxa-settings/src/models/Account.ts

Because:
* Users were not taken to the generate new account recovery key flow after resetting with an account recovery key since apollo cache still had this value set to true
This commit:
* Updates the cache to reflect that the account no longer has a recovery key after a successful password reset with recovery key
Closes FXA-7163
---
We don't currently have tests for `Account.ts`, and it feels like this should be tested in an end-to-end test anyway.

fix(reset_password): Update apollo cache after recovery key consumption

---

packages/functional-tests/tests/oauth/signinTokenCode.spec.ts

- The two tests for `Oauth Sign in token code` were failing in Stage and Prod with `Timeout error`
- Fixes the Stage and prod timeout errors and also adds steps for email cleanups after the tests.
- Below screenshot shows stage and prod runs for the tests
Closes: #[FXA-7145](https://mozilla-hub.atlassian.net/browse/FXA-7145)
[FXA-7145]: https://mozilla-hub.atlassian.net/browse/FXA-7145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(functional): fix timeout error

---

packages/fxa-auth-server/scripts/move-customers-to-new-plan.ts
packages/fxa-auth-server/scripts/move-customers-to-new-plan/move-customers-to-new-plan.ts
packages/fxa-auth-server/test/scripts/move-customers-to-new-plan.ts

* We need to be able to migrate customers off of a given plan.
* Adds a script to move customers from one plan to another.
Closes FXA-7125
Closes FXA-7122

feat(auth): customer mover script

---

packages/functional-tests/tests/signUp/signUp.spec.ts
packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/app/tests/spec/lib/router.js
packages/fxa-content-server/tests/functional.js
packages/fxa-content-server/tests/functional/lib/helpers.js
packages/fxa-content-server/tests/functional/pages.js
packages/fxa-content-server/tests/functional/sign_up.js
packages/fxa-settings/src/pages/CannotCreateAccount/index.tsx
packages/fxa-settings/src/pages/Clear/index.tsx

Because:
* We want to turn everything in simpleRoutes up to 100% rollout in production, and we want to be able to easily add to this list later for other route groups
This commit:
* Modifies showReactApp function to account for a new array constant containing the route groups that should always be enabled
* Adds tests
Closes FXA-7312
---
Note that you do still have to have the feature flag on, which we should keep around for easy rollback on the SRE side, and also because we need some value in the config anyway for the server-side check.

feat(react): Add logic for and effectively turn simpleRoutes to 100% rollout in prod

---

packages/fxa-customs-server/bin/customs_server.js

- Customs is failing to start up due to SyntaxError.
- Replace ESM export default with CommonJS syntax

fix(customs): refactor customs server export syntax

---

packages/fxa-content-server/app/scripts/views/mixins/password-strength-mixin.js
packages/fxa-content-server/app/scripts/views/post_verify/finish_account_setup/set_password.js
packages/fxa-content-server/app/styles/tailwind/inputs.css

* The password balloon and eye toggle weren't showing up on password input for the post_verify/finish_account_setup/set_password view in fxa-content-server.
* Supplies the correct element ID for the password balloon so that it will be applied correctly, and fixes an accidental CSS override in the cascade.
Closes #FXA-7083

bug(fxa-content-server): fix password balloon and eye toggle

---

packages/fxa-auth-server/package.json
yarn.lock

Reverts mozilla/fxa#15166
fxa-auth-server storybooks are broken, fixing might depend on updating @storybook/react from 6.5.9 to 7.0.*
Reverting now until we can commit time into looking at the migration details.

Revert "chore(deps-dev): bump @storybook/html from 6.5.10 to 7.0.4"

---

packages/fxa-content-server/app/tests/spec/lib/cocktail.js

- The copyright header was slightly duped.
```sh
git grep -c "* This Source Code Form is subject to the terms of the Mozilla Public" packages | grep -Ev ":1$"
```
Looks like we have roughly 360 [ *.ts | *.tsx | *.js | *.jsx ] files without any copyright headers, but that's an issue for some future PRs.
```sh
git grep -L "* This Source Code Form is subject to the terms of the Mozilla Public" -- ':*.tsx' ':*.ts' ':*.js' ':*.jsx' | wc -l # 362
```
-

chore(content): Remove duplicate copyright header line

---

packages/fxa-admin-panel/postcss.config.js
packages/fxa-admin-panel/server/jest.config.js
packages/fxa-admin-panel/src/lib/config.spec.ts
packages/fxa-admin-panel/src/react-app-env.d.ts

- Some files are missing copyright headers. Ref: FXA-6700
- Fixes the missing copyright headers in fxa-admin-panel package.

chore(copyright): Add missing copyright headers to fxa-admin-panel

---

packages/fxa-admin-server/src/auth/auth-header.decorator.ts
packages/fxa-admin-server/src/auth/auth-header.guard.spec.ts
packages/fxa-admin-server/src/auth/auth-header.guard.ts
packages/fxa-admin-server/src/database/database.module.ts
packages/fxa-admin-server/src/scripts/email-bounce.ts

- Some files are missing copyright headers. Ref: FXA-6700
- Fixes the missing copyright headers in fxa-admin-server package.

chore(copyright): Add missing copyright headers to fxa-admin-server

---

packages/functional-tests/tests/subscription-tests/coupons-ui-tests/coupon.spec.ts
packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts
packages/functional-tests/tests/subscription-tests/coupons-ui-tests/ui-tests.spec.ts
packages/functional-tests/tests/subscription-tests/subscription.spec.ts
packages/functional-tests/tests/subscription-tests/support.spec.ts

- Currently we have no real payment method in Prod for subscriptions, hence disabling tests related to CC or paypal payments in Prod only. They will still run in local and on Stage.
- Disables CC or paypal payment related tests in Prod only
Closes: #[FXA-7371](https://mozilla-hub.atlassian.net/browse/FXA-7371)
[FXA-7371]: https://mozilla-hub.atlassian.net/browse/FXA-7371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(subplat): disable tests related to payments in prod

---

packages/functional-tests/pages/cookiesDisabled.ts
packages/functional-tests/pages/index.ts
packages/functional-tests/tests/misc/cookiesDisabled.spec.ts
packages/functional-tests/tests/oauth/forceAuth.spec.ts
packages/functional-tests/tests/oauth/loginHint.spec.ts
packages/functional-tests/tests/oauth/signin.spec.ts
packages/functional-tests/tests/settings/changeEmail.spec.ts
packages/functional-tests/tests/settings/deleteAccount.spec.ts
packages/functional-tests/tests/settings/misc.spec.ts

As part of the playwright test migration, the [cookies disabled tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/cookies_disabled.js) have been rewritten in this PR.
contains [cookies disabled tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/cookies_disabled.js) modified to work with react pages.
Closes: #[FXA-5919](https://mozilla-hub.atlassian.net/browse/FXA-5919)
[FXA-5919]: https://mozilla-hub.atlassian.net/browse/FXA-5919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(functional): rewrite cookies disabled tests in playwright

---

packages/fxa-shared/metrics/navigation-timing.ts

- There was an app error when about:config > dom.enable_performance_observer = false.
- In this case, any reference to PerformanceObserver would result in an unhandled error
- Uses `typeof PerformanceObserver` instead, which works around the is not defined error.
Closes: FXA-7382
The fix here is a bit surprising, for some reason any ref to the PerformanceObserver results in a runtime error when it's been disabled in the Firefox config. As a result the check which ran `&& PerformanceObserver` wouldn't eval like a typical undefined variable, and instead threw an error. 
This can be replicated by going to about:config in the address bar, changing the dom.enable_performance_observer setting to false, opening a new tab and running a check like …

bug(shared): Fix issue with check on PerformanceObserver

---

packages/functional-tests/tests/signUp/signUp.spec.ts
packages/fxa-content-server/app/scripts/lib/fxa-client.js

- The local storage stage for `metricsEnabled` was not aligned with the server side state.
- Ensures that default value for `metricsEnabled` in local storage is true.
Closes: FXA-7296

bug(content): MetricsEnabled not set properly by default in local storage

---

_dev/docker/builder/Dockerfile
_scripts/base-docker.sh
_scripts/build-builder.sh

- We want the package.json version to match the git tag being deployed.
- We don't want to commit a change on the package.json file to accomplish this.
- If there is a git tag, the code will send the tag into the docker build as a VERSION build arg.
- This build arg is then used to update the version field in all package.json files.
Closes: FXA-7359
Testing this is a bit tricky. I was able to validate most of the changeset locally by running the docker build command directly, ie `docker build --build-arg VERSION=v1.2.3 -f _dev/docker/builder/Dockerfile . -t test`, and then bash into the container and validate the package.json files had been updated, ie `docker run -it test bash` and then `cat package.json | grep version`.

task(CI): Patch package.json version fields to reflect the git tag

---

packages/db-migrations/contentful/1683045086859_feature-2023-05-01_to_dev.js
packages/db-migrations/contentful/1683128671165_feature-2023-05-01_to_dev.js

- Content model was created in Contentful
- Adds the migration script for the initial load of the content model.
Closes: #FXA-7337

feat(contentful): initial migration script

---

packages/functional-tests/tests/reset-password/resetPassword.spec.ts

A few reset password tests were failing on Stage with error “You've tried too many times. Try again in 30 minutes." 
Circle CI run : https://app.circleci.com/pipelines/github/mozilla/fxa/40580/workflows/5f63d299-f26a-48d5-b3b5-a419037d2702/jobs/429056
Fixes the restmail domain for the test from .com to .net 
Closes: FXA-7396

fix(test): change restmail domain from com to net

---

packages/fxa-settings/src/lib/utilities.test.ts
packages/fxa-settings/src/lib/utilities.ts
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/mocks.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/mocks.tsx

Because:
* Recovery keys with an additional character were being accepted as valid due to how base32-decode works, wherein each character represents 5 bits of data which are ultimately split into 8-bit segments, and one extra character is not enough to change the resulting value
This commits:
* Disallows submission for recovery keys that are not 32 characters long, allowing for spaces in submission
* Clears errors onchange to better match parity
* Increases test coverage
Fixes FXA-7171
--
Mostly copied from my earlier Slack comment:
My understanding of the issue is when we decode the recovery key, the input string is 1) [processed one character at a time](https://github.com/LinusU/base32-decode/blob/a6601b2f57be2b2db954e939c66d09610256b5a4/index.js#L44), 2) each character is converted to …

fix(reset_password): Don't accept a recovery key with additional character

---

.circleci/config.yml
packages/fxa-content-server/app/tests/spec/lib/router.js
packages/fxa-content-server/server/config/local.json-dist
packages/fxa-content-server/server/lib/configuration.js
packages/fxa-content-server/server/lib/routes/react-app/index.js
packages/fxa-content-server/server/lib/routes/react-app/types.ts
packages/fxa-content-server/tests/server/routes/react-app.js

Because:
* We cancelled the React port of post_verify add recovery key routes and post_verify add secondary email routes and deemed 'push' routes out of scope (see tickets for details), so our feature flags needed some tweaking
* simpleRoutes are rolled out to 100% in production and updating local.json-dist to match keeps local dev in sync
closes FXA-6647
---
corresponding cloudops PR: https://github.com/mozilla-services/cloudops-deployment/pull/4831
- removes postVerifyAddRecoveryKeyRoutes
- removes signInVerificationViaPushRoutes
- adds postVerifyOtherRoutes

task(react): Update feature flag names, modify local.json-dist

---

packages/fxa-settings/src/lib/auth-errors/en.ftl
packages/fxa-settings/src/pages/ResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/index.tsx

Because:
* If an email isn't valid, we shouldn't bother sending up a request to the server
This commit:
* Adds a temporary Sentry log to help debug FXA-7347; we're hoping the issue resolves with a customs fix that will be pushed with the next tag, but this might help us glean a little more info in case it doesn't
* Does not allow form submission if the email is invalid, adds a couple tests
Closes FXA-7347
---
See [Slack thread 1](https://mozilla.slack.com/archives/CLV3KMZ8B/p1683656924296959) / [Slack thread 2](https://mozilla.slack.com/archives/CLV3KMZ8B/p1683657694032539).
FXA-7347 is not reproducible locally, what's mentioned locally in the ticket is a different error. We're hoping the issue is resolved with a customs push to staging that recently had a fix - our Account resolver for …

fix(reset_password): Don't allow submission with invalid email

---

packages/fxa-auth-server/lib/metrics/amplitude.js
packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
packages/fxa-auth-server/test/local/metrics/amplitude.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
packages/fxa-shared/metrics/amplitude-event.1.schema.json
packages/fxa-shared/metrics/amplitude.ts
packages/fxa-shared/test/metrics/amplitude.js

- we should log when a user’s subscription is Canceled
- this adds `fxa_subscribe - subscription_ended` event in auth-server
Closes: [FXA-6955](https://mozilla-hub.atlassian.net/browse/FXA-6955)
[FXA-6955]: https://mozilla-hub.atlassian.net/browse/FXA-6955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(metrics): Add `fxa_subscribe - subscription_ended` auth server event

---

packages/fxa-auth-server/scripts/move-customers-to-new-plan.ts
packages/fxa-auth-server/scripts/move-customers-to-new-plan/move-customers-to-new-plan.ts
packages/fxa-auth-server/test/scripts/move-customers-to-new-plan.ts

* We want to be able to do a dry run of the customer move script before moving customers.
* Adds a --dry-run flag to the customer mover script.
Closes FXA-7429

feat(auth): add dry-run support to move-customers script

---

.circleci/config.yml

- Recently we saw that every time we do a prod deployment all the content-server and playwright tests are run on stage as well. There doesn’t seem to be a good reason why it is set up like that. We need to remove the stage runs from prod deployments.
- Is to remove all the stage runs from the prod deployments and to run only the Prod smoke test - playwright suite
Closes: #[FXA-7370](https://mozilla-hub.atlassian.net/browse/FXA-7370)
[FXA-7370]: https://mozilla-hub.atlassian.net/browse/FXA-7370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

remove stage runs from prod deployments

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-payments-server/src/routes/Checkout/index.test.tsx
packages/fxa-payments-server/src/routes/Checkout/index.tsx

- This would break the user flow and they would have to open the product page again after signin
- Updates how our `/settings` redirect works to redirect without appending additional flow params (not needed since it is external)
- Updates the product signin url to include a `redirect_to` query param which is the product page
- 
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6783

feat(subs): Fix issue where user would not be redirected back to product after 3rd party auth

---

packages/fxa-auth-server/lib/redis.js
packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/index.stories.tsx
packages/fxa-shared/db/redis.ts
packages/fxa-shared/package.json
yarn.lock

- We want to monitor Redis calls for better observability
- Adds some metrics for analyzing Redis calls, specifically around custom routines
- Adds extra tracing support for custom routines which aren't auto instrumented
Closes: FXA-7193
Note that we are using metrics.histogram here. Ideally we would like to see distributions pertaining to the size of values being retrieved from Redis. We have reason to believe that some entries are quite large, however, we don't know the frequency at which these entries are queried. These metrics will shed some light on this. Extra tracing support has also been added, which might uncover scenarios where these calls could be optimized.

task(auth): Investigate redis calls and payload sizes

---

packages/functional-tests/pages/connectAnotherDevice.ts
packages/functional-tests/pages/login.ts
packages/functional-tests/tests/signin/signinCached.spec.ts
packages/functional-tests/tests/syncV3/signinCached.spec.ts

As part of the playwright test migration, the [signin cached tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sign_in_cached.js) have been rewritten in this PR.
contains [signin cached tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sign_in_cached.js) except the last 2 tests for token sessions. It will be covered as part of a different ticket (FXA-6230)
Closes: #[FXA-5911](https://mozilla-hub.atlassian.net/browse/FXA-5911)
[FXA-5911]: https://mozilla-hub.atlassian.net/browse/FXA-5911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …

test(functional): rewrite signin cached tests using playwright

---

packages/fxa-payments-server/src/lib/stripe.ts
packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

- Card holder name is not currently added to payment element on new subscriptions with a new card.
- Adds card holder name to card payment method.
Closes: # FXA-7440

feat(payments): Add name to card payment element

---

packages/fxa-auth-server/scripts/move-customers-to-new-plan.ts
packages/fxa-auth-server/scripts/move-customers-to-new-plan/move-customers-to-new-plan.ts
packages/fxa-auth-server/test/scripts/move-customers-to-new-plan.ts

* The product requirements changed regarding excluding customers.
* We no longer want to cancel-only for excluded customers, but now want to exclude completely.
* Excludes customers in the excluded list completely, rather than just excluding them from the cancellation behavior.
Closes FXA-7448

feat(auth): change exclude behavior for mover script

---

packages/fxa-auth-server/lib/payments/stripe-formatter.ts
packages/fxa-auth-server/test/local/payments/stripe-formatter.js
packages/fxa-auth-server/test/local/routes/validators.js
packages/fxa-auth-server/test/remote/subscription_tests.js
packages/fxa-payments-server/src/components/PaymentConfirmation/index.test.tsx
packages/fxa-payments-server/src/lib/apiClient.test.ts
packages/fxa-payments-server/src/lib/mock-data.tsx
packages/fxa-payments-server/src/lib/test-utils.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.stories.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx
packages/fxa-shared/dto/auth/payments/invoice.ts
packages/fxa-shared/test/subscriptions/metadata.ts

- On an upgrade where the interval or interval_count of the new price differs from the current price, the incorrect next invoice date is shown.
- Updates the invoice preview API to return the period
- Updates invoice preview and latest invoice DTO entities.
- Updates all tests and storybooks where invoice preview and latest invoice are used.
Closes: # FXA-7060
Monthly -> Yearly
Monthly -> Monthly

fix(payments): on upgrade correct next invoice

---

packages/fxa-payments-server/.eslintrc.json
packages/fxa-payments-server/src/components/AppLayout/index.test.tsx
packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx
packages/fxa-payments-server/src/components/PaymentConfirmation/index.test.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.stories.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx
packages/fxa-payments-server/src/components/TermsAndPrivacy/index.test.tsx
packages/fxa-payments-server/src/lib/apiClient.test.ts
packages/fxa-payments-server/src/lib/flow-event.test.ts
packages/fxa-payments-server/src/lib/mock-data.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionSuccess/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionIapItem/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx
packages/fxa-payments-server/tsconfig.json

- Typescript compilation on test files in payments were temporarily disabled
- fixes TypeScript errors from [https://app.circleci.com/pipelines/github/mozilla/fxa/39710/workflows/aadf68b4-2667-41a6-bb51-8fcced647d20/jobs/419847](https://app.circleci.com/pipelines/github/mozilla/fxa/39710/workflows/aadf68b4-2667-41a6-bb51-8fcced647d20/jobs/419847)
- removes the ‘exclude’ config in payment’s tsconfig file
Closes: [FXA-7144](https://mozilla-hub.atlassian.net/browse/FXA-7144)
[FXA-7144]: https://mozilla-hub.atlassian.net/browse/FXA-7144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(payments): Fix Typescript errors

---

packages/fxa-settings/src/components/Settings/ConnectedServices/Service.tsx
packages/fxa-settings/src/components/Settings/ConnectedServices/index.test.tsx

Because:
* This link is out of date
This commit:
* Updates the link
Closes FXA-4912

refactor(settings): change Pocket link. Fix FXA-4912

---

packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/index.stories.ts
packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoice/index.stories.ts
packages/fxa-auth-server/lib/senders/emails/templates/subscriptionSubsequentInvoice/index.stories.ts

- Some of the SubPlat emails were not loading due to undefined props.
- Corrects `subscriptionFirstInvoice` and `subscriptionSubsequentInvoice` email stories by adding missing prop `showTaxAmount`.
- Corrects `subscriptionCancellation` email story by adding missing props `showOutstandingBalance` and `cancelAtEnd`.
Closes: FXA-6171

fix(storybook): subplat email templates not loading

---

.circleci/config.yml
packages/functional-tests/scripts/start-services.sh
packages/functional-tests/scripts/test-ci.sh

- We'd like to only rerun failed tests
- Allows us to run run just the tests that have failed. See https://circleci.com/docs/rerun-failed-tests-only/
- Uses`circleci tests run` to invoke playwright command
- Adds required envs
- Removes functional-tests/test-ci.sh in favor of inline command in circleci config
Closes: FXA-7357
This PR focuses on playwright tests because they are known to be flaky and there is good support for playwright. Since content-server functional tests are being phased out the rerun only failed feature will not be enabled for them. Since unit and integration tests aren't typically flaky, the rerun only failed feature will not be enabled at this time.
Also here's some screenshots showing this in action. Note that in the second run, …

task(CI): Enable rerun of only failed tests

---

packages/fxa-auth-server/lib/metrics/amplitude.js
packages/fxa-auth-server/lib/metrics/events.js
packages/fxa-auth-server/lib/server.js
packages/fxa-auth-server/lib/types.ts
packages/fxa-auth-server/test/local/metrics/amplitude.js
packages/fxa-auth-server/test/local/metrics/events.js
packages/fxa-auth-server/test/local/server.js
packages/fxa-auth-server/test/mocks.js

- If events.emit data includes uid it should be included on request.app.metricsEventUid instead of request.auth.artifacts.metricsUid.
- Sets request.app.metricsEventUid and updates request.isMetricsEnabled to use metricsEventUid if necessary to determine Account.metricsEnabled.
Closes: #FXA-6967

task(auth): move metricsUid to app.metricsEventUid

---

packages/functional-tests/pages/login.ts
packages/functional-tests/tests/signin/signinBlocked.spec.ts

As part of the playwright test migration, the [signin blocked tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sign_in_blocked.js) have been rewritten in this PR. We decided to keep only 5 of the existing tests from the old file - `signin blocked - valid code entered`, `signin blocked - incorrect code entered`, `signin blocked - resend`, `signin blocked - unverified`, `signin blocked - with primary email changed`. The decision sheet could be found [here](https://docs.google.com/spreadsheets/d/11Wq-Y-ipeNFXqLHbr3GJCh_f_qEAG-CUuqBt5Dcnh5k/edit#gid=0)
contains the 5 [signin blocked tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sign_in_blocked.js)
Closes: FXA-5900 …

test(functional): rewrite signin blocked tests using Playwright

---

packages/fxa-auth-server/scripts/prune-tokens.ts
packages/fxa-auth-server/test/scripts/prune-tokens.js

- `--wait=100` not having an effect
- Specifies that `--wait` is a number which fixes the problem

bug(auth): Token pruner wouldn't accept --wait arg

---

packages/fxa-settings/src/components/Settings/PageDeleteAccount/en.ftl
packages/fxa-settings/src/components/Settings/PageDeleteAccount/index.test.tsx
packages/fxa-settings/src/components/Settings/PageDeleteAccount/index.tsx
packages/fxa-settings/src/constants/index.tsx

- We need updated messaging
- Adds Pocket to the deleted accounts list
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7086
This PR is blocked on https://getpocket.atlassian.net/browse/INFRA-1201, Pocket needs to listen to the FxA delete account even and process it accordingly.

feat(pocket): update pocket delete account messaging

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-payments-server/server/lib/amplitude.test.js
packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx
packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
packages/fxa-payments-server/src/components/PayPalButton/index.stories.tsx
packages/fxa-payments-server/src/components/PayPalButton/index.test.tsx
packages/fxa-payments-server/src/components/PayPalButton/index.tsx
packages/fxa-payments-server/src/lib/amplitude.ts
packages/fxa-payments-server/src/lib/apiClient.test.ts
packages/fxa-payments-server/src/lib/apiClient.ts
packages/fxa-payments-server/src/lib/stripe.test.ts
packages/fxa-payments-server/src/lib/stripe.ts
packages/fxa-payments-server/src/routes/Checkout/index.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
packages/fxa-shared/metrics/amplitude-event.1.schema.json
packages/fxa-shared/metrics/amplitude.ts
packages/fxa-shared/subscriptions/types.ts
packages/fxa-shared/test/metrics/amplitude.js

Because:
* we wanted to have an expanded set of properties on certain metrics events and want to enforce the schema appropriately
This commit:
* adds the required and optional properties to the fxa_pay_setup* and fxa_subscription_change* events and updates the ajv schema such that errors will be reported for missing information
Closes FXA-6953, FXA-6954, FXA-7499

feat(metrics): update Event Properties

---

packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-content-server/tests/server/amplitude.js
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyHint/index.test.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyHint/index.tsx

* With the design updates to the Recovery Key flow, we wanted to do a higher level sweep of all the tracking of users entering/exiting/interacting with that flow. This PR updates the views to have all tracking events listed in
https://docs.google.com/spreadsheets/d/1-HsNgIjT4IJQf088o2mM3a-vn3OCNNXixHU5L0QH_GI/edit?usp=sharing. It also adds comments for which pre-existing event should be removed in clean-up.
* We document which event should be removed in cleanup, and update existing events to match the above document per feedback from Wil and Jess.
Closes #FXA-7249

task(fxa-settings, fxa-content-server): tracking for recovery key

---

.circleci/config.yml
packages/functional-tests/lib/targets/production.ts
packages/functional-tests/lib/targets/stage.ts
packages/fxa-content-server/scripts/test-ci-remote.sh

- We want to try running smoke tests against a new environment
- Adds pipeline parameters for configuring standard domains
- Transfers pipeline parameters to a set of standard envs
- Updates playwright tests to use these envs
- Updates functional content server tests to use these envs
Closes: FXA-7017

task(CI): Make smoke test URLs configurable

---

packages/fxa-content-server/app/scripts/lib/glean/index.ts
packages/fxa-content-server/app/scripts/views/mixins/signup-mixin.js
packages/fxa-content-server/app/tests/spec/lib/glean.js
packages/fxa-content-server/app/tests/spec/views/mixins/signup-mixin.js

Because:
- we want to send a ping to Glean when someone attempts to register for
an account
This commit:
- send the Glean ping for 'reg_submit'

chore(metrics): add Glean event for reg_submit

---

packages/fxa-content-server/app/scripts/lib/glean/index.ts
packages/fxa-content-server/app/scripts/views/mixins/signup-mixin.js
packages/fxa-content-server/app/tests/spec/lib/glean.js
packages/fxa-content-server/app/tests/spec/views/mixins/signup-mixin.js

Because:
- we want to send a Glean ping when some successfully registered a new
account
This commit:
- sends a ping for reg_submit_success

chore(metrics): add Glean event for reg_submit_success

---

packages/fxa-content-server/app/scripts/views/mixins/signin-mixin.js
packages/fxa-content-server/app/scripts/views/sign_in_password.js
packages/fxa-content-server/app/tests/spec/views/mixins/signin-mixin.js
packages/fxa-content-server/app/tests/spec/views/sign_in_password.js

Because:
- we should not send Glean pings if the account has opted out of data collection
This commit:
- disable Glean when we know the account's data collection setting before or after signing in

feat(metrics): disable Glean metrics based on acct pref

---

.circleci/config.yml
packages/functional-tests/pages/resetPassword.ts
packages/functional-tests/pages/settings/components/unitRow.ts
packages/functional-tests/pages/settings/recoveryKey.ts
packages/functional-tests/tests/react-conversion/recoveryKey.spec.ts
packages/functional-tests/tests/settings/misc.spec.ts
packages/functional-tests/tests/settings/password.spec.ts
packages/functional-tests/tests/settings/recoveryKey.spec.ts
packages/fxa-content-server/server/config/local.json-dist
packages/fxa-content-server/server/lib/routes/get-index.js
packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/index.test.tsx
packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/index.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyDownload/index.tsx
packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.tsx

- We need to update functional tests to support the new account recovery key creation flow
- Update the recovery key page model
- Update `misc`, `password` and `recoveryKey` tests behind feature flag
- Update `react-conversion/recoveryKey` test
Closes: #FXA-7250
**The "old" flow (still live on stage and prod at the moment) :**
With the old flow, the user had to click "remove" then "create" to delete an existing key and create a new one.
**The new flow for creating a key:**
With the new flow, users can choose to change or delete an existing key:
If they click change, they are taken to a slightly modified version of the key creation flow.
This PR enables the `showRecoveryKeyV2` flag on local - running the functional tests with this flag enabled with only …

test(functional-tests) - Update recoveryKey tests for new flow

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/package.json
packages/fxa-settings/src/lib/gql.test.ts
packages/fxa-settings/src/lib/gql.ts

- We want to ensure that query params (ie `context`) are included when redirecting
- Updates the `redirect_to` to include the abolute url
- Updates gql to append the query params when doing to settings and in the `redirect_to` param
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7439
Here is an example of how the redirect works:
http://accounts.firefox.com/settings?context=oauth_webchannel_v1 redirects ->
https://accounts.firefox.com/signin?context=oauth_webchannel_v1&redirect_to=http%3A%2F%2Faccounts.firefox.com%2Fsettings%3Fcontext%3Doauth_webchannel_v1
Note that now the `context` param is loaded on the signin page. Depending on this param, the browser and FxA perform exchange information via webchannels to let web content know what user to load.

feat(url): Update settings redirect to append query params

---

packages/fxa-auth-server/lib/sentry.js
packages/fxa-auth-server/test/local/sentry.js

It appears these changes may have resulted in an abundance of irrelevant errors being reported. Rolling back these changes for now.

Revert "bug(auth): Sentry would ignore inner errors"

---

packages/fxa-content-server/app/scripts/views/mixins/third-party-auth-mixin.js
packages/fxa-content-server/app/tests/spec/views/mixins/third-party-auth-mixin.js

- These query params will show the error message if we are impacted
- Adds the query params to Google authorization endpoint
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7136
I tested this in the iOS simulator and did not see any error messages on Google sign-in page. It is hard to verify this with Pocket unless it is in production. This is safe to land since users have to opt in to third party auth anyways.

feat(auth): Update Google authorization endpoint to not show disclaimer

---

packages/fxa-admin-server/nest-cli.json
packages/fxa-graphql-api/nest-cli.json

- Nest APIs could fail to start because `main.js` wasn't found
- NX work changed structure of dist folder
- Adjust the path to point to the new location of main.js
I think this went unnoticed because it would only become a failure after the dist folder was cleaned out.
IIRC to reproduce the issue on main, run `nx run fxa-gql-api:build` then run `nx run fxa-gql-api:start`.

bug(admin,gql): Fix startup behavior in dev mode

---

packages/functional-tests/lib/targets/stage.ts

- We had the wrong default domain for subscriptions APIs
- Points at the correct domain (a gcp domain)
This caused problems in the 1.259.0 deployment.

bug(functional-tests): Fix default domain for subscriptions on stage

---

packages/fxa-event-broker/package.json
packages/fxa-event-broker/src/client-webhooks/client-webhooks.service.spec.ts
packages/fxa-event-broker/src/client-webhooks/client-webhooks.service.ts
packages/fxa-event-broker/src/firestore/firestore.service.spec.ts
packages/fxa-event-broker/src/firestore/firestore.service.ts
packages/fxa-event-broker/src/firestore/schemas.interface.ts
packages/fxa-event-broker/src/queueworker/queueworker.service.spec.ts
packages/fxa-event-broker/src/queueworker/queueworker.service.ts

Because:
* We need to be able to send all events to resource servers.
This commit:
* Adds a new `isResourceServer` flag to the `ClientWebhooks` interface on the clients Firestore document.
* Includes a new field on the ClientWebhooksService for the queue worker to use to determine if the client is a resource server and distribute all events to it (subscription events if the resource server is configured for the subscription capability).
Closes FXA-7475

feat(broker): add resource server support

---

packages/fxa-settings/src/lib/gql.test.ts
packages/fxa-settings/src/lib/gql.ts

- This was being encoded twice causing it to fail the url validation
- Remove the double encoding, `URLSearchParam` class handles it already
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7573

fix(redirect): Fix double encoded `redirect_to` query param

---

packages/functional-tests/tests/settings/recoveryKey.spec.ts
packages/fxa-content-server/app/styles/tailwind/ctas.css
packages/fxa-react/styles/ctas.css
packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/index.test.tsx
packages/fxa-settings/src/components/GetDataTrio/index.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyDownload/index.test.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyDownload/index.tsx
packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.test.tsx

* We want to ensure that the displayed key matches the download key, and that both can be used to reset the password.
* ~~We want to improve accessibility by preventing redirection in the background while the key is downloaded.~~
UPDATE 2023-05-30: UX/CX is reviewing how to handle the continue action on this step. Holding off on updating at this stage.
* ~~Remove the key from the localized string and include it directly in the file blob.~~
UPDATE 2023-05-30: Avoiding request to relocalize this string.
* Add functional tests to check the content of the downloaded file.
* Add a few missing unit tests for copy button and back button.
* ~~Separate "continue" action from "download" action on account recovery key download page.~~
* Fix margins around copy button in the DataBlock.
* Fix sizing …

fix(fxa-settings): Ensure downloaded recovery key is valid

---

packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx

Because:
* Users with a recovery key see a flash of CompleteResetPassword before being redirected to AccountRecoveryConfirmKey
This commit:
* Adjusts the loading spinner state to only hide when recovery key checks have completed
Fixes FXA-7170
---
See ticket for before.
Here's with this patch, hitting it twice (since it's fast) and then clicking "Don't have a an account recovery key?":
I also tested with an expired link and without a recovery key.
I tried using `account.loading` here because we have a `withLoadingStatus` on the account model and are using `account.loading` in just a couple of other places but there's something weird about it, it seems to load two inputs like it’s showing the complete reset PW screen without text; didn't dig further since we have plans to refactor some of …

fix(react): Hide loading spinner on CompleteResetPassword only when checks complete

---

jest.config.ts
jest.preset.js
nx.json
package.json
tsconfig.base.json
yarn.lock

* Nx released v16!
* Upgrades Nx to v16 using `nx migrate`
Closes FXA-7622

chore(build): upgrade nx to v16

---

packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/payments/fixtures/stripe/customer1.json
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
packages/fxa-payments-server/src/lib/amplitude.ts
packages/fxa-payments-server/src/lib/apiClient.test.ts
packages/fxa-payments-server/src/lib/apiClient.ts
packages/fxa-payments-server/src/lib/test-utils.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.stories.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionIapItem/index.test.tsx
packages/fxa-shared/metrics/amplitude-event.1.schema.json
packages/fxa-shared/test/metrics/amplitude.js

Because:
* We want to add `country_code` of payments on `fxa_pay_subscription_change - success` events
This commit:
* Updates the ajv schema to require it for success events
* Updates API endpoints to return the necessary data
* Passes it to the metrics endpoint
* Updates all applicable tests
Closes FXA-7391

feat(metrics): require country_code_source on upgrade events

---

packages/functional-tests/tests/react-conversion/recoveryKey.spec.ts
packages/fxa-auth-client/lib/recoveryKey.ts
packages/fxa-auth-client/test/recoveryKey.ts
packages/fxa-graphql-api/src/gql/account.resolver.ts
packages/fxa-settings/src/lib/cache.ts
packages/fxa-settings/src/models/Account.ts
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx

Because:
* There's an error when attempting to reset a password with an account recovery key, and other issues were uncovered during the fix
This commit:
* Fixes logic around accountResetToken, ensuring we only fetch getRecoveryBundle once with the same token
* Requests, receives, and sets sessionToken from account recovery reset and normal PW reset
* Uses this session token to perform other requests that must use authClient for now due to 'sessionToken.mustVerify' checks
Closes FXA-7189, FXA-7152
---
~I think we're going to have to unfortunately change all of our other reset PW apollo client calls back to auth client temporarily, which is probably going to fix at least a decent number of bugs. I'm guessing we've been accidentally doing a lot of testing while still authenticated, instead …

fix(react): Password reset unexpected error fixes, with and without recovery key

---

packages/fxa-content-server/server/lib/routes/post-csp.js

- We were generating a lot of error on this validation check
- This value is only used in a report, so the URI requirement isn't mandatory
- Removes the requirement that the string posted is a valid URL
Closes: FXA-7556

task(content): Make csp-report.blocked-uri validation check less strict

---

packages/fxa-event-broker/nest-cli.json
packages/fxa-event-broker/pm2.config.js
packages/fxa-event-broker/src/config.ts
packages/fxa-event-broker/src/queueworker/queueworker.module.ts

- Event broker would fail to start
- Event broker couldn't resolve client capabilities
- Event broker wasn't using devleopment config
- Nest couldn't resolve the ClientWebhooksService
- Configures the location of main.js
- Fixes a path resoultion of evn specific .json files
- Adds ipv4first dns result order node option to fix client capabilities startup
- Adds ClientWebhooksService to QueueworkerModule
These regressions were noticed while working on FXA-7465. It appears they only effect local development, and don't actually address the issue reported. To keep the PR succinct, these changes have been put up separately.

bug(event-broker): Fix startup behavior for local development

---

packages/functional-tests/pages/settings/recoveryKey.ts
packages/functional-tests/tests/settings/recoveryKey.spec.ts
packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/en.ftl
packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/index.test.tsx
packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/index.tsx
packages/fxa-settings/src/components/IconListItem/index.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyConfirmPwd/en.ftl
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyConfirmPwd/index.test.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyConfirmPwd/index.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyDownload/en.ftl
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyDownload/index.test.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyDownload/index.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyHint/en.ftl
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyHint/index.test.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyHint/index.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyInfo/en.ftl
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyInfo/index.test.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyInfo/index.tsx
packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.test.tsx
packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.tsx
packages/fxa-settings/src/components/Settings/Security/index.test.tsx
packages/fxa-settings/src/components/Settings/UnitRowRecoveryKey/en.ftl
packages/fxa-settings/src/components/Settings/UnitRowRecoveryKey/index.test.tsx
packages/fxa-settings/src/components/Settings/UnitRowRecoveryKey/index.tsx

* Content Design has recommended copy changes for the Account recovery key creation flow
* Update ftl strings and fallback text
* Move storage ideas from download to hint flow page, and update styling
* Update tests
Closes: #FXA-7613

feat(fxa-settings): Update recovery key copy and l10n

---

packages/functional-tests/lib/metrics.ts
packages/functional-tests/pages/products/index.ts
packages/functional-tests/pages/relier.ts
packages/functional-tests/tests/subscription-tests/coupons-ui-tests/ui-tests.spec.ts
packages/functional-tests/tests/subscription-tests/subscription.spec.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/test/local/payments/fixtures/stripe/customer1.json
packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
packages/fxa-payments-server/src/lib/amplitude.ts
packages/fxa-payments-server/src/lib/apiClient.test.ts
packages/fxa-payments-server/src/lib/apiClient.ts
packages/fxa-shared/metrics/amplitude-event.1.schema.json
packages/fxa-shared/test/metrics/amplitude.js

Because:
* We need assurances that we are recording the expected data on P1 conversion funnel events.
This commit:
* Extend the `MetricsObserver` to support checking acquisition query parameters with a new method, `getAcquisitionParamsFromEvents`.
* Extend an existing test case to verify acquisition query parameters are sent for the new user checkout flow.
- Add `setEmailAndConfirmNewUser` method to `SubscribePage` class.
* Extend existing test cases to verify all required event-specific fields are sent for the following critical flows:
- new user checkout flow, success
- new user checkout flow, failure
- existing user checkout flow, success
- existing user checkout flow, failure
- existing user plan change (i.e. upgrade) flow, success
Closes #FXA-7364 …

chore(functional-tests): add coverage for P1 payments funnel events

---

packages/fxa-auth-server/lib/profile/updates.js
packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
packages/fxa-auth-server/lib/routes/totp.js
packages/fxa-auth-server/test/local/profile/updates.js
packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
packages/fxa-auth-server/test/local/routes/totp.js
packages/fxa-event-broker/nest-cli.json
packages/fxa-event-broker/pm2.config.js
packages/fxa-event-broker/src/config.ts
packages/fxa-event-broker/src/queueworker/queueworker.module.ts
packages/fxa-profile-server/lib/events.js
packages/fxa-profile-server/test/events.js

- The event-broker was not emmiting events for profile change events.
- Fixes the naming of these events
- Changes profileDataChanged to profileDataChange, which is what the event-broker expects
Closes: FXA-7465
I ran into some other issues while debugging this. See this [PR](https://github.com/mozilla/fxa/pull/15403) for fixes that get the event-broker starting up locally again. Once this lands, the changes in this PR should seem much smaller.

bug(event-broker): Missing profile data changed events

---

packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx

- Upgrades where the interval and interval count do not change, the next invoice date is taken from the invoice preview.
- Fixes the invoice date for scenarioes where interval and interval count do not change, by using the date of the current subscription.
Closes: #FXA-7060

fix(payments): on upgrade next invoice date fix

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-settings/src/models/AppContext.ts
packages/fxa-settings/src/models/mocks.tsx
packages/fxa-settings/src/models/reliers/base-relier.ts
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.tsx
packages/fxa-settings/src/pages/ResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/index.tsx

- We access these settings through the relier
- Uses the relier model to determine if relier is in sync mode
- Some clean up to mocks.tsx
- Removes circular dependency between AppContext and mocks.tsx
Closes: FXA-6804
This is the exact same PR as [this](https://github.com/mozilla/fxa/pull/15395). I amended a commit through VSCODE's IDE and then forced pushed. It turns out the commit must not have actually finished by the time I forced pushed. This resulted in pushing any empty branch, and github subsequently closed the PR, and it cannot be reopened now. The force push was an effort to address your feedback.

task(settings): Use relier hook for ResetPassword flow

---

packages/functional-tests/tests/react-conversion/legal.spec.ts
packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-settings/src/components/App/index.test.tsx
packages/fxa-settings/src/components/LegalWithMarkdown/index.tsx
packages/fxa-settings/src/lib/metrics.ts

- We noticed errors when emitting metrics from legal doc pages
- Makes sure key flowEventData is set when metrics are initialized.
- Minor tweak to routes and back button issue. Fix was borrowed from cookies page.
Closes: FXA-7496

 bug(settings): FlowEventData not set for legal doc pages

---

packages/fxa-settings/src/components/App/index.test.tsx
packages/fxa-settings/src/components/App/index.tsx
packages/fxa-settings/src/components/Settings/PageRecoveryKeyAdd/index.test.tsx
packages/fxa-settings/src/components/Settings/PageSecondaryEmailAdd/index.test.tsx
packages/fxa-settings/src/lib/metrics.test.ts
packages/fxa-settings/src/lib/metrics.ts
packages/fxa-settings/src/lib/utilities.test.ts
packages/fxa-settings/src/lib/utilities.ts

- We would see the same metric being emitted multiple times.
- Introduces a new 'once' utility function that memoizes calls based on key
- Uses this in favor of fancy, but potentially buggy react-ish ways of doing this with useEffect and passing empty dependencies.
- Adds a calls to `initUserPreferences` when metrics initialized in the root app component.
- Adds log to alert developers of situations where user preferences may not have been set.
Closes: FXA-7201
I feel like there could potentially be a separate issue filed for looking more closely into page re-renders. Due to how we are using context it became apparent that re-renders could be triggered. It was unclear if these re-renders were intentional and needed for the page load correctly, or if …

task(settings): Ensure metrics are only emitted once

---

packages/fxa-auth-server/scripts/apple-transfer-users.js
packages/fxa-auth-server/scripts/transfer-users/apple.js
packages/fxa-auth-server/test/scripts/apple-transfer-users.js
packages/fxa-auth-server/test/scripts/fixtures/apple_users.csv

- Ops team needs the ability to run migration script and import users into FxA from Pocket
- Adds script
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7490
I need to find a better way to test this script. Since it is making network calls from another Node process, I can't use nock. I'm putting this up for initial review, it is still missing a few things

feat(apple): Add apple user migrations script

---

packages/functional-tests/pages/login.ts
packages/functional-tests/pages/relier.ts
packages/functional-tests/tests/oauth/oauthPermissions.spec.ts
packages/functional-tests/tests/oauth/oauthPromptNone.spec.ts
packages/fxa-content-server/tests/functional.js
packages/fxa-content-server/tests/functional_regression.js

As part of the playwright test migration, the [oauth permissions](https://github.com/pdehaan/fxa/blob/0ae60a1df256332e8581898db39b0e4997bab7b4/packages/fxa-content-server/tests/functional/oauth_permissions.js) and [oauth prompt none](https://github.com/pdehaan/fxa/blob/0ae60a1df256332e8581898db39b0e4997bab7b4/packages/fxa-content-server/tests/functional/oauth_prompt_none.js) have been rewritten in this PR.
contains the tests identified as 'Keep' in the [analysis sheet](https://docs.google.com/spreadsheets/d/11Wq-Y-ipeNFXqLHbr3GJCh_f_qEAG-CUuqBt5Dcnh5k/edit#gid=1966588528) for [oauth permissions](https://github.com/pdehaan/fxa/blob/0ae60a1df256332e8581898db39b0e4997bab7b4/packages/fxa-content-server/tests/functional/oauth_permissions.js) and [oauth prompt …

test(functional): rewrite oauth permissions tests

---

packages/fxa-content-server/app/scripts/lib/metrics.js
packages/fxa-content-server/app/tests/spec/lib/metrics.js
packages/fxa-content-server/server/lib/sentry.js
packages/fxa-content-server/tests/server/sentry.js
packages/fxa-shared/metrics/validate.ts

- We continue to see issues with navigation timing data being posted from clients
- Is a follow up to FXA-7005
- Will not post erroneous  L2 or L2 timing data.
- The content server now filters out 'navigationTiming' errors from sentry.
Closes: FXA-7005
We are currently investigating alternatives for getting this data. We will be looking into tapping Sentry's performance data if possible. See FXA-7558 for more info.

task(content): Don't report bad L2 navigation timing data either

---

packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts

- Coupon endpoint should support credentialed requests.
- Adds support for optional auth credentials.
Closes: #FXA-7451

fix(payments): add auth to coupon API

---

packages/fxa-settings/src/components/Settings/FlowRecoveryKeyConfirmPwd/index.tsx

* The account recovery key creation flow's password input label must be localized.
* The label should only be read once by speech readers.
* Use ftlMsgResolver for the label's l10n.
Closes: #FXA-7565
Before (not localized)
After (localized)
Tested with VoiceOver on MacOS - reproduced that label was previously read twice, and now only once with this PR.

fix(fxa-settings): Fix l10n and a11y of confirm password input

---

packages/fxa-content-server/app/scripts/templates/index.mustache
packages/fxa-content-server/app/tests/spec/views/index.js
packages/fxa-content-server/tests/functional/lib/selectors.js

Because:
* Users have to have an FxA account to register/login to Sync so we should not allow them to login with third-party auth in this flow
This commit:
* Hides these buttons if the flow is Sync
Fixes FXA-7655
---
Test locally @ [here](http://localhost:3030/?context=fx_desktop_v3&entrypoint=fxa%3Aenter_email&service=sync&action=email&forceExperiment=thirdPartyAuth&forceExperimentGroup=treatment) before and after patch. Looked better to me to leave the "firefox family" text when third party auth buttons are hidden - there's a nicer way to do this in Backbone/Mustache than have two sets of `#firefox-family-services` references in the mustache file (like setting a `shouldShowThirdPartyAuth` method) but we're refactoring this all soon enough so 🤷‍♀️ as-is seems fine to me.

fix(third-party-auth): Don't show Google/Apple login buttons in the Sync flow

---

packages/fxa-content-server/app/scripts/templates/partial/user-card.mustache
packages/fxa-settings/src/pages/Signin/index.tsx

Because:
* A web view modal is displayed when users are logging into FxA and on iPad the "Sign in" button is hidden unless the user scrolls
This commit:
* Reduces the size of the avatar, which increased at the mobileLandscape breakpoint and which is what the web view was displaying at, to increase at the tablet breakpoint instead
Fixes FXA-7425
---
There are a few different ways we could have tried to fix this:
1. Set a classname based on user agent and screen sizing, e.g. if iPad and still in `mobileLandscape` breakpoint. However, this is tricky for iPad because in the last few years, iOS for iPad has sent out a Desktop UA. We'd have to check if `iPad` (older iOS) or Desktop UA + check current screen size, and rerun when the window size changes... Would introduce a lot of overhead for …

fix(ipad): Reduce avatar size on mobileLandscape for iPad web view modal

---

packages/fxa-settings/src/components/Settings/FlowRecoveryKeyHint/en.ftl
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyHint/index.test.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyHint/index.tsx

* Previous sentence included two "it"s that could confuse localizers.
* We want to ensure that messages are clear for localizers.
* Update string and add comment
Closes: #FXA-7724

fix(l10n): Clarify recovery key hint explanation for l10n

---

packages/fxa-auth-server/lib/payments/currencies.ts

- We are aiming to launch VPN in 16 new countries in Europe.
- Adds additional currencies to `supportedPayPalCurrencies`.
Closes FXA-7606
BGN, HUF (decimals), RON and RSD are not currently supported by PayPal as per https://developer.paypal.com/api/nvp-soap/currency-codes/ and are therefore not included for the time being.

feat(payments): update supported PayPal currencies list

---

packages/fxa-graphql-api/src/decorators.ts

- The correct ip address was not being sent to auth-server from graphql server
- Sets the `x-forwarded-for` header to the cllient ip address, the auth-server uses this value to perform geo location
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6858

fix(ip): Set x-forwarded-for header from gql to auth-server

---

packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/en.ftl
packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/index.stories.tsx
packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/index.test.tsx
packages/fxa-settings/src/components/ButtonDownloadRecoveryKey/index.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyDownload/index.test.tsx
packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.test.tsx

* Localized plain text file is not rendering as expected on Android and Windows.
* Hidden directionality characters get copied with key, resulting in the key being marked as invalid during password reset.
* Reversal is temporary to prevent this issue from blocking deployment while next steps are determined.
* Serve key only in the file download.
Closes: #FXA-7688

task(fxa-settings): Revert localized content in key download file

---

packages/fxa-settings/src/components/Settings/FlowRecoveryKeyHint/index.tsx
packages/fxa-settings/src/pages/ResetPassword/index.tsx

* Controlled components that use `useWatch` to obtain the current input value would reset to default (empty string) on submit or re-render
* We want to ensure that if the submit aborts due to an error or if the page re-renders, controlled components will display the current input value and not an empty string.
* Use `getValues` to set the default input value for `useWatch` in both places where it is used in the codebase (`FlowRecoveryKeyHint` and `ResetPassword`)
Closes: #FXA-7547

fix(fxa-settings): Ensure useWatch uses current input value as default

---

packages/functional-tests/lib/channels.ts
packages/functional-tests/pages/settings/changePassword.ts
packages/functional-tests/tests/syncV3/settings.spec.ts

As part of the playwright test migration, the [sync v3 settings tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sync_v3_settings.js) have been rewritten in this PR.
contains the [sync v3 settings tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sync_v3_settings.js)
Closes: [FXA-5912](https://mozilla-hub.atlassian.net/browse/FXA-5912)
[FXA-5912]: https://mozilla-hub.atlassian.net/browse/FXA-5912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(functional): rewrite sync v3 settings test

---

packages/fxa-auth-server/lib/server.js
packages/fxa-auth-server/test/local/server.js

Because:
* we do not want to be inundated with request validation errors that are outside of our control
This commit:
* updates the reporting logic to only report response validation errors for all environments
Closes #FXA-7664

fix(auth): only Report Response Validation Errors

---

packages/fxa-auth-server/lib/payments/stripe-formatter.ts
packages/fxa-auth-server/test/local/payments/stripe-formatter.js

Because:
* stripe started returning an empty string for tax display name which causes our response validation to fail
This commit:
* ORs an empty string with undefined so that undefined is returned when display name is an empty string
Closes #FXA-7811

fix(auth): handle Empty String Tax Display Name

---

packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionIapItem/SubscriptionIapItem.tsx
packages/fxa-react/lib/utils.tsx
packages/fxa-settings/src/components/Settings/PageRecentActivity/SecurityEvent.tsx
packages/fxa-settings/src/components/Settings/PageRecentActivity/en.ftl
packages/fxa-settings/src/components/Settings/Security/index.tsx

- Subscription management date is localized to `en` locale, regardless of browser language.
- SecurityEvent created date is not being localized.
- Pass FluentDate to Fluent localization libraries to correctly localize dates.
- Add localization string for SecurityEvent created date.
Closes: #FXA-7795
English
German
English
German
English
German

fix(l10n): fix date localization in sub management

---

packages/fxa-graphql-api/src/gql/dto/payload/password-forgot.ts
packages/fxa-settings/src/components/LinkExpiredResetPassword/index.test.tsx
packages/fxa-settings/src/components/LinkExpiredResetPassword/index.tsx
packages/fxa-settings/src/lib/channels/helpers.ts
packages/fxa-settings/src/lib/storybook-utils.ts
packages/fxa-settings/src/models/Account.ts
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/mocks.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.tsx
packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/mocks.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx
packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/mocks.tsx
packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.tsx
packages/fxa-settings/src/pages/ResetPassword/index.stories.tsx
packages/fxa-settings/src/pages/ResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/index.tsx

Because:
* The browser should be be notified when a PW reset occurs on a verified account through the Sync flow, as this logs the user in
This commit:
* Conditionally runs the fxaLogin command with required account data after a password reset with or without recovery key, when the flow is sync
* Receives other values off the account reset call needed for webchannel account data
* Temporarily checks for SyncBasic and SyncDesktop flows to run the check because we don't need to port over context in local storage logic (which would account for SyncDesktop only), since we are switching to codes soon
* Sends up `service` with the email request so we can append the param and check when link is received (causing the  SyncBasic integration)
* Removes resendResetPassword and calls resetPassword …

feat(react): Send fxaLogin webchannel message conditionally after password reset

---

packages/fxa-auth-server/config/index.ts
packages/fxa-payments-server/server/config/index.js

Because:
* we want to use feature flags to enable/disable work
This commit:
* adds an env var for the stripe invoice immediately epic
Closes #FXA-7847

feat(invoice): add Env Vars for Stripe Invoice Immediately

---

packages/fxa-settings/src/lib/channels/firefox.ts

- We want to send fxaccounts:oauth_login events
- Adds new FirefoxCommand, OAuthLogin.
- Adds new type for OAuthLogins
- Adds ability to send command
Closes: FXA-6616
This was just a one pointer. There will be more testing when the change is actually integrated. The data type for FxAOAuthLogin was determined by looking at [existing code](https://github.com/mozilla/fxa/blob/6707c39c029f6e1898f12965f686a64c8b6e1526/packages/fxa-content-server/app/scripts/models/auth_brokers/pairing/supplicant-webchannel.js#L18). This data type seems typical of data associated with a login event.

task(settings): Support OAuth Login Event

---

packages/functional-tests/tests/oauth/signinTokenCode.spec.ts
packages/fxa-auth-client/lib/client.ts
packages/fxa-auth-server/lib/db/index.js
packages/fxa-auth-server/lib/routes/account.ts
packages/fxa-auth-server/test/local/routes/account.js
packages/fxa-auth-server/test/mocks.js
packages/fxa-auth-server/test/remote/db_tests.js
packages/fxa-content-server/app/scripts/lib/fxa-client.js
packages/fxa-content-server/app/scripts/models/account.js
packages/fxa-content-server/app/scripts/models/user.js
packages/fxa-content-server/app/scripts/templates/partial/third-party-auth.mustache
packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache
packages/fxa-content-server/app/scripts/views/index.js
packages/fxa-content-server/app/scripts/views/sign_in_password.js
packages/fxa-content-server/app/tests/spec/lib/fxa-client.js
packages/fxa-content-server/app/tests/spec/models/account.js
packages/fxa-content-server/app/tests/spec/views/index.js
packages/fxa-content-server/app/tests/spec/views/sign_in_password.js
packages/fxa-shared/db/models/auth/account.ts

Because:
* Users that have an account via third-party auth and have not yet set a password should be shown a login screen that shows the login button(s) relevant to them instead of the 'enter a password' view
This commit:
* Adds necessary conditional logic to sign_in_password
* Updates the account/status endpoint to return third party auth status data when requested
closes FXA-4776
--
Still need to write tests. Opening early for correspondence with @vbudhram.

feat(third-party-auth): Conditionally render login buttons on signin

---

packages/fxa-auth-server/scripts/transfer-users/apple.js
packages/fxa-auth-server/test/scripts/apple-transfer-users.js
packages/fxa-event-broker/src/jwtset/jwtset.service.ts
packages/fxa-event-broker/src/jwtset/set.interface.ts
packages/fxa-event-broker/src/pubsub-proxy/pubsub-proxy.controller.ts
packages/fxa-event-broker/src/queueworker/queueworker.service.spec.ts
packages/fxa-event-broker/src/queueworker/queueworker.service.ts
packages/fxa-event-broker/src/queueworker/service-notification.interface.ts
packages/fxa-event-broker/src/queueworker/sqs.dto.ts

- Pocket needs to do some account reconcilation after FxA imports the user
- Emits an account event via the event-broker that contains updated account information
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7666
@dschom Tagging you for review on this since you reviewed the original script. I wasn't able to verify the SQS message, but I was able to test that the event gets emitted properly with the Pocket clientId.
Event broker log when running the script
```
18|event-broker  | 2023-06-23T16:34:15: DEBUG fxa-event-broker.default.from.sqsMessage: {"msg":{"uid":"14699a2d8b044ccbb2d43344e31d9e0a","appleEmail":"amberappletesting1@gmail.com","fxaEmail":"amberappletesting1@gmail.com","transferSub":"000107.r739567061c144a2b81c45269552ef591","success":true,"err":"","timestamp":168755245578 …
```

Emit account event for Pocket Apple user migration

---

packages/fxa-settings/src/components/Settings/FlowRecoveryKeyConfirmPwd/index.tsx
packages/fxa-settings/src/components/Settings/FlowRecoveryKeyHint/index.tsx
packages/fxa-settings/src/components/Settings/Modal/index.tsx
packages/fxa-settings/src/components/Settings/UnitRowRecoveryKey/index.tsx

* We want to prevent users from clicking on submit buttons multiple times while account updates are in progress, and also provide users with feedback that the form has been submitted.
* Clicking on the confirm password button multiple times would result in an error banner "Account recovery key already exists"
* Disable submit button when account is in loading state.
Closes: #FXA-7551
https://github.com/mozilla/fxa/assets/22231637/1efb0666-82a8-4b58-8ef9-2cefa15b528f

fix(fxa-settings): Disable double-clicking on buttons in account recovery key flow

---

packages/fxa-auth-server/lib/payments/currencies.ts

- There are no plans configured to support RSD and, currently, PayPal does not support it.
- Removes RSD from approved currencies list.
Closes FXA-7815

chore(payments): remove RSD from approved currencies

---

libs/payments/paypal/src/lib/util.spec.ts
libs/payments/paypal/src/lib/util.ts

- objectToNVP converts object properties with undefined values to a string with value undefined. PayPal expects undefined values to be an empty string param.
- Converts object properties with an undefined value to empty string.

fix(payments/paypal): convert undefined before request

---

packages/functional-tests/lib/ci-reporter.ts
packages/functional-tests/lib/email.ts
packages/functional-tests/lib/react-flag.ts
packages/functional-tests/pages/index.ts
packages/functional-tests/pages/relier.ts
packages/functional-tests/pages/resetPassword.ts
packages/functional-tests/pages/resetPasswordReact.ts
packages/functional-tests/tests/oauth/resetPassword.spec.ts
packages/functional-tests/tests/react-conversion/cannotCreateAccount.spec.ts
packages/functional-tests/tests/react-conversion/legal.spec.ts
packages/functional-tests/tests/react-conversion/recoveryKey.spec.ts
packages/functional-tests/tests/react-conversion/resetPassword.spec.ts
packages/functional-tests/tests/react-conversion/syncV3ResetPassword.spec.ts
packages/functional-tests/tests/reset-password/resetPassword.spec.ts
packages/functional-tests/tests/settings/changePassword.spec.ts
packages/functional-tests/tests/settings/recoveryKey.spec.ts
packages/functional-tests/tests/signin/signIn.spec.ts
packages/functional-tests/tests/syncV3/syncV3ResetPassword.spec.ts
packages/fxa-settings/src/pages/ResetPassword/index.test.tsx
packages/fxa-settings/src/pages/ResetPassword/index.tsx

- We want to enable all reset password functional tests for both react and content-server
* Add playwright test for content-server reset password "happy path"
* Add additional tests for react reset password route
* Add react reset password test for sync
* Move some react reset password tests to unit tests 
Closes: #FXA-7248
Previous [draft PR](https://github.com/mozilla/fxa/pull/15427) was closed due to an error in the ticket number.

task(functional-tests): Add missing reset password tests in Playwright

---

packages/fxa-auth-server/lib/routes/validators.js
packages/fxa-content-server/app/scripts/lib/newsletters.js
packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache
packages/fxa-content-server/app/scripts/views/mixins/email-opt-in-mixin.js
packages/fxa-content-server/app/tests/spec/views/mixins/email-opt-in-mixin.js
packages/fxa-content-server/app/tests/spec/views/sign_up_password.js

Because:
* We want to update the label text for two existing newsletters and add a new option to subscribe users to two new newsletters from one new checkbox
This commit:
* Updates labels per ticket
* Adds new checkbox with array of slugs for new newsletter option, does not HTML escape label due to ampersand
* Updates server validity check, tests
Closes FXA-7527

feat(newsletters): Update newsletter checkbox labels, add new newsletter checkbox w/two slugs

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-shared/payments/stripe.ts

Because:
* we want to invoice immediately when subscriptions are upgraded
This commit:
* passes in the parameter to stripe (conditionally on env var) to invoice immediately on sub upgrades
Closes #FXA-7438

feat(auth): pass In 'always_invoice' On Subscription Upgrade

---

packages/functional-tests/pages/forceAuth/index.ts
packages/functional-tests/pages/index.ts
packages/functional-tests/pages/login.ts
packages/functional-tests/pages/resetPassword.ts
packages/functional-tests/tests/misc/forceAuth.spec.ts
packages/functional-tests/tests/oauth/webchannel.spec.ts
packages/functional-tests/tests/syncV3/signUpWithCWTS.spec.ts

As part of the playwright test migration, the [sync sign up with CWTS tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sync_v3_sign_up.js) and [force auth tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/force_auth.js) have been rewritten in this PR.
contains the [sync sign up with CWTS tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/sync_v3_sign_up.js) and [force auth tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/force_auth.js)
Closes: FXA-5928
Any other information that is important to …

test(functional) : rewrite sync sign up with CWTS tests

---

packages/functional-tests/tests/misc/forceAuth.spec.ts

- Changes introduced in #15478 removed the return value from method resetPasswordHeader and confirmResetPasswordHeader
- Updates test to no longer expect a return value from method resetPasswordHeader and confirmResetPasswordHeader

fix(functional-tests): update forceAuth test

---

packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/en.ftl
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.stories.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx

- Now that we are immediately invoicing on upgrades regardless of billing cycle, we want to revise copy throughout the checkout and email process to improve UX and be clear on payment dates and amounts.
- Revises the acknowledgement copy on upgrades.
- Shows updated copy when `useStripeImmediatelyInvoice` flag is set to true.
- Updates tests and stories when aforementioned flag is set to true, where applicable.
Closes: FXA-7399

feat(payments): revise acknowledgement copy on upgrades

---

packages/functional-tests/pages/login.ts
packages/functional-tests/tests/signin/signIn.spec.ts
packages/functional-tests/tests/syncV3/fxDesktopHandshake.spec.ts

As part of the playwright test migration, the [fx desktop handshake tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/fx_desktop_handshake.js) and sign in with bounced email (happy path) test have been rewritten in this PR.
contains the [fx desktop handshake tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/fx_desktop_handshake.js) and sign in with bounced email (happy path) test 
Closes: FXA-5907

test(functional): rewrite fx desktop handshake tests

---

packages/fxa-auth-server/scripts/prune-tokens.ts
packages/fxa-customs-server/lib/settings/settings.js

- We have a couple logs that fail to get imported in BigQuery
- Updates the logs to not have nested objects
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7679

fix(logs): Fix issues with bigquery logs

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/test/local/payments/stripe.js

- The incorrect amounts are showing in the upgrade email template for same and different billing cycles.
- Corrects amounts listed in same billing cycle upgrade email.
- Corrects amounts listed in different billing cycle upgrade email.
- Updates applicable stories and tests.
Closes: FXA-7349
The following scenarios were tested with both inclusive and exclusive tax(es) and for both same and different billing cycle (total of 16 different scenarios):
- single tax
- single tax with coupon
- multiple taxes
- multiple taxes with coupon
Additionally tested upgrading from exclusive to inclusive and vice versa with the aforementioned scenarios.

fix(emails): correct amounts in upgrade email

---

packages/functional-tests/tests/react-conversion/resetPassword.spec.ts
packages/fxa-settings/src/models/Account.ts

- Location in emails sent from React password reset pages were not showing the correct location
- There is an issue with using client -> GraphQL -> auth client -> auth server where the IP address from client is not getting propgated to the auth-server
- Updates the pages to use the auth-client directly so the correct IP address is geolocated
There are not unit test for these flows but things are covered with the functional tests.

fix(logs): Update password reset react pages to use auth client when neede

---

packages/fxa-content-server/app/scripts/templates/partial/third-party-auth.mustache
packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache
packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache
packages/fxa-content-server/app/styles/modules/_custom-rows.scss
packages/fxa-content-server/app/tests/spec/views/sign_in_password.js

Because:
* We are linking out to the English version of some links and want the site to handle language negotiation instead
* We want to display ToS and Privacy notice for Pocket and other users
This commit:
* Removes the hard-coded 'en' from these links
* Moves links out of signin `<form>`, always displays ToS and Privacy link and includes Pocket ToS and Privacy link when the client is Pocket
Closes FXA-7920
Closes FXA-7865
---
Ignore blurriness of 2nd pic, did something wonky during the resize. This is a normal login with a passwordless account and then through Pocket.

fix(third-party-auth): ToS + Privacy link tweaks

---

nx.json
package.json
yarn.lock

Because:
* We'd like faster builds to avoid repeat work.
This commit:
* Uses nx-cloud as a cache for build/test/lint operations.

chore: use nx-cloud

---

packages/fxa-auth-server/lib/pushpayloads.schema.json

- Auth strict mode type "object" was missing from some properties in `pushpayloads.schema.json` file and throwing a warning whenever a test is run in `auth`.
- Adds strict mode type "object" to aforementioned `json` file.
Closes [FXA-7952](https://mozilla-hub.atlassian.net/browse/FXA-7952)
[FXA-7952]: https://mozilla-hub.atlassian.net/browse/FXA-7952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(auth): adds missing strict mode type "object" in json file

---

packages/fxa-auth-server/scripts/transfer-users/apple.js
packages/fxa-auth-server/test/scripts/apple-transfer-users.js

- Apple only returns email when the user is private, otherwise we should use Pocket email
- Updates script to use the Pocket email and check Apple email as last case

fix(scripts): Update scripts to handle apple private emails
