mozilla/fxa

packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/lib/payments/stripe-formatter.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/subscriptions/mozilla.ts, packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/test/local/payments/capability.js, packages/fxa-auth-server/test/local/payments/fixtures/stripe/customer1.json, packages/fxa-auth-server/test/local/payments/stripe-formatter.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions/mozilla.js, packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js, packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js, packages/fxa-shared/dto/auth/payments/invoice.ts, packages/fxa-shared/subscriptions/types.ts
Because:
* we want proration information (one_time_charge and prorated_amount) to be returned with the invoice preview
This commit:
* changes the return type of invoice preview to be a named tuple, one with and one without the proration information, and formats the API response accordingly
Closes #FXA-6690
=> feat(auth): update Invoice Preview to Handle Prorations

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/en.ftl, packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.mjml, packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.stories.ts, packages/fxa-auth-server/test/local/payments/stripe.js
- We are moving to immediately invoicing and combining same and different billing cycle email templates.
- Removes condition for same billing in `mjml` template.
- Updates stripe to remove references for same billing behaviour.
- Updates applicable tests.
- Updates applicable stories.
Closes FXA-6691
=> feat(payments): remove same billing copy from subscription upgrade

.github/workflows/l10n-gettext-extract.yml
Because:
* This directory is not always present. When we try to just 'rm' when it doesn't exist, a hidden error is thrown
This commit:
* Simply adds "-rf" to the rm command for ./locale/templates/LC_MESSAGES/*
Fixes FXA-7862
---
Currently not sure _why_ this isn't always present, but I remember some branch last week that I later force-pushed to that had this passing with string changes so I didn't remove the line instead. I can investigate more if we want and find that CI run, but, @bcolsson tagging you for review since you'd written part of this script.
Facepalming a bit here since I got there by process of elimination, but see #15472 (I forgot to add back one file in that final commit). I'm not sure why [this error](https://github.com/mozilla/fxa/actions/runs/5558663789/jobs/10154019214) …
=> fix(ci): Add -rf to dir removal to fix string extraction test

packages/fxa-shared/sentry/pii-filter-actions.ts, packages/fxa-shared/sentry/pii-filters.ts, packages/fxa-shared/test/sentry/pii-filters.ts
- We want to sanitize validation errors which are held in sentry event 'context'
- Scrubs event.context
- Increase default depth to 6 because it's condusive to validation errors.
- Updates pii test with semi realistic validation error data.
Closes: FXA-7667
=> task(sentry): Scrub PII on validation errors

packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/test/local/senders/emails.ts
Because:
* Many of our emails did not send with a correctly localized date
This commit:
* Sends the acceptLanguage header through our determineLocale helper before using it in Moment, which requires a single locale
fixes FXA-7930
---
You can test this by changing your language preference in-browser and observing in MailDev before and after this patch, I manually checked Dutch and Japanese. Any email that uses `_constructLocalTimeString` is affected. Our tests assumed the accept language was already a single locale.
This also adjusted the time output which looks more correct to me.
Before and after:
=> fix(emails): Pass single locale to Moment for unlocalized dates

.circleci/config.yml, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-payments-server/src/components/PlanDetails/index.tsx, packages/fxa-payments-server/src/lib/format.test.ts, packages/fxa-payments-server/src/lib/formats.ts, packages/fxa-payments-server/src/lib/test-utils.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/en.ftl, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.stories.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx, packages/fxa-shared/dto/auth/payments/invoice.ts
- We need to show the customer what is owed and when (i.e. proration) on checkout.
- Updates `PlanUpgradeDetails` component and invoice preview to include proration amount.
- Adds a helper function to format for only plan intervals.
- Shows updated content when `useStripeImmediatelyInvoice` flag is set to `true`.
- Updates tests and stories when aforementioned flag is set to `true`, where applicable.
Closes FXA-6878
=> feat(payments): update PlanUpgradeDetails component content

packages/fxa-auth-server/scripts/create-mock-iap-subscriptions/mock-iap-subscription-manager.ts, packages/fxa-auth-server/scripts/set-subscription-purchases-apple-iap.ts, packages/fxa-auth-server/scripts/set-subscription-purchases-apple-iap/set-subscription-purchases-apple-iap.ts, packages/fxa-auth-server/test/local/payments/iap/apple-app-store/purchase-manager.js, packages/fxa-shared/payments/iap/apple-app-store/purchase-manager.ts
Because:
* The update method only updates existing fields and doesn't remove optional fields.
* The set method replaces the entire document.
This commit:
* Uses the set method instead of update, so we don't have stale optional properties left on the subscription in Firestore.
Closes #FXA-7118
- To test locally:
- You need App Store Server API sandbox credentials (see Ecosystem docs for how to obtain)
- Alternatively, I can show you this working for me locally or send you an `apiResponse` to temporarily stub out the API call.
- Start FxA locally
- Create a local FxA account and note the uid
- `cd packages/fxa-auth-server && yarn run create-mock-iap --uid=${uidYouJustCreated}`
- Go into stage Firestore, for the `fxa-auth-stage-iap-app-store-purchases` …
=> fix(auth): use Firestore set method to update Apple IAP subscriptions

docs/adr/0039-use-react-container-component-abstraction.md
Because:
* The Account class model has become too large and due to its mandatory use for all API calls, combined with concerns about over fetching, the excessive use of Context, more diverse data requirements, and a preference for Apollo Client hooks, we need an improved pattern moving forward
This commit:
* Provides an ADR to summarize problems and the proposed solution
closes FXA-7627
---
[See prototoype](https://github.com/mozilla/fxa/pull/15493/).
We can begin implementing this pattern when we work on the reset password redesign.
=> chore(adr): Use React container component abstraction (fxa-settings)

packages/functional-tests/pages/login.ts, packages/functional-tests/pages/products/index.ts, packages/functional-tests/pages/relier.ts, packages/functional-tests/pages/settings/avatar.ts, packages/functional-tests/pages/settings/changePassword.ts, packages/functional-tests/pages/settings/components/unitRow.ts, packages/functional-tests/pages/settings/displayName.ts, packages/functional-tests/pages/settings/index.ts, packages/functional-tests/pages/settings/layout.ts, packages/functional-tests/pages/settings/recoveryKey.ts, packages/functional-tests/pages/settings/secondaryEmail.ts, packages/functional-tests/pages/settings/totp.ts, packages/functional-tests/tests/misc.spec.ts, packages/functional-tests/tests/misc/cookiesDisabled.spec.ts, packages/functional-tests/tests/misc/fourOhFour.spec.ts, packages/functional-tests/tests/oauth/oauthPermissions.spec.ts, packages/functional-tests/tests/oauth/oauthPromptNone.spec.ts, packages/functional-tests/tests/oauth/signinTokenCode.spec.ts, packages/functional-tests/tests/postVerify/accountRecovery.spec.ts, packages/functional-tests/tests/settings/password.spec.ts, packages/functional-tests/tests/settings/passwordVisibility.spec.ts, packages/functional-tests/tests/settings/recoveryKey.spec.ts, packages/functional-tests/tests/signUp/signUpWithCode.spec.ts, packages/functional-tests/tests/signin/connectAnotherDevice.spec.ts, packages/functional-tests/tests/signin/relyingParties.spec.ts, packages/functional-tests/tests/subscription-tests/support.spec.ts, packages/functional-tests/tests/syncV3/signIn.spec.ts, packages/functional-tests/tests/syncV3/signUp.spec.ts, packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts
- The Playwright tests were using deprecated functions (`waitForNavigations()`) and use of `networkidle` and needed to be replaced.
- Removes and replaces deprecated functions `waitForNavigations()` and use of `networkidle`
- Also added a `waitForLoadState()` for the failing nightly test, to load the localhost website from  the relier page. Ran the full suite of tests thrice and it passed everytime.
Closes: FXA-7794 FXA-7792 FXA-7942
=> Test cleanup

packages/fxa-shared/speed-trap/timers.js
- Some devices may report performance.timeOrigin as a float instead of an int
- Converts performance.timeOrigin value to to an int
Closes: FXA-6477
=> fix(content): Make sure startTime is an integer

_dev/docker/ci/Dockerfile.dockerignore
- Our CI image build was failing
- Makes an exception for the `configs/gql/allowlist` folder in the dockerignore file
=> fix(ci): Fix broken ci images due to missing allowlist folder

.circleci/config.yml
- Some resubscription tests were failing/flaking/timing out
- Increase the playwright functional test resource class from large to xlarge.
=> fix(CircleCI): Increase playwright resource class to xlarge

packages/functional-tests/pages/layout.ts, packages/functional-tests/pages/settings/layout.ts, packages/functional-tests/tests/react-conversion/oauthResetPassword.spec.ts, packages/functional-tests/tests/react-conversion/recoveryKey.spec.ts, packages/functional-tests/tests/settings/password.spec.ts, packages/functional-tests/tests/settings/recoveryKey.spec.ts, packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/index.js, packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/new-recovery-key-UI.js, packages/fxa-content-server/app/scripts/lib/new-recovery-key-UI-experiment-mixin.js, packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/index.js, packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/new-recovery-key-UI.js, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.tsx, packages/fxa-settings/src/components/Settings/PageSettings/index.tsx, packages/fxa-settings/src/components/Settings/Security/index.tsx, packages/fxa-settings/src/components/Settings/UnitRowRecoveryKey/index.test.tsx, packages/fxa-settings/src/components/Settings/UnitRowRecoveryKey/index.tsx, packages/fxa-settings/src/components/Settings/index.tsx, packages/fxa-settings/src/index.tsx
feat(settings): Rollout new account recovery flow at 15%
Because:
* We want to rollout the new account recovery key creation flow to 15% of users before rolling out to 100% on prod.
This commit:
* Add NewRecoveryKeyUI experiment with 15% rollout
* Passes experiment group to Settings App, allows forceExperiment
* Conditionally render new UI if user is in treatment group AND feature flag is turned on
* Update related tests
Closes #[FXA-8030](https://mozilla-hub.atlassian.net/browse/FXA-8030)
[FXA-8030]: https://mozilla-hub.atlassian.net/browse/FXA-8030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(settings): Rollout new account recovery flow at 15%

packages/fxa-auth-server/lib/routes/subscriptions/apple.ts, packages/fxa-auth-server/test/local/routes/subscriptions/apple.js
This reverts commit c2c4ea035e8581f4f24ba7bb2fb4f41befc3208c.
Closes: #FXA-5848
=> Revert "chore(auth): allow profile scope on App Store registration route"

_dev/pm2/start.sh, _scripts/check-db-patcher.sh
- On stack startup, services start before mysql patches have completed, causing profile-server to fail on startup.
- Adds script to check if patcher script has started and is still running.
=> feat(infra): wait for db patches on startup

packages/fxa-admin-server/nest-cli.json, packages/fxa-graphql-api/nest-cli.json
- Allowlists weren't getting copied to build directory
- Includes allowlists as assets
This issue surfaced in the train 263.1 build. During development and test we run code with nest start which was not affected and able to resolve the allowlist config files. For production we use nest build to 'compile' our code into the dist folder. This required some extra 'asset' configuration to ensure the allowlists were copied over correctly.
=> bug(admin-server,graphql): Fix missing allowlists

packages/functional-tests/lib/targets/base.ts, packages/fxa-auth-client/package.json
Because:
- fxa-auth-client is used directly in Playwright tests, and Playwright has its own require or import logic
This commit:
- adds "type" in package.json for Playwright to figure it out
=> fix(esm-cjs-hell): add module type hints for Playwright

packages/fxa-settings/src/components/Settings/ConnectedServices/en.ftl, packages/fxa-settings/src/components/Settings/PageRecentActivity/SecurityEvent.tsx, packages/fxa-settings/src/components/Settings/PageRecentActivity/en.ftl, packages/fxa-settings/src/components/Settings/PageRecentActivity/index.test.tsx, packages/fxa-settings/src/components/Settings/PageRecentActivity/index.tsx, packages/fxa-settings/src/components/Settings/Security/en.ftl, packages/fxa-settings/src/components/Settings/Security/index.tsx
* Some real security events were showing as "unknown" in the user-facing "Recent account activity" list in account settings
* Update the list of security events in Settings to include user-facing names for all existing events and add corresponding FTL strings
* Update FTL messages and fallback text to standardize copy style
* Update styling of the "recent account activity" link in the security section
Closes: #FXA-7974, FXA-7102
New styling for link:
Updated list styling for RTL and updated date formatting (screenshot is for hebrew, but strings are new/updated and not yet localized):
=> fix(settings): Show event names in recent account activity

packages/fxa-auth-client/.cjs.package.json, packages/fxa-auth-client/package.json
Because:
- Playwright still cannot resolve the auth-client module
This commit:
- adds a package.json with exports mapping
=> fix(playwright): add exports in auth-client cjs dist

packages/fxa-settings/src/components/Settings/BentoMenu/index.tsx
Because:
* The old URL would send desktop users to Apple's store
This commit:
* Updates the URL
Closes FXA-7444
=> feat: update adjust.com URL

packages/fxa-content-server/app/scripts/lib/router.js
Because:
* We are incorrectly redirecting users to legal/terms
This commit:
* Updates content-server router to direct to the correct path
fixes FXA-8050
=> fix(content-server): Update ':locale/legal/privacy' route

packages/fxa-payments-server/src/routes/Subscriptions/ActionButton.tsx
- the Manage button from Subscription Management page did nothing when clicked
- fixes it so the Manage button opens up a modal when clicked
Closes: [FXA-8047](https://mozilla-hub.atlassian.net/browse/FXA-8047)
[FXA-8047]: https://mozilla-hub.atlassian.net/browse/FXA-8047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(payments): Manage button from Subscription management page does nothing when clicked

packages/functional-tests/pages/resetPassword.ts, packages/fxa-settings/src/components/InputText/index.tsx
* Input label should be narrated only once by screen readers, but it was duplicated due to the label text being applied to the input title.
* Title should only be used if it provides information in addition to the label.
* Remove the title from InputText component because it was only duplicating the label.
* Update reset password page model (for functional test) to `getByLabel` instead of `getByTitle`
Closes: #FXA-7565
Before fix, label duplicated:
After fix, label only present once in accessibility tree:
=> fix(settings): Remove label duplicated in InputText title attribute

packages/fxa-content-server/app/scripts/lib/glean/index.ts, packages/fxa-content-server/app/scripts/views/sign_in_totp_code.js, packages/fxa-content-server/app/tests/spec/lib/glean.js, packages/fxa-content-server/app/tests/spec/views/sign_in_totp_code.js
This commit also adds some missing tests for previously implemented events.
=> feat(metrics): add view Glean event for TOTP form

.github/workflows/l10n-gettext-extract.yml
Because:
* Our string extraction CI job is failing when changes are found and fxa-l10n has not been requested for review yet
This commit:
* Captures grep exit code to compare against directly, as grep -q "fxa-l10n" was failing and breaking out of the command pipeline with exit code 1
---
A [different fix](https://github.com/mozilla/fxa/pull/15532) was made previously, as it appeared to least at least fix the job in [this case](https://github.com/mozilla/fxa/pull/15472). Looks like that worked for when fxa-l10n was already added, but I didn't realize I'd neglected to test the case where l10n hadn't been requested yet.
I hit that case in #15561 - this change is in that branch at the time of writing to show its success, [see CI job](https://github.com/mozilla/fxa/actions/runs/5627381616/job/1 …
=> fix(ci): Capture grep -q exit code 1 to fix string extraction job

packages/fxa-content-server/app/scripts/lib/fxa-client.js, packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/templates/post_verify/third_party_auth/set_password.mustache, packages/fxa-content-server/app/scripts/views/mixins/third-party-auth-mixin.js, packages/fxa-content-server/app/scripts/views/post_verify/third_party_auth/set_password.js, packages/fxa-content-server/app/tests/spec/views/post_verify/third_party_auth/set_password.js, packages/fxa-content-server/app/tests/test_start.js, packages/fxa-content-server/server/lib/routes/react-app/content-server-routes.js
- Sync requires a password to encrypt a user's data, third party accounts don't have this set
- Prompts the user to set a password after logging in via a third party and into Sync
- After setting password they are logged into Sync
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8033
To test, login via `http://localhost:8080` using "Sign-in (Google)" link. After logging in, log into Sync via hamburger menu. You should be prompted to set a password after completing the Google auth flow.
=> feat(password): Add ability to set password after third party login to Sync

packages/fxa-settings/src/components/Settings/FlowRecoveryKeyConfirmPwd/index.tsx
* In the new account recovery key creation flow, the confirm password CTA would remain disabled after an incorrect password was entered and the user retypes in the input, making it impossible to correct the password and retry
* Enable the button when the password confirmation fails and an error message is displayed
Closes: #FXA-8092
=> fix(fxa-settings): Resolve recovery key confirm pwd button disabled

packages/fxa-settings/src/lib/reliers/relier-factory.test.ts, packages/fxa-settings/src/models/integrations/oauth-redirect-integration.ts, packages/fxa-settings/src/models/reliers/base-relier.test.ts, packages/fxa-settings/src/models/reliers/base-relier.ts, packages/fxa-settings/src/models/reliers/oauth-relier.test.ts, packages/fxa-settings/src/models/reliers/oauth-relier.ts, packages/fxa-settings/src/pages/ResetPassword/ResetPasswordConfirmed/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/index.test.tsx, packages/fxa-shared/test/oauth/scopes.js
- Password reset flow could fail due to an invalid scope being sent to the auth server's /authorization endpoint
- Applies minimal string processing to ensure the scope string is valid.
Closes: FXA-8087, FXA-8090
As of writing, the issue was simply an erroneous '+' character in the scope value.
valid scope: `profile https://identity.mozilla.com/account/subscriptions`
invalid scope: `profile+https://identity.mozilla.com/account/subscriptions`
However, there were a bunch of 'normalization' operations on the scope query param that existed in content server, but were never ported to settings server. This commit should take care of this. In effort not disrupt state normilzation will take place functionally by calling relier.getNormalizedScope().
=> bug(settings): Fix issue with 'scope' string format

packages/functional-tests/pages/login.ts, packages/functional-tests/tests/thirdPartyAuth/thirdPartyAuth.spec.ts, packages/fxa-content-server/app/scripts/views/mixins/third-party-auth-mixin.js, packages/fxa-content-server/app/tests/spec/views/mixins/third-party-auth-mixin.js
- The `/linked_account/login` route could be called multiple times and create a duplicate record error in the database
- Adds a check to call the completeSignin function on the correct view
- Adds a basic functional test for Google sign-in
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7959
=> fix(bug): Fix race condition in third party auth sign-in

packages/functional-tests/pages/login.ts, packages/functional-tests/tests/misc/cookiesDisabled.spec.ts, packages/functional-tests/tests/misc/forceAuth.spec.ts, packages/functional-tests/tests/oauth/oauthPermissions.spec.ts, packages/functional-tests/tests/oauth/oauthPromptNone.spec.ts, packages/functional-tests/tests/oauth/signUp.spec.ts, packages/functional-tests/tests/postVerify/accountRecovery.spec.ts, packages/functional-tests/tests/postVerify/forcePasswordChange.spec.ts, packages/functional-tests/tests/settings/recoveryKey.spec.ts, packages/functional-tests/tests/settings/totp.spec.ts, packages/functional-tests/tests/signUp/signUp.spec.ts, packages/functional-tests/tests/signUp/signUpWithCode.spec.ts, packages/functional-tests/tests/signin/signIn.spec.ts, packages/functional-tests/tests/signin/signinBlocked.spec.ts, packages/functional-tests/tests/signin/signinCached.spec.ts, packages/functional-tests/tests/subscription-tests/support.spec.ts, packages/functional-tests/tests/syncV3/fxDesktopHandshake.spec.ts, packages/functional-tests/tests/syncV3/settings.spec.ts, packages/functional-tests/tests/syncV3/signUp.spec.ts, packages/functional-tests/tests/syncV3/signinCached.spec.ts, packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts
- isVisible() doesn't have the default timeout set and becomes flaky when the selector/page takes a few more secs to resolve. hence replacing it with waitForSelector() as it has default timeout set and works more efficiently. 
- changed the name for `loginHeader()` to `isUserLoggedIn()`
replaces isVisible() with waitForSelector() wherever seems necessary.
Closes: FXA-7793
=> fix(test): replace isVisible() check with waitForSelector()

packages/fxa-content-server/server/lib/beta-settings.js, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-react/components/FeatureFlag/index.test.tsx, packages/fxa-react/components/FeatureFlag/index.tsx, packages/fxa-settings/src/components/OAuthClientFeatureFlag/index.test.tsx, packages/fxa-settings/src/components/OAuthClientFeatureFlag/index.tsx, packages/fxa-settings/src/lib/config.ts
- We want to feature flag certain features for certain oauth clients
- We want to be able to wrap this component around a view to feature flag it
- Adds config `oauth.reactClientIdsEnabled` to flag oauth client that
- Adds oauth client feature flag component to settings, which uses the config setting above and a 'wrapper' pattern.
- Adds a general feature flag wrapper component to fxa-react.
Closes: FXA-7126
=> task(settings,react): Add feature flag component that supports list of oauth client ids

.circleci/config.yml, package.json, packages/fxa-payments-server/src/components/AppLayout/index.test.tsx, packages/fxa-payments-server/src/lib/test-utils.tsx, packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.test.tsx, packages/fxa-react/lib/AppLocalizationProvider.test.tsx, packages/fxa-react/lib/AppLocalizationProvider.tsx, packages/fxa-react/lib/test-utils/index.test.tsx, packages/fxa-react/lib/test-utils/localizationProvider.tsx, packages/fxa-settings/src/components/Settings/index.test.tsx, packages/fxa-settings/src/setupTests.tsx, yarn.lock
- Fluent warning messages are slowing down tests.
- Updates to the latest @fluent/react version
- Adds a non-console.warn reportError to testing ReactLocalization instantiations.
Closes: # FXA-7958
=> feat(shared): hide fluent warning msgs in tests

packages/fxa-graphql-api/src/decorators.ts
- The graphql server sends requests to the auth server with the `Host: graphql` header from the client. In AWS this was harmless because each service was using it's own load balancer. In GCP this caused issues with host-based routing, and required us to create a separate load balancer for the auth server.
- Only sets the `X-Forwarded-For` header
Slack thread: https://mozilla.slack.com/archives/CLV3KMZ8B/p1690296747250679
=> fix(graphql): Only send the X-Forwarded-For header to the auth server

packages/fxa-payments-server/src/components/PayPalButton/index.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.tsx, packages/fxa-payments-server/src/lib/account.test.ts, packages/fxa-payments-server/src/lib/account.ts, packages/fxa-payments-server/src/lib/mock-data.tsx, packages/fxa-payments-server/src/lib/reactga-event.ts, packages/fxa-payments-server/src/lib/reactga-events.test.ts, packages/fxa-payments-server/src/lib/stripe.test.ts, packages/fxa-payments-server/src/lib/stripe.ts, packages/fxa-payments-server/src/routes/Checkout/index.test.tsx, packages/fxa-payments-server/src/routes/Checkout/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx, packages/fxa-payments-server/src/routes/Product/index.tsx
- there is a request to add GA to SubPlat checkout page
- Adds react-ga4 to the following events:
- To open a follow-up ticket in order to resolve bugs (though they potentially are on GA's end):
- [1] `discount` in `items` array appears in GA Debugger Console, but not in DebugView; `discount` appears in DebugView if it is moved outside of `items`
- [3] `items` array is missing in custom `purchase_submit` event
- [`price` is multiplied by one million in GA](https://github.com/firebase/firebase-ios-sdk/issues/8280)
Closes: [FXA-7671](https://mozilla-hub.atlassian.net/browse/FXA-7671)
To test, update `googleAnalytics` -> `enabled`: `true` and `measurementId`, in the following files:
- `fxa-payments-server/server/config/index.js`
- …
=> feat(payments): Add react-ga4 payments events

packages/functional-tests/pages/login.ts, packages/functional-tests/tests/signin/signinCached.spec.ts
- signinCached test was failing locally but not on CI
- Added the `newPagesForSync`
Closes: FXA-8080
=> fix(test): fix failing local test

packages/fxa-react/configs/tailwind.js, packages/fxa-settings/src/components/DataBlock/index.tsx, packages/fxa-settings/src/components/FormPasswordWithBalloons/index.tsx, packages/fxa-settings/src/components/FormVerifyCode/index.tsx, packages/fxa-settings/src/components/GetDataTrio/index.stories.tsx, packages/fxa-settings/src/components/GetDataTrio/index.test.tsx, packages/fxa-settings/src/components/GetDataTrio/index.tsx, packages/fxa-settings/src/components/InputPassword/index.stories.tsx, packages/fxa-settings/src/components/InputPassword/index.tsx, packages/fxa-settings/src/components/InputText/index.tsx, packages/fxa-settings/src/components/Tooltip/index.stories.tsx, packages/fxa-settings/src/components/Tooltip/index.tsx, packages/fxa-settings/src/pages/InlineRecoverySetup/index.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx, packages/fxa-settings/src/pages/ResetPassword/index.tsx, packages/fxa-settings/src/pages/Signin/index.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
* No feedback was displayed in the new account recovery key flow when the key was copied to the clipboard.
* The tooltips on other GetDataTrio buttons were never dismissed.
* Display a tooltip when the key is copied to the clipboard, and hide on blur.
* Update the Tooltip component to allow anchor end in addition to anchor middle and anchor start
* Does not change the focus behaviour of the copy button - it is intentional that the focus outline stay visible while keyboard focus is on the button. Focus is removed on blur.
Closes: #FXA-7541, FXA-7544
After:
https://github.com/mozilla/fxa/assets/22231637/ba1f64a3-227b-4479-b5f4-70b651db99d5
=> fix(bug): Display tooltip when DataTrio buttons are clicked

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/scripts/paypal-processor.ts, packages/fxa-auth-server/tsconfig.json
- fix(scripts): Chain original error from redlock
- fix(stripe): Skip over open invoices without subscriptions
- The stage paypal processor is failing on every run
- Adds more details error messages and fixes the one error we know about
Slack convo: https://mozilla.slack.com/archives/CLV3KMZ8B/p1690414747187909
=> paypal processor fixes

packages/fxa-auth-client/tsconfig.cjs.json
Because:
* Some packages can't locate fxa-auth-client
This commit:
* Adds 'declaration: true' to compilerOptions tsconfig.cjs.json
=> fix(auth-client): Add 'declaration: true' compile option

libs/payments/paypal/src/index.ts, libs/payments/paypal/src/lib/client.spec.ts, libs/payments/paypal/src/lib/client.ts, libs/payments/paypal/src/lib/error.spec.ts, libs/payments/paypal/src/lib/error.ts, libs/shared/error/README.md, libs/shared/error/src/index.ts, libs/shared/error/src/lib/error.spec.ts, libs/shared/error/src/lib/error.ts, packages/fxa-auth-server/lib/payments/paypal/helper.ts, packages/fxa-auth-server/lib/payments/paypal/processor.ts, packages/fxa-auth-server/test/local/payments/paypal-processor.js, packages/fxa-auth-server/test/local/payments/paypal.js
Because:
* We had some last minute tweaks to the error arrangement.
This commit:
* Moves the error class to the library using it and inherits from a shared base error.
=> feat: polsih error refactor

libs/payments/paypal/project.json, libs/shared/error/project.json
Because:
* The build was failing due to missing rootDir in the project.json files.
This commit:
* Adds the missing rootDir to the project.json files.
=> fix: add remaining rootDir for build to complete

packages/fxa-graphql-api/src/config.ts
Because:
* We will be using the Contentful hCMS (specifically their GraphQL Content API) to replace Stripe metadata for RP-provided content in SubPlat 3.0.
This commit:
* Adds the Contentful API key environment variable to the fxa-graphql-api service's config file.
Closes #FXA-7623
See this [summary](https://mozilla-hub.atlassian.net/browse/FXA-7623?focusedCommentId=715234) from a [team discussion yesterday](https://docs.google.com/document/d/1npPLTiWE3pjeq0sxQehOtgyOcbFgbectFyS2rSbwR1A/edit#bookmark=id.dduhnnqc8sgw) regarding which Contentful APIs we're using in which environments.
=> chore(graphql): add Contentful API key env var

packages/fxa-auth-server/scripts/test-local.sh
- Auth server tests run locally are failing with "Cannot find module" error.
- Add tsconfig-paths to arguments used by mocha tests.
Closes: #
=> fix(auth): fix path resolution for local tests

packages/fxa-settings/src/components/ThirdPartyAuth/index.stories.tsx, packages/fxa-settings/src/components/ThirdPartyAuth/index.test.tsx, packages/fxa-settings/src/components/ThirdPartyAuth/index.tsx, packages/fxa-settings/src/components/ThirdPartyAuth/mocks.tsx
- We wanted the code in the third party auth to use react conventions
- Creates a third party sign in form that is rendered.
- Submits this form when click 'continueWith' buttons.
Closes: FXA-7319
This component is not accessible via manual testing, because the routes for this have not yet been enabled, but it ca be manually tested in storybook.
=> task(settings): Use form component in ThirdpartyAuth component

_dev/docker/ci/Dockerfile
- Deploy ci image was failing
- Adds a missing ';'
Noticed while poking around circleci pipelines.
=> bug(ci): Broken ci image build

packages/fxa-content-server/app/scripts/lib/glean/event.js, packages/fxa-content-server/app/scripts/lib/glean/index.ts, packages/fxa-content-server/app/scripts/lib/glean/utm.js, packages/fxa-content-server/app/scripts/views/sign_in_password.js, packages/fxa-content-server/app/tests/spec/lib/glean.js, packages/fxa-content-server/app/tests/spec/views/sign_in_password.js
chore(metrics): add Glean ping for login submit error
Because:
- we want know when a user failed to log into their account and why
This commit:
- adds a labeled strings metric for event properties
- adds a function for the failed login event
=> chore(metrics): add Glean ping for login submit error

packages/fxa-payments-server/src/routes/Checkout/index.test.tsx, packages/fxa-payments-server/src/routes/Checkout/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx
Because:
* We are seeing fewer "engage" events relative to "submit", even though "engage" occurs upstream in the conversion funnel.
* We were not recording an "engage" event for clicking the consent checkbox.
* This is the only form field present in all scenarios and checkout flows on the payments server, so it likely makes up the majority of the missed events across all flows.
This commit:
* Records the "fxa_pay_setup - engage" event when clicking the consent checkbox.
Closes #FXA-7941
=> fix(payments): record checkout "engage" event for consent checkbox

packages/fxa-content-server/server/config/local.json-dist, packages/fxa-settings/src/components/App/index.tsx
Because:
* We've rolled out React reset PW routes and are working on signup and signin and don't wish to reset the config after every yarn install
This commit:
* Turns resetPasswordRoutes, signUpRoutes, and signInRoutes 'on' for local dev
* Removes stray console log
--
No idea why #15673 keeps failing to start playwright tests but #15683 is passing with same changes (... just noticed Ankita's doesn't have a trailing comma though? Is that it? 😅) so just opening another PR for it.
=> chore(react): Update local.json-dist for React routes, remove console log

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/payments/stripe-formatter.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/en.ftl, packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.mjml, packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.stories.ts, packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.txt, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/senders/emails.ts, packages/fxa-payments-server/server/config/index.js, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/en.ftl, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.stories.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx, packages/fxa-shared/payments/stripe.ts
- Enhanced Subscription Upgrade Experience is complete
- Removes the Stripe invoice immediately feature flag and all references and conditions in both auth and payments servers
Closes: [FXA-7796](https://mozilla-hub.atlassian.net/browse/FXA-7796)
[FXA-7796]: https://mozilla-hub.atlassian.net/browse/FXA-7796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(auth&payments): Remove feature flag

packages/fxa-settings/src/models/integrations/client-info.ts, packages/fxa-settings/src/models/integrations/oauth-integration.ts, packages/fxa-settings/src/models/integrations/signin-signup-info.ts, packages/fxa-settings/src/models/integrations/web-integration.ts
Because:
* Some validation checks are incorrect since params are always strings unless transformed, causing a blank page to show in some cases
This commit:
* Uses the 'isBooleanString' decorator instead of 'isBoolean' until we can better validate with (probably) a custom decorator
---
There are a couple of things this fixes:
* When the email param is not valid in a reset PW link, we were showing a blank page instead of the expired link. This tweak is needed for my signup PR as well
* In at least one OAuth flow (Monitor staging), the page is also blank, because `max_age` comes through as `'0'` and we were checking for a positive number
I went ahead and adjusted other 'boolean' checks to `IsBooleanString` since I tested them and they were causing errors. We should get a follow up filed to …
=> fix(react): class-validator decorator tweaks around query params

packages/fxa-auth-server/package.json, yarn.lock
- auth-server was failing to start after deploy due to tsconfig paths not resolving to the relevant libraries.
- Adds a tsc-alias to build step to resolve alias paths to relative paths.
Closes: # 
We ran into an issue when trying to startup the auth-server in stage. When starting up the server with run command, `node bin/key_server.js`, node didn't know what to do with the path aliases, for example `const { PayPalClient } = require('@fxa/payments/paypal');`
`tsc` does not resolve these path aliases to relative paths automatically. [Here is a discussion](https://github.com/microsoft/TypeScript/issues/10866) from a while back, where they go into a bit more detail. Maybe there's something more current?
One of the suggested approaches to resolve this …
=> fix(auth): could not resolve ts paths on startup

README.md
#15195 removed a section but a previous link to this section remained. This is a minor fix for this.
=> Follow-up of #15195 / dead link in readme

packages/fxa-auth-server/docs/swagger/oauth-api.ts
Because:
* We need either an auth header or a client_id
This commit:
* Adds a note to the docs
=> chore(docs): clarify API request requirement

packages/functional-tests/tests/react-conversion/resetPassword.spec.ts, packages/fxa-graphql-api/src/decorators.spec.ts, packages/fxa-graphql-api/src/decorators.ts
- Service name was blank for connected device after going through password reset flow
- Makes sure user agent propagates from graphql to auth-server
- Adds tests for our gql decorator class
- Adds logic to functional test to ensure the service name isn't blank
Closes: FXA-8123
=> bug(settings): Fix missing connected service name after password reset

packages/fxa-admin-panel/src/components/PageAccountSearch/Account/index.test.tsx, packages/fxa-admin-panel/src/components/PageAccountSearch/Account/index.tsx, packages/fxa-admin-panel/src/components/PageAccountSearch/index.gql.ts, packages/fxa-admin-panel/src/components/PageAccountSearch/index.test.tsx, packages/fxa-admin-panel/src/index.tsx, packages/fxa-admin-server/README.md, packages/fxa-admin-server/nest-cli.json, packages/fxa-admin-server/src/gql/account/account.resolver.spec.ts, packages/fxa-admin-server/src/gql/account/account.resolver.ts, packages/fxa-admin-server/src/gql/model/account.model.ts, packages/fxa-admin-server/src/graphql.ts, packages/fxa-admin-server/src/schema.gql
- We need to know if an accounts password was set
- Adds a row for Password Set
- Exposes the verifierSetAt field to the front end
- Uses verifierSetAt to determine if a password was set
- Fixes bug where dev mode wasn't starting due wrong path
- Fixes bug where StrictMode was stopping lazy queries from executing
Closes: FXA-8148
=> task(admin): Show if password is set on account

packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-settings/src/lib/gql.test.ts, packages/fxa-settings/src/lib/gql.ts
- Users could not access settings after pairing a device
- This issue was introduced in https://github.com/mozilla/fxa/pull/15362
- Revert the PR
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8214
I couldn't revert via github since the files have changed, had to manually revert.
=> revert(bug): Revert settings redirect in graphql to fix ios pairing bug

packages/fxa-content-server/app/scripts/lib/glean/index.ts, packages/fxa-content-server/app/tests/spec/lib/glean.js
Because:
- hashing the uid is async (`crypto.subtle.digest`), thus making the Glean ping calls async.  And preferably we don't block the UI on metrics.  However, we cannot overlap (not await) multiple Glean pings.  When that happened with the successful registration submission event overlapping the registration confirmation view event, we "lost" all the succession registration event because that event has an empty event name.  And the confirmation view event was submitted with the properties of the successful registration submission event.
This commit:
- calls and awaits the ping submissions in order inside GleanMetrics
=> fix(metrics): await Glean submissions

libs/payments/paypal/src/lib/client.config.ts, libs/payments/paypal/src/lib/client.ts, libs/payments/paypal/src/lib/types.ts, package.json, yarn.lock
Because:
* The paypal client config is a basic interface, and we'd like to be
able to use Nest-Typed-Config with a structured config file.
This commit:
* Adds a typed config class for the paypal client.
=> refactor: use typed config for paypal client

packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.stories.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/interfaces.ts, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/mocks.tsx
Because:
* We were only rendering the default service name
This commit:
* Sets the service name from the integration
* Sets up mock integration functions for that page and creates interfaces file for that page
closes FXA-8141
---
I'm on PTO early next week so this will need to be merged for me 🙏
=> fix(react): Grab service name from integration in AccountRecoveryConfirmKey

packages/fxa-auth-server/lib/metrics/glean/index.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/test/local/metrics/glean.ts, packages/fxa-auth-server/test/local/routes/account.js
It adds a backend Glean ping for account creation.
=> feat(metrics): add backend Glean ping for reg_acc_created

packages/functional-tests/tests/subscription-tests/subscription.spec.ts
- The funnel metrics subplat tests have been failing on Stage and a bug has been created to fix it. https://mozilla-hub.atlassian.net/browse/FXA-8078. Disabling the test so that the Stage smoke test passes.
- Disables the funnel metrics test
Closes: FXA-8201
=> test(subplat): disable the funnel metrics test

libs/shared/contentful/src/lib/contentful-client.config.ts, libs/shared/contentful/src/lib/contentful-client.spec.ts, libs/shared/contentful/src/lib/contentful-client.ts
Because:
* We'd like to be able to use Nest-Typed-Config with a structured config file that can be validated at runtime if desired.
This commit:
* Adds a typed config class for the Contentful client.
* Reference PR: https://github.com/mozilla/fxa/pull/15724
Closes #No ticket
=> refactor: use typed config for Contentful client

.circleci/config.yml
- We were running out of memory in CI
- Has integration tests use the large resource class
- Fixes 'projects' param on integration-test jobs
We should investigate why memory is spiking happening. This is a temporary fix.
=> task(ci): Make integration tests run on large resource class

_dev/docker/mono/Dockerfile
- Docker build in was failing when trying to install netcat
- Changes the install to `netcat-traditional`, because `netcat` isn't a valid package name anymore.
This was encountered during release of train-266. The regression was introduced when we updated our base image to use `node:18.17-slim`.
=> task(ci): Fix netcat install after updating docker base image to node:18.17-slim

_dev/docker/mono/build.sh
- The CI job `Create FxA Image` ran out of memory
- Applies the the `--max-old-space-size=7168` node option, which should prevent the OOM.
The root cause of this regression was like the node version upgrade.
=> task(ci): Include max-old-space-size node option in build.sh

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/third-party-auth.js
- We want product and UX go through the flows in stage before we enable it for all
- Enables the feature
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6726
=> chore(auth): Enable third party auth

.circleci/config.yml
- In train-266 stage smoke tests failed
- The auth client build was missing
- The auth client build used to be part of the docker image, but this changed now that we cache builds in nx.
- Builds auth client with nx prior to running smoke tests.
=> bug(ci): Fix broken stage/prod smoke tests

nx.json
- The daemon was crashing due to a file change on a .gitignore file in a sub repo
- This is a edge case in the nx code
- Configures nx to only watch and cache the improtant files in {workspaceRoot}/External
The edge case that trips this error can be seen here: https://github.com/nrwl/nx/blob/6d686564faf83f29ecc6129a0ed7ee8b29983e28/packages/nx/src/daemon/server/watcher.ts#L85C23-L85C23
=> bug(nx): Fix crashing nx daemon

packages/fxa-admin-panel/package.json
- The build-ts-server output wasn't getting deleted
- Changes the order of operations in the admin-panel build script
- Running build-ts-server at the end ensures the build output is left intact
Fix for:
=> bug(admin-panel): Fix missing server build ouptut

_scripts/check-url.sh
Because:
* Mac M1 and M2 machines are slower to start up infrastructure like Redis and Firestore (which runs under emulation).
This commit:
* Doubles the RETRY period from 120 to 240s as most of the time, the `__heartbeat__` (or similar) response for fxa-auth-server (port 9000) and firestore processes (port 9299 among others) responded between 140 - 190s.
[skip ci]
Closes #No ticket
It'd be nice to specifically wait for any and all dependencies that these processes have to start up, and we should consider that if this becomes a larger issue for more engineers. Right now, only Valerie and I are hitting this AFAIK.
=> chore(scripts): increase check-url.sh RETRY value

packages/fxa-auth-server/lib/error.js, packages/fxa-auth-server/lib/metrics/glean/index.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/test/local/error.js, packages/fxa-auth-server/test/local/metrics/glean.ts, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
Because:
- we want to know when a login attempt failed
This commit:
- sends a Glean ping with a reason for the login failure
=> feat(metrics): send Glean ping on login error

_dev/docker/mono/Dockerfile
a workaround for https://github.com/nodejs/node/issues/43064
=> Use bullseye as base image (instead of bookworm the current default)

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/new-recovery-key-UI.js
- We want to increase the rollout of the new account recovery key flow from 15% to 100%
- Increase rollout rate of experiment
Closes: # FXA-8237
=> task(settings): Roll out new account recovery key flow to 100% of users

packages/functional-tests/pages/login.ts, packages/functional-tests/pages/resetPassword.ts, packages/functional-tests/tests/misc/forceAuth.spec.ts, packages/functional-tests/tests/oauth/forceAuth.spec.ts, packages/functional-tests/tests/reset-password/resetPassword.spec.ts, packages/functional-tests/tests/settings/password.spec.ts, packages/functional-tests/tests/settings/recoveryKey.spec.ts, packages/functional-tests/tests/syncV3/syncV3ResetPassword.spec.ts, packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/app/tests/spec/lib/router.js, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx
Because:
* We want to increase React reset PW rollout from 15% to 100%
This commit:
* Adds 'resetPasswordRoutes' to the "always shown react routes" array
* Updates functional tests
* Modifies router.js to ensure query params are passed to complete reset PW link
closes FXA-8112
=> task(react): Turn reset PW routes to 100% rollout

packages/fxa-auth-server/lib/email/bounces.js, packages/fxa-auth-server/test/local/email/bounce.js
=> fix(logging): Rename field status to mailStatus to fix BigQuery export errors

packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/metrics/glean/index.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/lib/server.js, packages/fxa-auth-server/test/local/metrics/glean.ts, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/local/server.js
This commit moves the Glean ping call out of the route handler and into hapi's `preResponse`.
=> feat(metrics): add backend registration failure Glean ping

packages/fxa-auth-server/docs/swagger/shared/descriptions.ts, packages/fxa-auth-server/lib/routes/linked-accounts.ts
- Swagger docs for third party routes was missing some bits
- Updates the response on third party auth routes so swagger picks them up
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8167
-
Updated [ecosystem](https://github.com/mozilla/ecosystem-platform/commit/95f8b7ed609eb52e4b98e02348e800400948b77f) docs as well.
=> chore(docs): Updated third party swagger docs

packages/fxa-content-server/app/scripts/templates/partial/third-party-auth.mustache, packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache, packages/fxa-content-server/app/scripts/views/index.js, packages/fxa-content-server/app/scripts/views/sign_in_password.js, packages/fxa-content-server/app/tests/spec/views/sign_in_password.js
- We didn't always surface that a user could use third party auth login options (specifically when they have a password set)
- Updates the code so that third party auth is shown for almost all cases. The exception is for Sync (unless they already have a linked account)
Closes:  https://mozilla-hub.atlassian.net/browse/FXA-8233
See https://mozilla-hub.atlassian.net/browse/FXA-8233 for screenshots
=> fix(auth): Always show third party auth options except for certain Sync cases

packages/functional-tests/lib/targets/base.ts, packages/functional-tests/lib/targets/local.ts, packages/functional-tests/lib/targets/stage.ts, packages/functional-tests/pages/relier.ts, packages/functional-tests/tests/subscription-tests/subscription.spec.ts
- it is returning the URL before query params have been added
- waits for the selector to have the query params before returning the URL
Closes: [FXA-8078](https://mozilla-hub.atlassian.net/browse/FXA-8078)
[FXA-8078]: https://mozilla-hub.atlassian.net/browse/FXA-8078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(functional-tests): Subscription funnel metrics tests are failing on stage

packages/fxa-settings/package.json, packages/fxa-settings/src/components/ButtonDownloadRecoveryKeyPDF/RecoveryKeyPDF.tsx, packages/fxa-settings/src/components/ButtonDownloadRecoveryKeyPDF/requiredFont.tsx
- On iOS, account recovery key PDF text in Hebrew was rendered as rectangles instead of appropriate Hebrew fonts
- Long blocks of text in languages that don't use spaces between words (e.g., Chinese) were overflowing the PDF page instead of breaking to the next line.
- Add he-IL variant to PDF generation font selector
- Modify hyphenation rules to prevent page overflow for languages such as Chinese.
Closes: #FXA-8195
Before - Hebrew PDF on iOS with broken encoding
After - Hebrew PDF on iOS with correct encoding
Before - Chinese overflowing page:
After - Chinese with line return:
To test Hebrew on iOS:
1. Open the staged storybook for the PDF download button on iOS:
https://storage.googleapis.com/mozilla-storybooks-fxa/commits/43f4ac8d60a9451ba94730446f3 …
=> fix(fxa-setting): Add he-il lang variant for PDF generation

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/third-party-auth.js, packages/fxa-content-server/app/scripts/templates/index.mustache, packages/fxa-content-server/app/styles/modules/_custom-rows.scss
- We want to show the legal snippet on the email first page
- Adds the snippet
- Updates the spacing on the third party auth buttons to match ux specs
- Enables third party auth experiment to 100%
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8298
=> feat(legal): Add legal snippet to email first when third party option shown

packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-server/lib/routes/linked-accounts.ts, packages/fxa-auth-server/test/local/routes/linked-accounts.js, packages/fxa-content-server/app/scripts/lib/fxa-client.js, packages/fxa-content-server/app/scripts/views/post_verify/third_party_auth/set_password.js
- The service param was not being populated in our dashboards
- Sends the service value into the route directly
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8003
Here are the metrics logs for different flows
```
37|content  | INFO fxa-content-server.amplitudeEvent: {"op":"amplitudeEvent","event_type":"fxa_third_party_auth - view","time":1694713313434,"device_id":"b6d6300cbe65413dac97a7ac15bc8a56","session_id":1694713292657,"app_version":"0.0","language":"en-US","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"123done","oauth_client_id":"dcdb5ae7add825d2"},"user_properties":{"flow_id":"604ddf6ead726b47fdf3bfea5e5c53677efb5796e2d17b2d97290f68057b4766","ua_browser":"Firefox","ua_version":"109.0","$append":{"fxa_services_used":"123done"}}}
37|content  | INFO …
```
=> fix(metrics): Send service value when using the linked account login route

packages/fxa-content-server/app/scripts/templates/partial/brand-messaging.mustache, packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache, packages/fxa-content-server/app/scripts/views/mixins/brand-messaging-mixin.js, packages/fxa-content-server/app/styles/modules/_branding.scss, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-settings/Gruntfile.js, packages/fxa-settings/src/components/BrandMessaging/en.ftl, packages/fxa-settings/src/components/BrandMessaging/index.tsx, packages/fxa-settings/src/styles/brand-banner.css
- A couple defects were noticed.
- The X icon was always on the left side.
- role="Link" was missing in one spot, so screen readers wouldn't work for Learn more link.
- The link could not be tabbed to.
- In mobile view some pages would overlap the messaging
- In mobile view the 'X' icon would over overlap the text on some devices
- Noticed an existing issue with signup text due to line break in {{\t}} wrapper
- Branding ftl strings in [fxa-shared](https://mozilla-hub.atlassian.net/browse/FXA-shared) not coming through
- Mozilla hard coded in alt text
- Adds `rtl:` and `ltr:` prefix to ensure x is on the right side
- switched to using flex to ensure X icon doesn't overlap
- some tricks to ensure banner is fixed and sticky when render at top, and appended / inline rendered at bottom of page …
=> bug(settings,content): Follow up for in brand messaging

packages/fxa-settings/Gruntfile.js
* Merging the branding.ftl and react.ftl files into the settings.ftl file (to allow new brand terms to be visible in local development) was resulting in string duplication during l10n extract
* Reverts the changes to fxa-settings gruntfile
* Adds a copy step to the grunt file to make the branding file available for local development without duplicating strings for extraction (only the `settings.ftl` file will be extracted from the settings package)
After running `nx start fxa-settings` on this branch, the new Mozilla account brand terms are added to branding.ftl AND main.ftl in `fxa-settings/public/locales/en` but are no longer included in the settings.ftl file:
=> Revert grunt change

packages/db-migrations/contentful/1694798435403_fxa-8294.js
- we should only be able to add an existing Offering or create a new Offering in a Subgroup
Closes: [FXA-8294](https://mozilla-hub.atlassian.net/browse/FXA-8294)
[FXA-8294]: https://mozilla-hub.atlassian.net/browse/FXA-8294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(contentful): Update Contentful schema of the Subgroup model

packages/fxa-auth-server/lib/payments/capability.ts
* There were some TypeScript issues in configuredSubscribedMergedConfigs.
* This fixes the reference that was causing the TypeScript issue.
Polish PR.
=> chore(auth): polish configuredSubscribedMergedConfigs

apps/payments/next/app/%5F_heartbeat__/route.ts, apps/payments/next/app/%5F_lbheartbeat__/route.ts, package.json, yarn.lock
Because:
* We want to use the newer Next.js.
* We want to use proper Next.js JSON return handling.
This commit:
* Updates to Next.js 13.5.1.
* Updates the heartbeat routes to use the new JSON return handling.
=> chore: update next to 13.5 and polish heartbeat return

packages/functional-tests/tests/react-conversion/oauthResetPassword.spec.ts
- The react oauth reset password tests are failing in Stage and Prod and a tickest has been filed for it FXA-8192. Hence disabling it until it's fixed.
- Disables react oauth reset password tests in Stage and Prod
Closes: #
=> test(functional): disbaling react oauth test in Stage and Prod

libs/shared/contentful/src/__generated__/graphql.ts, packages/db-migrations/contentful/1695221177448_fxa-8229.js
- currently we can only select one country in which coupons could be applied
- provides the ability to select multiple countries in which coupons could be applied
=> fix(contentful) - Update CouponConfig schema in Contentful

packages/fxa-auth-server/lib/metrics/amplitude.js, packages/fxa-content-server/server/lib/amplitude.js, packages/fxa-payments-server/server/lib/amplitude.js, packages/fxa-shared/metrics/amplitude.ts, packages/fxa-shared/test/metrics/amplitude.js
- Content server was restarting due to unknown event group
- Wraps the mapping function with try catch to ensure it cannot result in an unhandled error
- Adds optional statsd and logger parameters so that we can track potential problems outside of sentry.
- Updates initialization to provide statsd and logger parameters to amplitude's initialization routine.
Closes: FXA-7683
It appears the code that currently calls this mapper function always checks to see if the event returned is empty and will log an amplitude dropped event if it is. Therefore the try catch isn't especially risky since we monitor these dropped events. Adding the optional internal logging and metrics is just icing on the cake to future proof it and help us pinpoint the issue in the …
=> bug(shared): Amplitude crashes on startup with unhandled error

packages/fxa-react/components/Head/en.ftl, packages/fxa-react/components/LogoLockup/en.ftl
Because:
* We want l10n strings that are changing from Firefox to Mozilla to be localized before launch
This commit:
* Creates new copies of FTL strings that contain Firefox branding references and replaces them with Mozilla branding
closes FXA-7990
---
[Quick reference](https://github.com/mozilla/fxa-content-server-l10n/blob/8331141fc538706639657f21097ddbfed61c5665/locale/templates/react.ftl) to help with review.
@bcolsson I feel like we're going to have some duplicate strings while doing this, even now our `app-logo-alt-2` here duplicates `app-footer-mozilla-logo-label`. Maybe we need an issue filed towards the end to combine some IDs where we can which would be nice on our end, but would this be not nice on the l10n side? I know translations can change based on context.
=> refactor(fxa-react): L10n updates for Mozilla accounts branding

packages/functional-tests/tests/oauth/oauthPermissions.spec.ts, packages/functional-tests/tests/oauth/oauthPromptNone.spec.ts
- The oauth permission test were failing in Prod because the pre-verification flow doesn't work in prod
- The oauth prompt none tests were failing in Prod because there is no test plan setup in prod yet.
- Fixes the pre-verification flow by using `credentials` id and password in Prod
- Skips the prompt none test until test plans are setup in prod
Closes: #FXA-8279 FXA-8280
=> fix(functional): fix oauth permission tests in prod for the pre verificaton

packages/fxa-content-server/app/scripts/views/authorization.js, packages/fxa-content-server/app/tests/spec/views/authorization.js
- In upcoming Safari Sonoma, FxA OAuth query params would be stripped from the url. This would cause FxA to default to sending the user to settings page and not complete the OAuth flow
- This doesn't happen to all RPs, for example https://production-123done.herokuapp.com/ fails but https://stage-123done.herokuapp.com/ works properly
- Skips using the `replaceCurrentPage` Backbone navigate function and uses `window.location.href` directly
- Doing this also skips a few query validation and checks we perform
I can't say for certain if this works but it should hopefully narrow down the issue. Getting Safari to load FxA locally is a pain since it forces urls to https.
Note, I would like to try this on stage since we can reproduce the issue with certain RPs.
=> fix(osx): Fix an issue in Sonoma where oauth query params were being stripped

libs/payments/capability/README.md, libs/payments/eligibility/.eslintrc.json, libs/payments/eligibility/README.md, libs/payments/eligibility/jest.config.ts, libs/payments/eligibility/package.json, libs/payments/eligibility/project.json, libs/payments/eligibility/src/index.ts, libs/payments/eligibility/src/lib/eligibility.manager.ts, libs/payments/eligibility/tsconfig.json, libs/payments/eligibility/tsconfig.lib.json, libs/payments/eligibility/tsconfig.spec.json, tsconfig.base.json
Because:
* Plan eligibility depends on a number of factors, including what plans the user is already subscribed to (in Stripe, Google IAP or Apple IAP) and available upgrade paths for those plans per product-specific config (in Stripe metadata currently but soon to live in Contentful).
* We want to break out eligibility checks and types into a separate library from the auth server's `CapabilityService.getPlanEligibility`, since it's not really capability-oriented.
This commit:
* Generates a new nx library in lib/payments/eligibility
Closes #FXA-7582
=> feat(libs): create EligibilityManager library

packages/functional-tests/pages/config.ts, packages/functional-tests/pages/index.ts, packages/functional-tests/pages/layout.ts, packages/functional-tests/pages/signupReact.ts, packages/functional-tests/tests/misc/forceAuth.spec.ts, packages/functional-tests/tests/oauth/forceAuth.spec.ts, packages/functional-tests/tests/oauth/resetPassword.spec.ts, packages/functional-tests/tests/react-conversion/cannotCreateAccount.spec.ts, packages/functional-tests/tests/react-conversion/legal.spec.ts, packages/functional-tests/tests/react-conversion/oauthResetPassword.spec.ts, packages/functional-tests/tests/react-conversion/recoveryKey.spec.ts, packages/functional-tests/tests/react-conversion/resetPassword.spec.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/functional-tests/tests/react-conversion/syncV3ResetPassword.spec.ts, packages/functional-tests/tests/reset-password/resetPassword.spec.ts, packages/functional-tests/tests/settings/misc.spec.ts, packages/functional-tests/tests/settings/password.spec.ts, packages/functional-tests/tests/settings/recoveryKey.spec.ts, packages/functional-tests/tests/syncV3/syncV3ResetPassword.spec.ts, packages/fxa-content-server/server/lib/routes/react-app/index.js, packages/fxa-settings/src/components/App/index.tsx
- We need to add P1 tests for all signup React flows
- Adds P1 tests for signup web, signup oauth, signup oauth webchannel and sigup sync flows
- Adds a new POM for config page, ensures that pulling config does not interfere with tests
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7315
=> test(react): Add signup P1 playwright tests in react

.gitignore, _dev/docker/ci/Dockerfile.dockerignore
- We want all files ending in .env to be ignored
- gitignores files ending with .env
- dockeringores files ending with .env
Closes: 
=> task(all): Ignore all .env files

packages/fxa-content-server/app/scripts/templates/partial/brand-messaging.mustache, packages/fxa-content-server/app/scripts/templates/post_verify/third_party_auth/set_password.mustache, packages/fxa-content-server/app/scripts/views/mixins/brand-messaging-mixin.js, packages/fxa-content-server/app/scripts/views/post_verify/third_party_auth/set_password.js, packages/fxa-content-server/app/styles/modules/_branding.scss, packages/fxa-content-server/server/templates/pages/src/index.html, packages/fxa-settings/src/components/AppLayout/index.tsx, packages/fxa-settings/src/components/BrandMessaging/index.stories.tsx, packages/fxa-settings/src/components/BrandMessaging/index.test.tsx, packages/fxa-settings/src/components/BrandMessaging/index.tsx, packages/fxa-settings/src/components/Settings/AppLayout/index.tsx, packages/fxa-settings/src/pages/ResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/index.tsx, packages/fxa-settings/src/pages/Signin/index.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.test.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx, packages/fxa-settings/src/pages/Signup/index.tsx, packages/fxa-settings/src/styles/brand-banner.css
- More than one banner could show up on mobile
- Tab order was wrong
- Settings header could overlap brand header
- Takes a different approach to injecting the banner
- Two banners are now rendered in a static matter at the top & bottom of page
- Responsive CSS is used to control the visibility of these headers
- Adds the banner to the confirm signup page for the react conversion
Closes: FXA-8352, FXA-8357, FXA-8359, FXA-8332
=> bug(settings,content): UX defects with brand messaging banner

packages/functional-tests/pages/settings/totp.ts, packages/functional-tests/tests/react-conversion/oauthResetPassword.spec.ts, packages/fxa-settings/src/models/Account.ts, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/container.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.stories.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/interfaces.ts, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/container.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/interfaces.ts, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/mocks.tsx, packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/index.tsx
- The `redirectTo` URL is an optional parameter for the `password/forgot/send_code` end point
- If we don't send this, the user just won't get redirected back to the RP. Rather they will see a success message instead that acts as a dead end to their flow.
- The redirect back to the RP would if the email link was opened in the same tab, so it's unlikely many users were experience flows where they were redirected. Therefore this change resolves a bug, and has low impact on our users.
- Removes the `redirectTo` URL form the call to the password/forgot/send_code endpoint.
Closes: FXA-8363, FXA-8358
These flows are being revisited in [FXA-6670](https://mozilla-hub.atlassian.net/browse/FXA-6670). For the time being we are choosing to reduce complexity, by …
=> bug(settings): redirectTo can be rejected by password/forgot/send_code endpoint

packages/fxa-settings/src/lib/integrations/integration-factory.ts, packages/fxa-settings/src/lib/oauth/hooks.tsx
Because:
* When resetting through mobile sync, a blank page was rendered on complete reset PW attempt
This commit:
* Passes `integration.data.service` into the get client info call if it's present, since this can sometimes contain the client ID
closes FXA-8358
---
See [comment here](https://github.com/mozilla/fxa/pull/15820/files#r1333442428) where I started to track down the problem. The reason it's loading a blank page is because we were accidentally trying to use material-ui's `CardHeader` instead of our own.
In prod / Backbone, we are hitting the OAuth broker for this flow, which can be verified by checking the network request and seeing `broker: redirect`. Testing locally, I'm able to see our `isOAuthVerificationDifferentBrowser` check return true for this same case (e.g. in the …
=> fix(react): Tweak integration clientInfo check for reset PW sync mobile

packages/fxa-content-server/app/scripts/templates/account_recovery_confirm_key.mustache, packages/fxa-content-server/app/scripts/templates/confirm_signup_code.mustache, packages/fxa-content-server/app/scripts/templates/force_auth.mustache, packages/fxa-content-server/app/scripts/templates/index.mustache, packages/fxa-content-server/app/scripts/templates/post_verify/finish_account_setup/set_password.mustache, packages/fxa-content-server/app/scripts/templates/post_verify/password/force_password_change.mustache, packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache, packages/fxa-content-server/app/scripts/templates/sign_in_token_code.mustache, packages/fxa-content-server/app/scripts/templates/support.mustache, packages/fxa-content-server/server/templates/pages/src/index.html, packages/fxa-content-server/server/templates/pages/src/update_firefox.html
- We are introducing new strings for Mozilla account
- Adds new strings in comment blocks
Closes: FXA-7989
Example of updated pot file
I validated locally that `{{#t}} {{/t}}` tags in comment blocks get extracted.
=> task(content): Add l10n strings for Mozilla account

packages/fxa-payments-server/src/components/Header/en.ftl, packages/fxa-payments-server/src/components/NewUserEmailForm/en.ftl, packages/fxa-payments-server/src/routes/Checkout/en.ftl
- We want to start the localization effort of updating strings from Firefox to Mozilla
- Creates new l10n strings / ids using the Mozilla branding
Closes: FXA-7991
=> task(payments): Update strings referencing 'Firefox accounts'

packages/fxa-react/components/LogoLockup/en.ftl, packages/fxa-settings/src/components/GetDataTrio/en.ftl, packages/fxa-settings/src/components/Settings/BentoMenu/en.ftl, packages/fxa-settings/src/components/Settings/ConnectedServices/en.ftl, packages/fxa-settings/src/components/Settings/DataCollection/en.ftl, packages/fxa-settings/src/components/Settings/DropDownAvatarMenu/en.ftl, packages/fxa-settings/src/components/Settings/HeaderLockup/en.ftl, packages/fxa-settings/src/components/Settings/PageDeleteAccount/en.ftl, packages/fxa-settings/src/components/TermsPrivacyAgreement/en.ftl, packages/fxa-settings/src/pages/CannotCreateAccount/en.ftl, packages/fxa-settings/src/pages/CookiesDisabled/en.ftl, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/en.ftl, packages/fxa-settings/src/pages/Signin/SigninTokenCode/en.ftl, packages/fxa-settings/src/pages/Signin/en.ftl, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/en.ftl
Because:
* We want l10n strings that are changing from Firefox to Mozilla to be localized before launch
This commit:
* Creates new copies of FTL strings that contain Firefox branding references and replaces them with Mozilla branding
closes FXA-7988
--
There were less string updates here than I figured there would be, so feel free to double check me. Here's [a handy link](https://github.com/mozilla/fxa-content-server-l10n/blob/main/locale/templates/settings.ftl) to see the full list.
=> refactor(fxa-settings): L10n updates for Mozilla accounts branding

packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/webpack.config.js
- It is hard to debug webpack bundle in production because of the optimizations that webpack does
- Add config to build an unoptmized build that is easier to debug
This is to help debug https://mozilla-hub.atlassian.net/browse/FXA-8354. We will need a cloud ops PR to add override value.
In my local testing, the gzip unoptmized bundle was 1.2MB and ~6MB extracted. In production, the optmized bundle is 500kB and 1.2MB extracted.
=> chore(build): Add env to override the webpack build mode

_dev/docker/mono/build.sh
- We were receiving what seemed like a nondeterministic cache hit
- Disables nx cache for now in docker build
This appeared to be working previously, but currently the cache hit doesn't seem to be getting restored despite circle ci out put indicating the file was restored. 
But the docker image doesn't appear to have the file:
More investigation into this behavior is needed, but for now, this small change should mitigate the issue.
=> task(CI): Disable nx cache in docker build

packages/fxa-profile-server/lib/server/web.js
- If the response from the auth server contained no body. The profile server would crash and restart.
- Gracefully handles the scenario where the body is missing.
Closes: FXA-8375
It's a bit odd the body isn't being provided. Not sure if other think so. If so, I can file a follow up for this.
=> bug(profile): Fix server crash on unexpected response.

packages/fxa-auth-client/lib/client.ts, packages/fxa-settings/src/models/Account.ts, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/interfaces.ts, packages/fxa-settings/src/pages/mocks.ts
Because:
* Users could land in a bad state if they first try to reset with an invalid recovery key since auth-server would send out a reset successful email and users would see an expired link
This commit:
* Passes accountResetToken from AccountRecoveryConfirmKey to CompleteResetPassword for reuse to prevent the expired state
* Properly passes up the 'accountResetWithRecoveryKey' option to prevent auth-server from landing in an unexpected state
fixes FXA-8419
=> fix(react): Prevent preemptive reset password email from sending with accountResetToken tweaks

packages/fxa-content-server/app/styles/modules/_branding.scss, packages/fxa-settings/src/styles/brand-banner.css
- Forgot password could not be clicked on when banner was visible on iPhone SE
- Use a different account could not be clicked on when banner was visible on iPhone SE
- Adds margin to body bottom when page is in brand messaging mode
Closes: FXA-8422
After fix page can be scrolled further down:
Content Server:
React:
=> bug(content): Links hidden on some devices by banner

packages/fxa-settings/src/components/LinkRememberPassword/index.test.tsx, packages/fxa-settings/src/components/LinkRememberPassword/index.tsx, packages/fxa-settings/src/pages/mocks.ts
Because:
* Not passing query parameters causes OAuth and Sync flows to lose their query params (and context) on signin
This commit:
* Passes params and email param if present back to /signin or /force_auth
fixes FXA-8427
=> fix(react): Pass query parameters on 'Remember your password' link

packages/fxa-content-server/app/scripts/templates/partial/brand-messaging.mustache, packages/fxa-content-server/app/scripts/templates/post_verify/third_party_auth/set_password.mustache
- There was invalid HTML
- Fixes the mismatched `<span>Learn more</a>` HTML
- Adds extra curly brace to the include
Closes: FXA-8423
The defect looked like this with HTML being output to the page:
=> bug(content): Page would not render properly in some cases

packages/fxa-content-server/server/config/local.json-dist
- Safari is upgrading the script fetching requests in the content server when it sees the Content-Security-Policy header includes `upgrade-insecure-requests`.
- The above prevents testing a local build of FxA against Firefox iOS, because firefox ios uses webkit which exhibits the same behaviour and tries to load resources using `https://localhost` (note the `https` here)
- Changes the local config for the content server to disable csp
cc @vbudhram 
Closes: N/A
=> Allow FxA to run locally on safari by disabling csp locally

packages/fxa-content-server/app/scripts/models/reliers/relier.js, packages/fxa-content-server/app/scripts/views/index.js, packages/fxa-content-server/app/scripts/views/mixins/cached-credentials-mixin.js, packages/fxa-content-server/app/tests/spec/views/index.js, packages/fxa-settings/src/pages/Signup/index.test.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
Because:
* Taking the user back to the Backbone index page on click of React "Change email"  when they had an account in local storage would force a redirect to /signin
This commit:
* Adds a new 'prefillEmail' parameter for the React app to pass back to the Backbone app to signify to Backbone that 'Change email' was clicked
* On the React side, remove existing 'emailFromContent' and 'email' params from link since 'email' alters behavior on the Backbone side and 'emailFromContent' alters behavior on the React side
* On the Backbone side, set this field as a new relier field (typical of how we handle/validate external params), and if it exists on the index page, don't redirect and instead, prefill the email to match parity
fixes FXA-8307
=> feat(react): Allow Signup 'Change email' to behave as expected

packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* The value of this key doesn't matter for the purpose of this test.
* This key isn't valid.
* Using a key that looks like a valid key is causing us to get security alerts.
This commit:
* Replaces the key value in the test with a dummy string.
Relates to #FXA-8371
=> chore(auth): remove unused and invalid test Stripe API key

packages/fxa-content-server/app/scripts/views/confirm_signup_code.js, packages/fxa-content-server/app/scripts/views/mixins/brand-messaging-mixin.js
- We weren't seeing a `flow.confirm_sign_up.brand-messaging-prelaunch-view` metric on the confirm sign up page
- The signin page would double emit `flow.signin.brand-messaging-prelaunch-view`
- Registers the brand-messaging-mixin on the `confirm_signup_code view`.
- Uses `logFowEventOnce` instead of `logFlowEvent` method to emit metric.
Closes: FXA-8429
Before:
Double metrics:
Missing confirm `flow.confirm_sign_up.brand-messaging-prelaunch-view`:
After:
Single metric:
Emitting `flow.confirm_sign_up.brand-messaging-prelaunch-view`:
_(Note testing with postlaunch view, but it works just like prelaunch view. Pre vs post is just a string in the config file.)_
=> bug(content): Missing & duplicate brand metrics

packages/fxa-auth-server/lib/routes/utils/signin.js
- We want to pin down reports of occasionally unsent emails.
- sendVerifyAccountEmail was written with promise chains, where as other similar functions were async/await
- Adds info log prior to email send, so we know if the email will send code will be triggered
- Adds try catch around sendEmail code so we can monitor any issues
- Converts sendVerifyAccountEmail to an async function to be consistent with rest of code in `signin.js` and prevent mixing of patterns and improve error handling/logging.
Closes: FXA-8376
An example log letting us gain more insight into the flow:
This won't fix the issue reported in FXA-8376, however, it will allow us to reopen it with more info. To validate this changeset locally:
- Add …
=> bug(auth): Random email non-delivery

packages/fxa-auth-server/scripts/paypal-processor.ts, packages/fxa-auth-server/scripts/prune-tokens.ts, packages/fxa-auth-server/scripts/subscription-reminders.ts, packages/fxa-auth-server/scripts/verification-reminders.js
Because:
* We don't have good cron visibility
This commit:
* Adds sentry logging
Closes FXA-7658
=> feat: add sentry monitoring to cron jobs

libs/shared/contentful/src/index.ts, libs/shared/contentful/src/lib/contentful.client.config.ts, libs/shared/contentful/src/lib/contentful.client.spec.ts, libs/shared/contentful/src/lib/contentful.client.ts, libs/shared/contentful/src/lib/contentful.error.ts, libs/shared/contentful/src/lib/contentful.manager.spec.ts, libs/shared/contentful/src/lib/factories.ts, libs/shared/contentful/src/lib/types.ts, libs/shared/l10n/package.json, packages/fxa-auth-server/config/index.ts, packages/fxa-graphql-api/src/config.ts
- Need to determine a valid locale configured in Contentful.
- Add getLocale method to ContentfulClient to determine locale using locales available in Contentful and defaulting to 'en' as a fallback.
Closes: #FXA-8225
Keeping in draft until #15798 is merged.
=> feat(contentful): add contentful get locale

apps/payments/next/.env.production.json, apps/payments/next/app/_nestapp/app.module.ts, apps/payments/next/project.json
- payments-next heartbeat api returns 500 due to missing config file.
- Reorders nest-typed-config loaders so that fileLoader is first, which results in an empty .env.json file to be included in the payments-next build.
- Adds normalization step to config loader, for non-string values.
Closes: #
=> fix(payments): config file missing in build

packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailRecoveryKey/en.ftl
- The ftl string uses Mozilla instead of the term -brand-mozilla and is causing a linting error
- Replaces the string with the correct brand term
=> chore(l10n): Replace string with brand term in autmatedEmailRecoveryKey

packages/functional-tests/tests/postVerify/accountRecovery.spec.ts, packages/functional-tests/tests/signin/relyingParties.spec.ts
- Fix pre verification step for post verify tests
- Disable monitor test until FXA-8446 is worked on
- Fixes pre verification step for post verify tests
- Disables monitor test until FXA-8446 is worked on
Closes: FXA-8281
=> test(functional): fix post verify account recovery test

packages/functional-tests/tests/subscription-tests/subscription.spec.ts
- it was observed that this test failed on stage env
- disables the test until it is fixed
=> test(functional): Disable failing test on stage

packages/fxa-payments-server/server/config/index.js, packages/fxa-payments-server/server/lib/server.js, packages/fxa-payments-server/src/lib/config.test.ts, packages/fxa-payments-server/src/lib/config.ts, packages/fxa-payments-server/src/lib/hooks.test.tsx, packages/fxa-payments-server/src/lib/hooks.tsx
- SubPlat currently does not request cookie consent from customers, therefore Google Analytics should be configured to not use any cookies.
- Sets Google Analytics default consent to denied for all consent types.
- Renames testMode to debugMode, and reassigned it to the gtag debug_mode option, which is what it was originally intended for.
Closes: #FXA-8445
=> feat(payments): google analytics deny consent

packages/fxa-settings/src/components/AppLayout/index.tsx, packages/fxa-settings/src/styles/brand-banner.css
- When the brand messaging banner is enabled, there's  extra white space at the bottom of the doc in the react flows.
- Only applies the extra margin for mobile flows with a sticky banner in the footer.
After fix:
This is a small follow up to https://github.com/mozilla/fxa/pull/15865.
=> bug(settings): Margin bottom should only be applied to mobile

packages/fxa-content-server/app/scripts/templates/force_auth.mustache, packages/fxa-content-server/app/scripts/templates/index.mustache, packages/fxa-content-server/app/scripts/templates/post_verify/finish_account_setup/set_password.mustache, packages/fxa-content-server/app/scripts/templates/post_verify/third_party_auth/set_password.mustache, packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache, packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache, packages/fxa-content-server/app/scripts/views/force_auth.js, packages/fxa-content-server/app/scripts/views/index.js, packages/fxa-content-server/app/scripts/views/mixins/monitor-client-mixin.js, packages/fxa-content-server/app/scripts/views/post_verify/finish_account_setup/set_password.js, packages/fxa-content-server/app/scripts/views/sign_in_password.js, packages/fxa-content-server/app/scripts/views/sign_up_password.js, packages/fxa-content-server/app/tests/spec/views/sign_in_password.js, packages/fxa-settings/src/components/CardHeader/index.tsx, packages/fxa-settings/src/components/TermsPrivacyAgreement/en.ftl, packages/fxa-settings/src/components/TermsPrivacyAgreement/index.stories.tsx, packages/fxa-settings/src/components/TermsPrivacyAgreement/index.test.tsx, packages/fxa-settings/src/components/TermsPrivacyAgreement/index.tsx, packages/fxa-settings/src/pages/Signin/index.stories.tsx, packages/fxa-settings/src/pages/Signin/index.tsx, packages/fxa-settings/src/pages/Signup/index.stories.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
* We want to show links to Monitor's terms of service and privacy notice when users are signing in/signing up from that relying party
* Add MoniterClientMixin to conditionally display Monitor terms
* Add monitor terms of service to index, sign_in_password, sign_up_password, set_password, force_auth when the oauth client id corresponds to Monitor's
* Add same terms to React version of the same pages
* Add l10n strings for rebrand to Mozilla account
* Update tests
* Disable 123Done client id from pocket-migration-mixin (intended for testing)
Closes: #FXA-8370
Signin/signup with Monitor terms
To simulate login to Monitor with 123Done (localhost:8080):
1) Uncomment 123Done client ID on line 12 of `monitor-client-mixin.js`
2) With stack running locally, go …
=> feat(monitor): Add monitor terms of service to signin/signup

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/lib/senders/emails/global.scss, packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml, packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.stories.ts, packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.txt, packages/fxa-auth-server/lib/senders/emails/partials/brandMessaging/en.ftl, packages/fxa-auth-server/lib/senders/emails/partials/brandMessaging/index.mjml, packages/fxa-auth-server/lib/senders/emails/partials/brandMessaging/index.scss, packages/fxa-auth-server/lib/senders/emails/partials/brandMessaging/index.txt
- We want to add in email product messaging about the Mozilla account brand
- Adds a banner to all fxa emails with intended messaging
Closes: FXA-7994
From mail dev:
In order to test set the add `BRAND_MESSAGING_MODE=postlaunch` in the `.dotenv` file in the root of fxa, and then run `dotenv -- yarn start`. To validate emails manually, run use [maildev](https://mozilla.github.io/ecosystem-platform/how-tos/local-emails-with-maildev).  We can also view the changes in storybook. `nx storybook fxa-auth-server`, then checkout the layouts which have branding and non branding versions.
One other thing to possibly test... I ended up using a background gradient with fallback solid background color. As far as I can tell this works even legacy clients. However, it …
=> task(auth): Add branding banner to emails

packages/functional-tests/pages/signupReact.ts, packages/fxa-settings/src/pages/Signup/index.test.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
* Submit button was not enabled if password field was autofilled by password manager, even if all form requirements met
* Validation was only happening if all inputs blurred
* Change onBlur form validation mode to onChange
* Update related tests
Closes: #FXA-8331
✅  Checked that form submission is disabled if password requirements are not met, passwords do not match, or any field is empty.
✅ Checked that form submission is enabled if all requirements above met and password field was autofilled and we don't manually touch/change/blur it
=> fix(react): Signup submit can be enabled if password autofilled

libs/payments/eligibility/src/index.ts, libs/payments/eligibility/src/lib/eligibility.manager.spec.ts, libs/payments/eligibility/src/lib/eligibility.manager.ts, libs/payments/eligibility/src/lib/eligibility.types.ts, libs/shared/contentful/src/lib/contentful.manager.spec.ts, libs/shared/contentful/src/lib/factories.ts, libs/shared/contentful/src/lib/queries/eligibility-content-by-plan-ids/util.spec.ts, libs/shared/contentful/src/lib/queries/eligibility-content-by-plan-ids/util.ts
* We want to determine whether a customer is eligible for a plan
offering, and if so, which offering they are eligible for.
* Adds the getOfferingOverlap method to the eligibility manager.
Closes FXA-8241
=> feat: add getOfferingOverlap to eligibility manager 

packages/fxa-auth-server/config/supportedLanguages.js, packages/fxa-auth-server/lib/customs.js, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/lib/server.js, packages/fxa-auth-server/scripts/bulk-mailer/normalize-user-records.js
- fxa-auth-server is failing to start up in build since TypeScript path aliases are still present in JavaScript files.
- Replace ts path aliases in fxa-auth-server JS files, with relative paths.
Closes: #
=> fix(auth): replace ts alias with relative paths

packages/fxa-settings/src/lib/glean/index.test.ts, packages/fxa-settings/src/lib/glean/index.ts
Because:
- the uid getter in fxa-settings could cause an error to be thrown (at least when the user has not signed in yet)
This commit:
- adds a workaround to ignore the error for now
=> fix(metrics): add workaround for uid check in fxa-settings

packages/fxa-admin-server/src/scripts/audit-tokens.ts, packages/fxa-auth-server/scripts/paypal-processor.ts, packages/fxa-auth-server/scripts/prune-tokens.ts, packages/fxa-auth-server/scripts/subscription-reminders.ts, packages/fxa-auth-server/scripts/verification-reminders.js
Because:
* Our monitoring doesn't show our crons ending
This commit:
* Flushes sentry before killing the process
Closes FXA-7658
=> feat: Flush sentry before ending cron processes

packages/fxa-auth-client/browser.ts, packages/fxa-auth-client/lib/client.ts, packages/fxa-graphql-api/src/gql/account.resolver.spec.ts, packages/fxa-graphql-api/src/gql/account.resolver.ts, packages/fxa-graphql-api/src/gql/dto/input/password-forgot.ts, packages/fxa-settings/src/models/Account.ts
- We should be using the authPW value in react routes
- Updates the reset password react to use authPW
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8471
enshots
=> fix(bug): Update reset password to use authPW

_scripts/clone-legal-docs.sh, packages/fxa-settings/src/lib/file-utils-legal.tsx
- We now want to reference a privacy policy specific to Mozilla
- Starts using the `mozilla_privacy_policy.md` legal doc
Closes: FXA-8347
Before:
After:
=> task(content): Update privacy policy document

packages/fxa-auth-server/lib/senders/emails/global.scss, packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml, packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.stories.ts, packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.txt
- We want the brand messaging notice on subscription emails too
- Adds the brand messaging.
- Increase max width on the message container to 640px to be inline with subscription email's max width.
Closes: FXA-8465
=> task(auth): Add brand messaging to subplat emails

libs/payments/capability/project.json, libs/payments/cart/project.json, libs/payments/eligibility/project.json, libs/payments/eligibility/src/lib/eligibility.manager.ts, libs/payments/paypal/project.json, libs/shared/account/account/project.json, libs/shared/contentful/project.json, libs/shared/db/mysql/account/project.json, libs/shared/db/mysql/account/src/index.ts, libs/shared/db/mysql/account/src/lib/account.provider.ts, libs/shared/db/mysql/core/project.json, libs/shared/db/mysql/core/src/lib/core.ts, libs/shared/error/project.json, libs/shared/l10n/project.json, libs/shared/log/project.json, libs/shared/metrics/statsd/project.json, packages/fxa-graphql-api/tsconfig.build.json
- Manual changes were needed to all nx libraries to ensure expected TypeScript build and development intellisense behavior.
- Removes the "rootDir" build option added to all libraries, to allow for relative paths. This is no longer necessary since issues using TypeScript path aliases have been resolved.
- Removes changes to "main" build option, which ensured the built version of package.json had the correct path to the main index.js.
=> fix(nx): remove nx prject rootDir and main changes

libs/shared/contentful/src/__generated__/graphql.ts, packages/db-migrations/contentful/1697485959016_fxa-8428.js
- Update Contentful content model to include newsletter fields
- Adds `newsletterLabelTextCode` and `newsletterSlug` to the Common Content content model
Closes: [FXA-8428](https://mozilla-hub.atlassian.net/browse/FXA-8428)
[FXA-8428]: https://mozilla-hub.atlassian.net/browse/FXA-8428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(contentful): Update Contentful Content Model with newsletter fields

_scripts/clone-legal-docs.sh, packages/fxa-settings/src/lib/file-utils-legal.tsx
Reverts mozilla/fxa#15915
See convo in FXA-8347. The actual updates to the legal docs are still a WIP. The document I referenced isn't the most up to date.
=> Revert "task(content): Update privacy policy document"

packages/fxa-auth-server/lib/server.js
- `fxa-content-server` was receiving CORS errors from auth-server, due to some headers not being allowed.
- Update auth cors settings to allow baggage header.
Necessary to resolve CORS issues, discussed in [Sentry docs here](https://docs.sentry.io/platforms/node/usage/distributed-tracing/dealing-with-cors-issues/), after adding [browser tracing in this PR](https://github.com/mozilla/fxa/pull/15778).
=> fix(auth): allow baggage header in request

packages/fxa-content-server/app/scripts/templates/partial/brand-messaging.mustache, packages/fxa-settings/src/components/BrandMessaging/index.tsx
- We want the banner close icon to be aligned right
- Aligns the X icon by using mr-auto (ml-auto for rtl) for flex
Closes: FXA-8455
Backbone:
React:
Note, that when testing the React version in Hebrew, the text direction wasn't swapping properly, where as for backbone it was. To get around this, I manually changed the `dir` attribute on the document, and you can see that once this is changed the layout renders correctly. I will be filing a follow up issue for the fact that Hebrew is not triggering a RTL direction in our react app. This defect is also observable on production.
=> bug(settings,content): Make banner x aligned right

packages/fxa-content-server/app/scripts/lib/glean/index.ts, packages/fxa-content-server/app/tests/spec/lib/glean.js, packages/fxa-settings/src/lib/glean/index.test.ts, packages/fxa-settings/src/lib/glean/index.ts
Because:
- glean.js/web v2 tries to access localStorage during initialization and that could cause an error in a small number of a browsers
This commit:
- catches errors from glean.js initialization and disable the feature
=> fix(metrics): try-catch Glean initialization error

packages/fxa-auth-server/docs/swagger/third-party-auth-api.ts, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/lib/routes/linked-accounts.ts, packages/fxa-auth-server/lib/routes/utils/third-party-events.ts, packages/fxa-auth-server/scripts/google-events-cli.js, packages/fxa-auth-server/test/local/routes/linked-accounts.js
- We need to be to handle Google RISC events, these are security events for the account
- Adds a reciever endpoint
- Adds a cli to setup, configure RISC stream from Google
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7963
=> feat(events): Add support for handling Google RISC events, add cli to test

packages/fxa-settings/src/components/Settings/ConnectedServices/Service.tsx
Because:
* RP names will change Dec 5 and we should continue to show the right icons
This commit:
* accepts the new names
Closes FXA-8506
=> feat: Accept new RP names

packages/fxa-auth-server/config/index.ts
- We were encoding Firefox as the service name used when setting up a 2FA authenticator
- Changes the totp service name to Mozilla
Closes: FXA-8509
From authy:
Note that authenticator apps, like Authy, automatically try to look up a logo based on service name. By changing the service name we also change the logo in the authenticator app.
Also note that this name has no bearing the authenticity of totp codes.
=> task(auth): Update totp service name

packages/fxa-settings/public/index.html
- We are updating <Mozilla branding
- Changes text to Mozilla accounts requires JavaScript
Closes: FXA-8517
=> bug(settings): Firefox Accounts requires JavaScript

packages/fxa-react/styles/flows.css
- We want to add a bit more spacing to make things look more balanced.
- Sets bottom padding to p-12, 3 rem
- Sets top padding to p-9, 2.25 rem
Closes: FXA-8516
In backbone:
In React:
=> task(content): Changing padding on card

packages/fxa-payments-server/src/components/PaymentConsentCheckbox/en.ftl, packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.test.tsx, packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.tsx, packages/fxa-payments-server/src/components/PaymentMethodHeader/index.test.tsx, packages/fxa-payments-server/src/components/TermsAndPrivacy/en.ftl, packages/fxa-payments-server/src/components/TermsAndPrivacy/index.tsx
* We are rebranding to Mozilla accounts
* Removes "make of Firefox products" from checkout page
* Replace Firefox Accounts with Mozilla Accounts in footer
Closes: #FXA-8510, FXA-8511
Previous:
Updated:
Previous:
Updated:
The ftl file served for payments include both the payments branding terms and general branding terms, so the payments app is able to access the new branding terms in fxa-shared.
=> fix(payments): Remove remaining mentions of Firefox accounts

packages/fxa-content-server/app/scripts/templates/partial/brand-messaging.mustache, packages/fxa-settings/src/components/BrandMessaging/index.tsx
- The font weight and size were not to spec
- Sets font to 12px (tailwind text-xs)
- Sets weight to 600 (tailwind font-semibold)
Closes: FXA-8508
=> bug(settings,content): Font weight and size incorrect in postlaunch banner

packages/fxa-auth-server/lib/senders/email.js
Because:
* We have unhandled exceptions for bounced emails
This commit:
* Stops throwing them
Closes FXA-3643
=> fix: stop throwing when an email bounces

packages/fxa-content-server/app/scripts/lib/dom-writer.js, packages/fxa-content-server/app/scripts/templates/support.mustache, packages/fxa-content-server/app/styles/_base.scss, packages/fxa-content-server/app/styles/_layout.scss, packages/fxa-content-server/app/styles/modules/_branding.scss, packages/fxa-content-server/app/styles/modules/_settings.scss, packages/fxa-payments-server/src/components/AppLayout/index.scss, packages/fxa-payments-server/src/components/AppLayout/index.tsx, packages/fxa-payments-server/src/routes/Subscriptions/index.scss
* The Mozilla logo was duplicated in the header
* remove background image in header
* Fix styling of Payments Subscription page header
* Fix styling of Support (on content-server) and adjust mobile layout
Closes: #FXA-8512
Before, Subscriptions:
Before, Support:
After, subscriptions (desktop):
After, subscriptions (mobile):
After, support (desktop):
After, support (mobile):
I've checked that the header renders correctly in RTL but spotted that the rest of the support form does not (filed FXA 8520)
Testing will require creating an account and subscribing to a product via 123Done. Then, go to:
- http://localhost:3030/subscriptions
- http://localhost:3030/support
=> fix(branding): Fix header styling for Subscriptions and Support pages

libs/shared/l10n/README.md, libs/shared/l10n/src/index.ts, libs/shared/l10n/src/lib/determine-direction.spec.ts, libs/shared/l10n/src/lib/determine-direction.ts, libs/shared/l10n/src/lib/rtl-locales.json, packages/fxa-auth-server/lib/senders/renderer/index.ts, packages/fxa-react/components/Head/index.tsx, packages/fxa-settings/src/components/ButtonDownloadRecoveryKeyPDF/VectorImagesForPdf.tsx, packages/fxa-settings/src/components/ButtonDownloadRecoveryKeyPDF/index.tsx, packages/fxa-settings/src/components/ButtonDownloadRecoveryKeyPDF/requiredFont.test.tsx, packages/fxa-settings/src/components/ButtonDownloadRecoveryKeyPDF/requiredFont.tsx, packages/fxa-shared/l10n/determineDirection.ts, packages/fxa-shared/l10n/rtl-locales.json
* Settings and payments were not automatically displayed in RTL for languages such as Hebrew
* dir and lang html attributes were defaulting to en, ltr
* Set lang and dir with react helmet
* Add method to determine locale direction
Closes: #FXA-6234
This fix does not apply to Storybook - storybook has a LTR/RTL toggle to manual control directionality. I'm not sure if we want to keep this manual control (only) or use the browser locale+ locale direction as a starting point for storybook.
To test this flow for the account settings:
- set the browser's preferred page display language to a supported RTL language (e.g., Hebew)
- go to `localhost:3030` and sign up/sign in …
=> fix(l10n): Ensure Settings and Payments are displayed RTL for RTL locales

packages/fxa-content-server/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json, yarn.lock
Because:
- we should upgrade to glean.js 2.0.5 because there are data schema validation errors from the accounts_frontend project
This commit:
- upgrades glean.js to 2.0.5
Fixes https://mozilla-hub.atlassian.net/browse/FXA-8521
=> chore(deps): upgrade glean.js to 2.0.5

packages/fxa-content-server/app/scripts/templates/400.mustache, packages/fxa-content-server/app/scripts/templates/500.mustache, packages/fxa-content-server/app/scripts/templates/post_verify/finish_account_setup/set_password.mustache, packages/fxa-content-server/app/styles/_layout.scss, packages/fxa-content-server/server/templates/pages/src/404.html, packages/fxa-content-server/server/templates/pages/src/500.html, packages/fxa-content-server/server/templates/pages/src/502.html, packages/fxa-content-server/server/templates/pages/src/503.html
- This view didn't look like others
- Adds appropriate classes
- Removes some legacy hacks in _layout.scss
Closes: FXA-8515
Note this could probably use a follow up due to the comment here. It's largely outside the scope of account branding work, so the minimum fix will be applied here.
=> bug(content): Fix font style on signup with passwordless flow

libs/payments/capability/src/lib/capability.manager.spec.ts, libs/payments/capability/src/lib/capability.manager.ts, libs/shared/contentful/src/index.ts, libs/shared/contentful/src/lib/__mocks__/contentful.client.ts, libs/shared/contentful/src/lib/contentful.manager.spec.ts, libs/shared/contentful/src/lib/contentful.manager.ts, libs/shared/contentful/src/lib/factories.ts, libs/shared/contentful/src/lib/queries/services-with-capabilities/index.ts, libs/shared/contentful/src/lib/queries/services-with-capabilities/query.ts, libs/shared/contentful/src/lib/queries/services-with-capabilities/types.ts, libs/shared/contentful/src/lib/queries/services-with-capabilities/util.spec.ts, libs/shared/contentful/src/lib/queries/services-with-capabilities/util.ts, libs/shared/contentful/tsconfig.lib.json, libs/shared/contentful/tsconfig.spec.json, packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/lib/payments/utils.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js, packages/fxa-auth-server/test/remote/subscription_tests.js
- we want to add getClients method in the CapabilityManager library
Closes: [FXA-8242](https://mozilla-hub.atlassian.net/browse/FXA-8242)
[FXA-8242]: https://mozilla-hub.atlassian.net/browse/FXA-8242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(libs): Create getClients method in CapabilityManager

packages/fxa-content-server/app/styles/_base.scss, packages/fxa-content-server/app/styles/modules/_branding.scss, packages/fxa-content-server/server/templates/pages/src/404.html, packages/fxa-content-server/server/templates/pages/src/500.html, packages/fxa-content-server/server/templates/pages/src/502.html, packages/fxa-content-server/server/templates/pages/src/503.html, packages/fxa-content-server/server/templates/pages/src/index.html, packages/fxa-content-server/server/templates/pages/src/update_firefox.html, packages/fxa-react/styles/flows.css, packages/fxa-settings/src/components/AppLayout/index.tsx
Because:
* There were some minor UI inconsistencies between the two versions
This commit:
* Fixes that in React, the banner link was expanding the full width
* Addresses in Backbone, extra horizontal space when tabbing, using px values instead of rem, and a reused style was referenced by ID instead of class
* There was some inconsistent margin/padding across breakpoints when comparing the two versions which this fixes, and adds a small margin-bottom on the card so the box shadow no longer cuts off
* Adds minor a11y improvements
fixes FXA-8539
**Note**: I realized after the `<header>` change that while this definitely makes sense in desktop IMO, it could probably go either way in mobile. I'm OK with reverting that back to a `div` if we want, but I also think it's fine the way it is. It's …
=> fix(branding): Minor UI tweaks for Mozilla banner in Backbone & React

packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- Capability APIs and related functions have high usage, and certain Sentry events do not need to be logged for every event.
- Adds a function to wrap calls to Sentry, to only send events for a specified sample rate.
=> feat(auth): add sample rate to capability sentry

packages/fxa-settings/config/webpack.config.js, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/lib/crypto/deriver.ts, packages/fxa-settings/src/lib/crypto/scoped-keys.ts
Because:
- we should split the fxa-settings js bundle into smaller chunks
This commit:
- splits Settings and non-Settings routes by lazy loading the Settings component
I did try Webpack's `splitChunks` but that did not make sense as the main js file will always load the "shared" code; we really have just one entrypoint.  All that would get us is an extra request to get the shared js.  
Any further lazy loading of components are very small incremental gains.  But more importantly, attempts in doing so resulted in `Error: The <Localized /> component was not properly wrapped in a <LocalizationProvider />.`  That's the reason there aren't any more lazy loaded components in this PR.
So this is the first attempt at code-splitting with the low hanging fruit.  If we want to reduce the file sizes, …
=> chore(build): split the fxa-settings js bundle

packages/fxa-auth-server/lib/senders/email.js
- We don't want users to see 'New sign-in to Firefox' in the email subject if they are signing directly into Mozilla accounts
- We don't want users to see 'Approve sign-in to Firefox' in the email subject if they are signing directly into Mozilla accounts
- Replaces the term Firefox with Mozilla for clientName/serviceName when the signin occurs directly from the web (ie not through sync)
Closes: FXA-8530
Note that because our email templates are expecting a product name for `New sign-in to <% -clientName %>` or `Approve sign-in to <%- serviceName ->`. I have opted to simply use the term Mozilla in this case so as to be consistent. This needs to be cleared with product. If this is not okay, we will need to come up with a different term, e.g. 'account …
=> bug(auth): Fix email subjects when signing in directly from browser

libs/shared/contentful/src/lib/contentful.client.config.ts, libs/shared/contentful/src/lib/contentful.client.ts
* Apollo client provides no means of setting a cache TTL
* Sets up cache busting on a 5 minute interval by default, configurable via optional Nestjs config option.
Closes: FXA-8224
=> feat(contentful): setup cachebusting

packages/functional-tests/tests/oauth/signUp.spec.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts
- We shouldn't run these tests in prod
- Disables them in production
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8540
=> fix(tests): Skip react signup tests in production

packages/fxa-react/components/Footer/index.test.tsx, packages/fxa-react/components/Footer/index.tsx, packages/fxa-settings/src/components/Settings/ConnectAnotherDevicePromo/index.test.tsx, packages/fxa-settings/src/components/Settings/ConnectAnotherDevicePromo/index.tsx, packages/fxa-settings/src/components/Settings/ConnectedServices/Service.tsx, packages/fxa-settings/src/components/Settings/ConnectedServices/index.test.tsx, packages/fxa-settings/src/components/Settings/DataCollection/index.test.tsx, packages/fxa-settings/src/components/Settings/DataCollection/index.tsx, packages/fxa-settings/src/components/Settings/UnitRowTwoStepAuth/index.tsx
* Some links to terms, support articles were forcing en-us version
* We want to show the user's preferred language
* Remove en-US from links
Closes: #FXA-8556
=> fix(l10n): Remove en-us from external links

packages/fxa-settings/src/pages/ResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/index.tsx, packages/fxa-shared/metrics/glean/web/index.ts
Because:
- we should send metrics on page view and form submission on the password reset page
This commit:
- adds the view and submit events to reset password
Closes FXA-8493, FXA-8494
=> feat(metrics): add view and submit events for password reset

packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/test/local/payments/capability.js, packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js, packages/fxa-auth-server/test/mocks.js
- CapabilityManager was added to StripeHelper when it should be in CapabilityService
- moves CapabilityManager into CapabilityService
=> fix(auth): Move CapabilityManager into CapabilityService

packages/fxa-settings/src/pages/Signup/index.test.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
* We are adding glean pings to the react version of signup route
* Add reg_submit glean ping and associated tests
Closes: #FXA-8017
=> feat(settings): Add reg_submit Glean Ping in React

packages/fxa-settings/src/components/Settings/UnitRowRecoveryKey/index.tsx
* "Delete recovery key" modal is staying on screen after clicking "delete" or dismiss button
* Fix the modal dismiss
Closes: #FXA-8550
=> fix(settings): Ensure "delete recovery key" modal can be dismissed

packages/fxa-content-server/app/scripts/templates/pair/auth_complete.mustache, packages/fxa-content-server/app/scripts/views/pair/auth_complete.js
* On the pair complete page, link text becomes unreadable on click due to insufficient contrast.
* Change link to button element
Closes: #FXA-8483
The two possible CTAs for the pair/auth/complete page, with updated focus active and not active states:
The `pair/auth/complete` page is difficult to reach locally. To validate that the change from links to buttons resolves the UI/a11y issue, I temporarily copied the buttons to the index page (_change not included in this PR_)
=> fix(content): Fix unreadable button text when active

packages/fxa-content-server/app/scripts/templates/account_recovery_confirm_key.mustache, packages/fxa-content-server/app/scripts/templates/inline_recovery_setup.mustache, packages/fxa-content-server/app/scripts/templates/inline_totp_setup.mustache, packages/fxa-content-server/app/scripts/templates/post_verify/password/force_password_change.mustache, packages/fxa-content-server/app/scripts/templates/post_verify/secondary_email/add_secondary_email.mustache, packages/fxa-content-server/app/scripts/templates/post_verify/secondary_email/confirm_secondary_email.mustache, packages/fxa-content-server/app/scripts/templates/sign_in_recovery_code.mustache, packages/fxa-content-server/app/scripts/templates/sign_in_totp_code.mustache, packages/fxa-content-server/app/tests/spec/views/pair/auth_totp.js
* Sign in with TOTP screen did not have styling applied to header and subheader
* Add styling to sign_in_totp_code mustache file
Closes: #FXA-8559
Before:
After:
=> fix(content): Apply styling to Signin TOTP

nx.json
- We are removing tokens from our source
- Even those that are just for dev purposes
- Removes the accessToken from the default nx tasksRunnerOptions.
Closes: FXA-8392
Note: Some instructions will be added for developers who want to an access token to speed up builds locally.
=> task(nx): Remove accessToken

packages/fxa-auth-server/lib/routes/linked-accounts.ts
- Calling db.accountRecord with an undefined email is invalid.
- Checks that an email is provided.
Closes: FXA-8382
It's odd that this case arises. We get the data from either apple or google's API. I did extensive black box testing and couldn't trip the problem. I noticed that in sentry this issue first showed up in v1.61.2. This is around the time the apple transfer of pocket user script landed. I wonder if this is somehow just impacting pocket users with transferred apple accounts. With the error log, I think we will have a better idea.
=> bug(auth): Fail fast if email isn't present in linked account

packages/fxa-content-server/app/scripts/templates/partial/brand-messaging.mustache, packages/fxa-content-server/app/scripts/views/mixins/brand-messaging-mixin.js, packages/fxa-react/components/LinkExternal/index.tsx, packages/fxa-settings/src/components/BrandMessaging/index.tsx
- The learn more link would not respond to an Enter key press
- Uses LinkExternal in React for this link instead of a span with role=link
- Modifies content-server to use an anchor instead of a span with role=link
Closes: FXA-8586
=> bug(settings,content): Switch 'Learn more' branding link to a native link

packages/fxa-content-server/server/lib/routes/post-csp.js
- Our CSP has a lot of failures.  See https://mozilla.sentry.io/issues/3551750499/?project=6231069&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=6 .  Also FXA-7556
- Loosens restrictions
=> Allow broader input for CSP document-uri

packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.test.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx
* We are adding Glean metrics to the React pages
* Add view and submit glean pings to the ConfirmSignupCode page in React
* Add associated unit tests
Closes: #FXA-8019, FXA-8074
=> feat(glean): And frontend glean pings to ConfirmSignupCode React

packages/fxa-settings/src/pages/Signup/index.test.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
* We are adding Glean metrics to Signup flow in React
* Add signup submit success Glean ping on the frontend
* Modify signup submit glean ping to also fire for underage account creation request
* Add/modify relevant tests
Closes: #FXA-8018
=> feat(glean): Add frontend reg submit success glean ping

libs/shared/contentful/src/lib/contentful.client.ts
Contentful cache reset is causing "Store reset while query was in flight (not completed in link chain)".
We'd like to replace apollo client with graphql-request server-side in #16008 but this is a fix for now.
=> fix(contentful): do not reset contentful cache

packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/test/local/payments/capability.js
- Errors originating from the capability manager caused the GET */subscriptions/clients API to throw an error.
- Report capability manager errors to Sentry and return results from Stripe metadata
- Sanitizes capabilities info sent to Sentry
=> fix(capability): handle capability manager errors

packages/fxa-content-server/app/styles/modules/_avatar.scss
- Centers avatar on Subscription Management
Closes: [FXA-8597](https://mozilla-hub.atlassian.net/browse/FXA-8597)
Before
After
[FXA-8597]: https://mozilla-hub.atlassian.net/browse/FXA-8597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(content): Avatar not centered on SubMan

packages/fxa-settings/src/components/Settings/DataCollection/index.test.tsx, packages/fxa-settings/src/components/Settings/DataCollection/index.tsx
- The link pointed at the previous Firefox Accounts privacy notice
- Updates the link to point at the Mozilla accounts privacy notice
Closes: FXA-8608
=> bug(settings): Fix link on data collection privacy notice

packages/db-migrations/contentful/1698948888495_fxa-8534.js
- adds `Stripe Legacy Plans` field to Offering
Closes: [FXA-8534](https://mozilla-hub.atlassian.net/browse/FXA-8534)
Changes to the updated codegen files will be included in the PR for FXA-8502
[FXA-8534]: https://mozilla-hub.atlassian.net/browse/FXA-8534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(contentful): Add Stripe Legacy Plans field to Offering

packages/fxa-settings/src/components/FormPassword/index.tsx, packages/fxa-settings/src/components/Settings/FlowRecoveryKeyHint/index.tsx, packages/fxa-settings/src/components/Settings/UnitRowRecoveryKey/index.test.tsx
* We are seeing errors in Sentry where '<Localized /> component was not properly wrapped in a <LocalizationProvider />'
* The breadcrumbs indicate this might be caused by missing Fluent IDs in the bundle
* Fix mismatched l10n ids
* Fix test descriptions (remove stray mentions of old recovery key flow)
Closes: # FXA-8557
This might not completely resolve the Sentry errors - another avenue to investigate is the construction of localized error messages, particularly for the CompleteResetPassword page.
=> fix(settings): Fix fluent ID errors causing errors in Sentry

packages/fxa-settings/config/jest/babelTransform.js, packages/fxa-settings/config/webpack.config.js, packages/fxa-settings/package.json, packages/fxa-settings/src/lib/integrations/integration-factory-flags.test.ts, packages/fxa-settings/src/lib/integrations/integration-factory-flags.ts, packages/fxa-settings/src/lib/integrations/integration-factory.test.ts, packages/fxa-settings/src/lib/integrations/integration-factory.ts, packages/fxa-settings/src/lib/model-data/bind-decorator.spec.ts, packages/fxa-settings/src/lib/model-data/bind-decorator.ts, packages/fxa-settings/src/lib/model-data/data-stores/generic-data.test.ts, packages/fxa-settings/src/lib/model-data/data-stores/generic-data.ts, packages/fxa-settings/src/lib/model-data/data-stores/storage-data.ts, packages/fxa-settings/src/lib/model-data/data-stores/url-data.ts, packages/fxa-settings/src/lib/model-data/model-data-provider.ts, packages/fxa-settings/src/lib/model-data/model-data-store.spec.ts, packages/fxa-settings/src/lib/model-data/model-data-store.ts, packages/fxa-settings/src/models/integrations/base-integration.ts, packages/fxa-settings/src/models/integrations/channel-info.test.ts, packages/fxa-settings/src/models/integrations/client-info.test.ts, packages/fxa-settings/src/models/integrations/client-info.ts, packages/fxa-settings/src/models/integrations/oauth-integration.ts, packages/fxa-settings/src/models/integrations/signin-signup-info.ts, packages/fxa-settings/src/models/mocks.tsx, packages/fxa-settings/src/models/pages/signup/query-params.ts, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/mocks.tsx, yarn.lock
- We want to be able to use a wide array of data types in our classes not just strings
- Updates bind decorator to reflect on property metadata and return the right type
- Switches validation from IsBooleanString to IsBoolean
- Switches IsString to IsNumber for numeric values
- Adds reflect-metadata and corresponding transforms to settings
Closes: FXA-8199
=> task(settings): Coerce data types for fields with @bind

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
* Abbrev plans have their metadata updated via contentful. If we switch to using abbrev plans, we'll already have the contentful switching behavior.
* Calls for abbrev plan in email sending logic.
Closes FXA-8532
=> feat(auth): use abbrev plans for metadata

.circleci/config.yml, _scripts/redis.sh, packages/123done/server.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-profile-server/lib/config.js, packages/fxa-shared/db/config.ts, packages/fxa-shared/scripts/feature-flags.js, packages/fxa-shared/test/feature-flags/integration.js, packages/fxa-shared/test/scripts/feature-flags.js
- We are cleaning up things that are being flagged as passwords
- Removes the dev password, fxa123, from source
Closes: FXA-8444
In circleci, there was a password being applied and used, it turns this was just a POC to validate that a password could be used with our deployed code. For local development and running in CI a password isn't really necessary.
=> task(ci): Remove redis dev password from source

packages/functional-tests/tests/signin/relyingParties.spec.ts
- The SUMO tests were failing as the text `Sign in to Firefox Account`is no longer valid. Updated the selector so that the test passes.
- Updates the selector.
Closes: FXA-8595
=> test(functional): update selectors for the failing SUMO test

packages/fxa-payments-server/src/components/PaymentForm/index.tsx, packages/fxa-payments-server/src/routes/Checkout/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx, packages/fxa-react/styles/ctas.css
- aria-disabled=true doesn't disable the button, allowing the submit
button to be pressed multiple times. Under the following scenario
this would result in a duplicate subscription
- Existing customer with existing PayPal payment method
- Customer subscribes to a new product
- Customer clicks the subscribe button multiple times
- When aria-disabled=true, show the submit button that appears disabled
- Exit early when submit button is pressed when using PayPal as the
payment method
- Do not flash enabled button before navigating to success screen
Closes: #FXA-8590
Ideally this change would not be necessary, and the PaymentForm would continue to use `aria-disabled`. However due to the difference in functionality provided by `disabled` and `aria-disabled`, …
=> fix(payments): display disabled on aria-disabled

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
* We don't have the concept of productOrder in Contentful.
* Removes productOrder from email logic, since we do not have downgrade functionality at this time.
Closes FXA-8620
=> feat(auth): remove productOrder from email logic

packages/123done/README.md, packages/123done/config-local-untrusted.json, packages/123done/config-local.json, packages/123done/config-stage.json, packages/123done/config.js, packages/123done/config.json
- We want to define the client_secret via an environment value or secrets file
- Removes all the 123Done stage configs
- Loads the client_secret from file when running locally
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8373
I have also updated our Heroku, CircleCI configs to specify this value from the ENV. Note, we will still need to rotate the secrets for stage.
=> chore(deps): Specify 123Done client secret from a secrets.json file

_scripts/firestore.sh
- Firestore is flaky to start up
- Sets it back to latest. Hopefully this helps :crossed_fingers: 
IIRC, we hard set the image version because 'latest' was causing problems at one point. There's been many more versions released since then, however, so it's worth giving this another shot.
=> task(scripts): Return firestore back to latest image version

packages/fxa-content-server/app/styles/modules/_avatar.scss, packages/fxa-payments-server/src/routes/Subscriptions/index.tsx
- reverts changes previously made in #16020
- revises the size of the avatar on Subscription Management in mobile view
Closes: [FXA-8597](https://mozilla-hub.atlassian.net/browse/FXA-8597)
Before
After
[FXA-8597]: https://mozilla-hub.atlassian.net/browse/FXA-8597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(content): Avatar in Subscription Management - mobile view

libs/shared/contentful/src/lib/constants.ts, libs/shared/contentful/src/lib/contentful.client.spec.ts, libs/shared/contentful/src/lib/contentful.client.ts, libs/shared/contentful/src/lib/contentful.manager.ts, packages/db-migrations/contentful/1699394072129_fxa-8502.js
- adds help texts to fields in Contentful
Closes: [FXA-8502](https://mozilla-hub.atlassian.net/browse/FXA-8502)
Changes to the updated codegen files were included in #15957
[FXA-8502]: https://mozilla-hub.atlassian.net/browse/FXA-8502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(contentful): Added help texts to fields and updated default locale

packages/fxa-content-server/app/scripts/templates/pair/auth_wait_for_supp.mustache, packages/fxa-content-server/app/scripts/templates/pair/supp_wait_for_auth.mustache, packages/fxa-content-server/app/scripts/templates/push/completed.mustache, packages/fxa-content-server/app/scripts/templates/ready.mustache
* Some headings were not styled on backbone pages
* Add `card-header` and `card-subheader` styles where missing in `ready`, `supp_wait_for_auth`, `auth_wait_for_supp`, `completed` mustache templates
Closes: #FXA-8585
Before:
After:
=> fix(content): Add header and subheader styling where missing

packages/fxa-content-server/app/styles/modules/_avatar.scss, packages/fxa-payments-server/src/routes/Subscriptions/index.tsx
- updates the classname from `profile-image` to `avatar-image`
Before - /signin (mobile)
After - /signin (mobile)
Settings homepage 
Mobile
Desktop
Subscription Management
Mobile
Desktop
=> fix(content): Fix avatar on sign in page

libs/payments/capability/src/lib/capability.manager.spec.ts, libs/payments/capability/src/lib/capability.manager.ts, libs/payments/eligibility/src/lib/eligibility.manager.spec.ts, libs/shared/contentful/src/lib/contentful.manager.spec.ts, libs/shared/contentful/src/lib/factories.ts, libs/shared/contentful/src/lib/queries/eligibility-content-by-plan-ids/factories.ts, libs/shared/contentful/src/lib/queries/eligibility-content-by-plan-ids/index.ts, libs/shared/contentful/src/lib/queries/eligibility-content-by-plan-ids/util.spec.ts, libs/shared/contentful/src/lib/queries/services-with-capabilities/factories.ts, libs/shared/contentful/src/lib/queries/services-with-capabilities/index.ts, libs/shared/contentful/src/lib/queries/services-with-capabilities/util.spec.ts
- The main factories file was getting a bit out of hand and separating them keeps everything more organized.
- Moves eligibility and services factories into their own directories.
- Updates factories that include more than the single override parameter.
- Updates paths where applicable.
- Updates tests where applicable.
- Adds missing tests for `planIdsToClientCapabilities` in capability manager
Closes: FXA-8621
=> chore(factories): move factories into their respective shared-contentful directories

packages/functional-tests/tests/react-conversion/resetPassword.spec.ts, packages/fxa-content-server/app/scripts/models/reliers/oauth.js
- We detected that on stage signing into firefox monitor and then visiting the forgot reset password link would result in an error stating, 'Bad Request - Missing Oauth parameter: 0'
- React now holds all data-store data as strings and then coverts it to the proper type. Content, sever doesn't understand this however. As a result, react would write the fxa session to local storage as: `__fxa_session: "{"oauth":"{\"client_id\":\"REDACTED\",\"scope\":\"profile openid\",\"state\":\"REDACTED-REDACTED\"}"}"` Where as content server was expecting the oauth field to be an object, not a json encoded string. This would result in model validation failing, and an error being generated.
- Addresses the issue head on and makes sure that the resume object is converted to an object if its data type is …
=> bug(content/settings): Fix issue where redirect to react app would fail for complete_reset_password

packages/fxa-settings/src/lib/model-data/data-stores/storage-data.test.ts, packages/fxa-settings/src/lib/model-data/data-stores/storage-data.ts
- We could run into type safety issues in the storage-data.ts data store implementation.
- There were scenarios where content server would write complex objects to local storage
- Ensures that the RawData type, which is used as the input output format for all model data, is upheld.
- Checks that data being accessed from local storage is returned as a string value, so that it can later be coerced into the expected type.
This is related to https://github.com/mozilla/fxa/pull/16066. It's a similar issue, but the reverse scenario. In this case `fxa-settings` needs to be able handle legacy values created by the content server. If you want to test …
=> bug(fxa-settings): Protect against legacy state in local storage

packages/fxa-settings/src/components/Settings/AppLayout/index.stories.tsx, packages/fxa-settings/src/components/Settings/BentoMenu/en.ftl, packages/fxa-settings/src/components/Settings/BentoMenu/index.test.tsx, packages/fxa-settings/src/components/Settings/BentoMenu/index.tsx, packages/fxa-settings/src/components/Settings/HeaderLockup/index.tsx, packages/fxa-settings/src/components/Settings/Nav/index.tsx
* With the rename to Mozilla accounts, we are removing the Firefox logo from prominent position
* Remove the Firefox logo from the bento menu header
* Update copy in the bento menu and add new l1on
* Update styling
* Fixes a styling issue with the nav bar, where the bar partially overlapped the page header in mobile view
Closes: #FXA-8594
Bento Menu - Desktop (before):
Bento Menu - Desktop (after):
Bento Menu - Mobile (before):
Bento Menu - Mobile (after):
Bento Menu Tooltip (before):
Bento Menu Tooltip (after):
Nav Menu - Mobile (before):
Nav Menu - Mobile (after):
=> feat(settings): Update bento menu

.gitignore, libs/payments/eligibility/src/index.ts, libs/payments/eligibility/src/lib/eligibility.manager.spec.ts, libs/payments/eligibility/src/lib/eligibility.manager.ts, libs/payments/eligibility/src/lib/eligibility.types.ts, libs/payments/eligibility/src/lib/utils.ts, packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/test/local/payments/capability.js
Because:
* We want to use the new eligibilitymanager in the capability service and compare its results to the existing check, reporting any differences in the eligibility comparison.
This commit:
* Adds the eligibility manager to the capability service.
* Adds a wrapper to the results of the elgibility call to verify it matches the existing comparison, and report to Sentry if it doesn't.
Closes FXA-8273
=> feat: add eligibility manager to capability service

packages/fxa-admin-server/package.json, packages/fxa-shared/package.json
- The script would not run with `nx email-bounce admin-server`
- Fixes the path to the script.
- Applies the necessary changes to `package.json` to expose `fxa-shared/test/db/models/auth/helper.ts`
=> bug(shared,admin-sever): Fix broken email-bounce script

packages/fxa-auth-server/package.json, yarn.lock
Because:
* We stopped using jwt-decode and forgot to remove the dependency.
This commit:
* Removes the unused jwt-decode dependency.
=> chore: remove unused jwt-decode dep

packages/fxa-content-server/server/lib/beta-settings.js, packages/fxa-settings/src/lib/auth-errors/en.ftl, packages/fxa-settings/src/lib/config.ts, packages/fxa-settings/src/lib/hooks/useWebRedirect/index.tsx, packages/fxa-settings/src/models/integrations/web-integration.ts, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.test.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/interfaces.ts, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/mocks.tsx
Because:
* Users that click the "Sign in" link from a subscription and choose to create a new account were not being redirected back to that subscription page on account verification
This commit:
* Makes the existing REDIRECT_CHECK_ALLOW_LIST config in fxa-content-server available in fxa-settings
* Creates a hook for web integration integration.data.redirectTo validity (OAuth integration redirects are handled differently)
* Accounts for this condition on ConfirmSignupCode submission
fixes FXA-8468
---
Go to 123done with a fresh stack (or hit `/clear`) and pick a subscription. Click "Sign in", add the force React experiment params. Enter an email to see React signup. Sign up, verify the account, and see the redirect back to the SubPlat page you were on.
This SubPlat link initially hits …
=> fix(react): Allow redirect back to SubPlat after Signup

libs/payments/legacy/.eslintrc.json, libs/payments/legacy/README.md, libs/payments/legacy/jest.config.ts, libs/payments/legacy/package.json, libs/payments/legacy/project.json, libs/payments/legacy/src/index.ts, libs/payments/legacy/src/lib/factories.ts, libs/payments/legacy/src/lib/plan-mapper.util.spec.ts, libs/payments/legacy/src/lib/plan-mapper.util.ts, libs/payments/legacy/src/lib/stripe-mapper.service.spec.ts, libs/payments/legacy/src/lib/stripe-mapper.service.ts, libs/payments/legacy/src/lib/types.ts, libs/payments/legacy/tsconfig.json, libs/payments/legacy/tsconfig.lib.json, libs/payments/legacy/tsconfig.spec.json, libs/payments/stripe/src/index.ts, libs/payments/stripe/src/lib/factories/plan.factory.ts, libs/shared/contentful/src/index.ts, libs/shared/contentful/src/lib/queries/purchase-with-details-offering-content/index.ts, libs/shared/contentful/src/lib/queries/purchase-with-details-offering-content/types.ts, packages/fxa-admin-server/src/subscriptions/stripe.service.ts, packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js, packages/fxa-shared/payments/stripe.ts, tsconfig.base.json
- The GET /plans API is used in multiple places to retrieve the relying party configuration data currently configured in Stripe.metadata
- Updates the logic used by the GET /plans API to retrieve the relying party configuration data from Contentful, with Stripe.metadata as a fallback
- Reports a Sentry error when the Contentful configuration data does not match the Stripe.metadata
Closes: #FXA-8538
=> fix(auth): add contentful to plans api

packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/lib/payments/utils.ts, packages/fxa-auth-server/test/local/payments/capability.js, packages/fxa-auth-server/test/local/payments/utils.js, packages/fxa-auth-server/test/mocks.js
- We want to use the new capability manager in the capability service and compare its results to the existing check, reporting any differences in the comparison.
- Updates `planIdsToClientCapabilities` in legacy capability service to compare data returned from Contentful and Stripe.
- If results are same, returns from Contentful, otherwise Stripe, with appropriate error messaging to Sentry.
- Adds tests to return from Stripe in the event that the results did not match and successfully logs error to Sentry.
- Adds a util function to sort data for comparison.
Closes: FXA-8274
=> feat(auth): add planIdsToClientCapabilities to legacy capability service

packages/fxa-shared/sentry/pii-filter-actions.ts, packages/fxa-shared/test/sentry/pii-filter-actions.ts
Because:
* It can be hard to debug error in Sentry
This commit:
* Removes the 16 char token filter
Fix FXA-8675
=> feat(sentry): Remove 16 char sentry filter

packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx
- Adjacent text explains the meaning, making the additional text unnecessary.
- Removes alt tag copy.
Closes: FXA-3047
=> fix(a11y): remove alt text for decorative image

packages/functional-tests/pages/login.ts, packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache, packages/fxa-content-server/app/scripts/views/sign_up_password.js, packages/fxa-content-server/app/tests/spec/views/sign_up_password.js
- We want to give users the option to use a third party account when signing up
- Adds third party auth options in the signup screen
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8293
Note this is only for the backbone version. I tried adding for React we needed to do some extra work integrating third party auth options.
=> fix(auth): Show third party options when signing up for non-sync

packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx
- Adjacent text explains the meaning, making the additional text unnecessary.
- Removes alt tag copy in two additional places.
Closes: FXA-3047
Follow up to #16098 and https://github.com/mozilla/fxa/pull/16098#discussion_r1398339749 .
=> chore(payments): remove additional alt text for decorative images

libs/shared/contentful/src/lib/contentful.client.spec.ts, libs/shared/contentful/src/lib/contentful.client.ts, libs/shared/contentful/src/lib/contentful.error.ts, libs/shared/contentful/src/lib/contentful.manager.spec.ts, libs/shared/contentful/src/lib/contentful.manager.ts, package.json, yarn.lock
- We've had numerous problems with Apollo Client server-side (it's intended as a frontend client, mostly for React).
- Replaces Apollo Client with graphql-request for server-to-server graphql requests in the Contentful lib.
Closes: FXA-8645
=> fix(contentful): switch to graphql-request for contentful client

packages/functional-tests/tests/oauth/totp.spec.ts, packages/functional-tests/tests/settings/totp.spec.ts, packages/fxa-settings/src/components/Settings/AlertBar/index.tsx, packages/fxa-settings/src/components/Settings/LinkedAccounts/LinkedAccount.tsx, packages/fxa-settings/src/components/Settings/LinkedAccounts/index.test.tsx, packages/fxa-settings/src/components/Settings/LinkedAccounts/index.tsx, packages/fxa-settings/src/components/Settings/LinkedAccounts/mocks.ts, packages/fxa-settings/src/components/Settings/PageCreatePassword/index.test.tsx, packages/fxa-settings/src/components/Settings/PageCreatePassword/index.tsx, packages/fxa-settings/src/lib/types.ts, packages/fxa-settings/src/models/Account.ts
Because:
* We want to take users back to actions they attempted to perform. If a user wants to unlink their third party account but do not have a password set, we should not only link them to the create password page, but on successful password creation we should also take them back to Settings with the third party auth modal automatically open
This commit:
* Adds router/location state containing the third party provider ID to the create password page if a user opts to "Set password" from the initial modal
* Accounts for this new state in create password by sending it back to Settings only if the password is successfully created
* Checks for this location state in the LinkedAccount component to automatically open it
* Removes the hard navigate from LinkedAccount
* Adds tests and refactors …
=> feat(settings): Automatically show third party auth modal from create password

packages/fxa-auth-server/scripts/update-subscriptions-to-new-plan.ts, packages/fxa-auth-server/scripts/update-subscriptions-to-new-plan/update-subscriptions-to-new-plan.ts, packages/fxa-auth-server/test/scripts/update-subscriptions-to-new-plan.ts
* We need a way to migrate users to SP3 plan scheme.
* Adds a script that facilitates the migration of users from one plan to another given a mapping of plan IDs.
Closes FXA-8662
=> feat(auth): update subscriptions to new plan script

packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/lib/routes/subscriptions/mozilla.ts, packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/test/local/payments/capability.js, packages/fxa-auth-server/test/local/routes/subscriptions/mozilla.js, packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js, packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js, packages/fxa-payments-server/src/lib/mock-data.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx, packages/fxa-payments-server/src/routes/Product/index.test.tsx, packages/fxa-payments-server/src/routes/Product/index.tsx, packages/fxa-payments-server/src/store/types.tsx, packages/fxa-shared/subscriptions/types.ts
- we want to move logic from frontend and utilize the new endpoint
Closes: [FXA-6166](https://mozilla-hub.atlassian.net/browse/FXA-6166)
[FXA-6166]: https://mozilla-hub.atlassian.net/browse/FXA-6166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(payments): Utilize new plan-eligibility endpoint

packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/container.test.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/container.tsx
- We want to add tests to ConfirmSignupCode
- Adds tests to the ConfirmSignupCode container
Closes: FXA-8303
- [x If applicable, I have modified or added tests which pass locally.
This is using the patterns set forth in FXA-8286.
=> task(settings): Add container tests for ConfirmSignupCode

packages/fxa-auth-server/test/oauth/api.js, packages/fxa-auth-server/test/remote/account_create_tests.js, packages/fxa-auth-server/test/remote/account_login_tests.js, packages/fxa-auth-server/test/remote/base_path_tests.js, packages/fxa-auth-server/test/remote/email_validity_tests.js, packages/fxa-auth-server/test/remote/misc_tests.js, packages/fxa-auth-server/test/remote/sign_key_tests.js, packages/fxa-geodb/package.json
- We were seeing integration tests failing in unit-test suites
- This indicates that our we incorrectly targeted tests.
- Makes sure that any test suite requiring a server to be started are marked as integration.
- Closes one server that may have been left open.
Closes: FXA-8663
Note this doesn't necessarily solve the related issue, FXA-8664, where we get random port conflicts. There's a small chance that closing a test server that is created mid test suite will help (see oauth/api.js) , but I don't think it's a silver bullet.
=> bug(auth): Fix targeting of integration tests

packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-server/docs/swagger/recovery-key-api.ts, packages/fxa-auth-server/lib/routes/recovery-key.js, packages/fxa-auth-server/test/local/routes/recovery-keys.js, packages/fxa-settings/src/models/Account.ts
* Rate limiting is not working as expected on this currently unused route
* Disable (by commenting out) the GET recoveryKey/hint route and associated tests
* Add comments about intended rate limiting on this route
Closes: #FXA-8722
See JIRA details for issue this is addressing. I'll be filing a follow up ticket for UX to review how this hint is displayed to users.
=> fix(auth): Disable GET recoveryKey/hint route

packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/app/tests/mocks/view.js, packages/fxa-content-server/app/tests/spec/lib/router.js, packages/fxa-content-server/server/lib/routes/react-app/add-routes.js, packages/fxa-content-server/server/lib/routes/react-app/index.js, packages/fxa-content-server/server/lib/routes/react-app/types.ts
* Changing `showReactApp` query param to false in the URL was resulting in an infinite loop preventing rendering
* Always render React app for routes fully turned on in prod and disregard `showReactApp` param in request
* Update tests
Closes: #FXA-8666
=> fix(content): Prevent infinite loop when showReactApp set to false

packages/fxa-admin-server/src/subscriptions/stripe.service.ts, packages/fxa-auth-server/lib/payments/processing-tasks-setup.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/server.js, packages/fxa-shared/payments/stripe.ts
- It is difficult to identify when a Stripe API key is no longer valid
- Adds an error messsage to service logs on Stripe initialization
Closes: #FXA-8552
Error on GraphQL response
Console log error
=> feat(auth,admin): add stripe key error on startup

packages/fxa-auth-server/lib/payments/stripe.ts
- Only get ContentfulManager from container if it is set
- Checks for ContentfulManager in container before getting
Closes: #FXA-8762
=> fix(auth): skip contentful if manager not set

packages/functional-tests/tests/react-conversion/cannotCreateAccount.spec.ts, packages/functional-tests/tests/react-conversion/legal.spec.ts, packages/functional-tests/tests/react-conversion/oauthResetPassword.spec.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts
- Tests are skipped based on feature flag value, does not need a skip based on project
- Removes the test skip based on production environment
Closes: #FXA-8543
Tested locally that react signup tests are skipped if showReactApp flag for signUpRoutes is set to false
=> fix(tests): Re-enable React signup tests in production

package.json, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/package.json, packages/fxa-event-broker/package.json, packages/fxa-graphql-api/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json, yarn.lock
Because:
* We want to move shared deps to the root package.json
This commit:
* Removes packages from several package.jsons as they are already present in root.json
* Moves @apollo/client to root package.json
---
follow up to #16130
Happy to make any other changes if I missed one, I assume we only want deps shared by more than one package to go in the root.
=> chore(all): Move gql dependencies to root package.json

packages/functional-tests/tests/subscription-tests/subscription.spec.ts
- we skipped this test as the Stripe test card caused the test to stall since the postal code field was not activated
- re-instates test upon Stripe update
Closes: FXA-8717
=> test(functional): Re-enable test upon Stripe update of test card

packages/fxa-settings/src/models/hooks.ts
Because:
- an oauth client id needs to be a 16 digit hex
This commit:
- skips the graphql-api query to fetch an oauth client's info that will result in an HTTP 400
=> fix(settings): skip oauth client info fetch when id is invalid

packages/fxa-payments-server/src/components/PaymentForm/index.stories.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.tsx, packages/fxa-payments-server/src/routes/Checkout/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx, packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
- The `PaymentCheckbox` used to be part of the `PaymentForm` component. However, wherever the `PaymentForm` is used its `PaymentCheckbox` is currently hidden and not used. This seems to be legacy.
- Removes `PaymentCheckbox` from `PaymentForm` and all applicable tests and stories.
Closes FXA-6303
=> chore(payments): remove legacy code

packages/fxa-settings/src/lib/gql.ts
Because:
* Users could login with 2FA enabled and then at the TOTP screen, try to reset their PW and in this state they would see an endless spinner
This commit:
* Sets the local isSignedIn state to 'false' for this case, allowing the page to render
fixes FXA-8792
---
Kind of a bandaid until we work on the related "Must verify" / session verify tickets in the architecture epic, but this seems to work for me.
=> fix(react): Set isSignedIn=false for 'Must verify' state resulting in spinner

packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx
- Success message was not displayed on connect_another_device when arriving from React
- Pass required search param to enable message
Closes: #FXA-8669
Follow up filed for failing Playwright sync test: https://mozilla-hub.atlassian.net/browse/FXA-8763
=> fix(signup): Enable sync success message from React

packages/fxa-payments-server/src/components/Header/index.tsx
- Mozilla `m` logo should be full logo on Set up your subscription page.
- Replaces Mozilla `m` logo with full logo on Set up your subscription page.
Closes FXA-8803
=> fix(payments): update Mozilla logo on Set up your subscription page

packages/functional-tests/tests/react-conversion/resetPassword.spec.ts
* The confirm reset password page redirects to email-first even if URL is set to /signin because the account is not in local storage
* The test was failing in stage smoke test because it was waiting for /signin to load
* Update polling on ConfirmResetPassword to navigate to email-first page if reset password is completed in another tab (instead of sign in)
* Update test to expect navigation to email-first
Closes: #FXA-8801
=> fix(functional-tests): Update react reset password playwright test to reflect background nav

packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts, packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
- Sentry expects an error object
- Assigns payload to existing error object before passing to Sentry
Closes: #FXA-8650
=> fix(auth): throw error on refused stripe credit note

packages/fxa-auth-server/lib/oauth/db/index.js, packages/fxa-auth-server/lib/oauth/db/mysql/index.js, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/scripts/must-reset/index.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/oauth/db/index.js
Because:
- we should delete more tokens when resetting an account
This commit:
- deletes all oauth tokens when resetting an account
- removes a couple unnecessary `resetAccountTokens` calls
=> chore(reset): delete more tokens when resetting account

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/customs.js, packages/fxa-auth-server/lib/http-agent.ts, packages/fxa-auth-server/lib/profile/client.js, packages/fxa-auth-server/package.json, yarn.lock
- We also need to set specify the keep alive value for axios
- Adds the `keepalive` library and uses the defaults from their example
- Removes unused auth-server poolee config
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8640
=> fxa(deps): Add keepalive library for axios

packages/fxa-settings/src/components/Settings/FlowRecoveryKeyDownload/index.test.tsx, packages/fxa-settings/src/components/Settings/FlowRecoveryKeyDownload/index.tsx
Because:
- we don't want to load the rather large react-pdf dependency whenever a user lands in Settings
This commit:
- loads react-pdf lazily with React
=> chore(settings): load react-pdf lazily

packages/fxa-settings/src/components/FormPasswordWithBalloons/index.tsx, packages/fxa-settings/src/pages/Signup/index.test.tsx
- We could get in a state where the Create Account button was not enabled even if passwords matched
- This would happen if the first password was updated to match the second (i.e. the repeat password field)
- Checks if the form is invalid and then triggers on the related input to clear any potential error state.
- Adds test coverage for these checks.
Closes: FXA-8486
=> bug(settings): Make 'Create Account' button work if passwords match and are valid

libs/shared/contentful/src/lib/contentful.manager.ts, libs/shared/contentful/src/lib/queries/purchase-with-details-offering-content/util.spec.ts, libs/shared/contentful/src/lib/queries/purchase-with-details-offering-content/util.ts
- we saw errors in Sentry after stage deploy regarding query size
- `purchaseWithDetailsOfferingContentQuery`
- `The maximum allowed size for a query is 8192 bytes but it was 8656 bytes`
- "code":"QUERY_TOO_BIG"
- splits out stripePlanIds to reduce query size and calls Contentful multiple times instead
Closes: FXA-8721
=> fix(shared-contentful): Fix Contentful errors regarding query size

packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/fxa-content-server/server/lib/beta-settings.js, packages/fxa-settings/src/lib/channels/firefox.ts, packages/fxa-settings/src/lib/config.ts, packages/fxa-settings/src/lib/crypto/scoped-keys.ts, packages/fxa-settings/src/lib/integrations/integration-factory.test.ts, packages/fxa-settings/src/lib/integrations/integration-factory.ts, packages/fxa-settings/src/lib/oauth/hooks.tsx, packages/fxa-settings/src/models/integrations/oauth-integration.ts, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
Because:
* We want to fix all Signup React bugs before rolling out to prod
This commit:
* Fixes AMO signup where client_id, scope, state, and access type are given params - we should only hit the 'account/keys' endpoint if integration.wantsKeys() is true
* Passes missing scopedKeysValidation config to React, as 'validation' was undefined when checking integration.wantsKeys() and sets scopedKeysEnabled to 'true' by default to match content-server's config
* Adds an event listener for fxaLogin in Playwright that resolves when a response is received from the browser and enables test, tweaks a couple of others
* Includes Sync mobile fixes:
1) Tweaks integration.isSync() to account for 'oldsync' scope to ensure sync mobile is considered 'sync'
2) passes back the correct state and redirect from …
=> fix(react): Fix various React signup OAuth/Sync bugs

packages/functional-tests/tests/react-conversion/recoveryKey.spec.ts, packages/fxa-settings/src/models/Account.ts
- The user was prompted to login again after resetting their password with a recovery key and clicking generate new key
- Sets the `isSignedIn` apollo client cache value to true, this value is what lets the settings app know the user is logged in
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8800
=> fix(bug): Set `isSignedIn` after reset password with recovery key

packages/functional-tests/pages/signupReact.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/app/scripts/views/index.js, packages/fxa-content-server/app/scripts/views/sign_in_bounced.js, packages/fxa-graphql-api/src/gql/account.resolver.ts, packages/fxa-graphql-api/src/gql/dto/payload/email-bounce.ts, packages/fxa-react/components/LoadingSpinner/index.tsx, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/Settings/index.tsx, packages/fxa-settings/src/pages/Pair/Supp/index.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx, packages/fxa-settings/src/pages/Signin/CompleteSignin/index.tsx, packages/fxa-settings/src/pages/Signin/SigninBounced/index.tsx, packages/fxa-settings/src/pages/Signup/Confirm/index.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/container.test.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/container.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/gql.ts, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/interfaces.ts, packages/fxa-settings/src/pages/Signup/container.tsx, packages/fxa-settings/src/pages/Signup/index.test.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
* We are converting the backbone signup flow to react and want to match behaviour for email bounces
* We want to redirect from confirm_signup_code if the email bounced
* Add GQL query to poll the db for hard bounces and redirect if a hard bounce was registered for the email
* Create an option for fullPage styling to the LoadingSpinner component
Closes: #FXA-8306, FXA-8305
This draft PR does not include a playwright test for email bounce on React Signup. If deemed necessary, this work will be filled in a separate ticket. (The skeleton test is currently skipped)
To test locally: 
1. Navigate to [localhost with react …
=> feat(react): Handle email bounces in react signup

libs/shared/contentful/src/lib/contentful.manager.spec.ts, libs/shared/contentful/src/lib/contentful.manager.ts, libs/shared/contentful/src/lib/queries/capability-service-by-plan-ids/factories.ts
- Update ContentfulManager method to account for zero results returned by Contentful query.
- Updates while loop condition
Closes: #FXA-8865
=> fix(contentful): add support for zero results

packages/fxa-content-server/app/scripts/templates/force_auth.mustache, packages/fxa-content-server/app/scripts/templates/index.mustache, packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache, packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache, packages/fxa-content-server/app/tests/spec/views/sign_in_password.js, packages/fxa-settings/src/components/TermsPrivacyAgreement/en.ftl, packages/fxa-settings/src/components/TermsPrivacyAgreement/index.test.tsx, packages/fxa-settings/src/components/TermsPrivacyAgreement/index.tsx
* We are change Monitor terms from Firefox Monitor links to Mozilla Subscription Services
* Updates ToS and Privacy notice links for Monitor on backbone and react pages
Closes: #FXA-7979
Before (React - Storybook)
After (Backbone)
After (React - Storybook)
=> feat(terms): Updated Monitor Terms for Premium launch

packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-server/lib/routes/linked-accounts.ts, packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/server/lib/routes/react-app/index.js, packages/fxa-settings/src/components/ThirdPartyAuth/index.tsx, packages/fxa-settings/src/models/Account.ts, packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.tsx, packages/fxa-settings/src/pages/Signup/index.test.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
* We want to match parity with backbone Signup and allow users to sign up with third party authentication when enrolled in the React Signup experiment
* Adds the ThirdPartyAuth component to the React Signup form
* Builds on the initial scaffolding for the React ThirdPartyAuthCallback, but does not enable this React route to complete sign in after third party auth. The final steps are still handled by backbone until FXA-8834
Closes: #FXA-8761
React signup form with ThirdPartyAuth options:
With this PR, it is expected that users will be able to:
- Sign up and sign in with Third Party Auth options whether or not they are enrolled in the React Signup experiment
- Third Party Auth options remain unavailable for both backbone and react if the signup is for …
=> feat(react): Enable ThirdPartyAuth in React Signup

packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/test/local/routes/account.js
Because:
- we want to have something to handle account deletes outside of a route handler
This commit:
- adds the AccountDeleteManager class (without no functionality yet)
- moves some dependency initialization
=> feat(accounts): create a AccountDeleteManager class

packages/fxa-settings/src/components/Settings/PageDisplayName/index.test.tsx, packages/fxa-settings/src/components/Settings/PageDisplayName/index.tsx, packages/fxa-settings/src/index.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPassword/index.tsx
* We were seeing <Localized /> component was not properly wrapped in a <LocalizationProvider /> errors in Sentry
* Locally, replicated the error in ResetPassword and CompleteResetPassword pages when errors occurred with callback refs
* The AppErrorDialog compoment was outside the LocalizationProvider, so this error could occur when a general application error is encountered
* Error tooltip on the PageDisplayName was showing unlocalized messages that weren't intended to be user facing
* Resolves errors with callback refs in CompleteResetPassword and ResetPassword
* Moves the LocalizationProvider outside the AppErrorBoundary to provide access to localization for the AppErrorDialog component
* Removes the PageDisplayName tooltip and replace with a more user-appropriate error message
Closes: …
=> fix(settings): Localized components not wrapped in LocalizationProvider

libs/payments/legacy/src/lib/stripe-mapper.service.spec.ts, libs/payments/legacy/src/lib/stripe-mapper.service.ts, packages/fxa-shared/payments/stripe.ts
- The Contentful content is fetched for only one locale, however the comparison logic was comparing it against all plan's for all "locales" configured for a product.
- Updates the error reporting to only include 1 error message per ID. Typically this will be a Stripe product ID.
- Adds the request acceptLanguage to Sentry context, so that it is easier to identify which language the comparison was done for.
Closes: #FXA-8856
=> fix(auth): contentful comparison per product

packages/fxa-payments-server/src/lib/reactga-event.ts
- product price and value were both reported in cents (e.g., $8388 for the bundle when the annual subscription is $83.88)
- adjusts price and value
Closes: FXA-8857
It has been observed that price is reported 1000x in DebugView - reports show the correct price.
=> fix(payments): Adjust price and value for GA4 reports

packages/functional-tests/tests/react-conversion/signup.spec.ts
Because:
* We want a functional test for this path which was commented out
This commit:
* Enables the last bit of this test, as it is passing
closes FXA-8795
--
This is passing for me locally, and I can go through the flow locally as well as in staging.
To test this, go to 123done and click a subscription product, then click "Sign in". Append the force experiment React params, and go through the flow. [Here's](http://localhost:3030/?device_id=aec7913a470a4fc9870b5c451a7cd334&flow_begin_time=1704239315404&flow_id=fda9de5b4f3fd8c55272f19d22423d7a9cc8fb2a282b17077a8bd3a1f2f06238&plan=price_1KbomlBVqmGyQTMaa0Tq7UaW&signin=yes&redirect_to=http%3A%2F%2Flocalhost%3A3031%2Fproducts%2Fprod_GqM9ToKK62qjkK%3Fdevice_id%3Daec7913a470a4fc9870b5c451a7cd334%26flow_begin_time%3D1704239315404%26flow_id%3Dfd …
=> chore(test): Enable functional test for React Signup redirect to SubPlat

packages/fxa-shared/nestjs/sentry/reporting.ts, packages/fxa-shared/nestjs/sentry/sentry.plugin.ts
- These aren't actually unexpected errors.
- Auth server will return http errors intentionally
- Invalid or missing session tokens on requests will result in intentional HTTP 401 errors.
- Won't report these kinds of errors to sentry.
Closes: FXA-8817
Note that before the graphql upgrade we didn't report these. The logic surrounding originalError.status just got lost in the shuffle.
=> bug(shared): Don't report gql errors that are due to http errors.

packages/functional-tests/pages/relier.ts, packages/functional-tests/tests/signin/relyingParties.spec.ts
* Monitor and Sumo sites had been updated, which caused our functional tests to fail
* Disconnect RP test was intermittently timing out for stage and production
* Update relying party tests to reflect updated RP user flows and UI
* Upgrade locators to use accessible roles
* Add timeout to relier email first navigation
Closes: #FXA-8446, FXA-8816
- Tests for relying parties are passing locally for prod environment (`yarn playwright test` in `packages/functional-tests`)
- Filed FXA-8858 for the prod login with pocket test that will require more extensive fixes - it was disabled in 2022 with no issue filed
=> fix(functional-tests): Fix relying party smoke tests

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/routes/auth-schemes/google-oidc.ts, packages/fxa-auth-server/lib/routes/cloud-tasks.ts, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/lib/server.js, packages/fxa-auth-server/test/lib/server.js, packages/fxa-auth-server/test/local/routes/auth-schemes/google-oidc.js, packages/fxa-auth-server/test/local/server.js
Because:
- we want to use GCP Cloud Tasks to delete accounts
This commit:
- adds few configuration options
- adds a new route as task handler (currently no-op)
- authenticates new route via ID token
=> feat(cloud): scaffold cloud tasks configs and route

packages/functional-tests/pages/layout.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts
Because:
* These tests are not reliably passing in staging
This commit:
* Waits until page load before checking for user's avatar on SubPlat
* Increases the timeout for checking for a web channel message response since confirming an account and sending the message can take longer than 2s
fixes FXA-8877
fixes FXA-8879
=> fix(functional-tests): Fix flaky React Signup tests

packages/fxa-content-server/app/styles/modules/_avatar.scss
- the default avatar was off-center
- centers the default avatar
Closes: FXA-8206
BEFORE
AFTER
Mobile
Tablet
Desktop
=> fix(content): Center default avatar

packages/fxa-settings/src/lib/channels/firefox.ts
Because:
* There is an intermittent "Invalid token" error on the confirm signup screen when going through Sync desktop
This commit:
* Removes the playwright only ('automatedBrowser' query param bit) check for resolving once a web channel message has been received
fixes FXA-8910
---
This should fix the issue we talked about in Slack / at triage. I've tested this several times locally and it works as expected for me every single time, though I don't believe I ever reproduced this locally so take that with a grain of salt. I'm still pretty certain this is the fix though.
=> fix(react): Wait for browser to respond to fxaLogin before navigation

packages/functional-tests/pages/login.ts, packages/fxa-content-server/app/scripts/models/sync-engines.js, packages/fxa-settings/src/components/ChooseWhatToSync/en.ftl, packages/fxa-settings/src/components/ChooseWhatToSync/sync-engines.ts
* The wording in CWTS was replaced elsewhere in Firefox
* Replace instances of 'credit cards' in CWTS options with 'Payment Methods'
Closes: #FXA-8837
=> feat(sync): Update 'credit cards' to 'payment methods'

packages/functional-tests/pages/signupReact.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/fxa-settings/src/lib/oauth/hooks.tsx, packages/fxa-settings/src/models/integrations/oauth-integration.ts
Because:
* AMO is erroring out in React signup due to missing a redirect URI, but also does not provide us a redirect URI in its query params
This commit:
* Falls back to integration.clientInfo.redirectUri if redirectUri is not given via query params
* Adjusts OAuthErrorInvalidRedirectUri - we weren't checking redirectUri for sync mobile because it didn't give us a redirect_uri in query params, but we should be checking that clientInfo.redirectUri exists
* Adds playwright test for missing redirect_uri
fixes FXA-8743
---
EDIT: below is relevant but semi-outdated, please [see my comment](https://github.com/mozilla/fxa/pull/16234#discussion_r1446500203) instead
--
It looks like `redirect_uri` is not a required parameter. For the Sync OAuth flow we were already not checking for it, but AMO's …
=> fix(react): Fall back to clientInfo.redirectUri when redirectUri is not provided via query params

packages/fxa-content-server/app/scripts/lib/auth-errors.js, packages/fxa-content-server/app/scripts/lib/vat.js, packages/fxa-content-server/app/scripts/views/index.js, packages/fxa-content-server/app/tests/spec/views/index.js, packages/fxa-settings/src/components/Settings/PageSecondaryEmailAdd/en.ftl, packages/fxa-settings/src/components/Settings/PageSecondaryEmailAdd/index.test.tsx, packages/fxa-settings/src/components/Settings/PageSecondaryEmailAdd/index.tsx, packages/fxa-shared/email/helpers.ts
- We don't want to create new accounts with Relay mask
- Disables the ability to create new accounts
Closes: https://mozilla-hub.atlassian.net/browse/FXA-5229
Ran into some issues trying to get my new laptop working with Settings, so couldn't fully test that it is disabled in secondary emails, added code in email helper so I can do a follow up more easily
=> Reject Relay email masks on signup

packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/payments/stripe-firestore.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe-firestore.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-shared/payments/stripe-firestore.ts
- Need to delete firestore customer document and all related subcollections.
- Uses firestore.recursiveDelete to delete customer document and all subcollections
Closes: #FXA-8839
=> feat(auth): add firestore record delete

packages/fxa-shared/nestjs/sentry/reporting.ts, packages/fxa-shared/nestjs/sentry/sentry.plugin.ts
- There were some unused imports that didn't get cleaned up prior to merging [FXA-8817.2](https://github.com/mozilla/fxa/tree/FXA-8817.2)
- Cleans up unused imports
=> task(shared): Remove unused imports

packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/routes/cloud-tasks.ts, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/package.json, packages/fxa-auth-server/test/lib/server.js, packages/fxa-auth-server/test/local/account-delete.js, packages/fxa-auth-server/test/local/ip_profiling.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/mocks.js, packages/fxa-auth-server/test/scripts/verification-reminders.js, yarn.lock
Because:
- we want to add a delete account task into the Clound Task queue
This commit:
- uses @google-cloud/tasks to create a delete account task on a Cloud Task queue
=> feat(cloud-tasks): add method to enqueue a delete account cloud task

packages/fxa-event-broker/src/firestore/firestore.service.spec.ts, packages/fxa-event-broker/src/firestore/firestore.service.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.spec.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.ts
- We also want to delete the user record in firebase when the delete account event is sent
- Refactors code to delete it
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8842
The original issue mentions deleting only login records, but since the user is being deleted I ended up removing their entire record. @bbangert is this the correct assumption?
=> feat(delete): Delete user firestore record on delete event

packages/functional-tests/lib/query-params.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/fxa-settings/src/lib/channels/firefox.ts
Because:
* We want to transfer relevant tests to React signup
This commit:
* Adds a couple missing web channel message checks in our React signup tests, ports content-server's saveEventForTests
* Changes the desktop v3 UA to our likely min supported version, tests for web channel events sent by the browser instead of sending a custom list since we respond to the first event received, which the browser sends automatically
* Adjusts oauth web channel to waitForURL before checking for the web channel event
fixes FXA-8854
---
Note the ticket calls out [this test file](https://github.com/mozilla/fxa/blob/main/packages/functional-tests/tests/syncV3/signUpWithCWTS.spec.ts), but this is actually the CWTS page seen _after_ Signup, which we only display in FF 58 and below. We previously said we …
=> chore(react): Port over some missing pieces of signup functional tests

packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx
- Reconfirm dialog only checked for existence of credit card and not `payment_provider`.
- Checks for existence of PayPal as `payment_provider` and provides alternative copy if true.
Closes FXA-8804
=> fix(payments): update resubscribe dialog to use PayPal when present

packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/payments/stripe-firestore.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe-firestore.js, packages/fxa-auth-server/test/local/payments/stripe.js
- removeFirestoreCustomer should reject with error so that it can be
handled by consumers.
- Adds StripeFirestoreError and StripeFirestoreMultiError to
stripe-firestore
- removeFirestoreCustomer rejects with error
Closes: #FXA-8839
=> feat(auth): update remove customer error handling

packages/functional-tests/lib/query-params.ts, packages/functional-tests/tests/settings/fxaStatus.spec.ts, packages/fxa-content-server/server/config/local.json-dist, packages/fxa-content-server/server/lib/beta-settings.js, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/server/lib/routes/get-index.js, packages/fxa-settings/src/components/App/index.test.tsx, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/lib/channels/firefox.ts, packages/fxa-settings/src/lib/config.ts, packages/fxa-settings/src/lib/storage-utils.ts, packages/fxa-settings/src/models/integrations/web-integration.ts, packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
Because:
* Users are asked to sign in again if they sign in using the pairing flow and try to access Settings through the browser
This commit:
* In Settings, sends an fxa_status web channel message to request the user's data from the browser in Settings if web+sync integration
* Adds a functional test for Settings fxa_status
* Pulls out storeAccountData into its own function, related App cleanup and firefox.ts type improvements
* Adds a feature flag since this is difficult to test locally
closes FXA-7439
---
This is basically a combination and iteration on #15723 + #16237
=> fix(sync): Request + set signedInUser from Sync in Settings

packages/fxa-settings/src/components/App/index.tsx
Because:
* We've got a lot of routes under AuthAndAccountSetupRoutes that could be better organized
This commit:
* Creates sections of routes with comment above each section, and organizes first by section comment alphabetically, then by path name within sections
---
I started to do this when working on React signin and figured it'd be better as a separate quick PR to avoid merge conflicts with other Signin tickets.
Happy to move anything around where preferred. In content-server, we organize alphabetically by route name (e.g. `account_recovery_confirm_key` is first, but it's part of the reset password flow, which I've put under "R" here).
=> refactor(react): Small adjustment to organize App routes by alphabetized flow

packages/functional-tests/pages/login.ts, packages/functional-tests/pages/signupReact.ts, packages/functional-tests/tests/oauth/loginHint.spec.ts, packages/functional-tests/tests/oauth/oauthPermissions.spec.ts, packages/functional-tests/tests/oauth/signUp.spec.ts, packages/functional-tests/tests/oauth/signin.spec.ts, packages/functional-tests/tests/oauth/syncSignIn.spec.ts, packages/functional-tests/tests/oauth/webchannel.spec.ts, packages/functional-tests/tests/react-conversion/legal.spec.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/functional-tests/tests/settings/changeEmail.spec.ts, packages/functional-tests/tests/settings/password.spec.ts, packages/functional-tests/tests/settings/passwordVisibility.spec.ts, packages/functional-tests/tests/signUp/signUp.spec.ts, packages/functional-tests/tests/signUp/signUpWithCode.spec.ts, packages/functional-tests/tests/signin/connectAnotherDevice.spec.ts, packages/functional-tests/tests/signin/redirect.spec.ts, packages/functional-tests/tests/signin/signIn.spec.ts, packages/functional-tests/tests/syncV3/fxDesktopV3ForceAuth.spec.ts, packages/functional-tests/tests/syncV3/signIn.spec.ts, packages/functional-tests/tests/syncV3/signUp.spec.ts, packages/functional-tests/tests/syncV3/signUpWithCWTS.spec.ts, packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts, packages/fxa-auth-server/scripts/test-ci.sh, packages/fxa-content-server/server/lib/routes/react-app/index.js, packages/fxa-content-server/server/templates/pages/src/404.html, packages/fxa-settings/src/components/FormPasswordWithBalloons/index.tsx, packages/fxa-settings/src/pages/Signup/index.test.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
* We are flipping the switch to 100% react signup
* Set fullProdRollout for react signUpRoutes to true
* Update functional-tests - skip backbone specific signup tests if showReactApp set to true for signUpRoutes
* Update other tests that are failing with the rollout
* Fixes a "passwords do not match" error causing issues in tests
Closes: #FXA-8927, fixes #FXA-8882
=> feat(react): Full prod rollout of react signup

libs/shared/l10n/src/lib/l10n.ts
- Async function in render logic caused hydration error on page refresh
- Remove async from `getFormatedMsg` wrapper function
Closes: #FXA-8852
=> fix(next): error on page refresh

docs/adr/0041-gcp-cloud-tasks-for-job-queuing.md
Because:
* We want to explain the architecture decision around using Google cloud tasks for job queuing.
This commit:
* Adds an ADR for using Google cloud tasks for job queuing.
Closes FXA-8824
=> feat(auth): add adr for google cloud tasks

backstage/firestore.resources.yaml, backstage/memcached.resources.yaml, backstage/mozilla-accounts.system.yaml, backstage/mysql.resources.yaml, backstage/redis.resources.yaml, packages/123done/backstage.yaml, packages/browserid-verifier/backstage.yaml, packages/fxa-admin-panel/backstage.yaml, packages/fxa-admin-server/backstage.yaml, packages/fxa-auth-server/backstage.yaml, packages/fxa-content-server/backstage.yaml, packages/fxa-customs-server/backstage.yaml, packages/fxa-event-broker/backstage.yaml, packages/fxa-graphql-api/backstage.yaml, packages/fxa-payments-server/backstage.yaml, packages/fxa-profile-server/backstage.yaml, packages/fxa-settings/backstage.yaml
Because:
* We should now be able to use the API location ref.
* We want to use the right group name.
This commit:
* Updates the backstage files to use the new API location ref.
* Updates the backstage files to use the right group name.
=> fix(backstage): use api ref now that its allowed

packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/lib/routes/cloud-tasks.ts, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/lib/routes/utils/account.ts, packages/fxa-auth-server/scripts/refund-unverified-accounts.ts, packages/fxa-auth-server/test/local/account-delete.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/local/routes/cloud-tasks.js
Because:
- we need to handle the account deletion cloud tasks
This commit:
- implements a route handler that
- performs a full account delete if the account is found in the fxa relational database
- performs a data "cleanup" if the account is not found in the db
=> feat(cloud tasks): handle account delete cloud task

packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/server/lib/routes/react-app/index.js, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/LinkDamaged/en.ftl, packages/fxa-settings/src/components/LinkDamaged/index.stories.tsx, packages/fxa-settings/src/components/LinkDamaged/index.test.tsx, packages/fxa-settings/src/components/LinkDamaged/index.tsx, packages/fxa-settings/src/models/pages/signin/index.ts, packages/fxa-settings/src/models/pages/signin/report-signin-query-params.ts, packages/fxa-settings/src/pages/Signin/ReportSignin/container.test.tsx, packages/fxa-settings/src/pages/Signin/ReportSignin/container.tsx, packages/fxa-settings/src/pages/Signin/ReportSignin/en.ftl, packages/fxa-settings/src/pages/Signin/ReportSignin/index.stories.tsx, packages/fxa-settings/src/pages/Signin/ReportSignin/index.test.tsx, packages/fxa-settings/src/pages/Signin/ReportSignin/index.tsx, packages/fxa-settings/src/pages/Signin/ReportSignin/interfaces.ts, packages/fxa-settings/src/pages/mocks.ts
* We are converting signin route pages to React
* Build out `report_signin` page in React, including Storybook and unit tests
* Hook up the page functionality to report an unauthorized sign in attempt
* Reorganize fxa-settings `App` imports list
Closes: #FXA-7047
- `signinRoutes` must be set to `true` in content-server `local.json`
- `showReactApp`,`uid`, `unblockCode` are required search params
For example: `localhost:3030/report_signin?showReactApp=true&uid=863a51659b8f615a25fad03248412979&unblockCode=12345678` (uses randomly generated hex string as uid)
NOTE: Currently, omitting the `uid` and `unblockCode` params entirely will render the link damaged component - …
=> task(react): Setup report_signin in React

backstage/memcached.resources.yaml, backstage/mozilla-accounts.system.yaml, backstage/redis.resources.yaml, packages/123done/backstage.yaml, packages/fxa-content-server/backstage.yaml, packages/fxa-graphql-api/backstage.yaml, packages/fxa-payments-server/backstage.yaml, packages/fxa-profile-server/backstage.yaml, packages/fxa-settings/backstage.yaml
Because:
* We want to properly name cache vs. databases.
* We want to add the GraphQL API to the list of services.
This commit:
* Renames the database resources to cache resources.
* Adds the GraphQL API to the list of services.
=> fix(backstage): update db references, add gql API ref

packages/fxa-graphql-api/backstage.yaml
[skip ci]
Because:
* We want to show the right provider.
This commit:
* Updates the definition errors to show the right provider.
=> fix(backstage): update definition errors

packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/payments/stripe-firestore.ts
- Error log for deleteFirestoreCustomer does not log original errors.
- Add getSummary method to StripeFirestoreMultiError to log errors of all errors.
=> chore(auth): log better error on deleteFirestoreCustomer

packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx, packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx
- Resubscription modal contained copy for both CC and non-CC confirmations.
- Updates the logic to an if/else rather than two ifs, since customers can have both PayPal and CC (last4).
- Updates all applicable tests.
Closes FXA-9018
=> fix(payments): remove duplicate text in resubscribe modal

packages/fxa-auth-server/lib/routes/cloud-tasks.ts, packages/fxa-auth-server/lib/types.ts, packages/fxa-auth-server/scripts/clean-up-partial-account-customer.ts, packages/fxa-auth-server/scripts/delete-unverified-accounts.ts
Because:
- we might have orphaned data from not deleting accountCustomers
This commit:
- adds a script that find accounts that were deleted from the `accounts` table but not the `accountC`ustomers table and create cloud tasks to clean them up
=> feat(scripts): clean up accountCustomers with a script

packages/fxa-settings/src/pages/Signin/ReportSignin/en.ftl
- ftl string was added twice
- Removes the extra string
Closes: #FXA-9066
=> fix(l10n): Remove duplicate string

packages/fxa-settings/src/components/Settings/PageSecondaryEmailAdd/en.ftl
- #16289 reverted a previous patch which included an ftl string. Since this string will be introduced again in the future, we should keep this string in the files so the translations are preserved.
- Restores "add-secondary-email-mask" to ensure translations are not deleted from l10n repos.
=> fix(l10n): Reintroduce string to preserve l10n translations

packages/fxa-graphql-api/src/gql/account.resolver.spec.ts, packages/fxa-graphql-api/src/gql/account.resolver.ts
- The clients IP wasn't making it to auth server, and there fore was being reported.
- Makes sure that headers are passed to auth client.
Closes: FXA-8629
=> bug(graphql-api): Fix relaying of client side IP

packages/functional-tests/lib/fixtures/standard.ts, packages/functional-tests/pages/login.ts, packages/fxa-settings/src/components/App/gql.ts, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/Settings/ConnectedServices/index.test.tsx, packages/fxa-settings/src/components/Settings/DropDownAvatarMenu/index.test.tsx, packages/fxa-settings/src/components/Settings/ModalVerifySession/index.stories.tsx, packages/fxa-settings/src/components/Settings/ModalVerifySession/index.test.tsx, packages/fxa-settings/src/components/Settings/ModalVerifySession/index.tsx, packages/fxa-settings/src/components/Settings/Page2faReplaceRecoveryCodes/index.test.tsx, packages/fxa-settings/src/components/Settings/PageDeleteAccount/index.test.tsx, packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.test.tsx, packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.test.tsx, packages/fxa-settings/src/components/Settings/VerifiedSessionGuard/index.test.tsx, packages/fxa-settings/src/components/Settings/VerifiedSessionGuard/index.tsx, packages/fxa-settings/src/components/Settings/index.test.tsx, packages/fxa-settings/src/lib/gql.ts, packages/fxa-settings/src/models/Account.ts, packages/fxa-settings/src/models/Session.ts, packages/fxa-settings/src/models/contexts/AppContext.ts, packages/fxa-settings/src/models/hooks.ts, packages/fxa-settings/src/models/mocks.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/mocks.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx, packages/fxa-settings/src/pages/Signup/Confirm/index.test.tsx, packages/fxa-settings/src/pages/Signup/Confirm/index.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.test.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx
- We want to separate out session functions from account related ones
- We also want to be able to use the Session hook when a user is not signed in locally
- Moves all session related react functions into the Session hook
- Updates all components to use the new hook
- Updates all tests 
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7184
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7626
To test this, you will need to signin with an unverified session, easiest way to set the `skipForNewAccounts` auth-server value to 0.
=> feat(react): Move all session related functions into the Session hook

packages/fxa-auth-server/scripts/test-ci.sh
- We were seeing some flaky unit tests in auth server
- Disables the parallel option for unit tests.
- Due to the way some tests are structured, we can't enable the parallel option here.
Closes: FXA-8875
We might want to consider filing a follow up for supporting the parallel option for unit tests. Ideally this would work, but would require ensuring there's no shared state between tests. Since it's hard to trigger these failures, validating that any shared state was successfully removed is a bit tricky... Furthermore the savings may be inconsequential since we have other longer running CI jobs anyway.
=> task(auth): Fix flaky unit tests in auth server

packages/functional-tests/pages/login.ts, packages/functional-tests/tests/signUp/signUp.spec.ts
Audited Signup modules and these are the conclusions:
- Removed the TODO comment - as the assert was already performed on the [URL](https://github.com/mozilla/fxa/blob/main/packages/functional-tests/tests/signUp/signUp.spec.ts#L104)
- Found the reason for High Failure rate for [relier test](https://github.com/mozilla/fxa/blob/main/packages/functional-tests/tests/signUp/signUp.spec.ts#L151) was due to GCP load balancer issue for the Timeouts [refer this](https://docs.google.com/document/d/14d-Z8LEsuf05zDhfrcasORNTYyVjJ8TA-WcMWBirtkI/edit) Doc for June 7, 2023 notes)
More info on [FXA-7347](https://mozilla-hub.atlassian.net/browse/FXA-7347)
- Removes unnecessary comments found during the audit process
Closes: FXA-8955
Please attach the screenshots of the …
=> test(signup): audit and remove the TODO statements

packages/fxa-content-server/app/scripts/views/sign_in_token_code.js, packages/fxa-content-server/app/tests/spec/views/sign_in_token_code.js
- Users that have TOTP enabled can not verify their session with an email, our API will not send the email
- Users should be prompted to verify with TOTP if they have it
- Redirects the user to the verify TOTP page if they somehow land on the signin confirmation page with TOTP enabled
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8793
To test
1. Add TOTP to account
2. Sign out
3. Login and enter password, should be prompted to enter TOTP
4. Navigate to `/signin_token_code` page, should be redirected to TOTP page
=> fix(signin): Redirect to totp page if user lands on signin confirm with totp enabled

packages/fxa-settings/src/lib/oauth/hooks.tsx, packages/fxa-settings/src/models/integrations/oauth-integration.ts, packages/fxa-settings/src/models/integrations/sync-desktop-v3-integration.ts, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/interfaces.ts, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/mocks.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/interfaces.ts, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/mocks.tsx, packages/fxa-settings/src/pages/Signup/index.stories.tsx, packages/fxa-settings/src/pages/Signup/index.test.tsx, packages/fxa-settings/src/pages/Signup/index.tsx, packages/fxa-settings/src/pages/Signup/mocks.tsx
Because:
* Sync desktop is moving to oauth_webchannel_v1 context and we need to accomodate to allow content and oauth sync to share the same session token
This commit:
* Sends oauth sync data up via firefox.fxaLogin and firefox.fxaLoginSignedInUser for signup and reset password
* Removes switch statements around integration type, as we're not following this pattern on new pages, and removes now obsolete comments
* Updates tests
closes FXA-8905
=> feat(sync): Send Sync oauth login data via firefox.fxaLogin

packages/fxa-graphql-api/src/decorators.spec.ts, packages/fxa-graphql-api/src/decorators.ts, packages/fxa-graphql-api/src/gql/account.resolver.ts, packages/fxa-graphql-api/src/gql/lib/factories.ts, packages/fxa-graphql-api/src/gql/lib/util.spec.ts, packages/fxa-graphql-api/src/gql/lib/util.ts, packages/fxa-graphql-api/src/gql/session.resolver.spec.ts, packages/fxa-graphql-api/src/gql/session.resolver.ts
- After landing the previous patch, there was some concern that something might also be off with the headers being sent to the gql-api.
- Adds logs to ensure that the x-forwarded-for headers are being sent to graphql-api
- Adds extra edge case such that current x-forwarded-for headers are respected. Note that in stage / production, these values are provided by the ingress. It's possible that the previous implementation, which just looked at req.ip was dropping these.
=> task(graphql): Add logging for incoming x-forwarded-for headers

packages/fxa-content-server/app/scripts/models/account.js
- We don't use this value anywhere except during signup where it is sent and stored in database, so don't require it to be in localstorage
- Removes it from Backbone account model
=> fix(storage): Don't persist `atLeast18AtReg` to local storage

packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/payments/paypal/helper.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/lib/routes/cloud-tasks.ts, packages/fxa-auth-server/test/local/account-delete.js, packages/fxa-auth-server/test/local/payments/paypal.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/cloud-tasks.js
- For unverified accounts, refund invoices paid through PayPal, up to 180 days ago.
- For unverified accounts, refund all invoices paid through Stripe.
- Adds invoice fetch to StripeHelper
- Adds invoices refund method to StripeHelper
- Adds invoices refund method to PayPalHelper
- Adds refundSubscriptions method to AccountDeleteManager
Closes: #FXA-8841 and FXA-8840
=> feat(auth): Refund Stripe and PayPal invoices on delete

packages/fxa-auth-server/scripts/delete-account.ts
Because:
- the account routes has a dependency on AccountDeleteManager but we are not setting one into the DI container
This commit:
- set an instance of AccountDeleteManager for the delete account script
=> fix(scripts): set AccountDeleteManager for delete account script

packages/fxa-settings/src/models/Account.ts
- We fixed the ip forwarding issue and want to validate the work
- Makes a gql call PASSWORD_FORGOT_SEND_CODE
Closes: 
This just restores, more or less, what was undone [here](https://github.com/mozilla/fxa/pull/15505).
=> task(settings): Restore use of gql query for resetPassword

packages/fxa-shared/sentry/pii-filter-actions.ts
- We could see from breadcrumbs on other sentry events that uriDecode would sometimes produce an exception
- Handles any uriDecode error and falls back to just using the raw string if this happens
=> bug(shared): Handle exception in email pii filter

packages/fxa-content-server/app/scripts/lib/auth-errors.js, packages/fxa-content-server/app/scripts/lib/vat.js, packages/fxa-content-server/app/scripts/views/index.js, packages/fxa-content-server/app/tests/spec/views/index.js, packages/fxa-settings/src/components/Settings/PageSecondaryEmailAdd/index.test.tsx, packages/fxa-settings/src/components/Settings/PageSecondaryEmailAdd/index.tsx, packages/fxa-settings/src/lib/auth-errors/auth-errors.ts, packages/fxa-settings/src/pages/Signup/index.test.tsx, packages/fxa-settings/src/pages/Signup/index.tsx, packages/fxa-shared/email/helpers.ts
- This is the updated version of the original PR in  https://mozilla-hub.atlassian.net/browse/FXA-5229
- Last attempt at this fix borked signin
- Allows Relay masks to be used for signin but disabled for signups
- Updates the React Signup page to reject Relay emails
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9065
React signup:
Backbone signup:
To test:
1. Before checking out PR, create an relay email (ex. a@relay.firefox.com)
2. Checkout PR, attempt to signin with relay email, should allow
3. Attempt to create a new relay email (b@relay.firefox.com), should fail
=> fix(email): Disable using Relay masks to create an account or secondary

packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/lib/routes/cloud-tasks.ts, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/lib/types.ts, packages/fxa-auth-server/scripts/clean-up-partial-account-customer.ts, packages/fxa-auth-server/scripts/delete-unverified-accounts.ts, packages/fxa-auth-server/test/local/account-delete.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/local/routes/cloud-tasks.js
Because:
* We want to simplify account deletion logic.
* We want to avoid having the user wait on account deletion.
This commit:
* Moved types to a single location and used an enum.
* Consolidated notify logic for account deletion.
* Updated delete path to work for cleanup and first-time deletion.
* Updated tests to reflect changes.
=> refactor(auth): update types and logic for account deletion

packages/fxa-auth-server/lib/customs.js, packages/fxa-auth-server/test/local/customs.js
- This wasn't ported over in https://github.com/mozilla/fxa/pull/16092, we ported over the block counts but not request timings
- Reports the customs server request timings
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9120
=> Fix customs server not reporting statsd url timings

libs/payments/capability/src/lib/capability.manager.spec.ts, libs/payments/capability/src/lib/capability.manager.ts
- Sentry is throwing an "items undefined" error when `items` are missing.
- Validates that `capabilitiesCollection` items and `servicesCollection` items are populated before proceeding.
- Adds additional tests to check that both collections are populated.
- In both cases, similar to when no `capabilityOffering` is found, an empty array is returned.
Closes FXA-9052
Items in both collections are required and expected. Since Contentful does not verify these fields are populated before publishing, these checks serve as an additional failsafe.
=> fix(contentful): validate that items in planIdsToClientCapabilities are populated

packages/functional-tests/pages/login.ts, packages/functional-tests/pages/products/subscriptionManagement.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/coupon.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/ui-tests.spec.ts, packages/functional-tests/tests/subscription-tests/subscription.spec.ts, packages/functional-tests/tests/subscription-tests/support.spec.ts
the functional tests have a nightly 90-day success rate < 95% and a skip rate ~ 11-12% indicating waning stability and sustainability respectively.
audits the 'subscription-tests' functional test module making changes to improve these metrics:
1. remove test case 'support form with active subscriptions > go to support form, submits the form
- The test case can present as a false positive since it can't be fulfilled due to Zendesk limitations in CI. Furthermore, the steps it does execute are repeated in 'support form with active subscriptions > go to support form, cancel, redirects to subscription management' so we can reduce CI cost and execution time by removing it.
2. uncomment and add fixme annotation to  'Flow, acquisition and new user checkout funnel metrics > New user checkout URL …
=> test(functional-tests): audit subscription-tests functional tests

packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/account-delete.js, packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* We want to track why a subscription was cancelled in Stripe.
This commit:
* Updates metadata with the reason on the Stripe subscriptions before deleteing them.
Closes FXA-9067
=> feat(auth): update active subs with cancellation reason before deleting

packages/fxa-auth-server/lib/metrics/glean/index.ts, packages/fxa-auth-server/test/local/metrics/glean.ts
Because:
- for certain server-side events we don't want to send the client ip for Glean ingestion
This commit:
- adds an option to skip the client ip in the event logging function
- uses the option for `access_token_checked` events
=> feat(glean): add option to skip client ip address

packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/test/local/payments/capability.js
- capabilities are not listed in Sentry error message
- updates Sentry error message to help debug process by showing capabilities within both Contentful and Stripe
=> fix(auth): Update Sentry error message to show capabilities

packages/fxa-content-server/package.json
* Transferred tailwind.out.css was very large (>3mb) and unused styles were not purged
* Optimize build-css for production
Closes: #FXA-9129
After the initial change, the tailwind file is down from >5 mb to just over 0.1mb.
A second commit adds a minification step, this reduces a tad further to 0.06mb.
=> perf(content): Optimize tailwind output

libs/shared/account/account/src/lib/account.manager.ts, libs/shared/account/account/src/lib/account.repository.ts, packages/fxa-auth-server/scripts/cleanup-partial-firestore-customers.ts, packages/fxa-shared/payments/stripe-firestore.ts
- Need to remove customers and related subcollections, from firestore,
for customers already deleted in FxA.
- Adds a script that parses through all Firestore customer records, and
checks if the customer has a valid FxA account. If not, the uid is
added to the delete account cloud task queue, for deletion.
Closes: #FXA-8969
=> feat(auth): partial delete cleanup script

_dev/loadtesting/script.js, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/customs.js, packages/fxa-auth-server/lib/http-agent.ts
- It appears that custom server is taking longer to respond on some requests, ref https://mozilla.sentry.io/performance/fxa-auth:c5096461f4ac4441b8d16c8480d0ef3d/?environment=stage&project=6231056&query=&statsPeriod=1h&transaction=POST#span-efeb80ef74e5b936
- When we migrated to use axios and keepalive, I [commented](https://github.com/mozilla/fxa/pull/16190/files#r1430547917) on using the defaults of keepalive (100) vs what was in our previous library (1000)
- Updates max sockets to 1000, reduces the timeoutMs
Connects to https://mozilla-hub.atlassian.net/browse/FXA-9117
Once this lands, its pretty straightforward to verify in stage. We would need to run the load tester script and then check to see how the response times are.
=> fix(customs): Update customs axios maxSockets and timeoutMs

.vscode/settings.json, packages/functional-tests/package.json, yarn.lock
- it would facilitate development to use the [VSCode Playwright Extension](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright)
- upgrades the @playwright/test version to 1.35.1 (the minimum required to enable the extension)
- adds required environment variables to the vscode settings
=> chore(functional-tests): update package and settings to allow for use of playwright vscode extension

packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/payments/iap/apple-app-store/purchase-manager.ts, packages/fxa-auth-server/lib/payments/iap/google-play/purchase-manager.ts, packages/fxa-auth-server/test/local/account-delete.js, packages/fxa-auth-server/test/local/payments/iap/apple-app-store/purchase-manager.js, packages/fxa-auth-server/test/local/payments/iap/google-play/purchase-manager.js
Because:
* We want to remove all IAP data when an account is deleted.
This commit:
* Adds a `delete` method to the `PurchaseManager` interface.
* Adds delete methods to the Apple and Google IAP purchase managers.
* Adds delete calls to the account delete manager.
Closes FXA-9055
=> feat(auth): remove purchases on account delete

packages/functional-tests/tests/misc/forceAuth.spec.ts, packages/functional-tests/tests/oauth/forceAuth.spec.ts, packages/functional-tests/tests/oauth/resetPassword.spec.ts, packages/functional-tests/tests/reset-password/resetPassword.spec.ts, packages/functional-tests/tests/syncV3/syncV3ResetPassword.spec.ts
the functional tests have a nightly 90-day success rate < 95% and a skip rate ~ 11-12% indicating waning stability and sustainability respectively.
adds a clarifying statement and JIRA ticket link for tests covering the backbone version of reset password flows. These tests are currently inflating the skip rate.
Closes: #FXA-8957
=> test(functional-tests): audit reset-password

libs/payments/legacy/src/lib/stripe-mapper.service.spec.ts, libs/shared/contentful/src/lib/contentful.client.spec.ts, libs/shared/contentful/src/lib/contentful.client.ts, libs/shared/contentful/src/lib/contentful.manager.spec.ts, libs/shared/contentful/src/lib/contentful.manager.ts, packages/fxa-auth-server/bin/key_server.js
- Want to track number of requests and timings of those requests made to contentful.
- Adds event emitter to Contentful Client, similar to PayPal Client.
- Add statsd to Contentful Manager to to track requests timings on contentful client event.
Closes: #FXA-9031
=> feat(contentful): Add statsd metrics to contentful

packages/fxa-auth-server/lib/payments/capability.ts
- Lodash's isEqual did not work when comparing array of objects
- sorts clients/services returned from Contentful and Stripe prior to comparison
Closes: FXA-8977
=> fix(auth): Sort clients from both Contentful and Stripe

packages/functional-tests/tests/misc/keyStretchingV2.spec.ts, packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-server/test/scripts/fixtures/accounts.sql, packages/fxa-graphql-api/src/gql/account.resolver.spec.ts, packages/fxa-graphql-api/src/gql/account.resolver.ts, packages/fxa-graphql-api/src/gql/dto/input/credential-status.ts, packages/fxa-graphql-api/src/gql/dto/input/index.ts, packages/fxa-graphql-api/src/gql/dto/input/password-change-finish.ts, packages/fxa-graphql-api/src/gql/dto/input/password-change-start.ts, packages/fxa-graphql-api/src/gql/dto/payload/credential-status.ts, packages/fxa-graphql-api/src/gql/dto/payload/index.ts, packages/fxa-graphql-api/src/gql/dto/payload/password-change-finish.ts, packages/fxa-graphql-api/src/gql/dto/payload/password-change-start.ts, packages/fxa-graphql-api/src/gql/dto/payload/wrapped-keys.ts, packages/fxa-graphql-api/test/accounts.sql, packages/fxa-settings/src/pages/Signin/container.test.tsx, packages/fxa-settings/src/pages/Signin/container.tsx, packages/fxa-settings/src/pages/Signin/gql.ts, packages/fxa-settings/src/pages/Signin/interfaces.ts
- Want  to support using V2 key stretching for react sign in
- Adds support for using v2 key stretching on sign in
- Updates functional tests to make sure V2 signin is active for react
Closes: FXA-9074
There was not an existing container.test.ts for sign in. Is there a ticket somewhere for this? We do have quite a bit of test coverage due to the keyStertchV2 tests, which cover a bunch of key stretching use cases and interchangeability between v1 and v2 key stretching.
=> task(settings): Support v2 key stretches for signin

packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signin/index.tsx
Because:
* We want to replace legacy amplitude events with Glean events
This commit:
* Emits this event when a user hits an error state when they attempt and fail to sign in with their password
closes FXA-8022
=> feat(metrics): Add Glean login_submit_frontend_error event to React signin

packages/functional-tests/tests/react-conversion/forceAuth.spec.ts, packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/server/lib/routes/react-app/index.js, packages/fxa-settings/src/components/App/index.tsx
- We have some browser that link to this route and we should still support it
- Adds support for the React version of `/force_auth`
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8268
I opted to redirect to the Signin component because it already validates the email and will send the user to create account page if email doesn't exist. This seemed like the most straightward thing to do.
To test:
1. Open http://localhost:3030/force_auth?context=fx_desktop_v3&entrypoint=fxa_app_menu&action=email&service=sync&email=<existing user email>, this should redirect to signin the user
2. Open http://localhost:3030/force_auth?context=fx_desktop_v3&entrypoint=fxa_app_menu&action=email&service=sync&email=<non exisitn user email>, this should redirect user to create account
=> feat(react): Add support for the `/force_auth` route in React

packages/functional-tests/pages/settings/totp.ts, packages/functional-tests/tests/react-conversion/signinTotp.spec.ts, packages/fxa-graphql-api/src/auth/session-token.strategy.ts, packages/fxa-graphql-api/src/auth/unverified-session-guard.spec.ts, packages/fxa-graphql-api/src/auth/unverified-session-guard.ts, packages/fxa-graphql-api/src/decorators.ts, packages/fxa-graphql-api/src/gql/account.resolver.ts, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/models/pages/signin/query-params.ts, packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/gql.ts, packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.stories.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.tsx, packages/fxa-settings/src/pages/Signin/gql.ts, packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signin/index.tsx, packages/fxa-settings/src/pages/Signup/container.test.tsx
- We are porting over pages from backbone to react
- Makes the signin totp code page functional
Closes: FXA-6491
=> task(settings): Make signin_totp_code page functional

packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/test/local/payments/capability.js
- `eligibilityFromEligibilityManager` and `eligibilityFromStripeMetadata` returned different results - should have both returned `blocked_iap`
- revises `eligibilityFromEligibilityManager`
Closes: FXA-9011
=> fix(auth): Revise eligibilityFromEligibilityManager - blocked_iap

libs/payments/eligibility/src/lib/eligibility.manager.spec.ts, libs/payments/eligibility/src/lib/utils.ts
- Offering comparison in the eligibility manager incorrectly indicates a downgrade if the difference between the target and source index is greater than 1, which can happen for subgroups with multiple offerings.
- During offering comparison, if the difference between target and source index is positive, return UPGRADE, for values that are the same return SAME, and negative values return DOWNGRADE.
Closes: #
=> fix(auth): offering comparison upgrade fix

libs/shared/db/type-cacheable/src/lib/type-cachable-firestore-adapter.ts
- Firestore expects TTL to be a timestamp.
- Updates TTL for type-cacheable Firestore to a timestamp.
Closes: No relevant issue
=> fix(type-cacheable): caching TTL

packages/fxa-content-server/server/lib/routes/react-app/index.js, packages/fxa-settings/src/components/App/gql.ts, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/Banner/index.tsx, packages/fxa-settings/src/components/FormVerifyCode/index.tsx, packages/fxa-settings/src/components/FormVerifyCode/mocks.tsx, packages/fxa-settings/src/lib/interfaces.ts, packages/fxa-settings/src/models/Account.ts, packages/fxa-settings/src/models/Session.ts, packages/fxa-settings/src/pages/InlineTotpSetup/index.tsx, packages/fxa-settings/src/pages/Pair/AuthTotp/index.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.stories.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/interfaces.ts, packages/fxa-settings/src/pages/Signin/SigninTokenCode/mocks.tsx, packages/fxa-settings/src/pages/Signin/container.test.tsx, packages/fxa-settings/src/pages/Signin/container.tsx, packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signin/index.tsx, packages/fxa-settings/src/pages/Signin/interfaces.ts, packages/fxa-settings/src/pages/Signin/mocks.tsx, packages/fxa-settings/src/pages/Signup/interfaces.ts, packages/fxa-settings/tailwind.config.js
Because:
* We're converting our legacy Backbone pages to React incrementally
This commit:
* Adds the signin_token_code route
* Creates a container component for the page component and does some checks before rendering the page
* Sets the page up to work functionally including success and error states for resending a code and submitting the code
* Tweaks the banner to take in an animation
closes FXA-6490
---
Users reach this screen when they need to verify their session. To test this locally you can set `SIGNIN_CONFIRMATION_FORCE_GLOBALLY` to `true` which will force this state on signin and then [hit localhost with the React experiment params](http://localhost:3030/?forceExperiment=generalizedReactApp&forceExperimentGroup=react).
=> feat(react): Recreate '/signin_token_code' page functionality in React

packages/fxa-auth-server/lib/customs.js, packages/fxa-auth-server/test/local/customs.js
- It is useful to log stats of custom server
- Updates the customs lib to log httpAgent status
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9169
I didn't add logging for the `freeSocket` value since it was an object and not sure exactly how many keys it could have.
=> chore(customs): Add statsd metrics for httpAgent socket status

packages/fxa-settings/src/lib/auth-errors/en.ftl, packages/fxa-settings/src/pages/Signup/en.ftl, packages/fxa-settings/src/pages/Signup/index.test.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
Because:
* The age limit was 999, which is too high
This commit:
* Adds an age limit of 130, else we display an error tooltip
* Moves a string from signup FTL to auth-errors FTL for consistency
fixes FXA-9104
=> fix(signup): Disallow age submissions > 130

packages/fxa-content-server/package.json
Because:
* This flag appears to cause multiple selectors with an asterisk to not work, as it strips out a needed space. We already perform some minification on Settings which does not use this flag
This commit:
* Removes the --minify option in content-server's build-css step
closes FXA-9167, closes FXA-9170
---
In triage I thought this was a JS file inclusion issue, but after some digging I saw the selectors were present in the `.out.css` file in staging very similarly to locally, but the `right: 1px` style on `input-password-toggle-label-hide` wasn't being rendered properly. I tracked it down to this (for FXA-9170):
This is from our stage CSS ([link as of now](https://accounts-cdn.stage.mozaws.net/styles/6edd0aac.tailwind.out.css)):
``` …
```
=> fix(css): Remove --minify flag from content-server build-css step

apps/payments/next/tsconfig.json, packages/functional-tests/tests/oauth/oauthPromptNone.spec.ts, packages/fxa-content-server/app/scripts/models/reliers/oauth.js, packages/fxa-content-server/app/tests/spec/models/reliers/oauth.js
- Allow prompt=none signin even if login_hint or id_token_hint is not provided, as the current spec has these as optional parameters.
- For prompt=none signin, if login_hint or id_token_hint is not provided it allows successful signin.
- For prompt=none signin, if login_hint or id_token_hint are provided it keeps the current checks as is.
Closes: #FXA-9035
Based on my reading of the following note in the OIDC spec, login_hint and id_token_hint are optional params, and if neither is provided, prompt=none should still attempt to return successfully. ([Link here](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest))
> When possible, an id_token_hint SHOULD be present when prompt=none is used and an invalid_request error MAY be returned if it …
=> feat(auth): allow prompt=none without hint

packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.tsx, packages/fxa-settings/src/pages/Signin/container.tsx, packages/fxa-settings/src/pages/Signin/index.tsx
Because:
* An associated ticket was created and could be added to a couple places for clarity, and we have a stray console.log
This commit:
* Adjusts comments
=> style(react): Add ticket number to comments, remove stray console.log

packages/functional-tests/tests/react-conversion/signinTotp.spec.ts
- Test is currently failing, and ticket has been created to debug the test.
- Disables the test with a ticket number.
=> chore(test): disable failing signInTotp test

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
- customer was unable to enter in new payment method after Support removed default payment method - "Use saved payment option" still appeared during checkout despite not having no default payment method
- updates getPaymentProvider based on customer's default payment method instead of active subscriptions.
Closes: FXA-9156
After removing the payment method and going to a new product's checkout page:
=> fix(auth): Revise getPaymentProvider

libs/payments/paypal/project.json, libs/payments/paypal/src/lib/paypal.manager.spec.ts, libs/payments/paypal/src/lib/paypal.manager.ts, libs/shared/account/account/src/lib/account.manager.spec.ts, libs/shared/db/mysql/account/src/index.ts, libs/shared/db/mysql/account/src/lib/associated-types.ts, libs/shared/db/mysql/account/src/lib/factories.ts, libs/shared/db/mysql/account/src/lib/tests.ts, libs/shared/db/mysql/account/src/test/accountCustomers.sql, libs/shared/db/mysql/account/src/test/paypalCustomers.sql
- We need Kysely interface for both AccountCustomers and PaypalCustomers
- Adds both to the mysql accounts library
Closes: FXA-8887 and FXA-8886
=> feat(mysql): add AccountCustomers and PaypalCustomers

packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* We want to use a direct stripe query to locate the subscriptions for a customer instead of relying on methods that may use firestore during delete.
This commit:
* Changes the fetch query to use the stripe customer id directly.
=> fix(auth): use direct subscription query

apps/payments/next/app/[offeringId]/checkout/[cartId]/error/page.tsx, apps/payments/next/app/[offeringId]/checkout/[cartId]/page.tsx, apps/payments/next/app/[offeringId]/checkout/[cartId]/success/page.tsx, apps/payments/next/app/[offeringId]/checkout/layout.tsx, apps/payments/next/app/[offeringId]/checkout/new/page.tsx, apps/payments/next/app/_lib/stubs.ts, apps/payments/next/app/page.tsx, libs/payments/ui/src/lib/server/purchase-details.tsx, libs/payments/ui/src/lib/server/terms-and-privacy.tsx, libs/shared/l10n/src/lib/determine-locale.spec.ts, libs/shared/l10n/src/lib/determine-locale.ts, libs/shared/l10n/src/lib/l10n.ts
- Reorganize checkout pages to include intent and cartId in path, and allow for landing page.
- Reorganizes checkout pages
- Add checkout landing page
- Add getLocaleFromRequest and update l10n locale logic
Closes: #FXA-7804
=> feat(next): reorg checkout pages

libs/payments/stripe/project.json, libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.manager.ts
=> feat(payments-stripe): Create StripeManager isCustomerStripeTaxEligible

packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/test/local/payments/capability.js
- [Sentry](https://mozilla.sentry.io/issues/4993075790/?environment=stage&project=6231056&query=is%3Aunresolved+mismatch&referrer=issue-stream&statsPeriod=30d&stream_index=1) logged an event for when a customer with a VPN EUR Annual Plan tried to subscribe to a VPN USD Annual plan
- eligibilityManagerResult: upgrade
- stripeEligibilityResult: invalid
- Updates eligibilityFromEligibilityManager
=> fix(auth): Update eligibilityFromEligibilityManager

packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/test/local/account-delete.js
Because:
* We want to avoid making changes to the database when queueing account delete tasks.
This commit:
* Directly queries the accountCustomers table to fetch the linked customer record instead of a fetchCustomer which may make db changes.
=> fix: directly query for customer to avoid db changes

packages/fxa-content-server/grunttasks/build.js, packages/fxa-content-server/grunttasks/replace.js
Because:
* Our content-server CSS minification build task is stripping a space between brackets and asterisks, invalidating the selector and causing some styles to not apply. See comment included in commit for more details
This commit:
* Adds a grunttask to add the whitespace back
fixes FXA-9167, fixes FXA-9170
---
In #16445, I wondered if removing `--minify` would not fix the problem (see the "EDIT" and comments). We included the fix in a dot release and I've since confirmed a few things:
* Stage is still having the problems described in the linked tickets
* `--minify` does not do anything for us for content-server at least, I compared what was uploaded to stage before and after this option and there is no diff because...
* We're using a grunt task to minify our content-server CSS not …
=> chore(css): Add grunttask to fix content-server Tailwind selectors

packages/db-migrations/contentful/1708637169029_fxa-8978.js
- Need to ease validations on the capability slug string to accommodate the following scenarios
- Capability string greater than 20 characters
- Same capability string used by multiple services
- Removes the character limits and unique constraint from the capability slug string.
Closes: #FXA-8978
=> feat(contentful): ease capability validation

packages/functional-tests/pages/products/index.ts, packages/functional-tests/pages/products/subscriptionManagement.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/coupon.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts, packages/functional-tests/tests/subscription-tests/subscription.spec.ts
- the PayPal functional tests continue to be brittle, reporting false negatives and disrupting the CI pipeline
- removes PayPal functional tests
Closes: # FXA-9180
- Alternative methods, monitoring & manual testing, exists to detect breakages with the PayPal interface
- A follow-up spike has been created to research alternative automated test methods (see [FXA-9186](https://mozilla-hub.atlassian.net/browse/FXA-9186))
[FXA-9186]: https://mozilla-hub.atlassian.net/browse/FXA-9186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test(functional-tests): remove PayPal functional tests

packages/functional-tests/pages/cookiesDisabled.ts, packages/functional-tests/pages/login.ts, packages/functional-tests/pages/relier.ts, packages/functional-tests/tests/misc/cookiesDisabled.spec.ts, packages/functional-tests/tests/oauth/oauthPermissions.spec.ts, packages/functional-tests/tests/oauth/oauthPromptNone.spec.ts, packages/functional-tests/tests/oauth/signUp.spec.ts, packages/functional-tests/tests/signUp/signUp.spec.ts, packages/functional-tests/tests/signin/signIn.spec.ts, packages/functional-tests/tests/signin/signinBlocked.spec.ts, packages/functional-tests/tests/signin/signinCached.spec.ts, packages/functional-tests/tests/syncV3/settings.spec.ts, packages/functional-tests/tests/syncV3/signUp.spec.ts, packages/functional-tests/tests/syncV3/signinCached.spec.ts, packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts
- In order to improve functional test performance, ease-of-use and maintainability complete the improvements and fixes listed as sub-tasks.
- Replaces page.selector() with page.locator()
- Replaces waitForSelector() with page.locator()
- Replaces expect().tobe() with expect.ToBeVisible()
- Adds fix.me() for failing test to be worked on with [this ticket](https://mozilla-hub.atlassian.net/browse/FXA-9194)
Closes: FXA-8997 FXA-9094
=> update waitForSelector() to page.locator()

libs/payments/paypal/src/lib/paypal.manager.spec.ts, libs/payments/paypal/src/lib/paypal.manager.ts
-  [x] creates PayPalManager getCheckoutToken
Ref: PayPalHelper getCheckoutToken
Closes: FXA-8932
=> feat(payments-paypal): Create PayPalManager getCheckoutToken

packages/fxa-customs-server/lib/cache.js, packages/fxa-customs-server/lib/config/config.js, packages/fxa-customs-server/lib/config/dev.json, packages/fxa-customs-server/lib/server.js, packages/fxa-customs-server/package.json, packages/fxa-customs-server/scripts/test-local.sh, packages/fxa-customs-server/test/memcache-helper.js, packages/fxa-customs-server/test/remote/block_email_tests.js, packages/fxa-customs-server/test/remote/check_ip_only_tests.js, packages/fxa-customs-server/test/remote/check_reputation_tests.js, packages/fxa-customs-server/test/remote/config_update_tests.js, packages/fxa-customs-server/test/remote/failed_login_attempt_tests.js, packages/fxa-customs-server/test/remote/ip_blocklist_disable.js, packages/fxa-customs-server/test/remote/ip_blocklist_tests.js, packages/fxa-customs-server/test/remote/memcache_error_tests.js, packages/fxa-customs-server/test/remote/never_blocked.js, packages/fxa-customs-server/test/remote/password_reset_clears_bad_logins.js, packages/fxa-customs-server/test/remote/password_reset_tests.js, packages/fxa-customs-server/test/remote/root_tests.js, packages/fxa-customs-server/test/remote/send_violations_tests.js, packages/fxa-customs-server/test/remote/too_many_emails.js, packages/fxa-customs-server/test/utils.js, packages/fxa-shared/db/config.ts
- We want to eventually migrate over to redis for all our caching needs
- Customs server is the only service that uses memcache
- We should expect a performance increase (TBD on running loadtesting)
- Adds a new `Cache` library to custom server that switches between memcache and redis
- To reduce code churn, I opted to keep existing memcache function names `getAsync` `setAsync`
- Updated tests where needed, added new test command to run redis version of test
- Redis entries match the lifetime of memcache entries
Closes: 
Test:
1. Enabled custom server in auth-server, in fxa-auth-server/config/dev.json, set `customUrl: http://127.0.0.1:7000`
2. Enable redis in customs server, fxa-customs-server/config/dev.json, set `enabled: true`
3. Start services
4. Create an account, attempt to login …
=> feat(redis): Add support to customs server to use redis or memcache

packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.tsx
- We need to add glean metrics
- Adds glean metric call for totpForm.success (event: login_totp_code_success_view)
- Adds glean metric call for totpForm.submit (event: login_totp_code_submit)
- Adds glean metric call for totpForm.view (event: login_totp_form_view)
Closes: FXA-8026, FXA-8027, FXA-8028
=> task(settings): Add glean metrics for totp

packages/fxa-auth-server/lib/geodb.js
- We are seeing errors when geodb throws an error, causing metrics to fail.
- Falls back to object with null properties (which is compatible with what fxa-geodb returns if it's unable to geolocate an IP address).
Closes: FXA-8571
=> fix(auth): fallback to null locations rather than empty object

packages/fxa-settings/src/pages/Signin/SigninUnblock/en.ftl, packages/fxa-settings/src/pages/Signin/SigninUnblock/index.test.tsx, packages/fxa-settings/src/pages/Signin/SigninUnblock/index.tsx
* There is a word missing in an error message string
* Add missing word and replace l10n string
Issue #FXA-9030
=> fix(l10n): Fix l10n string in signin unblock

packages/fxa-content-server/app/scripts/lib/app-start.js, packages/fxa-content-server/app/scripts/lib/experiment.js, packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/index.js, packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/key-stretch.js, packages/fxa-content-server/app/scripts/lib/fxa-client.js, packages/fxa-content-server/app/scripts/lib/key-stretch-experiment-mixin.js, packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/key-stretch.js, packages/fxa-content-server/server/lib/beta-settings.js, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/server/lib/routes/get-index.js, packages/fxa-settings/src/lib/config.ts, packages/fxa-settings/src/models/contexts/AppContext.ts, packages/fxa-settings/src/models/experiments/key-stretch-experiment.test.ts, packages/fxa-settings/src/models/experiments/key-stretch-experiment.ts, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx, packages/fxa-settings/src/pages/Signin/container.tsx, packages/fxa-settings/src/pages/Signup/container.tsx
- We are prepping for a slow key stretching v2 rollout
- Adds feature flag to to toggle on / off key stretching V2
- Adds experiment to enroll users into key stretching V2
- Allows fxa-settings to check experiment state
- Adds query parameters to override feature flags
- Adds query parameters to force experiment
- Adds experiment for key stretch v2
- Exposes config to control experiment's roll out rate
- Set config defaults such that v2 key stretching is disabled
Closes: FXA-9080
A way to validate this is to change the config settings as desired. Run a `pm2 restart content`, and watch the network tab. V2 key stretching payloads will be delivered if the feature flag is flipped and the user gets enrolled in the experiment. Other than this, the v2 key …
=> task(settings, content): Create configurable rollout rates for v2 key stretching

packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/test/local/payments/capability.js
- To help identify mismatches in capability calculatation between Contentful and Stripe metadata, always log when there is a mismatches and include the subscribedPrices.
- Always logs when there is a mismatch in `planIdsToClientCapabilities`.
- Include subscribedPrices in the log.
=> fix(capability): improve comparison logging

packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/functional-tests/tests/signin/signinBlocked.spec.ts
* Two Playwright tests are regularly failing in smoke tests but passing locally
* Tickets were created to fix these two tests
* Cleanup function on react-conversion/signup was causing even skipped tests to fail
* Mark the tests as fixme so they will be skipped until fixed
* Update the cleanup function for react-conversion/signup so it will only attempt account destroy if an account has in fact been created
Issues 9096, 9226
Failures on recent smoke tests:
https://app.circleci.com/pipelines/github/mozilla/fxa/48195/workflows/bff7e946-9985-402a-8bd3-05f539a7d35e
https://app.circleci.com/pipelines/github/mozilla/fxa/48139/workflows/4deda324-c579-4b64-9e18-206aae6b7625/jo …
=> fix(functional-tests): Mark failing smoke tests as fixme

packages/fxa-customs-server/lib/config/config.js, packages/fxa-customs-server/test/remote/user_defined_rules.js
- We need a custom configuration for rate limiting calls to `/account/credentials/status`
- Introduces a custom rate limiting rule for `getCredentialsStatus`
- Sets the config to allow up to 120 requests per minute and a rate limit interval of 15 minutes
- This call is automatically called in several scenarios, this should provide a generous upper limit of calls, allowing for page refreshes or multiple login attempts, while still preventing blatant abuse of the endpoint.
Closes: FXA-9112
The actual customs check was already in place and can be found [here](https://github.com/mozilla/fxa/blob/30c28bc4a2faa4fb65f5046dadfb47f2877eb3c6/packages/fxa-auth-server/lib/routes/account.ts#L1760).
To manually test this, remove `"customsUrl": "none",` in …
=> task(customs): Configure rate limiting for getCredentialsStatus

packages/browserid-verifier/lib/config.js, packages/fxa-admin-panel/server/config/index.ts, packages/fxa-admin-server/src/config/index.ts, packages/fxa-auth-server/config/index.ts, packages/fxa-content-server/server/lib/beta-settings.js, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/server/lib/routes/get-index.js, packages/fxa-content-server/server/lib/sentry.js, packages/fxa-customs-server/lib/config/config.js, packages/fxa-event-broker/src/config.ts, packages/fxa-graphql-api/src/config.ts, packages/fxa-payments-server/server/config/index.js, packages/fxa-payments-server/src/lib/config.test.ts, packages/fxa-payments-server/src/lib/config.ts, packages/fxa-profile-server/lib/config.js, packages/fxa-shared/sentry/config-builder.ts
- SENTRY_TRACES_SAMPLE_RATE was having no effect on front-end
- Fixes oversight where sample rate wasn't being copied into the config sent to client side
- Stops defaulting tracesSampleRate to 1.0 in  buildSentryConfig(), since this could result in quota exhaustion
=> bug(content): Fix SENTRY_TRACES_SAMPLE_RATE not being applied

packages/functional-tests/pages/resetPasswordReact.ts, packages/functional-tests/tests/react-conversion/resetPassword.spec.ts, packages/fxa-settings/src/components/Banner/en.ftl, packages/fxa-settings/src/components/Banner/index.tsx, packages/fxa-settings/src/components/ConfirmWithLink/index.test.tsx, packages/fxa-settings/src/components/LinkExpiredResetPassword/index.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.test.tsx, packages/fxa-settings/src/pages/Signin/SigninUnblock/index.test.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.test.tsx
* Messages in banner were not read by screen reader
* Add role "status" to banners
* Update English only text string to correct voice-over pronunciation (should not impact other locales)
Closes: #FXA-9007
Testing:
- Create a new account
- Turn on VoiceOver (or other screen reader) on `Confirm signup code` page
- Click "Email new code" and expect the banner message to be read by the screen reader
Additional testing - all banner message on React pages (including error banners) should now be read
=> fix(a11y): Enable screen reading for banner messages

packages/fxa-settings/src/components/FormPasswordWithBalloons/en.ftl, packages/fxa-settings/src/components/FormPasswordWithBalloons/index.test.tsx, packages/fxa-settings/src/components/FormPasswordWithBalloons/index.tsx, packages/fxa-settings/src/components/IconListItem/index.tsx, packages/fxa-settings/src/components/InputPassword/en.ftl, packages/fxa-settings/src/components/InputPassword/index.tsx, packages/fxa-settings/src/components/InputText/index.tsx, packages/fxa-settings/src/components/PasswordInfoBalloon/index.tsx, packages/fxa-settings/src/components/PasswordStrengthBalloon/index.test.tsx, packages/fxa-settings/src/components/PasswordStrengthBalloon/index.tsx, packages/fxa-settings/src/components/Tooltip/index.test.tsx, packages/fxa-settings/src/components/Tooltip/index.tsx, packages/fxa-settings/src/pages/Signup/index.test.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
* The password requirements dialog was not announced by screen readers
* Show/hide password control was not available to keyboard-only users
* Tooltip errors were not read by screen readers
* Add screen reader only password input feedback (positive and negative) to supplement existing visual feedback
* Modifies password visibility toggle to make it accessible w/ keyboard
* Add aria-live and aria-describedby arguments to ensure tooltips are read by screen readers
* Update anchor position of error tooltips for `confirm password` and `age` inputs
* Update styling of age link to nor stretch to full width
* Update tests and fix state update warnings for Signup tests
Closes: #FXA-9004, FXA-9005, FXA-9006
Error states:
Tested with VoiceOver on Mac with Safari …
=> fix(a11y): Improve accessibility of signup form

packages/functional-tests/pages/login.ts, packages/functional-tests/tests/thirdPartyAuth/thirdPartyAuth.spec.ts
- We currently don't run these tests
- Simplfy the tests and run them
Closes: # [FXA-8964](https://mozilla-hub.atlassian.net/browse/FXA-8964)
Previously, these tests tried to go through the entire Google login flow, while this provides good coverage, its very flaky. They also required lots of setup and used a custom gmail account to do the login. The new tests just verify that the Apple and Google login page loads.
Paired with @Trinaa on these
[FXA-8964]: https://mozilla-hub.atlassian.net/browse/FXA-8964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(test): Update Apple/Google third party auth tests

packages/functional-tests/README.md, packages/functional-tests/lib/fixtures/standard.ts, packages/functional-tests/tests/oauth/syncSignIn.spec.ts, packages/functional-tests/tests/postVerify/syncForcePasswordChange.spec.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/functional-tests/tests/react-conversion/syncV3ResetPassword.spec.ts, packages/functional-tests/tests/settings/fxaStatus.spec.ts, packages/functional-tests/tests/signin/signinCached.spec.ts, packages/functional-tests/tests/syncV3/fxDesktopHandshake.spec.ts, packages/functional-tests/tests/syncV3/fxDesktopV3ForceAuth.spec.ts, packages/functional-tests/tests/syncV3/settings.spec.ts, packages/functional-tests/tests/syncV3/signIn.spec.ts, packages/functional-tests/tests/syncV3/signUp.spec.ts, packages/functional-tests/tests/syncV3/signUpWithCWTS.spec.ts, packages/functional-tests/tests/syncV3/signinCached.spec.ts, packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts, packages/functional-tests/tests/syncV3/syncV3ResetPassword.spec.ts
- we want to isolate and assure proper creation and cleanup of `syncBrowserPages`
- refactors common code in before, after and test methods to playwrite test [fixtures](https://playwright.dev/docs/test-fixtures)
Closes: # FXA-9137
=> refactor(functional-tests): creation and cleanup of Sync browser pages to a fixture

packages/functional-tests/pages/products/index.ts, packages/functional-tests/tests/subscription-tests/subscription.spec.ts
- We want to maximize test coverage while respecting third party interface boundaries
- adds a test that assures when users click on the PayPal payment option they are directed to a PayPal popup
N/A (Relates To #FXA-9180)
Example error message:
- Related PR: https://github.com/mozilla/fxa/pull/16477
=> test(functional-tests): add minimum coverage PayPal test

packages/fxa-graphql-api/src/gql/account.resolver.spec.ts, packages/fxa-graphql-api/test/security-events.sql
- We could get in state where tests would fail
- Makes sure the test database is inline with the latest state
=> bug(graphql): Fix mismatch in test state

libs/payments/legacy/src/lib/plan-mapper.util.spec.ts, libs/payments/legacy/src/lib/plan-mapper.util.ts, libs/payments/legacy/src/lib/stripe-mapper.service.spec.ts, libs/payments/legacy/src/lib/stripe-mapper.service.ts, packages/fxa-admin-server/src/config/index.ts, packages/fxa-admin-server/src/subscriptions/stripe.service.ts, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/test/local/payments/capability.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-shared/payments/stripe.ts
- We want a seamless cutover from using Stripe metadata to Contentful.
- Adds a boolean feature flag to use Contentful data directly.
- Adds flag to comparison sections.
- Updates tests where applicable.
Closes FXA-9062
=> feat(auth): add boolean flag that skips Stripe comparison and returns Contentful

packages/fxa-auth-server/lib/routes/linked-accounts.ts, packages/fxa-auth-server/lib/routes/utils/third-party-events.ts, packages/fxa-auth-server/test/local/routes/linked-accounts.js
- Apple events don't specify JWT in header, they pass it as a POST param
- Removes the jwt authentication check, manually parses payload to get jwt for Apple
- Adds additional logging to both Apple and Google events
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9068
This PR should fix Apple events, however I could not simulate a Google event happening so opted to get more logs to debug them.
=> fix(events): Fix bugs for third party auth events

packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/app/scripts/views/mixins/signin-mixin.js, packages/fxa-content-server/app/tests/spec/views/mixins/signin-mixin.js, packages/fxa-content-server/server/lib/beta-settings.js, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/server/lib/routes/react-app/index.js, packages/fxa-content-server/server/lib/routes/react-app/types.ts, packages/fxa-content-server/tests/server/routes/react-app.js, packages/fxa-graphql-api/src/gql/session.resolver.spec.ts, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/models/integrations/oauth-integration.ts, packages/fxa-settings/src/pages/InlineRecoverySetup/container.test.tsx, packages/fxa-settings/src/pages/InlineRecoverySetup/container.tsx, packages/fxa-settings/src/pages/InlineRecoverySetup/gql.ts, packages/fxa-settings/src/pages/InlineRecoverySetup/index.stories.tsx, packages/fxa-settings/src/pages/InlineRecoverySetup/index.test.tsx, packages/fxa-settings/src/pages/InlineRecoverySetup/index.tsx, packages/fxa-settings/src/pages/InlineTotpSetup/container.test.tsx, packages/fxa-settings/src/pages/InlineTotpSetup/container.tsx, packages/fxa-settings/src/pages/InlineTotpSetup/gql.ts, packages/fxa-settings/src/pages/InlineTotpSetup/index.stories.tsx, packages/fxa-settings/src/pages/InlineTotpSetup/index.test.tsx, packages/fxa-settings/src/pages/InlineTotpSetup/index.tsx, packages/fxa-settings/src/pages/InlineTotpSetup/mocks.ts, packages/fxa-settings/src/pages/Signin/index.tsx
Because:
- a RP can optionally require 2FA from the user who is signing in
This commit:
- implements "inline" TOTP setup after the user successfully signed in but before redirecting back to the RP
Sorry about the draft quality but I have a hard stop and want to put something up to get feedback.
This is not quite feature complete.  It's missing a couple things.
- The redirect back to the RP is not done.  It's being implemented in FXA-6518.  We'll need to incorporate that in once it's ready.
- Since the flow is not completely done we don't have a functional test.  Lauren said we can do that in a follow-up; I don't know the issue number.
I tailed the auth-server and content-server logs while I stepped through the flow in Backbone and I didn't notice any inline-totp specific events, so there …
=> feat(react): add inline totp setup

packages/fxa-admin-server/src/subscriptions/stripe.service.spec.ts
- While running Admin Server unit tests the "Stripe Auth Error" warning would show up after stripe.service.spec.ts tests were run.
- Replace StripeFactory with mockStripeFactory for unit tests.
=> fix(admin): use mock stripe factory in unit test

packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/test/local/payments/capability.js
- No longer require sentry errors when Capability, Contentful or Eligibility managers are not found.
- Removes Sentry errors if relevant managers aren't found.
Closes: #FXA-9213
=> feat(auth): remove logging if contentful not found

packages/functional-tests/pages/index.ts, packages/functional-tests/pages/legal.ts, packages/functional-tests/pages/privacy.ts, packages/functional-tests/pages/termsOfService.ts, packages/functional-tests/tests/react-conversion/legal.spec.ts
* we want to stabilize the functional test suite to improve it's success rate
* renames tests
* refactors the legal tests to use Page objects
* uses fixme test annotations to skip tests requiring maintenance
* removes uses of waitForTimeout and waitForSelector functions
* removes commented-out code
Relates to FXA-8960 & FXA-9280
=> refactor(functional-tests): legal tests

libs/payments/paypal/src/lib/paypal.manager.spec.ts, libs/payments/paypal/src/lib/paypal.manager.ts, libs/payments/stripe/src/index.ts, libs/payments/stripe/src/lib/stripe.client.config.ts, libs/payments/stripe/src/lib/stripe.client.spec.ts, libs/payments/stripe/src/lib/stripe.client.ts, libs/payments/stripe/src/lib/stripe.constants.ts, libs/payments/stripe/src/lib/stripe.error.ts, libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.manager.ts, packages/fxa-auth-server/lib/payments/paypal/helper.ts
-  If amount is less than minimum amount (see current processZeroInvoice implementation for constant), call processZeroInvoice
- If amount is greater than minimum amount, call PaypalManager processNonZeroInvoice
- Per the ticket, we are to call the existing PaypalHelper processInvoice. However, we are unable to do so, and instead a comment has been added to remind us to update this in M3b.
- Leave a todo comment regarding migrating processInvoice rather than calling it directly
Closes: FXA-8942
=> feat(payments-paypal): Create PayPal processInvoice, processZeroInvoice, and processNonZeroInvoice

packages/fxa-payments-server/server/config/index.js
- The doc string still referenced Firefox Accounts
- Updates the doc string to say Mozilla Accounts
Closes: FXA-8602
Note that FXA-8602 also calls out another string the auth-server's config that has already been fixed. So that part of the ticket is not applicable.
=> task(payments): Fix doc on accountsCdn config

packages/functional-tests/tests/react-conversion/legal.spec.ts
- The “Back” button is intended to take users to the previous page and is a relic of backbone
- Removes the tests responsible for verifying logic that assures the button stays within the Mozilla domain
Closes: # FXA-9280
=> test(functional-tests): remove tests for back button

libs/payments/cart/src/lib/cart.error.ts, libs/payments/paypal/src/lib/paypal.error.spec.ts, libs/payments/paypal/src/lib/paypal.error.ts, libs/payments/paypal/src/lib/paypal.manager.spec.ts, libs/payments/paypal/src/lib/paypal.manager.ts, libs/payments/paypal/src/lib/paypalCustomer/paypalCustomer.error.ts, libs/payments/paypal/src/lib/paypalCustomer/paypalCustomer.factories.ts, libs/payments/paypal/src/lib/paypalCustomer/paypalCustomer.manager.spec.ts, libs/payments/paypal/src/lib/paypalCustomer/paypalCustomer.manager.ts, libs/payments/paypal/src/lib/paypalCustomer/paypalCustomer.repository.spec.ts, libs/payments/paypal/src/lib/paypalCustomer/paypalCustomer.repository.ts, libs/payments/paypal/src/lib/paypalCustomer/paypalCustomer.types.ts, libs/payments/stripe/src/lib/stripe.error.ts, libs/shared/account/account/src/lib/account.error.ts, libs/shared/contentful/src/lib/contentful.client.spec.ts, libs/shared/contentful/src/lib/contentful.client.ts, libs/shared/db/mysql/account/src/lib/factories.ts, libs/shared/db/mysql/account/src/lib/tests.ts, libs/shared/error/src/lib/error.ts, packages/fxa-auth-server/lib/payments/stripe-firestore.ts
Because:
* We want to be able to interact with the paypalCustomer table from the new libs structure
This commit:
* Adds a paypalCustomer repository
Closes FXA-8888
=> feat(paypal): Add paypal repository

packages/fxa-auth-server/lib/metrics/glean/index.ts, packages/fxa-auth-server/test/local/metrics/glean.ts
Because:
- we want to populate the OAuth client id value in our backend Glean events more reliably
- for OAuth RPs the content-server put the OAuth client id into the service property of the metrics context
This commit:
- uses the service value as the OAuth client id in Glean events if the value is shaped like an OAuth client id
=> fix(metrics): use the service metric value as OAuth client id

.github/dependabot.yml
Because:
* We want some dependencies to be updated together.
This commit:
* Configures groups for the larger dependencies that should be updated together.
=> chore: use dependabot groups to align dep updates

packages/123done/oauth.js
- It is hard to debug when you don't know the error
-Returns a better error when client secret is invalid or missing
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9312
=> chore(client): Show a better error message when client secret on 123done is not valid

packages/functional-tests/tests/oauth/oauthPromptNone.spec.ts, packages/functional-tests/tests/oauth/signUp.spec.ts
- These tests fail in production with new delete account route
- Fixes the test to pass a session token and not run afterEach
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9318
Ran this in production and all passing/skipped as needed
=> chore(tests): Fix production tests

packages/fxa-admin-panel/README.md, packages/fxa-admin-panel/src/components/AppLayout/index.tsx, packages/fxa-admin-panel/src/components/PageAccountSearch/index.tsx, packages/fxa-admin-panel/src/components/PageRelyingParties/index.tsx
- We want this to say Mozilla Accounts
- Updates the readme
- Updates the app layout
- Updates some verbiage on the account search page
- Updates some verbiage on the relying parties page
Closes: FXA-8601
Note that we decided not to make further styling adjustments, since it's just the admin panel, and just dropped this to a 1 pointer.
=> task(admin-panel): Remove 'Firefox Accounts' references

packages/fxa-content-server/app/scripts/models/password_strength/password_strength_balloon.js, packages/fxa-content-server/app/tests/spec/models/password_strength/password_strength_balloon.js
- We did this for Firefox Accounts
- Adds new case for banned names mozillaaccount
- Adds new case for banned names mozilla account
=> task(content): Add Mozilla Account(s) to banned password names

packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/mocks.tsx, packages/fxa-settings/src/pages/Signin/container.test.tsx, packages/fxa-settings/src/pages/Signin/container.tsx, packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signin/interfaces.ts, packages/fxa-settings/src/pages/Signin/mocks.tsx, packages/fxa-settings/src/pages/mocks.ts
- We want test coverage for automatically upgrading to a V2 password
- We want test coverage for signing in with a V2 password
- Adds tests for auto upgrading to a V2 password
- Adds tests for signing with a V2 password
- Adds tests for possible error states when upgrading a password
- Adds option to report apollo errors directly in test output
- Cleans up apollo test client warnings & errors
- Switches to using apollo client's mock provider.
- This was necessary due to the number of gql calls made in these tests
Closes: FXA-9158
=> task(fxa-settings): Add test coverage for key stretching v2 to signin container tests

packages/functional-tests/tests/signin/relyingParties.spec.ts
- The test hangs
- The text has changed on this button
- Removes the 'test.fixme'
- updates the selector text to be 'Continue with Mozilla'
Closes: FXA-8603
New pocket login text:
=> task(functional-tests): Fix button click for pocket login

packages/functional-tests/tests/oauth/syncSignIn.spec.ts, packages/functional-tests/tests/settings/changeEmail.spec.ts, packages/functional-tests/tests/signin/connectAnotherDevice.spec.ts, packages/functional-tests/tests/signin/redirect.spec.ts, packages/fxa-content-server/server/lib/routes/react-app/index.js
Because:
* We previously attempted to roll this out to 100% of users and had to turn it off via feature flag due to a GQL issues. This turns it back down to 15%
This commit:
* Updates fullProdRollout for signup from true to false
Closes FXA-9310
=> task(react): Turn React sign up back to 15%

libs/payments/paypal/src/lib/paypal.manager.spec.ts, libs/payments/paypal/src/lib/paypal.manager.ts
Reference: existing implementation in PayPalHelper.cancelBillingAgreement
Closes: FXA-8937
=> feat(payments-paypal): Create PayPalManager cancelBillingAgreement method

packages/functional-tests/pages/index.ts, packages/functional-tests/pages/settings/index.ts, packages/functional-tests/pages/settings/layout.ts, packages/functional-tests/pages/settings/totp.ts, packages/functional-tests/pages/signinReact.ts, packages/functional-tests/pages/signupReact.ts, packages/functional-tests/tests/oauth/totp.spec.ts, packages/functional-tests/tests/react-conversion/oauthResetPassword.spec.ts, packages/functional-tests/tests/react-conversion/signinTotp.spec.ts, packages/functional-tests/tests/settings/changeEmail.spec.ts, packages/functional-tests/tests/settings/misc.spec.ts, packages/functional-tests/tests/settings/totp.spec.ts, packages/functional-tests/tests/subscription-tests/subscription.spec.ts, packages/functional-tests/tests/syncV3/signIn.spec.ts
- The totp tests are failing in stage and prod and we want to promote stability and sustainability in the functional-tests
- ~Adds a configuration check for the React signInRoutes~
- Adds clarity and splits test concerns by separating and renaming the `add and remove totp` test into two tests.
- Refactors to use page object with auto-retrying assertions and built-in locators (causes cascading changes into other tests):
- oauth/totp.spec.ts
- oauthResetPassword.spec.ts
- changeEmail.spec.ts
- misc.spec.ts
- settings/totp.spec.ts
- subscription.spec.ts
- signIn.spec.ts
Closes #FXA-9178
Relates To #FXA-8960
=> fix(functional-tests): signInTotp tests in stage and prod

libs/payments/stripe/src/lib/stripe.client.spec.ts, libs/payments/stripe/src/lib/stripe.client.ts, libs/payments/stripe/src/lib/stripe.constants.ts, libs/payments/stripe/src/lib/stripe.error.ts, libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.manager.ts
- Part of M3a.
- We want `addTaxIdToCustomer` added to StripeManager.
- See **Other information** below
- Adds aforementioned method to `StripeManager` using existing implementation for reference.
- Updates customer metadata with `taxId` when customer `taxId` does not match incoming `taxId`.
- See **Other information** below
Closes FXA-8944, FXA-8945
After discussing with @julianpoy via Slack, it was decided to update the function to `setCustomerTaxId` and `getCustomerTaxId` respectively. This option would allow more flexibility in future and a function to retrieve a customer's tax id directly.
=> feat(payments-stripe): create StripeManager addTaxIdToCustomer

libs/payments/paypal/src/lib/paypal.manager.spec.ts, libs/payments/paypal/src/lib/paypal.manager.ts, libs/payments/paypal/src/lib/paypalCustomer/paypalCustomer.error.ts, libs/payments/stripe/src/lib/stripe.client.ts, libs/payments/stripe/src/lib/stripe.manager.ts
=> feat(payments-paypal): Create PaypalManager getCustomerBillingAgreementId

.gitignore
- adds the following files to gitignore:
- libs/shared/contentful/src/__generated__/graphql.d.ts
- libs/shared/contentful/src/__generated__/graphql.js
=> fix(git): Ignore shared-contentful generated files

packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/server/lib/routes/react-app/index.js, packages/fxa-graphql-api/src/gql/dto/input/consume-recovery-code.ts, packages/fxa-graphql-api/src/gql/dto/payload/consume-recovery-code.ts, packages/fxa-graphql-api/src/gql/session.resolver.spec.ts, packages/fxa-graphql-api/src/gql/session.resolver.ts, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/pages/InlineRecoverySetup/index.test.tsx, packages/fxa-settings/src/pages/InlineRecoverySetup/index.tsx, packages/fxa-settings/src/pages/InlineTotpSetup/index.test.tsx, packages/fxa-settings/src/pages/InlineTotpSetup/index.tsx, packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/container.test.tsx, packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/container.tsx, packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/gql.ts, packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.stories.tsx, packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.test.tsx, packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.tsx, packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/interfaces.ts, packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/mocks.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/mocks.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/mocks.tsx, packages/fxa-settings/src/pages/Signin/mocks.tsx, packages/fxa-settings/src/pages/Signup/container.test.tsx, packages/fxa-settings/src/pages/mocks.tsx
* We are converting backbone routes to React, and this is the last route to be converted to enable React sign in
* Add signin_recovery_code to routes that can be served with React
* Create container component for SigninRecoveryCode page and add logic to hook up the page
* Add unit tests and update storybook
* Fix error with react import for SigninTotpCode and SigninTokenCode
Closes: #FXA-9082
Enabled page: 
How to test:
- Create a new account and set up Two-factor authentication from /settings (make sure to save backup codes for later!)
- Sign out
- Set `forceGlobally`/`SIGNIN_CONFIRMATION_FORCE_GLOBALLY` to `true` to force the 2FA verification on signin (in auth-server config)
- Sign in with react experiment: …
=> feat(settings): Signin Recovery Code page in React

packages/functional-tests/tests/misc/cookiesDisabled.spec.ts
- The 'cookies disabled › visit verify page with localStorage disabled' test is flaking
- Adds a fixme annotation until the cause can be diagnosed and fixed
Relates To: #FXA-9323
=> test(functional-tests): add fixme annotation to cookies disabled › visit verify page with localStorage disabled

packages/fxa-settings/src/lib/cache.ts, packages/fxa-settings/src/pages/Signin/container.test.tsx, packages/fxa-settings/src/pages/Signin/container.tsx
- We could get in a bad state when there were accounts in local storage but none matched the 'current' account.
- It's unclear if this state would actually occur, but it was observed during development.
- Falls back to the last logged in account and uses that which will prevent the redirect back to content-server, which proved problematic.
Closes: FXA-9084
To test do the following
Scenario 1
- On local host sign up/in for a few accounts
- Then go to local storage, and clear `__fxa_storage.uniqueUserId`
- Now go to the the sign in page `http://localhost:3030/signin?showReactApp=true&fforceExperiment=generalizedReactApp&forceExperimentGroup=react`
- You should see the email you last logged in with, and you should be in the react app.
Scenario 2
- After …
=> task(settings): Handle account chooser edge case in react

.circleci/config.yml, libs/shared/cloud-tasks/src/lib/account-tasks.ts, libs/shared/cloud-tasks/src/lib/account-tasks.types.ts, libs/shared/cloud-tasks/src/lib/cloud-tasks.ts, packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/lib/routes/cloud-tasks.ts, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/scripts/clean-up-partial-account-customer.ts, packages/fxa-auth-server/scripts/cleanup-partial-firestore-customers.ts, packages/fxa-auth-server/scripts/delete-account.ts, packages/fxa-auth-server/scripts/delete-unverified-accounts.ts, packages/fxa-auth-server/test/local/account-delete.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/local/routes/cloud-tasks.js, packages/fxa-auth-server/test/local/routes/validators.js, packages/fxa-auth-server/test/remote/account_create_tests.js
- We want to use the `cloud-tasks` nx lib that introduced last sprint
- Updates account end points to use the nx lib
- Updates CI to include cloud-task emulator
Closes: FXA-9270
I'm not exactly sure what was done to test account deletion in the past. I've done my best to update existing tests and ensure that the cloud-tasks lib is under test.
=> task(auth): Have auth-server use cloud-tasks nx lib 

_scripts/config-fxios.js, packages/fxa-settings/src/lib/channels/firefox.ts, packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/interfaces.ts, packages/fxa-settings/src/pages/Signin/SigninTokenCode/mocks.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.tsx, packages/fxa-settings/src/pages/Signin/container.test.tsx, packages/fxa-settings/src/pages/Signin/container.tsx, packages/fxa-settings/src/pages/Signin/index.stories.tsx, packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signin/index.tsx, packages/fxa-settings/src/pages/Signin/interfaces.ts, packages/fxa-settings/src/pages/Signin/mocks.tsx, packages/fxa-settings/src/pages/Signin/utils.ts, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx, packages/fxa-settings/src/pages/Signup/container.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
Because:
* We are moving from Backbone to React and want to meet parity with Sync functionality
This commit:
* Tweaks config-fxios script since iOS changed directory nesting
* Adds firefox.fxaLogin and firefox.fxaOAuthLogin web channel events where needed; it should talk to the browser with a happy path login, signin_token_code flow, and signin_totp_code flow
* Return unwrapBKey as part of signin callback data for sync
* Always displays password input for Sync (no cached login)
* Adds temp 'hack' (tempHandleSyncLogin) to allow a hard navigate to CAD to work in these flows
* Fixes bug where we were sending fxaLogin instead of fxaCanLinkAccount. Removed these from signin and signup container pages because we send one on the index page and it's causing multiple Sync dialogs
* Renames …
=> feat(react): Add React signin Sync web channel events for fx_desktop_v3 + oauth_webchannel_v1

libs/payments/legacy/src/lib/stripe-mapper.service.spec.ts, libs/payments/paypal/src/lib/paypal.manager.spec.ts, libs/payments/paypal/src/lib/paypal.manager.ts, libs/payments/stripe/src/index.ts, libs/payments/stripe/src/lib/factories/card.factory.ts, libs/payments/stripe/src/lib/factories/customer.factory.ts, libs/payments/stripe/src/lib/factories/invoice-line-item.factory.ts, libs/payments/stripe/src/lib/factories/invoice.factory.ts, libs/payments/stripe/src/lib/factories/plan.factory.ts, libs/payments/stripe/src/lib/factories/price.factory.ts, libs/payments/stripe/src/lib/factories/product.factory.ts, libs/payments/stripe/src/lib/factories/subscription.factory.ts, libs/payments/stripe/src/lib/stripe.client.ts, libs/payments/stripe/src/lib/stripe.client.types.ts, libs/payments/stripe/src/lib/stripe.constants.ts, libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.manager.ts
- We want to override Stripe's types with our own to provide more predictability. See ADR for more details.
- Adds a generic that helps break down required/optional properties, while still allowing us to use Stripe's original types (for nice LSP passthrough!).
Closes: FXA-8891
=> feat(stripe-client): add stripe typings utility type and base types

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/routes/linked-accounts.ts, packages/fxa-auth-server/lib/routes/utils/third-party-events.ts
- This fixes the validation issue with Apple/Google security events
- FxA shouldn't check for the audience, just ensure that token is valid from auth provider
- Ignores audience 
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9315
=> fix(bug): Ignore audience when verifying security token

packages/functional-tests/lib/fixtures/standard.ts, packages/functional-tests/tests/oauth/loginHint.spec.ts, packages/functional-tests/tests/oauth/oauthPermissions.spec.ts, packages/functional-tests/tests/oauth/oauthPromptNone.spec.ts, packages/functional-tests/tests/oauth/scopeKeys.spec.ts, packages/functional-tests/tests/oauth/signUp.spec.ts, packages/functional-tests/tests/oauth/signin.spec.ts, packages/functional-tests/tests/oauth/signinTokenCode.spec.ts, packages/functional-tests/tests/oauth/syncSignIn.spec.ts, packages/functional-tests/tests/oauth/webchannel.spec.ts, packages/functional-tests/tests/postVerify/forcePasswordChange.spec.ts, packages/functional-tests/tests/postVerify/syncForcePasswordChange.spec.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/functional-tests/tests/settings/changeEmail.spec.ts, packages/functional-tests/tests/settings/fxaStatus.spec.ts, packages/functional-tests/tests/signUp/signUpWithCode.spec.ts, packages/functional-tests/tests/signin/signIn.spec.ts, packages/functional-tests/tests/signin/signinBlocked.spec.ts, packages/functional-tests/tests/signin/signinCached.spec.ts, packages/functional-tests/tests/syncV3/fxDesktopHandshake.spec.ts, packages/functional-tests/tests/syncV3/settings.spec.ts, packages/functional-tests/tests/syncV3/signIn.spec.ts, packages/functional-tests/tests/syncV3/signUp.spec.ts, packages/functional-tests/tests/syncV3/signUpWithCWTS.spec.ts, packages/functional-tests/tests/syncV3/signinCached.spec.ts, packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts
- we want to isolate and assure proper set up and tear down for our email/accounts
- refactors common code in before, after and test methods to playwright test [fixtures](https://playwright.dev/docs/test-fixtures)
Closes: [FXA-8984](https://mozilla-hub.atlassian.net/browse/FXA-8984)
This is a new PR for the same requirements as https://github.com/mozilla/fxa/pull/16594. All the review comments have been incorporated in this new PR from the old PR. The only reason for discarding the old PR were the merge conflicts which were not getting resolved.
[FXA-8984]: https://mozilla-hub.atlassian.net/browse/FXA-8984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
=> test(functional): create email fixtures for hooks

apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/error/page.tsx, apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/page.tsx, apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/success/page.tsx, apps/payments/next/app/[locale]/[offeringId]/checkout/layout.tsx, apps/payments/next/app/[locale]/[offeringId]/checkout/new/page.tsx, apps/payments/next/app/[offeringId]/checkout/new/page.tsx, apps/payments/next/app/_lib/apiClient.ts, apps/payments/next/app/_lib/stubs.ts, apps/payments/next/app/api/auth/[...nextauth]/route.ts, apps/payments/next/app/layout.tsx, apps/payments/next/app/page.tsx, apps/payments/next/auth.config.ts, apps/payments/next/auth.ts, apps/payments/next/jest.config.ts, apps/payments/next/next.config.js, apps/payments/next/postcss.config.js, apps/payments/next/tailwind.config.ts, apps/payments/next/tests/app/page.test.tsx, libs/payments/ui/src/index.ts, libs/payments/ui/src/lib/server/purchase-details.tsx, libs/payments/ui/src/lib/server/terms-and-privacy.tsx, libs/payments/ui/src/lib/utils/helpers.ts, libs/payments/ui/src/lib/utils/terms-and-privacy.ts, libs/payments/ui/src/server.ts, libs/payments/ui/src/styles/index.css, libs/shared/l10n/src/lib/determine-locale.ts
- To access certain path parameters from `layout.tsx`
Current URL
`https://subscriptions.firefox.com/{offering_identifier}/{intent}/{cart_id}/{page_name}?interval=&promotion_code=&experiment=&locale=`
Proposed URL
`https://subscriptions.firefox.com/{locale}/{offering_identifier}/{intent}/{interval}/{cart_id}/{page_name}?promotion_code=&experiment=`
Closes: FXA-9367
=> fix(payments-next): Move searchParams to params

libs/payments/stripe/src/lib/stripe.client.ts
- Customer.tax should always be expanded.
- Expands Customer.tax for updateCustomer calls.
=> fix(stripe-client): fix updateCustomer tax expand

packages/fxa-auth-server/lib/metricsCache.ts
- Auth server failed to start
- Converts metricsCache.js to typescript, which supports the export syntax
Closes: FXA-9372
This can be validated by locally by doing the following from the root of the mono repo.
`nx build fxa-auth-server`
`cd packages/fxa-auth-server/dist/packages/fxa-auth-server`
`NODE_ENV=dev node bin/key_server.js`
Observe that server starts up cleanly. If you were to do the same thing on main, the following error would occur on startup:
```
3
export class MetricsRedis extends RedisShared {
^^^^^^
SyntaxError: Unexpected token 'export'
at internalCompileFunction (node:internal/vm:77:18)
at wrapSafe (node:internal/modules/cjs/loader:1288:20)
at …
```
=> task(auth): Convert metricsCache.js to typescript

apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/error/page.tsx, apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/page.tsx, apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/success/page.tsx, apps/payments/next/app/[locale]/[offeringId]/checkout/layout.tsx, libs/shared/l10n/src/lib/determine-locale.ts
=> fix(payments-next): Page - Revise checkout layout

packages/fxa-settings/src/components/FormPasswordWithBalloons/index.test.tsx, packages/fxa-settings/src/components/FormPasswordWithBalloons/index.tsx
Because:
* We want to disallow space-only passwords
This commit:
* Includes a bandaid fix for React signup to disallow this by showing the "password must be at least 8 characters" error message. This is to meet parity with Backbone and we will revisit PW requirements in FXA-7482
closes FXA-9301
---
See [this thread in Slack](https://mozilla.slack.com/archives/C04LVV8V8BA/p1711643764605569). In Backbone this shows up as a tooltip after the user submits but here it will show in the PW balloon until we've decided how we want to do this. Backbone doesn't do a `trim()` option (it allows a trailing space at the end of a 7-character input, making it 8) but the check for a full empty PW does get converted to an empty string at some point during submit validation.
=> fix(signup): Disallow space-only passwords for React signup

packages/fxa-auth-server/lib/routes/auth-schemes/hawk-fxa-token.js, packages/fxa-auth-server/lib/server.js, packages/fxa-auth-server/package.json, packages/fxa-auth-server/test/client/api.js, packages/fxa-auth-server/test/local/routes/auth-schemes/hawk-fxa-token.js, packages/fxa-auth-server/test/local/server.js, packages/fxa-auth-server/test/remote/misc_tests.js, packages/fxa-auth-server/test/remote/oauth_tests.js, yarn.lock
- We are planning on phasing out support for Hawk authentication
- We want our internal services to talk to each other by sending a Hawk like token
- Adds a new authentication stragey `hawk-fxa-token`, this checks for a Hawk like token ie `Hawk id="<token id>"`, extracts the id and then does the token lookup
- Does not validate the Hawk header
- Removes the Hawk library from fxa-auth-server
- Updates test
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9282
=> feat(hawk): Add auth strategy for Hawk and FxA Bearer token support

libs/shared/l10n/src/index.ts, libs/shared/l10n/src/lib/localizer/localizer.base.ts, libs/shared/l10n/src/lib/localizer/localizer.client.bindings.ts, libs/shared/l10n/src/lib/localizer/localizer.client.spec.ts, libs/shared/l10n/src/lib/localizer/localizer.client.ts, libs/shared/l10n/src/lib/localizer/localizer.provider.ts, libs/shared/l10n/src/lib/localizer/localizer.server.bindings.ts, libs/shared/l10n/src/lib/localizer/localizer.server.ts, libs/shared/l10n/src/server.ts
- Need a Localizer implementation that can be used in a react client component.
- Creates LocalizerClient which instantiates an instance of ReactLocalization to be used by the LocalizationProvider.
Just missing some tests currently skipped.
=> feat(l10n): add localizer client

packages/functional-tests/pages/login.ts, packages/functional-tests/pages/relier.ts, packages/functional-tests/tests/oauth/loginHint.spec.ts, packages/functional-tests/tests/oauth/signin.spec.ts
- Prod oauth test was failing https://app.circleci.com/pipelines/github/mozilla/fxa/48563/workflows/9f57915b-6f6a-46c7-9228-795dd85e9fc5/jobs/489892/tests
- Replaces the wrong header function with the correct header function
Closes: FXA-9304
I tried fixing the header function to use locator object but it was breaking around 15 tests (see the previous commit) as its been used in various places in login page object. We already have a follow up task [here](https://mozilla-hub.atlassian.net/browse/FXA-9379) to address this issue and to convert all remaining selector objects to locator objects.
=> fix(test): fix prod oauth test

libs/payments/legacy/src/lib/stripe-mapper.service.spec.ts, libs/payments/paypal/src/lib/paypal.manager.spec.ts, libs/payments/stripe/src/index.ts, libs/payments/stripe/src/lib/factories/api-list.factory.ts, libs/payments/stripe/src/lib/factories/card.factory.ts, libs/payments/stripe/src/lib/factories/customer.factory.ts, libs/payments/stripe/src/lib/factories/invoice-line-item.factory.ts, libs/payments/stripe/src/lib/factories/invoice.factory.ts, libs/payments/stripe/src/lib/factories/plan.factory.ts, libs/payments/stripe/src/lib/factories/price.factory.ts, libs/payments/stripe/src/lib/factories/product.factory.ts, libs/payments/stripe/src/lib/factories/subscription.factory.ts, libs/payments/stripe/src/lib/stripe.client.spec.ts, libs/payments/stripe/src/lib/stripe.client.ts, libs/payments/stripe/src/lib/stripe.client.types.ts, libs/payments/stripe/src/lib/stripe.config.ts, libs/payments/stripe/src/lib/stripe.error.ts, libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.manager.ts
Ref: see existing implementation in StripeHelper.getTaxIdForCustomer
Closes: FXA-8946
=> feat(payments-stripe): Create StripeManager getTaxIdForCurrency

packages/fxa-settings/src/components/FormPasswordWithBalloons/index.test.tsx, packages/fxa-settings/src/lib/password-validator.ts
Because:
This Commit:
- We should not allow obvious passwords
- Adds mozillaccount the BANNED_SERVICE_NAMES
- Adds mozilla account to the BAND_SERVICE_NAMES
Closes: FXA-9411
This was discovered while validating a similar change for the content server in #16574.
=> task(settings): Add 'mozilla account' as a common password

packages/fxa-content-server/app/scripts/lib/sentry.js, packages/fxa-payments-server/src/lib/sentry.js, packages/fxa-shared/sentry/browser.ts
- FID (First Input Delay) metric is going away
- Turns on INP (Interaction to Next Paint) in the sentry's browser tracing integration
Closes: FXA-9278
We can now see INP metrics in sentry! (Note, I've set the environment to local and created this metrics by running fxa locally)
Turns out INP is not currently supported by firefox  :cry:... So when testing this locally I had to use chrome.
=> task(content,payments,settings): Enable sentry INP

libs/payments/stripe/src/lib/stripe.client.spec.ts, libs/payments/stripe/src/lib/stripe.client.ts, libs/payments/stripe/src/lib/stripe.client.types.ts, libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.manager.ts
* Our naming in our client needlessly renamed Stripe methods making it a little harder to understand what is going on
* Updates our naming to match what Stripe has, so that it's easier to look stuff up.
Closes FXA-9019
=> feat(payments-stripe): add new stripe methods and update naming

packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.test.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx, packages/fxa-shared/metrics/glean/web/index.ts
Because:
- we want a frontend Glean event for successful registration
This commit:
- adds the event and emit it when the user successfully verify their signup code
=> feat(metrics): add reg_success_view frontend Glean event

packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-webchannel-v1.js, packages/fxa-content-server/app/scripts/views/mixins/connect-another-device-mixin.js, packages/fxa-content-server/app/tests/spec/models/auth_brokers/oauth-webchannel-v1.js, packages/fxa-content-server/app/tests/spec/views/connect_another_device.js
…fter login
Because:
* This is the behavior for desktop v3 which we want to mimic; otherwise the behavior halts on signin
This commit:
* Updates afterSignIn method for oauth-webchannel-v1 broker
fixes FXA-9100
---
This appears to work as expected for me with React.
Testing locally:
* Update your configs (auth-server and content-server) to [match this diff](https://github.com/mozilla/fxa/commit/96c6b297c1731d0571c09395dbe128040fa20c85). Restart the stack
* Run `FXA_DESKTOP_CONTEXT=oauth_webchannel_v1 yarn start` in dev launcher, (make sure FF is latest), change `identity.fxaccounts.oauth.enabled` to `true` and set `identity.fxaccounts.contextParam` to `oauth_webchannel_v1`
* Sign in with Sync, try React (with params) and Backbone signin. See Sync signin is successful and CAD is shown
=> fix(sync): Send Fx desktop context=oauth_webchannel_v1 users to CAD after login

docs/adr/00042-use-node-oidc-for-oauth.md
- We want to move away from our custom oauth implemention and use something that is more actively supported
- Adds ADR for using node oidc
- From the meeting we want to move forward with doing this work, the ADR however does not define the timeline
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7219
=> feat(adr): Add ADR for using node oidc for oauth

packages/functional-tests/pages/baseTokenCode.ts, packages/functional-tests/pages/confirmSignupCodePage.ts, packages/functional-tests/pages/index.ts, packages/functional-tests/pages/layout.ts, packages/functional-tests/pages/signinTotpCode.ts, packages/functional-tests/pages/signinUnblock.ts, packages/functional-tests/tests/signUp/signUpWithCode.spec.ts, packages/functional-tests/tests/syncV3/signIn.spec.ts, packages/functional-tests/tests/syncV3/signUp.spec.ts, packages/functional-tests/tests/syncV3/signUpWithCWTS.spec.ts, packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts
- The tests were manually going through a sign up flow
- Doing so messed with react conversion testing, since the sign up implementation could vary
- Depending on react rollout rate. i.e Sometimes the the app would route an end user through
- Backbone, and sometimes it would route an end user through react.
- There were also some potential improvements that may improve clarity of these tests.
- Uses target.auth.signUp, which uses the auth-client to generate a signup, thereby isolating the sync sign in tests and fixing the issue with react react rollout.
- Cleans up tests by:
- Renaming some tests to make their intent more clear.
- Introducing a BaseTokenCode page that facilitates code reuse across pages that require a token code.
- Adding a 'checkUrlPath' method to BaseTokenCode. This …
=> task(functional): Modify syncV3 tests not use target.auth.signUp

packages/fxa-auth-server/lib/monitoring.js, packages/fxa-auth-server/lib/sentry.js
- We were seeing errors show up in Sentry that would typically be ignored.
- We were seeing errors show up in Sentry that lacked extra context set by our reportError function
- We were able to determine that instrumentations libraries that appear to have show up around the time we added tracing started propagating errors.
- Adds an extra flag to our errors we capture
- Ignores errors that aren't being captured by our code (ie errors being captured by instrumentation libraries).
Closes: FXA-9252
=> bug(auth): Regression in reporting known errors to sentry

packages/functional-tests/lib/metrics.ts, packages/functional-tests/tests/subscription-tests/subscription.spec.ts
- Initial view event for an existing customer with a new subscription occasionally shows up more than once.
- Removes unnecessary code from existing test.
- Adds additional check that final order of events are for existing customer.
- Adds sanity check that initial view event is not recorded multiple times.
Closes FXA-9322
=> fix(functional-test): update flaky metrics test with duplicate view event

libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.manager.ts
* We want to be able to cancel subscriptions from non-stripe lib
* Adds a stripe manager method to do so
Closes FXA-9027
=> feat(payments-stripe): add cancelSubscription to stripe manager

packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/test/local/account-delete.js, packages/fxa-auth-server/test/local/routes/account.js
Because:
- we need to know whose account we deleted
This commit:
- adds the account's primary email address and verified status to the 'account.deleted' activity event
- simplifies the logging by having it in one place
=> fix(metrics): add email to account.deleted activity event

packages/functional-tests/lib/fixtures/standard.ts, packages/functional-tests/pages/login.ts, packages/functional-tests/pages/settings/deleteAccount.ts, packages/functional-tests/tests/oauth/loginHint.spec.ts, packages/functional-tests/tests/oauth/oauthPermissions.spec.ts, packages/functional-tests/tests/oauth/oauthPromptNone.spec.ts, packages/functional-tests/tests/oauth/scopeKeys.spec.ts, packages/functional-tests/tests/oauth/signUp.spec.ts, packages/functional-tests/tests/oauth/signin.spec.ts, packages/functional-tests/tests/oauth/signinTokenCode.spec.ts, packages/functional-tests/tests/oauth/syncSignIn.spec.ts, packages/functional-tests/tests/oauth/webchannel.spec.ts, packages/functional-tests/tests/postVerify/forcePasswordChange.spec.ts, packages/functional-tests/tests/postVerify/syncForcePasswordChange.spec.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/functional-tests/tests/settings/deleteAccount.spec.ts, packages/functional-tests/tests/settings/fxaStatus.spec.ts, packages/functional-tests/tests/settings/totp.spec.ts, packages/functional-tests/tests/signUp/signUp.spec.ts, packages/functional-tests/tests/signUp/signUpWithCode.spec.ts, packages/functional-tests/tests/signin/signIn.spec.ts, packages/functional-tests/tests/signin/signinBlocked.spec.ts, packages/functional-tests/tests/signin/signinCached.spec.ts, packages/functional-tests/tests/syncV3/fxDesktopHandshake.spec.ts, packages/functional-tests/tests/syncV3/settings.spec.ts, packages/functional-tests/tests/syncV3/signIn.spec.ts, packages/functional-tests/tests/syncV3/signUp.spec.ts, packages/functional-tests/tests/syncV3/signUpWithCWTS.spec.ts, packages/functional-tests/tests/syncV3/signinCached.spec.ts, packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts
* we want to assure that all emails are created and removed in a re-usable and consistent way
* updates tests to use the email fixture when creating emails
* standardizes email prefix strings into constants
* re-structures some test modules to only create the emails needed for tests
* isolates email logic by removing references from test.beforeEach
* cleans up linter errors
* fixes cleanup of blocked emails
* a workaround deleting accounts from the settings page was applied to the impacted 8 test cases, rather than the fixture, since not having `Page` dependencies is necessary for planned fixture improvements 
Closes: # FXA-9359
Any other information that is …
=> refactor(functional-tests): move createEmail from login to email fixture

libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.manager.ts
=> feat(payments-stripe): Create StripeManager cancelIncompleteSubscription

packages/functional-tests/pages/login.ts, packages/functional-tests/tests/oauth/oauthPermissions.spec.ts, packages/functional-tests/tests/oauth/oauthPromptNone.spec.ts, packages/functional-tests/tests/oauth/signUp.spec.ts, packages/functional-tests/tests/signUp/signUp.spec.ts, packages/functional-tests/tests/signin/signIn.spec.ts, packages/functional-tests/tests/signin/signinBlocked.spec.ts, packages/functional-tests/tests/signin/signinCached.spec.ts, packages/functional-tests/tests/syncV3/settings.spec.ts, packages/functional-tests/tests/syncV3/signinCached.spec.ts
* there were missing awaits, which were fixed in 698210b, and tests were annotated with fixme 
* removes the fixme annotation
* conforms the signUpCodeHeader and signInCodeHeader to accessors in login.ts
Closes: # FXA-9194
=> fix(functional-tests): remove fixme for missing awaits

apps/payments/next/app/%5F_lbheartbeat__/route.ts, apps/payments/next/instrumentation.ts, apps/payments/next/next.config.js, libs/payments/ui/src/lib/nestapp/app.ts, package.json, yarn.lock
- Want to use Next.js instrumentation featuer to start NestApp on Next.js server startup.
- Upgrades Next.js to version 14.2 which includes intrumentation fixes.
- Adds instrumentation logic.
Co-authored-by: @bbangert 
=> feat(next): use next 14.2 instrumentation

packages/fxa-content-server/server/config/local.json-dist, packages/fxa-content-server/server/lib/beta-settings.js, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-settings/src/lib/config.ts
* We want to be able to switch the reset password with code functionality on/off with a feature flag
* Add a `resetPasswordWithCode`/`FEATURE_FLAGS_RESET_PWD_WITH_CODE` feature flag and make it available in fxa-settings with default set to false
Closes: #FXA-7909
=> feat(content): Add feature flag for password reset with code

libs/payments/ui/src/lib/actions/restartCart.ts, libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts, libs/payments/ui/src/lib/nestapp/validators/RestartCartActionArgs.ts
- We need a server action to restart the cart.
- Adds a simple server action to restart the cart.
Closes FXA-8899
Relates to: https://github.com/mozilla/fxa/pull/16684
=> feat(payments-ui): add restartCart server action

packages/fxa-payments-server/package.json
- Lint script was accidentally removed from fxa-payments-server.
- Readd lint script to fxa-payments-server.
=> chore(payments): readd lint to fxa-payments-server

packages/fxa-settings/src/lib/integrations/integration-factory.ts, packages/fxa-settings/src/lib/oauth/hooks.tsx
Because:
* We have validated clientInfo.redirectUri, but not integration.data.redirectUri, and want to "check" the clientInfo value only
This commit:
* Makes clientInfo.redirectUri the only check when referencing the redirect_uri
=> fix(oauth/react): Avoid directly referencing integration redirectUri

libs/shared/cloud-tasks/src/lib/cloud-tasks.factories.ts, libs/shared/cloud-tasks/src/lib/cloud-tasks.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/test/local/routes/account.js
- Accounts were not being fully deleted
- Since we do not use a keyfile, the check on whether or not the queue was enabled did not pass, and the explicit check to run in stage/prod was lost in the refactor
- Removes the queueEnabled flag check entirely. (Now that a local emulator is present we can assume the queue should always be available.)
- Adds back in the fallback option to the CloudTasksClient, which indicates the client should use https instead of grcp, which has proven to be a more reliable setting.
Closes: FXA-9471
=> bug(auth): Accounts aren't fully deleted

packages/fxa-auth-server/lib/metrics/events.js
* Geo is not always guaranteed to be present on request.
* Fixes an issue with typing in a JS file related to geo not being present.
Closes FXA-8571
=> fix(auth): support no geo present on request

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/error.js, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/lib/routes/sign.js, packages/fxa-auth-server/test/local/routes/sign.js
- We no longer support browserid and want to start disabling this route
- Adds a config to specify a disable rollout rate
- Based on our content server experiment enrollment function (hash user constant value, convert to 0-1 value, check if lower than rollout rate)
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9394
=> chore(routes): Add config to disable certificate sign route by user email

packages/fxa-settings/src/pages/Signin/container.test.tsx, packages/fxa-settings/src/pages/Signin/container.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx
Because:
* We should check local storage to see if an account already has an existing session token if the email is given via query param or router state
This commit:
* Removes newly added temp code that removes the 'email' param before navigating to this page during the inline TOTP flow, as it was a bandaid
* Always reads from local storage in Signin, because if the email is provided we want to see if a session token already exists for cached view and otherwise we want to use the account in local storage
fixes FXA-9435
---
I mentioned [here](https://github.com/mozilla/fxa/pull/16665#issuecomment-2047859197) that this was causing 15 test failures but that's not correct, seems like a lot of them were coming from `fxa-shared` needing to be rebuilt.
You can test this (basically checking we …
=> refactor(signin): Check for matching cached account if 'email' is provided

packages/fxa-auth-server/lib/payments/paypal/helper.ts, packages/fxa-auth-server/scripts/cancel-subscriptions-to-plan.ts, packages/fxa-auth-server/scripts/cancel-subscriptions-to-plan/cancel-subscriptions-to-plan.ts, packages/fxa-auth-server/test/local/payments/paypal.js, packages/fxa-auth-server/test/scripts/cancel-subscriptions-to-plan.ts
* We want to be able to refund Paypal invoices automatically
* Adds Paypal invoice refunds to plan cancellation script
Closes FXA-9198
=> feat(auth): add paypal refund behavior to subscription canceller

packages/functional-tests/lib/fixtures/standard.ts, packages/functional-tests/tests/react-conversion/signInRelyingParties.spec.ts, packages/functional-tests/tests/signin/connectAnotherDevice.spec.ts, packages/functional-tests/tests/signin/redirect.spec.ts, packages/functional-tests/tests/signin/relyingParties.spec.ts, packages/functional-tests/tests/signin/signIn.spec.ts, packages/functional-tests/tests/signin/signinBlocked.spec.ts, packages/functional-tests/tests/signin/signinCached.spec.ts
* we want to promote stability and sustainability in the functional-tests
* fixes linting errors and formatting
* removes the fixme from 'relyingParties.spec.ts > severity-1 #smoke > can login to addons'
* fixes 'relyingParties.spec.ts > severity-1 #smoke > can login to monitor'
* removes outdated testrail links
* propogates syncBrowserPages fixture
Closes: #FXA-8962
- A follow-up task was created to address the remaining playwright/no-wait-for-timeout linter errors and the flake that they cause(see FXA-9490)
=> test(functional-tests): audit signin

apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/error/page.tsx, apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/layout.tsx, apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/start/page.tsx, apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/success/page.tsx, apps/payments/next/app/_lib/apiClient.ts, libs/payments/ui/jest.config.ts, libs/payments/ui/project.json, libs/payments/ui/src/lib/actions/getCartOrRedirect.ts, libs/payments/ui/src/lib/nestapp/validators/SetupCartActionArgs.ts, libs/payments/ui/src/lib/utils/get-cart.spec.ts, libs/payments/ui/src/lib/utils/get-cart.ts, libs/payments/ui/src/lib/utils/types.ts, libs/payments/ui/src/server.ts, libs/payments/ui/tsconfig.json, libs/payments/ui/tsconfig.spec.json
- Pages were still calling mock get cart
- Adds getCartOrRedirect to all pages
- Redirects to appropriate page if cart.state does not much current page
Closes: #FXA-9039
=> feat(cart): add get cart action to pages

packages/fxa-event-broker/src/client-capability/client-capability.service.spec.ts, packages/fxa-event-broker/src/client-capability/client-capability.service.ts, packages/fxa-event-broker/src/client-webhooks/client-webhooks.service.spec.ts, packages/fxa-event-broker/src/client-webhooks/client-webhooks.service.ts, packages/fxa-event-broker/src/pubsub-proxy/pubsub-proxy.controller.spec.ts, packages/fxa-event-broker/src/pubsub-proxy/pubsub-proxy.controller.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.spec.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.ts, packages/fxa-event-broker/src/queueworker/service-notification.interface.ts
- Errors used be captured by calling this.log.error, but aren't anymore.
- Seems like queue processing errors aren't showing up in Sentry
- Calls Sentry.captureError anywhere log.error is invoked. 
This was mentioned in passing while discussing while discussing event broker changes for opt in metrics.
=> bug(event-broker): Make sure errors are sent to sentry

libs/payments/paypal/src/lib/paypal.manager.in.spec.ts, libs/payments/paypal/src/lib/paypalCustomer/paypalCustomer.manager.in.spec.ts, libs/payments/stripe/src/lib/accountCustomer/accountCustomer.manager.in.spec.ts, libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/shared/account/account/src/lib/account.manager.in.spec.ts
- [https://jestjs.io/docs/tutorial-async#error-handling](https://jestjs.io/docs/tutorial-async#error-handling)
=> fix(tests): Add expect.assertions for tests with `.rejects`

libs/payments/stripe/src/lib/stripe.client.spec.ts, libs/payments/stripe/src/lib/stripe.client.ts
- Creates `subscriptionsUpdate` method in StripeClient 
- Return a subscription object of the same type as the subscriptionsCreate method.
Closes: FXA-9452
=> feat(payments-stripe): Add subscriptionsUpdate method to StripeClient

libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.manager.ts
- Adds `StripeManager.updateSubscription`
- Should accept any valid subscription update options that Stripe supports
- Passes call through to subscriptions update method in the stripe client.
- Add test to verify pass-through of call
Closes: FXA-9453
=> feat(payments-stripe): Add updateSubscription to StripeManager

package.json, yarn.lock
Because:
* We want to use the latest version of next.
This commit:
* Updates next to 14.2.3.
=> chore: bump next to 14.2.3

.nxignore
- Builds were failing with a 'ProjectsWithConflictingNamesError: The following projects are defined in multiple locations'
- Adds folders that might contain rogue project.json files to the nx ignore list
Working locally now:
To test locally add version.json to packages folder with this:
`{ "version": { "version": "v0.0.0" } }`
Then run `./.circleci/docker-build-fxa.sh  9624cf31-6134-4eba-bea4-1ed71f2d66d7`
=> bug(nx): Fix nx build failures in docker

libs/payments/ui/src/lib/actions/getPayPalCheckoutToken.ts, libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts, libs/payments/ui/src/lib/nestapp/validators/GetPayPalCheckoutTokenArgs.ts
- We need a server action to get PayPal Checkout token.
- Adds server action to get PayPal Checkout token.
Closes FXA-8933
=> feat(payments-ui): create getPayPalCheckoutToken action

libs/shared/otp/src/lib/otp.ts, packages/fxa-auth-server/lib/routes/password.ts
Because:
* We want to use TypeScript and async/await.
* Otp Storage could have more precise TS definition.
This commit:
* Renames `password.js` to `password.ts`.
* Refactors promise chains in password.ts to async/await.
* Adds more precise types to `OtpStorage`.
=> chore: refactor password.js to password.ts and async

.circleci/config.yml, packages/functional-tests/package.json, yarn.lock
- To keep up with the latest version and new updates, upgrading the Playwright version to the latest 1.43.1.
- Updates the functional-test-runner images
- Upgrades Playwright version to 1.43.1
Closes: FXA-9135 FXA-9358
Typically we do this for node versions, but it should also work for playwright versions. See docs here: https://mozilla.github.io/ecosystem-platform/how-tos/ci-guidelines#updating-ci-runner-images
=> task(ci): update funcitonal test executor

packages/functional-tests/tests/oauth/signin.spec.ts, packages/functional-tests/tests/react-conversion/oauthSignin.spec.ts, packages/functional-tests/tests/react-conversion/signInRelyingParties.spec.ts
- Tests failed stage smoke tests
- All three tests are failing on redirect to 123Done stage with `Bad request - Unknown state`, but if a breakpoint is added on the preceding test step, the redirect works as expected and test passes on continuing from breakpoint without any code changes.
- Skip tests in stage and production until timing issue is fixed
Issue: # FXA-9518
=> bug(functional-tests): Skip failing smoke tests due to timing issue on redirect to Stage 123 Done

libs/payments/ui/src/lib/actions/checkoutCartWithPaypal.ts, libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts, libs/payments/ui/src/lib/nestapp/validators/CheckoutCartWithPaypalActionArgs.ts
* We want to be able to checkout with Paypal from payments-next
* Adds a server action to do so
Closes FXA-8940
=> feat(payments-ui): add checkoutCartWithPaypal action

libs/payments/ui/src/lib/actions/checkoutCartWithStripe.ts, libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts, libs/payments/ui/src/lib/nestapp/validators/CheckoutCartWithStripeActionArgs.ts
Because:
* We want to be able to checkout with Stripe from payments-next
This commit:
* Adds a server action to do so
Closes FXA-8950
=> feat(payments-ui): add checkoutCartWithStripe action

.nxignore
Because:
* We might have been ignoring too much previously.
This commit:
* Narrows the ignore down to just the dist directories.
=> fix: reduce ignore scope

libs/payments/stripe/src/index.ts, libs/payments/stripe/src/lib/factories/coupon.factory.ts, libs/payments/stripe/src/lib/factories/discount.factory.ts, libs/payments/stripe/src/lib/stripe.client.spec.ts, libs/payments/stripe/src/lib/stripe.client.ts, libs/payments/stripe/src/lib/stripe.error.ts, libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.manager.ts, libs/payments/stripe/src/lib/stripe.service.spec.ts, libs/payments/stripe/src/lib/stripe.service.ts, libs/payments/stripe/src/lib/stripe.types.ts, libs/payments/stripe/src/lib/stripe.util.spec.ts, libs/payments/stripe/src/lib/stripe.util.ts
=> feat(payments-stripe): Add applyPromoCodeToSubscription to StripeService

apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/start/en.ftl, apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/start/page.tsx, apps/payments/next/app/styles/global.css
1. Create a Mozilla account header
Already have a Mozilla account? 
Note: as the Sign In button is currently not used anywhere else, it will be added directly to the page for now
Closes: FXA-7521
Included an update to the stylesheet in this PR to eliminate gap seen below:
=> feat(payments-next): Add SignIn button

packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/interfaces.ts, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/mocks.tsx
Because:
* Users are not receiving the welcome email after confirming their account through Sync
This commit:
* Moves the 'service' option from OAuth-only to always be included if the service is not the default
fixes FXA-9527
---
You can test this by launching `fxa-dev-launcher` and seeing before this patch, the [welcome email](https://storage.googleapis.com/mozilla-storybooks-fxa/commits/latest/fxa-auth-server/index.html?path=/story/fxa-emails-templates-postverify--post-verify-desktop-tablet) does not come through when [signing up through Sync in React](http://localhost:3030?context=fx_desktop_v3&entrypoint=preferences&action=email&service=sync&forceExperiment=generalizedReactApp&forceExperimentGroup=react). With this patch, it does.
=> fix(sync): Send 'service' option with submission on ConfirmSignupCode for React sync

.circleci/config.yml
We're not sure what was going on with https://github.com/mozilla/fxa/commit/06c207480cf849539ad3f95c6dc25113c64cd39f but we think this is breaking stuff.
=> Add `provision` back to docker building steps

packages/fxa-settings/src/components/App/index.test.tsx, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/mocks.tsx, packages/fxa-settings/src/pages/Signin/index.tsx, packages/fxa-settings/src/pages/Signin/interfaces.ts, packages/fxa-settings/src/pages/Signin/mocks.tsx
- We can sometimes get into an infinite loop when going to `/signin` because of React feature flagging and going between Backbone version of app
- Alwasy redirect to content server email first and forward query params
- Doesn't change any React experiments or feature flagging
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9400
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9541
=> fix(params): Redirect to email first page when not signed in

.nxignore
- Nx is parsing build directories
- Update nxignore to ignore build directories
Reason for this change, is that while investigating an issue related to `fxa-payments-server` script `build-l10n`, it was identified that the script failed with the following error.
=> fix(nx): update nxignore to include build folder

packages/fxa-settings/src/components/ChooseNewsletters/en.ftl, packages/fxa-settings/src/components/ChooseNewsletters/newsletters.ts, packages/fxa-settings/src/pages/Signup/index.test.tsx
Because:
* We want to update the newsletter option and slug displayed for new users
This commit:
* Replaces the desired newsletter name, slug, and FTL ID
closes FXA-9493
=> feat(signup): Update email newsletter name and slug

packages/fxa-settings/src/components/FormVerifyTotp/en.ftl, packages/fxa-settings/src/components/FormVerifyTotp/index.stories.tsx, packages/fxa-settings/src/components/FormVerifyTotp/index.test.tsx, packages/fxa-settings/src/components/FormVerifyTotp/index.tsx, packages/fxa-settings/src/components/FormVerifyTotp/mocks.tsx, packages/fxa-settings/src/components/Settings/ModalVerifySession/index.stories.tsx, packages/fxa-settings/src/components/TotpInputGroup/en.ftl, packages/fxa-settings/src/components/TotpInputGroup/index.stories.tsx, packages/fxa-settings/src/components/TotpInputGroup/index.test.tsx, packages/fxa-settings/src/components/TotpInputGroup/index.tsx, packages/fxa-settings/src/components/TotpInputGroup/mocks.tsx
* New designs for reset password with code include code inputs with individual input boxes
* Create a `TotpInputGroup` component that contains individual input boxes for each character, with associated methods for handling input, keyboard navigation (including arrow keys, backspace, delete), pasting content into the boxes
* Add inline error feedback below new code input component, instead of tooltip
* Create a `FormVerifyTotp` component that includes the new `TotpInputGroup` (configurable for 6 or 8 digit codes) and submission button, with pre-submission validation that code contains the expected number of digits and no other characters
* Add l10n and storybooks
Closes: #FXA-7888
**Storybook links:
[FormVerifyTotp with 6-digit …
=> feat(fxa-settings): Add input component with separated characters

packages/fxa-shared/metrics/glean/glean-backend-metrics-compat.yaml
- This is a follow up to https://github.com/mozilla/fxa/pull/16298 - in order for ingestion pipeline to correctly parse `accounts-events` ping after adding `events` ping, we need to add some internal metrics definitions here so probe-scraper can pick them up.
- Adds definitions of internal Glean metrics to unblock BQ table generation in the ingestion pipeline.
Closes: https://bugzilla.mozilla.org/show_bug.cgi?id=1874935#c14
=> chore(metrics): add definitions of internal Glean metrics for better events ping support

package.json, yarn.lock
Because:
* We want to avoid multiple copies of bn.js.
This commit:
* Resolves bn.js to the latest verison.
=> chore: align bn.js with the latest version

packages/fxa-react/configs/tailwind.js, packages/fxa-settings/src/components/App/index.test.tsx, packages/fxa-settings/src/components/Settings/ConnectedServices/index.tsx, packages/fxa-settings/src/components/Settings/DataCollection/index.tsx, packages/fxa-settings/src/components/Settings/LinkedAccounts/index.tsx, packages/fxa-settings/src/components/Settings/Nav/index.test.tsx, packages/fxa-settings/src/components/Settings/Nav/index.tsx, packages/fxa-settings/src/components/Settings/PageSettings/index.test.tsx, packages/fxa-settings/src/components/Settings/PageSettings/index.tsx, packages/fxa-settings/src/components/Settings/Profile/index.tsx, packages/fxa-settings/src/components/Settings/Security/index.tsx, packages/fxa-settings/src/styles/tailwind.css
Because:
* This is the intended behavior of our settings nav
This commit:
* Includes CSS tweaks to make the nav sticky on scroll
* Adds an intersection observer and refs for sections and links and conditionally adds our active nav classes on the appropriate link
fixes FXA-9314
---
Note, this is not perfect, but I had to timebox myself on it. With more time I could probably improve the approach but as it stands, I tried various thresholds and checking options that IntersectionObserver gives us out of the box and I think it's in an acceptable state now, but LMK if you like something better when reviewing. I did not add new unit tests since I'm not sure they're worth the effort, but sure I could create fake refs and check we call `observe` on them if we wanted.
Please check in Settings …
=> fix(settings): Make nav sticky and highlight based on section in viewport

packages/functional-tests/tests/react-conversion/oauthSignin.spec.ts, packages/functional-tests/tests/react-conversion/signInRelyingParties.spec.ts
- We want to minimize disruption in the CI and have high trust in test results
- adds fixme annotations to additional impacted tests in oauthSignin.spec.ts
Relates to: #FXA-9518
- I've opted to shorten the descriptions in the fixme annotation, in favor of adding details to the JIRA task. Certain details, including line numbers, are likely to evolve and imo this reduces the maintenance required on comments.
=> test(functional-tests): add fixmes to oauthsignin.spec.ts

libs/payments/capability/src/lib/capability.manager.spec.ts, libs/payments/capability/src/lib/capability.manager.ts, libs/payments/cart/src/lib/cart.manager.in.spec.ts, libs/payments/cart/src/lib/cart.service.spec.ts, libs/payments/cart/src/lib/checkout.service.spec.ts, libs/payments/currency/src/lib/currency.manager.spec.ts, libs/payments/eligibility/src/lib/eligibility.service.spec.ts, libs/payments/paypal/src/lib/paypal.client.config.ts, libs/payments/paypal/src/lib/paypal.client.spec.ts, libs/payments/paypal/src/lib/paypal.manager.spec.ts, libs/payments/paypal/src/lib/paypal.manager.ts, libs/payments/paypal/src/lib/paypalCustomer/paypalCustomer.manager.in.spec.ts, libs/payments/stripe/src/lib/accountCustomer/accountCustomer.manager.in.spec.ts, libs/payments/stripe/src/lib/stripe.client.spec.ts, libs/payments/stripe/src/lib/stripe.config.ts, libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.manager.ts, libs/payments/stripe/src/lib/stripe.service.spec.ts, libs/payments/stripe/src/lib/stripe.util.spec.ts, libs/payments/stripe/src/lib/stripe.util.ts, libs/shared/account/account/src/lib/account.manager.in.spec.ts, libs/shared/contentful/src/lib/contentful.manager.spec.ts, libs/shared/contentful/src/lib/contentful.manager.ts, libs/shared/db/firestore/src/lib/firestore.provider.ts, libs/shared/geodb/src/lib/geodb.provider.ts, libs/shared/l10n/src/lib/localizer/localizer.rsc.factory.spec.ts, libs/shared/metrics/statsd/src/lib/statsd.provider.ts
* Many of the tests did not use NestJS test harness
* Many of the tests had poor structure
* Many of the tests did not use jest.spyOn and were not typesafe in their mocks
* Restructures tests within libs
Closes FXA-9540
=> chore(libs): restructure tests

packages/fxa-auth-server/package.json, yarn.lock
Because:
* The sandboxed-regexp dependency isn't used.
This commit:
* Removes the sandboxed-regexp dependency.
=> chore: remove unused dependency sandboxed-regexp

packages/fxa-shared/metrics/glean/glean-backend-metrics-compat.yaml
This is a follow up to https://github.com/mozilla/fxa/pull/16864
- Metrics definitions added in https://github.com/mozilla/fxa/pull/16864 contained wrong schema identifier
- Fixes metrics schema identifier
=> chore(metrics): fix schema identifier of internal Glean metrics

docs/adr/0043-react-functional-tests.md
- With the current functional test configuration, approximately 45% of tests fail and 20% of tests skip when React signin is set to full prod rollout
- This is partly due to backbone signin being a pre-condition for a large number of tests
- Document the problem and decide between possible solutions to ensure good tests coverage across backbone and react
Spreadsheet documenting test status after signin full prod rollout: 
https://docs.google.com/spreadsheets/d/1XWBi24ZJcSqfFX5BXYOrYyatkktVBp6m-YT-MOAI3AQ/edit#gid=0
=> docs(functional-tests): ADR for react conversion functional tests

packages/fxa-content-server/app/scripts/views/mixins/cached-credentials-mixin.js, packages/fxa-settings/src/pages/Signin/container.test.tsx, packages/fxa-settings/src/pages/Signin/container.tsx
* Fix a bug where email shown on React Signin page might change on refresh or submit if session expires or local storage changes
* Let the email-first page choose a suggested account, do not pick an account from local storage on the sign in page
* Pass the suggested account email from email-first in query params
* Only retrieve the email on React Signin from query params or location state, otherwise redirect to email-first
* Update unit tests to reflect that we are no longer checking local storage for a recent account on signin page
Closes: #FXA-9417
With the changes in PR, when accessing React sign in directly without params or location state, there's a brief …
=> fix(fxa-settings): Email shown on React Signin page should not change on submit

packages/functional-tests/README.md, packages/functional-tests/package.json, packages/functional-tests/playwright.config.ts, packages/functional-tests/tests/stub.spec.ts
- The Playwright version 1.31.1 introduced new method defineConfig to be used in the Playwright config file.
- New property [testProject.dependencies](https://playwright.dev/docs/api/class-testproject#test-project-dependencies) to configure dependencies between projects.
- [Release notes](https://playwright.dev/docs/release-notes#new-apis-8)
- Uses new method defineConfig in the config file.
- Removes the `stub.spec.ts` file as well as it's reference from the Playwright config file as it doesn't seem useful anymore and was created with an intent of helping when writing new tests but we already have 300+ tests now and don't need it anymore
Closes: FXA-9242
=> chore(functional-tests): update the playwright config file to use defineConfig method

libs/shared/sentry/src/lib/nest/sentry.interceptor.ts, libs/shared/sentry/src/lib/reporting.spec.ts, libs/shared/sentry/src/lib/reporting.ts, packages/fxa-shared/nestjs/sentry/reporting.spec.ts, packages/fxa-shared/nestjs/sentry/reporting.ts
- We were reporting known error response states that come from auth-server and were intended for flow control to Sentry
- Adds an extra check so we do not report these states needlessly.
- Fixes some tests so they adhere to latest sentry types.
Closes: FXA-9289
If a manual is desired, you can start up the stack, and run the following curl command (enable Sentry locally), and observe that the error does not propagate; yet the error, 'The authentication token could not be found', is still returned.
```
curl 'http://localhost:8290/graphql' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0' -H 'Accept: */*' -H 'Accept-Language: en-US' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Referer: …
```
=> bug(graphql): Prevent reporting of known auth-server errors

packages/fxa-settings/src/components/FormPasswordWithBalloons/index.tsx, packages/fxa-settings/src/components/InputPassword/index.tsx, packages/fxa-settings/src/components/InputText/index.tsx
* Apple keychain's password suggestion button was hidden under the password visibility icon in React password inputs
* Adjust styling in the password input to show and enable Apple's password button
* Add autoComplete=username to the signup email input to allow correct email/password association for password managers
Closes: #FXA-9422
Before:
After:
Note - The vertical alignment is a bit tricky because of the input's current design with nested label - opted for minimally functional fix here since we are planning to update the design in https://mozilla-hub.atlassian.net/browse/FXA-9349
To test - use **Safari on MacOS** to sign up and sign in to an account with React experiment params 
(http://localhost:3030/?forceExperiment=generalizedReactApp&forceExper …
=> fix(fxa-settings): Fix visibility of Apple password icon in password input

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/routes/cloud-scheduler.ts, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/lib/server.js, packages/fxa-auth-server/scripts/delete-unverified-accounts.ts, packages/fxa-auth-server/test/local/routes/cloud-scheduler.js, packages/fxa-auth-server/test/local/server.js
- We want to automate removal of unverified accounts
- Creates a new endpoint to delete unverified accounts via google cloud scheduler
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9257
We need to update our deploy doc to add new environment variables and to have google cloud scheduler service accounts created.
=> feat(scripts): refactor delete unverified account script to support cloud scheduler

packages/fxa-customs-server/lib/cache.js, packages/fxa-customs-server/lib/records.js, packages/fxa-customs-server/test/local/records_tests.js
Because:
* It's more efficient to run a single multi-key get with redis than serial key fetches.
This commit:
* Uses a single multi-key get to fetch all redis records.
=> refactor: parallelize customs redis hit

libs/vendored/common-password-list/tsconfig.lib.json, libs/vendored/incremental-encoder/tsconfig.lib.json, libs/vendored/jwtool/tsconfig.lib.json
Because:
* We want auth-server to load libs correctly.
This commit:
* Matches the tsconfig.lib.json of other working libraries in auth-server.
=> fix: match existing libs/ tsconfig.lib.json in vendored

packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/signer.ts
Because:
* Typescript path aliases aren't applied to JS files, resulting in them not being loadable in production.
This commit:
* Moves signer.js to a TypeScript file so the TS alias is resolved.
=> fix: switch signer to typescript

packages/fxa-auth-server/lib/oauth/keys.ts
Because:
* We aren't using module alias in auth-server, so we need to either use module-alias or convert the file to TS to use the TS path alias.
This commit:
* Converts key.js to TS.
=> fix: switch oauth keys.js to TS

libs/payments/ui/src/index.ts, libs/payments/ui/src/lib/client/components/FluentLocalizationProvider.tsx, libs/payments/ui/src/lib/client/components/Providers.tsx, libs/payments/ui/src/lib/client/components/StripeWrapper.tsx, libs/shared/l10n/src/lib/localizer/localizer.client.bindings.ts
- We want to localize client components using the Fluent/react library.
- Adds component FluentLocalizationProvider that initializes and wraps `children` in Fluent `<LocalizationProvider>`.
- Adds a test string to `Checkout` page as a means to test the client component localization works as expected.
Closes: #FXA-7827
Pay with card in English
In German
=> feat(next): add `Localization` wrapper client

packages/functional-tests/playwright.config.ts, packages/functional-tests/tests/settings/fxaStatus.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/coupon.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts, packages/functional-tests/tests/subscription-tests/subscription.spec.ts, packages/functional-tests/tests/syncV3/fxDesktopHandshake.spec.ts, packages/functional-tests/tests/syncV3/fxDesktopV3ForceAuth.spec.ts, packages/functional-tests/tests/syncV3/settings.spec.ts, packages/functional-tests/tests/syncV3/signIn.spec.ts, packages/functional-tests/tests/syncV3/signUp.spec.ts, packages/functional-tests/tests/syncV3/signUpWithCWTS.spec.ts, packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts
- we want the functional test suite to execute as fast as possible
- set the default configuration to run 'fullyParallel' 
Closes: # FXA-9389
Before: 11.33 minutes
After 9.52 minutes
=> chore(functional-tests): run fullyParallel by default

packages/fxa-auth-server/lib/routes/account.ts
- Calls to /account/credentials/status were getting blocked by customs
- Calls to /account/credentials/status were inadvertently triggering extra custom checks like accountLogin
- Fixes underlying problem by directly quering the account.
- Previously the account was loaded in a way that invoked other customs checks, and those were failing.
- We are also switch to using customs.checkIpOnly instead of customs.check, since this is actually a better / broader check.
Closes: FXA-9649, FXA-9415
Prior to this fix, this endpoint was triggering a customs check on the accountLogin action, it's quite possible this was causing erratic behavior elsewhere since this action would have gotten hit at a higher rate than we previously saw before key stretching v2 was …
=> bug(auth): Fix customs checks blocking /account/credentials/status

packages/functional-tests/tests/misc/cookiesDisabled.spec.ts
- We are aiming to make stage and prod deployments all green.
- Updates test to add timeout to page locator as `waitForTimeout()` tests are inherently flaky as per the Playwright docs.
Closes FXA-9323
Potential reason for flakiness: https://playwright.dev/docs/api/class-page#page-wait-for-timeout.
=> fix(functional-test): update failing cookies disabled test

packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/test/local/routes/newsletters.js
Because:
* Users are prevented from signing up when they select our new newsletter since it's considered an invalid slug
This commit:
* Adds the slug to our BE whitelist
fixes FXA-9655
---
You can test this locally by going through the entire flow, the newsletter list is sent up on `ConfirmSignupCode`.
=> fix(signup): Add newsletter slug to backend whitelist

packages/functional-tests/tests/misc/keyStretchingV2.spec.ts, packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-client/lib/error.ts, packages/fxa-settings/src/pages/Signin/container.tsx
- We uncovered a scenario where enabling totp could block the key stretching upgrade and result in a failure message on login.
- Ensures a fallback to use v1 creds when this happens
Closes: FXA-9415
This is largely based on #16934; however, we won't address the upgrade here, and instead this PR will focus on falling back to V1. The upgrade process for totp passwords will be addressed in a follow up.
=> task(settings): Fallback to key stretch v1 in the event of upgrade failure

apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/layout.tsx, apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/success/page.tsx, libs/payments/ui/src/lib/actions/fetchContentfulData.ts, libs/payments/ui/src/lib/nestapp/app.module.ts, libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts, libs/payments/ui/src/lib/nestapp/validators/FetchContentfulDataArgs.ts, libs/payments/ui/src/lib/server/purchase-details.tsx, libs/payments/ui/src/server.ts, libs/shared/contentful/src/index.ts, libs/shared/contentful/src/lib/contentful.service.spec.ts, libs/shared/contentful/src/lib/contentful.service.ts
=> feat(payments,shared): Add ContentfulService to Nest.js AppSingleton

.circleci/config.yml
Because:
- Nightly builds are failing
=> Upgrade docker builds to medium+

packages/fxa-auth-server/lib/routes/session.js, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/container.test.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/container.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.test.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/interfaces.ts, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/mocks.tsx
Because:
* reg_complete is not logging the flow id
This commit:
* For reg_complete, adds metricsContext to session/verify call on front-end in ConfirmSignupCode, update expected payload on backend
fixes FXA-9656
---
To verify the `reg_complete` fix, register for an account and grep the auth-server logs for `reg_complete`. See the missing flow ID. In this branch you'll see the flow ID now attached to the event. (Yes, adding `metricsContext` to the expected payload in auth-server is needed or it's still empty.)
--
**Edit: I investigated `reg_view` as part of the ticket but it does appear to be coming through? We might need another PR to fix it if it's a problem but I'll leave my note below, and will repush to update my actual commit message mentioning `reg_view` after r+ in case of nits.** …
=> fix(metrics): Metrics tweaks for React signup events

apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/start/en.ftl, apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/start/page.tsx, libs/payments/ui/src/index.ts, libs/payments/ui/src/lib/client/components/CheckoutCheckbox.ftl, libs/payments/ui/src/lib/client/components/CheckoutCheckbox.tsx, libs/payments/ui/src/lib/client/components/CheckoutForm.ftl, libs/payments/ui/src/lib/client/components/CheckoutForm.tsx, libs/payments/ui/src/lib/client/components/PaymentSection.ftl, libs/payments/ui/src/lib/client/components/PaymentSection.tsx, libs/payments/ui/src/lib/client/components/StripeWrapper.tsx, libs/shared/assets/src/configs/tailwind.config.js, package.json, yarn.lock
- Add consent checkbox, reminder error tooltip and payment section with default disabled state.
- Adds a new client component for the consent checkbox and implements a Radix holdover component for the error tooltip.
- Adds PaymentSection client component.
Closes: #FXA-7806
Just missing Localization which is currently blocked by #16595.
=> feat(next): add consent checkbox

libs/payments/cart/src/lib/cart.service.spec.ts, libs/payments/cart/src/lib/cart.service.ts, libs/payments/eligibility/src/lib/eligibility.manager.spec.ts, libs/payments/eligibility/src/lib/eligibility.manager.ts, libs/payments/eligibility/src/lib/eligibility.service.spec.ts, libs/payments/eligibility/src/lib/eligibility.service.ts, libs/payments/stripe/src/index.ts, libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.manager.ts, libs/payments/stripe/src/lib/stripe.types.ts, libs/payments/stripe/src/lib/util/doesPlanMatchSubplatInterval.spec.ts, libs/payments/stripe/src/lib/util/doesPlanMatchSubplatInterval.ts, libs/payments/ui/src/lib/nestapp/validators/SetupCartActionArgs.ts
* We need to actually check interval_count rather than just interval
* Adds a handy util for doing so, and uses it within the stripe manager
Closes FXA-9536
=> feat(payments-stripe): create doesPlanMatchSubplatInterval

packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/pages/InlineTotpSetup/container.test.tsx, packages/fxa-settings/src/pages/InlineTotpSetup/container.tsx
Because:
* The inline TOTP setup flow is being blocked by customs on stage
* This flow can also encounter a "token already exists" error in some cases
This commit:
* Adds metricsContext to the request for customs
* Does not rerun the TOTP create request if a totp token already exists
fixes FXA-9435
---
You can access this flow in React by going to 123done and clicking "Sign in (2FA required)", adding the React experiment params, then either signing up for an account or signing into an account. You should be redirected back to signin with a cached view, then on click of signin, you should be taken to the inline TOTP setup page.
Vijay flagged in the comments of this ticket that the flow wasn't working as expected (note, QA's comment/gif is not applicable to this issue). I did some …
=> fix(react): Address inline TOTP setup issues

packages/fxa-settings/src/components/Settings/Nav/index.tsx
Because:
* There's too much margin-top in desktop
This commit:
* Tweaks the margin-top classes
---
You can see on stage there's too much margin-top here and with this tweak it aligns "Settings" with "Profile". Not sure how I let this slip when I repushed to that previous branch/PR heh. Screenshot with this PR:
=> fix(css): Margin-top tweak for desktop Settings nav

libs/payments/cart/src/lib/cart.types.ts, libs/payments/cart/src/lib/cart.utils.spec.ts, libs/payments/cart/src/lib/cart.utils.ts
- We want to create a util function to handle the `EligibilityStatus` and ensure that the Cart is created with the correct `CartEligibilityStatus`, `CartState` and `ErrorReasonId` (if necessary).
- Creates a util function in `libs/payments/cart` to handle the `EligibilityStatus` to ensure that the Cart is created with the correct `CartEligibilityStatus`, `CartState` and `ErrorReasonId` (if necessary).
- Adds a test for each state.
Closes FXA-9537
=> feat(cart): add util function for cart handleEligibilityStatus

apps/payments/next/app/page.tsx, apps/payments/next/next.config.js, libs/payments/cart/src/lib/cart.service.spec.ts, libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/util/stripeInvoiceToFirstInvoicePreviewDTO.spec.ts, libs/payments/stripe/src/lib/util/stripeInvoiceToFirstInvoicePreviewDTO.ts
=> fix(apps,libs): Revise discountAmount and temporary page on  payments-next

packages/fxa-auth-server/lib/routes/cloud-scheduler.ts, packages/fxa-auth-server/scripts/delete-unverified-accounts.ts, packages/fxa-auth-server/test/local/routes/cloud-scheduler.js
- We were getting an error `Error [ERR_REQUIRE_ESM]: require() of ES Module` when using PQueue
- Updates this to use a dynamic import of the library which works for CommonJS modules
- Moved the `processDateRange` function to the cloud scheduler route
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9644
To test:
1. From fxa-auth-server, run `yarn build`
2. Run `NODE_ENV=dev node dist/packages/fxa-auth-server/scripts/delete-unverified-accounts.js` verify scripts starts but asks for uid
3. Run `NODE_ENV=dev node dist/packages/fxa-auth-server/bin/key_server.js` verify server starts
=> fix(scripts): Add dynamic import for PQueue to fix module error

packages/functional-tests/pages/config.ts, packages/functional-tests/tests/react-conversion/signIn.spec.ts, packages/fxa-graphql-api/src/gql/lib/error.ts, packages/fxa-settings/src/pages/Signin/SigninUnblock/container.tsx, packages/fxa-settings/src/pages/Signin/container.test.tsx, packages/fxa-settings/src/pages/Signin/container.tsx, packages/fxa-settings/src/pages/Signin/interfaces.ts, packages/fxa-settings/src/pages/Signin/mocks.tsx, packages/fxa-settings/src/pages/Signin/utils.ts
- We did not handle the incorrect email properly, and would just display incorrect email to the user.
- The incorrect email error contains a corrected email in the payload that should be used.
- Retries the login with the email provided by the incorrect email error state.
- Fixes typescript error in functional-tests/pages/config.ts.
- Adds functional test to cover this edge case.
Closes: FXA-9663
This also impacted the sign in unblock flow and is now fixed. However, it might conflict with https://github.com/mozilla/fxa/pull/16959  :disappointed: .
=> bug(settings): Handle incorrect email case in sign up

packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-client/test/client.ts, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-graphql-api/src/backend/auth-client.service.ts, packages/fxa-graphql-api/src/backend/profile-client.service.spec.ts, packages/fxa-graphql-api/src/backend/profile-client.service.ts, packages/fxa-graphql-api/src/gql/account.resolver.spec.ts, packages/fxa-graphql-api/src/gql/account.resolver.ts, packages/fxa-graphql-api/src/gql/session.resolver.spec.ts, packages/fxa-graphql-api/src/gql/session.resolver.ts
- We have scenarios where headers are not being forwarded between the graphql-api and auth-server
- This means the client IP isn’t forwarded properly, and customs may block requests
- Creates mode in authClient that fails hard / fast when headers are not provided
- Uses this mode for the authClient instance in our graphql api
- Ensures that headers are always provided to the auth client
Closes: FXA-9678
=> task(auth-client, gql): Create auth client mode where headers are required and provide headers in gql

packages/fxa-auth-server/lib/db/index.js, packages/fxa-auth-server/lib/routes/password.ts, packages/fxa-auth-server/test/local/routes/password.js, packages/fxa-auth-server/test/mocks.js
- When auto upgrading passwords to v2 key stretching, notification emails were being sent to users
- When auto upgrading passwords to v2 key stretching, notifications were sent to RPs
- Suppresses email when we detect an v2 key stretch upgrade scenario
- Suppresses notifications when we detect a v2 key stretch upgrade scenario
- Reports slightly different metrics for key stretch upgrades
Closes: FXA-9662
=> bug(auth): Don't notify of password change  for key stretch upgrades

packages/functional-tests/lib/testAccountTracker.ts, packages/functional-tests/tests/misc/keyStretchingV2.spec.ts, packages/fxa-settings/src/pages/Signin/SigninUnblock/container.tsx, packages/fxa-settings/src/pages/Signin/SigninUnblock/interfaces.ts, packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signin/index.tsx, packages/fxa-settings/src/pages/mocks.tsx
- After a getting blocked, the user would not be able to correctly signin after enter an unblock code
- Don't upgrade the user creds to v2 if they get blocked
- Fallback to v1 creds
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9661
=> fix(unblock): Use correct authPW when user is blocked

packages/functional-tests/pages/login.ts, packages/functional-tests/tests/oauth/loginHint.spec.ts, packages/functional-tests/tests/react-conversion/signInRelyingParties.spec.ts, packages/functional-tests/tests/signUp/signUp.spec.ts, packages/functional-tests/tests/signin/relyingParties.spec.ts, packages/functional-tests/tests/signin/signIn.spec.ts, packages/functional-tests/tests/signin/signinBlocked.spec.ts, packages/functional-tests/tests/syncV3/signIn.spec.ts, packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts
- The relying party and sign up tests were flaky
- Adds auto retrying assertions in places where flakiness was detected.
Closes: FXA-9386 FXA-9490
After the changes, ran the tests for local, stage and Prod on CI and it passed (the failures are for just coupon tests in Stage):
And ran the tests separately in local, Stage and prod locally several times and it didn't flake:
Stage:
Prod:
=> test(functional): add auto retrying assertion

packages/functional-tests/tests/subscription-tests/coupons-ui-tests/coupon.spec.ts
- 3 Coupon tests were failing in Stage. 2 were due to a customs failure issue and the third one because of a locator not visible issue.
- Adds fixme to all the 2 failing coupon tests with appropriate ticket mentioned.
=> test(functional): add fixme to failing coupon tests

libs/vendored/typesafe-node-firestore/.eslintrc.json, libs/vendored/typesafe-node-firestore/README.md, libs/vendored/typesafe-node-firestore/jest.config.ts, libs/vendored/typesafe-node-firestore/package.json, libs/vendored/typesafe-node-firestore/project.json, libs/vendored/typesafe-node-firestore/src/index.ts, libs/vendored/typesafe-node-firestore/src/lib/typesafe-node-firestore.ts, libs/vendored/typesafe-node-firestore/tsconfig.json, libs/vendored/typesafe-node-firestore/tsconfig.lib.json, libs/vendored/typesafe-node-firestore/tsconfig.spec.json, packages/fxa-admin-server/tsconfig.build.json, packages/fxa-auth-server/lib/payments/iap/iap-config.ts, packages/fxa-auth-server/package.json, packages/fxa-event-broker/package.json, packages/fxa-event-broker/src/firestore/firestore.service.ts, packages/fxa-event-broker/tsconfig.build.json, packages/fxa-shared/package.json, packages/fxa-shared/payments/configuration/manager.ts, tsconfig.base.json
Because:
* We don't want to maintain small external libs instead of using our monorepo.
This commit:
* Vendors in the typesafe-node-firestore typings.
=> chore: vendor typesafe-node-firestore

libs/payments/cart/src/lib/cart.service.spec.ts, libs/payments/cart/src/lib/cart.service.ts, libs/payments/stripe/src/lib/accountCustomer/accountCustomer.factories.ts, libs/payments/stripe/src/lib/util/stripeInvoiceToFirstInvoicePreviewDTO.spec.ts, libs/payments/stripe/src/lib/util/stripeInvoiceToFirstInvoicePreviewDTO.ts
- We want to remove skeleton placeholders and replace with actual values.
- Calls `stripeManager.previewInvoice` using priceId obtained from calling `contentfulService.retrieveStripePlanId`, and replaces the amount placeholder with `totalAmount`.
Closes FXA-8896
=> feat(cartService): update total in `CartService.setupCart`

packages/fxa-auth-server/docs/swagger/shared/descriptions.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-shared/subscriptions/types.ts
=> feat(auth): Verify and update promotion code info on endpoint

packages/fxa-content-server/app/scripts/lib/glean/index.ts
- PRs were failing CircleCI on the fxa-content-server compilation step
- Adds missing properties argument in Glean createEventFn
=> fix(content): Missing argument in createEventFn causing ts compilation issue

packages/functional-tests/pages/products/index.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/coupon.spec.ts
- We are aiming to make stage and prod deployments all green.
- Updates tests to add timeout to page locators.
- Follow up to https://github.com/mozilla/fxa/pull/16978, which added `fixme` annotation.
- Adds helper method to retrieve locator by `data-test-id`
Closes FXA-9689
=> fix(functional-test): update failing coupon tests

packages/fxa-shared/nestjs/sentry/sentry.interceptor.ts
- We are still seeing the 'The authentication token could not be found' sentry issue.
- GQL is using fxa-shared not libs!
- Fixes a bug where the isAuthServerError wasn't added to the sentry.interceptor in fxa-shared as well.
=> bug(gql): Follow fix for ignoring known auth server errors in graphql-api

apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/start/page.tsx, apps/payments/next/app/[locale]/layout.tsx, libs/payments/ui/src/index.ts, libs/payments/ui/src/lib/client/components/CheckoutCheckbox.tsx, libs/payments/ui/src/lib/client/components/Providers.tsx, libs/payments/ui/src/lib/client/providers/FluentLocalizationProvider.tsx, libs/payments/ui/src/lib/client/providers/Providers.tsx, libs/payments/ui/src/lib/nestapp/app.ts, libs/shared/l10n/src/lib/localizer/localizer.rsc.factory.ts
- Fluent LocalizationProvider is currently initialized on the client causing noticable load times for client components.
- Initialize ReactLocalization on the server
- Wrap near root layout with LocalizationProvider as suggested by Nextjs docs.
Closes: #
=> feat(next): move localization provider

libs/payments/cart/src/lib/checkout.service.spec.ts, libs/payments/cart/src/lib/checkout.service.ts, libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.manager.ts
- We want to clean up our code and make sure our methods are created and updated appropriately.
- Is a follow up to https://github.com/mozilla/fxa/pull/16924 comments and Slack messages between the SubPlat SWEs.
- Updates `StripeManager.createPlainCustomer`.
- Updates `CheckoutService.prePaySteps` to add `AccountCustomerManager.createAccountCustomer`.
- Updates all applicable tests.
=> feat(stripe): polish pr to update `prePaySteps` and `createPlainCustomer`

packages/functional-tests/tests/subscription-tests/coupons-ui-tests/coupon.spec.ts
- We want to reduce our failure rate on tests.
- Re-adds fixmes removed in https://github.com/mozilla/fxa/pull/16983.
=> fix(tests): Re-added fixmes as prior solution did not work

packages/fxa-auth-server/scripts/cancel-subscriptions-to-plan.ts
- cancel-subscriptions-to-plan currently fails to refund paypal subs
- Sets up credentials for PaypalClient in cancel-subscriptions-to-plan script
Closes: No relevant issue
=> fix(auth): setup paypalClient credentials for cancel-subscriptions-to-plan

packages/functional-tests/tests/key-stretching-v2/recoveryKey.spec.ts, packages/functional-tests/tests/key-stretching-v2/resetPassword.spec.ts, packages/functional-tests/tests/react-conversion/oauthResetPassword.spec.ts, packages/functional-tests/tests/react-conversion/recoveryKey.spec.ts, packages/functional-tests/tests/react-conversion/resetPassword.spec.ts, packages/functional-tests/tests/react-conversion/syncV3ResetPassword.spec.ts, packages/functional-tests/tests/settings/changePassword.spec.ts, packages/functional-tests/tests/signin/signIn.spec.ts
The tests that were marked as fixme for `FXA-9612` should be marked as skipped instead, they are not broken just skipped based on feature flag.
=> switch fixme to skip for tests that will be modified or created for reset pwd with code

libs/shared/notifier/src/lib/notifier.service.ts, packages/fxa-admin-server/src/app.module.ts, packages/fxa-admin-server/src/config/index.ts, packages/fxa-admin-server/src/gql/account/account.resolver.spec.ts, packages/fxa-admin-server/src/gql/account/account.resolver.ts, packages/fxa-admin-server/tsconfig.build.json, packages/fxa-auth-server/lib/profile/updates.js, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/lib/routes/sign.js, packages/fxa-auth-server/lib/routes/totp.js, packages/fxa-auth-server/test/local/profile/updates.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/local/routes/totp.js, packages/fxa-event-broker/src/jwtset/jwtset.service.spec.ts, packages/fxa-event-broker/src/jwtset/jwtset.service.ts, packages/fxa-event-broker/src/jwtset/set.interface.ts, packages/fxa-event-broker/src/pubsub-proxy/pubsub-proxy.controller.spec.ts, packages/fxa-event-broker/src/pubsub-proxy/pubsub-proxy.controller.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.spec.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.ts, packages/fxa-event-broker/src/queueworker/service-notification.interface.ts, packages/fxa-event-broker/src/queueworker/sqs.dto.ts, packages/fxa-graphql-api/src/database/database.service.spec.ts, packages/fxa-graphql-api/src/gql/account.resolver.spec.ts, packages/fxa-graphql-api/src/gql/account.resolver.ts, packages/fxa-graphql-api/src/scripts/must-change-password.ts
- In a previous PR, a new event type was created, but we should have repurposed the profileDataChange event type
- During the previous deployment it was noted that there are different ways to configure sns, and that a topic arn and/or topic endpoint might not be required
- Relaxes requirements for notifier service.
- Makes snsTopicEndpoint optional
- Makes snsTopicArn optional
- Removes the `metricsChange` event type
- Augments the `profileDataChange` type schema to support, locale, metricsEnabled, totpEnabled, accountDisabled, and accountLocked states.
- Emmits the `profileDataChange` whenever corresponding account data is mutated.
Closes: FXA-9412
The eco systems docs will also need to be updated to reflect this new state. It's also worth noting that …
=> task(auth, graphql-api, admin-server): Update event-broker's profileDataChange data schema and remove the metrics-change event

package.json, packages/fxa-auth-server/lib/routes/cloud-scheduler.ts, packages/fxa-auth-server/package.json, packages/fxa-auth-server/scripts/cancel-subscriptions-to-plan/cancel-subscriptions-to-plan.ts, packages/fxa-auth-server/scripts/convert-customers-to-stripe-automatic-tax/convert-customers-to-stripe-automatic-tax.ts, packages/fxa-auth-server/scripts/move-customers-to-new-plan/move-customers-to-new-plan.ts, packages/fxa-auth-server/scripts/set-subscription-purchases-apple-iap/set-subscription-purchases-apple-iap.ts, packages/fxa-auth-server/scripts/update-subscriptions-to-new-plan/update-subscriptions-to-new-plan.ts, yarn.lock
- We were still having issues with p-queue library and esm
- uses the `p-queue-compat` library
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9719
Will have to be a point release to enable cloud scheduler
=> chore(deps): Use the p-queue-compat library instead of p-queue

packages/fxa-customs-server/lib/email_record.js, packages/fxa-customs-server/lib/ip_record.js, packages/fxa-customs-server/test/local/email_record_tests.js, packages/fxa-customs-server/test/remote/too_many_password_reset_otp_verifications.js
Because:
- having the passwordForgotVerifyOtp action's rate limiting / blocking use the email/ip records' existing properties and retry after calculation was buggy, leading to unintended blocking
This commit:
- updates passwordForgotVerifyOtp action's rate limiting / blocking so that they won't affect other actions
=> fix(customs): update password otp verification rate limiting / blocking

packages/functional-tests/tests/signin/signinBlocked.spec.ts
- Signin Blocked - unverified test was failing in Local and stage
- Replaces the correct sign up function to be able to navigate to the sign in blocked header
Closes: FXA-9226
=> test(functional): fix unverified test

packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/container.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/interfaces.ts, packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/mocks.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.tsx
* When clicking on "Use a different account" link, should not redirect to signin with a cached account
* Should be able to edit email to use
* Reuse the click handling from signin page for "use different account" links on ConfirmResetPassword and SigninTotpCode
Closes: #FXA-9717
=> fix(settings): Use different account link redirects to signin with cached account

packages/functional-tests/lib/paymentArtifacts.ts, packages/functional-tests/lib/targets/base.ts, packages/functional-tests/lib/targets/local.ts, packages/functional-tests/lib/targets/production.ts, packages/functional-tests/lib/targets/stage.ts, packages/functional-tests/pages/index.ts, packages/functional-tests/pages/products/components/paymentInformation.ts, packages/functional-tests/pages/products/index.ts, packages/functional-tests/pages/products/subscriptionManagement.ts, packages/functional-tests/pages/products/support.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponExpired.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponForeverDiscount.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponInvalid.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponOneTimeDiscount.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/paymentMode.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/ui-tests.spec.ts, packages/functional-tests/tests/subscription-tests/subscription.spec.ts, packages/functional-tests/tests/subscription-tests/support.spec.ts
- we need to improve resilience in the subscription functional tests
- refactor the SubscribePage and SubscriptionManagement Page to use built-in locators
- use signinReact over login POM
- update the subscription-tests to use auto-awaiting asserts
Closes: # FXA-9729
=> refactor(functional-tests): subscription-tests

packages/functional-tests/playwright.config.ts, packages/functional-tests/tests/key-stretching-v2/recoveryKey.spec.ts, packages/functional-tests/tests/key-stretching-v2/signinBlocked.spec.ts
- we want to reduce the impact on execution time when tests fail and address issues of flake
- reduces the available retires in functional tests on CI from 3 to 1
- add a fixme annotation for the `severity-2 #smoke › signs up as v1, rate limited, unblocked, signs in as v2` test
- add a fixme annotation for the `severity-2 #smoke › signs up as v1 resets password with recovery key as v2 and signs in as v1` test
Closes: # FXA-9390
Repeated flake has been detected for the following tests on Stage, but I'm hoping they are addressed by https://github.com/mozilla/fxa/pull/17021
- `severity-2 #smoke › subscription …
=> chore(functional-tests): change retries from 3 to 1 on CI

packages/fxa-customs-server/lib/email_record.js, packages/fxa-customs-server/lib/ip_record.js, packages/fxa-customs-server/test/local/email_record_tests.js, packages/fxa-customs-server/test/local/ip_record_tests.js
Because:
- we want the rate limit for requesting password reset OTPs applied only to the OTP request action
This commit:
- reverts changes that used the existing rate limit property in email and ip records
- reverts changes to retryAfter to allow optional arguments to adjust the rate limit / block duration
- updates the password reset OTP request action handling so that it's self-contained, and won't affect other actions' rate limiting
=> fix(customs): apply password reset OTP limit only to OTP reqs

packages/functional-tests/README.md, packages/functional-tests/tests/react-conversion/oauthResetPasswordRecoveryKey.spec.ts, packages/functional-tests/tests/react-conversion/oauthResetPasswordScopeKeys.spec.ts, packages/functional-tests/tests/react-conversion/oauthResetPasswordSyncMobile.spec.ts, packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts
- we want to classify test.skip and test.fixme consistently
- updates functional-test documentation
- updates some test.fixme annotations to test.skip annotations 
- removes `open directly to /signup page, refresh on the /signup page`
Closes: # FXA-9740
Relates to https://github.com/mozilla/ecosystem-platform/pull/536
=> docs(functional-tests): update functional test documentation and fixme/skip annotations

libs/payments/ui/src/lib/client/components/CheckoutForm.tsx
- Stripe Payment Element is missing readOnly config value
- Readds readOnly config value to Payment Element
=> fix(next): readd readOnly to payment element

packages/fxa-react/lib/utils.tsx, packages/fxa-settings/src/components/LinkRememberPassword/index.test.tsx, packages/fxa-settings/src/components/LinkRememberPassword/index.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/CompleteResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/container.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/ResetPassword/container.tsx, packages/fxa-settings/src/pages/Signin/container.tsx
* If an email was blocked, following the "Remember your password? Sign in" would result in a 500 error
* Trying to reach confirm_reset_password directly without required location state would result in an infinite loading spinner
* Hard navigating from React to Backbone without search params, a stray ? was included in href
* Use the prefillEmail param instead of email when using the "Remember your password? Sign in" link
* When hard navigating, only include the ? if there are params to include
* If confirm_reset_password is accessed without required state, return to index
Closes: #FXA-9722
The initial error from this ticket only occurs when requests are throttled. To …
=> fix(setting): Fix 500 error and infinite spinner on redirects from reset password with code

packages/fxa-settings/src/pages/ResetPasswordRedesign/AccountRecoveryConfirmKey/container.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/CompleteResetPassword/container.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/CompleteResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/CompleteResetPassword/interfaces.ts, packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/container.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/ResetPassword/container.tsx
* Once password reset steps are completed (confirming code, setting new password), clicking back should only return to the beginning of the reset password flow, not to the previous step that cannot be repeated
* Set {replace:true} for navigation within password reset flow when steps are successfully completed
* Do not use {replace:true} when navigating between account_recovery_confirm_key and complete_reset_password (choosing to use a recovery key or not)
Closes: #FXA-9731
=> fix(settings): Should not be able to navigate back during password reset

packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/en.ftl, packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/ResetPassword/en.ftl, packages/fxa-settings/src/pages/ResetPasswordRedesign/ResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/ResetPassword/index.tsx
* The design was updated with revised copy
* Update the copy and ftl strings
* Update unit tests
Closes: #FXA-9747
Figma designs:
[New copy for reset_password](https://www.figma.com/design/8NqLKthkW1CWXFgmMv2qLj/Password_reset_flow_2023?node-id=4331-52452&t=RHjPKYpFGh0CKM12-4)
[New copy for confirm_reset_password](https://www.figma.com/design/8NqLKthkW1CWXFgmMv2qLj/Password_reset_flow_2023?node-id=4325-51185&t=4U9qDZPsCbiOmlJ7-4)
=> feat(settings): Update copy in reset password with code flow

packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx, packages/fxa-settings/src/pages/Signup/container.test.tsx, packages/fxa-settings/src/pages/Signup/container.tsx, packages/fxa-settings/src/pages/Signup/interfaces.ts
Because:
- after migrating to fxa-settings, the backend reg_complete pings no longer have an oauth client id or service value
This commit:
- sends a metrics context on sign up so that the service value is cached along with the metrics context
- stop sending a metrics context on verify sign up code so that the previously cached metrics context is used
=> fix(metrics): restore client id / service for reg_complete

.circleci/config.yml, packages/functional-tests/tests/react-conversion/changeEmail.spec.ts
* the `--split-by=timings` default type `file` and alternative type `name` are unsupported for the playwright junit xml file
* adds the `--split-by=classname` option
* removes a rogue `test.slow()` annotation and unused const from changeEmail.spec.ts
Closes: #FXA-9720
An alternative to using CircleCI parallel is to use [Playwright sharding](https://playwright.dev/docs/ci#circleci) Example here: https://github.com/mozilla/fxa/pull/17052
- The results are rather similar at this time
- My understanding is that:
- CircleCI splits the tests by module according to historical timing and would be weak against …
=> fix(functional-tests): `no timings found for` error in ci `run-playwright-tests` job

packages/fxa-auth-server/lib/routes/cloud-scheduler.ts
- It could take 30seconds or more to make these tasks
- We don't `await` the function
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9748
Tested this with Eric and cloud scheduler shows 200 response when timeout was removed at nginx level.
=> fix(cloud): Don't await for cloud scheduler delete unverified task

package.json, packages/fxa-admin-panel/.rescriptsrc.js, packages/fxa-payments-server/.rescriptsrc.js, packages/fxa-payments-server/server/bin/fxa-payments-server.js, packages/fxa-payments-server/server/jest.config.js, packages/fxa-payments-server/server/lib/amplitude.js, packages/fxa-payments-server/src/components/AlertBar/index.tsx, packages/fxa-payments-server/src/components/AppLayout/index.tsx, packages/fxa-payments-server/src/components/DialogMessage/index.tsx, packages/fxa-payments-server/src/components/Header/index.tsx, packages/fxa-react/components/Footer/index.tsx, packages/fxa-react/components/Head/index.tsx, packages/fxa-react/components/LogoLockup/index.tsx, packages/fxa-react/configs/rescripts.js, packages/fxa-react/configs/storybooks.js, packages/fxa-react/jest.config.js, packages/fxa-react/lib/AppLocalizationProvider.tsx, packages/fxa-settings/config/webpack.config.js, packages/fxa-settings/package.json, packages/fxa-settings/src/components/AppLayout/index.tsx, packages/fxa-settings/src/components/Banner/index.tsx, packages/fxa-settings/src/components/BrandMessaging/index.tsx, packages/fxa-settings/src/components/ButtonDownloadRecoveryKeyPDF/index.tsx, packages/fxa-settings/src/components/CardHeader/index.tsx, packages/fxa-settings/src/components/Settings/AlertBar/index.tsx, packages/fxa-settings/src/components/Settings/BentoMenu/index.tsx, packages/fxa-settings/src/components/Settings/ConnectedServices/Service.tsx, packages/fxa-settings/src/components/Settings/Modal/index.tsx, packages/fxa-shared/package.json, yarn.lock
- Could not import libs/* into apps using webpack
- Some apps failed with compilation errors when switching branches
- Imports from libs/assets used relative paths instead of the alias
- Adds support for libs/* into apps using webpack
- Replaces all relative paths for libs/assets with the alias
Closes: #FXA-9559
Closes: #FXA-9313
=> feat(many): add support for libs in webpack apps

.github/workflows/upload-assets-to-cdn.yml
We are migrating from AWS to GCP and part of that means moving from S3 to GCS buckets.
Adds support for the following workflow change (for each environment):
1. Authenticate with GCP using a service account and Workload Identity
2. Upload assets to GCS bucket
This does not stop uploading to S3. Once we are fully cut over to the GCS CDN + buckets in prod, I'll create a new PR to remove the S3 parts of this workflow.
Doesn't actually close, but helps implement: OPST-1072
~~This depends on another PR on the infrastructure side. Once that's merged, I'll take this out of draft status.~~ DONE!
This was successfully tested here: …
=> feat(assets): begin uploading assets to GCS buckets

packages/functional-tests/tests/key-stretching-v2/resetPassword.spec.ts
- To minimize disruption in the CI and have high trust in test results
- Adds fixme to the failed Key Stretching test
Relates to: FXA-9765
=> test(functional): add fixme to failed test

_dev/pm2/infrastructure.config.js, _scripts/check-ports.sh, _scripts/cirrus.sh, _scripts/configs/cirrus.env.sample, _scripts/configs/cirrus.fml.yml
- We want to create a cirrus container that we can interact with 
- We want this to become part of the fxa local development stack
- Adds a cirrus container
- Adds two other support containers, autograph, and kinto
- Add necessary configuration file
- Adds pm2 startup commands
Closes: FXA-9704
To validate the container is accepting requests:
-  `yarn start infrastructure`
-  Once complete run `yarn pm2 status` and validate that cirrus, autograph and kinto services exist.
-  Check the logs of each of the services.
The following curl command can also be issued, to validate that cirrus is accepting requests, and picking up the `cirrus.fml.yml` files configuration settings.
```
curl \
-H 'Content-Type: application/json' \
--request POST \
--data '{ …
```
=> task(cirrus): Setup cirrus container

packages/fxa-settings/src/pages/ResetPasswordRedesign/CompleteResetPassword/index.tsx, packages/fxa-shared/metrics/glean/web/index.ts
* Naming error for glean metric was causing build issues
* Fix the metric name
=> fix(metrics): Fix mismatched Glean metrics name

packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/lib/routes/linked-accounts.ts, packages/fxa-auth-server/test/local/routes/linked-accounts.js
Because:
* We are emitting this event for successful signup, but not for successful third party auth new account signup
This commit:
* Adds the event
closes FXA-9752
---
I didn't see a note about a new event (or capturing additional info) so I just used the existing event.
=> feat(metrics): Add reg_complete backend glean event for third party auth new account creation

_scripts/pm2-all.sh, apps/payments/next/project.json, package-scripts.js, packages/123done/package.json, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/package.json, packages/fxa-auth-server/package.json, packages/fxa-content-server/package.json, packages/fxa-customs-server/package.json, packages/fxa-event-broker/package.json, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/package.json, packages/fxa-profile-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json, yarn.lock
- Could be useful to start only parts of the stack needed for specific domains.
- Provides additional stack startup options to only start specific parts of the stack, by using nx projects and tags.
- Fixes bug, allowing for script commands other than `start`, i.e. `restart`, `delete` and `stop`. 
Closes: #FXA-9771
I’ve recently been running into some memory shortage issues when running the full FxA stack. (Maybe you can relate)
As a work around to this, I’ve found myself only running pieces of the stack that I’m working on, or pm2 deleting some memory intensive apps that weren’t necessary. (event-broker (1.2gb), admin-server (2.6gb), etc.)
Instead, what this PR introduces, are a few new script options using some new Nx tags added to apps with start …
=> feat(many): add partial stack startup scripts

packages/fxa-settings/src/components/ConfirmWithLink/index.tsx, packages/fxa-settings/src/components/ConfirmWithLink/mocks.tsx, packages/fxa-settings/src/components/FormVerifyTotp/en.ftl, packages/fxa-settings/src/components/FormVerifyTotp/index.test.tsx, packages/fxa-settings/src/components/FormVerifyTotp/index.tsx, packages/fxa-settings/src/components/LinkExpired/index.stories.tsx, packages/fxa-settings/src/components/LinkExpired/index.test.tsx, packages/fxa-settings/src/components/LinkExpired/index.tsx, packages/fxa-settings/src/components/LinkExpiredResetPassword/index.tsx, packages/fxa-settings/src/components/TotpInputGroup/index.test.tsx, packages/fxa-settings/src/components/TotpInputGroup/index.tsx, packages/fxa-settings/src/lib/types.ts, packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/CompleteResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/container.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/interfaces.ts, packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/mocks.tsx, packages/fxa-settings/src/pages/Signin/SigninUnblock/index.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx
* Form submission should be disabled when there was an error on submit
* Re-enable submit after the code is changed
* We want to prevent the user from accidentally hitting the verification limit by submitting the same wrong code too many times
* We do not want the submit button to be disabled if the error is caused by a resend code error
* Update the conditions where the submit button in FormVerify code component is disabled
* Remove the aria-label on submit button that was reading the code
* Separate the resend code error state from code verification error state
* Clear all banners before code verification and code resend to make way for new messages
Closes: #FXA-9724
Please attach the screenshots of the changes made in case of change in user …
=> fix(settings): Disable ConfirmResetPassword submit button

libs/payments/cart/src/lib/checkout.service.spec.ts, libs/payments/cart/src/lib/checkout.service.ts, libs/payments/stripe/src/lib/accountCustomer/accountCustomer.factories.ts, libs/payments/stripe/src/lib/accountCustomer/accountCustomer.types.ts
- AccountCustomerManager.createAccountCustomer included updateAt as a parameter even though it wasn't used.
- Remove updateAt from createAccountCustomer and update related files.
=> fix(cart): remove updateAt on createAccountCustomer

packages/fxa-auth-client/lib/client.ts, packages/fxa-settings/src/pages/Signin/container.test.tsx, packages/fxa-settings/src/pages/Signin/container.tsx
- We found a bug that occurred during sign in  after swapping secondary and primary emails.
- Makes sure to send up the 'originalEmail'
Closes: FXA-9663
This addresses feedback left by rvass on FXA-9663. The issue occurred when swapping primary and secondary email addresses. once this happens
To test:
- create an account with email aaa@mozilla.com
- logout
- login
- add secondary email bbb@mozilla.com
- swap primary and secondary
- logout
- login
=> bug(settings): Login breaking after swapping secondary and primary emails.

packages/fxa-settings/src/lib/sensitive-data-client.ts, packages/fxa-settings/src/models/contexts/AppContext.ts, packages/fxa-settings/src/models/hooks.ts, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPassword/ResetPasswordConfirmed/index.test.tsx, packages/fxa-settings/src/pages/ResetPasswordRedesign/AccountRecoveryConfirmKey/container.tsx, packages/fxa-settings/src/pages/Signin/SigninUnblock/container.tsx, packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signin/index.tsx
- We want to securely pass this data between components
- Creates a client that encrypts and decrypts sensitive data that might need to be passed between views
- Stores data in memory and gets cleared on page refresh
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9695
I haven't updated the tests but figured it would be good to check the logic before I refactored components. The intended behavior is to use this instead of passing sensitive data (password, authPW, etc) using `navigate` state.
=> fix(auth): add class for sensitive data that is passed between components

packages/fxa-admin-server/src/app.module.ts, packages/fxa-admin-server/src/gql/gql.module.ts
- Admin server wasn't starting up cleanly
- NotifierService dependencies weren't being provided
- Adds MozLoggerService to providers
- Adds LegacyStatsDProvider to providers
- Removes SentryModule, which is deprecated in favor of direct initialization
Closes: 
=> bug(admin-server): Fixes broken startup behavior

packages/fxa-auth-server/lib/routes/password.ts, packages/fxa-auth-server/test/mocks.js
- The email was still going out, even though the previous change attempted to stop this
- The logic to determine whether or not we were in upgrade state was always false
- Fixes the logic to determine whether or not we were in upgrade state
Closes: FXA-9662
Here's a manual test case:
- Sign up with new account
- Sign out
- Check admin panel and see that account is on v1
- Go to sign in page (add ?stretch=2) to the query
- Sign in
- Check inbox
- Observe that password change email was not sent
- Observe that new sign in email was sent
- Check admin panel
- Observe that account has been upgraded to v2 key stretching
=> bug(auth): Don't send password change email on v2 keystrech upgrade

packages/fxa-auth-server/lib/routes/utils/signin.js, packages/fxa-graphql-api/src/gql/dto/input/sign-in.ts, packages/fxa-settings/src/pages/Signin/SigninUnblock/container.tsx, packages/fxa-settings/src/pages/Signin/SigninUnblock/interfaces.ts
Because:
- the React + gql-api sign in unblock does not handle the "incorrect email" error when the user sign in with a new primary email
This commit:
- retries the unblock sign in with the original sign up email
=> fix(signin): retry signin unblock with signup email

packages/functional-tests/tests/misc/authClientV2.spec.ts
- We should cover support of legacy v1 passwords with a tests.
- Some RPs that have custom implementations will continue to provide v1 credentials.
- Adds some coverage showing that v1 key stretched passwords even after an upgrade.
=> task(functional-tests): Add test showing that v1 ks passwords continue to work after upgrade.

packages/fxa-settings/src/lib/channels/firefox.ts, packages/fxa-settings/src/pages/Signin/utils.ts
Because:
* Users are signed into the browser, but Sync is "off"
This commit:
* Adds `services: sync: {}`  to the fxaLogin web channel message to start Sync
fixes FXA-9791
---
Verify this by creating an account and then launching `fxa-dev-launcher`, click "sign into Sync", add the React params, and login. See Sync says ON.
=> fix(react): Send missing piece of fxaLogin web channel message for Sync login

packages/fxa-admin-server/src/gql/account/account.resolver.spec.ts, packages/fxa-admin-server/src/gql/account/account.resolver.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.spec.ts, packages/fxa-event-broker/src/queueworker/sqs.dto.ts, packages/fxa-graphql-api/src/gql/account.resolver.spec.ts, packages/fxa-graphql-api/src/gql/account.resolver.ts, packages/fxa-graphql-api/src/scripts/must-change-password.ts
- The events were rejected because the 'ts' field was missing
- In auth server this added in by the logger, so it wasn't initially detected
- Adds the ts field to all profileDataChange events emitted by admin-server
- Updates the DTO support additional optional fields
Closes: FXA-9802
=> bug(event-broker): Recently added profile change events were being rejected

packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/container.tsx, packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.tsx, packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/interfaces.ts, packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.tsx, packages/fxa-settings/src/pages/Signin/index.test.tsx
* Redirect back to /subscriptions after signin was not working
* Pass the redirectTo as search param
* Validate the redirectTo and if valid navigate there after signin
Closes: #FXA-9826
When directly hitting /subscriptions (e.g., from subscription renewal email), the user is bounced back to sign in if they aren't logged in. For React signin, we need to pass the redirectTo value that is held by the relier in content-server by adding it as a search param.
We already had logic in the React Signin component to handle the redirectTo, but the value was undefined.
Also added redirectTo handling for signinTokenCode and signinTotpCode.
=> fix(signin): Fix redirect to /subscriptions after signin

packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.tsx
Because:
* Users would be taken to the 2FA page from signin_token_code when they hadn't yet verified 2FA
* There's an edgecase at least in Sync signin causing an invalid token code on this page
This commit:
* Checks for totp verified instead of totp exists
* Uses the sessionToken passed into the component instead of useSession, which was causing console errors
fixes FXA-9836
---
This ended up being a weird one, it'll probably be helpful to read the ticket which has some screenshots.
I first started tackling this because I was working on another React Sync signin bug and saw this case, where a valid code was not being accepted. The console error shown in ticket was suspicious and I was seeing it any time that page is accessed, though it doesn't appear to always be the cause of the invalid …
=> fix(react): Address signin_token_code invalid token error + totp check

packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.tsx
- Recovery codes are alpha numeric so we need to display the `text` keyboard on mobile
- Displays text keyboard on mobile
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9838
=> fix(input): Show text keyboard for recovery code input

packages/fxa-settings/src/pages/InlineRecoverySetup/container.test.tsx, packages/fxa-settings/src/pages/InlineRecoverySetup/container.tsx
- We noticed that gql queries in inline_totp_setup were failing
- The value for service wasn't passing validation
- The service name was being passed instead of the service id
- Passes the service identifier (aka the RPs client id) in for the service value.
- Uses the integration's 'getService' function to determine this value
Closes: FXA-9808
=> bug(settings): Provide correct value for service when verifying 2fa

packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.tsx, packages/fxa-settings/src/pages/Signin/index.tsx
* Subplat subscriptions page sometimes redirects to force_auth and we need to pass params to this page as well as oauth/force_auth
* Update router.js to route force_auth and oauth/force_auth to react
* Only pass redirectTo to navigation handler if integration is web
Closes: #FXA-9826
- To test, use 123Done to add a subscription to an existing account.
- Use the "manage billing" link in the welcome email and append `&forceExperiment=generalizedReactApp&forceExperimentGroup=react` to the link 
- Sign in to the account and expect to be redirected to the subscriptions page.
=> fix(settings): Support subplat redirectTo for force_auth route

packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signin/utils.ts
Because:
* Users are not signed in to Sync after entering their 2FA code
This commit:
* Prevents the fxaLogin web channel message from being sent up if the next page in the navigation flow is TOTP since we send it up on submit on that page
fixes FXA-9837
---
To test this, create an account and add 2FA, then launch `fxa-dev-launcher` and go through the flow in Backbone and observe behavior. Then go through the flow again with React and ensure parity.
Also please double check going through this without TOTP to ensure no regression (which I did test). Might be good also to check the flow that goes through `signin_token_code` (I did not test) but Vijay is working on an intermittent issue in that flow.
=> fix(sync): Do not send fxaLogin on login submit when next page is 2FA

packages/fxa-content-server/server/lib/routes/react-app/index.js
- `oauth/force_auth` was missing in react signin routes
- add routes to list
=> add missing route to react signin routes

packages/fxa-settings/src/lib/gql.ts, packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.tsx
- We get an invalid token when entering 2FA code after being redirected from the `signin_token_code` page
- Passes the `signinState` to the TOTP view which specifies the session token to verify
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9836
I tested this by creating an account, adding 2FA. In a new browser profile, attempt to login, after being prompted for 2FA code, replace url `signin_totp_code` with `signin_token_code`.
The page should redirect to totp page and you should be able to login.
=> fix(totp): pass along signin state to totp view

packages/fxa-shared/subscriptions/configuration/helpers.ts, packages/fxa-shared/subscriptions/configuration/utils.ts, packages/fxa-shared/test/subscriptions/configuration/helpers.ts, packages/fxa-shared/test/subscriptions/configuration/utils.ts
- it was identified by QA that the successActionButtonURL added to a Relay price was not being shown as expected. 
- updates so that price metadata takes priority over Product metadata.
Closes: FXA-9746
=> fix(fxa-shared): Prioritize price metadata over product metadata

packages/eslint-plugin-fxa/lib/configs/default.js, packages/eslint-plugin-fxa/lib/rules/no-test-slow.js, packages/eslint-plugin-fxa/test/no-test-slow.js, packages/functional-tests/.eslintrc.js
- In the last meeting we mentioned that future playwright tests should avoid using `test.slow()` and change default timeout
- Add new eslint rule to check for `test.slow()` usage, shows lint warning if you do use it
=> fix(eslint): Add no test.slow() eslint rule to functional tests

packages/functional-tests/pages/layout.ts, packages/functional-tests/tests/react-conversion/signInConnectAnotherDevice.spec.ts, packages/functional-tests/tests/react-conversion/signInRelyingParties.spec.ts, packages/functional-tests/tests/react-conversion/signinTotp.spec.ts, packages/functional-tests/tests/react-conversion/syncV3SignIn.spec.ts, packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx, packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.test.tsx, packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signin/utils.ts, packages/fxa-settings/src/pages/Signup/index.test.tsx
- We were having intermitant issues when logging in using the React signin and Sync
- Adds an await to the `fxaLogin` message so that the browser has a chance to process it completely
- Updates our functional and unit tests to correctly await
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9836
=> fix(login): remove webchannel login when at signin token code load

packages/functional-tests/tests/resetPassword/resetPasswordWithCode/oauthResetPassword.spec.ts, packages/functional-tests/tests/resetPassword/resetPasswordWithCode/resetPasswordRecoveryKey.spec.ts
* Two tests were failing smoke tests
* Fix the PKCE test by using the correct url by environment (removed stray localhost)
* Fix failing assertion that was causing email check to fail
Closes: #FXA-9800
=> fix(functional-tests): Reset password with code tests failing on stage

.devcontainer/devcontainer.json
Because:
* It's useful having some CLI tooling for the fxa stack installed by default in the devcontainer.
This commit:
* Adds mycli, redis, and gcloud to the devcontainer.
=> chore: add mycli, redis, and gcloud to devcontainer

.devcontainer/devcontainer.json
Because:
* The other gcloud feature require arch linux, ours is debian based.
This commit:
* Changes the gcloud feature to one that works with debian based systems.
=> fix: use working gcloud feature in dev container

packages/fxa-settings/src/components/Settings/ModalVerifySession/index.tsx
- Calling `session.isSessionVerified` updates the apollo cache of session info, which I think causes a render of the component
- Removes that check and uses the current value `session.verified` to send email
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9835
I tried removing the depencies on the `useEffect` hook, which in theory should make the component render once, it didn't :/
=> fix(emails): Dont use `session.isSessionVerified` in modal since it causes re-render

packages/fxa-auth-server/package.json, packages/fxa-content-server/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json, yarn.lock
Because:
* Our 'yarn glean-generate' command was failing with 'No module named 'pkg_resources', and this is fixed in latest Glean
This commit:
* Upgrades the package
---
@jonalmeida filed an issue for the issues we've ran into with `yarn glean-generate` [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1902584) and we were informed upgrading resolves the issue.
=> chore(deps): Upgrade Glean for glean-generate bug fix

packages/fxa-content-server/app/scripts/views/base.js
* If the user reaches a page where they must reauth, for example when following a link from email, we want to suggest the provided email for signin instead of asking the user to re-enter their email (matching parity with backbone)
* When reauth is required and there is a redirect to force_auth, set the email on the user model so it can be picked up when navigating to react
Closes: #FXA-9855
One way to test:
1. Have an account created with a product subscription (subscribe to a product via 123Done)
2. Sign out of the account 
3. From the subscription welcome email, look for the "Update billing information" link
a. For backbone: follow the link and observe that …
=> fix(content): Set email for force_auth with React signin

packages/functional-tests/tests/react-conversion/signInConnectAnotherDevice.spec.ts, packages/functional-tests/tests/react-conversion/signInRelyingParties.spec.ts, packages/functional-tests/tests/react-conversion/signinTotp.spec.ts, packages/functional-tests/tests/react-conversion/syncV3SignIn.spec.ts, packages/fxa-settings/src/lib/channels/firefox.ts
- I think part of the issue with Sync was getting two login webchannel messages, the other part was not specifiying services in the message
- Removes test code that could make false positive results
- Adds login message when `signin_token_page` is loaded only
- Adds empty services on login message
Closes:
=> fix(login): fix sync login issue with react

packages/fxa-content-server/app/scripts/views/mixins/third-party-auth-mixin.js, packages/fxa-content-server/app/tests/spec/views/mixins/third-party-auth-mixin.js, packages/fxa-settings/src/components/ThirdPartyAuth/index.tsx
- Some metrics did not have corresponding complete events for third party auth
- If flowId was not provided in the query string, none would be used
- Always defer to using the flowId in the metrics model when redirecting in third party auth, this id is either pulled from query params or generated if not present
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9564
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9767
I ran through this locally and the flowId stays consistent throughout the third party auth login. No changes are needed in React since it always gets a flowId sent to its views from content-server.
| Component          | Operation       | Event Type                                 | Time           | User ID                        | Device ID                         | …
=> fix(metrics): always use the metrics flow data in `Metrics` model when redirecting in third party auth

packages/fxa-auth-server/lib/log.js, packages/fxa-auth-server/test/local/log.js, packages/fxa-event-broker/src/queueworker/sqs.dto.ts
- Client Ids with values 'none' were making their way to the event broker
- This was happening because 'none' is a valid value for service, and service is sometimes a fallback for client id.
- Creates stricter checks on what a valid client id is.
Closes: FXA-9802
Note that FXA-9802 has already been 'fixed'. For some reason sentry is grouping a couple validation errors together that are actually unrelated. Unfortunately, I can't reconcile this in Sentry, which is why I'm pulling this in as a part 2 fix.
=> bug(auth,event-broker): Don't allow invalid client ids through

packages/fxa-auth-server/lib/routes/oauth/key_data.js
- Trying to a new an object doesn't work, and results in a 'not a constructor' error.
- Removes the erroneous 'new' keyword.
Closes: FXA-9861
=> task(auth-server): Fix invalid call

.circleci/config.yml, packages/functional-tests/playwright.config.ts
- We want to integrate inbuilt HTML reporting with Playwright together with blob reporting
- Creates blob reports (.zip) for the test run for each parallel running machine
- Merges the test reports from 8 parallel machines running the tests
- Creates a HTML dashboard to display the functional test run details using the merged .zip file
- Adds an additional `Merge-Report` workflow and `playwright-functional-test-report` job in the config file
- Generates a `playwright-report/index.html` in the artifacts section on CircleCI, clicking which displays the dashboard
- All the above steps are integrated for local PRs and nightly
Closes: FXA-8998 FXA-9857
=> chore(functional): integrate html reporting with Playwright

packages/fxa-content-server/app/scripts/lib/glean/index.ts, packages/fxa-content-server/app/scripts/views/pair/index.js, packages/fxa-content-server/app/tests/spec/views/pair/index.js
Because:
* There are a couple of bugs we want to address with the existing CAD metrics
This commit:
* Swaps the event reason on choice submission, as they were inversed
* Fixes the Glean event map to cad_firefox_choice_view, as it referenced cad_firefox_view
* Only emits the 'cad_firefox_sync_device_submit' event when user reaches the "needs mobile" screen and clicks "Continue to sync"
fixes FXA-9834, fixes FXA-9833, fixes FXA-9832
=> fix(glean): Tweak view/submit CAD Glean events

packages/fxa-content-server/app/scripts/lib/app-start.js, packages/fxa-content-server/app/scripts/lib/nimbus/index.ts, packages/fxa-content-server/app/scripts/views/sign_in_password.js, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/server/lib/routes.js, packages/fxa-content-server/server/lib/routes/post-nimbus-experiments.js
- We want to integrate Nimbus experimentation into FxA UI.
- We fetch the experiments as a passthrough between the app and server so we don't have to expose another service. In this patch, we've also added the experiments to the sign-in page context.
Closes: # FXA-9788
=> task(content): Add cirrus integration to Backbone

packages/fxa-settings/src/lib/channels/firefox.ts, packages/fxa-settings/src/pages/ResetPasswordRedesign/CompleteResetPassword/container.tsx
* Sync was disabled after resetting password during a sync sign in
* Add services to the FxaLoginSignedInUserRequest webchannel message used by reset password
Closes: #FXA-9870
=> fix(fxa-settings): Enable sync after password reset

packages/fxa-content-server/app/scripts/lib/glean/email.js, packages/fxa-content-server/app/scripts/lib/glean/index.ts, packages/fxa-content-server/app/scripts/views/mixins/third-party-auth-mixin.js, packages/fxa-content-server/app/tests/spec/lib/glean.js, packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml
This doesn't seem like the best way for landing these metrics. I believe we should be using glean extras to add the provider to be either `google` or `apple`, but I've been struggling to get the `EventProperties` type checking to add a new property.
Open question: 
- should I add the fxa-settings equivalent in this patch too?
- is the test coverage sufficient?
- Adds `google_oauth_email_first_start` and `apple_oauth_login_start`.
Closes: FXA-9809, FXA-9808
=> fix(metrics): Add Google and Apple signin telemetry

packages/functional-tests/tests/react-conversion/oauthSignin.spec.ts, packages/fxa-content-server/server/lib/routes/react-app/index.js
- Not ready for full prod rollout
- Revert React Signin fullProdRollout flag to false
=> revert react signin full prod flag

packages/functional-tests/pages/baseTokenCode.ts, packages/functional-tests/pages/signup.ts, packages/functional-tests/tests/oauth/webchannel.spec.ts, packages/functional-tests/tests/react-conversion/forceAuth.spec.ts, packages/functional-tests/tests/react-conversion/signInConnectAnotherDevice.spec.ts, packages/functional-tests/tests/react-conversion/signinTotp.spec.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/functional-tests/tests/react-conversion/syncV3SignIn.spec.ts, packages/functional-tests/tests/resetPassword/resetPasswordWithCode/oauthResetPasswordSyncMobile.spec.ts, packages/functional-tests/tests/resetPassword/resetPasswordWithLink/oauthResetPassword.spec.ts, packages/functional-tests/tests/resetPassword/resetPasswordWithLink/oauthResetPasswordSyncMobile.spec.ts, packages/functional-tests/tests/signin/signIn.spec.ts
- Tests were failing in parallel runs, but passing in isolation
- Appears to mainly be caused by missing syncBrowserPages fixture in sync-related tests
- Applies `syncBrowserPages` where it was missing 
Closes: [FXA-9914](https://mozilla-hub.atlassian.net/browse/FXA-9914)
[FXA-9914]: https://mozilla-hub.atlassian.net/browse/FXA-9914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(functional-tests): Address isolation issues caused by sync tests

packages/fxa-settings/src/components/DataBlock/mocks.tsx, packages/fxa-settings/src/components/DataBlockManual/index.stories.tsx, packages/fxa-settings/src/components/DataBlockManual/index.tsx, packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.tsx, packages/fxa-settings/src/pages/InlineTotpSetup/index.test.tsx, packages/fxa-settings/src/pages/InlineTotpSetup/index.tsx
Because:
* We were not properly displaying this code on the inline TOTP page
This commit:
* Creates a new component to share with where we display this code inside Settings, and uses it in both locations
* Adds new component to Storybook, updates test
fixes FXA-9916
---
Before and after:
=> fix(inline-totp): Display totp code for manual entry

packages/fxa-content-server/app/scripts/lib/glean/index.ts, packages/fxa-content-server/app/tests/spec/lib/glean.js, packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml
- We want to track these events
- Updates the name since the work was done in https://mozilla-hub.atlassian.net/browse/FXA-9116
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9821
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9822
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9823
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9824
I didn't realize when I worked on the ticket that I made separate issues for each of this. The work was done in https://mozilla-hub.atlassian.net/browse/FXA-9116. This PR just updates the name to match what we have in https://docs.google.com/spreadsheets/d/1DgohA2JG8gvFOjk_8zUHOi6DSDSPzqCCwoNVvirDpkA/edit#gid=1073857271
=> feat(metrics): Update the Glean name for `third_party_auth_set_password` metrics

packages/functional-tests/pages/relier.ts, packages/functional-tests/tests/oauth/oauthPromptNone.spec.ts
* Error message was not awaited properly causing tests to error in smoke tests
* Await error message without using class selector
Closes: #FXA-9932
=> fix(functional-tests): Await oauth prompt none error

packages/functional-tests/pages/products/index.ts, packages/functional-tests/pages/products/subscriptionManagement.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts
* the test fails due to the incorrect comparison of the total with the resubscriptionPrice
* fixes the test by comparing resubscriptionPrices
Closes: #FXA-9912
=> fix(functional-tests): resubscribe successfully with the same coupon after canceling for stripe

packages/functional-tests/pages/login.ts, packages/functional-tests/pages/signup.ts, packages/functional-tests/tests/react-conversion/oauthSignup.spec.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts
- many updates have been made to improve isolation since March and the tests no longer exhibit flake locally
- removes the fixme annotation from: 
- react-conversion/oauthSignup.spec.ts:96:9 › severity-1 #smoke › signup react › signup oauth webchannel - sync mobile or FF desktop 123+ 
- react-conversion/signup.spec.ts:53:9 › severity-1 #smoke › signup react › signup sync desktop v3, verify account
- removes waitForRoot from SignupPage
- removes CWTSEngineOpenTabs from LoginPage
Closes: # FXA-9306
=> fix(functional-tests):  remove fixmes from webchannel tests

packages/fxa-settings/src/pages/ResetPasswordRedesign/ConfirmResetPassword/index.tsx
- We want the entire image to be visible
- Update styling of the image
Closes: #FXA-9911
Before:
After:
=> fix(settings): ConfirmResetPassword image cut off on small screens

packages/functional-tests/tests/signin/signIn.spec.ts, packages/functional-tests/tests/signin/signinCached.spec.ts, packages/fxa-settings/src/pages/Signin/container.tsx
* Confirmation code emails (either for unverified session or unverified account) were not sent out during cached signin with React (but clicking "Email new code" worked
* We want to ensure that an email is immediately sent out
* We want to match parity with Backbone
* Send out the email during cached signin if the account or session are unverified
* Update the cached signin functional test
* Add a new functional test for unverified signin
Closes: #FXA-9878
- Use React params `http://localhost:3030/?forceExperiment=generalizedReactApp&forceExperimentGroup=react`
- Signup for a new account, but *DON'T* confirm it on `confirm_signup_code`
- Go back to …
=> fix(fxa-settings): Ensure confirmation emails are sent for cached signin

packages/fxa-payments-server/src/components/PayPalButton/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
- When the paypal button fails to load during initialization, for example when there is a PayPal sandbox outage, the subscription checkout page loads into an error, instead of hiding the PayPal button.
- This has resulted in a confusing user experience, as well as causing unrelated functional test failures due to the error page being shown.
- If the PayPal button does not successfully finish it's onInit function, then hide the PayPal button instead of showing an error message.
- If any other PayPal error occurs, continue showing the error page.
Closes: #FXA-9886
The only way I found to replicate the failure scenario is to manually call the `onError` function before `onInit` completes.
Please attach the screenshots of the changes made in case of change …
=> fix(payments): hide paypal on paypal init failure

packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponExpired.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponInvalid.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponOneTimeDiscount.spec.ts
- on the stage environment applying coupons fails with the error message 'An error occured processing the code. Please try again.' indicating that we've hit a rate limit. Since adding fixmes improvements restricting the number of retries and updating tests to use auto-awaiting asserts have been implemented.
- removes the fixmes to see if rate limiting is still an issue
Closes: # FXA-9689
=> fix(functional-tests): subscription coupon tests failing on stage

packages/fxa-content-server/app/scripts/views/base.js
- Email address is lost when accessing the “here” link from “Automatic renewal notice” email with the force experiment parameter added
- Set the email on emailFromIndex instead of email to ensure it is passed to React force_auth/signin
Closes: #FXA-9975
If a renewal notice is not available for testing, these steps may be an adequate scenario for testing:
- Have an account with an active subscription (e.g., added from 123done);
- Sign out of account and clear local storage (localhost:30330/clear)
- Go to localhost:3030/subscriptions with React experiment params and account email as param
e.g. with an account created for test@gmail.com: …
=> fix(content): Email from subscriptions redirect not passed to react

packages/fxa-content-server/app/scripts/views/mixins/third-party-auth-mixin.js
- The metrics were behind the wrong view name.
- Updates that to what it should be now.
Closes: [FXA-9809](https://mozilla-hub.atlassian.net/browse/FXA-9809), [FXA-9808](https://mozilla-hub.atlassian.net/browse/FXA-9808)
Better tests for this will be covered in FXA-9816 and FXA-9817.
[FXA-9809]: https://mozilla-hub.atlassian.net/browse/FXA-9809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FXA-9808]: https://mozilla-hub.atlassian.net/browse/FXA-9808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(metrics): Update viewName for sign-in metrics

packages/functional-tests/tests/react-conversion/oauthSignup.spec.ts
Because:
* This test is not reliably passing
This commit:
* Adds a fixme to this test temporarily
=> chore(tests): Add fixme to flaky signup oauth webchannel test

packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/BrandMessaging/index.stories.tsx, packages/fxa-settings/src/components/FormPassword/index.stories.tsx, packages/fxa-settings/src/components/Settings/AppLayout/index.stories.tsx, packages/fxa-settings/src/components/Settings/AppLayout/index.test.tsx, packages/fxa-settings/src/components/Settings/AppLayout/index.tsx, packages/fxa-settings/src/components/Settings/AppLayout/mocks.tsx, packages/fxa-settings/src/components/Settings/DropDownAvatarMenu/index.stories.tsx, packages/fxa-settings/src/components/Settings/DropDownAvatarMenu/index.test.tsx, packages/fxa-settings/src/components/Settings/DropDownAvatarMenu/index.tsx, packages/fxa-settings/src/components/Settings/FlowRecoveryKeyConfirmPwd/index.stories.tsx, packages/fxa-settings/src/components/Settings/HeaderLockup/index.stories.tsx, packages/fxa-settings/src/components/Settings/HeaderLockup/index.test.tsx, packages/fxa-settings/src/components/Settings/HeaderLockup/index.tsx, packages/fxa-settings/src/components/Settings/Page2faReplaceRecoveryCodes/index.stories.tsx, packages/fxa-settings/src/components/Settings/PageAvatar/index.stories.tsx, packages/fxa-settings/src/components/Settings/PageChangePassword/index.stories.tsx, packages/fxa-settings/src/components/Settings/PageCreatePassword/index.stories.tsx, packages/fxa-settings/src/components/Settings/PageDeleteAccount/index.stories.tsx, packages/fxa-settings/src/components/Settings/PageDisplayName/index.stories.tsx, packages/fxa-settings/src/components/Settings/PageSecondaryEmailAdd/index.stories.tsx, packages/fxa-settings/src/components/Settings/PageSecondaryEmailVerify/index.stories.tsx, packages/fxa-settings/src/components/Settings/PageSettings/index.stories.tsx, packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.stories.tsx, packages/fxa-settings/src/components/Settings/index.test.tsx, packages/fxa-settings/src/components/Settings/index.tsx, packages/fxa-settings/src/components/Settings/interfaces.ts, packages/fxa-settings/src/components/Settings/mocks.tsx
Because:
* Users that sign out from within account settings destroy their session token but we don't tell the browser it's become invalid. Users trying to access settings again in mobile run into a case where we redirect them to oauth signin, causing problems with at least 2FA login in this scenario
This commit:
* Sends the integration down as a prop into DropDownAvatarMenu so we can conditionally send the webchannel message if the flow is Sync
* Adds unit tests, updates all stories/tests/mocks
closes FXA-9919
---
Product confirmed on Slack that this is the fix we want to implement. In at least iOS there's a menu that still comes up once the command is received for logout, [see video/thread](https://mozilla.slack.com/archives/C4DCECLGJ/p1719270947515019?thread_ts=1719270799.780619&cid=C4DC …
=> fix(sync): Send fxaLogout message on settings sign out if sync

packages/functional-tests/tests/oauth/totp.spec.ts, packages/functional-tests/tests/resetPassword/resetPasswordWithCode/oauthResetPassword.spec.ts, packages/functional-tests/tests/resetPassword/resetPasswordWithLink/oauthResetPassword.spec.ts, packages/functional-tests/tests/syncV3/signIn.spec.ts
* We were not await confirmation that totp was enabled before signing out of settings in tests
* This could cause a race condition where totp setup was incomplete before sign out, causing flakiness in tests
* Add assertion for totp enabled after forms are filled out
Closes: #FXA-10001
=> fix(functional-tests): Await confirmation of totp setup in tests

packages/fxa-settings/src/lib/glean/index.ts, packages/fxa-settings/src/pages/CannotCreateAccount/index.test.tsx, packages/fxa-settings/src/pages/CannotCreateAccount/index.tsx, packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml, packages/fxa-shared/metrics/glean/web/index.ts, packages/fxa-shared/metrics/glean/web/reg.ts
- We want a metric recorded when a user enters an invalid age
- Creates the reg_age_invalid glean metric
- Fires the event on the cannot_create_account page
Closes: FXA-9421
Test instructions
- Signup for an account
- Enter email
- Enter passwords
- For age enter 10
- Click Continue
- Observe the page saying 'You must meet certain age requirements to create a ⁨Mozilla account⁩.'
- Observe that the reg_invalid_age metric was fired
=> task(settings): Add reg_age_invalid glean metric

.circleci/config.yml
- The reports were not generating for parallel machines that had failed tests runs.
- Added the `when` parameter to config.yaml file for the 'rename reports' step
- Added condition to rename files when the reports otherwise provide an apt message 
- Added if condition for merging the reports when the report exist otherwise provide an apt message
Closes: FXA-9885 FXA-9979
=> fix(html_report): add if statement

packages/fxa-content-server/server/lib/beta-settings.js, packages/fxa-content-server/server/lib/flow-metrics.js, packages/fxa-content-server/server/lib/routes/get-index.js, packages/fxa-content-server/server/lib/routes/get-metrics-flow.js, packages/fxa-settings/public/index.html, packages/fxa-settings/src/components/App/index.test.tsx, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/lib/glean/index.test.ts, packages/fxa-settings/src/lib/glean/index.ts, packages/fxa-settings/src/lib/metrics-flow.test.ts, packages/fxa-settings/src/lib/metrics-flow.ts
Because:
- we need to able to get metrics flow data directly in React/Settings without relying on query params
This commit:
- injects a flow id and begin time into the HTML of the React page
- sets the metrics flow data for the app in the precedence of 0) direct argument, 1) query params, 2) body data attrs
=> feat(metrics): set metrics flow data via data attrs

packages/fxa-content-server/app/scripts/lib/glean/index.ts, packages/fxa-content-server/app/scripts/lib/glean/login.js, packages/fxa-content-server/app/scripts/views/sign_in_password.js, packages/fxa-content-server/app/tests/spec/views/sign_in_password.js, packages/fxa-settings/src/lib/glean/index.ts, packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signin/index.tsx, packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml, packages/fxa-shared/metrics/glean/web/index.ts, packages/fxa-shared/metrics/glean/web/login.ts
- We want to know when users click the "Use a different account" link on the login page.
- Adds a Glean telemetry probe for that link.
Closes: FXA-9570
=> feat(glean): Add login_diff_account_link_click event to login page

packages/fxa-auth-server/scripts/paypal-processor.ts, packages/fxa-shared/sentry/node.ts
- Sentry errors logged by the paypal processor did not include additional error information.
- Update paypal processor script to use initSentry, which includes additional Sentry integrations, such as ExtraErrorData.
- Replace deprecated ExtraErrorData integration with Sentry.extraErrorDataIntegration()
Closes: #FXA-9219
=> fix(paypal-processor): use initSentry helper

packages/fxa-content-server/package.json, packages/fxa-shared/package.json
Because:
- the diff looks large because the Glean generated code uses double quotes whereas our code base uses single quotes
This commit:
- runs the same prettier fix that's part of the pre-commit hook immediately after generating the code
=> chore(Glean): run prettier after generate Glean code

.devcontainer/devcontainer.json
Because:
* glean-generate needs venv and pip to run correctly
This commit:
* Add missing Python venv/pip dependencies.
=> chore: add missing deps for glean-generate

packages/functional-tests/tests/syncV3/fxDesktopV3ForceAuth.spec.ts, packages/fxa-settings/src/lib/channels/firefox.ts, packages/fxa-settings/src/pages/Signin/container.tsx
Because:
* In Backbone we ask users to confirm that they want to merge their Sync data on submission of password signin, if the flow is force_auth since they haven't answered the prompt at this point. We want to do the same for React
This commit:
* Modifies the fxaCanLinkAccount web channel message to return a promise waiting for the browser's response, and only proceeds if the user confirms
fixes FXA-9868
---
Our functional tests for force auth covers this case, but I can add a couple of unit tests if we want.
Maybe there's a better way to test this but I launched `fxa-dev-launcher`, then console.logged the [test credentials](https://github.com/mozilla/fxa/blob/7d6ae428b4399ec897e0c87c9e1dc014584028ce/packages/functional-tests/pages/forceAuth/index.ts#L28-L29) and …
=> fix(sync): Send fxaCanLinkAccount in force_auth signin submit

packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponExpired.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponForeverDiscount.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponInvalid.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponOneTimeDiscount.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/paymentMode.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/ui-tests.spec.ts, packages/functional-tests/tests/subscription-tests/subscription.spec.ts, packages/functional-tests/tests/subscription-tests/subscriptionFixtures.ts, packages/functional-tests/tests/subscription-tests/support.spec.ts
- coupon tests are failing in stage due to IP rate limiting
* adds signin as a pre-requisite to coupon tests 
* since all subscription tests now require signin, the steps have been encapsulated in an automatic fixture to reduce code duplication (subscriptionFixtures.ts)
* without signin rate limiting is measured per IP, with signin it is measured per account. Since tests have isolated accounts, signing in should add the resilience we need. 
Closes # FXA-10045
=> fix(functional-tests): failures due to rate limiting in coupon tests

packages/functional-tests/tests/subscription-tests/coupons-ui-tests/ui-tests.spec.ts
- this test is failing causing disruption to CI and development
- adds a fixme annotation until a proper fix can be added
Relates to: #FXA-10014
=> chore(functional-tests): add a fixme annotation to verify plan change funnel metrics & coupon feature not available when changing plans

packages/fxa-settings/src/lib/glean/index.ts, packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signin/index.tsx, packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml, packages/fxa-shared/metrics/glean/web/index.ts, packages/fxa-shared/metrics/glean/web/login.ts
- We want to know when a user interacts with the password field
- Adds the login_engage event
- Fires the event when a user focuses on the password input
Closes: FXA-9569
Test Instructions
- Create account
- Login
- Focus on password field
- Observe metric
=> task(settings): Add event when users engages with login password

packages/fxa-settings/src/components/ThirdPartyAuth/index.test.tsx, packages/fxa-settings/src/components/ThirdPartyAuth/index.tsx
- Third party auth fails when logging in with a different email than one already logged in (React)
- Sets the `state` param when lauching auth so that it logs in correct user
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10046
Testing steps
1. Be enrolled in React signin experiment
2. Log in with a user ( ex a@aa.com)
3. Sign out
4. Log in with Google user
=> fix(auth): Set state when navigating with third party auth in React

packages/fxa-settings/src/lib/oauth/hooks.tsx
- We can hit a state where Firefox will direct a user to sign in and the redirect uri, or client id won't be present
- This state is erroneous, but it'll take a bit for the fix in FF to be released.
- shortCircuits checkOauthData when we are dealing with a sync integration.
- Sync doesn't need to redirect back to a third party anyway, so this is probably okay.
Closes: FXA-10029
I had a hard time testing this locally... Testing on stage is needed.
=> bug(settings): Skip checkOauthData for sync

packages/functional-tests/pages/settings/layout.ts, packages/functional-tests/tests/signin/signinCached.spec.ts
* Sign in cached, sign in once, use a different account test was failing on the sign out step due to redirect to cached signin
* Update the sign out function to check for redirect away from settings but allow for different destinations (email first or sign in, for example)
* Remove the refresh in the test (not needed) and replace with URL check
Closes: #FXA-10064
=> fix(functional-test): Cached signin test failing on redirect

packages/fxa-settings/src/lib/channels/firefox.ts
- On android mobile this response for 'CanLinkAccount' comes back immediately and no pop up is displayed.
- As result, we potentially have a result, and the eventHandler might not be bound.
- Attach the event handler before sending the message.
Closes: FXA-10057
This is a bit tricky test on mobile at the moment. Final validation is needed on staging.
=> bug(settings): Make sure event handler is attached before message is sent

packages/fxa-settings/src/lib/channels/firefox.ts
Because:
* Android responds immediately to the can_link_account message and we don't appear to always have the event listener attached
This fix:
* Adds requestAnimationFrame, as we have needed to use this a couple of times before for testing when the response back was immediate
fixes FXA-10057
=> fix(sync): Use requestAnimationFrame to ensure event handler is attached before event

packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signin/index.tsx
* Avatar for a different cached account was shown after clicking on "Use a different account"
* Show the default avatar if there is no session token
* Update unit tests to test for custom avatar shown for cached sign in with session token, and default avatar without session token, including tests for both scenarios with passwordless accounts
Closes: #FXA-10044
=> fix(settings): Only show custom avatar for cached sign in

packages/fxa-settings/src/lib/channels/firefox.ts
- When signing into sync on Android,  the signin button can become 'stuck'
- Yesterday we uncovered a race condition that seemed to help, but didn't totally fix the problem.
- The event handler in fxaCanLinkAccount was too general and could pick up events that were not intended for it.
- Uses `this.addEventListener(FirefoxCommand.CanLinkAccount` instead of `window.addEventListener('WebChannelMessageToContent'...`
- Doing so ensures that only responses for the CanLinkAccount command are handled.
Closes: FXA-10057
Note, we should avoid using `window.addEventListener('WebChannelMessageToContent'`
=> Bug(settings): Fix for 'stuck' sign in button p2

packages/fxa-content-server/app/scripts/lib/glean/index.ts
- Some of the recently added `cad_` events are not sent in `events` ping
- Attempts to send missing events in events ping
Closes: issue described in https://mozilla-hub.atlassian.net/browse/DENG-3273?focusedCommentId=908657
=> fix(metrics): DENG-3273 Send cad_ events in events ping

packages/fxa-settings/src/components/Settings/ConnectAnotherDevicePromo/en.ftl, packages/fxa-settings/src/components/Settings/ConnectAnotherDevicePromo/index.test.tsx, packages/fxa-settings/src/components/Settings/ConnectAnotherDevicePromo/index.tsx
Because:
* This link no longer allows users to get a text via SMS, so we're removing it
This commit:
* Removes the link and updates copy
fixes FXA-9983
---
While looking at FXA-10049 I remembered this (FXA-9983) recently filed issue and confirmed we don't want this event and want to remove the link.
=> fix(settings): Remove obsolete 'send download link' link

packages/fxa-settings/src/lib/oauth/hooks.tsx
Reverts mozilla/fxa#17208
See comment on that PR. This was working for Backbone signin, so we thought the client-side React check could be short-circuited here, but it errors out later in the flow and this wasn't the fix.
=> Revert "bug(settings): Skip checkOauthData for sync"

packages/fxa-settings/src/components/Settings/ConnectAnotherDevicePromo/index.tsx, packages/fxa-settings/src/components/Settings/ConnectedServices/index.tsx, packages/fxa-settings/src/lib/glean/index.test.ts, packages/fxa-settings/src/lib/glean/index.ts, packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml, packages/fxa-shared/metrics/glean/web/accountPref.ts, packages/fxa-shared/metrics/glean/web/index.ts
- We want metrics to track when user clicks disconnect from settings, and click Apple/Google play store buttons
- Adds those metrics
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10043
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10048
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10047
=> feat(metrics): Add glean metrics for apple, google, and disconnect settings button

.circleci/config.yml, packages/functional-tests/tests/settings/changeEmail.spec.ts
- `severity-1 #smoke › change primary email tests › change primary email, change password, login, change email and login` test was failed in prod once
- Html reporting needed to be added with smoke test in Stage and Prod
- Adds a different expect method for rendering settings page
- integrates html reporting with smoke tests in Stage and Prod
Closes: FXA-10028 FXA-10059
=> fix(functional): integrate html reporting for smoke tests

packages/fxa-settings/src/components/Settings/LinkedAccounts/LinkedAccount.tsx, packages/fxa-settings/src/components/Settings/LinkedAccounts/index.test.tsx, packages/fxa-settings/src/components/Settings/LinkedAccounts/index.tsx, packages/fxa-settings/src/lib/glean/index.test.ts, packages/fxa-settings/src/lib/glean/index.ts, packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml, packages/fxa-shared/metrics/glean/web/accountPref.ts, packages/fxa-shared/metrics/glean/web/index.ts
Because:
* We want to track metrics events on Unlink click from settings, and Unlink confirm, with 'create_password' reason if the user needed to first set a password
This commit:
* Adds events account_pref_google_unlink_submit, account_pref_google_unlink_submit_confirm, account_pref_apple_unlink_submit, account_pref_apple_unlink_submit_confirm
* Includes 'reason' in events if user does not have a password set
* Updates some tests and one warning
closes FXA-10050, closes FXA-10051
--
See [Slack thread](https://mozilla.slack.com/archives/C04LVV8V8BA/p1721062687040009) for context around the two extra events and the `reason`.
=> feat(glean): Add unlink account submit and confirm submit events

packages/fxa-settings/src/components/Settings/Profile/index.tsx, packages/fxa-settings/src/components/Settings/UnitRowSecondaryEmail/index.tsx, packages/fxa-settings/src/lib/glean/index.test.ts, packages/fxa-settings/src/lib/glean/index.ts, packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml, packages/fxa-shared/metrics/glean/web/accountPref.ts, packages/fxa-shared/metrics/glean/web/index.ts
* We want to track metrics for clicks to add/change display name and add a secondary email
* Adds and implements glean events account_pref_display_name_submit and account_pref_secondary_email_submit
Closes: #FXA-10041, FXA-10042
=> feat(glean): Add frontend glean events for settings profile CTAs

packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/fxa-settings/src/lib/channels/firefox.ts
- We saw positive results from doing the same thing for the CanLinkAcocunt web channel message
- Updates the FxaLogin web channel message
Closes: FXA-10074
=> task(settings): Stop using window.addEventListener for web channel messages

.circleci/config.yml, packages/fxa-auth-server/lib/metrics/glean/index.ts
Because:
- it's unwieldy
This commit:
- calls the metric event record method based on the string event name
=> chore(metrics): remove the switch to call event metrics in auth-server

packages/fxa-graphql-api/src/auth/session-token.strategy.ts, packages/fxa-graphql-api/src/gql/session.resolver.spec.ts, packages/fxa-graphql-api/src/gql/session.resolver.ts, packages/fxa-settings/src/components/App/index.test.tsx, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/Settings/SignoutSync/en.ftl, packages/fxa-settings/src/components/Settings/SignoutSync/index.stories.tsx, packages/fxa-settings/src/components/Settings/SignoutSync/index.test.tsx, packages/fxa-settings/src/components/Settings/SignoutSync/index.tsx, packages/fxa-settings/src/lib/cache.ts, packages/fxa-settings/src/lib/channels/firefox.ts, packages/fxa-settings/src/lib/storage-utils.ts, packages/fxa-settings/src/models/Session.ts
- If users sign out in manner where the browser isn't notified, they can end up in a weird state when accessing settings.
- Asks Firefox for the current user
- Checks the current user's session token
- If the current session is token, uses it thereby letting the user access settings
- If the current session is not valid, a message is displayed saying to signout from sync.
Closes: FXA-10029
Edge where this code becomes active can be hit with these two scenarios:
Local cache cleared behind Firefox’s back
1. Create an account email+1@gmail.com
2. Click firefox menu > Sync and save data
3. Select use email instead
4. Sign in with email+1@gmail.com
5. Provide confirmation code
6. Observe settings page
7. Close settings page
8. In new tab (ie not from sync), …
=>  bug(settings): Fix android manage account settings glitch 

.yarnrc.yml
Because:
* Dependabot is running yarn in a manner that breaks the env var replacmeent in .yarnrc.yml.
This commit:
* Removes the env var replacement in .yarnrc.yml.
Closes FXA-10002
=> fix: avoid env vars due to dependabot bug

packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/lib/channels/firefox.ts
Because:
* There's a case where the session token given back from requestSignedInUser is undefined
This commit:
* Makes sure the sessionToken is defined before checking its validity and using it
fixes FXA-10156
=> fix(sync): Check and set sessionToken from browser only when provided

packages/fxa-settings/src/components/CardHeader/index.tsx
- It wasn't rendering the service image
- Removes the extra `span` around the image
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10163
=> fix(image): Fix issue with Pocket logo in cache signin page

packages/functional-tests/tests/react-conversion/oauthSignin.spec.ts
Reverts mozilla/fxa#17235
This test failure during nightly run may have been a one-off fluke, the failure is not replicating when run against local or stage.
See https://mozilla-hub.atlassian.net/browse/FXA-10102
=> Revert "chore(functional-tests): add fixme to verified account with cached login, no email confirmation required"

packages/fxa-auth-server/lib/metrics/glean/index.ts, packages/fxa-auth-server/test/local/metrics/glean.ts
Because:
- for the auth server backend Glean events, we resolve the event metric method based on the string event name
- but we currently do that in the created function for the event
This commit:
- resolves the method during the initial function creation for the event functions, e.g. during server startup
=> fix(metrics): resolve the event metric method at server start

packages/fxa-auth-server/lib/metrics/glean/index.ts, packages/fxa-auth-server/test/local/metrics/glean.ts
Because:
- the options for an event's function was not enclosed with the returned event function in the auth server, leading to the optional callback not being called
This commit:
- ensure the options for the event function is enclosed with the created event function
Fixes FXA-10169
=> fix(metrics): enclose the event function options

packages/fxa-content-server/app/scripts/models/auth_brokers/pairing/authority.js, packages/fxa-content-server/app/scripts/models/pairing/supplicant-state-machine.js, packages/fxa-content-server/app/scripts/templates/pair/failure.mustache, packages/fxa-content-server/app/scripts/views/pair/failure.js, packages/fxa-content-server/app/tests/spec/models/pairing/supplicant-state-machine.js
- When Firefox iOS goes into the background, iOS will close websocket connections based on system resources, this closes the pairing channel and causes it to fail
- Since we can't control what iOS does, the next best option is to give the user an option to login with another method (email/password)
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10056
I've filed https://github.com/mozilla-services/channelserver/issues/115 which maybe another option, but would require more effort.
=> fix(pairing): Give users option to login with email if pair failed

packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signin/index.tsx
- The login engage metric was being emitted too many times
- Ensures the metric can only be emitted once
Closes: FXA-10171
I tried doing this with focus / blur, but it didn't work well due to the field being auto focused by default.
=> bug(settings): Emit login enage metric only once

packages/fxa-settings/src/lib/auth-errors/en.ftl, packages/fxa-settings/src/pages/Signin/container.test.tsx, packages/fxa-settings/src/pages/Signin/container.tsx
Because:
* In the 'account disconnected' Sync state, users are now taken to /signin instead of /force_auth, so our logic needed to be updated
This commit:
* Adjusts the logic for when we send the message. Only send if the user didn't first hit content-server (we will know based on a temporary query param until email-first is converted to React). The browser decides when to automatically respond with ok: true or prompt the user
* Displays an error message when the user cancels
closes FXA-10176
=> fix(sync): Adjust conditions for sending can_link_account on signin

packages/fxa-content-server/app/scripts/lib/glean/index.ts, packages/fxa-content-server/app/tests/spec/lib/glean.js, packages/fxa-settings/src/components/App/index.test.tsx, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/lib/glean/index.test.ts, packages/fxa-settings/src/lib/glean/index.ts
- We want to track these events in Glean
- Adds `pageLoad` events
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9723
To test, enable Glean and start navigating through pages.
=> feat(metrics): Add Glean page load events when navigating

packages/fxa-content-server/grunttasks/build.js, packages/fxa-content-server/grunttasks/copy.js, packages/fxa-content-server/webpack.config.js
- Source maps weren't showing up on stage, yet were being deployed.
- The files in `fxa-settings/build` were effectively being webpacked twice.
- The ending comment, `//# sourceMapURL=` was being stripped off when webpacked the second time.
- Just copies over the files from `settings/build` without sending them through webpack.
Closes: FXA-9972
This will not close the related issue, FXA-9225, but does help a bit. I also tried fixing FXA-9225, but the additional web pack plugin sentry adds didn't work out of the box.
=> bug(content): Fix broken source maps

packages/fxa-settings/src/components/Settings/PageDeleteAccount/en.ftl, packages/fxa-settings/src/components/Settings/PageDeleteAccount/index.tsx
- Users think they are removed from marketing emails when they delete their account
- Adds a notice for the user that these emails are not unsubscribed and they have to do another step. `To stop receiving marketing emails from Mozilla Corporation and Mozilla Foundation, you must [request deletion of your marketing data](https://privacyportal.onetrust.com/webform/1350748f-7139-405c-8188-22740b3b5587/4ba08202-2ede-4934-a89e-f0b0870f95f0).`
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10187
=> feat(delete): Add notice marketing email notice on delete account page

packages/fxa-auth-server/lib/oauth/keys.ts
Because:
* The key comparison was requiring the old key to exist.
This commit:
* Handles the case where the old key is missing.
=> fix(auth): handle missing key comparison in genkeys

packages/fxa-event-broker/src/client-webhooks/client-webhooks.service.spec.ts, packages/fxa-event-broker/src/client-webhooks/client-webhooks.service.ts, packages/fxa-event-broker/src/pubsub-proxy/pubsub-proxy.controller.spec.ts, packages/fxa-event-broker/src/pubsub-proxy/pubsub-proxy.controller.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.spec.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.ts, packages/fxa-event-broker/src/queueworker/sqs.dto.ts
Because:
* We don't want to block the SQS queue or fill the PubSub backlog with messages if the client id has no webhookUrl configured.
This commit:
* Adds a check to the client-webhooks service to drop messages for client ids with no webhookUrl configured.
Closes FXA-10216
=> fix: drop messages for client ids with no webhook

packages/fxa-dev-launcher/profile.mjs
* FxA environment prefs were reset in `dev-launcher` on sign out from sync
* This caused sync to revert to FxA prod values (instead of local or stage as defined on startup with `fxa-dev-launcher`)
* Add `identity.fxaccounts.autoconfig.uri` to the `fxa-dev-launcher` startup profile
Closes: #FXA-10195
This change only affects the dev-launcher.
=> fix(fxa-dev-launcher): Prevent fxa browser prefs from getting reset on sync signout

packages/fxa-admin-server/src/gql/account/account.resolver.spec.ts, packages/fxa-admin-server/src/gql/account/account.resolver.ts, packages/fxa-auth-server/docs/swagger/account-api.ts, packages/fxa-auth-server/lib/profile/updates.js, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/lib/routes/sign.js, packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/lib/routes/totp.js, packages/fxa-auth-server/test/local/profile/updates.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js, packages/fxa-auth-server/test/local/routes/totp.js, packages/fxa-event-broker/README.md, packages/fxa-graphql-api/src/gql/account.resolver.spec.ts, packages/fxa-graphql-api/src/gql/account.resolver.ts, packages/fxa-graphql-api/src/scripts/must-change-password.ts, packages/fxa-profile-server/lib/routes/_core_profile.js, packages/fxa-profile-server/lib/routes/profile.js, packages/fxa-shared/db/models/auth/account.ts
- We want to simplify the profile change event
- Makes it such that profile events only transmit the uid in the event payload
- Adds `accountDisabledAt` and `accountLockedAt` to the /v1/profile endpoint.
Closes: FXA-10154
=> task(event-broker): Update profile-change event payload

packages/fxa-settings/src/components/ChooseNewsletters/en.ftl, packages/fxa-settings/src/components/ChooseNewsletters/newsletters.ts, packages/fxa-settings/src/pages/Signup/index.test.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
Because:
* We want updated copy and a new slug
This commit:
* Adjusts the copy and updates the 'security-privacy-news' slug to 'mozilla-and-you'
* Moves the MoFo checkbox to be the second checkbox
* Adjusts Glean marketing event
closes FXA-10027
---
A few notes:
* This new slug is already available in auth-server validators.
* I'm currently awaiting confirmation on if we want to remove the `mozilla-accounts` slug. I left it for now and just replaced `security-privacy-news` with `mozilla-and-you`
* On the SubPlat side, it looks like we pull what slug to display [from the Stripe metadata](https://github.com/mozilla/fxa/blob/175bf0e64fa08561ffc86a5a5053749d234e0556/packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx#L91-L92), and the new requested copy already exists as …
=> feat(newsletters): Update first checkbox slug and copy

packages/fxa-payments-server/src/lib/newsletter.test.ts, packages/fxa-payments-server/src/lib/newsletter.ts, packages/fxa-shared/subscriptions/validation.ts
Because:
* We want the default case for the switch statement handling newsletters to be shown across products, and a newsletter slug update was requested for this
This commit:
* Updates the default newsletter slug in SubPlat and updates test
fixes the SubPlat side of FXA-10027, minus the Stripe dashboard label update
=> feat(newsletters): Update default newsletter slug for SubPlat

packages/fxa-settings/src/components/Settings/index.tsx
* If multiple accounts were signed in on different tabs, operations could be applied to the wrong account
* Current account uid was not correctly updating to reflect the account in use in the focused tab
* On tab focus, check if the account uid matches the current account uid. If not, update current account uid.
* Only check for destroyed session after updating the current account uid to ensure the correct session is signed out on tab focus.
Closes: #FXA-9984
Steps to reproduce:
1. Sign in to two accounts in different tabs. (do not sign out of either)
2. Add a secondary email to each account.
3. Sign out of each account and sign back in.
Expected result (with this …
=> fix(settings): Handle multiple signins to settings

packages/fxa-content-server/server/lib/configuration.js
- Thunderbird for Android is using different redirect URIs from Thunderbird (desktop)
- adds those redirect URIs to the allow list of the `https://identity.thunderbird.net/apps/sync` scope
See also: https://github.com/thunderbird/thunderbird-android/issues/8031
=> Add redirect URIs for Thunderbird sync scope

packages/fxa-payments-server/src/lib/newsletter.test.ts, packages/fxa-payments-server/src/lib/newsletter.ts, packages/fxa-shared/subscriptions/validation.ts
Because:
* We want to support both default newsletters
This commit:
* Adds back previously removed 'mozilla-accounts' slug
---
Note, haven't tested this locally yet.
=> feat(newsletters): Add back mozilla-accounts slug to SubPlat default

libs/shared/sentry/src/lib/nest/sentry.interceptor.ts, libs/shared/sentry/src/lib/nest/sentry.plugin.ts, libs/shared/sentry/src/lib/reporting.spec.ts, libs/shared/sentry/src/lib/reporting.ts
- We were seeing lots of 'Incorrect Email Case' exceptions showing up in Sentry.
- Suppress known auth server errors
Closes: FXA-100249
Note, this logic is also in place in `sentry.interceptor.ts`. After some manual testing in fxa-graphql-api  it appears that it is needed in both places, since the errors can be reported from either place.
=> bug(graphql-api): Prevent known auth-server errors from percolating.
