mozilla/fxa

- packages/functional-tests/lib/ci-reporter.ts
- packages/functional-tests/lib/targets/firefoxUserPrefs.ts
- packages/functional-tests/lib/targets/index.ts
- packages/functional-tests/lib/targets/production.ts
- packages/functional-tests/lib/targets/remote.ts
- packages/functional-tests/lib/targets/stage.ts
- packages/functional-tests/pages/fourOhFour.ts
- packages/functional-tests/pages/index.ts
- packages/functional-tests/pages/legal.ts
- packages/functional-tests/pages/privacy.ts
- packages/functional-tests/pages/resetPassword.ts
- packages/functional-tests/pages/settings/avatar.ts
- packages/functional-tests/pages/settings/changePassword.ts
- packages/functional-tests/pages/settings/components/dataTrio.ts
- packages/functional-tests/pages/settings/components/unitRow.ts
- packages/functional-tests/pages/settings/deleteAccount.ts
- packages/functional-tests/pages/settings/displayName.ts
- packages/functional-tests/pages/settings/layout.ts
- packages/functional-tests/pages/settings/secondaryEmail.ts
- packages/functional-tests/pages/settings/totp.ts
- packages/functional-tests/pages/signup.ts
- packages/functional-tests/pages/termsOfService.ts
- packages/functional-tests/playwright.config.ts
- packages/functional-tests/tests/subscription-tests/subscriptionFixtures.ts
- There were nits in other reviews about missing headers. 
- It'd be nice if headers were just added in
- Adds missing headers in functional tests, where it seems they were often omitted.
The following command is not perfect but does a pretty good job at finding files that don't have headers. `find . -name '*ts' -exec awk 'NR==1&&/^import.*/{print FILENAME}' {} \;`
> task(functional-tests): Add missing licenses

- packages/fxa-auth-server/lib/metrics/context.js
- packages/fxa-auth-server/package.json
- yarn.lock
Because:
* buffer-equal-constant-time is no longer supported and is used in a single place
This commit:
* Replaces it with crypto.timingSafeEqual()
Fixes FXA-10266
> refactor(metrics): replace outdated package

- packages/fxa-event-broker/src/client-webhooks/client-webhooks.service.spec.ts
- packages/fxa-event-broker/src/client-webhooks/client-webhooks.service.ts
Because:
* The previous check was checking the wrong object, and not finding the webhook url as it should for delivery.
This commit:
* Fixes the check to use the correct object, and now finds the webhook url as it should for delivery.
> fix(event-broker): use proper check for webhook urls

- libs/payments/paypal/src/index.ts
- libs/payments/paypal/src/lib/checkoutToken.manager.spec.ts
- libs/payments/paypal/src/lib/checkoutToken.manager.ts
- libs/payments/paypal/src/lib/paypal.manager.spec.ts
- libs/payments/paypal/src/lib/paypal.manager.ts
- libs/payments/ui/src/lib/nestapp/app.module.ts
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- We want to have managers separated by responsibility rather than their implementation/service.
- Moves getCheckoutToken to a CheckoutTokenManager.
Closes: FXA-10184
> chore(payments-paypal): move getCheckoutToken to CheckoutTokenManager

- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/paypal/src/lib/paypal.manager.spec.ts
- libs/payments/paypal/src/lib/paypal.manager.ts
- libs/payments/stripe/src/lib/invoice.manager.spec.ts
- libs/payments/stripe/src/lib/invoice.manager.ts
> refactor(payments): Move processNonZeroInvoice, processZeroInvoice, and processInvoice to InvoiceManager

- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/paypal/src/lib/paypal.manager.spec.ts
- libs/payments/paypal/src/lib/paypal.manager.ts
- libs/payments/stripe/src/lib/subscription.manager.spec.ts
- libs/payments/stripe/src/lib/subscription.manager.ts
- Move getCustomerPayPalSubscriptions from PaypalManager to SubscriptionManager to match our responsibility-driven structure.
Closes: FXA-10181
> refactor(payments): Move getCustomerPayPalSubscriptions to SubscriptionManager

- libs/payments/paypal/src/lib/paypal.manager.spec.ts
- libs/payments/paypal/src/lib/paypal.manager.ts
- libs/payments/paypal/src/lib/util/getPayPalAmountStringFromAmountInCents.spec.ts
- libs/payments/paypal/src/lib/util/getPayPalAmountStringFromAmountInCents.ts
- Moves getPayPalAmountStringFromAmountInCents from PaypalManager to a util folder with the name getPayPalAmountStringFromAmountInCents.ts.
Closes: FXA-10183
> refactor(payments-paypal): Move getPayPalAmountStringFromAmountInCents to a util

- .circleci/config.yml
- We want nightly to build and test everything
- Removes the 'affected' command from nx operations for lint, compile, and unit-test commands
Closes: FXA-10278
> bug(ci): Nightly should run all lints, builds, and unit tests not just affected ones

- packages/functional-tests/lib/channels.ts
- packages/functional-tests/pages/layout.ts
- packages/functional-tests/tests/misc/authClientV2.spec.ts
- packages/functional-tests/tests/oauth/webchannel.spec.ts
- packages/functional-tests/tests/react-conversion/oauthSignup.spec.ts
- packages/functional-tests/tests/react-conversion/signup.spec.ts
- packages/functional-tests/tests/syncV3/fxDesktopHandshake.spec.ts
- packages/functional-tests/tests/syncV3/fxDesktopHandshakeNonSync.spec.ts
- packages/functional-tests/tests/syncV3/fxDesktopV3ForceAuth.spec.ts
- packages/functional-tests/tests/syncV3/settings.spec.ts
- packages/functional-tests/tests/syncV3/signUpWithCWTS.spec.ts
- packages/fxa-settings/src/lib/channels/firefox.ts
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.test.tsx
- packages/fxa-settings/src/pages/Signin/index.test.tsx
- packages/fxa-settings/src/pages/Signup/container.tsx
- packages/fxa-settings/src/pages/Signup/index.test.tsx
- packages/fxa-settings/src/pages/WebChannelExample/index.tsx
- We noticed that some of the usage for webchannels was inconsistent.
- Of the web channel messages we send only FxAStatus and LinkAccount actually return responses.
- Removes implied response from the fxaLogin command that wasn't actually sent by firefox.
- Updates the functional tests to better reflect the actual commands and responses sent by firefox by creating some types. This should avoid mistakes
Closes: FXA-9874
Note this based on the [functional-tests-support-typescript-compilation](https://app.circleci.com/pipelines/github/mozilla/fxa?branch=functional-tests-support-typescript-compilation) branch. To have reliable type checking, this became a prerequisite.
> task(settings,functional-tests): Review use of webchannel messages

- packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.tsx
- packages/fxa-settings/src/lib/glean/index.ts
- packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml
- packages/fxa-shared/metrics/glean/web/accountPref.ts
- packages/fxa-shared/metrics/glean/web/index.ts
- We want to know when a user clicks the 'Can't scan code?' button.
- Adds a glean telemetry metric for this button click.
Closes: FXA-9577
> feat(metrics): Add '2FA Can't Scan Code Link' frontend event

- packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.tsx
- packages/fxa-settings/src/lib/glean/index.ts
- packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml
- packages/fxa-shared/metrics/glean/web/accountPref.ts
- packages/fxa-shared/metrics/glean/web/index.ts
- We want to know when a user submits step 1 of the 2FA flow.
- Depends on https://github.com/mozilla/fxa/pull/17298.
- We add telemetry to know the button is clicked.
Closes: FXA-9573
> feat(metrics): Add '2FA QR Code Setup View' frontend Glean event

- packages/fxa-settings/README.md
- packages/fxa-settings/src/components/CardHeader/index.tsx
- packages/fxa-settings/src/pages/Signin/index.test.tsx
Because:
* In production the SVG is not rendering properly
This commit:
* Sends a network request for the image instead of inlining the SVG
---
Storybook on this branch:
> fix(pocket): Do not inline Pocket SVG due to text logo rendering issue

- packages/fxa-settings/src/components/Settings/BentoMenu/index.tsx
- packages/fxa-settings/src/components/Settings/ProductPromo/index.test.tsx
- packages/fxa-settings/src/components/Settings/ProductPromo/index.tsx
- packages/fxa-settings/src/constants/index.tsx
* We want to distinguish between monitor free and monitor plus
* We want to link out to monitor stage from accounts stage
* Switch the UTM content param in the promo link
* Select the appropriate monitor link if host is stage
Closes: #FXA-10213
> feat(settings): Update UTM params for monitor plus promo

- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- libs/payments/ui/src/lib/nestapp/validators/RecordGleanEvent.ts
- To simplify the Glean implementation payments-next will only make use of Glean server side events. In cases were client events are required, a server action will be called to record the glean event.
- Adds a generic server action that can be used client side to record any glean event.
Closes: #FXA-9999
> feat(next): Add generic server action for glean

- libs/payments/stripe/src/lib/paymentMethod.manager.spec.ts
- libs/payments/stripe/src/lib/paymentMethod.manager.ts
- libs/payments/stripe/src/lib/stripe.client.spec.ts
- creates PaymentMethodManager
Closes: FXA-10179
> feat(payments-stripe): Create PaymentMethod manager

- .circleci/config.yml
- Compile job was failing in nightly
- Lint job was failing in nightly
- Add 'run-many' option, which is required when affected isn't present.
> bug(ci): Fix compile and lint jobs for nightly

- .circleci/config.yml
- packages/fxa-auth-server/test/remote/recovery_key_tests.js
- The Integration Test - Servers - Auth V2  job was not producing artifacts
- Corrects a typo in the target name
- Fixes bug where this.skip() cannot be used with fat arrow functions.
> fix target name and temporarily run-many

- packages/functional-tests/tests/key-stretching-v2/recoveryKey.spec.ts
- packages/functional-tests/tests/key-stretching-v2/recoveryKeyWithLink.spec.ts
- packages/functional-tests/tests/key-stretching-v2/resetPassword.spec.ts
- packages/functional-tests/tests/key-stretching-v2/resetPasswordWithLink.spec.ts
- There were some key stretching tests that at one point in time were flaky
- Re-enables these tests
Closes: FXA-9734, FXA-9742, FXA-9765
> Fix key stretch tests

- packages/fxa-shared/test/oauth/scopes.js
- An invalid token in the JUnit XML report for fxa_shared I believe is causing test result ingestion to fail in CI, resulting in 200-300 test statuses not being reported.
- this error is on line 786 of a test xml file that has 1493 lines, all the tests before it are included in CircleCI reporting and all the tests after are not, so i think it's reading sequentially and giving up when it encounters the invalid token
- makes the invalid token print safe for reporting
Closes: # FXA-10279
> fix(fxa-shared): failure to injest all unit test results in CI

- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/paypal/src/index.ts
- libs/payments/paypal/src/lib/paypal.error.ts
- libs/payments/paypal/src/lib/paypalBillingAgreement.manager.ts
- libs/payments/paypal/src/lib/paypalBillingAgreement.spec.ts
- libs/payments/ui/src/lib/nestapp/app.module.ts
> refactor(payments-paypal): Create PaypalBillingAgreementManager

- packages/fxa-settings/src/components/Settings/BentoMenu/index.test.tsx
- packages/fxa-settings/src/components/Settings/BentoMenu/index.tsx
- packages/fxa-settings/src/lib/glean/index.test.ts
- packages/fxa-settings/src/lib/glean/index.ts
- packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml
- packages/fxa-shared/metrics/glean/web/accountPref.ts
- packages/fxa-shared/metrics/glean/web/index.ts
- We want to track views of the bento menu and clicks on suggested product links
- Add new Glean events and implement in fxa-settings, add unit tests
Closes: #FXA-10219
> feat(glean): Add Glean events for BentoMenu

- packages/fxa-settings/src/components/Settings/ProductPromo/index.stories.tsx
- packages/fxa-settings/src/components/Settings/ProductPromo/index.test.tsx
- packages/fxa-settings/src/components/Settings/ProductPromo/index.tsx
Because:
* Monitor Plus is not available for non-US customers and there are UX questions
This commit:
* Hides the MonitorPlus promo temporarily
closes FXA-10289
---
There's a lot of ways we could have sliced this one. I'd love to make this more configurable for other products but we can do that when we get there. I didn't want to just remove the code either, that would have been fine but we've got a meeting scheduled to discuss what to do with Plus, and it's nice keeping the tests and storybook states to show what it'll look like.
> fix(promo): Disable MonitorPlus piece of ProductPromo

- apps/payments/next/project.json
- libs/shared/metrics/glean/.eslintrc.json
- libs/shared/metrics/glean/.swcrc
- libs/shared/metrics/glean/README.md
- libs/shared/metrics/glean/jest.config.ts
- libs/shared/metrics/glean/package.json
- libs/shared/metrics/glean/project.json
- libs/shared/metrics/glean/src/index.ts
- libs/shared/metrics/glean/src/registry/subplat-backend-metrics.yaml
- libs/shared/metrics/glean/tsconfig.json
- libs/shared/metrics/glean/tsconfig.lib.json
- libs/shared/metrics/glean/tsconfig.spec.json
- package.json
- tsconfig.base.json
- yarn.lock
- Have project target to generate glean code.
- Adds glean metrics library.
- Adds blank subplat-backend-metrics.yaml
- Add glean-generate target to project.
Closes: #FXA-9996
> feat(next): add glean-generate script

- libs/payments/eligibility/src/lib/eligibility.manager.spec.ts
- libs/payments/eligibility/src/lib/eligibility.service.spec.ts
- libs/payments/legacy/src/lib/stripe-mapper.service.spec.ts
- libs/shared/cms/src/lib/queries/eligibility-content-by-offering/factories.ts
- libs/shared/cms/src/lib/queries/eligibility-content-by-plan-ids/factories.ts
- libs/shared/cms/src/lib/strapi.client.spec.ts
- Several of our tests were not using the NestJS DI helper or were using the old style.
- Updates a few tests to the new style.
Closes FXA-10174
> chore(libs): update tests to use NestJS DI helper

- _dev/docker/mono/Dockerfile
- Glean glinter needs python3-venv.
- Adds python3-venv to circleci mono image used during fxa image create
> fix(ci): add python3-venv to mono image

- packages/fxa-settings/src/components/Settings/SignoutSync/index.stories.tsx
- There was a typo
- Fixes typo
> bug(settings): Fix storybook typo for SignoutSync

- packages/123done/package.json
- packages/123done/server.js
- yarn.lock
Because:
* We don't want to use an obsolete library and this test usage is not security sensitive.
This commit:
* Uses cookie-session instead, as this cookie is not security sensitive.
> feat: remove encrypted cookie sessions from 123done

- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/stripe/src/lib/stripe.types.ts
- sets billing agreement ID on customer metadata within the checkout service in the payWithPaypal method after the billing agreement is created
Closes: FXA-10162
> refactor(payments): Set billing agreement ID on customer metadata

- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/stripe/src/lib/stripe.client.spec.ts
- libs/payments/stripe/src/lib/stripe.client.ts
- libs/payments/stripe/src/lib/subscription.manager.spec.ts
- libs/payments/stripe/src/lib/subscription.manager.ts
- updates both method calls for `subscriptionManager.create` by setting cartId as the idempotency key to prevent duplicate subscription creation with a given cart
Closes: FXA-10161
> refactor(payments): Update CheckoutService to use cartId as idempotency key

- libs/payments/stripe/src/lib/price.manager.ts
- libs/payments/stripe/src/lib/product.manager.ts
- libs/payments/stripe/src/lib/stripe.error.ts
- several instances incorrectly nullish checks the return value from a stripe call, where the type signature indicates the underlying method cannot return a nullish value.
- cleans up following instances, along with the associated errors:
- `retrieve` in `PriceManager`
- `retrieve` in `ProductManager`
Closes: FXA-9620
> fix(payments-stripe): Cleanup instances that incorrectly expect nullish values returned from client

- package.json
- yarn.lock
- We use 5.0.2 in fxa-settings, the version mismatch was causing two different Gleans to be initalized
- Updates all Glean to use 5.0.2
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10310
Verified locally the error does not show up
```
(Glean.core.Pings.Maker) {
"metrics": {
"string": {
"event.name": "reg_view",
"account.user_id_sha256": "",
"relying_party.oauth_client_id": "",
"relying_party.service": "sync",
"session.device_type": "desktop",
"session.entrypoint": "preferences",
"session.flow_id": "4ee696408490a771af4ca607d6672bce945e360dc047668349c8404c552e6321",
"utm.campaign": "",
"utm.content": "",
"utm.medium": "",
"utm.source": "",
"utm.term": "",
"entrypoint.variation": "", …
```
> fix(glean): Downgrade glean to 5.0.2 instead of 5.0.3

- packages/fxa-auth-server/test/local/routes/cloud-scheduler.js
- These tests were flaky
- Mocks `Date.now()` so it won't be flaky
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10140
> fix(tests): Mock `Date.now()` in cloud scheduler tests

- packages/fxa-content-server/app/tests/spec/lib/glean.js
- packages/fxa-content-server/server/lib/configuration.js
- packages/fxa-settings/src/lib/config.ts
- packages/fxa-settings/src/lib/glean/index.test.ts
Because:
* This must be enabled for automatic Glean click events and is already set to true for stage and prod
This commit:
* Updates the default config option from false to true for dev env
---
Context is [here](https://github.com/mozilla/fxa/pull/17446#discussion_r1727700988) + a recent Slack thread.
> chore(config): Set default Glean uploadEnabled option to true

- packages/fxa-settings/src/components/Settings/Page2faReplaceRecoveryCodes/index.tsx
- packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetup/index.tsx
Because:
* We are adding glean click events
This commit:
* Adds the click event for inline setup, normal setup, and replace recovery codes, after users submit the recovery code to confirm and finish the flow
closes FXA-10127
> feat(glean): Add click event for 2fa backup code submit

- packages/fxa-settings/src/components/Settings/DataCollection/en.ftl
- packages/fxa-settings/src/components/Settings/DataCollection/index.test.tsx
- packages/fxa-settings/src/components/Settings/DataCollection/index.tsx
- packages/fxa-settings/src/components/Settings/Profile/index.tsx
- packages/fxa-settings/src/components/Settings/Security/index.tsx
- packages/fxa-settings/src/components/Settings/UnitRow/index.stories.tsx
- packages/fxa-settings/src/components/Settings/UnitRow/index.test.tsx
- packages/fxa-settings/src/components/Settings/UnitRow/index.tsx
- packages/fxa-settings/src/components/Settings/UnitRow/mocks.tsx
- packages/fxa-settings/src/components/Settings/UnitRowSecondaryEmail/index.tsx
- packages/fxa-settings/src/components/Settings/UnitRowTwoStepAuth/index.tsx
Because:
* We want to add a new 'Firefox browser' row to our Data Collection and Use section
This commit:
* Refactors DataCollection to use our standard UnitRow component per the new content design
* Adjusts UnitRow for new hideHeaderValue prop, doesn't render action div if action wasn't provided, renames noHeaderValueText to defaultHeaderValueText for clarity
* Tweaks related stories and tests
closes FXA-10297
--
Now that `DataCollection` is using `UnitRow`, it means the "action" (the switch) is dropped to a new line in mobile. I've sent screenshots of this to Eduardo and he gave the thumbs up.
> feat(settings): Refactor 'Data Collection' for new content + UnitRow adjustments

- packages/fxa-settings/src/components/Settings/Page2faReplaceRecoveryCodes/index.tsx
- packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetup/index.tsx
Because:
* We want click events for "Cancel" and "Continue" buttons after the backup codes are shown
This commit:
* Adds the events for normal setup, inline setup, and replace
closes FXA-9583, closes FXA-9584
> feat(glean): Add click events for 2FA 'cancel' and 'continue' on inline/setup/replace

- packages/fxa-react/components/LinkExternal/index.tsx
- packages/fxa-settings/src/components/GetDataTrio/index.tsx
- packages/fxa-settings/src/components/Settings/Page2faReplaceRecoveryCodes/index.tsx
- packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.tsx
- packages/fxa-settings/src/lib/types.ts
- packages/fxa-settings/src/pages/InlineRecoverySetup/index.tsx
- packages/fxa-settings/src/pages/InlineTotpSetup/index.tsx
Because:
* We want metrics for when a user clicks on this link
* Simplifies glean data attrs in DataBlock because the type is string or undefined, and if this is undefined the attribute does not render
This commit:
* Adds the glean attrs on LinkExternal
* Shares 2fa glean data 'type's for consistency
closes FXA-9578
> feat(glean): Add 2FA 'these authentication apps' link click event, adjust DataBlock data attrs

- libs/payments/cart/src/lib/cart.error.ts
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/stripe/src/lib/promotionCode.manager.spec.ts
- libs/payments/stripe/src/lib/promotionCode.manager.ts
- libs/payments/stripe/src/lib/stripe.util.spec.ts
- libs/payments/stripe/src/lib/stripe.util.ts
- libs/shared/cms/src/lib/product-configuration.manager.spec.ts
- libs/shared/cms/src/lib/product-configuration.manager.ts
- We don't want carts to be able to proceed with actions with invalid coupon codes
- Adds validation so that an invalid coupon code doesn't result in the customer getting invisibly charged more than they saw in the checkout ui.
Closes FXA-10173
> feat(cart): validate promo code prior to cart actions

- libs/shared/cms/src/lib/product-configuration.manager.spec.ts
- libs/shared/cms/src/lib/strapi.client.spec.ts
- libs/shared/cms/src/lib/strapi.client.ts
- The caching decorator was disabled in a previous PR (pre-Strapi) due to some issues. I was unable to replicate these issues in the latest Strapi client.
- Re-enables the caching decorator.
Closes FXA-10175
> fix(shared-cms): re-enable caching decorator

- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/stripe/src/lib/promotionCode.manager.spec.ts
- libs/payments/stripe/src/lib/stripe.types.ts
- libs/payments/stripe/src/lib/util/assertPromotionCodeApplicableToPrice.spec.ts
- libs/payments/stripe/src/lib/util/assertPromotionCodeApplicableToPrice.ts
- libs/payments/stripe/src/lib/util/isCustomerTaxEligible.spec.ts
- libs/payments/stripe/src/lib/util/isCustomerTaxEligible.ts
Closes: FXA-10159
Closes: FXA-10160
> feat(payments-cart): Add tax ID to customer and set appliedPromotionCode metadata in CheckoutService postPaySteps

- packages/fxa-settings/src/pages/Signin/index.tsx
* There was no spacing between Use a different account and Forgot password? links on mobile sign in page
* Tweak styling to show links on separate lines for mobile
Closes: #FXA-10305
Before:
After:
> fix(settings): Styling tweak to add spacing between links on mobile

- packages/fxa-settings/package.json
- yarn.lock
* Glean metrics were not emitted for settings with a console error
* Remove glean from fxa-settings dependencies as follow-up to PR-17470
> fix(glean): Glean metrics were erroring for settings

- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- We were previously always updating the cart
- Eliminates the unnecessary cart update call
Closes FXA-10167
> feat(payments-cart): do not update cart when not needed

- packages/fxa-settings/src/components/Settings/ProductPromo/index.test.tsx
- packages/fxa-settings/src/components/Settings/ProductPromo/index.tsx
Because:
* We use this component in multiple places (sidebar and setitngs), and it fired a view event for each instance
* We want a glean click event for comparison on a custom event
fixes FXA-10317
---
This is the quick fix mentioned [in this comment](https://github.com/mozilla/fxa/pull/17486). We will follow up with Ross / whoever else to see if we want that intersection observer approach instead, which could also give us insight on if users are scrolling all the way down to see this in mobile.
To see this fixed, comment out `<React.StrictMode>` in `src/index.tsx` and search the Glean pings for `account_pref_promo_monitor_view` after hitting Settings. Before this patch it'd fire 2x and with this patch I'm seeing 1x.
> fix(glean): Fix ProductPromo firing extra view event, add glean click event

- libs/payments/stripe/src/lib/subscription.manager.spec.ts
- libs/payments/stripe/src/lib/subscription.manager.ts
- revises `SubscriptionManager.update()` to set metadata only if keys are included in `STRIPE_CUSTOMER_METADATA`
> fix(payments-stripe): Revises SubscriptionManager.update()

- .github/workflows/docker.yml
- This job did not successfully detect the `git_tag` input when called as a `workflow_call` event: https://github.com/mozilla/fxa/actions/runs/10600680735/job/29378760414
- This changes the input validation from `github.event.inputs.git_tag` to `inputs.git_tag`. The latter appears to pick up inputs from `workflow_call`, `workflow_dispatch` triggers: https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#inputs-context
Closes: N/A (issue number)
> fix(docker): using inputs.<input> for workflow input validation

- packages/fxa-settings/src/pages/Index/en.ftl
- packages/fxa-settings/src/pages/Index/index.stories.tsx
- packages/fxa-settings/src/pages/Index/index.test.tsx
- packages/fxa-settings/src/pages/Index/index.tsx
- packages/fxa-settings/src/pages/Index/interfaces.ts
- packages/fxa-settings/src/pages/Index/mocks.tsx
Because:
* We are converting our flows from Backbone to React
This commit:
* Creates the initial component buildout and displays states in Storybook
closes FXA-8635
---
I'm open to a few different naming conventions here:
* `pages/Index/index.tsx` feels OK and what I went with here but I really don't love `Index/index.tsx` 
* `pages/EmailFirst/index.tsx` I don't like that it's descriptive of what the page _currently_ is since if we change it we'll want to change the name as well but 🤷‍♀️ 
* `pages/index.tsx` this is fine, but then we'd have `pages/index.stories.tsx` etc. in the pages directory and we already have a pages-shared `pages/mocks.tsx` file that we'd probably want to move
> feat(react): Build out Index / email-first component

- packages/fxa-graphql-api/src/backend/legal.service.spec.ts
- packages/fxa-graphql-api/src/backend/legal.service.ts
- packages/fxa-graphql-api/src/config.ts
- Legal docs weren't loading after switching to the CDN
- Adjust the path where legal docs reside
*Imortant!* This will also need web-infra change.
> bug(graphql): Fix url for legal docs being fetched by graphql

- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/docs/swagger/session-api.ts
- packages/fxa-auth-server/lib/routes/session.js
- packages/fxa-auth-server/test/local/routes/session.js
- I demo this at all hands and it required some backend updates 
- Adds a few tweaks and changes to api
- Only sends 2FA push notification to desktop devices if they support it
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10320
I would like to land this since it updates are already existing 2FA push functionality.
> feat(auth): Update 2FA via push backend api

- packages/fxa-content-server/server/lib/beta-settings.js
- packages/fxa-content-server/server/lib/configuration.js
- packages/fxa-settings/src/index.tsx
- packages/fxa-settings/src/lib/config.ts
- With the CDN changes, l10n was broken
- We want to reference .ftl on the cdn
- Adds config so we can target the location of the l10n files
*Important!* There are accompanying web-infra changes required for these changes.
> task(content,settings): Reference l10n files on CDN

- apps/payments/next/.env.development
- apps/payments/next/.env.production
- apps/payments/next/app/[locale]/layout.tsx
- apps/payments/next/config/index.ts
- apps/payments/next/middleware.ts
- libs/payments/ui/src/lib/client/components/CheckoutForm/index.tsx
- libs/payments/ui/src/lib/client/providers/ConfigProvider.tsx
- libs/payments/ui/src/lib/client/providers/Providers.tsx
- package.json
- yarn.lock
- Initialize PayPal SDK and add button to checkout page
- Adds PayPal SDK and initializes provider
- Adds PayPal button and only display when PayPal is selected in Payment Element
- Updates CSP for PayPal URLs
- Adds config options
Closes: #FXA-7585
When PayPal is selected
When Card is selected
> feat(next): add paypal sdk

- packages/fxa-admin-server/src/backend/backend.module.ts
- packages/fxa-admin-server/src/backend/profile-client.service.spec.ts
- packages/fxa-admin-server/src/backend/profile-client.service.ts
- packages/fxa-admin-server/src/config/development.json
- packages/fxa-admin-server/src/config/index.ts
- packages/fxa-admin-server/src/gql/account/account.resolver.spec.ts
- packages/fxa-admin-server/src/gql/account/account.resolver.ts
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/index.js
- packages/fxa-auth-server/lib/routes/sign.js
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- packages/fxa-auth-server/test/local/routes/totp.js
- packages/fxa-graphql-api/pm2.config.js
- packages/fxa-graphql-api/src/backend/profile-client.service.ts
- packages/fxa-graphql-api/src/config.ts
- packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
- packages/fxa-graphql-api/src/gql/account.resolver.ts
- It's possible a race condition can occur where the cache isn't cleared in time.
- Note that this can happen because events can be delivered to RPs in any order.
- Note that the profile server attempts to clear the cache [here](https://github.com/mozilla/fxa/blob/6bb9b093fb926d4b7d37b446d20cc7c66cdfb633/packages/fxa-profile-server/lib/events.js#L62).
- Manually clears the profile server cache prior to sending out the profile data change event.
- Adds supporting nest services.
Closes: FXA-10262
*Important !* We must also update the ENVs configs with bearer token value needed to clear the profile server cache. This change should be noted in deploy docs, and PRs be made on web infra.
> task(auth,graphql,profile,admin): Make sure profile cache is cleared before sending profile update event.

- packages/fxa-settings/src/components/App/index.test.tsx
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/lib/config.ts
- packages/fxa-settings/src/lib/glean/index.test.ts
- packages/fxa-settings/src/lib/glean/index.ts
- packages/fxa-shared/metrics/glean/web/index.ts
Because:
- Glean in Settings was initialized with the default "development" value
This commit:
- uses the actual configuration value for the app channel
You can verify this locally by setting `GLEAN_APP_CHANNEL` to something other than "development".
> fix(Glean): use the configured app channel for Glean in Settings

- .circleci/config.yml
- _dev/docker/ci/Dockerfile
- To be able achieve Browser compatibility and run tests in multiple browsers we have to update the CI runner image with the new browsers installed.
- Updates the CI runner image with Firefox, Chromium and webkit installed.
Closes: FXA-10306
> chore(functional_tests): update CI image to add different browsers

- packages/fxa-content-server/server/config/local.json-dist
- packages/fxa-content-server/server/lib/beta-settings.js
- packages/fxa-content-server/server/lib/configuration.js
- packages/fxa-settings/src/lib/config.ts
- This needs a feature flag
- Adds the feature flag
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10077
> feat(sync): Add initial feature flag for setting up recovery code after Sync sign-in

- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/test/local/routes/account.js
- Some code was still referencing the auth-server profile client
- Update code to reference the profile client library
Closes: #FXA-10389
> fix(auth): missing profile client references

- packages/fxa-settings/src/pages/Signin/SigninPushCode/en.ftl
- A string landed with a hard coded brand term for Firefox
- Replaces the hardcoded string with the correct brand term
> chore(l10n): Replace hardcoded Firefox with brand term

- .gitignore
- apps/payments/next/.env.development
- apps/payments/next/.env.production
- apps/payments/next/app/global-error.tsx
- apps/payments/next/config/index.ts
- apps/payments/next/instrumentation.ts
- apps/payments/next/next.config.js
- apps/payments/next/package.json
- apps/payments/next/sentry.client.config.ts
- apps/payments/next/sentry.server.config.ts
- libs/payments/ui/src/lib/config.utils.ts
- libs/shared/sentry/src/client.ts
- libs/shared/sentry/src/index.ts
- libs/shared/sentry/src/lib/next/client.ts
- libs/shared/sentry/src/lib/next/server.ts
- libs/shared/sentry/src/lib/utils/beforeSend.client.spec.ts
- libs/shared/sentry/src/lib/utils/beforeSend.client.ts
- libs/shared/sentry/src/lib/utils/cleanUpQueryParam.spec.ts
- libs/shared/sentry/src/lib/utils/cleanUpQueryParam.ts
- libs/shared/sentry/src/lib/utils/tagFxaName.ts
- package.json
- tsconfig.base.json
- yarn.lock
- Be able to use Sentry in Next.js on both the client and the server
- Add Sentry to payments-next using the installation wizard
Closes: #FXA-9998
> feat(next): add sentry to payments-next

- packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
- packages/fxa-graphql-api/src/gql/account.resolver.ts
- packages/fxa-graphql-api/src/gql/model/account.ts
- packages/fxa-graphql-api/src/gql/model/recoveryKey.ts
- packages/fxa-settings/src/components/App/gql.ts
- packages/fxa-settings/src/components/App/index.test.tsx
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/components/Settings/FlowRecoveryKeyConfirmPwd/index.stories.tsx
- packages/fxa-settings/src/components/Settings/FlowRecoveryKeyConfirmPwd/index.test.tsx
- packages/fxa-settings/src/components/Settings/FlowRecoveryKeyConfirmPwd/index.tsx
- packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.stories.tsx
- packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.tsx
- packages/fxa-settings/src/components/Settings/PageSettings/index.stories.tsx
- packages/fxa-settings/src/components/Settings/Security/index.stories.tsx
- packages/fxa-settings/src/components/Settings/Security/index.test.tsx
- packages/fxa-settings/src/components/Settings/UnitRowRecoveryKey/index.stories.tsx
- packages/fxa-settings/src/components/Settings/UnitRowRecoveryKey/index.test.tsx
- packages/fxa-settings/src/components/Settings/UnitRowRecoveryKey/index.tsx
- packages/fxa-settings/src/lib/glean/index.test.ts
- packages/fxa-settings/src/lib/metrics.test.ts
- packages/fxa-settings/src/models/Account.ts
- packages/fxa-settings/src/models/contexts/AppContext.ts
- packages/fxa-settings/src/models/contexts/SettingsContext.ts
- We want to be able to give the user better messaging to add a recovery key (which helps when users have a Sync enabled device)
- Updates account resolver to return `{exists: boolean, estimatedSyncDeviceCount: number}`
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10006
> feat(recoveryKey): Add `estimatedSyncDeviceCount` to graphql account resolver

- .circleci/config.yml
- Currently CircleCI doesn't let jobs with `require` parameter to be executed when the previous job fails with a failed status. But we needed to find a workaround for this to be able to generate HTML reports.
- A detailed explanation of the whole workaround is added on FXA-10298
- Created a `waiter` job that will check for all the required job's status and when it's complete it executes the dependent job.
- The `waiter` job is called `check-required-jobs-complete` and the dependent job is `playwright-functional-test-report`
Closes: FXA-10298
There are a few pieces left that will be covered in separate tickets:
- Currently after a test fails, and when re-run from …
> chore(functional_test): update config to run merge reports even when tests fail

- packages/fxa-content-server/app/scripts/lib/channels/senders/web-channel.js
- packages/fxa-content-server/app/scripts/lib/user-agent.js
- packages/fxa-content-server/app/tests/spec/lib/user-agent.js
Originally this was opened to run CI for #17518.  But due to time zone differences, FxA fixed the issue that was causing the test failures here.  See #17518 for its original description.
closes FXA-10411
> Stringify webchannel event details on Thunderbird as well as Firefox

- packages/fxa-react/components/Head/index.tsx
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/components/AppLayout/index.tsx
- packages/fxa-settings/src/components/Settings/PageSettings/index.tsx
- packages/fxa-settings/src/components/Settings/index.test.tsx
- packages/fxa-settings/src/components/Settings/index.tsx
- packages/fxa-settings/src/lib/glean/index.ts
* We want to enable grouping of the automated page load Glean pings, and the default data included all query params in url and generic page title ("Mozilla accounts") for most pings
* We initially thought the title could be a good way to group, but the document title is localized and not as useful as anticipated
* Sets a custom document title in the Head component
* Override the url provide on page load to glean to only include the pathname (excluding the params allows for easier grouping by route)
* Moves the page load event closer to page rendering for Settings pages, ensuring custom document titles are more reliably included with the pings
* Ensures additional metrics data (including flow id) is included for Settings pages
* Attempted to move the page load event into the AppLayout …
> fix(settings): Improve value of extra data included with automated Glean page load pings

- packages/fxa-settings/src/components/Settings/PageSettings/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageSettings/index.tsx
- packages/fxa-settings/src/components/Settings/ProductPromo/index.test.tsx
- packages/fxa-settings/src/components/Settings/ProductPromo/index.tsx
- packages/fxa-settings/src/models/Account.ts
- packages/fxa-settings/src/pages/Signin/SigninPushCodeConfirm/index.tsx
- packages/fxa-settings/src/pages/mocks.tsx
Because:
* We are seeing this event fire too many times, reproducible when navigating around Settings
This commit:
* Creates a shared function for PageSettings and ProductPromo to use to conditionally send the Glean ping and render the component as expected
fixes FXA-10403
---
I think the more ideal fix for this would still be the intersection observer to better tweak when this ping is sent especially in mobile, but we talked about simply having this fire once (if a promo is rendered) whenever the Settings page view event fires despite there being multiple promos rendered (in mobile there's one in nav + in Settings), so that's what this does.
I found that Barry's guess was correct - the Settings page view fires whenever you navigate inside of Settings and then navigate back to Settings, …
> fix(glean): Conditionally fire promo view event when Settings view event fires

- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- NextActions service methods do not reject on validation failures.
- `validateOrReject` returns a promise that needs to be awaited.
Closes: #
> fix(payments): failed validation does not reject

- packages/fxa-settings/src/components/NotificationPromoBanner/index.stories.tsx
- packages/fxa-settings/src/components/NotificationPromoBanner/index.tsx
- packages/fxa-settings/src/components/Settings/ConnectedServices/index.tsx
- packages/fxa-settings/src/components/Settings/DataCollection/index.tsx
- packages/fxa-settings/src/components/Settings/LinkedAccounts/index.tsx
- packages/fxa-settings/src/components/Settings/PageSettings/index.stories.tsx
- packages/fxa-settings/src/components/Settings/PageSettings/index.tsx
- packages/fxa-settings/src/components/Settings/ProductPromo/index.tsx
- packages/fxa-settings/src/components/Settings/Profile/index.tsx
- packages/fxa-settings/src/components/Settings/Security/index.tsx
* We want to match designs for mobile view
* Adjust styling of the NotificationPromoBanner component to support mobile view
* Adjust styling of PageSettings to use a gap between components (removes needs for setting external margins in section components
* Remove stacked banner story, the spacing between the banners is now set at the PageSettings level
* Adds story to PageSettings to show NotificationPromoBanner in context
* Small drive-by tweaks for ltr/rtl
Closes: #FXA-10405
Will add storybook links when deployed
> feat(settings): Adjust settings promo banner for mobile

- .circleci/config.yml
- The playwright test report job were failing for smoke tests due to a recent [PR](https://github.com/mozilla/fxa/pull/17537)
-
> remove HTML report job for smoke tests

- package.json
Because:
- we run two mysql containers now
This commit:
- updates the `mysql` "script" to connect to the container that's listening on the default port for mysql
> fix(dx): fix the `mysql` yarn command

- apps/payments/next/next.config.js
- apps/payments/next/sentry.client.config.ts
- apps/payments/next/sentry.server.config.ts
- Importing package.json in sentry config files resulted in build warning 'Should not import the named export'
- Add package version as env var added to js bundle by nextjs
> fix(next): resolve package import version warnings

- .circleci/config.yml
- Currently CircleCI doesn't let jobs with require parameter to be executed when the previous job fails with a failed status. But we needed to find a workaround for this to be able to generate HTML reports.
- A detailed explanation of the whole workaround is added on [FXA-10298](https://mozilla-hub.atlassian.net/browse/FXA-10298)
- This is for nightly only.
- Created a `waiter` job that will check for all the required job's status and when it's complete it executes the dependent job.
- The `waiter` job is called `check-required-jobs-complete` and the dependent job is `playwright-functional-test-report`
Any other information that is important …
> chore(functional_test): update config to run merge reports with test failures in Nightly

- .circleci/config.yml
- The `Check all required jobs are complete` waiter job needs additional job present in nightly only to be skipped while fetching the status and trying to proceed because of which `Nightly' job failed in the last run.
[CircleCI job run](https://app.circleci.com/pipelines/github/mozilla/fxa/54100/workflows/ffcc4fa8-84f3-4439-84f5-908da0feacec/jobs/528201)
- Adds the additional job for nightly to be skipped while fetching the status.
> fix nightly issue

- packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/container.tsx
- We noticed that if navigate action was slow, we could might still execute the subsequent code.
- Exits the function after navigation occurs.
Closes: FXA-10410
- [] I have added necessary documentation (if appropriate).
> bug(settings): Code should exit after navigation

- packages/fxa-settings/src/components/NotificationPromoBanner/index.test.tsx
- packages/fxa-settings/src/components/NotificationPromoBanner/index.tsx
- packages/fxa-settings/src/components/Settings/PageSettings/index.tsx
- Users that don't have Sync devices might not want to create a recovery key
- Only shows the recovery key banner if they have Sync devices and no recovery key
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10431
> fix(bug): Only show account recovery promo if the user has Sync-able devices

- packages/fxa-content-server/app/scripts/lib/app-start.js
- packages/fxa-content-server/app/scripts/lib/glean/index.ts
- packages/fxa-content-server/app/tests/spec/lib/glean.js
- packages/fxa-settings/src/components/App/index.test.tsx
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/components/Settings/index.tsx
- packages/fxa-settings/src/lib/glean/index.test.ts
- packages/fxa-settings/src/lib/glean/index.ts
Because:
- we want to send known metric values in the automatic page load events
This commit:
- set the available metrics when initializing Glean, before any page load events
> feat(metrics): set available ping metrics during Glean init

- packages/fxa-content-server/server/lib/routes/react-app/content-server-routes.js
- packages/fxa-content-server/server/lib/routes/react-app/index.js
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/components/InlineRecoveryKeySetupCreate/index.tsx
- packages/fxa-settings/src/components/NotificationPromoBanner/index.test.tsx
- packages/fxa-settings/src/components/NotificationPromoBanner/index.tsx
- packages/fxa-settings/src/lib/constants.ts
- packages/fxa-settings/src/pages/InlineRecoveryKeySetup/container.tsx
- packages/fxa-settings/src/pages/InlineRecoveryKeySetup/index.test.tsx
- packages/fxa-settings/src/pages/InlineRecoveryKeySetup/index.tsx
- We want to be able to dismiss this promo
- Adds functionalit to the do it later button
- Sets a localstorage value so that it wont appear again if the user clicked do it later
- Adds glean metric for button click
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10080
> feat(recovery): Add functionality of `do it later` in inline recovery key

- packages/fxa-content-server/app/scripts/models/pairing/supplicant-state-machine.js
- packages/fxa-content-server/app/scripts/templates/pair/failure.mustache
- packages/fxa-content-server/app/scripts/views/pair/failure.js
- packages/fxa-content-server/app/tests/spec/models/pairing/supplicant-state-machine.js
- The signin link when pairing fails is flaky
- Removes the signin buton
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10395
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10258
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10409
> fix(pairing): Remove the signin link when pairing fails

- packages/fxa-settings/src/components/Settings/PageDeleteAccount/index.tsx
* Incorrect password error was shown for all errors with account deletion
* Show correct localized error message
* Show in tooltip if incorrect password, otherwise use alertBar
Issue: #FXA-10392
This is only a partial fix for the reported error - it only fixes the message but not cause of the error (I have not been able to reproduce).
> fix(settings): Fix error message if account deletion fails

- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/docs/swagger/recovery-key-api.ts
- packages/fxa-auth-server/lib/db/index.js
- packages/fxa-auth-server/lib/routes/auth-schemes/hawk-fxa-token.js
- packages/fxa-auth-server/lib/routes/recovery-key.js
- packages/fxa-auth-server/lib/server.js
- packages/fxa-auth-server/test/client/index.js
- packages/fxa-auth-server/test/local/routes/recovery-keys.js
- packages/fxa-auth-server/test/mocks.js
- packages/fxa-auth-server/test/remote/password_forgot_tests.js
- packages/fxa-auth-server/test/remote/recovery_key_tests.js
- packages/fxa-settings/src/models/Account.ts
- packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/container.tsx
- packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/interfaces.ts
- packages/fxa-shared/db/models/auth/recovery-key.ts
Because:
- we want to allow the user to get their recovery key status with the 'passwordForgotToken' they received during the reset password flow
This commit:
- adds passwordForgotToken to the allowed auth strategies for the /recoveryKey/exists auth-server endpoint
- updates the auth client to use the passwordForgotToken to access that endpoint
- returns the recovery key hint along with the exists status
- passes the hint in Setting when navigating post-reset
Fixes FXA-9398, FXA-7400
> feat(recovery): fetch recovery key status with passwordForgotToken

- packages/fxa-settings/src/components/FormVerifyTotp/en.ftl
- typo in ftl string variable
- fix the typo
> fix(l10n): fix typo in FormVerifyTotp ftl file

- .circleci/config.yml
- packages/functional-tests/playwright.config.ts
- packages/functional-tests/tests/subscription-tests/support.spec.ts
- We need to add `chromium browser` to run our Playwright functional tests in `Nightly`
- Adds `chromium` as a project to the `playwright.config.ts` file
- Adds a different job for `run-playwright-tests-chromium` , `rename-reports-chromium` and a workflow `playwright-functional-tests-chromium` to run these jobs in.
- The `playwright-functional-tests` and `playwright-functional-tests-chromium` runs the firefox tests and chromium tests respectively, and generates separate `test.xml` file and `blob reports` (firefox: `reports-[0-7]-firefox.zip`, chromium: `reports-[0-7]-chromium`)
- Currently, HTML reports are only generated for firefox tests.
- One of the tests in `support.spec.ts` - `go to support form, cancel, redirects to subscription management` is currently failing in `chromium` as the …
> chore(functional_test): run playwright functional tests in chromium browser

- packages/functional-tests/lib/fixtures/standard.ts
- packages/functional-tests/pages/index.ts
- packages/functional-tests/pages/inlineRecoveryKey.ts
- packages/functional-tests/tests/misc/recoveryKeyPromo.spec.ts
- packages/functional-tests/tests/settings/recoveryKey.spec.ts
- packages/functional-tests/tests/signin/connectAnotherDevice.spec.ts
- packages/functional-tests/tests/syncV3/settings.spec.ts
- packages/functional-tests/tests/syncV3/signIn.spec.ts
- packages/functional-tests/tests/syncV3/signinCached.spec.ts
- packages/fxa-content-server/server/lib/routes/get-index.js
- packages/fxa-settings/src/components/NotificationPromoBanner/index.tsx
- We want to add functional tests for the recovery key inline flow
- Adds functional tests
- Sets a localstorage flag so that it is disabled for all other functional tests
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10081
This is blocked by https://mozilla-hub.atlassian.net/browse/FXA-10079, but I should be able to get it close while that issue is still being worked.
> feat(tests): Add functional test for inline recovery key and settings promo

- apps/payments/next/app/%5F_version__/route.ts
- other applications have a __version__ route, but the payments-next app does not
- adds a GET /__version__ endpoint, which returns the version as described in apps/payments/next/package.json
Closes: # [FXA-8295](https://mozilla-hub.atlassian.net/browse/FXA-8295)
[FXA-8295]: https://mozilla-hub.atlassian.net/browse/FXA-8295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(next): add __version__ route for next app

- packages/functional-tests/package.json
- packages/functional-tests/playwright.config.ts
- packages/functional-tests/tests/misc/recoveryKeyPromo.spec.ts
- packages/functional-tests/tests/settings/changeEmailBlocked.spec.ts
- Sync test should fail in Chrome because it won't always respond with the correct webchannels
- Skips for the local-chrome project
- Adds a new command `yarn test-local-chromium --grep="<some tests>"`  for easier local testing
- Updates the local playwright test workers to 4 because 16 was causing timeout issues (I can't imagine a local machine that can handle 16 playwright test workers at once)
- Fixes an unrelated unblock test
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10445
> fix(tests): Skip Chrome when doing Sync base test

- packages/fxa-settings/src/components/App/index.test.tsx
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/lib/glean/index.test.ts
- packages/fxa-settings/src/lib/glean/index.ts
Because:
- the account uid in the Settings Glean metrics context does not change when the user signs in
This commit:
- uses Settings' currentAccount function to get the account whenever Glean sets a metric with the current account uid
> fix(metrics): use Settings' currentAccount directly for uid

- libs/payments/legacy/src/lib/stripe-mapper.service.spec.ts
- libs/payments/legacy/src/lib/stripe-mapper.service.ts
- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- Legacy mapper was not using localization data from the CMS
- Updated legacy mapper to utilize localization data.
Closes: #FXA-10436
This can be tested by using the following product and price.
- prod_JYy0wNbTbA5fDv
- price_1OUAavBVqmGyQTMazqzrIjcz
Note that until FXA-10428 is fixed, [the following lines of code](https://github.com/mozilla/fxa/blob/00bc5d2fcbfdcb8d6644d86dcae75933719b4241/packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts#L950-L953) need to be deleted or commented out.
```
.items(
validators.subscriptionsPlanWithProductConfigValidator,
validators.subscriptionsPlanWithMetaDataValidator
) as any,
```
> fix(payments-legacy): support cms localization

- libs/shared/sentry/src/lib/next/client.ts
- libs/shared/sentry/src/lib/utils/beforeSend.client.ts
- package.json
- packages/fxa-admin-server/package.json
- packages/fxa-admin-server/src/app.module.ts
- packages/fxa-admin-server/src/event-logging/event-logging.module.ts
- packages/fxa-admin-server/src/main.ts
- yarn.lock
- We are narrowing down the issue
- Downgrades @sentry/nextjs to version 7.
- Adds rudimentary logging for simple timings data
This maybe the smoking gun. When `@sentry/nextjs` was downgraded to v7 locally a significant reduction in start up time was observed. Almost every subsequent import took much less time. Here's just a quick comparison of some of the initial start up logs from my local machine. I suspect these effects will only be amplified in staging/prod.
With @sentry/nextjs:^8
```
main: { step: './monitoring', delta: 1253, elapsed: 1253 }
main: { step: '@nestjs/common', delta: 1, elapsed: 1254 }
main: { step: '@nestjs/core', delta: …
```
> task(admin-server): More debugging into admin-server startup times

- apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/new/page.tsx
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/ui/src/lib/client/components/CouponForm/index.tsx
validation done, removing comments
- Current coupons need to be manually entered by user. Links to initiate a subscription checkout flow currently can't contain coupon information.
- Passes `coupon` route parameter to the stripe cart.
- Works with [FXA-10439](https://mozilla-hub.atlassian.net/browse/FXA-10439), which handles coupon information display.
Closes: # [FXA-7831](https://mozilla-hub.atlassian.net/browse/FXA-7831)
Validated against stripe by enabling hacktheplanet coupon code for one of the test VPN subscription prices: https://dashboard.stripe.com/test/prices/price_1OUAavBVqmGyQTMazqzrIjcz
[FXA-10439]: https://mozilla-hub.atlassian.net/browse/FXA-10439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> Add support for subscription coupon via route param

- packages/functional-tests/pages/resetPassword.ts
- packages/fxa-settings/src/components/FormPasswordWithInlineCriteria/en.ftl
- packages/fxa-settings/src/components/FormPasswordWithInlineCriteria/index.test.tsx
- packages/fxa-settings/src/components/FormPasswordWithInlineCriteria/index.tsx
- packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.test.tsx
- New design has "Create new password" button copy
- Update button copy and related tests
Closes: #FXA-10071
> update reset password button copy

- libs/payments/metrics/src/lib/glean/glean.provider.ts
- libs/shared/db/firestore/src/lib/firestore.provider.ts
- In development, while payments-next is running, when the nestapp restarts due to dev changes, the Glean logger adds additional log handlers, resulting in duplicate messages.
- In development only, use a randomized logger name, so that no duplicate log handlers are created.
Closes: #FXA-10450
> fix(payments-next): fix duplicate glean logs

- libs/payments/metrics/src/lib/glean/glean.service.spec.ts
- libs/payments/metrics/src/lib/glean/glean.service.ts
- libs/shared/db/mysql/account/src/index.ts
- libs/shared/db/mysql/account/src/lib/factories.ts
- Currently glean logs data on users irrespective of if they have opted out of metrics collection
- Checks `metricsOptOutAt` field on db user, and prevents logging if the field is set
- Adds `AccountFactory` to the factories.ts file for use in tests
> feat(next): respect metrics opt-out flag

- packages/fxa-content-server/app/scripts/views/pair/unsupported.js
Because:
* We want a different view to render if this is true, and there was an issue with the check where it was always falsey
This commit:
* Adjusts what's passed into getHashParams
fixes FXA-10443
---
Run `yarn firefox`, change the UA to a mobile UA in dev tools/responsive design mode, and go to `pair/unsupported#channel_id=hello&channel_key=world`
> fix(pair): Fix check around isSystemCameraUrl

- packages/functional-tests/pages/connectAnotherDevice.ts
- packages/fxa-content-server/app/scripts/templates/connect_another_device.mustache
- packages/fxa-content-server/app/scripts/templates/ready.mustache
- packages/fxa-content-server/app/tests/spec/views/ready.js
- packages/fxa-settings/src/components/Ready/en.ftl
- packages/fxa-settings/src/components/Ready/index.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/index.test.tsx
- packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml
- packages/fxa-shared/metrics/glean/web/cad.ts
Because:
* 'Start browsing' is confusing since it takes users to account settings
This commit:
* Updates the copy to 'Manage your account'
fixes FXA-10376
---
I realized after I started on this that with our tickets recently landed with the CAD/pair updates, I'm not sure if users will ever see this page. It was pretty quick though and won't hurt to land.
> task(CAD): Update 'Start browsing' to 'Manage your account'

- packages/fxa-settings/src/components/ResetPasswordWarning/en.ftl
- we need to use brand terms in l10n strings
- adds brand term
> add missing l10n brand term

- _scripts/check-pre-launch.sh
- The NX Cache can get really big
- It's easy to not realize until it's a problem :(
- Adds a pre-launch check for nx cache size, and offers to clear it out for you.
> chore(dev): Check size of nx cache

- packages/functional-tests/pages/resetPassword.ts
- packages/functional-tests/tests/key-stretching-v2/recoveryKey.spec.ts
- packages/functional-tests/tests/key-stretching-v2/resetPassword.spec.ts
- packages/fxa-settings/src/pages/ResetPassword/ResetPassword/en.ftl
- packages/fxa-settings/src/pages/ResetPassword/ResetPassword/index.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPassword/index.tsx
* Page was redesigned, needs new strings and left-alignment
* Update copy, l10n, styling and tests for the initial reset password page
Closes: #FXA-10475
Updated design:
> feat(settings): Update copy and styling of initial reset password page

- packages/functional-tests/tests/key-stretching-v2/recoveryKey.spec.ts
- packages/functional-tests/tests/key-stretching-v2/resetPassword.spec.ts
- packages/functional-tests/tests/resetPassword/oauthResetPassword.spec.ts
- packages/functional-tests/tests/resetPassword/oauthResetPasswordSyncMobile.spec.ts
- packages/functional-tests/tests/resetPassword/resetPassword.spec.ts
- packages/functional-tests/tests/resetPassword/resetPasswordRecoveryKey.spec.ts
- packages/functional-tests/tests/resetPassword/syncV3ResetPassword.spec.ts
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/models/Account.ts
- packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/container.tsx
Because:
- the user could have a verified session after successfully resetting
their password for an account
This commit:
- logs the account in and take the user to /settings if the session is
verified and the user did not use a recovery key during the reset
> Log account in and navigate to /settings after password reset

- apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/layout.tsx
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/cart.types.ts
- libs/payments/ui/src/index.ts
- libs/payments/ui/src/lib/client/components/MetricsWrapper.tsx
- libs/shared/sentry/src/lib/next/client.ts
- libs/shared/sentry/src/lib/utils/beforeSend.client.spec.ts
- libs/shared/sentry/src/lib/utils/beforeSend.client.ts
- Currently metrics are still collected from the user via sentry, regardless of their "opt-out" status.
- Checks the user's account status via the cart service, which sets a tag at the top level of the sentry client instance
- If the metricsOptOut tag is set with the value `true`, then sentry does not send events from anywhere on the front end
Closes: [# FXA-10398](https://mozilla-hub.atlassian.net/browse/FXA-10398)
> feat(next): Sentry client to respect metrics opt-out

- packages/fxa-auth-server/config/dev.json
- packages/fxa-content-server/server/config/local.json-dist
- packages/fxa-dev-launcher/README.md
- packages/fxa-dev-launcher/profile.mjs
- packages/fxa-react/lib/utils.tsx
- packages/fxa-settings/src/lib/oauth/hooks.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/index.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
- packages/fxa-settings/src/pages/Signin/index.test.tsx
- packages/fxa-settings/src/pages/Signin/index.tsx
- packages/fxa-settings/src/pages/Signin/mocks.tsx
- packages/fxa-settings/src/pages/Signin/utils.ts
Because:
* We want to support the new oauth desktop flow, and there is a bug during signin because we were sending fxaOAuthLogin first
This commit:
* Refactors signin/utils to swap the order these web channel messages fire
* Fixes an additional intermittent bug for 2FA and new account signins caused by sending keyFetchToken and unwrapBKey
* Adds oauth desktop config
* Renames oauthCode to oauthData in oauth hook
fixes FXA-10388
---
Most of this was already accounted for in page-level tests. I'm going to be taking a better look at our test coverage in FXA-10328 next.
Test this by running `yarn firefox` for our desktop v3 flow and `FXA_DESKTOP_CONTEXT=oauth_webchannel_v1 yarn firefox` for the oauth desktop flow. Check out a standard Sync signin (requires email code), a new Sync account …
> fix(oauth-desktop): Call fxaLogin before fxaOAuthLogin with expected data during signin

- packages/fxa-admin-server/src/scripts/restore-rk.mjs
- We want to restore a few RKs from a backup db
- Adds a script to do this
Closes: FXA-10508
To run, create .env with necessary db hosts and and config.
```
cd packages/fxa-admin-server
yarn install
dotenv -- node src/scripts/restore-ky.mjs --start=2024-09-30 --stop=2024-10-01 --dry=true
```
This does a dry run, which just produces info. Set dry=false to do actual run.
> task(admin): Create script for restoring RKs

- packages/fxa-admin-server/src/scripts/restore-rk.mjs
- We might not want to process all users in the flat file
- Applies start stop times to flat file processing
> bug(admin): Use start / stop when reading from flat file

- packages/fxa-settings/src/components/FormVerifyTotp/index.tsx
- packages/fxa-settings/src/components/RecoveryKeySetupHint/index.test.tsx
- packages/fxa-settings/src/components/RecoveryKeySetupHint/index.tsx
- packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/container.tsx
- packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPassword/container.tsx
* ConfimResetPassword code submit button was not disabled after an invalid code error
* AccountRecoveryConfirmKey input did not have a character limit
* RecoveryKeySetupHint returned an error when the submitted hint was too long, but submit stayed disabled even after updating the hint
* Set a character limit on the AccountRecoveryConfirmKey and RecoveryKeySetupHint inputs, ensure submit is re-enabled onChange
* Disable the ConfirmResetPassword submit button if the code is invalid
Closes: #FXA-10477, FXA-10481, FXA-10495
> fix(settings): Improve code and key input for reset password

- packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.tsx
- The metric was incorrectly added to fire on the 'Continue' button click, but we really want this to fire when the QR code was viewed instead.
- We now fire the Glean metric when the QR code is visible.
- Is a clone of https://github.com/mozilla/fxa/pull/17745 (upstream PR vs fork PR).
Closes: FXA-9573
> feat(metrics): Fix '2FA QR Code Setup View' to fire on view

- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/docs/swagger/totp-api.ts
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/test/local/routes/totp.js
- We need to add a few backend methods to check 2FA status
- Adds new routes that are authenicated with a `passwordForgotToken` to verify code and recovery code
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10513
I could not reuse our existing routes to check for 2FA code and recovery code. There was to many session specific things which did not make sense (metrics, verify session). This approach is a little cleaner and simplier than to try to fit it in.
> feat(totp): Add backend methods for 2FA before password reset

- libs/shared/notifier/src/index.ts
- libs/shared/notifier/src/lib/notifier.provider.ts
- libs/shared/notifier/src/lib/notifier.service.spec.ts
- libs/shared/notifier/src/lib/notifier.service.ts
- libs/shared/notifier/src/lib/notifier.sns.config.ts
- packages/fxa-admin-server/src/app.module.ts
- packages/fxa-admin-server/src/gql/gql.module.ts
- packages/fxa-graphql-api/src/app.module.ts
- packages/fxa-graphql-api/src/gql/gql.module.ts
- packages/fxa-graphql-api/src/scripts/must-change-password.ts
- we are using TypedConfig, while NotifierService and ProfileClient are using ConfigService
~~- [ ] adds config for `domain`~~ this will be its own ticket/PR
Closes: FXA-10511
> feat(libs): Create NestLogger wrappers

- packages/fxa-content-server/app/scripts/models/reliers/oauth.js
- packages/fxa-settings/src/pages/Signin/container.test.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
Because:
* We were only checking for desktopv3 in this case and want to check for desktopv3 and oauth desktop
This commit:
* Modifies the condition to call firefox.fxaCanLinkAccount, updates tests
fixes FXA-10328
---
**NOTE**, what I have here does fix the issue at hand but a more ideal solution (especially considering the Relay work) for this is WIP [in this branch](https://github.com/mozilla/fxa/compare/FXA-10328), but it's not ready yet. I'm going to be reducing points on this and instead creating a follow up ticket to finish that branch out on, which I will also review our oauth desktop tests in (as mentioned in this ticket).
edit: follow up is FXA- 10528
> fix(oauth-desktop): Send canLinkAccount if service=sync

- libs/payments/cart/src/lib/checkout.service.ts
- accountCustomer record is not created for uid and stripeCustomerId for a new customer.
- Updates the CheckoutServic to create accountCustomer record when uid and stripeCustomerId exist.
> fix(next): create accountCustomer record on sub

- packages/functional-tests/tests/resetPassword/resetPassword.spec.ts
- packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/container.tsx
Because:
- when an account has an unverified 2fa and the user opt to not use the recovery key, we should not prompt for the TOTP during password reset
This commit:
- ensures that 2fa is enabled, exists and verified, for the account
> fix(password reset): stop prompting for unverified 2fa during reset

- .github/workflows/docker.yml
- _scripts/create-version-json.sh
The `GITHUB_REF_NAME` variable only works for tags pushed by developers.
When calling the docker.yml workflow from tag-release.yml, the contents
of `GITHUB_REF_NAME` is `main`, the branch that the GitHub Action is
running on. This will fix the version output for x.y.0 tags created by
tag-release.yml.
> fix(docker): Use git tag from lookup

- packages/fxa-settings/src/components/Settings/ConnectedServices/index.tsx
- packages/fxa-settings/src/lib/utilities.test.ts
- packages/fxa-settings/src/lib/utilities.ts
- packages/fxa-settings/src/models/Account.ts
- We got a sentry report where client name wasn't defined
- Changes types to reflect grqphql schema, which allows name to be null
- Updates codes accordingly
- Adds fallback for null/undefined client names
Closes: FXA-10326
From the sentry issue it appears that the client name can be undefined. In general this shouldn't happen, but our code should still be able to handle this in the event it does occur. I also noticed that there's existing comment about the GQL schema and our client side model don't necessarily match. This is really how this bug originated in the first place. If our types don't match what's on the server, we expose ourselves to these types of bugs.
> bug(settings): Client name can be undefined

- packages/fxa-auth-server/lib/routes/auth-schemes/hawk-fxa-token.js
- packages/fxa-auth-server/lib/routes/emails.js
- packages/fxa-auth-server/lib/routes/recovery-codes.js
- packages/fxa-auth-server/lib/routes/session.js
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/lib/server.js
- packages/fxa-auth-server/test/remote/recovery_code_tests.js
- packages/fxa-auth-server/test/remote/totp_tests.js
- We currently do this in the code, but it is better to make it generic
- Updates our `sessionToken` auth scheme to make sure that session token is 2FA verified (assurance level < 2), if the user has it
- Adds a new auth scheme `sessionTokenNoAssurance` that does not do this check, which is needed in certain verification routes that mark the session 2FA verified.
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10418
> feat(2fa): Add auth scheme to require 2FA on session token

- packages/fxa-settings/src/pages/InlineTotpSetup/container.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninPushCode/container.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.test.tsx
- packages/fxa-settings/src/pages/Signin/container.test.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
* We want to make sure that the email shown after redirect to signin from reset password with 2FA is correct
* If another account was signed into Sync or a different emails was included in query params, that email would be shown after redirect
* Include the email in location state when navigating to signin after password reset with unverified session
* Prioritize email from location state vs query params on sign in
* Cleanup warnings for a few unit tests
Closes: #FXA-10557
We should also validate and clean unused query params, but I'll file a separate issue for that.
> fix(fxa-settings): Show correct email for signin after reset

- libs/payments/cart/src/lib/cart.error.ts
- libs/payments/cart/src/lib/cart.manager.in.spec.ts
- libs/payments/cart/src/lib/cart.manager.ts
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/checkout.factories.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/cart/src/lib/checkout.types.ts
- libs/payments/ui/src/lib/actions/checkoutCartWithPaypal.ts
- libs/payments/ui/src/lib/actions/getPayPalCheckoutToken.ts
- libs/payments/ui/src/lib/client/components/CheckoutForm/index.tsx
- Submit PayPal checkout to payments-next
- Add logic to PayPal button createOrder and onApprove hooks.
Closes: #FXA-7586
> feat(next): paypal createOrder and onApprove hooks

- packages/fxa-auth-server/lib/routes/recovery-codes.js
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/test/local/routes/totp.js
- We don't want a user to get locked out of account if they run out of recovery codes
- Emails the user to let them know a code was consumed (and how many remaining), also emails user if they have "low" amount
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10555
> fix(bugs): Send low recovery codes email when consuming during password reset

- packages/functional-tests/tests/resetPassword/resetPassword.spec.ts
- packages/fxa-settings/src/pages/ResetPassword/ConfirmTotpResetPassword/en.ftl
- packages/fxa-settings/src/pages/ResetPassword/ConfirmTotpResetPassword/index.tsx
- We want to add a few more metrics for 2FA with password reset
- Adds Glean events
- `reset_password_confirm_recovery_code_submit_button`
- `reset_password_confirm_recovery_code_trouble_with_code_button`
- `reset_password_confirm_totp_code_submit_button`
- `reset_password_confirm_totp_use_different_account_button`
- `reset_password_confirm_totp_trouble_with_code_button`
- Adds the `Use different account` link
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10558
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10533
Added a bunch of new Glean metrics for this feature, note that the names are a little different than ticket to match other events and for more clarity.
> feat(2fa): Add metrics for 2FA password reset, add `use different account` link

- packages/functional-tests/lib/query-params.ts
- packages/functional-tests/tests/misc/relayIntegration.spec.ts
- We want functional tests for Relay
- Adds functional tests for signin, signup, signin with email confirm, and signin with 2FA
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10415
> feat(tests): Add functional tests for Relay

- packages/fxa-settings/src/pages/Signup/index.test.tsx
- packages/fxa-settings/src/pages/Signup/index.tsx
Because:
* This is causing intermittent issues where desktop thinks it should fetch keys
This commit:
* Does not send keyFetchToken/unwrapBKey if isOAuth is true
fixes FXA-10617
---
This was fixed [here for signin](https://github.com/mozilla/fxa/pull/17744/files#diff-a9a9b44d99bf0ed9a478d27f27cb4071ac2dc6874ead5caea0648f1df9bb25c5R174) a couple of weeks back. I want to DRY this up so we don't have to think about this when sending `fxaLogin`, but I already need to modify the login message in FXA-10614, so I'll create a helper function or make tweaks in `firefox.ts` for that in the other ticket.
To the reviewer - you _probably_ won't be able to reproduce the issue locally. I tried 7 times yesterday and didn't reproduce once, but it's reproducing more in stage/prod (this is a pref in Nightly …
> fix(oauth-desktop): Don't send up some options to fxaLogin when OAuth sync

- packages/fxa-settings/src/lib/channels/firefox.ts
- packages/fxa-settings/src/pages/Signin/index.test.tsx
- packages/fxa-settings/src/pages/Signin/utils.ts
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.test.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx
- packages/fxa-settings/src/pages/Signup/index.test.tsx
- packages/fxa-settings/src/pages/Signup/index.tsx
Because:
* We want to send service: { relay: {} } in fxaLogin instead of fxaOAuthLogin in case users start with the Relay flow and then click the browser profile icon to finish the flow; this will prevent 'surprise sync' when patch lands on desktop side
* For sync, we don't want the browser to forget which sync engines were sent up if users drop off after signing up but don't confirm their account
This commit:
* Sends these pieces of data up in fxaLogin instead of fxaOAuthLogin, but keeps sending sync engines in ConfirmSignupCode around for mobile clients until we can get issues filed and worked on their side
closes FXA-10614, closes (on our side) FXA-10596
---
When I started to look at tests, I realized we're actually already sending up sync engines for `fxaLogin` if `isSync` is true; …
> fix(sync): Adjust fxaLogin / fxaOAuthLogin web channel data for oauth desktop

- packages/fxa-auth-server/scripts/delete-inactive-accounts/get-inactive-account-uids.ts
- packages/fxa-shared/db/models/auth/security-event.ts
Because:
- we want to get an estimate of inactive accounts
This commit:
- adds a script that writes a list of UIDs of inactive accounts
- it is a one-time script to help us to understand the problem size of inactive accounts
- it is meant to be manually executed (i.e. no cron job)
> chore(scripts): add script to get inactive accounts

- packages/fxa-settings/src/lib/channels/firefox.ts
- packages/fxa-settings/src/pages/Signin/container.test.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
- We have a report that a user logs in but is immediately disconnected from sync
- We know from FF logs, that when this happens a keyFetchToken is present, but the unwrapBKey is missing.
- Adds more sentry error capture to try and pinpoint exact condition this occurs under.
Aside from reports in bugzilla, we haven't been able to reproduce through normal usage. Things I've tried:
- I've tried both with the key stretching experiment disabled and enabled.
- I've tried on v1, v2, and v1 upgrading to v2 accounts.
- I've tried on v1 accounts where the primary email was changed.
- I tried on a mac and a windows machine.
Other important things to …
> task(settings): Add more error capture

- packages/fxa-payments-server/src/components/DialogMessage/index.scss
- packages/fxa-payments-server/src/components/DialogMessage/index.tsx
- adds hover-state style to DialogMessage component
Closes: FXA-10633
> fix(payments-server): Add hover style to Close Button in DialogMessage component

- libs/payments/cart/src/lib/cart.error.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- Removes logic creating stub account as it is no longer needed with the new signin/up process
Closes: FXA-10550
> fix(payments-cart): Remove stub account logic

- package.json
- packages/fxa-auth-server/lib/payments/iap/apple-app-store/purchase-manager.ts
- packages/fxa-auth-server/package.json
- packages/fxa-auth-server/test/local/payments/fixtures/apple-app-store/decoded_transaction_info.json
- packages/fxa-auth-server/test/local/payments/iap/apple-app-store/subscription-purchase.js
- packages/fxa-shared/package.json
- packages/fxa-shared/payments/iap/apple-app-store/subscription-purchase.ts
- yarn.lock
- Apple App Store Server API added new fields to the transaction and renewal info which should be recorded in the SubPlat Firestore.
- Adds fields currency, price and storefront from transactionInfo
- Adds fields currency and renewalPrice from renwalInfo
Closes: #FXA-10549
> feat(iap): add new apple iap fields to firestore

- packages/fxa-auth-server/scripts/delete-inactive-accounts/get-inactive-account-uids.ts
Because:
- an account is considered active when any of the timestamps is at or newer than the active by date
This commit:
- fixes the sql's where conditions so that any such timestamp filters the account out of the list
> fix(scripts): update where conditions on inactive accounts query

- packages/fxa-settings/src/lib/oauth/hooks.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/container.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/mocks.tsx
- packages/fxa-settings/src/pages/Signin/interfaces.ts
- packages/fxa-settings/src/pages/Signin/mocks.tsx
- We had reports of users getting disconnected from sync
- We had firefox logs showing the unwrapBKey was not being provided by FxA
- Ensures unwrapBKey is provided
- Introduces a test file for SigninUnbock container
- Fixes a bug in our mocks where the credentialStatus.currentVersion wasn't the correct format
- Switches to SigninOAuthIntegration for useFinishOAuthFlowHandler, which is a more accurate and restricted interface.
Closes: FXA-10641 
This is a follow for the main branch. The issue was also quickly patched on train-285 [here](https://github.com/mozilla/fxa/pull/17923).
> bug(settings): Signin Unblock was dropping unwrapBKey

- packages/functional-tests/pages/relier.ts
- packages/functional-tests/tests/oauth/totp.spec.ts
- packages/fxa-settings/src/pages/InlineTotpSetup/container.tsx
- Some users were having issues setting up 2FA in the inline flow
- It appears that the `useEffect` was being called twice and creating then replacing the 2FA device
- Adds a ref so that the async create function only gets called once
- Adds a functional test for the flow
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10583
I looked at having the create token only be trigger when the user clicks "Continue" but it was turning out to be a big refactor the way the container pattern was setup.
> feat(tests): Fix 2FA inline setup flow

- packages/fxa-dev-launcher/README.md
- packages/fxa-settings/src/lib/channels/firefox.ts
- packages/fxa-settings/src/models/integrations/base-integration.ts
- packages/fxa-settings/src/models/integrations/client-matching.ts
- packages/fxa-settings/src/models/integrations/oauth-native-integration.ts
- packages/fxa-settings/src/models/integrations/oauth-web-integration.ts
- packages/fxa-settings/src/models/integrations/utils.test.ts
- packages/fxa-settings/src/models/integrations/utils.ts
- packages/fxa-settings/src/pages/InlineRecoverySetup/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/container.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx
- packages/fxa-settings/src/pages/Signup/container.tsx
- packages/fxa-settings/src/pages/Signup/mocks.tsx
Because:
* We want to clean up some things that recently landed
This commit:
* Adds a function to check if the service is 'relay' or 'sync', fixes typos, removes redundent option in dev-launcher README
fixes part of FXA-10614
> chore(cleanup): DRY up service checks, comment/dev-launcher README tweak

- libs/payments/ui/src/lib/client/components/SignInForm/en.ftl
- libs/payments/ui/src/lib/client/components/SignInForm/index.tsx
- adds error message for invalid email input
Closes: FXA-10546
Missing email
Invalid email
> feat(payments-ui): Add error messaging for invalid email input

- libs/accounts/recovery-phone/.eslintrc.json
- libs/accounts/recovery-phone/README.md
- libs/accounts/recovery-phone/jest.config.ts
- libs/accounts/recovery-phone/package.json
- libs/accounts/recovery-phone/project.json
- libs/accounts/recovery-phone/src/index.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.ts
- libs/accounts/recovery-phone/tsconfig.json
- libs/accounts/recovery-phone/tsconfig.lib.json
- libs/accounts/recovery-phone/tsconfig.spec.json
- tsconfig.base.json
Because:
* We want a root recovery-phone library for related functionality.
This commit:
* Adds a new recovery-phone library.
> feat: add recovery-phone library

- packages/fxa-auth-server/lib/routes/oauth/token.js
- We are getting alot more unverified session errors in this route
- Uses our legacy auth scheme on the route
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10677
I don't have solid leads on why it was having such a huge increaes in errors, but suspect legacy sessions before 2FA was enabled might be getting tripped. We do have other routes with exceptions so this might have to fall in that category.
> fix(bug): Skip session assurance check in /oauth/token route

- packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-webchannel-v1.js
- packages/fxa-content-server/app/tests/spec/models/auth_brokers/oauth-webchannel-v1.js
- packages/fxa-settings/src/pages/Signin/container.test.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
Because:
* iOS and Android now support responding with ok: true automatically
This commit:
* Makes conditions for when we send this more consistent
closes FXA-10638
---
~I'm thinking we should wait for Mark's response [here](https://mozilla.slack.com/archives/C07MSPY85LN/p1729892740422919) where I ask what our plan is for `isDesktopRelay`; I can either remove my comment in Signin or go ahead and implement any changes here, I'll mark this as a draft in the meantime.~
Mark said this is good for now, so I'm going to just leave it open and also leave the comment unless someone requests I remove it. Mark says we'll probably be revisiting this soon when we discuss third party auth buttons + `service=sync` integration.
> feat(sync): Remove 'desktop only' restriction to send can_link_account

- packages/fxa-auth-server/lib/routes/auth-schemes/hawk-fxa-token.js
- packages/fxa-auth-server/lib/routes/emails.js
- packages/fxa-auth-server/lib/routes/oauth/token.js
- packages/fxa-auth-server/lib/routes/recovery-codes.js
- packages/fxa-auth-server/lib/routes/session.js
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/lib/server.js
- packages/fxa-auth-server/test/remote/recovery_code_tests.js
- packages/fxa-auth-server/test/remote/totp_tests.js
> Revert "feat(2fa): Add auth scheme to require 2FA on session token"

- libs/accounts/two-factor/.eslintrc.json
- libs/accounts/two-factor/README.md
- libs/accounts/two-factor/jest.config.ts
- libs/accounts/two-factor/package.json
- libs/accounts/two-factor/project.json
- libs/accounts/two-factor/src/index.ts
- libs/accounts/two-factor/src/lib/backup-code.factories.ts
- libs/accounts/two-factor/src/lib/backup-code.manager.in.spec.ts
- libs/accounts/two-factor/src/lib/backup-code.manager.ts
- libs/accounts/two-factor/src/lib/backup-code.repository.ts
- libs/accounts/two-factor/src/lib/backup-code.types.ts
- libs/accounts/two-factor/tsconfig.json
- libs/accounts/two-factor/tsconfig.lib.json
- libs/accounts/two-factor/tsconfig.spec.json
- libs/shared/db/mysql/account/src/lib/tests.ts
- libs/shared/db/mysql/account/src/test/recoveryCodes.sql
- tsconfig.base.json
- We want to be able to retrieve recovery codes for a given user
- Adds the `BackupCodeManager` class
- Adds method `hasRecoveryCodes`
- Supporting tests
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10332
The linked issue mentions the nx lib should be `2fa`, but nx wont let you create a lib starting with a number. Opted for `two-factor` instead.
> feat(2fa): Add `two-factor` lib

- packages/fxa-auth-server/lib/l10n/index.ts
- packages/fxa-auth-server/lib/metrics/glean/index.ts
- packages/fxa-auth-server/lib/payments/iap/apple-app-store/errors.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/password.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/lib/senders/emails/mjml-browser-helper.ts
- packages/fxa-auth-server/lib/senders/emails/partials/userDevice/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/index.stories.ts
- packages/fxa-auth-server/lib/senders/renderer/bindings-browser.ts
- packages/fxa-auth-server/lib/senders/renderer/bindings.ts
- packages/fxa-auth-server/lib/senders/renderer/index.ts
- packages/fxa-auth-server/package.json
- packages/fxa-auth-server/scripts/populate-firestore-customers.ts
- packages/fxa-auth-server/scripts/prune-tokens.ts
- packages/fxa-auth-server/scripts/stripe-products-and-plans-to-firestore-documents/stripe-products-and-plans-converter.ts
- packages/fxa-auth-server/test/local/metrics/glean.ts
- packages/fxa-auth-server/test/local/senders/emails.ts
- packages/fxa-auth-server/test/scripts/convert-customers-to-stripe-automatic-tax-helpers.ts
- packages/fxa-auth-server/test/scripts/convert-customers-to-stripe-automatic-tax.ts
- packages/fxa-auth-server/test/scripts/move-customers-to-new-plan.ts
- packages/fxa-auth-server/tsconfig.json
- While working on FXA-10460, I noticed that auth-server wasn't actually targeting all typescript files for compilation.
- Targets all files
- Fixes ensuing errors
Closes: FXA-10676
This is a fast follow to #17938. Also it's good to note that make this PR reasonable in size, `noImplicitAny` was set to false. We can address this at a later point in time. There were enough of these errors that it didn't make sense to fix them here, and to fix them properly actual types should be tracked down.
> bug(auth): Typescript not checking all files

- packages/fxa-auth-server/package.json
- Build process no longer included JS files in the bin/ folder
- Updates build-finalize script to manually copy the entire bin folder into dist/
> fix(auth): fix missing bin js files

- packages/fxa-auth-server/package.json
- packages/fxa-auth-server/tsconfig.json
- JS files in bin/ directory did not have TS aliases replaced with relative paths.
- Include JS files in bin/ directory in tsconfig, so that it's picked up by tsc-alias during the build-ts script execution.
> fix(auth): include bin/ in build-ts script

- packages/fxa-auth-server/lib/payments/iap/apple-app-store/apple-iap.ts
- packages/fxa-auth-server/lib/payments/iap/google-play/play-billing.ts
- packages/fxa-auth-server/lib/payments/iap/google-play/user-manager.ts
- packages/fxa-auth-server/scripts/delete-inactive-accounts/get-inactive-account-uids.ts
- packages/fxa-auth-server/scripts/delete-inactive-accounts/lib.ts
Because:
- the script was checking for IAP subscriptions on every account in the db results
This commit:
- builds a set of account uids that might have IAP subscriptions and only check when the account uid is in the set
- moved some code into a file that will be shared with another script
> feat(scripts): update IAP subscription check on inactive uids script

- packages/fxa-auth-server/scripts/delete-inactive-accounts/get-inactive-account-uids.ts
Adding some basic performance stats to the inactive uids script to better understand why it takes so long to run.
> chore(scripts): add option for perf stats on inactive uids script

- libs/accounts/recovery-phone/src/lib/recovery-phone.manager.in.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.manager.ts
- We want to store the unconfirmed code in Redis
- Updates the RecoveryPhoneManager to store this code
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10346
I took a look at adding the `OtpManager` (same one we use for password reset code), but we would need to refactor it a good bit to accept additional data needed for sms. To unblock other stuff, we can add that in a follow up.
> feat(phone): Add `unconfirmed` to RecoveryPhoneManager

- libs/accounts/recovery-phone/src/lib/recovery-phone.errors.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.config.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- libs/accounts/recovery-phone/src/lib/sms.manager.ts
- libs/shared/otp/src/lib/otp.ts
- We want to be able to setup a new phone number
- Creates a recovery phone service
- Stubs out storeUnconfirmed in RecoveryPhoneManager
- Adds config for recovery phone service
- Adds tests for recovery phone service
- Adds new error type RecoveryNumberNotSupportedError
Closes: FXA-10347
Waiting on blocker to land, put a stub in place for now.
> task(recovery-phone): Create new phone number setup method

- packages/functional-tests/pages/resetPassword.ts
- packages/functional-tests/pages/signinRecoveryCode.ts
- packages/functional-tests/pages/signinTotpCode.ts
- packages/fxa-settings/src/components/HeadingPrimary/index.stories.tsx
- packages/fxa-settings/src/components/HeadingPrimary/index.tsx
- packages/fxa-settings/src/components/InlineRecoveryKeySetupCreate/index.tsx
- packages/fxa-settings/src/pages/InlineRecoveryKeySetup/index.tsx
- packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx
- packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx
- packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.tsx
- packages/fxa-settings/src/pages/ResetPassword/ConfirmTotpResetPassword/en.ftl
- packages/fxa-settings/src/pages/ResetPassword/ConfirmTotpResetPassword/index.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/ConfirmTotpResetPassword/index.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPassword/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/en.ftl
- packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/en.ftl
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.tsx
Because:
* We are prepping for SMS work and want to make some small UX improvements
This commit:
* Creates HeadingPrimary for our grey h1 text at the top of our flows that we are moving towards
* Updates copy and styling for 2FA signin and reset password
closes FXA-10210
---
See UX channel, there's a slight variance to what's in the ticket, Figma, and what's here, but this should be what's discussed in thread, and I will add notes on that other ticket mentioned with follow ups:
> feat(ux): Update 2fa signin screens/reset PW copy, create HeadingPrimary

- apps/payments/next/.env.development
- apps/payments/next/.env.production
- apps/payments/next/app/[locale]/[offeringId]/checkout/[interval]/[cartId]/start/page.tsx
- apps/payments/next/auth.ts
- apps/payments/next/config/index.ts
- libs/payments/ui/src/index.ts
- libs/payments/ui/src/lib/client/components/SignInForm/index.tsx
- libs/payments/ui/src/lib/utils/buildRedirectUrl.ts
- package.json
- packages/fxa-auth-server/config/dev.json
- yarn.lock
- On the checkout page, after populating the email clicking continue should navigate the user to the FxA signin page for signin.
- On the checkout page, when clicking Google/Apple button, it should start the third party auth via FxA.
- Completion of either signin option should navigate the user back to the checkout page in a signed in state.
- Updated Auth.js provider to support email, google and apple login
- Customers are redirected to the '/new' page on successful login, which creates a new cart with the customers uid added.
- Updates Payments Next auth config to a non-public client.
Closes: #FXA-10548
- For local setup for third party providers, see the [Ecosystem Docs …
> feat(next): add email, google, apple sign in

- libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- We want to able to confirm a user's setup code
- Adds a method called confirmCode to the recovery-phone service
- Register the phone number to the account in the event the code provided is valid.
Closes: FXA-10348
> task(recovery-phone): Add confirmCode method

- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/customer/src/lib/error.ts
- libs/payments/customer/src/lib/invoice.manager.spec.ts
- libs/payments/customer/src/lib/invoice.manager.ts
- libs/payments/customer/src/lib/types.ts
- libs/payments/customer/src/lib/util/stripeInvoiceToFirstInvoicePreviewDTO.ts
- libs/payments/paypal/src/index.ts
- libs/payments/paypal/src/lib/factories.ts
- libs/payments/paypal/src/lib/paypal.client.spec.ts
- libs/payments/paypal/src/lib/paypal.client.ts
- libs/payments/paypal/src/lib/paypal.error.spec.ts
- libs/payments/paypal/src/lib/paypal.error.ts
- libs/payments/paypal/src/lib/paypal.types.ts
- libs/payments/paypal/src/lib/paypalBillingAgreement.spec.ts
- libs/payments/paypal/src/lib/util/getPayPalAmountStringFromAmountInCents.spec.ts
- libs/payments/paypal/src/lib/util/getPayPalAmountStringFromAmountInCents.ts
- libs/payments/stripe/src/lib/stripe.client.ts
- libs/payments/ui/src/lib/client/components/CartPoller/index.tsx
- packages/fxa-admin-server/tsconfig.build.json
- We need to be able to process nonzero PayPal invoices
- Brings in functionality from SP2.5 to allow users to pay for their subscriptions with PayPal
Closes: [# FXA-10189](https://mozilla-hub.atlassian.net/browse/FXA-10189)
> setup paypal processnonzeroinvoice

- libs/shared/cms/src/lib/strapi.client.ts
- packages/fxa-auth-server/bin/key_server.js
- We want to spread out any flood of cache resets (unlikely since servers take varying amounts of time to spin up, but possible)
- We want to wait on a pending cachable request between reset periods, simply due to the sheer number of requests that could go through in the interval during a cache reset period.
- We want to enable Strapi in "shadow mode" to log potential mismatches
- Adds a random spread to cache reset interval
- Waits on pending cachable requests
- Enables Strapi in key_server if config is present
> feat(auth): fixes for Strapi

- packages/fxa-react/components/AppErrorBoundary/index.tsx
- packages/fxa-settings/src/components/Settings/index.tsx
* We want to measure how often users see this screen from an error on retrieving initial settings state, and compare with AppErrorBoundary
* Add Sentry capture exception, add tags for source
> feat(settings): Add sentry capture for AppErrorDialog

- packages/fxa-customs-server/lib/actions.js
- packages/fxa-customs-server/lib/config/config.js
- packages/fxa-customs-server/test/remote/user_defined_rules.js
- We've seen an increase in 'unblock sign in' page views, which led to investigating the customs config.
- If a key stretching upgrade occurs, we will trigger a `getCredentialsStatus`, `passwordChange` & `accountLogin` action.
- Therefore we potentially have 3x the number actions during an upgrade scenario.
- Moves the `getCredentialStatus` action into the `ACCOUNT_STATUS_ACTION` set, which more correctly fits the nature of this action.
- The default for `maxAccountStatusCheck` has been increased, because key stretching changes need a bit more overhead for these types of actions.
Closes: FXA-10777
> task(customs): Alter customs rules for getCredentialStatus action

- packages/fxa-content-server/app/scripts/lib/router.js
- packages/fxa-content-server/server/config/local.json-dist
- packages/fxa-settings/src/lib/integrations/integration-factory-flags.ts
- packages/fxa-settings/src/lib/integrations/integration-factory.ts
- packages/fxa-settings/src/lib/integrations/interfaces/integration-flags.ts
- packages/fxa-settings/src/lib/model-data/data-stores/url-query-data.ts
- packages/fxa-settings/src/models/Account.ts
- packages/fxa-settings/src/models/integrations/base-integration.ts
- packages/fxa-settings/src/models/integrations/index.ts
- packages/fxa-settings/src/models/integrations/third-party-auth-callback-integration.test.ts
- packages/fxa-settings/src/models/integrations/third-party-auth-callback-integration.ts
- packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.test.tsx
- packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.tsx
- packages/fxa-settings/src/pages/Signin/index.tsx
- We want our users to not have to bounce back and forth React pages and Backbone pages when doing a third party auth login
- Updates the existing `ThirdPartyAuthCallback` to make it functional
I would like to land this part to unblock https://github.com/mozilla/fxa/pull/18044. This page still needs to have support for 2FA prompt and metrics, but can do that in a follow up.
> Update ThirdPartyAuthCallback React page, enable the flow

- packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.tsx
- After navigating back to the AccountRecoveryConfirmKey page from the complete_reset_password reset page, the recovery key hint would be missing.
- Makes sure the recoveryKeyHint is set in location state
Closes: FXA-10728
https://github.com/user-attachments/assets/fc1131fa-42b4-44de-99cd-e54916e2253f
Tests were not added. It's actually a navigation issue so unit tests aren't applicable and it seems overkill to add a functional test for this bug.
> bug(settings): Hint disappears after navigating back to page

- packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.tsx
- We would get prompted to login again if the cache was not set
- Updates the signed in state in apollo cache if the user verifies a totp code
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10751
Found this while working through https://github.com/mozilla/fxa/pull/18057. I think it makes sense to pull into a different PR since it fixes https://mozilla-hub.atlassian.net/browse/FXA-10751. We should consider uplifting it.
Testing steps: 
1. Login with third party auth, enable 2FA, log out
2. Login with localhost:3030, click third party auth, enter creds
You should be taken directly to settings after.
> fix(react): Update apollo cache after doing a successful totp code verify

- packages/fxa-settings/src/lib/integrations/integration-factory-flags.ts
- packages/fxa-settings/src/models/integrations/third-party-auth-callback-integration.ts
- packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.test.tsx
- packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.tsx
- I did't get to address all the code review comments in https://github.com/mozilla/fxa/pull/18053
- Adds review feedback
- Does not use `linkedAccount` data ref, the value does not appear to keep the state on rerender, instead uses the user from the linked account login route
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10812
> feat(react): Tweaks for Third party auth in React

- libs/accounts/recovery-phone/src/lib/recovery-phone.manager.in.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.manager.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- We need to be able to remove a recovery phone number
- Adds `removePhoneNumber`, which throws error if nothing was removed
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10349
> feat(phone): Add `removePhoneNumber` to RecoveryPhoneService

- packages/fxa-settings/src/lib/integrations/integration-factory-flags.ts
- packages/fxa-settings/src/models/integrations/third-party-auth-callback-integration.test.ts
- packages/fxa-settings/src/models/integrations/third-party-auth-callback-integration.ts
- packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.test.tsx
- packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.tsx
- The user could be stuck in a loading spinner if they canceled third party auth login
- Checks for the error param and redirects back to login page if found
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10818
> fix(react): Handle case where user cancels third party auth login

- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.test.tsx
- packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.tsx
Because:
* Users should be redirected back to SubPlat if they started in a SubPlat flow when signing in through 3rd party auth
This commit:
* Checks the redirectTo with our useWebRedirect hook and passes this into handleNavigation accordingly
fixes FXA-10822
> fix(react): Redirect back to SubPlat during 3rd party auth

- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/lib/routes/recovery-codes.js
- packages/fxa-auth-server/test/client/api.js
- packages/fxa-auth-server/test/client/index.js
- packages/fxa-auth-server/test/local/routes/recovery-codes.js
- packages/fxa-auth-server/test/mocks.js
- packages/fxa-auth-server/test/remote/recovery_code_tests.js
- packages/fxa-customs-server/lib/actions.js
- packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
- packages/fxa-graphql-api/src/gql/account.resolver.ts
- packages/fxa-graphql-api/src/gql/model/account.ts
- packages/fxa-graphql-api/src/gql/model/backupCodes.ts
- packages/fxa-settings/src/components/Settings/UnitRowTwoStepAuth/index.tsx
- packages/fxa-settings/src/lib/interfaces.ts
- packages/fxa-settings/src/models/Account.ts
- packages/fxa-settings/src/models/contexts/AppContext.ts
- packages/fxa-settings/src/models/contexts/SettingsContext.ts
* We want to hook up the BackupCodeManager to the front end
* Add new /recoveryCodes/exists route
* Add new handler method that uses the BackupCodeManager to retrieve the count of remaining codes
* Add backup codes to account resolver
* Update fxa-settings account model to include backup codes count
Closes: #FXA-10231
> feat(2fa): Add /recoveryCodes/exists endpoint

- packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.test.tsx
- packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.tsx
- We want the user to continue the flow they started
- Keeps the original query params so the user can continue and oauth or sync flow
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10824
> fix(auth): One third party auth error, keep the query params on redirect

- libs/shared/metrics/glean/src/index.ts
- libs/shared/metrics/glean/src/lib/metrics.context.spec.ts
- libs/shared/metrics/glean/src/lib/metrics.context.ts
- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/lib/metrics/glean/index.ts
- packages/fxa-settings/package.json
- packages/fxa-settings/src/lib/metrics.test.ts
- packages/fxa-settings/src/lib/metrics.ts
- packages/fxa-settings/src/models/Account.ts
- packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/interfaces.ts
- packages/fxa-settings/src/pages/Signin/container.tsx
- packages/fxa-settings/src/pages/Signup/interfaces.ts
- tsconfig.base.json
- Some back end events seemed to disappear
- This is due to the entry point not being defined on the event
- Fixes missing entrypoint glean data
- Ensures entrypoint is sent in graphql requests if it is present in URL
- Fixes typo in utm parameter. `utmContext` should have been `utmContent`.
- Puts the `MetricContext` model in a shared place to reduce the chance this happens again.
> bug(settings): Backend events for login_reg and login_complete have gone missing

- packages/fxa-settings/src/models/integrations/oauth-native-integration.ts
Because:
* Thunderbird is using web channels and is using the OAuthNative integration. However we have some conditional checks around isDesktopClient that's currently causing a web redirect.
This commit:
* Temporarily adds Thunderbird's client ID to the isFirefoxDesktopClient check to unblock them, with follow up filed to do this check in a more ideal way
---
Putting this up for consideration.
> fix(thunderbird): Add band-aid to unblock Thunderbird

- packages/fxa-settings/src/lib/hooks/useWebRedirect/index.tsx
- packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.test.tsx
- packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninPushCode/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/container.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/mocks.tsx
- packages/fxa-settings/src/pages/Signin/index.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/container.test.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.test.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx
* redirectTo provided by subscriptions page was not handled on the signin unblock page, so users were bumped out of the subscription flow
* Handle and check redirectTo param on the signin unblock page
* Add unit test
* If provided redirectTo is invalid, navigate to settings with an error message (do not entirely interrupt navigation)
Closes: #FXA-10747
> fix(settings): Handle redirectTo from signin unblock

- libs/shared/cms/src/lib/strapi.client.ts
- We have some strange behavior going on with Strapi cache.
- We're unsure what the issue is, but this is a diff between our previous successful deploy and deploys that have had high route latency
- Rolls back some cache changes.
> fix(auth): disable strapi cache changes

- packages/functional-tests/tests/key-stretching-v2/signinBlocked.spec.ts
- packages/functional-tests/tests/key-stretching-v2/totp.spec.ts
- packages/fxa-settings/src/lib/gql-key-stretch-upgrade.ts
- packages/fxa-settings/src/lib/sensitive-data-client.ts
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/container.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/container.tsx
- packages/fxa-settings/src/pages/Signin/container.test.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
- packages/fxa-settings/src/pages/Signin/interfaces.ts
- packages/fxa-settings/src/pages/Signin/mocks.tsx
- Users that were required to enter a secondary code weren't getting upgraded.
- Upgrades key stretching when in unblock code flow
- Upgrades key stretching when in totp flow
- Breaks out gql-key-stretch-upgrade module for code reuse
- Won't attempt an upgrade when a session is unverified
- Changes the order operations for upgrade. Previously we always upgraded before login, now we upgrade after, which allows to determine when the session has become verified.
Closes: FXA-10804
> bug(settings): Allow totp or unblock codes to conduct key stretch upgrade

- packages/fxa-content-server/app/scripts/templates/pair/index.mustache
* 2 strings on the pair choice page were not exposed for l10n
* Add tags for translation
Closes: #FXA-10845
> task(content): Expose two strings for translation

- apps/payments/next/auth.ts
- SP3 needs access to the users email, profile picture, and display name in order to render up-to-date UIs
- Adds the fields to the userinfo auth context object, which is then set on the jwt
Closes: [FXA-7599](https://mozilla-hub.atlassian.net/browse/FXA-7599)
[FXA-7599]: https://mozilla-hub.atlassian.net/browse/FXA-7599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add name, email, and image to next jwt

- packages/fxa-admin-server/src/newsletters/basket.service.ts
Basket is migrating APIs. FxA uses basket's user lookup API to get basket tokens. This API works identically to the prior API, just the behind the scenes has changed.
> task(basket): Update user lookup API

- packages/fxa-dev-launcher/profile.mjs
- We don't typically need this enabled. Our pages are stable enough that we don't require use to validate it daily.
- Disables password autofill in Firefox with `signon.rememberSignons`.
Closes: FXA-10846
n/a
> chore(dev-launcher): Disable password autofill for developer testing

- packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.tsx
- Looks like the service value was not being sent in the linked account login endpoint, Glean uses this value to filter out events in the backend
- Grabs the original service/clientId and passes it along the request
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10851
We would want to get this on a point release to production
> fix(metrics): pass the `service` value to the linked account login endpoint

- packages/fxa-auth-server/lib/account-delete.ts
- packages/fxa-auth-server/lib/devices.js
- packages/fxa-auth-server/lib/google-maps-services.ts
- packages/fxa-auth-server/lib/log.js
- packages/fxa-auth-server/lib/payments/capability.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/emails.js
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/lib/sentry.js
- packages/fxa-auth-server/test/local/google-maps-services.js
- packages/fxa-auth-server/test/local/log.js
- packages/fxa-auth-server/test/local/payments/capability.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- Sentry events were being filtered out by the packages/fxa-auth-server/lib/monitoring.js:`filterSentryEvent` method
- Adds a new method, `reportSentryMessage`, to the auth server sentry module, modeled after the `reportSentryError` method.
- Converts all explicit calls to `Sentry.captureException` and `Sentry.captureMessage` within the auth server to their respective `report` methods. 
Closes: [FXA-10717](https://mozilla-hub.atlassian.net/browse/FXA-10717)
The assumption here is that every case where sentry is explicitly told to capture a message or exception is a case where these calls should not be filtered out.
[FXA-10717]: https://mozilla-hub.atlassian.net/browse/FXA-10717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> fix(auth-server): sentry filtering events unexpectedly

- libs/payments/legacy/src/lib/stripe-mapper.config.ts
- libs/payments/legacy/src/lib/stripe-mapper.service.spec.ts
- libs/payments/legacy/src/lib/stripe-mapper.service.ts
- libs/payments/legacy/src/lib/utils/cacheKeyForMap.spec.ts
- libs/payments/legacy/src/lib/utils/cacheKeyForMap.ts
- libs/shared/cms/src/lib/product-configuration.manager.spec.ts
- libs/shared/cms/src/lib/product-configuration.manager.ts
- packages/fxa-admin-server/src/subscriptions/stripe.service.ts
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-shared/payments/stripe.ts
- The operation mapping Strapi data to Stripe metadata is too expensive for a method that is expected to be fast.
- Adds a memory cache decorator to the legacy mapper function.
Closes: #FXA-10852
> fix(auth): add cache to legacy mapper

- packages/fxa-settings/src/components/Settings/PageChangePassword/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageChangePassword/index.tsx
- packages/fxa-settings/src/components/Settings/PageCreatePassword/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageCreatePassword/index.tsx
- packages/fxa-settings/src/lib/auth-errors/auth-errors.ts
- packages/fxa-settings/src/lib/auth-errors/en.ftl
* "Can not create password, password already set" error was not localized, and therefore replaced with "Unexpected error" in UI
* After setting a password on create_password, was not navigated back to settings
* On error with changing the password, the error shown was always "incorrect password", no matter the actual error (e.g., throttling)
* Add l10n for auth error 206
* Update navigation on create_password to ensure it correctly navigates to settings (and doesn't redirect to change password) after successfully setting a password without request to unlink account
* Validate that no regression for showing the unlink account modal after creating a password, when the initial user request was to unlink a third party account
* Update error handling on change_password to show the relevant …
> fix(settings): Add missing error l10n and fix bugs with password create/change

- libs/accounts/recovery-phone/src/lib/recovery-phone.manager.in.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.manager.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.repository.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.config.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/config/index.ts
- We want to check to see if a user can setup a recovery phone
- Adds the `available` method to RecoveryPhoneService
- Adds `hasRecoveryCodes` method to RecoveryPhoneManager
- Adds supporting tests
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10444
> feat(phone): Add method `available` to RecoveryPhoneService

- packages/functional-tests/tests/key-stretching-v2/signInTokenCode.spec.ts
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/interfaces.ts
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/mocks.tsx
- We already landed a PR for 10804 that does this for totp and unblock codes. In that review, another place where this could be done was spotted.
- We didn't want to block a release, so this is being done as a fast follow.
- Adds the ability to upgrade key stretching after providing a signin token code
- Adds functional tests to validate the upgrade.
Closes: 
> task(FXA-10804): Fast-follow apply upgrade process to signin token code

- packages/fxa-settings/src/lib/auth-errors/en.ftl
- packages/fxa-settings/src/lib/error-utils.ts
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/en.ftl
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.stories.tsx
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/mocks.tsx
* Entering an alphanumeric code returned an unexpected error instead of invalid code
* Switch from FormVerifyCode to FormVerifyTotp component
* Add some missing l10n
* Update stories and tests
Closes: #FXA-10072
> fix(settings): Handle invalid code format on 2FA verification

- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
- We want to be able to query whether or not a user can setup recovery phone
- Adds endpoint `/available` endpoint
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10359
@dschom Tagging you for review. If looks good please merge since I'll be out!
> feat(phone): Add `available` endpoint for checking for recovery phone

- apps/payments/next/app/_lib/scripts/create-payments-next.ts
- apps/payments/next/project.json
- `payments-next` reuses many of the localization strings currently in use by `fxa-payments-server`. The strings being reused can by identified by the `next-` prefix of the ftl id.
- Adds a script to copy reused ids along with the localized string, into the new `payments-next.ftl` file.
- The script also generates a report.txt detailing what ids were missing translations, if any.
Closes: #FXA-7840
This script can be tested with the following command.
```
nx l10n-create payments-next
```
> feat(l10n): copy current l10n to payments-next.ftl

- libs/shared/cms/src/lib/product-configuration.manager.spec.ts
- libs/shared/cms/src/lib/product-configuration.manager.ts
- libs/shared/cms/src/lib/strapi.client.ts
- We want to see the cache type for Strapi cache requests in statsd
- Logs cache type to statsd
> fix(strapi): log cache type to statsd

- packages/fxa-react/lib/hooks.tsx
Because:
* If users navigate away, document.body might not be defined
This commit:
* Adds an optional '?' chain since 'body' might not exist
fixes FXA-10874
> fix(react): Ensure document.body is defined before removing event listener

- _scripts/ports.txt
- We run the syncstorage-rs on 8000 (fixed in https://github.com/mozilla/fxa/pull/17447) instead of 5000 because it's a port used by a system service on MacOS. Our check-ports script wasn't updated to reflect this when that patch landed.
- Updates the ports.txt list based on the `docker-compose.yaml` and `sync-for-fxa/Dockerfile`.
Closes: FXA-9745
n/a
n/a
> chore(dev): Update sync server in check-ports to 8000

- apps/payments/next/.env
- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/start/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/landing/route.ts
- apps/payments/next/app/[locale]/[offeringId]/[interval]/new/route.ts
- apps/payments/next/app/[locale]/error/auth/signin/page.tsx
- apps/payments/next/config/index.ts
- libs/payments/ui/src/lib/utils/types.ts
- libs/payments/ui/src/server.ts
- On hosted environments the landing page redirects to internal localhost domain instead of the external domain.
- Do not use Next.js request.nextUrl to determine the URL domain for redirects.
- Builds the redirect using config.paymentsNextHostedUrl to determine the domain.
- Rename BASE_URL to PAYMENTS_NEXT_HOSTED_URL
Closes: #FXA-10817
> fix(next): landing page redirects to internal ip

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/start/page.tsx
- libs/payments/ui/src/lib/client/components/CheckoutCheckbox/index.tsx
- libs/payments/ui/src/lib/client/components/CheckoutForm/index.tsx
- package.json
- yarn.lock
- Customers should not be able to enter payment information until they have created or signed into their FxA account
- Adds disabled state to CheckoutCheckbox component
- Adds disabled state to section 2 headers
- Disable CheckoutCheckbox and section 2 headers if current cart does not have an FxA account
Closes: #FXA-10748
Co-authored-by: Lisa Chan <lchan@mozilla.com>
> feat(next): disable payment method without account

- .circleci/config.yml
- Chromium tests have been failing in Nightly, and there is limited capacity to address the failures.
- Removes the tests from nightly to be re-evaluated in 2025
Relates To: #FXA-10806
> chore(circleci): remove playwright-functional-tests-chromium from the nightly build

- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/lib/routes/subscriptions/utils.ts
- packages/fxa-auth-server/lib/types.ts
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
- packages/fxa-auth-server/test/remote/recovery_phone_tests.js
- We want to provide access to recovery phones that exist and have been confirmed.
- Adds a new end point that checks for the recovery phone
- If session is verified, the response from RecoveryPhoneServices.hasConfirmed is returned.
Closes: FXA-10380
> task(auth): Add GET /recovery-phone

- docs/adr/0044-use-rest-over-gql-when-convenient.md
Because:
* This conversation has been ongoing for a while and given the mixed state of GQL and auth-client in FXA we want to document pros/cons of our options and what we want to do moving forward
This commit:
* Adds the ADR for this decision
closes FXA-10893
> chore(adr): Use REST/auth-client over GQL when convenient in FxA

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/routes/index.js
- packages/fxa-auth-server/lib/routes/totp.js
- We want to be able to distinguish the environment that generated the totp entries
- Append the environment name to the service provided to `authenticator.keyuri`
Closes: FXA-10834
> task(auth): Add environment to totp service name

- packages/fxa-content-server/app/scripts/views/index.js
- packages/fxa-content-server/app/scripts/views/mixins/relay-client-mixin.js
- packages/fxa-content-server/app/tests/spec/views/index.js
- packages/fxa-settings/src/components/TermsPrivacyAgreement/index.stories.tsx
- packages/fxa-settings/src/components/TermsPrivacyAgreement/index.tsx
- packages/fxa-settings/src/lib/types.ts
- packages/fxa-settings/src/models/integrations/client-matching.ts
- packages/fxa-settings/src/pages/Index/index.tsx
- packages/fxa-settings/src/pages/Signin/index.tsx
- packages/fxa-settings/src/pages/Signup/index.tsx
Because:
* We should display these ToS/PP when users are signing up for Relay
This commit:
* Adds logic to account for this in content-server for email-first, and React for signin/signup
closes FXA-10819
> feat(RP): Display subscription ToS/PP when client is Relay

- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/customer/src/lib/invoice.manager.ts
- libs/payments/customer/src/lib/util/stripeInvoiceToFirstInvoicePreviewDTO.spec.ts
- libs/payments/customer/src/lib/util/stripeInvoiceToFirstInvoicePreviewDTO.ts
- libs/payments/ui/src/lib/server/components/PriceInterval/index.tsx
- List amount should not include exclusive tax.
- Changes list amount to invoice.subtotal in DTO, to support inclusive and exclusive tax amounts.
- Adds currency to invoice preview
- Explicitly set a default currency to USD as a temporary solution.
Closes: #FXA-10899
> fix(next): display correct list amount

- packages/fxa-auth-server/lib/routes/totp.js
Because:
- a *.js cannot require() an aliased path intended for *.ts
This commit:
- updates the path to a relative path
> fix(build): fix require() of ts path alias in *.js

- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
- packages/fxa-auth-server/test/remote/recovery_phone_tests.js
- packages/fxa-customs-server/lib/actions.js
- We want to prevent excessive requests to certain end points
- Adds customs checks to 
- `/recovery-phone/available`
- `/recovery-phone/confirm`
- `/recovery-phone/create`
Closes: FXA-10361
I wanted to add some integrations tests but ran into some problems enabling customs in the tests. Hopefully I'll have this addressed in FXA-10913. Also, initially I started patterning this more like [#16948](https://github.com/mozilla/fxa/pull/16948), but realized we already had rules in place for SMS that could be reused.
> task(auth): Setup up customs for recovery phone operations

- libs/accounts/recovery-phone/src/lib/recovery-phone.manager.in.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.manager.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- libs/accounts/recovery-phone/src/lib/sms.manager.ts
- Lookup data has extra info that could be helpful down the road. e.g Info about sim swapping.
- Calls the Twilio API to get lookup data
- Stores data in DB
Closes: FXA-10727
> task(recovery-phone): Add lookup data to registered numbers

- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/emails.js
- packages/fxa-auth-server/lib/routes/index.js
- packages/fxa-auth-server/lib/routes/linked-accounts.ts
- packages/fxa-auth-server/lib/routes/password.ts
- packages/fxa-auth-server/lib/routes/session.js
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/lib/routes/utils/otp.js
- packages/fxa-auth-server/lib/routes/utils/signin.js
- packages/fxa-auth-server/test/local/routes/emails.js
- packages/fxa-auth-server/test/local/routes/session.js
- packages/fxa-auth-server/test/local/routes/totp.js
- packages/fxa-auth-server/test/local/routes/utils/signin.js
- packages/fxa-auth-server/test/mocks.js
- We want to see how timing data is distributed with our totp checks
- Adds a histogram statsd metric for each route that uses totp codes
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10932
This does not fix the issue but will hopefully give us enough insight to make a next step. I bele
> fix(totp): Add statsd metrics for totp 'checkDelta'

- packages/fxa-auth-server/scripts/clean-up-partial-account-customer.ts
- packages/fxa-auth-server/scripts/cleanup-partial-firestore-customers.ts
- packages/fxa-auth-server/scripts/delete-inactive-accounts/enqueue-inactive-account-deletions.ts
- packages/fxa-auth-server/scripts/delete-inactive-accounts/get-inactive-account-uids.ts
- packages/fxa-auth-server/scripts/delete-inactive-accounts/lib.ts
- packages/fxa-auth-server/scripts/delete-unverified-accounts.ts
- packages/fxa-auth-server/scripts/lib/args.ts
- packages/fxa-auth-server/scripts/refund-unverified-accounts.ts
- packages/fxa-auth-server/scripts/stripe-products-and-plans-to-firestore-documents.ts
- packages/fxa-auth-server/test/scripts/delete-inactive-accounts/enqueue-inactive-account-deletions.ts
Because:
- we want to allow RPs to exclude accounts from deletion by providing a list of uids in BigQuery
This commit:
- uses BigQuery in multiple steps
- unions the exclusion lists into a single session-scoped temp table
- saves the MySQL results into a table
- excludes the RP provided uids by joining the MySQL results
- (optionally) saves the inactive account uids into a table
- adds a parameter to make enqueuing emails optional
- adds a parameter to schedule the emails
- updates some Commander argument parsing functions
> feat(scripts): use BigQuery in inactive account deletion script

- packages/fxa-settings/src/components/Settings/DropDownAvatarMenu/en.ftl
- packages/fxa-settings/src/components/Settings/DropDownAvatarMenu/index.tsx
Because:
* Fluent strips at least some characters, and user's display names are allowed to have special characters
This commit:
* Removes the user's display name from the localization string
fixes FXA-10890
> fix(settings): Don't localize user's display name

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/routes/oauth/token.js
- packages/fxa-auth-server/test/oauth/routes/token.js
Because:
- we want to keep the last access time of a session token as up to date as possible
This commit:
- updates a session token's last access time in Redis whenever it is used to create an OAuth token
> feat(tokens): update a session token's last access time more frequently

- libs/payments/metrics/src/lib/glean/glean.manager.ts
- libs/shared/metrics/glean/src/registry/subplat-backend-metrics.yaml
- The uid associated with the firefox account is sensitive user data, and does not need to be collected along with the other metrics that subplat uses.
- Updates the config and glean logic to remove reporting of the fxa uid
Closes: [FXA-10900](https://mozilla-hub.atlassian.net/browse/FXA-10900)
[FXA-10900]: https://mozilla-hub.atlassian.net/browse/FXA-10900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> task(next): Remove FxA user id from subplat glean

- packages/fxa-auth-server/lib/routes/recovery-codes.js
- packages/fxa-customs-server/lib/actions.js
- This endpoint is authenticated with a sessionToken, we don't need to check customs
- This might cause a user to get rate limited unexpectedly
- Remove the customs check
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10880
> fix(customs): Don't call customs on the GET /recoveryCodes/exist endpoint

- packages/fxa-settings/src/components/Settings/FlowSetupRecoveryPhoneSubmitNumber/en.ftl
- packages/fxa-settings/src/components/Settings/FlowSetupRecoveryPhoneSubmitNumber/index.tsx
- Missing brand term and curly apostrophe
- Fix the ftl string and fallback
> fix(l10n): Update ftl string with brand term and fix apostrophe

- packages/fxa-auth-server/lib/payments/capability.ts
- packages/fxa-auth-server/test/local/payments/capability.js
- packages/fxa-shared/payments/stripe.ts
- We no longer want to rate limit our error logging to Sentry since errors are actionable and we don't want to miss them.
- We want to log all error types to BigQuery.
- Disables rate limit for Sentry logging for Strapi mismatches
- Adds logs to BigQuery for all mismatch types
> fix(strapi): log all mismatches to BQ as errors, remove sentry rate limit

- packages/fxa-settings/src/lib/gql-key-stretch-upgrade.ts
- packages/fxa-settings/src/lib/sensitive-data-client.ts
- packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/container.tsx
- packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/container.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninPushCode/container.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/container.test.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
- We want to remove the remaining deprecated usages in the SensitiveDataClient.
- Replaces the last few calls to `setData`/`getData` with `setDataType`/`getDataType`.
Closes: FXA-10849
n/a
n/a
> chore(settings): Move remaining SensitveDataClient calls to new function

- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/customer/project.json
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- libs/shared/error/src/index.ts
- libs/shared/error/src/lib/sanitizeExceptionsDecorator.spec.ts
- libs/shared/error/src/lib/sanitizeExceptionsDecorator.ts
- In instances where the client can call methods "directly" (such as via NextJS Server Actions), we need to ensure that the only data that gets passed through to the user is what is intended. Error propagation is a common way for unexpected data to leak to the user.
- Adds a SanitizeExceptions decorator to libs/shared/error that wraps a class, and captures any errors thrown by its methods. Unless specified, errors are replaced with a generic error message. Original error data is sent to Sentry, along with a data tag to indicate whether it was sanitized or passed through.
Closes: [FXA-10626](https://mozilla-hub.atlassian.net/browse/FXA-10626)
[FXA-10626]: https://mozilla-hub.atlassian.net/browse/FXA-10626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …
> feat(shared): SanitizeExceptions decorator

- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhoneCodeConfirm/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhoneCodeConfirm/en.ftl
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhoneCodeConfirm/index.stories.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhoneCodeConfirm/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhoneCodeConfirm/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhoneCodeConfirm/mocks.tsx
- packages/fxa-settings/src/pages/mocks.tsx
- We want a React page to confirm recovery codes for a recovery phone
- Adds the ConfirmRecoveryCode page
- Adds l10n, unit tests
- Does not add functionality
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10367
> feat(sms): Add confirm recovery code page screens

- libs/shared/l10n/src/lib/branding.ftl
- packages/fxa-auth-server/lib/senders/emails/global.scss
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.scss
- packages/fxa-auth-server/lib/senders/emails/partials/accountDeletionInfoBlock/en.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/accountDeletionInfoBlock/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/accountDeletionInfoBlock/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/partials/accountDeletionInfoBlock/index.txt
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailChangePassword/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailInactiveAccount/en.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailInactiveAccount/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailInactiveAccount/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailInactiveAccount/index.txt
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailNoAction/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailNotAuthorized/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailRecoveryKey/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailResetPassword/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/partials/userDevice/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/partials/userInfo/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/storybook-email.ts
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFirstWarning/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFirstWarning/includes.json
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFirstWarning/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFirstWarning/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFirstWarning/index.txt
* We will be sending out warnings before deleting inactive accounts
* Adds new email template for inactiveAccountFirstWarning including l10n and storybook
* Adds new partials for use in inactive account emails
* Adds stories for automated email partials
* 
Closes: #FXA-10636
> feat(emails): Add inactiveAccountFirstWarning email template + partials

- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/verifyShortCode/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/verifyShortCode/includes.json
- packages/fxa-auth-server/lib/senders/renderer/bindings.ts
- packages/fxa-auth-server/lib/senders/renderer/index.ts
- packages/fxa-auth-server/test/local/senders/emails.ts
* New preheaders will be introduced for the inactive account warning emails
* Email preheaders were not localized
* MJML has a dedicated tag for email previews
* Remove preHeader passed in template values
* Set preview content in email templates instead of handler
* Use MJML mj-preview to set preview text
* Add localization handling for preview text
Closes: #FXA-8558
Maildev does not show previews, which makes it harder to validate this change locally. I have verified that the preview text is included in the email source and hidden from view (as expected for preview text), but this might need to be validated on stage to ensure it works as expected.
> feat(emails): Localize email preheaders

- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/container.tsx
- We can sometimes get into a point where the page is unloaded after a new
recovery key is created. We want to gracefully handle this flow since
the user is already verified.
- We navigate to `/reset_password_confirmed` if we don't have the recovery key anymore in the `SensitiveDataClient`.
Closes: FXA-10869
n/a
Built on top of https://github.com/mozilla/fxa/pull/18136. Will rebase when the prior PR lands.
> fix(settings): Navigate to confirmation if we don't have the recoveryKey

- packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/container.tsx
Because:
* These errors were all coming up as 'Unexpected error'
This commit:
* Passes in the full error object instead of error.error to getLocalizedErrorMessage
fixes FXA-10936
---
This ticket ended up being more of a spike than anything - the person was getting rate limited (more details will be added in ticket). We should be displaying the correct error here though because we were showing "Unexpected error" for all errors and it looked like this is the fix.
There's no container tests here yet unfortunately but I tested this by manually testing and `throw`ing an error object here.
> fix(errors): Display correct error for reset PW submit fail

- packages/functional-tests/tests/subscription-tests/coupons-ui-tests/paymentMode.spec.ts
- The flaky test in question is blocking development of unrelated code.
- Tags the test with `fixme` so involved circleCI builds will pass.
Closes: # FXA-10979
> task(playwright-tests): Mark flaky test with fixme

- packages/fxa-settings/src/components/Settings/FlowSetupRecoveryPhoneConfirmCode/en.ftl
- packages/fxa-settings/src/components/Settings/FlowSetupRecoveryPhoneConfirmCode/index.tsx
- packages/fxa-settings/src/components/Settings/FlowSetupRecoveryPhoneSubmitNumber/en.ftl
- packages/fxa-settings/src/components/Settings/FlowSetupRecoveryPhoneSubmitNumber/index.tsx
- packages/fxa-settings/src/components/Settings/SubRow/en.ftl
- packages/fxa-settings/src/components/Settings/SubRow/index.test.tsx
- packages/fxa-settings/src/components/Settings/SubRow/index.tsx
- packages/fxa-settings/src/components/Settings/UnitRowTwoStepAuth/index.tsx
Because:
* We decided removing 'backup' is clearer for users
This commit:
* Updates references in our codebase from 'backup recovery phone' to 'recovery phone', adds new FTL strings
closes FXA-10949
> fix(sms): Update 'backup recovery phone' strings to 'recovery phone'

- libs/shared/cloud-tasks/src/lib/account-tasks.types.ts
- libs/shared/cloud-tasks/src/lib/cloud-tasks.ts
- libs/shared/cloud-tasks/src/lib/send-email-tasks.spec.ts
- libs/shared/cloud-tasks/src/lib/send-email-tasks.ts
- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/docs/swagger/shared/descriptions.ts
- packages/fxa-auth-server/lib/email-cloud-tasks.ts
- packages/fxa-auth-server/lib/routes/cloud-tasks.ts
- packages/fxa-auth-server/lib/routes/index.js
- packages/fxa-auth-server/scripts/delete-inactive-accounts/enqueue-inactive-account-deletions.ts
- packages/fxa-auth-server/test/local/email-cloud-tasks.js
- packages/fxa-auth-server/test/local/routes/cloud-tasks.js
- packages/fxa-content-server/app/scripts/views/mixins/password-mixin.js
Because:
- we need an endpoint to accept the requests of the inactive account deletion email notification cloud tasks
This commit:
- adds the endpoint and handler
- adds task auto-rescheduling based on a new delivery time option
- refactors/updates some code to rely on the auto-rescheduling feature
> feat(cloud tasks): add route handler for inactive notification cloud tasks

- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/container.tsx
~~⚠️ I'm not really sure, what the right behaviour should be if the email is null.~~
- We want to handle the missing email case and not get this information from the location state.
- Switches to using `currentAccount`.
Closes: FXA-10876
n/a
Built on top of https://github.com/mozilla/fxa/pull/18136. Will rebase when the prior PR lands.
> fix(settings): Get email from account hook instead of location state

- packages/fxa-settings/src/pages/ResetPassword/ResetPassword/index.tsx
`password-reset-start-heading` doesn't exist in any FTL file, noticed in the console.
(Things we would catch earlier if we got l10n testing working 😅)
> fix(l10n): Fix l10n string in JSX not matching FTL

- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/test/client/api.js
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
- packages/fxa-auth-server/test/remote/recovery_phone_tests.js
- packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
- We noticed that endpoint names could be a bit better
- Changes endpoints names. `/recovery-code/*` is now `/recovery_code/*`
- Endpoints solely for sign in operations now have `signin` in the path name.
Closes: FXA-10946
> task(auth): Improve recovery phone endpoint names

- packages/fxa-settings/src/components/Banner/index.stories.tsx
- packages/fxa-settings/src/components/Banner/index.tsx
- packages/fxa-settings/src/components/Banner/interfaces.ts
- packages/fxa-settings/src/components/Settings/PageRecoveryPhoneRemove/en.ftl
- packages/fxa-settings/src/components/Settings/PageRecoveryPhoneRemove/index.stories.tsx
- packages/fxa-settings/src/components/Settings/PageRecoveryPhoneRemove/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageRecoveryPhoneRemove/index.tsx
- packages/fxa-settings/src/models/Account.ts
Because:
* We're buildling out our SMS components
This commit:
* Creates PageRecoveryPhoneRemove for use in settings
* Adds l10n, basic unit tests, and updates stories
closes FXA-10247
---
This does not _precisely_ match Figma because the "info" icon in Figma is closer to the top, but we don't have a banner like that right now from what I can tell? I can update it across the board for Banner types if desired. Similarly, I used our existing `cta-caution` red button for consistency, which is slightly lighter than what I see in Figma.
> feat(settings): Create PageRecoveryPhoneRemove, add l10n/tests/stories

- apps/payments/next/middleware.ts
- The next app uses routing to handle locale indication, but has no rerouting fallback functionality for improper locales.
- Adds functionality to the Next.js middleware to catch incoming requests to next app on routes other than: api|_next/static|_next/image|favicon.ico|__heartbeat__|__lbheartbeat__|__version__
Closes FXA-10440
> feat(next): Redirect next app to default locale for invalid locales

- packages/fxa-auth-server/lib/senders/emails/global.scss
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.scss
- packages/fxa-auth-server/lib/senders/emails/partials/accountDeletionInfoBlock/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFinalWarning/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFinalWarning/includes.json
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFinalWarning/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFinalWarning/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFinalWarning/index.txt
Because:
* We want to send users a third and final email warning about their impending inactive account deletion
This commit:
* Adds the MJML, FTL, plain text, and stories file to complete the template
* Tweaks the grey info box below to better match Figma
closes FXA-10943
---
> feat(email): Add inactiveAccountFinalWarning template, tweak styles

- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFirstWarning/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFirstWarning/includes.json
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountSecondWarning/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountSecondWarning/includes.json
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountSecondWarning/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountSecondWarning/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountSecondWarning/index.txt
- We want to send a 2nd notice that Mozilla account will be delete because of inactivity
- Adds the email template
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10637
> feat(email): Add second warning delete account notice

- libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
- By generating the mask server side we offer better data privacy for unverified sessions.
- Masks the phone number when session is not verified.
Closes: FXA-10947
> task(auth): Add ability to mask recovery phone number

- packages/fxa-auth-server/package.json
- packages/fxa-auth-server/scripts/write-emails-to-disk.js
Because:
* This script is sometimes useful for debugging emails and seeing true link output with UTM params etc.
This commit:
* Restores the script from the commit prior to a3c090, with one tweak on config import
---
This script is [noted in our ecosystem-platform docs here](url), I'm wondering if it was removed accidentally [here](https://github.com/mozilla/fxa/pull/14855/commits/a3c090edc2a95a874d1b294f79f9ef710985b914)? While we don't usually need it, sometimes it's useful for debugging, and I'd like to use it to help me debug why an EJS variable passing to Fluent in plain text isn't working. I'll just rebase on top of this temporarily to debug, but wanted to open this as well.
Looks like a test file for this was also removed that I could potentially restore here too, but when finding …
> feat(auth): Restore write-emails-to-disk script

- apps/payments/next/tailwind.config.ts
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/cart.types.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/customer/src/index.ts
- libs/payments/customer/src/lib/customerSession.manager.spec.ts
- libs/payments/customer/src/lib/customerSession.manager.ts
- libs/payments/stripe/src/index.ts
- libs/payments/stripe/src/lib/factories/customer-session.factory.ts
- libs/payments/stripe/src/lib/stripe.client.ts
- libs/payments/stripe/src/lib/stripe.client.types.ts
- libs/payments/ui/src/lib/actions/checkoutCartWithPaypal.ts
- libs/payments/ui/src/lib/client/components/CheckoutForm/en.ftl
- libs/payments/ui/src/lib/client/components/CheckoutForm/index.tsx
- libs/payments/ui/src/lib/client/components/PaymentSection/index.tsx
- libs/payments/ui/src/lib/client/components/StripeWrapper.tsx
- libs/payments/ui/src/lib/nestapp/app.module.ts
- Adds support for customers with existing payment methods.
- Create Customer Sessions and add it to the Payment Element to support reuse of existing payment method. This only supports non-external payment methods, i.e. PayPal.
- Support existing PayPal payment method.
- If existing Payment Element payment method exists, do not allow PayPal as a payment method.
- If existing PayPal payment method exists, do not allow adding of new Payment Element payment method.
Closes: #FXA-7591
> feat(next): support existing payment methods

- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFinalWarning/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountSecondWarning/en.ftl
Because:
* These were updated in the MJML/txt files but not in the en.ftl files
This commit:
* Corrects the l10n IDs
> fix(l10n): Update incorrect FTL IDs for inactive second/final emails

- packages/fxa-content-server/server/config/local.json-dist
- packages/fxa-content-server/server/lib/beta-settings.js
- packages/fxa-content-server/server/lib/configuration.js
- packages/fxa-settings/src/lib/config.ts
Because:
* We want SMS to be behind a feature flag
This commit:
* Creates two feature flags to support disabling users from adding a new phone while preventing locking them out if they already have a backup phone added
closes FXA-10250
--
SRE side PR: https://github.com/mozilla-it/webservices-infra/pull/3750
> feat(sms): Create 'adding' and 'using' backup phone feature flags

- .circleci/config.yml
- the parallelism was accidentally omitted from the smoke-tests job
- adds it back
> fix(ci): parallelism for smoke-tests job

- .circleci/config.yml
- packages/functional-tests/playwright.config.ts
* the HTML reports aren't widely used
* there are alternative means of viewing results and traces
* creating the HTML reports costs time and money
* removes the creation of HTML reports from CI
* uses an alternative in playwright.config for giving unique names to JUNIT XML reports when using CircleCI parallelism
Closes: #FXA-10807
> chore(ci): remove functional test HTML reports

- packages/fxa-auth-server/lib/payments/capability.ts
- packages/fxa-auth-server/test/local/payments/capability.js
- We want additional logging for stripe/iap mismatch
- Adds stripe and iap subscribed plans to mismatch logs
> fix(capability): add stripe and iap subscribed plans to mismatch logs

- packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.tsx
- The `login_totp_code_trouble_link` was missing.
- Adds the `login_totp_code_trouble_link` metric via a `data-glean-id` on the link.
> bug(settings): Missing login_totp_code_trouble_link metric

- .circleci/config.yml
- packages/functional-tests/package.json
- packages/functional-tests/playwright.config.ts
- packages/functional-tests/tests/misc/recoveryKeyPromoInline.spec.ts
- packages/functional-tests/tests/subscription-tests/support.spec.ts
* The chromium functional tests do not cover a known critical risk or a significant usership sector
* The ETE and FxA teams do not have capacity to finish their implementation or keep them in good health
* The chromium functional tests give false positives, for example tests using Sync pass
* removes the chromium tests from the project
Closes: #FXA-10806
> chore(test): remove chromium functional tests

- packages/fxa-auth-server/config/index.ts
- packages/fxa-graphql-api/src/config.ts
- The env naming was not consistent
- Uses the double underscore notation, where a double underscore indicates a '.' in a json structure.
I've already updated the CI to support this. We should also communicate this change to team members.
> polish(auth,gql): Use double underscore notation for twilio confict config

- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
- packages/fxa-auth-server/test/remote/recovery_phone_tests.js
- packages/fxa-customs-server/lib/actions.js
- packages/fxa-customs-server/lib/config/config.js
- packages/fxa-customs-server/test/remote/too_many_sms.js
- We were reviewing customs rules and deemed this recoveryPhoneAvailable check wasn't necessary.
- We also decided to change the default custom rate limits here.
- Removes the recoveryPhoneAvailable check.
- Removes the action from customs.
- Leaving isTwilioAction, however. We might need it later.
- Changes default config to 9 sms per 24 hour period
- Fixes remote test to be inline with updated customs rate limits
Closes: FXA-11006, FXA-11005
We are leaving `isTwilioAction` and the `TWILIO_ACTION` group set in customs. Pretty sure we will need it at some point soon, but with different actions.
> task(auth): Remove recoveryPhoneAvailable customs check

- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-client/test/crypto.ts
- This fell through the cracks in the backend sms spec. 
- Updates the auth client to be inline with the backend endpoints.
It's a bit unclear where this responsibility lies. Is this a back end task or a front end task? At any rate, this should make `auth-client` one to one with `/recovery_phone/**` endpoints.
> polish(auth-client): Update auth client recovery-phone api

- libs/accounts/recovery-phone/src/lib/recovery-phone.errors.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/test/remote/recovery_phone_tests.js
- We want this config to gate all recovery-phone endpoints
- Adds checks to see if config indicates recovery-phone is enabled.
Closes: FXA-11020
> task(auth): Check recovery-phone enabled config for all endpoints

- packages/fxa-dev-launcher/README.md
- packages/fxa-dev-launcher/profile.mjs
- This is the default flow that we use in desktop today, but we can't remove the old flow until ESR is updated to v140+.
- Changes the default context to use the Firefox browser default OAuth flow.
Closes: Fixes FXA-9872
n/a
> **From [this comment in JIRA](https://mozilla-hub.atlassian.net/browse/FXA-9872?focusedCommentId=917774):**
> Following up on  https://github.com/mozilla/fxa/pull/17274, we might want to take this opportunity to clean up the profile for dev-launcher. A lot of the custom configuration might not be needed anymore with the addition of the autoConfig setting.
We still need to support the older flow until the next ESR version ([v140](https://whattrainisitnow.com/release/?version=140)), so I don't recommend removing or cleaning up the …
> chore(dev-launcher) - Change the default context to oauth_webchannel_v1

- apps/payments/next/.env
- apps/payments/next/app/[locale]/[offeringId]/[interval]/landing/route.ts
- apps/payments/next/config/index.ts
- libs/payments/legacy/src/index.ts
- libs/payments/legacy/src/lib/factories.ts
- libs/payments/legacy/src/lib/sp2map.config.ts
- libs/payments/legacy/src/lib/utils/getSP2Params.spec.ts
- libs/payments/legacy/src/lib/utils/getSP2Params.ts
- libs/payments/ui/src/lib/actions/determineCurrency.ts
- libs/payments/ui/src/lib/actions/index.ts
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- libs/payments/ui/src/lib/nestapp/validators/DetermineCurrencyActionArgs.ts
- The payments-next landing page needs to be able to map SP3 parameters to SP2 product and price IDs.
- Adds new mapper function to map offeringId+interval+currency to productId+priceId.
- Adds config to provide correct values to mapping function
Closes: #FXA-10967
> feat(next): add mapper function for sp3 to sp2 conversion

- apps/payments/next/.env
- apps/payments/next/app/[locale]/[offeringId]/[interval]/landing/route.ts
- apps/payments/next/config/index.ts
- libs/payments/legacy/src/index.ts
- libs/payments/legacy/src/lib/factories.ts
- libs/payments/legacy/src/lib/sp2map.config.ts
- libs/payments/legacy/src/lib/utils/buildSp2RedirectUrl.spec.ts
- libs/payments/legacy/src/lib/utils/buildSp2RedirectUrl.ts
- libs/payments/legacy/src/lib/utils/redirectToSp2.spec.ts
- libs/payments/legacy/src/lib/utils/redirectToSp2.ts
- Landing page needs to redirect to either `payments-server` or `payments-next` depending on configuration per offering.
- Adds SP2 redirect config to `payments-next`.
- Adds a function to determine whether SP3 landing page should redirect to SP2 based on per offeringId percentage configuration.
Closes: #FXA-10968
> feat(next): add percentage based redirects to landing

- packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/container.tsx
- packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/interfaces.ts
Because:
* This text is not being rendered as it should be on this page
This commit:
* Passes the missed prop into CompleteResetPassword from the container component, updates the optional type
fixes FXA-11016
> fix(l10n): Ensure a11y text is displayed on Complete Reset PW page for service=relay

- packages/functional-tests/tests/settings/totpRecoveryCode.spec.ts
- packages/fxa-auth-server/lib/routes/index.js
- packages/fxa-auth-server/lib/routes/recovery-codes.js
- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/emails/templates/postAddRecoveryPhone/index.stories.ts
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
- packages/fxa-auth-server/test/local/senders/emails.ts
- packages/fxa-auth-server/test/mocks.js
- packages/fxa-auth-server/test/remote/recovery_code_tests.js
- packages/fxa-settings/src/components/Settings/Page2faReplaceRecoveryCodes/en.ftl
- packages/fxa-settings/src/components/Settings/Page2faReplaceRecoveryCodes/index.tsx
- packages/fxa-settings/src/components/Settings/PageRecoveryPhoneRemove/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageRecoveryPhoneRemove/index.tsx
* We want to send emails to users to let them know when sms is added, used or removed
* Add email sending to the client methods for adding, removing and using recovery phone to sign in
Closes: #FXA-11027
Filed a new ticket to review the emails sent when backup authentication codes are used for password reset.
> feat(emails): Send out emails for SMS actions

- .circleci/config.yml
- .github/workflows/docker.yml
- We are using GitHub Actions and Google Artifact Registry to build and push production container images
- Pushes the container image to Docker Hub from GitHub Actions
Closes: FXA-10933
> feat(docker): Push to Docker Hub

- packages/fxa-settings/src/components/Settings/PageSettings/en.ftl
- packages/fxa-settings/src/components/Settings/PageSettings/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageSettings/index.tsx
- packages/fxa-settings/src/components/Settings/index.tsx
- packages/fxa-settings/src/components/Settings/interfaces.ts
- packages/fxa-settings/src/components/Settings/mocks.tsx
- packages/fxa-settings/src/lib/glean/index.ts
- packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml
- packages/fxa-shared/metrics/glean/web/accountBanner.ts
- packages/fxa-shared/metrics/glean/web/index.ts
- We want to show a banner when a user signs in after clicking an inactive account reminder email.
- Shows a banner when we receive particular UTM params from clicking links in the inactive account emails.
- Adds metric `account_banner_reactivation_success_view` as custom metric.
Fixes FXA-10983
- Separated the metrics to different commit instead it's preferable to have it linked to another issue or PR.
- For testing, add the UTM params when signing in. e.g. `http://localhost:3030/signin?email=tester%40gmail.com&utm_medium=email&utm_campaign=fx-account-inactive-reminder-third&utm_content=fx-account-deletion`
> feat(settings): Show banner when unverified accounts signin

- packages/fxa-settings/src/pages/Signin/SigninRecoveryChoice/en.ftl
- packages/fxa-settings/src/pages/Signin/SigninRecoveryChoice/index.tsx
- string id was duplicated with different messages
- rename strings to align with component where they are used
> Rename duplicate ftl string in 2FA recovery flow

- packages/fxa-settings/src/components/Settings/SubRow/en.ftl
- packages/fxa-settings/src/components/Settings/SubRow/index.test.tsx
- packages/fxa-settings/src/components/Settings/SubRow/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryChoice/en.ftl
- packages/fxa-settings/src/pages/Signin/SigninRecoveryChoice/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryChoice/index.tsx
Because:
* We are displaying '1 codes remaining' which is improper
This commit:
* Uses a selector in Fluent to handle one + other number of codes remaining, updates fallback text and tests
closes FXA-11048
---
✅ Confirmed with Eduardo the copy for 0, 1, and 2+ codes is correct
✅ Confirmed we never show users "No codes available" on SigninChoice, as they will be redirected to the phone number prompt if set up
🗒️ I didn't update the FTL to handle the "zero" case in Settings because it was already separated out and rendering correctly, and makes it easier for our fallback text to be correct anyway and for us to display the yellow alert icon
> fix(copy): Update fallback text/FTL to handle '1 code remaining'

- packages/fxa-settings/src/pages/Signin/utils.ts
Because:
* This is causing the integration to get recreated in Settings, and we're not currently passing params into Settings, meaning the integration query param data is undefined and the active banner is not shown
This commit:
* Checks that the 'redirectTo' condition in our signin utils does not equal '/settings', to avoid the hard navigate
fixes FXA-11092
> fix(inactives): Don't hard navigate when redirectTo is 'settings'

- packages/functional-tests/tests/settings/recoveryPhone.spec.ts
- packages/fxa-settings/src/components/Settings/Page2faReplaceRecoveryCodes/en.ftl
- packages/fxa-settings/src/components/Settings/PageRecoveryPhoneSetup/en.ftl
- packages/fxa-settings/src/components/Settings/PageRecoveryPhoneSetup/index.tsx
- packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/en.ftl
- packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/en.ftl
* Some string localization was incorrectly matched and not displayed in product
* Fix ftl ids
* Update one string for backup authentication codes to match updated design since no l10n was available for old string
> fix(l10n): Fix mismatched or missing l10n

- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/currency/src/index.ts
- libs/payments/currency/src/lib/currency.manager.ts
- libs/payments/customer/src/lib/invoice.manager.spec.ts
- libs/payments/customer/src/lib/invoice.manager.ts
- libs/payments/paypal/src/lib/factories.ts
- libs/payments/paypal/src/lib/paypal.client.spec.ts
- libs/payments/paypal/src/lib/paypal.client.ts
- libs/payments/paypal/src/lib/paypal.client.types.ts
- libs/payments/paypal/src/lib/paypal.types.ts
- libs/payments/stripe/src/index.ts
- libs/payments/stripe/src/lib/factories/address.factory.ts
- libs/payments/stripe/src/lib/stripe.client.types.ts
- packages/fxa-admin-server/tsconfig.build.json
- packages/fxa-auth-server/lib/payments/paypal/helper.ts
- packages/fxa-auth-server/test/local/payments/paypal.js
- Accounting needs a queriable country code on paypal transactions
- uses the ip-located country when available (or the currency default country when not), and sends that to paypal's `COUNTYCODE` NVP field.
Closes #FXA-10948
> feat(paypal): Send country code with paypal transactions

- packages/fxa-auth-server/config/index.ts
A partial revert of 82b67a4e348090bb3dc3b52d0290d7206f8daf03.
- I looked at the defaults in the now removed [`fxa-email-service`](https://github.com/mozilla/fxa/tree/b033d5f6a96b072bac8bb9b591c811161012df18/packages/fxa-email-service) package to see if there was an equivalent in the `fxa/k8s/fxa/values-prod.yaml` but couldn't find any.
- This patch hasn't been tested.
- We want to revert the `BOUNCES_COMPLAINT` default
- Does that.
Closes: FXA-10962
> fix(auth): update bounce config defaults

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/error/en.ftl
- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/error/page.tsx
- apps/payments/next/config/index.ts
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/cart.utils.ts
- libs/payments/eligibility/src/lib/eligibility.manager.spec.ts
- libs/payments/eligibility/src/lib/eligibility.manager.ts
- libs/payments/eligibility/src/lib/eligibility.service.spec.ts
- libs/payments/eligibility/src/lib/eligibility.service.ts
- libs/payments/ui/src/index.ts
- libs/shared/db/mysql/account/src/lib/kysely-types.ts
- packages/fxa-auth-server/lib/payments/capability.ts
- packages/fxa-auth-server/test/local/payments/capability.js
> feat(payments): Do not allow duplicate subscriptions to the same offering and interval

- libs/accounts/recovery-phone/src/lib/recovery-phone.manager.in.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- libs/shared/db/mysql/account/src/index.ts
- packages/fxa-auth-server/bin/key_server.js
Because:
This Commit:
- We want to let the user know if the number is invalid.
- If the number look fails we probably can't send either.
- Fails fast if the number look fails
- Throws the `PhoneNumberNotSupported` error
- Logs the error, so we can keep tabs on it.
- Injects logger into recovery-phone-service. This might be helpful in general.
- Fixes import in recovery-phone-manager.in.spec.
Closes: FXA-11055
> task(recovery-phone): Handle error retrieveving Twilio lookup

- packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx
* Error banners were not cleared on submit even if error no longer applied (e.g., throttling) and could result in both an (outdated) error banner and an error tooltip being displayed simultaneously
* clear error messages on submit for both SigninTokenCode and ConfirmSignupCode pages
Closes: #FXA-11059
To test, turn on customs (set `customsUrl` in `fxa-auth-server/config/dev.json` to `http://localhost:7000`) and submit wrong codes until throttled during sign up. Clear customs with `redis-commander` then resubmit an incorrect code. Banner should be cleared and only error tooltip shown.
> fix(settings): Clear error messages on submit SigninTokenCode/ConfirmSignupCode

- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/cart.types.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/customer/src/lib/invoice.manager.spec.ts
- libs/payments/customer/src/lib/invoice.manager.ts
- libs/payments/customer/src/lib/types.ts
- libs/payments/eligibility/src/lib/eligibility.manager.spec.ts
- libs/payments/eligibility/src/lib/eligibility.manager.ts
- libs/payments/eligibility/src/lib/eligibility.service.spec.ts
- libs/payments/eligibility/src/lib/eligibility.service.ts
- libs/payments/eligibility/src/lib/eligibility.types.ts
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
-  [x] Updates checkEligibility, when eligibility status is upgrade, to also return the price and the offering config id that the customer is upgrading from
Closes: FXA-11023
> feat(libs): Update libs for subscription upgrades

- libs/accounts/recovery-phone/project.json
- libs/accounts/recovery-phone/src/lib/recovery-phone.manager.in.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.repository.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- libs/accounts/two-factor/project.json
- libs/accounts/two-factor/src/lib/backup-code.manager.in.spec.ts
- libs/accounts/two-factor/src/lib/backup-code.manager.ts
- libs/accounts/two-factor/src/lib/backup-code.repository.ts
- libs/shared/db/mysql/account/src/index.ts
- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/lib/routes/recovery-codes.js
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/test/local/routes/recovery-codes.js
- packages/fxa-auth-server/test/local/routes/totp.js
- tsconfig.base.json
- When a user removes 2fa-totp, we want to also destroy any registered recovery phone.
- When a user removes 2fa-totp, we want to also destroy an existing backup recovery codes (ie 2fa back up codes).
- If recovery phone was registered, removes it during call to /totp/destroy
- If backup codes exist, removes them during call to /totp/destroy
- Adds ability to remove recovery codes to backup-code.manager
- Some cleanup:
- Renames `recovery-phone` to `account-recovery-phone` in `account/recovery-phone/project.json` to be consistent.
- Add tag 'scope:shared:lib' to `account/recovery-phone/project.json`
- Add tag 'scope:shared:lib' to `account/recovery-phone/project.json`
- Removes entry for  `accounts/recovery-phone` in `tsconfig.base.json`, because`@fxa/accounts/recovery-phone` already …
> task(auth): Have totp/destroy remove recovery phone

- libs/shared/mozlog/src/index.ts
- libs/shared/mozlog/src/lib/mozlog.module.ts
- libs/shared/mozlog/src/lib/mozlog.service.spec.ts
- libs/shared/mozlog/src/lib/mozlog.service.ts
- libs/shared/notifier/src/lib/notifier.provider.ts
- libs/shared/sentry/project.json
- packages/fxa-admin-server/src/app.module.ts
- packages/fxa-admin-server/src/auth/user-group-header.guard.spec.ts
- packages/fxa-admin-server/src/auth/user-group-header.guard.ts
- packages/fxa-admin-server/src/database/database.module.ts
- packages/fxa-admin-server/src/database/database.service.spec.ts
- packages/fxa-admin-server/src/database/database.service.ts
- packages/fxa-admin-server/src/event-logging/event-logging.module.ts
- packages/fxa-admin-server/src/event-logging/event-logging.service.ts
- packages/fxa-admin-server/src/gql/account/account.resolver.spec.ts
- packages/fxa-admin-server/src/gql/account/account.resolver.ts
- packages/fxa-admin-server/src/gql/email-bounce/email-bounce.resolver.spec.ts
- packages/fxa-admin-server/src/gql/email-bounce/email-bounce.resolver.ts
- packages/fxa-admin-server/src/gql/gql.module.ts
- packages/fxa-admin-server/src/gql/relying-party/relying-party.resolver.spec.ts
- packages/fxa-admin-server/src/gql/relying-party/relying-party.resolver.ts
- packages/fxa-admin-server/src/mocks.ts
- packages/fxa-admin-server/src/scripts/audit-tokens.spec.ts
- packages/fxa-admin-server/src/subscriptions/appstore.service.ts
- packages/fxa-admin-server/src/subscriptions/playstore.service.ts
- packages/fxa-admin-server/src/subscriptions/stripe.service.ts
- packages/fxa-admin-server/src/subscriptions/subscriptions.module.ts
- packages/fxa-admin-server/src/subscriptions/subscriptions.service.ts
- packages/fxa-shared/guards/AdminPanelGuard.ts
- packages/fxa-shared/guards/Guard.ts
- Some analytics were lost
- A previous refactor broke logging
- Restores mzlog.service.ts to its previous glory
- Fixes wonky injection
- Fixes circular ref in admin-panel gaurds that would sometimes cause esbuild error
- Fixes project.json in libs/shared/sentry to avoid esbuild error
Closes: FXA-10920
Working Example from Train-294
`28|admin-server  | 2025-02-06T15:30:38: {"Timestamp":1738884638766000000,"Logger":"fxa-user-admin-server","Type":"default.admin-panel-events","Severity":6,"Pid":70121,"EnvVersion":"2.0","Fields":{"event":"account-search","search-type":"email","auto-completed":false}}`
Broken Example from train-305. Note "Fields": { "0": "{...}"}. This won't ingest into our logging tables properly.
`28|admin-server  | 2025-02-06T15:06:20: …
> bug(admin-server): Broken logs

- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/customer/src/lib/promotionCode.manager.spec.ts
- libs/payments/customer/src/lib/promotionCode.manager.ts
- libs/payments/ui/src/lib/client/components/SelectTaxLocation/index.tsx
- it currently crashes if currency for coupon and cart do not match
- handles the error when currency for coupon and cart do not match
- customer will see an `The code you entered is invalid.` error message
Closes: FXA-10915
> fix(payments): Coupons - Handle error when currency for coupon and cart do not match

- packages/functional-tests/tests/key-stretching-v2/changePassword.spec.ts
- packages/functional-tests/tests/key-stretching-v2/recoveryKey.spec.ts
- packages/functional-tests/tests/key-stretching-v2/resetPassword.spec.ts
- packages/functional-tests/tests/misc/authClientV2.spec.ts
- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/lib/routes/password.ts
- packages/fxa-auth-server/test/local/routes/password.js
- packages/fxa-auth-server/test/mail_helper.js
- packages/fxa-auth-server/test/mocks.js
- packages/fxa-content-server/app/scripts/lib/fxa-client.js
- packages/fxa-content-server/app/tests/spec/lib/fxa-client.js
- packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
- packages/fxa-graphql-api/src/gql/account.resolver.ts
- packages/fxa-graphql-api/src/gql/dto/input/password-change-start.ts
- packages/fxa-settings/src/lib/gql-key-stretch-upgrade.ts
- packages/fxa-settings/src/models/Account.ts
- packages/fxa-settings/src/pages/Signin/mocks.tsx
- Users and playwright tests might be running into the rate limit in stage and production
- We use the customs.check request (much stricter rate limit) in password change
- This is used in key stretching upgrades, createing recovery key, so could in theory get trigger a lot
- Updates the `/password/change/start` route to optionally use a session token and call `customs.checkAuthenticated`
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11060
@dschom I ended up making the session token optional in the backend, but updated all the front end bits to use session token. This seems like a reasonable approach since it won't require the FxA Python client to ugrade yet. I will file some tickets with what I found while working on this.
> feat(keys): Update key stretching to optionally use session token on password change

- packages/fxa-auth-server/lib/bounces.js
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/index.js
- packages/fxa-auth-server/test/local/bounces.js
- packages/fxa-auth-server/test/local/senders/emails.ts
- We want to increment a statsd metric when we are blocked from sending an email.
- Adds a statsd metric when we throw a bouce check exception.
- This change also includes a change to bounces.js that isn't used in the metrics along with tests because it was part of a footgun that I ran into while working on this patch.
Closes: FXA-10964
> feat(metrics): Add metrics when the bounce check blocks an email

- packages/fxa-settings/src/components/Settings/ConnectedServices/index.test.tsx
- packages/fxa-settings/src/components/Settings/ConnectedServices/index.tsx
- Some users could not disconnect a service if the `client.name` was undefined
- Lodash stores those entries in an `""` keu
- Fixes the issue by using the `""` key if client is undefined
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10330
Thought about removing lodash.groupBy package...but meh. Lodash has a strange behavior when running in the browser and running test.
To test, use a UA agent (FxATester) and login, then disconnect the service.
> fix(settings): Fix bug with disconnecting an "unknown" service

- libs/accounts/recovery-phone/src/lib/recovery-phone.manager.in.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.config.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- libs/accounts/recovery-phone/src/lib/sms.manager.config.ts
- libs/accounts/recovery-phone/src/lib/sms.manager.ts
- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/config/index.ts
- We want to block phone numbers suspected of SMS pumping
- Adds threshold
- Adds configuration to add extra data fields to look up api call
- Adds metrics around sim pumping risk scores and rejections
- Adds statsd to recovery phone service
Closes:FXA-11065
> task(recovery-phone): Add check for sms pumping risk

- libs/accounts/recovery-phone/README.md
- libs/accounts/recovery-phone/src/lib/recovery-phone.manager.in.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- packages/functional-tests/lib/email.ts
- packages/functional-tests/tests/settings/recoveryPhone.spec.ts
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/l10n/index.ts
- packages/fxa-auth-server/lib/l10n/server.ftl
- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/test/client/index.js
- packages/fxa-auth-server/test/local/l10n/index.ts
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
- packages/fxa-auth-server/test/remote/recovery_phone_tests.js
- packages/fxa-graphql-api/src/config.ts
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/en.ftl
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/index.tsx
* We want to include a localized message in addition to the code
* Add ftl strings for localized SMS messages
* Pass strings to sms manager for inclusion in sms
* Add missing import in integration test
* Add tags to accounts libs projects for inclusion in CI integration tests
* Add some more logging
* Split email sending for recovery phone actions into separate try catch with error logging that doesn't crash the main SMS actions
Closes: #FXA-11007
Noticed that the recovery-phone libs tests weren't running on CI and added them + updated instructions in readme to run the tests locally.
> feat(sms): Add localized body text to SMS

- libs/accounts/recovery-phone/src/lib/recovery-phone.manager.in.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- We want to be consistent with how we revoke codes
- Revokes the older unconfirmed codes
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11130
> feat(sms): Revoke old recovery phone codes when sending new code

- packages/fxa-auth-server/package.json
- packages/fxa-auth-server/scripts/copy-assets.sh
- packages/fxa-auth-server/tsconfig.json
- Build finalize was clobbering js output produces by `build-ts` which effectively undid any `tsc-aliases` applied by typescript compilation
- Creates a script for copying assets and not code
- Removes the `build-finalize` script that was clobbering assets
This was an attempt to fix a deploy issue in train-304. Note that previous fix is [here](https://github.com/mozilla/fxa/pull/18365), which would have worked if not for this problem... 
To validate / see why this fix works do the following:
- Check out main
- run `cd packages/fxa-auth-server`
- run `yarn build`
- run `cat dist/packages/fxa-auth-server/lib/routes/totp.js | grep @fxa`
Prior to …
> bug(auth): fix broken @fxa imports

- packages/fxa-auth-server/README.md
- Our readme with test instructions was very outdated
- Updates readme
- Throws in modern examples
> polish(auth): Better readme for testing commands

- packages/functional-tests/lib/sms.ts
- packages/functional-tests/tests/settings/recoveryPhone.spec.ts
- The recovery phone tests need access to redis to get the code
- Disables the test until we have a better solution for peeking at codes for tests
- Cleans up some redis error logging in tests
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11157
> fix(sms): Disable playwright tests for recovery phone for stage/prod

- libs/payments/paypal/src/lib/paypal.client.ts
- libs/payments/paypal/src/lib/paypal.client.types.ts
- packages/fxa-auth-server/lib/payments/paypal/helper.ts
Because:
* The paypal country code logic is required by finance, but is a Map not a POJO, and can't be accessed via bracket notation
This commit:
* Fixes this
Closes #FXA-11174
- [x I have verified that my changes render correctly in RTL (if appropriate).
> fix(paypal): Fix map accessing for paypal country code

- libs/accounts/recovery-phone/src/lib/sms.manager.spec.ts
- libs/accounts/recovery-phone/src/lib/sms.manager.ts
- packages/fxa-auth-server/lib/routes/index.js
- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
- We wanted additional statsd metrics for sms
- Adds statsd metrics
- **Graph for Lookup Phone Number error**
- **Graph for Lookup Phone Number success**
- Potential sim swap
- Potential sim pumping risk
- **Graph for Recovery Phone Added**
- **Graph for Recovery Phone Setup Confirmed**
- **Graph for Recovery Phone SignIn Confirmed**
- **Graph for Recovery Phone Removed**
- Updates our routes to also replace `this.log.info` with statsd
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11128
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11067
Dashboards have been started here https://yardstick.mozilla.org/d/eed2dadjju48wc/fxa-sms?orgId=1&from=now-6h&to=now&timezone=browser
> feat(metrics): Add missing metrics for recovery phone

- libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- We only want to safe guard against calls that might incur costs
- Disabling / enabling of features can be done through UI feature flags
- Removes config.enabled checks in: available, removePhoneNumber, hasConfirmed and stripPhoneNumber
Closes: FXA-11064
> task(recovery-phone): Allow some operations when recovery phone config enabled is false

- packages/fxa-settings/src/components/FormPhoneNumber/index.tsx
- packages/fxa-settings/src/components/InputPhoneNumber/index.tsx
- packages/fxa-settings/src/components/InputPhoneNumber/mocks.tsx
* Typing in phone number input was not working in browsers other than Firefox
* use react-hook-form setValue to update input value with formatted phone number
Closes: #FXA-11163
> fix(settings): Phone number input not working in non-Firefox browsers

- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
Because:
* We are stripping the nationalFormat from Twilio to only return 4 digits, even though the response in question is for a successful recovery phone set up
This commit:
* Returns the full nationalFormat in this case, as the user is logged in and confirmed their code
fixes FXA-11162
fixes FXA-11166
> fix(recovery-phone): Don't strip nationalFormat number after successful setup

- jest.preset.js
We are seeing jest processes being killed  when running jest tests in CI.  It started happening after the increased the nx parallelism level to 2.
> fix(ci): set jest maxWorkers to 1

- packages/fxa-settings/src/components/Settings/SubRow/index.tsx
- We want to inform users about sim swapping risks
- Updates link per bugzilla discussion #1941933
- Note the article has not yet been updated, but should be soon.
Closes: FXA-11164
If for some reason the placeholder link changes, we will need to revisit this. That doesn't seem likely though.
> bug(settings): Missing link to sumo article about sim swap

- libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- libs/accounts/recovery-phone/src/lib/sms.manager.spec.ts
- libs/accounts/recovery-phone/src/lib/sms.manager.ts
- libs/accounts/recovery-phone/src/lib/twilio.config.ts
- libs/accounts/recovery-phone/src/lib/twilio.provider.spec.ts
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/routes/auth-schemes/twilio-signature.ts
- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/lib/routes/session.js
- packages/fxa-auth-server/lib/server.js
- packages/fxa-auth-server/test/local/routes/auth-schemes/twilio-signature.js
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
- We want to monitor sms delivery status
- Adds endpoint for twilio webhook
- Logs info about delivery status
- Records metrics about delivery status
Closes: FXA-11133
We can fully test this once we get it on stage.
> task(recovery-phone): Add support for message status updates

- packages/fxa-settings/src/components/Settings/PageRecoveryPhoneRemove/index.stories.tsx
- packages/fxa-settings/src/components/Settings/PageRecoveryPhoneRemove/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageRecoveryPhoneRemove/index.tsx
- packages/fxa-settings/src/models/Account.ts
* Recovery phone information and removal option are shown for any user that has enabled the service, even if they are not located in a supported location for setup
* After removing the phone number, service availability should be checked to determine if the user should be able to add another phone number
* refresh recovery phone info after removing phone (this will force a geodb check for service availability)
Closes: #FXA-11165
> fix(settings): Refresh recovery phone service availability on delete

- package.json
- packages/functional-tests/lib/sms.ts
- packages/functional-tests/tests/settings/recoveryPhone.spec.ts
- yarn.lock
- We want to run recovery phone tests in local, stage, prod
- Uses real Twilio api key to fetch sms for test numbers when running in stage and prod
- Fallsback to using redis peeking in local/ci tests
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11152
Unfortunately we have to run tests in series when using real keys since we use one phone number and wont be able to tell the codes apart. This means that the tests will take ~5mins in stage/pro vs 30seconds in local. 
We will need to ensure that environment variables are setup in each environmnent.
> fix(tests): Update sms functional tests to run in stage/prod

- packages/fxa-settings/src/components/InputPhoneNumber/index.tsx
- The style is off in Safari
- Fixes the styling in Safari to not show country
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11189
Before:
After:
I didn't test this on mobile but Safari had the same issue on OSX. Since both are webkit it should work.
> fix(bug): Fix phone number input, dont show country name

- packages/123done/static/index.html
- packages/123done/static/js/123done.js
- 123Done Pro needs links to plans for SP3 checkout pages
- Adds links to SP3 checkout for various 123Done Pro plans.
Closes: #FXA-11188
Automatic locale determination to be completed by #18415
> feat(123done): add links for sp3

- packages/fxa-content-server/package.json
- yarn.lock
* Seems unused and not compatible with Node 22
* Remove from content-server dependencies
> cleanup(deps): Remove node-sass

- packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/container.tsx
- The user is redirected back to signin after using recovery phone or code (after third party auth login)
- Sets the apollo cache to signed in and adds a small delay
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11207
I spent a decent amount of time on this because just adding the apollo cache update did not consistenly make this pass. i suspect there is some state management issue between local storage and apollo cache that causes the user to be redirected back to `signin`. Adding a small delay consistently fixed the issue but its meh. I added a commend and think we can address this in the state refactoring.
> fix(sms): Set signed in state to true in apolloClient after using recovery phone and code

- packages/fxa-settings/src/components/Settings/PageRecoveryPhoneSetup/en.ftl
- packages/fxa-settings/src/components/Settings/PageRecoveryPhoneSetup/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageRecoveryPhoneSetup/index.tsx
* Back arrow on step 2 was returning to settings
* Return to step 1
* Add test cases
Closes: #FXA-11178
> fix(settings): Fix back arrow navigation from step 2 of recovery phone setup

- packages/fxa-content-server/app/scripts/lib/nimbus/index.ts
- We send an exception when a client times out from making a request.
- We ignore this request because it could be due to multiple network failures. 
- Note that this is different from `post-nimbus-experiments.js` where we expect Nimbus to return to us within 50ms.
Closes: FXA-9987
> fix(cirrus): Do not throw an exception for user request timeouts

- packages/fxa-settings/src/components/InputPhoneNumber/index.test.tsx
- packages/fxa-settings/src/components/InputPhoneNumber/index.tsx
* Divider is picked up as an option on Android
* HR nested in select component is not currently supported on Android
* Countries should be sorted alphabetically
* Remove HR in select component
* Sort country list alphabetically based on localized name
* Select USA by default for now
Closes: #FXA-11210
Before:
After:
> fix(settings): Remove divider in country selector

- .circleci/config.yml
- the integration tests use a fan-out strategy for parallel execution
- refines the test_suite name by integration test job instead of the overall 'integration'
Relates To: FXA-10808
> fix(ci): integration test_suite names for metric reporting

- packages/functional-tests/tests/settings/recoveryPhone.spec.ts
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/en.ftl
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/index.tsx
* We want to show a custom error with a link to use backup authentication codes instead
* Add custom handling for invalid code error
Closes: FXA-11170
> fix(settings): Show custom error message on SigninRecoveryPhone code error

- packages/functional-tests/tests/settings/recoveryPhone.spec.ts
- CI runs are failing for PRs unrelated to recovery phone
- adds a temporary fixme on the recovery phone functional tests - fix is already up in draft PR
> temp skip of recovery phone tests

- packages/fxa-settings/src/components/FormChoice/index.tsx
- packages/fxa-settings/src/components/FormChoice/mocks.tsx
- packages/fxa-settings/src/components/FormPhoneNumber/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryChoice/index.tsx
* Double clicking on the submit button sends two SMS
* Form submission not disabled during submission
* Disables form submission while initial handling in progress
Closes: FXA-11235
Note: recovery phone tests are currently skipped on CI, but I ran the tests locally and they were 🟢
> fix(settings): Prevent multiple SMS sends on form submission

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/layout.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/success/page.tsx
- apps/payments/next/app/layout.tsx
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/customer/src/lib/promotionCode.manager.spec.ts
- libs/payments/customer/src/lib/promotionCode.manager.ts
- libs/payments/customer/src/lib/subscription.manager.spec.ts
- libs/payments/customer/src/lib/subscription.manager.ts
- libs/payments/customer/src/lib/types.ts
- libs/payments/ui/src/lib/client/components/CouponForm/index.tsx
- we were unable to apply valid coupons to subscriptions
- fixes ability to apply valid coupons to subscriptions
- updates subscriptionManager.update to check metadata key before updating subscription
- revises layout
- CouponForm should not be shown on pages other than /start if a valid coupon was not applied to the subscription
- CouponForm should not be interactive on pages other than /start if valid coupon was applied
Closes: FXA-11251
> fix(payments-next): Create subscription with valid coupon

- libs/shared/db/mysql/account/src/lib/setup.ts
- libs/shared/db/mysql/core/src/lib/core.ts
- packages/fxa-auth-server/README.md
- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/test/remote/recovery_phone_tests.js
- Integration tests were failing in a flaky manner because db connections couldn't be created.
- Connection pool was getting exhausted.
- Connection pool was not getting terminated
- Exposes the connection pool
- Makes sure it's terminated when destroy is called on the Kysely db instance.
- Adds a couple missing places where destroy wasn't called during a tear down.
Closes: ?
Prior to fix:
Also mysql workbench would show **lots** of open connections from fxa:
It's possible this fix addresses issues already filed in the backlog. I'll go snoop around, but if the reviewer knows any off hand please comment.
Running locally with `yarn workspace fxa-auth-server test-integration remote` would consistently fail for prior to this fix. Basically tests would fail …
> bug(auth): Fix connection pooling issues observed in integration tests

- .circleci/config.yml
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.config.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts
- libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- libs/accounts/recovery-phone/src/lib/sms.manager.ts
- packages/functional-tests/lib/sms.ts
- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/test/remote/recovery_phone_tests.js
- It's not enough to block by IP
- Not all +1 numbers reside in our initial target regions of US and Canada
- Adds config for validCountryCodes.
- Adds call to get lookup data on phone number during setup.
- If look up data cannot be retrieved, phone number is deemed invalid.
- If look up data indicates country code isn't a target country, phone number is deemed invalid.
- Updates auth server config to include validCountryCodes
- Modifies phoneNumberLook up so that extra fields can be passed in conditionally.
- Updates tests to reflect how phone number prefixes and country code actually interact with configs.
- Adds some comments to config classes.
Closes: FXA-11257 …
> task(recovery-phone): Also block on twilio country country

- packages/functional-tests/tests/oauth/syncSignIn.spec.ts
- packages/functional-tests/tests/settings/multitab.spec.ts
- packages/fxa-settings/src/pages/Signin/container.test.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
Because:
- Settings should use an account that on local storage when no email argument is given on sign in
This commit:
- updates Settings signin to use an account from local storage when no email is given
> chore(settings): load account from local storage

- packages/fxa-auth-server/config/index.ts
- Can be configured per deploy environment as needed.
- We don't need it on by default.
- This look up costs money.
- Removes `sms_pumping_risk` as a default extra lookup field.
> task(auth): Remove sms_pumping_risk as default for extraLookupFields

- libs/shared/cms/src/__generated__/graphql.ts
- Need to be able to link a specific offering to a list of Stripe prices
- Adds stripeLegacyIapPrices and stripePlanChoices to IAP content type
Closes: #FXA-7837
Related CMS content changes PR is listed below
* https://github.com/mozilla/fxa-strapi/pull/50
> feat(cms): updateiap with stripe prices

- packages/fxa-settings/src/pages/Signin/SigninRecoveryChoice/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/index.tsx
* We want to show a more informative error message
* Add FEATURE_NOT_AVAILABLE case to the error handler
Closes: FXA-11305
> fix(settings): Show user-friendly message if recovery phone service is disabled

- packages/fxa-settings/src/components/FormVerifyTotp/index.tsx
- packages/fxa-settings/src/components/InputPhoneNumber/index.tsx
- packages/fxa-settings/src/components/RecoveryKeySetupHint/index.tsx
- packages/fxa-settings/src/components/Settings/Page2faReplaceRecoveryCodes/index.tsx
- packages/fxa-settings/src/components/Settings/PageTwoStepAuthentication/index.tsx
- packages/fxa-settings/src/components/Settings/UnitRowTwoStepAuth/index.tsx
- packages/fxa-settings/src/lib/hooks/useNavigateWithQuery/index.tsx
* The top part of some pages (replace backup authentication codes, add recovery phone, remove recovery phone) was not visible on first load
* AlertBar from adding recovery phone stayed on screen after navigation to remove recovery phone
* Only optionally include existing hash from router location when navigating
* Remove autofocus on components where it was causing page to scroll away from top on smaller viewscreens
Closes: FXA-11239, FXA-11110
> fix(settings): Fix Settings pages scrolling down on render

- packages/fxa-settings/src/lib/cache.ts
- packages/fxa-settings/src/lib/nimbus/index.ts
- packages/fxa-settings/src/models/contexts/AppContext.ts
- packages/fxa-settings/src/models/hooks.ts
- packages/fxa-settings/src/models/mocks.tsx
- We want to fetch experiments that can target a user on the first render/launch.
- Adds uniqueUserId generation which would happen in Backbone into React as a prerequiste.
- Adds a new call to experiments in the AppContext.
Closes: FXA-9783
- In development, `useMemo` is called twice because of StrictMode. This will not happen in a production build.
- Tests will be followed up in FXA-9784, but I'd happily take some links and pointers to equivalent features that I could base mine on top of.
> feat(settings): Add nimbus experiments to AppContext

- libs/shared/cms/src/__generated__/graphql.ts
- Repeating components currently allow empty entries
- By marking the field as required, empty entries are now allowed in a repeating component.
> feat(cms): prevent empty entries

- libs/accounts/recovery-phone/src/lib/recovery-phone.manager.ts
- packages/fxa-customs-server/lib/config/config.js
- We want a consistent user experience.
- We want to give users 5 attempts for codes
- We want to have consistent ban durations
- Changes OTP recovery phone code validity to 5 minute windows
- Changes max attempts to OTP recovery phones to 5
- Changes block durations for otp codes to 15 minutes on recovery phone, 2FA, and password reset otp
Closes: FXA-11272
There's a chance this could break some tests... Hopefully impact is small. If impact is big we might need to roll back some of these.
> task(customs): Update rules for consistency

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/error/en.ftl
- removes duplicate ftl ids; these ftl ids are currently in `apps/payments/next/app/[locale]/en.ftl` and are shared between `/checkout` and `/upgrade`
> fix(payments-next): Remove duplicate ftl ids

- libs/accounts/recovery-phone/README.md
- packages/fxa-auth-server/README.md
- We want to offer some guidance on configuring twilio.
- Updates READMEs
- Explains Twilio credential modes
> polish(recovery-phone/auth): More docs on twilio config.

- libs/accounts/recovery-phone/src/lib/twilio.config.ts
- libs/accounts/recovery-phone/src/lib/twilio.provider.ts
- packages/fxa-auth-server/config/index.ts
- Auth server should still start if twilio isn't configured
- Creates an default empty config state that allows auth server to still start up.
> bug(auth): Allow startup even if twilio is not configured.

- packages/functional-tests/tests/react-conversion/oauthPromptNone.spec.ts
- packages/fxa-content-server/app/scripts/lib/router.js
- packages/fxa-content-server/server/lib/routes/react-app/index.js
- packages/fxa-react/components/AppErrorBoundary/index.tsx
- packages/fxa-react/components/AppErrorDialog/index.stories.tsx
- packages/fxa-react/components/AppErrorDialog/index.test.tsx
- packages/fxa-react/components/AppErrorDialog/index.tsx
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/components/OAuthDataError/index.tsx
- packages/fxa-settings/src/components/Settings/index.tsx
- packages/fxa-settings/src/models/Account.ts
- packages/fxa-settings/src/models/contexts/AppContext.ts
- packages/fxa-settings/src/models/integrations/base-integration.ts
- packages/fxa-settings/src/models/integrations/oauth-web-integration.ts
- packages/fxa-settings/src/pages/Authorization/container.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
- packages/fxa-settings/src/pages/Signin/utils.ts
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/container.test.tsx
Because:
- we need our React UI to handle the /authorization route
This commit:
- adds the /authorization route to fxa-settings
- moves the cached sign-in logic out of the sign-in container
- fixes bugs in the prompt=none validation
- fixes/updates code or comments (not necessarily related to /authorization) for clarity or consistency
> feat(Settings): add /authorization to fxa-settings

- packages/fxa-content-server/app/scripts/lib/router.js
- packages/fxa-content-server/server/lib/routes/react-app/index.js
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/pages/Authorization/container.tsx
- packages/fxa-settings/src/pages/Index/container.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
- packages/fxa-settings/src/pages/Signup/container.tsx
Because:
* We are converting Backbone flows to React
This commit:
* Displays email-first Index page if path is /oauth, for React
closes FXA-6516
> feat(react): Add '/oauth' to React app

- packages/fxa-settings/src/components/Settings/FlowSetupRecoveryPhoneConfirmCode/index.test.tsx
- packages/fxa-settings/src/models/mocks.tsx
branched from #18340
--
Because:
* This import was not being allowed, seemingly from a circular dependency somewhere
This commit:
* Changes the import to avoid the problem, but investigation is still needed
> chore(tests): Fix mock import issue, more investigation needed 

- packages/fxa-content-server/server/lib/routes.js
- packages/fxa-content-server/server/lib/routes/post-nimbus-experiments.js
We can do this here to covert Backbone and React because both of them use content-server to access nimbus experiments. We should also keep it this way in the future too. It is also recommended by [the nimbus demo app](https://github.com/mozilla/experimenter/tree/main/demo-app) to proxy the request.
- We want to mark how long it takes requests from the Cirrus container to the content server to complete for Grafana.
- We want to rule out that timeouts are caused by the sidecar container.
- Adds a statsd metric for the fetch request.
Fixes FXA-11260
How do I write unit tests for this?
> chore(cirrus): Add statsd metric to nimbus experiments

- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/customer/src/index.ts
- libs/payments/customer/src/lib/error.ts
- libs/payments/customer/src/lib/invoice.manager.spec.ts
- libs/payments/customer/src/lib/invoice.manager.ts
- libs/payments/customer/src/lib/subscription.manager.spec.ts
- libs/payments/customer/src/lib/subscription.manager.ts
- libs/payments/customer/src/lib/util/retrieveSubscriptionItem.spec.ts
- libs/payments/customer/src/lib/util/retrieveSubscriptionItem.ts
- libs/payments/eligibility/src/lib/eligibility.factories.ts
- Reuse function to retrieve subscription item from subscription.
- Move retrieveSubscriptionItem into util function and reuse in invoice.manager.
- Extract logic to fetch upcoming upgrade invoice into previewUpcomingUpgrade method.
- Rewrite previewUpcomingForUpgrade to more accurately reflect its purpose.
> fix(next): reuse subscription item fetch logic

- packages/fxa-payments-server/src/lib/hooks.test.tsx
- Test related to useInfoBoxMessage is failing intermittently.
- Skips failing test noting ticket number to resolve the intermittent test failures.
> fix(payments): skip intermittent failing hook test

- packages/fxa-auth-server/test/local/payments/iap/apple-app-store/purchase-manager.js
- packages/fxa-shared/payments/iap/apple-app-store/purchase-manager.ts
- For expired Apple IAP subscriptions, Apple is still queried to check if any change has occured to the subscription since the same transaction ID will be reused for a new subscription.
- If an Apple subscription is already expired, ignore TransactionIdNotFoundError errors received from Apple and log an info message.
Closes: #FXA-6720
The code being changed in this PR is used in a few scenarios, some of which are listed below.
1. When a customers subscriptions are fetched
1. When handling a webhook message from Apple
This PR aims to address a specific issue related to the scenario when a customers subscriptions are fetched.
A record of a customers Apple IAP subscriptions are stored in a Firestore table. These records contain a bunch of information, …
> fix(auth): handle apple iap transaction 404 error

- packages/fxa-settings/src/components/InputPhoneNumber/index.tsx
* Select element is handled differently on different platforms
* Country option text was only visible on hover
* Select component was not selectable on narrow viewscreens
* 
* Use text indent instead of text transparent
* Add z-index to ensure selectability
Closes: FXA-11319
Screenshots from storybook on Windows:
And in high contrast mode:
> fix(settings): Country selector options hidden on Windows

- packages/fxa-settings/src/pages/Signin/container.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/container.tsx
- packages/fxa-settings/src/pages/Signup/index.tsx
Because:
* We are unintentionally taking users not in the React experiment from Backbone index to React signup back to React index if they click 'Change email' on signup because we do a hard navigate with the showReactApp param that is added by Backbone routing to reach React signup. In this case we want this user to see Backbone email-first as they are not enrolled in the experiment
This commit:
* Removes 'showReactApp' param when hard navigating from signup back to email-first
fixes FXA-11358
---
Noticed this when playing around on stage.
> fix(react): Remove 'showReactApp' param on signup 'Change email'

- packages/fxa-shared/payments/iap/apple-app-store/purchase-manager.ts
- The Apple app-store-server-api SDK in certain circumstances throws an AppStoreError which is not currently being handled.
- Correctly handle Apple AppStoreError when using app-store-server-api.
> fix(auth): handle apple appstore error

- packages/fxa-settings/src/pages/Signin/container.test.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
Because:
* If users give the OK on email-first, they don't need to see the merge warning on /signin
This commit:
* Fixes a logical error where we were checking if hasLinkedAccountFromLocationState was true, instead of if it's not undefined, to denote the user has come from email-first
fixes FXA-11368
> fix(react): Only show Sync merge warning once

- libs/payments/ui/src/lib/client/components/SelectTaxLocation/index.tsx
- libs/payments/ui/src/lib/nestapp/validators/ValidatePostalCodeActionResult.ts
- invalid postal codes were not throwing an error and could be saved in `<SelectTaxLocation />`
- fixes validation
> fix(payments): Postal code validation

- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/ui/src/lib/actions/updateCart.ts
- CartService.wrapWithCartCatch is catching Coupon errors in updateCart and finishing the cart with and error instead of allowing the error to propogate to the client so that it is handled appropriately there.
- Overrides the CartService.wrapWithCartCatch method to add an optional options argument which adds an errorAllowList, which will serve as a passthrough for errors added in the errorAllowList.
Closes: #FXA-11256 FXA-11348 FXA-11345
> fix(next): allow coupon errors to propogate to client

- apps/payments/next/project.json
- Translated localization files are not loaded into public folder of payments-next.
- Calls l10n-prime script to load translated ftl files into public folder before calling l10n-bundle script.
Closes: #FXA-11330
> fix(next): call l10n-prime script before bundle

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/layout.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/start/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/landing/route.ts
- apps/payments/next/app/[locale]/[offeringId]/[interval]/location/en.ftl
- apps/payments/next/app/[locale]/[offeringId]/[interval]/location/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/new/page.tsx
- libs/payments/cart/src/lib/cart.factories.ts
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/cart.types.ts
- libs/payments/ui/src/lib/actions/getTaxAddress.ts
- libs/payments/ui/src/lib/actions/index.ts
- libs/payments/ui/src/lib/actions/setupCart.ts
- libs/payments/ui/src/lib/client/components/SelectTaxLocation/index.tsx
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- libs/payments/ui/src/lib/nestapp/validators/getTaxAddressArgs.ts
- libs/payments/ui/src/lib/nestapp/validators/getTaxAddressResult.ts
- libs/payments/ui/src/lib/utils/buildRedirectUrl.ts
- Subscription carts need the users tax location to function properly. Currently, if a user can't be found via maxmind, we set their tax address to empty.
- Ensures the tax address and currency code are set on the cart. If the user cannot be located, their cart-creation attempt is intercepted and they are directed to a new page, where they are prompted to input their details
Closes: #FXA-10384
> feat(payments-next): add location intercept to cart creation

- packages/fxa-settings/src/components/Settings/UnitRowTwoStepAuth/index.tsx
* Alerts were staying on screen and not dismissed on delete button click
* Explicitly hide the alert
Closes: FXA-11110
> fix(settings): Hide alert bar on navigation to remove recovery phone

- libs/payments/ui/src/lib/client/components/CouponForm/index.tsx
- libs/payments/ui/src/lib/client/components/SelectTaxLocation/index.tsx
- libs/payments/ui/src/lib/client/components/SignInForm/index.tsx
- libs/payments/ui/src/lib/client/components/SubmitButton/index.tsx
- libs/payments/ui/src/lib/server/components/UpgradePurchaseDetails/index.tsx
> fix(payments-ui): Updates SubmitButton and UpgradePurchaseDetails components

- packages/fxa-settings/src/pages/Index/container.tsx
* Navigating to react email first with an email param was causing an infinite redirect
* If an email is provided, check email status and redirect appropriately to signin or signup
Closes: FXA-11327
Container tests will be added in follow-up `FXA-11316`
> fix(settings): Redirect from React email first with email param

- libs/payments/ui/src/lib/client/components/CouponForm/index.tsx
- limits number of characters for input field to 30 max
- prevents the input field from being editable when "Apply" button is clicked
Closes: FXA-11363, FXA-11416
> fix(payments-ui): CouponForm - limit number of characters and prevent changes to input field when Apply button is clicked

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/start/en.ftl
- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/start/page.tsx
- libs/payments/ui/src/lib/client/components/SignInForm/index.tsx
- Remove "Create a Mozilla account" from Checkout page
Mobile
Tablet
Desktop
> fix(payments-next): Update sign-in section on Checkout page

- packages/fxa-content-server/server/lib/beta-settings.js
- packages/fxa-content-server/server/lib/configuration.js
- packages/fxa-content-server/server/lib/routes/post-nimbus-experiments.js
- packages/fxa-content-server/server/lib/routes/react-app/route-definition-index.js
- packages/fxa-settings/src/lib/config.ts
- packages/fxa-settings/src/lib/nimbus/index.ts
- packages/fxa-settings/src/models/contexts/AppContext.ts
- For an A/A experiment we need to also be able to use preview mode.
- This follows the pattern used by `GLEAN_ENABLED` so that `NIMBUS_PREVIEW` can be used the same way for local development and deployments.
Fixes FXA-11372
- Adding the query param `nimbusPreview=[true|false]` to the requests should also have the equivalent params request to the `/nimbus-experiments` endpoint.
- For reference, see the demo-app in experimenter: https://github.com/mozilla/experimenter/tree/main/demo-app
> feat(cirrus): Add nimbus preview support to React and Backbone

- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFirstWarning/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFirstWarning/index.txt
Because:
- a fluent id and string was updated but the ids where it's used were not
> fix(emails): update fluent id for inactiveAccountFirstWarning

- apps/payments/next/app/[locale]/[offeringId]/[interval]/new/page.tsx
- libs/payments/cart/src/lib/cart.error.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/customer/src/lib/error.ts
- libs/payments/ui/src/lib/actions/updateCart.ts
- Nextjs build minification changes the name of classes, making it not feasible for comparison logic on the client.
- Set the error name property to match the name of the error class and then use that in client side comparisons.
Closes: #FXA-11348
Discussed in a bit more detail in [this SO post](https://stackoverflow.com/questions/77336592/how-to-throw-and-handle-custom-errors-from-server-to-client-side-in-next-js). Note, I'm not sure it's 100% applicable anymore.
> fix(next): add name to server errors used in client

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/layout.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/landing/route.ts
- apps/payments/next/app/[locale]/[offeringId]/[interval]/location/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/new/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/page-not-found/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/layout.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(startLayout)/layout.tsx
- apps/payments/next/app/[locale]/not-found.tsx
- apps/payments/next/app/en.ftl
- apps/payments/next/app/layout.tsx
- apps/payments/next/app/not-found.tsx
- apps/payments/next/middleware.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/customer/src/lib/util/doesPriceMatchSubplatInterval.ts
- libs/payments/eligibility/src/lib/eligibility.service.spec.ts
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- libs/payments/ui/src/lib/utils/buildRedirectUrl.ts
- libs/shared/cms/src/lib/cms.error.ts
- libs/shared/cms/src/lib/product-configuration.manager.ts
- libs/shared/cms/src/lib/queries/eligibility-content-by-offering/util.spec.ts
- libs/shared/cms/src/lib/queries/eligibility-content-by-offering/util.ts
- libs/shared/cms/src/lib/queries/page-content-for-offering/util.ts
- Invalid paths currently display a generic error message to the user and log a generic error message in Sentry.
- Add {locale}/not-found.tsx for localized not found page.
- Add {root}/not-found.tsx as fallback page.
- Update thrown server errors for invalid path params, so that they can be handled on the client, and use Next.js notFound function.
- Adds new page-not-found/page.tsx for to handle invalid path params errors thrown in a route handler, that need to show a page not found error to the client. This is mainly applicable to the /landing page
Closes: #FXA-11271
> feat(next): redirect to 404 page for invalid path

- packages/fxa-settings/src/pages/Index/index.tsx
* Should show the correct keyboard for the input on mobile
* Set 'type' attribute for the index page email input
Closes: FXA-11366
I had initially included `type="email"` too, but this modified the input validation and error handling. Reverted to only including the inputmode attribute
> fix(settings): Show email keyboard type for email input

- packages/fxa-settings/src/components/App/index.test.tsx
- packages/fxa-settings/src/components/ThirdPartyAuth/index.test.tsx
- packages/fxa-settings/src/components/ThirdPartyAuth/index.tsx
- packages/fxa-settings/src/lib/glean/index.test.ts
- packages/fxa-settings/src/lib/glean/index.ts
- packages/fxa-settings/src/pages/Index/container.test.tsx
- packages/fxa-settings/src/pages/Index/container.tsx
- packages/fxa-settings/src/pages/Index/index.test.tsx
- packages/fxa-settings/src/pages/Index/index.tsx
- packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml
- packages/fxa-shared/metrics/glean/web/email.ts
- packages/fxa-shared/metrics/glean/web/index.ts
* We want to track metrics for the react email-first conversion
* Adds custom glean events and automated click event for react email-first page
* Add tests for these events
Closes: FXA-11312
> feat(glean): Add glean metrics for React email-first page

- apps/payments/next/app/[locale]/[offeringId]/[interval]/landing/route.ts
- libs/payments/legacy/src/lib/utils/getSP2Params.spec.ts
- libs/payments/legacy/src/lib/utils/getSP2Params.ts
- Next.js does not allow redirects within a try-catch block.
- Move the redirect to the try-catch, finally block instead.
> fix(next): move redirect out of try-catch

- apps/payments/next/app/[locale]/[offeringId]/[interval]/landing/route.ts
- libs/payments/legacy/src/index.ts
- libs/payments/legacy/src/lib/utils/buildSp2RedirectUrl.spec.ts
- libs/payments/legacy/src/lib/utils/buildSp2RedirectUrl.ts
- libs/payments/legacy/src/lib/utils/determineRedirectToSp2.spec.ts
- libs/payments/legacy/src/lib/utils/determineRedirectToSp2.ts
- If spVersion is provided in query params, it should always be override any other logic.
- Updates determineRedirectToSp2 function to include override param.
- If spVersion is provided, pass it into determineRedirectToSp2
Closes: FXA-11431
> fix(next): spVersion should override other logic

- packages/fxa-react/package.json
- packages/fxa-settings/package.json
- yarn.lock
Reverts mozilla/fxa#18592
This may be causing problems with string extraction and netlify checks failing - reverting to test
> Revert "chore(deps): bump babel-preset-react-app from 10.0.1 to 10.1.0"

- packages/fxa-content-server/server/lib/routes/post-nimbus-experiments.js
* gettext doesn't support optional chaining, and using optional chaining in content-server breaks the string extraction
* Replace optional chaining in the one line that was causing string extraction failure
> fix(content): Optional chaining breaking string extraction

- packages/fxa-settings/src/lib/nimbus/index.ts
- packages/fxa-settings/src/models/contexts/AppContext.ts
- A [follow-up review comment](https://github.com/mozilla/fxa/pull/18598#discussion_r2014092326) made a good suggestion to lift this logic to the caller.
- Does just that.
Closes: FXA-11372
> chore(cirrus): Move preview fallback logic to caller

- apps/payments/next/middleware.ts
Because:
* nextRequest.hostname was defaulting to localhost, rather than the correct base url
This commit:
* nextRequest.url has the correct hostname. Using it fixes the redirect host issue
Closes #N/A
> fix(payments-next): fix locale-less redirects

- packages/fxa-auth-server/lib/routes/recovery-codes.js
- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/test/local/routes/recovery-codes.js
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
- packages/fxa-auth-server/test/local/routes/totp.js
Because:
- the backend login.complete Glean event was not emitted when a user signed in successfully with TOTP 2FA, TOTP backup code, or SMS recovery code
This commit:
- emits the end of flow signal so that the login.complete Glean event is emitted
> fix(metrics): emit login.complete at end of multi-step signin

- packages/fxa-auth-server/bin/key_server.js
-The stripe client is being instantiated in the auth server's key_server, and is missing the statsd argument.
- Adds in the statsd arg to allow the statsd decorator to coorrectly read the call timing
- Removes the productManager and subscriptionManagegr args, as they are no longer being used.
Closes: #FXA-11335
> fix(StatsD): Fix StripeClient StatsD key server injection

- packages/functional-tests/tests/key-stretching-v2/recoveryKey.spec.ts
- these tests, using v1 sign up in the recoveryKey flows, are flaky, 
- and users cannot sign up with v1, 
- and the v1 support is going away soon
- Skips any tests here that try to sign up with `v1` then perform another action in the `recoveryKey.spec` flows
Closes: (FXA-11160)
> test(functional-tests): skip flaky v1 signup to v2 keystretching recoveryKey tests

- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/customer/src/lib/invoice.manager.spec.ts
- libs/payments/customer/src/lib/invoice.manager.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- A stripe webhooks race condition occurs in SP3 for upgrades, which can cause the cart to be thrown into an error state.
- A cart in the error state cancels the subscription.
- The race condition causes some upgrades that use PayPal to cancel the original subscription, despite payment 
- Prevents stripe webhook from erroring when it attempts to finalize an invoice that was finalized elsewhere.
- Adjusts the logic in the cart service to only cancel the subscription for erroring carts that are creating a new subscription.
Closes: #FXA-11414
> fix(payments-next): Prevent stripe webhook race condition from cancelling subscription

- .circleci/config.yml
- packages/fxa-settings/src/pages/Index/container.test.tsx
- packages/fxa-settings/src/pages/Index/container.tsx
* We want to suggest the last stored account from local storage if there is no account marked as current
* Add lastStoredAccount to the suggested account check in react email first
Closes: FXA-11429
Example use case (on local):
- `yarn firefox`
- Sign in to Sync with Account1
- Go directly to localhost:3030
- See cached sign in for Account1, click "Use different account"
- Sign in with Account2
- Go directly to localhost:3030
- See cached sign in for Account2
- Sign in, sign out from Account2
- See cached sign in for Account1 (sync account) --- this is what was previously not working, there would not have been as suggested account and would have stayed on email first
> fix(settings): Retrieve last stored account from email-first

- libs/google/src/lib/factories.ts
- libs/google/src/lib/google.client.spec.ts
- libs/google/src/lib/google.client.ts
- libs/google/src/lib/google.manager.spec.ts
- libs/google/src/lib/google.manager.ts
- libs/google/src/lib/types.ts
- libs/payments/ui/src/lib/actions/index.ts
- libs/payments/ui/src/lib/actions/validateAndFormatPostalCode.ts
- libs/payments/ui/src/lib/client/components/SelectTaxLocation/index.tsx
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- libs/payments/ui/src/lib/nestapp/validators/ValidatePostalCodeActionResult.ts
- Postal code currently allows special characters to be saved as a valid postal code.
- Validate postal code action returns formatted postal code
- Update Google geocode to validate postal code specifically
Closes: #FXA-11359
(Note in the image below, white space is manually added to the start and end of the postal code. These are automatically removed by Google Geocode)
> fix(next): do not allow special chars in postal code

- packages/fxa-content-server/server/lib/routes/post-nimbus-experiments.js
- Increment is the wrong type of statsd call to use here.
- This call was causing issues for telegraph
- Fixes the call by using `statsd.timing` instead
Closes: FXA-11466
> bug(content): Fix statsd call for cirrus.response-time

- packages/fxa-admin-server/src/gql/account/account.resolver.ts
- When an account delete task completes it disappears from the task queue.
- When it disappears we'd show a status of 'Could not locate task', which confused users...
- We'd like to make this less confusing.
- Changes wording if task fails to locate.
- Logs the error code so we can keep tabs on this.
Closes: FXA-11183
Note, this is a very optimistic behavior... and could result in a false positive. However, we know it's currently functioning so taking the quick and dirty approach here, as its unclear from google docs what error code states might arise.
> task(admin): Improve messaging for account delete task status

- package.json
- packages/functional-tests/tests/misc/cookiesDisabled.spec.ts
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/index.tsx
- packages/fxa-settings/src/lib/channels/firefox.ts
- yarn.lock
Because:
- the "cookies disabled" page was not rendered in Settings
This commit:
- detect for lack of local storage access (browsers group that with the cookies pref) and display the cookies disabled page
- try-catch local/session storage access so that won't break rendering
- that's the purpose of the glean.js upgrade
> fix(settings): check and display the "cookies disabled" page

- libs/payments/iap/src/lib/google/factories.ts
- libs/payments/iap/src/lib/google/google-iap-purchase.manager.ts
- libs/payments/iap/src/lib/google/google-iap.error.ts
- libs/payments/iap/src/lib/google/google-iap.service.spec.ts
- libs/payments/iap/src/lib/google/google-iap.service.ts
- libs/payments/iap/src/lib/google/types.ts
- libs/payments/iap/src/lib/types.ts
- Move and restructure existing Google IAP methods into the new libs Google IAP Service
- Moves the logic and tests for the methods listed below, with minor restructuring, into GoogleIapService
- getActiveSubscriptions
- processNotification
- registerToUserAccount
Closes: #FXA-10731
This PR varies slightly from what was initially listed as a requirement in the Jira ticket, since some of the work was done in a previous ticket, and some work is no longer required. The Jira ticket has been updated to reflect the differences.
> feat(iap): add google iap service

- packages/functional-tests/tests/syncV3/fxDesktopHandshake.spec.ts
- packages/functional-tests/tests/syncV3/fxDesktopHandshakeNonSync.spec.ts
- packages/fxa-settings/src/components/App/index.test.tsx
- packages/fxa-settings/src/components/App/index.tsx
* In React, account status web channel message was only checked when signing in to a browser service
* This did not match backbone and caused test failures
* Always check for web channel message on app start
* Update test cases
Closes: FXA-11432
Ran functional tests with and without react email-first routes set to full prod rollout
> fix(tests): Fix and re-enable sync handshake functional tests

- libs/payments/iap/src/lib/apple/apple-iap-purchase.manager.ts
- libs/payments/iap/src/lib/apple/apple-iap.error.ts
- libs/payments/iap/src/lib/apple/apple-iap.service.spec.ts
- libs/payments/iap/src/lib/apple/apple-iap.service.ts
- libs/payments/iap/src/lib/apple/constants.ts
> feat(payments-iap): Create Apple IAP Service

- libs/payments/ui/src/lib/client/components/CouponForm/index.tsx
> fix(payments-ui): CouponForm - handle pending state and remove console warning

- apps/payments/next/app/[locale]/[offeringId]/[interval]/landing/route.ts
- With shadow mode enabled the SP2 redirect loads a not found page for valid offering and interval
- With shadow mode enabled, do not redirect to SP2 URL.
> fix(next): sp2 redirect shadow mode redirect

- libs/payments/stripe/src/lib/cacheKeyForClient.ts
- libs/payments/stripe/src/lib/stripe.client.ts
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- libs/shared/cms/src/lib/product-configuration.manager.spec.ts
- libs/shared/db/type-cacheable/src/index.ts
- libs/shared/db/type-cacheable/src/lib/type-cachable-async-local-storage-adapter.spec.ts
- libs/shared/db/type-cacheable/src/lib/type-cachable-async-local-storage-adapter.ts
- libs/shared/db/type-cacheable/src/lib/type-cachable-async-local-storage-init.ts
- We want to cache things for the request lifetime
- Adds an adapter for type-cachable where we can store things on the async local context to reuse data across services during the request lifecycle.
- Uses this adapter within the nextjs actions service
Closes FXA-11315
> feat(type-cacheable): add async local storage adapter

- libs/google/src/lib/google.constants.ts
- libs/google/src/lib/google.manager.spec.ts
- libs/google/src/lib/google.manager.ts
- Google geocode does not place romanian postal codes
- Adds a bypass for romanian postal codes
Closes FXA-11482
> fix(google): support romanian postal codes

- libs/payments/events/src/lib/emitter.factories.ts
- libs/payments/events/src/lib/emitter.service.spec.ts
- libs/payments/events/src/lib/emitter.service.ts
- libs/payments/events/src/lib/emitter.types.ts
- libs/payments/metrics/src/lib/glean/glean.factory.ts
- libs/payments/metrics/src/lib/glean/glean.manager.spec.ts
- libs/payments/metrics/src/lib/glean/glean.manager.ts
- libs/payments/metrics/src/lib/glean/glean.test-provider.ts
- libs/payments/metrics/src/lib/glean/glean.types.ts
- libs/payments/metrics/src/lib/glean/utils/mapSubscriptionCancellation.spec.ts
- libs/payments/metrics/src/lib/glean/utils/mapSubscriptionCancellation.ts
- libs/payments/webhooks/src/lib/subscriptionHandler.service.spec.ts
- libs/payments/webhooks/src/lib/subscriptionHandler.service.ts
- libs/shared/metrics/glean/src/registry/subplat-backend-metrics.yaml
Because:
* We need to get the subscription platform to the data recording state of SP2.5
This commit:
* Alters the subplat-backend-metrics.yaml file to add newly recorded fields, and the subscription.ended event
* Uses the handleSubscriptionEnded event on the emitter service to record the data in glean
Closes #FXA-11139
> feat(payments-next): Record glean data for subscription deletion event

- packages/fxa-settings/src/pages/Index/container.test.tsx
- packages/fxa-settings/src/pages/Index/container.tsx
- In a previous PR, it was pointed out that maybe we shouldn't fail if a bad email is provided.
- It's questionable if our email validation logic and RP's email validation logic is aligned...
- Allows loginHint query param to be an invalid email address.
- Allows email query param to be an invalid email address.
- Captures errors in Sentry so we can monitor how much of a problem this really is.
This commit is based on feedback that arose while addressing FXA-11297.
> task(settings): Fast follow for allowing invalid emails

- packages/fxa-content-server/app/scripts/lib/router.js
- packages/fxa-settings/public/index.html
- packages/fxa-settings/public/query-fix.js
* Some relying parties have legacy code that passes partially unencoded query parameters (specifically, + signs)
* We added stricter validation and now see validation errors because of this encoding issue
* Using URLSearchParams introduces other encoding issues, with + sign converted to space
* Use custom functions in content-server and settings to correctly preserve and encode email characters
* Encode query params before settings bundle load
Closes: FXA-11327
> fix(content): Encode URL components

- packages/fxa-auth-server/scripts/recorded-future/check-and-reset.ts
- packages/fxa-auth-server/scripts/recorded-future/lib.ts
- packages/fxa-auth-server/test/scripts/recorded-future/lib.ts
Because:
- we need to fetch all paginated Recorded Future credential search results and filter for those that are accounts without 2FA
This commit:
- handles result pagination
- filters logins to accounts without 2FA
- adds more metrics
> feat(scripts): fetch and filter all credential search results

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/layout.tsx
- customers should only be able to edit their tax location on /checkout
- the Tax Location should not be seen after `start`
- updates the Checkout layout so that the TaxLocation is only editable when cart state is `start`
Closes: FXA-11456
> fix(payments-next): TaxLocation component should only be editable on Checkout and hidden on other pages

- .circleci/config.yml
- We were getting some flaky behavior on yarn install.
- There were seemingly random node-gyp errors
- We think this might have to with older cached packages and node version 22
- Bumps the key prefix
Closes: FXA-11521
See https://circleci.com/docs/caching/#restoring-cache for info on how key matching works for circle ci caches.
> task(ci): Bump yarn cache key prefix

- apps/payments/next/app/[locale]/[offeringId]/[interval]/location/page.tsx
- libs/payments/events/src/lib/emitter.service.ts
- libs/payments/events/src/lib/emitter.types.ts
Because:
* we need to understand how often our users are experiencing issues with location changes
This commit:
* Adds statsd collection for counts of ip location failures, unsupported locations, and sactioned locations
Closes #FXA-11481
> feat(payments-next): collect metrics for location changes

- packages/fxa-auth-server/scripts/recorded-future/check-and-reset.ts
- packages/fxa-auth-server/scripts/recorded-future/lib.ts
Because:
- for testing, or scenarios where we know we want to force reset accounts, we want to be able to pass in account email addresses to force reset the accounts
This commit:
- adds a new repeatable parameter to accept email addresses
- breaks up and moves code around so that email argument values can be checked for existing accounts and their 2FA status
> feat(scripts): accept email args for direct acct reset

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/layout.tsx
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/ui/src/lib/actions/applyCoupon.ts
- libs/payments/ui/src/lib/actions/index.ts
- libs/payments/ui/src/lib/actions/updateTaxAddress.ts
- libs/payments/ui/src/lib/client/components/CouponForm/index.tsx
- libs/payments/ui/src/lib/client/components/SelectTaxLocation/index.tsx
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- libs/payments/ui/src/lib/nestapp/validators/UpdateCartActionResult.ts
- After changing location through the location picker, the collapsed view shows the previous values before flashing to the new value.
- Split updateCartAction into function specific actions applyCouponAction and updateTaxAddressAction.
- Modify updateCart functions to return updated Cart.
- Add local state to SelectTaxLocation component to show new tax location before cart is revalidated.
Closes: #FXA-11030
> feat(next): location shows updates optimistically

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/error/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/layout.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/new/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/error/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/layout.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(startLayout)/layout.tsx
- apps/payments/next/app/[locale]/en.ftl
- libs/payments/cart/src/lib/cart.manager.in.spec.ts
- libs/payments/cart/src/lib/cart.manager.ts
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/cart.utils.ts
- libs/payments/eligibility/src/lib/eligibility.manager.spec.ts
- libs/payments/eligibility/src/lib/eligibility.manager.ts
- libs/payments/eligibility/src/lib/eligibility.types.ts
- libs/payments/ui/src/lib/server/components/SubscriptionTitle/en.ftl
- libs/payments/ui/src/lib/server/components/SubscriptionTitle/index.tsx
- libs/payments/ui/src/lib/utils/getErrorFtlInfo.ts
- libs/payments/ui/src/server.ts
- libs/shared/db/mysql/account/src/lib/kysely-types.ts
- When a customer attempts to subscribe to a purchase offering that they've already subscribed to, a generic error page is shown, instead of an error page informing they are already subscribed.
- Adds new error message to inform customer when they have an existing subscription to a purchase offering.
- Adds new SubscriptionTitle
- Adds new Icon for error message if a customer has an existing subscription
- Redirects to error page directly from new page when CartService.setupCart results in a cart in error state.
Closes: FXA-11252
> feat(next): error page for existing sub

- packages/functional-tests/pages/signup.ts
- packages/functional-tests/tests/misc/recoveryKeyPromoInline.spec.ts
- packages/functional-tests/tests/misc/relayIntegration.spec.ts
- packages/functional-tests/tests/react-conversion/oauthSignup.spec.ts
- packages/functional-tests/tests/react-conversion/signup.spec.ts
- packages/fxa-settings/src/components/FormPasswordWithBalloons/index.test.tsx
- packages/fxa-settings/src/components/FormPasswordWithBalloons/index.tsx
- packages/fxa-settings/src/components/FormPasswordWithBalloons/mocks.tsx
- packages/fxa-settings/src/components/FormSetupAccount/index.tsx
- packages/fxa-settings/src/pages/Signup/index.test.tsx
* We want to reduce registration friction
* Remove password confirmation field in non-sync registration form
* Maintains password confirmation field for sync signup
* Update tests
Closes: FXA-10467
> feat(settings): Remove password confirmation field in signup

- libs/payments/ui/src/lib/client/components/CouponForm/index.tsx
- libs/payments/ui/src/lib/client/components/SelectTaxLocation/index.tsx
> fix(payments-ui): Add Cancel button and fix style/functionality in Chrome and Safari

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/error/page.tsx
- apps/payments/next/app/[locale]/en.ftl
- libs/payments/cart/src/lib/cart.error.ts
- libs/payments/cart/src/lib/cart.factories.ts
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/cart.types.ts
- libs/payments/cart/src/lib/cart.utils.spec.ts
- libs/payments/cart/src/lib/cart.utils.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/cart/src/lib/util/resolveErrorInstance.ts
- libs/payments/ui/src/lib/server/components/SubscriptionTitle/index.tsx
- libs/payments/ui/src/lib/utils/getErrorFtlInfo.ts
- libs/shared/db/mysql/account/src/lib/kysely-types.ts
- It is currently not easy to throw an error on the server and display a user friendly message on the frontend.
- When debugging a specific cart, it is not easy to determine what caused the cart to error.
- Create one function to resolve an error instance to a specific CartErrorReasonId, which can be used to display a user friendly message on the frontend.
- For error instances not specifically mapped to a CartErrorReasonId, but still thrown by SubPlat libraries, add the instance name to the cart.errorReasonId field instead, to help with debugging.
> feat(next): improve error recording and display

- package.json
- packages/fxa-event-broker/jest.config.js
- packages/fxa-event-broker/package.json
- yarn.lock
Our older version of Axios (0.29) has multiple security vulnerabilities
Upgrades Axios to the latest version 1.8.4
Closes: FXA-6043
- Because this version of Axios now uses ESM, we had to add it to `transformIgnorePatterns` so that Jest process it correctly.
- There was an attempt to replace Axios altogether with native Node Fetch, which is now standard and much more prevalent in our codebase: https://github.com/mozilla/fxa/pull/18698  Unfortunately due to the extensive amount of test incompatibilities and changes required, this was abandoned for now.
> chore: upgrade axios to major version 1.8.4

- packages/functional-tests/tests/resetPassword/oauthResetPassword.spec.ts
- packages/functional-tests/tests/resetPassword/resetPassword2FA.spec.ts
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-auth-server/test/remote/totp_tests.js
- We don't want users to have to enter 2FA twice during a password reset (one to reset, one to login)
- Updates our frontend parts to handle this case correctly, only prompt for 2FA once and then login after successful password reset
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11225
> feat(2fa): Auto login user after reset password and 2FA

- packages/functional-tests/tests/oauth/syncSignIn.spec.ts
- `signin to OAuth with Sync creds` functional test failing intermittently in smoke tests
- mark the test as fixme until resolved in `FXA-11542`
> temporarily skip failing functional test

- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveRecoveryPhone/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveRecoveryPhone/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveRecoveryPhone/index.txt
- packages/fxa-auth-server/test/local/senders/emails.ts
- Remove recovery phone email didn't match spec
- Updates to match spec
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11176
> feat(images): Update to remove recovery phone email

- libs/payments/iap/src/lib/apple/apple-iap.client.config.ts
- libs/payments/iap/src/lib/google/google-iap.client.config.ts
- class-validator does not validate nested @Transform'd objects correctly
- Removes the nested validation of the IAP config
> fix(payments-next): remove class-validator nested IAP config validation

- packages/fxa-auth-server/lib/senders/emails/templates/postAddRecoveryPhone/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postAddRecoveryPhone/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postAddRecoveryPhone/index.txt
- packages/fxa-auth-server/test/local/senders/emails.ts
- The incorrect title is displayed in the email received: “You created a recovery phone number”
- Fixes the copy to read “You added a recovery phone number”
Closes: FXA-11194
> Fix Incorrect title in “Recovery phone added” email

- .github/workflows/codeql-analysis.yml
- .github/workflows/docker.yml
- .github/workflows/glean-probe-scraper.yml
- .github/workflows/l10n-gettext-extract.yml
- .github/workflows/pull-legal-docs.yml
- .github/workflows/tag-release.yml
- .github/workflows/upload-assets-to-cdn.yml
- .github/workflows/zizmor.yml
Zizmor is a Static Analysis tool for GitHub Actions https://woodruffw.github.io/zizmor/usage/#use-in-github-actions
Ran Zizmor locally to fix up any open issues on existing GitHub Actions. There are some caching features which were disabled based on https://woodruffw.github.io/zizmor/audits/#cache-poisoning
This was originally done in https://github.com/mozilla/fxa/pull/18628 but reverted. Requiring pinning was released after that PR was put up causing some issues. Going forward you may need to adjust things in Zizmor or other Github Actions as new checks are added to the tool.
> Zimzor static analysis update

- libs/payments/stripe/src/lib/stripe.client.ts
Because:
* Currently, while payments do go through for paypal purchases in sp3 (and the subscription is successfully created), the user is directed to the error page.
* The caching layer persists values, and payment validation errors were being thrown because the retrieved value was not updated as expected.
This commit:
* Removes the caching functionality on the payment intent
Closes #FXA-11527
> fix(payments-next): Subscriptions using paypal entering error page

- packages/fxa-settings/src/models/hooks.ts
- If experiment info is undefined, we shouldn't set anything.
- Checks that experiment info was actually returned before setting features.
Closes: FXA-11564
> bug(settings): Make sure experiment info is defined

- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/cart.types.ts
- When a customer changes location that results in price change, the cart isn't update with the new amount, resulting in an error during checkout.
- On location update, if currency is changed, fetch the new subtotal for that price and currency and update the cart.amount
Closes: #FXA-11290
> fix(next): location change doesnt update cart amount

- libs/payments/ui/src/lib/client/components/CheckoutForm/index.tsx
- The Payment Element is configured never show the country and postal code.
- Remove config values hiding country and postal.
- By default, set the Country to match the Tax Address country
Closes: FXA-11451
Changing country in tax location will automatically update the payment element country
> fix(next): show default address on payment element

- libs/payments/eligibility/src/lib/eligibility.manager.spec.ts
- libs/payments/eligibility/src/lib/eligibility.manager.ts
- When a customer is subscribed to a non-multi currency price and attempts to subscribe to the multi currency version of that price, the eligibility manager does not mark these as having a "SAME" overlap.
- Update logic checking if target price is the same as subscribed price, by checking if the product and interval info is the same
Closes: FXA-11252
To reproduce this issue follow these steps.
* Subscribe to a monthly plan, for product A on SP2 (This will select a non-multi-currency price)
* With the same user, subscribe to a monthly plan for product A on SP3. (This will select a multi-currency price)
* Expected behavior, see screen informing customer they are already subscribed to the product.
> fix(next): match same eligiblity on product and interval

- libs/payments/events/src/lib/emitter.factories.ts
- libs/payments/events/src/lib/emitter.service.spec.ts
- libs/payments/events/src/lib/emitter.service.ts
- libs/payments/events/src/lib/emitter.types.ts
- libs/payments/metrics/src/lib/glean/glean.factory.ts
- libs/payments/metrics/src/lib/glean/glean.manager.ts
- libs/payments/metrics/src/lib/glean/glean.types.ts
- libs/payments/metrics/src/lib/glean/utils/mapSubscriptionCancellation.spec.ts
- libs/payments/metrics/src/lib/glean/utils/mapSubscriptionCancellation.ts
- libs/payments/webhooks/src/index.ts
- libs/payments/webhooks/src/lib/subscriptionHandler.service.spec.ts
- libs/payments/webhooks/src/lib/subscriptionHandler.service.ts
- libs/payments/webhooks/src/lib/util/determineCancellation.spec.ts
- libs/payments/webhooks/src/lib/util/determineCancellation.ts
- libs/shared/metrics/glean/src/registry/subplat-backend-metrics.yaml
- Updates determineCancellation to return one of 3 reasons for cancellation: “customer_initiated”, “involuntary”, “redundant”
Closes: FXA-11537
> feat(payments): Update SubscriptionEventsService to check subscription metadata for redundantCancellation property

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/layout.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/new/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/layout.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(startLayout)/layout.tsx
- apps/payments/next/app/[locale]/layout.tsx
- libs/payments/ui/src/lib/client/components/Header/index.tsx
- When a customer has manually changed their location on the checkout page, and then signs out, the previously set location is not retained. This could result in the user being navigated to their default location instead of the location selected before sign out.
- Moves the Heading component into checkout and upgrade layouts
- Pass countryCode and postalCode to the /new page when a customers signs out and is redirected there.
Closes: FXA-11452
> fix(next): sign out retains current location

- packages/fxa-auth-server/lib/oauth/assertion.js
- packages/fxa-auth-server/lib/routes/defaults.js
- packages/fxa-auth-server/test/oauth/api.js
- packages/fxa-auth-server/test/oauth/assertion.js
- BrowserID assertions are complex and we no longer use them in our services
- We want to reduce code and service complexity
- Removes BrowserID assertion support from the OAuth server
- Updates the `verifyAssertion` function to exclusively handle JWT verification
- Removes BrowserID configuration fields (`issuer`, `verificationUrl`) from the `/config` endpoint in `lib/routes/defaults.js`
- Replaces BrowserID assertion mocks with JWT-based equivalents in the test suite (`test/oauth/api.js`, `test/oauth/assertion.js`)
- Removes BrowserID-specific test cases and updates integration tests to use JWT assertions for all OAuth flows.
N/A - No user interface changes.
> feat(oauth): Remove BrowserID assertion logic from oauth server

- packages/fxa-graphql-api/src/gql/account.resolver.ts
- packages/fxa-graphql-api/src/gql/session.resolver.ts
Because:
- we are doubling the ip based counts in customs when _both_ gql-api and auth-server (in response to gql-api) check customs on an action
- a lot has changed since GqlCustomsGuard was added as some sort of preventive measure to denial-of-service from service call fan-out
- we've added gql allowlist
- we use Cloud Armor for ip based rate limiting
- when GqlCustomsGuard rate limits a user, they see a generic error on the frontend
This commit:
- removes GqlCustomsGuard if the resolver calls an auth-server API endpoint that also checks customs
> fix(gql-api): remove GqlCustomsGuard from select resolvers

- libs/payments/metrics/src/lib/glean/glean.manager.spec.ts
- libs/payments/metrics/src/lib/glean/glean.manager.ts
Because:
* glean reporting needs to be either disabled during CI or tagged as such
This commit:
* disables glean reporting during CI
Closes #11516 
> feat(payments-next): Disable glean in CI

- libs/google/src/lib/google.constants.ts
- Our postal code validation for romanian postal codes was too permissive
- Increases the strictness of our postal code validation for romania
Closes FXA-11482
> fix(next): stricter postal code validation for romania

- packages/fxa-auth-server/lib/inactive-accounts/index.ts
- packages/fxa-auth-server/scripts/delete-inactive-accounts/enqueue-inactive-account-deletions.ts
Because:
- we saw some "entity already exists" errors reported to Sentry when creating Google Cloud Task for the second inactive account notification email
This commit:
- updates the error detection to use the error message only
- I originally used 10 as the error code as that was what I saw in the error during development (and still see at the time of this patch); that value does not match the documented gRPC constant for that type of error.  But this wouldn't be the first time I've noticed a discrepancy between the gRPC stuff and nodejs + REST.
> fix(cloud tasks): ignore duplicate inactive acct email task error by message

- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/customer/src/lib/types.ts
- On a subscription upgrade, `plan_change_date` and `previous_plan_id` need to be added to the subscription metadata.
- Adds missing `plan_change_date` and `previous_plan_id` to subscription updates.
Closes: FXA-11540
> fix(next): missing metadata on upgrade

- packages/functional-tests/pages/config.ts
- packages/functional-tests/pages/signup.ts
- packages/functional-tests/tests/key-stretching-v2/changePassword.spec.ts
- packages/functional-tests/tests/key-stretching-v2/recoveryKey.spec.ts
- packages/functional-tests/tests/key-stretching-v2/recoveryKeyUpgrade.spec.ts
- packages/functional-tests/tests/key-stretching-v2/resetPassword.spec.ts
- packages/functional-tests/tests/key-stretching-v2/signinBlocked.spec.ts
- packages/functional-tests/tests/key-stretching-v2/signup.spec.ts
- packages/functional-tests/tests/key-stretching-v2/totp.spec.ts
- packages/functional-tests/tests/misc/recoveryKeyPromoInline.spec.ts
- packages/functional-tests/tests/misc/relayIntegration.spec.ts
- packages/functional-tests/tests/oauth/signin.spec.ts
- packages/functional-tests/tests/oauth/syncSignIn.spec.ts
- packages/functional-tests/tests/react-conversion/oauthSignin.spec.ts
- packages/functional-tests/tests/react-conversion/oauthSignup.spec.ts
- packages/functional-tests/tests/react-conversion/signup.spec.ts
- packages/functional-tests/tests/settings/changeEmail.spec.ts
- packages/functional-tests/tests/settings/multitab.spec.ts
- packages/functional-tests/tests/syncV3/signUpWithCWTS.spec.ts
- packages/fxa-settings/src/components/FormSetupAccount/index.tsx
- packages/fxa-settings/src/components/FormSetupAccount/interfaces.ts
- packages/fxa-settings/src/lib/glean/index.test.ts
- packages/fxa-settings/src/pages/Signup/container.tsx
- packages/fxa-settings/src/pages/Signup/en.ftl
- packages/fxa-settings/src/pages/Signup/index.test.tsx
- packages/fxa-settings/src/pages/Signup/index.tsx
- packages/fxa-settings/src/pages/Signup/interfaces.ts
- packages/fxa-shared/metrics/glean/web/index.ts
- We want to remove the age check requirement to improve registration conversion and simplfy our code
- Removes the age input field, error handling, and "Why do we ask?" link from the signup form
- Updates signup page logic to remove age validation, `tooyoung` cookie, and redirection to `/cannot_create_account`
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11545
> chore(deps): Remove age check field in signup

- packages/fxa-auth-server/test/scripts/bulk-mailer.js
https://github.com/mozilla/fxa/blob/f38938c0805df6e3ca0b9773a2e1eb266cbc7775/packages/fxa-auth-server/test/scripts/bulk-mailer.js#L256-L256
fix the issue will replace the use of `execAsync` with `execFileAsync` (or `execFile` if asynchronous behavior is not required). This approach allows us to pass the command and its arguments separately, ensuring that the shell does not interpret the file path or other arguments. Specifically:
1. Extract the `node` command and its arguments into separate variables.
2. Use `execFileAsync` to execute the command, passing the arguments as an array.
3. Ensure that the `USER_DUMP_PATH` and other arguments are passed as-is without being concatenated into a single string.
This change will prevent any unintended shell interpretation of the file path or other …
> fix(feat): Shell command built from environment values

- packages/fxa-auth-server/scripts/recorded-future/check-and-reset.ts
- packages/fxa-auth-server/test/scripts/recorded-future/check-and-reset.ts
Because:
- we need to search for more than the accounts.firefox.com domain in Recorded Future
This commit:
- adds a param to the script for search domains
> feat(scripts): search multpl domains in Recorded Future

- libs/payments/customer/src/lib/invoice.manager.ts
- When an existing customer changes their location at checkout, which results in a change in price, the new price is not shown as expected, since the customers stored location is used instead.
- If taxAddress is provided to InvoiceManager.previewInvoice, then use the provided taxAddress instead of the customers stored address.
Closes: FXA-11582
> fix(next): show update price for existing customers

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/needs_input/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/needs_input/page.tsx
- libs/payments/customer/src/lib/util/determinePaymentMethodType.ts
- libs/payments/stripe/src/lib/stripe.client.ts
- libs/payments/ui/src/lib/client/components/PaymentSection/index.tsx
- libs/payments/ui/src/lib/client/components/StripeWrapper.tsx
- libs/payments/ui/src/lib/nestapp/validators/GetNeedsInputActionResult.ts
- If a customer has existing payment methods on file, but no active subscriptions, then allow customers to pay with any payment method
- Do not remove external_paypal as a payment method option if a customer has no active subscriptions.
- If a customer has active subscriptions, only allow the current payment method on file.
Closes: FXA-11453
> fix(next): allow all payment methods if no active subs

- packages/fxa-content-server/server/lib/configuration.js
- packages/fxa-settings/src/lib/config.ts
Because:
- we want to have a feature flag for using a recovery phone code for 2FA during password reset
This commit:
- add a feature flag to Settings, defaults to false
> feat(recovery phone): add feature flag for password reset routes

- _scripts/check-db-patcher.sh
- _scripts/pm2-all.sh
* We want to provide clear error messaging when stack startup fails
* Add more error handling and messages for db patch checker, node version check on startup, nx project startup
Re-opening from new branch, previous had issues with unrelated filename case changes.
> task(startup): Add messaging for db patch checker and start script

- packages/fxa-settings/src/components/PreparedImage/index.tsx
- Icon aria labels are not being translated; defaulting to English
- Fixes the aria-label key within the attrs prop of the FtlMsg component
Closes: FXA-11374
> fix(fxa-settings): Fluent attrs require kebob-case aria-label

- packages/fxa-settings/src/lib/gql.ts
- packages/fxa-settings/src/pages/InlineRecoverySetup/container.tsx
- packages/fxa-settings/src/pages/InlineTotpSetup/container.tsx
- packages/fxa-settings/src/pages/Signin/index.tsx
- This error was showing up in many Sentry bread crumbs and being logged to the console.
- This console corrects the write that was causing this problem.
The call stack gets spliced during this write operation, so it becomes difficult to pin down the location where the bad write actually occurs. It takes quite a bit of debugging to find the exact spot it happens. The best way to validate this fix is to run the app, and navigate to http://localhost:3030. Without this change you should observer the error in the console, then apply the patch and navigate to http://localhost:3030/ again and you should see the error is no longer present.
> bug(settings): Fix errors about `Missing field 'account' while writing result {}`

- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/checkout.factories.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/customer/src/lib/types.ts
- libs/payments/eligibility/src/lib/eligibility.factories.ts
- libs/payments/eligibility/src/lib/eligibility.manager.spec.ts
- libs/payments/eligibility/src/lib/eligibility.manager.ts
- libs/payments/eligibility/src/lib/eligibility.service.spec.ts
- libs/payments/eligibility/src/lib/eligibility.service.ts
- libs/payments/eligibility/src/lib/eligibility.types.ts
- libs/payments/webhooks/src/lib/util/determineCancellation.ts
- packages/fxa-auth-server/lib/payments/capability.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- packages/fxa-shared/subscriptions/types.ts
- We want to cancel any plans that have an overlap with your upgraded plan
- Cancels any overlapping plans when a user upgrades
Closes FXA-11534
Closes FXA-11535
Closes FXA-11536
> feat(payments): cancel redundant plans when upgrading

- packages/fxa-settings/src/lib/gql.test.ts
- packages/fxa-settings/src/lib/gql.ts
- packages/fxa-settings/src/lib/nimbus/index.ts
- We were seeing network errors in sentry, but couldn't tell where they originated.
- Adds apollo links so we can get more visibility into gql queries
- Adds a comment about how sentry records failed fetch events, since the Sentry UI is a little ambiguous
Closes: FXA-10879 (Partially)
(This should help us determine what GQL are actually failing. The issue will still persist until the underlying problems are corrected.)
> task(settings): Improve error handling for gql errors and network errors

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/subscription_replaced.json
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
- sends subscriptionReplacedEmail for redundant cancellation
Closes: FXA-11538
> fix(auth): Send SubscriptionReplacedEmail for redundant cancellations

- packages/fxa-settings/src/pages/Signin/SigninTokenCode/en.ftl
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/en.ftl
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx
- The “Enter your confirmation code” page has UI issues on mobile when using a long email address
- breaks long email into multiple lines so that the lines does not grow out of the box (in both ConfirmSignupCode and SigninTokenCode)
Closes: FXA-10726
> fix(settings): break long email in verification code pages

- package.json
- packages/fxa-settings/package.json
- yarn.lock
- [@react-pdf version 3.3.0](https://github.com/diegomura/react-pdf/releases/tag/%40react-pdf%2Frenderer%403.3.0) introduced WASM, our CSP is now flagging failures and our pdf does not generate
- `@react-pdf` does not keep transitive dep locked, and despite pinning `@react-pdf` to a known working version <3.3, the transitive deps automatically upgrade and violate our CSP
- bumps `@react-pdf/renderer` (the main package) to 3.2.1 – the latest release before WASM introduction
- pins breaking transitive dependencies to versions specified for 3.2.1
Closes: FXA-11626
> fix(settings): pin react-pdf sub-dependencies

- packages/fxa-content-server/app/scripts/lib/nimbus/index.ts
- We had a perf metrics dip
- We know cirrus is having some issues
- Comments out the code that fetches nimbus experiments
- Adds comment explaining how this is temporary.
Closes: FXA-11622
> task(content): Disable nimbus experiments request

- packages/fxa-auth-server/lib/customs.js
- packages/fxa-auth-server/test/local/customs.js
- We don't want to send values with high cardinality to stats
- Ensures retryAfter isn't sent
Closes: FXA-11492
> task(auth-server): Don't report retryAfter to statsd on customs check events

- packages/fxa-content-server/server/lib/beta-settings.js
- packages/fxa-content-server/tests/server/beta-settings.js
- packages/fxa-content-server/tests/server/fixtures/server-config-index.html
- packages/fxa-settings/public/index.html
- The lighthouse report said this was a good idea
- Adds preconnect definitions for our servers, which can save time
Closes: FXA-11616
> task(settings): Add preconnect directives

- packages/fxa-settings/src/components/Settings/ModalVerifySession/index.tsx
- “Verify” button becomes enabled while typing letters during the unverified session state (only happens at the first typing attempt)
- makes ModalVerifySession's input validation work on the first attempt
Closes: FXA-2704
> fix(settings): make ModalVerifySession's input validation work on the first attempt

- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/components/ErrorBoundaries/index.stories.tsx
- packages/fxa-settings/src/components/PasswordStrengthInline/index.test.tsx
- packages/fxa-settings/src/components/Settings/FlowRecoveryKeyDownload/index.test.tsx
- packages/fxa-settings/src/components/Settings/UnitRowTwoStepAuth/index.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/ConfirmBackupCodeResetPassword/container.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/ConfirmBackupCodeResetPassword/container.tsx
- packages/fxa-settings/src/pages/ResetPassword/ConfirmBackupCodeResetPassword/en.ftl
- packages/fxa-settings/src/pages/ResetPassword/ConfirmBackupCodeResetPassword/index.stories.tsx
- packages/fxa-settings/src/pages/ResetPassword/ConfirmBackupCodeResetPassword/index.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/ConfirmBackupCodeResetPassword/index.tsx
- packages/fxa-settings/src/pages/ResetPassword/ConfirmBackupCodeResetPassword/mocks.tsx
- packages/fxa-settings/src/pages/ResetPassword/ConfirmTotpResetPassword/container.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/ConfirmTotpResetPassword/en.ftl
- packages/fxa-settings/src/pages/ResetPassword/ConfirmTotpResetPassword/index.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/ConfirmTotpResetPassword/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/container.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/mocks.tsx
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/mocks.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/mocks.tsx
- packages/fxa-settings/src/pages/Signin/container.test.tsx
- packages/fxa-settings/src/pages/Signup/container.test.tsx
* We are setting up this flow to expand and include recovery phone option
* We want to simplify components and remove internal branches between 2FA TOTP and backup authentication codes
* We want to assign individual routes to each page
* We want to update to the new designs for these pages
* Split ConfirmTotpResetPassword into to components (adding ConfirmBackupCodeResetPassword)
* Update design of both pages
* Add missing localization
* Swap FormVerifyCode to FormVerifyTotp that disables input unless code of correct length is input
* Add container tests
* Fix act warning in CompleteResetPassword tests
Closes: FXA-11511
Latest design:
https://www.figma.com/design/Xnjs0YApSnC0CV6Ns5gCt4/2SV_Security_key_flow-Email_phone_number_2023?node-id=9947-15331&t=S …
> feat(settings): Split and update design ConfirmTotpResetPassword

- apps/payments/next/.env
- apps/payments/next/config/index.ts
- apps/payments/next/sentry.server.config.ts
- libs/payments/ui/src/lib/client/providers/ConfigProvider.tsx
- libs/payments/ui/src/lib/client/providers/Providers.tsx
- libs/shared/error/src/index.ts
- libs/shared/error/src/lib/error.ts
- libs/shared/error/src/lib/sanitizeExceptionsDecorator.ts
- libs/shared/sentry/src/lib/config-builder.ts
- libs/shared/sentry/src/lib/models/SentryConfigOpts.ts
- tsconfig.base.json
Because:
* Sentry should not be recording "something went wrong" errors
* Errors should be separated out to clientside and serverside sentry projects
This commit:
* prevents generic errors from propagating to sentry
* [creates a separate sentry project for payment-next client errors](https://mozilla.sentry.io/issues/?project=4509311130861568&referrer=sidebar&statsPeriod=48h)
Closes #FXA-11331
> fix(payments-next): Sentry reporting 'something went wrong' errors

- packages/fxa-settings/src/components/ChooseNewsletters/index.stories.tsx
- packages/fxa-settings/src/components/ChooseNewsletters/index.test.tsx
- packages/fxa-settings/src/components/ChooseNewsletters/index.tsx
- packages/fxa-settings/src/components/ChooseNewsletters/mocks.tsx
- packages/fxa-settings/src/components/ChooseNewsletters/newsletters.ts
- packages/fxa-settings/src/components/FormPasswordWithBalloons/index.tsx
- packages/fxa-settings/src/components/InputPassword/index.tsx
- packages/fxa-settings/src/components/InputText/index.tsx
- packages/fxa-settings/src/components/Settings/PageSecondaryEmailAdd/index.tsx
- packages/fxa-settings/src/pages/Signup/index.test.tsx
- We are disabling the newsletters field to help improvement registration
- Updates newsletter component to not render if no newsletters are set
- Auto focus on our set password field
- Emits the `engage` event when user starts typing password instead of on focus of password field
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11614
I had a bunch of issues getting auto focus to work correctly. I believe this was mostly because of using react hook forms to handle form submission. I opted to have an additional inputRef that allowed for `focus` and `click` events. There might an easier solution but I couldn't think of another way.
> feat(reg): remove newsletters from reg form, autofocus set password

- packages/fxa-content-server/pm2.config.js
- Content server wouldn't restart on changes, and this could catch developers off guard.
- Adds pm2 watch config for content server
> chore(content): Make content-server watch files

- libs/payments/cart/src/lib/cart.manager.in.spec.ts
- libs/payments/cart/src/lib/cart.manager.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- libs/shared/error/src/lib/sanitizeExceptionsDecorator.spec.ts
- libs/shared/error/src/lib/sanitizeExceptionsDecorator.ts
- libs/shared/metrics/statsd/src/lib/statsd.decorator.spec.ts
- libs/shared/metrics/statsd/src/lib/statsd.decorator.ts
- We want to see metrics for each server action
- Adds a statsd counter for each server action
Closes FXA-11593
Closes FXA-11578
> feat(payments-next): add metrics for each server action, better tagging

- packages/fxa-react/components/Footer/index.tsx
- packages/fxa-react/components/LogoLockup/index.tsx
- packages/fxa-react/styles/focus.css
- packages/fxa-react/styles/index.css
- packages/fxa-settings/src/components/Banner/index.tsx
- packages/fxa-settings/src/components/BrandMessaging/index.tsx
- packages/fxa-settings/src/components/ButtonBack/index.tsx
- packages/fxa-settings/src/components/InputPassword/index.tsx
- packages/fxa-settings/src/components/ResetPasswordWarning/index.tsx
- packages/fxa-settings/src/components/Settings/AlertBar/index.tsx
- packages/fxa-settings/src/components/Settings/BentoMenu/index.tsx
- packages/fxa-settings/src/components/Settings/ConnectAnotherDevicePromo/index.tsx
- packages/fxa-settings/src/components/Settings/DropDownAvatarMenu/index.tsx
- packages/fxa-settings/src/components/Settings/HeaderLockup/index.tsx
- packages/fxa-settings/src/components/Settings/Modal/index.tsx
- packages/fxa-settings/src/components/Settings/Nav/index.tsx
- packages/fxa-settings/src/components/ThirdPartyAuth/index.tsx
- packages/fxa-settings/src/styles/switch.css
- Front-page Settings elements focus use system default outlines.
- makes elements use proper focus outline colors and adds rounded corners to focus outlines.
Closes: FXA-5787
etc. Please checkout Storybook for full detail.
Made some changes to the spacing (e.g., padding -> margin, margin -> gap) to make the outline box sizing look right. No actual layout is changed.
> fix(settings): make elements use proper focus colors

- packages/fxa-settings/src/pages/Index/container.test.tsx
- packages/fxa-settings/src/pages/Index/container.tsx
- There is a potential for a momentary flash of the email-first page while already signed in
- Adds a loading state and spinner to hide the email-first page until ready
Closes: FXA-11642
> fix(email-first): fix flicker of email-first page

- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
- adds in tests for https://github.com/mozilla/fxa/pull/18829
> chore(auth): Add stripe and stripe-webhooks tests for SubscriptionReplacedEmail

- libs/payments/ui/src/lib/server/components/UpgradePurchaseDetails/en.ftl
- libs/payments/ui/src/lib/server/components/UpgradePurchaseDetails/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/en.ftl
- packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.test.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/Cancel/en.ftl
- revises Subscription Management page to remove interval and add credit messaging
- revises Upgrade page to add credit messaging in both 2.0 and 3.0
Closes: FXA-11634
**Credit**
**Prorated**
**Zero - No additional cost/credit**
**Credit**
**Prorated**
**Zero - No additional cost/credit**
> feat(payments): Revise Subscription Management page and Upgrade page to handle credits

- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/cart.types.ts
- libs/payments/customer/src/index.ts
- libs/payments/customer/src/lib/error.ts
- libs/payments/customer/src/lib/factories/pricing-for-currency.factory.ts
- libs/payments/customer/src/lib/price.manager.spec.ts
- libs/payments/customer/src/lib/price.manager.ts
- libs/payments/customer/src/lib/subscription.manager.ts
- libs/payments/customer/src/lib/types.ts
- libs/payments/customer/src/lib/util/determinePriceUnitAmount.spec.ts
- libs/payments/customer/src/lib/util/determinePriceUnitAmount.ts
- libs/payments/eligibility/src/lib/eligibility.service.ts
- libs/payments/stripe/src/lib/factories/price.factory.ts
- libs/payments/stripe/src/lib/stripe.client.ts
- libs/payments/stripe/src/lib/stripe.client.types.ts
- libs/payments/ui/src/lib/client/components/CheckoutForm/index.tsx
- libs/payments/ui/src/lib/nestapp/validators/GetCartActionResult.ts
- libs/payments/ui/src/lib/server/components/UpgradePurchaseDetails/index.tsx
- The purchase details component for upgrades shows the incorrect interval and currency amount during an upgrade.
- Fetches the correct price amounts for the customers currency
- Converts Stripe intervals to SubplatIntervals
Closes: #FXA-11605 #FXA-11457
> feat(next): upgrade shows incorrect interval

- packages/fxa-content-server/server/lib/beta-settings.js
- Static html that is generated and then deployed to the CDN didn't get preconnect directives replaced.
- Makes sure static html that is deployed to CDN also gets its preconnect directives updated.
Closes: FXA-11692
> bug(content): Pre-connects weren't getting replaced in 'static' html

- apps/payments/next/next.config.js
##Because
- when checking errorReasonId in Admin Panel, the value provided was `d` due to class names being minified
- sets `serverMinification: false` in next.config.js
> fix(payments-next): fix class names being minified

- packages/fxa-settings/src/components/ThirdPartyAuth/index.test.tsx
- packages/fxa-settings/src/components/ThirdPartyAuth/index.tsx
- packages/fxa-settings/src/lib/glean/index.ts
- packages/fxa-settings/src/models/pages/index/query-params.ts
- packages/fxa-settings/src/models/pages/signin/query-params.ts
- packages/fxa-settings/src/models/pages/signup/query-params.ts
- packages/fxa-settings/src/pages/Index/container.tsx
- packages/fxa-settings/src/pages/Index/index.test.tsx
- packages/fxa-settings/src/pages/Index/index.tsx
- packages/fxa-settings/src/pages/Index/interfaces.ts
- packages/fxa-settings/src/pages/Index/mocks.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
- packages/fxa-settings/src/pages/Signin/index.test.tsx
- packages/fxa-settings/src/pages/Signin/index.tsx
- packages/fxa-settings/src/pages/Signin/interfaces.ts
- packages/fxa-settings/src/pages/Signup/container.tsx
- packages/fxa-settings/src/pages/Signup/index.tsx
- packages/fxa-settings/src/pages/Signup/interfaces.ts
- packages/fxa-shared/metrics/glean/web/index.ts
- This currently does not deeplink into the third party auth flow
- Adds support to deeplink in our React email first pages
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11678
To test goto `http://localhost:8080` and click `Sign In (Google)`. You will need to have Google auth configured locally.
> fix(auth): Fix issues with deeplinking third party auth

- package.json
- packages/fxa-auth-server/.eslintignore
- yarn.lock
- pinning old packages prohibits security patches and feature adds
- removes the yarn resolution for eslint-plugin-import
Closes: FXA-11693
After removal, I confirmed all dependent installs of eslint-plugin-import are >= 2.30, which satisfies the original resolution.
As a bonus, I attempted to move all eslint packages to root, but they seem tightly coupled to individual packages with specific plugins and versions.  I got as far as NX breaking when attempting to run lint – I believe we might need to set individual NX project.json files within each FxA package specifying eslint target, or something similar.
> task: audit yarn resolutions – eslint-plugin-import

- packages/fxa-settings/src/components/FormVerifyCode/index.stories.tsx
- packages/fxa-settings/src/components/FormVerifyCode/index.test.tsx
- packages/fxa-settings/src/components/FormVerifyCode/index.tsx
- packages/fxa-settings/src/components/FormVerifyCode/mocks.tsx
- packages/fxa-settings/src/components/InputText/index.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.test.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/interfaces.ts
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/mocks.tsx
- we want to automatically submit email confirmation code form when a valid code is pasted.
- implements such feature for email registration in non-sync flows.
Closes: FXA-11671
> feat(auth): auto submit email confirmation code form on paste (non-sync only)

- .circleci/config.yml
- libs/accounts/rate-limit/src/lib/rate-limit.spec.ts
- libs/accounts/rate-limit/src/lib/rate-limit.ts
- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/customs.js
- packages/fxa-auth-server/lib/error.js
- packages/fxa-auth-server/test/local/customs.js
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-auth-server/test/mocks.js
- We want to test out the new customs library with a single call
- Wires up the new rate limit library into auth-server's customs wrapper
- Ensures metrics are preserved
- Injects rate limit instance into auth-server's customs wrapper
- Adds config for accountStatusCheck rate limit rule
- Fixes tsc compiler error that wasn't caught by esbuild in the rate-limit lib.
- Adds switch to existing customs.js module so that if a new rule has been configured for the supplied action, the new rate limit will be used instead of the customs server.
- Disables rate-limit rules for functional tests
Closes: FXA-11607
The format for customs rules configuration is specified in …
> task(auth-server): Replace accountStatusCheck customs rule with new rate limit library call

- packages/fxa-settings/src/components/ThirdPartyAuth/index.tsx
- packages/fxa-settings/src/pages/PostVerify/ThirdPartyAuthCallback/index.tsx
- When we switched over to React email first, the flowId value switched to `flow_id`
- Checks and uses `flow_id` if available
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11706
> fix(auth): Fix bug related to flowId and third party auth

- _dev/docker/ci-lockfile-generator/Dockerfile
- _dev/docker/ci/Dockerfile
- Mismatch in node versions was causing nx cache misses
- Update all node images to use 22.15.1, matching the current repo required node version.
> fix(circleci): update all node images to 22.15.1

- packages/fxa-settings/src/pages/Signin/index.test.tsx
- packages/fxa-settings/src/pages/Signin/index.tsx
* For sync sign in with an account that has a linked account but no password, show "Sign in" heading and not "Enter your password"
* Updates the condition for the heading selection
> fix(settings): Show correct heading for sync signin with no password set

- package.json
- yarn.lock
- pinning old packages prohibits security patches and feature adds
- removes the yarn resolution for @graphql-typed-document-node/core
Closes: FXA-11701
At the time of this writing, the latest @graphql-typed-document-node/core release is 3.2.0 (which was pinned via resolution).  After removing the resolution and auditing via `yarn why`, the resolved transitive dependencies remain at the latest 3.2.0 version.
> task: audit yarn resolutions – @graphql-typed-document-node/core

- package.json
- yarn.lock
- pinning old packages prohibits security patches and feature adds
- removes the yarn resolution for @types/node
Closes: FXA-11707
This also removes `zod` which was temp-installed as a noop cache-buster for updated Node version.
I attempted to also remove @types/react but it's a transitive dep of other packages that cannot be easily updated (@material-ui/core, @types/react-is, tap)
> task: audit yarn resolutions – @types/node

- libs/accounts/rate-limit/README.md
- libs/accounts/rate-limit/src/lib/rate-limit.in.spec.ts
- libs/accounts/rate-limit/src/lib/rate-limit.spec.ts
- libs/accounts/rate-limit/src/lib/rate-limit.ts
- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/customs.js
- packages/fxa-auth-server/test/local/customs.js
- We want the ability to skip customs checks for certain emails, ips, or uids.
- This was supported in the previous version of customs, and useful for development or smoke testing.
- Adds ability to configure and ignore certain ips, email, uids
- Wires this up in auth-server
Closes: FXA-11663
> Support rate limit allow lists

- libs/payments/paypal/src/lib/paypalBillingAgreement.manager.spec.ts
- libs/payments/paypal/src/lib/paypalBillingAgreement.manager.ts
- PaypalBillingAgreementManager returns billing agreement even if its status is not active.
- Update method to only return active billing agreement ids.
Closes: #FXA-11679
> fix(paypal): do not return inactive billing agreemnt ids

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/processing/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/processing/page.tsx
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/ui/src/lib/actions/getCartOrRedirect.ts
- libs/payments/ui/src/lib/actions/getCartState.ts
- libs/payments/ui/src/lib/actions/index.ts
- libs/payments/ui/src/lib/actions/validateCartStateAndRedirect.ts
- libs/payments/ui/src/lib/client/components/PaymentInputHandler/index.tsx
- libs/payments/ui/src/lib/client/components/PaymentStateObserver/index.tsx
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- libs/payments/ui/src/lib/nestapp/validators/GetCartStateActionArgs.ts
- libs/payments/ui/src/lib/nestapp/validators/GetCartStateActionResult.ts
- We're exceeding Stripe rate limits with payments-next
- Greatly reduces the number of getCart calls during checkout
Relates to FXA-11715
> feat(payments-next): reduce getCart & Stripe calls

- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- updates the amount for subscription metadata from the cart amount to the unit amount upon subscription creation and upgrade via 3.0 for multi-currency prices
- adds currency and (unit) amount to subscription metadata for subscription upgrade via 2.0
Closes: FXA-11683
> feat(payments-cart): Updates amount in metadata to unit amount

- packages/fxa-content-server/server/lib/routes/react-app/index.js
- Desktop launches its pairing screen with `/oauth` path containing pairing query params
- React pages try to create an OAuth integration and fails beacause it does not have all the correct oauth params 
- Removes `oauth` from our email first roll out, note that I think this won't have a big impact on other RPs since the `/authorization` endpoint also handles OAuth authenication
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11702
> fix(pairing): Remove `/oauth` from react email first rollout

- packages/fxa-settings/src/pages/Legal/Privacy/index.test.tsx
- packages/fxa-settings/src/pages/Legal/Privacy/index.tsx
- packages/fxa-settings/src/pages/Legal/Terms/index.test.tsx
- packages/fxa-settings/src/pages/Legal/Terms/index.tsx
This reduces the gzip'd main js bundle by a little over 87 kB (from ~462 kB to ~374 kB), using commit 5e3506e4d8 as the baseline.
> chore(perf): load LegalWithMarkdown lazily

- packages/fxa-settings/src/lib/channels/firefox.ts
* We will need this webchannel for upcoming changes to sync registration
* Adds the command to available channels in fxa-settings
Closes: FXA-11741
> feat(webchannel): Add support for SYNC_PREFERENCES command

- packages/functional-tests/pages/layout.ts
- packages/functional-tests/tests/syncV3/fxDesktopHandshake.spec.ts
- packages/functional-tests/tests/syncV3/fxDesktopHandshakeNonSync.spec.ts
- packages/functional-tests/tests/syncV3/fxDesktopV3ForceAuth.spec.ts
- We had a skipped and flaky syncV3 test
- Removes the skip on `blocked with an registered email, unregistered uid`
- Fixes a race condition in `Non-Sync - no user signed into browser, no user signed in locally` which has been flaking in CI.
Closes: (FXA-7108)
> test(function): add back skipped syncV3 test and fix flaky test

- packages/fxa-settings/src/components/Tooltip/index.stories.tsx
- packages/fxa-settings/src/components/Tooltip/index.tsx
- Error tooltip text is centered and should be RTL or LTR
- makes tooltip text start-aligned instead of centered.
- fixes the bug where a tooltip is limited to have half the width of its parent when anchor position is set to middle.
Closes: FXA-11351
LTR:
RTL:
anchor at middle:
> fix(settings): make tooltip text start-aligned instead of centered

- libs/payments/ui/src/lib/server/components/UpgradePurchaseDetails/index.tsx
- Prorated amount is cut off in certain languages.
- Prevents prorated price from shrinking.
Closes: #FXA-11648
> fix(payments-next):Truncated price in upgrade page

- packages/fxa-react/lib/utils.tsx
- packages/fxa-settings/src/pages/Signin/SigninPushCode/container.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/index.test.tsx
- packages/fxa-settings/src/pages/Signin/index.test.tsx
- packages/fxa-settings/src/pages/Signin/interfaces.ts
- packages/fxa-settings/src/pages/Signin/utils.ts
- When navigating to RPs the oauth signin page is added to the browser history.
- Use location.replace() instead of location.href so that hardNavidations do not add a new record to history.
Closes: #FXA-11700 #FXA-11728
Before - Note the additional Mozilla Accounts
After
> feat(react): navigate to RPs without adding to browser history

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/error/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/needs_input/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/processing/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/start/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/success/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/error/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/needs_input/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/processing/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/success/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(startLayout)/start/page.tsx
- libs/payments/ui/src/index.ts
- libs/payments/ui/src/lib/utils/en.ftl
- libs/payments/ui/src/lib/utils/getPageMetadataFtlInfo.ts
- libs/payments/ui/src/lib/utils/pageMetadata.ts
- libs/payments/ui/src/server.ts
- titlePrefix and description were hardcoded values and not localized.
- Adds localization to titlePrefix and description.
Closes: #FXA-11717
> fix(payments-next): Add localization to page metadata

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/error/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/error/page.tsx
- apps/payments/next/app/[locale]/en.ftl
- apps/payments/next/app/[locale]/error.tsx
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/cart.utils.ts
- libs/payments/ui/src/lib/utils/getErrorFtlInfo.ts
- libs/shared/db/mysql/account/src/lib/kysely-types.ts
- the error page does not reflect the correct error message
- updates the error message for blocked IAP subs
Closes: FXA-11699
**Mobile**
**Tablet**
**Desktop**
> fix(payments): Update error message for customers with active IAP subscription

- libs/accounts/rate-limit/src/lib/rate-limit.provider.ts
- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-graphql-api/src/config.ts
- packages/fxa-shared/db/config.ts
- We wanted to have a clean slate for rate limiting db state
- We've stood up a separate instance in staging
- Adds config for a 'ratelimit' Redis instance
Initially it seemed like we could just use the the custom's server redis instance, but ultimately decided it would be better to keep these DBs separate. There's a couple reasons for this:
- Easier to roll back
- Ensures no impact to existing customs service
- Allows us to scale individually
- Don't have to worry about old keys sticking around after fully migrating to new customs approach
> task(auth,graphql): Configure separate redis instance for rate limiting

- libs/payments/ui/src/lib/utils/en.ftl
- The coupon error messages were not being localized, and were hard coded to be in English.
- Puts the error messages in an .ftl file instead of just relying on the hard coded values.
Closes: #FXA-11758
> fix(payments-next): SP3 invalid coupon code not localized

- libs/payments/cart/src/lib/cart.error.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/customer/src/lib/customer.manager.ts
- libs/payments/stripe/src/lib/stripe.client.ts
Because:
* Stripe payments for a free purchase or for a reimbursement do not generate a payment intent as part of the payment process. The existing code throws an error for payments missing a payment intent
This commit:
* Adds in a special case for payments with a total amount of 0. Both "negative" payments (e.g. an upgrade to a lower price) and free purchases result in invoices with a total of 0, and a 'paid' status. Stripe automatically handles the application of negative purchase amounts towards the customer's account as a credit.
Closes #FXA-11413
> feat(payments-next): Enable no-charge payments with stripe

- packages/fxa-settings/src/index.tsx
- packages/fxa-settings/src/lib/config.ts
- packages/fxa-shared/sentry/browser.ts
- packages/fxa-shared/sentry/config-builder.ts
- packages/fxa-shared/sentry/models/SentryConfigOpts.ts
- We want to monitor the index page's performance
- Adds  the tracesSampler callback to the sentry config
- Hard codes this callback to only capture traces for '/'
Closes: FXA-11723
I was able to validate this manually by setting the `SENTRY_DSN_CONTENT` env, and adding a break point in the `tracesSampler` callback.
> task(settings): Target sentry tracing to capture metrics for index

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/layout.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/layout.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(startLayout)/layout.tsx
- fixes styling issue that caused SubscriptionTitle component to appear larger during loading state in Chrome
Closes: FXA-11288
> fix(payments-next): Component appears larger during loading state in Chrome

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/error/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/layout.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/start/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/location/page.tsx
- apps/payments/next/middleware.ts
- apps/payments/next/next.config.js
- libs/payments/ui/src/lib/client/components/BaseButton/index.tsx
- libs/payments/ui/src/lib/client/components/SelectTaxLocation/index.tsx
- libs/payments/ui/src/lib/client/components/SubmitButton/index.tsx
- The browser console on the Payments Next pages had a few CSP and React related errors.
- Missing HSTS header is resulting in poor scores on MDN HTTP Observatory Report.
- Adds unsafe-hashes for style-src
- Update CSP configuration in middleware.ts
- Fix ref related issues with BaseButton and SubmitButton.
- Adds missing HSTS header to middleware.
Closes: FXA-11266
The remaining CSP errors are not due to Payments Next's CSP config, and instead appear to be from Stripe/HCaptacha SDKs. These CSP errors do not appear in Chromes console.
> fix(next): resolve CSP and console errors

- packages/fxa-auth-server/lib/routes/session.js
- packages/fxa-auth-server/test/local/routes/session.js
- We should use this customs api since the request is authenticated
- calls `checkAuthenticated` instead of `check`
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11784?linkSource=email
> feat(customs): Use checkAuthenticated in `/session/verify_code` route

- package.json
- yarn.lock
- removes the resolutions for @svgr/webpack
Closes: FXA-11797
After removal, most @svgr/webpack versions resolve to `8.1.0` which satisfies the original resolution.  The `react-scripts` package pulls an older version 5.5.0.  This is probably ok, because `react-scripts` is more for one-off usage to eject CRA.  We can probably remove `react-scripts` entirely from our dependencies?
> task: audit yarn resolutions – @svgr/webpack

- libs/payments/cart/src/lib/cart.service.ts
Because:
* a variable could be undefined, and one of its attributes is accessed unsafely
This commit:
* safely access the attribute
Closes #N/A
> fix(payments-next): resolve linting error

- .circleci/config.yml
- libs/accounts/rate-limit/src/lib/config.ts
- packages/functional-tests/lib/ratelimit.ts
- packages/functional-tests/lib/targets/base.ts
- packages/functional-tests/lib/targets/local.ts
- packages/functional-tests/lib/targets/remote.ts
- packages/functional-tests/tests/key-stretching-v2/changePassword.spec.ts
- packages/functional-tests/tests/misc/authClientV2.spec.ts
- packages/functional-tests/tests/settings/changePassword.spec.ts
- packages/functional-tests/tests/settings/recoveryPhone.spec.ts
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/config/rate-limit-rules.txt
- packages/fxa-auth-server/lib/customs.js
- packages/fxa-auth-server/lib/routes/password.ts
- packages/fxa-auth-server/lib/routes/utils/signin.js
- packages/fxa-auth-server/scripts/delete-account.ts
- packages/fxa-auth-server/test/local/routes/password.js
- packages/fxa-auth-server/test/mocks.js
- packages/fxa-auth-server/test/remote/recovery_phone_tests.js
- packages/fxa-auth-server/test/test_server.js
- packages/fxa-graphql-api/nest-cli.json
- packages/fxa-graphql-api/src/config.ts
- packages/fxa-graphql-api/src/config/rate-limit-rules.txt
- We are getting ready to swap in the new rate limiting service
- Recreates the policies current held in the customs server, but in a flat file config format.
Closes: FXA-11608
> task(auth,gql): Configure default limiting rules

- packages/fxa-auth-server/config/rate-limit-rules.txt
- packages/fxa-auth-server/lib/customs.js
- packages/fxa-auth-server/lib/routes/devices-and-sessions.js
- packages/fxa-auth-server/lib/routes/password.ts
- packages/fxa-auth-server/lib/routes/recovery-key.js
- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/lib/routes/session.js
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/lib/routes/utils/signin.js
- packages/fxa-auth-server/test/local/customs.js
- packages/fxa-auth-server/test/local/routes/password.js
- packages/fxa-auth-server/test/local/routes/recovery-keys.js
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
- packages/fxa-auth-server/test/local/routes/session.js
- packages/fxa-auth-server/test/local/routes/totp.js
- We were tripping rate limits during functional tests
- Adds email to `customs.checkAuthenticated`
- Fixes the verifySessionCode check. We can check on UID here, so we don't need to also check IP since the endpoint is protected by a session token.
> bug(auth): Fix broken functional tests due to rate-limiting

- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-graphql-api/src/gql/account.resolver.ts
- packages/fxa-graphql-api/src/gql/dto/input/verify-totp.ts
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninTotpCode/container.tsx
- These flowId were missing
- Sets the flowId in settings and progagates them through gql and auth server
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11697
We have a lot of endpoints that don't specify `metricsContext` but could use them. I think we should try to find a way to automatically set this if avaiable.
> fix(metrics): Set flowId when user verifies totp session

- apps/payments/next/app/[locale]/auth/error/en.ftl
- apps/payments/next/app/[locale]/auth/error/page.tsx
- apps/payments/next/app/api/auth/callback/fxa/route.ts
- apps/payments/next/auth.ts
- libs/payments/events/src/lib/emitter.error.ts
- libs/payments/events/src/lib/emitter.factories.ts
- libs/payments/events/src/lib/emitter.service.spec.ts
- libs/payments/events/src/lib/emitter.service.ts
- libs/payments/events/src/lib/emitter.types.ts
- In an attempt to have statsd for all 3rd party dependencies, add statsd recording to Auth.js actions and events.
- On auth error, users are navigated to Auth.js default error page
- Add statsd counters signin, signout, prompt_none_fail and error
- Add custom Auth.js error page
Closes: #FXA-11670 #FXA-11754
To get to this Error Page follow these steps
1. Navigate to Checkout, enter email and hit "Sign in"
1. When on the FxA page, copy the URL
1. Complete the FxA Sign In, and navigate back to Checkout successfully
1. Open the copied URL into a new tab. This should load the FxA sign in page. Complete Sign In again
1. The new error page should be shown
> feat(next): add auth statsd and error page

- packages/functional-tests/tests/react-conversion/oauthPromptNone.spec.ts
- packages/fxa-settings/src/pages/Authorization/container.tsx
- packages/fxa-settings/src/pages/Index/container.tsx
- packages/fxa-settings/src/pages/Signin/container.test.tsx
- packages/fxa-settings/src/pages/Signin/interfaces.ts
- packages/fxa-settings/src/pages/Signin/utils.ts
- Users that have 2FA enabled are unable to login with prompt=none
- Correctly checks for the verification level of session and continues the flow
- Fixes a bug where it would call the `promptNoneHandler` twice
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11847
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11804
To test, enabled 2FA on your account and go through the prompt=none flow in 123Done.
> fix(prompt): Support prompt=none with 2FA, don't send two authorization reqs

- packages/fxa-auth-server/config/rate-limit-rules.txt
- packages/fxa-auth-server/lib/customs.js
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/emails.js
- packages/fxa-auth-server/lib/routes/recovery-codes.js
- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/lib/routes/session.js
- packages/fxa-auth-server/lib/routes/subscriptions/mozilla.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/support.ts
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-auth-server/test/local/routes/emails.js
- packages/fxa-auth-server/test/local/routes/recovery-codes.js
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
- packages/fxa-auth-server/test/local/routes/session.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- Check authenticated is a better option when a route requires a sessionToken
- Switches over to using `checkAuthenticated`
- Adds email as a parameter to the `checkAuthenticated` call, which allows us to use emails filters
Closes: FXA-11777
> task(auth): Use customs.checkAuthenticated where possible

- packages/fxa-settings/src/pages/Signin/container.tsx
- When a user has multiple accounts they can hit an expected error on sign in.
- This happens when the `lastStoredAccount()` exists but the `currentAccount()` does not.
- This can occur by signing into several different accounts and then logging out of settings.
- Ensures that `currentAcount()` is always set.
Closes: FXA-11843
When following the STR for FXA-11843, this patch fixes the error. Unfortunately there's still a glitchy UX where you sometimes have to click the sign in button twice. I feel like this patch is still worthwhile since the error is very disruptive. I'm still a bit perplexed what causes this strange UX behavior though.
> Fix error on signin with multiple accounts

- package.json
- yarn.lock
- the koa transitive dependency includes vulnerability alerts
- sets a resolution for minimum resolved koa version (2.16.1)
Closes: FXA-11799
I wanted to avoid using a resolution, but the vulnerability is a transitive dependency called by `@module-federation/dts-plugin` which eventually traces up to `@nx/react` – which was just upgraded to it's latest version 21.1.2.  Unfortunately the upgrade did not resolve the vulnerability.  
Also, koa is not installed as a caret range which means we can't upgrade it specifically.
> resolve koa vulnerability

- libs/payments/ui/src/lib/server/components/SubscriptionTitle/en.ftl
- libs/payments/ui/src/lib/server/components/SubscriptionTitle/index.tsx
- Revises title to `This subscription plan change is not supported` when `CartErrorReasonId` is either downgrade, invalid, or a blocked IAP
Closes: FXA-11839
> fix(payments-ui): Update SubscriptionTitle

- packages/fxa-settings/src/components/FormChoice/index.stories.tsx
- packages/fxa-settings/src/components/FormChoice/index.test.tsx
- packages/fxa-settings/src/components/FormChoice/index.tsx
- packages/fxa-settings/src/components/FormChoice/mocks.tsx
- packages/fxa-settings/src/components/Settings/FlowSetup2faBackupChoice/en.ftl
- packages/fxa-settings/src/components/Settings/FlowSetup2faBackupChoice/index.stories.tsx
- packages/fxa-settings/src/components/Settings/FlowSetup2faBackupChoice/index.test.tsx
- packages/fxa-settings/src/components/Settings/FlowSetup2faBackupChoice/index.tsx
- packages/fxa-settings/src/lib/glean/index.ts
- packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml
- packages/fxa-shared/metrics/glean/web/accountPref.ts
- packages/fxa-shared/metrics/glean/web/event.ts
- packages/fxa-shared/metrics/glean/web/index.ts
- The design for 2FA setup has been updated, and we have this new step in the flow
- Creates a new UI component with l10n, Glean metrics, storybook and unit tests
- Does not hook up the component in the setup flow - that will be done in a later ticket
Closes: FXA-10235
> feat(settings): create new FlowSetup2faBackupChoice component

- .gitignore
- packages/fxa-content-server/server/lib/beta-settings.js
- packages/fxa-settings/package.json
- packages/fxa-settings/scripts/build.js
Because:
- we want to verify/test the production build of Settings locally
This commit:
- adds 'script' to copy the build into content-server
- serves the static files when in development and proxy is off
- fixes 'undefined' being in the paths of the dev build
> chore(build): serve Settings locally without proxy

- libs/payments/ui/src/lib/client/components/CheckoutForm/index.tsx
- centers the PayPal button when PayPal is acting up
Before / After
> fix(payments-ui): Center PayPal button

- .vscode/settings.json
- libs/accounts/rate-limit/README.md
- libs/accounts/rate-limit/src/lib/config.ts
- libs/accounts/rate-limit/src/lib/models.ts
- libs/accounts/rate-limit/src/lib/rate-limit.in.spec.ts
- libs/accounts/rate-limit/src/lib/rate-limit.spec.ts
- libs/accounts/rate-limit/src/lib/rate-limit.ts
- We want to be able to block in ip+email
- Adds support for ip_email as a blocking option
- Creates a 'BlockOnOpts' types
- Cleans up method signatures
- Adds some new tests
Closes: FXA-11858 (Partially, #19016 is the second half)
To make review easier, this was broken up into two PRs. See #19016 for the other half of FXA-11858.
> task(rate-limit): Support blocking on 'ip_email'

- packages/fxa-react/lib/utils.tsx
- Our metrics before a hard navigate (ie navigating to an RP), might get dropped
- Adds a small delay before navigating away from React app
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11872
The Glean team wants a bugzilla and additionall steps to help troubleshoot. While we wait for that, I think its ok to land this change since it is small and gives incremental improvement. The 200ms delay is not noticable.
> fix(metrics): Add a small delay before hard navigating away from React app

- libs/accounts/rate-limit/README.md
- libs/accounts/rate-limit/src/lib/config.ts
- libs/accounts/rate-limit/src/lib/models.ts
- libs/accounts/rate-limit/src/lib/rate-limit.in.spec.ts
- libs/accounts/rate-limit/src/lib/rate-limit.spec.ts
- libs/accounts/rate-limit/src/lib/rate-limit.ts
- libs/accounts/rate-limit/src/lib/util.ts
- packages/fxa-auth-server/config/rate-limit-rules.txt
- packages/fxa-graphql-api/src/config/rate-limit-rules.txt
- In many cases a single default pule/policy is fine
- Creates a special case for the 'default' action. That any action can fallback into in the event a policy is not specified.
Closes: FXA-11838
Note, that this won't be truly turned on until we phase out the check for hasSupportedAction in customs.js. For now if an action isn't defined, we will fallback to using the customs server...
> task(rate-limit): Create default rate limit rule to fallback to

- yarn.lock
- the tar-fs transitive dependency includes vulnerability alerts
- updates the tar-fs transitive dependency alone
Closes: FXA-11832
The vulnerability is a transitive dependency of `storybook`, which requires a major bump to 8 in order to upgrade.  Thankfully, `tar-fs` is installed with caret which allows us to simply reinstall it to pick up the patched `2.1.3` version.
> resolve tar-fs vulnerability

- .circleci/config.yml
- the recent enabling of NX cache appears to have broken profile-server unit tests, complaining of missing folder that is created via prebuild script
- explicitly creates the missing folder as a CI step
Closes: FXA-11885
The profile-server unit tests fail in CI because `var/public` is missing, and NX doesn’t run the prebuild script that creates it, or NX cache discards the empty dir. This issue is hidden locally since NX cache is off and the folder gets created.
> fix(profile-server): unit tests missing public dir

- package.json
- yarn.lock
- removes the resolution for `flat` package
Closes: FXA-11867
I added this resolution after running into issues a couple months ago while [bulk-updating packages](https://github.com/mozilla/fxa/pull/18768).  We've done numerous upgrades and resolution removals since then, and I'm hoping it "just works".  After removing the resolution, the package still resolves at `5.0.2` (no change), suggesting this removal is safe.
> task: audit yarn resolutions – flat

- packages/fxa-settings/config/webpack.config.js
Because:
- we don't want the CSS request to block rendering
This commit:
- change the link tag's initial rel to preload and switch to stylesheet
on page load
> fix(perf): change css link tag's initial rel attr to preload

- packages/fxa-settings/src/components/Settings/FlowSetup2faApp/en.ftl
- flow-setup-2fa-step-2-instruction contains a <strong> tag with capitalized S
- Changes the capitalization to lowercase
> fix(l10n): Fix capitalization in html tag

- packages/fxa-content-server/server/lib/csp/blocking.js
This is a follow-up to https://github.com/mozilla/fxa/pull/19006 so that CSP would allow it.
> chore(perf): update csp to allow link tag rel attr update

- packages/fxa-settings/src/models/hooks.ts
Because:
* We send a GQL request when we don't need to, if product ID isn't present
This commit:
* Skips the request if it's not present
fixes FXA-11878
---
I filed an issue for this and then realized it's a 1-line fix, woot.
> perf(front-end): Don't request product data without product ID

- libs/accounts/rate-limit/README.md
- libs/accounts/rate-limit/src/lib/config.ts
- libs/accounts/rate-limit/src/lib/models.ts
- libs/accounts/rate-limit/src/lib/rate-limit.in.spec.ts
- libs/accounts/rate-limit/src/lib/rate-limit.provider.spec.ts
- libs/accounts/rate-limit/src/lib/rate-limit.spec.ts
- libs/accounts/rate-limit/src/lib/rate-limit.ts
- libs/accounts/rate-limit/src/lib/util.ts
- packages/fxa-auth-server/config/rate-limit-rules.txt
- packages/fxa-graphql-api/src/config/rate-limit-rules.txt
- Some actions need to trigger a ban
- Bans are more aggressive and result in a user being blocked from all other actions
- Updates rules to support allow configuration of a block or ban policy
- Updates rate-limit.check to support bans
- Makes a couple performance improvements by batching async calls with Promise.all
Closes: FXA-11850
I broke this into two PRs to make review easier. Let's review and lank the PR for supporting ip_email as a blocking field first. Then review and land this one.
> task(rate-limit): Support bans in rate-limit lib

- packages/functional-tests/lib/ratelimit.ts
- packages/fxa-settings/src/pages/Signin/en.ftl
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/container.test.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/container.tsx
- Users could end up in a deadend screen if keyFetchToken or unwrapBkey is not set in the confirm email code page
- Redirect the user to login again if those values are missing
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11810
Before:
After: 
This might happen if a page/browser crashed. In order to continue that flow, they would need to close the tab and signin again.
> fix(metrics): Redirect user to signin if missing keyFetchToken or unwrapBKey during confirm code

- libs/payments/cart/src/index.ts
- libs/payments/cart/src/lib/cart.factories.ts
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/cart/src/lib/checkout.types.ts
- libs/payments/customer/src/lib/types.ts
- libs/payments/ui/src/lib/actions/checkoutCartWithPaypal.ts
- libs/payments/ui/src/lib/actions/checkoutCartWithStripe.ts
- libs/payments/ui/src/lib/client/components/CheckoutForm/index.tsx
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- libs/payments/ui/src/lib/nestapp/validators/CheckoutCartWithPaypalActionArgs.ts
- libs/payments/ui/src/lib/nestapp/validators/CheckoutCartWithStripeActionArgs.ts
Because:
* With the changes to SP3 glean metrics reporting, we lose the ability to associate utm and session parameters with an fxa account, but this is necessary for marketing to analyze the success of thecapaigns
This commit:
* passes attribution data from the front end through to the subscription creation/update event
Closes #FXA-11879
> feat(payments-next): add attribution fields to subscription metadata

- packages/functional-tests/tests/oauth/loginHint.spec.ts
- packages/fxa-content-server/app/scripts/models/reliers/oauth.js
- packages/fxa-settings/src/models/integrations/data/data.ts
- packages/fxa-settings/src/models/pages/signin/oauth-query-params.ts
- Some RPs send over an empty string for the login_hint
- Ignores empty string values for login_hint, ie `login_hint=` if they are sent
- Allows this value in React and Backbone app
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11916
The OpenID spec says this value is optional, but depends on the server if they want to reject (strict) or allow (lenient) the value if it is empty
> login_hint
OPTIONAL. Hint to the Authorization Server about the login identifier the End-User might use to log in (if necessary). This hint can be used by an RP if it first asks the End-User for their e-mail address (or other identifier) and then wants to pass that value as a hint to the discovered authorization service. It is RECOMMENDED that the hint value match the value used for discovery. This value …
> fix(oauth): Allow empty string `login_hint`

- packages/functional-tests/tests/resetPassword/resetPassword2FA.spec.ts
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/test/local/routes/account.js
Fixes FXA-11877, where the user is automatically signed into Settings after the reset but they cannot get more recovery codes with the session.
> fix(totp): copy verification method to session post-reset w/ recovery code

- packages/fxa-admin-server/src/config/index.ts
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/test/local/payments/configuration/manager.js
- packages/fxa-auth-server/test/scripts/cancel-subscriptions-to-plan.ts
- packages/fxa-auth-server/test/scripts/convert-customers-to-stripe-automatic-tax.ts
- packages/fxa-auth-server/test/scripts/move-customers-to-new-plan.ts
- packages/fxa-auth-server/test/scripts/stripe-products-and-plans-converter.js
- packages/fxa-auth-server/test/scripts/update-subscriptions-to-new-plan.ts
- packages/fxa-payments-server/server/config/index.js
- packages/fxa-payments-server/server/lib/routes/legal-docs.js
- packages/fxa-payments-server/server/lib/routes/legal-docs.test.js
- packages/fxa-shared/subscriptions/configuration/base.ts
- packages/fxa-shared/subscriptions/validation.ts
- packages/fxa-shared/test/subscriptions/configuration/plan.ts
- packages/fxa-shared/test/subscriptions/configuration/product.ts
- packages/fxa-shared/test/subscriptions/configuration/utils.ts
- we are referencing deprecated CDN
- adds support to new CDN (to remove deprecated one once Stripe metadata has been updated)
Closes: FXA-11869
> fix(payments-server): Update CDN reference

- apps/payments/next/app/[locale]/[offeringId]/[interval]/new/page.tsx
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/customer/src/lib/customer.error.ts
- libs/payments/customer/src/lib/util/assertPromotionCodeApplicableToPrice.spec.ts
- libs/payments/customer/src/lib/util/assertPromotionCodeApplicableToPrice.ts
- libs/payments/ui/src/lib/actions/applyCoupon.ts
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- libs/payments/ui/src/lib/utils/en.ftl
- libs/payments/ui/src/lib/utils/error-ftl-messages.ts
- we don't allow coupons to be applied during upgrades
- there was an unhandled error for first-time coupons
Closes: FXA-11583
> fix(payments-next): Handle Stripe coupon errors

- libs/payments/cart/src/lib/cart.service.ts
- libs/shared/sentry/src/lib/models/SentryConfigOpts.ts
- libs/shared/sentry/src/lib/next/server.ts
- libs/shared/sentry/src/lib/utils/beforeSend.server.ts
- The following errors don't seem appropriate for Sentry.
- Does not report expected errors to Sentry but records them to StatsD.
Closes: #FXA-11630
> fix(payments-next):Do not report expected errors to Sentry

- packages/functional-tests/pages/resetPassword.ts
- packages/functional-tests/tests/resetPassword/resetPassword2FA.spec.ts
- packages/fxa-settings/src/components/Banner/index.tsx
- packages/fxa-settings/src/components/Banner/interfaces.ts
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordRecoveryPhone/container.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordRecoveryPhone/index.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordRecoveryPhone/index.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordRecoveryPhone/interfaces.ts
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordRecoveryPhone/mocks.tsx
Because:
- the error banner for failed recovery phone code during password reset has a link to use backup codes, but it doesn't pass the necessary state for the functionality
This commit:
- updates the link in the error banner so that it has the state with the required token for password reset with backup auth codes
- adds a functional test
- fixes minor bugs where clicks in functional tests were not awaited
> fix(reset): pass state to back 2fa code page from sms code error

- packages/fxa-content-server/webpack.config.js
- An unexpected appDependencies.css was generated by the recently added MiniCssExtractPlugin.
- `[name].css` was used as the output filename as before, which was expected to resolve to `main.css`.
- The SCSS is imported from a non-entry module, and Webpack assigns a fallback chunk name, "appDependencies".
- sets the plugin’s filename explicitly to `main.css`, restoring original behavior and preventing unintended file generation.
Closes: FXA-11922
Misconfiguration introduced via https://github.com/mozilla/fxa/pull/18996
> task(content-server): update miniCssExtractPlugin configuration

- packages/fxa-settings/src/lib/validation/index.ts
- packages/fxa-settings/src/models/integrations/data/data.ts
- packages/fxa-settings/src/models/pages/index/query-params.test.ts
- packages/fxa-settings/src/models/pages/index/query-params.ts
- packages/fxa-settings/src/models/pages/signin/oauth-query-params.test.ts
- packages/fxa-settings/src/models/pages/signin/oauth-query-params.ts
- The fix in https://github.com/mozilla/fxa/pull/19050, was tested against our 123Done client which did not go through same steps as IAM, but failed when in stage
- Adds a new class validator to check if login_hint is an email or empty string
I'm not really sure how/why the functional test I added in https://github.com/mozilla/fxa/pull/19050 gave me a false positive.
> fix(oauth): Allow empty string `login_hint` another attempt

- .circleci/config.yml
- NX Caching prevents nightly builds from running tests fully from scratch
- And, we _want_ tests to run fully every night
- Disables the NX Cache for nightly builds
Closes: (FXA-11911)
Here are two runs of this to confirm that the `--skipNxCache` flag does what we think it should. The lower one is with the flag enabled on `Integration Test - Frontends (PR)` workflow, and then the top is with it off. Large time difference shows we're building from cache vs not.
> chore(ci): skip nx cache for nightly tests

- .circleci/config.yml
Because:
- Nx spitting cached output instead of running tests, which means no actual test results for the steps that follow
This commit:
- skips Nx cache on select jobs
> fix(ci): fix test jobs in test_and_deploy_tag

- libs/shared/nestjs/customs/src/lib/customs.service.spec.ts
- libs/shared/nestjs/customs/src/lib/customs.service.ts
- There _could be_ rules in the future in graphql-api that need to look ip_uid or ip_email
- Passes ip_uid into the rate-limit check
- Passes ip_email into the rate limit check
> bug(gql): ip_uid and ip_email were not provided to rate-limit check

- libs/accounts/rate-limit/src/lib/rate-limit.in.spec.ts
- packages/fxa-auth-server/lib/customs.js
- packages/fxa-graphql-api/src/auth/gql-customs.guard.ts
- Seems like maybe this isn't always getting picked up by Sentry
- In the event this happens we'd like some extra info
- Explicitly captures any error that happens when calling `rateLimit.check(...)`
- Adds sentry tags so we can easily identify action and context
This is something I noticed during triage.
> task(gql,auth): Capture unexpected rate-limit errors and send to Sentry

- apps/payments/next/app/[locale]/[offeringId]/[interval]/new/page.tsx
- libs/payments/ui/src/lib/client/components/Header/index.tsx
- /location page had unexpected placeholders for Country and Postal Code fields.
- Country and Postal codes were being doubled in the URL, creating unexpected behavior (like showing 'Product unavailable' for countries like USA).
- Removes countryCode and postalCode from /new page's searchParams
- Removes countryCode and postalCode from remainingQueryParams, preventing them from getting doubled in the resulting path. 
Closes: #FXA-11889
> fix(payments-next):/location page - unexpected placeholders for Country and Postal Code fields

- .circleci/config.yml
- We still want to use the workspace cache
- Using the remote cache was breaking test output
- Changes --skipNxCache to --no-cloud
- This should let us use the build step's cached output.
> bug(ci): Workspace cache still useful

- nx.json
- We want to be able to use the nx cache
- Makes sure test artifacts are cached as part of the test output
> bug(ci): Test artifacts were not declared in nx.json config

- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* A hook within the stripe-helpers was failing for users who cancelled a subscription while they had a positive account balance (such as after a significantly cheaper bundle purchase)
* In each case, a cusomer had manually cancelled the subscription before this error occurred
This commit:
* Moves the logic to exit early from the subscription-deletion email send function, preventing the unnecessary, failing, Stripe call.
* This method had previously exited early without sending an email, so no functionality is altered
* Removes the unused `return` value for the `sendSubscriptionDeletedEmail` function
Closes #FXA-11934
This is a somewhat shallow fix, as …
> fix(payments): Fix failing subscription deletion email send hook

- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/ui/src/lib/actions/getNeedsInput.ts
- libs/payments/ui/src/lib/client/components/PaymentInputHandler/index.tsx
- Error in getNeedsInput does not cleanup subscription.
- Wraps getNeedsInput in wrapWithCartCatch to clean up subscription if error occurs.
- Redirects user to appropriate page (like error) from needs_input.
Closes: #FXA-11864
> fix(payments-next):Error in getNeedsInput does not cleanup subscription

- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/docs/swagger/misc-api.ts
- packages/fxa-auth-server/lib/routes/geo-location.ts
- packages/fxa-auth-server/lib/routes/index.js
- packages/fxa-auth-server/test/client/api.js
- packages/fxa-auth-server/test/client/index.js
- packages/fxa-auth-server/test/local/routes/geo-location.js
- packages/fxa-settings/src/components/App/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageSettings/index.stories.tsx
- packages/fxa-settings/src/components/Settings/PageSettings/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageSettings/index.tsx
- packages/fxa-settings/src/components/Settings/PageSettings/mocks.tsx
- packages/fxa-settings/src/components/Settings/ProductPromo/index.stories.tsx
- packages/fxa-settings/src/components/Settings/ProductPromo/index.test.tsx
- packages/fxa-settings/src/components/Settings/ProductPromo/index.tsx
- packages/fxa-settings/src/components/Settings/Sidebar/index.tsx
- packages/fxa-settings/src/components/Settings/index.test.tsx
- packages/fxa-settings/src/constants/index.tsx
- packages/fxa-settings/src/lib/gql-key-stretch-upgrade.ts
- packages/fxa-settings/src/lib/hooks/useGeoEligibilityCheck/index.tsx
* We want to check if users are located in the US and eligible for MonitorPlus
* Would be nice if we can reuse this checkpoint in the future for other features
* Adds a new auth-server endpoint and adds handlers
* Uses this endpoint to conditionally display monitor promo to US users
Closes: FXA-11920
Feature availability rules are controlled via config for easier/faster updates (to add or remove rules and/or countries) without requiring a deployment
> feat(auth): Add API endpoint to check for feature availability based on location

- package.json
- yarn.lock
- removes the resolution for `parse-asn1` package
Closes: FXA-11988
After removing, I confirm that `parse-asn1` still resolves to `5.1.7`, the minimum version set by original resolution.
> task: audit yarn resolutions – parse-asn1

- package.json
- yarn.lock
- removes the resolution for `typescript` package
Closes: FXA-11992
This resolution was originally added by me in https://github.com/mozilla/fxa/pull/18768 .  Since then many resolutions have been removed, packages updated, group versions aligned, and now removing the resolution seems to "just work".
> task: audit yarn resolutions – typescript

- packages/db-migrations/databases/fxa/patches/patch-173-174.sql
- deleteAccount will fail if called twice on the same uid.
- fixes the problem by using INSERT IGNORE INTO instead of INSERT INTO
Closes: FXA-11655
> fix(auth): fix deleteAccount procedure potentially failing in edge cases

- packages/functional-tests/tests/oauth/totp.spec.ts
- packages/functional-tests/tests/react-conversion/oauthPromptNone.spec.ts
- packages/functional-tests/tests/settings/avatar.spec.ts
- packages/functional-tests/tests/settings/changeEmail.spec.ts
- packages/functional-tests/tests/settings/changePassword.spec.ts
- packages/functional-tests/tests/settings/changePasswordValidation.spec.ts
- packages/functional-tests/tests/settings/deleteAccount.spec.ts
- packages/functional-tests/tests/settings/displayName.spec.ts
- packages/functional-tests/tests/settings/fxaStatus.spec.ts
- packages/functional-tests/tests/settings/misc.spec.ts
- packages/functional-tests/tests/settings/recoveryPhone.spec.ts
- packages/functional-tests/tests/settings/totp.spec.ts
- packages/functional-tests/tests/signin/signIn.spec.ts
- packages/functional-tests/tests/signin/signinBlocked.spec.ts
- packages/functional-tests/tests/syncV3/signIn.spec.ts
* we want to keep testAccountTracker calls within tests and pass credentials to functions like signInAccount
* update all tests that passed the testAccountTracker
> fix(functional-tests): Don't pass testAccountTracker

- apps/payments/next/app/[locale]/en.ftl
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/checkout.error.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/cart/src/lib/util/resolveErrorInstance.ts
- libs/payments/customer/src/lib/invoice.factories.ts
- libs/payments/customer/src/lib/invoice.manager.spec.ts
- libs/payments/customer/src/lib/invoice.manager.ts
- libs/payments/customer/src/lib/promotionCode.manager.spec.ts
- libs/payments/customer/src/lib/promotionCode.manager.ts
- libs/payments/customer/src/lib/types.ts
- libs/payments/ui/src/lib/utils/getErrorFtlInfo.ts
- libs/shared/db/mysql/account/src/lib/kysely-types.ts
- libs/shared/error/src/lib/sanitizeExceptionsDecorator.ts
- It is possible for the one time charge on an upgrade to change while the customer is checking out, resulting in a mismatch between the value shown to the customer and what they are charged.
- Updates the cart.amount for upgrades to use the one time charge subtotal.
- On checkout, for upgrades, compare the cart.amount with the one time charge subtotal and error if the amounts don't match.
- Add new error message to be displayed on the error page when the cart totals do not match.
- Handle errors thrown during checkout
Closes: #FXA-11840
> feat(next): error on changing upgrade amount

- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/test/local/routes/totp.js
- The TOTP routes were emitting login and account confirmation events during both setup and login flows, which caused duplicate or misleading metrics.
- Updates the TOTP route to only emit login success and account confirmation events during actual login, not during TOTP setup.
- Updates related tests to match the new event flow.
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11697
> fix(metrics): Tweak 2FA Glean metrics to only emit on a login flow

- packages/functional-tests/tests/signin/signinCached.spec.ts
- packages/fxa-settings/src/components/Settings/index.test.tsx
- packages/fxa-settings/src/components/Settings/index.tsx
- User's can direct navigate to /settings from the confirmation code page.
- Makes `session.verified` required to render `/settings` route
Closes: FXA-11927
Although it might seem strange, it's not actually a big deal if someone access `/settings` with unverified session. The `session.verified` flag is mostly just an artifact that `auth-server` uses to gate access to certain actions. That said, there's really no reason to render the `/settings` route in this case, since the majority of actions would be blocked anyways.
> bug(settings): Don't allow access to /settings if session isn't verified.

- packages/fxa-settings/src/pages/Signup/en.ftl
Singular `-payment` is what we're referencing in the code. 😭
> fix(l10n): Fix incorrect FTL ID reference

- apps/payments/next/app/[locale]/en.ftl
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/checkout.error.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/cart/src/lib/util/isPaymentIntent.ts
- libs/payments/cart/src/lib/util/resolveErrorInstance.ts
- libs/payments/cart/src/lib/util/throwIntentFailedError.spec.ts
- libs/payments/cart/src/lib/util/throwIntentFailedError.ts
- libs/payments/customer/src/lib/customer.error.ts
- libs/payments/customer/src/lib/setupIntent.manager.spec.ts
- libs/payments/customer/src/lib/setupIntent.manager.ts
- libs/payments/customer/src/lib/subscription.manager.spec.ts
- libs/payments/customer/src/lib/subscription.manager.ts
- libs/payments/stripe/src/lib/stripe.client.ts
- libs/payments/ui/src/lib/utils/getErrorFtlInfo.ts
- libs/shared/db/mysql/account/src/lib/kysely-types.ts
- libs/shared/sentry/src/lib/utils/beforeSend.server.ts
- Currently a failed payment or setup intent results in Sentry errors and only shows the customer a generic error message.
- Reduces the number of errors thrown in the wrapWithCartCatch.
- Adds handling of Setup Intents to wrapWithCartCatch
- Updates error handling of Payment Intents in wrapWithCartCatch
- Adds new errors for various types of intent failures
- Copies existing error messages from SP2 to be used in SP3 for various types of intent failures.
Closes: #FXA-11981
To test with a setup intent, ensure that zero dollar invoice is generated. Easiest way to do this is to use 123DonePro - monthly and the EVERYTHING coupon
Get in touch error - With Contact Support
Get in touch error - With Try Again
Card Decline - Insufficient funds decline
Card …
> fix(next): add descriptive error for intent failures

- packages/fxa-settings/config/webpackDevServer.config.js
- packages/fxa-settings/public/index.html
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/components/LoadingSpinnerSprite/index.tsx
- packages/fxa-settings/src/pages/Index/container.test.tsx
- packages/fxa-settings/src/pages/Index/container.tsx
Because:
* React Profiler shows our LoadingSpinner is heavy
This commit:
* Adds a spritesheet to our public HTML file and updates references to our LoadingSpinner on App/Index to an svg use instead, to load less XML on renders
fixes FXA-11880
---
The spritesheet approach gave me slightly better results in the Profiler than using `<img src=` and referencing it as a background image. However, the Profiler seems to be giving me slightly inconsistent results now compared to before - I was getting around 4.9ms in [this branch](https://github.com/mozilla/fxa/compare/main...LZoog:remove-loading-spinner-email-first?expand=1) with it swapped to an empty string, but when I do that off `main` now, I seem to get around ~7ms? I'm unsure if this is because locally I changed `compress: false` in webpack …
> fix(perf): Change email-first LoadingSpinner fallback to LoadingSpinnerSprite

- apps/payments/next/auth.ts
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- libs/payments/ui/src/lib/nestapp/validators/GetUserinfoArgs.ts
- libs/payments/ui/src/lib/nestapp/validators/GetUserinfoResult.ts
- libs/profile/client/src/lib/profile.client.spec.ts
- libs/profile/client/src/lib/profile.client.ts
- libs/profile/client/src/lib/profile.error.ts
- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/lib/payments/processing-tasks-setup.ts
- packages/fxa-auth-server/scripts/delete-account.ts
Because:
* the userinfo for next-auth comes from their default handler currently
This commit:
* updates the userinfo provider to be the profile client
Closes #FXA-11964
> task(payments-next): update nextauth to use profile client

- apps/payments/next/Gruntfile.js
Because:
* The ProfileClient class is used by nextjs, but changes to it do not cause a hotreload
This commit:
* Adds the libs/profile/**/*.ts files to the payments-next gruntfile
Closes #n/a
> polish(payments-next): Add libs/profile ts files to payments-next hot reload

- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/cart/src/lib/util/delay.ts
- libs/payments/customer/src/lib/types.ts
- Due to SP3 subscription creation differences compared to SP2, it is possible that when subscription update events are processed by the stripe-webhook handler, that the subscription stored in firestore will have an incorrect status compared to the actual value in Stripe.
- This change helps mitigate the incorrect status, by performing a delayed update to the subscription. This results in a delayed webhook event, which should allow for enough time for the correct Stripe subscription status to be updated in SubPlat firestore
> fix(next): add delayed subscription update

- packages/fxa-auth-server/lib/senders/emails/partials/support/en.ftl
- support-message-3 contains a syntax error causing issues in Pontoon sync
-  Removes the syntax error
> chore(l10n): Fix syntax error in support-message-3

- libs/payments/management/.eslintrc.json
- libs/payments/management/.swcrc
- libs/payments/management/README.md
- libs/payments/management/jest.config.ts
- libs/payments/management/package.json
- libs/payments/management/project.json
- libs/payments/management/src/index.ts
- libs/payments/management/src/lib/subscriptionManagement.service.spec.ts
- libs/payments/management/src/lib/subscriptionManagement.service.ts
- libs/payments/management/tsconfig.json
- libs/payments/management/tsconfig.lib.json
- libs/payments/management/tsconfig.spec.json
- tsconfig.base.json
Because:
* payments-next is going to own the subscription management page, and as such needs a service to wrap the logic
This commit:
* Adds in a new nx project, payments-management
* Adds in a SubscriptionManagementService, along with a standin function for testing purposes Closes #FXA-11240
Closes: #FXA-11240
> task(payments-next): Add SubscriptionManagementService

- .circleci/config.yml
- packages/functional-tests/playwright.config.ts
- packages/functional-tests/scripts/start-services.sh
- Playwright can skip tests due to `maxFailures`
- And we want to attempt to run all tests during `nightly`
- And we want to improve build time by utilizing the nx cache
- Adds an environment variable for `PLAYWRIGHT_FAIL_FAST`, defaulted to true
- Passes an override for this environment variable to the workflows to disable it for appropriate builds
- And fixes env var that caused NX to ignore local and remote cache
Closes: FXA-12015
> chore(functional-tests): disable maxFailures for functional-tests on nightly

- package.json
- removes the resolution for `protobufjs` package
Closes: FXA-11991
I confirm that before and after resolution removal, `protobufjs` resolves to `7.5.0` (satisfying the resolution).  This is also why yarn.lock is unchanged.
> task: audit yarn resolutions – protobufjs

- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordRecoveryChoice/container.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordRecoveryChoice/index.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordRecoveryChoice/index.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordRecoveryPhone/container.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordRecoveryPhone/index.stories.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordRecoveryPhone/index.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordRecoveryPhone/index.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordRecoveryPhone/interfaces.ts
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordRecoveryPhone/mocks.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryChoice/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryChoice/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryChoice/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/index.stories.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/interfaces.ts
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/mocks.tsx
* When entering an incorrect (sms) recovery code when signing in or resetting password, error message contained a message to use backup codes instead - this suggestion should not be shown if the user does not have backup authentication codes
* Check num of codes when constructing error message
Closes: FXA-12031
> fix(settings): Dont show backup codes link if no codes available

- libs/payments/ui/src/lib/client/components/CheckoutForm/index.tsx
- Continuing to press the Subscribe Now button while it is loading results in duplicate action calls.
- Early exists the Subscribe Now button submit handler, while it  is loading so that multiple button presses do not result in duplicate subscription creation calls.
Closes: #FXA-12044
> fix(next): early exit subscribe submit handler while loading

- packages/fxa-auth-server/lib/log.js
- We want to debug metrics issues in https://mozilla-hub.atlassian.net/browse/FXA-11965
- Add additional logging on the 108 and 183 errors for this endpoint
- Logs the metrics context for these requests
Closes: https://mozilla-hub.atlassian.net/browse/FXA-12057
> fix(metrics): Add more logging to verifySession endpoint

- packages/fxa-settings/src/lib/cache.ts
- packages/fxa-settings/src/pages/Signin/container.test.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
- The wrong account was being used
- Adjust the logic for how to select an account during sign in.
This is in draft, because I feel like I didn't spend enough time testing it. Considering there's some bugs around this issue, maybe we should just throw it up for QA to look at... 
I'll ultimately leave this up to the reviewer to decide. This is actually a follow up to a previous PR. In that PR, note that during code review we were questioning the basic implementation for `getAccountInfo`. This PR should be seen as re-write of that where the email parameter makes a best effort to find the target account. The PR that this follows is, …
> bug(settings): Wrong account being picked

- packages/functional-tests/tests/signin/signinBlocked.spec.ts
- packages/fxa-auth-server/lib/routes/utils/signin.js
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-auth-server/test/local/routes/utils/signin.js
- packages/fxa-auth-server/test/mocks.js
- packages/fxa-settings/src/pages/Signin/SigninUnblock/container.tsx
- Even after entering an unblock code the user was still being prompted to enter an unblock code on the next login.
- This was previously done inside the customs server, so there was no analogue for v2 customs.
- Fixes a bug where 'email-otp' verification type wasn't honored
- Fixes a bug where providing an unblock code wasn't clearing all active user blocks, rather it was just allowing the login block to be bypassed.
- Fixes bug where sensitive data client was being cleared out prematurely.
Closes: FXA-12067, FXA-9882
>  bug(auth,settings): Fix issue with consuming signin unblock code 

- libs/payments/ui/src/lib/client/components/StripeWrapper.tsx
- When the charge amount is less than min charge amount, payment element fails to load and instead has an error in the browser console.
- Changes StripeElementsOptions mode to 'setup' instead of 'subscription' when prorated change is less than Stripe min charge amount.
- Uses SetupIntent in such cases, saving user's payment method without immediate charging them.
Closes: #FXA-12072
> fix(payments-next): Payment element does not load when charge amount is less than minimum charge amount

- packages/fxa-settings/src/components/Settings/DataCollection/index.test.tsx
- packages/fxa-settings/src/components/Settings/DataCollection/index.tsx
Because:
* We have an updated article so all current and future data scenarios are covered
This commit:
* Updates the link
closes FXA-12060
> refactor(settings): Update 'Learn more' link

- packages/functional-tests/tests/signin/signinBlocked.spec.ts
-  It appears the loop with waitForTimeout caused a race condition in the CI
- Perhaps the CI is slower and the timeout wasn't sufficient
- Replaces loop with set number of password attempts.
- Fixes misleading comment
> bug(functional): Avoid do while loop with waitForTimeout.

- packages/fxa-settings/src/components/FormPasswordWithBalloons/index.tsx
- packages/fxa-settings/src/components/FormPasswordWithInlineCriteria/index.tsx
* React Hook Form was attempting to trigger validation on confirmPassword field even when the field didn't exist in the DOM
* This occurred in signup flows where password confirmation is not required, causing "Field is missing with name attribute: confirmPassword" warnings
* The warnings were appearing in FormPasswordWithBalloons and FormPasswordWithInlineCriteria components
* Adds conditional checks around trigger('confirmPassword') calls to only execute when requirePasswordConfirmation/showConfirmPasswordInput is true
* Updates FormPasswordWithBalloons to guard confirmPassword validation with requirePasswordConfirmation prop
* Updates FormPasswordWithInlineCriteria to guard confirmPassword validation with showConfirmPasswordInput prop
* Prevents getValues('confirmPassword') calls when …
> fix(settings): Fix missing name attribute warnings for confirmPassword field

- libs/shared/mozlog/project.json
- libs/shared/nestjs/customs/project.json
- libs/shared/notifier/project.json
- shared-mozlog was failing to build due to nestjs dependency errors
- Mark missing dependencies as external
> fix(mozlog): resolve nestjs dependencies errors

- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/ui/src/lib/actions/applyCoupon.ts
- libs/payments/ui/src/lib/client/components/SelectTaxLocation/index.tsx
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- Version mismatch errors on tax address or coupon changes result in the cart going into fail state.
- Handles version mismatch and invalid cart state errors and returns an appropriate error to the user and revalidates the data on the current page.
- Removes local state from SelectTaxLocation's Expand component.
Closes: #FXA-12047
Easiest steps to reproduce are listed below.
1. Open the checkout page for any offer
1. Duplicate the tab, so that both tabs use the same cart
1. Change the address in the first tab and save
1. Without refreshing the page, on the 2nd tab change the address, and save.
1. User should be shown an error message, and allowed to try resave the address. (Previously it would move the cart to error state)
> fix(next): cart updates handle version mismatch

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe-firestore.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-shared/payments/stripe-firestore.ts
- Stripe webhooks that come in within a tight window are subject to race conditions in the legacy Stripe webhook handling logic
- Wraps Firestore updates triggered by Stripe webhooks in transactions. This does not cover invoices or payment methods, which should be covered but expand the scope of this ticket. I will file a follow-up ticket for these.
Closes FXA-12065
> fix(auth): transactionalize stripe webhook firestore updates

- packages/fxa-settings/src/components/Settings/PageSettings/index.stories.tsx
- PageSettings storybook was not rendering
- add an authclient mock for the useGeoEligibilityCheck hook, resolving eligibility to true
- this setting shows the global Monitor promo in the "cold start" story with no services, and the special US-only promo in the "completely filled out" story which includes Monitor in the services list
> fix(storybook): PageSettings storybook missing auth client mock

- packages/fxa-settings/src/components/Settings/FlowSetup2faPrompt/en.ftl
- packages/fxa-settings/src/components/Settings/FlowSetup2faPrompt/index.stories.tsx
- packages/fxa-settings/src/components/Settings/FlowSetup2faPrompt/index.test.tsx
- packages/fxa-settings/src/components/Settings/FlowSetup2faPrompt/index.tsx
- The first screen of the inline flow is unique and was not included in the previous epic.
- extracts the first page of the inline setup flow into FlowSetup2faPrompt and updates it to match the latest design
Closes: FXA-10208
> feat(settings): Create new FlowSetup2faPrompt component

- packages/fxa-settings/src/components/Settings/FlowContainer/index.tsx
- packages/fxa-settings/src/components/Settings/FlowSetup2faComplete/en.ftl
- packages/fxa-settings/src/components/Settings/FlowSetup2faComplete/index.stories.tsx
- packages/fxa-settings/src/components/Settings/FlowSetup2faComplete/index.test.tsx
- packages/fxa-settings/src/components/Settings/FlowSetup2faComplete/index.tsx
- packages/fxa-settings/src/lib/glean/index.ts
- packages/fxa-shared/metrics/glean/fxa-ui-metrics.yaml
- packages/fxa-shared/metrics/glean/web/accountPref.ts
- packages/fxa-shared/metrics/glean/web/index.ts
- we need a new flow component to communicate success at the end of the inline 2FA flow before redirecting to the relying party.
- create a new FlowSetup2faComplete component, with storybook, unit tests, l10n and metrics
Closes: FXA-10244
> feat(settings): create new FlowSetup2faComplete component

- packages/functional-tests/tests/signin/signinCached.spec.ts
- packages/fxa-settings/src/components/Settings/index.test.tsx
- packages/fxa-settings/src/components/Settings/index.tsx
- packages/fxa-settings/src/models/Session.ts
- packages/fxa-settings/src/pages/Authorization/container.tsx
- packages/fxa-settings/src/pages/PostVerify/SetPassword/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
- packages/fxa-settings/src/pages/Signin/index.tsx
- packages/fxa-settings/src/pages/Signin/interfaces.ts
- packages/fxa-settings/src/pages/Signin/utils.ts
Because:
* Non-new accounts have issues signing in, where /settings takes them back to sign-in in an endless loop
This commit:
* Adds a check for sessionVerified and redirects accordingly
fixes FXA-12035
---
Opening as a draft for now because I need to check on tests.
Currently not sure how to test this locally very well but I'm sure there's a way. Late last week I created a couple of accounts locally before signing off, and then could repro on those accounts this morning and used those to test and fix for cached signin + signin with PW. Setting `SIGNIN_CONFIRMATION_FORCE_GLOBALLY` doesn't seem to give me what I want.
I think we've been directing users with an unverified session to settings a lot more than we realized. We could revert #19086, but this is an attempt at fixing the …
> fix(sign-in): Properly redirect users without verified sessions (+ reverted revert of #19086)

- packages/fxa-settings/src/components/Settings/PageSettings/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageSettings/index.tsx
- packages/fxa-settings/src/lib/gql.test.ts
- packages/fxa-settings/src/lib/gql.ts
- Some RPs link directly to `/settings`
- If the user is no longer logged in, we'd direct them to signin and say they were a sync user, which might not be the case.
- No longer assumes a user accessing the /settings page is a sync user.
- Adds support for an email query parameter to the settings page.
- Checks if the email query param matches the current account email, if not redirects to sign in.
Closes: FXA-11928
https://github.com/user-attachments/assets/1b06363c-962d-4319-a5c6-7b3173a289fc
To ensure that RPs direct their users to the right settings page, they can now supply the target email in the settings page link, e.g. `https://accounts.firefox.com/settings?email=target@email.com`.
> bug(settings): Redirect to signin from `/settings` not working as intended

- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(startLayout)/start/page.tsx
- In instances where a customer does not have a default payment method, these customers should not be blocked from upgrading the subscription.
- Hides payment information section on upgrade page if not available and lets customers checkout with a new payment method.
Closes: #PAY-3131
> fix(next): allow upgrade for missing payment method

- libs/payments/cart/src/lib/cart.types.ts
- libs/payments/customer/src/lib/types.ts
- libs/payments/customer/src/lib/util/stripeInvoiceToFirstInvoicePreviewDTO.spec.ts
- libs/payments/customer/src/lib/util/stripeInvoiceToFirstInvoicePreviewDTO.ts
- libs/payments/ui/src/lib/client/components/PurchaseDetails/en.ftl
- libs/payments/ui/src/lib/client/components/PurchaseDetails/index.tsx
- libs/payments/ui/src/lib/server/components/UpgradePurchaseDetails/en.ftl
- libs/payments/ui/src/lib/server/components/UpgradePurchaseDetails/index.tsx
- the invoice may display the amount for the remaining time (prorated price) of the upgraded plan, not the price of the product (see invoice [1] -  $3.74 (Remaining time on MDN Plus 10M) - $1.87 (Unused time on MDN Plus 5M) = $1.87 total due)
- the confirmation page is showing the list price of the product, so the math is off (see screenshot [2] - $10.00 - $1.87 = $1.87)
- adds remainingAmountTotal to DTO, if amount for remaining time is available
- if remainingAmountTotal is available, display instead of the list price of the product with "Prorated product ({productName})" label
- if list price and remaining amount are the same, display "List Price" label
[1] 
[2] 
[3] Amount for remaining time exists
[4] No amount for remaining time exists
[5] Amount …
> fix(payments-next): Display prorated price if available instead of list price to match invoice

- packages/functional-tests/tests/signin/signinCached.spec.ts
- packages/fxa-settings/src/components/Settings/index.test.tsx
- packages/fxa-settings/src/components/Settings/index.tsx
- packages/fxa-settings/src/models/Session.ts
- packages/fxa-settings/src/pages/Authorization/container.tsx
- packages/fxa-settings/src/pages/PostVerify/SetPassword/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx
- packages/fxa-settings/src/pages/Signin/container.tsx
- packages/fxa-settings/src/pages/Signin/index.tsx
- packages/fxa-settings/src/pages/Signin/interfaces.ts
- packages/fxa-settings/src/pages/Signin/utils.ts
Reverts mozilla/fxa#19144
These changes caused `FXA-12096` bug - reverting before the prod deployment. 
https://github.com/mozilla/fxa/pull/19208 will propose an alternative for `FXA-11927`, and an additional issue will be filed about inconsistencies in session verification.
> Revert "fix(sign-in): Properly redirect users without verified sessions (+ reverted revert of #19086)"

- packages/fxa-settings/src/components/Settings/index.test.tsx
- packages/fxa-settings/src/components/Settings/index.tsx
- packages/fxa-settings/src/models/Session.ts
* It was possible to bypass confirm_signup_code and go directly to /settings
* Note: this gave very limited access to the account info, majority of settings changes are guarded + sync not accessible until account is confirmed
* Reverts PR-19086 and PR-19144 which modified redirection based on session verification status
* Add a redirect from settings if account email unverified
[FXA-12096](https://mozilla-hub.atlassian.net/browse/FXA-12096)
[FXA-12096]: https://mozilla-hub.atlassian.net/browse/FXA-12096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(settings) - Redirect away from /settings if account unverified

- packages/fxa-auth-server/.mocharc.js
- packages/fxa-auth-server/test/local/l10n/index.ts
- packages/fxa-auth-server/test/local/routes/recovery-phone.js
- packages/fxa-auth-server/test/local/senders/renderer.ts
- packages/fxa-auth-server/test/remote/password_forgot_tests.js
- packages/fxa-auth-server/test/remote/recovery_phone_tests.js
- packages/fxa-auth-server/test/setup.js
- Test modules that don't configure chaiAsPromised are implicitly coupled to other test modules that do
- Uses a global setup for configuring chaiAsPromised
Closes (FXA-12098)
> chore(tests): add global setup for chaiAsPromised

- packages/fxa-settings/src/components/FormPasswordWithBalloons/index.test.tsx
- packages/fxa-settings/src/components/FormPhoneNumber/index.test.tsx
- packages/fxa-settings/src/components/Settings/FlowRecoveryKeyDownload/index.test.tsx
- packages/fxa-settings/src/components/Settings/FlowSetupRecoveryPhoneSubmitNumber/index.test.tsx
- packages/fxa-settings/src/components/Settings/SettingsLayout/index.test.tsx
- packages/fxa-settings/src/components/Settings/VerifiedSessionGuard/index.test.tsx
- packages/fxa-settings/src/components/ThirdPartyAuth/index.test.tsx
- packages/fxa-settings/src/pages/Index/container.test.tsx
- packages/fxa-settings/src/pages/Index/index.test.tsx
- packages/fxa-settings/src/pages/InlineRecoveryKeySetup/index.test.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetup/index.test.tsx
- packages/fxa-settings/src/pages/InlineTotpSetup/index.test.tsx
- packages/fxa-settings/src/pages/PostVerify/SetPassword/index.test.tsx
- packages/fxa-settings/src/pages/Signin/container.test.tsx
- packages/fxa-settings/src/pages/Signin/index.test.tsx
- packages/fxa-settings/src/pages/Signup/index.test.tsx
- There are a number of `act(...)` warnings from fxa-settings React unit-tests
- Updates tests to prevent any `act(...)` tests. This forces tests to complete flushing events and render components as they would appear to the user - more accurate tests
Closes: (FXA-12097)
There are a few buckets that the React `act(...)` warnings could fall under and best ways to resolve them.
- If tests use `waitFor` or `userEvent.click()` or other `@testing-library` tools, actions are automatically wrapped in `act()`. 
- Using `fireEvent` can cause the `act()` warning because a click can change the state of the component, and in places where we were still relying on `fireEvent` we …
> chore(fxa-settings): clean up React act() unit test warnings

- packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponExpired.spec.ts
- packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponForeverDiscount.spec.ts
- packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponInvalid.spec.ts
- packages/functional-tests/tests/subscription-tests/coupons-ui-tests/couponOneTimeDiscount.spec.ts
- packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts
- packages/functional-tests/tests/subscription-tests/subscription.spec.ts
- packages/functional-tests/tests/subscription-tests/support.spec.ts
- Some SP2 checkout tests are flaky causing unnecessary circle ci delays and issues during releases.
- SP2 checkout functional tests are no longer as important as before as most subscription checkout is now done through SP3 checkout pages.
- Adds fixme to flaky functional tests, and added a reference to a future ticket to remove the functional tests.
Closes: #PAY-3168
List of flaky tests is based on CircleCi Flaky test designation with tests failing more than 2 times. in the last 2 weeks.
> feat(functional-tests): skip flaky sp2 tests

- libs/payments/cart/src/index.ts
- libs/payments/cart/src/lib/cart-als.factories.ts
- libs/payments/cart/src/lib/cart-als.provider.ts
- libs/payments/cart/src/lib/cart-als.types.ts
- libs/payments/cart/src/lib/cart.service.spec.ts
- libs/payments/cart/src/lib/cart.service.ts
- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/ui/src/lib/nestapp/app.module.ts
- It is possible that an error can occur after subscription creation, but before the subscription ID is written to the cart. As a result the created subscription will not correctly rollback during cleanup.
- Adds async local storage to stripe and paypal checkout to store the subscriptionId.
- Updates the error cleanup code to check for subscription Id in the cart followed by async local storage.
Closes: #PAY-3164
> feat(cart): add subscriptionId to async local storage

- libs/payments/customer/src/lib/customerSession.manager.ts
Because:
* Depending on how a card is saved, we may not be displaying the user's default payment method at checkout
This commit:
* Permits 'limited' cards to be displayed in the payment element
Closes #[PAY-3185](https://mozilla-hub.atlassian.net/browse/PAY-3185)
[PAY-3185]: https://mozilla-hub.atlassian.net/browse/PAY-3185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(payments-next): Display any saved card in checkout

- libs/shared/metrics/glean/src/lib/metrics.context.ts
- packages/fxa-auth-server/lib/metrics/context.js
- packages/fxa-auth-server/lib/routes/session.js
- packages/fxa-auth-server/lib/routes/utils/account.ts
- packages/fxa-auth-server/test/local/metrics/context.js
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-auth-server/test/local/routes/utils/account.js
- packages/fxa-auth-server/test/local/routes/utils/signin.js
- packages/fxa-graphql-api/src/gql/dto/input/metrics-context.ts
- Sync emails were not getting customizations loaded correctly
- Typically the `metricsContext.service` is the clientId, however for sync it is "sync". Changing that value could risk breaking our metrics so I opted to pass the clientId directly into the account create and login routes
- Updates graphql to pass the clientId in metricsContext
- Updates auth-server to stash the clientId in metricsContext
- Updates the auth-server to fetch customizations on the clientId instead of service value
Closes: https://mozilla-hub.atlassian.net/browse/FXA-12121
Closes: https://mozilla-hub.atlassian.net/browse/FXA-12123
> fix(bug): Fix issue where some cms customized emails are missing logo

- packages/fxa-settings/README.md
- packages/fxa-settings/src/components/Settings/ConnectAnotherDevicePromo/en.ftl
- packages/fxa-settings/src/components/Settings/ConnectAnotherDevicePromo/index.test.tsx
- packages/fxa-settings/src/components/Settings/ConnectAnotherDevicePromo/index.tsx
- packages/fxa-settings/src/components/Settings/ConnectAnotherDevicePromo/storeImageLoader.tsx
- the Google Play Store badge is not rendered correctly
- fixes this issue by switching from using inline SVG to using <img> elements, incidentally cutting down bundle size by 380 KB.
Closes: FXA-12063
> fix(settings): Google play store badge not rendered correctly

- packages/fxa-auth-server/test/local/payments/stripe-firestore.js
- packages/fxa-shared/payments/stripe-firestore.ts
- We want to reconcile cached Firestore data against Stripe, even for canceled subscriptions.
- Adds the `status: "all"` parameter when fetching customer subscriptions.
Closes PAY-3098
> fix(stripe-webhooks): include canceled subscriptions in customer.updated

- packages/fxa-react/lib/storybooks.tsx
- packages/fxa-settings/src/components/FormPassword/index.stories.tsx
- packages/fxa-settings/src/components/Settings/FlowRecoveryKeyConfirmPwd/index.stories.tsx
- packages/fxa-settings/src/components/Settings/FlowSetup2faApp/index.stories.tsx
- packages/fxa-settings/src/components/Settings/FlowSetup2faBackupChoice/index.stories.tsx
- packages/fxa-settings/src/components/Settings/FlowSetup2faBackupCodeConfirm/index.stories.tsx
- packages/fxa-settings/src/components/Settings/FlowSetup2faBackupCodeDownload/index.stories.tsx
- packages/fxa-settings/src/components/Settings/FlowSetup2faComplete/index.stories.tsx
- packages/fxa-settings/src/components/Settings/FlowSetupRecoveryPhoneConfirmCode/index.stories.tsx
- packages/fxa-settings/src/components/Settings/FlowSetupRecoveryPhoneSubmitNumber/index.stories.tsx
- packages/fxa-settings/src/components/Settings/ProductPromo/index.stories.tsx
- packages/fxa-settings/src/components/Settings/Security/index.stories.tsx
- packages/fxa-settings/src/components/Settings/SettingsLayout/index.stories.tsx
- A bunch of stories using SettingsLayout are broken. We need to wrap them in LocationProvider.
- wraps broken stories in `LocationProvider` by using a new `withLocation` decorator
Closes: FXA-12150
> fix(storybook): fix broken stories using SettingsLayout

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/error/page.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/error/page.tsx
- apps/payments/next/app/[locale]/error.tsx
- libs/payments/ui/src/lib/actions/handleStripeError.ts
- libs/payments/ui/src/lib/actions/submitNeedsInputAndRedirect.ts
- libs/payments/ui/src/lib/client/components/CheckoutForm/index.tsx
- libs/payments/ui/src/lib/client/components/PaymentInputHandler/index.tsx
- libs/payments/ui/src/lib/utils/getErrorFtlInfo.ts
- packages/fxa-content-server/app/scripts/lib/router.js
- packages/fxa-content-server/app/tests/spec/lib/router.js
- packages/fxa-content-server/server/lib/routes/react-app/add-routes.js
- packages/fxa-content-server/server/lib/routes/react-app/index.js
- packages/fxa-settings/src/models/integrations/oauth-web-integration.ts
- In some places, query params are lost in route reconstruction.
- Preserves query params from the original request
Closes: #FXA-12002
> feat(payments-next): Ensure redirects do not strip out attribution route parameters.

- libs/payments/management/src/lib/subscriptionManagement.error.ts
- libs/payments/management/src/lib/subscriptionManagement.service.spec.ts
- libs/payments/management/src/lib/subscriptionManagement.service.ts
- libs/payments/ui/src/lib/actions/index.ts
- libs/payments/ui/src/lib/actions/setDefaultStripePaymentDetails.ts
- libs/payments/ui/src/lib/client/components/PaymentMethodManagement/index.tsx
- libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts
- libs/payments/ui/src/lib/nestapp/validators/SetDefaultStripePaymentDetailsActionArgs.ts
Because:
* Customers need the ability to save 3D Secure cards to their account
This commit:
* Adds in a handler for setupIntents with the 'requires_action' status
* Adds a simplified server action for updating which default payment method is used with the account
* Sets the newly-added payment method as the account's default, as with other payment methods
Closes #PAY-3174
> feat(payments-management): Add 3D Secure payment method support

- packages/functional-tests/tests/cms/cms.spec.ts
- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-settings/src/components/AppLayout/index.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetup/container.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetup/index.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetup/interfaces.ts
- packages/fxa-settings/src/pages/InlineTotpSetup/container.tsx
- packages/fxa-settings/src/pages/InlineTotpSetup/index.tsx
- packages/fxa-settings/src/pages/InlineTotpSetup/interfaces.ts
- packages/fxa-settings/src/pages/InlineTotpSetup/old.tsx
- packages/fxa-settings/src/pages/PostVerify/SetPassword/container.tsx
- packages/fxa-settings/src/pages/PostVerify/SetPassword/index.tsx
- packages/fxa-settings/src/pages/PostVerify/SetPassword/interfaces.ts
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx
- packages/fxa-settings/src/pages/mocks.tsx
- Playwright cms tests were broken in stage
- RPs also use "." in entrypoint names
- Some components dont get customized styles
- Fixes cms tests
- Allows "." in entrypoint for enabling cms, Monitor uses these
We will also need to add some Strapi validation on inputs. While we shouldnt change the values for the CI RPs, it is possible to copy paste strings (ex Figma), and they would contain special uicode characters. The correct fix is to add validation to all inputs to not allow this.
> feat(cms): Fix cms playwright tests for stage, fix entrypoint regex, fix background styling

- packages/functional-tests/lib/sms.ts
- packages/functional-tests/tests/oauth/totp.spec.ts
- packages/fxa-content-server/server/lib/beta-settings.js
- packages/fxa-content-server/server/lib/configuration.js
- packages/fxa-content-server/server/lib/routes/react-app/route-definition-index.js
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/components/Settings/FlowSetup2faComplete/index.tsx
- packages/fxa-settings/src/lib/config.ts
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/container.test.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/container.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/gql.ts
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/index.stories.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/index.test.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/index.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/interfaces.ts
- packages/fxa-settings/src/pages/InlineTotpSetup/container.tsx
Because:
- we want to offer the recovery phone 2fa recovery option during inline
2fa
This commit:
- implements 2fa recovery choices with new flow components from
Settings' 2FA setup
> feat(2fa): show 2fa recovery choices "inline"

- libs/shared/guards/src/lib/admin-panel-guard.spec.ts
- libs/shared/guards/src/lib/admin-panel-guard.ts
- We want to add a new group for DSAR users
- We want to add a new group for read only users
- Adds DSAR group, which has a ability to search for and delete accounts
- Adds readonly group, which has a read only view
- Updates configurations accordingly
Closes: FXA-10976
Note, this is based on [#19237](https://github.com/mozilla/fxa/pull/19239), which moves fxa-shared/guards into libs. Please review that first!
> task(admin-panel): Support new user groups and permissions

- packages/123done/static/js/123done.js
- packages/fxa-payments-server/backstage.yaml
- We're implementing the Fastly WAF
- Some of our domains needed friendly URLs to accommodate this
- Adds/updates friendly urls for event-broker, payments-server, and payments-next
Closes: FXA-12157
This PR should be merged in coordination with DNS cutover.
See also https://github.com/mozilla/webservices-infra/blob/main/fxa/tf/stage/waf.tf which sets up the friendly domains (under `subscription_domains`)
> task: WAF-related friendly url updates

- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/cart/src/lib/util/delay.ts
- libs/payments/customer/src/lib/types.ts
- This customer update after a short delay, a temporary fix to resolve an incident, is no longer necessary since a permanent solution has been implemented.
- Reverts the temporary fix.
Closes: #PAY-3186
> revert(next): remove delayed subscription update

- packages/functional-tests/lib/targets/stage.ts
- I never saved the change to this url in my [previous PR](https://github.com/mozilla/fxa/pull/19257)
- replaces the old url with the newly created Fastly WAF friendly url
Closes: FXA-12157
> task(payments): update payments domain to WAF friendly url

- packages/fxa-content-server/server/config/local.json-dist
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx
* When RP requires 2FA, confirm signup code was navigating to cache signin instead of directly to inline totp setup
* Fix navigation and include state
Closes: FXA-11573
Enabled the new inline recovery setup by default in local env
> fix(settings): Navigate directly to inline_totp_setup

- apps/payments/next/app/[locale]/en.ftl
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/cart/src/lib/util/resolveErrorInstance.ts
- libs/payments/ui/src/lib/utils/getErrorFtlInfo.ts
- libs/shared/db/mysql/account/src/lib/kysely-types.ts
- libs/shared/sentry/src/lib/utils/beforeSend.server.ts
- PayPal customer has active subscriptions but no billing agreement
- Does not report to Sentry
- Provides better error messaging to the client
Closes: #[PAY-3139](https://mozilla-hub.atlassian.net/browse/PAY-3139)
[PAY-3139]: https://mozilla-hub.atlassian.net/browse/PAY-3139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(payments-next): PayPalActiveSubscriptionsMissingAgreementError: PayPal customer has active subscriptions but no billing agreement

- libs/payments/customer/src/lib/types.ts
- Subscription metadata updates are failing due to a previously supported key no longer be in the list of valid keys, however the key is still in the current subscription metadata.
- Temporarily re-add the previously valid key, last_updated.
> fix(next): re-add previously used sub metadata

- packages/fxa-auth-server/lib/metrics/amplitude.js
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/emails/templates/_versions.json
- packages/fxa-auth-server/lib/senders/emails/templates/postChangeTwoStepAuthentication/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postChangeTwoStepAuthentication/includes.json
- packages/fxa-auth-server/lib/senders/emails/templates/postChangeTwoStepAuthentication/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postChangeTwoStepAuthentication/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postChangeTwoStepAuthentication/index.txt
- packages/fxa-auth-server/test/local/routes/totp.js
- packages/fxa-auth-server/test/local/senders/emails.ts
- packages/fxa-auth-server/test/mocks.js
- we have a new endpoint that allows changing 2FA
- Creates a new email template for successful 2FA replacement to be sent in the /totp/replace endpoint
Closes: FXA-12140
> feat(email): Create new email template for 2FA replacement

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/layout.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/layout.tsx
- apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(startLayout)/layout.tsx
- apps/payments/next/app/[locale]/subscriptions/layout.tsx
- apps/payments/next/auth.ts
- libs/payments/ui/src/lib/client/components/Header/index.tsx
- The Header component currently requires consumers to pass in the signout function, which has typically been a server action calling the next-auth server signOut function.
- Use the next-auth client signOut function to simplify the Header component.
There should be no difference in functionality. This is purely a simplification of the <Header> component by removing one of it's required props.
> feat(next): use client signOut function

- packages/functional-tests/pages/settings/components/connectedService.ts
- packages/functional-tests/pages/settings/components/dataTrio.ts
- packages/functional-tests/pages/settings/components/unitRow.ts
- packages/functional-tests/pages/settings/index.ts
- packages/functional-tests/pages/settings/layout.ts
Because:
* Accessing actinos directly on page, like page.click() are deprecated in favor us locator() context
This Commit:
* Updates any reference to the deprecated function calls with proper PW actions
Closes #FXA-9658
The original ticket (FXA-9658) is calling out that accessing element and other functions directly on the `page` object is deprecated in favor of accessing them through the `locator()` or similar element references. 
One in particular that is also found with a warning from PW is `await page.waitForTimeout()`. This is just not a great practice can introduce flakiness. I've logged a [follow up ticket](https://mozilla-hub.atlassian.net/browse/FXA-12248) …
> chore(functional-tests): Remove deprecated page.* actions

- packages/fxa-settings/src/components/ButtonBack/calculate-contrast.test.tsx
- packages/fxa-settings/src/components/ButtonBack/calculate-contrast.ts
- packages/fxa-settings/src/components/ButtonBack/index.stories.tsx
- packages/fxa-settings/src/components/ButtonBack/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryChoice/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/index.tsx
Because:
* Our 'back' arrow contrast with only text-grey-400 is poor against our CMS configurable background colors/gradient
This commit:
* Adds a color contrast check against the BG color or gradient average and returns a white, default (grey-400), or dark (grey-600) color accordingly
* Adds new tests and stories
closes FXA-12207
> feat(cms): Set back arrow color based on CMS BG color

- _scripts/l10n/bundle.sh
- The ftl comments are only useful for translating, we don't need them in bundled ftl files
- Removes lines that start with "#"
Closes: https://mozilla-hub.atlassian.net/browse/FXA-12260
I'm a bit surprised but this reduces our ftl file sizes by roughly ~50kb per locale (~40%). This seems significant and could help mobile users espeically.
> fix(bundle): Remove comments from ftl files when bundling

- packages/fxa-settings/src/components/Settings/Page2faReplaceBackupCodes/en.ftl
* tfa-replace-code-download-description contains a string with a straight quote instead of a curly quote: Strings with apostrophes should use foo’s instead of foo's.
* Adds the curly quote
> fix(l10n): Fix linter error

- packages/fxa-react/styles/ctas.css
- CMS button turns white on hover in older browsers because of the `color-mix` CSS function is not supported.
- gracefully fallbacks to no darkening
Closes: FXA-12185
> fix(cms): fix CMS button turning white on hover in old browsers

- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/container.test.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/container.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/index.stories.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/index.test.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/index.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/interfaces.ts
* Backup codes were not generated when recovery phone was unavailable as a recovery option during inline setup (e.g., for locations outside Canada/US)
* Ensure backup codes are generated and available when setting up 2FA inline, whether choice screen is shown or not
Closes: FXA-12181
> fix(settings): Ensure backup codes generated when phone not available

- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/index.test.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/index.tsx
- Full phone number is displayed on the “Two-step authentication enabled” page
- makes the page only display the last 4 digits
Closes: FXA-12277
A side note: Currently we just assume that all phone numbers are 10 digits long. We will want to programmatically calculate the number of dots before the last 4 digits when we expand the sms option outside of North America.
> fix(2fa): full phone number displayed on the “Two-step authentication enabled” page

- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/container.test.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/index.test.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/index.tsx
* When recovery phone is not available as a recovery method, the incorrect success screen was shown
* Handle the case where no choice screen is shown and user is directly navigated to backup codes
* Adds more unit tests
Closes: FXA-12282
To test locally:
- Either do not set a geo location override in local env or set the override to a non US/Canada location, this results in recovery phone not being available
- Use the Signin with 2FA required flow from 123Done to trigger the inline 2FA setup flow
- Only backup codes should be available as recovery method and the final confirmation screen should show that backup codes were enabled
> fix(setting): Show correct success screen after inline 2FA setup

- packages/fxa-settings/src/pages/InlineRecoverySetup/container.tsx
- packages/fxa-settings/src/pages/InlineRecoverySetupFlow/container.tsx
- packages/fxa-settings/src/pages/InlineTotpSetup/container.test.tsx
- packages/fxa-settings/src/pages/InlineTotpSetup/container.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.tsx
- packages/fxa-settings/src/pages/Signin/index.test.tsx
- packages/fxa-settings/src/pages/Signin/utils.ts
* Forced 2FA OAuth flows without existing TOTP were incorrectly routed to TOTP code
* Unverified sessions should complete email verification before 2FA setup
* Revise navigation targets for unverified session
* Update tests to match
Closes: FXA-12285
> fix(settings): correct unverified session and 2FA routing

- packages/fxa-auth-server/lib/account-events.ts
- packages/fxa-auth-server/lib/db.ts
- packages/fxa-auth-server/lib/routes/utils/security-event.ts
- packages/fxa-shared/.eslintrc
- packages/fxa-shared/db/models/auth/security-event.ts
- Pretty sure this responsible for our DB 'mysql convert' errors
- We can make `recordSecurityEvent` typesafe.
- Adds type safety, so we must define the name
- Improves async/await chain. It should really be up to the calling code, not a deeper layer if the call is fire and forget.
- Adopts auth-server's eslint config in fxa-shared... 
Closes: [FXA-11681](https://mozilla-hub.atlassian.net/browse/FXA-11681)
- Without this using auth-server's eslint config in fxa-shared, it wouldn't pass pre commit linting. I'm not sure how anybody ever changed this file! Basically, with previous rule set, eslint didn't like `} as const;` trailing the security event names.
- I strongly …
> bug(auth, shared): Make security event names typesafe

- packages/functional-tests/lib/sms.ts
- packages/functional-tests/pages/baseTokenCode.ts
- packages/functional-tests/pages/settings/components/unitRow.ts
- packages/functional-tests/pages/settings/recoveryPhone.ts
- packages/functional-tests/pages/signin.ts
- packages/functional-tests/tests/settings/recoveryPhone.spec.ts
- packages/functional-tests/tests/settings/replace2fa.spec.ts
- packages/functional-tests/tests/settings/totpRecoveryCode.spec.ts
* We want functional test coverage of the workflows to change 2FA
* Adds new tests for Change 2FA
* Adds a few new functions to page objects needed for the Change 2FA
flows
* Has a few cleanups of code, removing unsued vars, unneccessary
await, etc
Closes: FXA-12244
> chore(functional-tests): add tests for 2fa change workflows

- packages/fxa-settings/src/components/FormVerifyCode/index.test.tsx
- packages/fxa-settings/src/components/FormVerifyCode/index.tsx
- packages/fxa-settings/src/components/FormVerifyCode/mocks.tsx
- packages/fxa-settings/src/components/RecoveryKeySetupHint/index.test.tsx
- packages/fxa-settings/src/pages/InlineTotpSetup/old.tsx
- packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.test.tsx
- packages/fxa-settings/src/pages/Signin/SigninUnblock/index.test.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.test.tsx
- Turns out we allow code submissions even if they are invalid and have no chance of being verified
- Disable to submit button until code entered matches the correct pattern
- When a user submits a code, a submit metric is logged and this skews our conversion rates
- Don't allow submission of codes that do not ahve the correct format
- Uses React Form Hook "watch" to test the code validation
- Adds additional tests in FormVerifyCode component
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11965
Button disabled on load:
Button disabled with invalid format code:
Button enabled for valid format code:
I thought about writing a functional test for this but the coverage in unit tests seemed good.
> fix(metrics): Don't enable code submission until a valid code is entered

- libs/payments/cart/src/lib/checkout.service.spec.ts
- libs/payments/cart/src/lib/checkout.service.ts
- libs/payments/customer/src/lib/customer.manager.spec.ts
- libs/payments/customer/src/lib/customer.manager.ts
- libs/payments/customer/src/lib/subscription.manager.spec.ts
- libs/payments/customer/src/lib/subscription.manager.ts
- libs/payments/customer/src/lib/types.ts
- libs/payments/management/src/lib/subscriptionManagement.service.spec.ts
- libs/payments/management/src/lib/subscriptionManagement.service.ts
- Subscription update will fail validation if existing metadata is invalid.
- Subscription create, and customer update managers do not validate metadata.
- Modify subscription manager update and create and customer manager update metadata types to only allow valid metadata values.
Closes: #PAY-3203
Co-authored-by: Julian Poyourow <julianpoyo@gmail.com>
> feat(next): validate metadata in payments-customer libs

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/mozilla.ts
- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-auth-server/package.json
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/price1.json
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/price2.json
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/price3.json
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/mozilla.js
- packages/fxa-shared/dto/auth/payments/iap-subscription.ts
- packages/fxa-shared/payments/iap/apple-app-store/subscription-purchase.ts
- packages/fxa-shared/payments/stripe.ts
- packages/fxa-shared/subscriptions/types.ts
- Currency and pricing information can no longer be reliably retrieved from the /subscriptions/plans API, for a specific price ID, due to the utilization of multi-currency prices.**
- Updates the /billing-and-subscriptions API to return relevant price info for a customers subscriptions, with correct currency and pricing information.
Closes: #PAY-3192
> fix(auth): provide price info on billing-and-subscriptions

- apps/payments/next/app/[locale]/subscriptions/layout.tsx
- the bottom of the email was cut off
- removes leading
Before
After
> polish(payments-next): Remove leading from email display on SubMan page

- packages/fxa-content-server/server/config/local.json-dist
- packages/fxa-content-server/server/lib/beta-settings.js
- packages/fxa-content-server/server/lib/configuration.js
- packages/fxa-content-server/server/lib/routes/react-app/route-definition-index.js
- packages/fxa-react/components/Footer/index.test.tsx
- packages/fxa-react/components/Footer/index.tsx
- packages/fxa-settings/src/components/AppLayout/index.test.tsx
- packages/fxa-settings/src/components/AppLayout/index.tsx
- packages/fxa-settings/src/components/FormVerifyTotp/index.test.tsx
- packages/fxa-settings/src/components/InputPhoneNumber/index.test.tsx
- packages/fxa-settings/src/components/LocaleToggle/en.ftl
- packages/fxa-settings/src/components/LocaleToggle/index.test.tsx
- packages/fxa-settings/src/components/LocaleToggle/index.tsx
- packages/fxa-settings/src/components/Settings/SettingsLayout/index.tsx
- packages/fxa-settings/src/contexts/DynamicLocalizationContext.tsx
- packages/fxa-settings/src/index.tsx
- packages/fxa-settings/src/lib/config.ts
- packages/fxa-settings/src/lib/glean/index.test.ts
- packages/fxa-settings/src/lib/hooks/useLocaleManager.ts
- packages/fxa-settings/src/lib/locales.ts
- packages/fxa-settings/src/models/hooks.ts
- packages/fxa-settings/src/pages/ResetPassword/AccountRecoveryConfirmKey/index.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPassword/index.test.tsx
- packages/fxa-settings/src/pages/ResetPassword/ResetPasswordConfirmed/index.test.tsx
- We want to be able to switch locales easily, without going to browser settings and setting preferences
- Added `LocaleToggle` component for users to switch languages.
- Implemented `useLocaleManager` hook to handle locale state and switching logic.
- Updated `AppLayout` to conditionally render the `LocaleToggle` based on the `showLocaleToggle` prop.
- Adds a local storage key to keep track of the language selected.
- Adds `LocaleToggle` to AppLayout and SettingsLayout
Closes: https://mozilla-hub.atlassian.net/browse/FXA-12273
I ended up using this while working on cms l10n customization. Seems like a useful thing for others too. It puts a langauge toggle in the lower left hand corner, uses grey text to support light and dark backgrounds, does not refresh the page to reload languages.
> feat(l10n): Implement dynamic localization context and language switcher

- libs/payments/customer/src/lib/paymentMethod.manager.spec.ts
- libs/payments/stripe/src/index.ts
- libs/payments/stripe/src/lib/factories/card-payment-method.factory.ts
- libs/payments/stripe/src/lib/stripe.client.types.ts
- In general, "any" is not allowed in the codebase.
- Removes "any" from the unit test.
> polish(payments-next): Remove "any" from paymentMethod.manager.spec.

- packages/fxa-settings/src/models/hooks.ts
- We can not cleanly uplift this fix from main because of changes to how localization is loaded
- Target the train exactly with required fix
Closes: https://mozilla-hub.atlassian.net/browse/FXA-12308
> fix(locale): Only load cms customization for en only locales (for uplif to 317)

- packages/fxa-settings/src/lib/config.ts
- packages/fxa-settings/src/models/hooks.test.ts
- packages/fxa-settings/src/models/hooks.ts
- Users that have multiple locales specified in browser ie (es, en), with at least one of them being English could be served the cms customization
- This would show the page half with English and half with other locale
- Fixes this by only checking the users preferred locale
Closes: https://mozilla-hub.atlassian.net/browse/FXA-12308
We should try to uplift this to prod if possible.
> fix(locale): Only use the users preferred locale to check for cms customization

- apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/start/page.tsx
- apps/payments/next/app/[locale]/auth/error/page.tsx
- libs/payments/ui/src/lib/client/components/CheckoutForm/index.tsx
- libs/payments/ui/src/lib/client/components/CouponForm/index.tsx
- libs/payments/ui/src/lib/client/components/PageNotFound/index.tsx
- libs/payments/ui/src/lib/client/components/PaymentMethodManagement/index.tsx
- libs/payments/ui/src/lib/client/components/SelectTaxLocation/index.tsx
- libs/payments/ui/src/lib/client/components/SignInForm/index.tsx
- the height was previously removed from buttons in other to reuse the component in the new Subscription Management page; however, the height was not added to existing buttons
- adds the height to existing buttons
Closes: [PAY-3225](https://mozilla-hub.atlassian.net/browse/PAY-3225)
[PAY-3225]: https://mozilla-hub.atlassian.net/browse/PAY-3225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(payments-ui): Fix height of buttons

- packages/fxa-settings/src/models/Session.ts
- There's no guarantee that session is in the apollo cache.
- If there's no session in the cache we'd hit a run time error
- Handles the case that session is missing.
- Creates empty string fallback for token getter
- Creates false fallback for verified getter
Closes: FXA-12299
I _think_ this is okay to do. Note that sentry issue indicates this happening when users hit the `ModalVerifySession` dialog, and somehow there's not a session in the apollo cache. In this case, this PR works around the issue by essentially falling back to a session state that no sessionToken and is not verified. I feel like this fallback state adequately represents a lack of the session in …
> bug(setting): Fix issue with empty session in cache.

- packages/fxa-settings/src/models/hooks.test.ts
- packages/fxa-settings/src/models/hooks.ts
- We could possibly show translated strings with customization
- If language toggle is set, check that language for en, otherwise check `navigator.language`
> fix(locale): Small fix for language selector

- packages/fxa-react/lib/storybooks.tsx
- packages/fxa-settings/src/components/Settings/ModalMfaProtected/en.ftl
- packages/fxa-settings/src/components/Settings/ModalMfaProtected/index.stories.tsx
- packages/fxa-settings/src/components/Settings/ModalMfaProtected/index.test.tsx
- packages/fxa-settings/src/components/Settings/ModalMfaProtected/index.tsx
Closes #
- we need a modal for MFA confirmation code input for `MfaProtectedActionGuard`
- creates a new `ModalMfaProtected` component, with stories and unit tests.
Closes: FXA-12302
> feat(mfa): create new ModalMfaProtected component

- packages/functional-tests/lib/sms.ts
- packages/functional-tests/lib/targets/index.ts
- packages/functional-tests/lib/totp.ts
- packages/functional-tests/pages/settings/totp.ts
- packages/functional-tests/tests/cms/cms-2fa.spec.ts
- packages/functional-tests/tests/key-stretching-v2/totp.spec.ts
- packages/functional-tests/tests/misc/recoveryKeyPromoInline.spec.ts
- packages/functional-tests/tests/misc/relayIntegration.spec.ts
- packages/functional-tests/tests/oauth/totp.spec.ts
- packages/functional-tests/tests/react-conversion/signinTotp.spec.ts
- packages/functional-tests/tests/resetPassword/oauthResetPassword.spec.ts
- packages/functional-tests/tests/resetPassword/resetPassword2FA.spec.ts
- packages/functional-tests/tests/settings/recoveryPhone.spec.ts
- packages/functional-tests/tests/settings/replace2fa.spec.ts
- packages/functional-tests/tests/settings/setup2faWithBackupCodes.spec.ts
- packages/functional-tests/tests/signin/signinBlocked.spec.ts
- packages/functional-tests/tests/syncV3/signIn.spec.ts
Because:
- We centralized the sms functions onto the smsClient
This Commit:
- Updates any funcitonal test references to the getPhoneNumber and other functions to use the target.smsClient
- Updates the call signature for `getCode` for ease of use
Closes: FXA-12293
> chore(functional-tests): Update sms references to smsClient

- packages/fxa-settings/src/components/App/index.tsx
- We currently show the "General application error" message when user is in settings page but the underlying session token becomes invalid
- I suspect its how the pages are being lazy loaded, we did have logic to do this redirect but 
- Does a simple redirect if user is not signed in
Closes: https://mozilla-hub.atlassian.net/browse/FXA-12309
There is probably a better way to do this and we should try to find the actual reason why its failing.
> fix(logout): Redirect to email first if user is at settings but not valid session

- packages/fxa-auth-server/config/index.ts
Because:
- We want to ease the process for new sync logins
This Commit:
- Increases auth server ipProfiling allowedRecency default value to 7 days
Closes: FXA-12132
> chore(auth): Update ipProfiling allowedRecency to 7 days

- packages/fxa-settings/src/components/ThirdPartyAuth/__snapshots__/index.test.tsx.snap
- packages/fxa-settings/src/components/ThirdPartyAuth/index.test.tsx
- packages/fxa-settings/src/components/ThirdPartyAuth/index.tsx
Because:
- We want to improve the visibility and contrast for Google Thirdparty Auth button
This Commit:
- Adds a border to the button container of the Google svg
- Adds snapshot tests for both thirdpartyauth buttons
Closes: FXA-12325
> chore(settings): Add border to Google thirdparty auth button

- packages/fxa-react/lib/utils.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.test.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.tsx
- packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/mocks.tsx
- SubPlat is requesting the ability to understand if a user logged in with a new account or with a pre-existing account.
- attaches newAccount=true or newAccountVerification=true query params to the redirect back to RPs based on flow type.
Closes: FXA-12292
> feat(signin): return newAccount and newAccountVerification flags with login redirect

- libs/payments/customer/src/lib/paymentMethod.manager.ts
- The subscriptions management page was no longer displaying payment information correctly.
- Shows correct payment information.
Closes: (issue number)#[PAY-3226](https://mozilla-hub.atlassian.net/browse/PAY-3226)
[PAY-3226]: https://mozilla-hub.atlassian.net/browse/PAY-3226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(payments-next): Link disappeared from under Payment Information

- .circleci/config.yml
- .circleci/run-playwright.sh
Because:
- re-run failed tests was not working as the first `circle tests run` consumed the tests list for a count
This commit:
- removes the check-playwright-test-count step so that there is only a single `circle tests run` call
> fix(ci): ensure one circleci tests run call

- packages/fxa-auth-server/lib/routes/utils/account.ts
- packages/fxa-auth-server/test/local/routes/utils/account.js
-  Users getting the "default" cms customization would not get the customized emails
- We were not checking if there was a default entrypoint when entrypoint was not specified
- Checks for entrypoint=default before sending customized emails
Closes: https://mozilla-hub.atlassian.net/browse/FXA-12331
STR:
1. You can try this with 123Done, create a customization with entrypoint=default
2. Go through the 123Done signup/signin flow, don't add any entrypoint to the query params
3. Verify that you get customized emails
> fix(emails): Send customized email when coming from a "default" entrypoint

- packages/fxa-settings/src/components/Settings/MfaGuard/index.test.tsx
- packages/fxa-settings/src/components/Settings/MfaGuard/index.tsx
- packages/fxa-settings/src/components/Settings/ModalMfaProtected/index.stories.tsx
- packages/fxa-settings/src/components/Settings/ModalMfaProtected/index.test.tsx
- packages/fxa-settings/src/components/Settings/ModalMfaProtected/index.tsx
- invalid MFA OTP error states are not handled for the mfa guard
- shows error tooltip on invalid OTP error in the modal
Closes: FXA-12328
> feat(mfa): handle invalid MFA OTP error state for MFA guard

- packages/fxa-settings/src/components/AppLayout/index.tsx
- packages/fxa-settings/src/components/LocaleToggle/en.ftl
- packages/fxa-settings/src/components/LocaleToggle/index.test.tsx
- packages/fxa-settings/src/components/LocaleToggle/index.tsx
- packages/fxa-settings/src/contexts/DynamicLocalizationContext.tsx
- packages/fxa-settings/src/lib/hooks/useLocaleManager.ts
- packages/fxa-settings/src/lib/locales.ts
- I missed some feedback comments
- Adds an option "Browser default" that clears the lanuage local storage key and sets the locale to the browser value
- Updates test to use `userEvent`
- Don't render stray `footer`
> Address feedback for language switcher

- packages/functional-tests/tests/misc/mfa.spec.ts
- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/lib/routes/mfa.ts
- We didn't check posting a body
- Adds posting a body to the example.
Closes: FXA-12351
This was prompted by some feedback that POSTs with a payload where being rejected. These e2e test indicates that no changes are necessary. Let's figure out exactly what's going on here.
> polish(auth): Make sure posts with payloads work for mfa auth strategy

- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/emails.js
- packages/fxa-auth-server/lib/routes/password.ts
- packages/fxa-auth-server/lib/routes/recovery-codes.js
- packages/fxa-auth-server/lib/routes/recovery-key.js
- packages/fxa-auth-server/lib/routes/recovery-phone.ts
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/lib/routes/utils/signin.js
- packages/fxa-auth-server/test/local/ip_profiling.js
- packages/fxa-auth-server/test/local/routes/recovery-keys.js
- packages/fxa-auth-server/test/mocks.js
- If an error occurs and the call is not awaited, the call stack is spliced and the source of the issue is difficult to track down.
- Not await is likely a premature and unnecessary optimization.
- awaits all the calls to record security event
We decided to do this in two steps just in case we needed to rollback this one for performance reasons.
> polish(auth): Make sure calls to recordSecurityEvent are awaited

- .github/workflows/docker.yml
- We want to sanitize the tag avoid bogus values
- It's better not to ENV vars
- Uses env vars instead of replacements
- Validates the tag name
- Makes quoting consistent
Closes: FXA-12358
> task(ci): Clean up tag job

- packages/fxa-auth-server/config/index.ts
Because:
- We want to ease the process for new sync login
This Commit:
- Increases the maxAge for skipForNewAccounts to 48 hours
Closes #FXA-12131
> chore(auth): Update skipForNewAccounts max age

- packages/fxa-settings/src/pages/Authorization/container.test.tsx
- packages/fxa-settings/src/pages/Authorization/container.tsx
- The way useState was invoked was incorrect and resulted in re-render loop.
- The container component had no test coverage!
- Simply returns the error page when there is an oAuthDataError.
- Adds full test coverage
Closes: FXA-12296
Before:
After:
This is easy to trigger. Simply enter a bad redirect_uri in the URL provided to `/authorization`. For example, locally navigating to this URL would trigger the edge case: `http://localhost:3030/authorization/signin?client_id=dcdb5ae7add825d2&redirect_uri=http%3A%2F%2Flocallllhost%3A8080%2Fapi%2Foauth&scope=profile%20openid&response_type=code&state=45bccf18e0db02c8783ff9fa095fb9589d1b43cb480431e55d519f6e5bb07f3d&access_type=offline`
> bug(settings): Fix too many re-renders

- .vscode/launch.json
- libs/payments/iap/src/lib/google/google-iap-purchase.manager.spec.ts
- libs/payments/iap/src/lib/google/google-iap-purchase.manager.ts
- libs/payments/iap/src/lib/google/google-iap.client.spec.ts
- libs/payments/iap/src/lib/google/google-iap.client.ts
- libs/payments/iap/src/lib/google/google-iap.error.ts
- packages/fxa-auth-server/lib/payments/iap/google-play/user-manager.ts
- packages/fxa-shared/payments/iap/google-play/purchase-manager.ts
- packages/fxa-shared/payments/iap/google-play/user-manager.ts
- We are seeing issues where some purchaseTokens are returning invalid and blocking user access to their account.
- Ignores purchases with an invalid purchaseToken (can happen after 60 days of expiry, where our Firestore cache missed an update)
Closes: PAY-3244
> fix(iap): handle invalid google play store purchaseTokens

- packages/functional-tests/tests/settings/changeEmail.spec.ts
- packages/functional-tests/tests/settings/changeEmailBlocked.spec.ts
- packages/functional-tests/tests/signin/signinBlocked.spec.ts
- packages/functional-tests/tests/syncV3/fxDesktopV3ForceAuth.spec.ts
- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/docs/swagger/emails-api.ts
- packages/fxa-auth-server/lib/routes/emails.js
- packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
- packages/fxa-graphql-api/src/gql/account.resolver.ts
- packages/fxa-graphql-api/src/gql/dto/input/email.ts
- packages/fxa-graphql-api/src/gql/dto/input/verify-email.ts
- packages/fxa-settings/src/components/Settings/PageSecondaryEmailAdd/index.tsx
- packages/fxa-settings/src/components/Settings/PageSecondaryEmailVerify/index.tsx
- packages/fxa-settings/src/components/Settings/index.test.tsx
- packages/fxa-settings/src/components/Settings/index.tsx
- packages/fxa-settings/src/lib/types.ts
- packages/fxa-settings/src/models/Account.ts
Because:
- We want to protect adding a secondary email to an account
This commit:
- Wraps the SecondaryEmail pages in the MfaGuard
- Updates Auth Client to require JWT
- Updates the auth server to use the Mfa auth strategy for
secondary_email endpoints
Closes: FXA-12224
I added some recordings of the flows since those are easier to show. I tested more cases manually, but these are the more major ones.
Happy path:
https://github.com/user-attachments/assets/bba63a4b-0923-4f68-894b-f5ffe70ae17a
Expired token while sitting on `/settings`:
https://github.com/user-attachments/assets/447a6127-1632-466c-b5c8-af0a13753871
Restarting flow for an unconfirmed email:
https://github.com/user-attachments/assets/e656c550-7c50-434e-b024-37e0e0a4b682
Any other …
> feat(mfa): Wrap secondary email pages in MfaGuard

- packages/fxa-auth-server/lib/payments/stripe-firestore.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe-firestore.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-shared/payments/stripe-firestore.ts
- We want transactions on our payment method and invoice cache stripe webhook endpoints to avoid situations where stale data could get written.
- Adds firestore transactions to those method within stripe-firestore, and marks non-transactionalized methods as deprecated (we don't want to modify legacy 2.5 code).
Closes: PAY-3183
> fix(stripe-webhook): transactionalize payment method and invoice cache

- packages/fxa-auth-server/lib/routes/mfa.ts
- MFA OTP code emails are sent to the old primary email address after swapping primary and secondary emails
- make it send to both primary and secondary email
Closes: FXA-12409
> fix(mfa): MFA OTP not sent to all emails

- libs/payments/ui/src/lib/client/components/SubscriptionContent/index.tsx
- “Cancel subscription” shows as active without clicking on the confirmation checkbox.
- After cancelling, checkedState is true and is never reset back to false.
- Sets checkedState to false when it is not clicked.
Closes: #[PAY-3260](https://mozilla-hub.atlassian.net/browse/PAY-3260)
[PAY-3260]: https://mozilla-hub.atlassian.net/browse/PAY-3260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(payments-next): “Cancel subscription” button is active without marking the checkbox for users that had their subscription previously reactivated

- packages/fxa-settings/src/lib/mfa-guard-utils.test.ts
- packages/fxa-settings/src/lib/mfa-guard-utils.ts
Because:
- There are a few cases where a page cannot directly rely on MFA error-boundary and needs to check the JWT reponse directly
This Commit:
- Adds a mfa-guard-utils to check for a bad JWT server response
- Adds a helper to clear cache when JWT is invalid
> chore(mfa): Add mfa helper utility for checking invalid JWT

- packages/fxa-settings/src/components/ThirdPartyAuth/index.tsx
- packages/fxa-settings/src/pages/Signin/index.tsx
- we want to ensure fallback text in the event fluent lookup fails
- refactors to allow fallback text
Closes: FXA-12397
In response to https://github.com/mozilla/fxa/pull/19441#discussion_r2342373817
> task(settings): add fallback text for linked account 3rd-party auth

- apps/payments/next/app/[locale]/subscriptions/manage/page.tsx
- Date encoded within strong tags on the Payments Screen for IAP subscriptions.
- l10n.getString() was returning the actual string, which included strong tags.
- Uses l10n.getFragmentWithSource() instead.
Closes: #[PAY-3261](https://mozilla-hub.atlassian.net/browse/PAY-3261)
[PAY-3261]: https://mozilla-hub.atlassian.net/browse/PAY-3261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(payments-next): Date encoded within <strong> tags on the Payments Screen for IAP subscriptions

- packages/fxa-auth-server/lib/routes/auth-schemes/mfa.ts
- packages/fxa-auth-server/test/local/routes/auth-schemes/mfa.js
- packages/fxa-auth-server/test/local/routes/mfa.js
- packages/fxa-settings/src/components/Settings/MfaGuard/error-boundary.test.tsx
- The return type must be of type session token, or down stream code can fail
- When `auth.credentials` was populated by the `mfa` auth strategy, downstream code would fail if `authenticatorAssuranceLevel` was accessed.
- Avoids spreading the sessionToken object
- Ensures the original sessionToken object is returned
- A little bit of cleanup... AppError.unauthorized to be consistent with sessionToken strategy
- Adds test to directly test the `mfa` auth strategy.
> bug(auth): Fix mfa strategy return type

- libs/payments/ui/src/lib/client/components/SubscriptionContent/en.ftl
- libs/payments/ui/src/lib/client/components/SubscriptionContent/index.tsx
- In the console -> `Warning: Text content did not match. Server: "$12.00 + $1.07 billed on September 18, 2025" Client: "$12.00 + $1.07 " p`
- Adds "isClient" to eliminate console warning
- Adds missing "tax" to string and updates ftl id used in component
- Updates ftl ids to ids in component
> polish(payments): Fix ftl strings

- apps/payments/next/app/[locale]/subscriptions/manage/page.tsx
- libs/payments/ui/src/lib/client/components/AlertBar/en.ftl
- libs/payments/ui/src/lib/client/components/AlertBar/index.tsx
- libs/payments/ui/src/lib/client/components/Breadcrumbs/en.ftl
- libs/payments/ui/src/lib/client/components/Breadcrumbs/index.tsx
- package.json
- yarn.lock
- Alert dialog was prevent users from using the breadcrumbs and the header menus.
- Allow usage of header menus while alert is active
- Always show dialog close button
- Open PayPal management page in new window
- Changes breadcrumb text to "Manage Payment Methods"
Closes: #PAY-3270 PAY-3273 PAY-3274
> fix(next): enable close on alert dialog

- packages/functional-tests/README.md
- packages/functional-tests/lib/fixtures/standard.ts
- packages/functional-tests/lib/testAccountTracker.ts
- packages/functional-tests/tests/settings/changeEmail.spec.ts
- packages/fxa-auth-server/lib/routes/emails.js
Because:
- We want to make it possible to pre-fetch JWT tokens in functional tests
This Commit:
- Adds a new function to the TestAccountTracker to signup and fetch tokens by scope
- Adds on page load hook to ensure tokens are stored in cache as soon as possible after signin
Closes: FXA-12356
> feat(mfa): Add ability to pre fetch JWT tokens in functional tests

- packages/functional-tests/tests/resetPassword/resetPassword2FA.spec.ts
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/test/local/routes/account.js
* Account recovery key is considered equivalent to 2FA, and the issued token should match 2FA AAL
* When using an account recovery key, verify token with totp-2fa method
* Add a test to verify that this change allows account deletion
Closes: FXA-12425
> bug(auth, tests): Issue AAL2 token for password reset with recovery key

- packages/functional-tests/tests/settings/totpRecoveryCode.spec.ts
- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/docs/swagger/recovery-codes-api.ts
- packages/fxa-auth-server/lib/routes/recovery-codes.js
- packages/fxa-settings/src/components/Settings/Page2faReplaceBackupCodes/index.tsx
- packages/fxa-settings/src/components/Settings/index.test.tsx
- packages/fxa-settings/src/components/Settings/index.tsx
- packages/fxa-settings/src/models/Account.ts
- We want to protect the 'replace backup codes' action with MFA
- Adds an MFA guard to `Page2faReplaceBackupCodes`
Closes: FXA-12232
> task(settings): Wrap 2FA Replace Backup Codes with MFA guard 

- libs/payments/ui/src/lib/utils/getErrorFtlInfo.ts
- User is redirected to old Sub Manage page.
- Redirects user to the new Sub Manage page.
Closes: #PAY-3281
https://github.com/user-attachments/assets/de394f58-4149-4618-8f49-71a3804ea3f3
> fix(payments-next): [Payments-Next Subscription] Manage my subscription from subplat redirects to old Subscriptions page

- packages/functional-tests/tests/key-stretching-v2/recoveryKey.spec.ts
- packages/functional-tests/tests/key-stretching-v2/recoveryKeyUpgrade.spec.ts
- packages/functional-tests/tests/misc/recoveryKeyPromoInline.spec.ts
- packages/functional-tests/tests/misc/recoveryKeyPromoSettingsBanner.spec.ts
- packages/functional-tests/tests/resetPassword/oauthResetPasswordRecoveryKey.spec.ts
- packages/functional-tests/tests/resetPassword/resetPassword2FA.spec.ts
- packages/functional-tests/tests/resetPassword/resetPasswordRecoveryKey.spec.ts
- packages/functional-tests/tests/settings/recoveryKey.spec.ts
- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/docs/swagger/recovery-key-api.ts
- packages/fxa-auth-server/lib/routes/recovery-key.js
- packages/fxa-settings/src/components/Settings/FlowRecoveryKeyConfirmPwd/index.tsx
- packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.stories.tsx
- packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.test.tsx
- packages/fxa-settings/src/components/Settings/PageRecoveryKeyCreate/index.tsx
- packages/fxa-settings/src/components/Settings/index.test.tsx
- packages/fxa-settings/src/components/Settings/index.tsx
- packages/fxa-settings/src/lib/types.ts
- packages/fxa-settings/src/models/Account.ts
- packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/container.tsx
- We want to protect the create account recovery keys with an MFA guard
- Adds an MFA guard to to the create account recovery key page
Closes: FXA-12235
>  task(settings): Wrap create account recovery keys with MFA guard 

- libs/payments/customer/src/lib/invoice.manager.ts
- Retrieving upcoming invoices using customer and subscription fails for customers with a subscription set to cancel at period end.
- Updates query fetching an upcoming invoice to always behave as if the subscription is not set to cancel at period end.
Closes: #PAY-3290
> fix(next): do not crash sub manage on canceled sub

- packages/fxa-settings/src/pages/Signin/container.tsx
- packages/fxa-settings/src/pages/Signin/index.test.tsx
- packages/fxa-settings/src/pages/Signin/index.tsx
Because:
* When users are taken to '/signin_token_code' from a sign in with password navigation, we don't automatically send the associated email
This commit:
* Ensures the email is sent
fixes FXA-12467
---
See ticket for how to reproduce.
> fix(email): Send signin code for sign in with password unverified session case

- packages/fxa-settings/src/components/Settings/UnitRowRecoveryKey/index.tsx
- packages/fxa-settings/src/models/Account.ts
* The invalid jwt error was uncaught on ARK delete
* manually clear the jwt from cache and reshow the mfa modal
Closes: FXA-12478
> fix(settings): General app error with invalid jwt on ARK delete

- packages/functional-tests/lib/ci-reporter.ts
Because:
- We only capture and report the top 10 slowest tests, that take > 15 seconds
- And we want better visibility into long running individual tests
This Commit:
- Adds a human readable format of test duration to each test output for CI
> chore(functional-tests): Add test duration to ci reporter

- packages/fxa-settings/src/components/Settings/UnitRowRecoveryKey/index.tsx
- can't dismiss mfa guard for ARK delete
- makes mfa guard for ARK delete dismissible
Closes: FXA-12470
> fix(mfa): fix can't dismiss mfa guard for ARK delete

- packages/fxa-settings/src/pages/Signin/index.stories.tsx
I cannot reproduce the issue in Storybook, locally, or in stage. I've asked QA to look at this again but in the meantime here's a story for this state that we must have lost at some point.
closes FXA-12481
> fix(stories): Add Sync signin without password story

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/senders/emails/partials/subscriptionSupportGetHelp/en.ftl
- packages/fxa-payments-server/backstage.yaml
- yarn.lock
Because:
* The subscription management link was being set to the content server's /subscription url
This commit:
* The subscription management link now uses the config value
* The subscription management link now points to SP3's page
Closes #PAY-3302
> fix(emails): Fix subscription management link in emails

- packages/fxa-settings/src/components/Settings/MfaGuard/index.test.tsx
- packages/fxa-settings/src/lib/cache.ts
- packages/fxa-settings/src/models/Account.ts
- If a flow is started with an expired token, the MFA dialog will not render until a web request is made that invalidates the token. Once the token is invalidated, the flow must be restarted... This is pretty annoying!
- Adds the ability to decode the JWT's payload
- Adds a check to determine if the JWT is expired to the hasToken check.
- If the token is expired, hasToken returns false, and the MFA dialog will render, so the user can get a valid JWT before the flow starts.
To make this easier to test, change the config for `mfa.jwt.expiresIn` to 30 seconds in the auth server config.
Testing steps:
- Sign in
- Click account recovery key
- Go …
> bug(settings): Add pre-check for JWT expiration

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/db.ts
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/utils/security-event.ts
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-auth-server/test/local/routes/utils/security-event.ts
- packages/fxa-auth-server/test/mocks.js
- packages/fxa-shared/db/models/auth/security-event.ts
- yarn.lock
-   Users were required to verify their login with a confirmation code every time they signed in, even from devices they regularly use
- Adds device fingerprinting to skip signin confirmation for recognized devices
- Implements user agent matching against recent verified logins within a configurable timeframe (default
7 days)
- Adds configuration options for enabling/disabling the feature and report-only mode
- Creates new database query methods to retrieve verified login security events
Closes: https://mozilla-hub.atlassian.net/browse/FXA-12422
To test
1. In dev.json for auth-server, set skipForNewAccounts=false, allowedRecency=0
2. Create an account for Sync
3. Login with account for Sync (first time requires confirmation), disconnect
4. Login again with account for Sync (no prompt for …
> feat(skip): Skip confirmation code for a seen device user agent

- packages/fxa-react/.eslintrc.json
- packages/fxa-react/Gruntfile.js
- packages/fxa-react/components/AppErrorDialog/index.stories.tsx
- packages/fxa-react/components/AppErrorDialog/index.tsx
- packages/fxa-react/components/Header/index.stories.tsx
- packages/fxa-react/components/LinkExternal/index.stories.tsx
- packages/fxa-react/components/LoadingSpinner/index.stories.tsx
- packages/fxa-react/components/LoadingSpinner/index.test.tsx
- packages/fxa-react/components/LoadingSpinner/index.tsx
- packages/fxa-react/components/LogoLockup/index.test.tsx
- packages/fxa-react/components/Portal/index.test.tsx
- packages/fxa-react/components/Portal/index.tsx
- packages/fxa-react/extract-imported-components.js
- packages/fxa-react/lib/hooks.stories.tsx
- packages/fxa-react/lib/hooks.test.tsx
- packages/fxa-react/lib/test-utils/index.test.tsx
- packages/fxa-react/lib/test-utils/localizationProvider.tsx
- packages/fxa-react/lib/utils.tsx
- The eslintrc.json didn't match fxa-settings eslintrc.json
- The prettier rules and the previous eslintrc.json rules conflicted
- Applies the eslintrc.json config in settings to fxa-react
- Fixes all the problems...
I ran into these problems while working on #19531.
> polish(fxa-react): Fix eslint in fxa-react

- packages/fxa-auth-server/lib/routes/auth-schemes/mfa.ts
- packages/fxa-auth-server/lib/server.js
- packages/fxa-auth-server/test/local/routes/auth-schemes/mfa.js
- packages/fxa-auth-server/test/local/routes/mfa.js
- packages/fxa-auth-server/test/mocks.js
- We should ensure the parent session meets the verification requirements
- Copies logic from `verified-session-token.js` into the `mfa.ts` auth strategy
Closes: FXA-12432
Note, I've also filed a clean up so we can reuse this logic and fix the copy paste. This will done as part of a larger MFA clean up effort.
> task(auth): Add verified session checks to mfa strategy

- packages/functional-tests/pages/settings/components/connectedService.ts
- packages/functional-tests/pages/settings/components/unitRow.ts
- packages/fxa-settings/src/components/App/index.test.tsx
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/components/Settings/index.test.tsx
- packages/fxa-settings/src/components/Settings/index.tsx
- packages/fxa-settings/src/lib/gql.ts
Because:
* Users should not be able to directly bypass /signin_token_code
This commit:
* Uses session.isSessionVerified to check if the user should be redirected away
closes FXA-12472
---
We can now use `session.isSessionVerified` for this as of my last PR.
You can test this with the `SIGNIN_CONFIRMATION_TOKEN_VERIFICATION` flag to get in an unverified state. Try to access settings directly after you're taken to `/signin_token_code`, and see you'll be redirected away from Settings.
> fix(settings): Redirect users from /settings if session is unverified
