packages/fxa-auth-server/config/index.js, packages/fxa-auth-server/lib/routes/support.js, packages/fxa-auth-server/test/local/routes/support.js
Because:
* Support wants to easily filter on topic.
This commit:
* Moves the support topic to a custom field.
Closes #3883
=> feat(auth-server): support topic as custom fld

packages/fxa-auth-server/lib/routes/subscriptions.js
Didn't update tests around this, but noticed some internal service errors on subscription create that this seems to solve.
=> fix(payments): fix subscription create route with missing awaits

packages/fxa-auth-server/lib/routes/subscriptions.js
Because:
* Routes that hit Stripe should be minimized to when we know the user
is a customer.
This commit:
* Uses only the Redis copy of stripe data in more routes that we could
accidentally hit in settings pages for all FxA users.
=> fix(auth-server): use cached customer only

packages/fxa-auth-db-mysql/db-server/index.js, packages/fxa-auth-db-mysql/db-server/test/backend/db_tests.js, packages/fxa-auth-db-mysql/db-server/test/backend/remote.js, packages/fxa-auth-db-mysql/lib/db/mysql.js, packages/fxa-auth-db-mysql/lib/db/patch.js, packages/fxa-auth-db-mysql/lib/db/schema/patch-106-107.sql, packages/fxa-auth-db-mysql/lib/db/schema/patch-107-106.sql, packages/fxa-auth-server/lib/db.js, packages/fxa-auth-server/lib/routes/recovery-key.js, packages/fxa-auth-server/test/client/api.js, packages/fxa-auth-server/test/client/index.js, packages/fxa-auth-server/test/local/routes/recovery-keys.js, packages/fxa-auth-server/test/mocks.js, packages/fxa-auth-server/test/remote/recovery_key_tests.js
Fixes #3936 
This PR adds the DB support and auth-server support for enabling a recovery key. The enable flag is specified when creating the recovery key.
Some notes
* Added `enabled` column on recoveryKey table
* New db method `updateRecoveryKey_1` to update column value
* New route `/recoveryKey/verify` can enable a recovery key
=> feat(keys): Add ability to enable/disable recovery key

packages/fxa-content-server/app/scripts/templates/settings/recovery_codes.mustache
Fixes #4088 
Turns out that this wasn't a circleci issue but the string extraction script error. The script fails to extract empty string values like `value=""`. I've removed this and the extraction should work as expected.
=> fix(l10n): Remove empty `value` field since that fails to extract string

packages/fxa-auth-server/lib/routes/account.js
Because:
* SubHub will handle deleting the customer and cleanup.
This commit:
* Updates the metadata attribute subhub is watching for.
=> fix(auth-server): don't delete the stripe customer

packages/fxa-content-server/app/scripts/templates/settings/delete_account.mustache, packages/fxa-content-server/app/tests/spec/views/settings/delete_account.js
fixes #4041 
Added a test to make sure this doesn't reoccur.
Co-authored-by: Ben Bangert <ben@groovie.org>
=> fix(delete_account): Change manage subscription link conditional from 'for' loop to 'if at least one'

packages/fxa-content-server/app/styles/_breakpoints.scss
[See this doc](https://docs.google.com/document/d/1JL3dgpAvzmSrGIZg9MB0APNoYFG325n2kJaUlb1hYDo) for more details on why these values and media queries were chosen.
No associated issue. We intended on adding these new breakpoints when our CSS is updated from the impending settings redesign, but it seemed prudent to add them now for use in the payments server for the FPN mobile updates/enhancements. Current functionality has not been changed.
`$breakpoints` seemed like an appropriate map name for the new values. I changed the old map name to `$media-queries` since that more accurately describes what they are (although technically the media query includes `@media` but… I digress). The `respond-to` mixin still uses this map. These can be removed when we don't use them anymore.
I checked:
- …
=> feat(css): Add new breakpoints and corresponding mixins

.circleci/config.yml
Because node:8 is three years old, and the default JRE version on it is
old enough that the fxa-js-client is failing on:
- E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/o/openjdk-8/openjdk-8-jre-headless_8u232-b09-1~deb9u1_amd64.deb  404  Not Found
- E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/o/openjdk-8/openjdk-8-jre_8u232-b09-1~deb9u1_amd64.deb  404  Not Found
=> chore(CI): update three jobs to use node 12

packages/fxa-auth-server/.nsprc, packages/fxa-event-broker/package-lock.json, packages/fxa-event-broker/package.json, packages/fxa-profile-server/.nsprc, packages/fxa-support-panel/package-lock.json, packages/fxa-support-panel/package.json
This patch adds four exceptions to .nsprc in the auth and profile
servers.  All hapi related.  The fix is to upgrade to @hapi/hapi.
https://npmjs.com/advisories/1472
https://npmjs.com/advisories/1478
https://npmjs.com/advisories/1479
https://npmjs.com/advisories/1481
This patch also upgrades @hapi/hapi on event broker and support panel to
18.4.1 for vulnerability fixes.
Fixes #4181 
=> chore(nsp): add four nsp exceptions to auth and profile servers

packages/fxa-content-server/app/scripts/views/pair/index.js, packages/fxa-content-server/app/tests/spec/views/pair/index.js, packages/fxa-content-server/server/lib/amplitude.js, packages/fxa-content-server/tests/server/amplitude.js, packages/fxa-shared/metrics/amplitude.js
This patch adds a couple missing Amplitude events to /pair on the
content server.  The events are 'fxa_connect_device - view' and
'fxa_connect_device - submit' with the event property
'connect_device_flow' set to 'pairing'.
Fixes #4103 
=> fix(metrics): add Amplitude events for /pair on content server

packages/fxa-content-server/app/scripts/templates/complete_reset_password.mustache, packages/fxa-content-server/app/scripts/templates/reset_password.mustache, packages/fxa-content-server/app/styles/modules/_button-row.scss, packages/fxa-content-server/app/styles/modules/_settings-account-recovery.scss
fixes #4137 
I removed the class check from the PW recovery flow… It receives the blue styles by default. See screens.
I noticed this was also affecting the “delete account” button. I conferred with Ryan Feeley about this who said this button should be red and gave the thumbs up on the styling.
Also fixed a line-height issue while I was at it.
#4137 is resolved:
Delete account change:
Line-height before:
Now: 
=> fix(css): Fix account recovery flow button CSS bug + line-height, fix .warning-button CSS

packages/fxa-support-panel/lib/api.ts, packages/fxa-support-panel/test/lib/api.spec.ts
This patch URI encodes the email address of the FxA user for whom the
support panel is fetching a list of subscriptions from the auth server.
Previously the request fails when the email address contains a '+'.
Fixes #4193 
=> fix(support-panel): encode email addr in subscriptions request

packages/fxa-content-server/app/scripts/lib/app-start.js, packages/fxa-content-server/app/scripts/lib/channels/web.js, packages/fxa-content-server/app/tests/spec/lib/channels/web.js
=> fix(webchannel): ignore native Gecko WebChannel errors for the OAuth WebChannel

packages/fxa-auth-server/lib/senders/templates/downloadSubscription.html, packages/fxa-auth-server/lib/senders/templates/partials/icon.html
fixes #3875 
Pretty minor tweaks of the inline-styles. The `icon` partial is only used by `downloadSubscription`.
Before:
After:
@meandavejustice I didn't PR this into your mobile FPN tweaks branch since this is separate from payments. I'll wait for your approval here since it falls under your epic.
=> fix(email): Minor CSS tweaks for subscription email

packages/fxa-auth-db-mysql/Dockerfile-build, packages/fxa-auth-server/Dockerfile-build, packages/fxa-customs-server/Dockerfile-build, packages/fxa-profile-server/Dockerfile-build, packages/fxa-support-panel/Dockerfile-build
an upstream update changed the ownership of /tmp and broke our build.
deleting /tmp isn't that important, only a couple mb.
=> fix(docker): don't rm /tmp after npm i

packages/fxa-auth-server/.vscode/launch.json, packages/fxa-auth-server/test/local/routes/subscriptions.js
- added coverage for the specified function
- updated vscode script for Arch 2.0 coverage
fixes #4233
=> test(routes/subscriptions.js): Coverage for updateCustomerAndSendStatus

packages/fxa-auth-server/.vscode/launch.json, packages/fxa-auth-server/test/local/routes/subscriptions.js
- added coverage for the specified function
- updated vscode script for Arch 2.0 coverage
fixes #4236
=> test(auth-server): Coverage for getUidEmail

packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
- refactored deleteSubscription, so as to not call stripe library directly
- added coverage for deleteSubscription in subscriptions.js DirectStripeRoutes
- added coverage for new cancelSubscriptionForCustomer in stripe.js StripeHelper
fixes #4225
=> test(auth-server): Coverage for Delete Subscription

packages/fxa-auth-server/.vscode/launch.json, packages/fxa-auth-server/lib/routes/emails.js, packages/fxa-auth-server/test/local/routes/emails.js
Because:
* We were failing to refresh our cached customer record for Stripe
subscriptions on primary email change.
* Our cached copy is keyed by email + uid, so the email change meant
we lost our local reference.
This commit:
* Refreshes the Redis record for a customer to the new email address.
Fixes #4247
=> fix(auth-server): stripe refresh on primary change

packages/fxa-content-server/app/scripts/views/post_verify/verified.js
Just noticed this while localizing the string. A quotation mark is missing.
=> Fix typo in RECOVERY_KEY text

packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
- refactored reactivateSubscription, so as to not call stripe library directly
- added coverage for reactivateSubscription in subscriptions.js DirectStripeRoutes
- added coverage for new reactivateSubscriptionForCustomer in stripe.js StripeHelper
- added placeholders for upcoming tests to reduce likelihood of merge conflicts
fixes #4230
=> test(auth-server): Coverage for reactivateSubscription

packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
- added code coverage for specified function
- removed duplicate code. the stripe error handling was already being taken care of by the method being called
fixes #4227
=> test(auth-server): Coverage for createSubscriptionExistingCustomer

packages/fxa-auth-server/scripts/test-local.sh, packages/fxa-profile-server/scripts/test-local.sh
Not connected to an issue, but sometimes if switching between branches and re-running tests you might get an error complaining about code coverage files.
This removes the coverage files before testing.
=> fix(coverage): Remove the temporary coverage directory before running tests

packages/fxa-admin-server/package-lock.json, packages/fxa-admin-server/package.json, packages/fxa-admin-server/src/config.ts, packages/fxa-admin-server/src/lib/db/index.ts, packages/fxa-admin-server/src/lib/db/models/account.ts, packages/fxa-admin-server/src/lib/db/models/email-bounces.ts, packages/fxa-admin-server/src/lib/db/models/emails.ts, packages/fxa-admin-server/src/lib/db/models/index.ts, packages/fxa-admin-server/src/lib/db/transformers.ts, packages/fxa-admin-server/src/lib/resolvers/account-resolver.ts, packages/fxa-admin-server/src/lib/resolvers/email-bounce-resolver.ts, packages/fxa-admin-server/src/lib/server.ts, packages/fxa-admin-server/src/test/lib/db/models/account.spec.ts, packages/fxa-admin-server/src/test/lib/db/models/accounts.sql, packages/fxa-admin-server/src/test/lib/db/models/email-bounces.spec.ts, packages/fxa-admin-server/src/test/lib/db/models/email-bounces.sql, packages/fxa-admin-server/src/test/lib/db/models/emails.sql, packages/fxa-admin-server/src/test/lib/db/models/helpers.ts, packages/fxa-admin-server/src/test/lib/resolvers/account-resolver.spec.ts, packages/fxa-admin-server/src/test/lib/resolvers/email-bounce-resolver.spec.ts
Because:
* User admin needs to talk to the db and resolve the graphql
objects.
This commit:
* Adds the db models to talk to the necessary tables in the database.
* Adds the resolvers to lookup the data and return it.
Fixes #4202, #4206, #4207
=> feat(admin-server): add db and resolvers

packages/fxa-auth-server/test/local/routes/subscriptions.js
- added coverage for DirectStripeRoutes.sendSubscriptionStatusToSqs
fixes #4234
=> test(auth-server): Coverage for sendSubscriptionStatusToSqs

packages/fxa-auth-server/config/dev.json, packages/fxa-auth-server/config/index.js, packages/fxa-auth-server/lib/oauth/grant.js, packages/fxa-auth-server/lib/routes/account.js, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/lib/routes/utils/subscriptions.js, packages/fxa-auth-server/test/local/routes/subscriptions.js, packages/fxa-auth-server/test/local/routes/utils/subscriptions.js, packages/fxa-auth-server/test/oauth/grant.js, packages/fxa-auth-server/test/remote/subscription_tests.js
- remove support and tests for subscription capabilities sourced from
server config
- add support for capabilities from Stripe metadata in
/oauth/subscriptions/clients getClients API
- ensure subscription status SQS messages include product capabilities
from Stripe metadata
- ensure plans are sanitized to remove capabilities in API responses
- add better handling for varied whitespace in capability lists
https://jira.mozilla.com/browse/FXA-944
fixes #3913
=> chore(auth-server): remove subscription capabilities in server config

packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/test/local/payments/fixtures/customer_deleted.json, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
- moved getCustomerUidEmailFromSubscription to StripeHelper
- added coverage for getCustomerUidEmailFromSubscription
- updated references to getCustomerUidEmailFromSubscription
fixes #4232
=> test(auth-server): coverage for getCustomerUidEmailFromSubscription

packages/fxa-auth-server/config/dev.json, packages/fxa-auth-server/config/index.js, packages/fxa-auth-server/lib/luaScripts/getAccessTokens_1.lua, packages/fxa-auth-server/lib/luaScripts/removeAccessToken_1.lua, packages/fxa-auth-server/lib/luaScripts/removeAccessTokensForPublicClients_1.lua, packages/fxa-auth-server/lib/luaScripts/removeAccessTokensForUserAndClient_1.lua, packages/fxa-auth-server/lib/luaScripts/removeAccessTokensForUser_1.lua, packages/fxa-auth-server/lib/luaScripts/setAccessToken_2.lua, packages/fxa-auth-server/lib/oauth/db/accessToken.js, packages/fxa-auth-server/lib/oauth/db/index.js, packages/fxa-auth-server/lib/oauth/db/mysql/index.js, packages/fxa-auth-server/lib/oauth/grant.js, packages/fxa-auth-server/lib/oauth/routes/token.js, packages/fxa-auth-server/lib/redis.js, packages/fxa-auth-server/test/lib/oauth-test.json, packages/fxa-auth-server/test/local/redis.js, packages/fxa-auth-server/test/oauth/api.js, packages/fxa-auth-server/test/oauth/db/index.js, packages/fxa-auth-server/test/oauth/db/purgeExpiredTokens.js, packages/fxa-auth-server/test/oauth/grant.js
The intent here is to store oauth access tokens in redis instead of mysql in order to move load off of mysql in anticipation of increased load from Fenix. We also have a legacy use case that [tokens for Pocket are kept indefinitely](https://bugzilla.mozilla.org/show_bug.cgi?id=1547902) that we need to keep supporting. Instead of putting new Pocket tokens in redis and having to support them in two places I opted to keep them going into mysql while vanilla oauth access tokens only go into redis where they can expire with a set TTL.
=> feat(oauth): store access tokens in redis

packages/fxa-content-server/app/scripts/models/support-form.js
This patch adds two Firefox Private Network specific support topic
options to the support form.  They are currently hard coded.
Fixes #3876 
=> chore(support form): add two FPN specific topics

packages/fxa-payments-server/package-lock.json, packages/fxa-payments-server/package.json, packages/fxa-payments-server/server/config/index.js, packages/fxa-payments-server/server/lib/routes/index.js, packages/fxa-payments-server/server/lib/routes/index.test.js, packages/fxa-payments-server/server/lib/routes/navigation-timing.js, packages/fxa-payments-server/server/lib/routes/navigation-timing.test.js, packages/fxa-payments-server/server/lib/server.js, packages/fxa-payments-server/server/lib/server.test.js, packages/fxa-payments-server/src/App.tsx, packages/fxa-payments-server/src/index.test.tsx, packages/fxa-payments-server/src/lib/navigation-timing.test.ts, packages/fxa-payments-server/src/lib/navigation-timing.ts, packages/fxa-payments-server/src/lib/sentry.test.js
This patch uses sendBeacon and Navigation Timing Level 2
(https://www.w3.org/TR/navigation-timing-2/) to report performance
timing from Payments pages.  The metrics are collected with StatsD.
Fixes #3596 
=> feat(metrics): collect navigation timing on Payments with StatsD

packages/fxa-content-server/app/styles/modules/_settings.scss
- fixes #4173
- also removed non existant css rule 'text-wrap'
=> fix(content-server): address letter dangles being cut off

packages/fxa-auth-server/scripts/find-stripe-sync-issues.js
Because:
* Due to bugs, we had a period where we didn't delete customers, or
update their primary email address.
This commit:
* Will scan all the Stripe users, and let us know which ones are in
Stripe but aren't in our FxA db, and if they have an email or uid
mismatch.
Closes #4186
=> feat: stripe mismatch checker

packages/fxa-auth-server/scripts/find-stripe-sync-issues.js
Because:
* We use the primary email in support/subscriptions routes not the
email on the accounts table.
This commit:
* Uses the proper email for comparison.
=> fix: use proper email in mismatch script

packages/fxa-auth-server/lib/routes/emails.js
Because:
* We verify and key zendesk/stripe by raw email and were updating
the primary using the normalized which wouldn't match.
This commit:
* Uses the raw email rather than normalized for consistency.
Fixes #4303
=> fix(auth-server): use raw email for primary updates

packages/fxa-content-server/app/styles/modules/_input-row.scss, packages/fxa-content-server/app/styles/modules/_marketing.scss
This patch fixes some rtl styles on the Firefox family services list on
the sign in/up pages.
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1617725
Fixes #4263 
=> fix(style): fix rtl styles on Firefox Family Servcies

packages/fxa-content-server/.nsprc
decompress is used by @theintern/digdug, so please don't write a test that'll write arbitrary files to your system.
=> chore(nsp): add exception for advisory 1217

CONTRIBUTING.md, packages/fxa-auth-db-mysql/CONTRIBUTING.md, packages/fxa-auth-server/CONTRIBUTING.md, packages/fxa-content-server/docs/architecture.md, packages/fxa-customs-server/CONTRIBUTING.md, packages/fxa-geodb/README.md, packages/fxa-js-client/CONTRIBUTING.md, packages/fxa-profile-server/CONTRIBUTING.md
Because: On March 2020, Mozilla moved from IRC to Matrix. To ensure a smooth transition, information on how to access Matrix and reach the fxa team in this new virtual space needed to be added to our documentation.
=> docs(contributing): update contact information to reflect move to Matrix

.circleci/config.yml, .circleci/test-email-service.sh, .gitignore
I noticed [here](https://circleci.com/workflow-run/c9fa699d-d3d3-4ad3-a3b8-dd94d35977f2?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) that email-service was building even though only content and payments were changed. email-service uses an xlarge instance so we should minimize its usage.
=> chore(ci): skip email service tests for PRs when not required

.circleci/config.yml, .circleci/test-content-server.sh
This patch reverts the VM size for content server tests to the default
(medium).  Now Firefox is restarted more frequently (per X test suites).
Part of #4374
=>  chore(CircleCI): run content server tests on medium VM

packages/fxa-admin-server/.vscode/launch.json, packages/fxa-admin-server/.vscode/tasks.json
Because:
* There's no existing defined settings to run the admin server or
tests with the debugger.
This commit:
* Add's VS code settings to run the debugger for the admin-server
and its tests.
Closes #4244
=> feat(admin-server): add vscode settings

packages/fxa-customs-server/lib/config/config.js
When setting FLOW_ID_EXEMPT_UA_REGEXES in the environment, this `format: Array` is required. (Otherwise, node-convict tries to infer the type from the default, but uses `typeof` on Array, which is `object`, so node-convict tries and fails to JSON.parse the environment value.
I had a test for this, but with tests not working, I can't really tell if the tests plays nicely with the other tests. (The test needs to `delete require.cache[configModulePath]` to reload `../../lib/config`.)
=> fix(customs): set config for flowIdExemptUserAgentREs to `format: Array`

_scripts/pubsub.sh, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-event-broker/bin/workerDev.ts, packages/fxa-event-broker/lib/notificationProcessor.ts, packages/fxa-event-broker/package-lock.json, packages/fxa-event-broker/package.json, packages/fxa-event-broker/test/lib/notificationProcessor.spec.ts, packages/fxa-event-broker/tsconfig.json
Because:
* The capability list assembling could result in duplicate capabilities
for a clientId.
* When sending the subscription state SQS message, only the capabilities
are included, not prefixed with a clientID as the event-broker had
assumed based on a prior un-implemented concept.
This commit:
* Removes duplicates from the client/capabilities response by using a
Set.
* Looks up the clientId based on the capability rather than assuming
its the prefix in the productCapabilities.
Fixes #4315
=> fix: lookup clientids in eventbroker

packages/fxa-auth-server/lib/oauth/grant.js, packages/fxa-auth-server/lib/routes/utils/subscriptions.js, packages/fxa-auth-server/test/local/routes/utils/subscriptions.js, packages/fxa-auth-server/test/oauth/grant.js
=> fix(payments): support clientId as buffer in subscription capability lookup

packages/fxa-content-server/app/styles/modules/_settings.scss
This patch fixes the RTL style of the header text on the disconnect a
client modal.
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1617720
Fixes #4262 
=> fix(style): fix rtl style for disconnect client header

packages/fxa-auth-server/test/local/payments/fixtures/subscription_cancelled.json, packages/fxa-auth-server/test/local/payments/fixtures/subscription_past_due.json, packages/fxa-auth-server/test/local/payments/fixtures/subscription_trialing.json, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
- add coverage for DirectStripeRoutes.listActive
- fix tests that were breaking due to shallow copies of test object by adding deepCopy function
fixes #4228
=> test(auth-server): add coverage for listActive

packages/fxa-payments-server/src/lib/navigation-timing.test.ts, packages/fxa-payments-server/src/lib/navigation-timing.ts
This patch fixes a race condition where the PerformanceObserver instance
is created after the navigation timing performance entry has already
queued.
Fixes #4396 
=> fix(metrics): handle race condition in Payments nav timing metrics

packages/fxa-auth-server/test/local/routes/subscriptions.js
- add coverage for DirectStripeRoutes.getSubscriptions
fixes #4237
=> test(auth-server): add coverage for getSubscriptions

packages/fxa-content-server/app/scripts/models/reliers/oauth.js, packages/fxa-content-server/app/scripts/views/settings.js, packages/fxa-content-server/app/tests/spec/models/reliers/oauth.js, packages/fxa-content-server/app/tests/spec/views/settings.js
Fixes #4284 
I went back and forth on a decent way to do this, but settled on the simple approach verses doing a larger refactor. This PR checks to see if the old sync scope is requested for the oauth client, if so then the `Sign out` button will not appear in the settings view. The expectation is that the client will have its own sign out button.
I considered checking the entrypoint, for ios settings it is `?entrypoint=ios_settings_manage` but that seemed more likely to change so stuck with checking scope.
Note that I wasn't actually able to test this locally because it requires application services library to build built and run against local servers. However, I feel good about the tests so it should work as expected.
=> fix(settings): Don't show signout when oauth clients that request oldsync scope

packages/fxa-event-broker/lib/api/proxy-controller.ts, packages/fxa-event-broker/lib/notificationProcessor.ts, packages/fxa-event-broker/test/lib/notificationProcessor.spec.ts
Because:
* We were storing clientId's, status codes, and event types in the
metric name itself.
* Repeated a chunk of mostly identical code 3 times.
This commit:
* Uses tags for the metrics.
* Has a small refactor into one generic fanout method.
Fixes #4418
=> feat(event-broker): use tags for unique metrics

packages/fxa-auth-server/lib/redis.js, packages/fxa-auth-server/package-lock.json, packages/fxa-auth-server/package.json
Because:
* We originally didn't use additional redis.set arguments, our set
pass-through function dropped anything other than key/value.
This commit:
* Retains all redis.set arguments supported by the ioredis library we
use.
Fixes #4413
=> fix(auth-server): pass all redis set args

README.md, _scripts/check_ports.sh, package.json
Closes https://github.com/mozilla/fxa/issues/4343
1. Updates README setup instructions to note that you shouldn't be running any services yourself.
2. Modifies root `npm start` to perform a pre-check on any ports our servers use. Doesn't abort, but warns you if anything is already running on those ports.
=> Check for local services on startup

packages/fxa-email-service/src/types/headers/mod.rs, packages/fxa-email-service/src/types/headers/test.rs
Closes https://github.com/mozilla/fxa/issues/4390
Enforces a maximum header size of 998 characters per [RFC 5322](https://tools.ietf.org/html/rfc5322#section-2.1.1) recommendation. This is a hopeful solution to a failed mail delivery noted in [Bugzilla 1618831](https://bugzilla.mozilla.org/show_bug.cgi?id=1618831).
Note this is 998 characters total (key + value).
=> Enforce a max header size of 998 characters in emails

packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/test/local/payments/fixtures/charge_failed.json, packages/fxa-auth-server/test/local/payments/fixtures/customer1.json, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
- add coverage to StripeHelper.subscriptionsToResponse
- extract plan name formatter function to ease testing
- add coverage for new function to ensure it works as expected
- fix skip test
fixes #4222
=> test(auth-server): add coverage for subscriptionsToResponse

packages/fxa-auth-server/grunttasks/eslint.js, packages/fxa-auth-server/lib/oauth/db/accessToken.js, packages/fxa-auth-server/lib/oauth/db/index.js, packages/fxa-auth-server/lib/oauth/db/mysql/index.js, packages/fxa-auth-server/lib/oauth/db/mysql/schema.sql, packages/fxa-auth-server/package.json, packages/fxa-auth-server/test/oauth/db/index.js, packages/fxa-auth-server/tsconfig.json
The MySQL access-token storage deliberately does not write the raw access token to disk, and instead only writes a hash. This allows us to look up a given token but prevents a db compromise from immediately leaking all tokens in useable form.
The new Redis access-token storage currently includes the raw token in its JSON serialization. We should never need this value again in practice, so I suggest we avoid storing it for all the same reasons we don't store it in MySQL. This commit changes the serialization logic to persist `tokenId` instead, while continuing to support data with the old field that may already be in redis.
Relatedly, the value returned when looking up an access token could differ depending on whether it came from Redis (in which case the `token` field would be the raw …
=> fix(oauth): Do not store raw access tokens in Redis.

packages/fxa-auth-db-mysql/lib/db/mysql.js, packages/fxa-auth-server/lib/oauth/db/mysql/index.js, packages/fxa-auth-server/test/oauth/db/mysql.js, packages/fxa-profile-server/lib/db/mysql/index.js, packages/fxa-profile-server/test/mysql.js
Because:
* Some of our security checks (such as checking whether a token
has expired) compare a timestamp generated in JS with a timestamp
generated in MySQL.
* MySQL returns timestamps in whatever it believes to be the local
timezone by default.
* We try to be robust to suboptimally-configured MySQL databases,
especially when it could lead to security issues.
This commit:
* Explicitly tells MySQL to return timestamps in UTC regardless
of the system- or database-level timezone setting.
=> fix(mysql): Force MySQL connections to always use UTC timezone.

packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
- add function to ensure that the payment intent is loaded prior to evaulating the status
because:
- users have been reporting errors when attempting to signup for a subscription when their initial payment failed. after verifying that the stripe payment_intent objects appear to be in correct "payment_method_required" state, a potentialcause is that the payment_intent object is not actually loaded. this adds a StripeHelper function to ensure we are working with an object and not a string.
fixes #4437
=> bug(auth-server): add payment_intent check in handling open invoices

packages/fxa-auth-server/lib/payments/stripe.js
- a variable being assigned with the result of an asynction was missing the keyword `await`, this commit adds the missing keyword and adds to the async function's docblock
fixes #4449
=> bug(auth-server): Add missing `await` to var assignment

packages/fxa-content-server/app/scripts/models/auth_brokers/base.js, packages/fxa-content-server/app/scripts/models/auth_brokers/web.js, packages/fxa-content-server/app/scripts/views/behaviors/settings.js, packages/fxa-content-server/app/scripts/views/post_verify/account_recovery/add_recovery_key.js, packages/fxa-content-server/app/scripts/views/post_verify/account_recovery/confirm_password.js, packages/fxa-content-server/app/scripts/views/post_verify/verified.js, packages/fxa-content-server/app/tests/spec/models/auth_brokers/base.js, packages/fxa-content-server/app/tests/spec/models/auth_brokers/web.js, packages/fxa-content-server/app/tests/spec/views/post_verify/account_recovery/add_recovery_key.js, packages/fxa-content-server/app/tests/spec/views/post_verify/account_recovery/confirm_password.js, packages/fxa-content-server/tests/functional/lib/helpers.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/post_verify/account_recovery.js
Closes https://github.com/mozilla/fxa/issues/4369
- Only display "Account recovery enabled" message if you're coming from the final step of the post-verify recovery key setup flow.
- Otherwise, don't display any success message, including from "Maybe later" clicks, unless one is provided via `options.success`.
Additionally, beef up tests with
- Assert that the success and error messages were shown with a specific message
- Refute that success and error messages were shown at all
---
@vbudhram this is one of my first stabs at this stack, so I am 100% cool with if this isn't the right approach, or if my assumptions were off.
=> fix(account-recovery): Only display recovery confirmation if you're coming from the confirmation page

packages/fxa-metrics-processor/README.md, packages/fxa-metrics-processor/package-lock.json, packages/fxa-metrics-processor/package.json, packages/fxa-metrics-processor/tsconfig.json, packages/fxa-metrics-processor/types/mozlog/index.d.ts
As we move the FxA metrics processing off the web servers, we can collect the code and JSON schemas in this new package. Read more in the metrics epic: https://jira.mozilla.com/browse/FXA-838
Using typescript because we really care about data types for this work (inputs and outputs will follow schemas).
Using mocha/sinon because we won't have any UI here, it's just Pub/Sub worker code.
Otherwise, just trying to pull in as many standard parts from other monorepo typescript projects as possible. I'm a typescript novice, so pushing this early to allow others to offer feedback or just land improvements directly in the branch.
=> Create fxa-metrics-processor package

packages/fxa-content-server/app/scripts/templates/sms_send.mustache, packages/fxa-content-server/app/scripts/views/sms_send.js, packages/fxa-content-server/app/styles/modules/_branding.scss, packages/fxa-content-server/app/tests/spec/views/sms_send.js
Also adds aria-label and role to a graphic for for ADA purposes.
fixes #4435 
---
We don't have to worry about potential lag between a device just verifying and then fetching from `attachedClients` because #4432 should redirect users that register with a mobile device.
I expect to have merge conflicts if #4454 is merged first.
=> feat(sms): Conditionally render heading text based on mobile deviceType presence

packages/fxa-content-server/app/scripts/templates/marketing_snippet.mustache, packages/fxa-content-server/app/scripts/templates/sms_send.mustache, packages/fxa-content-server/app/scripts/views/sms_send.js, packages/fxa-content-server/app/styles/modules/_branding.scss, packages/fxa-content-server/app/styles/modules/_marketing.scss, packages/fxa-content-server/tests/functional/send_sms.js
Closes #4431, Closes #4433
Various updates as part of FXA-878
- Validates phone number as you type, conditionally enabling submit button (see code comment)
- Disable Firefox logo in container
- Update SMS disclaimer and multi-device explanation copy
- Groups app download links closer together (I think this also addresses #1215?)
Note the disabled button is not gray, per the guidelines, but faded blue as this was what already exists in our design patterns/CSS. Happy to change to the gray version if desired.
=> refactor(sms page): cosmetic/copy updates and validation functionality for SMS page

README.md
No associated issue, just seemed like we needed these changes.
=> chore(docs): Update root README to include table of contents, links to ecosystem plat + Riot

packages/fxa-content-server/app/styles/modules/_marketing.scss
This patch updates how the alignment between the h2 and the Firefox
services product list items are accomplished for RTL.
Fixes #4383 
=> fix(style): update rtl padding for Firefox services list

packages/fxa-content-server/app/scripts/templates/post_verify/account_recovery/confirm_recovery_key.mustache, packages/fxa-content-server/app/tests/spec/views/post_verify/account_recovery/confirm_recovery_key.js
Fixes #4367
This PR adds the recovery graphic on the confirmation page.
=> fix(recovery): Add recovery key graphic on confirmation screen

.circleci/config.yml, packages/fxa-event-broker/scripts/test-ci.sh, packages/fxa-event-broker/src/test/lib/db/firestore.spec.ts
There's a race in here somewhere... `await` on the set can complete before the webhook triggers.
This isn't the most elegant fix. There's prob a better way.
fixes #4469
=> fix(test): fixed race in event-broker test

.circleci/assert-branch.sh
Train branches update the package.json and Changelog
for all the packages whether there were code changes
or not. These PRs are already in the release so there's
no need to test email-service here now.
Sorry to Jackie for breaking your PR.
=> fix(ci): exclude train branches from assert-branch.sh

packages/fxa-content-server/app/scripts/templates/sms_send.mustache, packages/fxa-content-server/app/scripts/views/sms_send.js, packages/fxa-content-server/app/styles/modules/_branding.scss, packages/fxa-content-server/app/tests/spec/views/sms_send.js
Closes https://github.com/mozilla/fxa/issues/4436
We currently display the success banner "This Firefox is connected" on the Connect Another Device screen after a successful sign in or registration via Sync, but there are cases where the user can be shown the SMS screen (skipping CAD altogether), so we want to show that same confirmation message here.
This should only appear in the following scenario:
1. You have just signed in (returning or new registration)
2. You are in a state that is eligible to receive SMS messages
You should not be seeing this message if you hit any variation of `/sms` directly. Even reloading the page when you first see the banner should not show it again.
=> fix(sms page): display "This Firefox is connected" after sign in or registration via sync occurs

packages/fxa-content-server/tests/intern.js
You currently encounter errors running content server functional tests locally because it conflicts with our firestore port, set to 9090.
=> fix(tests): change port that selenium tests run on from 9090 to 9091

packages/fxa-content-server/app/scripts/lib/cropper.js, packages/fxa-content-server/app/scripts/views/settings/avatar_crop.js, packages/fxa-content-server/app/styles/modules/_cropper.scss, packages/fxa-content-server/app/tests/spec/lib/cropper.js
Closes #674
This should address the avatar image cropper at smaller window sizes.
This was actually a bit of a doozy, since the cropper sizing was hard coded. The remedies I've used are:
- Update all the cropper component styles to be a little more fluid.
- Remove the ability to specify explicit vertical and horizontal gutters, instead relying on the calculated width of the wrapper versus the size of the cropping box.
- Position accordingly on page load and on window resize (debounced).
[Here's a demo video](https://imgur.com/v2qU6AK) of the cropping container at various window sizes.
=> fix(avatar): update avatar image cropper to work effectively at all window sizes

packages/fxa-content-server/app/scripts/templates/sms_send.mustache, packages/fxa-content-server/app/tests/spec/views/sms_send.js
A simple copy update. This should have been part of #4431 but I missed including it in the bullet points of things to do.
=> refactor(sms): SMS Clarity - replace subheader text

packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/remote/subscription_tests.js
- add created timestamp to the subscription response
Because:
- as a part of allowing longer duration subscriptions, we need to provide support agents with the date the subscription began for the purpose of time-sensitive refunds
issue #3981
=> feat(auth-server): add created to subscription response

.circleci/base-install.sh, .circleci/config.yml
A full `npm ci` sometimes takes a long time for whatever
reason. Before this change it always ran, even if the
tests were going to be skipped. Now it checks whether
the tests are going to run first.
=> feat(ci): optimize when 'npm ci' is run on circleci

packages/fxa-content-server/app/scripts/templates/post_verify/account_recovery/save_recovery_key.mustache, packages/fxa-content-server/app/styles/modules/_modal.scss
Closes #4366
All the functionality is there in the mixin, the selector and styling was just needed.
=> fix(post verify): add selector so downloaded/copied/printed messaging can appear

packages/fxa-payments-server/server/lib/routes/navigation-timing.js, packages/fxa-payments-server/src/lib/navigation-timing.test.ts, packages/fxa-payments-server/src/lib/navigation-timing.ts
This patch updates the navigation timing reporting request to send its
content as text/plain.  Some users were seeing blank pages on Payments
due to errors caused by the blob's content-type.
Fixes #4522 (FXA-1351)
=> fix(metrics): send nav timing as text/plain

packages/fxa-content-server/app/scripts/lib/constants.js, packages/fxa-content-server/app/scripts/models/reliers/oauth.js, packages/fxa-content-server/app/scripts/views/settings.js, packages/fxa-content-server/app/tests/spec/models/reliers/oauth.js, packages/fxa-content-server/app/tests/spec/views/settings.js, packages/fxa-content-server/server/lib/configuration.js
Follow up fix to #4284
Trying to avoid spinning my wheels too hard on this, I created a follow up to fix what I think the underlying problem is in #4509. In the meantime, this checks to see if the page is being loaded from an iOS client and doesn't show the signout button if it is.
This time I was able to verify it works locally.
=> fix(ios): Don't show signout button with Firefox iOS client

packages/fxa-circleci/Dockerfile, packages/fxa-circleci/scripts/build-ci.sh
This checks the diff of the current Dockerfile
with the one pulled from latest. If they are
the same it skips the build in order to save time.
Like #4512 (but hopefully works) - _I've got a follow up to that one coming_
=> feat(ci): added build-ci script to fxa-circleci

packages/fxa-circleci/scripts/build-ci.sh
My local version of `diff` is 2.8.1 while the one run
in circleci/node:12 is 3.5 and they apparently treat
-b differently. Let's try -w. But there's still the
underlying question of why line 12 in the script
is changing the line endings from LF to CRLF in the
piped file?
Edit:
after ^ didn't work...
The `cat | diff` method worked for me locally but doesn't
on CircleCI. Instead copy the Dockerfile out of the latest
image and then diff against the local one.
=> fix(ci): changed diff method of fxa-circleci build-ci.sh

packages/fxa-email-service/scripts/build-ci.sh
The `cat | diff` method worked sometimes (I've seen it!) but
not reliably. This method has worked for fxa-circleci. We'll
have this working eventually
=> fix(ci): use the same diff method as fxa-circleci in email-service build-ci

.circleci/build-all.sh, .circleci/build.sh, .circleci/create-version-json.sh, packages/fxa-circleci/scripts/build-ci.sh, packages/fxa-email-event-proxy/scripts/build-ci.sh, packages/fxa-email-service/scripts/build-ci.sh
The build step ci output was really noisy with docker logs
so this writes that output into log files in the build
artifacts instead.
=> chore(ci): improved ci build step output

.circleci/config.yml
After cleaning up build.sh in #4557 circleci errored with:
`Too long with no output (exceeded 10m0s): context deadline exceeded`
adding [no_output_timeout](https://circleci.com/docs/2.0/configuration-reference/#run) should fix it
https://app.circleci.com/pipelines/github/mozilla/fxa/8816/workflows/852a58e9-49dc-4b52-bcee-a4c3b6b9d314/jobs/160011
=> fix(ci): circleci deploy needs no_output_timeout

packages/fxa-payments-server/src/index.tsx, packages/fxa-payments-server/src/lib/amplitude.test.ts, packages/fxa-payments-server/src/lib/amplitude.ts
This patch augments the Amplitude event properties with the uid from the
Redux store when it's available.
Fixes #4439 (FXA-1305)
=> fix(metrics): add uid to Payments Amplitude events

.circleci/deploy.sh, packages/fxa-circleci/scripts/build-ci.sh, packages/fxa-email-service/scripts/build-ci.sh
This should cut master ci build times by a minute or so.
=> chore(ci): no need to tag/push unchanged docker images

packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/test/local/routes/validators.js
- update the plan validator
Because:
- when the plan response was updated in https://github.com/mozilla/fxa/pull/4554, the validator was not also updated
=> bug(auth-server): fix validator

packages/fxa-auth-server/lib/log.js, packages/fxa-auth-server/lib/metrics/events.js, packages/fxa-auth-server/lib/server.js, packages/fxa-auth-server/test/local/metrics/events.js, packages/fxa-auth-server/test/local/server.js, packages/fxa-auth-server/test/mocks.js
This patch makes two updates to the auth server's route perf metrics:
- Hapi's `request.info.responded` timestamp is now used to calculate
the duration
- The identical value is reported to Redshift and InfluxDB
Fixes #4429 (FXA-1296)
=> chore(metrics): update calculation of auth server route perf metrics

packages/fxa-content-server/app/scripts/templates/post_verify/account_recovery/save_recovery_key.mustache, packages/fxa-content-server/app/scripts/views/mixins/save-options-mixin.js, packages/fxa-content-server/app/styles/modules/_modal.scss
Closes #4547
This issue was introduced by me in 3332874bce6bac3679b49b522cebcf1094609288.
Instead of modifying the style of the success banner to work like the variety that lives in the modal, I've updated the Javascript that gets called when a copy-print-download button is clicked to target our success banner.
=> fix(recovery key): update post-verify recovery key styling to not look like a modal on mobile

packages/fxa-auth-server/lib/senders/templates/downloadSubscription.html, packages/fxa-auth-server/lib/senders/templates/partials/button.html, packages/fxa-auth-server/lib/senders/templates/verifySecondary.html
Closes #4543
The content in the emails noted is misaligned because of a non-semantic HTML structure where the layout ends up being:
```html
<tr>...</tr>
<table>...</table>
<tr>...</tr>
```
Some email clients ignore it, but some don't like it.
The reason this is happening is because we [started](https://github.com/mozilla/fxa/commit/fa1d31440555e72a9e4a0ccb92423adf76261449#diff-ad28990900043fd71d26e323cb2eb9f4) wrapping our `button` partial in `<table>` tags in order to satisfy a layout issue in [this email](https://github.com/mozilla/fxa/commit/fa1d31440555e72a9e4a0ccb92423adf76261449#diff-a121c68141a89cb12e131f4e9eda0163R90).
Since this is the only place where a surrounding `<table>` is expected, and all other instances of the `button` partial usage expect a surrounding `<tr>`, I've gone …
=> fix(emails): update usage of button partial in emails to fix broken HTML structure

packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/test/client/api.js, packages/fxa-auth-server/test/client/index.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js, packages/fxa-payments-server/package-lock.json, packages/fxa-payments-server/package.json, packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.tsx, packages/fxa-payments-server/src/lib/apiClient.ts, packages/fxa-payments-server/src/lib/hooks.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx, packages/fxa-payments-server/src/store/actions/api.ts, packages/fxa-payments-server/src/store/sequences.ts
Closes #4516
This centers around [Stripe's support for idempotency keys](https://stripe.com/docs/api/idempotent_requests) when performing POST requests against its API, and requires some changes in a few spots:
- Update the payment form to submit a nonce as the idempotency key (not used for creating tokens, though)
- Handle it in Payments Server, update `ClientApi.createSubscription` to support it
- Receive the key on the auth server and pass it to Stripe with each "create" request, this includes customer and subscription creation
Additionally, this is backed by replacing our previous nonce token generation from `${Date.now()}-${Math.random()}` to proper UUID v4 for _max_ entropy.
---
Note - I see the Payments Server uses Storybook. I don't think I've touched much of it, so I can …
=> feat(subscriptions): implement idempotency when creating a subscriptions

.gitignore, README.md, mysql_servers.json, packages/fxa-auth-server/README.md, packages/fxa-payments-server/README.md
Closes #4483
**Problem**: developers need to manually modify Auth and Payment server files with their own Stripe keys, which results in changes to tracked files in git. It has resulted in accidental commits of these secrets, and of course don't want to be committing secrets! It's also just a pain to be updating these because of how spread out they are.
~**Solution**: add the ability to create a file called `local.env` at the root level of this repo, where you can supply your Stripe publishable and secret keys, so they can be supplied to the servers that require them.~
**Solution:** in places where we use convict we're already checking and loading in a file that is set at the `CONFIG_FILES` env var, so I've gone ahead and updated the pm2 server script to automatically check for a specific …
=> refactor(env): implement ability to supply your secret and publishable Stripe keys in a `local.env` file

packages/fxa-content-server/app/scripts/lib/url.js, packages/fxa-content-server/app/scripts/views/settings/emails.js, packages/fxa-content-server/app/tests/spec/views/settings/emails.js
Fixes #4504
This PR fixes the above issue by doing the following
* On primary email change, update the query email param to reflect new email. When a user signs out, the login page treats the `?email=something` as gospel and prefills the page.
* Unset the `originalLoginEmail` value on the account if present. This should only be set if user is attempting to login.
=> fix(emails): Update cached email after changing primary email

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/send-sms-header.js, packages/fxa-content-server/app/scripts/templates/sms_send.mustache, packages/fxa-content-server/app/scripts/views/sms_send.js, packages/fxa-content-server/app/tests/spec/views/sms_send.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/send_sms.js
This addresses a misunderstanding in the experiment where we neglected to use a "control". More can be found in [this Slack discussion](https://mozilla.slack.com/archives/C4D36CAJW/p1584452512384100).
Here are the three versions now:
`control`:
`syncPhone`:
`syncBrowser`:
=> fix(experiment): update sendSmsHeader frontend experiment to include previous control option

packages/fxa-auth-server/lib/oauth/grant.js, packages/fxa-auth-server/lib/routes/account.js, packages/fxa-auth-server/lib/routes/utils/subscriptions.js, packages/fxa-auth-server/scripts/clean-up-old-ci-stripe-customers.js, packages/fxa-auth-server/test/local/routes/utils/subscriptions.js, packages/fxa-auth-server/test/remote/subscription_tests.js, packages/fxa-content-server/tests/functional.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/subscriptions.js, packages/fxa-profile-server/lib/routes/_core_profile.js, packages/fxa-profile-server/lib/routes/profile.js, packages/fxa-profile-server/lib/routes/subscriptions.js, packages/fxa-profile-server/lib/subscriptions.js
- end-to-end functional test in content-server that exercises
subscription flow
- fix an issue where the profile-server caching only retained subscription
capabilities per user based on the first client ID that fetched the
profile on a cache miss
- separate gathering up subscription capabilities from filtering by
relevant client ID
- send all subscription capabilities from auth-server /account/profile
endpoint so that profile-server can do client ID filtering
- cache all subscription capabilities in profile-server, filter by
client ID at request time
- small bugfix for clean-up-old-ci-stripe-customers asserting pattern
for Stripe test key
FXA-1278
fixes #4394
=> fix(payments): end-to-end subscription functional test with profile caching bugfix

packages/fxa-content-server/package-lock.json, packages/fxa-content-server/package.json, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/server/lib/flow-event.js, packages/fxa-content-server/server/lib/statsd.js, packages/fxa-content-server/tests/server/flow-event.js
This patch sends the navigation timing performance metrics to InfluxDB.
It's a step in replacing the performance dashboard in Redash, and
removing our dependency on Redshift.
Fixes #4589  (FXA-1295)
=> feat(metrics): send nav timing metrics to statsd/influxdb

packages/123done/.nsprc, packages/browserid-verifier/.nsprc, packages/fortress/.nsprc, packages/fxa-admin-server/.nsprc, packages/fxa-auth-db-mysql/.nsprc, packages/fxa-auth-server/.nsprc, packages/fxa-content-server/.nsprc, packages/fxa-customs-server/.nsprc, packages/fxa-dev-launcher/.nsprc, packages/fxa-email-event-proxy/.nsprc, packages/fxa-event-broker/.nsprc, packages/fxa-geodb/.nsprc, packages/fxa-js-client/.nsprc, packages/fxa-metrics-processor/.nsprc, packages/fxa-payments-server/.nsprc, packages/fxa-profile-server/.nsprc, packages/fxa-support-panel/.nsprc
Can't finish today's release without addressing this.
Not 100% sure we aren't ever passing untrusted input to handlebars, which is affected; filed https://github.com/mozilla/fxa/issues/4592 to follow up.
=> chore(deps): Updates to address nsp advisory 1179

packages/fxa-content-server/server/lib/flow-event.js
This patch restricts the navigation timing statsd metric names to those
defined in fxa-shared/metrics/flow-performance.js.
Fixes #4599 (FXA-1391)
=> fix(metrics): restrict content-server nav timing metric names

packages/fxa-payments-server/package-lock.json, packages/fxa-payments-server/package.json, packages/fxa-payments-server/server/config/index.js, packages/fxa-payments-server/server/lib/routes/index.js, packages/fxa-payments-server/server/lib/routes/index.test.js, packages/fxa-payments-server/server/lib/routes/navigation-timing.js, packages/fxa-payments-server/server/lib/routes/navigation-timing.test.js, packages/fxa-payments-server/server/lib/server.js, packages/fxa-payments-server/server/lib/server.test.js
This patch removes the country, OS, and user-agent name tags from statsd
metric.  It helps to lower the amount of metrics in InfluxDB.
Fixes #4594 (FXA-1387)
=> chore(metrics): reduce nav timing metric tags in Payments

packages/fxa-content-server/app/styles/modules/_settings.scss
This patch fixes the left/right paddings of the product list and
checkbox list of the delete account panel in settings.
Fixes #4559 (FXA-1377)
=> fix(style): fix rtl style of delete account panel

packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js, packages/fxa-payments-server/src/components/PaymentConfirmation/index.stories.tsx, packages/fxa-payments-server/src/components/PaymentConfirmation/index.test.tsx, packages/fxa-payments-server/src/lib/test-utils.tsx, packages/fxa-payments-server/src/routes/Product/index.stories.tsx, packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx, packages/fxa-payments-server/src/store/types.tsx
- updated the getCustomer response to include the billing_name
- updated tests and validators
fixes #4612
=> feat(auth-server + payments-server): add billing_name to customer response

packages/fxa-content-server/server/lib/statsd.js
When statsd metrics are disabled on the content server, a mocked object
with NOOP functions is used.  However, there was a bug where the object
was not returned from the function where it was created.
=> fix(metrics): return the mocked statsd instance

_scripts/syncserver.sh
Because:
* When running the syncserver docker image for local development, we need to
configure it with a different verifier URL depending on whether it can reach
the verifier process over localhost (which it can on Linux) or whether it
needs to talk to a special hostname (necessary on Mac and Windows).
* The latest Docker Desktop for Windows seems to report its operating system
as "Docker Desktop" rathert than anything with the word "Windows" in it.
This commit:
* Treats "Docker Desktop" as another case where we have to the special hostname
for accessing other services running under docker.
* Works on my machine, but hasn't been tested on yours.
=> fix(docker): Improve detection of Docker running on Windows.

packages/fxa-payments-server/server/lib/server.js, packages/fxa-payments-server/src/App.tsx, packages/fxa-payments-server/src/index.tsx, packages/fxa-payments-server/src/lib/amplitude.ts, packages/fxa-payments-server/src/lib/config.ts, packages/fxa-payments-server/src/lib/flow-event.test.ts, packages/fxa-payments-server/src/lib/flow-event.ts, packages/fxa-payments-server/src/lib/sentry.js, packages/fxa-payments-server/src/lib/sentry.test.js
Because:
* Sentry was being configured at import time before the config had been
loaded.
This commit:
* Switches the SentryMetrics default export to be a sentryMetrics
singleton that can be configured after the config is loaded.
Fixes #4531
=> fix(payment-server): configure DSN later

packages/fxa-payments-server/src/lib/navigation-timing.ts
This patch fixes a Safari only bug where the navigation timing
performance entry is undefined prior to the completion of the navigation
event.
Fixes #4630 (FXA-1401)
=> fix(metrics): fix undefined nav timing perf entry bug on Safari for Payments

packages/fxa-content-server/app/scripts/templates/settings/emails.mustache, packages/fxa-content-server/app/styles/modules/_button-row.scss
Closes #4602 #4597
**For #4602**
This matches the pattern set forth in the refresh buttons in the Devices & apps and Account recovery sections:
**For #4597**
Just apply `type="submit"` to the button, like it is done with the other refresh buttons, so it applies the disabled-blue styling to the button as expected
=> Fix settings refresh buttons styles

packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/lib/senders/templates/layouts/subscription.html
Closes #4591
This attempts to address a potential attack vector where clicking a link can redirect you to a malicious website. More info: https://dev.to/dhilipkmr/why-should-you-use-noopener-beware-of-security-flaws-3i57
This sort of attack is less likely to occur in email, but is technically still possible in a web client. More info: https://stackoverflow.com/a/51194051/717633
=> feat(email): add rel="noopener noreferrer" to any email links that have target="_blank"

packages/fxa-profile-server/lib/routes/root.js
Navigating to `/` will result in a 500 if a `version.json` is not present
=> fix(profile): Fix 500 error in the root of the profile server

packages/fxa-auth-server/lib/log.js, packages/fxa-auth-server/lib/profile/updates.js, packages/fxa-auth-server/test/local/profile/updates.js
Fixes #4499 
This PR will notify our event broker and RP listening for `profileDataChanged` messages when a user's display name or avatar has changed. 
I was originally concerned about the profile server emitting a push notification when it processed the `profileDataChanged` event, but it only clears the profile-server cache. There shouldn't be a feedback loop of messages.
=> fix(profile): Call `notifyAttachedServices` when profile-server data changes

packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.tsx
- updated legal checkbox text on payment confirmation page to handle various billing intervals and interval counts
issue #3987
=> feat(payment-server): update legal checkbox text on payments page

packages/fxa-content-server/server/config/local.json-dist
Because:
* The fxa-auth-server dev config defaults Fenix and Firefox-iOS to
using OAuth redirect URIs on https://127.0.0.1:3030.
* The fxa-content-server dev config defaults to checking OAuth scoped
key access against production OAuth redirect URIs.
* The resulting mis-match means you can't sign in to Fenix using
a local dev server in the default config.
This commit:
* Changes the default local config for fxa-content-server to check
OAuth scoped key access against the development OAuth redirect URIs.
=> chore(config): Default to a useable Fenix OAuth config in local dev

packages/fxa-content-server/app/styles/modules/_settings.scss
Addresses https://github.com/mozilla-mobile/firefox-ios/issues/6130
In English none of our settings titles are long enough to bump up against the right side button. Lucky us. However in localized versions of the settings panel these titles can get quite long. Currently long strings push the content of the element out, effectively breaking the settings layout.
This fix allows the text to wrap to a new line. To accommodate this I've changed the explicit height of the settings row to a minimum height, and added vertical padding equivalent to the space between the right-side button and the top/bottom of the container.
This is more unlikely, but works on desktop as well:
=> fix(settings): wrap overflowing settings group headers so they don't break layout

packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.tsx, packages/fxa-payments-server/src/index.scss
Closes #2580
Stripe doesn't want us doing this.
Visually accommodate by vertically aligning the frame inside the faux input container
Updated look (the same):
Desktop
Mobile
=> refactor(stripe): remove usage of lineHeight property when styling Stripe input fields

packages/fxa-auth-server/config/dev.json, packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/test/local/payments/fixtures/plan1.json, packages/fxa-auth-server/test/local/payments/fixtures/plan2.json, packages/fxa-auth-server/test/local/payments/fixtures/product1.json, packages/fxa-auth-server/test/local/payments/fixtures/product2.json
Stripe metadata key [is defined as productOrder][1], but verify logic expects
productSetOrder. This fixes that.
[1]: https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-sub-platform#product-metadata
=> fix(payments): bugfix to subscription upgrade verification

packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
- updated legal checkbox text on subscription upgrade confirmation page to handle various billing intervals and interval counts
issue #3987
=> feat(payment-server): update legal checkbox text on tiers page

packages/fxa-auth-server/lib/redis.js
Because:
* It's normal and expected to have access token lookup return `null`.
* Emitting error logs for things that are expected makes it harder to
find the error logs for things that aren't expeted.
* I happened to be poking around in bigquery and saw lots of error logs
about this.
This commit:
* Avoids emitting an error log when redis access-token lookup returns `null`.
=> fix(redis): Don't log an error if an access token is `null` in redis.

packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
- updated plan billing text on subscription upgrade confirmation page to handle various billing intervals and interval counts
issue #3987
=> feat(payment-server): update plan billing text on tiers page

packages/fxa-content-server/app/styles/modules/_button-row.scss
My style change to address #4597 earlier this week was a little overzealous and inadvertently allowed disabled primary `[type='submit']` buttons to have a gray background applied. I noticed this on the subscription checkout.
Note .secondary-button and .warning-button disabled states still look good.
=> fix(ui): don't target submit buttons with gray disabled background state

packages/fxa-auth-server/lib/routes/recovery-key.js, packages/fxa-auth-server/test/local/routes/recovery-keys.js
Fixes #4613 
This PR correctly sends the `postAddAccountRecoveryEmail` when a user verifies their recovery key in the standalone flow.
=> fix(recovery): Send `postAddAccountRecoveryEmail` when recovery key verified

packages/fxa-content-server/app/scripts/templates/settings/subscription.mustache
Closes #4675
Looks like this was introduced [here](https://github.com/mozilla/fxa/commit/09be98757fc6aef1606d024a89f05ae4c08c5627#diff-6c4fc621920a9a78dfd234a6e3e4a125) and our translated strings don't like encoded characters.
=> fix(settings): replace Subscriptions & Payments section title encoded "&amp;" with "&"

packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/lib/senders/templates/downloadSubscription.html, packages/fxa-auth-server/lib/senders/templates/index.js, packages/fxa-auth-server/scripts/write-emails-to-disk.js, packages/fxa-auth-server/test/local/senders/email.js
- fixes #3872
Opening this up to get some feedback before I get it pixel perfect
cc/ @johngruen I'm wondering about the box shadow border, are we adding this to all emails or just this one?
cc/ @jackiemunroe This patch is assuming app store and play store links will be stored in Stripe, does this seem correct to you? (comment in diff)
This is what our email looks like with the changes in this patch
Here is the design from the jira issue.
=> task(auth-server): add app links to download email

packages/fxa-auth-server/scripts/test-local.sh, packages/fxa-auth-server/scripts/write-emails-to-disk.js
Not connected to an issue, we currently don't run tests for our scripts in auth-server.
=> fix(tests): Run auth server script tests in CI

packages/fxa-payments-server/src/components/PaymentConfirmation/index.scss, packages/fxa-payments-server/src/components/PaymentForm/index.scss, packages/fxa-payments-server/src/components/PlanDetails/index.test.tsx, packages/fxa-payments-server/src/components/PlanDetails/index.tsx, packages/fxa-payments-server/src/index.scss, packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.scss, packages/fxa-payments-server/src/routes/Product/SubscriptionSuccess/index.scss, packages/fxa-payments-server/src/routes/Product/index.scss
Some CSS tweaks and changing `role` to `undefined` when we don't need it so it doesn't render on the element as `''` when `role` should be read as its default.
=> fix(styles): Minor FPN mobile enhancements tweaks

_scripts/syncserver.sh
Because:
* The syncserver docker container used for local development needs to
talk to the local FxA server to verify OAuth tokens.
This commit:
* Passes appropriate environment variables to configure syncserver to
use the local FxA server as its identity provider.
* Requires an update to the syncserver docker image in order to work around
some network access issues; ref https://github.com/mozilla-services/syncserver/pull/209
=> fix(docker): Configure docker syncserver to correctly verify oauth tokens.

packages/fxa-auth-server/docs/oauth/api.md, packages/fxa-auth-server/lib/oauth/routes/verify.js, packages/fxa-auth-server/test/oauth/routes/verify.js, packages/fxa-profile-server/lib/server/web.js, packages/fxa-profile-server/test/lib/mock.js
Issue #488
One follow up to this would be to:
* Drop the email column from codes and tokens and refreshTokens tables
=> refactor(oauth): finish removing the "email" field in oauth /v1/verify response

_scripts/adb-reverse.sh, _scripts/syncserver.sh, packages/fxa-auth-server/config/dev.json
This commit addresses the following papercuts that I found while testing
various mobile browsers against a local FxA stack:
* The profile-server runs a pretend CDN on port 1112, which the device
needs to be able to reach in order to fetch profile images. I've added
this to `adb reverse` alongside the existing ports.
* Fennec has a bug where it doesn't correctly send the port number
in the Host header, causing auth errors on the tokenserver;
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1482462
I've set `force_wsgi_environ` to allow it to work. This setting is
generally not advised as it can mask security problems, but they're
not relevant for us in local dev.
* The Firefox for iOS OAuth client id was not in the default local dev
configuration for auth-server. I've added it.
=> fix(localdev): Help local dev environment work with mobile browsers.

packages/fxa-auth-server/lib/customs.js, packages/fxa-auth-server/test/local/customs.js, packages/fxa-customs-server/lib/server.js, packages/fxa-customs-server/test/remote/check_reputation_tests.js, packages/fxa-customs-server/test/remote/ip_blocklist_tests.js
Fixes #4653 
This PR adds statsd reporting for customs server block rates. I opted to add this into the auth-server library that interacts with the customs-server because it is already configured and required less changes.
Running `nc -klvu 127.0.0.1 8125`, reports values as
```
fxa-auth-server.customs.request.check:1|c|#action:accountLogin,block:true,unblock:true,suspect:false,blockReason:other
fxa-auth-server.customs.request.check:1|c|#action:sendUnblockCode,block:true,unblock:true,suspect:false,blockReason:other
```
=> feat(stats): Add statsd block rate reporting

packages/fxa-auth-server/lib/error.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
Because:
- We are going to be offering variable billing cycles for products, we want to prevent users from accidentally purchasing multiple subscriptions to the same product
fixes #4701
=> feat(auth-server): prevent users from purchasing the same product with different plans

packages/fxa-content-server/server/lib/amplitude.js, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/tests/server/amplitude.js
This patch logs a "raw" Amplitude event in content server to stdout
along with enough context for another service to transform the raw
event into an Amplitude event identical to one that's emitted by
fxa-amplitude-send.
Fixes #4695 (FXA-1443)
=> feat(metrics): log raw Amplitude events in content server

packages/fxa-email-event-proxy/index.js
Minor nit, noticed when looking at this code. There's no need to require bluebird as two variable names.
=> fix(email-event): remove redundant require of bluebird

packages/fxa-auth-server/config/index.js, packages/fxa-auth-server/lib/log.js, packages/fxa-auth-server/lib/oauth/metrics/amplitude.js, packages/fxa-auth-server/test/local/log.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/oauth/metrics/amplitude.js, packages/fxa-content-server/server/lib/amplitude.js, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/tests/server/amplitude-schema-validation.js, packages/fxa-content-server/tests/server/amplitude.js, packages/fxa-content-server/tests/tests_server.js, packages/fxa-payments-server/Dockerfile, packages/fxa-payments-server/server/config/index.js, packages/fxa-payments-server/server/lib/amplitude.js, packages/fxa-payments-server/server/lib/amplitude.test.js, packages/fxa-shared/metrics/amplitude-event.1.schema.json, packages/fxa-shared/metrics/amplitude.js
This patch adds a JSON schema to fxa-shared and uses it to validate the
Amplitude events in the auth, content, payments servers.
At the moment when an Amplitude event fails validation against this
initial schema, it is still emitted.  This will be changed in a future
commit once the degree of confidence on the schema is higher.
=> feat(metrics):  validate Amplitude events with a JSON schema

packages/fxa-admin-panel/package.json, packages/fxa-admin-panel/public/index.html, packages/fxa-admin-panel/server/lib/csp/blocking.ts
This permits you to use port 8091 in development without CSP violations.
Also remove extraneous stylesheet reference.
In place of #4720
=> fix(admin panel): permit unsafe-inline styles when in development

packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/scripts/delete-account.js
Unblock train tagging and get `latest.dev.lcip.org/` working.
=> fix(sentry): Add missing sentry mocks when disabled

release.sh
This seems to be a left-over from when we involved the fxa-private repo
=> fix(release): remove note about fxa-admins from release script

packages/fxa-payments-server/src/components/PaymentForm/index.scss
Closes #4725
iOS doesn't like the explicit line-heights, and does best with a value of `normal`. However, in our case at least, Firefox is not liking that so we need to target just it with the explicit value.
Firefox:
Chrome:
iOS sim:
=> fix(payments): update line-height styles on payment inputs to address a buggy offset

packages/fxa-payments-server/src/components/PaymentConfirmation/index.scss
=> task(payments-server): diplay amex logo in confirmation billing details

packages/fxa-payments-server/server/config/index.js, packages/fxa-payments-server/server/lib/amplitude.js, packages/fxa-payments-server/server/lib/amplitude.test.js, packages/fxa-payments-server/server/lib/routes/post-metrics.js
This patch logs a "raw" Amplitude event in payments server to stdout
along with enough context for another service to transform the raw event
into an Amplitude event identical to one that's emitted by
fxa-amplitude-send.
It also removes a unused parameter from the exported amplitude function;
that change is not directly related to the raw event changes.
Fixes #4696 (FXA-1445)
=> feat(metrics): log raw Amplitude events in payments server

packages/fxa-auth-db-mysql/db-server/test/backend/db_tests.js, packages/fxa-auth-db-mysql/db-server/test/fake.js, packages/fxa-auth-db-mysql/scripts/createAccounts.js, packages/fxa-auth-db-mysql/scripts/migration-lint.js, packages/fxa-auth-db-mysql/scripts/populate-session-tokens.js, packages/fxa-auth-db-mysql/test/local/metrics_tests.js, packages/fxa-auth-db-mysql/test/local/mysql_tests.js, packages/fxa-auth-server/lib/db.js, packages/fxa-auth-server/lib/routes/emails.js, packages/fxa-auth-server/lib/routes/password.js, packages/fxa-auth-server/lib/routes/utils/signin.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/local/routes/emails.js, packages/fxa-auth-server/test/mailer_helper.js, packages/fxa-auth-server/test/mocks.js, packages/fxa-auth-server/test/remote/db_tests.js, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/models/password_strength/password_strength_balloon.js, packages/fxa-shared/email/helpers.js
Closes #4644
~I ended up using `String.localeCompare` to check email equality, based on the responses to this [Stack Overflow question](https://stackoverflow.com/q/2140627/717633) ([this response](https://stackoverflow.com/a/51005583/717633) is particularly helpful).~
[For now](https://github.com/mozilla/fxa/pull/4736#discussion_r402647434) we're going to use the regular `toLowerCase` comparison.
In case you're curious, I put together a comparison of the three common methods for string comparison here: https://codepen.io/jodyheavener/pen/rNVbvjg
=> refactor(emails): move all email normalization and equality checks to helper functions

packages/fxa-content-server/tests/intern.js
By default intern.js runs a feature detection routine before each test. Since we have a large number of tests skipping it can save a significant amount of time.
https://github.com/theintern/intern/blob/master/docs/concepts.md#webdriver-feature-tests
=> chore(tests): set fixSessionCapabilities to no-detect

packages/fxa-auth-server/config/index.js, packages/fxa-auth-server/lib/metrics/amplitude.js, packages/fxa-auth-server/lib/oauth/metrics/amplitude.js, packages/fxa-auth-server/test/local/metrics/amplitude.js, packages/fxa-auth-server/test/local/metrics/events.js, packages/fxa-auth-server/test/mocks.js, packages/fxa-auth-server/test/oauth/metrics/amplitude.js
This patch logs "raw" Amplitude events in auth server to stdout along
with enough context for another service to transform the raw events into
Amplitude events identical to those emitted by fxa-amplitude-send.
Fixes #4697 (FXA-1444)
=> feat(metrics): log raw Amplitude events in auth server

packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/metrics/amplitude.js, packages/fxa-auth-server/package-lock.json, packages/fxa-auth-server/package.json, packages/fxa-auth-server/test/local/metrics/amplitude.js, packages/fxa-content-server/server/lib/amplitude.js, packages/fxa-content-server/tests/server/amplitude.js, packages/fxa-payments-server/package-lock.json, packages/fxa-payments-server/package.json, packages/fxa-payments-server/server/lib/amplitude.js, packages/fxa-payments-server/server/lib/amplitude.test.js, packages/fxa-payments-server/server/lib/server.js
Because:
* We want to know how many amplitude events are dropped by the
transform step.
* Creating ad-hoc non-uniform singletons is inconsistent and difficult
to effectively test.
This commit:
* Add's metrics to amplitude events in content-server, auth-server, and
payments-server.
* Uses typedi for Dependency Injection for a consistent mechanism to set
singleton type objects and retrieve them.
Closes #4656
=> feat(metrics): add metrics to amplitude events

packages/fxa-auth-server/lib/log.js, packages/fxa-auth-server/lib/oauth/metrics/amplitude.js, packages/fxa-auth-server/test/local/log.js, packages/fxa-auth-server/test/oauth/metrics/amplitude.js, packages/fxa-content-server/server/lib/amplitude.js, packages/fxa-content-server/tests/server/amplitude-schema-validation.js, packages/fxa-payments-server/server/lib/amplitude.js, packages/fxa-payments-server/server/lib/amplitude.test.js, packages/fxa-shared/metrics/amplitude-event.1.schema.json
This patch loosens the regular expression pattern on the language
property of the Amplitude event JSON schema.
The time property is also updated to be a positive integer as that is
what fxa-amplitude-send expects.
Fixes #4783 (FXA-1504)
=> fix(metrics): update language property on Amplitude schema

packages/fxa-content-server/server/lib/configuration.js
Fixes #4157 
After speaking with Adjust support, they recommended that we update our adjust deeplink with these params.
* Use `jsr` [type link](http://help.adjust.com/optimize/re-engagement/deeplinks/direct-links-for-ios#javascript-universal-links)
* Append encoded param value `adjust_deeplink_js=1`
Using these values I was able to successfully open the Firefox iOS application after clicking on the link after an install.
=> fix(deeplink): Update our deeplinking url based on updates from adjust support

_scripts/test-package.sh, package.json
IDK that anyone should ever use the `all` case, and I doubt it would pass right now but I wanted a top-level command for running an individual package's tests.
=> chore(tests): made root level "npm test" more functional

release-feature-branch.sh, release.sh
- in release.sh: filter out release tags with hyphens, under the
assumption that these are feature branch releases
- add release-feature-branch.sh script that produces a branch & tag
consisting of the last-deployed train with feature branch merged in
=> fix(release): fix last-tag lookup in release.sh, add feature branch script

.circleci/config.yml, packages/fxa-auth-server/package.json, packages/fxa-customs-server/scripts/test-local.sh, packages/fxa-shared/package-lock.json, packages/fxa-shared/package.json, packages/fxa-shared/scripts/mocha-coverage.js
Fixes #3994 
This adds support for code coverage reporting via CodeCov. There were a couple issues I found with coveralls
* Difficult to rollup individual package test result into one larger report 
* You had to individually run the upload coverage on each package (CodeCov scans root fxa folder and uploads all coverage reports)
We currently track reports for
* fxa-auth-server
* fxa-auth-db-server
* fxa-shared
* fxa-profile-server
* fxa-customs-server
* fxa-admin-panel
* fxa-payments-server
=> fix(coverage): Update code report coverage

packages/fxa-content-server/tests/functional/lib/helpers.js
This patch will stop uploading screenshots of functional test failures to
Shane's server.
Fixes #3513 (FXA-584)
=> chore(CI): stop using screencap.co.uk

debug_servers.json
Because:
* secrets.json should be used when starting the servers locally and
these files were only added to `mysql_servers.json`.
This commit:
* Adds the same options for `debug_servers.json`.
=> fix: include CONFIG_FILES in debug_servers file

packages/fxa-content-server/tests/functional/delete_account.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/settings.js
I made the following changes:
- added scenario for "delete account with **incorrect** password" in the delete_account.js, selectors.js file
- made small changes to the "delete account with **correct password** and **click cancel** testcases" in delete_account.js file
- added scenario for 'changing display name' in the settings.js file
@vbudhram - Please review.
=> test(functional): add missing scenarios to the delete account and display name test

packages/fxa-content-server/app/styles/modules/_settings.scss
Closes #4775
Also, the name in my screenshot is [real](https://www.historyrundown.com/top-5-people-with-the-longest-names/#3David_Fearn).
=> fix(settings): don't allow display name or email to break page layout

packages/fxa-content-server/app/styles/modules/_cropper.scss
=> fix(avatar): add some space below controls

.gitignore, _scripts/audit.sh, package.json
Totally fine if this idea gets rejected, but it was quick so I wanted to get everyone's take on it.
I am consistently running into issues with the NPM audit service, and am frequently having to push with `--no-verify`. This PR changes the pre-push hook to run a script that checks if you've audited within the last 24 hours. If you have, skip it, and audit again when 24 hours has passed.
To be clear, it doesn't solve the problem with auditing, buuuut it reduces the amount of times you could encounter the issue. Plus, with the number of people pushing to the repo there are absolutely going to be checks less than 24 hours apart.
Thoughts?
=> chore(audit): only audit on push once per day

packages/fxa-content-server/app/styles/_variables.scss, packages/fxa-content-server/app/styles/modules/_password-row.scss
Closes #4917
Before:
After:
For those of you saying "wait, I can still see a _little_ but of the white!", this is what it looks like (unfocused) when we go 1px further:
=> fix(password input): use 1px less border radius on password revealer button

packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
- ensure 'invoices' is accepted as a valid Stripe resource to expand
- move call to expand latest subscription invoice out of webhook handler
and into StripeHelper
- replace a few resource name strings with constant references
- fix error log call on an attempt to expand an invalid Stripe resource
- update tests
FXA-1634
=> fix(payments): ensure 'invoices' is valid expandable Stripe resource

packages/fxa-content-server/app/styles/modules/_settings.scss
Closes #4888
Before:
After:
Additionally, I made a small tweak to allow full text width on mobile.
Before:
After:
=> fix(devices + apps): update styles to allow overflowing long device names

packages/fxa-payments-server/.storybook/components/MockApp.tsx, packages/fxa-payments-server/src/routes/Product/index.stories.tsx
Noticed this error when trying to view some stories. Seems like the Stripe JS API has changed to freeze some object properties we were manipulating in place? This PR seems to fix
=> fix(payments): bugfix for creating default mock stubs for stripe JS API

packages/fxa-auth-server/docs/oauth/api.md, packages/fxa-auth-server/docs/oauth/prompt-none.md, packages/fxa-auth-server/lib/oauth/jwt_id_token.js, packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/test/local/routes/oauth.js, packages/fxa-auth-server/test/oauth/jwt_id_token.js, packages/fxa-content-server/app/scripts/lib/oauth-errors.js, packages/fxa-content-server/app/scripts/lib/vat.js, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/models/reliers/oauth.js, packages/fxa-content-server/app/tests/spec/models/reliers/oauth.js, packages/fxa-content-server/tests/functional/oauth_prompt_none.js, packages/fxa-js-client/client/FxAccountClient.js, packages/fxa-js-client/tests/lib/oauth.js, packages/fxa-js-client/tests/mocks/request.js
Adds a server-side id token verifier and threads the token verification
step through fxa-js-client and the account and oauth relier models.
=> Add `id_token_hint` support to `prompt=none` flow

packages/fxa-content-server/tests/functional/recovery_key.js
Added testcase for:
- entering blank recovery key and verifying with the error message
- trying to use old recovery key to reset password (expect error) and then trying with the new one(expect sign in) 
@vbudhram - Please review.
=> test(functional): add testcase for old and blank recovery key

packages/fxa-content-server/package-lock.json, packages/fxa-content-server/package.json, packages/fxa-content-server/webpack.config.js
Since #4763 introduced async/await the uglifyjs minimizer
fails. The built in webpack minimizer (Terser) does handle
it and performs about equally well.
The other issue is whether we transpile async/await for
older browsers, hence the addition of babel-loader to .ts
files. <strike>I opted for the safer option of doing the transpile
for now. We can defer that decision until later.</strike>
Unless we want to add babel/polyfill we should go with native async/await. According to https://caniuse.com/#feat=async-functions all our supported browsers have it.
=> fix(content-server): fixed build-production after #4763

.circleci/config.yml
Using parallelism means that if any tests fail
we need to rerun all the tests and risk having
another unrelated test fail. By unrolling
the parallelism into separate jobs we're able
to run just the section that failed, saving
resources and dev time.
=> feat(ci): unroll content-server test in circleci

packages/fxa-content-server/app/scripts/lib/auth/client.ts, packages/fxa-content-server/tests/functional/settings_change_email.js
Fixes #5002 
I'm a bit of noob at typescript but reading through the [blog](https://itnext.io/error-handling-with-async-await-in-js-26c3f20bc06a) they recommended adding the `await` keyword so that errors get caught correctly. Maybe a better way to do this? Also added a test so we catch it next time.
I've targeted as a point release on train-167 since it breaks account delete when users have changed their primary email. cc @dannycoates
=> fix(delete): Specify `await` on `this.sessionPost` so error get caught

.gitignore, packages/fxa-components/LICENSE, packages/fxa-components/package-lock.json, packages/fxa-components/package.json, packages/fxa-settings/.rescriptsrc.js, packages/fxa-settings/README.md, packages/fxa-settings/package-lock.json, packages/fxa-settings/package.json, packages/fxa-settings/pm2.config.js
Sort of an extension to #4819, but also a precursor for #4817 
This PR allows `fxa-settings` to import React components beyond its `./src` directory. This is not allowed in a standard CRA setup, so we are introducing [Rescripts](https://github.com/harrysolovay/rescripts) per [ADR 0013](https://github.com/mozilla/fxa/blob/master/docs/adr/0013-react-toolchain-for-settings-redesign.md#decision-outcome) to allow us to override CRA's Webpack configuration.
I've documented what I'm doing in `.rescriptsrc.js` -- it might _look_ scary, but it's actually pretty straightforward.
=> feat(settings): add rescripts, allow external imports

packages/browserid-verifier/Dockerfile
I don't recall if this ENTRYPOINT and/or CMD were particularly needed here for some reason. Anyways, `npm start` will now trigger a `pm2` command, so should remove these now.
=> fix(verifier): remove ENTRYPOINT/CMD

.circleci/config.yml, packages/fxa-metrics-processor/.prettierrc, packages/fxa-metrics-processor/.vscode/launch.json, packages/fxa-metrics-processor/.vscode/tasks.json, packages/fxa-metrics-processor/Dockerfile, packages/fxa-metrics-processor/package-lock.json, packages/fxa-metrics-processor/package.json, packages/fxa-metrics-processor/src/bin/queueWorker.ts, packages/fxa-metrics-processor/src/config.ts, packages/fxa-metrics-processor/src/lib/message-processor/index.ts, packages/fxa-metrics-processor/src/lib/pubsub.ts, packages/fxa-metrics-processor/src/lib/version.ts, packages/fxa-metrics-processor/src/test/lib/pubsub.spec.ts, packages/fxa-metrics-processor/tslint.json
Because:
* Metrics processor should be run on raw event queue.
This commit:
* Add's the queue worker with base metric processor class that
consumes using polling from the PubSub raw event queue and
outputs processed messages to the amplitude topic. Messages
that failed to process are added to the dead letter topic.
Closes #4698
Co-authored-by: Barry Chen <chenba@gmail.com>
=> feat(metrics-processor): add's queue worker

packages/fxa-admin-panel/.rescriptsrc.js, packages/fxa-admin-panel/README.md, packages/fxa-admin-panel/jest.config.js, packages/fxa-admin-panel/package-lock.json, packages/fxa-admin-panel/package.json, packages/fxa-admin-panel/pm2.config.js, packages/fxa-admin-panel/src/components/Footer/index.tsx, packages/fxa-admin-panel/src/components/LinkAbout/index.tsx, packages/fxa-admin-panel/tsconfig.json, packages/fxa-components/.eslintrc, packages/fxa-components/LinkExternal/index.test.tsx, packages/fxa-components/LinkExternal/index.tsx, packages/fxa-components/README.md, packages/fxa-components/jest.config.js, packages/fxa-components/package-lock.json, packages/fxa-components/package.json, packages/fxa-components/rescripts.js, packages/fxa-components/tsconfig.common.json, packages/fxa-components/tsconfig.json, packages/fxa-settings/.rescriptsrc.js, packages/fxa-settings/README.md, packages/fxa-settings/jest.config.js, packages/fxa-settings/scripts/test-ci.sh
Closes #4817
This PR does a few things:
- Sets up Rescripts in `fxa-admin-panel` (see #5001 if you're confused)
- Moves `LinkedExternal` from `fxa-admin-panel` to `fxa-components` 🎉 
- Sets up testing, linting, tsconfig, etc for `fxa-components`
- Updates our CRA setups to permit importing via `@fxa-components`
=> Finish settings up external components

packages/fxa-content-server/tests/functional/sign_in_cached.js
Hopefully fixes the `sign in with incorrect email case before normalization fix, on second attempt canonical form is used` test. This passed 7/7 times locally.
=> fix(test): Attempt to fix denormalization signin error

packages/fxa-metrics-processor/.prettierrc, packages/fxa-metrics-processor/Dockerfile, packages/fxa-metrics-processor/package-lock.json, packages/fxa-metrics-processor/package.json, packages/fxa-metrics-processor/scripts/test-ci.sh, packages/fxa-metrics-processor/src/config.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/amplitude-event.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/common.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/event-properties.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/event-type.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/types.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/user-agent.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/user-properties.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/version.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/transforms/amplitude-event.spec.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/transforms/common.spec.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/transforms/event-properties.spec.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/transforms/event-type.spec.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/transforms/user-agent.spec.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/transforms/user-properties.spec.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/transforms/version.spec.ts, packages/fxa-shared/metrics/user-agent.d.ts
This patch introduces a function that takes a services map, events map,
and fuzzy events map, and returns a function that accepts a "raw"
Amplitude event and its context and produces the payload for an
Amplitude HTTP API request.
Fixes #4700 (FXA-1447)
=> feat(metrics): transform a "raw" Amplitude event into a HTTP payload

packages/fxa-auth-server/docs/api.md, packages/fxa-auth-server/docs/service_notifications.md, packages/fxa-auth-server/lib/error.js, packages/fxa-auth-server/lib/metrics/amplitude.js, packages/fxa-auth-server/lib/routes/emails.js, packages/fxa-auth-server/lib/routes/session.js, packages/fxa-auth-server/lib/routes/utils/signup.js, packages/fxa-auth-server/test/local/metrics/amplitude.js, packages/fxa-auth-server/test/local/routes/emails.js, packages/fxa-auth-server/test/local/routes/utils/signup.js, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/models/resume-token.js, packages/fxa-content-server/app/tests/spec/models/account.js, packages/fxa-content-server/app/tests/spec/models/resume-token.js, packages/fxa-content-server/server/lib/amplitude.js, packages/fxa-content-server/tests/server/amplitude.js, packages/fxa-js-client/client/FxAccountClient.js, packages/fxa-js-client/tests/lib/session.js, packages/fxa-js-client/tests/lib/verifyCode.js, packages/fxa-payments-server/server/lib/amplitude.js, packages/fxa-shared/metrics/amplitude.js, packages/fxa-shared/test/metrics/amplitude.js
Fixes https://github.com/mozilla/fxa/issues/4919
This PR removes the last remains of the `marketingOptIn` param. 
Confirmed with marketing/basket teams that they have moved away from the `marketingOptIn` param and this is safe to merge.
=> chore(cleanup): Remove the `marketingOptIn` param

packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
- move cancellation email sending from subscription deletion to when a
subscription is updated to cancel_at_period_end = true
- rework details extracted for cancellation and reactivation to match up
with the corresponding email sending methods
https://jira.mozilla.com/browse/FXA-1157
=> feat(payments): send email on subscription cancellation & reactivation

packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/server/lib/routes/redirect-m-to-adjust.js, packages/fxa-content-server/tests/server/routes/redirect-m-to-adjust.js, packages/fxa-settings/tsconfig.json
Lets revert the Android deeplink in https://github.com/mozilla/fxa/pull/4777 while debugging https://github.com/mozilla/fxa/issues/5069.
This keeps the iOS deeplink since it appears to be working per this [dashboard](https://analytics.amplitude.com/mozilla-corp/chart/scj19m8).
Since this is a regression, I would like to target train-167 as a point release.
=> fix(deeplink): Revert deeplink used on Android

packages/fxa-metrics-processor/src/lib/amplitude/index.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/amplitude-event.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/amplitude-identify.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/common.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/event-properties.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/event-type.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/types.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/user-agent.ts, packages/fxa-metrics-processor/src/lib/amplitude/transforms/user-properties.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/index.spec.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/transforms/amplitude-event.spec.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/transforms/amplitude-identify.spec.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/transforms/common.spec.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/transforms/event-properties.spec.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/transforms/event-type.spec.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/transforms/user-agent.spec.ts, packages/fxa-metrics-processor/src/test/lib/amplitude/transforms/user-properties.spec.ts
This patch adds a function to produce the payload for Amplitude's
identify API from other FxA services' "raw" events.
It also provides a function that will accept a raw event and its context
and return the payloads for Amplitude's http, and if applicable,
identify APIs.
Fixes #4979 (FXA-1671)
=> feat(metrics): create $identify Amplitude payload from raw event

packages/fxa-email-service/scripts/build-ci.sh
fixes #5103
The copy command moved out of .circleci/build.sh so this got orphaned.
=> fix(email-service): copy version.json in build-ci.sh

packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/test/local/routes/oauth.js
Because:
* We did not emit logins to relying parties if the user was already
logged into their Firefox Account.
This commit:
* Will emit login events when users login to a relying party via an
already authenticated account.
Closes #4994
=> feat(auth-server): emit login notif on oauth login

renovate.json
The past few weeks we've been talking about dependency management and I've done some asking around.  It's particularly challenging with all the packages we have, but the longer we wait the further behind we are, so...
We originally disabled renovate because it had a bug in it that failed with how we were managing one of our packages (pinning to an unpublished version, if I understood correctly).  Danny says that is fixed now.
At the time, we were also struggling with a lot of intermittent test failures and long testing times.  That has also been improved.
So, I think we should leverage automation as much as possible.  Best case, it can keep our packages up to date, but even in the worse case we'll at least be notified of updates and can decide what we need to do.
I asked several other …
=> chore(deps): Update renovate config

packages/fxa-content-server/app/tests/spec/lib/auth/hawk.js
fixes #4989
in chrome the raw key data length needs to match the length specified to importKey. In onePW it's always 32 bytes
=> fix(tests): updated hawk tests with proper key length

CONTRIBUTING.md
One of the things I've been thinking about for the past few weeks is how FxA should participate (or not) in the coding contributions side of open source.  It's no question that it's time consuming to work with contributors to get FxA up and running and can be frustrating when they end up disappearing after a few days of work.  On the other hand, many of us got our starts committing small patches to projects after being helped by the project maintainers.
I think this patch sets some context for the project that will help set realistic expectations.  I think the actual throughput of contributions (and time spent) should be controlled by whether or not we are tagging `help wanted` and `good first issue` on our issues.
If we get into a crunch period where we don't have much time, or, for …
=> docs(contributing): Add some context about FxA to contributing doc

packages/fxa-auth-server/docs/oauth/jwt-access-tokens.md, packages/fxa-auth-server/docs/oauth/pairwise-pseudonymous-identifiers.md, packages/fxa-auth-server/docs/oauth/signing-key-management.md, packages/fxa-auth-server/lib/oauth/jwt_access_token.js
Because:
* Our JWT access token implementation was done referencing
an early personal draft of a spec.
* The spec has now been officially adopted by the IETF OAuth
Working Group, with significant revisions.
* The updated spec addresses one of my personal bugbears about the
current implementation.
This commit:
* Updates reference links to point to the latest draft.
* Rewords a comment block to indicate that some current (IMHO)
strange behaviour was previously implied to be mandatory, but
has been addressed in the latest draft spec.
* Doesn't actually change the behaviour, because we'd need to
QA how that affects existing reliers.
=> Update link to OAuth JWT access tokens spec.

packages/fxa-content-server/app/scripts/models/account.js
Fixes #5135 
I believe there are still some old resume tokens that use this and it might require an additional train before it can be fully removed. This PR allows setting the property meanwhile (it still isn't used anywhere).
=> fix(marketing): Add back the ability for account model to set `needsOptedInToMarketingEmail`

packages/fxa-auth-server/config/index.js, packages/fxa-auth-server/lib/geodb.js
Are we actually using these lines for analysis? If not, they are a large proportion of our logging costs for auth server. @davismtl @vbudhram might recall.
=> fix(geodb): make geodb accuracy logging optional

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/send-sms-header.js
This PR enables variation B `Would you like to sync your phone?` for 100% of users. 
This should be uplifted as a point release on latest train, cc @chenba
=> fix(experiments): Enabled variation B 100% for sms header experiment

packages/fxa-content-server/app/scripts/lib/auth/crypto.ts
Chrome was loading the webcrypto polyfill even though
it doesn't need it because it threw an error about the
input key length on HKDF and HMAC.
=> fix(chrome): fixed webcrypto check on Chrome

packages/fxa-auth-server/bin/update_firestore_from_oauth.js, packages/fxa-auth-server/config/index.js, packages/fxa-auth-server/lib/oauth/db/mysql/index.js, packages/fxa-auth-server/package-lock.json, packages/fxa-auth-server/package.json
Because:
* We were not emitting a login event for users logging
into relying parties if they were already logged into
FxA.
* FxA Event Broker relies on loging events to determine
what relying parties to deliver user events to.
This commit:
* Will load the Firestore db used by Event Broker with
all the users for a provided RP Client ID that have
previously logged into that RP.
Closes #4993
=> feat(auth-server): add oauthdb firestore sync

packages/fxa-auth-server/tsconfig.json
Closes #5150
This prevented CI from building properly.
```
Could not find a declaration file for module 'accept-language'. '/fxa/packages/fxa-shared/node_modules/accept-language/index.js' implicitly has an 'any' type.
Try `npm install @types/accept-language` if it exists or add a new declaration (.d.ts) file containing `declare module 'accept-language';`
```
@chenba I know your original comment was to add the type declaration file to fxa-auth-server, but I figured since the issue stemmed from a module referenced in a file from fxa-shared that we should have a single source of truth/keep it dry.
=> fix(auth server): reference fxa-shared types in tsconfig

README.md, packages/fxa-graphql-api/package-lock.json, packages/fxa-graphql-api/package.json, packages/fxa-graphql-api/pm2.config.js, packages/fxa-graphql-api/src/bin/main.ts, packages/fxa-graphql-api/src/config.ts, packages/fxa-graphql-api/src/lib/constants.ts, packages/fxa-graphql-api/src/lib/oauth/index.ts, packages/fxa-graphql-api/src/lib/server.ts, packages/fxa-graphql-api/src/lib/user/index.ts, packages/fxa-graphql-api/src/lib/user/types.ts, packages/fxa-graphql-api/src/test/lib/oauth/index.spec.ts, packages/fxa-graphql-api/src/test/lib/server.spec.ts, packages/fxa-graphql-api/src/test/lib/user/index.spec.ts
This patch enables graphql-api server to accept an OAuth2 access token
on the graphql route.
It:
1. validates the format of the authorization header value in middleware
2. looks up the token in Redis
3. ensures the client id of the token is in the allowed clients list
4. includes the user's id and email in the 'authUser' property in
Apollo's context
5. includes the authorization header value as 'token' in Apollo's
context
Fixes #5092 (FXA-1753)
=> feat(gql-api): add auth to graphql-api server

packages/fxa-customs-server/lib/server.js
This missed the train, but it would be nice to get on if we do a point release. It updates the connection timeout for customs server to reduce the socket hangups that occur from auth-server.
cc @jrgm @bbangert
=> fix(customs): Update the route timeout level for customs server

_dev/docker/node/Dockerfile
=> fix(docker): add graphicsmagick to base node image

packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/test/local/payments/stripe.js
Similar to PR #5137, another spot where we need to use a different billing date
fixes #5200
=> fix(payments): use period end from first invoice line for reactivation billing date

packages/fxa-shared/tsconfig.json
The l10n repo build installs things differently from
this repo. The `npm ci` on fxa-auth-server is "broken"
with how deps are currently laid out. We really need
a better way to manage interpackage dependencies, but
that's a more involved issue.
In the meantime adding the @types from fxa-auth-server
to the fxa-shared tsconfig fixes the build error.
This is in response to: https://app.circleci.com/pipelines/github/mozilla/fxa-content-server-l10n/119/workflows/eec13c72-35c9-446c-a574-5dbe076fb3eb/jobs/6364
ref: https://github.com/mozilla/fxa-content-server-l10n/blob/8a5515c75395169b2f1badbdc03f36f5dd5fbd99/scripts/extract-and-pull-request.sh
=> fix(l10n): temporary (hopefully) fix for l10n CI build

packages/fxa-components/AppErrorBoundary/index.tsx, packages/fxa-components/jest.config.js, packages/fxa-components/rescripts.js, packages/fxa-components/scripts/test-ci.sh, packages/fxa-components/tsconfig.json, packages/fxa-settings/package-lock.json, packages/fxa-settings/package.json, packages/fxa-settings/src/index.tsx, packages/fxa-settings/src/lib/config.ts, packages/fxa-shared/lib/logger.ts, packages/fxa-shared/lib/sentry.ts, packages/fxa-shared/package-lock.json, packages/fxa-shared/package.json, packages/fxa-shared/test/lib/logger.ts, packages/fxa-shared/test/lib/sentry.ts
Closes #5017
This PR adds the files for Sentry (and by extension a logger), and sets it up in fxa-settings.
Notes:
- The Sentry and Logging files, as well as their accompanying tests, more or less came from fxa-payments-server, and were converted to TypeScript.
- The Sentry and Logging files are in fxa-shared because they are being used in AppErrorBoundary, which is itself a shared fxa-component. I am open to directory naming suggestions.
=> feat(settings): add sentry setup

packages/fxa-auth-server/docs/service_notifications.md, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/lib/routes/newsletters.js, packages/fxa-auth-server/test/local/routes/newsletters.js, packages/fxa-content-server/app/scripts/lib/auth/client.ts, packages/fxa-content-server/app/scripts/lib/fxa-client.js, packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/templates/post_verify/newsletters/add_newsletters.mustache, packages/fxa-content-server/app/scripts/views/confirm_signup_code.js, packages/fxa-content-server/app/scripts/views/mixins/email-opt-in-mixin.js, packages/fxa-content-server/app/scripts/views/post_verify/newsletters/add_newsletters.js, packages/fxa-content-server/app/styles/_base.scss, packages/fxa-content-server/app/styles/modules/_graphic.scss, packages/fxa-content-server/app/tests/spec/views/post_verify/newsletters/add_newsletters.js, packages/fxa-content-server/app/tests/test_start.js, packages/fxa-content-server/server/lib/routes/get-frontend.js
Fixes https://github.com/mozilla/fxa/issues/4930
* This adds the supporting view to add a newsletter subscription
* Updated client methods
* Adds auth-server endpoint to accept newsletters and send and SQS message for basket to process. Basket will be updated to handle new message per https://github.com/mozmeao/basket/issues/523
To test goto [http://localhost:3030/post_verify/newsletters/add_newsletters](http://localhost:3030/post_verify/newsletters/add_newsletters)
Note that I will add the functional tests in the upcoming experiment PR, https://github.com/mozilla/fxa/issues/4928.
=> feat(newsletters): Add subscribing to newsletters to signup flow for Sync

packages/fxa-customs-server/Dockerfile
since customs-server doesn't have a pm2.config.js file
it needs a Dockerfile in order to build and deploy
fixes #5208
=> fix(docker): added Dockerfile for fxa-customs-server

packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/src/App.tsx, packages/fxa-payments-server/src/components/PlanDetails/index.stories.tsx, packages/fxa-payments-server/src/components/PlanDetails/index.test.tsx, packages/fxa-payments-server/src/components/PlanDetails/index.tsx, packages/fxa-payments-server/src/index.tsx, packages/fxa-payments-server/src/lib/AppContext.tsx, packages/fxa-payments-server/src/lib/test-utils.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.stories.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/mocks.tsx, packages/fxa-payments-server/src/routes/Product/index.stories.tsx, packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx, packages/fxa-payments-server/src/store/types.tsx, packages/fxa-payments-server/src/store/utils.test.tsx, packages/fxa-payments-server/src/store/utils.tsx
Localizable product details in Stripe metadata. Documentation updates to
follow separately in ecosystem docs.
Example usage in Stripe metadata:
```
product:name = "Firefox Private Network"
product:subtitle = "Full-device VPN"
product:details:1 = "Device-level encryption"
product:details:2 = "Servers in 30+ countries"
product:details:3 = "Connects 5 devices with one subscription"
product:details:4 = "Available for Windows, iOS and Android"
product:name:xx-pirate = "Firefox Private Network"
product:subtitle:xx-pirate = "VPN fer yer full-device"
product:details:1:xx-pirate = "Device-level encryption arr"
product:details:2:xx-pirate = "Servers is 30+ countries matey"
product:details:3:xx-pirate = "Connects 5 devices wit' one subscription"
product:details:4:xx-pirate = "Available fer Windows, …
```
=> feat(payments): make product details configurable in Stripe metadata

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/index.js, packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/newsletter-sync.js, packages/fxa-content-server/app/scripts/templates/post_verify/newsletters/add_newsletters.mustache, packages/fxa-content-server/app/scripts/views/confirm_signup_code.js, packages/fxa-content-server/app/scripts/views/mixins/newsletter-sync-experiment-mixin.js, packages/fxa-content-server/app/scripts/views/post_verify/newsletters/add_newsletters.js, packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/index.js, packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/newsletter-sync.js, packages/fxa-content-server/tests/functional.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/post_verify/newsletters.js
~Blocked by https://github.com/mozilla/fxa/pull/5124~
Fixes #4928
This PR adds all the supporting logic the newsletters sync experiment per https://docs.google.com/document/d/1S9Mt83DNHfQHtiuU4m3dLOIyA_FhU5tPHAgJqZkGoCE/edit#. 
* `control` - not shown newsletters
* `trailhead-copy` - description says "Practical knowledge is coming to your inbox."
* `new-copy` - description says "Get practical knowledge in your inbox about:"
This experiment will be disabled by default, but you can test by going to these urls and signing up for an account.
http://localhost:3030/?service=sync&context=fx_desktop_v3&entrypoint=fxa_discoverability_native&action=email&forceExperiment=newsletterSync&forceExperimentGroup=trailhead-copy
http://localhost:3030/?service=sync&context=fx_desktop_v3&entrypoint=fxa_discove …
=> feat(newsletters): Add experiment for newsletter subscriptions

packages/fxa-auth-server/README.md, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/oauth/metrics/amplitude.ts, packages/fxa-auth-server/package.json, packages/fxa-auth-server/pm2.config.js, packages/fxa-auth-server/scripts/test-local.sh, packages/fxa-auth-server/test/local/senders/select_email_services.js, packages/fxa-auth-server/test/oauth/key-management-scripts.js, packages/fxa-auth-server/test/scripts/email-config.js
Closes #4879 
_Part of a larger effort to [adopt TypeScript in the Auth Server](https://jira.mozilla.com/browse/FXA-1500)._
---
I'm trying to take a slow, educational approach to TypeScript, so please feel free to tear this apart.
=> refactor(auth server): typescript lib/oauth/metrics

packages/fxa-content-server/app/scripts/lib/experiment.js, packages/fxa-content-server/app/scripts/lib/metrics.js, packages/fxa-content-server/app/scripts/views/post_verify/newsletters/add_newsletters.js, packages/fxa-content-server/app/tests/spec/lib/metrics.js, packages/fxa-content-server/server/lib/amplitude.js, packages/fxa-content-server/server/lib/routes/post-metrics.js, packages/fxa-content-server/server/lib/validation.js, packages/fxa-shared/metrics/amplitude.js, packages/fxa-shared/test/metrics/amplitude.js
Fixes #4927 
Amplitude metrics
```
{"op":"amplitudeEvent","event_type":"fxa_newsletter - view","time":1588865495023,"device_id":"b94ac7668fb843cba9e5213103107493","session_id":1588865494644,"app_version":"169.1","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"933fb9f1110616a8d582ad1681e90e005527f25d6f061145dc347f3222cfe490","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync","experiments":["newsletter_sync_trailhead_copy"]}}}
{"op":"amplitudeEvent","event_type":"fxa_newsletter - engage","time":1588865499011,"device_id":"b94ac7668fb843cba9e5213103107493","session_id":1588865494644,"app_version":"169.1","language":"en","os_name":"Mac OS …
```
=> feat(newsletters): Add newsletters experiment metrics

packages/fxa-content-server/app/scripts/lib/country-telephone-info.js, packages/fxa-customs-server/lib/config/config.js
Prepped PR in case we need this. Targets train 169.
cc @jbuck @jrgm
=> fix(sms): Enable sms for only US/CAD at 10%, reduce default max sms to 3

packages/fxa-auth-db-mysql/CHANGELOG.md, packages/fxa-auth-server/CHANGELOG.md, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/senders/sms.js, packages/fxa-auth-server/test/local/senders/sms.js, packages/fxa-content-server/CHANGELOG.md, packages/fxa-content-server/app/scripts/lib/country-telephone-info.js, packages/fxa-customs-server/CHANGELOG.md, packages/fxa-customs-server/lib/config/config.js, packages/fxa-email-service/CHANGELOG.md, packages/fxa-event-broker/CHANGELOG.md, packages/fxa-geodb/CHANGELOG.md, packages/fxa-payments-server/CHANGELOG.md, packages/fxa-profile-server/CHANGELOG.md, packages/fxa-shared/CHANGELOG.md, packages/fxa-support-panel/CHANGELOG.md
Uplift changes from train 169. This also fixes the change logs. Once this merges we can tag a new release on 170.
=> Train 170 uplift 169

packages/fxa-auth-server/.vscode/launch.json
Changes:
- added arguments to the mocha scripts in the launch file to load `ts-node`
Because:
- the recent addition of typescript config files caused the current test scripts to fail to run due to `MODULE NOT FOUND`
=> chore(auth-server): fix vscode launch.json test scripts

packages/fxa-content-server/app/scripts/lib/country-telephone-info.js
r? - @vbudhram 
Undoes the changes in https://github.com/mozilla/fxa/commit/5f750ee080c0e2e48ac9bc5c822a1beb27bc37ef except for the change to maxSms for customs-server
Fixes #5277
=> fix(sms): revert non-US sms restrictions; US/CA back to 100%

packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
Adds new cancelled_for_customer_at metadata property on Stripe
subscription. This is distinct from canceled_at and cancel_at_period_end
which are modified by immediate cancellation which happens when
account is deleted.
https://jira.mozilla.com/browse/FXA-1769
fixes #5121
=> fix(payments): record our subscription cancellation time to avoid duplicate email on account deletion

packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
https://jira.mozilla.com/browse/FXA-1814
issue #5193
Still thinking if / when / how to retry email sending in general for email-related Stripe errors.
But from what I can tell, "hard" email bounces will never succeed after retries. (e.g. the example error in the issue leads to a testing email of `test@testo.com`) So, maybe we can at least just ignore those?
=> feat(payments): ignore hard email bounce errors in Stripe webhooks

packages/fxa-auth-server/lib/oauth/db/mysql/index.js, packages/fxa-auth-server/lib/oauth/token.js
=> refactor(oauth): stop querying for 'email' in oauth tables

packages/fxa-auth-server/lib/oauth/jwt.js, packages/fxa-auth-server/lib/oauth/jwt_id_token.js, packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/test/local/routes/oauth.js, packages/fxa-auth-server/test/oauth/jwt.js, packages/fxa-auth-server/test/oauth/jwt_id_token.js, packages/fxa-content-server/app/scripts/lib/auth/client.ts, packages/fxa-content-server/app/scripts/lib/constants.js, packages/fxa-content-server/app/scripts/lib/fxa-client.js, packages/fxa-content-server/app/scripts/lib/vat.js, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/models/reliers/oauth.js, packages/fxa-content-server/app/tests/spec/lib/fxa-client.js, packages/fxa-content-server/app/tests/spec/models/account.js, packages/fxa-content-server/app/tests/spec/models/reliers/oauth.js
Grab bag of small fixes. Biggest change is allowing ID tokens to be used as id_token_hint for up to 7 days after being issued. Also tweaked response schema for id-token-verify auth server route, added a wrapper function to the right (new) fxa-js-client, and updated related tests.
=> fix(bug): small fixes for id_token_hint

.gitignore
Because:
We had to occasionally add to our list of !.* exceptions which was getting a little unwieldy. Instead, we'll manually add the ones we need ignored.
fixes #5250
--
While `.tmp` and `.tscompiled` could go under "build and temp files," they're content-server specific which is why I've stuck them in that section.
The content server's `outDir` for TS could be changed to `dist` for consistency - we could then remove line 101. I'll create a follow up ticket for that when this is approved.
Will the reviewer check into my branch and check their `git status` and poke through our `packages/` dir to help ensure I haven't missed anything? 😬
=> fix(gitignore): Remove .* and subsequent .* exceptions

docs/adr/0014-auth-for-settings-redesign.md, docs/adr/0017-switch-settings-auth-to-sessiontoken.md
After comments [from dannycoates](https://github.com/mozilla/fxa/pull/5253#issuecomment-626112085) [and rfk](https://github.com/mozilla/fxa/pull/5253#issuecomment-627037889) on the now-closed PR #5253, I threw this together as an attempt to summarize what seems to be current thinking.
=> docs(settings): Switch from OAuth2 to sharing sessionToken with GraphQL server for settings redesign auth

packages/fxa-customs-server/package-lock.json, packages/fxa-customs-server/package.json, packages/fxa-customs-server/test/remote/check_reputation_tests.js, packages/fxa-customs-server/test/test_reputation_server.js, packages/fxa-customs-server/test/test_reputation_server_stub.js
Update version of ip-reputation-js-client to most recent available which
is 6.0.0.
This also adjusts the iprepd mock endpoints to emulate the new endpoints
in iprepd that the new reputation module makes use of.
=> feat(customs): ip-reputation-js-client 6.0.0

packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/app/scripts/templates/redirect_loading.mustache, packages/fxa-content-server/app/scripts/templates/subscriptions_redirect.mustache, packages/fxa-content-server/app/scripts/views/get_flow.js, packages/fxa-content-server/app/scripts/views/subscriptions_management_redirect.js, packages/fxa-content-server/app/scripts/views/subscriptions_product_redirect.js, packages/fxa-content-server/app/tests/spec/views/get_flow.js, packages/fxa-content-server/app/tests/spec/views/subscriptions_management_redirect.js, packages/fxa-content-server/app/tests/spec/views/subscriptions_product_redirect.js, packages/fxa-content-server/app/tests/test_start.js, packages/fxa-content-server/server/lib/routes/get-frontend.js, packages/fxa-content-server/tests/server/routes.js, packages/fxa-settings/package-lock.json, packages/fxa-settings/package.json, packages/fxa-settings/src/components/App/index.test.tsx, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/index.tsx, packages/fxa-settings/src/lib/flow-event.test.ts, packages/fxa-settings/src/lib/flow-event.ts, packages/fxa-settings/src/lib/types.ts, packages/fxa-settings/src/lib/url-params.ts
Closes #5019
Alternative approach to #5282.
Here's how:
- Set up minimal library in fxa-settings to parse flow data params, and redirect you to fxa-content-server to fetch new flow data if they're not present
- The majority of the flow-event lib comes from the existing one in the payments server, with the exception that it can optionally redirect you to the content server for flow data is it's not present
- Set up new route in fxa-content-server (`/get_flow`) to retrieve a new set of flow data, and send you back to your original address
Here's how I'm testing this:
```
// Should redirect you to /beta/settings with Flow data params
http://localhost:3030/get_flow?redirect_to=/beta/settings
// Should do nothing (console error about no redirect_to)
http://localhost:3030/get_flow
// Should do …
```
=> feat(content + settings): ensure visiting beta/settings/ always has flow data

docs/adr/0018-use-tailwind-with-custom-scss.md
Closes #5087
> This ADR serves to determine how we'll approach our CSS architecture in the Settings Redesign project, evaluating libraries and frameworks to determine which if any will be the best option for the FxA ecosystem.
📖 [Pretty version](https://github.com/mozilla/fxa/blob/jh/5087/css-adr-p2/docs/adr/0018-use-tailwind-with-custom-scss.md)
=> docs(adr): Use Utility-First CSS (Tailwind) with Custom SCSS

packages/fxa-content-server/tests/functional/lib/helpers.js
Not connected to an issue, but this PR prints a base64 string of the screenshot taken when a functional test errors. This would be helpful in debugging errors in non-circle ci environments (ie Team City).
=> chore(image): Add env to specify logging base64 screenshot error

packages/fxa-auth-server/.vscode/launch.json, packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js, packages/fxa-support-panel/lib/api.ts, packages/fxa-support-panel/lib/templates/index.html, packages/fxa-support-panel/test/lib/api.spec.ts
auth server:
- created simplified endpoint to return only the data needed for the support panel
- included past plan information from subscription metadata
support panel:
- added past plan information to subscription data displayed
Because:
- when we introduce the ability to upgrade/downgrade subscriptions, we want to ensure that our support team is aware of plan changes to allow for a better customer experience
fixes #5242
=> feat (support + auth server): add past product information to support panel

packages/fxa-admin-panel/src/components/EmailBlocks/Account/index.test.tsx, packages/fxa-admin-panel/src/components/EmailBlocks/Account/index.tsx, packages/fxa-admin-panel/src/components/EmailBlocks/index.test.tsx, packages/fxa-admin-panel/src/components/EmailBlocks/index.tsx
Closes #5284 
Real simple, we were just forgetting to include the `emailVerified` response property when looking up an account.
I also added some basic UI tests.
=> fix(settings): add missing emailVerified property to GQL query

packages/fxa-auth-server/lib/push.js
Because:
* The push logic was indiscriminately logging `sendPush.success` messages
even in cases where the send had actually failed.
This commit:
* Restricts these messages to only be logged when the send succeeds.
=> fix(metrics): Don't log `sendPush.success` message unless it actually succeeded.

packages/fxa-content-server/app/scripts/views/settings/change_password.jsx
adds https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password#Allowing_autocomplete
Which gives hints to password managers, like Firefox Lockwise, on where to enter the existing password, and where to suggest a new password.
---
also runs `npm run format` on the file, it appears to have been a while since the format task was last applied to the file.
https://github.com/mozilla/fxa/pull/5262/files?w=1 shows a clearer diff.
=> feat(fx-content-server): add autocomplete annotations to change password

packages/fxa-auth-server/lib/push.js, packages/fxa-auth-server/test/local/push.js
Looking at the [send tab metrics document](https://docs.google.com/document/d/1XxNHWuotwNpaOSzrdN3KPu0bFPe28SSxZZp4HNWezhM), I think it could be useful to figure out what's the split between push subscription missing and push subscription expired. I'm thinking of the "verified device" case where the push notification is "sent" before the new device had a chance to register the push callback. 
One thing we could also do is log the "reason" of the push (verified, command, etc) in the logs, wdyt?
=> Log push expired callbacks separately

packages/fxa-react/components/Survey/index.test.tsx, packages/fxa-react/components/Survey/index.tsx
Because:
- The message posted isn't always "submitted survey"
This commit:
- Sets a default of "survey complete"
- Accepts an argument for the message
Fixes #5309 (FXA-1881)
=> fix(surveys): update survey complete message check

packages/fxa-content-server/server/lib/amplitude.js, packages/fxa-content-server/tests/server/amplitude.js
Fixes #5290 
This PR logs the `fxa_connect_device - view` amplitude event. Currently this event will now be triggered when opening from FxA toolbar menu, signin and signup.
cc @irrationalagent @davismtl 
Content-server Amplitude logs (`./pm2 logs content | grep 'amplitudeEvent'`)
From toolbar menu connect another device
```
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_connect_device - view","time":1589815030251,"device_id":"208d6f103d084390853a46b453cfdd04","session_id":1589815029465,"app_version":"171.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync","connect_device_flow":"sms"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"bea421113027562fd4316ee8ae24236a30f5187e2eaa15e888b7ce5028aeee36","ua_browser":"Fi …
```
=> fix(metrics): Correctly log CAD view metrics when coming from signin/signup

packages/fxa-content-server/app/scripts/lib/experiment.js, packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/index.js, packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/qr-code-cad.js, packages/fxa-content-server/app/scripts/views/connect_another_device.js, packages/fxa-content-server/app/scripts/views/mixins/connect-another-device-mixin.js, packages/fxa-content-server/app/scripts/views/post_verify/cad_qr/scan_code.js, packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/index.js, packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/newsletter-sync.js, packages/fxa-content-server/app/tests/spec/views/connect_another_device.js, packages/fxa-content-server/tests/functional.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/post_verify/cad_qr.js
Fixes #5236 
This PR adds all the feature flag plumbing needed for the CAD to QR code experiment.
Steps to test are to `npm start` and then `npm start firefox` and then open the urls below
- Open http://localhost:3030/?service=sync&context=fx_desktop_v3&action=email&forceExperiment=qrCodeCad&forceExperimentGroup=control
- Open http://localhost:3030/?service=sync&context=fx_desktop_v3&action=email&forceExperiment=qrCodeCad&forceExperimentGroup=treatment-a
- Open http://localhost:3030/?service=sync&context=fx_desktop_v3&action=email&forceExperiment=qrCodeCad&forceExperimentGroup=treatment-b
This feature is setup to work with both existing and new users so the links above could be repeated for each case. I've added functional tests that exercise all of the paths above.
cc @irrationalagent …
=> feat(cad): Add feature flag for CAD via QR code

packages/fxa-auth-server/scripts/activate-new-signing-key.js, packages/fxa-auth-server/scripts/clean-up-old-ci-stripe-customers.js, packages/fxa-auth-server/scripts/delete-account.js, packages/fxa-auth-server/scripts/find-stripe-sync-issues.js, packages/fxa-auth-server/scripts/gen_keys.js, packages/fxa-auth-server/scripts/gen_vapid_keys.js, packages/fxa-auth-server/scripts/must-reset.js, packages/fxa-auth-server/scripts/oauth_gen_keys.js, packages/fxa-auth-server/scripts/populate-stripe-customer-cache.js, packages/fxa-auth-server/scripts/prepare-new-signing-key.js, packages/fxa-auth-server/scripts/retire-old-signing-key.js, packages/fxa-auth-server/scripts/sms/send.js, packages/fxa-auth-server/scripts/test-remote-quick.js, packages/fxa-auth-server/scripts/verification-reminders.js, packages/fxa-auth-server/scripts/write-emails-to-disk.js
Closes #5261
Independently executed Auth Server scripts (like `delete-account.js, the issue) that import the config, which was recently converted to TypeScript, no longer work because they're not using TS themselves.
So, I've gone ahead and updated the shebangs in these files to compile with ts-node (specifically [ts-node-script](https://www.npmjs.com/package/ts-node#shebang)). I did not modify any scripts that do not use the config.
Also, per the initial issue, I ran `delete-account.js` and it additionally fails because it can't find `../lib/subhub/client`. Sure enough, `lib/subhub` does not exist in the repo. Any ideas where this comes from?
=> fix(auth server): use ts-node-script shebang when executing ts-dependent scripts

.gitignore, _scripts/build-storybooks-indexes.js, _scripts/build-storybooks.sh, _scripts/gh-pages.sh, packages/fxa-payments-server/.storybook/components/MockApp.tsx, packages/fxa-payments-server/package.json, packages/fxa-react/components/Survey/index.scss
issue #4823
I've got this script building & deploying storybooks to one of my own gh-repos with some static index.html pages for navigation:
https://lmorchard.github.io/fxa-storybooks/
Still working on this, haven't gotten it hooked up to CI yet. But, maybe worth opening as a draft and a demo of what's working so far. Could be worth some early feedback on the general approach.
There are several commits worth of builds there. However, only the newest one probably works. I had to fix some path-related issues for locales in fxa-payments-server, and had trouble with stylesheet paths in fxa-related for the Survey component. Fixed now I think.
Also there's a pull request number mentioned. That's a fake number I passed in to simulate a CI build from PR
=> feat(storybook): build static gh-pages site from storybook builds

packages/fxa-content-server/app/scripts/templates/post_verify/cad_qr/ready_to_scan.mustache, packages/fxa-content-server/app/scripts/templates/post_verify/cad_qr/scan_code.mustache, packages/fxa-content-server/app/scripts/views/post_verify/cad_qr/connected.js, packages/fxa-content-server/app/scripts/views/post_verify/cad_qr/get_started.js, packages/fxa-content-server/app/scripts/views/post_verify/cad_qr/ready_to_scan.js, packages/fxa-content-server/app/scripts/views/post_verify/cad_qr/scan_code.js, packages/fxa-content-server/app/tests/spec/views/post_verify/cad_qr/connected.js, packages/fxa-content-server/app/tests/spec/views/post_verify/cad_qr/get_started.js, packages/fxa-content-server/app/tests/spec/views/post_verify/cad_qr/ready_to_scan.js, packages/fxa-content-server/app/tests/spec/views/post_verify/cad_qr/scan_code.js, packages/fxa-content-server/server/lib/amplitude.js, packages/fxa-shared/metrics/amplitude.js
Fixes #5240
This PR adds metrics defined in https://docs.google.com/document/d/1JfHd-zX47af-seUToS6fHSzpcTKG5l1WFiojGLUQYYE/edit#. If you scroll to `Metric definitions` section you can see what amplitude metrics are emitted for which pages.
```
fxa_qr_connect_device - get_started_view
fxa_qr_connect_device - get_started_later
fxa_qr_connect_device - get_started_submit
fxa_qr_connect_device - ready_to_scan_view
fxa_qr_connect_device - ready_to_scan_use_sms
fxa_qr_connect_device - ready_to_scan_later
fxa_qr_connect_device - ready_to_scan_submit
fxa_qr_connect_device - scan_code_view
fxa_qr_connect_device - scan_code_device_connected
fxa_qr_connect_device - connected_view
fxa_qr_connect_device - connected_connect_another
fxa_qr_connect_device - connected_use_sms
fxa_qr_connect_device - …
```
=> feat(cad): Add metrics for the CAD via QR code

packages/fxa-profile-server/docs/API.md, packages/fxa-profile-server/lib/routes/_core_profile.js, packages/fxa-profile-server/lib/routes/ecosystem_anon_id/get.js, packages/fxa-profile-server/lib/routes/ecosystem_anon_id/post.js, packages/fxa-profile-server/lib/routes/profile.js, packages/fxa-profile-server/lib/routing.js, packages/fxa-profile-server/test/api.js
Starting off the AET work with an API that will need to agree with changes that ride the trains into desktop. This ecosystem_anon_id field isn't yet persisted in the core profile fields in the auth DB, that's a different bug. Not 100% sure I'm logging correctly. Still need to add tests to api.js.
=> feat(profile): Add API endpoints for ecosystem_anon_id

packages/fxa-graphql-api/package-lock.json, packages/fxa-graphql-api/package.json, packages/fxa-graphql-api/src/lib/datasources/authServer.ts, packages/fxa-graphql-api/src/lib/resolvers/account-resolver.ts, packages/fxa-graphql-api/src/lib/resolvers/types/account.ts, packages/fxa-graphql-api/src/lib/resolvers/types/attachedClient.ts, packages/fxa-graphql-api/src/lib/resolvers/types/location.ts, packages/fxa-graphql-api/src/lib/resolvers/types/subscription.ts, packages/fxa-graphql-api/src/lib/resolvers/types/totp.ts, packages/fxa-graphql-api/src/lib/server.ts, packages/fxa-graphql-api/src/test/lib/datasources/authServer.spec.ts, packages/fxa-graphql-api/src/test/lib/mocks.ts, packages/fxa-graphql-api/src/test/lib/resolvers/account-resolver.spec.ts, packages/fxa-graphql-api/src/test/lib/schema.spec.ts, packages/fxa-graphql-api/types/fxa-js-client/index.d.ts
Because:
* We want to show a users attached clients and security settings.
This commit:
* Retrieves the requested graph fields from the auth-server and
resolves them.
Closes #5230
=> feat(graphql-api): implement security/devices resolvers

CONTRIBUTING.md
Because:
* We want to have uniform commit message that describe why the commit
is being made.
This commit:
* Includes a git message template with the agreed upon format for our
commits.
=> chore: update contributing for git template

_scripts/base-docker.sh, packages/fxa-admin-server/tsconfig.json, packages/fxa-auth-server/tsconfig.json, packages/fxa-graphql-api/tsconfig.json, packages/fxa-metrics-processor/tsconfig.json
since `@types` can be lifted to the top-level now
and jest and mocha have competing definitions
we need to specify the "types" config to use
the correct one.
=> fix(docker): need to specify types in some tsconfigs

.circleci/config.yml, packages/fxa-auth-server/package.json, packages/fxa-auth-server/scripts/clean-up-old-ci-stripe-customers.js
fixes #5326
So I *thought* there weren't going to be any code changes for this. Looks like there probably should be a few.
Also, rather than run this on a schedule, it seemed maybe easier to just tack it on after content-server functional tests. The script deletes customers with an email pattern of 'signin.*@restmail.net' that are over a day old. That should only cover testing customers and leave them around for a little while in case we have to peek at them after failed tests. Running this after each batch of functional tests should be pretty quick.
=> chore(tests): clean up old Stripe customers after functional tests

packages/fxa-content-server/app/scripts/models/support-form.js
Because:
- The 'Getting Started' option was supposed to be removed as a part of the initial request from the support team
This commit:
- Remove 'Getting Started' from the topic options
close #5302
=> bug (content-server): remove 'Getting Started' from support form

packages/fxa-content-server/app/scripts/lib/experiment.js, packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/index.js, packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/newsletter-cad-chooser.js, packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/newsletter-sync.js, packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/qr-code-cad.js, packages/fxa-content-server/app/scripts/views/index.js, packages/fxa-content-server/app/scripts/views/mixins/newsletter-sync-experiment-mixin.js, packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/index.js, packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/newsletter-sync.js, packages/fxa-content-server/app/tests/test_start.js
Fixes #5390 
Connects #5249 
Some notes
* Adds newsletter sync experiment plumbing (does not enable yet)
* Updated to only be enabled for `en` based users
* Enables the CAD via QR experiment
* Test emails (softvision/mozilla) always get QR experience
* User can only be in one of those experiments
Once ready, I'll tag a point release on 172 cc @jackiemunroe
=> feat(experiments): Add mutally exclusive experiment logic for CAD QR and newsletters

packages/fxa-auth-server/scripts/delete-account.js
fixes #5261
I guess prettier also really wanted a whack at parentheses & spaces in this file.
=> fix(auth-server): remove subhub references from delete-account script

packages/fxa-content-server/app/scripts/views/support.js
Because:
* the support form success message is missing the product value
This commit:
* fix the message creation function to reference the correct form value
* remove the 'FxA - ' prefix that is added for Zendesk Agents, to match mockups and to show users the value they selected accurately
fixes #5298
=> bug (content server): fix support form success message

packages/fxa-payments-server/pm2.config.js
This one took me awhile to figure out - my secrets.json with a custom Stripe API was never getting used. Turns out PM2 had the wrong path.
Someday, we should probably move payments-server config out of server/config and to just config at the root of the package
=> fix(payments-server): correct location for secrets.json alongside config

_scripts/git-checkout-hook.sh, _scripts/git-merge-hook.sh, package.json
Submitting this as a proposal... It adds a tiny bit of lag when doing a `git checkout` but I've found it useful on other projects. Now that there's only one file to diff it seems worth adding.
It's easy to not notice when to run a `yarn install` either
when switching branches or doing a git pull. This adds a
hook to diff your previous yarn.lock with the one you're changing
to, and if there's changes running 'yarn install' for you.
=> feat(dev): added post-checkout git hook to keep deps in sync

packages/fxa-profile-server/lib/routes/profile.js
At the higher logging level it fills up our production logs.  At a
lower level it will still show up for debugging.
supersedes #5402
=> refactor(logging): reduce profile cache logging from info to verbose

packages/fxa-react/components/Portal/index.test.tsx, packages/fxa-react/components/Portal/index.tsx, packages/fxa-react/lib/hooks.test.tsx, packages/fxa-settings/package.json, packages/fxa-settings/src/components/Modal/index.test.tsx, packages/fxa-settings/src/components/Modal/index.tsx, packages/fxa-settings/src/components/Settings/index.tsx, packages/fxa-settings/src/components/UnitRow/index.tsx, packages/fxa-settings/src/lib/hooks.test.tsx, packages/fxa-settings/src/lib/hooks.tsx
This commit:
* Allows the Modal component to close on escape key press
* Shifts focus back to the element that opened the modal when closed
* Disallows interaction with root element when modal is opened via aria-hidden, pointer events, and scroll prevention
* Adds `aria-labelledby`, `aria-describedby`, and `role='dialog'` properties
* Adds a tab fence so screenreaders are directed to the modal after opening
Because:
The current modal component needed some accessibility improvements.
Fixes #5016
This also makes `onDismiss` for `Modal` required because all of the modals in settings have a cancel/X button. I'll be opening an issue for us to backlog to better consolidate `DialogMessage` from payments with some of these updates, in the meantime I went with a check on `id` in the shared Portal …
=> feat(a11y settings): Improve modal a11y

packages/fxa-auth-server/lib/oauth/token.js
This log message isn't really useful these days, so lower it to trace logging.
=> fix(oauth): quiet logging on >24 hour tokens

packages/fxa-auth-server/lib/routes/account.js, packages/fxa-profile-server/lib/routes/ecosystem_anon_id/get.js, packages/fxa-profile-server/test/api.js
The ecosystem_anon_id work for AET (Jira epic FXA-880) started from the
API used by desktop code, in order to unblock that work, which can be
done in parallel. This new identifier is eventually going to be part
of the core profile fields stored in the auth server DB, which means
there will be changes in mysql, auth-db, auth-server, and profile-server.
The initial no-op profile-server API implementation landed as
https://github.com/mozilla/fxa/pull/5364.
This change moves one step further down the stack, updating the
profile-server API handler from a no-op to an actual call into the
_core_profile, and adding a deceptively simple change to the auth server
that allows an ecosystemAnonId field to be passed through from auth-db.
Future commits will integrate this new field into the auth-db and …
=> feat(aet): add ecosystem_anon_id field to auth server core profile data

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/newsletter-sync.js
Fixes #5249 
Basket code to support this has landed in production, it is safe to enable this now.
=> feat(experiments): Enable newsletter sync experiment

packages/fxa-content-server/tests/teamcity/run-server.sh
For reasons I don't know, the `tsc --build` was not happening for fxa-shared. I tried a couple of things, and this is what works. There's probably a better way to achieve this but WFM.
=> fix(tests): run-server npx yarn and then fxa-shared tsc --build

packages/fxa-auth-server/lib/push.js, packages/fxa-auth-server/test/local/push.js
Connects to https://github.com/mozilla/application-services/pull/3177#issuecomment-635738358.
I've removed the UA-related special handling because it is not reliable anymore, as the iOS UA [is now static](https://searchfox.org/mozilla-mobile/rev/d3a620b6a311422ec13de0345ee3bdeb78e6f837/application-services/components/support/viaduct-reqwest/src/lib.rs#24-31).
=> Filter out collection_changed commands for iOS

packages/fxa-shared/metrics/amplitude-event.1.schema.json, packages/fxa-shared/metrics/amplitude.js, packages/fxa-shared/test/metrics/amplitude.js
fixes #5070
Soaked my head in metrics & amplitude things for a day or two. Got very turned around. But, this seems to be what the issue is asking for?
Am I under-thinking this? Do we need to add this `settings_version` property to a schema or config somewhere in Amplitude?
=> feat(settings-redesign): add settings_version event property for fxa_pref amplitude events

.circleci/config.yml, package.json, packages/fxa-auth-server/scripts/test-local.sh, packages/fxa-auth-server/test/local/routes/devices-and-sessions.js
with hoisted eslint dependency `npm run lint` can't find
eslint on the path. We've got linting globally as a precommit
hook, it doesn't need to run on tests.
=> fix(auth): fixed test-local.sh in fxa-auth-server

packages/fxa-auth-server/lib/push.js, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/test/e2e/push_tests.js, packages/fxa-auth-server/test/local/push.js, packages/fxa-auth-server/test/remote/push_db_tests.js
Because:
- Robust delivery of push messages to connected devices is an
important part of "send tab" and other account-related experiences.
- It's hard to monitor or alert on changes to push delivery success
rate.
This commit:
- Emits "attempt", "success" and "failure" counters to statsd,
where they can be graphed and monitored more easily.
- Lightly refactors and adds additional metadata to push-related
logs that go into bigquery, based on experience from recent
ad-hoc log exploration.
Fixes #5367.
(To review this, please [ignore identation changes](https://github.com/mozilla/fxa/pull/5462/files?w=1))
=> feat(metrics): Emit statsd metrics around push message sending.

.gitignore, _scripts/pm2-all.sh, packages/fxa-content-server/app/scripts/views/survey.jsx, packages/fxa-content-server/package.json, packages/fxa-content-server/tsconfig.json, packages/fxa-content-server/webpack.config.js, packages/fxa-react/components/Survey/README.md, packages/fxa-react/package.json, packages/fxa-react/tsconfig.json, yarn.lock
`@fxa-react` is no longer used. content-server should reference
fxa-react through a workspace dependency.
This commit fixes references and build configs for this change.
=> fix(content-server): fixed content-server build

packages/fxa-payments-server/public/locales/en-US/main.ftl
Because:
* Groups include all group comments for all the strings which makes
these spammy
This commit:
* Splits groups out
=> refactor: clean up the fluent file

packages/fxa-react/components/Survey/index.scss, packages/fxa-react/package.json, yarn.lock
Closes #5439 
In case ya wanna reference: https://github.com/FirefoxUX/photon-colors/blob/master/photon-colors.css
=> refactor(fxa-react): replace imported fxa-content-server scss variables, remove dependency

packages/fxa-content-server/server/config/surveys.json
Because:
- should show the survey on reset password page
This commit:
- update a survey's "view" config value
Fixes #5524 (FXA-2018)
=> chore(surveys): update test survey view config to reset-password

packages/fxa-shared/l10n/supportedLanguages.json
Because:
* Some languages aren't enabled in Pontoon
This commit:
* Removes them
Related to #5523
=> refactor: update supported languages

packages/fxa-auth-server/lib/error.js, packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
fixes #5522
Assuming we want to allow downgrades, this should enable it on the server-side. UI changes to better depict a downgrade are pending for issue #5521 
Most of the changes here are renaming "upgrades" to "updates". The real change is just changing validation to accept less than or greater than for productOrder and testing both cases.
=> fix(payments): Allow subscription downgrades

packages/fxa-content-server/app/scripts/lib/survey-filter.js, packages/fxa-content-server/app/scripts/lib/survey-targeter.js, packages/fxa-content-server/app/tests/spec/lib/survey-filter.js, packages/fxa-content-server/app/tests/spec/lib/survey-targeter.js
Because:
- eagerly evaluating all the survey conditions can be costly and does
not work
This commit:
- evaluate the configured surveys for a view, and only that view, when
the view is being rendered
- cache model/state data at the filter function level so that they are
up to date per navigation but cached for evaluating multiple surveys
configured for the same view
- DRY up the filter code
Fixes #5387 (FXA-1938)
=> feat(surveys): evaluate survey conditions for the rendering view only

release.sh
Because:
* All our changelogs use dashes for bullets, and our release script generates using asterisks
This commit:
* Change dashes in release script changelog bullets to asterisks for consistency
=> chore(release): use dashes instead of asterisks in release script

packages/fxa-customs-server/lib/dataflow.js, packages/fxa-customs-server/lib/server.js, packages/fxa-customs-server/test/local/dataflow_tests.js
Since dataflow can only set one record at a time, update method to call `setRecord` instead of `setRecords`
This has a few breaking tests, fixing them up.
=> fix(customs): Call setRecord instead of setRecords in dataflow

packages/fxa-auth-server/test/local/senders/email.js
I don't really like doing this, but l10n may have diverged between 172 and current translations, making these tests fail.
=> fix(l10n): on train-172, temporarily disable two failing tests (ar & ru)

packages/fxa-graphql-api/src/lib/datasources/authServer.ts, packages/fxa-graphql-api/src/lib/resolvers/account-resolver.ts, packages/fxa-graphql-api/src/lib/resolvers/types/input/attached-client-disconnect.ts, packages/fxa-graphql-api/src/test/lib/resolvers/account-resolver.spec.ts, types/fxa-js-client/index.d.ts
Because:
* We want to allow gql-api clients to revoke attached clients.
This commit:
* Add's the attachedClientDisconnect mutation.
Closes #5398
=> feat(gql-api): add attached client revoke

packages/fxa-payments-server/src/lib/amplitude.ts, packages/fxa-payments-server/src/lib/apiClient.test.ts, packages/fxa-payments-server/src/lib/apiClient.ts, packages/fxa-shared/metrics/amplitude.js, packages/fxa-shared/test/metrics/amplitude.js
Because:
- we like to know the geo distribution of subscriptions in Amplitude
This commit:
- add the payment country code from a successful subscription to an
Amplitude event as an event property
Part of and closes #5454 (closes FXA-2023); follows PR #5566
=> feat(metrics): add subscription payment source country to Amplitude events

packages/fxa-graphql-api/src/lib/datasources/authServer.ts, packages/fxa-graphql-api/src/lib/resolvers/account-resolver.ts, packages/fxa-graphql-api/src/lib/resolvers/types/input/change-recovery-codes.ts, packages/fxa-graphql-api/src/lib/resolvers/types/input/create-totp.ts, packages/fxa-graphql-api/src/lib/resolvers/types/input/delete-totp.ts, packages/fxa-graphql-api/src/lib/resolvers/types/input/index.ts, packages/fxa-graphql-api/src/lib/resolvers/types/input/metrics-context.ts, packages/fxa-graphql-api/src/lib/resolvers/types/input/verify-totp.ts, packages/fxa-graphql-api/src/lib/resolvers/types/payload/change-recovery-codes.ts, packages/fxa-graphql-api/src/lib/resolvers/types/payload/create-totp.ts, packages/fxa-graphql-api/src/lib/resolvers/types/payload/index.ts, packages/fxa-graphql-api/src/lib/resolvers/types/payload/verify-totp.ts, packages/fxa-graphql-api/src/test/lib/resolvers/account-resolver.spec.ts, types/fxa-js-client/index.d.ts
Because:
* The gql-api needs the ability to issue new recovery codes and
update the users two-factor auth settings.
This commit:
* Add's two-factor auth and recovery code mutations.
Closes #5395
=> feat(gql-api): Add totp/recovery code mutations.

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/newsletter-cad-chooser.js, packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/newsletter-sync.js, packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/qr-code-cad.js
This was supposed to go onto train-173, targeting train-174 instead. Updated to enable QR CAD and disable sync experiment.
=> fix(experiments): Enabled QR cad, disable newsletters experiment

packages/fxa-settings/README.md
Because:
* The settings redesign project has introduced Tailwind into FxA and
some standards have been set. We need a 'getting started' guide.
This commit:
* Adds to the fxa-settings README.
fixes #5552
=> chore(docs): Update fxa-settings README with Tailwind + shared component details

packages/fxa-admin-panel/src/components/EmailBlocks/index.scss, packages/fxa-admin-panel/src/styles/_variables.scss
Not sure what changed, but this hurt my eyes when I was working on restyling the footer now shared with new settings/admin panel.
before:
after:
=> fix(admin-panel): Adjust input height

.git-blame-ignore-revs, packages/fxa-auth-server/lib/push.js, packages/fxa-auth-server/test/local/push.js
Because:
* A few small changes that I want to make in a push-related PR (#5546)
are being swamped by a bunch of automated reformatting on commit.
* It's hard to have a discussion about said changes in a PR that's
almost entirely formatting changes.
This commit:
* Applies said formatting changes separately.
I assume that it's expected that we now apply formatting changes on commit, and this isn't just something funky in my local setup...but if it's not expected please let me know and I'll dig deeper. I think maybe it was an in-flight collision between some recent refactoring I was doing in these routes that meant these didn't get refactored as part of #5431.
=> chore(formatting): Apply automated formatting to push-related code.

.circleci/base-install.sh, packages/fxa-auth-db-mysql/db-server/test/backend/db_tests.js, packages/fxa-auth-db-mysql/lib/db/mysql.js, packages/fxa-auth-db-mysql/lib/db/patch.js, packages/fxa-auth-db-mysql/lib/db/schema/patch-109-110.sql, packages/fxa-auth-db-mysql/lib/db/schema/patch-110-109.sql, packages/fxa-auth-server/lib/routes/account.js, packages/fxa-auth-server/test/local/routes/account.js
When a password change is required the lockedAt flag is set, currently by an external script. Until the password is changed all sessions for such an account must be verified. The 'password-change' verificationReason is returned in the response to tell the frontend to show the change password ui. The resetAccount db procedure resets the lockedAt value to null when the password is changed.
=> feat(auth): handle a password change requirement in login

packages/fxa-react/configs/tailwind.js, packages/fxa-settings/src/components/AlertBar/index.stories.tsx, packages/fxa-settings/src/components/AlertBar/index.test.tsx, packages/fxa-settings/src/components/AlertBar/index.tsx, packages/fxa-settings/src/components/AppLayout/index.tsx, packages/fxa-settings/src/components/Modal/index.test.tsx, packages/fxa-settings/src/components/Modal/index.tsx, packages/fxa-settings/src/components/Settings/index.tsx, packages/fxa-settings/src/lib/hooks.test.tsx, packages/fxa-settings/src/lib/hooks.tsx
Because:
* The new Settings page needs an alert-style bar to display messages to users.
This commit:
* Creates an AlertBar component in fxa-settings and places it in the correct DOM location
* Moves shared hooks with Modal into hooks.tsx
* Adds titles to AlertBar/Modal close buttons per content strategy request
* Removes 'transition:desktop' class in AppLayout because it canceled out position:fixed Nav functionality
fixes #4929
--
Known issues which I will create a follow up for, these will be fine to do after new Settings is in beta:
* If you reveal the alert bar then activate a modal, `esc` keypress will hide the modal _and_ alert bar when it should just hide the modal.
* If you reveal the alert bar the same time you close the modal (this is what I've done with this PR), focus is …
=> feat(settings): Add AlertBar

packages/fxa-auth-server/lib/routes/devices-and-sessions.js, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/test/local/routes/devices-and-sessions.js
@eoger I spent a big of time trying to get #5652 working using the `oauthdb` absatraction, but it ended up getting out of hand. Then I noticed that some newer routes were just directly importing `./oauth/db` and using that, and doing similarly here makes things much easier.
=> fix(devices): List refresh tokens by direct db access, not internal request routing

packages/fxa-content-server/app/scripts/lib/auth/utils.ts
because ancient webviews on android are ancient
=> fix(content): stop using padStart

.github/.codecov.yaml
Lets disable the requirement for codecov to pass ci, not all projects run on every ci build so overall fxa project coverage can vary.
=> fix(coverage): disable codecov requirement for passing ci

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/qr-code-cad.js
Fixes #5476 maybe?
This removes the `newsletterCadChooser` check that should have in theory made the qr code and newsletter experiment exclusive. Since we are not running the newsletter experiment yet, it is probably safe to remove the check to see if it was interfering with the qr code experiment.
=> fix(experiment): Fix attempt for qr code cad enrollment

_scripts/build-storybooks.sh
Because:
* We'd like to have a history of storybook builds for a pull request
This commit:
* Changes the target URL for the storybook status check to point at the specific commit for the build, rather than the pull request index.
The original issue that I filed asserted that we needed to rework the pull request static index pages. But, after some thought, I decided this was unnecessary:
* Github retains the status checks for every commit - i.e. the green "✔" or red "❌" next to a commit reveals the status checks when clicked.
* A pull request in Github lists the history of commits involved, even through force-pushes
* Changing the Storybook status check target URL to point at the per-commit build - rather than the overall PR - means that we can access previous Storybook builds for a PR by …
=> feat(storybooks): link to commit rather than pull request for status check target URL

packages/fxa-content-server/app/scripts/views/form.js, packages/fxa-content-server/app/tests/spec/views/form.js
fixes #5607
Because:
*  When the tooltip error was already displayed, the input wasn't marked as invalid.
This commit:
* Change the order in which the element is marked as invalid.
=> fix(content-server): mark the element as invalid.

packages/fxa-admin-server/src/lib/resolvers/account-resolver.ts
Because:
* We want to limit the permissions of the mysql user for the admin
panel to non-sensitive account columns.
This commit:
* Reduces the select from * to just the desired columns.
Fixes #5380
=> fix(admin-server): restrict account columns selected

packages/123done/pm2.config.js, packages/browserid-verifier/pm2.config.js, packages/fortress/pm2.config.js, packages/fxa-admin-panel/pm2.config.js, packages/fxa-admin-server/pm2.config.js, packages/fxa-auth-db-mysql/pm2.config.js, packages/fxa-auth-server/pm2.config.js, packages/fxa-content-server/pm2.config.js, packages/fxa-customs-server/pm2.config.js, packages/fxa-event-broker/pm2.config.js, packages/fxa-graphql-api/pm2.config.js, packages/fxa-payments-server/pm2.config.js, packages/fxa-profile-server/pm2.config.js, packages/fxa-react/pm2.config.js, packages/fxa-settings/pm2.config.js, packages/fxa-shared/pm2.config.js, packages/fxa-support-panel/pm2.config.js
Sometimes, when I'm debugging a service locally, I can't tell if the error logs are showing recent or older errors. To fix this, it would be handy to have pm2 log the current timestamp with each log line.
This change just adds `time: true` to each of the per-package pm2 server configs to insert the timestamp. It is a _full_ ISO timestamp, which does make the lines about 20 chars longer; this is a bit of an annoyance, but I think having the time is worth it, and everyone but me lives in VSCode anyway, which has very wide terminals by default.
You can try this out locally, but here's a snippet of `./pm2 logs` output that shows pretty clearly where the timestamps start getting inserted:
```
/Users/jh/.pm2/logs/payments-out.log last 15 lines:
32|payment | fxa-payments-server.server.main.INFO: …
```
=> chore(pm2): Add ISO timestamp to pm2 log lines

packages/fxa-payments-server/src/components/AppLayout/index.test.tsx, packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.tsx, packages/fxa-payments-server/src/components/TermsAndPrivacy/index.stories.tsx, packages/fxa-payments-server/src/components/TermsAndPrivacy/index.test.tsx, packages/fxa-payments-server/src/components/TermsAndPrivacy/index.tsx, packages/fxa-payments-server/src/lib/mock-data.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.stories.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx, packages/fxa-payments-server/src/store/types.tsx, packages/fxa-payments-server/src/store/utils.test.tsx, packages/fxa-payments-server/src/store/utils.tsx
- add support for new product metadata properties
- product:termsOfServiceURL
- product:termsOfServiceURL:{locale}
- product:privacyNoticeURL
- product:privacyNoticeURL:{locale}
- rework TermsAndPrivacy compoment to use localized product details as
source of terms & privacy link URLs
- refactor product details parsing to simplify & DRY up types
- updates to tests & stories
https://jira.mozilla.com/browse/FXA-2150
fixes #5711
=> feat(payments): Use Stripe metadata for terms & privacy URLs in payments-server

packages/fxa-auth-server/lib/payments/stripe.js
Because:
* Type checking tools can't see dynamic property assignments.
This commit:
* Individually attaches the properties in a way that type checking
can see.
=> fix(auth-server): use individual assignments

packages/fxa-payments-server/.storybook/components/MockApp.tsx, packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/src/components/PaymentForm/index.stories.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.tsx, packages/fxa-payments-server/src/lib/formats.ts, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
~Depends on first merging https://github.com/mozilla/fxa/pull/5723~ Merged
- replace `according to payment term` in all FTL strings with `according to <termsOfServiceLink>Terms of Service</termsOfServiceLink> and <privacyNoticeLink>Privacy Notice</privacyNoticeLink>`
- update message IDs from `payment-confirm-*` to `payment-confirm-with-legal-links-*`
- supply legal doc URLs to localized rendering of confirmation checkbox label from Stripe metadata product details
- enable storybook MockApp to accept a locale to exercise localized content
fixes #5584
=> feat(payments): Add legal doc links to payment confirmation checkbox label

packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/package.json, yarn.lock
Because:
* Our SCA and 3D Secure implementation will benefit from using the
latest Stripe API version.
* Keeping up on the API version reduces large breaking changes.
This commit:
* Updates our Stripe API version to 2020-03-02, which includes no
breaking changes.
Closes #5737
=> feat(auth-server): update stripe api version

.github/.codecov.yaml, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/cad-reminders.js, packages/fxa-auth-server/lib/redis.js, packages/fxa-auth-server/test/local/cad-reminders.js
- We need to be able to create, remove and process entries in redis this will allow us to know if a user has requested to be reminded later to connect another device
- Adds a library to do create, remove and processing of these reminders (based on account verification reminders)
Closes: #5702
=> feat(cad): Add remind me later CAD redis lib

packages/123done/static/js/123done.js
123Done in staging goes to the wrong plan
Adds an explicit plan parameter to the staging subscription URL
Closes: #5726
=> chore(subs): add plan to 123done

packages/fxa-payments-server/.gitignore, packages/fxa-payments-server/package.json, packages/fxa-payments-server/scripts/download_l10n.sh, packages/fxa-payments-server/server/lib/server.test.js, packages/fxa-payments-server/server/lib/version.js
Because:
- Payments need to serve the translated strings in .ftl files
This commit:
- add a postinstall script to copy the .ftl files from fxa-content-server-l10n
- update Payments' \_\_version__ to show the git hash of the l10n checkout
- git ignore the copied files
closes #5663 (FXA-2114)
closes #5664 (FXA-2115)
=> chore(l10n): copy .ftl files from fxa-content-server-l10n into payments

packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
We get the payment source country code from "charges" in the payment
intent of the latest invoice of a created subscription to include in an
Amplitude event.  However, it works most but not all of the time.
Occasionally "charges" is not in the object graph, according an error
captured by Sentry.
Because:
- "charges" is missing from the subscription object graph in the Stripe
resposne on some rare instances
This commit:
- check for the existence of "charges"
- log the subscription id of the subscription with the missing
"charges" to help with debugging in Stripe
Closes: #5740 (FXA-2169)
=> fix(payments): handle "charges" missing from the subscription object graph

packages/fxa-content-server/tests/functional/security_events.js
\*
This commit is to fix the Security_events.js file and 'delete security events' test. The test was failing at the assertion point as it wasn't able to validate the presence/absence of the selector. So I added the refresh() to reload the page and now the assertion passes and so does the test.
\*
Closes: #5443
@vbudhram  please review this PR.
=> fix(security-events):fix delete security events test by adding refresh function

packages/fxa-react/lib/hooks.stories.tsx, packages/fxa-react/lib/hooks.test.tsx, packages/fxa-react/lib/hooks.tsx, packages/fxa-react/package.json, yarn.lock
Because:
* I'd like to refactor payments-server to no longer use Redux to orchestrate API calls
This PR:
* Introduces a new useAwait hook for managing promise-based API calls closer to the component using the APIs.
issue #5683
=> feat(react): introduce useAwait hook

packages/fxa-auth-server/lib/metrics/amplitude.js, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/lib/senders/templates/_versions.json, packages/fxa-auth-server/lib/senders/templates/cadReminderFirst.html, packages/fxa-auth-server/lib/senders/templates/cadReminderFirst.txt, packages/fxa-auth-server/lib/senders/templates/cadReminderSecond.html, packages/fxa-auth-server/lib/senders/templates/cadReminderSecond.txt, packages/fxa-auth-server/lib/senders/templates/partials/cadReminder.html, packages/fxa-auth-server/package.json, packages/fxa-auth-server/test/local/senders/email.js
This commit:
* Adds cadReminders and templates in email.js to create cadReminderFirstEmail and cadReminderSecondEmail for 'remind me later' functionality
* Fixes write-emails command
Because:
* Users should receive an email to remind them to connect a device later if they opt-in.
fixes #5705
--
=> feat(emails): Add CAD reminder templates

packages/fxa-payments-server/scripts/download_l10n.sh
Because:
- `cp` on BSD/macos does not have the --parents option
This commit:
- loop through the glob results and copy each .ftl file
This PR is not a part of any issue.
=> fix(scripts): use mkdir and cp in a loop to copy .ftl files

packages/fxa-auth-server/lib/routes/emails.js, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/test/local/routes/emails.js, packages/fxa-auth-server/test/mocks.js, packages/fxa-content-server/app/scripts/lib/auth/client.ts, packages/fxa-content-server/app/scripts/lib/fxa-client.js, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/templates/post_verify/cad_qr/get_started.mustache, packages/fxa-content-server/app/scripts/templates/post_verify/cad_qr/ready_to_scan.mustache, packages/fxa-content-server/app/scripts/views/post_verify/cad_qr/get_started.js, packages/fxa-content-server/app/scripts/views/post_verify/cad_qr/ready_to_scan.js, packages/fxa-content-server/app/tests/spec/lib/fxa-client.js, packages/fxa-content-server/app/tests/spec/views/post_verify/cad_qr/get_started.js, packages/fxa-content-server/app/tests/spec/views/post_verify/cad_qr/ready_to_scan.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/post_verify/cad_qr.js
* The CAD QR flow has two spots to "reminder me later" that need to actually do that
* We need an auth server endpoint to facilitate creating new CAD reminders for a user
* Sets up the auth server endpoint to talk to the CAD Reminders mechanism for creating new reminders
* Updates the content server JS client to talk to the auth server and create reminders
* Updates the template and view for the CAD QR flow to invoke the JS client that talks to the auth server
Closes: #5703 
Closes: #5704 
=> feat(auth + content): add endpoint and hook up CAD QR flow to trigger reminder

.github/.codecov.yaml
* Code coverage shows up as failing on commits
* Marks coverage as informational (always pass), devs can still check it out 
Closes: #5754
=> fix(cov): code cov will display coverage but always pass

packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/test/local/senders/email.js
It was pointed out [in this comment](https://github.com/mozilla/fxa/pull/5743#discussion_r445581368) that this is the incorrect usage of "how-to". Alex approved the copy change request.
=> fix(emails): Swap grammatically incorrect 'How-To' for 'How To'

packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.tsx
Because:
- we want to accept non-US payments
- Stripe should perform the validation
This commit:
- remove zip code validation that enforce length and numbers only
Closes: #5732 (FXA-2161)
=> chore(payments): remove zip code validation

packages/fxa-content-server/app/scripts/templates/settings/delete_account.mustache
This is [ready](https://github.com/mozilla/fxa/issues/5557#issuecomment-648865631) to be addressed. GitHub wouldn't let me re-open #4532 because I rebased, so here's a new one.
---
Closes #4467
No test changes as it's already covered [here](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/tests/spec/views/settings/delete_account.js#L531) and [here](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/tests/functional/delete_account.js).
=> feat(account deletion): add checkbox to deletion confirming that your developer extensions and themes will be deleted

packages/fxa-payments-server/scripts/download_l10n.sh
Because:
- language codes use hyphens but the directories for Payments' .ftl
files use underscores (e.g. pt-BR vs pt_BR)
This commit:
- change the underscore to a hyphen during the .ftl copying
Closes: #5765 (FXA-2182)
=> chore(l10n): match directory names to language codes

_dev/docker/node/Dockerfile
openssl was removed from the base node image
fixes #5669
=> fix(docker): added openssl to fxa-node docker image

packages/fxa-auth-server/config/index.ts
- The post-verify Sync URL points to production in emails sent on stage
- Sets the Sync URL in post-verify email to stage address when in stage env
Closes: #5614
=> fix(auth): use stage-specific sync url in post verify emails, when in stage

.circleci/base-install.sh, packages/fxa-profile-server/scripts/test-ci.sh, packages/fxa-shared/package.json
In dev we want to be able to go from a `yarn install` to
running code but we also want to keep typescript as a
devDependency for production builds where we have an
explicit build phase then --production install. To keep the
production install from failing on the postinstall we need
it to succeed even if tsc is missing, hence the `|| true`.
=> fix(build): added postinstall to fxa-shared

packages/fxa-content-server/grunttasks/l10n-extract.js
npx babel tries to install the latest package from npm
which is now deprecated in favor of @babel/cli. By using
`yarn babel` instead we use the correct babel cli command
installed via @babel/cli in package.json
=> fix(l10n): fixed l10n-extract script

packages/fxa-shared/l10n/supportedLanguages.json
Because:
- `locale/en_US/LC_MESSAGES` exists in the fxa-content-server-l10n repo
for content-server
- `public/locales/en-US/main.ftl` exists in fxa-payments-server
- Fluent will set a requested but not available locale as the last
fallback locale
This commit:
- add en-US to the shared list of supported locales
Closes: #5762 (FXA-2181)
=> chore(l10n): add en-US to shared list of supported locales

README.md
- Running `yarn test` doesn't run tests. 
- Add info about starting services before running tests.
=> docs(tests): add info about running services before running tests

packages/fxa-auth-server/test/local/mailer_locales.js, packages/fxa-content-server/tests/server/l10n.js
Because:
- adding en-US to the supported languages list cause some test failures
This:
- update en-US related l10n tests
The problem was introduce in the PR for #5762 (FXA-2181).
=> fix(tests): fix l10n fallback language tests

.circleci/config.yml
caching node_modules didn't really speed us up with npm but caching .yarn might improve our build time. let's see
=> feat(ci): cache .yarn in circleci

packages/fxa-auth-server/docs/metrics-events.md, packages/fxa-auth-server/lib/push.js, packages/fxa-auth-server/lib/routes/devices-and-sessions.js, packages/fxa-auth-server/test/local/push.js, packages/fxa-auth-server/test/local/routes/devices-and-sessions.js, packages/fxa-auth-server/test/mocks.js
The context for this is https://github.com/mozilla/application-services/issues/3197, and I wanted to push it early to make the proposal easier to discuss. In particular, @6a68, is this the sort of thing for which I should fill out an explicit data-review request?
~~Unfortunately some autocommit reformatter appears to be adding a bunch of noise to this PR, which I'll try to figure out tomorrow. The changes in `/lib/routes/devices-and-sessions.js` are the important bits.~~ (Formatting issues in this PR have now been resolved)
---
Because:
* We don't currently have good metrics on how many "send tab" attempts
are successfully received by the target device.
* Client-side telemetry for send-tab appears to be rather flaky.
* We can reliably observe tabs being sent and received from FxA server …
=> feat(devices): Emit events for a basic "device commands" delivery funnel.

packages/fxa-content-server/app/scripts/lib/experiment.js, packages/fxa-content-server/server/lib/amplitude.js, packages/fxa-content-server/tests/server/amplitude.js
* Our QR code experiment cohorting rules were not grouping users correctly
* QR code experiment had half the volume of users as SMS and non-sms groups
* Targeted against train-177 since this is metrics related
* Updates our flow events matching based on https://github.com/mozilla/fxa/issues/5628#issuecomment-649739353
* The previous rules were matching sign-in users only, the New Rules match sign-in/sign-up/direct flows
Closes: #5628
Raw logs
```
{"op":"amplitudeEvent","event_type":"fxa_email_first - view","time":1593462327561,"device_id":"7ccdf8fda46549f49a5137261dd5e305","session_id":1593462323017,"app_version":"177.0","language":"en-US","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fx …
```
=> fix(experiments): fix qr code experiment cohorting rules

.github/.codecov.yaml
* Commit status for overall project code coverage is non-nonsensical because it could be based on a commit that didn't necessarily run tests
* We still report `patch` which shows the coverage of the current PR on the tests that did run
* Disables the `project` commit status.
=> fix(coverage): only show code coveage for tests that run, not the entire project

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/routes/utils/signup.js, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/lib/senders/templates/_versions.json, packages/fxa-auth-server/lib/senders/templates/partials/appBadges.html, packages/fxa-auth-server/lib/senders/templates/postVerify.html, packages/fxa-auth-server/test/local/senders/email.js
Because:
* We want to include "connect on another desktop device" text with a link to download Firefox when users register with a tablet (which largely send desktop UA) or desktop.
This commit:
* Allows `onMobileDevice` to be passed into `message` as an option for the mailer and displays different copy for the link following the app store links.
* Replaces postVerify and appBadges images with CDN versions.
fixes #5553
=> feat(emails): Add onMobileDevice mailOption for post registration email

packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/src/components/PaymentForm/index.tsx, packages/fxa-payments-server/src/components/fields/index.test.tsx, packages/fxa-payments-server/src/components/fields/index.tsx
Fix an issue with the way we were concatenating error message labels in our payment form. Decided to keep the english fallback in the case that there is no translation in the user's language
Closes: #5719
TRANSLATED:
FALLBACK TO ENGLISH TRANSLATION:
=> task(payments-server): l10n msg 4 required fields

packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/package.json, yarn.lock
Because:
- Node's Intl.NumberFormat doesn't format currencies correctly prior to v13
This commit:
- polyfill Intl.NumberFormat if Node is < 13
Part of #FXA-2202
=> fix(l10n): polyfill Intl.NumberFormat for emails

packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/src/components/PaymentForm/index.stories.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
- Remove Terms of Service and Privacy Notice legal links from payment
update form when no specific plan is provided
- Add stories for PaymentForm to cover cases without confirmation
checkbox and without plan
- Also update sub-update-confirm-* l10n IDs to
sub-update-confirm-with-legal-* so changed strings are flagged new
fixes #5733
=> fix(payments): further l10n updates for payment update form

packages/fxa-auth-server/lib/routes/validators.js
Because:
* Objects from Stripe cached previously may be missing the plan_name
and the client doesn't use it at this time. It was added purely to
support e-mail requirements.
This commit:
* Removes plan_name from a required return attribute in the responses
that include plans.
=> fix(auth-server): remove plan_name requirement

packages/fxa-auth-server/config/dev.json, packages/fxa-auth-server/docs/metrics-events.md, packages/fxa-auth-server/lib/metrics/amplitude.js, packages/fxa-auth-server/lib/metrics/events.js, packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/test/local/metrics/amplitude.js, packages/fxa-auth-server/test/local/routes/oauth.js
Apologies in advance—the questions I have here probably will make this borderline incomprehensible to everyone except vladikoff and rfk. I will do my best to summarize.
Probably best to start with [this earlier comment](https://github.com/mozilla/fxa/issues/5143#issuecomment-648510736) for context on this issue other than these metrics-related changes.
This change adds a new amplitude event, `fxa_activity - oauth_access_token_created`, emitted by the auth server for the `oauth/token` API endpoint, which will contain the device info needed to restore sync cross-device metrics. I'm also including the grant type in the event, in case we need to slice that data further.
There is code in auth server (the [`request.app.devices` getter](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-s …
=> fix(metrics): Create a new oauth token created event that includes sync device data

packages/fxa-content-server/app/scripts/views/base.js, packages/fxa-content-server/app/scripts/views/mixins/settings-panel-mixin.js, packages/fxa-content-server/app/scripts/views/settings/account_recovery/confirm_password.js
* The doorhanger to save the password appeared on "cancel".
* The password input value was not cleaned before navigating.
* Clean the input before navigating to account recovery
fixes #606 
=> fix(content-server): clean the password input value.

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/luaScripts/schema.md, packages/fxa-auth-server/lib/luaScripts/setRefreshToken_1.lua, packages/fxa-auth-server/lib/oauth/db/index.js, packages/fxa-auth-server/lib/oauth/db/mysql/index.js, packages/fxa-auth-server/lib/oauth/db/redis.js, packages/fxa-auth-server/lib/oauth/db/refreshTokenMetadata.js, packages/fxa-auth-server/lib/oauth/routes/authorized-clients/list.js, packages/fxa-auth-server/lib/oauth/routes/destroy.js, packages/fxa-auth-server/lib/oauth/routes/token.js, packages/fxa-auth-server/lib/redis.js, packages/fxa-auth-server/test/local/redis.js, packages/fxa-auth-server/test/oauth/api.js, packages/fxa-auth-server/test/oauth/db/index.js
Because:
* The last-used-at timestamp on refresh tokens changes frequently,
and it's good UX to be able to present an accurate value for this
field.
* We're expecting a significant increase in the volume of clients
using refresh tokens.
* Writes to MySQL are expensive at scale.
This commit:
* Stores the last-used-at timestamp in redis, where writes are cheaper.
=> feat(oauth): Store refresh_token last-used-at timestamp in redis.

packages/fxa-auth-server/lib/routes/account.js, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/lib/routes/session.js, packages/fxa-auth-server/lib/routes/utils/signin.js, packages/fxa-auth-server/test/local/ip_profiling.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/local/routes/session.js, packages/fxa-auth-server/test/local/routes/utils/signin.js
* Users were getting the reminder emails even though they already logged into another device
* Deletes the reminders on a successful login or verifying a session
Closes: #5799
=> fix(reminders): only send reminders if the user has not logged into another device

packages/fxa-graphql-api/src/config.ts
Because:
* envPrefix wasn't properly specified for each key, different
db configs couldn't be used.
This commit:
* Uses envPrefix on all config vars that need it.
Closes #5862
=> fix(gql-api): use envPrefix correctly

packages/fxa-payments-server/package.json, yarn.lock
The Payments server Storybook isn't properly loading SVGs when built. This is due to a shared config trying to invoke a loader that doesn't exist in the Payments dependencies.  
Adds the `@svgr/webpack` dependency to fxa-payments-server.
Closes: #5753
=> feat(payments): add @svgr/webpack to storybook can properly compile svgs

packages/fxa-auth-server/lib/routes/attached-clients.js, packages/fxa-auth-server/test/local/routes/attached-clients.js
* OAuth refresh tokens live in a separate database from device records,
for hysterial raisins.
* We've observed at least one instance where the device record appears to
have a "dangling pointer" to a refresh token that no longer exists.
* We can't really do anything useful with a `refreshTokenId` that doesn't
correspond to an actual refresh token, apart from "ignore it" or
"delete it".
* Silently ignores dangling refreshTokenId references when listing
the clients attached to a user's account.
* Opts not to try to repair the device record, mostly because this
is easier and it seems harmless to ignore.
Closes: https://bugzilla.mozilla.org/show_bug.cgi?id=1647126
- ~~[ ] I have added necessary documentation (if appropriate).~~
=> fix(attached-clients): Ignore a device's refreshTokenId if it's not a live token

packages/fxa-react/components/Survey/index.tsx
Because:
* We want screenreaders to be able to access the survey.
This commit:
* Removes 'aria-hidden="true" from the survey container.
--
Pre-req to all the a11y survey work this sprint. Didn't make an issue for this because eh it'd block everything else and it's a 1 line change.
=> fix(surveys): Remove aria-hidden attribute from survey component

packages/fxa-auth-server/lib/routes/subscriptions.js
Because:
* Payment Method API POST should use payload for data, not the query.
This commit:
* Switches to payload validation.
=> fix(auth-server): payload validation for payment methods

packages/fxa-content-server/app/styles/modules/_survey.scss
We want to respect the accessibility system preference to reduce on-screen motion.
Disables the survey's vertical transition when the media query `prefers-reduced-motion` is present.
**Reviewer**: if you'd like to test this on macOS you can enable the preference under `System Preferences > Accessibility > Display > Reduce motion`; on iOS this is under `Settings > Accessibility > Motion > Reduce Motion`. I don't know about other operating systems. 🤷
Closes: #5843
=> feat(surveys): don't animate survey when prefers-reduced-motion is present

packages/fxa-content-server/app/scripts/lib/survey-filter.js, packages/fxa-content-server/app/tests/spec/lib/survey-filter.js
Surveys can be configured to check the user's current RP, but just against a single value. We'd like to be able to test against 1 or more RP IDs.
Permits you to use either a string or an array of strings when setting up the RP condition. For example:
```json
"conditions": {
"relier": "booya",
"relier": ["booya", "bonkers"],
},
```
And because a user can only have one current RP, the matching value will still always be returned as a single string.
Closes: #5642
=> feat(surveys): permit strings or arrays to be used in RP checks

packages/fxa-content-server/app/scripts/lib/survey-filter.js, packages/fxa-content-server/app/tests/spec/lib/survey-filter.js
Currently User Agent property checks (OS, browser, device) only accept single strings, and we'd like to be able to test against 1 or more values of a given property.
Permits you to use either a string or an array of strings when setting up User Agent property checks. For example:
```json
"conditions": {
"browser": "Firefox",
"browser": ["Firefox", "Chrome"],
"os": "Windows",
"os": ["Mac OS", "Windows", "Linux"],
"deviceType": "desktop",
"deviceType": ["desktop", "mobile"],
},
```
And because a user can only have one device type, OS, and browser, the matching value of a property will still always be returned as a single string.
Closes: #5641
=> feat(surveys): permit strings or arrays to be used in ua property checks

packages/fxa-content-server/app/scripts/lib/app-start.js, packages/fxa-content-server/app/scripts/lib/constants.js, packages/fxa-content-server/app/scripts/lib/survey-filter.js, packages/fxa-content-server/app/scripts/lib/survey-targeter.js, packages/fxa-content-server/app/tests/spec/lib/survey-filter.js
We want to be able to see surveys in development
Ensures a survey will always show up in development, regardless of when you last saw it or the rate for which it should be shown (including a rate of 0). Note that all other conditions must still be met. To aid in development the matched conditions will also be console table-logged.
Closes: #5529, though the requirements changed to [this](https://github.com/mozilla/fxa/issues/5529#issuecomment-653156870).
=> feat(surveys): always show surveys in dev, regardless of rate or last shown timestamp

packages/fxa-content-server/app/scripts/lib/app-start.js, packages/fxa-content-server/app/scripts/lib/constants.js, packages/fxa-content-server/app/scripts/lib/survey-filter.js, packages/fxa-content-server/app/scripts/lib/survey-targeter.js, packages/fxa-content-server/app/scripts/lib/url.js, packages/fxa-content-server/app/styles/modules/_survey.scss, packages/fxa-content-server/app/tests/spec/lib/survey-filter.js, packages/fxa-content-server/app/tests/spec/lib/survey-targeter.js, packages/fxa-content-server/app/tests/spec/lib/url.js
We currently check the configured conditions during the filtering phase to determine eligibility, but we don't surface the matched values.
Extract user value based on satisfied conditions and passes them along as query params to Survey Gizmo.
- Originally we only passed along the values that satisfied the conditions, but per [this request](https://github.com/mozilla/fxa/issues/5640#issuecomment-653161604) this has changed to now pass along _all_ items of a given condition category belonging to the user. Some examples of this could be:
- If the browser locale is `en-CA,fr-CA,zh-TW` and the `language` condition is `['en', 'fr-CA', 'es']`, this would be passing and the returned value would be `en-CA,fr-CA,zh-TW` because either `en-CA` _or_ `fr-CA` could have satisfied the condition.
- If you …
=> feat(surveys): send matching conditions over to survey gizmo

packages/fxa-auth-server/docs/api.md, packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/test/local/payments/fixtures/setup_intent_new.json, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
Because:
* We want to use the SetupIntent API to update the default payment
method used for a customer.
This commit:
* Allows the client to create a SetupIntent API for a given customer
and set the payment method id (after confirming it) as the customer's
default payment method.
Closes #5744
=> feat(auth-server): add setup intent methods

packages/fxa-react/components/Survey/index.test.tsx, packages/fxa-react/components/Survey/index.tsx
* Without this fix, screenreaders hit the survey control button first without any context on what it is that they've just entered.
* Changes the 'section' tag to an 'aside', as a 'complimentary' element to the main content seems more applicable, and adds a generic survey aria-label to provide screenreaders with context because we can't easily use an aria-labelledby and aria-describedby due to SurveyGizmo's dynamic IDs that will change with every survey.
Closes: #5834
Changing 'section' to 'aside' does not change anything visually. The survey control piece of this issue is taken care of in #5871.
=> fix(surveys): Provide context to screenreaders when entering the survey

packages/fxa-auth-server/lib/push.js, packages/fxa-auth-server/lib/routes/devices-and-sessions.js, packages/fxa-auth-server/test/local/routes/devices-and-sessions.js, packages/fxa-auth-server/test/mocks.js
- When I added metrics to the /invoke_command route, I modified it
to return the metrics info to the client without really thinking
too hard about the implications.
- When we tried to deploy this in train-178, the result was response
validation errors in production.
- Adjusts the response schema for /invoke_command to accommodate the
new fields.
- Updates the device route tests to validate the response, in order
to help avoid similar oversights in future.
- Fixes a bunch of unrelated mock values in the device route tests
that do not pass validation.
Closes: #5886.
- ~~[ ] I have added necessary documentation (if appropriate).~~
This PR targets the `train-178` release branch, for a point-release.
=> fix(devices): Fix response validation for /invoke_command

packages/fxa-payments-server/src/routes/Product/index.test.tsx, packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ManagementPanel.tsx, packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx, packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx, packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx, packages/fxa-payments-server/src/routes/Subscriptions/index.tsx, packages/fxa-payments-server/src/store/sequences.test.ts, packages/fxa-payments-server/src/store/sequences.ts, packages/fxa-payments-server/src/store/state.ts, packages/fxa-payments-server/src/store/types.tsx
While working on #5745, I found an error on the subscription management page when the redis cache for customer data hasn't been refreshed.
Chased down that rabbit hole and discovered that we're not actually using that cached data on the subscription management UI. We're just throwing errors when it doesn't match up with fresh subscriptions listed in customer data.
Splitting this commit out of #5745, because a) it removes an HTTP fetch we do on every page load and b) it will solve an error whenever #5745 lands.
=> fix(payments): stop fetching unused cached subscription data on payments frontend

packages/fxa-content-server/app/scripts/templates/settings/delete_account.mustache
* When deleting an account, after all required inputs is completed, the "Save Password" is displayed.
* Create a fake input with "required" atribute to trick the browser into not showing the "Save Password" doorhanger.
* Remove autcomplete="off", this was added 5 years ago and now it does not hide the doorhanger to save the password.
fixes #932
=> fix(content-server): create fake hidden input

packages/fxa-auth-server/lib/routes/validators.js
Because:
* We throw errors if we have customers with no payment method on file.
This commit:
* Allows the customer endpoint to validate even without payment
information on file.
Closes #5898
=> fix(auth-server): allow customer to not have source on file

packages/fxa-auth-server/docs/oauth/jwt-access-tokens.md, packages/fxa-auth-server/lib/oauth/jwt.js, packages/fxa-auth-server/test/oauth/jwt.js
* The docs for JWT OAuth tokens tell RPs check for for "at+jwt".
* The actual code for JWT OAuth tokens uses a value of "at+JWT".
* The relevant RFC says this value should be compared case-insensitively,
and should be treated as if it has a magic "application/" prefix
prepended to it (ref https://tools.ietf.org/html/rfc7515#section-4.1.9).
* Rewords the docs on JWT OAuth tokens to clarify these requirements.
* Updates our own JWT-verification logic to implement them.
~~Closes: # (issue number)~~
~~It would have taken me longer to file the issue than to make this one-line PR...~~
OK sorry, turns out this was more than a one-line PR. But still, here we are...
- ~~[ ] If applicable, I have modified or added tests which pass locally.~~
- ~~[ ] I have added necessary documentation (if …
=> fix(docs): Clarify that JWT `typ` header is case-insensitive.

packages/fxa-content-server/app/scripts/templates/settings/avatar_camera.mustache, packages/fxa-content-server/app/scripts/views/mixins/disable-form-mixin.js, packages/fxa-content-server/app/tests/spec/views/mixins/disable-form-mixin.js
Because:
* The button was clickable
This commit:
* Make the "Take picture" button disabled when the error appears. And enable it when there's no error.
fixes #1472
=> fix(content-server): disable the "Take picture" button

packages/fxa-content-server/app/scripts/views/sign_in_password.js
Because:
* The password value is not cleaned before navigating.
This commit:
* Clean the password input before navigating.
fixes #2220
=> fix(content-server): clean the password input

packages/fxa-payments-server/src/components/PaymentFormV2/index.scss, packages/fxa-payments-server/src/components/PaymentFormV2/index.tsx, packages/fxa-payments-server/src/components/fields/index.tsx, packages/fxa-payments-server/src/index.scss, packages/fxa-payments-server/src/routes/Subscriptions/index.scss
We do not correctly handle adding styles to Stripe's card object
Resolves that issue by adding an options property to our StripeElement component. I've also made small adjustments to the layout of the input for the paymentsV2 form.
Closes: #5906
=> bug(styles): correctly pass styles into stripe card element

packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
Because:
- stubs in tests for async functions should return a promise
This commit:
- replace `returns` with `resolves` on stubs in StripeHelper and
subscriptions route tests
- fix a bug found during the test updates
Closes: #5897 (FXA-2253)
=> fix(tests): replace returns with resolves on stubs

packages/fxa-auth-db-mysql/README.md, packages/fxa-auth-db-mysql/db-server/index.js, packages/fxa-auth-db-mysql/db-server/test/backend/db_tests.js, packages/fxa-auth-db-mysql/db-server/test/backend/remote.js, packages/fxa-auth-db-mysql/db-server/test/fake.js, packages/fxa-auth-db-mysql/docs/API.md, packages/fxa-auth-db-mysql/docs/DB_API.md, packages/fxa-auth-db-mysql/lib/db/mysql.js, packages/fxa-auth-db-mysql/lib/db/patch.js, packages/fxa-auth-db-mysql/lib/db/schema/patch-110-111.sql, packages/fxa-auth-db-mysql/lib/db/schema/patch-111-110.sql, packages/fxa-auth-db-mysql/test/local/metrics_tests.js, packages/fxa-auth-db-mysql/test/local/mysql_tests.js, packages/fxa-auth-server/lib/routes/account.js
* Add ecosystemAnonId column to accounts table
* Update stored procedures that create or return an account to include
ecosystemAnonId
* Add stored procedure to update ecosystemAnonId for an account, given
the uid
* Update the authdb API to include ecosystemAnonId in endpoints that
create or return an account
* Add endpoint to authdb API to update ecosystemAnonId
* Add db API tests and update existing tests
* Remove references to deleted memory DB from README
I'm looking forward to ensuring the profile, auth, and auth-db API changes all line up correctly, but that seems like a separate issue from what's in issue #4321, so opening this separately.
This PR also closes part of #4322 (except for the historical anonid tracking)
=> feat(aet): Add ecosystemAnonId to auth-db and mysql

packages/fxa-content-server/app/scripts/lib/constants.js, packages/fxa-content-server/app/scripts/templates/pair/index.mustache, packages/fxa-content-server/app/scripts/views/marketing_snippet.js, packages/fxa-content-server/app/scripts/views/pair/index.js, packages/fxa-content-server/app/tests/spec/views/marketing_snippet.js, packages/fxa-content-server/app/tests/spec/views/pair/index.js, packages/fxa-content-server/tests/functional/connect_another_device.js, packages/fxa-content-server/tests/functional/send_sms.js
* The pairing page needs to have more than links to install Android
* Adds our marketing mixin which gives us App store badges for android and ios
Closes: #5883
=> fix(pair): Add marketings links (app badges) to pairing page

packages/fxa-auth-server/lib/routes/subscriptions.js
I had some downtime and saw [this](https://jira.mozilla.com/browse/FXA-2270) in Jira 🤷
- Some redundant auth-server subscription code was identified
- Removes it and nothing else
Closes: #5918
=> refactor(auth): remove redundant subscription code

packages/fxa-auth-server/test/oauth/key-management-scripts.js
The tests were exceeding the timeout. Type checking here isn't necessary.
=> fix(test): use ts-node in transpile only mode for script tests

packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/test/local/routes/validators.js, packages/fxa-payments-server/src/App.tsx, packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx, packages/fxa-payments-server/src/components/TermsAndPrivacy/index.stories.tsx, packages/fxa-payments-server/src/components/fields/index.tsx, packages/fxa-payments-server/src/lib/apiClient.ts, packages/fxa-payments-server/src/lib/errors.ts, packages/fxa-payments-server/src/lib/mock-data.tsx, packages/fxa-payments-server/src/lib/types.tsx, packages/fxa-payments-server/src/routes/Product/AcceptedCards/index.stories.tsx, packages/fxa-payments-server/src/routes/Product/index.test.tsx, packages/fxa-payments-server/src/routes/ProductV2/SubscriptionCreate/index.stories.tsx, packages/fxa-payments-server/src/routes/ProductV2/SubscriptionCreate/index.test.tsx, packages/fxa-payments-server/src/routes/ProductV2/SubscriptionCreate/index.tsx, packages/fxa-payments-server/src/routes/ProductV2/index.test.tsx, packages/fxa-payments-server/src/routes/ProductV2/index.tsx, packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
Starting a draft of this PR for issue #5745. Lots of work left to do, but worth starting to take a look at.
Following along with [Stripe's fixed-price subscription example](https://stripe.com/docs/billing/subscriptions/fixed-price), we need to handle a small flowchart of process here.
It's growing into a significant re-write of the product subscription page. And, some of what's here might end up useful to reuse for using the endpoints from #5744 in updating payment method.
=> In-progress reworking of product subscription page for new payment flows

packages/fxa-auth-server/bin/key_server.js, packages/fxa-customs-server/bin/customs_server.js
I want to run the services in standard Docker/Kubernetes environment.
Adds support for handling `SIGTERM` for services which currently do not react to such a signal.
Refs: #5921
=> Support SIGTERM for auth/customs server

packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
fixes #5873
Legal links are not included when `plan` is not supplied to `PaymentForm`. Only really needs to be passed in when we want a confirmation checkbox mentioning plan & price, which we don't do here.
Also turns out we weren't testing for the presence of these links in this context anyway.
=> fix(payments): remove legal links from footer of payment update form

packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/scripts/write-emails-to-disk.js, packages/fxa-auth-server/test/local/senders/email.js, packages/fxa-shared/subscriptions/metadata.ts, packages/fxa-shared/subscriptions/types.ts, packages/fxa-shared/test/subscriptions/metadata.ts
- add support for two new product metadata properties for legal PDF downloads
- product:termsOfServiceDownloadURL
- product:privacyNoticeDownloadURL
- switch emails to link to these download URLs rather than web pages
fixes #5875
=> feat(payments): Support new download URLs for legal links in emails

packages/fxa-auth-server/docs/api.md, packages/fxa-auth-server/lib/db.js, packages/fxa-auth-server/lib/error.js, packages/fxa-auth-server/lib/routes/account.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/mocks.js, packages/fxa-profile-server/docs/API.md, packages/fxa-profile-server/lib/error.js, packages/fxa-profile-server/lib/routes/ecosystem_anon_id/post.js, packages/fxa-profile-server/test/api.js
The Profile server can receive an updated ecosystem anon ID, but doesn't do much with it at the moment.
Makes the Profile server ping the Auth server when it receives a new anon ID, which in turn shoots it over to the Auth DB server.
Closes: #5909 
Closes: #4322
=> feat(profile+auth): pass anon id from profile to auth to db

packages/fxa-content-server/app/styles/modules/_settings-account-recovery.scss
Because:
* The buttons were overlapping.
This commit:
* Add a margin to the button.
Closes: #5659
=> fix(style): add margin to the 'account recovery' button

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/qr-code-cad.js, packages/fxa-content-server/app/scripts/views/connect_another_device.js, packages/fxa-content-server/app/tests/spec/views/connect_another_device.js
- We were showing users CAD in the sync optional flow even though they declined using sync
- In the sync optional flow, `syncPreference` is false, check this and redirect as needed
Closes: #5881
=> fix(cad): don't show CAD SMS if user declines sync in sync optional flow

packages/fxa-payments-server/src/lib/AppLocalizationProvider.tsx
For en locales that don't have their own ftl file this change
sets their FluentResource to be that of en-GB, which does have
an ftl file in order for the currency to be rendered as 'US$x.xx'
instead of the US fallback of '$x.xx' which is ambiguous in which
currency is meant.
These locales are currently hard coded in AppLocalizationProvider
because other services fail when they can't load l10n files that
are present in supportedLanguages.json but not in the l10n repo.
=> fix(l10n): fixed currency localization for "other than US" locales

packages/fxa-content-server/app/scripts/lib/auth-errors.js, packages/fxa-content-server/app/scripts/lib/constants.js, packages/fxa-content-server/app/scripts/views/settings/avatar_change.js, packages/fxa-content-server/app/tests/mocks/file-reader.js, packages/fxa-content-server/app/tests/spec/views/settings/avatar_change.js
Because:
* When the user uploaded a big image and an error message appeared, it was not possible to know the cause of the problem.
This commit:
* Create a limit size to uploaded images.
Closes: #5348, #5123
=> fix(content-server): create storage size limit to uploaded avatar image.

packages/fxa-auth-server/lib/payments/stripe.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/test/local/payments/fixtures/customer_new_pmi_default_invoice_expanded.json, packages/fxa-auth-server/test/local/routes/subscriptions.js
Because:
* We only looked at sources to return payment method before and
now we also handle payent methods as a default invoice option.
This commit:
* Looks to see if a payment method was attached as a default invoice
option and uses it for returned card data.
Closes #5902
I've also added expansion of this object to the cached customer object, even though its not needed at the moment so that they will match up as desired later.
=> feat(auth-server): use payment method on file for card

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/qr-code-cad.js
- We have gathered enough experiment data and don't need to keep running while we do the analysis
- Stops the qr code experiment
=> chore(cad): disable qr code experiment

packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/server/lib/routes/get-fxa-client-configuration.js, packages/fxa-content-server/tests/server/routes/get-fxa-client-configuration.js
* We need the public key from the profile server exposed to the content-server so that desktop clients can encrypt the ecosystem user ID to the ecosystem anon ID.
* Adds 'ecosystem_anon_id.keys_file' and 'ecosystem_anon_id.keys' to the content server config, checking for a path set in a new env var ECOSYSTEM_ANON_ID_KEYS_FILE and setting it to the .keys value, then exposes it in the .well-known/fxa-client-configuration bundle.
Closes: #5520 (oopsy on my branch name here)
* Defaults to an empty array when `ECOSYSTEM_ANON_ID_KEYS_FILE` env var isn't set
* Expects `ECOSYSTEM_ANON_ID_KEYS_FILE=file` to equal `config/[file]`. I had the thrown error in a check for `conf.get('env') !== 'development'` as well but removed it in case we want to set the env …
=> feat(AET): Add 'ecosystem_anon_id' field to content server config and expose keys in fxa-client-configuration

packages/fxa-admin-panel/server/lib/csp.test.ts, packages/fxa-admin-panel/server/lib/csp/blocking.ts, packages/fxa-admin-panel/server/lib/server.test.ts, packages/fxa-admin-panel/server/lib/server.ts
[Mozilla Observatory](https://observatory.mozilla.org/) identified two areas where security could be improved with the Admin Panel:
1. We don't set the [`form-action` CSP directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/form-action), which dictates which addresses can be used in `<form>` submissions.
2. We don't set the [`Referrer-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) header, which means it defaults to `no-referrer-when-downgrade`. 
1. Sets the `form-action` CSP directive to `'none'`. This could also be `'self'`, but because currently our only form's submission is handled by React there is no need for an `action`. In the future we may want to relax this. I left a note in the code.
2. Sets the …
=> feat(admin): set referrer-policy header, form-action csp directive

packages/fxa-admin-panel/src/components/EmailBlocks/Account/index.scss, packages/fxa-admin-panel/src/components/EmailBlocks/Account/index.test.tsx, packages/fxa-admin-panel/src/components/EmailBlocks/Account/index.tsx, packages/fxa-admin-panel/src/components/EmailBlocks/index.test.tsx, packages/fxa-admin-panel/src/components/EmailBlocks/index.tsx, packages/fxa-admin-server/src/lib/resolvers/account-resolver.ts, packages/fxa-admin-server/src/lib/resolvers/types/account.ts, packages/fxa-admin-server/src/lib/resolvers/types/emails.ts, packages/fxa-admin-server/src/test/lib/db/models/helpers.ts, packages/fxa-admin-server/src/test/lib/resolvers/account-resolver.spec.ts, packages/fxa-admin-server/src/test/lib/schema.spec.ts
Right now in the Admin Panel you can perform an Email Blocks query using an account's secondary email, and it will return the correct account, but only display the primary email. So you have little context as to why this account is being returned.
- Updates the Admin Server GraphQL query to resolve and return `emails`, an array of the account's emails, with `isPrimary` and `isVerified` properties (but keeps `email` and `emailVerified` top-level properties "just in case"). 
- Update the Admin Panel UI to reflect both primary and secondary emails, and highlights the email that matched your query.
**Notes for reviewer:**
- It looks like Prettify got its hands on some of these files, so the diff looks a little larger than it should 😢 
- Some of the markup/style changes are a little... bleh... …
=> feat(admin): support secondary emails and query highlighting

packages/fxa-content-server/tests/server/routes/get-fxa-client-configuration.js
* This test slipped through CI and is causing test failures on main.
* Updates a mock ecosystem_anon_id_keys from ecosystem_anon_id_keys to ecosystem_anon_id.keys
Closes: none
=> fix(tests): Fix broken get-fxa-client content-server test

packages/fxa-content-server/app/scripts/templates/settings/delete_account.mustache, packages/fxa-content-server/app/scripts/views/settings/delete_account.js, packages/fxa-content-server/app/tests/spec/views/settings/delete_account.js
* If users have multiple subscriptions of the same name they show multiple times.
* Creates a new Set of active subscription product names and displays this list rather than display all active subscriptions.
Closes: #5884
=> fix(delete account): Filter active subscriptions for unique product names

packages/fxa-profile-server/lib/config.js, packages/fxa-profile-server/lib/img-workers.js, packages/fxa-profile-server/test/api.js
HTTP headers are re-used as is from the original incoming request to the profile server when uploading an avatar to the worker service, it also includes headers that might confuse the environment the services are running in.
Most notably, the `Host` header is re-used and the `request` module does not rewrite that for the worker request.
Adds the following configuration keys:
* array `worker.headers_exclude` (env variable `WORKER_HEADERS_EXCLUDE`) for blocking headers from passing through to the worker request
* array `worker.headers_include` (env variable `WORKER_HEADERS_INCLUDE`) for passing only the specified headers to the worker request
Closes: #5874
Refs: #FXA-2240
The new default configuration removes the `Host` header by default, which is functionally not required but confuses some …
=> [fxa-profile-server] Add block-/allow-lists for passed-through HTTP headers

packages/fxa-auth-server/docs/metrics-events.md, packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/test/local/routes/oauth.js, packages/fxa-auth-server/test/mocks.js
- We want to add a unique anonymous identifier so we can get a correct count of Daily Active Users. More info https://jira.mozilla.com/browse/FXA-1885
- add the `ecosystemAnonId` to the `oauth.token.created` metrics ping.
Closes: #5313
=> feat(auth-server): add ecosystem anon id to oath.token.created metrics ping

packages/fxa-email-service/scripts/build-ci.sh, packages/fxa-email-service/scripts/hash-source.sh
We're building email-service on train tags more often
than we need to and doing so adds a good chunk of time to the
build process.
We've already got some logic in hash-source.sh to determine
when a build should happen. This change adjusts the criteria
to exclude the files that change when a tag is done even when
there's no meaningful changes.
=> chore(build): build fxa-email-service less often

packages/fxa-admin-server/src/lib/resolvers/account-resolver.ts
Because:
* MySQL decided to not use its index on email even though
that was where the join was taking place.
This commit:
* Uses a sub-query to retrieve the keys the hope that MySQL will manage
to use the index as desired.
Closes #5943
=> refactor(admin-server): use subquery for index use

packages/fxa-payments-server/src/components/DialogMessage/index.scss, packages/fxa-payments-server/src/components/PlanDetails/index.scss, packages/fxa-payments-server/src/components/PlanDetails/index.tsx, packages/fxa-payments-server/src/lib/mock-data.tsx, packages/fxa-payments-server/src/lib/test-utils.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx, packages/fxa-payments-server/src/routes/Product/index.stories.tsx, packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx, packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/SuccessDialog.tsx, packages/fxa-payments-server/src/store/types.tsx, packages/fxa-shared/subscriptions/metadata.ts, packages/fxa-shared/subscriptions/types.ts, packages/fxa-shared/test/fixtures/stripe/plan1_with_product.json, packages/fxa-shared/test/fixtures/stripe/price1.json, packages/fxa-shared/test/fixtures/stripe/price1_with_product.json, packages/fxa-shared/test/fixtures/stripe/product1.json, packages/fxa-shared/test/subscriptions/metadata.ts, packages/fxa-shared/test/subscriptions/stripe.ts
Icons for mozilla services will be white and will need different bg colors
makes bg color configurable as stripe metadata. Any valid CSS color value can be included in metadata (gradients, color names etc)
Closes: #5952
Notes:
* I may need to add a tests here, but could use a bit of help/direction if so
* I will add a PR for ecosystem docs to highlight the new metadata key once this lands
=> chore(styles): make subscription icon background configurable as metadata

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
Because:
- the API should allow subscription creation with a payment method
already on record for the customer
This commit:
- make the payment method id in the create subscription route optional
Closes: FXA-2288
=> feat(auth-server): create a subs w/out a payment method in req

packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/src/routes/Product/index.test.tsx, packages/fxa-payments-server/src/routes/ProductV2/SubscriptionCreate/index.stories.tsx, packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx
One more spot where the credit card is mentioned. Not an error, but the
message looks broken when the card is unavailable.
fixes #5901
=> fix(payments): hide mention of card in reactivate dialog when unavailable

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
Using the last invoice for the next amount due on reactivating a
cancelled subscription is incorrect. The upcoming invoice has the
correct prorated price. This switches to that.
fixes #5914
=> fix(payments): use upcoming invoice for subscription reactivation price

packages/fxa-content-server/app/scripts/lib/app-start.js, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/models/user.js, packages/fxa-content-server/app/tests/spec/models/account.js, packages/fxa-content-server/server/lib/routes/get-index.js, packages/fxa-content-server/tests/server/routes/get-index.js
* In the account model, we need to generate the ecosystem_anon_id with one of these keys plus the user's kB.
* Adds 'ecosystemAnonIdPublicKeys' to 'configForFrontEnd'
* Passes this value into the user model and then account model
Partial fix for #4320 but does not close.
Looks like we test for this value in the FE config in `get-index` but not in `app-start`, and also only testing values in `user.js` we're actually using there so I replicated those tests. The one in `models/account` doesn't show much but the assertion can happen when we work on tests for `generateEcosystemAnonIdIfRequired` in #5989.
=> feat(AET): Pass ecosystem anon ID public keys through account model and expose to client

packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-server/lib/routes/account.js, packages/fxa-content-server/app/scripts/lib/fxa-client.js, packages/fxa-content-server/app/tests/spec/lib/fxa-client.js
- We need to be able to send an updated EAI to the auth server
- Updates the fxa-js-client to also support this
- Updates the content server auth client to support this
- It delegates to the fxa-js-client
- Allows the EAI endpoint on the auth server to authenticate with a sessionToken
Reference: #5954 - which turned into this PR after discussion.
I'm not sure if we can close that issue from this. It sounded like we might not want to implement it just yet.
=> feat(auth-js + content): add updateEcosystemAnonId to auth clients

packages/fxa-content-server/app/scripts/views/settings/avatar_change.js, packages/fxa-content-server/app/scripts/views/settings/avatar_crop.js, packages/fxa-content-server/app/tests/spec/views/settings/avatar_change.js, packages/fxa-content-server/app/tests/spec/views/settings/avatar_crop.js
- #5941 introduced a bug where certain device photo uploads triggered a too-large error, when the file size is out of the user's control
- The cropper does a lot of work to reduce the size of the file that gets uploaded to the server
- Instead of validating the file size on photo selection, validate the output image generated by the cropper
Closes: #5976
**Why is this approach better?**
When you select an image for upload, or take an photo on your device camera, the image may be larger than the maximum-allowable file size set by the server. However, this is _not_ the image being submitted to the server. When you select the image and resize/crop it, it is processed in the client by our cropper and typically always yields a file size _much_ smaller than …
=> refactor(avatars): move file size validation to post-crop

packages/fxa-payments-server/server/config/index.js, packages/fxa-payments-server/server/lib/server.js, packages/fxa-payments-server/src/App.test.tsx, packages/fxa-payments-server/src/App.tsx, packages/fxa-payments-server/src/lib/AppContext.tsx, packages/fxa-payments-server/src/lib/test-utils.tsx
- support for FEATURE_USE_SCA_PAYMENT_UI_BY_DEFAULT=1 env var to select
SCA as default
- also adds support for /v1 and /v2 URL paths to select legacy or SCA
payment UI, respectively
- tests to exercise App router against paths with mock routes
fixes #5970
=> feat(payments): feature flag support to select SCA or legacy payment UI as default

packages/fxa-profile-server/lib/request.js
fixes #5691
We've got a lot of connection churn on profile-server. This is the minimal patch to attempt to fix it. Since 'request' is deprecated we should consider swapping it for something else in a future release.
=> fix(profile): set `forever: true` in request

packages/fxa-content-server/app/styles/modules/_settings-account-recovery.scss
Because:
* When highlighted the buttons were overlapping.
This commit:
* Add margin between the buttons from account recovery.
fixes #5986
=> fix(style): add margin between buttons from account recovery.

packages/fxa-content-server/app/scripts/views/mixins/signup-mixin.js, packages/fxa-content-server/app/tests/spec/views/mixins/signup-mixin.js
Because:
* The values were still present after confirming the signup.
This commit:
* Clean the inputs after confirming the signup.
fixes #643
=> fix(content-server): clean the input values before navigating to '/confirm_signup_code'

packages/fxa-auth-db-mysql/db-server/test/backend/db_tests.js, packages/fxa-auth-db-mysql/db-server/test/backend/remote.js, packages/fxa-auth-db-mysql/lib/db/mysql.js, packages/fxa-auth-db-mysql/lib/db/patch.js, packages/fxa-auth-db-mysql/lib/db/schema/patch-111-112.sql, packages/fxa-auth-db-mysql/lib/db/schema/patch-112-111.sql, packages/fxa-auth-db-mysql/test/local/mysql_tests.js
- MySQL doesn't use indexes on stored procedure queries if the collation of the field doesn't explicitly match that of the table.
- explicitly sets collation on email fields used to search the email table
- also removes the ecosystem_anon_id from the create account stored procedure, because in general we will never have that data at account creation time
Closes: #6006
=> fix(db): Set collation on stored procedure email fields

packages/fxa-content-server/app/scripts/lib/verification-reasons.ts, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/tests/spec/models/account.js, packages/fxa-content-server/server/lib/configuration.js
Paired on this with @LZoog 
- We need to have methods that can update and store the ecosystem anon id for a user
- On loading the settings page, fetches and stores the anon id from the auth-server
- Adds account model methods to generate and store ecosystemAnonId to localstorage and auth-server
- Can generate `ecosystemAnonId` either from kB, using authentication token that can retrieve keys, or using password and sessionReauth
Closes: https://github.com/mozilla/fxa/issues/4320
=> feat(aet): Add account model methods to generate and store anon id

packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/tests/spec/models/account.js
#6004 without the capability check on reliers 
fixes #4318 
cc/ @vbudhram 
Should be merged after #5989 (for `account.generateEcosystemId` method)
=> feat(fxa-content-server): AET adding calls to check and generate

packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-server/docs/api.md, packages/fxa-auth-server/lib/error.js, packages/fxa-auth-server/lib/routes/account.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-content-server/app/tests/spec/lib/fxa-client.js, packages/fxa-profile-server/docs/API.md, packages/fxa-profile-server/lib/config.js, packages/fxa-profile-server/lib/error.js, packages/fxa-profile-server/lib/routes/ecosystem_anon_id/post.js, packages/fxa-profile-server/test/api.js
- Services internal and external to FxA need to be able to set an the Ecosystem Anon ID under various circumstances, such as only if one isn't set, or if it matches a specific existing value
- Improves [`If-None-Match`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) and adds [`If-Match`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Match) header support across the Profile server, Auth Server, and Auth Client
For both implementations I tried to follow as close to spec as possible, which includes support for one or more specific values (comma-delimited), and `*` (If-None-Match only). Comparisons are made using an MD5 hashed version of the existing anon ID.
=> feat(aet): support for if-match and if-none-match across the board

packages/fxa-auth-server/lib/db.js, packages/fxa-auth-server/lib/routes/account.js, packages/fxa-auth-server/test/local/routes/account.js
- We need to support updating ecosystemAnonId with sessionToken
- sessionTokens are considered to contain all scopes
- Tested this against https://github.com/mozilla/fxa/pull/6020 and the ecosystemAnonId gets correctly set when user changes password
- Adds this support
- Some minor cleanup
Closes: #
=> fix(aet): Add support for updating ecosystemAnonId using sessionToken

packages/fxa-content-server/tests/functional/recovery_key.js
- These assertions are flaky and really don't test anything of value
- We have other supporting tests in https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/app/tests/spec/views/elements/recovery-key-input.js to test input.
- Removes the flake
=> fix(tests): Remove flaky recovery key assertion

packages/fxa-auth-server/config/dev.json, packages/fxa-content-server/server/config/local.json-dist
- I'm running Send locally again ;)
- Adds configs for a localhost install of Send
=> chore(oauth): add Firefox Send oauth client to local config

packages/fxa-auth-server/lib/senders/templates/subscriptionFirstInvoice.html, packages/fxa-auth-server/test/local/senders/email.js
Because:
- !s are bad for deliverability
This commit:
- remove the ! from the receipt email
Closes: #6001 (FXA-2324)
=> chore(emails): remove ! from sub receipt email

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/oauth/logging/index.ts, packages/fxa-auth-server/lib/oauth/metrics/amplitude.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/redis.js, packages/fxa-auth-server/lib/routes/account.js, packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/lib/routes/utils/subscriptions.js, packages/fxa-auth-server/package.json, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/local/routes/subscriptions.js, packages/fxa-auth-server/tsconfig.json, yarn.lock
Because:
* Using a library for caching provides a nicer UX with additional
capabilities to rolling our own.
* require() imports always resolve to any.
This commit:
* Uses type-cacheable for decorator based caching and clearing instead
of our DIY function.
* Switches config.ts to use imports for Config type-safety and updates
use of config for proper typing.
Closes #6000
This removes the logging assertions as the default strategy in type-cacheable does not log Redis failures. Our logging was never consulted, so it doesn't seem useful that we were logging before. If we do want to know when a Redis command fails, my recommendation for a future PR/issue would be to supply our own [default CacheStrategy](https://github.com/joshuaslate/type-cacheable/blob/mas …
=> refactor(auth-server): use type-cacheable for caching

packages/fxa-auth-server/lib/routes/subscriptions.js, packages/fxa-auth-server/test/local/routes/subscriptions.js, packages/fxa-payments-server/src/App.tsx, packages/fxa-payments-server/src/lib/apiClient.test.ts, packages/fxa-payments-server/src/lib/apiClient.ts, packages/fxa-payments-server/src/lib/mock-data.tsx, packages/fxa-payments-server/src/lib/test-utils.tsx, packages/fxa-payments-server/src/routes/ProductV2/SubscriptionCreate/index.test.tsx, packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateFormV2.test.tsx, packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateFormV2.tsx, packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx, packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx, packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx, packages/fxa-payments-server/src/routes/Subscriptions/index.tsx
Because:
* To support SCA we must migrate to using Stripe's SetupIntent API
This commit:
* Add call to auth server to create SetupIntent
* Use secret from SetupIntent result to confirm card prior to creating a subscription
Closes #5832
Co-authored-by: Jackie Munroe <jmunroe@mozilla.com>
Co-authored-by: Les Orchard <me@lmorchard.com>
=> feat(payments): use SetupIntent API for SCA payment update

packages/fxa-auth-server/test/local/senders/email.js
- Translation test broke
- Surprised the text changed because the equivalent English text didn't 🤷🏽‍♂️
- Uses new translation text in test.
Closes: NA
=> fix(emails): Fix translation test

packages/fxa-email-service/src/types/headers/mod.rs, packages/fxa-email-service/src/types/headers/test.rs
* Our email headers always contain ": " separating the name and value.
* We weren't accounting for these two extra characters when enforcing
the maximum length of a header line.
* Ensures that the header line length calculation includes the formatting
characters.
Closes: https://bugzilla.mozilla.org/show_bug.cgi?id=1655259
=> fix(emails): Account for formatting chars in max email header length.

packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/tests/spec/models/account.js
Per the issue:
> Using `sessionReauth` to get keys could potentially pose some issues if the user is attempting to come from an unverified session. FxA only allows fetching keys from sessions that are verified (ex. performed some email verification loop).
Checks that the flow's session is verified, and doesn't attempt to call `sessionReauth` if it's not, therefor not setting the anon ID at all in this flow
Additional comment from rfk:
> We should make our best effort to generate an anon_id, but not at the expense of RP user experience. Given that we have logic in AET clients to generate placeholder ids when the real one is missing, it doesn't seem too bad to leave the non_id empty in this case and just hope the user does a verified flow some time later to fill it in.
Closes: #6018
_Put an …
=> feat(aet): bail out of set with password if session unverified

packages/fxa-content-server/app/scripts/lib/verification-reasons.ts, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/tests/spec/models/account.js
- We don't want to use the keyfetch token the browser will use, it will throw a 401 and not start syncing
- If a password is specified in `generateEcosystemAnonID` use the password to reauth and attempt to get a new keyfetch token
- Updated change password to not pass a password, this will make it use the `this.canFetchKeys()` if branch if possible
Closes: https://github.com/mozilla/fxa/issues/6047
Targets train-181
=> fix(aet): On password reset, reauth to get new keyfetch token to set ecosystem id

packages/fxa-content-server/app/scripts/templates/settings/delete_account.mustache, packages/fxa-content-server/app/scripts/templates/settings/subscription.mustache, packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/src/App.test.tsx, packages/fxa-payments-server/src/components/AppLayout/index.tsx, packages/fxa-payments-server/src/routes/Subscriptions/index.tsx
Because:
- these mocks https://zpl.io/bAWMO9B
This commit:
- change "Subscriptions & Payments" to just "Subscriptions"
Closes: FXA-2318
=> chore(subscriptions): use just "Subscriptions"

dependabot.yml
* We want to keep our dependencies up to date
* Enables Github's Dependabot support
=> Enable dependabot

packages/fxa-payments-server/src/lib/AppLocalizationProvider.tsx
because they don't exist on the server, so create useless 404s
fixes #6048
=> fix(payments): filter "synthetic" locales out of the fetch list

packages/fxa-auth-client/server.ts
because it'll help server clients not waste tcp connections and dns lookups
=> feat(auth-client): set keepAlive on globalAgent

packages/fxa-auth-server/docs/api.md, packages/fxa-profile-server/lib/routes/ecosystem_anon_id/get.js, packages/fxa-profile-server/test/api.js
Fixes #5351
- We want to be sure we're logging eco_anon_id related behavior at each layer of the FxA service stack, to help understand usage and identify bugs.
- Adds a missing logger to the profile server `GET eco_anon_id` route
- Updates the auth-server API docs to be clear that `PUT /account/ecosystemAnonId` accepts a session token or an oauth token
Closes: #5351
=> bug(aet): Add logging to profile-server get anon_id route

packages/fxa-profile-server/lib/routes/ecosystem_anon_id/post.js, packages/fxa-profile-server/test/api.js, packages/fxa-profile-server/test/lib/mock.js
- We were GETing to the auth server '/account/ecosystemAnonId' endpoint, when it should be [PUTing](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/routes/account.js#L1494)
- Fixes that, adds test to assert call happens
Closes: #6031
=> fix(profile): aet call to auth server should be put, not get

packages/fxa-content-server/app/scripts/lib/auth-errors.js, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/tests/spec/models/account.js
- When generateEcosystemAnonId calls updateEcosystemAnonId it can fail with a 412 error, which means we tried to update the anon id but another client beat us to it. We need to handle this scenario.
- When updateEcosystemAnonId fails in this method, check if it's a 412 error, and retrieve the existing anon id from the auth server to store on the account instead
- If it’s not a 412 error, or if the profile query doesn’t yield an existing anon ID, just unset the value to avoid any confusion
Closes: #6017
=> feat(aet): handle generateEcosystemAnonId update failure

packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-client/package.json, packages/fxa-auth-client/server.ts, yarn.lock
because we want to be able to timeout requests on the server side as well
feat(auth-client): make auth-client request timeout configurable
because server timeouts should be lower than client ones
=> feat(auth-client): add abort-controller support to server env

package.json
Looks like we're not running payments-server tests when fxa-shared or fxa-react change, but payments-server uses those. This hopefully fixes that
=> fix(payments): add fxa-shared and fxa-react as CI dependencies for fxa-payments-server

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* We previously did not send an upgrade email if the prior subscription
had been cancelled.
This commit:
* Sends the upgrade email if the subscription is not cancelled and was
upgraded even if it was previously cancelled.
Closes #5987
=> feat(auth-server): send email on upgrade from cancelled

packages/fxa-admin-server/src/lib/resolvers/account-resolver.ts
Because:
* We don't want to give the admin server access to the emailCode field.
This commit:
* Restricts the select on emails to everything except the emailCode
field.
Closes #6064
=> fix(admin-server): restrict selected email columns

packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js, packages/fxa-content-server/app/scripts/views/pair/supp_allow.js, packages/fxa-content-server/app/tests/spec/views/pair/supp_allow.js, packages/fxa-content-server/server/lib/amplitude.js, packages/fxa-content-server/tests/server/amplitude.js
- We currently don't log any complete events when a user completes a login via pairing
- Adds the `fxa_login - complete` event when the user finishes the pairing flow
- Note that I was not able to add the `login_type` property to these events. I can do that part in a follow up.
Closes: #5990
The flow itself is a little hard to test. I ran `node tests/intern.js --suites=pairing` and made sure that content-server emitted the correct metrics
Output:
```
31|content  | 2020-07-29T23:39:03: fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_connect_device - view","time":1596080343378,"device_id":"9af7ee53c9a8496a9809909822adcdf8","session_id":1596080342818,"app_version":"181.2","language":"en-US","os_name":"Mac OS …
```
=> fix(metrics): Add fxa_login - complete for pairing login

_dev/tsconfig.browser.json, packages/fxa-content-server/app/scripts/app.js, packages/fxa-content-server/package.json, packages/fxa-content-server/webpack.config.js, yarn.lock
because the preset-env didn't transpile various spread (...) operations
this adds all the preset-env config required to transform for Edge. interestingly, setting the target version for edge is not enough to transform them properly and seems like a bug in the loader. with these transforms core-js is now a necessary import, and typescript browser target back to ES2016.
=> fix(edge): fxa failed on Edge

packages/fxa-content-server/app/styles/_variables.scss, packages/fxa-content-server/app/styles/modules/_button-row.scss
Closes #5658
* The warning buttons did not have an effect.
* Change the background color from the warning buttons, when the button receives hover or active.
fixes #5658
=> fix(style): add active and hover effect to the warning buttons from settings

packages/fxa-auth-server/docs/api.md, packages/fxa-auth-server/lib/error.js, packages/fxa-auth-server/lib/routes/account.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-profile-server/docs/API.md, packages/fxa-profile-server/lib/error.js, packages/fxa-profile-server/lib/routes/ecosystem_anon_id/post.js, packages/fxa-profile-server/test/api.js
- There's no valid reason to be performing an eco id change without either asserting one does not exist, or that an existing one matches
- Makes either If-Match or If-None-Match mandatory when performing the ID update
This is going to conflict with #6081 - I'm happy to wait until it's merged and then resolve conflicts on my end.
=> feat(aet): make either precondition header mandatory when updating anon id

packages/fxa-shared/package.json
Because auth-server doesn't use ts-node/register in production and fxa-shared compiles typescript, requiring a subpath like 'fxa-shared/subscriptions/metadata' finds no js to load. The "exports" field of package.json allows us to map required paths to other locations, in this case ./dist.
see https://nodejs.org/dist/latest-v12.x/docs/api/esm.html#esm_package_entry_points
=> fix(auth): added exports to fxa-shared package.json

.github/.codecov.yaml
Because, well the code cov comments are providing no real value and are noisy. Once we implement https://docs.codecov.io/docs/carryforward-flags, the code coverage will actually be more accurate.
=> chore(coverage): disable codecov comments

packages/fxa-content-server/app/scripts/templates/account_recovery_confirm_key.mustache, packages/fxa-content-server/app/scripts/templates/choose_what_to_sync.mustache, packages/fxa-content-server/app/scripts/templates/complete_reset_password.mustache, packages/fxa-content-server/app/scripts/templates/ready.mustache, packages/fxa-content-server/app/scripts/templates/settings/account_recovery/confirm_password.mustache, packages/fxa-content-server/app/scripts/templates/would-you-like-to-sync.mustache, packages/fxa-content-server/app/styles/modules/_button-row.scss, packages/fxa-content-server/app/styles/modules/_settings-account-recovery.scss
* All the `.button-link` should be links and not buttons.
* Change the buttons with `.button-link` to links, and place it outside of `.button-row`.
* Remove the class `.button-link`.
fixes #3951
I think the class `.centered` should have another name.
=> fix(content-server): change the buttons from account-recovery to links.

packages/fxa-auth-server/lib/routes/account.js, packages/fxa-auth-server/test/local/routes/account.js
* Hapi normalizes all headers to lowercase, but the code for if-match checking was looking for headers with mixed case.
* You have to provide a uid when looking up an account in the db, but the route for updating ecosystemAnonId was not 😅.
* Fixes the precondition checks so they execute correctly.
Closes: #6092
=> fix(aet): Correctly check preconditions when updating ecosystemAnonId

packages/fxa-email-service/src/providers/mod.rs, packages/fxa-email-service/src/types/headers/mod.rs, packages/fxa-email-service/src/types/headers/test.rs
- we send X-Verify-Short-Code in [tests](https://github.com/mozilla/fxa/search?q=%22x-verify-short-code%22&unscoped_q=%22x-verify-short-code%22) and in [Mailer.prototype.verifyShortCodeEmail](https://github.com/mozilla/fxa/blob/b0c80f64452e0b1228b2ca0ab265e22b555a96d8/packages/fxa-auth-server/lib/senders/email.js#L600-L620)
- allows X-Verify-Short-Code to pass through the email-service
Closes: #5186 
Test changes pass when run locally with ./scripts/test-ci.sh but I don't see where we actually run the tests under circle-ci, which isn't optimal (unless they are run and I'm just not seeing where).
=> fix(headers): allow X-Verify-Short-Code header to pass through

packages/fxa-admin-panel/.rescriptsrc.js, packages/fxa-auth-client/lib/crypto.ts, packages/fxa-content-server/webpack.config.js, packages/fxa-payments-server/.rescriptsrc.js, packages/fxa-react/configs/rescripts.js, packages/fxa-settings/.rescriptsrc.js
Because I was about to add fxa-auth-client to the additionalJSIpmorts but ran into problems. Instead of trying to include the minimum set of paths to add to the webpack rule this just lets all of fxa in.
Also, since we started using `workspace:*` in package.json we no longer need the aliases or jest module mappings!
=> refactor(rescripts): include all of fxa as valid paths in rescripts

packages/fxa-graphql-api/README.md, packages/fxa-settings/README.md
- We didn't have instructions on connecting to the playground documented.
- Adds docs for the GQL playground
Closes: # none
=> chore(docs): Add documentation for connecting to the GQL playground

packages/fxa-content-server/app/scripts/lib/auth-errors.js
- We don't intend for AET update errors to ever be displayed to users (who won't understand or be able to fix those errors)
- Removes the AET update precondition failed error from the list of translated error strings
=> bug(aet): Don't translate anon_id update errors

packages/fxa-content-server/app/tests/spec/views/connect_another_device.js
- We had a failing test in chrome that needed to mock the useragent to FF
- Adds the mock
Closes: #6023
=> fix(tests): Fix chrome failing test

packages/fxa-content-server/app/scripts/lib/metrics.js, packages/fxa-content-server/app/scripts/lib/validate.js, packages/fxa-content-server/app/tests/spec/lib/metrics.js, packages/fxa-content-server/app/tests/spec/lib/validate.js
- We shouldn't stop a user from logging in if we detect invalid utm params
- Replaces the invalid utm param with `invalid` and logs a Sentry error. Hopefully we can see how often this happens and what RPs are sending
- By replacing the utm param, it allows us to still submit the metrics
Closes: #3673 
Try to login with an invalid utm param set. Ex [http://localhost:3030/signin_token_code?context=fx_desktop_v3&entrypoint=fxa_discoverability_native&action=email&service=sync&utm_term=(not%20ready)](http://localhost:3030/signin_token_code?context=fx_desktop_v3&entrypoint=fxa_discoverability_native&action=email&service=sync&utm_term=(not%20ready))
=> fix(params): Gracefully handle invalid utm params

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
- removes global TTL for StripeHelper cacheManager
- sets per-method ttlSeconds based on config setting
- tests to assert the TTL changes
- some TODOs for follow up issues
fixes #6097
=> fix(payments): ensure Customer data is not cached with an expiration TTL

packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-server/lib/routes/totp.js, packages/fxa-auth-server/test/local/routes/totp.js, packages/fxa-auth-server/test/remote/totp_tests.js
Because the new settings page shows the enabled state more prominently and the data returned by this call isn't sensitive it makes more sense to lower the restriction than to burden the frontend with a more complicated design.
=> feat(totp): remove session verification requirement from /totp/exists

packages/fxa-auth-db-mysql/CHANGELOG.md, packages/fxa-auth-db-mysql/package.json, packages/fxa-auth-server/CHANGELOG.md, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/package.json, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-content-server/CHANGELOG.md, packages/fxa-content-server/package.json, packages/fxa-customs-server/CHANGELOG.md, packages/fxa-customs-server/package.json, packages/fxa-email-event-proxy/package.json, packages/fxa-email-service/CHANGELOG.md, packages/fxa-email-service/Cargo.lock, packages/fxa-email-service/Cargo.toml, packages/fxa-event-broker/CHANGELOG.md, packages/fxa-event-broker/package.json, packages/fxa-geodb/CHANGELOG.md, packages/fxa-geodb/package.json, packages/fxa-payments-server/CHANGELOG.md, packages/fxa-payments-server/package.json, packages/fxa-profile-server/CHANGELOG.md, packages/fxa-profile-server/package.json, packages/fxa-shared/CHANGELOG.md, packages/fxa-shared/package.json, packages/fxa-support-panel/CHANGELOG.md, packages/fxa-support-panel/package.json
Just in case anyone else is fuzzy on how this "point release" or "dot release" thing works, I'm following the 'cherry-pick from main into train branch' approach documented in the release docs [as "another option for a patch release"](https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/release-process#another-option-for-a-patch-release):
1. revive the train-182 branch that had been deleted the last time we did a dot release, nbd
2. cherry-pick the required commit into the branch locally
3. run `./release.sh patch` to generate the tags and changelogs locally (see below for the raw script output just FYI)
4. push the branch and tag to the `origin` remote
5. per instructions from the `release.sh` script output, update the ops deploy …
=> Release 182.2

packages/fxa-content-server/app/scripts/lib/constants.js, packages/fxa-graphql-api/src/config.ts, packages/fxa-profile-server/lib/config.js
- The current max file size for avatar upload is 1mb locally, 1.35mb in prod.
- Bumps frontend and [default] server validation to 2mb across the board. Ops will still need to set the server env var to 2mb.
Closes: #6075
**Hold merge**. We need to wait until this change is set in prod first (cc @jrgm).
=> refactor(avatars): increase max file size to 2mb

packages/fxa-settings/package.json, packages/fxa-settings/src/components/AccountDataHOC/gql.ts, packages/fxa-settings/src/components/AccountDataHOC/index.test.tsx, packages/fxa-settings/src/components/App/index.test.tsx, packages/fxa-settings/src/index.tsx, packages/fxa-settings/src/lib/auth.test.tsx, packages/fxa-settings/src/lib/auth.ts, packages/fxa-settings/src/lib/cache.ts, packages/fxa-settings/tsconfig.json, yarn.lock
This provides the base functionality needed for fxa-settings to make api calls to the auth-server. There's an `AuthContext.Provider` initialized in index.tsx and the `useAuth` hook to retrieve the client from components.
This is a pared down version of #6109 which is more of a POC. That one has a functional example of change password.
=> feat(settings): added fxa-auth-client to fxa-settings

packages/fxa-auth-server/lib/routes/subscriptions.ts, packages/fxa-auth-server/test/local/routes/subscriptions.js
I noticed that I didn't get a download email after going through the new SCA subscription flow. Also, we didn't trigger `customerChanged`, which invalidates the profile cache and forces a customer cache update along with some other messaging.
=> fix(payments): ensure SCA flow sends download email and triggers customer update

packages/fxa-auth-server/lib/routes/subscriptions.ts, packages/fxa-auth-server/test/local/routes/subscriptions.js, packages/fxa-payments-server/src/lib/amplitude.ts, packages/fxa-payments-server/src/lib/apiClient.test.ts, packages/fxa-payments-server/src/lib/apiClient.ts, packages/fxa-payments-server/src/routes/ProductV2/SubscriptionCreate/index.test.tsx, packages/fxa-payments-server/src/routes/ProductV2/SubscriptionCreate/index.tsx
- expand response from SCA subscription create to add sourceCountry
- add amplitude lifecycle events for SCA subscription create and payment
update APIs
- wrap SCA API client methods in Amplitude lifecycle event pings
fixes #6136
=> feat(payments): implement metrics for SCA flows

packages/fxa-auth-server/docs/oauth/prompt-none.md, packages/fxa-content-server/app/scripts/models/reliers/oauth.js, packages/fxa-content-server/app/tests/spec/models/reliers/oauth.js, packages/fxa-content-server/server/lib/routes/get-index.js
* If an RP uses prompt=none with an id_token_hint, don't check against the allowed client list. This is because the user must have signed in to the RP before, otherwise the RP could not provide us a valid id_token.
* We still require an RP to be on the allowlist if they want to use prompt=none with the user email (via either the login_hint or email parameters).
Closes #4963, closes #6028.
- AMO has run into an error using `id_token_hint` due to the `prompt=none` allowlist
- And because we have long planned (see #4963) to allow any RP with an ID Token to use `prompt=none` without being on the allowlist (see also discussion in the docs updated in this PR)
- modifies the `prompt=none` validation flow to only check against the RP allowlist if the RP uses the `login_hint` aka `email` query …
=> fix(oidc): Allow prompt=none with id_token_hint for all RPs

packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/src/lib/amplitude.ts, packages/fxa-payments-server/src/lib/apiClient.test.ts, packages/fxa-payments-server/src/lib/apiClient.ts, packages/fxa-payments-server/src/lib/test-utils.tsx, packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.test.tsx, packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.tsx, packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.test.tsx, packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx, packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateFormV2.test.tsx, packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateFormV2.tsx, packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx, packages/fxa-payments-server/src/routes/Subscriptions/index.scss, packages/fxa-payments-server/src/routes/Subscriptions/index.tsx, packages/fxa-payments-server/src/store/actions/api.ts, packages/fxa-payments-server/src/store/sequences.ts
Because:
- payment method for subscriptions should be updated in one place
This commit:
- move the payment method info and update form into their own section
- move CancelSubscriptionPanel into its own file
- replace 'react-test-renderer' tests with 'Testing-Library/react' ones
- make minor style and layout changes
- remove product and plan ids from payment update Amplitude events as
they are no longer associated with a subscription
Closes: FXA-2316
=> refactor(subscriptions): use a single payment update form

packages/fxa-settings/src/components/Security/index.stories.tsx, packages/fxa-settings/src/components/Security/index.test.tsx, packages/fxa-settings/src/components/Security/index.tsx, packages/fxa-settings/src/components/Settings/index.tsx
- Adds the security panel to settings
- Buttons will be updated once (newly filed)  is complete.
- [figma link](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A1)
- Enabled/fresh load is hard coded (as suggested in issue), this will be updated in the future once we get the data flowing
Closes: #4911
=> task(fxa-settings): Add security panel to settings

packages/fxa-react/components/Portal/index.tsx, packages/fxa-settings/src/components/AlertBar/index.test.tsx, packages/fxa-settings/src/components/AlertBar/index.tsx, packages/fxa-settings/src/components/AppLayout/index.tsx, packages/fxa-settings/src/components/Settings/index.tsx, packages/fxa-settings/src/components/UnitRow/index.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.stories.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx, packages/fxa-settings/src/lib/AlertBarContext.tsx, packages/fxa-settings/src/lib/hooks.test.tsx, packages/fxa-settings/src/lib/hooks.tsx
* We need to use the AlertBar component throughout the project while keeping it as the first DOM element after the main tag.
* Adds 'alert-bar-root' element and uses createPortal in AlertBar to mount
* Adds AlertBarContext for referencing the 'alert-bar-root' element
* Modifies the hook that sets focus on the element opening a modal, allowing for a 'triggerException' to allow AlertBar to take focus
* Pulls the secondary email section into its own component
Closes: #4926 
This issue had a couple of different parts to it, but part of it was to look into Apollo client cache to ensure that would handle our state needs across our GQL and REST API calls plus anything that would require a global state. Through reading I've done plus Danny's work on #6125, …
=> feat(settings): Add AlertBar root el with Context, UnitRowSecondaryEmail

packages/fxa-auth-db-mysql/CHANGELOG.md, packages/fxa-auth-db-mysql/package.json, packages/fxa-auth-server/CHANGELOG.md, packages/fxa-auth-server/package.json, packages/fxa-content-server/CHANGELOG.md, packages/fxa-content-server/package.json, packages/fxa-customs-server/CHANGELOG.md, packages/fxa-customs-server/package.json, packages/fxa-email-event-proxy/package.json, packages/fxa-email-service/CHANGELOG.md, packages/fxa-email-service/Cargo.lock, packages/fxa-email-service/Cargo.toml, packages/fxa-event-broker/CHANGELOG.md, packages/fxa-event-broker/package.json, packages/fxa-geodb/CHANGELOG.md, packages/fxa-geodb/package.json, packages/fxa-payments-server/CHANGELOG.md, packages/fxa-payments-server/package.json, packages/fxa-profile-server/CHANGELOG.md, packages/fxa-profile-server/package.json, packages/fxa-shared/CHANGELOG.md, packages/fxa-shared/package.json, packages/fxa-support-panel/CHANGELOG.md, packages/fxa-support-panel/package.json
Changes for train 1.183.0, per our [release doc](https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/release-process).
=> Release 1.183.0

packages/fxa-content-server/server/lib/routes/get-frontend.js, packages/fxa-content-server/tests/server/routes.js
- Missed a spot in the inline totp routes setup. Now that the OIDC bug is fixed, this route is 404ing on the server.
- Registers the inline totp routes with the server, so the frontend app knows to handle them.
=> fix(server): register 2FA inline setup routes with server

packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/Settings/index.test.tsx, packages/fxa-settings/src/components/Settings/index.tsx, packages/fxa-settings/src/models/_mocks.tsx
- opts for `useAccount` over passing `account` object into components. builds off of @dannycoates pr, https://github.com/mozilla/fxa/pull/6145/files
Closes: #6154 
=> task(fxa-settings): convert settings component to use cache

packages/fxa-admin-server/src/lib/resolvers/account-resolver.ts
Because:
* MySQL optimizer doesn't like using emailBounces index when using a
sub-query.
This commit:
* Splits the query into two, which then utilizes the indexes of both
tables as expected.
Closes #6064
=> fix(admin): split query for index usage

packages/fxa-settings/src/index.tsx, packages/fxa-settings/src/lib/auth.test.tsx, packages/fxa-settings/src/lib/auth.ts, packages/fxa-settings/src/lib/gql.ts
When the graphql server fails authentication it means we need to reauthenticate the user. We do this in a slightly roundabout way by redirecting to /get_flow and having it navigate to the login page so that we can redirect_to back to /beta/settings. Once new settings is no longer in beta we ought to be able to redirect straight to /signin.
fixes #6118
=> feat(settings): redirect to login when session token is invalid

packages/fxa-react/components/AppErrorBoundary/index.test.tsx, packages/fxa-react/components/AppErrorDialog/index.test.tsx, packages/fxa-react/components/Footer/index.test.tsx, packages/fxa-react/components/LinkExternal/index.test.tsx, packages/fxa-react/components/LoadingSpinner/index.test.tsx, packages/fxa-react/components/LogoLockup/index.test.tsx, packages/fxa-react/components/Portal/index.test.tsx, packages/fxa-react/components/Survey/index.test.tsx, packages/fxa-react/jest.config.js, packages/fxa-react/setupTests.ts, packages/fxa-settings/src/components/AlertBar/index.test.tsx, packages/fxa-settings/src/components/App/index.test.tsx, packages/fxa-settings/src/components/AppLayout/index.test.tsx, packages/fxa-settings/src/components/Avatar/index.test.tsx, packages/fxa-settings/src/components/ContentSkip/index.test.tsx, packages/fxa-settings/src/components/HeaderLockup/index.test.tsx, packages/fxa-settings/src/components/Modal/index.test.tsx, packages/fxa-settings/src/components/Nav/index.test.tsx, packages/fxa-settings/src/components/Security/index.test.tsx, packages/fxa-settings/src/components/Security/index.tsx, packages/fxa-settings/src/components/Settings/index.test.tsx, packages/fxa-settings/src/components/UnitRow/index.test.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.stories.tsx, packages/fxa-settings/src/components/UnitRowWithAvatar/index.test.tsx, packages/fxa-settings/src/components/VerifiedSessionGuard/index.test.tsx, packages/fxa-settings/src/lib/config.test.ts, packages/fxa-settings/src/lib/flow-event.test.ts, packages/fxa-settings/src/setupTests.js
I went down a rabbit hole of making our new React app testing environments a little more consistent and DRY.
- Adds `setupTests.js` file in fxa-settings and fxa-react. Because fxa-settings is a create-react-app, react-scripts detects this file [automatically](https://create-react-app.dev/docs/running-tests/#initializing-test-environment) if it's present. fxa-react doesn't, so I updated the Jest config to do this. You should put any boilerplate code in these files.
- Stubs console log/error/warning. These just add noise to the test output. You can still assert on them if you want to ensure they were invoked (though, would you?)
- Removes all instances of `cleanup`. [Don't need it.](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-cleanup)
- Prefers usage of …
=> refactor(settings + react): update tests to be more consistent and DRY

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/subscriptions.ts, packages/fxa-auth-server/test/local/routes/subscriptions.js
In the new SCA payment flow, there is at least one case where we'll only
know that the subscription has been successfully paid for when the
webhook event comes in from Stripe. (i.e. client-side 3D Secure
authentication)
But, as far as I can tell, we can't tell the difference between that and any other
case. So, this PR switches all cases over to sending the download email
along with initial invoice in response to the invoice webhook event.
fixes #6175
=> fix(payments): send subscription download email along with initial invoice

packages/fxa-content-server/app/styles/_layout.scss, packages/fxa-content-server/server/templates/pages/src/404.html, packages/fxa-payments-server/public/404.html
Put the 404 page message in a "p" tag and Corrected the Line-heigth to 1.5em
-Current one doesn't go with other Styles according to the ISSUE this is fixing.
- Fixed the issue by simply changing the tag and adding the necessary styles.
Closes: #6102 
=> Changed the 404 page Text to be Match with Other Styles

packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/views/base.js, packages/fxa-content-server/app/scripts/views/behaviors/navigate.js, packages/fxa-content-server/app/tests/spec/views/base.js, packages/fxa-content-server/app/tests/spec/views/behaviors/navigate.js, packages/fxa-settings/src/components/AlertExternal/index.test.tsx, packages/fxa-settings/src/components/AlertExternal/index.tsx, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/Settings/index.tsx, packages/fxa-settings/src/lib/cache.ts, packages/fxa-settings/src/models/Account.ts, packages/fxa-settings/src/models/_mocks.tsx
Some actions in fxa-content-server end up displaying an alert message on the settings page. We want to be able to display those messages across the "app" boundary between the content-server front-end and new settings.
To do this we store the message in localStorage and whichever app gets to it first will display it and remove it from storage.
closes #4933
=> New settings: display alerts from content-server

packages/fxa-event-broker/src/lib/notificationProcessor.ts, packages/fxa-event-broker/src/lib/serviceNotifications.ts, packages/fxa-event-broker/src/test/lib/notificationProcessor.spec.ts
Because:
* Some producers manage to upper-case the clientId or just bungle it
entirely.
This commit:
* Screen the clientId to ensure it looks proper, upper-case it before
handling the message for normalization.
Fixes #6185
=> feat(event-broker): prevent invalid client ids

packages/fxa-auth-server/lib/routes/subscriptions.ts, packages/fxa-auth-server/test/local/routes/subscriptions.js
=> fix(payments): do not send payment failure emails during subscription creation flow

.yarnrc.yml, package.json, packages/fxa-admin-panel/package.json, packages/fxa-auth-client/package.json, packages/fxa-auth-server/package.json, packages/fxa-content-server/package.json, packages/fxa-metrics-processor/package.json, packages/fxa-payments-server/package.json, packages/fxa-payments-server/src/lib/test-utils.tsx, packages/fxa-payments-server/src/lib/validator.ts, packages/fxa-react/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json, yarn.lock
Because:
* Using the latest everywhere helps with consistency and smaller build
size.
This commit:
* Updates for TypeScript 3.9.7 everywhere in FxA.
=> chore: update typescript

packages/fxa-auth-client/lib/client.ts, packages/fxa-graphql-api/src/lib/datasources/authServer.ts, packages/fxa-graphql-api/src/lib/resolvers/account-resolver.ts, packages/fxa-graphql-api/src/lib/resolvers/types/input/index.ts, packages/fxa-graphql-api/src/lib/resolvers/types/input/send-session-verification.ts, packages/fxa-graphql-api/src/lib/resolvers/types/input/verify-email.ts, packages/fxa-graphql-api/src/lib/resolvers/types/input/verify-session.ts, packages/fxa-graphql-api/src/test/lib/datasources/authServer.spec.ts, packages/fxa-graphql-api/src/test/lib/resolvers/account-resolver.spec.ts
This adds the `verifySecondaryEmail` `sendSessionVerificationCode` and `verifySession` mutations to support new settings page.
closes #6204
=> feat(graphql): add new settings mutations

packages/fxa-auth-server/lib/routes/utils/signin.js, packages/fxa-auth-server/test/remote/recovery_email_change_email.js
- When users change their primary email address would could potentially do an account lookup on the wrong email value
- The `originalLoginEmail` is a value that the users password is hashed with
- Uses the `originalLoginEmail` if present
Closes: https://bugzilla.mozilla.org/show_bug.cgi?id=1635027
=> fix(email): Lookup account by `originalLoginEmail` if present

docs/adr/0020-application-architecture.md
Because:
* FxA has no chosen application architecture, with several ad-hoc ones
in place.
This commit:
* Proposes that an application architecture for our back-end services
should be formally defined, chosen, and have documentation/tooling
available.
=> docs(adr): add application architecture

packages/fxa-auth-server/lib/metrics/amplitude.js, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/subscriptions.ts, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/lib/senders/templates/_versions.json, packages/fxa-auth-server/lib/senders/templates/layouts/subscription.html, packages/fxa-auth-server/lib/senders/templates/layouts/subscription.txt, packages/fxa-auth-server/lib/senders/templates/partials/subscriptionEmail.html, packages/fxa-auth-server/lib/senders/templates/subscriptionsPaymentExpired.html, packages/fxa-auth-server/lib/senders/templates/subscriptionsPaymentExpired.txt, packages/fxa-auth-server/scripts/write-emails-to-disk.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js, packages/fxa-auth-server/test/local/senders/email.js
Because:
- a soon to expire credit card can be used to pay for multiple
subscriptions
This commit:
- send a slightly different reminder email to customers with multiple
subscriptions
Closes: FXA-2319
=> chore(emails): add CC expiration email for Multiple Products

packages/fxa-settings/package.json, packages/fxa-settings/src/components/Checkbox/index.stories.tsx, packages/fxa-settings/src/components/Checkbox/index.test.tsx, packages/fxa-settings/src/components/Checkbox/index.tsx, packages/fxa-settings/src/components/DataBlock/index.stories.tsx, packages/fxa-settings/src/components/DataBlock/index.test.tsx, packages/fxa-settings/src/components/DataBlock/index.tsx, packages/fxa-settings/src/components/PasswordInput/index.stories.tsx, packages/fxa-settings/src/components/PasswordInput/index.tsx, packages/fxa-settings/src/components/TextInput/index.stories.tsx, packages/fxa-settings/src/components/TextInput/index.test.tsx, packages/fxa-settings/src/components/TextInput/index.tsx, yarn.lock
- There were still a few outstanding items to address as part of #6206
- Eliminates all component `readerText` props. We determined they didn't add a substantial amount of value, and any accompanying a11y content can be implemented on a case-by-case basis.
- As a result of removing readerText I also refactored the the usage of component IDs and was able to eliminate the UUID dependency.
- Makes `DataBlock` only copyable. We currently don't have a need for a read-only version.
- Further cleans up some leftover event handlers and weird syntax in the new components.
=> refactor(settings): ui component followups

packages/fxa-auth-server/scripts/must-reset.js, packages/fxa-auth-server/scripts/must-reset/index.js, packages/fxa-auth-server/test/scripts/fixtures/accounts.json, packages/fxa-auth-server/test/scripts/fixtures/invalid_email.txt, packages/fxa-auth-server/test/scripts/fixtures/invalid_uid.txt, packages/fxa-auth-server/test/scripts/must-reset.js
* With a plain list of emails/uids it's easier to use the script.
* Add the option of running the script must-reset from a plain text
list of uids or emails.
* Remove the option to read from a json.
fixes #5894
This script from a secondary email can reset an account, even if the secondary email is not yet verified.
I've had to change `setTimeOut` value to make the tests pass locally, maybe this only happens with me.
When I run 'npm run test', why is the "script part" being skipped?
=> feat(auth-server): enhance must-reset script to accept a plain text list

packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/ChangePassword/index.stories.tsx, packages/fxa-settings/src/components/ChangePassword/index.test.tsx, packages/fxa-settings/src/components/ChangePassword/index.tsx, packages/fxa-settings/src/components/TextInput/index.tsx
- We need some basic views for change password
- Implements those views per the design doc
- Does not add any form validation or perform the actual password change
Closes: #5028
Mobile:
Non-mobile:
=> feat(settings): Add basic change password views

_scripts/build-storybooks.sh, packages/fxa-payments-server/.storybook/config.js
Because I assumed that git retained file creation timestamps, I had a simple find command to delete old commits and pulls after 90 days. Two problems here:
1. 90 days is too long
2. git doesn't retain file creation timestamps anyway - so all files look as if they were created at the beginning of a CircleCI run.
Thus, aging storybook builds have been piling up in [mozilla-fxa/storybooks gh-pages branch](https://github.com/mozilla-fxa/storybooks/tree/gh-pages) and we hit a 10GB limit. 
Still thinking about a cleaner solution, maybe in node.js. But for now, this change should do [what I did manually](https://github.com/mozilla-fxa/storybooks/commit/2f692f3f8cdfa5ba156817db9809bcca4d502aaf).
It's an ugly hack that munges git log output to find `commit/*` and `pull/*` directories to delete old …
=> fix(storybook): delete commits and pulls over 3 weeks old on every build

packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache
⚠️ **Reviewer**: please check that this works locally for you in Safari desktop. I am unable to get Keychain working in my iOS simulator, so once this is merged and on Latest I will verify on an iPhone as well. It's possible this only fixed the desktop portion of this bug.
Safari does not effectively save the email you enter with the Keychain login item. It instead grabs the age.
Attempts to direct Safari to store the correct fields.
My current theory is that it has something to do with the email field being `disabled` or set to `display: none`. From my testing, using a `name` appeared to direct Safari to the correct fields, and this still appears to work in other browsers. Also, because we don't submit the form in a traditional way, the `name` on inputs has no impact on the data going …
=> fix(content server): make safari save the correct fields in keychain

packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js, packages/fxa-content-server/server/lib/routes/post-metrics.js
- The pairing success metric was not being emitted when a user signed in via pairing
- Checks for the pairing metrics via `action=pairing`
- Adjusts the `initialView` metric to accept numbers since oauth clients id are numbers and are used in the view name
I tested this using UA faker (iOS). The logs show that the device was connected via iOS...so it must work right?
Logs:
```
31|content  | 2020-08-18T17:05:15: fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_login - complete","time":1597784715716,"device_id":"71046070560244a6a6285754e7ddc6d2","session_id":1597784701500,"app_version":"184.0","language":"en-US","os_name":"iOS","os_version":"12.0","device_model":"iPhone","event_properties":{},"user_properties":{"flow_id":"eaa16267bd2204580b2d84427177aac2c951b8 …
```
=> fix(metrics): Emit pairing success metric when broker sends `action=pairing`

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/subscriptions.ts, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js
Because:
* When updating a customer with a payment method, we don't want any
sources from the Sources API around.
This commit:
* Removes all sources from a customer after updating the default
payment method with a payment method id.
Closes #2348
=> feat(auth-server): remove sources on payment update

packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.stories.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.test.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx, packages/fxa-settings/src/models/_mocks.tsx
Because:
* We setup many 'email' objects and need a helper for DRYer code
* We must have an onError option in mutations to allow tests to pass
This commit:
* Gets tests passing and DRYs them up
fixes #6192
I was going to wait to put this PR up because the secondary email section needs a refactor to change the `primaryEmail` verified state check to guard against a _session_ being unverified instead but I'll do that in a follow up since these changes are needed in another PR.
=> refactor(settings): Cleanup secondary email tests, catch mutation errors

packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/server/lib/csp/blocking.js, packages/fxa-content-server/tests/server/csp.js
Because:
- the need for basket proxy was removed in f2d2a2d
This commit:
- delete some configs that are no longer used
=> chore(configs): remove basket proxy configs

packages/fxa-settings/README.md
- We can provide some further explanations on what's going on in Settings around API calls, global state, Context/the `AlertBar`, `verifiedSessionGuard`, and test mocks.
- Updates `fxa-settings` README with things listed above.
Closes #6239
WIP, have a couple things left to finish.
=> chore(docs): Update fxa-settings docs

packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-webchannel-v1.js, packages/fxa-content-server/app/tests/spec/models/auth_brokers/oauth-webchannel-v1.js
- When an account is deleted by an oauth webchannel client, it should be the responsibility of the client to navigate the user to the correct screens (which may or may not be a webview)
- Oauth webchannel clients need to be loaded with specific oauth params in order for an account to be created, in the previous delete account flow. If an account is deleted, and then navigated back to the signup page, it might not have the correct query params to re-create the account.
- Emits the proper `fxaccounts:delete_account` web channel message when an account is deleted in any oauth webchannel broker
- FxiOS currently handles these messages by dismissing the current view and going to the view behind it
Closes: #6164 
It is a bit of a pain to test this locally. But if you dare you will need to …
=> fix(delete): Emit a `delete_account` webchannel message when account deleted by supported client

packages/fxa-settings/src/components/Profile/index.stories.tsx, packages/fxa-settings/src/components/Profile/index.test.tsx, packages/fxa-settings/src/components/Profile/index.tsx, packages/fxa-settings/src/components/SecondaryEmailInputForm/index.stories.tsx, packages/fxa-settings/src/components/SecondaryEmailInputForm/index.test.tsx, packages/fxa-settings/src/components/SecondaryEmailInputForm/index.tsx, packages/fxa-settings/src/components/Security/index.stories.tsx, packages/fxa-settings/src/components/Security/index.test.tsx, packages/fxa-settings/src/components/Security/index.tsx, packages/fxa-settings/src/components/Settings/index.tsx, packages/fxa-settings/src/components/TextInput/index.stories.tsx, packages/fxa-settings/src/components/TextInput/index.tsx, packages/fxa-settings/src/components/UnitRow/index.tsx, packages/fxa-settings/src/styles/tailwind.scss, packages/fxa-settings/src/styles/tooltip.scss
- we need to let the user know when they are adding a duplicate email
- Pulls `<Profile/>` into own component
- adds tooltip css
- adds `<SecondaryEmailInputForm/>`
Closes: #4959
=> task(fxa-settings): display errors in tooltip

packages/fxa-content-server/app/scripts/views/inline_totp_setup.js, packages/fxa-content-server/app/scripts/views/sign_in_token_code.js, packages/fxa-content-server/app/tests/spec/views/sign_in_token_code.js, packages/fxa-content-server/tests/functional/oauth_sign_in_token_code.js
- A verified session is required to enable 2FA.
- Existing flows do this from within the settings page, where we have the session upgrade mixin (this mixin does DOM twiddling to put an upgrade template in place of the regular template, and doesn't easily generalize to an inline flow)
- We do have a screen to do something similar inline, where users are asked to verify a code sent in an email
- Updates the inline totp setup view to redirect users to the signin_token_code screen if their session is unverified. Users will be redirected back to inline totp setup when that step is completed.
Closes: #5206
=> fix(totp): Ensure the user has a verified session before starting inline TOTP setup

packages/fxa-react/components/Portal/index.tsx
- train 185 tag is broken https://app.circleci.com/pipelines/github/mozilla/fxa/13110/workflows/8818676d-11a2-41e0-9bc2-30fe9267e666/jobs/189669
this may end up being a temporary fix. there might be a better way to do this
=> fix(portal): remove non-modal portal roots when unloaded

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/test/local/payments/stripe.js
This switches from displaying the payment details used in the last
charge to displaying default payment details which will be used in the
next invoice.
fixes #6172
=> fix(payments): use default payment details in reactivation email

packages/fxa-settings/README.md, packages/fxa-settings/src/lib/hooks.test.tsx, packages/fxa-settings/src/lib/hooks.tsx
- We want to be able to automatically handle mutation errors without importing error handling libs each time `useMutation` is used.
- Documentation needed some syntax highlighting ;)
- Adds `useHandledMutation`. This wraps `useMutation` with the option to specify an onError handler, which can itself throw and send the error to Sentry. In all other cases onError is just a noop. Per #6249, the idea is that we'd like to do this by default instead of importaing the Sentry lib each time. Note this does not close that issue though, as it does not address conventions for a general error message and GQL vs. other error types.
- Adds doc syntax highlighting in a couple spots
This sets the stage for a few things I'm working on in #6107, and also touches on #6249.
=> feat(settings): introduce hook to handle errors in mutations

packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/test/remote/device_tests.js, packages/fxa-profile-server/lib/routes/display_name/post.js, packages/fxa-profile-server/test/api.js
* Some clients (notably Firefox Desktop) will attempt to build a default
device name out of system-provided data, and if they encounter unicode
encoding issues then they'll insert the unicode replacment character
rather than failing.
* Such clients cannot complete FxA device registration, because we forbid
the device name from containing any characters in the unicode specials
block.
* There is not a concrete risk associated with characters from the specials
block, we just exclude them because they might have unexpected effects
(and particularly because some of them are currently unassigned).
* Allows the unicode replacement character U+FFFD (otherwise known as
"that diamond thingy with a question mark in it") in the display-safe
string validator.
Closes: #6269 
- ~~[ ] I have added …
=> fix(validation): Allow unicode replacement character in display-safe strings

packages/fxa-admin-panel/package.json, packages/fxa-admin-server/package.json, packages/fxa-auth-client/package.json, packages/fxa-graphql-api/package.json, packages/fxa-metrics-processor/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, release.sh
Because:
* The release script makes some wrong assumptions about the format of data
This commit:
* Fixes the changelog updates to work with empty/new changelogs
* Updates version numbers to the latest versions
Fixes #6195
=> fix(release): fixes versioning and changelogs

packages/fxa-settings/src/components/ChangePassword/index.tsx, packages/fxa-settings/src/components/Modal/index.tsx, packages/fxa-settings/src/components/ModalVerifySession/index.tsx, packages/fxa-settings/src/components/SecondaryEmailInputForm/index.tsx, packages/fxa-settings/src/components/UnitRow/index.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx, packages/fxa-settings/src/components/UnitRowWithAvatar/index.tsx, packages/fxa-settings/src/styles/ctas.scss
Breakout from #6283
- We should have consistent button styles
- Note the only visual change here is that I've update the type face to Metropolis, per the Figma doc. Everything else is just how classes are approached. My goal is to provide a consistent base class that can be layered on top of with sizing classes, whereas currently we have a different sized primary/neutral buttons
- Updates our CTA classes to use modular classes that supply the style and sizing.
=> refactor(settings): make cta buttons more modular, uniform in size

packages/fxa-content-server/app/scripts/views/settings/change_password.jsx
Because:
* When changing password, after all required inputs is completed, the "Save Password" is displayed.
This commit:
* Create a fake input with "required" atribute to trick the browser to not showing the "Save Password" doorhanger until the route is changed.
Closes #547
=> fix(content-server): create fake hidden input on change password.

packages/123done/static/css/main.css, packages/123done/static/index.html, packages/fxa-content-server/tests/functional/lib/selectors.js
- adds subscription buttons to the footer of 123done while logged in but
not yet subscribed.
- removes the "Subscribe to pro" button from header because there's not
room for all the currency buttons in that header
fixes #6216
=> feat(payments): add subscription buttons for 123done while logged in

packages/fxa-settings/README.md, packages/fxa-settings/src/components/AppLayout/index.stories.tsx, packages/fxa-settings/src/components/FlowSecondaryEmailAdd/index.stories.tsx, packages/fxa-settings/src/components/FlowSecondaryEmailVerify/index.stories.tsx, packages/fxa-settings/src/components/Profile/index.stories.tsx, packages/fxa-settings/src/components/Security/index.stories.tsx, packages/fxa-settings/src/components/UnitRow/index.stories.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.stories.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.stories.tsx, packages/fxa-settings/src/components/UnitRowWithAvatar/index.stories.tsx
- Many storybook views were broken
- address LocationProvider errors in multiple stories
- address MockedProvider(missing Apollo provider) in AppLayout
- added "common errors" section into storybook portion of README
Closes: #6226
=> task(fxa-settings): fix storybook errors

packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/tests/spec/models/account.js
- The account that uses a recovery code is not being recognized as verified when it is redirected to the CAD screen, and the user is thusly prompted to sign in/enter a password after they just entered a recovery code.
- Modifies the `Account` model's `consumeRecoveryCode` to mark the account as verified once the request is complete, allowing the redirection to the CAD screen to be completed.
Closes: #6173
=> fix(content server): mark account as verified so recovery code usage can redirect you to cad screen

packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-webchannel-v1.js, packages/fxa-content-server/app/tests/spec/models/auth_brokers/oauth-webchannel-v1.js
- Pairing authentications were not being properly logged
- While debugging other pairing issues I found that the auth broker used was not the one emitting the metrics 
- Adds logging for pairing in the `oauth-webchannel-v1` broker, this is the broker that pairing uses
Closes: #5990
=> fix(metrics): Emit metrics for pairing part 2

packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache
Because:
* When trying to sign in with wrong password, the "Save Password" is displayed.
This commit:
* Create a fake input with "required" atribute to trick the browser to not showing the "Save Password" doorhanger.
=> fix(content-server): create fake hidden input on sign in

packages/fxa-admin-panel/package.json, packages/fxa-react/configs/tailwind.js, packages/fxa-react/package.json, packages/fxa-settings/package.json, packages/fxa-settings/src/components/Avatar/index.stories.tsx, packages/fxa-settings/src/components/Avatar/index.test.tsx, packages/fxa-settings/src/components/Avatar/index.tsx, packages/fxa-settings/src/components/DropDownAvatarMenu/index.stories.tsx, packages/fxa-settings/src/components/DropDownAvatarMenu/index.test.tsx, packages/fxa-settings/src/components/DropDownAvatarMenu/index.tsx, packages/fxa-settings/src/components/DropDownAvatarMenu/sign-out.svg, packages/fxa-settings/src/components/HeaderLockup/index.stories.tsx, packages/fxa-settings/src/components/HeaderLockup/index.tsx, packages/fxa-settings/src/components/Profile/index.tsx, packages/fxa-settings/src/components/Settings/index.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx, packages/fxa-settings/src/components/UnitRowWithAvatar/index.stories.tsx, packages/fxa-settings/src/components/UnitRowWithAvatar/index.test.tsx, packages/fxa-settings/src/components/UnitRowWithAvatar/index.tsx, packages/fxa-settings/src/lib/cache.ts, packages/fxa-settings/src/models/_mocks.tsx, packages/fxa-settings/src/styles/drop-down-menu.scss, packages/fxa-settings/src/styles/tailwind.scss, yarn.lock
* Settings needs an avatar drop-down showing the user's avatar, display name or primary email, and sign out button.
* Adds DropDownAvatarMenu component and .drop-down-menu class for Bento menu reuse
* Adds client-side destroySession mutation
* Uses the useAccount hook in Avatar component instead of drilling the prop down and updates the default to use placekitten URL so the avatar actually loads in an img tag
* Adds truncate class to UnitRow showing the displayName
Closes: #4869
Tailwindcss needed a package update to work with gradients.
=> feat(settings): Add avatar drop down component

packages/fxa-content-server/app/scripts/lib/auth-errors.js, packages/fxa-content-server/app/scripts/views/form.js, packages/fxa-content-server/app/scripts/views/mixins/upgrade-session-redirect-mixin.js, packages/fxa-content-server/app/scripts/views/settings/delete_account.js, packages/fxa-content-server/app/scripts/views/sign_in_token_code.js, packages/fxa-content-server/app/scripts/views/sign_in_totp_code.js, packages/fxa-content-server/app/tests/spec/views/settings/delete_account.js
- When an account is paired, the paired session would not have the assurance level to delete the account (ie `unverified session`)
- Adds a mixin to redirect the user to verify the session with TOTP if they have it setup on the account
Closes: #6199 #4257
I wasn't actually able to test the pairing flow locally with 2FA enabled. You would need custom build of FxiOS (pointing to local FxA) and then be able to run it on a physical phone since the iOS simulator does not support a camera. I was able to simulate this by the following though
1. Disable session being verified for new accounts via [skipForNewAccount](https://github.com/mozilla/fxa/blob/db20d69957612ea411c1b89d992d52b20763d927/packages/fxa-auth-server/config/index.ts#L1349)
2. Create account A and sign into non Firefox browser A
a. …
=> fix(totp): Add mixin to verify session if a request is `unverified session` based

packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.tsx, packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx
Each cancellation panel now tracks whether it initiated the current cancellation in flight. If so, it displays the spinner. All other cancellation panels just get disabled buttons.
fixes #6234
=> fix(payments): display only one in-progress spinner during subscription cancellation

packages/fxa-content-server/app/styles/modules/_legal.scss
Because:
* Links from `#legal-footer` have different focus borders shapes.
This commit:
* FIx the padding in the last link from `#legal-footer`.
Closes #6235
=> fix(content-server): fix padding in link from legal footer

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-payments-server/src/components/PaymentFormV2/index.test.tsx, packages/fxa-payments-server/src/components/PaymentFormV2/index.tsx, packages/fxa-payments-server/src/routes/ProductV2/SubscriptionCreate/index.tsx, packages/fxa-payments-server/src/routes/ProductV2/index.test.tsx
Because:
- an unpaid invoice could block a user from a successful subscription
- current retry only updates the default payment method, not paying the
inovice
This commit:
- use Stripe's API to pay an invoice on a retry
Part of FXA-2494
=> fix(payments): pay invoice on retry

_dev/tsconfig.base.json
This should hopefully get main passing...
- Because it's in the base config shared across all tsconfigs in the repo, the incremental property is clashing with other properties, which is leading to failures in circle ci
- Removes it. Ben said it's okay to disable for now.
=> fix(config): disable incremental compilation in base ts config

packages/fxa-react/components/Header/index.tsx, packages/fxa-react/configs/tailwind.js, packages/fxa-settings/src/components/FlowContainer/index.tsx, packages/fxa-settings/src/components/InputPassword/index.tsx, packages/fxa-settings/src/components/InputText/index.tsx, packages/fxa-settings/src/components/Modal/index.tsx, packages/fxa-settings/src/components/ModalVerifySession/index.tsx, packages/fxa-settings/src/components/PageChangePassword/index.tsx, packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.tsx, packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.tsx, packages/fxa-settings/src/components/UnitRow/index.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx, packages/fxa-settings/src/components/UnitRowWithAvatar/index.tsx, packages/fxa-settings/src/styles/ctas.scss
- There are a handful of areas in new Settings that could be improved to be more consistent or to adhere more closely to the Figma design.
- Makes various stylistic changes that add a little more polish to the Settings app. These changes are all pretty subtle and may not be noticeable at first. This includes things like:
- Consistent form button presentation
- Small spacing improvements to match Figma
- Updates to make spacing consistent across the various flows that implemented the same elements (think modals, forms)
- Add transition to base cta class as it's clearly being used manually everywhere lol
- Adds z-index to header so relatively positioned elements will appear under it
- There's a TODO to uncomment two props once Dave's work in #6302 is merged
=> refactor(settings): various cosmetic changes to better reflect designs

.yarn/plugins/@yarnpkg/plugin-relock.js, .yarnrc.yml
The [relock plugin](https://github.com/mozilla-fxa/yarn-plugin-relock) regenerates the `yarn.lock` without doing a full install. This is mainly for the github bot to automatically update dependabot PRs with commits to update the `yarn.lock`.
part of #6311
=> feat(dev): added yarn relock plugin

packages/fxa-settings/src/components/DropDownAvatarMenu/index.tsx
- There was unwanted vertical spacing in iOS
- Adjust flexbox usage to clean it up
Closes: #6357
=> fix(settings): fix vertical spacing in avatar dropdown

packages/fxa-content-server/app/scripts/lib/fxa-client.js, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/views/account_recovery_confirm_key.js, packages/fxa-content-server/app/scripts/views/complete_reset_password.js, packages/fxa-content-server/app/tests/spec/lib/fxa-client.js
- We can only create one `accountResetToken` per password reset. The recovery key flow and password reset flow attempts to create one
- If you start the recovery key flow and generate a `accountResetToken`, store the value in the account model so that it can be reused in the regular password reset flow
Closes: #6343
=> fix(recovery): Use the existing accountResetToken if account model has it set

packages/123done/server.js, packages/123done/version.js
- We should have version endpoints on the 123done server
- Adds basic versioning library to retrieve package.json version, source, and commit hash to 123done (also updates 321done)
Closes: #6219
=> feat(123done): add version route

packages/fxa-auth-server/lib/geodb.js
These don't need to be logged as error, it clutters up the logs when testing.
=> fix(logging: trace log geodb failures

packages/fxa-content-server/tests/functional/reset_password.js
-Added few missing checks from the manual test steps for reset password.
- check if the email is resent
-Then try to sign in again
=> test(reset-password): add few missing checks for resend email

packages/fxa-content-server/app/scripts/lib/newsletters.js, packages/fxa-content-server/app/scripts/templates/post_verify/newsletters/add_newsletters.mustache, packages/fxa-content-server/app/scripts/views/confirm_signup_code.js, packages/fxa-content-server/app/scripts/views/mixins/email-opt-in-mixin.js, packages/fxa-content-server/app/scripts/views/post_verify/newsletters/add_newsletters.js, packages/fxa-content-server/app/tests/spec/views/mixins/email-opt-in-mixin.js
- QA found a couple bugs with newsletter flows
- Updates the newsletter labels for the new copy
- Only enabled the subscribe button if a user selects a newsletter
- Set account as verified after verifying session and in the newsletter experiment
Closes: #6254 #6257 #6255
=> fix(newsletter): Various newsletter fixes

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/subscriptions.ts, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js, packages/fxa-payments-server/src/lib/apiClient.test.ts, packages/fxa-payments-server/src/lib/apiClient.ts, packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx, packages/fxa-payments-server/tsconfig.json
Because:
- a customer is required to enter a different, working, credit card
after a failed payment during the subscription to their first product,
so there's no reason to keep the payment method created by the failed
payment
This commit:
- have the Payments frontend call the auth-server to detach the payment
method
Closes: #6336 (FXA-2494)
=> chore(payments): detach payment method on failed first sub payment

packages/fxa-settings/README.md, packages/fxa-settings/src/components/AlertBar/index.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx, packages/fxa-settings/src/lib/hooks.test.tsx, packages/fxa-settings/src/lib/hooks.tsx
We have a handful of hooks and functions that make up AlertBar usage
Consolidates the various hooks and functions we use with AlertBar into a single hook.
Now you can use the `useAlertBar` hook in combination with the `AlertBar` component to...
- Hide, show, and check the visibility of the alert bar
- Set the type and contents of the alert bar
- Use the `success`, `info`, and `error` convenience methods to do the above much quicker
Closes: #6316
=> feat(settings): add useAlertBar hook

packages/fxa-settings/src/components/Modal/index.tsx, packages/fxa-settings/src/components/PageSettings/index.tsx, packages/fxa-settings/src/components/Security/index.stories.tsx, packages/fxa-settings/src/components/Security/index.test.tsx, packages/fxa-settings/src/components/Security/index.tsx, packages/fxa-settings/src/components/UnitRow/index.stories.tsx, packages/fxa-settings/src/components/UnitRow/index.test.tsx, packages/fxa-settings/src/components/UnitRow/index.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.stories.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.test.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx, packages/fxa-settings/src/styles/ctas.scss
- detect Two-step auth and add ability to disable
- created `UnitRowTwoStepAuth` component
- added `SecondaryButtonClassName`,` SecondaryCta`, and `SecondaryModalReveal`
options to UnitRow
- updated Security component, and all tests and stories to reflect
changes
- updated each story touched with `<LocationProvider/>` fix
Closes: #4913 #6327 
=> task(fxa-settings): rework Two-step auth unit row

packages/fxa-content-server/tests/functional/post_verify/account_recovery.js
- This fails every once in a while, ref https://app.circleci.com/pipelines/github/mozilla/fxa/13463/workflows/62f96750-d696-4241-b49e-dcd1e8c3bf71/jobs/192617/steps
- Adds a ready selector after the user clicks submit that should hopefully wait for the tooltip to appear before checking the text content
Connects to #2822
=> fix(tests): fix attempts for intermittent functional test failures

packages/fxa-content-server/app/scripts/views/sign_in_token_code.js
Fixes #6342.
- changes in #6295 might have regressed unverified session handling for the force-2FA flow
- restores the redirect behavior by adding the `redirectTo` parameter check back to the `sign_in_token_code` screen
Closes: #6342
=> fix(totp): Restore unverified session handling in the force-2FA flow

packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/test/local/routes/oauth.js
- We stopped emitting the `flow.complete` metrics for FF80 which we use in amplitue to signal that the user completed the specific action
- For FF 80 we moved to a sync oauth flow and don't call the `/certificate/signed` anypoint anymore, which would have emitted the `account.signed` event.
- Emits the `account.signed` event when an oauth token is created. If the flow has a `flowCompleteSignal=account.signed`, it will emit the `flow.complete` event.
Closes: #6347 
I will be uplifting this to the current train (186) since its metrics related.
=> fix(metrics: Emit the the `flow.complete` event when a user creates an oauth token for sync

packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/test/local/senders/email.js
Because:
- the Intl module throws an exception when given a language tag that does
not conform to BCP 47
This commit:
- handles the exception and use the default 'en-US' instead
Closes: #6312 (FXA-2480)
=> fix(emails): use default lang tag for sub emails when given invalid tag

packages/fxa-auth-server/config/index.ts
Fixes #5143.
Our goal is to get sync access token lifetimes down to six hours, so
that the cross-device metrics resolution is the same as it previously
was, when sync used browserid assertions (with a six hour lifetime). By
keeping the TTL just above six hours, we ensure the tokens are backed by
redis, preserving existing validation behavior.
=> fix(oauth): lower access token lifetimes to six hours plus five minutes

packages/fxa-content-server/app/scripts/views/form.js, packages/fxa-content-server/app/scripts/views/settings/change_password.jsx, packages/fxa-content-server/app/scripts/views/sign_up_password.js
* The "passwords do not match" tooltip is still displayed, even if there is a validation error.
* Check if the input is valid before showing the tooltip.
Closes #3575
=> fix(content-server): validate the sign up input before showing validation error

packages/fxa-auth-server/docs/oauth/api.md, packages/fxa-auth-server/docs/oauth/pairwise-pseudonymous-identifiers.md, packages/fxa-auth-server/lib/oauth/error.js, packages/fxa-auth-server/lib/oauth/jwt_access_token.js, packages/fxa-auth-server/test/oauth/jwt_access_token.js
Refs #5826. [Note: please see the review comments below, as this description is not quite accurate. In particular, enforcing ppid_seed not be passed for a profile grant request is a good edge case to handle, but doesn't fix the underlying issues FPN is encountering.]
- JWT access tokens are intended for use by any RP, not necessarily a trusted RP. PPIDs provide an extra layer of user protection by concealing the user's FxA uid while still enabling untrusted RPs to access resources owned by that user. In particular, PPIDs prevent two evil RPs from comparing user identifiers and correlating a user's behavior across their two services.
- As [mentioned](https://github.com/mozilla/fxa/blob/0ed71f677637ee5f817fa17c265191e952f5500e/packages/fxa-auth-server/fxa-oauth-server/docs/pairwise-pseudonym …
=> fix(oauth): do not issue JWT access tokens that both use PPIDs and grant access to profile scopes

packages/fxa-auth-server/docs/oauth/api.md, packages/fxa-auth-server/docs/oauth/pairwise-pseudonymous-identifiers.md, packages/fxa-auth-server/lib/oauth/error.js, packages/fxa-auth-server/lib/oauth/jwt_access_token.js, packages/fxa-auth-server/test/oauth/jwt_access_token.js
Reverts mozilla/fxa#6368
we'll need to coordinate with FPN before landing this
=> Revert "fix(oauth): do not issue JWT access tokens that both use PPIDs and grant access to profile scopes"

.circleci/config.yml, packages/fxa-content-server/scripts/test-ci-remote.sh, packages/fxa-content-server/tests/functional_smoke.js, packages/fxa-content-server/tests/intern.js
- having a functional test of stage run before further testiing of stage is useful
- adds a job that can be triggered by the api to run tests in stage. (For now; later we can work out a way to automagically trigger test runs)
This will run a smaller suite of tests. In the future I may reintroduce parallelism for that suite.
=> fix(tests): add job to run tests against remote target

.vscode/settings.json, packages/fxa-event-broker/src/health/health.controller.spec.ts, packages/fxa-event-broker/src/health/health.controller.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.spec.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.ts
Because:
* Development mode is used on a deployed stack that doesn't use a
local SQS testing instance.
* lbheartbeat was missing from the health routes.
This commit:
* Checks that the SQS URL includes localhost before turning on the
local SQS dev mode flags.
* Includes a lbheartbeat route.
=> fix(event-broker): include lbheartbeat and dev check

packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/test/local/routes/oauth.js
- Right now, we're not gathering quite enough data with the AET pings to understand if AET is working properly across RPs.
- Adds the client_id to the `oauth.token.created` event.
Closes: #6290
=> fix(metrics): include the client_id when logging the `oauth.token.created` event

packages/fxa-event-broker/src/firestore/firestore.service.spec.ts, packages/fxa-event-broker/src/firestore/firestore.service.ts, packages/fxa-event-broker/src/google-pubsub.service.ts, packages/fxa-event-broker/src/metrics.service.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.ts
Because:
* The env var isn't sufficient to indicate whether local emulators
should be used. Each service has its own config that more clearly
reflects whether it is running in a local-dev env vs. deployed
where remote services are available.
This commit:
* Updates the services to inspect the config such that they can
determine whether to use mock/local emulators or attempt connecting
to actual remote services.
=> fix(event-broker): dont use env for local checks

packages/fxa-content-server/tests/functional/lib/selectors.js
- Recent mozilla.org changes removed the ID on the post-download page that our content-server tests expect to find when exercising various firefox download flows.
- Updates the selector to a new one that the helpful folks on the bedrock team are inserting for us (h/t @craigcook)
Closes: #6411
=> fix(tests): Update the post-download page selector

packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js, packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-webchannel-v1.js, packages/fxa-content-server/app/tests/spec/models/auth_brokers/oauth-webchannel-v1.js, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/tests/functional/sign_up_with_code.js
- We were not emitting the service name with the `fxa_login - complete` amplitude event from pairing
- Sets the service name for oauth-redirect and oauth-webchannel brokers. In local testing the `oauth-redirect` broker is used, but in production its oauth-webchannel.
- Updates the channel server config to point to a valid server
Closes: #5990
I wasn't able to verify this 100% with a real device since building to test apps are a bit difficult at the moment. However, using the functional pairing test, I was able to see an amplitude log with the service set to the oauth clientId, which I think is probably good enough.
=> fix(metrics): Emit the service name with pairing login complete

.github/.codecov.yaml
- The "Unchanged files with check annotations" is still in beta and the comments clutter reviews
- Disables the check
Closes: NA
=> fix(tests): disable codecov beta check annotations

packages/fxa-auth-server/package.json, yarn.lock
* We're using a version of the `web-push` module that defaults to
a legacy encryption scheme.
* The latest release of `web-push` has switched to using a more
modern default encryption scheme.
* It's good to keep dependencies up to date.
* Updates the version of our `web-push` dependency to the latest
release.
Closes: #6434
- ~[ ] If applicable, I have modified or added tests which pass locally.~
- ~[ ] I have added necessary documentation (if appropriate).~
As noted in #6434, there's a small but non-zero chance this will uncover bugs in the `aes128gcm` handling in our push client libraries or in their integration with FxA client code. We'll need to keep an eye out for bustage in send-tab push notifications as part of this change, and it seems worth …
=> Update web-push lib to latest version.

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/subscriptions.ts, packages/fxa-auth-server/lib/routes/support.js, packages/fxa-auth-server/test/local/routes/support.js, packages/fxa-content-server/app/scripts/templates/support.mustache, packages/fxa-content-server/app/scripts/views/support.js, packages/fxa-content-server/app/styles/modules/_chosen.scss, packages/fxa-content-server/app/tests/spec/models/support-form.js, packages/fxa-content-server/app/tests/spec/views/support.js, packages/fxa-content-server/tests/functional/support.js, packages/fxa-shared/subscriptions/metadata.ts, packages/fxa-shared/subscriptions/types.ts, packages/fxa-shared/test/subscriptions/metadata.ts
Because:
- subscribers should be able to select a product specific app/service
on the support form
This commit:
- present product metadata with keys starting with 'support:app:' as
options on a new field in the support form
Closes: #6220 (FXA-2434)
=> feat(subscriptions): add product specific app/service support field

packages/fxa-content-server/tests/server/validation.js
- We were pointing to a broken link that was used in tests
- The tests ensure that we have the correct information in the document, honestly not sure how much value this provides
- It is still a mystery to me why this gives error `browserName` undefined
- Point to correct metrics document
Closes: #6317 
=> fix(tests): Point to correct metrics doc for validation which caused `browserName` unknown

.yarn/plugins/@yarnpkg/plugin-relock.js
updated relock plugin to resolve missing checksums.
ref https://github.com/mozilla-fxa/yarn-plugin-relock/commit/9c2c624556c2bce68a8dec7395a651f90e9bcbb3
- the bot wasn't setting checksums in the lock so we'd get changes locally on `yarn install`
=> chore(deps): updated yarn relock

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/newsletter-sync.js
- We want to enable this experiment
- After merge I will uplift this to the current train 
- Enables the newsletter sync experiment for 50% of sync users
=> chore(experiments): Enable newsletters experiment on 50% of sync users

packages/fxa-event-broker/src/auth/google-jwt-auth.guard.ts, packages/fxa-event-broker/src/auth/googlejwt.strategy.ts, packages/fxa-event-broker/src/pubsub-proxy/pubsub-proxy.controller.spec.ts, packages/fxa-event-broker/src/pubsub-proxy/pubsub-proxy.controller.ts
Because:
* It's possible I named the strategy in the incorrect location when
moving this to NestJS.
* We would like more debug logging to detect details about why a proxy
request may have failed from an RP.
This commit:
* Moves the strategy name so the guard could pick it up.
* Adds more logging to the pubsub controller for additional debugging.
Issue #6458
I spent a bit of time with Lets Encrypt and a Google console to setup the event-broker locally and verify that the auth is working. It is! That means the error is possibly somewhere else in the delivery chain, which we need to verify in our dev environment. So additional logging is included here.
=> fix(event-broker): possible guard fix + logging

packages/fxa-shared/nestjs/health/health.controller.spec.ts, packages/fxa-shared/nestjs/health/health.controller.ts, packages/fxa-shared/nestjs/sentry/reporting.ts, packages/fxa-shared/nestjs/sentry/sentry.interceptor.ts, packages/fxa-shared/nestjs/sentry/sentry.service.ts
Because:
* Sentry relocation didn't clean up reporting functionality from the
service using it.
* We had no way to verify exceptions are thrown and captured by Sentry.
This commit:
* Refactors the sentry reporting functionality so it can be used
directly by other code.
* Adds an __exception__ route with basic trigger protection to avoid
excessive error reporting.
Closes #6454
=> refactor(fxa-shared): cleanup sentry and add exc route

packages/fxa-content-server/tests/functional/settings_change_email.js
Test to recreate an account after deletion using the same primary email.
-
-
@vbudhram please review. Thank you!
=> test(delete-account): add test to recreate an account after deletion using the same email

packages/fxa-auth-server/lib/routes/subscriptions.ts, packages/fxa-auth-server/test/local/routes/subscriptions.js, packages/fxa-content-server/app/scripts/lib/app-start.js, packages/fxa-content-server/app/scripts/models/reliers/relier.js, packages/fxa-content-server/app/scripts/views/mixins/service-mixin.js, packages/fxa-content-server/app/scripts/views/mixins/sync-suggestion-mixin.js, packages/fxa-content-server/app/scripts/views/subscriptions_product_redirect.js, packages/fxa-content-server/app/tests/spec/models/reliers/relier.js, packages/fxa-content-server/app/tests/spec/views/confirm.js, packages/fxa-content-server/app/tests/spec/views/mixins/service-mixin.js, packages/fxa-content-server/app/tests/spec/views/mixins/sync-suggestion-mixin.js, packages/fxa-content-server/app/tests/spec/views/reset_password.js, packages/fxa-content-server/app/tests/spec/views/subscriptions_product_redirect.js, packages/fxa-content-server/tests/functional/subscriptions.js
- also hides "Looking for Firefox Sync?" when headed to payment
fixes #6121
This issue spans a weird slice of FxA auth views and subscription APIs. Opening a draft early before I get tests together, will maybe request some extra eyes on this to see whether this is a terrible hack.
=> feat(payments): display product name in subscription payment signup / signin flow

.yarnrc.yml, packages/fortress/package.json, packages/fxa-admin-panel/package.json, packages/fxa-event-broker/package.json, packages/fxa-payments-server/package.json, packages/fxa-react/package.json, packages/fxa-shared/package.json, packages/fxa-support-panel/package.json, yarn.lock
fixes these:
```
➤ YN0002: │ fxa-shared@workspace:packages/fxa-shared doesn't provide class-transformer@^0.3.0 requested by @nestjs/mapped-types@npm:0.1.0
➤ YN0002: │ fxa-shared@workspace:packages/fxa-shared doesn't provide class-validator@^0.11.1 || ^0.12.0 requested by @nestjs/mapped-types@npm:0.1.0
➤ YN0002: │ @nestjs/graphql@npm:7.6.0 [ace81] doesn't provide class-transformer@^0.2.3 requested by @nestjs/mapped-types@npm:0.0.5
➤ YN0002: │ @nestjs/graphql@npm:7.6.0 [ace81] doesn't provide class-validator@^0.11.1 || ^0.12.0 requested by @nestjs/mapped-types@npm:0.0.5
➤ YN0060: │ @apollo/gateway@npm:0.17.0 [ead0f] provides graphql@npm:15.3.0 with version 15.3.0 which doesn't satisfy ^14.2.1 requested by apollo-graphql@npm:0.4.5
➤ YN0060: │ @apollo/federation@npm:0.17.0 [0cab6] provides …
```
=> chore(deps): fixed yarn dependency warnings

packages/fxa-shared/nestjs/README.md
Because:
* It's nice to have some documentation on using the shared modules.
This commit:
* Add's documentation on configuration and usage of the NestJS shared
modules.
=> docs(fxa-shared): add nestjs module docs

packages/fxa-content-server/app/scripts/views/support.js, packages/fxa-content-server/app/tests/spec/views/support.js
Because:
- the app/service Support Form field is optional
This commit:
- add an empty option to the app/service field
Closes: #6501 (FXA-2552)
=> fix(support form): add empty option for app/service field

packages/fxa-content-server/app/scripts/lib/constants.js, packages/fxa-content-server/app/scripts/views/mixins/connect-another-device-mixin.js, packages/fxa-content-server/app/tests/spec/views/connect_another_device.js
- We should redirect to pairing if user is coming from desktop and signed in
- Adds the `preferences` entrypoint to redirect to pairing
Closes: #6422
=> fix(pairing): Redirect to pairing from fxa desktop preferences entrypoint

packages/fxa-auth-db-mysql/lib/db/patch.js, packages/fxa-auth-db-mysql/lib/db/schema/patch-112-113.sql, packages/fxa-auth-db-mysql/lib/db/schema/patch-113-112.sql, yarn.lock
* We want to be able to tell if an FxA user has an associate Stripe Customer account without having to query Stripe
* Creates the userCustomers table that will be used to associate FxA user ids with Stripe Customer ids
=> feat(db): Create table to store user-customer relationship

packages/fxa-graphql-api/src/lib/auth.ts, packages/fxa-graphql-api/src/test/lib/auth.spec.ts, packages/fxa-settings/src/lib/gql.test.ts, packages/fxa-settings/src/lib/gql.ts
I'm annoyed by the branch name, but whatever. Final changes, from the commit message:
fix(settings): improve GQL error handling to avoid redirect loop
* Update the GQL API server to only return an AuthenticationError if it
received an auth-related 400 or 401 error from auth-server. Otherwise,
just return a generic ApolloError.
* Add tests for the front-end GQL library to be sure this works
correctly.
* Add tests for the front-end GQL lib.
Fixes #6400.
-----
Original description from WIP draft:
The bug is that the gql-api was always returning an auth error, even if the problem was that it couldn't hit auth server. Setting up the (missing) tests for this lib has been a little complex; just looking for some feedback on test harness setup. Mocking out globals vs. wrapping in accessor …
=> fix(settings): improve GQL error handling to avoid redirect loop

packages/fxa-settings/README.md, packages/fxa-settings/src/components/DropDownAvatarMenu/index.test.tsx, packages/fxa-settings/src/components/DropDownAvatarMenu/index.tsx, packages/fxa-settings/src/components/ModalVerifySession/index.test.tsx, packages/fxa-settings/src/components/ModalVerifySession/index.tsx, packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.test.tsx, packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.tsx, packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.test.tsx, packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.test.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx, packages/fxa-settings/src/components/VerifiedSessionGuard/index.tsx, packages/fxa-settings/src/lib/hooks.test.tsx, packages/fxa-settings/src/lib/hooks.tsx
- We perform many mutations and actions across Settings that require error/success messages. Some of the error instances should be reported to Sentry.
- Tries to standardize how we show messages and report errors.
Closes: #6249
Okay, so the goal of this issue was to set a convention for how we handle mutation errors. Here's exactly what I did. I encourage pushback:
- Moved all mutations to our custom `useMutation` hook.
- This hook can be supplied an `onError` function that supplies an `ApolloError` object for you to check for `graphQLErrors`, which should then be rendered in the UI or AlertBar. You can also throw inside this function to send an error to report the error object or another object to Sentry.
- Internally, `onError` will always report …
=> feat(settings): standardize error/success messages and reporting

.circleci/config.yml, packages/fxa-content-server/tests/functional/recovery_key.js, packages/fxa-content-server/tests/functional/settings_v2/settings.js, packages/fxa-content-server/tests/functional_settings_v2.js, packages/fxa-content-server/tests/intern.js, packages/fxa-settings/scripts/test-ci.sh
- We need some basic functional tests to ensure the new settings page loads
- Adds a new test functional test suite to test settings v2 views
- I unfortunately couldn't move helpers to fxa-shared because some of them access libs from content-server. Moving helpers would require a bigger refactor of content-server
- I ended up moving settings functional tests to content-server functional test directory. I think this makes sense because fxa-settings already requires content-server to be running to access it. If we wanted to expand our smoke testing, its really easy to add them to that suite of tests.
Closes: #4851 Fixes #6320
=> chore(tests): Add settings v2 initial functional testing

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* We want to ensure the stripe record is deleted, and subhub has not
been deleting them.
This commit:
* Deletes the stripe customer record on account deletion.
Closes #6493
=> feat(auth-server): delete stripe record

.circleci/config.yml, .gitignore, packages/fxa-content-server/tests/intern.js
Looks like this broke a little while back and we were logging the results for content-server.
Fixes https://github.com/mozilla/fxa/issues/5320
=> fix(tests): Store test results in insights

packages/fxa-payments-server/server/lib/routes/post-metrics.js
Because:
- the payload validation on Payments metrics endpoint was not
validating the flow begin time and the flow id
This commit:
- move the Joi validators into the correct spot
Closes: #6564
=> fix(metrics): fix payload validation for payments metrics

.circleci/config.yml, .github/.codecov.yaml
- Our code coverage metrics are not always accurate
- Adds support for the [carryflags](https://docs.codecov.io/docs/carryforward-flags) which in theory should help. Not 100% sure I set it up correctly since it needs to be merged to master and get a base commit for coverage reports. Doesn't hurt to try
Closes: https://github.com/mozilla/fxa/issues/6086
=> fix(tests): Add carryflags to codecov

packages/fxa-auth-server/.vscode/launch.json, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/scripts/populate-stripe-customer-db.ts, packages/fxa-auth-server/test/scripts/fixtures/account-customers.sql, packages/fxa-auth-server/test/scripts/fixtures/accounts.sql, packages/fxa-auth-server/test/scripts/fixtures/emails.sql, packages/fxa-auth-server/test/scripts/populate-stripe-customer-db.spec.ts, packages/fxa-shared/db/models/auth/index.ts, packages/fxa-shared/test/db/models/auth/index.spec.ts
- To use the accountCustomers table effectively, we need to prepopulate it with Stripe data
- Create script to populate accountCustomers table from existing customers in Stripe
Closes: #6160
=> feat(auth): create script to populate accountCustomers table

packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/fixtures/customer_new.json, packages/fxa-auth-server/test/local/payments/fixtures/customer_new_pmi.json, packages/fxa-auth-server/test/local/payments/fixtures/customer_new_pmi_default_invoice_expanded.json, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-graphql-api/src/config.ts, packages/fxa-shared/db/config.ts
- We want to have a persistent record connection account ids to stripe customer ids
- Adds relationship creation and deletion to the Stripe Customer Creation and Deletion flows
closes: #6161
=> feat(auth): Add Create/Delete for Account-Customer Relationship

packages/fxa-auth-server/test/remote/account_create_tests.js
- Our remote tests start the auth-server, which will now do some additional database connection/migration from https://github.com/mozilla/fxa/pull/6580
- Remote tests are run serially and migrations wont run if they have ran already, therefore probably don't need in other remote tests
- This targets train-190 to unblock it.
- Updates the test timeout to the first functional test to give it a little extra time for these connections
Closes:
=> Increase test timeout to make time for new migration

packages/fxa-admin-panel/README.md, packages/fxa-admin-panel/package.json, packages/fxa-admin-panel/server/config/index.ts, packages/fxa-admin-panel/src/components/EmailBlocks/Account/index.test.tsx, packages/fxa-admin-panel/src/components/EmailBlocks/Account/index.tsx, packages/fxa-admin-panel/src/components/EmailBlocks/index.test.tsx, packages/fxa-admin-panel/src/components/EmailBlocks/index.tsx, packages/fxa-admin-panel/src/index.tsx, packages/fxa-admin-server/README.md, packages/fxa-settings/package.json, yarn.lock
* The admin panel can't connect to the admin server in development
* We use '@apollo/client' in fxa-settings and should be consistent, preferring one package over a lot of separated dependencies
* Changes the gql server port to 8095
* Adds oidc-claim-id-token-email auth header in development
* Removes react-apollo, apollo-boost, apollo-client etc. in favor of @apollo/client
* Includes doc updates for admin-panel and admin-server
* Upgrades @apollo/client version in fxa-settings to be consistent
Closes: #6579 
I realize duplicating `exampleAccountResponse` in `exampleNoResultsAccountResponse` isn't as "clean" as `Object.assign`, but I couldn't get the test passing without changing it to this. I tried a couple other things and kept getting test failures …
=> fix(admin-panel): Fix connection to admin server in dev, remove unneeded Apollo dependencies, update README

packages/fxa-auth-server/config/dev.json, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/test/local/routes/oauth.js
Because:
- the "faked" 'cert_signed' event should have a service name of "sync"
in its event properties when the oauth client is one of the old sync
clients
- the 'account.signed' event should be faked only when sync requests a
token with the "oldsync" scope
This commit:
- add `service: sync` to the event properties for the events in the
/oauth/token handler when "oldsync" is in the scopes and the client
is one of the old sync clients
- emit the 'account.signed' event only when "oldsync" is in the scopes
- set the service to the oauth client in the events except for the
conditions mention in the first bullet
Closes: #6503 (and maybe #6578)
=> fix(metrics): add service name to sync oauth Amplitude events

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/account.js, packages/fxa-auth-server/lib/routes/subscriptions.ts, packages/fxa-auth-server/lib/routes/utils/subscriptions.js, packages/fxa-auth-server/test/local/payments/fixtures/customer1.json, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/account.js
- We want to use our new stored account-customer relationship for determining Stripe calls for customer data
- Implements read-thru and write-thru caching based off of defined relationship in AccountCustomers table
Closes: #6162
=> feat(payments): Use AccountCustomer info for Fetching Customer info

packages/fxa-auth-server/lib/cad-reminders.js, packages/fxa-auth-server/lib/db.js, packages/fxa-auth-server/lib/log.js, packages/fxa-auth-server/lib/metrics/context.js, packages/fxa-auth-server/lib/oauth/grant.js, packages/fxa-auth-server/lib/oauth/routes/verify.js, packages/fxa-auth-server/lib/push.js, packages/fxa-auth-server/lib/pushbox.js, packages/fxa-auth-server/lib/routes/utils/clients.js, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/test/local/metrics/context.js, packages/fxa-auth-server/test/local/push.js, packages/fxa-auth-server/test/local/routes/utils/clients.js, packages/fxa-auth-server/test/local/senders/email.js, packages/fxa-auth-server/test/local/senders/sms.js, packages/fxa-auth-server/test/mocks.js, packages/fxa-auth-server/test/oauth/grant.js, packages/fxa-auth-server/test/oauth/routes/verify.js, packages/fxa-auth-server/test/remote/db_tests.js, packages/fxa-auth-server/test/remote/push_db_tests.js
Because we don't need this level of verbosity for them in production and which are costing us extra storage space and query time.
This lowers the log level of some lines identified by this query:
```
SELECT
jsonPayload.type,
COUNT(*) AS count,
SUM(COUNT(*)) OVER () AS total,
ROUND(COUNT(*) / SUM(COUNT(*)) OVER (),4) AS percentage
FROM
`moz-fx-fxa-prod-0712.fxa_prod_logs.docker_fxa_auth_20200928`
GROUP BY
1
ORDER BY
4 DESC;
```
=> chore(logs): lower the log level of some lines

packages/fxa-auth-server/config/dev.json
* Firefox Desktop will soon be able to calculate the ecosystem_user_id as part
of its logn flow (https://bugzilla.mozilla.org/show_bug.cgi?id=1647588)
* Calculating this value the right way means deriving it like a scoped key,
and the FxA server controls wht scoped-key metadata is available to whic
clients.
* Allows the ecosystem_telemetry scope for the Firefox Desktop OAuth
client in dev environments.
* Accompanies the production change requested in
https://bugzilla.mozilla.org/show_bug.cgi?id=1668972
Closes: https://bugzilla.mozilla.org/show_bug.cgi?id=1668972 (for dev environments)
- ~~[ ] If applicable, I have modified or added tests which pass locally.~~
- ~~[ ] I have added necessary documentation (if appropriate).~~
=> chore(config): Allow Firefox Desktop to request ecosystem telemetry scope

packages/fxa-content-server/app/styles/modules/_cropper.scss
The mask on photos uploaded in the settings is not positioned correctly over the photo in RTL languages.
Adds CSS that places the mask on the right location for both LTR and RTL languases.
Before:
After:
This pull request is related to #5169 but the fix is actually for the current settings page, not the new one. I have another PR in the works that will address the new settings page
=> fix(fxa-settings): fix photo mask on RTL

packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/PageDisplayName/index.stories.tsx, packages/fxa-settings/src/components/PageDisplayName/index.test.tsx, packages/fxa-settings/src/components/PageDisplayName/index.tsx
Because:
- new settings need a page for updating the display name
This commit:
- add a (not-yet-functional) form for the display name
Closes: #4955 
=> feat(settings): add display name page

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
- Now that we store the customer-account relationship, we don't have to have forever cache
- Establishes a ttl for customer records in redis
Closes #6163
=> feat(payments): set cache ttl on customers in redis

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/emails.js, packages/fxa-auth-server/lib/routes/subscriptions.ts
The keys for the fields to expand on a customer call are different from a customer list call. The 'data' prefix for the key needs to be dropped.
=> bug(payments): bad stripe expand fields

packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.test.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx
- fixes the placement of secondary email msg in UnitRow
Closes: #6370
=> bug(fxa-settings): fix secondary email msg placement

packages/fxa-settings/src/components/PageDisplayName/index.test.tsx, packages/fxa-settings/src/components/PageDisplayName/index.tsx
Because:
- the disabled state of the save button should be based on the input
value of the display name
This commit:
- update the disabled attr of the save button when the display name
input value changes
Closes: #4954 
=> feat(settings): update save btn state on display name input

packages/fxa-auth-server/lib/metrics/events.js, packages/fxa-auth-server/test/local/metrics/events.js
Noticed this while creating signin/signup papercut milestone, we really don't need this to be `error` since it really isnt.
Fixes #5306
Fixes #3580
=> fix(log): Update metrics error log to trace

packages/fxa-content-server/tests/functional/lib/helpers.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/settings_v2/change_password.js, packages/fxa-content-server/tests/functional/settings_v2/settings.js, packages/fxa-content-server/tests/functional_settings_v2.js, packages/fxa-settings/src/components/InputPassword/index.tsx, packages/fxa-settings/src/components/InputText/index.tsx, packages/fxa-settings/src/components/PageChangePassword/index.test.tsx, packages/fxa-settings/src/components/PageChangePassword/index.tsx, packages/fxa-settings/src/components/Profile/index.tsx, packages/fxa-settings/src/components/UnitRow/index.tsx
- We don't have functional tests in the new beta settings page
- Adds functional tests for change password in beta settings
- Adds a helper method `formatDataTestId` that prepends a value to the `data-testid` field so that it is unique
Closes: #4858
=> fix(tests): Add change password functional test for beta settings

packages/fxa-customs-server/package.json, yarn.lock
Merged the dependabot PR to update this, but then realized we don't really use it.
=> chore(deps): Remove unused npmshrink dev dep

_dev/docker/circleci/Dockerfile, packages/fxa-content-server/scripts/test-ci.sh
Another small fix I found while making papercut milestone.
=> chore(test): Remove custom firefox build for pairing tests

packages/fxa-settings/src/components/AppLayout/index.test.tsx, packages/fxa-settings/src/components/InputText/index.tsx, packages/fxa-settings/src/components/PageChangePassword/index.tsx, packages/fxa-settings/src/components/PageDisplayName/index.test.tsx, packages/fxa-settings/src/components/PageDisplayName/index.tsx, packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.tsx, packages/fxa-settings/src/constants/index.tsx
Because:
- new settings should save the account's new display name
This commit:
- save the new display name with gql-api
- allow empty display name (delete)
Closes: #4956 
=> feat(settings): update display name

packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/InputText/index.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.stories.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.test.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
Because:
- we need to scaffold the two step auth page
This commit:
- add the two step auth page
Closes: #4968 
=> feat(settings): add two step authentication page

packages/fxa-settings/src/lib/metrics.ts
fixes #6652
The startTime function of metrics throws an error on mobile safari. Try/catch is better here than trying to sniff for availability.
... the page looks like garbage but it renders. 🤷
=> fix(settings): fix mobile safari failing to render new settings

packages/fxa-auth-server/lib/oauth/routes/authorization.js, packages/fxa-auth-server/lib/oauthdb/create-authorization-code.js
fixes #6703
Depending on the url parameters AMO redirects are exceeding 256 characters for state. There's no harm in extending this limit.
=> fix(oauth): increase `state` size limit for oauth requests

packages/fxa-settings/src/components/HeaderLockup/index.tsx
- Moves the `onClick` handler up to parent element to solve the issue of menu not closing on mobile when selecting an anchor link.
Closes: #6638 
=> fix(fxa-settings): mobile nav toggle visibility

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/subscriptions.ts, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions.js, packages/fxa-shared/db/models/auth/index.ts, packages/fxa-shared/test/db/models/auth/index.spec.ts
Because:
- we should add a Stripe customer to the local DB when a customer is
created on Stripe
This commit:
- handle the 'customer.created' webhook event from Stripe by inserting
into the local DB if that account does not already have a record
Closes: #6689 
=> feat(subscriptions): handle 'customer.created' Stripe event

packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
- Adds a bit of margin-left to the refresh button(same amount applied between normal buttons `ml-2`) so it doesn't look odd when focused
Closes: #6651 
=> fix(fxa-settings): add refresh button margin

packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-settings/src/components/Checkbox/index.tsx, packages/fxa-settings/src/components/ConnectedServices/Service.tsx, packages/fxa-settings/src/components/ConnectedServices/index.test.tsx, packages/fxa-settings/src/components/ConnectedServices/index.tsx
Fixes #5099.
- We want to show a confirmation modal when the user clicks the 'sign out' button on a sync device in the new-settings connected services list
- Displays a modal when 'sign out' is clicked on a connected service item. 
- The issue description mentions pulling the sync disconnect survey from "the relevant content-server files". Where exactly are these files?
- Should I modify the `Checkbox` component to allow me to pass in styling for the checkbox labels, or should I just use extra specificity to override the default label size? What's the right Tailwind-y React-y approach here?
- The specs show device specific info in the modal text. What's the nicest way to pass the specific device info back to the parent component, so that it passes this into the modal? Can I pass device …
=> Show modal on connected services 'sign out' click

packages/fxa-settings/README.md
Because:
- the old index is no longer updated
This commit:
- replace old with new
=> chore(docs): update storybooks index for settings

packages/fxa-settings/package.json, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.test.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx, packages/fxa-settings/src/lib/totp.ts, yarn.lock
Because:
- the user need to enter a valid auth code
- the user should save recovery codes
This commit:
- verify the code from the user's authenticator app
- display the recovery codes
Closes: #4973 
- [x ] If applicable, I have modified or added tests which pass locally.
=> feat(settings): add step 2 of two step auth

packages/fxa-settings/src/components/PageDisplayName/index.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/_mocks.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.test.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx
Because:
- we need to verify a recovery code and enable two step auth as the
last step in the enabling two step auth
This commit:
- check the recovery code and then verify the totp with gql-api
Closes: #4976 
=> feat(settings): verify recovery code and enable two step auth

packages/fxa-settings/src/components/PageTwoStepAuthentication/index.test.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx
Because:
- we should let the user know that 2fa was successfully enabled
This commit:
- display a message on the main settings page after enabling 2fa
Closes: #4977
=> feat(settings): show 2fa enabled message

packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/_mocks.tsx, packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.stories.tsx, packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.test.tsx, packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.test.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
Because:
- users might want to replace their 2fa recovery codes
This commit:
- add the page to get and display the new recovery codes
Closes: #4978 
=> feat(settings): add replace 2fa recovery codes page

packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
Because:
- the two step auth button always go to the replace recovery codes page
This commit:
- fix the routes
In a previous commit, instead of adding an additional route for the
replace recovery code page, the single existing route was incorrectly
updated.
Fixes a bug introduced in #6767
=> fix(settings): fix two step auth route

packages/fxa-settings/src/components/Tooltip/index.tsx
=> fix(settings): use non-interpolated classnames on tooltip

.circleci/build.sh, packages/fxa-auth-server/Dockerfile
- We're using `fxa-mono` in production and don't need images for each service anymore.
- Eliminates the build step that generates the default individual images. Custom dockerfiles and build scripts are still run.
=> chore(build): stop building docker images for each service by default

packages/fxa-settings/src/components/GetDataTrio/index.tsx
- finishes up #4975, by correcting the formatting for COPY, PRINT, and DOWNLOAD functionality of the recovery codes.
Closes: #4975
The main change here is in that we are now creating a template for the print file in function `recoveryCodesPrintTemplate`.
also we are joining the arrays with ` \r\n`, two things we were doing in the content server. I'm a little unsure of a reliable way to test the template as it is just a string. Also not sure if we need to be testing a template like this, it may be redundant. Happy to take input of the reviewer on whatever we think is correct.
=> fix(fxa-settings): format 2fa recovery codes for export

packages/fxa-settings/src/components/PageChangePassword/PasswordValidator.ts, packages/fxa-settings/src/components/PageChangePassword/index.tsx
This ports the, frankly, obscure password rules from `password_strength_balloon.js` to new settings. Whatevs 🤷‍♂️ 
fixes #6779
=> fix(settings): port old settings pwd validation rules

packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/ScrollToTop/index.tsx
Because:
- a new page should start at the top
This commit:
- scroll to the top when a user navigates to a new page (but not when
back/forward with browser history)
Closes: #6778
=> fix(settings): scroll to top on navigation

packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/settings_v2/display_name.js, packages/fxa-content-server/tests/functional/settings_v2/lib/helpers.js, packages/fxa-content-server/tests/functional/settings_v2/navigation.js, packages/fxa-content-server/tests/functional_settings_v2.js, packages/fxa-content-server/tests/intern.js
- `This PR is for ticket FXA-1560 for add/change/remove Display name`
- `Another change is to add the config set up for Settings V2 url`
- `I also added a helper function which have steps to create user, email and login and then redirect to Settings page`
- `This PR closes task FXA-1560`
@mozilla/fxa-devs please review. Thanks!
=> tests(Settings_V2): add tests for display name, config and helper functions for settings 

packages/fxa-settings/src/styles/unit-row.scss
- Sets a min-width to the unit-row-header so that we don't have misalignment in the 2fa section
Closes: #6795
=> fix(fxa-settings): fix 2fa unit row alignment

packages/fxa-settings/src/components/PageChangePassword/index.test.tsx, packages/fxa-settings/src/components/PageChangePassword/index.tsx, packages/fxa-settings/src/lib/auth-errors.ts
Because:
- some users enter the old password as the new password during a
password change...?
This commit:
- ask the user to enter a new password that is not the old password
Closes: #6788 
=> fix(settings): show error when new password = old

packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/app/scripts/templates/settings.mustache, packages/fxa-content-server/app/styles/modules/_settings.scss, packages/fxa-settings/src/components/HeaderLockup/index.tsx
- Adds links to fxa-content-server settings header and fxa-settings header to link to and from beta settings
Closes: #5072 
=> task(fxa-settings): add beta and classic settings links

packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/settings_v2/recovery_key.js, packages/fxa-content-server/tests/functional_settings_v2.js
`- added tests for creating recovery key with valid password`
`- verifying error message when entered invalid password`
`- revoking recovery key`
`This PR closes task FXA-1564`
@mozilla/fxa-devs @rbillings please review. Thank you!
=> Create test for adding and revoking a recovery key

packages/fxa-content-server/package.json, packages/fxa-content-server/tests/functional/lib/helpers.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/settings_v2/secondary_email.js, packages/fxa-content-server/tests/functional_settings_v2.js
Because:
- we should verify that the secondary email feature is working in new
settings
This commit:
- add functional test for secondary email feature in new settings
Closes: #4854, #4855 
=> test(settings): add secondary email functional tests

packages/fxa-event-broker/src/client-capability/client-capability.service.spec.ts, packages/fxa-event-broker/src/client-capability/client-capability.service.ts, packages/fxa-event-broker/src/pubsub-proxy/pubsub-proxy.controller.ts, packages/fxa-shared/nestjs/error.ts
Because:
* We would like to see the originating error in the caught location
when thrown by axios.
This commit:
* Adds a helper exception that appends an original error context when
throwing.
* Properly captures and re-throws the error during start-up in the
event-broker.
Fixes #6872
=> feat(event-broker): capture error context

packages/fxa-content-server/server/config/surveys.json
- reset password survey has been out there for a long time
- stop showing the survey to selected users
=> chore(surveys): remove reset password survey

packages/fxa-content-server/tests/functional/lib/helpers.js
Because:
- the error might be less confusing when someone tries to use one of those helpers from those returned by `helpersRemoteWrapped` or `applyRemote`
=> chore(tests): remove string helpers from helpersRemoteWrapped and applyRemote

packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx
fixes #6890
Instead of a full modal I just went with showing the secret inline once you click the link.
@pwalm is this ok?
=> feat(settings): added "Can't scan code?" option to 2fa setup

packages/fxa-settings/src/components/FlowContainer/index.test.tsx, packages/fxa-settings/src/components/FlowContainer/index.tsx
Because:
- sometimes popping the browser's history stack isn't what QA or UX
expects
This commit:
- allow a callback function to be passed in to handle the click event
Closes: #6937 
=> refactor(settings): allow callback override of FlowContainer's back button

packages/fxa-settings/src/components/PageTwoStepAuthentication/index.test.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx
Because:
- the flow container's back button should move the user back a step on
the 2fa form
This commit:
- pass a handler to the flow container for the expected back button
behavior
- change the form's Back button on step 3 to a Cancel button
Closes: #6898 
=> feat(settings): nav backwards on 2fa form

packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/server/config/surveys.json, packages/fxa-content-server/server/lib/routes/get-frontend.js, packages/fxa-settings/src/components/HeaderLockup/index.tsx
Because:
- we want to learn why people prefer old settings to new
This commit:
- configure a new settings opt-out survey
- add a new route on content-server where the survey will be displayed
to selected users
Closes: #6880 
=> feat(content-server): add new settings opt-out survey

packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx
- adds forgotten word to copy of authenticator flow step
Closes: #6888
=> fix(fxa-settings): add forgotten work in authenticator flow copy

packages/fxa-settings/src/components/ConnectedServices/MOCK_SERVICES.js, packages/fxa-settings/src/components/ConnectedServices/Service.tsx, packages/fxa-settings/src/components/ConnectedServices/index.test.tsx, packages/fxa-settings/src/components/ConnectedServices/index.tsx
Because:
- connected OAuth RPs should be able to sign out
This commit:
- restore the sign out for OAuth RPs
Closes: #6936 
=> fix(settings): restore the sign out button for OAuth RPs

packages/fxa-content-server/tests/functional/lib/helpers.js, packages/fxa-content-server/tests/functional/settings_v2/change_password.js, packages/fxa-content-server/tests/functional/settings_v2/external_links.js, packages/fxa-content-server/tests/functional/settings_v2/navigation.js, packages/fxa-content-server/tests/functional/settings_v2/settings.js, packages/fxa-content-server/tests/functional/subscriptions.js, packages/fxa-settings/scripts/test-ci.sh
- Adds the subscriptions link test back to functional settings v2 tests
- cleans up some duplication around functional tests for settings v2 and content server tests
Closes: #4856 
=> task(fxa-settings): add subscriptions link test

packages/fxa-content-server/app/scripts/templates/settings.mustache, packages/fxa-content-server/app/scripts/views/settings.js
- Checks for `en-US` before rendering the beta settings link in fxa-content-server
Closes: #6909
=> task(fxa-content-server): render beta link for en-US

packages/fxa-graphql-api/package.json, packages/fxa-graphql-api/src/lib/server.ts, yarn.lock
This is a stop-gap implementation of query complexity handling for #6876 with a hard coded limit of 100. The most complex query for new settings is currently 38. This should prevent the huge amplification mentioned in the issue, but we should revisit and have a more thorough design before leaving beta.
I've tested this locally and it indeed blocks queries over the complexity limit. Time permitting I'll add a test case.
=> feat(gql-api): limit query complexity

packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/sign_up.js
- mozilla.org changed their css
- changes the assertion to use the utm parameter in our href, something we control.
=> fix(content): fix test that relied on a css selector from mozilla.org

packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/test/local/routes/oauth.js
When an oauth-based mobile sync device signs in, we're not seeing the corresponding `fxa_login - complete` metrics event that should mark the login, an event which includes the updated count of active sync devices per day for that user. Building on the changes in #6383 and #6581, I think we need to fire the 'account.signed' event when mobile browsers request the oldsync token, which will trigger the flow complete signal that fires the `fxa_login - complete` event (see #6347).
There's also a change here to avoid firing the 'account.signed' event if a 'profile' scoped token is requested, in a first step towards reducing the number of inaccurate device counts recorded in our metrics (see #6578), but I'm thinking we might want to remove that commit, since it's not strictly needed to address …
=> Restore mobile sync device counts by firing a flow complete event for mobile browsers

docs/adr/0023-paypal-support.md
Because:
* We want to document our Paypal integration approach.
This commit:
* Add's an ADR around how we plan to implement PayPal in FxA.
Closes #6924
=> docs: add paypal adr

packages/fxa-graphql-api/src/config.ts, packages/fxa-graphql-api/src/gql/gql.module.ts, packages/fxa-graphql-api/src/main.ts
Because:
* We want to enforce CORS origin on requests.
This commit:
* Adds a corsOrigin configuration value used the same as in the auth
server.
Closes #6875
=> feat(gql-api): add cors

packages/fxa-admin-server/src/app.module.ts, packages/fxa-graphql-api/src/app.module.ts, packages/fxa-graphql-api/src/gql/gql.module.ts, packages/fxa-shared/nestjs/sentry/reporting.ts, packages/fxa-shared/nestjs/sentry/sentry.plugin.ts, packages/fxa-shared/package.json, yarn.lock
Because:
* Interceptors for NestJS do not capture field resolvers due to how
apollo-server runs the query/mutation before then running separate
queries to resolve fields.
This commit:
* Hooks into an apollo-server request lifecycle hook made for error
reporting to accurately report errors to Sentry that occur when
resolving fields.
Closes #7059
=> fix: capture GraphQL errors in field resolvers

packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/routes/oauth/client/get.js, packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/lib/routes/oauth/proxied.js, packages/fxa-auth-server/lib/routes/oauth/verify.js, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/lib/senders/index.js, packages/fxa-auth-server/lib/senders/oauth_client_info.js, packages/fxa-auth-server/lib/server.js
Because:
- we want less indirection with our OAuth routes
This commit:
- move the /client/{client_id} route
Closes: #7054 
=> refactor(oauth): move /client/{client_id} route

packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/lib/routes/oauth/key_data.js
Because:
- we want oauth routes better integrated into auth-server
This commit:
- move the /key-data route
Closes: #7053
=> refactor(oauth): move /key-data route

packages/fxa-auth-server/lib/routes/oauth/authorization.js, packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/lib/routes/oauth/redirect.js
Because:
- we want oauth routes better integrated into auth-server
This commit:
- move the GET and POST /authorization routes
- copy some route config modifying logic from oauth/routes
Closes: #7052
=> refactor(oauth): move GET and POST /authorization routes

packages/fxa-auth-server/lib/routes/oauth/destroy.js, packages/fxa-auth-server/lib/routes/oauth/index.js
- Moves the oauth destroy route to auth-server
Closes: #7094
=> chore(oauth): move oauth destroy route to auth server

packages/fxa-auth-client/server.ts, packages/fxa-graphql-api/pm2.config.js, packages/fxa-graphql-api/src/auth/auth.module.ts, packages/fxa-graphql-api/src/auth/gql-customs.guard.ts, packages/fxa-graphql-api/src/auth/session-token.strategy.spec.ts, packages/fxa-graphql-api/src/auth/session-token.strategy.ts, packages/fxa-graphql-api/src/config.ts, packages/fxa-graphql-api/src/gql/account.resolver.spec.ts, packages/fxa-graphql-api/src/gql/account.resolver.ts, packages/fxa-graphql-api/src/gql/gql.module.ts, packages/fxa-graphql-api/src/gql/session.resolver.spec.ts, packages/fxa-graphql-api/src/gql/session.resolver.ts, packages/fxa-graphql-api/src/main.ts, packages/fxa-graphql-api/tsconfig.json, packages/fxa-shared/db/models/auth/index.ts, packages/fxa-shared/db/models/auth/session-token.ts, packages/fxa-shared/nestjs/customs/customs.module.ts, packages/fxa-shared/nestjs/customs/customs.service.ts, packages/fxa-shared/package.json, packages/fxa-shared/test/db/models/auth/index.spec.ts, yarn.lock
Because:
* We want to limit query/mutations by uid/ip using customs.
This commit:
* Alters the session token verification to use a direct db query to load
the session data from the auth database so the email is available for
use with customs check.
* Adds a Gql customs check that queries customs for the given
class/method.
Closes #6876
=> feat(gql-api): add customs check on query/mutations

packages/fxa-settings/src/components/ScrollToTop/index.tsx
Because:
- we have some logic for scrolling to the top of the page when the user
navigates to a new route
This commit:
- account for the hrefs with a hash and let the browser does its default
thing
Closes: #7015
=> fix(settings): scroll to element id in url hash

packages/fxa-graphql-api/src/auth/gql-auth.guard.ts
Because:
* The complexity analysis doesn't seem to notice queries done in the
query string.
This commit:
* Rejects requests that include a query param in the query string.
Issue #6876
=> fix(gql-api): disallow query in query string

packages/fxa-graphql-api/src/auth/session-token.strategy.spec.ts, packages/fxa-graphql-api/src/auth/session-token.strategy.ts
Because:
* When switching token lookup, verification was accidentally required.
This commit:
* Allows unverified tokens to proceed for lookup to match existing
settings page behavior.
=> fix(graphql-api): allow unverified sessions

packages/fxa-content-server/app/scripts/views/mixins/cached-credentials-mixin.js, packages/fxa-content-server/app/scripts/views/mixins/signin-mixin.js, packages/fxa-content-server/app/tests/spec/views/mixins/cached-credentials-mixin.js
- If a user has 2FA and is using a cached credential to login, they won't be redirected to the enter 2FA code page
- Fixes this issue by checking for 2FA in cached creds mixin and setting the account property that would redirect to the correct page on login
Closes: NA
=> fix(2fa): Fixed cached creds and 2fa redirecting to verify account page

packages/fxa-auth-server/lib/oauthdb/index.js, packages/fxa-auth-server/lib/routes/auth-schemes/refresh-token.js, packages/fxa-auth-server/lib/server.js, packages/fxa-auth-server/test/local/routes/auth-schemes/refresh-token.js, packages/fxa-auth-server/test/mocks.js
- part of #5167
-  pulls out the `oauthdb.checkRefreshToken` thread
=> refactor(oauth): remove oauthdb.checkRefreshToken

packages/fxa-settings/src/index.tsx
Because:
- we are not using the Sentry dsn
This commit:
- init Sentry after the config's ready
Closes: #7140
=> fix(settings): use Sentry dsn after config's loaded

packages/fxa-admin-server/src/main.ts
Because:
* We want to log the correct IP of the accessing request.
This commit:
* Sets the IP correctly for remote requests.
Closes #5904
=> feat(admin-server): record x-forwarded-for correctly

packages/fxa-auth-server/lib/devices.js, packages/fxa-auth-server/lib/oauth/validators.js, packages/fxa-auth-server/lib/oauthdb/index.js, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/lib/routes/oauth/destroy.js, packages/fxa-auth-server/lib/routes/oauth/proxied.js, packages/fxa-auth-server/test/client/api.js, packages/fxa-auth-server/test/local/devices.js, packages/fxa-auth-server/test/local/routes/oauth.js, packages/fxa-auth-server/test/mocks.js, packages/fxa-auth-server/test/remote/oauth_tests.js
- part of #5167
- pulls out the `oauthdb.revokeAccessToken`, `oauthdb.revokeRefreshToken`, and `oauthdb.revokeRefreshTokenById` threads
- adds `introspect` to the test client api
=> refactor(oauth): remove oauthdb destroy functions

packages/fxa-auth-db-mysql/lib/db/patch.js, packages/fxa-auth-db-mysql/lib/db/schema/patch-113-114.sql, packages/fxa-auth-db-mysql/lib/db/schema/patch-114-113.sql
Because:
* We want to be able to tell if an FxA user has an associated PayPal billing agreement without having to query PayPal
This Commit:
* Creates the paypalCustomers table that will be used to associate FxA user ids with PayPal billing agreements
Closes #7031
=> feat(db): Create table to store PayPal customer information

packages/fxa-auth-server/lib/routes/account.js, packages/fxa-auth-server/package.json, packages/fxa-auth-server/test/local/devices.js, packages/fxa-auth-server/test/local/ip_profiling.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/local/routes/attached-clients.js, packages/fxa-auth-server/test/local/routes/devices-and-sessions.js, packages/fxa-auth-server/test/local/routes/emails.js, packages/fxa-auth-server/test/local/routes/password.js, packages/fxa-auth-server/test/local/routes/security-events.js, packages/fxa-auth-server/test/local/routes/sign.js, packages/fxa-auth-server/test/local/routes/subscriptions.js, packages/fxa-auth-server/test/local/routes/support.js, packages/fxa-auth-server/test/local/routes/unblock-codes.js, packages/fxa-auth-server/test/mailer_helper.js, packages/fxa-auth-server/test/remote/db_tests.js, packages/fxa-auth-server/test/remote/push_db_tests.js, yarn.lock
The fxa-auth-server was depending on an ancient version of the `uuid` module.
Upgrades the `uuid` module dependency to benefit from the project-global cache.
Closes: _n/a_
=> [fxa-auth-server] Upgrade uuid dependency

packages/fxa-content-server/tests/functional/oauth_sign_in_token_code.js
- Flaky tests
- Checks for the error tooltip to appear before asserting the text in tooltip
Closes: #6513
=> fix(test): Fix flaky oauth signin test

packages/fxa-auth-server/lib/routes/totp.js, packages/fxa-auth-server/test/local/routes/totp.js
Retrying the fix for #7111 at the right level: when 2FA is removed from the account, immediately downgrade the session. 
- AMO requires developers to have 2FA enabled.
- To minimize friction, AMO first logs the user in, then checks their developer state against the user's Firefox Account 2FA state, and if 2FA is not enabled on a developer account, redirects back to the FxA using the [`prompt=none` flow](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/oauth/prompt-none.md) and the user is prompted to enable 2FA in an inline flow, redirecting back to AMO when done.
- In the edge case where a user sets up 2FA, then logs out of AMO, then disables 2FA, then logs back in to AMO, the user gets trapped in a redirect loop (#6762)
- The redirect occurs because, as outlined in …
=> fix(totp): downgrade session to email-based verification after TOTP is removed

packages/fxa-shared/nestjs/sentry/reporting.ts
Because:
* HttpExceptions are for flow control to halt request processing and
return a result, not actual errors that should be reported to Sentry.
This commit:
* Does not report HttpException type errors.
Closes #7067
=> fix(shared): don't report NestJS HttpExceptions

packages/fxa-content-server/tests/functional/settings_v2/external_links.js
- The external links functional tests were broken
- Updates the test to not use `async` because it wouldn't have [access to the scope](https://theintern.io/docs.html#Intern/4/api/lib%2FTest/skip) that contains the `skip` method.
Closes: #7096
=> fix(test): Fix settings v2 external link test

packages/fxa-content-server/app/scripts/lib/email-domain-validator.js, packages/fxa-content-server/app/tests/spec/lib/email-domain-validator.js, packages/fxa-content-server/server/lib/routes.js, packages/fxa-content-server/server/lib/routes/validate-email-domain.js, packages/fxa-content-server/tests/server/routes/validate-email-domain.js
-
-
Closes: #5896 
@chenba 
Fixxed all the requirements in the fxa-content-server for both the front and backend. As well added the required test cases in both the front and backend . Also one more question that I am unable to add the reviewers  since I am missing the reviewers section. Maybe I don't have the required permissions.
=> chore(fxa-content-server): apply the MX record validation feature flag to the validate-email-domain endpoint

packages/fxa-auth-server/lib/routes/defaults.js, packages/fxa-auth-server/lib/routes/index.js
because token server still uses it
see https://github.com/mozilla/fxa/pull/7113#issuecomment-753505539
=> refactor(oauth): add /config route back

packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/settings_v2/connected_services_oauth_clients.js, packages/fxa-settings/src/components/ConnectedServices/index.tsx, packages/fxa-settings/src/components/Profile/index.tsx, packages/fxa-settings/src/components/Security/index.tsx, packages/fxa-settings/src/styles/tailwind.scss
Because:
- settings has a fixed heaer that covers up content
This commit:
- account for the height of the header when navigating to a section
with an anchor
Closes: #7016
=> fix(settings): account for header height on anchor jump

packages/fxa-admin-server/src/app.module.ts, packages/fxa-event-broker/src/app.module.ts, packages/fxa-graphql-api/src/app.module.ts, packages/fxa-support-panel/src/app.module.ts
Because:
* Version is not a valid Sentry Config parameter, but oddly was not
caught by the type-checker.
This commit:
* Uses the `release` property to correctly specify the project release.
=> fix: use proper Sentry arguments

packages/fxa-graphql-api/src/gql/account.resolver.ts, packages/fxa-graphql-api/src/gql/lib/error.ts
Because:
- new settings was receiving JSON as error messages
This commit:
- restore the decorator that was used to catch and re-throw errors
prior to the NestJS conversion
Closes: #7128
=> fix(gql-api): restore CatchGatewayError decorator

packages/fxa-content-server/server/config/surveys.json
- sets our rate to 1 for showing the settings survey
Closes: #7171
=> task(fxa-content-server): show settings survey for all

packages/fxa-content-server/server/bin/fxa-content-server.js
Adding this to get more info about the request that is causing https://sentry.prod.mozaws.net/operations/fxa-content-server-prod/issues/6602579/events/latest/
- adds a log with query and url info for joi validation errors.
refs #3718 
Need to check with @jbuck to see how we will be able to access this once it is in production. Additionally we may be able to avoid this patch if I can get access to see `fxa-content-server.server.routes.validation.failed` in our logs. Waiting to hear back from @ckolos on that. It's the holidays so we may not get answers until after the break.
=> task(fxa-content-server): add log to track down entrypoint sentry error

packages/fxa-react/components/Head/index.stories.tsx, packages/fxa-react/components/Head/index.tsx, packages/fxa-react/package.json, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/FlowContainer/index.tsx, yarn.lock
- In the original settings page the page title is updated when navigating to different subsections
- Based on https://github.com/mozilla/experimenter/pull/4126
- Updates the page title when navigating to a subsection based on the `FlowContainer` title
- Defaults to `Firefox Accounts` if no title is passed
Closes: #7210
=> feat(head): Add react-helmet to update page title

packages/fxa-content-server/app/scripts/lib/app-start.js
- entrypoint_experiment and entrypoint_variation weren't being passed
from frontend to amplitude
Closes: #6925
=> fix(fxa-content-server): pass params to amplitude

packages/fxa-settings/package.json, packages/fxa-settings/src/components/ConnectedServices/index.tsx, packages/fxa-settings/src/components/PageChangePassword/index.tsx, packages/fxa-settings/src/components/PageDisplayName/index.tsx, packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx, packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.tsx, packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.test.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.test.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx, packages/fxa-settings/src/lib/cache.ts, packages/fxa-settings/src/models/Account.ts, packages/fxa-settings/src/models/_mocks.tsx, yarn.lock
Because:
- querying everything for an account when reloading the state of
recovery key, two step auth, or connected services incur unnecessary
costs
This commit:
- use reload queries that only query gql-api for what they need
The most impactful change is actually the 'keyFields' configuration for
Account in the InMemoryCache's 'typePolicies'.  It allows the query
results from the reloads to be automagically merged into the cache.
(The value of 'keyFields' is set to '[]', making the cached account a
singleton.)
However, setting 'keyFields' affected the `cache.modify` calls to update
the cached account.  The account passed into the field modifier function
is now a Reference, not a plain object, thus breaking the "clone object
then merged in updated properties" pattern.
Setting the proper …
=> refactor(settings): limit queried data for reloads

.gitignore, _dev/README.md, _scripts/base-docker.sh
I want to avoid running into NPM rate limiting or I am required to use a proxy for outgoing HTTP(S) connections.
Introduces generic support to allow adding environment variables inside Docker image builds by sourcing the file `_dev/local-build-env.sh` if available locally (ignored by Git) and exporting all defined variables, so that they become visible to sub-processes of the build process.
One use case is to configure proxy URL's (e.g. standard HTTP or for NPM, YARN, aso.). The following is an example configuration for the newly supported file:
```bash
npm_config_http_proxy="https://npm-proxy.mycorp.localdomain:9876"
npm_config_https_proxy="https://npm-proxy.mycorp.localdomain:9876"
yarn_http_proxy="https://npm-proxy.mycorp.localdomain:9876" …
```
=> Support custom environment variables inside Docker builds

packages/fxa-graphql-api/src/main.ts
Because:
- we want to disable unused HTTP methods on gql-api
This commit:
- update CORS config to allow only OPTIONS and POST
Closes: #6874
=> chore(gql-api): allow fewer CORS HTTP methods

packages/fxa-content-server/server/lib/beta-settings.js, packages/fxa-content-server/tests/functional/lib/helpers.js, packages/fxa-content-server/tests/functional/settings_v2/external_links.js, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/Nav/index.test.tsx, packages/fxa-settings/src/components/Nav/index.tsx, packages/fxa-settings/src/index.tsx, packages/fxa-settings/src/lib/config.ts
Because:
- the Email Communications link on the nav was not working
This commit:
- encode the email in the link
- pass the configured email communication URL to the client
- add a ConfigContext with a hook for accessing the config
Closes: #6562
=> fix(settings): fix email communications link

packages/fxa-auth-server/lib/payments/paypal-client.ts, packages/fxa-auth-server/package.json, packages/fxa-auth-server/test/local/payments/paypal-client.js, yarn.lock
Because:
* We want to use the PayPal NVP API, and there isn't a suitable
existing library.
This commit:
* Adds a base PayPal NVP API client for extending with additional
methods.
Closes #7232
=> feat(auth-server): add paypal API base client

packages/fxa-auth-server/lib/error.js, packages/fxa-auth-server/lib/oauth/assertion.js, packages/fxa-auth-server/lib/oauth/auth_client_management.js, packages/fxa-auth-server/lib/oauth/authorized_clients.js, packages/fxa-auth-server/lib/oauth/client.js, packages/fxa-auth-server/lib/oauth/error.js, packages/fxa-auth-server/lib/oauth/grant.js, packages/fxa-auth-server/lib/oauth/jwt_access_token.js, packages/fxa-auth-server/lib/oauth/jwt_id_token.js, packages/fxa-auth-server/lib/oauth/token.js, packages/fxa-auth-server/test/local/error.js
In anticipation of combining the auth/oauth error.js source files I prematurely removed the pre-existing logic to convert oauth errors into auth errors for certain routes. This restores that logic in the `appErrorFromOauthError` function and calls it as part of `AppError.translate` where appropriate.
I also renamed the AppError 'type' in oauth/error.js to OauthError to make them easier to differentiate.
This fixes https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/10391764
=> fix(oauth): fixed oauth -> auth error conversion after refactoring

packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/payments/paypal-client.ts, packages/fxa-auth-server/lib/payments/paypal.ts, packages/fxa-auth-server/lib/routes/subscriptions.ts, packages/fxa-auth-server/test/remote/subscription_tests.js
Because:
* We want to have a helper for PayPal that takes a similar role as the
StripeHelper.
This commit:
* Add's the PayPalHelper and wires in its configuration, initialization,
and use in the subscription routes.
Closes #7233
=> feat(auth-server): add paypal helper

packages/fxa-auth-server/lib/routes/oauth/token.js
This ended up being a copy-pasta bug. The `config` object changed "types" out from under the copied code. Coincidentally the error was being caught and ignored
=> fix(metrics): fixed broken "fxa_reg - compete" metric

packages/fxa-payments-server/.storybook/components/MockApp.tsx, packages/fxa-payments-server/src/App.test.tsx, packages/fxa-payments-server/src/App.tsx, packages/fxa-react/lib/AppLocalizationProvider.test.tsx, packages/fxa-react/lib/AppLocalizationProvider.tsx, packages/fxa-react/package.json, packages/fxa-settings/package.json, packages/fxa-settings/public/locales/en-US/settings.ftl, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/PageDisplayName/index.tsx, yarn.lock
- Settings v2 needs to be localized
- Moves the [AppLocalizationProvider]() to fxa-react
- Updates payment server and settings server to use the provider
- Adds `settings.ftl` in locales/en-US
- Adds basic support for display name page localization
- Note that we will have to refactor this once we split the ftl files by route/components
Closes: #6036
=> feat(l10n): Add initial fluent l10n for settings v2
