mozilla/fxa

docs/index.md

@philbooth r?  (and welcome aboard!)

Add philbooth to the people list

---

docs/dev-process.md
docs/index.md
mkdocs.yml

Add some more detailed docs on our dev process:
* An overview of how we use waffle, milestones and labels to manage our issues
* A checklist of things to cover when reviewing code
The waffle thing is based on the combined "fxa" waffleboard, does this seem like a sensible thing to promote going forward?
@vladikoff or @shane-tomlinson r?

Dev process docs

---

scripts/git_counts.py

last version was buggy - this looks good.

first implementation

---

features/FxA-16-devices-view/README.md

This is a complement to #64, adding detailed textual descriptions of the requirements for this feature.  In conjunction with the UI mocks provided by @ryanfeeley, this should give us all the information we need to implement and verify the feature.
(And I mean "should give us..." in the sense of "the desired end state is that this gives us..." - it's probably not quite there yet, but posting it for discussion).
(Doing this as a separate PR to #64 may or may not turn out to have been a good idea in practice, but let's find out...)

First draft of detailed requirements for "FxA-16: devices view"

---

features/FxA-33-choose-what-to-sync/README.md

Returned sync datatypes to mobile

---

features/FxA-57-verify-reminder/README.md

Closes https://github.com/mozilla/fxa-auth-server/issues/1082

fix(fxa-57): add metrics success

---

features/FxA-45-device-registration-api/README.md

This adds a little scene-setting overview for the feature, and some notes on coordinating with legacy devices which come out of a discussion with @ckarlof and @mhammond earlier today.  @philbooth r?

FxA-45: add some notes about legacy devices

---

features/FxA-45-device-registration-api/FX-DESKTOP.md

This goes along with @philbooth's work in #69 
@rfk, @philbooth, @mhammond, and @ncalexan - This is by no means complete but a starting point for discussion. Mind giving a read and some feedback?

feat(fxa-45): Add Fx Desktop states needed for device registration.

---

features/FxA-38-openid-connect/README.md

design of core openid connect spec

---

features/FxA-16-devices-view/README.md

/cc @ryanfeeley @vladikoff @philbooth 
This PR just does some formatting cleanups on the text of the feature description, it doesn't change anything about the feature.  Flagging it for your reference but merging r=me because it's entirely cosmetic.

chore(fxa-16): Formatting and phrasing cleanups.

---

features/FxA-45-device-registration-api/README.md

Inspired by #92, this is an attempt to make the feature description for FxA 45 match the reality of the initial deliverable.
@rfk r?

feat(docs): update fxa-45 feature to match the initial reality

---

features/FxA-16-devices-view/README.md

/cc @ryanfeely @vladikoff @philbooth @ckarlof 
As we've moved forward with implementing the "devices list" feature, it has become clear that the spec captured in this feature description does not accurately represent everyone's consensus on what we should be building.  I've tried my hand at updating it based on in-person conversations.  Highlights:
* We only show syncing devices, and only those new enough to explicitly register themselves with the devices API.  I've added some clarifying examples and changed some others to reflect this reality.
* Removed talk about devices with an "invalid login state" since AFAICT we don't have any UI for this; devices are either connected and registered, or they're not in the list at all.
* Removed discussion about auto-generating names for older …

fix(fxa-16): Update feature description to only include syncing devices.

---

features/FxA-45-device-registration-api/README.md

Updates the feature description for the latest auth server change.

feat(docs): update devices response to include lastAccessTime

---

features/FxA-46-sms-install-link/README.md

> As a user signing up for a Firefox Account, I may want to easily install Firefox on my Android or iOS device, removing the friction of searching by sending me the link in a text message.
Closes #102

FXA-46 SMS Install Link

---

features/FxA-49-cdn/README.md

feat(fxa-49): Add documentation for FxA-49 - CDN.

---

features/FxA-46-sms-install-link/README.md

Clarify where form will appear, and add percentages of users affected

---

features/FxA-70-kpi-dashboards/README.md

The way the term `sequence` is used in this feature description is a little bit jarring to me. Feel free to ignore this as bikeshedding / splitting hairs / my poor level of English comprehension.
I understand 'sequence' as meaning a specific order that items occur in, rather than an instance of that order which happened at a specific point in time. For example, if the sequence `2-4-6-8` has an id `1`, I expect all instances of that sequence to have the same sequence id, regardless of when they occurred (in this imaginary and arbitrary model that I just invented to try and prove a point :confused:).
In a chat with @rfk, I wondered whether the word `series` was better suited to uniquely identifying a set of events. He pointed out that the proper term would be `session` and also suggested …

fix(docs): rename sequence to flow in fxa-70

---

features/FxA-54-push-on-status-change/README.md

feat(fxa-54): update success criteria

---

scripts/sync_labels.js

The scripting behind the new waffleboard "active" column; raising as a PR for context, but merging r=myself

fix(waffle): Merge "waffle:now" and "waffle:progress" into "waffle:active"

---

features/README.md
features/TEMPLATE.md
features/TEMPLATE_CLEAN.md

add feature template

---

README.md

Add link to Community Participation Guidelines

---

docs/local-development/getting-started.md

Fixes https://github.com/mozilla/fxa-content-server/issues/3859
@rfk r?

chore(docs): add shrinkwrap docs

---

docs/faq.md
docs/index.md
mkdocs.yml

chore(docs): move content from wiki

---

scripts/repos.txt

chore(repos): add geodb repo

---

docs/dev-process.md
docs/local-development/getting-started.md

chore(docs): add etherpad and contributing docs

---

features/FxA-108-update-deps/README.md

feat(fxa-108): update deps

---

features/FxA-41-signin-funnel-metrics/README.md

@vladikoff, this changes the event definitions to match what you recently implemented in the content server and also adds the `flow.completed` event, which will be implemented soon. r?

Update the feature doc for flow events

---

docs/dev-process.md

chore(docs): Update Web Coordination meeting times and purpose.

---

features/FxA-89-devices-view/README.md

feat(fxa-89): update phase 1 results

---

features/FxA-108-update-deps/README.md

feat(fxa-108): add results section

---

features/FxA-50-end-to-end-testing/README.md

feat(fxa-50): add end-to-end testing doc.

---

features/FxA-15-OAuth-Management/README.md

feat(fxa-15): close out fxa-15

---

features/FxA-56-email-deliverability/README.md

add language that we will build a bounce database table

---

features/FxA-89-devices-view/README.md

Fixes https://github.com/mozilla/fxa-features/issues/49

feat(fxa-89): close out device view phase 2

---

scripts/ghlib.js
scripts/repos.txt

feat(repos): Add the fxa-testing-e2e repo

---

docs/dev-process.md

chore(docs): Document the mailing lists uses for meeting minutes

---

features/FxA-107-security-event-history/README.md

There are parts of this document that we didn't do, let's make an explicit statement of why.  @davismtl @vbudhram r?

fix(ip-profiling): Explicitly note parts of this feature that were not completed.

---

scripts/train_summary.js

To help make the train summary emails more useful, this spits out the commit messages grouped by feature.  @mozilla/fxa-devs r?

fix(train-summary): Group commit listings by feature milestone.

---

features/FxA-54-connect-another-device-phase-3/README.md

Clarify installation of Firefox for Android beta.

fix(cad): More cleanup on the CAD phase 3 doc.

---

scripts/repos.txt
scripts/sync_labels.js

@rfk r?
ref https://help.github.com/articles/finding-open-source-projects-on-github/

refactor(labels): migrate to `help wanted` everywhere as GitHub suggests

---

scripts/repos.txt

chore(scripts): add fxa-email-service to repo list

---

scripts/repos.txt
scripts/sync_labels.js

Also replace fxa-password-strength-meter with fxa-common-passwords-list in the list of repos.
@rfk - r?

feat(labels): Add train-116, train-117, and :qa-needed labels.

---

scripts/sync_labels.js

chore(labels): train-114, 115 out, train-118 in

---

package.json
scripts/blog_post.js

feat(blog): Use mustache templates for the blog post generation.

---

scripts/templates/train_blog_post.mustache

fix(blog): Actually commit the blog post generator template.

---

scripts/sync_labels.js

feat(labels): Add labels for Q4 2018

---

scripts/repos.txt

chore(repos): add the email event proxy to repo list

---

README.md

fix(docs): Update the README with current links

---

scripts/repos.txt
scripts/sync_labels.js

Also removed archived repos from the list.

feat(labels): Add q2 2019 labels, ditch old ones

---

packages/fxa-content-server/tests/teamcity/run-server.sh
packages/fxa-content-server/tests/teamcity/run.sh

fix some directory path expectations

fix(teamcity): content: fix teamcity directory location

---

.circleci/config.yml
.circleci/test-content-server.sh
packages/fxa-content-server/tests/intern.js

Give failed functional tests another try before failing the build
Also increase parallelism to 6. supersedes #721

Rerun failed functional tests on CircleCI

---

packages/fxa-geodb/package-lock.json

Fixes https://github.com/mozilla/fxa/issues/735

fix(npm): add package-lock for geodb

---

packages/fxa-content-server/tests/teamcity/run-server.sh
packages/fxa-content-server/tests/teamcity/run.sh

fix(teamcity): actually fix teamcity directory location for real this time

---

packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js
packages/fxa-content-server/app/scripts/models/reliers/oauth.js
packages/fxa-content-server/app/tests/spec/models/auth_brokers/oauth-redirect.js
packages/fxa-content-server/app/tests/spec/models/reliers/oauth.js

Fixes https://github.com/mozilla-mobile/reference-browser/issues/609

fix(oauth): persist PKCE params for same tab verification

---

_scripts/auth_mysql.sh
_scripts/create_mysql.js
_scripts/profile_mysql.sh
mysql_servers.json

I had to make these changes to get `./pm2 start mysql_servers.json` to work.

fix(scripts): fix paths to start mysql servers in local dev

---

docs/supported-browsers.md
packages/fxa-content-server/docs/architecture.md

Also update the docs to recent browsers.

feat(docs): Move browser support to top level doc

---

packages/fxa-content-server/.gitignore

fix(git): Ignore the rerun.txt file

---

packages/fxa-auth-server/lib/devices.js
packages/fxa-auth-server/test/remote/device_tests_refresh_tokens.js

fix(oauth): mark devices that register with OAuth tokens as 'mobile'

---

packages/fxa-auth-server/scripts/verification-reminders.js

from the it's-not-a-log-message-if-it-has-no-timestamp department ...
r? - @philbooth

fix(reminders): output a timestamp with verification reminder logging

---

packages/fxa-customs-server/lib/dataflow.js
packages/fxa-customs-server/lib/server.js
packages/fxa-customs-server/test/local/dataflow_tests.js

feat(dataflow): Log if DataFlow declares a block that FxA does not have.

---

.circleci/build.sh
.circleci/deploy.sh
packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/npm-shrinkwrap.json
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/npm-shrinkwrap.json
packages/fxa-auth-server/package.json
packages/fxa-auth-server/scripts/verification-reminders.js
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/npm-shrinkwrap.json
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package-lock.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/npm-shrinkwrap.json
packages/fxa-profile-server/package.json

Cherry-picked some changes from `master` into `train-134` so that we can deploy verification reminders, then ran the release script. This is the result.

Merge train-134 into master

---

packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/npm-shrinkwrap.json
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/npm-shrinkwrap.json
packages/fxa-auth-server/package.json
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/npm-shrinkwrap.json
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package-lock.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-event-broker/CHANGELOG.md
packages/fxa-event-broker/Cargo.lock
packages/fxa-event-broker/Cargo.toml
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/npm-shrinkwrap.json
packages/fxa-profile-server/package.json

Merge train-135 into master

---

release.sh

This business of the release script creating a separate commit for each package is annoying. Let's do everything in one commit instead.

chore(scripts): do all release script work in a single commit

---

release.sh

chore(scripts): add a comment about private diff size to release script

---

.circleci/build.sh
.circleci/deploy.sh

@jrgm, these are the required changes for the build scripts IIUC. Going to kick off builds with them now, but just flagging to check I'm on the same page...

fix(scripts): make build and deploy scripts work with private repo

---

release.sh

Replaces #855.
Yesterday, in #841, I added a comment to the end of the release script about the size of the private diff. It occurred to me this morning there's no need to show that warning when there's only a handful of commits, it's more there for the big train releases.
So this PR just adds a little condition around that warning, dependent on the size of the diff. I chose 300 lines as the threshold, because the size of a diff for just version bumps and adding `No changes.` to the changelogs is 266 lines.

fix(scripts): conditionally show diff size warning at end of release

---

packages/fxa-auth-server/scripts/verification-reminders.js

Fixes #866.
Opened against the `train-134` branch as we want to deploy this as soon as possible. Without it we can't measure the impact of verification reminders.
The problem was caused by the use of a NOP `log` object in the script. I was only thinking about making the direct script output useful in a standalone sense, not of the wider metrics ecosystem. It's a simple fix to instantiate a real log object instead.
/cc @jrgm @davismtl @irrationalagent

fix(scripts): log metrics from verification reminder script

---

.circleci/build.sh

@jrgm r?
(feel free to replace with your own PR if this wasn't what you had in mind)

fix(scripts): ensure content server build copies version.json correctly

---

packages/fxa-shared/l10n/supportedLanguages.json

feat(l10n): Enable Thai (th)

---

packages/fxa-content-server/app/scripts/templates/settings/account_recovery/account_recovery.mustache
packages/fxa-content-server/app/scripts/templates/settings/clients.mustache
packages/fxa-content-server/app/scripts/templates/settings/emails.mustache
packages/fxa-content-server/app/scripts/templates/settings/two_step_authentication.mustache
packages/fxa-content-server/app/scripts/templates/settings/upgrade_session.mustache

fix(settings views): Refresh status button text fixed

---

packages/fxa-auth-server/lib/log.js
packages/fxa-auth-server/test/local/log.js

remove mozlog.config() fxa-auth-server-I467

---

packages/fxa-content-server/tests/functional_circle.js

From https://github.com/mozilla/fxa/issues/914, I think we should add this flow to our basic circle tests. A lot more clients are using it and it would be nice to find issues a little quicker.
@mozilla/fxa-devs

chore(tests): Add token code tests to circle

---

packages/fxa-content-server/app/scripts/templates/settings/communication_preferences.mustache

As a legal request, we are being more precise that communications related to email, and that subscriptions related to email

fix(emails): Changed communications to email

---

packages/fxa-content-server/app/scripts/templates/pair/auth_allow.mustache
packages/fxa-content-server/app/scripts/templates/pair/auth_wait_for_supp.mustache
packages/fxa-content-server/app/scripts/templates/pair/index.mustache
packages/fxa-content-server/app/scripts/templates/pair/supp_allow.mustache
packages/fxa-content-server/app/scripts/templates/pair/supp_wait_for_auth.mustache
packages/fxa-content-server/app/scripts/templates/partial/device-being-paired.mustache
packages/fxa-content-server/app/scripts/views/pair/auth_allow.js
packages/fxa-content-server/app/tests/spec/views/pair/auth_allow.js

feat(pairing): update the pairing strings based on latest UX

---

packages/fxa-content-server/app/styles/modules/_settings.scss

fix(devices): Show the Android device icon for Fenix

---

packages/fxa-content-server/app/styles/modules/_button-row.scss

fix(style): remove text underline from download buttons

---

packages/fxa-content-server/app/scripts/models/auth_brokers/fx-fennec-v1.js
packages/fxa-content-server/app/tests/spec/models/auth_brokers/fx-fennec-v1.js
packages/fxa-content-server/tests/functional.js
packages/fxa-content-server/tests/functional/fx_fennec_v1_email_first.js
packages/fxa-content-server/tests/functional_circle.js

Experiment is enabled for 10% of people, 5% in control, 5% in treatment.
fixes #953

feat(email-first): Enable email-first experiment for Fennec users.

---

packages/fxa-content-server/tests/functional/fx_fennec_v1_email_first.js

fix(lint): Fix the lint error in the fennec_v1_email_first test.

---

packages/fxa-content-server/app/scripts/lib/config-loader.js

I plucked @shane-tomlinson's jquery change from #919, since it's mostly unrelated

refactor(content-server): Remove jquery dependency from config-loader.js

---

packages/fxa-auth-server/test/local/backendService.js

This updates the tests so they were failing before https://github.com/mozilla/fxa/pull/998 and will pass after.  @jbuck r?

Tests for #998

---

packages/fxa-auth-server/fxa-oauth-server/config/dev.json

ref https://github.com/mozilla/fxa/pull/940#discussion_r280394505
issue #940
@lmorchard or @ianb - r?

feat(subscriptions): Add a dev OAuth entry for the subscriptions page.

---

packages/fxa-content-server/app/scripts/models/auth_brokers/base.js
packages/fxa-content-server/app/tests/spec/models/auth_brokers/base.js

feat(pairing): support private browsing mode for pairing status

---

packages/123done/oauth.js
packages/123done/server.js
packages/123done/static/index.html
packages/123done/static/js/123done.js

feat(subscriptions): add subscription feature to 123done

---

packages/fxa-content-server/app/scripts/lib/app-start.js
packages/fxa-content-server/app/scripts/models/user.js
packages/fxa-content-server/app/scripts/views/pair/index.js
packages/fxa-content-server/app/tests/spec/lib/app-start.js
packages/fxa-content-server/app/tests/spec/models/user.js
packages/fxa-content-server/app/tests/spec/views/pair/index.js

~~Draft to fix pair edge cases with unverified accounts. Gonna add some tests and clean up~~
Fixes https://github.com/mozilla/fxa/issues/923

fix(pairing): fix issues with unverified sessions and lack of sessionToken

---

docs/adr/0000-use-markdown-architectural-decision-records.md
docs/adr/index.md
docs/adr/template.md
package-lock.json
package.json

More an ice-breaker than anything - just dropping some initial boilerplate into docs/adr to kick off the collection of Architectural Decision Records. The initial `0000` ADR kind of recursively explains things, but more details here: https://adr.github.io/madr/

chore(adrs): initial setup of docs/adr using MADR format

---

packages/123done/package.json
packages/browserid-verifier/package.json
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/package.json
packages/fxa-basket-proxy/package.json
packages/fxa-content-server/package.json
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package.json
packages/fxa-geodb/package.json
packages/fxa-js-client/package.json
packages/fxa-oauth-console/package.json
packages/fxa-payments-server/package.json
packages/fxa-profile-server/package.json
packages/fxa-shared/package.json

fix(url): base, homepage, bug url updated for all packages in package.json

---

packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/npm-shrinkwrap.json
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/npm-shrinkwrap.json
packages/fxa-auth-server/package.json
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/app/scripts/models/flow.js
packages/fxa-content-server/app/tests/spec/models/flow.js
packages/fxa-content-server/npm-shrinkwrap.json
packages/fxa-content-server/package.json
packages/fxa-content-server/server/lib/routes/get-metrics-flow.js
packages/fxa-content-server/tests/server/routes/get-metrics-flow.js
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/npm-shrinkwrap.json
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package-lock.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-event-broker/CHANGELOG.md
packages/fxa-event-broker/Cargo.lock
packages/fxa-event-broker/Cargo.toml
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/npm-shrinkwrap.json
packages/fxa-profile-server/package.json

Merge train-136 into master

---

docs/adr/0002-use-react-redux-and-typescript-for-subscription-management-pages.md
docs/adr/index.md

This is related to PR #961 and the choice to use React, Redux, and Typescript.
Normally, we should work on an ADR first and *then* implement the choice. So this PR is kind of backing into the decision already made via conversations here and there.
I think I need some help on this PR, though. I don't feel like I have enough positive points in the Backbone.js option and I don't want to misrepresent it.
So, any & all feedback welcome here!

docs(adrs): Use React, Redux, and Typescript for subscription management pages

---

packages/fxa-content-server/app/styles/modules/_settings.scss

fix(ui): let settings buttons stretch to fit text

---

docs/adr/index.md

docs(adrs): Update ADRs index with missing link

---

packages/fxa-content-server/grunttasks/l10n-extract.js

fixes #1074
@mozilla/fxa-devs, @vladikoff - r?

fix(content:l10n): Update l10n-extract babel config for babel@7

---

packages/fxa-auth-server/lib/db.js
packages/fxa-auth-server/lib/routes/devices-and-sessions.js
packages/fxa-auth-server/test/local/routes/devices-and-sessions.js

 refactor(auth-server): use returned value from .deviceDelete in devices-and-sessions

---

AUTHORS
packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/npm-shrinkwrap.json
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/npm-shrinkwrap.json
packages/fxa-auth-server/package.json
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/npm-shrinkwrap.json
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/npm-shrinkwrap.json
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package-lock.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-event-broker/CHANGELOG.md
packages/fxa-event-broker/Cargo.lock
packages/fxa-event-broker/Cargo.toml
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/npm-shrinkwrap.json
packages/fxa-profile-server/package.json

Merge train-137 into master

---

packages/fxa-content-server/app/scripts/models/sync-engines.js
packages/fxa-content-server/app/tests/spec/models/sync-engines.js

See https://mozilla.invisionapp.com/share/3GRZJ9J65A9#/screens/362776356
extraction from #1098
ref #1084

feat(CWTS): Re-order the Sync engines to match the Trailhead spec.

---

packages/fxa-content-server/app/scripts/lib/constants.js

feat(pairing): update pairing app to Firefox Preview

---

packages/fxa-content-server/npm-shrinkwrap.json
packages/fxa-content-server/package.json
packages/fxa-content-server/webpack.config.js

A small performance improvement while updating templates.
Extraction from #1098

chore(build): Add the cache-loader to mustache compilation

---

packages/fxa-content-server/app/scripts/lib/app-start.js
packages/fxa-content-server/app/scripts/models/user.js
packages/fxa-content-server/app/tests/spec/lib/app-start.js

Fixes #1130 
@shane-tomlinson r?
See the problem described in https://github.com/mozilla/fxa/issues/1130#issuecomment-493278186

fix(pairing): make sure not to use unverified sessions for pairing

---

README.md

Not attached to an issue. Noticed this while trying to install in Ubuntu 18.04.

fix(docs): Update docs on how to work with ubuntu

---

packages/fxa-auth-server/scripts/delete-account.js

fix(accounts): Ensure scripts/delete-account.js initializes subhub

---

README.md

From https://pullreminders.com/badge

Add pull reminder badge

---

packages/fxa-auth-server/bin/subhub_messaging.js
packages/fxa-auth-server/docs/service_notifications.md
packages/fxa-auth-server/lib/subhub/updates.js
packages/fxa-auth-server/test/local/subhub/updates.js

Fixes #1103.
This is my reading of what the linked issue asks for, although it's possible I've misunderstood because I'm not fully immersed in all the subscriptions jargon yet.
@bbangert, @lmorchard r?

feat(subscriptions): emit subscription update notifications

---

.circleci/test-js-client.sh
packages/fxa-js-client/CONTRIBUTING.md
packages/fxa-js-client/package-lock.json
packages/fxa-js-client/package.json

Revert "chore(package): add sjcl postinstall step to fxa-js-client"

---

packages/fxa-content-server/app/scripts/models/auth_brokers/base.js

Fixes https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/5802978/events/30349732/

fix(verification): update pairing check for IE

---

packages/fxa-content-server/app/scripts/lib/app-start.js
packages/fxa-content-server/app/tests/spec/lib/app-start.js

fix(pairing): fix up the regex to detect pairing

---

packages/fxa-content-server/app/styles/modules/_marketing.scss

fix(trailhead): Left align Fx family services on mobile

---

packages/fxa-content-server/app/scripts/lib/newsletters.js
packages/fxa-content-server/app/scripts/lib/validate.js
packages/fxa-content-server/app/scripts/lib/vat.js
packages/fxa-content-server/app/scripts/models/account.js
packages/fxa-content-server/app/scripts/models/resume-token.js
packages/fxa-content-server/app/scripts/templates/choose_what_to_sync.mustache
packages/fxa-content-server/app/scripts/templates/sign_up.mustache
packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache
packages/fxa-content-server/app/scripts/views/choose_what_to_sync.js
packages/fxa-content-server/app/scripts/views/mixins/email-opt-in-mixin.js
packages/fxa-content-server/app/scripts/views/sign_up.js
packages/fxa-content-server/app/scripts/views/sign_up_password.js
packages/fxa-content-server/app/styles/modules/_branding.scss
packages/fxa-content-server/app/styles/modules/_custom-rows.scss
packages/fxa-content-server/app/tests/spec/lib/validate.js
packages/fxa-content-server/app/tests/spec/models/resume-token.js
packages/fxa-content-server/app/tests/spec/views/choose_what_to_sync.js
packages/fxa-content-server/app/tests/spec/views/mixins/email-opt-in-mixin.js
packages/fxa-content-server/app/tests/spec/views/sign_up.js
packages/fxa-content-server/app/tests/spec/views/sign_up_password.js
packages/fxa-content-server/docs/client-metrics.md
packages/fxa-content-server/tests/functional/lib/selectors.js

feat(trailhead): Hook up new newsletters to backend.

---

_scripts/install_all.sh
mysql_servers.json
packages/support-panel/README.md
packages/support-panel/lib/app.js
packages/support-panel/lib/config.js
packages/support-panel/lib/logging.js
packages/support-panel/lib/server.js
packages/support-panel/lib/templates/index.html
packages/support-panel/package-lock.json
packages/support-panel/package.json
servers.json

This implements much of the server setup, but doesn't connect to a database, and is not show correct information.
Intended to fix #1100 (after this is deployed)

feat(support): implement a stub support panel app

---

packages/support-panel/lib/app.js
packages/support-panel/lib/config.js
packages/support-panel/lib/server.js

Oops, I addressed the license/etc nits in #1167 but didn't push them properly to the branch before I landed it. This just contains those trivial fixes.

chore(support): fix license comment blocks

---

packages/fxa-auth-server/test/client/api.js

Noticed this while working on #1208. The implementation of `ClientApi.doRequestWithBearerToken` was a cut-and-paste job on it's sibling `doRequest`, but really it should just call `doRequest` instead.

refactor(tests): re-use client.doRequest in doRequestWithBearerToken

---

packages/fxa-content-server/app/scripts/templates/choose_what_to_sync.mustache
packages/fxa-content-server/app/scripts/templates/sign_up.mustache
packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache
packages/fxa-content-server/app/scripts/views/choose_what_to_sync.js
packages/fxa-content-server/app/scripts/views/sign_up_password.js
packages/fxa-content-server/app/styles/modules/_branding.scss
packages/fxa-content-server/app/styles/modules/_marketing.scss

Still need to do `index` and `choose_what_to_sync` templates. How do I browse them locally?
Closes #1241

Put trailhead feture list on the side

---

packages/fxa-auth-server/config/index.js

fix(subhub): fix config name to be subhubUpdatesQueueUrl

---

packages/fxa-auth-server/lib/error.js
packages/fxa-auth-server/lib/subhub/client.js
packages/fxa-auth-server/lib/subhub/stubAPI.js
packages/fxa-auth-server/test/local/subhub/client.js

- Also update subhub stubs to better reflect subscriptions list offered
as part of customer resource
Issue #718

feat(payment): Add error specific to customer payment update

---

packages/fxa-content-server/app/scripts/lib/auth-errors.js
packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/app/scripts/templates/sign_in_totp_code.mustache
packages/fxa-content-server/app/scripts/views/pair/auth_totp.js
packages/fxa-content-server/app/scripts/views/pair/index.js
packages/fxa-content-server/app/scripts/views/pair/pairing-totp-mixin.js
packages/fxa-content-server/app/tests/spec/views/pair/auth_allow.js
packages/fxa-content-server/app/tests/spec/views/pair/auth_totp.js
packages/fxa-content-server/app/tests/spec/views/pair/index.js
packages/fxa-content-server/app/tests/test_start.js
packages/fxa-content-server/server/lib/routes/get-frontend-pairing.js
packages/fxa-content-server/tests/functional/oauth_sign_in.js
packages/fxa-content-server/tests/functional/pairing.js

feat(pairing): add 2FA support to pairing

---

README.md
_scripts/check.sh
_scripts/install_all.sh
mysql_servers.json
package-lock.json
packages/fxa-event-broker/bin/worker.ts
packages/fxa-event-broker/bin/workerDev.ts
packages/fxa-event-broker/config/development.json
packages/fxa-event-broker/config/index.ts
packages/fxa-event-broker/lib/db/firestore.ts
packages/fxa-event-broker/package-lock.json
packages/fxa-event-broker/package.json
packages/fxa-event-broker/test/lib/db/firestore.spec.ts
packages/fxa-event-broker/test/lib/db/in-memory.spec.ts
packages/fxa-event-broker/test/lib/notificationProcessor.spec.ts
servers.json

Adds local google cloud pubsub/firestore emulator and rigs tests into
it.
Issue #1267
Closes #1266

feat(event-broker): add database tests

---

release.sh

@shane-tomlinson can you give this a try locally to see if it runs to completion for you? Works for me locally, so 🤞.

fix(scripts): stop the release script getting hung up on colour codes

---

packages/fxa-content-server/docs/query-params.md

Also trigger a new build for https://github.com/mozilla/fxa/issues/1329

Clean up some docs spacing.

---

packages/fxa-payments-server/src/App.tsx
packages/fxa-payments-server/src/index.tsx
packages/fxa-payments-server/src/lib/types.tsx
packages/fxa-payments-server/src/routes/Product.tsx
packages/fxa-payments-server/src/store/index.tsx

feat(payments): use query string for plan selection rather than UI

---

packages/fxa-auth-server/fxa-oauth-server/lib/routes/root.js
packages/fxa-auth-server/lib/routes/defaults.js

Otherwise I get local test failures in fxa-auth-server.

fix(repo): Fix /__version__ to correctly locate git directory in the monorepo.

---

.circleci/modules-to-test.js

Fixes #1322.
Also adds semis to the lines that didn't have them, so the diff is a bit messier than it would have been otherwise. Substantive change just adds a regex `IS_BUILD_SCRIPT` and short-circuits the rest of the `getModules` logic if it matches.
See the build for this PR for a demo:
https://circleci.com/workflow-run/15623dec-c173-4efb-909e-6d95f054f995

fix(scripts): force all tests to run if build scripts change

---

packages/fxa-payments-server/Dockerfile-test

chore(payments): Add Dockerfile-test to fxa-payments-server

---

packages/fxa-content-server/tests/functional/oauth_choose_redirect.js
packages/fxa-content-server/tests/functional_circle.js

Open FxA from the RP and then use the client_id returned
from there.
fixes #1353

fix(test): Fix the oauth choose redirect test

---

docs/adr/0004-product-capabilities-for-subscription-services.md
docs/adr/index.md

This is mostly plagiarized from an email thread back in April. But I've seen questions come up a few times over the what's & why's, so I figured it was a good candidate for an ADR.

docs(payments): Product Capabilities for Subscription Services

---

packages/fxa-js-client/client/FxAccountClient.js
packages/fxa-js-client/tests/all.js
packages/fxa-js-client/tests/lib/oauth.js
packages/fxa-js-client/tests/mocks/request.js

Adds
* createOAuthCode
* createOAuthToken
* getOAuthScopedKeyData
Extraction from #795
@vladikoff - r?

feat(oauth): Add OAuth methods to fxa-js-client

---

packages/fxa-auth-server/lib/error.js

Point error api url to monorepo

---

packages/fxa-js-client/package-lock.json
packages/fxa-js-client/package.json

feat(release): Release fxa-js-client 1.0.13

---

.circleci/config.yml
packages/support-panel/Dockerfile-build

fix(support-panel): docker build

---

packages/support-panel/lib/app.js

Needed for deployment - r? @ianb

fix(support-panel): add /__lbheartbeat__

---

packages/fxa-content-server/app/scripts/templates/settings/emails.mustache
packages/fxa-content-server/app/styles/modules/_button-row.scss
packages/fxa-content-server/app/styles/modules/_settings.scss

fix(settings): improve secondary email section buttons

---

packages/fxa-payments-server/.storybook/components/MockApp.tsx
packages/fxa-payments-server/src/App.tsx
packages/fxa-payments-server/src/lib/AppContext.tsx
packages/fxa-payments-server/src/routes/Product.stories.tsx
packages/fxa-payments-server/src/routes/Product.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

feat(payments): shared route props in AppContext, mock Stripe in stories

---

packages/fxa-payments-server/src/components/fields.test.tsx
packages/fxa-payments-server/src/lib/validator.test.tsx
packages/fxa-payments-server/src/lib/validator.ts

Working through further progress on #1365 and found a need to add some initial state for stories, which lead me to some improvements to the just-merged form validation stuff that I figured was worth carving off.
TL;DR: No more awkward hacky JSON stringifying / parsing in tests to assert validator state. Validator now accepts a middleware reducer and initial state. General simplifications all around.

feat(payments): Improve validator reducer with initial state and middleware

---

packages/fxa-payments-server/.storybook/components/MockApp.tsx
packages/fxa-payments-server/src/App.tsx
packages/fxa-payments-server/src/components/Tooltip.test.tsx
packages/fxa-payments-server/src/components/Tooltip.tsx
packages/fxa-payments-server/src/index.tsx
packages/fxa-payments-server/src/lib/AppContext.tsx
packages/fxa-payments-server/src/lib/screen-info.ts

Also provides ScreenInfo from src/index.tsx

feat(payments): move source for Tooltip screen info into AppContext

---

packages/fxa-payments-server/package-lock.json

chore(payments): update package-lock.json for fxa-payments-server

---

packages/fxa-payments-server/package-lock.json

fix(payments): Update package-lock.json for websocket-driver version

---

README.md
_scripts/check.sh

The docker deps were out of date, also added a section on
installing rust nightly.

fix(docs): Update the Ubuntu installation docs

---

packages/fxa-event-broker/config/index.ts
packages/fxa-event-broker/lib/db/firestore.ts
packages/fxa-event-broker/test/lib/db/firestore.spec.ts

feat(event-broker): use firestore collection prefix

---

packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/npm-shrinkwrap.json
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/npm-shrinkwrap.json
packages/fxa-auth-server/package.json
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/npm-shrinkwrap.json
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/npm-shrinkwrap.json
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package-lock.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/npm-shrinkwrap.json
packages/fxa-profile-server/package.json

Release 1.140.0

---

package-lock.json
package.json
packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/CONTRIBUTING.md
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/CONTRIBUTING.md
packages/fxa-auth-server/fxa-oauth-server/CONTRIBUTING.md
packages/fxa-basket-proxy/CONTRIBUTING.md
packages/fxa-customs-server/CONTRIBUTING.md
packages/fxa-oauth-console/CONTRIBUTING.md

This adds a precommit hook to auto-format changes and top level `npm run format`

Add prettier precommit hook

---

packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/lib/error.js
packages/fxa-auth-server/lib/routes/oauth.js
packages/fxa-auth-server/test/local/routes/oauth.js
packages/fxa-auth-server/test/mocks.js
packages/fxa-content-server/CHANGELOG.md
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-email-service/CHANGELOG.md
packages/fxa-profile-server/CHANGELOG.md

Not 100% sure this is correct, but here's my attempt to merge the new train-139 point-release to train-140, after which it can be merged to master.

Merge v1.139.2 to the train-140 branch

---

packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/npm-shrinkwrap.json
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/lib/error.js
packages/fxa-auth-server/lib/routes/oauth.js
packages/fxa-auth-server/npm-shrinkwrap.json
packages/fxa-auth-server/package.json
packages/fxa-auth-server/test/local/routes/oauth.js
packages/fxa-auth-server/test/mocks.js
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/npm-shrinkwrap.json
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/npm-shrinkwrap.json
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package-lock.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/npm-shrinkwrap.json
packages/fxa-profile-server/package.json

There were some merge conflicts bringing https://github.com/mozilla/fxa/pull/1622 to master; this resolves them and also does `npm run format` to bring things in line with latest formatting rules.

Merge v1.140.1 to master

---

package-lock.json
package.json

Pulls in the latest fxa dev launcher so that it can work in FF67+.

chore(deps): update to latest fxa dev launcher

---

README.md

Include Firefox and OpenJDK in the apt-get install list.
Fixes #1639.

chore(docs): update Ubuntu installation docs

---

README.md

chore(docs): Explicitly state WSL requirement for Windows users

---

packages/fxa-auth-server/lib/routes/validators.js
packages/fxa-auth-server/test/local/subhub/client.js

fix: update subhub validation call to match API

---

packages/fxa-auth-server/test/local/routes/subscriptions.js

Spillover from https://github.com/mozilla/fxa/pull/1655#discussion_r300032800.

fix(tests): add missing assertion for subhub.reactivateSubscription

---

packages/fxa-auth-db-mysql/db-server/test/backend/remote.js

Realised I forgot to include these in #1655. There's remote tests in the auth server so they weren't actually uncovered, but still good to have testing of these stored procedures through the API in the db package too.

fix(tests): add remote db tests for subscription cancellation

---

packages/fxa-payments-server/Dockerfile
packages/fxa-payments-server/Dockerfile-test

fix(payments): standardize docker image at /app

---

packages/fxa-content-server/server/lib/routes.js
packages/fxa-content-server/server/lib/routes/post-csp.js
packages/fxa-content-server/tests/server/routes/post-csp.js

This still needs some test changes before merging, but one step closer to getting off heka!

chore(csp): Change CSP logging format to mozlog 2.0

---

.vscode/extensions.json
.vscode/settings.json
README.md

Fixes issue with fxa-email-service by not building it as it has
outdated Rust crates in use.
Update docs to reflect usage of docker-ce vs. outdated docker.io.
Closes #1072.

feat: add vscode settings

---

.circleci/test-content-server.sh

fix(ci): run content-server server tests

---

AUTHORS
packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/npm-shrinkwrap.json
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/npm-shrinkwrap.json
packages/fxa-auth-server/package.json
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/npm-shrinkwrap.json
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/npm-shrinkwrap.json
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package-lock.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/npm-shrinkwrap.json
packages/fxa-profile-server/package.json

Merge train-141 into master

---

packages/fxa-content-server/npm-shrinkwrap.json

Testing a shrinkwrap update, I suspect there could be breaking changes in the test dependencies

chore(deps): update shrinkwrap in the fxa-content-server

---

packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/npm-shrinkwrap.json
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/npm-shrinkwrap.json
packages/fxa-auth-server/package.json
packages/fxa-content-server/.prettierignore
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/npm-shrinkwrap.json
packages/fxa-content-server/package.json
packages/fxa-content-server/server/templates/pages/src/index.html
packages/fxa-content-server/server/templates/pages/src/update_firefox.html
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/npm-shrinkwrap.json
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package-lock.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-event-broker/package-lock.json
packages/fxa-event-broker/package.json
packages/fxa-payments-server/package-lock.json
packages/fxa-payments-server/package.json
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/npm-shrinkwrap.json
packages/fxa-profile-server/package.json

chore(release): Merge Train 141 into master

---

packages/fxa-content-server/app/scripts/lib/app-start.js
packages/fxa-content-server/app/scripts/lib/fxa-client.js
packages/fxa-content-server/app/scripts/models/account.js
packages/fxa-content-server/app/scripts/models/user.js
packages/fxa-content-server/app/tests/spec/models/account.js
packages/fxa-content-server/package.json

`fxa-js-client` work was done in #1715.
Issues #797, #1078, #1071

feat(subscriptions): add active subscriptions and support ticket endpoint access

---

packages/fxa-content-server/npm-shrinkwrap.json
packages/fxa-content-server/package.json

chore(deps): Update fxa-common-password-list to @0.0.3

---

packages/fxa-event-broker/bin/worker.ts
packages/fxa-event-broker/lib/api/proxy-controller.ts
packages/fxa-event-broker/lib/api/proxy-validator.ts
packages/fxa-event-broker/lib/api/routes.ts
packages/fxa-event-broker/test/lib/api/proxy-controller.spec.ts

feat(event-broker): clean shutdown, allow extra pubsub vars, lbheartbeat

---

packages/fxa-event-broker/lib/notificationProcessor.ts
packages/fxa-event-broker/test/lib/notificationProcessor.spec.ts

feat(event-broker): log errors for malformed messages instead of error

---

packages/fxa-auth-server/docs/api.md
packages/fxa-auth-server/fxa-oauth-server/config/dev.json
packages/fxa-auth-server/fxa-oauth-server/config/test.json
packages/fxa-auth-server/fxa-oauth-server/docs/api.md
packages/fxa-auth-server/fxa-oauth-server/docs/pairwise-pseudonymous-identifiers.md
packages/fxa-auth-server/fxa-oauth-server/lib/config.js
packages/fxa-auth-server/fxa-oauth-server/lib/grant.js
packages/fxa-auth-server/fxa-oauth-server/lib/jwt_access_token.js
packages/fxa-auth-server/fxa-oauth-server/lib/jwt_sub.js
packages/fxa-auth-server/fxa-oauth-server/lib/routes/token.js
packages/fxa-auth-server/fxa-oauth-server/lib/validators.js
packages/fxa-auth-server/fxa-oauth-server/test/api.js
packages/fxa-auth-server/fxa-oauth-server/test/grant.js
packages/fxa-auth-server/fxa-oauth-server/test/jwt_access_token.js
packages/fxa-auth-server/fxa-oauth-server/test/jwt_sub.js
packages/fxa-auth-server/lib/oauthdb/grant-tokens-from-authorization-code.js
packages/fxa-auth-server/lib/oauthdb/grant-tokens-from-refresh-token.js
packages/fxa-auth-server/lib/oauthdb/utils.js
packages/fxa-auth-server/lib/routes/validators.js
packages/fxa-auth-server/test/remote/oauth_tests.js

Also enables PPID rotation based on both time and a client sent seed
fixes #1143
fixes #1144

feat(oauth): Add pairwise pseudonymous identifiers in access/id tokens

---

packages/fxa-content-server/app/scripts/models/reliers/oauth.js
packages/fxa-content-server/app/tests/spec/models/reliers/oauth.js

Based on experience implementing consuming code, it's much more convenient to be able to always pass in `keys_jwk` than it is to require the client code to decide up-front whether any of its requested scopes will have keys.
This removes some "belt and braces" check that were enforcing clients the provide `keys_jwk` if and only if requesting a key-bearing scope, and instead just ignores `keys_jwk` when not requesting any key-bearing scopes.
Fixes #1792.
@vladikoff does this fit with what you were thinking?

fix(scoped-keys): Allow clients to provide `keys_jwk` when not requesting scoped keys.

---

packages/fxa-content-server/tests/functional/lib/helpers.js
packages/fxa-content-server/tests/functional/lib/selectors.js
packages/fxa-content-server/tests/functional/oauth_sign_in.js

These tests take a _while_ to run, so thought I'd get CI going in parallel with local test run, but this patch does seem to fix the breakage locally.
Fixes #1830.

fix(tests): Fix functional tests broken by 123done page layout changes

---

packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

fix(payments): Remove period from subscription cancellation dialog

---

packages/fxa-payments-server/src/components/PaymentForm/index.tsx
packages/fxa-payments-server/src/lib/formats.ts
packages/fxa-payments-server/src/routes/Product/PlanDetails/Details123DonePro.tsx
packages/fxa-payments-server/src/routes/Product/PlanDetails/DetailsDefault.tsx
packages/fxa-payments-server/src/routes/Product/index.stories.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx

fix(payments): Better formatting for currency in cents

---

packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx

fix(payments): date formatting on subscription list

---

packages/fxa-payments-server/src/routes/Product/index.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx

fix(payments): address inconsistencies in capitalization

---

packages/fxa-auth-server/fxa-oauth-server/test/api.js

The failing test checked that two `sub`s in two JWT access
tokens were the same as long as they had the same ppid_seed,
and did not take into account the server may have force
rotated the sub. This would be especially problematic
on CI VMs which are slow and where tests take longer.
The "fix" is to no longer compare the `sub` claims
between the two tokens.
fixes #1854

fix(ppid): Fix the failing ppid test.

---

AUTHORS
packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/npm-shrinkwrap.json
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/npm-shrinkwrap.json
packages/fxa-auth-server/package.json
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/npm-shrinkwrap.json
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/npm-shrinkwrap.json
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package-lock.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-event-broker/package-lock.json
packages/fxa-event-broker/package.json
packages/fxa-payments-server/package-lock.json
packages/fxa-payments-server/package.json
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/npm-shrinkwrap.json
packages/fxa-profile-server/package.json
packages/fxa-support-panel/package-lock.json
packages/fxa-support-panel/package.json
release.sh

Merge train-142 into master

---

packages/fxa-payments-server/src/routes/Product/PlanDetails/Details123DonePro.tsx
packages/fxa-payments-server/src/routes/Product/PlanDetails/DetailsDefault.tsx
packages/fxa-payments-server/src/routes/Product/PlanDetails/index.scss

fix(payments): update value copy on payment form

---

.circleci/config.yml
packages/fxa-auth-server/npm-shrinkwrap.json
packages/fxa-auth-server/package.json
packages/fxa-content-server/npm-shrinkwrap.json
packages/fxa-content-server/package.json
packages/fxa-content-server/server/lib/configuration.js
packages/fxa-shared/l10n/supportedLanguages.json
packages/fxa-shared/package-lock.json
packages/fxa-shared/package.json

Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1566346

chore(config): Add FireTV to the validation list for "oldsync" scope.

---

packages/fxa-payments-server/src/components/PaymentForm/index.scss
packages/fxa-payments-server/src/components/PaymentForm/index.tsx

Zip code field tweak and add name field placeholder

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/app/scripts/views/subscriptions_management_redirect.js
packages/fxa-content-server/app/tests/spec/views/subscriptions_management_redirect.js
packages/fxa-content-server/app/tests/test_start.js
packages/fxa-content-server/server/lib/routes/get-frontend.js
packages/fxa-content-server/tests/server/routes.js

feat(payments): support /subscriptions redirect on content-server

---

packages/123done/static/js/123done.js

r? - @lmorchard 
That product code came from Ben.

fix(123done): configure stage paymentURL

---

packages/fxa-event-broker/bin/worker.ts

fix(event-broker): exit with non-zero for unhandledRejection

---

packages/fxa-support-panel/lib/api.ts
packages/fxa-support-panel/test/lib/api.spec.ts

fix(support-panel): log totp error, return appropriate errors

---

packages/fxa-support-panel/.gitignore

fix(support-panel): add gitignore for dist/common files

---

packages/fxa-event-broker/bin/worker.ts

feat(event-broker): extract region from service notification url

---

packages/fxa-auth-server/docs/service_notifications.md
packages/fxa-event-broker/lib/notificationProcessor.ts

fix(event-broker): handle a missing clientId

---

packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/server/lib/configuration.js
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-email-service/CHANGELOG.md
packages/fxa-profile-server/CHANGELOG.md

Actually target train-142 branch this time...

Merge v1.141.8 into train-142

---

packages/fxa-content-server/app/scripts/lib/constants.js
packages/fxa-content-server/app/scripts/lib/fxa-client.js
packages/fxa-content-server/app/scripts/models/account.js
packages/fxa-content-server/app/scripts/templates/settings.mustache
packages/fxa-content-server/app/scripts/views/settings.js
packages/fxa-content-server/app/styles/modules/_settings.scss
packages/fxa-content-server/app/tests/spec/lib/fxa-client.js
packages/fxa-content-server/app/tests/spec/models/account.js
packages/fxa-content-server/app/tests/spec/views/settings.js
packages/fxa-content-server/npm-shrinkwrap.json

Fixes #970.
Joint effort by me and @meandavejustice.
Displays a banner on the settings screen if a user has a subscription with an expired card. Wires in to the auth server work from #1824.
Although all the pieces are tested individually, I haven't actually done a proper end-to-end test because I'm not sure how. If someone else understands how to make that happen, let me know.
And /cc @LZoog, this conflicts with your WIP PR #1801. Note the changes to the `settingsData` method where it caches its own result to protect us from the situation discussed in #1808. That should mean we can each call it from wherever we need without needing to co-ordinate or whatever.

feat(settings): add ui for expired credit card alert

---

packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/npm-shrinkwrap.json
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/npm-shrinkwrap.json
packages/fxa-auth-server/package.json
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/npm-shrinkwrap.json
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/npm-shrinkwrap.json
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package-lock.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-event-broker/package-lock.json
packages/fxa-event-broker/package.json
packages/fxa-payments-server/package-lock.json
packages/fxa-payments-server/package.json
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/npm-shrinkwrap.json
packages/fxa-profile-server/package.json
packages/fxa-support-panel/package-lock.json
packages/fxa-support-panel/package.json

The actual commits for this accidentally got merged to master already, this is just the changelogs and version bumps.

Merge v1.142.1 to master

---

packages/fxa-event-broker/bin/worker.ts
packages/fxa-event-broker/test/bin/worker.spec.ts

feat(event-broker): add test for region extraction

---

packages/fxa-auth-server/lib/subhub/client.js
packages/fxa-auth-server/test/local/subhub/client.js

fix(subscriptions): rename 'orig_system' to 'origin_system' in subscription creation params

---

packages/fxa-auth-server/lib/subhub/client.js
packages/fxa-auth-server/test/local/subhub/client.js

fix(subscriptions): throw correct error for unknown subhub customer

---

packages/fxa-content-server/app/scripts/templates/settings/delete_account.mustache
packages/fxa-content-server/app/scripts/views/settings/delete_account.js
packages/fxa-content-server/app/styles/modules/_button-row.scss
packages/fxa-content-server/app/styles/modules/_settings.scss
packages/fxa-content-server/app/tests/spec/views/settings/delete_account.js
packages/fxa-content-server/tests/functional/lib/helpers.js
packages/fxa-content-server/tests/functional/lib/selectors.js

fixes #1071 
Notes:
I checked with Julia about disabled button active states when addressing a hover/active state change request from John and we agreed it made sense to not give visual feedback when clicking a disabled button so that change was made in `button-row.scss` instead of on the delete account button specifically.

feat(fxa-content-server): fixes #1071 - new delete account view to display apps & subscriptions

---

packages/fxa-event-broker/.prettierrc
packages/fxa-event-broker/README.md
packages/fxa-event-broker/bin/simulate-webhook-call.ts
packages/fxa-event-broker/bin/worker.ts
packages/fxa-event-broker/bin/workerDev.ts
packages/fxa-event-broker/lib/proxy-server.ts
packages/fxa-event-broker/test/lib/api/proxy-controller.spec.ts
packages/fxa-support-panel/bin/worker.ts
packages/fxa-support-panel/lib/server.ts
packages/fxa-support-panel/test/lib/api.spec.ts

feat: productize event-broker and fix excessive logging in prod

---

packages/fxa-support-panel/config/index.ts
packages/fxa-support-panel/lib/api.ts
packages/fxa-support-panel/test/lib/api.spec.ts

Issue #702
This also fixes a place I was using snake_case var names instead of camelCase.
**NOTE**: This changes a config var used for deploying.

feat(support-panel): log the accessing user by provided header

---

packages/fxa-content-server/app/scripts/templates/support.mustache
packages/fxa-content-server/app/styles/modules/support.scss

fix(css): update support form spacing

---

packages/fxa-content-server/app/styles/modules/_settings.scss

fix(fxa-content-server): Fix horizontal bar caused by settings header by changing width unit

---

packages/fxa-content-server/app/scripts/templates/sign_up.mustache
packages/fxa-content-server/app/scripts/views/form.js
packages/fxa-content-server/app/scripts/views/mixins/password-mixin.js
packages/fxa-content-server/app/tests/spec/views/mixins/password-mixin.js
packages/fxa-content-server/app/tests/spec/views/sign_up.js
packages/fxa-content-server/tests/functional/password_visibility.js

Fix Fire TV issues

---

.circleci/test-content-server.sh
packages/fxa-content-server/tests/functional/sign_in.js

Let's see if Firefox 68 works on Circle. It'd be nice to test on the latest Firefox.

chore(ci): Use Firefox 68 on CircleCI

---

packages/fxa-content-server/tests/functional/support.js

The test title was also incorrect previously.
Fixes #2003

fix(tests): remove cross functional test dependency

---

packages/fxa-support-panel/lib/server.ts

chore(security): add HSTS to Support Panel

---

packages/fxa-js-client/client/FxAccountClient.js
packages/fxa-js-client/tests/all.js
packages/fxa-js-client/tests/lib/securityEvents.js
packages/fxa-js-client/tests/mocks/request.js

@vbudhram I've closed previous PR because that was branch was child of my remote auth-server's branch, please continue with this one.

feat(routes): added securityEvents to js-client

---

packages/fxa-content-server/npm-shrinkwrap.json
packages/fxa-content-server/package.json
packages/fxa-js-client/package-lock.json
packages/fxa-js-client/package.json

chore(deps): bump the js-client package version

---

packages/fxa-content-server/app/scripts/templates/force_auth.mustache
packages/fxa-content-server/app/scripts/templates/index.mustache
packages/fxa-content-server/app/scripts/templates/sign_in.mustache
packages/fxa-content-server/app/scripts/templates/sign_up.mustache
packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache

missed a few spots in #1991 
fixes #1735

fix(tv): set tabindex of TOS on all login pages

---

packages/fxa-content-server/tests/functional/lib/selectors.js

fix(tests): update selector for privacy notice page

---

packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/test/local/senders/email.js

Unfortunately this only came up #2017 after landed, but apparently secops advise that we shouldn't include any kind of authorisation code in the subject line of emails. So this removes the two cases that got added earlier and, at @ryanfeeley's suggestion, includes the client name instead.

fix(email): remove codes from email subjects

---

packages/fxa-support-panel/lib/api.ts

fix(support panel): populate devices list correctly

---

.circleci/test-content-server.sh

fix(CI): check payments server before tests in CI

---

packages/fxa-support-panel/lib/api.ts
packages/fxa-support-panel/test/lib/api.spec.ts

fix(support panel): update query param validation

---

packages/fxa-payments-server/package.json

issue #2102
This enables verbose test output & coverage reports, for a baseline of 47% of statements covered.
I also set some failure thresholds for test coverage - initially at a sad 30% so things pass, but ultimately this should get bumped up to 80% before issue #2102 can be considered closed.
```
➜  fxa-payments-server git:(2102-test-coverage-baseline) CI=yes npm run test
> fxa-payments-server@1.143.0 test /mnt/c/Users/lmorc/devel/fxa/packages/fxa-payments-server
> react-scripts test --coverage --verbose
PASS src/lib/errors.test.tsx
✓ returns the basic error text if not predefined error type (8ms)
✓ returns the payment error text for the correct error type (1ms)
PASS src/lib/validator.test.tsx
✓ supports registering a field (34ms)
✓ supports updating a field (6ms)
✓ supports checking …
```

chore(payments): enable test coverage reports

---

packages/fxa-js-client/client/FxAccountClient.js
packages/fxa-js-client/tests/lib/securityEvents.js
packages/fxa-js-client/tests/mocks/request.js

fix(request): adding payload to deleteSecurityEvents and fix js-client tests

---

packages/fxa-auth-server/docs/device_registration.md
packages/fxa-content-server/app/images/icon-device-tv.svg
packages/fxa-content-server/app/images/icon-device-vr.svg
packages/fxa-content-server/app/styles/modules/_settings.scss

Fixes https://github.com/mozilla/fxa/issues/1856.
The icons are not really pixel perfect but @ryanfeeley said he will get back to it later when he has some bandwidth.

feat(devices): add VR and TV devices types

---

packages/fxa-auth-db-mysql/db-server/test/backend/db_tests.js
packages/fxa-auth-db-mysql/lib/db/mem.js
packages/fxa-auth-db-mysql/lib/db/mysql.js
packages/fxa-auth-db-mysql/lib/db/patch.js
packages/fxa-auth-db-mysql/lib/db/schema/patch-101-102.sql
packages/fxa-auth-db-mysql/lib/db/schema/patch-102-101.sql

feat(recovery): Clear recovery keys when resetting account

---

packages/fxa-payments-server/package.json
packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.tsx

chore(payments): get PaymentForm up to 100% test coverage

---

packages/fxa-payments-server/package.json
packages/fxa-payments-server/server/jest.config.js
packages/fxa-payments-server/src/components/DialogMessage.test.tsx
packages/fxa-payments-server/src/components/DialogMessage.tsx
packages/fxa-payments-server/src/components/fields.test.tsx
packages/fxa-payments-server/src/components/fields.tsx
packages/fxa-payments-server/src/jest.config.js
packages/fxa-payments-server/src/lib/hooks.test.tsx
packages/fxa-payments-server/src/lib/hooks.tsx
packages/fxa-payments-server/src/lib/validator.test.tsx
packages/fxa-payments-server/src/store/utils.test.tsx
packages/fxa-payments-server/src/store/utils.tsx

Before:
```
-----------------------------------------|----------|----------|----------|----------|-------------------|
File                                     |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------------------------------------|----------|----------|----------|----------|-------------------|
All files                                |     66.4 |    57.93 |    47.98 |    66.75 |                   |
```
After:
```
-----------------------------------------|----------|----------|----------|----------|-------------------|
File                                     |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------------------------------------|----------|----------|----------|----------|-------------------|
All files …
```

chore(payments): improve test coverage a bit more

---

packages/fxa-support-panel/lib/templates/index.html

fix(support): remove inline style for CSP issue #2164

---

packages/fxa-auth-server/bin/subhub_messaging.js

I did the fix for this, which has it running in stage. Merge if the other refactorings look good to you.
fixes #2170

fix(auth): remove extra `/lib` from require path

---

packages/fxa-auth-server/bin/key_server.js
packages/fxa-auth-server/config/index.js
packages/fxa-auth-server/lib/routes/index.js
packages/fxa-auth-server/lib/subhub/client.js
packages/fxa-auth-server/lib/subhub/stubAPI.js
packages/fxa-auth-server/test/local/subhub/client.js

chore(subhub): cache the plans list in Redis

---

packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/npm-shrinkwrap.json
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/bin/subhub_messaging.js
packages/fxa-auth-server/npm-shrinkwrap.json
packages/fxa-auth-server/package.json
packages/fxa-auth-server/scripts/verification-reminders.js
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/npm-shrinkwrap.json
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/npm-shrinkwrap.json
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package-lock.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-event-broker/package-lock.json
packages/fxa-event-broker/package.json
packages/fxa-payments-server/package-lock.json
packages/fxa-payments-server/package.json
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/npm-shrinkwrap.json
packages/fxa-profile-server/package.json
packages/fxa-support-panel/package-lock.json
packages/fxa-support-panel/package.json

Merge train-143 into master

---

packages/fxa-content-server/app/scripts/views/base.js
packages/fxa-content-server/app/tests/spec/views/base.js

@shane-tomlinson can you please review this!

chore(base): added a function to render the react component

---

packages/fxa-auth-server/docs/service_notifications.md
packages/fxa-auth-server/lib/subhub/updates.js
packages/fxa-auth-server/test/local/subhub/updates.js
packages/fxa-event-broker/README.md
packages/fxa-event-broker/bin/simulate-webhook-call.ts
packages/fxa-event-broker/lib/api/proxy-controller.ts
packages/fxa-event-broker/lib/db/firestore.ts
packages/fxa-event-broker/lib/jwts.ts
packages/fxa-event-broker/lib/notificationProcessor.ts
packages/fxa-event-broker/lib/serviceNotifications.ts
packages/fxa-event-broker/package-lock.json
packages/fxa-event-broker/package.json
packages/fxa-event-broker/test/lib/api/proxy-controller.spec.ts
packages/fxa-event-broker/test/lib/notificationProcessor.spec.ts

Also refactors event handling to be a bit better structured for
additional event types.
Closes #2110

feat(event-broker): add delete event propagation

---

packages/fxa-event-broker/bin/worker.ts
packages/fxa-event-broker/bin/workerDev.ts
packages/fxa-event-broker/lib/notificationProcessor.ts
packages/fxa-event-broker/package-lock.json
packages/fxa-event-broker/package.json
packages/fxa-event-broker/tsconfig.json

feat(event-broker): add sentry error reporting

---

packages/fxa-content-server/app/scripts/views/mixins/settings-panel-mixin.js
packages/fxa-content-server/app/scripts/views/settings/delete_account.js
packages/fxa-content-server/app/tests/spec/views/base.js
packages/fxa-content-server/app/tests/spec/views/settings/change_password.jsx
packages/fxa-content-server/app/tests/spec/views/settings/delete_account.js

Currently only 4 tests run, this brings back the rest of the tests

fix(tests): fix content server unit tests

---

packages/fxa-shared/.gitignore
packages/fxa-shared/.prettierignore
packages/fxa-shared/index.js
packages/fxa-shared/package-lock.json
packages/fxa-shared/package.json
packages/fxa-shared/tsconfig.json
packages/fxa-shared/tslint.json

Let's review this PR as a group at the start of tomorrow's TypeScript workshop.

Prepare fxa-shared for conversion to typescript

---

packages/fxa-payments-server/package.json
packages/fxa-payments-server/src/lib/test-utils.tsx
packages/fxa-payments-server/src/routes/Product/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

- lots of additional test cases for subscription management page
- sprinkle in lots of data-testid in subscription route components
- refactor some more shared stuff into test-utils.tsx
fixes #2102

chore(payments): 100% test coverage for subscription management route

---

packages/fxa-auth-server/lib/routes/unblock-codes.js

From the workshop #2286. Thanks Jared for presenting.

refactor(unblock-codes): Convert unblock-codes.js to async/await 

---

packages/fxa-content-server/npm-shrinkwrap.json
packages/fxa-content-server/package.json
packages/fxa-js-client/package-lock.json
packages/fxa-js-client/package.json

Updates the js-client to get new signup code functions.
Connects to #457

fix(deps): Update to js-client 19

---

packages/fxa-auth-db-mysql/db-server/test/backend/db_tests.js
packages/fxa-auth-db-mysql/lib/db/mem.js
packages/fxa-auth-db-mysql/lib/db/mysql.js
packages/fxa-auth-db-mysql/lib/db/patch.js
packages/fxa-auth-db-mysql/lib/db/schema/patch-103-104.sql
packages/fxa-auth-db-mysql/lib/db/schema/patch-104-103.sql

fix(subscriptions): bump account profileUpdatedAt when a subscription is created or deleted

---

renovate.json

chore(deps): enable renovate for all monorepo packages

---

packages/fxa-auth-server/fxa-oauth-server/docs/api.md

docs(oauth-server): add introspect endpoint in API.md

---

packages/fxa-content-server/app/scripts/lib/fxa-client.js
packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/app/scripts/models/account.js
packages/fxa-content-server/app/scripts/models/auth_brokers/base.js
packages/fxa-content-server/app/scripts/models/security-events.js
packages/fxa-content-server/app/scripts/templates/security_events.mustache
packages/fxa-content-server/app/scripts/templates/settings.mustache
packages/fxa-content-server/app/scripts/views/security_events.js
packages/fxa-content-server/app/scripts/views/settings.js
packages/fxa-content-server/app/styles/_modules.scss
packages/fxa-content-server/app/styles/modules/_security-events.scss
packages/fxa-content-server/app/tests/spec/lib/fxa-client.js
packages/fxa-content-server/app/tests/spec/models/account.js
packages/fxa-content-server/app/tests/spec/models/security-events.js
packages/fxa-content-server/app/tests/spec/views/settings.js
packages/fxa-content-server/app/tests/test_start.js
packages/fxa-content-server/server/lib/routes/get-frontend.js
packages/fxa-content-server/tests/functional.js
packages/fxa-content-server/tests/functional/lib/selectors.js
packages/fxa-content-server/tests/functional/security_events.js
packages/fxa-content-server/tests/functional/settings.js

@vbudhram our final phase, working on `content-server` to make the security dashboard.

Working on Security Dashboard

---

packages/fxa-content-server/app/tests/spec/lib/crypto/a256gcm.js

fix(tests): fix unit tests in Webkit

---

packages/fxa-payments-server/src/routes/Product/index.scss

fix(style): make billing info heading bold

---

packages/fxa-content-server/app/styles/modules/_spinner.scss

fix(content-server): Center the loading indicator

---

packages/fxa-auth-server/lib/routes/support.js
packages/fxa-auth-server/test/local/routes/support.js
packages/fxa-content-server/app/scripts/models/account.js
packages/fxa-content-server/app/scripts/models/support-form.js
packages/fxa-content-server/app/scripts/templates/support.mustache
packages/fxa-content-server/app/scripts/views/support.js
packages/fxa-content-server/app/styles/modules/support.scss
packages/fxa-content-server/app/tests/spec/models/support-form.js
packages/fxa-content-server/app/tests/spec/views/support.js
packages/fxa-content-server/tests/functional/support.js

feat(support form): add subscription plan dropdown

---

packages/fxa-auth-server/lib/routes/unblock-codes.js

The practice of using nested functions inside route handlers was an artifact of the long promise chains we used to have. It was easier to understand the big picture when each `.then` callback was a named function rather than a tangle of inline code.
But the handler for `POST /account/login/send_unblock_code` was already pretty simple to read and the recent switch to async/await made it even simpler, so it seems like a redundant practice there now. This change just removes the named functions and does everything inline instead.

refactor(api): simplify POST /account/login/send_unblock_code handler

---

packages/fxa-auth-server/lib/routes/sms.js

refactor(api): prefer async/await in sms routes

---

packages/fxa-content-server/app/styles/modules/_settings.scss

Adjust button size to accomodate button title better
and increase content width in mobile view.
fixes: #1254
@ryanfeeley review please

fix(ui): adjust button size and client name in devices list

---

packages/fxa-auth-server/lib/routes/signin-codes.js

refactor(api): prefer async/await in signin-codes route

---

packages/fxa-auth-server/lib/routes/token-codes.js

refactor(api): prefer async/await in token codes routes

---

packages/fxa-auth-server/lib/routes/recovery-codes.js

refactor(api): prefer async/await in recovery-codes routes

---

packages/fxa-content-server/tests/teamcity/run-server.sh
packages/fxa-content-server/tests/teamcity/run.sh

These just need to be adjusted for the changes to use ../ paths to fxa-shared and fxa-geodb

fix(teamcity): install peer directories fxa-shared and fxa-geodb

---

packages/fxa-auth-server/lib/routes/recovery-key.js

refactor(api): prefer async/await in recovery-key routes

---

packages/fxa-event-broker/config/index.ts
packages/fxa-event-broker/lib/selfUpdatingService/clientCapabilityService.ts
packages/fxa-event-broker/lib/selfUpdatingService/index.ts
packages/fxa-event-broker/test/lib/selfUpdatingService/clientCapabilityService.spec.ts

feat(event-broker): add config flag to allow capability check to fail

---

packages/fxa-payments-server/src/components/AppLayout/index.scss
packages/fxa-payments-server/src/components/AppLayout/index.test.tsx
packages/fxa-payments-server/src/components/AppLayout/index.tsx

fix(layout): fix ToS and Privacy Notice links on payments server

---

packages/fxa-customs-server/npm-shrinkwrap.json
packages/fxa-customs-server/package.json

chore(deps): Update @google-cloud/pubsub for node 12 compat

---

packages/fxa-auth-server/lib/metrics/amplitude.js

refactor(api): prefer async/await in lib/amplitude.js

---

packages/fxa-js-client/client/FxAccountClient.js
packages/fxa-js-client/package.json
packages/fxa-js-client/tests/lib/subscriptions.js
packages/fxa-js-client/tests/mocks/request.js

chore(fxa-js-client): add method to get subscription plans

---

packages/fxa-auth-server/lib/metrics/events.js

refactor(api): prefer async/await in lib/metrics/events.js

---

packages/fxa-auth-server/lib/senders/translator.js

refactor(auth-server): prefer async/await in lib/senders/translator.js

---

packages/fxa-js-client/client/FxAccountClient.js
packages/fxa-js-client/package.json

This fixes the screw up by me in #2429.  😳 

fix(fxa-js-client): fix the subscription plans path

---

packages/fxa-content-server/server/lib/routes/get-openid-configuration.js
packages/fxa-content-server/tests/server/routes/get-openid-configuration.js

fix(content-server): advertise introspection and revocation endpoints

---

packages/fxa-content-server/app/scripts/lib/vat.js
packages/fxa-content-server/app/scripts/models/auth_brokers/pairing/supplicant.js
packages/fxa-content-server/app/tests/spec/models/auth_brokers/pairing/supplicant.js
packages/fxa-content-server/app/tests/spec/models/reliers/relier.js

Fixes https://github.com/mozilla/application-services/issues/1740

feat(pairing): add action param to the pairing flow

---

packages/fxa-auth-server/fxa-oauth-server/lib/routes/token.js

Ref: https://github.com/mozilla/fxa/pull/2442#discussion_r322049620

chore(typo): fix typo in token code logging

---

packages/fxa-auth-server/fxa-oauth-server/config/dev.json
packages/fxa-auth-server/fxa-oauth-server/lib/assertion.js
packages/fxa-auth-server/fxa-oauth-server/lib/db/memory.js
packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/index.js
packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/patches/patch-027-028.sql
packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/patches/patch-028-027.sql
packages/fxa-auth-server/fxa-oauth-server/lib/grant.js
packages/fxa-auth-server/fxa-oauth-server/lib/routes/authorization.js
packages/fxa-auth-server/fxa-oauth-server/lib/routes/token.js
packages/fxa-auth-server/fxa-oauth-server/lib/validators.js
packages/fxa-auth-server/fxa-oauth-server/test/grant.js
packages/fxa-auth-server/lib/constants.js
packages/fxa-auth-server/lib/oauthdb/grant-tokens-from-authorization-code.js
packages/fxa-auth-server/lib/oauthdb/utils.js
packages/fxa-auth-server/lib/routes/oauth.js
packages/fxa-auth-server/lib/routes/session.js
packages/fxa-auth-server/lib/routes/utils/oauth.js
packages/fxa-auth-server/lib/routes/validators.js
packages/fxa-auth-server/lib/scheme-refresh-token.js
packages/fxa-auth-server/lib/tokens/session_token.js
packages/fxa-auth-server/test/local/constants.js
packages/fxa-auth-server/test/local/routes/oauth.js
packages/fxa-auth-server/test/local/routes/session.js
packages/fxa-auth-server/test/local/tokens/session_token.js
packages/fxa-auth-server/test/remote/oauth_session_token_scope_tests.js
packages/fxa-auth-server/test/remote/oauth_tests.js

Fixes https://github.com/mozilla/application-services/issues/1669
Requires https://github.com/mozilla/application-services/pull/1759
Ref: https://docs.google.com/document/d/1Q7xinEA3uXnUVobT5yaU7gXHcKK2Zj49nBrkUwHZVbg/edit?ts=5d5f0ffc#heading=h.bnyo94zc3qqz
Ref: https://github.com/mozilla-mobile/fenix/pull/5203

feat(oauth): support the session token scope for user agent clients

---

packages/fxa-content-server/app/scripts/lib/metrics.js
packages/fxa-content-server/app/scripts/views/mixins/flow-events-mixin.js
packages/fxa-content-server/app/scripts/views/support.js
packages/fxa-content-server/app/tests/spec/lib/metrics.js
packages/fxa-content-server/app/tests/spec/views/mixins/flow-events-mixin.js
packages/fxa-content-server/app/tests/spec/views/support.js
packages/fxa-content-server/server/lib/amplitude.js
packages/fxa-content-server/server/lib/routes/post-metrics.js
packages/fxa-content-server/tests/server/amplitude.js
packages/fxa-shared/metrics/amplitude.js
packages/fxa-shared/test/metrics/amplitude.js

feat(metrics): add support form metrics

---

packages/fxa-profile-server/config/development.json
packages/fxa-profile-server/docs/API.md
packages/fxa-profile-server/lib/config.js
packages/fxa-profile-server/lib/routes/cache/delete.js
packages/fxa-profile-server/lib/routing.js
packages/fxa-profile-server/lib/server/web.js
packages/fxa-profile-server/test/api.js

feat(profile-server): offer DELETE /v1/cache/{uid} resource to clear cached profile data

---

packages/fxa-content-server/app/scripts/models/support-form.js
packages/fxa-content-server/app/scripts/templates/partial/support-form-success.mustache
packages/fxa-content-server/app/scripts/templates/support.mustache
packages/fxa-content-server/app/scripts/views/support.js
packages/fxa-content-server/app/styles/modules/support.scss
packages/fxa-content-server/app/tests/spec/views/support.js
packages/fxa-payments-server/src/lib/types.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

feat(support form): add successful submission message modal

---

packages/fxa-auth-server/docs/service_notifications.md
packages/fxa-auth-server/lib/log.js
packages/fxa-auth-server/test/local/devices.js
packages/fxa-auth-server/test/local/log.js
packages/fxa-event-broker/README.md
packages/fxa-event-broker/bin/worker.ts
packages/fxa-event-broker/bin/workerDev.ts
packages/fxa-event-broker/config/index.ts
packages/fxa-event-broker/lib/api/index.ts
packages/fxa-event-broker/lib/api/proxy-controller.ts
packages/fxa-event-broker/lib/api/routes.ts
packages/fxa-event-broker/lib/notificationProcessor.ts
packages/fxa-event-broker/lib/proxy-server.ts
packages/fxa-event-broker/lib/serviceNotifications.ts
packages/fxa-event-broker/package-lock.json
packages/fxa-event-broker/package.json
packages/fxa-event-broker/test/lib/api/proxy-controller.spec.ts
packages/fxa-event-broker/test/lib/notificationProcessor.spec.ts

feat(event-broker): add performance metrics

---

packages/fxa-content-server/app/scripts/models/auth_brokers/base.js
packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-webchannel-v1.js
packages/fxa-content-server/app/tests/spec/models/auth_brokers/oauth-webchannel-v1.js
packages/fxa-content-server/tests/functional/oauth_webchannel.js

fix(oauth): fix the status check for the oauth webchannel broker

---

packages/fxa-content-server/app/styles/modules/_custom-rows.scss

fix(css): fixes #2130 - Account flow sync checkbox style tweak

---

packages/fxa-auth-server/docs/api.md
packages/fxa-auth-server/fxa-oauth-server/lib/client.js
packages/fxa-auth-server/lib/oauthdb/index.js
packages/fxa-auth-server/lib/oauthdb/revoke-access-token.js
packages/fxa-auth-server/lib/oauthdb/revoke-refresh-token.js
packages/fxa-auth-server/lib/routes/oauth.js
packages/fxa-auth-server/test/client/api.js
packages/fxa-auth-server/test/client/index.js
packages/fxa-auth-server/test/local/oauthdb/revoke-access-token.js
packages/fxa-auth-server/test/local/oauthdb/revoke-refresh-token-by-id.js
packages/fxa-auth-server/test/local/routes/oauth.js
packages/fxa-auth-server/test/mocks.js
packages/fxa-auth-server/test/remote/oauth_tests.js

Fixes #2540. Depends on #2566.

Add RFC7009-compatible token revocation endpoint.

---

packages/fxa-customs-server/lib/dataflow.js
packages/fxa-customs-server/test/local/dataflow_tests.js

Related to #2445.
The customs dataflow integration re-uses a pubsub queue that used to contain messages in a different format. As written, the error-handling code would keep pushing those old messages back onto the queue. This change fixes it by calling `message.ack()` instead of `message.nack()` on any old messages that can't be parsed.

fix(dataflow): ensure old-format messages don't clog the queue

---

package-lock.json
package.json
packages/fxa-auth-server/bin/key_server.js
packages/fxa-auth-server/config/index.js
packages/fxa-auth-server/lib/backendService.js
packages/fxa-auth-server/lib/customs.js
packages/fxa-auth-server/lib/oauthdb/index.js
packages/fxa-auth-server/lib/pushbox.js
packages/fxa-auth-server/lib/routes/index.js
packages/fxa-auth-server/lib/subhub/client.js
packages/fxa-auth-server/package-lock.json
packages/fxa-auth-server/package.json
packages/fxa-auth-server/test/local/backendService.js

feat(metrics): collect perf metrics with StatsD on auth server's HTTP API clients

---

packages/fxa-payments-server/server/config/index.js
packages/fxa-payments-server/server/lib/server.js
packages/fxa-payments-server/src/components/AppLayout/index.test.tsx
packages/fxa-payments-server/src/components/AppLayout/index.tsx
packages/fxa-payments-server/src/lib/config.test.ts
packages/fxa-payments-server/src/lib/config.ts

chore(legal): update payments server footer links

---

packages/fxa-content-server/app/scripts/models/flow.js
packages/fxa-content-server/app/tests/spec/models/flow.js

Related to https://github.com/mozilla/fxa/issues/2662#issuecomment-537078501.

fix(metrics): accept camel-cased flow metrics query params

---

packages/fxa-auth-server/fxa-oauth-server/lib/config.js

follow on for #2538
@vbudhram - r?

fix(config): Add an environment variable name for the auth server url

---

packages/fxa-auth-server/lib/error.js

Using the term verification code to be more user friendly than acronym

fix(copy): Changed OTP code to verification code

---

_scripts/postinstall.sh

The servers.json doesn't exist anymore

fix(dev): fix the local dev script

---

.github/ISSUE_TEMPLATE/bug_report.md
.vscode/extensions.json
packages/fxa-auth-db-mysql/.vscode/launch.json
packages/fxa-auth-db-mysql/.vscode/tasks.json
packages/fxa-auth-server/.vscode/launch.json
packages/fxa-auth-server/.vscode/tasks.json
packages/fxa-content-server/README.md
packages/fxa-customs-server/.vscode/launch.json
packages/fxa-customs-server/.vscode/tasks.json
packages/fxa-email-event-proxy/.vscode/launch.json
packages/fxa-event-broker/.vscode/launch.json
packages/fxa-event-broker/.vscode/tasks.json
packages/fxa-event-broker/package-lock.json
packages/fxa-event-broker/package.json
packages/fxa-geodb/.vscode/launch.json
packages/fxa-geodb/.vscode/tasks.json
packages/fxa-shared/.vscode/launch.json
packages/fxa-shared/.vscode/tasks.json
packages/fxa-support-panel/.vscode/launch.json
packages/fxa-support-panel/.vscode/tasks.json
packages/fxa-support-panel/package-lock.json
packages/fxa-support-panel/package.json

feat: add vscode tasks for running tests and debugger

---

packages/fxa-auth-server/fxa-oauth-server/lib/config/schema.json

fxa-dev is broken because the schema lost some convict format types

fix(config): fixed missing oauth config types

---

packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.tsx
packages/fxa-payments-server/src/components/fields.test.tsx
packages/fxa-payments-server/src/components/fields.tsx
packages/fxa-payments-server/src/routes/Product/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx

fix(payments): only show zip input error onBlur

---

packages/fxa-auth-server/fxa-oauth-server/lib/auth_server.js

fxa-dev special case

---

packages/fxa-auth-server/bin/email_notifications.js
packages/fxa-auth-server/bin/key_server.js
packages/fxa-auth-server/bin/profile_server_messaging.js
packages/fxa-auth-server/bin/subhub_messaging.js
packages/fxa-auth-server/lib/log.js
packages/fxa-auth-server/lib/notifier.js
packages/fxa-auth-server/lib/senders/index.js
packages/fxa-auth-server/lib/senders/sms.js
packages/fxa-auth-server/lib/sqs.js
packages/fxa-auth-server/scripts/bulk-mailer/index.js
packages/fxa-auth-server/test/local/notifier.js
packages/fxa-auth-server/test/local/senders/sms.js
packages/fxa-auth-server/test/local/sqs.js

feat(metrics): add statsd perf metrics for SNS/SQS in auth server

---

packages/fxa-auth-server/lib/subhub/updates.js
packages/fxa-auth-server/test/local/subhub/updates.js

fix(auth-server): call createAccountSubscription correctly

---

packages/fxa-auth-server/fxa-oauth-server/docs/jwt-access-tokens.md
packages/fxa-content-server/tests/server/routes.js

I'm not sure if this is the right place for this
or whether this should be an ADR.

feat(docs): Add a JWT access token doc.

---

packages/fxa-content-server/app/scripts/templates/cannot_create_account.mustache

fix(content-server): update COPPA URL. fixes #2572

---

packages/fxa-auth-server/config/dev.json
packages/fxa-auth-server/config/index.js
packages/fxa-auth-server/fxa-oauth-server/config/dev.json

fix(oauth): refuse default JWT signing key in production

---

packages/123done/static/js/123done.js

This needs an actual product id, so don't merge yet.

fix(123done): config 123done-prod redirect

---

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/token-code.js
packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/token-code.js

Targeted as a point release for Train 147.

Enable 100% signin codes for sync users

---

packages/fxa-auth-server/lib/senders/templates/verifyShortCode.html
packages/fxa-auth-server/lib/senders/templates/verifyShortCode.txt
packages/fxa-content-server/app/scripts/templates/confirm_signup_code.mustache
packages/fxa-content-server/app/scripts/templates/sign_in_token_code.mustache

Fixes #2238 
Fixes https://github.com/mozilla/fxa/issues/2576
These fixes are pretty small and only touch text, pulled into one PR.

Update expiration text and input field text from user testing

---

packages/fxa-auth-server/lib/subhub/updates.js
packages/fxa-auth-server/test/local/subhub/updates.js

check for existing subscription before attempting to create one, but
still send the download email
fixes #2769

fix(auth-server): skip redundant subscription create on subhub message

---

packages/fxa-auth-server/fxa-oauth-server/docs/jwt-access-tokens.md

chore(docs): Clarify a couple of things in jwt access token doc

---

.circleci/config.yml
.circleci/install-content-server.sh
.circleci/test-content-server.sh
circleci_servers.json
packages/fxa-circleci/Dockerfile
packages/fxa-content-server/tests/functional/sign_in_token_code.js

Move some install tasks up into a docker image and moved some tasks around to save a few minutes of CI time

use custom docker image for content-server ci tests

---

packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

chore(strings): fix typo in subscription settings

---

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/signup-code.js

fix(codes): Enabled signup code experiment for FPN website

---

README.md

@meandavejustice does this work for you on GCP?

fix(docs): Dynamically determine mailserver pm2 id

---

packages/fxa-auth-server/bin/subhub_messaging.js
packages/fxa-auth-server/lib/subhub/updates.js
packages/fxa-auth-server/test/local/subhub/updates.js

Because:
* The existing subhub processor had multiple states it failed to
account for.
* Profile cache locations were not updated.
This commit:
* Clears the profile cache and notifies that the profile was updated.
* Handles cancelled subscription state.
* Refactors subhub processor for less closure indents.
Closes #2851

fix(auth-server): rewrite subhub msg processor

---

packages/fxa-payments-server/src/lib/errors.ts

fix(payments) Basic payment submission error message update

---

packages/fxa-payments-server/src/App.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.stories.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.tsx
packages/fxa-payments-server/src/lib/flow-event.test.ts
packages/fxa-payments-server/src/lib/flow-event.ts
packages/fxa-payments-server/src/lib/test-utils.tsx
packages/fxa-payments-server/src/lib/types.tsx
packages/fxa-payments-server/src/routes/Product/index.stories.tsx
packages/fxa-payments-server/src/routes/Product/index.test.tsx
packages/fxa-payments-server/src/routes/Product/index.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx
packages/fxa-payments-server/src/store/actions.ts
packages/fxa-payments-server/src/store/amplitude-middleware.test.ts
packages/fxa-payments-server/src/store/amplitude-middleware.ts
packages/fxa-payments-server/src/store/index.tsx
packages/fxa-payments-server/src/store/thunks.ts
packages/fxa-payments-server/src/store/types.tsx

feat(metrics): add Amplitude metrics to payments pages

---

packages/fxa-auth-server/lib/subhub/updates.js

fix(auth-server): check proper code location

---

packages/fxa-payments-server/src/components/PaymentForm/index.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

fix(payments-server): use refs to track metric state

---

packages/fxa-auth-server/lib/subhub/updates.js
packages/fxa-auth-server/test/local/subhub/updates.js

fix(auth-server): compare message timestamp in milliseconds

---

packages/fxa-auth-server/lib/metrics/amplitude.js
packages/fxa-auth-server/test/local/metrics/amplitude.js

Fixes https://github.com/mozilla/fxa/issues/2976
Creating as draft since I need to figure out why test cases didn't catch it.
If we do another point on train-148 it would be nice to get on it.

fix(metrics): Fix email metrics not reporting to amplitude

---

packages/fxa-payments-server/src/components/LoadingOverlay.tsx

fix(styles): remove alt text from loading spinner on payments

---

packages/fxa-payments-server/src/components/PaymentForm/index.scss

fix(styles): fix invalid input shadow

---

packages/fxa-content-server/app/scripts/views/settings/change_password.jsx

A one-liner fix for your Friday enjoyment 🥂 
Fixes #3019.

fix(typo): stop event propagation correctly

---

packages/fxa-content-server/app/scripts/views/connect_another_device.js
packages/fxa-content-server/app/tests/spec/views/connect_another_device.js
packages/fxa-content-server/tests/functional/connect_another_device.js
packages/fxa-content-server/tests/functional/lib/helpers.js

feat(email-first): Use email-first for CAD by default.

---

packages/fxa-payments-server/src/components/PaymentForm/index.tsx
packages/fxa-payments-server/src/components/fields.test.tsx
packages/fxa-payments-server/src/components/fields.tsx

chore(styles): make price and billing cycle bold on payments page

---

packages/fxa-auth-server/scripts/write-emails-to-disk.js
packages/fxa-auth-server/test/scripts/write-emails-to-disk.js

Found in https://github.com/mozilla/fxa/pull/2921. This updates the script to pass mock statd object.
Fixes #2964

fix(emails): Fix write-emails-to-disk script

---

packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

fix(payment-server): cancel dialog loading indication in button

---

packages/fxa-content-server/app/scripts/models/account.js
packages/fxa-content-server/app/scripts/views/index.js
packages/fxa-content-server/app/scripts/views/mixins/session-verification-poll-mixin.js
packages/fxa-content-server/app/scripts/views/oauth_index.js
packages/fxa-content-server/app/tests/spec/views/index.js
packages/fxa-content-server/app/tests/spec/views/mixins/session-verification-poll-mixin.js
packages/fxa-content-server/app/tests/spec/views/oauth_index.js
packages/fxa-content-server/tests/functional/bounced_email.js
packages/fxa-content-server/tests/functional/lib/helpers.js
packages/fxa-content-server/tests/functional/lib/selectors.js
packages/fxa-content-server/tests/functional/oauth_sign_up.js

feat(email-first): Add bounce handling to the email-first flow

---

packages/fxa-payments-server/public/index.html

Embed bg color

---

packages/fxa-payments-server/src/lib/test-utils.tsx
packages/fxa-payments-server/src/routes/Product/PlanDetails/Details123DonePro.tsx
packages/fxa-payments-server/src/routes/Product/PlanDetails/DetailsDefault.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionRedirect/index.test.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionRedirect/index.tsx
packages/fxa-payments-server/src/routes/Product/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

chore(text): use product name on payments server instead of plan

---

packages/fxa-payments-server/src/components/PaymentForm/index.tsx

fix(links): open stripe priv notice in new window

---

packages/fxa-content-server/app/scripts/templates/index.mustache
packages/fxa-content-server/app/scripts/views/index.js
packages/fxa-content-server/app/scripts/views/mixins/sync-suggestion-mixin.js
packages/fxa-content-server/app/scripts/views/sign_up.js
packages/fxa-content-server/app/tests/spec/views/mixins/sync-suggestion-mixin.js
packages/fxa-content-server/tests/functional/sign_up.js

feat(email-first): Add the sync-suggestion UI to email-first flow

---

packages/fxa-auth-db-mysql/Dockerfile-build
packages/fxa-auth-db-mysql/grunttasks/nsp.js
packages/fxa-auth-db-mysql/package-lock.json
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/package-lock.json
packages/fxa-auth-server/package.json
packages/fxa-content-server/Dockerfile-build
packages/fxa-content-server/package-lock.json
packages/fxa-content-server/package.json
packages/fxa-content-server/server/lib/version.js

I'm a little nervous because I couldn't figure out where the `shrink` npm run script is called 🤷‍♂️, otherwise not much to see here. Also fixed an nsp error in auth-server.

Remove the last few npm-shrinkwrap files

---

packages/fxa-auth-server/lib/routes/account.js
packages/fxa-auth-server/test/local/routes/account.js

fix(auth-server): skip subhub request when local db has no subscriptions

---

packages/fxa-content-server/tests/functional/email_opt_in.js

On latest, clicking on the "Email preferences" link redirected
the user to a random allzom.org page because latest is not
hooked up to basket. Instead of redirecting to basket,
check the link is well-formed as we understand it.
fixes #3102

fix(test): Fix the communication preferences - open manage link test

---

packages/fxa-content-server/app/scripts/templates/sign_in_recovery_code.mustache
packages/fxa-content-server/app/scripts/templates/sign_in_totp_code.mustache
packages/fxa-content-server/app/scripts/views/sign_in_recovery_code.js
packages/fxa-content-server/app/tests/spec/views/sign_in_recovery_code.js

fix(2fa): Add `Are you locked out` links

---

packages/fxa-content-server/app/scripts/templates/support.mustache
packages/fxa-content-server/app/scripts/views/support.js
packages/fxa-content-server/app/tests/spec/views/support.js

fix(buttons): add UI to disable support buttons while user submits

---

packages/fxa-content-server/app/scripts/templates/partial/support-form-success.mustache
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx

fix(strings): grammar issues in subscription strings

---

packages/fxa-content-server/tests/teamcity/run.sh

Also, skip mocha here. r? - @shane-tomlinson

fix(test): skip mocha while running teamcity

---

packages/fxa-payments-server/src/routes/Product/index.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx
packages/fxa-payments-server/src/store/selectors.ts

fixes #2372
- remove outdated comment
- add redirect to settings
- update tests

fix(payments): redirect to settings if customer has no subscriptions

---

.circleci/config.yml

Once #2825 is ready this'll be ready to go

chore(build): use mozilla/fxa-circleci

---

packages/fxa-content-server/app/scripts/lib/metrics.js
packages/fxa-content-server/app/scripts/views/settings/account_recovery/account_recovery.js
packages/fxa-content-server/app/scripts/views/settings/emails.js
packages/fxa-content-server/app/scripts/views/settings/two_step_authentication.js
packages/fxa-content-server/app/tests/spec/lib/metrics.js
packages/fxa-content-server/app/tests/spec/views/settings/account_recovery/account_recovery.js
packages/fxa-content-server/app/tests/spec/views/settings/emails.js
packages/fxa-content-server/app/tests/spec/views/settings/two_step_authentication.js
packages/fxa-content-server/server/lib/routes/post-metrics.js
packages/fxa-content-server/server/lib/validation.js
packages/fxa-payments-server/server/lib/amplitude.js
packages/fxa-payments-server/server/lib/amplitude.test.js
packages/fxa-payments-server/server/lib/routes/post-metrics.js
packages/fxa-shared/metrics/amplitude.js
packages/fxa-shared/test/metrics/amplitude.js

From today's meeting these are the commits that we wanted to get into the point release. 
Ref: https://docs.google.com/document/d/1dIkxIyp-6mieJ3oYG7f-jHX_1Vj_9fAmnyXxuKxGOMg/edit#
Cirlce is having a bad day and not running tests, so I'll hold off on tagging until we get ✅

Train 149 cherry pick master

---

README.md

task(monorepo): link to package docs in main README.md

---

_scripts/fxa_email_service.sh
_scripts/mysql.sh
_scripts/pushbox.sh
_scripts/pushbox_db.sh

fix(local): fixed localhost docker networking

---

package.json

maybe this will help the random lerna errors? let's find out

fix(build): try --parallel on lerna npm-ci-all

---

packages/fxa-auth-server/lib/routes/emails.js

I'm really leaning on the tests to tell me that I haven't borked anything.  Preferably someone who's familiar with the emails routes will review this.

refactor(api): prefer async/await in emails routes

---

_scripts/install_packages.sh
package-lock.json
package.json

fix(build): go back to `concurrently` for `install_packages.sh`

---

packages/fxa-content-server/app/scripts/templates/choose_what_to_sync.mustache

Update button copy at the request of the content team

fix(copy):Optional button change

---

packages/fxa-auth-server/lib/routes/defaults.js

refactor(async/await): Update lib/routes/defaults to use async/await

---

packages/fxa-auth-server/bin/key_server.js
packages/fxa-auth-server/lib/routes/utils/oauth.js
packages/fxa-auth-server/scripts/test-local.sh

running auth-server tests locally broked

fix(tests): baaaaAAAAA 🤯

---

_scripts/install_packages.sh
package.json

seeing if this improves the errno 254 situation

fix(build): slow-roll npm ci on circle

---

packages/fxa-content-server/app/scripts/views/mixins/signin-mixin.js
packages/fxa-content-server/app/scripts/views/would_you_like_to_sync.js
packages/fxa-content-server/tests/functional/fx_browser_relier.js

fix(cwts): no longer present a CWTS option for sign-in flows

---

packages/fxa-payments-server/src/routes/Product/index.test.tsx
packages/fxa-payments-server/src/routes/Product/index.tsx

fix for #3151
@johngruen please confirm we also want to update the header to be more generic.

chore(payments/copy): Update subscription failed error message to display generic error

---

packages/fxa-content-server/app/scripts/templates/sms_send.mustache
packages/fxa-content-server/app/styles/modules/_graphic.scss
packages/fxa-content-server/app/tests/spec/views/sms_send.js
packages/fxa-content-server/tests/functional/sync_v3_sign_up.js

feat(cad): Make connect another device direct-link friendly

---

packages/fxa-content-server/app/scripts/views/elements/otp-code-input.js
packages/fxa-content-server/app/tests/spec/views/confirm_signup_code.js
packages/fxa-content-server/app/tests/spec/views/elements/otp-code-input.js

fix(input): Fix otp code input error

---

packages/fxa-content-server/tests/functional/settings_common.js

The functional tests in /tests/functional/settings_common.js were
not being run because the suites were being added to the test
runner incorrectly.
This ensures the tests run, as well as pass (they didn't once
enabled), and converts inline selectors to use the selectors
module.
fixes #3280

fix(test): Ensure settings_common tests are run

---

packages/fxa-payments-server/src/components/fields.tsx

feat(payments): more explicit auto-focus for name field

---

packages/fxa-content-server/app/scripts/views/index.js
packages/fxa-content-server/app/scripts/views/settings/delete_account.js
packages/fxa-content-server/app/tests/spec/views/index.js
packages/fxa-content-server/app/tests/spec/views/settings/delete_account.js
packages/fxa-content-server/tests/functional/delete_account.js
packages/fxa-content-server/tests/functional/sign_in_totp.js

feat(email-first): delete-account now completes at /

---

packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx

fixes #3299 
This copy was confirmed/approved by @johngruen.

chore(payments/copy): Update cancel subscription item copy to prevent confusion

---

CONTRIBUTING.md

This came up in the weekly meeting today, and it seemed worth adding to the docs.

chore(docs): clarify how estimates work for PRs

---

packages/fxa-auth-server/fxa-oauth-server/lib/metrics/amplitude.js
packages/fxa-auth-server/fxa-oauth-server/test/metrics/amplitude.js

This reverts commit ffc08790a4f17a455c229a4b4f6807f7cd505375.

fix(metrics): Restore high volume oauth events from amplitude logging

---

packages/fxa-auth-server/test/known-ip-location.js

Not associated with an issue, but noticed geodb reports a new city. This updates tests to check for it.

fix(tests): Add Fairfield to known cities

---

packages/fxa-content-server/app/styles/modules/support.scss

fix(style): Support panel - disable horizontal textarea resizing

---

packages/fxa-payments-server/.nsprc
packages/fxa-payments-server/package-lock.json
packages/fxa-payments-server/package.json

- https://www.npmjs.com/advisories/1316
- https://www.npmjs.com/advisories/1300
fixes #3238

security(payments): force an upgrade to handlebars dependency

---

packages/fxa-content-server/app/scripts/templates/sign_in_token_code.mustache

fix(codes): Update resend signin code link text

---

packages/fxa-payments-server/package-lock.json
packages/fxa-payments-server/package.json

https://www.npmjs.com/advisories/1324
https://www.npmjs.com/advisories/1325

chore(payments): bump handlebars up to 4.5.3

---

packages/fxa-profile-server/Dockerfile-build
packages/fxa-profile-server/Dockerfile-test

Unit tests are failing with 1.3.32
maybe this mitigates #3414

fix(profile-server): revert graphicsmagick to 1.3.31

---

packages/fxa-auth-server/lib/routes/subscriptions.js
packages/fxa-auth-server/lib/subhub/client.js
packages/fxa-auth-server/test/local/routes/subscriptions.js

Because:
* We want to support plan upgrades for subscriptions.
* SubHub API now has tiered subscription API's.
This commit:
* Extends the upgrade API to use the new SubHub API.
Closes #3273

feat(auth-server): add tiered subs with subhub

---

packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx

fix for #3438 
Super quick so I decided to get this issue resolved this morning.

chore(copy): fix #3438 - Update payments upgrade billing copy

---

packages/fxa-content-server/app/scripts/models/auth_brokers/fx-sync-channel.js
packages/fxa-content-server/app/scripts/views/mixins/cwts-on-signup-password-experiment-mixin.js
packages/fxa-content-server/app/tests/spec/models/auth_brokers/fx-sync-channel.js
packages/fxa-content-server/app/tests/spec/views/mixins/cwts-on-signup-password-experiment-mixin.js

Fixes https://github.com/mozilla/fxa/issues/3440

fix(sync): fix data choice select for service=sync Sync flows

---

packages/fxa-auth-server/config/dev.json
packages/fxa-auth-server/config/index.js

fix(email): update subscription TOS url to be correct

---

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/cwts-on-signup-password.js
packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/cwts-on-signup-password.js
packages/fxa-content-server/tests/functional/sync_v3_sign_up.js

Does not affect the sync optional flow.
@mozilla/fxa-devs - r? We'll want to cherry-pick this into train-150 and 151 too.

feat(cwts): 100% of sync users see CWTS on signup page

---

.circleci/config.yml
packages/fxa-content-server/tests/functional/lib/helpers.js
packages/fxa-content-server/tests/intern.js

This reverts commit b31dca72443ebb275f83d3d733ff0823c469ab44.
fixes #3510

Revert "fix(circleci): use default size resources for content-server tests"

---

packages/fxa-content-server/webpack.config.js

issue #3517
issue #3509
@vladikoff - r?

fix(sentry): Remove Sentry until we get its configuration figured out.

---

packages/fxa-content-server/app/scripts/views/confirm_signup_code.js
packages/fxa-content-server/app/tests/spec/views/confirm_signup_code.js
packages/fxa-content-server/tests/functional/sign_up_with_code.js

/confirm_signup_code didn't have bounce handling. This changes that.
fixes #3405
@vbudhram - r?

feat(signup-code): Add bounce handling to /confirm_signup_code

---

packages/fxa-customs-server/.nsprc
packages/fxa-customs-server/package-lock.json
packages/fxa-customs-server/package.json

- remove npm advisory exception
Not sure of the best way to test this manually.

chore(fxa-customs-server): update google-code/pubsub

---

packages/fxa-content-server/package-lock.json
packages/fxa-content-server/package.json
packages/fxa-content-server/server/lib/configuration.js

Just tidying up some unused settings in config for content server

task(fxa-content-server): tidy up sentry configuration in content server

---

.circleci/config.yml
packages/fxa-content-server/tests/functional/lib/helpers.js

Pretty rudimentary but a step towards #3513

feat(ci): store screenshots as ci artifacts

---

packages/fxa-content-server/app/scripts/lib/constants.js
packages/fxa-content-server/app/scripts/models/reliers/relier.js
packages/fxa-content-server/app/scripts/templates/account_recovery_confirm_key.mustache
packages/fxa-content-server/app/scripts/templates/confirm_signup_code.mustache
packages/fxa-content-server/app/scripts/templates/force_auth.mustache
packages/fxa-content-server/app/scripts/templates/index.mustache
packages/fxa-content-server/app/scripts/templates/ready.mustache
packages/fxa-content-server/app/scripts/templates/reset_password.mustache
packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache
packages/fxa-content-server/app/scripts/templates/sign_in_recovery_code.mustache
packages/fxa-content-server/app/scripts/templates/sign_in_totp_code.mustache
packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache
packages/fxa-content-server/app/scripts/views/mixins/service-mixin.js
packages/fxa-content-server/app/scripts/views/ready.js
packages/fxa-content-server/app/tests/spec/views/force_auth.js
packages/fxa-content-server/app/tests/spec/views/mixins/service-mixin.js
packages/fxa-content-server/app/tests/spec/views/ready.js

feat(content-server): Set relier 'serviceName' default to 'Account Settings'

---

.circleci/build.sh
packages/fxa-profile-server/Dockerfile-build
packages/fxa-profile-server/lib/profileCache.js
packages/fxa-profile-server/lib/server/web.js
packages/fxa-profile-server/package-lock.json
packages/fxa-profile-server/package.json

chore(fxa-profile-server): install fxa-shared directly in docker build

---

packages/fxa-payments-server/server/lib/server.js

fix(payments-server): update meta tags in index.html for each request

---

packages/fxa-payments-server/server/lib/csp.test.js
packages/fxa-payments-server/server/lib/csp/blocking.js

feat(payments): add accounts-static CDN as imgSrc to CSP header

---

.eslintrc
packages/fxa-auth-server/.eslintrc
packages/fxa-auth-server/.vscode/launch.json
packages/fxa-auth-server/bin/key_server.js
packages/fxa-auth-server/lib/cache.js
packages/fxa-auth-server/lib/db.js
packages/fxa-auth-server/lib/metrics/context.js
packages/fxa-auth-server/lib/server.js
packages/fxa-auth-server/package-lock.json
packages/fxa-auth-server/package.json

Async/await updates to:
* cache.js
* db.js
* server.js
* context.js

refactor(auth-server): async/await updates

---

packages/fxa-auth-server/lib/backendService.js
packages/fxa-auth-server/lib/profile/updates.js
packages/fxa-auth-server/lib/signer.js

Updates for async/await:
* signer.js
* updates.js
* backendService.js
Issue #2305

refactor(auth-server): asyncify signer/updates/BS

---

packages/fxa-auth-server/lib/authMethods.js
packages/fxa-auth-server/lib/devices.js
packages/fxa-auth-server/lib/push.js

refactor(auth-server): asyncify devices/push/AM

---

packages/fxa-auth-server/lib/tokens/bundle.js
packages/fxa-auth-server/lib/tokens/key_fetch_token.js
packages/fxa-auth-server/lib/tokens/password_forgot_token.js
packages/fxa-auth-server/lib/tokens/token.js

refactor(auth-server): asyncify lib/tokens

---

packages/fxa-auth-server/lib/email/bounces.js
packages/fxa-auth-server/lib/email/delivery.js
packages/fxa-auth-server/lib/email/notifications.js
packages/fxa-auth-server/lib/email/utils/helpers.js
packages/fxa-auth-server/test/local/email/utils.js

refactor(auth-server): asyncify lib/email

---

_scripts/check.sh

fix(build): update check.sh to use node 12

---

packages/fxa-auth-server/lib/routes/utils/otp.js
packages/fxa-auth-server/lib/routes/utils/signup.js

refactor(auth-server): asyncify utils/otp and utils/signup

---

packages/fxa-auth-server/test/remote/account_create_with_code_tests.js

Fixes https://github.com/mozilla/fxa/issues/3661 by making it the minimum code window size.

fix(test): Update sign up code previous window test

---

.circleci/test-js-client.sh
packages/123done/README.md
packages/browserid-verifier/README.md
packages/fxa-auth-db-mysql/README.md
packages/fxa-auth-server/README.md
packages/fxa-content-server/.gitignore
packages/fxa-content-server/README.md
packages/fxa-content-server/package.json
packages/fxa-customs-server/README.md
packages/fxa-email-event-proxy/README.md
packages/fxa-email-service/README.md
packages/fxa-geodb/README.md
packages/fxa-js-client/CONTRIBUTING.md
packages/fxa-js-client/Gruntfile.js
packages/fxa-js-client/README.md
packages/fxa-js-client/tasks/watch.js
packages/fxa-profile-server/README.md

- removed pre-monorepo stale build status badges for circleci
- refs #3630

chore(monorepo): remove stale references to travisci

---

packages/fxa-payments-server/server/config/development.json
packages/fxa-payments-server/server/config/index.js
packages/fxa-payments-server/src/lib/config.test.ts
packages/fxa-payments-server/src/lib/config.ts
packages/fxa-payments-server/src/routes/Product/SubscriptionRedirect/index.scss
packages/fxa-payments-server/src/routes/Product/SubscriptionRedirect/index.test.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionRedirect/index.tsx
packages/fxa-payments-server/src/routes/Product/index.test.tsx

Implement subscribe survey

---

packages/fxa-payments-server/server/config/development.json
packages/fxa-payments-server/server/config/index.js
packages/fxa-payments-server/src/lib/config.test.ts
packages/fxa-payments-server/src/lib/config.ts
packages/fxa-payments-server/src/routes/Product/SubscriptionRedirect/index.scss
packages/fxa-payments-server/src/routes/Product/SubscriptionRedirect/index.test.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionRedirect/index.tsx
packages/fxa-payments-server/src/routes/Product/index.test.tsx

Reverts mozilla/fxa#3653
It's breaking a couple functional tests.

Revert "Implement subscribe survey"

---

packages/fxa-auth-server/config/index.js

chore(metrics): up the default auth server StatsD sampling rate to 1

---

packages/fxa-payments-server/src/components/DialogMessage.stories.tsx
packages/fxa-payments-server/src/components/DialogMessage.test.tsx
packages/fxa-payments-server/src/components/DialogMessage.tsx
packages/fxa-payments-server/src/routes/Product/index.test.tsx
packages/fxa-payments-server/src/routes/Product/index.tsx

fix(payments): hide dialog close button for "plan not found" error

---

.circleci/config.yml

Might fix https://github.com/mozilla/fxa/issues/3771

fix(build): set MySQL 5.7.27 for the email service testing build

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/components/AppLayout/index.tsx

App layout l10n

---

packages/fxa-auth-server/lib/routes/index.js
packages/fxa-auth-server/lib/routes/session.js
packages/fxa-auth-server/test/local/routes/session.js

Fixes https://github.com/mozilla/fxa/issues/3734
Targeted as a point release for train 152 since metrics related.
Before metrics logged:
```
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_login - success","time":1577114787032,"user_id":"a444f5dcb7924b09b2ab0a7504959f1c","device_id":"50f6f2dde66d4187ad2b423ddb9b180c","session_id":1577114754082,"app_version":"152.1","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"flow_id":"0dee63f2d16b2ff08a242eba1cb992258bb68bde8a5a1949dc9b82b040dfc329","ua_browser":"Firefox","ua_version":"71.0","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_email - sent","time":1577114787640,"user_id":"a444f5dcb7924b09b2ab0a7504959f1c","device_id": …
```

fix(metrics): Emit the `email_confirmed` metric when user verifies a sign-in

---

packages/fxa-payments-server/src/components/Tooltip/index.stories.tsx
packages/fxa-payments-server/src/components/Tooltip/index.test.tsx
packages/fxa-payments-server/src/components/Tooltip/index.tsx

chore(payments-server): move tooltip to directory

---

packages/fxa-payments-server/src/components/DialogMessage/index.scss
packages/fxa-payments-server/src/components/DialogMessage/index.stories.tsx
packages/fxa-payments-server/src/components/DialogMessage/index.test.tsx
packages/fxa-payments-server/src/components/DialogMessage/index.tsx

chore(payments-server): move dialog message component into directory

---

packages/fxa-payments-server/src/components/AlertBar/index.scss
packages/fxa-payments-server/src/components/AlertBar/index.stories.tsx
packages/fxa-payments-server/src/components/AlertBar/index.test.tsx
packages/fxa-payments-server/src/components/AlertBar/index.tsx

chore(payments-server): move AlertBar component files into directory

---

packages/fxa-payments-server/src/components/ErrorMessage/index.scss
packages/fxa-payments-server/src/components/ErrorMessage/index.tsx

chore(payments-server): move error message component into directory

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/routes/Product/PlanDetails/Details123DonePro.tsx
packages/fxa-payments-server/src/routes/Product/PlanDetails/DetailsDefault.tsx

chore(payments-server): l10n for plan details

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/routes/Product/index.tsx

chore(payments-server): l10n for product route index

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/components/PaymentLegalBlurb/index.tsx

chore(payments-server): add l10n for payment legal blurb

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/components/PaymentForm/index.stories.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.tsx
packages/fxa-payments-server/src/components/fields.tsx

chore(payments-server): add l10n to payments form component

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/routes/Product/SubscriptionRedirect/index.tsx

chore(payments-server): SubscriptionRedirect l10n

---

packages/fxa-payments-server/.storybook/config.js

chore(payments-server): fix Storybook build for missing App.scss

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/components/fields/index.test.tsx
packages/fxa-payments-server/src/components/fields/index.tsx

chore(payments-server): l10n and componetize for fields.tsx

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx

chore(payments-server): SubscriptionUpgrade l10n

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ManagementPanel.tsx
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/SuccessDialog.tsx

chore(payments-server): Reactivate l10n

---

packages/fxa-profile-server/Dockerfile-build
packages/fxa-profile-server/package.json
packages/fxa-profile-server/test/lib/inject.js

Update profile server to node 12

---

packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.tsx

fix(payments): ensure a request is not already in progress on submission

---

packages/fxa-content-server/app/scripts/models/account.js
packages/fxa-content-server/app/tests/spec/models/account.js

fix(totp): disabling totp should change totpVerified state

---

packages/fxa-auth-server/lib/routes/emails.js
packages/fxa-auth-server/package-lock.json
packages/fxa-auth-server/test/local/payments/fixtures/customer1_new_email.json
packages/fxa-auth-server/test/local/routes/emails.js

Because:
* We need to keep Stripe up to date on email changes.
This commit:
* Update the customer record in Stripe when the email changes.
Closes #3813

feat(auth-server): update Stripe on email change

---

packages/fxa-content-server/app/styles/modules/_button-row.scss

fix(style): disabled cursor changed to not-allowed

---

packages/fxa-content-server/app/scripts/templates/settings/recovery_codes.mustache

show success message on recovery code copy/download

---

packages/fxa-content-server/app/scripts/views/settings/recovery_codes.js

fixed validation string for recovery code confirmation

---

_scripts/upload_assets_to_cdn.sh

Just remind to check that you are on master when running this.
r? - @jbuck

fix(assets): add a self-documenting echo comment

---

packages/fxa-content-server/app/styles/modules/_button-row.scss

fix(style): background darkness fixed on hovering disable button

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx

chore(payments-server): add l10n to PaymentUpdateForm

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx

chore(payments-server): add l10n to subscriptionItem

---

packages/fxa-content-server/app/scripts/views/account_recovery_confirm_key.js
packages/fxa-content-server/app/tests/spec/views/account_recovery_confirm_key.js

Fixes #3842 
@LZoog Took a look at this and it turned out to be a one liner 😬. We needed to import the `ServiceNameMixin` into the view. I'm not really sure when this bug was introduced or regressed.
Also added some more tests to hopefully catch it next time. r?

fix(service): Show service name when loading reset password with recovery key

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/components/DialogMessage/index.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

chore(payments-server): aria label l10n

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/AccountActivatedBanner.tsx

chore(payments-server): account activated banner l10n

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

chore(payments-server): add l10n to subscription route index

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx

chore(payments-server): create subscription index l10n

---

packages/fxa-auth-server/lib/routes/utils/subscriptions.js

followup to PR #3918 with a clarity tweak that I neglected to commit

chore(subscriptions): code clarity tweak for determining subscriptions

---

packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx

fix(payments): ensure correct month used in credit card expiration

---

packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.tsx

fix(payments): filter non-numeric characters out of zip code field

---

packages/fxa-auth-server/lib/routes/session.js

Fixes #3970 
Simple fix based on rfk recommendation of reordering the order that the verification events and notifications happen. Make sure that the session and account are verified and then send push notifications to connected devices.

fix(codes): Verify session first then send push notifications

---

packages/fxa-auth-server/lib/routes/subscriptions.js

Noticed an internal service error while investigating FXA-1026 / #4038 - looks like we weren't catching the card error from rejection of the payment token on subscription create. This tweak seems to wrap it in the error expected by the frontend.

fix(subscriptions): wrap payment token failures in expected error class

---

docs/adr/0009-testing-stacks.md

fixes #3993
This is a draft that I *think* captures what we came up with in Berlin. If anyone wants to review / add / revise, we can do that and add to the "Deciders" list here

chore(adr): note choices in testing stacks

---

packages/fxa-payments-server/public/locales/en-US/main.ftl

fix(payments): Add dollar signs to prices on product subscription page

---

packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx

fix(payments): ensure correct 'try again' message used for card_declined error

---

packages/fxa-auth-server/lib/payments/stripe.js
packages/fxa-auth-server/lib/routes/subscriptions.js
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/subscriptions.js

fix(payments): refresh cached customer data rather than delete

---

.circleci/config.yml

I need to fix up how/when coveralls does it coverage reporting. In the meantime, this disables it.
@chenba r?

fix(cov): Disable coveralls reporting

---

packages/fxa-auth-server/scripts/populate-stripe-customer-cache.js

https://jira.mozilla.com/browse/FXA-1063
fixes #4089

feat(payments): script to populate redis cache with Stripe customers

---

packages/fxa-content-server/app/scripts/models/auth_brokers/base.js
packages/fxa-content-server/app/tests/spec/models/auth_brokers/base.js
packages/fxa-content-server/app/tests/spec/models/auth_brokers/oauth-webchannel-v1.js

feat(webchannels): report context in the status message

---

packages/fxa-auth-server/.vscode/launch.json
packages/fxa-auth-server/lib/payments/stripe.js
packages/fxa-auth-server/lib/routes/subscriptions.js
packages/fxa-auth-server/test/local/payments/fixtures/customer_new.json
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/fixtures/abbreviated_product_list.json
packages/fxa-auth-server/test/local/routes/subscriptions.js
packages/fxa-auth-server/test/mocks.js

increased code coverage for payments/stripe.js
added Arch 2.0 code coverage and test runner to launch.json
issue #4073

test(fxa stripeHelper): add tests

---

packages/fxa-auth-server/test/local/routes/account.js

Because:
* My prior commit didn't update tests for the direct stripe account
delete route.
This commit:
* Add's tests for the direct stripe account delete route.
Closes #4160

test(auth-server): add missing direct stripe test

---

packages/fxa-auth-server/scripts/delete-account.js

https://jira.mozilla.com/browse/FXA-1024

fix(auth-server): Get delete-account.js working again

---

packages/fxa-auth-server/lib/luaScripts/getAccessToken_1.lua
packages/fxa-auth-server/lib/luaScripts/getAccessTokens_1.lua
packages/fxa-auth-server/lib/luaScripts/removeAccessToken_1.lua
packages/fxa-auth-server/lib/luaScripts/removeAccessTokensForPublicClients_1.lua
packages/fxa-auth-server/lib/luaScripts/removeAccessTokensForUserAndClient_1.lua
packages/fxa-auth-server/lib/luaScripts/removeAccessTokensForUser_1.lua
packages/fxa-auth-server/lib/luaScripts/setAccessToken_2.lua
packages/fxa-auth-server/lib/oauth/db/accessToken.js
packages/fxa-auth-server/lib/redis.js
packages/fxa-auth-server/test/local/redis.js

feat(oauth): added redis scripts to store oauth access tokens

---

packages/fxa-auth-server/.vscode/launch.json
packages/fxa-auth-server/test/local/routes/subscriptions.js

- added coverage for the specified function
- updated vscode script for Arch 2.0 coverage
fixes #4226

test(auth-server): Coverage for handleOpenInvoice

---

packages/fxa-auth-server/test/local/routes/subscriptions.js

- added coverage for the specified function
- updated vscode script for Arch 2.0 coverage
fixes #4229

test(auth-server): Coverage for DirectStripeRoutes updateSubscription

---

packages/fxa-auth-server/lib/db.js
packages/fxa-auth-server/lib/routes/recovery-key.js
packages/fxa-js-client/client/FxAccountClient.js
packages/fxa-js-client/tests/lib/recoveryKeys.js

Extracted from https://github.com/mozilla/fxa/pull/4192 so that we can land the js client functions first and get the tests passing.

feat(recovery): Add confirm recovery key js client calls

---

packages/fxa-auth-server/test/local/routes/subscriptions.js

- added coverage for DirectStripeRoutes.createSubscription
fixes #4223

test(auth-server): Coverage for createSubscription

---

packages/fxa-auth-server/test/local/routes/subscriptions.js

- added coverage for DirectStripeRoutes.handleWebhookEvent
fixes #4231

test(auth-server): Coverage for handleWebhookEvent

---

packages/fxa-auth-server/test/local/routes/subscriptions.js

- added code coverage for DirectStripeRoutes.updatePayment
fixes #4224

test(auth-server): coverage for updatePayment

---

packages/fxa-content-server/app/scripts/views/settings/delete_account.js
packages/fxa-content-server/app/tests/spec/views/settings/delete_account.js

fix(delete-account): Include subscription status filtering for 'trialing' and 'past_due'

---

packages/fxa-auth-server/test/local/routes/subscriptions.js

- add coverage for DirectStripeRoutes.getCustomer
- fix broken test
fixes #4235

test(auth-server): add coverage for getCustomer

---

packages/fxa-customs-server/.eslintrc
packages/fxa-customs-server/lib/server.js
packages/fxa-customs-server/test/remote/flow_id_checks.js

Not connected to an issue but fixes our lint errors in customs server. Most of the changes here are due to prettier formatting the code.

fix(lint): Fix customs server lint issues

---

packages/fxa-auth-server/lib/server.js
packages/fxa-auth-server/package-lock.json
packages/fxa-auth-server/package.json
packages/fxa-auth-server/test/local/sentry.js
packages/fxa-auth-server/test/local/server.js
packages/fxa-auth-server/test/mail_helper.js
packages/fxa-auth-server/test/profile_helper.js
packages/fxa-auth-server/test/remote/db_tests.js

also couldn't help but rm the old redis lib

chore(auth): updated auth-server to latest hapi

---

CONTRIBUTING.md

Minor thing, but always annoys me.

chore(docs): correct ordering in estimation table in CONTRIBUTING doc

---

packages/fxa-content-server/app/scripts/templates/settings/subscription.mustache
packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/components/AppLayout/index.tsx
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx

task(content/payments): update subscription label to include payment

---

packages/fxa-content-server/app/scripts/views/pair/auth_totp.js
packages/fxa-content-server/app/tests/spec/views/pair/auth_totp.js

fix(content-server): Add serviceMixin to auth_totp

---

packages/fxa-admin-server/package-lock.json
packages/fxa-admin-server/package.json
packages/fxa-admin-server/src/bin/main.ts
packages/fxa-admin-server/src/config.ts
packages/fxa-admin-server/src/lib/sentry.ts
packages/fxa-admin-server/src/lib/server.ts
packages/fxa-admin-server/src/lib/version.ts
packages/fxa-admin-server/src/test/lib/sentry.spec.ts
packages/fxa-admin-server/tsconfig.json

Because:
* We have no sentry reporting of internal errors.
This commit:
* Captures internal resolver errors to Sentry.
Closes #4242

feat(admin-server): add sentry reporting

---

packages/fxa-content-server/app/scripts/views/post_verify/account_recovery/confirm_password.js
packages/fxa-content-server/app/scripts/views/post_verify/account_recovery/confirm_recovery_key.js
packages/fxa-content-server/server/lib/amplitude.js

Fixes #4402 
Marking as draft to see if any tests break.
To test go through the flow and view logs for content-server `./pm2 logs 11 | grep 'amplitudeEvent'`
Amplitude events for creating recovery key
```
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - add_recovery_key_view","time":1583346618519,"device_id":"c65d120d8717493f9f6e42b1a5878137","session_id":1583346618167,"app_version":"160.0","language":"en","os_name":"Mac OS X","os_version":"10.15","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"3d69805165159e0b13807eed9b59aee32b2fbdb9e79fbc05b4e727164ef1b02b","ua_browser":"Firefox","ua_version":"72.0","$append":{"fxa_services_used":"sync"}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_pref - …
```

fix(metrics): Add account recovery key flowEvents -> amplitudeEvents mapping

---

packages/fxa-auth-server/package-lock.json
packages/fxa-auth-server/package.json

fix(sms): Update google-libphonenumber to include newer area codes

---

packages/fxa-content-server/app/scripts/templates/post_verify/secondary_email/confirm_secondary_email.mustache
packages/fxa-content-server/app/scripts/views/post_verify/secondary_email/confirm_secondary_email.js
packages/fxa-content-server/app/scripts/views/post_verify/verified.js
packages/fxa-content-server/app/tests/spec/views/post_verify/secondary_email/confirm_secondary_email.js
packages/fxa-content-server/tests/functional/lib/selectors.js
packages/fxa-content-server/tests/functional/post_verify/secondary_email.js

fix(emails): Add `use different email` button to add secondary email page

---

packages/fxa-auth-server/scripts/clean-up-old-ci-stripe-customers.js
packages/fxa-content-server/tests/functional/sign_up.js
packages/fxa-content-server/tests/functional/support.js
packages/fxa-content-server/tests/intern.js

Turns out there's a difference in CI for passing env vars on PRs opened from forked repos vs the main repo. Trying this PR to see if it passes
FXA-1242
fixes #4339

fix(payments): re-enable functional tests with direct Stripe access

---

.circleci/config.yml

tests hang when run in `test-many`, let's try it's own job.

ci(payments): added payments-server to ci tests

---

packages/fxa-content-server/app/scripts/templates/post_verify/secondary_email/confirm_secondary_email.mustache
packages/fxa-content-server/app/scripts/views/post_verify/secondary_email/confirm_secondary_email.js
packages/fxa-content-server/app/tests/spec/views/post_verify/secondary_email/confirm_secondary_email.js

fix(emails): Fix the resend secondary email code button

---

packages/fxa-customs-server/bin/customs_server.js
packages/fxa-customs-server/lib/settings/requestChecks.js

This is so I have a way to check that I have the values I expect when this is set by a comma-separated environment variable.
r? - @clouserw

fix(customs): dump out config at startup

---

packages/fxa-payments-server/src/components/PaymentForm/index.stories.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx
packages/fxa-payments-server/src/components/PaymentForm/index.tsx
packages/fxa-payments-server/src/lib/hooks.test.tsx
packages/fxa-payments-server/src/lib/hooks.tsx
packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx

fix(payments): use a nonce to guard against repeat payment submissions

---

packages/fxa-content-server/app/scripts/lib/experiment.js
packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/index.js
packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/send-sms-header.js
packages/fxa-content-server/app/scripts/templates/sms_send.mustache
packages/fxa-content-server/app/scripts/views/sms_send.js
packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/index.js
packages/fxa-content-server/tests/functional/lib/selectors.js
packages/fxa-content-server/tests/functional/send_sms.js

fixes #4434
Co-authored-by: Jody Heavener <j.heavener@gmail.com>

feat(sms): Add A/B test for sms header copy

---

.circleci/assert-branch.sh
.circleci/base-install.sh
.circleci/build-all.sh
.circleci/build.sh
.circleci/create-version-json.sh
.circleci/deploy-all.sh
.circleci/deploy.sh
.circleci/test-package.sh

[Shellcheck](https://github.com/koalaman/shellcheck) made some recommendations.

lint(ci): .circleci shell script updates from shellcheck

---

packages/fxa-support-panel/lib/api.ts
packages/fxa-support-panel/lib/templates/index.html
packages/fxa-support-panel/test/lib/api.spec.ts

- add the subscription creation timestamp to the information displayed
fixes #3981
~~Blocked by https://github.com/mozilla/fxa/pull/4489~~

feat(support-panel): add subscription created date

---

packages/fxa-event-broker/package-lock.json
packages/fxa-event-broker/package.json

fix(event-broker): make uuid a full dependency

---

packages/fxa-content-server/app/scripts/templates/connect_another_device.mustache
packages/fxa-content-server/app/scripts/templates/pair/auth_complete.mustache
packages/fxa-content-server/app/scripts/templates/pair/index.mustache
packages/fxa-content-server/app/scripts/templates/pair/success.mustache
packages/fxa-content-server/app/scripts/templates/sms_sent.mustache

added `role` and `aria-label` 
closes #4473
@jodyheavener

Ensure correct `graphicId` HTML element / labels

---

.circleci/deploy-all.sh
.circleci/deploy.sh

slightly improved the output of the deploy step in ci

chore(ci): improved deploy log output

---

packages/fxa-auth-server/lib/payments/stripe.js
packages/fxa-auth-server/test/local/payments/stripe.js

- add interval_count to the Plan response object
- updated the value being returned for plan_name to use the aggreed plan name format, since the `nickname` is not intended for external (outside of Stripe) usage
- implement TODO for plan formatter: handle cases where the product for a plan hasn't loaded is or invalid
issue #3987

feat(auth-server): update plan response format

---

packages/fxa-content-server/app/scripts/models/user.js
packages/fxa-content-server/app/scripts/views/mixins/account-by-uid-mixin.js
packages/fxa-content-server/app/tests/spec/models/user.js
packages/fxa-content-server/app/tests/spec/views/mixins/account-by-uid-mixin.js
packages/fxa-content-server/app/tests/spec/views/settings.js
packages/fxa-content-server/tests/functional/settings.js

fixes #4293 
cc @johngruen @rfk

Don't log out of sync when clearing the signed in account on accounts.firefox.com

---

packages/fxa-auth-server/lib/oauth/grant.js
packages/fxa-auth-server/lib/routes/account.js
packages/fxa-auth-server/lib/routes/utils/subscriptions.js
packages/fxa-auth-server/scripts/clean-up-old-ci-stripe-customers.js
packages/fxa-auth-server/test/local/routes/utils/subscriptions.js
packages/fxa-auth-server/test/remote/subscription_tests.js
packages/fxa-content-server/tests/functional.js
packages/fxa-content-server/tests/functional/lib/selectors.js
packages/fxa-content-server/tests/functional/subscriptions.js
packages/fxa-profile-server/lib/routes/_core_profile.js
packages/fxa-profile-server/lib/routes/profile.js
packages/fxa-profile-server/lib/routes/subscriptions.js
packages/fxa-profile-server/lib/subscriptions.js

This is the same as PR #4571, but I'm giving it a try with a push to an upstream repo branch to ensure that CircleCI runs with a Stripe API key

fix(payments): end-to-end subscription functional test with profile caching bugfix

---

packages/fxa-content-server/app/scripts/views/sms_send.js

Ref: https://mozilla.slack.com/archives/GLV3KMZ8B/p1584628770324300

chore(todo): remove ancient TODO from the script

---

packages/fxa-content-server/server/lib/flow-event.js
packages/fxa-content-server/server/lib/statsd.js

A point release to fix a couple statsd metrics related issues.

Train 163 uplift for 163.1

---

packages/fxa-payments-server/src/lib/navigation-timing.ts

A point release to fix a Safari issue on Payments.

Train 163 Uplift for 163.2

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/routes/Product/PlanDetails/index.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.test.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx

- updated subscription billing description on settings page to handle various billing intervals and interval counts
issue #3987

feat(payment-server): update settings page billing description

---

packages/fxa-content-server/app/scripts/templates/settings/delete_account.mustache
packages/fxa-content-server/app/scripts/templates/settings/subscription.mustache
packages/fxa-content-server/app/styles/modules/_settings.scss

chore(styles): update sub cancel warning UI in settings

---

packages/fxa-auth-db-mysql/README.md

fix(docs): update MySQL version and node version

---

docs/adr/0010-transition-fxa-from-backbone-to-react.md
docs/adr/0011-create-new-react-app-for-settings-redesign.md

Gives #3430 an ADR with "Transition FxA from Backbone to React"
Closes #3741 with "Create a new React app for settings redesign"
Ready for review/commentary. ~I still need to add links and will do one more read for proofreading.~

docs(adrs): (1) Transition FxA from Backbone to React, (2) Create a new React app for settings redesign

---

packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx

task(payments-server): display billing name in confirmation page

---

packages/fxa-auth-server/lib/crypto/pbkdf2.js
packages/fxa-auth-server/package-lock.json
packages/fxa-auth-server/package.json

node has native pbkdf2 since v8

chore(deps): removed sjcl from auth-server

---

packages/fxa-auth-server/lib/metrics/amplitude.js
packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/lib/senders/templates/_versions.json
packages/fxa-auth-server/lib/senders/templates/subscriptionAccountDeletion.html
packages/fxa-auth-server/lib/senders/templates/subscriptionAccountDeletion.txt
packages/fxa-auth-server/test/local/senders/email.js

feat(payments): email method for subscription cancellation on account deletion

---

packages/fxa-profile-server/lib/routes/cache/delete.js

fix(profile): add missing await in cache delete

---

docs/adr/0012-next-two-factor-authentication.md
docs/adr/index.md

feat(docs): Add ADR for WebAuthn and FIDO2

---

packages/fxa-payments-server/Dockerfile

fix(Docker): fix path to a JSON schema in fxa-shared for Payments

---

packages/fxa-content-server/app/scripts/views/mixins/cwts-on-signup-password.js
packages/fxa-content-server/app/tests/spec/views/mixins/cwts-on-signup-password.js

fix(sync): Always show CWTS on signup for sync users

---

packages/fxa-content-server/Dockerfile

fix(docker): fix content-server build broken by last commit

---

packages/fxa-auth-server/lib/metrics/amplitude.js
packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/lib/senders/templates/_versions.json
packages/fxa-auth-server/lib/senders/templates/subscriptionPaymentExpired.html
packages/fxa-auth-server/lib/senders/templates/subscriptionPaymentExpired.txt
packages/fxa-auth-server/lib/senders/templates/subscriptionPaymentFailed.html
packages/fxa-auth-server/lib/senders/templates/subscriptionPaymentFailed.txt
packages/fxa-auth-server/test/local/metrics/amplitude.js
packages/fxa-auth-server/test/local/senders/email.js

feat(payments): email methods for subplat payment failed and expired

---

packages/fxa-auth-server/config/index.js
packages/fxa-auth-server/lib/payments/stripe.js
packages/fxa-auth-server/lib/routes/account.js
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/account.js

- remove ttl for cusomer caching
- ensure customer cache entry removal on account deletion
fixes #4651

refactor(payments): remove ttl for customer caching

---

README.md

fix(readme): Update the README section with more commands.

---

packages/fxa-auth-server/lib/routes/subscriptions.js
packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/test/local/payments/fixtures/event_invoice_payment_failed.json
packages/fxa-auth-server/test/local/routes/subscriptions.js
packages/fxa-auth-server/test/mocks.js

Depends on https://github.com/mozilla/fxa/pull/4781
FXA-1155

 feat(payments): send email on subscription payment failure

---

packages/fxa-auth-server/lib/payments/stripe.js
packages/fxa-auth-server/lib/routes/subscriptions.js
packages/fxa-auth-server/test/local/payments/fixtures/event_customer_source_expiring.json
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/mocks.js

- DRY up tests a bit
- also work email detail extraction helpers in general to throw errors
rather than still allow a nonsensical email to be sent out
FXA-1156

feat(payments): subplat email logic on payment expiring

---

packages/fxa-auth-server/lib/payments/stripe.js

- fix bad parameter
- add check to expandResource to prevent misuse in the future.

bug(auth-server): fix bad parameter being passed to stripeHelper.expandResource

---

packages/fxa-content-server/tests/teamcity/run.sh

Adjustment for https://github.com/mozilla/fxa/pull/4764
r? - @dannycoates

fix(test): install ../fxa-js-client

---

packages/fxa-auth-server/lib/error.js
packages/fxa-auth-server/lib/routes/emails.js
packages/fxa-auth-server/test/local/routes/emails.js
packages/fxa-auth-server/test/remote/recovery_email_emails.js
packages/fxa-content-server/app/scripts/lib/auth-errors.js
packages/fxa-content-server/app/tests/spec/views/post_verify/secondary_email/add_secondary_email.js
packages/fxa-content-server/tests/functional/settings_secondary_emails.js

feat(settings): add error for when you try to add a secondary email already on your account

---

packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx

task(payments-server): clear checkbox when stay subscribed clicked

---

packages/fxa-payments-server/src/components/PlanDetails/index.scss

task(payments-server): fix padding on hide/show button

---

docs/adr/0013-react-toolchain-for-settings-redesign.md

Closes #4811
📖 Preview [here](https://github.com/mozilla/fxa/blob/jh/4811-adr-settings-react-toolchain/docs/adr/0013-react-toolchain-for-settings-redesign.md) and review [here](https://github.com/mozilla/fxa/pull/4897/files).

docs(adrs): proposal for "React Toolchain for Settings Redesign"

---

packages/fxa-admin-panel/src/components/EmailBlocks/Account/index.tsx
packages/fxa-admin-panel/src/components/EmailBlocks/index.test.tsx
packages/fxa-admin-panel/src/components/EmailBlocks/index.tsx
packages/fxa-admin-panel/src/index.scss
packages/fxa-admin-server/README.md
packages/fxa-admin-server/scripts/email-bounce.ts

Closes #4209 
- Send request to GQL server to clear an account's email bounces / updated UI to reflect this action
- Updates/documents email bounce generation script

feat(admin panel): send mutation event to graphql server in order to unblock email

---

packages/fxa-email-event-proxy/package-lock.json
packages/fxa-email-event-proxy/package.json

Just some dependency updates, running in stage now.

fix(email-event-proxy): update dependency versions

---

packages/fxa-payments-server/public/locales/en-US/main.ftl
packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
packages/fxa-payments-server/src/routes/Product/index.test.tsx

task(payments-server): no more dialog errors in subscription create

---

packages/fxa-content-server/tests/functional/oauth_prompt_none.js

🙄 Can't forget to wait around during these functional tests...

bug(functional): fix breakage in login_hint test

---

packages/fxa-content-server/app/scripts/lib/constants.js
packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-webchannel-v1.js
packages/fxa-content-server/app/scripts/views/mixins/cwts-on-signup-password.js
packages/fxa-content-server/app/tests/spec/views/mixins/cwts-on-signup-password.js
packages/fxa-content-server/app/tests/test_start.js
packages/fxa-content-server/tests/functional/lib/helpers.js
packages/fxa-content-server/tests/functional/oauth_webchannel.js

Also, actually run the CWTS Sign up Tests
Fixes #4603
@vbudhram r?

fix(cwts): Display CWTS on signup page for Fenix and iOS

---

packages/fxa-auth-server/lib/payments/stripe.js
packages/fxa-auth-server/lib/routes/subscriptions.js
packages/fxa-auth-server/test/local/payments/fixtures/event_customer_subscription_updated.json
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/subscriptions.js

~Depends on https://github.com/mozilla/fxa/pull/4877 being merged first~
FXA-1159
FXA-1160

 feat(payments): logic for email on subscription upgrade/downgrade

---

packages/fxa-auth-server/lib/metrics/amplitude.js
packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/lib/senders/templates/_versions.json
packages/fxa-auth-server/lib/senders/templates/subscriptionReactivation.html
packages/fxa-auth-server/lib/senders/templates/subscriptionReactivation.txt
packages/fxa-auth-server/lib/senders/templates/subscriptionSubsequentInvoice.txt
packages/fxa-auth-server/test/local/metrics/amplitude.js
packages/fxa-auth-server/test/local/senders/email.js
packages/fxa-auth-server/test/mocks.js

https://jira.mozilla.com/browse/FXA-1157

feat(payments): email sender method for subscription reactivation

---

packages/fxa-auth-db-mysql/db-server/test/backend/db_tests.js
packages/fxa-auth-db-mysql/lib/db/mysql.js
packages/fxa-auth-db-mysql/lib/db/patch.js
packages/fxa-auth-db-mysql/lib/db/schema/patch-108-109.sql
packages/fxa-auth-db-mysql/lib/db/schema/patch-109-108.sql

feat(db): modified procedures to set verifiedAt field when email gets verified

---

packages/fxa-auth-server/package-lock.json
packages/fxa-auth-server/package.json
packages/fxa-auth-server/pm2.config.js
packages/fxa-auth-server/tsconfig.json

Closes #4884 
This is just laying some groundwork so that we can allow the Auth Server to slowly adopt TypeScript.

feat(auth server): prepare for typescript compilation

---

docs/adr/0014-auth-for-settings-redesign.md

docs(adrs): proposal for "Authentication in Settings Redesign"

---

packages/fxa-admin-server/src/bin/main.ts
packages/fxa-admin-server/src/config.ts
packages/fxa-admin-server/src/lib/middleware.ts
packages/fxa-admin-server/src/test/lib/middleware.spec.ts

feat(admin-server): set hsts header on all requests

---

packages/fxa-auth-server/lib/routes/emails.js
packages/fxa-auth-server/test/local/routes/emails.js
packages/fxa-auth-server/test/remote/recovery_email_emails.js

fix(auth server): change order of email checks so primary check comes first

---

packages/fxa-content-server/app/styles/modules/_settings.scss

fix(content-server): Header / modal collision index

---

packages/fxa-content-server/server/lib/csp/blocking.js
packages/fxa-content-server/tests/server/csp.js

- fixes #4796
- payments server already has a rule for surveygizmo

task(content-server): add csp rule for survey gizmo

---

packages/fxa-admin-panel/package.json
packages/fxa-payments-server/package.json
packages/fxa-support-panel/package-lock.json
packages/fxa-support-panel/package.json

bundling 2 commits/fixes into one PR - see commit messages

fixes for a couple build bugs

---

packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/lib/senders/templates/partials/subscriptionEmail.html
packages/fxa-auth-server/lib/senders/templates/subscriptionAccountDeletion.html
packages/fxa-auth-server/lib/senders/templates/subscriptionCancellation.html
packages/fxa-auth-server/lib/senders/templates/subscriptionDowngrade.html
packages/fxa-auth-server/lib/senders/templates/subscriptionFirstInvoice.html
packages/fxa-auth-server/lib/senders/templates/subscriptionPaymentExpired.html
packages/fxa-auth-server/lib/senders/templates/subscriptionPaymentFailed.html
packages/fxa-auth-server/lib/senders/templates/subscriptionReactivation.html
packages/fxa-auth-server/lib/senders/templates/subscriptionSubsequentInvoice.html
packages/fxa-auth-server/lib/senders/templates/subscriptionUpgrade.html
packages/fxa-auth-server/scripts/write-emails-to-disk.js

~Depends on #5038 being merged first~ (merged)
- extract a shared reusable partial template from subscription emails
- clean up some variable use in subscription email methods
https://jira.mozilla.com/browse/FXA-1639
fixes #4951

refactor(payments): subscription email cleanup & refactorings

---

packages/fxa-content-server/app/scripts/lib/auth/client.ts

Maybe fixes the support submission issue?

fix(client): Use correct support ticket url

---

packages/fxa-graphql-api/.prettierrc
packages/fxa-graphql-api/pm2.config.js
packages/fxa-graphql-api/src/bin/main.ts
packages/fxa-graphql-api/src/config.ts
packages/fxa-graphql-api/src/lib/db/index.ts
packages/fxa-graphql-api/src/lib/resolvers/account-resolver.ts
packages/fxa-graphql-api/src/lib/resolvers/types/account.ts
packages/fxa-graphql-api/src/lib/sentry.ts
packages/fxa-graphql-api/src/lib/server.ts
packages/fxa-graphql-api/src/lib/version.ts
packages/fxa-graphql-api/src/test/lib/db/models/helpers.ts
packages/fxa-graphql-api/src/test/lib/middleware.spec.ts
packages/fxa-graphql-api/src/test/lib/mocks.ts
packages/fxa-graphql-api/src/test/lib/schema.spec.ts
packages/fxa-graphql-api/src/test/lib/sentry.spec.ts

Formatting only commit.  It's not part of any issue.  I want keep these changes in a separate commit in case anyone want to use some git magic to skip them while viewing diffs.

chore(code style): update graphql-api to prettier 2 formatting

---

packages/fxa-content-server/app/styles/_base.scss
packages/fxa-content-server/app/styles/_breakpoints.scss
packages/fxa-content-server/app/styles/fontello.scss
packages/fxa-content-server/app/styles/modules/_avatar.scss
packages/fxa-content-server/app/styles/modules/_button-row.scss
packages/fxa-content-server/app/styles/modules/_chosen.scss
packages/fxa-content-server/app/styles/modules/_graphic.scss
packages/fxa-content-server/app/styles/modules/_input-row.scss
packages/fxa-content-server/app/styles/modules/_marketing.scss
packages/fxa-content-server/app/styles/modules/_settings-totp.scss
packages/fxa-content-server/app/styles/modules/_settings.scss

style(fxa-content-server): fix lint errors

---

packages/fxa-auth-server/lib/routes/subscriptions.js
packages/fxa-auth-server/test/local/routes/subscriptions.js

fix(payments): avoid sending redundant subscription cancellation email after account deletion

---

packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/lib/senders/templates/layouts/subscription.html
packages/fxa-auth-server/test/local/senders/email.js

fix(payments): switch to reactivate link in footer for subscription cancellation emails

---

packages/fxa-auth-server/lib/payments/stripe.js
packages/fxa-auth-server/test/local/payments/stripe.js

fix(payments): use period end from first invoice line for next billing date

---

packages/fxa-customs-server/lib/sentry.js
packages/fxa-customs-server/lib/server.js
packages/fxa-customs-server/package-lock.json
packages/fxa-customs-server/package.json
packages/fxa-customs-server/test/local/sentry.js

fix(sentry): Fix sentry reporting in customs server

---

packages/fxa-auth-server/bin/update_firestore_from_oauth.js

Because:
* The script was run unexpectedly with an uppercase
client id, the wrong queue name is tried.
This commit:
* Allows ops to run the script to remove the entries
made in error.
Closes #5183

fix: allow fixup script to remove bad settings

---

packages/fxa-auth-server/bin/update_firestore_from_oauth.js

fix(event-broker): do not add items if REMOVE_CLIENT

---

README.md
packages/123done/README.md
packages/browserid-verifier/README.md
packages/fortress/README.md
packages/fxa-admin-panel/README.md
packages/fxa-admin-server/README.md
packages/fxa-auth-db-mysql/README.md
packages/fxa-auth-server/README.md
packages/fxa-components/README.md
packages/fxa-content-server/README.md
packages/fxa-dev-launcher/README.md
packages/fxa-event-broker/README.md
packages/fxa-geodb/README.md
packages/fxa-graphql-api/README.md
packages/fxa-js-client/CONTRIBUTING.md
packages/fxa-metrics-processor/README.md
packages/fxa-payments-server/README.md
packages/fxa-settings/README.md
packages/fxa-shared/README.md
packages/fxa-support-panel/README.md

Taking a stab at improving our various READMEs to include exactly how to run test suites, test specific files, and grep for tests.

docs(all): update readmes across all packages to improve testing documentation

---

packages/fxa-auth-server/.vscode/launch.json
packages/fxa-auth-server/config/index.js
packages/fxa-auth-server/lib/routes/support.js
packages/fxa-auth-server/test/local/routes/support.js
packages/fxa-content-server/app/scripts/lib/auth/client.ts
packages/fxa-content-server/app/scripts/lib/fxa-client.js
packages/fxa-content-server/app/scripts/models/support-form.js
packages/fxa-content-server/app/scripts/templates/support.mustache
packages/fxa-content-server/app/scripts/views/support.js
packages/fxa-content-server/app/tests/spec/models/account.js
packages/fxa-content-server/app/tests/spec/models/support-form.js
packages/fxa-content-server/app/tests/spec/views/support.js
packages/fxa-content-server/tests/functional/support.js
packages/fxa-js-client/client/FxAccountClient.js
packages/fxa-js-client/tests/lib/subscriptions.js

auth changes (support.js):
- Add new required field to request options.
- Added tests to cover missed lines.
- Refactored handleAuth function: removed unused path.
content-server changes
- add new Support form field
- update dropdowns for support form
fixes #5093

feat(auth + content-server): add new support form field and update options in dropdown

---

packages/fxa-components/AppErrorDialog/index.stories.tsx
packages/fxa-components/LinkExternal/index.stories.tsx
packages/fxa-settings/.storybook/main.js
packages/fxa-settings/.storybook/webpack.config.js
packages/fxa-settings/README.md
packages/fxa-settings/package-lock.json
packages/fxa-settings/package.json
packages/fxa-settings/src/components/AppLayout/index.stories.tsx

Closes #4820
- Adds basic setup for Storybook in fxa-settings
- Updates a couple small things for fxa-components Storybook
Unblocks #4823

feat(settings): set up base storybook

---

packages/fxa-content-server/app/scripts/views/settings/emails.js
packages/fxa-content-server/app/tests/spec/views/settings/emails.js

fix(l10n): fix primary email update message l10n

---

packages/fxa-payments-server/src/routes/Subscriptions/index.scss

fix(payments-server): remove border in update pay

---

packages/fxa-auth-server/config/index.ts
packages/fxa-auth-server/lib/senders/sms.js
packages/fxa-auth-server/test/local/senders/sms.js

feat(sms): make AWS.SNS.SMS.SMSType configurable

---

packages/fxa-auth-server/lib/error.js
packages/fxa-auth-server/lib/payments/stripe.js
packages/fxa-auth-server/lib/routes/subscriptions.js
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-auth-server/test/local/routes/subscriptions.js

https://jira.mozilla.com/browse/FXA-1819
fixes #5198

fix(payments): squelch error response to Stripe on expiring payment method without subscription

---

packages/fxa-settings/README.md
packages/fxa-settings/scripts/test-ci.sh

Forgot to hit save when fixing a conflict

fix(settings): borked readme

---

packages/fxa-auth-server/lib/payments/stripe.js
packages/fxa-auth-server/test/local/payments/stripe.js

- add previous_plan_id and plan_change_date to subscription on update
Because:
- we want to be able to provide support agents with information concerning when a plan was changed and what the previous plan was to allow for better support for customers
fixes #5243

feat (auth-server): add plan changed metadata to subscription

---

packages/fxa-content-server/app/scripts/lib/auth/client.ts

🤓 whoops, not sure how the tests missed that

fix(bug): fix typescript error

---

docs/adr/0016-use-graphql-and-apollo-for-settings-redesign.md

Closes #4810 
This is more of a follow up / documentation of a decision than it is a true proposal.
I'll need to go through and proofread and possibly add a little more detail tomorrow morning but in general, this feels pretty complete from my end, but I fully expect comments and especially would like @bbangert to go through and point out what I'm missing. 😄
I added the folks involved in the Settings Redesign project estimation meeting under "deciders" since I asked during that meeting if there was any opposition or reason why we shouldn't do this. I will take your name off if you prefer.

docs(adrs): Use GraphQL and Apollo for Settings Redesign

---

packages/fxa-content-server/server/bin/fxa-content-server.js

gets rid of deprecation message

task(content-server): fix includeSubDomains option

---

packages/fxa-content-server/app/scripts/models/support-form.js
packages/fxa-content-server/app/scripts/templates/support.mustache
packages/fxa-content-server/app/tests/spec/views/support.js

- add Firefox Account as option for product field
- update issue topics according to request
fixes #5302

feat(support-form): update dropdown options

---

packages/fxa-content-server/app/scripts/templates/support.mustache
packages/fxa-content-server/app/scripts/views/support.js
packages/fxa-content-server/app/tests/spec/views/support.js

- fix submit button still clickable when disabled
- fix buttons not restoring after error modal dismissal
fixes #5266

bug(content-server): fix support form submit button

---

packages/fxa-content-server/tests/teamcity/run.sh

fix(test): grep teamcity intern.js for pattern

---

packages/fxa-content-server/tests/teamcity/run.sh

r? - @vbudhram 
Seemed possibly useful to expose this, so I did.

fix(tests): support optional --suites

---

packages/fxa-react/.prettierignore
packages/fxa-react/.storybook/main.js
packages/fxa-react/.storybook/webpack.config.js
packages/fxa-react/components/AppErrorBoundary/index.test.tsx
packages/fxa-react/components/AppErrorBoundary/index.tsx
packages/fxa-react/components/AppErrorDialog/index.stories.tsx
packages/fxa-react/components/AppErrorDialog/index.test.tsx
packages/fxa-react/components/AppErrorDialog/index.tsx
packages/fxa-react/components/LinkExternal/index.stories.tsx
packages/fxa-react/components/LinkExternal/index.test.tsx
packages/fxa-react/components/LinkExternal/index.tsx
packages/fxa-react/components/Portal/index.scss
packages/fxa-react/components/Survey/index.scss
packages/fxa-react/components/Survey/index.stories.tsx
packages/fxa-react/components/Survey/index.test.tsx
packages/fxa-react/components/Survey/index.tsx
packages/fxa-react/jest.config.js
packages/fxa-react/lib/hooks.test.tsx
packages/fxa-react/lib/hooks.tsx
packages/fxa-react/package.json
packages/fxa-react/rescripts.js
packages/fxa-react/tsconfig.common.json
packages/fxa-react/tsconfig.json
yarn.lock

chore(fxa-react): add prettier rules, update existing files to respect them

---

packages/fxa-content-server/app/scripts/templates/support.mustache
packages/fxa-content-server/tests/functional/lib/helpers.js
packages/fxa-content-server/tests/functional/support.js

fix(support): don't exit the form when you hit enter

---

packages/fxa-payments-server/scripts/test-ci.sh

fixes #5428
It looks like fxa-content-server was the missing dep.

chore(build): updated payments-server test-ci.sh

---

packages/fxa-content-server/app/scripts/lib/sentry.js
packages/fxa-content-server/app/tests/spec/lib/sentry.js
packages/fxa-content-server/tests/functional/fx_browser_relier.js

Related to https://github.com/mozilla/fxa/issues/2298

feat(sentry): reduce Sentry 'info' logging from the content-server

---

packages/fxa-auth-server/lib/routes/subscriptions.js

fix(auth-server): fix incorrect response validation on subscription upgrade route

---

packages/fxa-content-server/app/scripts/views/connect_another_device.js
packages/fxa-content-server/app/scripts/views/mixins/connect-another-device-mixin.js

Maybe fix #5476
This was also being reported in sentry, ref https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/8555777/events/54195076c3ca4ba785dfabc5ea54c18b/

feat(experiments): Fix qr code experiment grouping undefined bug

---

packages/fxa-payments-server/scripts/test-ci.sh

Let's see if this passes on circleci ...

fix(payments): hack to get 1.172.2 to build

---

packages/fxa-content-server/app/scripts/lib/error-utils.js
packages/fxa-content-server/app/scripts/templates/500.mustache
packages/fxa-content-server/app/styles/_layout.scss
packages/fxa-content-server/app/tests/spec/lib/error-utils.js

Related to https://github.com/mozilla/fxa/issues/5415

feat(errors): add a details section for content-server 500 errors

---

docs/adr/0019-use-workspace-dependencies.md
docs/adr/index.md

docs(adrs): Added workspaces ADR

---

packages/fxa-content-server/tests/teamcity/run.sh

fix(tests): teamcity run.sh npx yarn workspaces focus fxa-content-server fxa-js-client

---

packages/fxa-content-server/app/scripts/views/form.js

fix(content-server): change tooltip render order

---

packages/fxa-customs-server/scripts/block-ip.js
packages/fxa-customs-server/scripts/test-local.sh
packages/fxa-customs-server/test/scripts/block-ip.js

fix(scripts): Fix the borked block-ip custom server script

---

packages/fxa-content-server/app/scripts/templates/post_verify/cad_qr/ready_to_scan.mustache
packages/fxa-content-server/app/scripts/templates/post_verify/cad_qr/scan_code.mustache

fix(strings): Updated CAD QR strings

---

packages/fxa-auth-server/scripts/must-reset.js
packages/fxa-auth-server/test/scripts/fixtures/accounts.json
packages/fxa-auth-server/test/scripts/must-reset.js
packages/fxa-content-server/app/scripts/views/mixins/account-reset-mixin.js
packages/fxa-content-server/app/tests/spec/views/mixins/account-reset-mixin.js

Fixes #5538 
Updates our script to put an account in the "must reset" state. This also logs users out of their current sessions.

fix(scripts): Fix the account reset script

---

packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/lib/senders/templates/layouts/fxa.html
packages/fxa-auth-server/lib/senders/templates/partials/appBadges.html
packages/fxa-auth-server/lib/senders/templates/postVerify.html
packages/fxa-auth-server/lib/senders/templates/postVerify.txt
packages/fxa-auth-server/test/local/senders/email.js

Fixes #5400 
Designs: https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit#
Rendered template:

feat(email): Update post verify email template

---

packages/fxa-admin-panel/pm2.config.js
packages/fxa-react/pm2.config.js
packages/fxa-settings/pm2.config.js

feat(css): watch and rebuild css on changes

---

packages/fxa-auth-server/config/index.ts
packages/fxa-auth-server/lib/routes/account.js
packages/fxa-auth-server/lib/server.js
packages/fxa-auth-server/test/local/routes/account.js
packages/fxa-auth-server/test/local/server.js
packages/fxa-auth-server/test/mocks.js
packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/qr-code-cad.js
packages/fxa-customs-server/lib/config/config.js
packages/fxa-customs-server/lib/dataflow.js
packages/fxa-customs-server/lib/email_record.js
packages/fxa-customs-server/lib/records.js
packages/fxa-customs-server/lib/server.js
packages/fxa-customs-server/lib/settings/limits.js
packages/fxa-customs-server/test/local/dataflow_tests.js
packages/fxa-customs-server/test/local/email_record_tests.js
packages/fxa-customs-server/test/memcache-helper.js
packages/fxa-customs-server/test/remote/too_many_bad_logins.js

@vbudhram squash maybe? since these need to go to 174 too

Uplift 172.x changes

---

packages/fxa-auth-server/config/index.ts
packages/fxa-auth-server/lib/routes/account.js
packages/fxa-auth-server/lib/server.js
packages/fxa-auth-server/test/local/routes/account.js
packages/fxa-auth-server/test/local/server.js
packages/fxa-auth-server/test/mocks.js
packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/qr-code-cad.js
packages/fxa-customs-server/lib/config/config.js
packages/fxa-customs-server/lib/dataflow.js
packages/fxa-customs-server/lib/email_record.js
packages/fxa-customs-server/lib/records.js
packages/fxa-customs-server/lib/server.js
packages/fxa-customs-server/lib/settings/limits.js
packages/fxa-customs-server/test/local/dataflow_tests.js
packages/fxa-customs-server/test/local/email_record_tests.js
packages/fxa-customs-server/test/memcache-helper.js
packages/fxa-customs-server/test/remote/too_many_bad_logins.js

fix(customs): Fix undefined errors when blocking a request from ip service
fix(customs): don't try to write records from reputationService to memcache
fix(customs): Call setRecord instead of setRecords
fix(logs): Emit statsd errnos
feat(auth): changed handling of logins
fix(customs): flag emails in customs server blocking

Uplift commits from 172.x to 174

---

packages/fxa-content-server/tests/server/amplitude.js

Match one or two digests in the patch level, and d.r.y. the regex.

fix(tests): fix test regex used in amplitude test

---

packages/fxa-auth-server/lib/payments/stripe.js
packages/fxa-auth-server/test/local/payments/stripe.js

fix(payments): use upcoming subscription invoice for one-time prorated charge

---

packages/fxa-customs-server/lib/server.js

Noticed this while working in customs, lets update these variables to be consistent with other parts of the app.

refactor(customs): Update vars to `checkAllowlist`

---

packages/fxa-auth-server/lib/routes/auth-schemes/refresh-token.js
packages/fxa-auth-server/lib/routes/devices-and-sessions.js
packages/fxa-auth-server/lib/routes/index.js
packages/fxa-auth-server/test/local/routes/auth-schemes/refresh-token.js
packages/fxa-auth-server/test/local/routes/devices-and-sessions.js

Continuation of https://github.com/mozilla/fxa/pull/5618.

fix(devices): improve lastAccessTime accuracy for OAuth devices

---

.circleci/config.yml
packages/fxa-auth-server/package.json
packages/fxa-auth-server/scripts/mocha-coverage.js
packages/fxa-auth-server/scripts/test-ci.sh
packages/fxa-content-server/scripts/test-ci.sh
packages/fxa-content-server/tests/intern.js
yarn.lock

this might help us keep track of flaky tests over time

feat(ci): use store_test_results in circleci

---

packages/fxa-content-server/server/lib/routes/post-metrics.js

fix(validation): Allow for optional deviceIds

---

packages/fxa-auth-server/config/index.ts
packages/fxa-auth-server/lib/routes/account.js
packages/fxa-auth-server/pm2.config.js
packages/fxa-auth-server/test/local/routes/account.js
packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/app/scripts/lib/verification-reasons.ts
packages/fxa-content-server/app/scripts/models/account.js
packages/fxa-content-server/app/scripts/models/auth_brokers/base.js
packages/fxa-content-server/app/scripts/models/auth_brokers/fx-sync-channel.js
packages/fxa-content-server/app/scripts/models/auth_brokers/fx-sync-web-channel.js
packages/fxa-content-server/app/scripts/templates/post_verify/password/force_password_change.mustache
packages/fxa-content-server/app/scripts/views/confirm.js
packages/fxa-content-server/app/scripts/views/mixins/signin-mixin.js
packages/fxa-content-server/app/scripts/views/mixins/verification-reason-mixin.js
packages/fxa-content-server/app/scripts/views/post_verify/password/force_password_change.js
packages/fxa-content-server/app/scripts/views/sign_in_token_code.js
packages/fxa-content-server/app/scripts/views/sign_in_totp_code.js
packages/fxa-content-server/app/tests/spec/views/mixins/signin-mixin.js
packages/fxa-content-server/app/tests/spec/views/post_verify/password/force_password_change.js
packages/fxa-content-server/app/tests/spec/views/sign_in_token_code.js
packages/fxa-content-server/app/tests/spec/views/sign_in_totp_code.js
packages/fxa-content-server/app/tests/test_start.js
packages/fxa-content-server/server/lib/routes/get-frontend.js
packages/fxa-content-server/tests/functional.js
packages/fxa-content-server/tests/functional/lib/helpers.js
packages/fxa-content-server/tests/functional/lib/selectors.js
packages/fxa-content-server/tests/functional/post_verify/force_password_change.js

Fixes #5595 
Marking as a draft since this doesn't handle the auth-server responses from https://github.com/mozilla/fxa/pull/5624.
This also needs tests etc.

feat(password): Add force password screens

---

packages/fxa-shared/lib/sentry.ts
packages/fxa-shared/package.json
packages/fxa-shared/test/lib/sentry.ts

- also fix a Sentry test that failed once it started running

fix(shared): ensure *.ts tests run

---

packages/fxa-content-server/app/scripts/views/mixins/settings-panel-mixin.js
packages/fxa-content-server/app/scripts/views/settings/change_password.jsx

fix(content-server): clean the input values before navigating

---

packages/fxa-auth-server/config/dev.json
packages/fxa-auth-server/scripts/verification-reminders.js
packages/fxa-content-server/tests/functional/lib/helpers.js

added CAD reminders to scripts/verification-reminders

---

packages/fxa-content-server/app/scripts/lib/channels/receivers/web-channel.js
packages/fxa-content-server/app/tests/spec/lib/channels/receivers/web-channel.js

Fixes #2344
Too many sentry errors for this one. They are also ignored https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/377150/
Fixes that! 
Closes: # 2344

fix(sentry): Do not report "No Such Channel" events to Sentry

---

.circleci/base-install.sh
.circleci/config.yml
.circleci/modules-to-test.js
CONTRIBUTING.md
packages/fxa-auth-server/scripts/test-ci.sh

Set this label if you want to skip ci tests on a PR. Add `fxa-` labels on top to skip specific packages.

feat(dev): handle skip ci label to skip tests

---

packages/fxa-content-server/tests/functional/sign_in.js

* This adds test automation coverage
* Adds a test to sign in an existing user

[test] Add test to sign in existing user

---

packages/fxa-content-server/app/scripts/lib/router.js
packages/fxa-content-server/app/tests/spec/lib/router.js

fix(content-server): fix broken links within legal pages

---

_scripts/upload-assets-to-cdn.sh

ref: https://jira.mozilla.com/browse/FXA-2184

fix(legal): change upload script to handle pdf

---

packages/fxa-content-server/app/styles/modules/_survey.scss

- fixes #5675
pulled fix for #5675 from https://github.com/mozilla/fxa/pull/5801/files#diff-e3870fe3ddab53f8e5ae8445c170f724R5 so we can still get that in for the train 🎉

task(content-server): fix z-index of survey

---

.github/PULL_REQUEST_TEMPLATE.md

Couple things bugging me about the PR template.
The current pull request template...
- Has the title `This commit`, but this is a pull request, so I change it every time.
- Has bullets that start with `\*` that you must change to either `*` or `-`, and we use regular `-`s elsewhere.
- Changes the title `This commit` to `This pull request`.
- Changes bullets to just be `-` across the board.

chore(github): minor updates to pull request template

---

packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/package.json
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-event-broker/CHANGELOG.md
packages/fxa-event-broker/package.json
packages/fxa-geodb/CHANGELOG.md
packages/fxa-geodb/package.json
packages/fxa-payments-server/CHANGELOG.md
packages/fxa-payments-server/package.json
packages/fxa-payments-server/src/lib/AppLocalizationProvider.tsx
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/package.json
packages/fxa-shared/CHANGELOG.md
packages/fxa-shared/package.json
packages/fxa-support-panel/CHANGELOG.md
packages/fxa-support-panel/package.json

- we are at v1.179.3 now
- merge latest prod train into main

main <- Train 179@179.3

---

packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/test/local/senders/email.js

same reason as 5f8495594d4edd8c3f959aad70bd70b2f5e1c253

fix(l10n): use accept language for currency l10n in emails

---

packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/lib/senders/email.js
packages/fxa-auth-server/package.json
packages/fxa-auth-server/test/local/senders/email.js
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-event-broker/CHANGELOG.md
packages/fxa-event-broker/package.json
packages/fxa-geodb/CHANGELOG.md
packages/fxa-geodb/package.json
packages/fxa-payments-server/CHANGELOG.md
packages/fxa-payments-server/package.json
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/package.json
packages/fxa-shared/CHANGELOG.md
packages/fxa-shared/package.json
packages/fxa-support-panel/CHANGELOG.md
packages/fxa-support-panel/package.json

- 179.4
- merge train into main

main <- Train 179@179.4

---

packages/fxa-auth-server/lib/payments/stripe.ts

Because:
* We want type-safe Stripe interactions.
This commit:
* Converts stripe.js to stripe.ts.

refactor(auth-server): convert stripe.js to TS

---

AUTHORS
packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/package.json
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-event-broker/CHANGELOG.md
packages/fxa-event-broker/package.json
packages/fxa-geodb/CHANGELOG.md
packages/fxa-geodb/package.json
packages/fxa-payments-server/CHANGELOG.md
packages/fxa-payments-server/package.json
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/package.json
packages/fxa-shared/CHANGELOG.md
packages/fxa-shared/package.json
packages/fxa-support-panel/CHANGELOG.md
packages/fxa-support-panel/package.json

Release 1.180.0

---

packages/fxa-content-server/app/scripts/lib/crypto/account-ecosystem-telemetry.js
packages/fxa-content-server/app/scripts/lib/crypto/scoped-keys.js
packages/fxa-content-server/app/scripts/lib/crypto/util.js
packages/fxa-content-server/app/tests/spec/lib/crypto/account-ecosystem-telemetry.js
packages/fxa-content-server/app/tests/spec/lib/crypto/scoped-keys.js
packages/fxa-content-server/app/tests/test_start.js

First attempt at an account model function to generate and return the eco_anon_id.
Comments welcome :+1:

feat(AET): Generate the ecosystem_anon_id on the client

---

packages/123done/static/css/main.css
packages/123done/static/index.html
packages/123done/static/js/123done.js
packages/fxa-payments-server/server/config/index.js

chore(test): add non-usd flows to 123 done

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/lib/routes/subscriptions.ts
packages/fxa-auth-server/lib/routes/utils/subscriptions.js
packages/fxa-auth-server/lib/types.ts
packages/fxa-shared/subscriptions/types.ts
packages/fxa-shared/test/subscriptions/metadata.ts

Because:
* We find edge cases and want to move our code to TypeScript.
This commit:
* Converts subscription routes from JS to TS and updates other types
where needed.
Closes #6002

refactor(auth-server): convert subscriptions to TS

---

packages/fxa-payments-server/src/components/TermsAndPrivacy/index.test.tsx
packages/fxa-payments-server/src/components/TermsAndPrivacy/index.tsx
packages/fxa-payments-server/src/lib/format.test.ts
packages/fxa-payments-server/src/lib/formats.ts
packages/fxa-payments-server/src/lib/mock-data.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateFormV2.tsx
packages/fxa-payments-server/src/store/types.tsx
packages/fxa-shared/subscriptions/types.ts

feat(payments): Add "Download Terms" link to terms and privacy component

---

release.sh

- I noticed we were missing a few CHANGELOG.md files in our packages
- We were also missing entries for a few packages to update the CHANGELOG files in the release script
- Add the files
- Update the script
I think I recall that we wanted to eventually move away from changelogs altogether, so this is an optional change. 🤷

chore(releases): add missing CHANGELOG files, mod release script to update them

---

packages/fxa-auth-server/lib/routes/account.js
packages/fxa-auth-server/test/local/routes/account.js

- In order for the data pipeline to (1) correlate AET data per user across anon_id changes and (2) reconstruct a user's historical list of anon_ids as part of a data deletion request, we need to log an event when the anon_id is updated. Ops will then relay this into the data pipeline on the backend.
- Adds a log.info call in the auth-server route that updates the eco_anon_id, just after we successfully update the value in the auth-db database.
Closes: #6074.

fix(aet): When the eco_anon_id is updated, log the old and new values

---

packages/fxa-auth-server/lib/routes/account.js
packages/fxa-auth-server/test/local/routes/account.js

I  just want CircleCI to build me a docker image, which it says it will only do if there's a PR.

[DO NOT MERGE] dockerpush.aet image builder, take two

---

packages/fxa-settings/README.md

* The documentation needs to be updated.
* Updates the 'testing' section
* Mentions the design guide available in Storybook
* Adds a link to Storybook builds pushed
Closes: # none

chore(docs): fxa-settings - Correct the 'testing' section, add design guide mention

---

packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/package.json
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-event-broker/CHANGELOG.md
packages/fxa-event-broker/package.json
packages/fxa-geodb/CHANGELOG.md
packages/fxa-geodb/package.json
packages/fxa-payments-server/CHANGELOG.md
packages/fxa-payments-server/package.json
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/package.json
packages/fxa-shared/CHANGELOG.md
packages/fxa-shared/package.json
packages/fxa-support-panel/CHANGELOG.md
packages/fxa-support-panel/package.json

Opening a PR to merge the train back into the main branch, per our [release process docs](https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/release-process) :+1:

Release 1.182.0

---

packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/lib/routes/account.js
packages/fxa-auth-server/package.json
packages/fxa-auth-server/test/local/routes/account.js
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-event-broker/CHANGELOG.md
packages/fxa-event-broker/package.json
packages/fxa-geodb/CHANGELOG.md
packages/fxa-geodb/package.json
packages/fxa-payments-server/CHANGELOG.md
packages/fxa-payments-server/package.json
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/package.json
packages/fxa-shared/CHANGELOG.md
packages/fxa-shared/package.json
packages/fxa-support-panel/CHANGELOG.md
packages/fxa-support-panel/package.json

Release 182.1

---

packages/fxa-auth-client/lib/client.ts
packages/fxa-graphql-api/src/lib/auth.ts
packages/fxa-graphql-api/src/lib/resolvers/account-resolver.ts
packages/fxa-graphql-api/src/lib/resolvers/session-resolver.ts
packages/fxa-graphql-api/src/lib/resolvers/types/session.ts
packages/fxa-graphql-api/src/lib/server.ts
packages/fxa-graphql-api/src/test/lib/auth.spec.ts
packages/fxa-graphql-api/src/test/lib/datasources/authServer.spec.ts
packages/fxa-graphql-api/src/test/lib/datasources/profileServer.spec.ts
packages/fxa-graphql-api/src/test/lib/mocks.ts
packages/fxa-graphql-api/src/test/lib/resolvers/account-resolver.spec.ts
packages/fxa-graphql-api/src/test/lib/schema.spec.ts
packages/fxa-graphql-api/src/test/lib/server.spec.ts
packages/fxa-settings/src/components/AccountDataHOC/index.tsx
packages/fxa-settings/src/components/VerifiedSessionGuard/index.test.tsx
packages/fxa-settings/src/components/VerifiedSessionGuard/index.tsx
packages/fxa-settings/src/lib/auth.ts
packages/fxa-settings/src/lib/cache.ts

adding session verified state to gql and the frontend

feat(settings): add session verified state to graphql-api

---

packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/package.json
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/package.json
packages/fxa-content-server/server/lib/routes/get-frontend.js
packages/fxa-content-server/tests/server/routes.js
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-event-broker/CHANGELOG.md
packages/fxa-event-broker/package.json
packages/fxa-geodb/CHANGELOG.md
packages/fxa-geodb/package.json
packages/fxa-payments-server/CHANGELOG.md
packages/fxa-payments-server/package.json
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/package.json
packages/fxa-shared/CHANGELOG.md
packages/fxa-shared/package.json
packages/fxa-support-panel/CHANGELOG.md
packages/fxa-support-panel/package.json

Picking up changes from https://github.com/mozilla/fxa/pull/6156.

183.1 point release

---

packages/fxa-settings/src/components/Settings/index.tsx

feat(settings): Display formatted password set time on new settings

---

packages/fxa-payments-server/src/lib/errors.test.tsx
packages/fxa-payments-server/src/lib/errors.ts

fix(payments): ensure SCA payment update uses same error as subscription create

---

AUTHORS
packages/fxa-auth-db-mysql/CHANGELOG.md
packages/fxa-auth-db-mysql/package.json
packages/fxa-auth-server/CHANGELOG.md
packages/fxa-auth-server/package.json
packages/fxa-content-server/CHANGELOG.md
packages/fxa-content-server/package.json
packages/fxa-customs-server/CHANGELOG.md
packages/fxa-customs-server/package.json
packages/fxa-email-event-proxy/package.json
packages/fxa-email-service/CHANGELOG.md
packages/fxa-email-service/Cargo.lock
packages/fxa-email-service/Cargo.toml
packages/fxa-event-broker/CHANGELOG.md
packages/fxa-event-broker/package.json
packages/fxa-geodb/CHANGELOG.md
packages/fxa-geodb/package.json
packages/fxa-payments-server/CHANGELOG.md
packages/fxa-payments-server/package.json
packages/fxa-profile-server/CHANGELOG.md
packages/fxa-profile-server/package.json
packages/fxa-shared/CHANGELOG.md
packages/fxa-shared/package.json
packages/fxa-support-panel/CHANGELOG.md
packages/fxa-support-panel/package.json

Seems like a suspiciously small amount of changes because the settings changelog isn't updated, see FXA-2422.

Release 1.184.0

---

docs/adr/0021-use-internjs-testing.md

- We should document these decisions for future us
- Documents why we choose to use InternJS in the new settings V2 app
Closes: #4849

chore(docs): Add E2E testing ADR for settings V2

---

packages/fxa-settings/src/components/AppLayout/index.test.tsx
packages/fxa-settings/src/components/AppLayout/index.tsx
packages/fxa-settings/src/components/FlowContainer/index.tsx
packages/fxa-settings/src/components/Settings/index.tsx

Make the back arrow navigate back in history.
A couple style adjustments.

refactor(settings): a few adjustments to FlowContainer

---

packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js
packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache
packages/fxa-content-server/server/lib/routes/post-metrics.js

Cherry-picked from #6229 and #6230.

Train 184 uplift

---

packages/fxa-graphql-api/src/lib/datasources/authServer.ts
packages/fxa-graphql-api/src/lib/resolvers/account-resolver.ts
packages/fxa-graphql-api/src/lib/resolvers/types/input/delete-recovery-key.ts
packages/fxa-graphql-api/src/lib/resolvers/types/input/index.ts
packages/fxa-graphql-api/src/test/lib/datasources/authServer.spec.ts
packages/fxa-graphql-api/src/test/lib/resolvers/account-resolver.spec.ts
packages/fxa-react/components/Portal/index.tsx
packages/fxa-settings/src/components/Modal/index.stories.tsx
packages/fxa-settings/src/components/Modal/index.tsx
packages/fxa-settings/src/components/ModalVerifySession/index.stories.tsx
packages/fxa-settings/src/components/ModalVerifySession/index.test.tsx
packages/fxa-settings/src/components/ModalVerifySession/index.tsx
packages/fxa-settings/src/components/Security/index.stories.tsx
packages/fxa-settings/src/components/Security/index.test.tsx
packages/fxa-settings/src/components/Security/index.tsx
packages/fxa-settings/src/components/UnitRow/index.stories.tsx
packages/fxa-settings/src/components/UnitRow/index.test.tsx
packages/fxa-settings/src/components/UnitRow/index.tsx
packages/fxa-settings/src/components/UnitRowRecoveryKey/index.stories.tsx
packages/fxa-settings/src/components/UnitRowRecoveryKey/index.test.tsx
packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx
packages/fxa-settings/src/components/VerifiedSessionGuard/index.test.tsx
packages/fxa-settings/src/components/VerifiedSessionGuard/index.tsx
packages/fxa-settings/src/models/_mocks.tsx

Settings: remove recovery key

---

packages/fxa-graphql-api/src/lib/datasources/authServer.ts
packages/fxa-graphql-api/src/lib/resolvers/session-resolver.ts
packages/fxa-graphql-api/src/lib/resolvers/types/input/destroy-session.ts
packages/fxa-graphql-api/src/lib/resolvers/types/input/index.ts
packages/fxa-graphql-api/src/test/lib/datasources/authServer.spec.ts
packages/fxa-graphql-api/src/test/lib/resolvers/session-resolver.spec.ts

fixes #6286
Add the destroySession mutation to log out of the current session

feat(gql): added destroySession mutation

---

packages/fxa-content-server/app/scripts/lib/constants.js
packages/fxa-content-server/app/tests/spec/views/marketing_snippet.js

- Fenix is live now everywhere
- Updates the link to Fenix release branch

feat(mobile): direct users to Firefox for Android release page instead of Beta

---

packages/fxa-auth-server/lib/payments/stripe.ts
packages/fxa-auth-server/test/local/payments/stripe.js
packages/fxa-payments-server/src/components/PaymentFormV2/index.test.tsx
packages/fxa-payments-server/src/components/PaymentFormV2/index.tsx
packages/fxa-payments-server/src/routes/ProductV2/SubscriptionCreate/index.tsx
packages/fxa-payments-server/src/routes/ProductV2/index.test.tsx

Because:
- point release
This commit:
- merge 408fcfe2b into the train-186

Train 186 Uplift

---

packages/fxa-content-server/app/scripts/models/account.js
packages/fxa-content-server/app/tests/spec/models/account.js

- During password reset the eco anon id tries to update but is silently failing because the endpoint to update requires the old (current) anon ID be passed along via the `If-Match` header. This ensures that you're only updating the anon ID if it's what you currently know it to be.
- Updates the account model `generateEcosystemAnonId` method to pass in the old anon ID via the `ifMatch` option on `fxaClient.updateEcosystemAnonId`
Closes: #6231

feat(aet): set ifMatch option when generating new eco anon id on account model

---

packages/fxa-admin-panel/package.json
packages/fxa-admin-panel/server/lib/server.ts
packages/fxa-content-server/package.json
packages/fxa-payments-server/package.json
yarn.lock

This introduced one breaking change with Helmet in the admin-panel. Fix here: https://github.com/mozilla/fxa/pull/6407/commits/c8d20c5acadef37f9814903fe16d524c3c800dc9

Merge Dependabot #6405 #6406 #6404 #6403

---

packages/fxa-content-server/tests/functional/lib/helpers.js
packages/fxa-content-server/tests/functional/subscriptions.js

Because:
- let's test to verify expired CC behavior
This commit:
- add a functional test to verify that an expired CC triggers an error
message to be shown
Closes: #1871 (FXA-225)

chore(tests): add expired CC subscription functional test

---

yarn.lock

because fxa-graphql-api tests are failing https://app.circleci.com/pipelines/github/mozilla/fxa/13694/workflows/f803ef35-7402-467f-bfe2-eab7e69d0673/jobs/194534

fix(dep): fixed graphql dep conflict

---

packages/fxa-settings/src/components/Modal/index.test.tsx
packages/fxa-settings/src/components/Modal/index.tsx
packages/fxa-settings/src/components/ModalVerifySession/index.test.tsx
packages/fxa-settings/src/components/UnitRow/index.test.tsx
packages/fxa-settings/src/components/UnitRow/index.tsx
packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.test.tsx
packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
packages/fxa-settings/src/components/VerifiedSessionGuard/index.test.tsx

- fixes #4914
You will notice some changes to the `yarn.lock` file. I confirmed with @dannycoates that this is a normal update after running `yarn install` fresh from `main`

task(fxa-settings): add change codes modal to 2fa
