packages/fxa-auth-server/scripts/test-ci.sh
- tests are still failing to connect on circleci
=> chore(ci): wait for mysql to respond on auth-server tests

_dev/docker/mono/Dockerfile
=> chore(docker): added /app/version.json to fxa-mono

packages/fxa-settings/src/components/ConnectedServices/index.stories.tsx, packages/fxa-settings/src/components/ConnectedServices/index.test.tsx, packages/fxa-settings/src/components/ConnectedServices/index.tsx, packages/fxa-settings/src/components/PageSettings/index.test.tsx, packages/fxa-settings/src/components/PageSettings/index.tsx, yarn.lock
- puts in the basic structure and placeholders for the Connected Services section in settings
Closes: #5094
=> task(fxa-settings): Connected Services skeleton

packages/fxa-event-broker/src/pubsub-proxy/pubsub-proxy.controller.spec.ts, packages/fxa-event-broker/src/pubsub-proxy/pubsub-proxy.controller.ts
Because:
* It was not clear what the proxy logic did and difficult to fully
test.
This commit:
* Splits up the proxy logic into logical components and add's a test
for additional coverage.
=> refactor(event-broker): cleanup proxy logic

packages/fxa-content-server/tests/functional/sign_in_blocked.js
- I wasn't able to reproduce the bug in https://github.com/mozilla/fxa/issues/2434, the network requests looked similar but the request succeed and I was able to login
- It is possible that this was fixed by https://github.com/mozilla/fxa/pull/6179
- Adds a functional test to verify it is working
Closes: #2434 
=> chore(tests): Add a functional test for the unblock code and primary email flow

packages/fxa-shared/.vscode/launch.json, packages/fxa-shared/db/models/auth/account-customers.ts, packages/fxa-shared/db/models/auth/index.ts, packages/fxa-shared/test/db/models/auth/account-customers.sql, packages/fxa-shared/test/db/models/auth/helpers.ts, packages/fxa-shared/test/db/models/auth/index.spec.ts
* We want to be able to maintain the relationships between customers and users
* Establishes CRUD methods to maintain this relationship
closes #6159
=> feat(shared): add CRUD methods for maintaining fxa user and customer relationship

packages/fxa-auth-server/package.json
=> fix(scripts): Copy scripts into dist directory

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/newsletter-sync.js
- The experiment has collected enough data to be disabled
- Disables the experiment 
Closes: NA
=> chore(experiments): disable newsletter experiments until next steps

packages/fxa-settings/src/components/UnitRow/index.test.tsx, packages/fxa-settings/src/components/UnitRow/index.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx
- fixes a broken link in secondary email section
Closes: #6372
=> fix(fxa-settings): fix recovery key link

packages/fxa-settings/README.md
Fixes #6531.
Just some doc fixes. If there are other README changes you'd like to see, but haven't gotten around to making, feel free to add suggestions here.
=> Document the local URL for new-settings

packages/fxa-settings/src/components/ConnectedServices/MOCK_SERVICES.js, packages/fxa-settings/src/models/Account.ts
=> fix(fxa-settings): address ts error in Account model

packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/FlowContainer/index.tsx, packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.stories.tsx, packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.test.tsx, packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx
=> feat(settings): added Recovery key add page

packages/fxa-settings/src/components/ConnectedServices/Icon.tsx, packages/fxa-settings/src/components/ConnectedServices/Service.tsx
- dynamically loads svg icons
- refactors the icon choosing code into a switch statement
- adds the Icon component for dynamically loading svgs
Closes: #3566
=> task(fxa-setttings): refactor Service component

packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/settings_v2/navigation.js, packages/fxa-content-server/tests/functional_settings_v2.js, packages/fxa-settings/src/components/DropDownAvatarMenu/index.test.tsx, packages/fxa-settings/src/components/DropDownAvatarMenu/index.tsx, packages/fxa-settings/src/components/PageDisplayName/index.tsx
- `added basic navigation tests for settings v2`
- `This is for task FXA-2596`
@chenba @dannycoates @LZoog please review. Thanks!
=> Settings v2 basic navigation test

packages/fxa-settings/src/components/Checkbox/index.tsx, packages/fxa-settings/src/components/DataBlock/index.tsx, packages/fxa-settings/src/components/Tooltip/index.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.test.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.test.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.test.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
=> chore(settings): set / add unique testids

packages/fxa-auth-server/scripts/delete-account.js
=> fix(script): added setupAuthDatabase to delete-account script

.github/PULL_REQUEST_TEMPLATE.md
- updates pr template to add rtl checkbox
=> task(monorepo): add rtl checkbox to pr template

packages/fxa-settings/src/components/GetDataTrio/index.tsx, packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx, packages/fxa-settings/src/lib/metrics.ts
=> feat(settings): added view metrics to account-recovery

packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.tsx, packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.tsx
=> feat(settings): added metric events for secondary email to new settings

packages/fxa-settings/scripts/test-ci.sh, packages/fxa-settings/src/components/BentoMenu/index.test.tsx, packages/fxa-settings/src/components/BentoMenu/index.tsx, packages/fxa-settings/src/components/Checkbox/index.tsx, packages/fxa-settings/src/components/ConnectedServices/index.tsx
=> chore(settings): fix new settings build warnings

packages/fxa-settings/src/components/ConnectedServices/index.tsx
=> fix(settings): fixes react duplicate key warning in Connected Services component

packages/fxa-react/configs/tailwind.js, packages/fxa-settings/src/components/Nav/index.tsx
=> fix(settings): set text alignment on nav

packages/fxa-settings/src/components/PageTwoStepAuthentication/index.test.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx, packages/fxa-settings/src/lib/metrics.ts
Because:
- we try to achieve parity with content server on metrics
This commit:
- emit metric events for two step auth
- add a couple new helper functions to metrics lib
Closes: #5177
=> feat(settings): add metrics for two step auth

packages/fxa-react/components/LogoLockup/index.tsx
=> fix(settings): work around weird webkit render bug

packages/fxa-content-server/tests/functional/email_domain_mx_validation.js
- `xyz.gd` started resolving an "A" record
- changes the test domain
=> fix(content): fixed broken functional test from dns change

packages/fxa-settings/src/components/ModalVerifySession/index.test.tsx, packages/fxa-settings/src/components/ModalVerifySession/index.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.test.tsx, packages/fxa-settings/src/components/VerifiedSessionGuard/index.test.tsx
fixes #6796 
Any input that doesn't pass validation will cause the button to be disabled.
=> fix(settings): add form validation to ModalVerifiedSession

packages/fxa-settings/src/styles/unit-row.scss
=> fix(settings): add scroll margin to UnitRow

packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.tsx, packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx
=> fix(settings): add some padding to solo buttons. 

packages/fxa-settings/src/components/PageChangePassword/index.tsx
=> feat(settings): add password confirmation match to criteria list

packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/settings_v2/external_links.js, packages/fxa-content-server/tests/functional_settings_v2.js
- Functional tests for external links on new settings page
Closes: #4856
These changes are dependent on #6860
=> task(fxa-settings): E2E external links tests

packages/fxa-content-server/tests/functional/lib/selectors.js
- for external links terms test
=> fix(fxa-settings): fix functional test selector

packages/fxa-content-server/pm2.config.js, packages/fxa-content-server/server/bin/fxa-content-server.js, packages/fxa-content-server/server/lib/csp/blocking.js
=> feat(settings): use CSP rules on /beta/settings page

packages/fxa-content-server/tests/functional/settings_v2/external_links.js
temporarily removes newsletters link test from external links tests to fix main
reopened https://jira.mozilla.com/browse/FXA-1570
=> task(fxa-settings): temporarily remove newsletters test

packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-server/lib/routes/session.js, packages/fxa-auth-server/lib/routes/validators.js
…m both the frontend and backend
-
-
Closes: #6058 
-  [x] My commit is GPG signed.
@chenba
=> chore(fxa-client): removingparam style from /sessions/verify_code from both the frontend and backend 

README.md
We want to make onboarding as well documented and accurate as possible.
Adds a step that appears when installing the Rust dependency.
=> Updated the README (test for capstone)

packages/fxa-settings/src/components/PageTwoStepAuthentication/index.test.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx
- updates some error message copy around 2fa.
Closes: #6463
=> task(fxa-settings): error msg copy updates 2fa

packages/fxa-settings/src/components/PageDisplayName/index.tsx
=> fix(settings): limit display name input to 256 characters

packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/settings_v2/connected_services_oauth_clients.js, packages/fxa-content-server/tests/functional/settings_v2/external_links.js, packages/fxa-content-server/tests/functional_settings_v2.js, packages/fxa-settings/scripts/test-ci.sh
Because:
- we want to know that the disconnect RP feature works
This commit:
- add functional tests
Closes: #4860 
=> test(settings): add disconnect RP tests

packages/fxa-content-server/server/lib/flow-event.js
- refs #6925
Updating regex so that we are consistent across instances of entrypoint and documentation. Discussion here: https://mozilla.slack.com/archives/CLV3KMZ8B/p1606858874009700
=> task(fxa-content-server): edit entrypoint regexp for consistency

packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/lib/routes/oauth/token.js
=> refactor(oauth): moved /token implementation

packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/lib/routes/oauth/introspect.js
=> refactor(oauth): moved /introspect implementation

packages/fxa-auth-server/lib/routes/oauth/authorized-clients/destroy.js, packages/fxa-auth-server/lib/routes/oauth/authorized-clients/list.js, packages/fxa-auth-server/lib/routes/oauth/index.js, packages/fxa-auth-server/lib/routes/oauth/jwks.js
closes #7048
closes #7047 
closes #7046
=> refactor(oauth): moved /jwks and /authorized-clients implementations

packages/fxa-auth-server/lib/senders/templates/layouts/fxa.html, packages/fxa-auth-server/lib/senders/templates/layouts/fxa.txt, packages/fxa-auth-server/lib/senders/templates/layouts/subscription.html, packages/fxa-auth-server/lib/senders/templates/layouts/subscription.txt
Fixes #7131.
- We need to update the MoCo address by the end of the year
- Updates all occurrences of the old Mountain View address in the FxA codebase
Closes: #7131
=> bug(legal): Update Mozilla Corporation address

packages/fxa-support-panel/README.md, packages/fxa-support-panel/src/app/app.controller.spec.ts, packages/fxa-support-panel/src/app/app.controller.ts, packages/fxa-support-panel/src/auth/auth-header.guard.spec.ts
Because:
* Some helpful feedback on the conversion PR didn't get addressed.
This commit:
* Addresses PR feedback on better test types and some code quality.
=> refactor(support-panel): address PR feedback

packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/cache.js, packages/fxa-auth-server/lib/cad-reminders.js, packages/fxa-auth-server/lib/oauth/assertion.js, packages/fxa-auth-server/lib/oauth/db/mysql/index.js, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/lib/senders/sms.js, packages/fxa-auth-server/lib/verification-reminders.js, packages/fxa-auth-server/scripts/write-emails-to-disk.js, packages/fxa-auth-server/test/local/cache.js, packages/fxa-auth-server/test/local/cad-reminders.js, packages/fxa-auth-server/test/local/senders/email.js, packages/fxa-auth-server/test/local/senders/index.js, packages/fxa-auth-server/test/local/senders/sms.js, packages/fxa-auth-server/test/local/verification-reminders.js, packages/fxa-auth-server/test/remote/recovery_key_tests.js, packages/fxa-auth-server/test/scripts/bulk-mailer.js, packages/fxa-auth-server/test/scripts/dump-users.js, packages/fxa-auth-server/test/scripts/email-config.js, packages/fxa-auth-server/test/scripts/must-reset.js, packages/fxa-shared/lib/promise-extras.ts
there's still some bluebird in test and script code but that's a lower priority and needs more work.
- we should only need native promises and they ought to be more performant
=> refactor(auth): use native promises in all production / non-test code

packages/fxa-graphql-api/src/main.ts
- Security requested these headers on responses from graph-ql server
- Adds security headers from #6873
Closes: #6873
=> feat(security): Add several security headers to graph-ql server

packages/fxa-settings/src/components/Nav/index.test.tsx, packages/fxa-settings/src/components/Nav/index.tsx
=> chore(settings): s/Newsletters/Email Communications/

packages/fxa-graphql-api/src/gql/gql.module.ts
Because:
- we should return the proper HTTP status on unsupported content types
This commit:
- return a HTTP 415 when the request's content-type is not
'application/json' or 'multipart/form-data'
Closes: #6871
=> fix(gql-api): return HTTP 415 on unsupported req content type

packages/fxa-settings/public/locales/en-US/settings.ftl, packages/fxa-settings/src/components/PageDeleteAccount/en-US.ftl, packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
- Delete account page should be localized
- Adds localization..
Closes: #5066
=> feat(l10n): setup localization for delete account page

packages/fxa-settings/public/locales/en-US/settings.ftl, packages/fxa-settings/src/components/PageTwoStepAuthentication/en-US.ftl, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx
Because:
- we should set up l10n on new settings
This commit:
- update two step auth to use localized strings
Closes: #5067
=> chore(settings): add l10n to two step auth

packages/fxa-settings/public/locales/en-US/settings.ftl, packages/fxa-settings/src/components/GetDataTrio/en-US.ftl, packages/fxa-settings/src/components/GetDataTrio/index.tsx, packages/fxa-settings/src/components/PageRecoveryKeyAdd/en-US.ftl, packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx
- we want to localize the Recovery Key page
- localizes the Recovery Key page
- adds en-US strings
Closes: #5062 
=> Localize the Recovery Key page

packages/fxa-settings/public/locales/en-US/settings.ftl, packages/fxa-settings/src/components/ConnectAnotherDevicePromo/en-US.ftl, packages/fxa-settings/src/components/ConnectAnotherDevicePromo/index.tsx, packages/fxa-settings/src/components/ConnectedServices/Service.tsx, packages/fxa-settings/src/components/ConnectedServices/en-US.ftl, packages/fxa-settings/src/components/ConnectedServices/index.tsx, packages/fxa-settings/src/components/PageChangePassword/en-US.ftl, packages/fxa-settings/src/components/PageSettings/en-US.ftl, packages/fxa-settings/src/components/PageSettings/index.tsx, packages/fxa-settings/src/components/Profile/en-US.ftl, packages/fxa-settings/src/components/Profile/index.tsx, packages/fxa-settings/src/components/Security/en-US.ftl, packages/fxa-settings/src/components/Security/index.tsx, packages/fxa-settings/src/components/UnitRow/en-US.ftl, packages/fxa-settings/src/components/UnitRow/index.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/en-US.ftl, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/en-US.ftl, packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/en-US.ftl, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx, packages/fxa-settings/src/components/UnitRowWithAvatar/en-US.ftl, packages/fxa-settings/src/components/UnitRowWithAvatar/index.tsx, packages/fxa-settings/src/lib/hooks.tsx
Because:
- we should localize new settings
This commit:
- localize the Settings component and the components therein
- update the alert bar to make use of the auth-error-{errno} strings by
default when available
Closes: #5061
=> chore(settings): localize main settings page

packages/fxa-auth-server/docs/api.md, packages/fxa-auth-server/lib/routes/subscriptions/index.ts, packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/lib/routes/subscriptions/utils.ts, packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- Route must be added to get paypal checkout token
- Adds the route
=> feat(auth-server): add route for getCheckout Token

packages/fxa-auth-server/.vscode/launch.json
- Mocha launch commands were not recursing to pick up all tests
- Adds the `--recursive` flag
=> chore(auth-server): Make mocha launch commands recursive

packages/fxa-settings/src/components/BentoMenu/index.tsx, packages/fxa-settings/src/components/HeaderLockup/index.tsx
=> fix(settings): added hover style to help icon and fixed 1px alignment issue

packages/fxa-settings/src/components/DropDownAvatarMenu/index.tsx
=> fix(settings): fix size of avatar in dropdown

packages/fxa-settings/src/components/AppLayout/index.tsx, packages/fxa-settings/src/components/BentoMenu/index.tsx, packages/fxa-settings/src/components/HeaderLockup/index.tsx, packages/fxa-settings/src/components/InputText/index.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx, packages/fxa-settings/src/components/UnitRow/index.tsx
fixes #7481
fixes #7477
fixes #7014 
fixes #7009
fixes #6917
fixes #7027 
fixes #6899
=> fix(settings): mobile style fixes

packages/fxa-settings/public/locales/en-US/settings.ftl, packages/fxa-settings/src/components/App/en-US.ftl, packages/fxa-settings/src/components/ConnectedServices/en-US.ftl, packages/fxa-settings/src/components/PageDeleteAccount/en-US.ftl, packages/fxa-settings/src/components/PageSecondaryEmailVerify/en-US.ftl
Another small round of review changes from https://github.com/mozilla/fxa-content-server-l10n/pull/466#pullrequestreview-593684316.
Refs #7319
=> fix(settings): Another round of settings l10n fixes

packages/fxa-settings/package.json, packages/fxa-settings/src/components/PageAvatar/index.tsx, packages/fxa-settings/src/lib/utilities.ts, yarn.lock
- the figma designs exclude the "Take photo" option on mobile
closes #5045
=> task(settings): do not show "take a photo" option on mobile

packages/fxa-content-server/tests/functional/settings_v2/recovery_key.js, packages/fxa-content-server/tests/functional/settings_v2/two_step_auth.js, packages/fxa-settings/src/components/App/en-US.ftl, packages/fxa-settings/src/components/ConnectedServices/en-US.ftl, packages/fxa-settings/src/components/ConnectedServices/index.test.tsx, packages/fxa-settings/src/components/ConnectedServices/index.tsx, packages/fxa-settings/src/components/PageAvatar/buttons.tsx, packages/fxa-settings/src/components/PageAvatar/en-US.ftl, packages/fxa-settings/src/components/PageAvatar/index.tsx, packages/fxa-settings/src/components/PageChangePassword/en-US.ftl, packages/fxa-settings/src/components/PageChangePassword/index.tsx, packages/fxa-settings/src/components/PageDeleteAccount/en-US.ftl, packages/fxa-settings/src/components/PageDeleteAccount/index.tsx, packages/fxa-settings/src/components/PageDisplayName/en-US.ftl, packages/fxa-settings/src/components/PageDisplayName/index.tsx, packages/fxa-settings/src/components/PageSettings/en-US.ftl, packages/fxa-settings/src/components/PageSettings/index.tsx, packages/fxa-settings/src/components/PageTwoStepAuthentication/en-US.ftl, packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx, packages/fxa-settings/src/components/Security/index.test.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/en-US.ftl, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.test.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx, packages/fxa-settings/src/components/UnitRowSecondaryEmail/en-US.ftl, packages/fxa-settings/src/components/UnitRowTwoStepAuth/en-US.ftl, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.test.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
- The designs use sentence case not title case for most strings
=> fix(settings): fixed casing for new settings strings

packages/fxa-settings/src/components/PageAvatar/index.test.tsx, packages/fxa-settings/src/components/PageAvatar/index.tsx
=> task(settings): add metrics to new avatar page

packages/fxa-settings/src/components/ConnectedServices/en-US.ftl, packages/fxa-settings/src/components/ConnectedServices/index.tsx, packages/fxa-settings/src/components/PageAvatar/buttons.tsx, packages/fxa-settings/src/components/PageAvatar/en-US.ftl, packages/fxa-settings/src/components/PageAvatar/index.tsx, packages/fxa-settings/src/components/PageDeleteAccount/en-US.ftl, packages/fxa-settings/src/components/PageDeleteAccount/index.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/en-US.ftl, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/en-US.ftl, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
This PR fixes a few issues noticed by our localizers.
Fixes mozilla/fxa-content-server-l10n#470, fixes mozilla/fxa-content-server-l10n#473.
=> L10n fixes

packages/fxa-settings/src/components/UnitRow/index.tsx, packages/fxa-settings/src/components/UnitRowWithAvatar/index.tsx
avatar row margin was opposite of others. added rtl to others
=> fix(setting): small margin misalignment

packages/fxa-graphql-api/src/gql/account.resolver.ts
- We don't want this mutation publicly accessible yet
=> chore(settings): "disable" updateAvatar mutation for now

packages/fxa-settings/src/components/PageDeleteAccount/en-US.ftl, packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
Based on review feedback from https://github.com/mozilla/fxa-content-server-l10n/pull/475
=> fix(l10n): Update a stray l10n ID

packages/fxa-content-server/server/bin/fxa-content-server.js
=> fix(settings): #7632 broke dev

packages/fxa-settings/src/components/PageAvatar/index.tsx, packages/fxa-settings/src/styles/slider.scss
=> fix(settings): fixed slider style when csp blocks inline styles

packages/fxa-settings/src/components/PageAvatar/buttons.tsx, packages/fxa-settings/src/components/PageAvatar/en-US.ftl, packages/fxa-settings/src/components/PageAvatar/index.tsx
=> fix(settings): added "Saving" button state to avatar upload

packages/fxa-auth-db-mysql/lib/db/mysql.js
When running the fxa-auth-db-mysql service against a MySQL cluster with read-only secondaries, some functionality is broken.
The error thrown by the MySQL secondary is:
```
ERROR 1290 (HY000): The MySQL server is running with the --read-only option so it cannot execute this statement
```
...which apparently doesn't make it up into Sentry, but we can see the MySQL error:
```
ER_OPTION_PREVENTS_STATEMENT
```
One of the broken functionality is `verifyTokensWithMethod` and the corresponding MySQL procedure `verifyTokensWithMethod_3`, which internally wants to execute an `UPDATE`.
Makes use of the internal `write` function instead of `read` where needed.
Closes: #7753
* [MySQL server error reference](https://dev.mysql.com/doc/mysql-errors/5.7/en/server-error-reference.html#error_er_option_preve …
=> Fix use of MySQL cluster read-only nodes

packages/fxa-payments-server/src/components/PaymentLegalBlurb/index.tsx
- I made a copy/paste error in "fixing" #7744 .
- Fixes the error.
Closes: # No issue; just a quick follow-up.
Before
After
My apologies @chenba . I had caught the error before opening PR #7781 and fixed it locally, but I didn't commit the fix and push it upstream... >.> The diff was waiting for me in my terminal just now.
=> chore(payments): Fix copy/paste error in main.ftl.

packages/fxa-content-server/app/scripts/templates/support.mustache
An ask from https://github.com/mozilla/fxa-content-server-l10n/pull/478#discussion_r588821030
Closes: #7743
=> chore(support form): update placeholder text to sentence case

packages/fxa-settings/src/components/PageDeleteAccount/index.tsx, packages/fxa-settings/src/components/PageSettings/index.tsx
=> fix(settings): scroll position

packages/fxa-content-server/tests/functional/lib/helpers.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/recovery_key.js, packages/fxa-content-server/tests/functional/sign_in_totp.js
i removed the new tab / window tests because with a code they aren't relevant anymore.
=> update verification code functional tests for new settings

packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/server/config/index.js, packages/fxa-payments-server/src/components/PaymentErrorView/index.test.tsx, packages/fxa-payments-server/src/components/PaymentErrorView/index.tsx, packages/fxa-payments-server/src/components/SubscriptionTitle/index.test.tsx, packages/fxa-payments-server/src/components/SubscriptionTitle/index.tsx, packages/fxa-payments-server/src/lib/errors.ts, packages/fxa-payments-server/src/lib/test-utils.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgradeRoadblock/index.stories.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgradeRoadblock/index.test.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgradeRoadblock/index.tsx, packages/fxa-payments-server/src/routes/Product/index.test.tsx, packages/fxa-payments-server/src/routes/Product/index.tsx
Because:
- the subscription upgrade feature is not working correctly
This commit:
- add a feature flag based screen to replace the subscription upgrade
one
Closes: #7794
=> feat(subscriptions): add upgrade roadblock

packages/fxa-auth-server/scripts/gen_keys.js
When the absolute path to the fxa repo contained spaces the gen_keys script would fail.
=> fix(auth): make gen_keys script path indepedent

packages/fxa-content-server/docs/pairing-architecture.md
* The only current description of the security considerations that
went into designing the pairing flow, are tucked away in a section
of the "Phase 1 Project Plan" google doc.
* Google docs are not very discoverable and can have permission
management issues.
* Copies the relevant security discussion into the long-lived doc
in the github repo.
* Does a bit of light editing for clairty.
No issue.
- Oh no, I had cleverly put my GPG root key in offline storage with a randomly generated password and then printed the password and put it in a safe place and then made a sub-key for signing things with, but now my sub-key has expired and the printed-out password doesn't work for some reason and I can't GPG sign things anymore and I have been putting off doing …
=> Add a section on security properties to the pairing architecture doc.

packages/fxa-content-server/server/lib/beta-settings.js
```
Error: ENOENT: no such file or directory, open '/fxa/packages/fxa-content-server/dist/beta/settings/index.html'
at Object.openSync (fs.js:476:3)
at readFileSync (fs.js:377:35)
at Object.<anonymous> (/fxa/packages/fxa-content-server/server/lib/beta-settings.js:23:23)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/fxa/packages/fxa-content-server/server/bin/fxa-content-server.js:37:5)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at …
```
=> fix(path): Update location of settings page on disk

packages/fxa-settings/src/components/Security/index.test.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/en-US.ftl, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.test.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/en-US.ftl, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.test.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
- There are some l10n issues in the recovery key row
- Fixes them
Closes: #8007
=> fix(l10n): Fix recovery key l10n issues

packages/fxa-content-server/tests/functional.js, packages/fxa-content-server/tests/functional/force_auth.js
Easy little fix. Closes #7984.
=> Fix force_auth test by updating sign out flow

packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.tsx
Closes: #8010 
https://user-images.githubusercontent.com/44236566/112882858-21941800-90eb-11eb-8f06-30176b3383f7.mp4
=> fix(settings): resolve two auth new recovery code styling issue

packages/fxa-content-server/tests/functional.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/oauth_settings_clients.js, packages/fxa-settings/src/components/ConnectedServices/Service.tsx
* Added data-name to each individual connected service listing to simplify selecting the right row
Fixes #7989
=> fix(tests): get oauth_settings_clients test passing

packages/fxa-payments-server/src/routes/Subscriptions/ActionButton.tsx
=> fix(fxa-payment-server): remove debugging code from ActionButton

packages/fxa-payments-server/src/components/PaymentErrorView/index.scss, packages/fxa-payments-server/src/styles/_mixins.scss
- Fixes a layout issue with the Checkout error view on mobile
Closes: #7934
=> fixes(fxa-payments-server): Checkout error view layout issue

packages/fxa-settings/src/components/ConnectedServices/index.tsx, packages/fxa-settings/src/components/Modal/en-US.ftl, packages/fxa-settings/src/components/Modal/index.test.tsx, packages/fxa-settings/src/components/Modal/index.tsx, packages/fxa-settings/src/components/ModalVerifySession/en-US.ftl, packages/fxa-settings/src/components/ModalVerifySession/index.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx
- The ModalVerifySession component was not localized
- Localizes that component
- I also had to add some localization to the base `Modal` component to handle the tooltip
Closes: #7940
=> fix(l10n): Localize ModalVerifySession component

packages/fxa-content-server/tests/functional.js, packages/fxa-content-server/tests/functional/force_auth.js, packages/fxa-content-server/tests/functional/lib/helpers.js, packages/fxa-content-server/tests/functional/oauth_reset_password.js, packages/fxa-content-server/tests/functional/oauth_sign_in.js, packages/fxa-content-server/tests/functional/settings_change_email.js, packages/fxa-content-server/tests/functional/settings_v2/navigation.js, packages/fxa-content-server/tests/functional/sign_in.js, packages/fxa-content-server/tests/functional/sign_in_blocked.js, packages/fxa-content-server/tests/functional/sign_in_totp.js
* Extract duplicated secondary email setup code into a helper
* Extract duplicated sign out code into a helper
Fixes #7982.
=> fix(tests): get sign_in_blocked tests passing

packages/fxa-content-server/tests/functional.js, packages/fxa-content-server/tests/functional/lib/selectors.js
=> fix(tests): update selectors to get email_opt_in passing

_dev/docker/circleci/Dockerfile
=> fix(chore): use the latest version of Firefox in CI testing

packages/fxa-auth-server/scripts/must-reset.js, packages/fxa-graphql-api/src/scripts/must-change-password.ts
=> feat(graphql-api): enhance must-change-password script to accept a plain text

CONTRIBUTING.md
- The CONTRIBUTING.md file doesn't include instructions on how to sync the fork with the original repository.
- Aims to include the information and steps needed to sync the local fork with the original repository 
which can be very helpful for first-time contributers
-
=> chore(docs): Update 'CONTRIBUTING.md' to include info about syncing the fork

package-scripts.js
- We are updating all the npm references and replacing them with yarn
- Updates the package-scripts.js file to replace npm references with yarn
Closes: #8146 
=> chore(scripts): Update package-scripts.js

packages/fxa-auth-server/scripts/paypal-processor.ts
Because:
* Auth db code changed how to initialize the DB object.
This commit:
* Updates the processor to initialize properly.
=> fix(auth-server): fix processor startup

packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx
=> fix(fxa-settings): remove horizontal margin for resend verification code

README.md
=> docs(fxa): replace npm references with yarn in readme.md

packages/fxa-auth-server/config/index.ts
=> fix(email): Correct broken account recovery links in emails

packages/fxa-content-server/tests/intern.js
This will probably help fix flaky tests.
=> chore(deps): Update selenium version to 0.29.1

packages/fxa-content-server/tests/intern.js, packages/fxa-settings/src/models/hooks.ts
Fixes regression found in stage, ref https://github.com/mozilla/fxa/pull/8305
=> Uplift email sending fix

README.md
- Some details on how that Storybook thing works in CircleCI would be nice
- Updates README.md with some further details on Storybook in CircleCI
=> chore(docs): add details on Storybook in CircleCI to README.md

packages/fxa-content-server/tests/functional/delete_account.js, packages/fxa-content-server/tests/functional/fx_fennec_v1_settings.js, packages/fxa-content-server/tests/functional/lib/helpers.js, packages/fxa-content-server/tests/functional/reset_password.js, packages/fxa-content-server/tests/functional/settings_change_email.js, packages/fxa-content-server/tests/functional/sign_in_totp.js, packages/fxa-content-server/tests/functional/sync_v3_settings.js, packages/fxa-settings/src/lib/storage.ts, packages/fxa-settings/src/models/Account.ts
=> fix(settings): clear local storage on account delete

packages/fxa-payments-server/src/components/PaymentErrorView/index.scss, packages/fxa-payments-server/src/styles/_mixins.scss
-
- fixes #7934 
- refs #5369 
=> fix(fxa-payments): checkout mobile layout fixes

packages/fxa-auth-server/lib/payments/paypal-processor.ts, packages/fxa-auth-server/test/local/payments/paypal-processor.js
Because:
- the PayPal processor is sending one payment failed email per charge
attempt whenever the invoice charge fails
This commit:
- check the invoice metadata for sent email types to ensure we do not
send duplicate payment failed emails
Closes: #8329
=> fix(emails): send one payment failed email per invoice

packages/fxa-auth-server/lib/payments/paypal-processor.ts, packages/fxa-auth-server/test/local/payments/paypal-processor.js, packages/fxa-content-server/tests/functional/delete_account.js, packages/fxa-content-server/tests/functional/fx_fennec_v1_settings.js, packages/fxa-content-server/tests/functional/lib/helpers.js, packages/fxa-content-server/tests/functional/reset_password.js, packages/fxa-content-server/tests/functional/settings_change_email.js, packages/fxa-content-server/tests/functional/sign_in_totp.js, packages/fxa-content-server/tests/functional/sync_v3_settings.js, packages/fxa-payments-server/src/components/AppLayout/index.test.tsx, packages/fxa-payments-server/src/components/PaymentErrorView/index.scss, packages/fxa-payments-server/src/components/PaymentErrorView/index.stories.tsx, packages/fxa-payments-server/src/components/PaymentErrorView/index.test.tsx, packages/fxa-payments-server/src/components/PaymentErrorView/index.tsx, packages/fxa-payments-server/src/components/TermsAndPrivacy/index.test.tsx, packages/fxa-payments-server/src/components/TermsAndPrivacy/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgradeRoadblock/index.tsx, packages/fxa-payments-server/src/styles/_mixins.scss, packages/fxa-settings/src/lib/storage.ts, packages/fxa-settings/src/models/Account.ts
- We would like QA to test some fixes on Stage ASAP for SubPlat given the launch is next week.
- Cherry-pick's a few fixes from some recent PRs that have merged into `main` to that end (and an extra one per Vijay's request).
Closes: # None
=> Train 204.3

packages/fxa-content-server/scripts/test-ci-remote.sh, packages/fxa-content-server/tests/functional/fx_desktop_handshake.js, packages/fxa-content-server/tests/functional/lib/helpers.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/oauth_handshake.js, packages/fxa-content-server/tests/functional/oauth_reset_password.js, packages/fxa-content-server/tests/functional/oauth_sign_in.js, packages/fxa-content-server/tests/functional/oauth_sign_in_token_code.js, packages/fxa-content-server/tests/functional/pairing.js, packages/fxa-content-server/tests/functional/recovery_key.js, packages/fxa-content-server/tests/functional/settings_change_email.js, packages/fxa-content-server/tests/functional/settings_v2/recovery_key.js, packages/fxa-content-server/tests/functional/settings_v2/two_step_auth.js, packages/fxa-content-server/tests/functional/subscriptions.js, packages/fxa-content-server/tests/functional/support.js, packages/fxa-content-server/tests/functional/sync_v3_email_first.js, packages/fxa-content-server/tests/functional_regression.js, packages/fxa-content-server/tests/functional_smoke.js, packages/fxa-content-server/tests/intern.js
- Our smoke tests currently failing when ran against stage
- Fixes all the test failures from stage
- Added some additional checks for various tests to account for timing issues and delays
Fixes #5376
=> fix(tests): Fix functional smoke testing

packages/fxa-admin-panel/package.json, packages/fxa-payments-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, yarn.lock
This reverts commit 72ac7648b28e16ebc79189f34d762426d7f547d1, reversing
changes made to ccd8007027a1db2657e507eec91dca52cdb84e94.
fixes #8391
=> chore(deps-dev): downgrade @storybook/addons from 6.2.9 to 5.3.19

packages/fxa-content-server/scripts/test-ci-remote.sh, packages/fxa-content-server/tests/functional/404.js, packages/fxa-content-server/tests/functional/500.js, packages/fxa-content-server/tests/functional/avatar.js, packages/fxa-content-server/tests/functional/back_button_after_start.js, packages/fxa-content-server/tests/functional/cookies_disabled.js, packages/fxa-content-server/tests/functional/email_domain_mx_validation.js, packages/fxa-content-server/tests/functional/lib/helpers.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/oauth_sign_in.js, packages/fxa-content-server/tests/functional/oauth_sign_in_token_code.js, packages/fxa-content-server/tests/functional/post_verify/account_recovery.js, packages/fxa-content-server/tests/functional/post_verify/force_password_change.js, packages/fxa-content-server/tests/functional/security_events.js, packages/fxa-content-server/tests/functional/settings_v2/change_password.js, packages/fxa-content-server/tests/functional/settings_v2/connected_services_oauth_clients.js, packages/fxa-content-server/tests/functional/settings_v2/secondary_email.js, packages/fxa-content-server/tests/functional/sign_in_blocked.js, packages/fxa-content-server/tests/functional/sign_up_with_code.js, packages/fxa-content-server/tests/functional_regression.js, packages/fxa-content-server/tests/intern.js
- These tests were failing when they ran against stage environment
- Fixes many small issues with failing tests
- Majority were clicking a button and not having a ready selector to let the test know to continue to next step
- Couple were stage config related
- Adds a small delay (100ms) when opening Rp window, before making any clicks
- I can't exactly pinpoint why this delay helps fixing these, but they were passing 5/5 times on stage 🤷🏾‍♂️
Closes: #8390
Triggered the job directly and all tests were passing.
=> fix(tests): Fix regression functional tests

packages/fxa-admin-panel/src/components/AccountSearch/index.tsx
- completion of UID search feature for admin panel enhancements
- adds a new feature to admin panel and closes FXA-2634
Closes: # 6748
- [x ] My commit is GPG signed.
=> 2634 uid search

packages/fxa-shared/l10n/supportedLanguages.json
=> chore(l10n): add eu to supported languages

packages/fxa-content-server/server/lib/routes/post-metrics.js, packages/fxa-content-server/server/lib/validation.js, packages/fxa-shared/metrics/amplitude-event.1.schema.json, packages/fxa-shared/metrics/amplitude.js, packages/fxa-shared/test/metrics/amplitude.js
=> chore(settings): remove settings_version from metrics

packages/fxa-admin-panel/package.json, packages/fxa-payments-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, yarn.lock
=> Revert "chore(deps-dev): bump @storybook/addon-links from 6.2.8 to 6.2.9"

packages/fxa-content-server/app/scripts/templates/force_auth.mustache, packages/fxa-content-server/app/scripts/views/force_auth.js
=> fix(fxios): allow /oauth/force_auth to link to 'use a different account'

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* We want to know more details about Stripe calls, and whether they are
throwing errors.
This commit:
* Adds a counter for the stripe call along with whether it resulted in
an error.
Closes #8358
=> feat(auth-server): add stripe metric details

packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.tsx
=> fix(l10n): added missing l10n to replace-recovery-codes page

packages/fxa-settings/src/components/InputText/index.tsx
=> fix(l10n): added title to input text element for l10n

packages/123done/package.json, yarn.lock
=> fix(deps): remove convict types from 123done

packages/fxa-auth-server/scripts/delete-account.js
Because:
- with PayPal enabled the delete account script now need dependencies
that depends on the DI container to have such dependencies
This commit:
- create and add dependencies into the DI container in the perfect
order
Closes: #8497
=> fix(scripts): fix dependencies for delete-account

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/package.json, packages/fxa-auth-server/scripts/populate-stripe-customer-db.ts, packages/fxa-auth-server/test/local/payments/fixtures/stripe/event_customer_subscription_updated.json, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/remote/subscription_tests.js, packages/fxa-payments-server/src/components/PaymentConfirmation/index.stories.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.stories.tsx, packages/fxa-payments-server/src/components/PlanDetails/index.stories.tsx, packages/fxa-payments-server/src/lib/mock-data.tsx, packages/fxa-payments-server/src/lib/test-utils.tsx, packages/fxa-payments-server/src/routes/Product/index.stories.tsx, packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx, packages/fxa-shared/package.json, packages/fxa-shared/subscriptions/metadata.ts, packages/fxa-shared/subscriptions/stripe.ts, packages/fxa-shared/subscriptions/types.ts, packages/fxa-shared/test/subscriptions/metadata.ts, yarn.lock
Because:
* We want to use the latest library and API to avoid falling behind.
This commit:
* Updates to the latest Stripe library.
Closes #7436
=> chore(auth-server): update stripe

packages/fxa-auth-server/config/index.ts
to the new settings route
fixes #8024
=> fix(email): update refresh recovery codes link in email

.vscode/extensions.json, .vscode/launch.json
- I finally published pm2-node-debugger to the marketplace
=> feat(debug): add new vscode extension recommendations and launch config

packages/fxa-content-server/app/scripts/templates/index.mustache, packages/fxa-content-server/app/scripts/views/index.js
Lets see if all these tests pass...
=> fix(autofill): disable email autocomplete while we figure out why it broke

packages/fxa-auth-server/lib/routes/utils/signin.js
Because:
* There was some complex bits tangled in promise chains.
This commit:
* Updates the remaining promise chains to async.
=> chore(auth-server): asyncify signin

package.json, packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx, packages/fxa-admin-panel/src/components/AccountSearch/index.tsx, packages/fxa-admin-server/src/database/model/recovery-keys.model.ts, packages/fxa-admin-server/src/database/model/security-events.model.ts, packages/fxa-admin-server/src/database/model/session-tokens.model.ts, packages/fxa-admin-server/src/database/model/totp.model.ts, packages/fxa-admin-server/src/gql/account/account.resolver.spec.ts, packages/fxa-admin-server/src/gql/account/account.resolver.ts
- We want to limit access to sensitive data
Closes: #8570
=> chore(admin): remove unnecessary columns from admin panel queries

packages/fxa-auth-server/lib/db/index.js, packages/fxa-auth-server/lib/luaScripts/touchSessionToken_1.lua, packages/fxa-auth-server/lib/routes/attached-clients.js, packages/fxa-auth-server/test/local/redis.js, packages/fxa-auth-server/test/local/routes/attached-clients.js, packages/fxa-auth-server/test/remote/db_tests.js
Cherry picked from https://github.com/mozilla/fxa/commit/e67a6033017605d879bcbc0989f67e97f9e6bbf2
=> Train 207 fix session locatoin in settings

packages/fxa-auth-server/lib/routes/account.ts
Because:
* Creating an account with no password needs to re-use most of the parts
of accountCreate with some slight alterations. The existing
accountCreate needed its component parts split out for re-use.
This commit:
* Refactors the nested functions in accountCreate into private functions
on the class for future re-use.
Issue #8735
=> refactor(auth): split account create functions out

packages/fxa-admin-panel/src/components/AccountSearch/Account/index.test.tsx, packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx, packages/fxa-admin-panel/src/components/AccountSearch/index.test.tsx, packages/fxa-admin-panel/src/components/AccountSearch/index.tsx, packages/fxa-admin-server/src/database/model/account.model.ts, packages/fxa-admin-server/src/database/model/accounts.sql, packages/fxa-admin-server/src/gql/account/account.resolver.ts, packages/fxa-admin-server/src/gql/model/account.model.ts, packages/fxa-admin-server/src/schema.gql, packages/fxa-auth-db-mysql/lib/db/patch.js, packages/fxa-auth-db-mysql/lib/db/schema/patch-116-117.sql, packages/fxa-auth-db-mysql/lib/db/schema/patch-117-116.sql, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-shared/db/models/auth/account.ts, packages/fxa-shared/db/models/auth/base-auth.ts
=> feat(admin): disable account

packages/fxa-shared/package.json, yarn.lock
=> Revert "chore(deps): bump accept-language from 2.0.17 to 3.0.18"

packages/fxa-settings/src/lib/auth-errors/en-US.ftl
Closes: https://github.com/mozilla/fxa/issues/9783
=> chore(localization): Add comments for the retryAfter fluent variable

packages/fxa-auth-server/package.json, packages/fxa-auth-server/scripts/populate-vat-taxes.ts
Because:
* We want existing subscribers to have VAT included on their invoices.
This commit:
* Adds the appropriate VAT to the subscription items for existing
subscribers that didn't have a tax rate listed.
Closes #9359
=> feat(auth): add VAT tax population script

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/package.json, packages/fxa-auth-server/scripts/populate-vat-taxes.ts, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js, packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
=> Train 210 uplift for 210.2

packages/fxa-content-server/tests/functional.js, packages/fxa-graphql-api/package.json, yarn.lock
Disable these tests while we debug https://github.com/mozilla/fxa/issues/9863
=> fix(tests): disable verification reminders functional tests

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/scripts/populate-vat-taxes.ts, packages/fxa-auth-server/test/local/payments/stripe.js
=> Train 210 uplift for 210.3

packages/fxa-auth-server/bin/email_notifications.js
Because:
* We need to check Stripe data during email bounce handling, and it
requires the StripeHelper to be setup.
This commit:
* Adds the container setup to the email notification script so that
the StripeHelper is available.
Closes #9971
=> fix(auth): setup containers for email script

packages/fxa-auth-server/bin/email_notifications.js
Because:
* We need to hotfix bin/email_notifications.js
=> Train 211.2 --> Train 211

packages/fxa-auth-server/scripts/generate-client-for-ops.js
Updated usage info to include allowedScopes, updated SQL command and added console ouput for client id. 
Removed legacy deployment config output. 
Output has been validated with a recent stage credential generation.
=> Updated generate-client-for-ops.js script 

packages/fxa-content-server/app/scripts/views/post_verify/finish_account_setup/set_password.js, packages/fxa-content-server/app/tests/spec/views/post_verify/finish_account_setup/set_password.js
- We need to be able to see why users fail to set passwords on their new accounts
- Adds `logError` to spots where we need them in set password view. This call sentry under the hood
Closes: https://github.com/mozilla/fxa/issues/9729
=> feat(passwords): Add sentry logging for set password errors

packages/fxa-content-server/app/scripts/views/post_verify/finish_account_setup/set_password.js, packages/fxa-content-server/app/tests/spec/views/post_verify/finish_account_setup/set_password.js
Follow up from slack and https://github.com/mozilla/fxa/pull/9995, lets not log these non bug errors.
=> fix(sentry): Don't log password not match errors

package.json
Fixes https://github.com/mozilla/fxa/issues/10020
=> chore(tests): add fxa-graphql-api as test dep for fxa-settings

packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/lib/routes/subscriptions/utils.ts, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js, packages/fxa-auth-server/test/local/senders/email.js, packages/fxa-auth-server/test/mocks.js, packages/fxa-auth-server/test/remote/password_forgot_tests.js, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/models/verification/set-password.js, packages/fxa-content-server/app/scripts/views/post_verify/finish_account_setup/set_password.js, packages/fxa-content-server/app/tests/spec/models/account.js, packages/fxa-content-server/app/tests/spec/views/post_verify/finish_account_setup/set_password.js
=> send the "setup account" email

packages/fxa-payments-server/server/lib/server.js
Because:
* We are seeing a 404 on stage for the new checkout route
This commit:
* Ensures we correctly route to index.html for this new route.
Closes #10041
Regression introduced by #9793
=> fix(payments): add checkout route to INDEX_ROUTES

packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/src/components/Header/index.stories.tsx, packages/fxa-payments-server/src/components/Header/index.test.tsx, packages/fxa-payments-server/src/components/Header/index.tsx, packages/fxa-payments-server/src/components/NewUserEmailForm/index.scss, packages/fxa-payments-server/src/components/NewUserEmailForm/index.stories.tsx, packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx, packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx, packages/fxa-payments-server/src/components/PayPalButton/index.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.tsx, packages/fxa-payments-server/src/routes/Checkout/index.scss, packages/fxa-payments-server/src/routes/Checkout/index.stories.tsx, packages/fxa-payments-server/src/routes/Checkout/index.test.tsx, packages/fxa-payments-server/src/routes/Checkout/index.tsx
-Adds components needed to fulfill the layout of the new checkout page.
- Adds the check to enable submit button once consent checkbox is
checked.
- fixes #9750
- refs #9361
=> task(fxa-payments-server): add components to new checkout layout

packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/src/components/PaymentConfirmation/images/checkmark.svg, packages/fxa-payments-server/src/components/PaymentConfirmation/images/email-sent.svg, packages/fxa-payments-server/src/components/PaymentConfirmation/index.scss, packages/fxa-payments-server/src/components/PaymentConfirmation/index.stories.tsx, packages/fxa-payments-server/src/components/PaymentConfirmation/index.test.tsx, packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx, packages/fxa-payments-server/src/components/PlanDetails/index.scss, packages/fxa-payments-server/src/components/PlanDetails/index.tsx, packages/fxa-payments-server/src/components/SubscriptionTitle/index.scss, packages/fxa-payments-server/src/routes/Checkout/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionSuccess/index.tsx, packages/fxa-payments-server/src/styles/_mixins.scss
- We need to update these to match new figma designs
- Updates designs from https://www.figma.com/file/cOIAuHIIbrPbAlAIcpejNM/%F0%9F%8E%A1MVP-Subscription-Optimization-Flow?node-id=400%3A2098
Closes: https://github.com/mozilla/fxa/issues/9365
=> feat(payment): update payment success page to new designs

packages/fxa-auth-server/lib/routes/auth-schemes/pubsub.js, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/test/local/senders/email.js
=> Train 213 uplift

packages/fxa-auth-server/README.md, packages/fxa-auth-server/config/dev.json, packages/fxa-auth-server/lib/senders/emails/fluent-localizer.ts, packages/fxa-auth-server/lib/senders/emails/partials/button/index.ts, packages/fxa-auth-server/lib/senders/emails/partials/manageAccount/en-US.ftl, packages/fxa-auth-server/lib/senders/emails/partials/manageAccount/index.txt, packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/en-US.ftl, packages/fxa-auth-server/lib/senders/emails/templates/index.ts, packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/en-US.ftl, packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/index.txt, packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/en-US.ftl, packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.stories.ts, packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.ts, packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.txt, packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Clone of #10122 but not on a fork
=> Do not merge - feat(auth-server): Convert postRemoveSecondary template to new stack

packages/fxa-auth-server/lib/pool.js, packages/fxa-auth-server/test/local/backendService.js
=> fix(auth): enable a retry on backendServices

packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-content-server/app/scripts/lib/fxa-client.js, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/models/user.js, packages/fxa-content-server/app/scripts/views/post_verify/finish_account_setup/set_password.js, packages/fxa-content-server/app/tests/spec/views/post_verify/finish_account_setup/set_password.js
=> fix(auth): return a session token in /account/finish_setup

packages/fxa-auth-server/config/dev.json, packages/fxa-auth-server/lib/senders/emails/global.scss, packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.scss, packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.ts, packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.txt, packages/fxa-auth-server/lib/senders/emails/partials/appBadges/index.scss, packages/fxa-auth-server/lib/senders/emails/partials/appBadges/index.ts, packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailNoAction/index.scss, packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailNoAction/index.ts, packages/fxa-auth-server/lib/senders/emails/partials/cadReminder/index.ts, packages/fxa-auth-server/lib/senders/emails/partials/verificationReminder/index.ts, packages/fxa-auth-server/lib/senders/emails/partials/verificationReminder/index.txt, packages/fxa-auth-server/lib/senders/emails/templates/cadReminderFirst/index.stories.ts, packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/index.stories.ts, packages/fxa-auth-server/lib/senders/emails/templates/index.ts, packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/index.ts, packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.stories.ts, packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.ts, packages/fxa-auth-server/lib/senders/emails/templates/postVerify/en-US.ftl, packages/fxa-auth-server/lib/senders/emails/templates/postVerify/index.ts, packages/fxa-auth-server/lib/senders/emails/templates/postVerify/index.txt, packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/en-US.ftl, packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.stories.ts, packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.ts, packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.txt, packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/en-US.ftl, packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/index.stories.ts, packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/index.ts, packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/index.txt, packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Clone of #10136 but not on a fork to get CI passing
=> feat(auth-server): Convert verificationReminder templates to new stack

packages/fxa-auth-server/lib/cad-reminders.js, packages/fxa-auth-server/lib/verification-reminders.js, packages/fxa-auth-server/package.json, packages/fxa-auth-server/scripts/clean-up-old-ci-stripe-customers.js, packages/fxa-auth-server/scripts/test-ci.sh, packages/fxa-auth-server/scripts/test-local.sh, packages/fxa-auth-server/test/local/cad-reminders.js, packages/fxa-auth-server/test/local/verification-reminders.js, packages/fxa-auth-server/test/oauth/api.js, yarn.lock
Almost 2x faster
also closes #8962
=> chore(tests): use esbuild to speed up auth-server tests (experimental)

packages/fxa-auth-server/test/local/metrics/amplitude.js, packages/fxa-content-server/tests/server/amplitude-schema-validation.js, packages/fxa-shared/metrics/amplitude.js, packages/fxa-shared/test/metrics/amplitude.js
=> fix(tests): surprise! some tests fail with a patch version > 9

packages/fxa-auth-server/lib/payments/capability.ts
=> fix(auth): fixed auth-server startup when stripe is not configured

packages/123done/static/js/123done.js
Fixes https://github.com/mozilla/fxa/issues/10462
=> fix(tests): Update 123done stage url

release.sh
Got burned by this when doing my first patch release in a while :D
=> chore(release): make sure you're not on main if you're doing a patch release

packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts, packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* We are incorrectly reporting Sentry errors when refunding users
that paid via Stripe on credit notes.
This commit:
* Only reports via Sentry if a Stripe paying user was credited out of
band or on their account balance.
Closes #9323
=> fix(auth): stop reporting errors on legit credit notes

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/pocket-migration.js, packages/fxa-content-server/app/scripts/templates/index.mustache, packages/fxa-content-server/app/scripts/templates/ready.mustache, packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache, packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache, packages/fxa-content-server/app/styles/modules/_graphic.scss, packages/fxa-content-server/tests/functional/lib/selectors.js
- We have some minor fixes for pocket
- Fixes image loading issue
- Enables the migration
Closes: #10720
=> Train 217 pocket fixes uplift

packages/fxa-content-server/app/scripts/templates/index.mustache, packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache, packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache, packages/fxa-payments-server/public/locales/en-US/main.ftl
- Localization team found a few issues in https://github.com/mozilla/fxa-content-server-l10n/pull/529
- This fixes it
Closes: NA
=> fix(tet): Fix a few pocket localization issues

packages/fxa-auth-server/lib/senders/email.js
Because:
* We want a unified survey for VPN and Relay cancellation
This commit:
* Updates the cancellation survey url
Closes #10647
=> chore(auth): update survey url

packages/fxa-shared/db/config.ts, packages/fxa-shared/db/index.ts, packages/fxa-shared/db/models/auth/account.ts
Disables the query to check for metrics opt out for now.
Fixes https://github.com/mozilla/fxa/issues/10963
=> fix(metrics): temporarily disable the metrics opt out check

packages/fxa-graphql-api/src/database/database.service.spec.ts
Missed updating a test on last commit :(
=> fix(tests): Add fixes for test

packages/fxa-auth-server/package.json, yarn.lock
Reverts mozilla/fxa#10916 because no thanks pure ESM
=> Revert "chore(deps): bump p-retry from 4.6.1 to 5.0.0"

packages/fxa-auth-server/lib/payments/processing-tasks-setup.ts, packages/fxa-auth-server/scripts/paypal-processor.ts
Because:
* Components started using containers that hadn't been setup for the
paypal-processor resulting in it erroring on startup.
This commit:
* Sets up the needed objects and adds a basic statsd metric emit when
startup completes.
Closes #10985
=> fix(auth): setup container objects for processor

packages/fxa-auth-server/bin/email_notifications.js
im not sure this is everything...
=> fix(auth): add firestore to email_notifications process

packages/fxa-admin-server/scripts/email-bounce.ts
- I yanked most of the db stuff out of the admin-server in #11113, but forgot to update the imports in the email-bounce script
- Updates the email-bounce script to import from fxa-shared as well
=> fix(admin-server): update imports in email-bounce script

packages/fxa-auth-server/config/index.ts, packages/fxa-email-service/config/default.json, packages/fxa-email-service/scripts/test-ci.sh
we want to relax the contraints on bounce handling. with the shape of the config i don't see any way to do it with environment variables so this changes the detault json config :shrug:
=> chore(email): change email-service bounce config

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/fixtures/stripe/event_payment_method_attached.json, packages/fxa-auth-server/test/local/payments/stripe.js
I landed a [fix](https://github.com/mozilla/fxa/pull/11139) in `main` yesterday that I'd like to ridealong if/when we next do a dot release. Tagging @jodyheavener , as IIUC, you are the Train 220 release owner?
=> Train 220 dot release optional ridealong

.circleci/config.yml, _scripts/check-url.sh, packages/functional-tests/playwright.config.ts, packages/fxa-admin-server/package.json, packages/fxa-auth-server/scripts/start-local.sh, packages/fxa-graphql-api/package.json, packages/fxa-profile-server/package.json
Should fix broken admin server
=> fix(admin-server): move ts-morph to dependencies

packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-profile-server/lib/routes/_core_profile.js, packages/fxa-profile-server/lib/routes/profile.js, packages/fxa-shared/db/models/auth/account.ts
=> Add metricsEnabled to profile

packages/fxa-auth-server/test/local/senders/mjml-emails.ts
fix(auth-server): investigate test regarding subscriptionTermsUrl for new email templates
Because:
* the test for subscriptionTermsUrl kept failing
This commit:
* fixes the test
Closes #11226
=> fix(auth-server): investigate test regarding subscriptionTermsUrl for new email templates

packages/fxa-settings/README.md, packages/fxa-settings/package.json, packages/fxa-settings/scripts/test-ci.sh
- We want to increase test coverage.
- Adds configuration for test coverage thresholds.
Closes #10774
=> chore(settings): add test coverage thresholds

packages/fxa-graphql-api/src/gql/account.resolver.ts
Because:
* The sentry error indicates an error with unverified accounts when
querying the avatar on occasion.
This commit:
* Adds additional error details to determine what is happening.
Issue #9364
=> feat(gql): add more detailed error on avatar

packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/test/local/payments/capability.js
Because:
* We want to gracefully handle firestore fetch errors that we can't
remedy.
This commit:
* Catches the firestore fetch error and gracefully continues.
Closes #11026
=> fix(auth): handle firestore play fetch error

packages/fxa-customs-server/test/remote/password_reset_clears_bad_logins.js
skip it until we can fix it in #11320
=> test(customs): skip flaky customs test

packages/fxa-content-server/app/tests/spec/lib/metrics.js
fixes #11012
setTimeout isn't 1ms precise
=> fix(test): fixed flaky mocha test

_dev/goaws/goaws.yaml, _scripts/goaws.sh, packages/123done/server.js, packages/fxa-auth-server/config/dev.json, packages/fxa-event-broker/README.md, packages/fxa-event-broker/config/development.json, packages/fxa-event-broker/src/firestore/firestore.service.ts, packages/fxa-event-broker/src/google-pubsub.service.ts, packages/fxa-event-broker/src/jwtset/jwtset.service.spec.ts, packages/fxa-event-broker/src/jwtset/jwtset.service.ts, packages/fxa-event-broker/src/jwtset/set.interface.ts, packages/fxa-event-broker/src/pubsub-proxy/pubsub-proxy.controller.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.spec.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.ts, packages/fxa-event-broker/src/queueworker/sqs.dto.ts
=> feat(event-broker): add email to profile-change event 

packages/fxa-auth-server/.vscode/launch.json
- Debugging is nice.
- Adds a launch task for quickly debugging the email verification reminders script.
=> chore(auth): Adds launch task for verification reminders.

packages/fxa-content-server/tests/functional/avatar.js, packages/fxa-settings/src/components/App/index.tsx
=> fix(settings): redirect /settings/avatar/change to /settings/avatar/

packages/fxa-auth-server/lib/senders/emails/fluent-localizer.ts, packages/fxa-auth-server/test/local/senders/emails/fluent-localizer.ts
=> Revert "bug(auth): Don't fail when l10n id is missing from en bundle"

.circleci/config.yml, packages/functional-tests/tests/misc.spec.ts
Thanks @chenba for fixing the stripe metadata!
=> chore(tests): enable subscribe test on dev

packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/index.stories.ts
- New email template storybook file contains identical data to existing
template.
- Updates storybook file to accurately represent the new template.
=> fix(email): Storybook fixes for invoice discount

_dev/docker/builder/Dockerfile, _dev/docker/mono/Dockerfile
local dev and CI have been stable on 16 for a while. Let's update prod.
=> chore(deps): update docker images to node 16

packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* This didn't get into the prior PR for FXA-4182.
This commit:
* Add's the missing test.
=> feat(auth): test cleanup

packages/fxa-settings/src/components/ConnectedServices/index.test.tsx, packages/fxa-settings/src/components/DataCollection/en-US.ftl, packages/fxa-settings/src/components/DataCollection/index.test.tsx, packages/fxa-settings/src/components/DataCollection/index.tsx, packages/fxa-settings/src/components/Nav/index.test.tsx, packages/fxa-settings/src/components/Nav/index.tsx, packages/fxa-settings/src/components/PageDeleteAccount/index.test.tsx, packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.test.tsx, packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.test.tsx, packages/fxa-settings/src/components/PageSettings/index.stories.tsx, packages/fxa-settings/src/components/PageSettings/index.test.tsx, packages/fxa-settings/src/components/PageSettings/index.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.test.tsx
Because:
* We want users to be able to use the feature now that we're more code complete
This commit:
* Removes conditionals hiding this feature
* Handles toggling errors
* Increases test coverage including metric events
fixes #10732
=> feat(settings): Display DataCollection in UI, increase test coverage

AUTHORS, packages/fxa-admin-panel/CHANGELOG.md, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/CHANGELOG.md, packages/fxa-admin-server/package.json, packages/fxa-auth-server/CHANGELOG.md, packages/fxa-auth-server/package.json, packages/fxa-content-server/CHANGELOG.md, packages/fxa-content-server/package.json, packages/fxa-customs-server/CHANGELOG.md, packages/fxa-customs-server/package.json, packages/fxa-event-broker/CHANGELOG.md, packages/fxa-event-broker/package.json, packages/fxa-geodb/CHANGELOG.md, packages/fxa-geodb/package.json, packages/fxa-graphql-api/CHANGELOG.md, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/CHANGELOG.md, packages/fxa-payments-server/package.json, packages/fxa-profile-server/CHANGELOG.md, packages/fxa-profile-server/package.json, packages/fxa-react/CHANGELOG.md, packages/fxa-react/package.json, packages/fxa-settings/CHANGELOG.md, packages/fxa-settings/package.json, packages/fxa-shared/CHANGELOG.md, packages/fxa-shared/package.json, packages/fxa-support-panel/CHANGELOG.md, packages/fxa-support-panel/package.json
=> Release 1.224.0

packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/test/local/routes/account.js
Because:
- we see duplicate customers in Stripe for some email addresses
This commit:
- delete a customer without any subscriptions when we delete the
associated "stub" account
Closes: #10303
=> fix(subscriptions): delete customer when deleting stub acct

packages/fxa-auth-server/lib/google-maps-services.ts, packages/fxa-auth-server/lib/routes/subscriptions/account.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/test/local/google-maps-services.js, packages/fxa-auth-server/test/local/routes/subscriptions/account.js, packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js, packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js, packages/fxa-payments-server/src/routes/Checkout/index.tsx
- let's get https://github.com/mozilla/fxa/pull/11760 and https://github.com/mozilla/fxa/pull/11701 into 224.2
=> 224.2 uplift for subplat fixes

packages/fxa-auth-server/lib/google-maps-services.ts, packages/fxa-auth-server/lib/routes/subscriptions/account.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/lib/senders/emails/fluent-localizer.ts, packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.scss, packages/fxa-auth-server/lib/senders/emails/localizer-bindings-node.ts, packages/fxa-auth-server/lib/senders/emails/localizer-bindings.ts, packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountReminderFirst/index.txt, packages/fxa-auth-server/lib/senders/emails/templates/unblockCode/index.mjml, packages/fxa-auth-server/lib/senders/emails/templates/verifyLoginCode/en.ftl, packages/fxa-auth-server/lib/senders/emails/templates/verifyLoginCode/index.mjml, packages/fxa-auth-server/lib/senders/emails/templates/verifyLoginCode/index.stories.ts, packages/fxa-auth-server/package.json, packages/fxa-auth-server/test/local/google-maps-services.js, packages/fxa-auth-server/test/local/routes/subscriptions/account.js, packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js, packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js, packages/fxa-auth-server/test/local/senders/emails/fluent-localizer.ts, packages/fxa-auth-server/test/local/senders/mjml-emails.ts, packages/fxa-payments-server/src/routes/Checkout/index.tsx, packages/fxa-react/lib/AppLocalizationProvider.tsx, packages/fxa-shared/l10n/otherLanguages.ts
=> Train 224 uplift 2

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-profile-server/lib/config.js
=> Train 224 uplift 3

packages/fxa-auth-server/lib/payments/stripe.ts
need to fix a couple names for Stripe retrieves
=> 224.4 uplift

packages/fxa-auth-server/config/index.ts
=> feat(config): Add options for mysql pool queue limit

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/senders/emails/storybook-email.ts, packages/fxa-content-server/app/scripts/lib/strings.js
- Mozilla Support URL was updated
- Reflects updated Mozilla Support URL
Closes: #11827
=> fix(auth-server): fix broken link for Mozilla Support

docs/adr/0029-using-google-auth-library.md
- Add ADR for Google Auth Library approach
Closes: https://github.com/mozilla/fxa/issues/11841
=> chore(docs): Add ADR for Google Auth Library approach

packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts, packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
- when a PayPal user's initial payment failed while subscribing to a
product through the "passwordless" flow, we erroneously send a
cancellation email to the user, who hasn't successfully created an
account or subscription yet
This commit:
- skip the email if the subscription is a PayPal based one and the user
isn't verified (has set a password)
Closes: #11746
=> fix(subscriptions): stop cancellation email on failed PayPal payment

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
Because:
- Stripe payment methods and customers can be updated independently, so
it's not an exception to receive a payment method update event on a
deleted customer
This commit:
- ignore deleted customers on payment method update events
Closes: #11901
=> fix(subscriptions): ignore deleted customers on payment method updates

packages/fxa-auth-server/lib/routes/subscriptions/account.ts, packages/fxa-auth-server/test/local/routes/subscriptions/account.js, packages/fxa-payments-server/src/routes/Checkout/index.test.tsx, packages/fxa-payments-server/src/routes/Checkout/index.tsx, packages/fxa-payments-server/src/routes/Product/index.tsx, yarn.lock
Reverts mozilla/fxa#12014 because yarn lockfile conflicts
=> Revert "fix(subscriptions): send email and reduce errors for SCA flow"

packages/fxa-settings/src/components/LinkedAccounts/LinkedAccount.tsx, packages/fxa-settings/src/components/LinkedAccounts/en-US.ftl, yarn.lock
- Updates unlink text per l10n request
Closes: https://github.com/mozilla/fxa/issues/12028
=> fix(l10n): Update unlink account text

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/senders/email.js
Removes mailer connection pool
=> fix(email): remove pooling to fix delivery failures (#12058)

packages/fxa-admin-panel/CHANGELOG.md, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/CHANGELOG.md, packages/fxa-admin-server/package.json, packages/fxa-auth-server/CHANGELOG.md, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/package.json, packages/fxa-content-server/CHANGELOG.md, packages/fxa-content-server/package.json, packages/fxa-customs-server/CHANGELOG.md, packages/fxa-customs-server/package.json, packages/fxa-event-broker/CHANGELOG.md, packages/fxa-event-broker/package.json, packages/fxa-geodb/CHANGELOG.md, packages/fxa-geodb/package.json, packages/fxa-graphql-api/CHANGELOG.md, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/CHANGELOG.md, packages/fxa-payments-server/package.json, packages/fxa-profile-server/CHANGELOG.md, packages/fxa-profile-server/package.json, packages/fxa-react/CHANGELOG.md, packages/fxa-react/package.json, packages/fxa-settings/CHANGELOG.md, packages/fxa-settings/package.json, packages/fxa-shared/CHANGELOG.md, packages/fxa-shared/package.json, packages/fxa-support-panel/CHANGELOG.md, packages/fxa-support-panel/package.json
Removes pooling so every email gets its own request.
=> Train 226.3

packages/fxa-auth-server/bin/email_notifications.js
add logger to Container for email notifications script
=> Train 226 uplift 3

packages/fxa-admin-panel/CHANGELOG.md, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/CHANGELOG.md, packages/fxa-admin-server/package.json, packages/fxa-auth-server/CHANGELOG.md, packages/fxa-auth-server/package.json, packages/fxa-content-server/CHANGELOG.md, packages/fxa-content-server/package.json, packages/fxa-customs-server/CHANGELOG.md, packages/fxa-customs-server/package.json, packages/fxa-event-broker/CHANGELOG.md, packages/fxa-event-broker/package.json, packages/fxa-geodb/CHANGELOG.md, packages/fxa-geodb/package.json, packages/fxa-graphql-api/CHANGELOG.md, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/CHANGELOG.md, packages/fxa-payments-server/package.json, packages/fxa-profile-server/CHANGELOG.md, packages/fxa-profile-server/package.json, packages/fxa-react/CHANGELOG.md, packages/fxa-react/package.json, packages/fxa-settings/CHANGELOG.md, packages/fxa-settings/package.json, packages/fxa-shared/CHANGELOG.md, packages/fxa-shared/package.json, packages/fxa-support-panel/CHANGELOG.md, packages/fxa-support-panel/package.json
Fixing merge conflicts on train-226 into main. (We think conflicts are caused by a squash and merge accidentally being done from train-226 into main.)
=> Uplift main from train 226

packages/fxa-settings/src/components/App/index.test.tsx
- adds the following tests:
- renders `LoadingSpinner` component when loading initial state is true
- renders `LoadingSpinner` component when the error in initial state includes "Invalid token"
- renders `AppErrorDialog` component when the error in initial state doesn't include "Invalid token"
- routes to `/display_name`
- routes to `/avatar`
- routes to `/change_password`
- routes to `/account_recovery`
- routes to `/emails`
- routes to `/emails/verify`
- routes to `/two_step_authentication`
- routes to `/two_step_authentication/replace_codes`
- routes to `/delete_account`
- redirects to `/settings#connected-services`
- redirects to `/settings/avatar/`
Closes: #11518
=> chore(settings): Include additional tests within App component

packages/fxa-admin-panel/CHANGELOG.md, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/CHANGELOG.md, packages/fxa-admin-server/package.json, packages/fxa-auth-server/CHANGELOG.md, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/package.json, packages/fxa-content-server/CHANGELOG.md, packages/fxa-content-server/package.json, packages/fxa-customs-server/CHANGELOG.md, packages/fxa-customs-server/package.json, packages/fxa-event-broker/CHANGELOG.md, packages/fxa-event-broker/package.json, packages/fxa-geodb/CHANGELOG.md, packages/fxa-geodb/package.json, packages/fxa-graphql-api/CHANGELOG.md, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/CHANGELOG.md, packages/fxa-payments-server/package.json, packages/fxa-profile-server/CHANGELOG.md, packages/fxa-profile-server/package.json, packages/fxa-react/CHANGELOG.md, packages/fxa-react/package.json, packages/fxa-settings/CHANGELOG.md, packages/fxa-settings/package.json, packages/fxa-shared/CHANGELOG.md, packages/fxa-shared/package.json, packages/fxa-support-panel/CHANGELOG.md, packages/fxa-support-panel/package.json
=> Ivo squash merge 2 2264

packages/fxa-admin-panel/package.json, packages/fxa-content-server/package.json, packages/fxa-payments-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, yarn.lock
=> Revert "chore(deps): bump react-dom from 16.14.0 to 17.0.2"

packages/fxa-auth-server/lib/redis.js
Fix typescript build error in docker build stage.
=> Train 226 uplift 5

packages/fxa-admin-panel/CHANGELOG.md, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/CHANGELOG.md, packages/fxa-admin-server/package.json, packages/fxa-auth-server/CHANGELOG.md, packages/fxa-auth-server/package.json, packages/fxa-content-server/CHANGELOG.md, packages/fxa-content-server/package.json, packages/fxa-customs-server/CHANGELOG.md, packages/fxa-customs-server/package.json, packages/fxa-event-broker/CHANGELOG.md, packages/fxa-event-broker/package.json, packages/fxa-geodb/CHANGELOG.md, packages/fxa-geodb/package.json, packages/fxa-graphql-api/CHANGELOG.md, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/CHANGELOG.md, packages/fxa-payments-server/package.json, packages/fxa-profile-server/CHANGELOG.md, packages/fxa-profile-server/package.json, packages/fxa-react/CHANGELOG.md, packages/fxa-react/package.json, packages/fxa-settings/CHANGELOG.md, packages/fxa-settings/package.json, packages/fxa-shared/CHANGELOG.md, packages/fxa-shared/package.json, packages/fxa-support-panel/CHANGELOG.md, packages/fxa-support-panel/package.json
=> Release 1.228.0

packages/fxa-auth-server/test/local/senders/emails.ts
- European DST has switched resulting in a timezone change
- Updates the test to include both timezones for the region
=> fix(mailer): mailer changing timezone test

packages/browserid-verifier/lib/config.js, packages/fxa-admin-panel/server/config/index.ts, packages/fxa-admin-server/src/config.ts, packages/fxa-auth-server/config/index.ts, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-customs-server/lib/config/config.js, packages/fxa-event-broker/src/config.ts, packages/fxa-graphql-api/src/config.ts, packages/fxa-payments-server/server/config/index.js, packages/fxa-payments-server/src/lib/config.test.ts, packages/fxa-payments-server/src/lib/config.ts, packages/fxa-payments-server/src/lib/sentry.test.js, packages/fxa-profile-server/lib/config.js, packages/fxa-settings/src/lib/config.ts, packages/fxa-shared/sentry/config-builder.ts, packages/fxa-shared/test/sentry/config-builder.ts, packages/fxa-support-panel/src/config.ts
229.2 was requested to include 8b4079c665a89db02c97792ef1cd32d4eba8d1b0.
=> 229 uplift 2 -> train 229

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
Because:
- we are receiving payment method webhook events for deleted customers
This commit:
- detach the customer's default payment method before the customer deletion
- (note that the Stripe api docs do not explicitly state that they will stop
sending payment method webhook events once it's detached; we also started
ignoring the deleted customer error on those events so at least we will no
longer return an error to Stripe)
Closes: #11984
=> feat(subscriptions): detach payment method when deleting customer

packages/fxa-auth-server/lib/routes/emails.js, packages/fxa-auth-server/test/local/routes/emails.js
=> chore(recovery_email): Audit `/recovery_email/*` endpoint

packages/fxa-auth-server/lib/payments/stripe.ts
Because:
* TS Hero was removing a duplicate error/AppError overlap.
* Logger was no longer imported for typing leading to build failures.
This commit:
* Updates error module usage for the type and module namespace to avoid
TS Hero removing duplicate name imports.
* Imports Logger again.
=> fix(auth): repair imports for Logger/error

packages/fxa-customs-server/package.json, packages/fxa-event-broker/package.json, yarn.lock
=> Revert "chore(deps): bump @google-cloud/pubsub from 2.18.4 to 2.19.0"

packages/fxa-auth-server/package.json, yarn.lock
=> Release 230.3

packages/fxa-admin-panel/CHANGELOG.md, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/CHANGELOG.md, packages/fxa-admin-server/package.json, packages/fxa-auth-server/CHANGELOG.md, packages/fxa-auth-server/package.json, packages/fxa-content-server/CHANGELOG.md, packages/fxa-content-server/package.json, packages/fxa-customs-server/CHANGELOG.md, packages/fxa-customs-server/package.json, packages/fxa-event-broker/CHANGELOG.md, packages/fxa-event-broker/package.json, packages/fxa-geodb/CHANGELOG.md, packages/fxa-geodb/package.json, packages/fxa-graphql-api/CHANGELOG.md, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/CHANGELOG.md, packages/fxa-payments-server/package.json, packages/fxa-profile-server/CHANGELOG.md, packages/fxa-profile-server/package.json, packages/fxa-react/CHANGELOG.md, packages/fxa-react/package.json, packages/fxa-settings/CHANGELOG.md, packages/fxa-settings/package.json, packages/fxa-shared/CHANGELOG.md, packages/fxa-shared/package.json, packages/fxa-support-panel/CHANGELOG.md, packages/fxa-support-panel/package.json, yarn.lock
=> Patch release 1.230.3 -> main

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* Due to a race condition on paypal customers, it was possible that
we did not get the latest customer record with currency when
creating the billing agreement and subscription.
This commit:
* Updates fetchCustomer to always refresh the customer if their
record is missing currency but they have subscriptions.
* Updates the stripe webhook to refresh as needed on subscription
events if no currency is detected.
Closes #12301
=> feat(auth): ensure customer currency is set when needed

package.json, packages/fxa-auth-server/lib/payments/paypal/processor.ts, packages/fxa-auth-server/scripts/paypal-processor.ts, packages/fxa-auth-server/test/local/payments/paypal-processor.js, yarn.lock
This reverts commit 0fd7eccf94dfaa283ee9b138593183bc0065f388, reversing
changes made to 599c83212ad8b402639585ad3501792c37a78a98.
- paypal-processor appears to be unable to run on Stage
=> Revert "Merge pull request #12403 from mozilla/fxa-4698-paypal-lock"

packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/tests/spec/models/user.js
Train 230 uplift 5 -> Train 230
=> Train 230 uplift 5 -> Train 230

packages/fxa-admin-panel/CHANGELOG.md, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/CHANGELOG.md, packages/fxa-admin-server/package.json, packages/fxa-auth-server/CHANGELOG.md, packages/fxa-auth-server/package.json, packages/fxa-content-server/CHANGELOG.md, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/tests/spec/models/user.js, packages/fxa-content-server/package.json, packages/fxa-customs-server/CHANGELOG.md, packages/fxa-customs-server/package.json, packages/fxa-event-broker/CHANGELOG.md, packages/fxa-event-broker/package.json, packages/fxa-geodb/CHANGELOG.md, packages/fxa-geodb/package.json, packages/fxa-graphql-api/CHANGELOG.md, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/CHANGELOG.md, packages/fxa-payments-server/package.json, packages/fxa-profile-server/CHANGELOG.md, packages/fxa-profile-server/package.json, packages/fxa-react/CHANGELOG.md, packages/fxa-react/package.json, packages/fxa-settings/CHANGELOG.md, packages/fxa-settings/package.json, packages/fxa-shared/CHANGELOG.md, packages/fxa-shared/package.json, packages/fxa-support-panel/CHANGELOG.md, packages/fxa-support-panel/package.json
=> Patch release 1.230.5 -> main

packages/fxa-auth-server/lib/devices.js, packages/fxa-auth-server/lib/routes/attached-clients.js, packages/fxa-auth-server/lib/routes/devices-and-sessions.js, packages/fxa-auth-server/lib/routes/emails.js, packages/fxa-auth-server/lib/routes/idp.js, packages/fxa-auth-server/lib/routes/newsletters.js, packages/fxa-auth-server/lib/routes/oauth/authorization.js, packages/fxa-auth-server/lib/routes/oauth/authorized-clients/destroy.js, packages/fxa-auth-server/lib/routes/oauth/authorized-clients/list.js, packages/fxa-auth-server/lib/routes/oauth/client/get.js, packages/fxa-auth-server/lib/routes/oauth/destroy.js, packages/fxa-auth-server/lib/routes/oauth/id_token_verify.js, packages/fxa-auth-server/lib/routes/oauth/introspect.js, packages/fxa-auth-server/lib/routes/oauth/jwks.js, packages/fxa-auth-server/lib/routes/oauth/key_data.js, packages/fxa-auth-server/lib/routes/oauth/token.js, packages/fxa-auth-server/lib/routes/oauth/verify.js, packages/fxa-auth-server/lib/routes/password.js, packages/fxa-auth-server/lib/routes/recovery-codes.js, packages/fxa-auth-server/lib/routes/recovery-key.js, packages/fxa-auth-server/lib/routes/security-events.js, packages/fxa-auth-server/lib/routes/session.js, packages/fxa-auth-server/lib/routes/sign.js, packages/fxa-auth-server/lib/routes/totp.js, packages/fxa-auth-server/lib/routes/unblock-codes.js, packages/fxa-auth-server/lib/routes/util.js
Uplift 1 :  fix(swagger): SyntaxError: Cannot use import statement outside a module
=> Train 231 uplift 1 -> Train 231

packages/fxa-auth-server/lib/senders/emails/partials/cancellationSurvey/en.ftl
See also https://github.com/mozilla/fxa-content-server-l10n/pull/578
=> Remove extra characters from data-l10n-name

packages/fxa-settings/src/components/PageDeleteAccount/en-US.ftl, packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
- I forgot to update the string id on a string which I changed, so it needs an updated ID to alert localizers to the change.
- updates the string id on the changed string.
Closes: #12787 
N/a (no visible change)
=> fix(fxa-settings): update string id on updated string

AUTHORS, packages/fxa-admin-panel/CHANGELOG.md, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/CHANGELOG.md, packages/fxa-admin-server/package.json, packages/fxa-auth-server/CHANGELOG.md, packages/fxa-auth-server/package.json, packages/fxa-content-server/CHANGELOG.md, packages/fxa-content-server/package.json, packages/fxa-customs-server/CHANGELOG.md, packages/fxa-customs-server/package.json, packages/fxa-event-broker/CHANGELOG.md, packages/fxa-event-broker/package.json, packages/fxa-geodb/CHANGELOG.md, packages/fxa-geodb/package.json, packages/fxa-graphql-api/CHANGELOG.md, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/CHANGELOG.md, packages/fxa-payments-server/package.json, packages/fxa-profile-server/CHANGELOG.md, packages/fxa-profile-server/package.json, packages/fxa-react/CHANGELOG.md, packages/fxa-react/package.json, packages/fxa-settings/CHANGELOG.md, packages/fxa-settings/package.json, packages/fxa-shared/CHANGELOG.md, packages/fxa-shared/package.json, packages/fxa-support-panel/CHANGELOG.md, packages/fxa-support-panel/package.json
=> main <- train 232 @ 232.0

packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.tsx
- Variables were renamed and not included in patch.
- Reverts variables to previous name.
=> fix(payments): rename url variables

packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.test.tsx, packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.tsx, packages/fxa-payments-server/src/components/PaymentMethodHeader/index.test.tsx, packages/fxa-payments-server/src/lib/formats.ts, packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
We need a new tag to add some l10n fallback messages
=> Train 232 uplift 2 for 232.2

packages/fxa-settings/src/components/App/en-US.ftl, packages/fxa-settings/src/components/Security/en-US.ftl, packages/fxa-settings/src/components/Security/index.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.test.tsx, packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.test.tsx, packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
=> fix(ftl): Don't treat Firefox Sync as a feature name (draft PR for contributor CI run)

.github/workflows/upload-assets-to-cdn.yml
=> fix(ci): Interpolate Slack message correctly

packages/fxa-shared/l10n/supportedLanguages.json
We have some tests that check for this on train branches
=> Uplift l10n fix for Train 232

packages/fxa-auth-server/package.json, packages/fxa-payments-server/package.json, packages/fxa-react/.eslintrc.json, packages/fxa-react/package.json
- nit: We have a few .storybook folders which aren't being linted.
- Does that thing mentioned above.
=> chore(lint): Lint hidden .storybook/ directories

packages/fxa-support-panel/src/remote-lookup/remote-responses.dto.ts
Another TS error introduced by PR #12890 . This should be the last one, as I built all the packages locally to ensure everything compiled successfully. #12823 Should help us to avoid this in the future.
Closes: # No issue
=> fix(support-panel): remove AbbrevPlayPurchase type

packages/fxa-event-broker/src/firestore/firestore.service.spec.ts, packages/fxa-settings/src/components/ConnectAnotherDevicePromo/index.test.tsx, packages/fxa-settings/src/components/DropDownAvatarMenu/index.test.tsx
Just double checking all these pass.
Will be closed when #12892 is merged
=> CI run for #12892 (contributor PR)

packages/fxa-auth-server/lib/profile/client.js, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/lib/routes/linked-accounts.ts, packages/fxa-auth-server/lib/types.ts, packages/fxa-auth-server/test/local/routes/linked-accounts.js, packages/fxa-auth-server/test/mocks.js, packages/fxa-profile-server/lib/routes/display_name/post-from-auth-server.js, packages/fxa-profile-server/lib/routing.js, packages/fxa-profile-server/test/api.js
- Local route tests were breaking, so we reverted.  @StaberindeZA wrote a patch fixing the tests!
- Merges this branch back in (rebased on top of the latest updates to main, and with the patch added.)
=> 3rd party auth sets display name

packages/fxa-auth-server/package.json, yarn.lock
=> Revert "chore(deps): bump p-retry from 4.6.2 to 5.1.1"

AUTHORS, packages/fxa-admin-panel/CHANGELOG.md, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/CHANGELOG.md, packages/fxa-admin-server/package.json, packages/fxa-auth-server/CHANGELOG.md, packages/fxa-auth-server/package.json, packages/fxa-content-server/CHANGELOG.md, packages/fxa-content-server/package.json, packages/fxa-customs-server/CHANGELOG.md, packages/fxa-customs-server/package.json, packages/fxa-event-broker/CHANGELOG.md, packages/fxa-event-broker/package.json, packages/fxa-geodb/CHANGELOG.md, packages/fxa-geodb/package.json, packages/fxa-graphql-api/CHANGELOG.md, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/CHANGELOG.md, packages/fxa-payments-server/package.json, packages/fxa-profile-server/CHANGELOG.md, packages/fxa-profile-server/package.json, packages/fxa-react/CHANGELOG.md, packages/fxa-react/package.json, packages/fxa-settings/CHANGELOG.md, packages/fxa-settings/package.json, packages/fxa-shared/CHANGELOG.md, packages/fxa-shared/package.json, packages/fxa-support-panel/CHANGELOG.md, packages/fxa-support-panel/package.json, yarn.lock
=> Release 1.233.0

packages/fxa-auth-server/lib/senders/emails/templates/downloadSubscription/includes.json
- We want to make sure that changed ids are updated everywhere to avoid missing translation errors/warnings, and future dead code
- Updates old id to fix fluent missing translation error
Closes: #12807
N/A
Related: [PR#11962](https://github.com/mozilla/fxa/pull/11962) and [PR#12206](https://github.com/mozilla/fxa/pull/12206)
=> fix(fluent): update missing id to fix fluent error

packages/fxa-content-server/package.json, packages/fxa-payments-server/package.json, yarn.lock
- Uplifting the fix for #13226 into the `train 234` branch.
=> Train 234.1 Uplift

AUTHORS, packages/fxa-admin-panel/CHANGELOG.md, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/CHANGELOG.md, packages/fxa-admin-server/package.json, packages/fxa-auth-server/CHANGELOG.md, packages/fxa-auth-server/package.json, packages/fxa-content-server/CHANGELOG.md, packages/fxa-content-server/package.json, packages/fxa-customs-server/CHANGELOG.md, packages/fxa-customs-server/package.json, packages/fxa-event-broker/CHANGELOG.md, packages/fxa-event-broker/package.json, packages/fxa-geodb/CHANGELOG.md, packages/fxa-geodb/package.json, packages/fxa-graphql-api/CHANGELOG.md, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/CHANGELOG.md, packages/fxa-payments-server/package.json, packages/fxa-profile-server/CHANGELOG.md, packages/fxa-profile-server/package.json, packages/fxa-react/CHANGELOG.md, packages/fxa-react/package.json, packages/fxa-settings/CHANGELOG.md, packages/fxa-settings/package.json, packages/fxa-shared/CHANGELOG.md, packages/fxa-shared/package.json, packages/fxa-support-panel/CHANGELOG.md, packages/fxa-support-panel/package.json
=> Release 1.234.1

.github/workflows/upload-assets-to-cdn.yml
- 
- Adds the `workflow_dispatch` trigger which will allow manual runs.
=> Added workflow_dispatch trigger to allow manual runs

packages/123done/package.json, yarn.lock
Fixes https://github.com/mozilla/fxa/issues/13395
=> chore(deps): Update ioredis in 123Done

packages/fxa-admin-server/package.json, yarn.lock
- Major version upgrade needed
- Upgrades ts-morph
Closes: #13384
=> task(admin-server): Update ts-morph from 13.0.3 to 15.1.0

packages/fxa-admin-server/package.json, yarn.lock
- Package upgrade needed.
- Upgrades googleapis package.
Closes: #13387
=> task(admin-server): Update googleapis from 102.0.0 to 104.0.0

packages/fxa-admin-server/package.json, yarn.lock
=> Revert "task(admin-server): Update googleapis from 102.0.0 to 104.0.0"

packages/fxa-geodb/lib/fxa-geodb.js, packages/fxa-geodb/package.json, yarn.lock
Fixes https://github.com/mozilla/fxa/issues/13407
=> chore(deps): Updates maxmind dep

packages/fxa-admin-panel/package.json, yarn.lock
- Package upgrade needed
- Upgrades @sentry/node
Closes: #13351
=> task(admin-panel): Upgrade @sentry/node from ^6.19.2 to ^7.2.0

packages/fxa-admin-panel/package.json, packages/fxa-admin-panel/server/lib/client-config/index.ts, yarn.lock
- Package upgrade needed
- Upgrades @types/convict
Closes: #13357
=> task(admin-panel): Upgrade @types/convict from ^5.2.2 to ^6.1.1

packages/fxa-content-server/package.json, yarn.lock
Reverts mozilla/fxa#13510 - failed `deploy-packages`
=> Revert "chore(deps): bump postcss-cli from 7.1.1 to 10.0.0"

packages/fxa-geodb/lib/maxmind-db-downloader.js, packages/fxa-geodb/package.json, yarn.lock
Fixes https://github.com/mozilla/fxa/issues/13406
=> chore(deps): Removes mkdirp dep in favor of fs impl

packages/fxa-admin-panel/package.json, yarn.lock
- We are cleaning up package dependencies and it appears this package is actually only need in the admin-server.
- Removes the graphql package.
Closes: #13354
=> task(admin-panel): Remove graphql package

packages/fxa-auth-server/lib/routes/subscriptions/paypal-notifications.ts, packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js
- Should a user get a new billing agreement added to their customer
record, while a prior one was recently deleted, but its IPN
notification arrives later, we will remove the newer billing agreement
ID from the Stripe customer metadata.
- Removes the PayPal billing agreement ID from Stripe only if the
billing agreement ID from the IPN matches what is in Stripe. If the
IDs do not match, then only the database billing agreement should be
updated.
Closes: #9328
=> fix(auth): handleMpCancel remove on BA id match [WIP]

packages/fxa-admin-panel/package.json, yarn.lock
- Package upgraded needed
- Upgrades @sentry/tracing
Closes: #13350 
=> task(fxa-admin-panel): Upgrade @sentry/tracing from ^6.19.2 to ^7.3.1

packages/fxa-geodb/package.json, yarn.lock
- We've updated these deps in other packages, so I'm cleaning them up in fxa-geodb also
- Updates eslint and sinon
Closes: #13506 
- All tests passed both before, and after updating these dependencies.
=> Fxa 5461 upgrade fxa geodb deps

packages/fxa-auth-server/lib/routes/subscriptions/paypal-notifications.ts, packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js
- Currently once a PayPal message is received for an open Stripe invoice
it is marked as paid, without performing additional checks.
- Performs additional checks on the Stripe invoice, either refunds
or marks the invoice as paid, or throws an error. More information
for each provided below.
- If the Stripe invoice is missing paypalTransactionId, it will now be
added to the Stripe invoice.
- If the Stripe paypalTransactionId does not match the PayPal IPN
transaction ID, an error is reported to Sentry, and no further action
is taken.
- If the subscription is canceled, then the payment is refunded.
- Otherwise the Stripe invoice is marked as paid.
Closes: #9325
=> fix(auth): validate invoice for paypal before marking paid

AUTHORS, packages/fxa-admin-panel/CHANGELOG.md, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/CHANGELOG.md, packages/fxa-admin-server/package.json, packages/fxa-auth-server/CHANGELOG.md, packages/fxa-auth-server/package.json, packages/fxa-content-server/CHANGELOG.md, packages/fxa-content-server/package.json, packages/fxa-customs-server/CHANGELOG.md, packages/fxa-customs-server/package.json, packages/fxa-event-broker/CHANGELOG.md, packages/fxa-event-broker/package.json, packages/fxa-geodb/CHANGELOG.md, packages/fxa-geodb/package.json, packages/fxa-graphql-api/CHANGELOG.md, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/CHANGELOG.md, packages/fxa-payments-server/package.json, packages/fxa-profile-server/CHANGELOG.md, packages/fxa-profile-server/package.json, packages/fxa-react/CHANGELOG.md, packages/fxa-react/package.json, packages/fxa-settings/CHANGELOG.md, packages/fxa-settings/package.json, packages/fxa-shared/CHANGELOG.md, packages/fxa-shared/package.json, packages/fxa-support-panel/CHANGELOG.md, packages/fxa-support-panel/package.json
Dot Release for 236.1
Commits:
* https://github.com/mozilla/fxa/commit/329c184ab4f088e32e90c2ec7011ffe8459a7d4b
=> Train 236 - Patch 1.236.1

packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/test/local/routes/validators.js
Increases redirectTo max length to 2048 characters
=> Train 236 uplift 3

packages/123done/.eslintignore, packages/123done/.eslintrc, packages/123done/.eslintrc.json
- ESLint recommends using config files w/ [explicit extensions](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#configuration-file-formats) vs generic .eslintrc mystery files.
- Adds the .json config extension and merges the .eslintignore file into the config file, per https://eslint.org/docs/latest/user-guide/configuring/ignoring-code.
=> chore(lint): Fix 123done ESLint config

packages/fxa-auth-server/README.md, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/db/index.js, packages/fxa-auth-server/package.json, packages/fxa-auth-server/scripts/prune-tokens.ts, packages/fxa-auth-server/test/local/db.js, packages/fxa-auth-server/test/scripts/prune-tokens.js, packages/fxa-shared/db/models/auth/index.ts, packages/fxa-shared/db/models/auth/prune-tokens.ts, packages/fxa-shared/db/models/auth/sign-in-codes.ts, packages/fxa-shared/db/models/auth/unblock-codes.ts
- We want use a scheduled job to prune tokens
- Introduces a script that can be used to prune tokens.
- Removes old fire and forget pruning code.
Closes: #13339
Once this lands a pruning job still needs to be setup in cloud ops.
=> task(auth): Setup out of process token pruning

packages/fxa-admin-panel/.eslintrc.json
=> chore(lint): Fix fxa-admin-panel ESLint config

packages/fxa-payments-server/src/components/PaymentMethodHeader/index.scss, packages/fxa-payments-server/src/components/PaymentMethodHeader/index.stories.tsx, packages/fxa-payments-server/src/components/PaymentMethodHeader/index.tsx, yarn.lock
- we are converting to Tailwind
Closes: #13586 
Default
With prefix
=> refactor(payments): update PaymentMethodHeader component to utilize Tailwind

packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/views/mixins/connect-another-device-mixin.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/pairing.js, yarn.lock
Reverts mozilla/fxa#13558 due to FXA-5597 (#13735)
=> Revert "fix(content): Show the download firefox page after sign in from browser menu"

packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/views/mixins/connect-another-device-mixin.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/pairing.js
=> Train 237.4 Uplift 4

packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts, packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* We don't want to accept payments on stripe customer records that
are in an invalid or inconsistent state.
This commit:
* Reports invoice payments to Sentry with sufficient information to
resolves them.
Closes FXA-5442
=> feat(auth): report invoice paid on invalid customers

packages/fxa-admin-server/package.json, packages/fxa-auth-server/package.json, yarn.lock
Reverts mozilla/fxa#13650
closes: #13766
=> Revert "chore(deps): bump googleapis from 102.0.0 to 105.0.0"

packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/views/mixins/connect-another-device-mixin.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/pairing.js, yarn.lock
Reverts mozilla/fxa#13758
Restoring behavior for 'Show the download firefox page after sign in from browser menu'. A follow up patch to address a regression caused by this change will land shortly.
=> Revert "Revert "fix(content): Show the download firefox page after sign in from browser menu""

packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/views/mixins/connect-another-device-mixin.js, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/pairing.js, yarn.lock
Train 237 uplift 5 includes changes from the following PRs
- https://github.com/mozilla/fxa/pull/13774
- https://github.com/mozilla/fxa/pull/13775
=> Train 237 uplift 5

packages/fxa-admin-panel/package.json, packages/fxa-admin-server/package.json, packages/fxa-auth-server/package.json, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/scripts/views/mixins/connect-another-device-mixin.js, packages/fxa-content-server/package.json, packages/fxa-content-server/tests/functional/lib/selectors.js, packages/fxa-content-server/tests/functional/pairing.js, packages/fxa-customs-server/package.json, packages/fxa-event-broker/package.json, packages/fxa-geodb/package.json, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/package.json, packages/fxa-profile-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json, packages/fxa-support-panel/package.json
=> Release 1.237.5

packages/fxa-admin-panel/src/components/AccountSearch/index.test.tsx, packages/fxa-admin-panel/src/components/AccountSearch/index.tsx, packages/fxa-admin-server/src/app.module.ts, packages/fxa-admin-server/src/event-logging/event-logging.module.ts, packages/fxa-admin-server/src/event-logging/event-logging.service.spec.ts, packages/fxa-admin-server/src/event-logging/event-logging.service.ts, packages/fxa-admin-server/src/gql/account/account.resolver.spec.ts, packages/fxa-admin-server/src/gql/account/account.resolver.ts, packages/fxa-admin-server/src/gql/email-bounce/email-bounce.resolver.spec.ts, packages/fxa-admin-server/src/gql/email-bounce/email-bounce.resolver.ts, packages/fxa-admin-server/src/gql/gql.module.ts, packages/fxa-admin-server/src/graphql.ts, packages/fxa-admin-server/src/schema.gql, packages/fxa-admin-server/test/app.e2e-spec.ts
- We want to track certain events
- Introduces a new event logging service
- Adds event logging
- Adds flag for whether or not account searches were done with an auto complete
Closes: #13644
This is a re-issue of this [PR](https://github.com/mozilla/fxa/pull/13742). It turns out that removing fxa-admin-server/src/config/development.json broke the build_deploy CI pipeline that runs when code is merged into main. The PR was reverted and is now being reissued, without the removed development.json config file.
=> task(admin-panel): Add event logging for analytics

packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.stories.tsx, packages/fxa-payments-server/src/components/PlanErrorDialog/index.stories.tsx, packages/fxa-payments-server/src/components/TermsAndPrivacy/index.stories.tsx, packages/fxa-payments-server/src/components/Tooltip/index.stories.tsx
- We are updating all of our stories to CSF for improved flexibility and maintenance
- Updates Storybook for the following components:
- TermsAndPrivacy
- PaymentConsentCheckbox
- PlanErrorDialog
- Tooltip
Closes: #13795
=> refactor(payments): update Storybook for Payments components

packages/123done/static/index.html, packages/123done/static/js/123done.js
- QA functional test automation requires 6m and 12m plans.
- Update 123Done with 6m and 12m plans.
Closes: #13841
=> feat(123done): add additional 123done pro plans

packages/fxa-auth-server/lib/senders/emails/templates/_versions.json, packages/fxa-auth-server/lib/senders/emails/templates/postVerify/en.ftl, packages/fxa-auth-server/lib/senders/emails/templates/postVerify/includes.json, packages/fxa-auth-server/lib/senders/emails/templates/postVerify/index.mjml, packages/fxa-auth-server/lib/senders/emails/templates/postVerify/index.stories.ts, packages/fxa-auth-server/lib/senders/emails/templates/postVerify/index.txt, packages/fxa-auth-server/test/local/senders/emails.ts
- We're updating copy on confirmation/verification emails
- Updates copy, stories, and tests for the postVerify email
=> chore(fxa-auth-server) update postVerify email copy

packages/fxa-auth-server/lib/senders/emails/templates/_versions.json, packages/fxa-auth-server/lib/senders/emails/templates/verifyLogin/en.ftl, packages/fxa-auth-server/lib/senders/emails/templates/verifyLogin/includes.json, packages/fxa-auth-server/lib/senders/emails/templates/verifyLogin/index.mjml, packages/fxa-auth-server/lib/senders/emails/templates/verifyLogin/index.stories.ts, packages/fxa-auth-server/lib/senders/emails/templates/verifyLogin/index.txt, packages/fxa-auth-server/test/local/senders/emails.ts, packages/fxa-auth-server/test/remote/account_signin_verification_tests.js
- We're updating copy in verification/confirmation emails
- Updates copy for the verifyLogin email template
=> chore(fxa-auth-server): update copy for verifyLogin email

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* We want to be able to use automatic tax when creating a subscription.
This commit:
* Adds automaticTax options to both subscription create helper methods.
Closes FXA-5671
=> feat(auth): update subscription create helpers for tax

packages/fxa-admin-panel/package.json, packages/fxa-admin-server/package.json, packages/fxa-auth-server/package.json, packages/fxa-content-server/package.json, packages/fxa-customs-server/package.json, packages/fxa-event-broker/package.json, packages/fxa-geodb/package.json, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/package.json, packages/fxa-profile-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json, packages/fxa-support-panel/package.json
=> Release 1.239.0

packages/fxa-auth-server/lib/sentry.js, packages/fxa-customs-server/lib/sentry.js, packages/fxa-profile-server/lib/server/web.js
Because:
- we want to fix a sentry related bug that's in the 240.0 tag
=> 240.1 Uplift

AUTHORS, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/package.json, packages/fxa-auth-server/lib/sentry.js, packages/fxa-auth-server/package.json, packages/fxa-content-server/package.json, packages/fxa-customs-server/lib/sentry.js, packages/fxa-customs-server/package.json, packages/fxa-event-broker/package.json, packages/fxa-geodb/package.json, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/package.json, packages/fxa-profile-server/lib/server/web.js, packages/fxa-profile-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json, packages/fxa-support-panel/package.json
=> main <- train-240

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
The wrong email is sent to the user when upgrading between different
products since the invoice detail extraction only pulls from the first
line item in the invoice. In the case of a prorated invoice, the first
line item will always be the proration, which in the case of
cross-product upgrades will be the wrong plan.
Filters all prorated line items for invoice detail extraction.
Closes: FXA-5733
=> fix(fxa-auth-server): handle prorations during invoice detail extraction

packages/fxa-auth-server/lib/pushbox/db.ts, packages/fxa-auth-server/lib/pushbox/index.ts, packages/fxa-auth-server/lib/routes/index.js, packages/fxa-auth-server/test/local/pushbox.js, packages/fxa-auth-server/test/remote/pushbox/db.ts, packages/fxa-content-server/app/scripts/views/elements/password-input.js, packages/fxa-content-server/app/scripts/views/mixins/password-mixin.js, packages/fxa-content-server/app/tests/spec/views/force_auth.js, packages/fxa-content-server/app/tests/spec/views/mixins/password-mixin.js, packages/fxa-payments-server/src/routes/Checkout/index.tsx
Cherry-picked commits for 240.2.
=> Release 240.2 uplift

packages/fxa-content-server/app/scripts/templates/connect_another_device.mustache, packages/fxa-content-server/app/scripts/views/connect_another_device.js, packages/fxa-content-server/app/tests/spec/views/connect_another_device.js, packages/fxa-content-server/server/lib/amplitude.js, packages/fxa-content-server/tests/server/amplitude.js
Because:
- we want to update the CAD page
This commit:
- make copy changes
- add a link to settings
- add a metrics event for link clicks
Fixes FXA-5841
=> chore(CAD): update CAD copy and add link

packages/fxa-content-server/app/scripts/templates/pair/index.mustache, packages/fxa-content-server/app/scripts/views/pair/index.js, packages/fxa-content-server/app/styles/tailwind/images.css, packages/fxa-content-server/app/tests/spec/views/pair/index.js, packages/fxa-content-server/server/lib/amplitude.js, packages/fxa-content-server/tests/server/amplitude.js
Because:
- we want to update the /pair page
This commit:
- update the copy and layout of the /pair page
Fixes FXA-5842
=> chore(pairing): update copy and layout on /pair

packages/fxa-admin-server/pm2.config.js, packages/fxa-admin-server/src/config/index.ts, packages/fxa-admin-server/src/main.ts
- We want to see traces from the admin-server
- Adds tracing to the admin-panel
Closes: FXA-5719
=> task(admin-panel): Instrument admin-server with tracing

packages/fxa-graphql-api/pm2.config.js, packages/fxa-graphql-api/src/config.ts, packages/fxa-graphql-api/src/main.ts
- We want to see traces in graphql-api
- Adds tracing to the graphql api
Closes: FXA-5723
=> task(graphql-api): Add tracing instrumentation to graphql-api

packages/fxa-event-broker/pm2.config.js, packages/fxa-event-broker/src/config.ts, packages/fxa-event-broker/src/main.ts
- We want to see traces from the event broker
- Adds tracing to the event broker
=> task(admin-panel): Instrument event-broker with tracing

packages/fxa-support-panel/pm2.config.js, packages/fxa-support-panel/src/config.ts, packages/fxa-support-panel/src/main.ts
- We want to see traces in support panel
- Adds tracing to support panel
Closes: FXA-5725
=> task(support-panel): Adds tracing to support panel

packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts, packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* It's possible to have a valid Stripe plan missing from Redis on a product.updated webhook, for example, if the plan was created before the product metadata was valid and never updated afterward.
This commit:
* Loops through any valid plans for the product on a product.updated webhook and adds them to the Redis cache if they are missing.
Closes #FXA-5967
=> fix(auth): cache missing, valid Stripe plans on product.updated webhooks

packages/fxa-auth-server/scripts/prune-tokens.ts, packages/fxa-auth-server/test/scripts/prune-tokens.js
- Metrics were getting dropped from the token pruner
- Awaits statsd.close to ensure all metrics have been flushed.
- Adds awaits to fix potential false positives in pruner tests
Closes: FXA-5964
=> FXA-5964-token-pruner-missing-error-metric

packages/fxa-auth-server/lib/senders/emails/templates/_versions.json, packages/fxa-auth-server/lib/senders/emails/templates/verifyLoginCode/en.ftl, packages/fxa-auth-server/lib/senders/emails/templates/verifyLoginCode/includes.json, packages/fxa-auth-server/lib/senders/emails/templates/verifyLoginCode/index.mjml, packages/fxa-auth-server/lib/senders/emails/templates/verifyLoginCode/index.txt, packages/fxa-auth-server/test/local/senders/emails.ts
* We have final copy for verifyLoginCode email
* Updates copy and tests for email
=> copy(fxa-auth-server): update verifyLoginCode copy

packages/fxa-content-server/app/scripts/lib/constants.js, packages/fxa-content-server/app/scripts/views/connect_another_device.js, packages/fxa-content-server/app/scripts/views/mixins/pairing-graphics-mixin.js, packages/fxa-content-server/app/tests/spec/views/connect_another_device.js
Because:
- the entrypoint param from CAD to /pair was hardcoded
This commit:
- pass the (valid) entrypoint param through to /pair
Fixes FXA-5990
=> fix(CAD): pass entrypoint thru to /pair

packages/fxa-admin-server/package.json, packages/fxa-admin-server/src/subscriptions/stripe.service.ts, packages/fxa-auth-server/lib/payments/paypal/helper.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/package.json, packages/fxa-auth-server/scripts/paypal-refund-fixer.ts, packages/fxa-shared/package.json, yarn.lock
- failing CI tests due to update in Stripe's API version
- upgrades Stripe dependency and `apiVersion` in respective files
- [FXA-5840](https://mozilla-hub.atlassian.net/browse/FXA-5840)
=> chore(deps): Update stripe to 10.7.0

packages/fxa-auth-server/lib/log.js
- We noticed a defect during checkout with paypal.
- The logger was adding a traceId to a logged response object.
- This in turn broke validation on the response object's format.
- Updates the logger so data provided to the logger isn't mutated.
Closes: FXA-6063
This needs to be patched on stage.
=> bug(auth): Don't mutate objects sent into logger

packages/fxa-settings/src/components/AppLayout/index.stories.tsx
- We want to standardize all components to the new Storybook format
- Refactor the AppLayout component to the new SB format
Closes: #14251
=> refactor(fxa-settings): update AppLayout component to new SB format

packages/fxa-auth-server/lib/log.js, packages/fxa-auth-server/test/local/log.js
- When two loggers with the same name are created, logs end up being emitted twice.
- Prevents creating loggers with the same name.
Closes: FXA-6031
=> task(auth): Prevent possibility of double emitting logs

packages/functional-tests/pages/login.ts, packages/functional-tests/pages/relier.ts, packages/functional-tests/tests/settings/misc.spec.ts, packages/functional-tests/tests/settings/password.spec.ts, packages/functional-tests/tests/signin/relyingParties.spec.ts
- Fixes our flaky playwright
- Updates the login method to handle the different login states
- Updates forgot password to go directly to reset password page
- Fixes disconnect service tests
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6105
=> fix(tests): Fix flaky functional test

packages/fxa-payments-server/public/locales/en-US/main.ftl, packages/fxa-payments-server/src/components/CouponForm/index.scss, packages/fxa-payments-server/src/components/CouponForm/index.stories.tsx, packages/fxa-payments-server/src/components/CouponForm/index.tsx, packages/fxa-payments-server/src/components/PlanDetails/index.tsx
- We want to convert to Tailwind across fxa for consistency and to improve overall maintenance
- We want to improve responsiveness and UI/UX
- We want to improve accessibility
- Replaces all CSS/SCSS with Tailwind utility classes with the exception of:
- shared styles associated with form input, CTAs, and colours
- Removes styles from the .scss file specific to the `CouponForm` component, not including what is mentioned above
- Reworks Storybook files
Closes: #13796/FXA-5625 and FXA-5845
=> refactor(payments): update CouponForm to utilize Tailwind

packages/fxa-settings/src/components/Checkbox/index.stories.tsx
-We want to standardize the Storybook format used for all fxa-settings components
- Update Checkbox component story to new SB format
Closes: #14250
=> refactor(fxa-settings): Update Checkbox component story to new SB format

packages/fxa-payments-server/src/components/PlanDetails/index.tsx
- we do not want to call preview invoice if automatic tax is not enabled
- short circuits that call if the env variable is not set to true
=> fix(payments): short Circuit Preview Invoice If Automatic Tax Not Enabled

packages/functional-tests/playwright.config.ts
Lets merge this and see if there is an improvment in flaky tests
=> Revert "fix(tests): Increase playwright ci worker to 4"

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/en.ftl, packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/index.mjml, packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/index.txt, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/senders/emails.ts, packages/fxa-payments-server/src/lib/mock-data.tsx, packages/fxa-payments-server/src/routes/Checkout/index.test.tsx, packages/fxa-payments-server/src/routes/Checkout/index.tsx
Two hotfixes for production. We will temporarily deploy 243.5 to stage, verify the fixes, and if it looks good, promote 243.5 to production.
A separate tag will be done to restore 244.0 to stage (or apply 244.1 to stage as we have some fixes planned for that train as well).
=> Train 243.5

packages/functional-tests/pages/login.ts, packages/functional-tests/tests/settings/recoveryKey.spec.ts
- We are still getting some flaky test
- I made these changes locally and got 5/5 successful runs
=> fix(tests): Playwright test tweaks

packages/fxa-admin-server/README.md
- It's good to know how gql schema generation is triggered.
- Explains what triggers gql schema generation
=> task(admin-server): Update readme with notes about gql schema generation

packages/functional-tests/tests/settings/totp.spec.ts
As part of the playwright test migration, the [totp tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/settings/two_step_auth.js) have been rewritten in this PR. The tests not covered here are:
- The reset password tests (they will be covered as part of the reset password ticket)
- The unverified session test (it will be covered as part of [this ticket](https://mozilla-hub.atlassian.net/browse/FXA-6230)
- Contains the missing sync login tests and a few verification steps from [file](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/settings/two_step_auth.js) 
- Does not contain tests related to reset password and unverified session tests. This test will be covered as part of a different PR
Closes: # …
=> test(functional): rewrite totp tests using playwright

packages/fxa-payments-server/.storybook/preview.js, packages/fxa-payments-server/src/index.scss, packages/fxa-payments-server/src/styles/tailwind.css
- We want to convert the main-content class to using Tailwind.
- Creates a custom class and converts main-content to using Tailwind.
Closes: #FXA-5628
=> refactor(payments): convert class main-content

packages/fxa-auth-server/lib/pushbox/index.ts, packages/fxa-auth-server/test/local/pushbox.js
=> Train 244 uplift 3

README.md
- Guess this was shut down
- Removes the badge
NA
=> Remove pull reminders badge

packages/fxa-payments-server/Gruntfile.js, packages/fxa-react/components/Footer/en.ftl, packages/fxa-react/components/Head/en.ftl, packages/fxa-settings/Gruntfile.js, packages/fxa-settings/src/components/en.ftl
🤞 this works in CI across the board, it did earlier
=> [DO NOT MERGE] Temp PR for contributor full CI run on #14439

packages/fxa-payments-server/src/components/CouponForm/index.tsx, packages/fxa-payments-server/src/components/PlanDetails/index.scss, packages/fxa-payments-server/src/components/PlanDetails/index.stories.tsx, packages/fxa-payments-server/src/components/PlanDetails/index.tsx, packages/fxa-payments-server/src/routes/Checkout/index.tsx, packages/fxa-payments-server/src/routes/Product/IapRoadblock/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionChangeRoadblock/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionSuccess/index.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.scss, packages/fxa-payments-server/src/styles/tailwind.css
- we are converting to Tailwind
- converts responsive design within the stylesheet of PlanDetails component to use Tailwind
Closes: [FXA-5571](https://mozilla-hub.atlassian.net/browse/FXA-5571)
Checkout
Mobile
Tablet
Desktop
Error
Mobile
Tablet
Desktop
Confirmation
Mobile
Tablet
Desktop
Roadblock
Mobile
Tablet
Desktop
Upgrade
Mobile
Tablet
Desktop
Passwordless
Mobile
Tablet
Desktop
SubscriptionSuccess
Mobile
Tablet
Desktop
=> refactor(payments-server): Convert responsive design in PlanDetails component to use Tailwind

.circleci/config.yml
- We were running an old version
- Maybe it helps with flaky test 🤷🏾‍♂️
- Updates to latest version
=> chore(deps): Update playwright docker to v1.28.0

.circleci/config.yml, packages/functional-tests/pages/products/index.ts, packages/functional-tests/pages/relier.ts, packages/functional-tests/pages/settings/layout.ts, packages/functional-tests/playwright.config.ts, packages/functional-tests/tests/settings/recoveryKey.spec.ts, packages/functional-tests/tests/settings/totp.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/coupon.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/ui-tests.spec.ts, packages/functional-tests/tests/subscription-tests/subscription.spec.ts
- A lot of subplat tests were breaking because the CPU and RAM storage were maxing out while enabling those tests to run on CircleCI (local)
- Increases the resource size from large to xlarge
- Enables all the subplat tests to run locally on CircleCi
- Fixes a few flaky tests by adding waitForLoadState() and waitForSelector() statements
Closes: #[FXA-6385](https://mozilla-hub.atlassian.net/browse/FXA-6385), [FXA-6236](https://mozilla-hub.atlassian.net/browse/FXA-6236)
=> Increase resource size and fix a few flaky tests and enable subplat tests to run on CircleCi

_scripts/firestore.sh
- Something in the 'latest' tag on the firestore image is preventing startup
- Rolls back to a known good tag
=> task(pm2): Fix firefstore startup failure

packages/fxa-auth-server/.eslintrc.json, packages/fxa-auth-server/lib/account-events.ts, packages/fxa-auth-server/lib/firestore-db.ts, packages/fxa-auth-server/lib/metrics/events.js, packages/fxa-auth-server/lib/oauth/db/mysql/index.js, packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/lib/payments/iap/apple-app-store/subscriptions.ts, packages/fxa-auth-server/lib/payments/iap/google-play/subscriptions.ts, packages/fxa-auth-server/lib/payments/iap/iap-config.ts, packages/fxa-auth-server/lib/payments/paypal/helper.ts, packages/fxa-auth-server/lib/payments/stripe-firestore.ts, packages/fxa-auth-server/lib/payments/stripe-formatter.ts, packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/payments/subscription-reminders.ts, packages/fxa-auth-server/lib/pushbox/index.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/lib/tokens/session_token.js, packages/fxa-auth-server/lib/types.ts, packages/fxa-auth-server/scripts/paypal-refund-fixer.ts, packages/fxa-auth-server/scripts/stripe-products-and-plans-to-firestore-documents/plan-language-tags-guesser.ts, packages/fxa-auth-server/scripts/stripe-products-and-plans-to-firestore-documents/stripe-products-and-plans-converter.ts, packages/fxa-auth-server/test/local/payments/iap/iap-config.js, packages/fxa-auth-server/test/local/senders/emails.ts, packages/fxa-auth-server/test/push_helper.js, packages/fxa-auth-server/test/test_server.js, packages/fxa-shared/payments/iap/util.ts, packages/fxa-shared/payments/stripe.ts, packages/fxa-shared/subscriptions/configuration/base.ts, packages/fxa-shared/test/iap/util.js
* We never properly linted TS files
* Enables the typescript recommended ruleset
Closes FXA-6137
=> chore(auth-server): turn on typescript-eslint recommended

packages/fxa-auth-server/lib/payments/paypal/client.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
* These lint issues were blocking deploy
* Ignores one issue and changes the other to an optional chain
Closes: no relevant issue
=> chore(auth-server): temporarily ignore nullish assertions

packages/fxa-admin-panel/package.json, packages/fxa-admin-server/package.json, packages/fxa-auth-server/lib/payments/paypal/client.ts, packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts, packages/fxa-auth-server/package.json, packages/fxa-content-server/package.json, packages/fxa-customs-server/package.json, packages/fxa-event-broker/package.json, packages/fxa-geodb/package.json, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/package.json, packages/fxa-profile-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json, packages/fxa-support-panel/package.json
=> Release 1.247.0

.circleci/config.yml, packages/functional-tests/package.json, packages/fxa-content-server/scripts/test-ci.sh, yarn.lock
- This might reduce flaky tests
- Increase instance size, reduce test executors
- Updates playwright test package
Closes: https://mozilla-hub.atlassian.net/browse/FXA-6507
=> fix(tests): Lower number of content-server test executors and increase instance size

packages/fxa-content-server/tests/functional/lib/helpers.js, packages/fxa-payments-server/src/components/NewUserEmailForm/en.ftl, packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx, packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.tsx, packages/fxa-payments-server/src/components/PlanDetails/index.test.tsx, packages/fxa-payments-server/src/components/PlanDetails/index.tsx, packages/fxa-payments-server/src/en.ftl, packages/fxa-payments-server/src/routes/Checkout/index.test.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx
- Attributes to FTL strings were added/removed without issuing a new ID Strings exposed to localizers are currently not in sync with source.
- Issues new IDs for the affected strings and updates associated tests
Closes: #14638
=> chore(l10n): Issue new FTL IDs to expose missing attributes

packages/fxa-content-server/tests/functional/lib/helpers.js, packages/fxa-payments-server/src/components/NewUserEmailForm/en.ftl, packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx, packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx, packages/fxa-payments-server/src/components/PaymentForm/index.tsx, packages/fxa-payments-server/src/components/PlanDetails/index.test.tsx, packages/fxa-payments-server/src/components/PlanDetails/index.tsx, packages/fxa-payments-server/src/en.ftl, packages/fxa-payments-server/src/routes/Checkout/index.test.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx
Because:
* Attributes to FTL string were added/removed without issuing a new ID Strings exposed to localizers are currently not in sync with source.
This commit:
* Issues new IDs for the affected strings and updates associated tests
Closes #14638
-
-
=> [DO NOT MERGE] chore(l10n): Issue new FTL IDs to expose missing attributes

packages/fxa-auth-server/lib/oauth/validators.js
Fixes https://mozilla-hub.atlassian.net/browse/FXA-6411
=> fix(validation): update regex for basic auth

packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Train 248 uplift 3 -> Train 248
=> Train 248 uplift 3 -> Train 248

packages/fxa-auth-server/lib/payments/stripe.ts
- Unnecessary console.log statements were included in previous work.
- Removes unnecessary console logs.
Closes: #
=> fix(payments): remove unnecessary console logs

.circleci/config.yml, AUTHORS, _scripts/compile-backend-ts-services.sh, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/package.json, packages/fxa-auth-client/package.json, packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts, packages/fxa-auth-server/package.json, packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js, packages/fxa-content-server/package.json, packages/fxa-customs-server/package.json, packages/fxa-event-broker/package.json, packages/fxa-geodb/package.json, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/package.json, packages/fxa-profile-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json, packages/fxa-support-panel/package.json
=> Release 1.248.0

packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts, packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
* We do not currently validate that a user can subscribe to a given plan when subscribing to a plan via PayPal.
* Adds a check before creating a subscription with PayPal, same as we do now for Stripe.
Closes FXA-6221
[FXA-6221]: https://mozilla-hub.atlassian.net/browse/FXA-6221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(auth-server): verify eligibility for PayPal subs

packages/fxa-shared/speed-trap/performance-factory.js
- We can see that some browsers on some platforms don't produce a valid flush time value.
- Uses a more robust check to determine if the window.performance api should be used, or if the fallback api should be used.
Closes: FXA-6600
It is difficult to test this fully, because it seems to only occur on certain browsers on certain platforms.
=> bug(content): Fix flush time metric

packages/fxa-settings/package.json
- We observe the settings server functional tests being flaky
- Applies the isolated modules option to hopefully improve memory utilization.
=> task(CI): Settings using high resources

.circleci/config.yml, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/package.json, packages/fxa-auth-server/package.json, packages/fxa-content-server/package.json, packages/fxa-customs-server/package.json, packages/fxa-event-broker/package.json, packages/fxa-geodb/package.json, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/package.json, packages/fxa-profile-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json, packages/fxa-support-panel/package.json
=> Release 1.251.0

packages/fxa-auth-server/scripts/convert-customers-to-stripe-automatic-tax/convert-customers-to-stripe-automatic-tax.ts, packages/fxa-auth-server/scripts/convert-customers-to-stripe-automatic-tax/helpers.ts, packages/fxa-auth-server/test/scripts/convert-customers-to-stripe-automatic-tax-helpers.ts, packages/fxa-auth-server/test/scripts/convert-customers-to-stripe-automatic-tax.ts
* We want to move all customers to automatic tax.
* Creates a script that automatically converts all customers to automatic tax.
Closes FXA-6579
Closes FXA-6580
=> feat(auth): convert users to stripe autotax

packages/fxa-admin-server/package.json, packages/fxa-admin-server/scripts/email-bounce.ts, packages/fxa-admin-server/scripts/gen_keys.ts, packages/fxa-admin-server/tsconfig.json
- We want to execute scripts in container
- Makes sure that scripts folder is compiled and available in dist folder.
Closes: FXA-6807
=> task(admin-server): Compile admin server scripts

.circleci/config.yml, packages/fxa-admin-server/package.json, packages/fxa-settings/src/components/Settings/PageRecentActivity/index.test.tsx
- We were hitting flakiness on some integration tests
- Increases the number integration test runners
- Decreases the resource class for integration tests
- Temporarily disabled admin-server integration tests. It appears these can conflict with other test suites, a follow up is needed here.
=> task(ci): Experiment with increased integration test runners.

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-content-server/app/scripts/lib/router.js, packages/fxa-content-server/server/lib/routes/react-app/index.js, packages/fxa-graphql-api/src/gql/account.resolver.ts, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/components/LinkRememberPassword/index.tsx, packages/fxa-settings/src/components/Settings/PageRecentActivity/index.test.tsx, packages/fxa-settings/src/models/Account.ts, packages/fxa-settings/src/models/hooks.ts, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.stories.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.test.tsx, packages/fxa-settings/src/pages/ResetPassword/CompleteResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPassword/ConfirmResetPassword/index.tsx, packages/fxa-settings/src/pages/ResetPassword/ResetPasswordConfirmed/index.tsx
Commits:
* fix(auth): errors when generating subscription email](https://github.com/mozilla/fxa/pull/14897/commits/6925d092baed4aaaf20de04be2c998941d5dc7a3)
* feat(react): Add password reset confirm page](https://github.com/mozilla/fxa/pull/14883/commits/b1dc81fbce686308deb9679a794818675e1c8595)
=> Train 252 uplift 1

packages/fxa-settings/package.json
=> Train 252 w/ uplift 2

packages/functional-tests/pages/index.ts, packages/functional-tests/pages/legal.ts, packages/functional-tests/tests/react-conversion/legal.spec.ts, packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts
- For react conversion M1 - simple routes, legal functional tests were needed
- Contains functional tests for legal, terms of service and privacy notice
- Due to an ongoing [bug](https://mozilla-hub.atlassian.net/browse/FXA-6874) for the back button on the Terms of service page not working , the step to test the back button on the test has been commented out.
Closes: #[FXA-6820](https://mozilla-hub.atlassian.net/browse/FXA-6820)
[FXA-6820]: https://mozilla-hub.atlassian.net/browse/FXA-6820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Legal tests react

packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts, packages/fxa-auth-server/lib/routes/utils/security-event.ts, packages/fxa-shared/db/models/auth/security-event.ts
- Fixes issue with auth server build
- converts `/utils/security-event` to typescript
=> fix(auth): convert record security event to ts

.circleci/run-list-parallel.sh
- We had some scenarios where we see anything written to std out
- Applies the `--ungroup` option, which allows std out to be written in real time.
- Only does this when max parallel jobs is set 1
- Prints the actual operations being run to std out for easier debugging
This part of an effort to identify and remedy flakiness as described in FXA-6781.
=> task(CI): Improve output in run-list-parallel

packages/fxa-auth-server/lib/routes/totp.js
- This fails to start auth
- Don't do this, I checked other places where we might possibly have this issue and it doesn't appear anywhere
=> fix(auth): Don't use import in js files

packages/fxa-admin-panel/package.json, packages/fxa-admin-server/package.json, packages/fxa-auth-server/package.json, packages/fxa-content-server/package.json, packages/fxa-content-server/server/lib/beta-settings.js, packages/fxa-content-server/tests/server/beta-settings.js, packages/fxa-content-server/tests/server/fixtures/server-config-index.html, packages/fxa-customs-server/package.json, packages/fxa-event-broker/package.json, packages/fxa-geodb/package.json, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/package.json, packages/fxa-profile-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json, packages/fxa-support-panel/package.json
=> Train 252 Release 1.252.4

packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/routes/validators.js, packages/fxa-payments-server/src/components/PaymentConfirmation/index.stories.tsx, packages/fxa-shared/dto/auth/payments/invoice.ts
Uplift 4 for the following changes
- https://github.com/mozilla/fxa/pull/15007
=> Train 253 - Uplift 4

packages/functional-tests/tests/react-conversion/resetPassword.spec.ts, packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
=> fix(tests): Skip flaky pw test for now

.circleci/config.yml, packages/fxa-settings/src/components/Settings/UnitRowSecondaryEmail/index.test.tsx, packages/fxa-settings/src/lib/gql.test.ts, packages/fxa-settings/src/pages/Signin/CompleteSignin/index.test.tsx, packages/fxa-settings/src/pages/Signin/index.test.tsx
- We want to add compile checks before things get caught in stage/prod pushes
- Fixes issues found in https://github.com/mozilla/fxa/pull/15045
- Except for content-server and payments, took a stab and was taking longer than expected 
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7064
We can run `yarn workspaces foreach --exclude fxa-payments-server --exclude fxa-content-server --topological-dev --verbose run compile` and get passing compile checks.
=> fix(tests): Fix compile issues in services

packages/fxa-auth-server/package.json
Follow-up to https://github.com/mozilla/fxa/pull/15040
=> fix(scripts): correct a typo

packages/fxa-payments-server/server/lib/amplitude.test.js, packages/fxa-shared/express/routing.ts, packages/fxa-shared/test/express/routing.js
Because:
* we want to record both in logs and sentry all joi validation errors that might occur when post amplitude events
This commit:
* adds logs and reports to sentry all joi validation errors
Closes #FXA-6964
To test, add code below to delete one of the properties, and then change the flow_id to something less than 64 characters in the url
=> feat(payments): report All Joi Validation Errors

docs/adr/0036-payments-standalone-configuration.md
- The subscription platform wants to provide a standalone solution for site experience configuration.
- Adds the ADR discussing various standalone configuration solutions
Closes: #FXA-7015
=> chore(docs): payments standalone configuration

packages/functional-tests/tests/react-conversion/resetPassword.spec.ts, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/package.json, packages/fxa-auth-server/package.json, packages/fxa-content-server/package.json, packages/fxa-customs-server/package.json, packages/fxa-event-broker/package.json, packages/fxa-geodb/package.json, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/package.json, packages/fxa-profile-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json
Paired with @vbudhram to correct https://github.com/mozilla/fxa/pull/15052
=> Train 254.2 merge into main 2

_dev/docker/builder/Dockerfile, _dev/docker/mono/Dockerfile
=> Train 255 uplift 2

AUTHORS, _dev/docker/builder/Dockerfile, _dev/docker/mono/Dockerfile, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/package.json, packages/fxa-auth-server/package.json, packages/fxa-content-server/package.json, packages/fxa-customs-server/package.json, packages/fxa-event-broker/package.json, packages/fxa-geodb/package.json, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/package.json, packages/fxa-profile-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json
=> Release 1.255.2

packages/fxa-auth-server/lib/push.js, packages/fxa-auth-server/test/local/push.js
- We have a hypothesis that a large number of push failures are attributed to devices that never sign in again.
- Adds Statsd field that reports when that device was last seen
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7066
=> feat(fxa-auth-server): Adds recording when the device was last seen in push

packages/fxa-auth-server/scripts/check-users.js, packages/fxa-auth-server/test/scripts/check-users.js
- We want to be able to get user stats
- Adds a script that gets users stats (mfa enabled, password match, etc)
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7148
=> feat(script): Add script to export cvs file with user stats

packages/fxa-auth-server/scripts/prune-tokens.ts
- We were documenting the pruner, and realized the help output could be better.
- Improves the help output.
=> task(auth): Improve help output for token pruner.

packages/fxa-auth-server/scripts/check-users.js, packages/fxa-auth-server/test/scripts/check-users.js
- This is failing tests in main
- Use correct export in script and test
=> fix(test): Fix config export in check-users script

docs/adr/0035-refactor-payments-frontend-with-nextjs.md, docs/adr/0036-payments-standalone-configuration-with-contentful.md
- The subscription platform wants to refactor the payments frontend.
- Adds the ADR discussing various payments frontend refactor solutions.
Closes: #FXA-7014
=> chore(docs): refactor payments frontend

packages/functional-tests/README.md, packages/functional-tests/pages/products/subscriptionManagement.ts, packages/functional-tests/playwright.config.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/coupon.spec.ts, packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts, packages/functional-tests/tests/subscription-tests/subscription.spec.ts, packages/functional-tests/tests/syncV3/fxDesktopV3ForceAuth.spec.ts, packages/functional-tests/tests/syncV3/signIn.spec.ts, packages/functional-tests/tests/syncV3/signUp.spec.ts, packages/functional-tests/tests/syncV3/syncV3EmailFirst.spec.ts, packages/functional-tests/tests/syncV3/syncV3ResetPassword.spec.ts
- The playwright tests were failing a lot recently. This PR is to fix and document everything that might make the tests more stable. This PR is an extension of the changes made to [this PR here](https://github.com/mozilla/fxa/pull/15168)
- Is an extension to the changes made [in this PR](https://github.com/mozilla/fxa/pull/15168) and to document all the best practices while writing tests.
- Enables parallelization for the sync tests and subscription platform test, which takes maximum time to run
- Enables the paypal tests
- Increases CI worker to 2
Closes: #[FXA-7214](https://mozilla-hub.atlassian.net/browse/FXA-7214) [FXA-7215](https://mozilla-hub.atlassian.net/browse/FXA-7215)
Please attach the screenshots of the changes made in case of change in …
=> Fix test flakiness for Playwright tests

packages/fxa-content-server/app/scripts/templates/post_verify/newsletters/add_newsletters.mustache, packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache, packages/fxa-content-server/app/scripts/views/mixins/email-opt-in-mixin.js, packages/fxa-content-server/app/scripts/views/post_verify/newsletters/add_newsletters.js, packages/fxa-content-server/app/tests/spec/views/mixins/email-opt-in-mixin.js
Contains a prod hotfix. I'll verify this on staging and request a push to prod.
=> train-256 <= train-256-uplift-2

packages/fxa-shared/index.ts, yarn.lock
- `auth-server` was erroring out while trying to build the `fxa-services`, Somehow the `errors.js` file in the `fxa-shared` dir was missing while building the service with the below error:
```
15|auth  | 2023-04-24T16:02:02: For help, see: https://nodejs.org/en/docs/inspector 
15|auth  | 2023-04-24T16:02:03: CRITICAL tracing.uncaughtException: Error: Cannot find module '/Users/ashrivastava/Desktop/working/fxa/node_modules/fxa-shared/dist/lib/errors.js'
15|auth  | 2023-04-24T16:02:03:     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1096:15)
15|auth  | 2023-04-24T16:02:03:     at finalizeEsmResolution (node:internal/modules/cjs/loader:1089:15)
15|auth  | 2023-04-24T16:02:03:     at resolveExports (node:internal/modules/cjs/loader:565:14)
15|auth  | 2023-04-24T16:02:03:     at …
```
=> fix auth server error

.circleci/deploy.sh
- If the image wasn't present locally, the deploy would simply skip the push.
- Checks to see if the target image tag is present on the remote docker registry.
- Pulls the target image the from the registry and then pushes it with the correct tag.
Closes: FXA-7435
=> bug(CI): Fix deploying image tag

packages/functional-tests/playwright.config.ts
-We want to catch all the stage failures at once. With this change we will create individual ticket for each issue and work on fixing it. 
-Sets the MaxFailure limit to 0
Closes: 
=> task(CI): change max failure limit for test in CI to 0

packages/functional-tests/tests/subscription-tests/coupons-ui-tests/resubscription.spec.ts
=> Disable paypal tests as paypal sandbox is taking a long time to load

packages/123done/package.json, packages/browserid-verifier/package.json, packages/db-migrations/package.json, packages/eslint-plugin-fxa/package.json, packages/fortress/package.json, packages/functional-tests/package.json, packages/fxa-admin-panel/package.json, packages/fxa-admin-server/package.json, packages/fxa-auth-client/package.json, packages/fxa-auth-server/package.json, packages/fxa-content-server/package.json, packages/fxa-customs-server/package.json, packages/fxa-dev-launcher/package.json, packages/fxa-event-broker/package.json, packages/fxa-geodb/package.json, packages/fxa-graphql-api/package.json, packages/fxa-payments-server/package.json, packages/fxa-profile-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json, packages/fxa-shared/package.json
- We now dynamically generate package versions on deployment.
- Sets all work spaces packages to version 0.0.0
This is just a follow up to FXA-7359. That PR neglected to set the versions to 0.0.0, so here it is. We will land this once we have released and verify the version patches are being applied correctly.
=> task(all): Set package.json versions to 0.0.0

.circleci/config.yml, _scripts/redis.sh, packages/123done/server.js, packages/functional-tests/scripts/start-services.sh, packages/functional-tests/scripts/test-ci.sh, packages/fxa-admin-server/src/database/database.service.ts, packages/fxa-auth-server/lib/oauth/db/redis.js, packages/fxa-auth-server/test/local/payments/stripe.js, packages/fxa-auth-server/test/local/redis.js, packages/fxa-auth-server/test/remote/db_tests.js, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-profile-server/lib/config.js, packages/fxa-profile-server/lib/server/web.js, packages/fxa-shared/db/config.ts, packages/fxa-shared/scripts/feature-flags.js, packages/fxa-shared/test/feature-flags/integration.js, packages/fxa-shared/test/scripts/feature-flags.js
- We want a POC that Auth can be added to Redis
- Configures all configs to support a redis password
- Sets the standard env for redis auth to REDIS_PASSWORD
- Creates a default redis password of 'fxa123' for local dev
- Starts redis container with --requirepass fxa123
Closes: FXA-7333
This is the minimum requirement for auth in Redis, as we are only configuring a single password. We can also configure an ACL that includes usernames with passwords and allows us to set different permissions for different operations (i.e. read vs write). This doesn't seem to be the current task though, so we are keeping it simple for now and just use one password.
Note that we can safely add this config without breaking anything. In other words, adding a password to the …
=> task(many): Investigate adding auth to redis connection

packages/fxa-payments-server/package.json, packages/fxa-react/package.json, packages/fxa-settings/package.json
- L10N files were not being copied to storybook 
- Makes sure l10n files are copied to google storage
=> task(ci): Make sure l10n files are copied to static storybook assets

.vscode/launch.json, packages/functional-tests/lib/metrics.ts, packages/functional-tests/tests/subscription-tests/subscription.spec.ts
- We have little in the way of metrics tests in our functional tests currently.
- Adds test helpers to assert our events are being recorded as expected.
Closes: FXA-7363
=> test(metrics): add functional test helpers to track metrics

packages/functional-tests/pages/index.ts, packages/functional-tests/pages/login.ts, packages/functional-tests/pages/postVerify.ts, packages/functional-tests/pages/relier.ts, packages/functional-tests/tests/oauth/signUp.spec.ts, packages/functional-tests/tests/postVerify/accountRecovery.spec.ts, packages/functional-tests/tests/postVerify/forcePasswordChange.spec.ts, packages/functional-tests/tests/postVerify/syncForcePasswordChange.spec.ts
As part of the playwright test migration, the [Post verify account recovery tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/post_verify/account_recovery.js), [Post verify force password change tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/post_verify/force_password_change.js), and [oauth sign up tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/oauth_sign_up.js) have been rewritten in this PR.
contains the the [Post verify account recovery tests](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/post_verify/account_recovery.js), [Post verify force password change …
=> test(functional): rewrite post verify account recovery/force password change and oauth sign up tests

packages/functional-tests/package.json, yarn.lock
Also removed playwright as it is no longer needed.
=> chore(deps): upgrade @playwright/test

.github/workflows/glean-probe-scraper.yml
https://github.com/mozilla/fxa/pull/15377 with a signed commit.
=> task(CI): Enable Glean probe-scraper task

.github/workflows/tag-release.yml
=> fix(release): Env var must be in same command as echo

.github/workflows/tag-release.yml
=> fix(release): Fetch all git tags

packages/fxa-auth-server/scripts/apple-transfer-users.js, packages/fxa-auth-server/scripts/transfer-users/apple.js, packages/fxa-auth-server/test/scripts/apple-transfer-users.js, packages/fxa-auth-server/test/scripts/fixtures/test_users.csv
- We need the abilty to do a mock run and see results
- Fixes a few issue where apple provider was being passed as undefined
- tweaks to csv parse to match what Pocket is doing
- Fixes the issues
=> fix(apple): Fix few bugs with migration script and add ability to mock

packages/fxa-content-server/app/scripts/lib/glean/index.ts, packages/fxa-content-server/app/scripts/views/mixins/signin-mixin.js, packages/fxa-content-server/app/scripts/views/sign_in_password.js, packages/fxa-content-server/app/tests/spec/views/sign_in_password.js
This PR includes the changes from #15510, please review that first.
=> chore(metrics): add Glean event for login success

packages/fxa-admin-panel/.rescriptsrc.js, packages/fxa-payments-server/.rescriptsrc.js, packages/fxa-react/configs/rescripts.js, packages/fxa-settings/.rescriptsrc.js
=> chore(webpack): opt out of runtime error overlay in dev

packages/fxa-content-server/app/scripts/lib/glean/index.ts, packages/fxa-content-server/app/scripts/views/sign_in_password.js, packages/fxa-content-server/app/tests/spec/views/sign_in_password.js
This PR contains the changes from https://github.com/mozilla/fxa/pull/15510, please review that first.
=> chore(metrics): add Glean login submit event

packages/fxa-content-server/app/scripts/lib/glean/index.ts, packages/fxa-content-server/app/scripts/views/sign_in_token_code.js, packages/fxa-content-server/app/tests/spec/views/sign_in_token_code.js
Note that this PR includes the commit from https://github.com/mozilla/fxa/pull/15590
=> feat(metrics): add Glean event for login confirmation submit attempt

packages/fxa-content-server/app/scripts/lib/glean/index.ts, packages/fxa-content-server/app/scripts/views/sign_in_totp_code.js, packages/fxa-content-server/app/tests/spec/lib/glean.js, packages/fxa-content-server/app/tests/spec/views/sign_in_totp_code.js
Follows https://github.com/mozilla/fxa/pull/15603
Closes FXA-7416
Closes FXA-7417
=> feat(metrics): add TOTP submit and success Glean events

.github/workflows/upload-assets-to-cdn.yml
* First attempt to upload fonts did not work because target dir was not allowed
* Trying again with existing dir
Issue #FXA-7223
=> feat(assets): Upload fonts for PDF to CDN (take 2)

packages/fxa-content-server/app/scripts/lib/glean/index.ts, packages/fxa-content-server/app/tests/spec/lib/glean.js
Because:
- some Glean events should have a hashed account uid but do not have that value populated
This commit:
- includes a sha-256 hashed account uid in the Glean metrics if the account is signed in (has a session token)
=> feat(metrics): send hashed uid in Glean metrics

packages/fxa-auth-server/lib/routes/validators.js
=> fix(config): Replace all . in hostnames not just the first one

packages/fxa-auth-server/lib/routes/linked-accounts.ts, packages/fxa-auth-server/test/local/routes/linked-accounts.js
- Updated based on requirements in https://mozilla-hub.atlassian.net/browse/FXA-8093
-
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8093
=> fix(bug): Updated third party auth and 2fa

packages/fxa-auth-server/scripts/bulk-mailer.js, packages/fxa-auth-server/scripts/check-users.js, packages/fxa-auth-server/scripts/must-reset.js, packages/fxa-auth-server/test/scripts/fixtures/check_users.csv
Because:
* We're confused every time we try to use these scripts
This commit:
* Adds some docs
=> chore(docs): Just adding some docs to the scripts

.circleci/config.yml
=> chore(ci): use large instances for functional tests

packages/db-migrations/contentful/1691700067382_fxa-7631.js
- some changes were made to the content model.
- includes the migration script from updating the content model in Contentful to match the latest version in the Tech Spec.
Closes: [FXA-7631](https://mozilla-hub.atlassian.net/browse/FXA-7631)
[FXA-7631]: https://mozilla-hub.atlassian.net/browse/FXA-7631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(contentful): Update content model

packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/third-party-auth.js
- We want this disabled for production
- Makes the rollout 0%
There is a better way to do this (ie passing in the environment into the experiment and then selecting), but for the sake of not holding the trains up lets do it the safest way.
=> chore(auth): Disable third party auth in production

packages/functional-tests/pages/login.ts
- The Oauth test for 'verified using a cached expired login' was failing on CI
- Add an extra step to clear the browser context cookies/cache
Closes: #FXA-8291
=> test(functional): add step to clear the cache for browser context

packages/fxa-auth-server/lib/devices.js
=> fix(logging): Rename id to deviceId to fix BigQuery export errors

libs/payments/cart/src/lib/cart.error.ts, libs/payments/cart/src/lib/cart.factories.ts, libs/payments/cart/src/lib/cart.manager.spec.ts, libs/payments/cart/src/lib/cart.manager.ts, libs/payments/cart/src/lib/cart.repository.ts, libs/payments/cart/src/lib/cart.service.spec.ts, libs/payments/cart/src/lib/cart.service.ts, libs/payments/cart/src/lib/cart.types.ts, libs/shared/db/mysql/account/src/lib/keysley-types.ts, packages/fxa-graphql-api/src/gql/model/cart.model.ts
* We need a starter for a cart service as described in FXA-8130
* Adds a skeleton for a cart service with the methods described in FXA-8130
Closes FXA-8130
=> feat(cart): add cart service skeleton

packages/fxa-auth-server/bin/key_server.js
=> fix(logging): Remove incorrect usage of fields for shutdown message

libs/payments/capability/.eslintrc.json, libs/payments/capability/README.md, libs/payments/capability/jest.config.ts, libs/payments/capability/package.json, libs/payments/capability/project.json, libs/payments/capability/src/index.ts, libs/payments/capability/src/lib/capability.manager.ts, libs/payments/capability/tsconfig.json, libs/payments/capability/tsconfig.lib.json, libs/payments/capability/tsconfig.spec.json, tsconfig.base.json
Closes: [FXA-8275](https://mozilla-hub.atlassian.net/browse/FXA-8275)
[FXA-8275]: https://mozilla-hub.atlassian.net/browse/FXA-8275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(libs): Create CapabilityManager library

packages/fxa-content-server/app/scripts/templates/pair/index.mustache
* "Or download" currently appears untranslated in other locales
* Adds a {{#t}} tag around the string in the mustache file to mark for translation.
Closes #15780
=> chore(l10n) - mark string for localization

.circleci/config.yml
- We want to see if anything breaks
- Setting `CI: true` changes the behavior of tsc such that warnings result in a non-zero exit code
- Turns off overrides
=> task(CI): Remove CI: false overrides

packages/fxa-shared/l10n/supportedLanguages.json
=> fix(l10n): Update enabled locales list to include Friulian (fur)

packages/fxa-payments-server/src/components/NewUserEmailForm/index.stories.tsx, packages/fxa-payments-server/src/components/PayPalButton/index.stories.tsx, packages/fxa-payments-server/src/components/PaymentProcessing/index.stories.tsx, packages/fxa-payments-server/src/routes/Product/AcceptedCards/index.stories.tsx
- We want all our Storybook components to load correctly.
- Corrects localization wrapper to fix error.
Closes: FXA-8393
=> fix(storybook): add missing AppLocalizationProvider

packages/fxa-content-server/app/scripts/views/authorization.js, packages/fxa-content-server/app/tests/spec/views/authorization.js, packages/fxa-content-server/webpack.config.js
- This might make it easier to debug
- Reverts the change
=> chore(sonoma): Revert fix for Sonoma and enable webpack development mode always

.circleci/config.yml
- Styling in auth server story books was off
- Adds the output directory for auth server email css to the workspace
Before:
(https://storage.googleapis.com/mozilla-storybooks-fxa/commits/fae8cf082e99c0187692f19aadba25c655df41f7/fxa-auth-server/index.html?path=/story/fxa-emails-layout--not-through-sync-flow)
After:
(https://storage.googleapis.com/mozilla-storybooks-fxa/commits/3e985c34d22d2edbb5a47b2029181e1d88c0a0bd/fxa-auth-server/index.html?path=/story/fxa-emails-layout--not-through-sync-flow)
=> bug(CI): Fix missing CSS in auth server storybooks

docs/adr/0040-stripe-typings.md
* We're deciding on how to handle Stripe typings going forward.
* Documents the available options, and our proposed path.
Closes FXA-8310
=> chore(adr): create adr for stripe typings

packages/fxa-auth-server/bin/key_server.js
- Corrects the Contentful config var
=> fix(auth): Correct Contentful config var

packages/fxa-auth-server/lib/routes/linked-accounts.ts, packages/fxa-auth-server/lib/routes/utils/third-party-events.ts, packages/fxa-auth-server/test/local/routes/linked-accounts.js
- We need to support security events from Apple
- Adds support for the email disabled, email enabled, consent-revoked and account delete events
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7978
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8001
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8002
=> feat(events): Add remaining Apple account security events

_scripts/l10n/prime.sh
- The comment was just some left over copy pasta
- Fixes the comment with something a bit more accurate
=> task(scripts): Update misleading comment

package.json, yarn.lock
Because:
* We want to use the latest next.
This commit:
* Updates to next 14.0.2.
=> chore: update to next 14.0.2

packages/fxa-settings/src/lib/glean/index.test.ts, packages/fxa-settings/src/lib/glean/index.ts, packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/index.tsx, packages/fxa-shared/metrics/glean/web/index.ts
Closes fxa-8024, fxa-8025, fxa-8257
=> feat(metrics): add glean pings to signin token code page

packages/fxa-auth-server/config/dev.json
=> chore(rotate): Rotate client 123Done hash

packages/functional-tests/tests/subscription-tests/subscription.spec.ts
=> disable failing subplat test

packages/fxa-react/components/LoadingSpinner/index.tsx, packages/fxa-react/lib/utils.tsx, packages/fxa-settings/src/lib/channels/firefox.ts, packages/fxa-settings/src/models/AlertBarInfo.ts, packages/fxa-settings/src/models/integrations/oauth-integration.ts, packages/fxa-settings/src/pages/Signup/container.test.tsx, packages/fxa-settings/src/pages/Signup/container.tsx, packages/fxa-settings/src/pages/Signup/index.tsx, packages/fxa-settings/src/pages/Signup/interfaces.ts, packages/fxa-shared/express/index.ts
- We want to be able to test container components
- We want to establish some patterns around testing container components
- Adds test coverage to signup's container component
- Adds additional comments since this is the first time we are testing a container and some basic patterns are being established.
Closes: FXA-8286
=> task(settings): Create tests for signup container component

packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/backendService.js, packages/fxa-auth-server/lib/customs.js, packages/fxa-auth-server/lib/payments/processing-tasks-setup.ts, packages/fxa-auth-server/lib/pool.js, packages/fxa-auth-server/lib/profile/client.js, packages/fxa-auth-server/scripts/delete-account.js, packages/fxa-auth-server/test/local/backendService.js, packages/fxa-auth-server/test/local/customs.js, packages/fxa-auth-server/test/local/db.js, packages/fxa-auth-server/test/local/pool.js, packages/fxa-auth-server/test/local/profile/client.js
=> Revert "feat(auth): Convert auth customs/profile server lib to axios, general cleanup"

packages/fxa-content-server/package.json, packages/fxa-content-server/tests/intern.js, packages/fxa-content-server/tests/lib/restmail.js, packages/fxa-content-server/tests/server/l10n-entrained.js, packages/fxa-content-server/tests/server/lang.js
- This reverts commit 5a5e8e7b49f4a75a337c404c88fa38e8ed3f5d2c.
- Adds the `test-ci.sh` file back. 
Closes: FXA-8492
=> Revert "test(functional): remove old functional intern tests and files"

packages/fxa-shared/tracing/node-tracing.ts
- auth-server wasn't starting up
- We recently updated open telemetry
- Disables file system auto integration in open telemetry
=> bug(auth): fs instrumentation was breaking auth server

packages/functional-tests/pages/products/index.ts, packages/functional-tests/pages/signupReact.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/fxa-settings/src/pages/Signup/container.test.tsx, packages/fxa-settings/src/pages/Signup/index.test.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
- We have some test coverage that needs to be added.
- Converts content server tests to either unit tests or playwright functional tests.
Closes: FXA-7316, FXA-8754
While porting these tests there were a few observations made. See comments starting with TBD, and please provide feedback on how to proceed.
=> task(settings): Port sign-up functional and unit tests.

packages/fxa-settings/src/components/Settings/FlowRecoveryKeyDownload/index.test.tsx
=> fix(tests): wait longer for a lazily loaded component

packages/fxa-settings/src/lib/gql.ts
Because:
* We send a query up for the initial metrics data which requires a valid session token to receive data back. We shouldn't send this network request if the user does not have a session token
This commit:
* Cancels the network request and sets 'isSignedIn' to false when no session token is available
relates to FXA-8817, but Dan stopped Sentry from reporting this in #16217
---
I originally did this as a `skip` in `useInitialMetricsQueryState` and wrote the `isSignedIn` status there as well. However, I couldn’t get `metricsLoading` to be falsey, so it was just an endless spinner. Placing this in `gql.ts` lets us return a `data` object while cancelling the network request - I kind of like the idea of keeping the state modifications related to `isSignedIn` in one file as much as …
=> fix(react): Do not perform initial GQL query if no session token

packages/fxa-auth-server/tsconfig.json
=> fix(scripts): Add delete-account script to TS compile list

packages/functional-tests/.eslintrc.js, packages/functional-tests/package.json, packages/functional-tests/tests/oauth/oauthPermissions.spec.ts, packages/functional-tests/tests/oauth/oauthPromptNone.spec.ts, packages/functional-tests/tests/postVerify/forcePasswordChange.spec.ts, packages/functional-tests/tests/postVerify/syncForcePasswordChange.spec.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/functional-tests/tests/signin/signinCached.spec.ts, packages/functional-tests/tests/syncV3/fxDesktopHandshake.spec.ts, packages/functional-tests/tests/syncV3/settings.spec.ts, yarn.lock
- test failures are being suppressed and are reported with status 'unknown' in CircleCI
- removes instances of 'console.error' which causes the invalid status
- adds basic ESLint to functional-tests to prevent additions of 'console.error'
Closes: # [FXA-8773](https://mozilla-hub.atlassian.net/browse/FXA-8773)
- [Lint failure example](https://app.circleci.com/pipelines/github/mozilla/fxa/46792/workflows/508ec67a-2dac-42ea-ac39-3dab2799acff/jobs/477840?invite=true#step-103-16393_56)
- [Test failure example](https://app.circleci.com/pipelines/github/mozilla/fxa/46793/workflows/bceeb156-513d-43fb-aa13-97ce856e6 …
=> fix(functional-tests): report unknown terminal state 'system-err'

packages/fxa-auth-server/scripts/delete-account.ts
Because:
* The delete script needs a proper import for the Paypal client which requires TS compilation.
This commit:
* Does the minimum changes to the script to have it compile properly.
=> fix(auth): update delete account to TS for proper imports

apps/payments/next/app/[offeringId]/error/page.tsx, apps/payments/next/app/_lib/stubs.ts
- We want to start building out pages in preparation for M3.
- Introduces a fully accessible desktop version for the error page.
- Hackathon demo.
- Includes starter and backlog tasks for error page.
Closes N/A (Hackathon demo)
=> feat(next): Hackathon error page

backstage/firestore.resources.yaml, backstage/memcached.resources.yaml, backstage/mozilla-accounts.system.yaml, backstage/mysql.resources.yaml, backstage/redis.resources.yaml, catalog-info.yaml, packages/123done/backstage.yaml, packages/browserid-verifier/backstage.yaml, packages/fxa-admin-panel/backstage.yaml, packages/fxa-admin-server/backstage.yaml, packages/fxa-auth-server/backstage.yaml, packages/fxa-content-server/backstage.yaml, packages/fxa-customs-server/backstage.yaml, packages/fxa-event-broker/backstage.yaml, packages/fxa-graphql-api/backstage.yaml, packages/fxa-payments-server/backstage.yaml, packages/fxa-profile-server/backstage.yaml, packages/fxa-settings/backstage.yaml
Because:
* We want to test Backstage for software catalog uses.
This commit:
* Adds a catalog-info.yaml file to the root of the repo, with individual entries for each package.
=> feat(backstage): setup initial backstage metadata

packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-webchannel-v1.js, packages/fxa-content-server/app/tests/spec/models/auth_brokers/oauth-webchannel-v1.js
- In order to support FF desktop using `oauth_webchannel_v1` auth broker, we need to add some broker methods to send the login data (session token info) during different stages of the login flow
- Added broker methods `beforeSignUpConfirmationPoll` `afterCompleteSignInWithCode` `afterSignIn` `afterSignUpConfirmationPoll`, similar to our Sync broker methods
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7530
This flow can not be fully tested in mobile because they need to be updated to support the new web channel events. Currently, mobile clients ignore unknown events.
To test in desktop:
1. Run the latest Nightly, set `identity.fxaccounts.oauth.enabled=true` and `identity.fxaccounts.contextParam=oauth_webchannel_v1`
2. Enable these configs …
=> feat(oauth): Update oauth webchannel auth broker to support desktop

packages/fxa-content-server/app/scripts/lib/auth-errors.js, packages/fxa-content-server/app/scripts/lib/vat.js, packages/fxa-content-server/app/scripts/views/index.js, packages/fxa-content-server/app/tests/spec/views/index.js, packages/fxa-settings/src/components/Settings/PageSecondaryEmailAdd/en.ftl, packages/fxa-settings/src/components/Settings/PageSecondaryEmailAdd/index.test.tsx, packages/fxa-settings/src/components/Settings/PageSecondaryEmailAdd/index.tsx, packages/fxa-shared/email/helpers.ts
Reverts mozilla/fxa#16219
Fixes https://mozilla-hub.atlassian.net/browse/FXA-9057
=> Revert "Reject Relay email masks on signup"

packages/fxa-auth-server/lib/error.js, packages/fxa-auth-server/lib/monitoring.js, packages/fxa-auth-server/lib/sentry.js
- After adding tracing and upgrading sentry it appears errors can propagate in other ways.
- Moves the ignoreError check into the error module
- Runs the ignoreError check in the filterEvents function that runs on before send.
=> bug(auth): Fix issue where errors are being reported that should be repressed.

packages/fxa-auth-server/scripts/delete-account.ts
- We are missing some delete events
- Adds the delete activity event when we use the delete script, we previously mocked the event
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8999
I'm not 100% sure if this will fix the issue, but from my code audit it seems like this was the only path where we didn't emit anything.
Log statements from running script
```
INFO delete-account-script.activityEvent: {"uid":"e6cc998b08a0454db520aacb50af8d10","event":"account.deleted"}
DEBUG delete-account-script.Notifier.publish: {"success":true,"data":{"ResponseMetadata":{"RequestId":"2d3a3e8f-6a38-423c-b299-ab92c80c9a3b"},"MessageId":"3e39a1d0-6d2e-4fbf-b235-72eccb3ac7ee"}}
DEBUG delete-account-script.AccountDeleteManager.deleteFirestoreCustomer: {"uid":"e6cc998b08a0454db520aacb50af8d10"}
```
=> fix(bug): Update delete script to emit delete activity event

packages/fxa-settings/src/lib/cache.ts, packages/fxa-settings/src/pages/Signin/container.test.tsx, packages/fxa-settings/src/pages/Signin/container.tsx, packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signin/index.tsx, packages/fxa-settings/src/pages/Signin/interfaces.ts, packages/fxa-settings/src/pages/Signin/mocks.tsx, packages/fxa-settings/src/pages/Signup/ConfirmSignupCode/index.test.tsx, packages/fxa-settings/src/pages/Signup/container.test.tsx, packages/fxa-settings/src/pages/mocks.ts
Because:
* We needed more unit test coverage
This commit:
* Adds said coverage, makes a couple tweaks discovered along the way
closes FXA-9072
=> chore(test): Add test coverage for Signin container and additional coverage for Signin

packages/fxa-settings/src/components/ThirdPartyAuth/en.ftl, packages/fxa-settings/src/components/ThirdPartyAuth/index.tsx, packages/fxa-settings/src/pages/Signin/index.test.tsx, packages/fxa-settings/src/pages/Signup/index.tsx
- The styles in Backbone version and React version are slightly off
- Updates React version to match Backbone version
- Uses `or` text, updates text color, increases text size
- Changes hover button color
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9060
Updated:
=> fix(css): Update third party auth css

packages/fxa-auth-server/package.json, yarn.lock
- Guess we don't use this
- Removes the `acorn` dependency
=> chore(deps): Remove unused dependency `acorn`

configs/nimbus.yaml
- We're trying to integrate with Nimbus and unblock SRE
- Lands the initial yaml
Closes: FXA-9124
=> feat(integrations): Land initial Nimbus FML

packages/fxa-payments-server/package.json
- Optimize build-css for production (see #16357)
=> perf(payments): Optimize tailwind output

libs/payments/stripe/src/index.ts, libs/payments/stripe/src/lib/stripe.client.ts, libs/payments/stripe/src/lib/stripe.manager.ts
- creates StripeClient instance
Closes: FXA-8890, FXA-9023
=> feat(payments-stripe): Create StripeClient and StripeManager

libs/payments/paypal/src/lib/paypal.manager.ts
- creates PayPalManager
Closes: FXA-8930
=> feat(payments-paypal): Create PayPalManager

packages/fxa-settings/src/models/Account.ts
=> Revert "task(settings): Restore use of gql query for resetPassword"

libs/payments/capability/src/lib/capability.manager.spec.ts, libs/payments/capability/src/lib/capability.manager.ts, packages/fxa-auth-server/lib/payments/capability.ts, packages/fxa-auth-server/test/local/payments/capability.js, packages/fxa-auth-server/test/remote/subscription_tests.js
- [Sentry](https://mozilla.sentry.io/issues/4596022042/?environment=stage&project=6231056&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=2) reported a mismatch due to the order of capabilities
- returns clients and sorted capabilities
=> fix(payments): Return sorted capabilities

apps/payments/next/.env.example, apps/payments/next/app/[offeringId]/checkout/page.tsx, apps/payments/next/app/api/auth/[...nextauth]/route.ts, apps/payments/next/app/api/hello/route.ts, apps/payments/next/auth.config.ts, apps/payments/next/auth.ts, package.json, packages/fxa-auth-server/config/dev.json, packages/fxa-content-server/server/lib/configuration.js, yarn.lock
- Need to be able to authenticate with FxA
- Add NextAuth to facilitate promp and no prompt signin with FxA
Closes: #FXA-7522
=> feat(next): add NextAuth 

libs/payments/paypal/src/lib/paypal.service.ts
- creates PayPalService
Closes: FXA-8931
=> feat(payments-paypal): Create PayPalService

package.json, yarn.lock
Because:
* We want the instrumentation fix.
This commit:
* Updates next to 14.1.1.
=> chore: update Next to 14.1.1

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/test/local/payments/stripe.js
=> Revert "fix(auth): Revise getPaymentProvider"

.circleci/config.yml, _dev/docker/docker-compose.yml, _scripts/mysql.sh, packages/fxa-auth-server/test/oauth/db/index.js
=> chore(mysql): Upgrade to MySQL 8.0.31

packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts, packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js, packages/fxa-shared/payments/stripe-firestore.ts
- Stripe webhook events are reporting FirestoreCustomerNotFound exceptions to Sentry, for customers who have already been deleted.
- When processing a Stripe webhook event, on any FirestoreStripeError where the customerId is included in the error, check if the FxA Account for that customer still exists. If it does not, the error can be ignored, else throw the error.
Closes: #FXA-9181
=> fix(auth): handle stripe events for deleted accounts

packages/fxa-auth-server/scripts/delete-unverified-accounts.ts
Because:
* We want to enqueue tasks to Google Cloud Tasks faster.
This commit:
* Queues all enqueue tasks to a concurrent queue that is rate limited per p-queue.
=> feat: add rate limiting concurrency to enqueue script

packages/fxa-shared/db/config.ts
=> chore(config): Rename customs Redis password config

packages/fxa-auth-server/scripts/delete-unverified-accounts.ts
Because:
* We want to auto-scale our queueing.
This commit:
* Adds a scaling policy to the delete script.
=> feat: add rate limit scaling to delete script

packages/fxa-auth-server/scripts/delete-unverified-accounts.ts
Because:
* We want to use the non-grpc client for higher concurrency on sending tasks to Google Cloud Tasks.
* We want to avoid db lookups when sending tasks to Google Cloud Tasks.
This commit:
* Swaps the client used to send tasks to Google Cloud Tasks to the fallback task client.
* Removes the db lookups when sending tasks to Google Cloud Tasks.
=> feat(auth): use fallback task client with direct queries

packages/fxa-auth-server/scripts/delete-unverified-accounts.ts
Because:
* We want to avoid long running streams that may run into timeouts in holding open result queries.
* Waiting on empty may take a very long time depending on timeouts in the queue so we'd prefer to only wait for the queue to empty.
This commit:
* Switches to loading all db results into memory.
* Switches to waiting on the queue to empty.
=> fix: avoid long running mysql stream or waiting on all queue items

packages/functional-tests/lib/fixtures/standard.ts, packages/functional-tests/pages/layout.ts, packages/functional-tests/playwright.config.ts, packages/functional-tests/tests/misc/authClientV2.spec.ts, packages/functional-tests/tests/oauth/oauthPermissions.spec.ts, packages/functional-tests/tests/oauth/oauthPromptNone.spec.ts, packages/functional-tests/tests/oauth/signUp.spec.ts, packages/functional-tests/tests/oauth/signinTokenCode.spec.ts, packages/functional-tests/tests/oauth/syncSignIn.spec.ts, packages/functional-tests/tests/oauth/totp.spec.ts, packages/functional-tests/tests/postVerify/forcePasswordChange.spec.ts, packages/functional-tests/tests/postVerify/syncForcePasswordChange.spec.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/functional-tests/tests/settings/changeEmail.spec.ts, packages/functional-tests/tests/settings/fxaStatus.spec.ts, packages/functional-tests/tests/settings/totp.spec.ts, packages/functional-tests/tests/signin/connectAnotherDevice.spec.ts, packages/functional-tests/tests/signin/signIn.spec.ts, packages/functional-tests/tests/signin/signinBlocked.spec.ts, packages/functional-tests/tests/signin/signinCached.spec.ts, packages/functional-tests/tests/syncV3/fxDesktopHandshake.spec.ts, packages/functional-tests/tests/syncV3/settings.spec.ts, packages/functional-tests/tests/syncV3/signinCached.spec.ts, packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/test/remote/account_destroy_tests.js
- We should always require a session to delete an account
- Updates the route options to require it
Closes: https://mozilla-hub.atlassian.net/browse/FXA-8467
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9096
=> fix(delete): Update delete account route

packages/fxa-auth-server/scripts/check-users.js, packages/fxa-auth-server/test/client/index.js, packages/fxa-auth-server/test/scripts/check-users.js
- I removed the script because I thought it wasn't used, we still use it
- Adds the script back and updates the check password function 
Closes:https://mozilla-hub.atlassian.net/browse/FXA-9319
=> chore(scripts): Add back check-users script

packages/functional-tests/pages/login.ts, packages/functional-tests/pages/products/index.ts, packages/functional-tests/pages/settings/layout.ts, packages/functional-tests/pages/signupReact.ts, packages/functional-tests/tests/misc/keyStretchingV2.spec.ts, packages/functional-tests/tests/oauth/signin.spec.ts, packages/functional-tests/tests/oauth/syncSignIn.spec.ts, packages/functional-tests/tests/oauth/webchannel.spec.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/functional-tests/tests/settings/avatar.spec.ts, packages/functional-tests/tests/settings/changeEmail.spec.ts, packages/functional-tests/tests/signin/connectAnotherDevice.spec.ts, packages/functional-tests/tests/signin/relyingParties.spec.ts, packages/functional-tests/tests/syncV3/signUpWithCWTS.spec.ts
* We want to promote stability and sustainability in the functional-tests
* Refactors creation and cleanup of email into a test fixture
* Refactors to use page object with auto-retrying assertions and built-in locators (causes cascading changes into other tests):
* keyStretchingV2.spec.ts
* signin.spec.ts
* syncSignIn.spec.ts
* webchannel.spec.ts
* avatar.spec.ts
* changeEmail.spec.ts
* connectAnotherDevice.spec.ts
* relyingParties.spec.ts
* signUpWithCWTS.ts
* Removes the pre-fill tests since they are generating false positives and a decision on whether the feature will be implemented has not yet been made (see [FXA-8794](https://mozilla-hub.atlassian.net/browse/FXA-8794))
* 'Visits the privacy policy links save information upon return'
* 'Visits the terms of service links save …
=> test(functional-tests): audit react conversion signup tests

apps/payments/next/pm2.config.js, apps/payments/next/project.json
=> feat(l10n): Add localization scripts/targets to payments-next

.circleci/config.yml, libs/shared/cloud-tasks/src/lib/account-tasks.ts, libs/shared/cloud-tasks/src/lib/account-tasks.types.ts, libs/shared/cloud-tasks/src/lib/cloud-tasks.ts, packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/lib/routes/cloud-tasks.ts, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/scripts/clean-up-partial-account-customer.ts, packages/fxa-auth-server/scripts/cleanup-partial-firestore-customers.ts, packages/fxa-auth-server/scripts/delete-account.ts, packages/fxa-auth-server/scripts/delete-unverified-accounts.ts, packages/fxa-auth-server/test/local/account-delete.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/local/routes/cloud-tasks.js, packages/fxa-auth-server/test/local/routes/validators.js, packages/fxa-auth-server/test/remote/account_create_tests.js
Revert to fix an issue in stage deployment (https://mozilla.sentry.io/issues/5107020061/)
Reverts mozilla/fxa#16626
=> Revert "task(auth): Have auth-server use cloud-tasks nx lib "

.circleci/config.yml, libs/shared/cloud-tasks/src/lib/account-tasks.ts, libs/shared/cloud-tasks/src/lib/account-tasks.types.ts, libs/shared/cloud-tasks/src/lib/cloud-tasks.ts, packages/fxa-auth-server/bin/key_server.js, packages/fxa-auth-server/lib/account-delete.ts, packages/fxa-auth-server/lib/metricsCache.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/lib/routes/cloud-tasks.ts, packages/fxa-auth-server/lib/routes/validators.js, packages/fxa-auth-server/scripts/clean-up-partial-account-customer.ts, packages/fxa-auth-server/scripts/cleanup-partial-firestore-customers.ts, packages/fxa-auth-server/scripts/delete-account.ts, packages/fxa-auth-server/scripts/delete-unverified-accounts.ts, packages/fxa-auth-server/test/local/account-delete.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/local/routes/cloud-tasks.js, packages/fxa-auth-server/test/local/routes/validators.js, packages/fxa-auth-server/test/remote/account_create_tests.js, packages/fxa-shared/db/redis.ts
- Requiring `@fxa/shared/cloud-tasks` from `validators.js` was failing to resolve the module and stopping auth-server from starting up
- Exports `ReasonForDeletion` in  cloud-tasks.ts so other js files like `validator.js` can access it
- Updates `delete-account.ts` to reference `@fxa/shared/cloud-tasks` instead of the relative path
Closes: FXA-9373
This can be validated locally by building (nx build fxa-auth-server) then going to `packages/fxa-auth-server/dist/packages/fxa-auth-server` and running `NODE_ENV=dev node bin/key_server.js`. With the changes the server will start. Without these changes the server will faiil to start with the following error:
```
Cannot …
```
=> bug(auth): Fix module resolution for @fxa/shared/cloud-tasks

packages/fxa-settings/src/lib/metrics.ts, packages/fxa-settings/src/pages/Signin/SigninUnblock/container.tsx, packages/fxa-settings/src/pages/Signin/container.test.tsx, packages/fxa-settings/src/pages/Signin/container.tsx, packages/fxa-settings/src/pages/Signin/mocks.tsx, packages/fxa-settings/src/pages/mocks.tsx
=> fix(metrics): Pass metricsContext to gql signin mutation

packages/fxa-content-server/app/robots.txt
- We don't want to be crawled by [common crawler](https://commoncrawl.org/)
- Adds common crawler to robots.txt
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9300
=> chore(robots): Update robots.txt to add CCBot

libs/payments/stripe/src/lib/stripe.client.spec.ts, libs/payments/stripe/src/lib/stripe.client.ts
* We need some additional methods in Stripe client
* Adds those methods
Closes FXA-9025
=> feat(payments-stripe): add methods to stripe client

libs/payments/cart/src/lib/cart.types.ts, libs/payments/ui/src/lib/actions/getCart.ts, libs/payments/ui/src/lib/actions/updateCart.ts, libs/payments/ui/src/lib/nestapp/app.module.ts, libs/payments/ui/src/lib/nestapp/app.ts, libs/payments/ui/src/lib/nestapp/nextjs-actions.service.ts, libs/payments/ui/src/lib/nestapp/validators/GetCartActionArgs.ts, libs/payments/ui/src/lib/nestapp/validators/UpdateCartActionArgs.ts
* We need a server action to fetch the cart and update the cart
* Adds a simple server action to fetch the cart and another to update the cart
Closes FXA-8900
Closes FXA-8902
=> feat(payments-ui): add getCart & updateCart server actions

packages/fxa-settings/src/pages/Signin/container.test.tsx
- This is broken in main
- Fixes the test
=> fix(tests): Update broken test

packages/fxa-payments-server/server/lib/amplitude.test.js, packages/fxa-payments-server/server/lib/routes/legal-docs.test.js, packages/fxa-payments-server/server/lib/server.js, packages/fxa-payments-server/src/components/CouponForm/index.test.tsx, packages/fxa-payments-server/src/components/PaymentConfirmation/index.test.tsx, packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.test.tsx, packages/fxa-payments-server/src/components/PlanDetails/index.test.tsx, packages/fxa-payments-server/src/lib/apiClient.test.ts, packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.test.tsx
- We want to make sure our code is properly linted and passing Circle CI.
- Fixes lint errors causing failures in Circle CI tests for payments.
Found in PRs: https://github.com/mozilla/fxa/pull/16630 and https://github.com/mozilla/fxa/pull/16676
=> fix(lint): correct lint errors causing CI failures in payments

packages/fxa-settings/src/components/App/index.test.tsx, packages/fxa-settings/src/components/App/index.tsx, packages/fxa-settings/src/lib/glean/index.ts
- There are certain scenarios where might ignore metrics prefs
- Standard how we perform this check
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9403
Targetting this as a point release
=> fix(metrics): Updated how we enable/check metrics in React app

libs/payments/eligibility/src/lib/eligibility.manager.spec.ts
- cleans up unnecessary mocks in tests
=> fix(payments-eligibility): Clean up tests

apps/payments/next/next.config.js, libs/payments/cart/src/lib/cart.error.ts, libs/payments/cart/src/lib/cart.service.spec.ts, libs/payments/cart/src/lib/cart.service.ts, libs/payments/cart/src/lib/checkout.error.ts, libs/payments/cart/src/lib/checkout.service.spec.ts, libs/payments/cart/src/lib/checkout.service.ts, libs/payments/paypal/src/index.ts, libs/payments/paypal/src/lib/paypal.error.ts, libs/payments/paypal/src/lib/paypal.manager.in.spec.ts, libs/payments/paypal/src/lib/paypal.manager.ts, libs/payments/paypal/src/lib/paypalCustomer/paypalCustomer.manager.in.spec.ts, libs/payments/paypal/src/lib/paypalCustomer/paypalCustomer.manager.ts, libs/payments/paypal/src/lib/paypalCustomer/paypalCustomer.repository.in.spec.ts, libs/payments/paypal/src/lib/paypalCustomer/paypalCustomer.repository.ts, libs/payments/stripe/src/index.ts, libs/payments/stripe/src/lib/accountCustomer/accountCustomer.manager.ts, libs/payments/stripe/src/lib/factories/payment-intent.factory.ts, libs/payments/stripe/src/lib/factories/payment-method.factory.ts, libs/payments/stripe/src/lib/factories/promotion-code.factory.ts, libs/payments/stripe/src/lib/stripe.client.ts, libs/payments/stripe/src/lib/stripe.client.types.ts, libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.manager.ts, libs/payments/stripe/src/lib/stripe.service.ts
* We want a service to manage checkout behaviors
* Adds a checkout service
Closes FXA-9020
Closes FXA-8943
Closes FXA-9022
Closes FXA-8941
=> feat(checkout): add checkout service with stripe and paypal

packages/fxa-settings/src/pages/Signin/SigninUnblock/container.tsx, packages/fxa-settings/src/pages/Signin/container.tsx
- We added the sign in unblock page after V2 support was added
- Adds the V2 upgrade routine to signin unblock
- Extracts functions in Singin/container for reuse
Closes: FXA-9353
We don't have any container tests for signin unblock at the time of this PR, however, the code used here is under in the main sign in page. There is a pending issue, FXA-9503, to create container tests for sign in unblock container.
=> task(settings): Add key stretching v2 support for signin unblock page

packages/fxa-auth-server/lib/routes/recovery-key.js, packages/fxa-auth-server/test/local/routes/recovery-keys.js
- We want to give users a better warning message when reseting their password if they have connected a sync device
- Updates our recovery key exists route to return `estimatedSyncDeviceCount`, this route was chosen instead of `/account/profile` because account profile is not used during the password reset flow but recovery key exist is
Closes: https://mozilla-hub.atlassian.net/browse/FXA-7430
=> feat(sync): Return estimated sync devices in recovery key exist route

packages/fxa-auth-server/lib/routes/password.ts
Because:
* Having nested functions modify closure state is hard to reason about.
This commit:
* Updates the nested functions to return values instead of modifying closure state.
=> refactor: untangle password change function

packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js, packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-webchannel-v1.js
- Pulling in Prs from https://github.com/mozilla/fxa/pull/16486/ and https://github.com/mozilla/fxa/pull/16798
- Fixes a bug with CAD and oauth_webchannel_v1 broker
- Updates mysql command to use mysqladmin to check that it has been started
Authored by @tarikeshaq, making this PR to get commit signed and run all tests
=> Update CAD with oauth_webchannel_v1

packages/fxa-settings/package.json, yarn.lock
=> Revert "chore(deps-dev): bump storybook-addon-rtl from 0.5.0 to 1.0.0"

packages/functional-tests/lib/ci-reporter.ts
- we want some visibility on the fixme rate (a subset of skip rate) in CI
- adds count information for passed, failed and skipped (with fixme) tests to the output of the CIReporter
Closes: # FXA-9044
CI Output Example:
The use of this CI output primarily acts as a sanity for the fixme trend we have calculated and graphed in [FxA Functional Test Suite Metrics](https://docs.google.com/spreadsheets/d/1qKwxsSI2RNo-qKZflETtBbyZ9b0ZUB_id2SL17_MmYo/edit#gid=1830381531)
=> test(functional-tests): add pass/fail/skip/fixme counts to CIReporter

apps/payments/next/.env.development, apps/payments/next/.env.production, apps/payments/next/config/index.ts, libs/payments/ui/src/lib/nestapp/app.module.ts, yarn.lock
- Stay up to date with latest next-auth/authjs beta releases
- Updates to latest beta version
- Removes env vars no longer needed
Closes: #FXA-9543
=> chore(next): update next-auth beta to latest

.circleci/config.yml
=> Revert "Disable NX_DAEMON when building the container"

_dev/docker/mono/build.sh
=> Revert "Update build.sh"

packages/fxa-settings/package.json, yarn.lock
=> Revert "chore(deps): bump @react-pdf/renderer from 3.1.12 to 3.4.4"

packages/functional-tests/tests/subscription-tests/subscription.spec.ts
- We are aiming to make stage and prod deployments all green.
- Updates test to follow new standards introduced in [PR#16739](https://github.com/mozilla/fxa/pull/16739) and remove event duplication to improve flakiness.
Closes FXA-8447
=> fix(functional-test): update failing new user test with metrics

packages/fxa-admin-panel/src/components/PageAccountSearch/Account/index.test.tsx, packages/fxa-admin-panel/src/components/PageAccountSearch/Account/index.tsx, packages/fxa-admin-panel/src/components/PageAccountSearch/index.gql.ts, packages/fxa-admin-server/src/gql/account/account.resolver.ts, packages/fxa-admin-server/src/gql/model/account.model.ts, packages/fxa-admin-server/src/graphql.ts, packages/fxa-admin-server/src/schema.gql
- We want to make debugging easier
- Exposes key stretch version to an admin panel user
Just a quick change that I made while testing locally. Thought it'd be nice to have available to everyone.
=> task(admin): Expose key stretch version on account

libs/shared/contentful/src/index.ts
=> fix(shared-contentful): Update index to add page-content-for-offering

packages/fxa-auth-server/lib/routes/utils/third-party-events.ts, packages/fxa-auth-server/test/local/routes/linked-accounts.js
- the link account record could have already been deleted, so we wouldn't be able to take any action on a third party security event
- Adds a check that account exists before processing the event
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9220
=> fix(account): add a check if link account exists before revoking session

libs/payments/cart/src/lib/cart.service.spec.ts, libs/payments/cart/src/lib/cart.service.ts, libs/payments/cart/src/lib/cart.types.ts, libs/payments/stripe/src/index.ts, libs/payments/stripe/src/lib/factories/total-discount-amounts.factory.ts, libs/payments/stripe/src/lib/factories/total-tax-amounts.factory.ts, libs/payments/stripe/src/lib/factories/upcoming-invoice.factory.ts, libs/payments/stripe/src/lib/stripe.factories.ts, libs/payments/stripe/src/lib/stripe.manager.spec.ts, libs/payments/stripe/src/lib/stripe.types.ts, libs/payments/stripe/src/lib/util/stripeInvoiceToFirstInvoicePreviewDTO.spec.ts, libs/payments/stripe/src/lib/util/stripeInvoiceToFirstInvoicePreviewDTO.ts, yarn.lock
- TypeError: Cannot read properties of undefined (reading 'tax_rate')
- `discount` now deprecated
=> fix(payments): Revise formatting of upcoming invoice tax and discounts

packages/functional-tests/pages/signinReact.ts, packages/functional-tests/tests/react-conversion/changeEmail.spec.ts, packages/fxa-auth-server/test/local/routes/cloud-scheduler.js, packages/fxa-graphql-api/src/gql/dto/input/sign-in.ts, packages/fxa-settings/src/components/Settings/DropDownAvatarMenu/index.test.tsx, packages/fxa-settings/src/components/Settings/DropDownAvatarMenu/index.tsx, packages/fxa-settings/src/lib/gql.ts, packages/fxa-settings/src/pages/Signin/SigninRecoveryCode/container.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.test.tsx, packages/fxa-settings/src/pages/Signin/SigninTokenCode/container.tsx, packages/fxa-settings/src/pages/Signin/SigninUnblock/container.tsx, packages/fxa-settings/src/pages/Signin/container.test.tsx, packages/fxa-settings/src/pages/Signin/container.tsx, packages/fxa-settings/src/pages/Signin/index.tsx, packages/fxa-settings/src/pages/Signin/mocks.tsx, packages/fxa-settings/src/pages/Signin/utils.ts
- We want to land only the React component changes and not functional test changes for full prod rollout
- Various fixes to components
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9684
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9696
If you checkout https://github.com/mozilla/fxa/pull/16989 and run functional tests, this should all pass.
=> fix(functional-tests): Fix React signin components for full prod rollout

.devcontainer/README.md, .devcontainer/devcontainer.json, .yarnrc.yml
Because:
* We want a consistent development environment for all developers.
This commit:
* Adds a devcontainer configuration for Docker in Docker development.
=> feat: add devcontainer for Docker in Docker development

packages/fxa-auth-server/config/dev.json, packages/fxa-content-server/server/config/local.json-dist, packages/fxa-content-server/server/lib/configuration.js
- the development server should use the same behaviour as the staging server
- updates the development server to match the staging server
=> Update client ID for Thunderbird to match stage server.

packages/functional-tests/tests/settings/changeEmailBlocked.spec.ts
- changeEmailBlocked tests were failing when run on CI
- Add assertions to make sure correct state is awaited
=> fix(functional-test): changeEmailBlocked tests failing on main

packages/fxa-settings/src/pages/InlineTotpSetup/container.test.tsx, packages/fxa-settings/src/pages/InlineTotpSetup/container.tsx
- When 2FA is required, and user did not have 2FA enabled yet, they would get bounced to the signup page
- Allows isSessionVerified to settle before redirecting
- Allows totpStatus to settle before redirecting
- Puts redirect logic in separate useEffect to consolidate redirect logic
- Removes that catch block that was using an undefined error state to control user flow
- Cleans up tests:
- Made mocks accessible
- Made sure implementations were defined in setMocks
- Use mockReturnValue where appropriate
- Make sure waitFor is used as needed
Closes:  FXA-9848
The issue here was that the code did allow the call that checked for totpStatus to settle. As a result, the code would createTotp when it did not need to. An error would ensue, and the catch block …
=> bug(settings): Fix unnecessary bounce to signup page

packages/functional-tests/playwright.config.ts, packages/functional-tests/tests/oauth/webchannel.spec.ts, packages/functional-tests/tests/react-conversion/oauthSignin.spec.ts, packages/functional-tests/tests/react-conversion/signinTotp.spec.ts, packages/functional-tests/tests/react-conversion/signup.spec.ts, packages/functional-tests/tests/resetPassword/resetPasswordWithCode/oauthResetPasswordSyncMobile.spec.ts, packages/functional-tests/tests/settings/changeEmail.spec.ts
* Some functional tests were failing for the tag
* Add assertions in the failing tests
Closes: #FXA-9909
=> fix(functional-tests): fix test failures on train 287.1 tag

packages/functional-tests/tests/oauth/signinTokenCode.spec.ts
* This test was failing on the latest tag
* Marks test as fixme to not block the tag
=> fix(functional-tests): Mark Oauth SigninTokenCode tests with fixme

packages/functional-tests/tests/react-conversion/oauthSignin.spec.ts, packages/functional-tests/tests/react-conversion/signInRelyingParties.spec.ts
- Tests are no longer flaking or failing
- re-enables them
Closes: # FXA-9518
=> fix(functional-tests): smoke test failures on train 283

packages/fxa-admin-server/src/subscriptions/subscriptions.service.ts
- Admin panel rejects with an error if it can't find a Stripe invoice.
- Stripe typically does not allow invoice deletion, and therefore this error is usually only seen on Stage after Stripe cleans up test data.
- Catches the error on invoice failure, and if its due to missing invoice, log the error, and assume customer subscription data is stale, and simply return void.
Closes: #FXA-9051
=> fix(admin): handle no invoice error

package.json, packages/fxa-content-server/server/lib/routes/react-app/index.js, packages/fxa-settings/config/webpack.config.js, packages/fxa-settings/package.json
- We want to roll out react signin to all users
- Sets react signin routes to full prod rollout
Closes: #FXA-9427
=> feat(react): Enable react signin at 100%

_scripts/adb-reverse.sh, _scripts/check-ports.sh, _scripts/ports.txt
- Script was outdated
- More ports are needed to get this working with android emulator on localhost.
- Adds more ports
Closes: FXA-10075
=> task(scripts): Update adb-reverse script

packages/functional-tests/tests/react-conversion/oauthSignin.spec.ts
- We want to minimize disruption to CI workflows
- Adds a fixme annotation to a failing test
Relates to: #FXA-10102
=> chore(functional-tests): add fixme to verified account with cached login, no email confirmation required

packages/fxa-settings/src/pages/Signup/index.tsx
=> fix(sync): Don't await the `firefox.fxaLogin`

_scripts/ports.txt
- Two more ports were need to debug android
- Adds 8290 for graphql
- Adds 3000 for react app
=> bug(scripts): Not all ports were listed

.github/workflows/docker.yml
=> fix(docker): Specify fxa-mono Dockerfile

.circleci/config.yml
- To optimize the execution time for the Smoke tests in Stage and Prod, we need to add Parallelization for our CircleCI `smoke-tests`  job. And subsequently use the ‘Merge reports’ job to be able to merge and create html reports for it 
- Adds `parallelism` to `smoke-test` job
- Add the existing 'Merge reports' job for smoke tests.
Closes: FXA-10224
=> chore(functional_tests): add parallelism to smoke tests

.circleci/config.yml
- Add `filters` for html reports workflow for smoke tests to be picked up by the Pipeline.
-
=> chore(config): add filters for smoke tests workflow

packages/functional-tests/playwright.config.ts
- We want to add `reportSlowTest` in the TestConfig so that all the slow test files are listed down in the CircleCi
- adds `reportSlowTest` in the `playwright.config.ts` file
- Since `reportSlowTest` works only with a dot, line or list reporter, we added a dot reporter for CircleCi.
Closes: FXA-9751
=> chore(functional_tests): add reportSlowTest in the config file

_scripts/create-version-json.sh
=> feat(scripts): Support Github Actions environment variables for version.json

.github/workflows/docker.yml, .github/workflows/tag-release.yml
=> fix(docker): Call docker build after tagging a release

libs/payments/cart/src/lib/checkout.service.spec.ts, libs/payments/cart/src/lib/checkout.service.ts, libs/shared/cms/src/lib/product-configuration.manager.spec.ts, libs/shared/metrics/statsd/src/lib/statsd.provider.ts
- Resolves/removes comments in the CheckoutService for statsd by implementing statsd
Closes: FXA-10168
=> feat(payments-cart): Increment statsd counters

.circleci/config.yml, packages/fxa-content-server/server/config/local.json-dist, packages/fxa-content-server/server/lib/configuration.js, packages/fxa-content-server/server/lib/routes/react-app/index.js, packages/fxa-content-server/server/lib/routes/react-app/types.ts, packages/fxa-content-server/tests/server/routes/react-app.js
* We are preparing to enable react version of email first route
* Adds feature flag
Closes: #FXA-8638
Related SRE PR: https://github.com/mozilla-it/webservices-infra/pull/2562
=> feat(content): Set up feature flag for email first routes

packages/fxa-settings/scripts/build.js
- CDN URL was incorrect
- Corrects URL
Closes: 
=> bug(settings): Fix typo in cdn url

packages/fxa-settings/scripts/build.js
- The path to folder where settings CDN resources were held was incorrect
- Fixes the path
=> bug(settings): CDN path was incorrect

packages/fxa-content-server/server/lib/csp/blocking.js
- Calls to our cdn were getting blocked
- Adds CDN URL to connect-src rule group
=> bug(content): Add cdn to csp for connect-src

packages/fxa-auth-server/lib/routes/utils/third-party-events.ts
- This was causing some sentry errors, most likely from trying to get account after it was deleted
- Adds some additional logging and doesn't throw if account isn't found
Closes: https://mozilla-hub.atlassian.net/browse/FXA-9764
=> fix(logs): Adds some additional logging for security events and catch exceptions

.github/workflows/docker.yml
=> fix(docker): Use correct variable for git tag

packages/db-migrations/databases/fxa/patches/patch-153-154.sql, packages/db-migrations/databases/fxa/patches/patch-154-153.sql, packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-server/docs/swagger/security-events-api.ts, packages/fxa-auth-server/lib/db/index.js, packages/fxa-auth-server/lib/routes/security-events.js, packages/fxa-auth-server/test/client/api.js, packages/fxa-auth-server/test/client/index.js, packages/fxa-auth-server/test/local/routes/security-events.js, packages/fxa-auth-server/test/mocks.js, packages/fxa-auth-server/test/remote/db_tests.js, packages/fxa-auth-server/test/remote/security_events.js, packages/fxa-content-server/app/scripts/lib/fxa-client.js, packages/fxa-content-server/app/scripts/models/account.js, packages/fxa-content-server/app/tests/spec/lib/fxa-client.js, packages/fxa-content-server/app/tests/spec/models/account.js, packages/fxa-shared/db/models/auth/base-auth.ts, packages/fxa-shared/db/models/auth/security-event.ts
Because:
* We no longer support this endpoint
This commit:
* Removes the endpoint
=> feat(secevents): remove DELETE endpoint

libs/payments/cart/src/lib/cart.service.spec.ts, libs/payments/cart/src/lib/cart.service.ts, libs/payments/customer/src/lib/error.ts, libs/payments/customer/src/lib/invoice.manager.spec.ts, libs/payments/customer/src/lib/invoice.manager.ts, libs/payments/customer/src/lib/util/assertPromotionCodeActive.spec.ts, libs/payments/customer/src/lib/util/assertPromotionCodeActive.ts, libs/payments/ui/src/lib/actions/updateCart.ts, libs/payments/ui/src/lib/client/components/CouponForm/index.tsx
- validates the coupon code when applying in CouponForm component
- If code is valid, add coupon code to cart
- If code is not valid, display appropriate error message in CouponForm component
Closes: FXA-7834
Expired
Invalid
=> feat(libs/payments): Validate coupon code

packages/fxa-settings/src/components/FormVerifyTotp/en.ftl
remove stray word in ftl string
=> remove stray word in ftl string

packages/fxa-admin-server/src/app.module.ts, packages/fxa-admin-server/src/main.ts
- Debugging admin-server startup
- Adds some more logs
- Cranks up nestjs default log levels
=> Add more logs about timing

libs/payments/ui/src/lib/server/components/Details/index.tsx
- updates the component to get `discountEnd` and `discountType` from the passed in invoice
=> fix(payments-next): Revise Details component

package.json, yarn.lock
- Rolling back to `sentry:nextjs@8`, so we can compare timings
-
=> Train 293 uplift 4.2

packages/fxa-settings/src/components/ResetPasswordWarning/en.ftl
- brand term should be lowercase
- update brand term in string
=> brand term lowercase

_dev/docker/ci/Dockerfile, _dev/docker/mono/Dockerfile
- Docker job in github complained about this (e.g. https://github.com/mozilla/fxa/actions/runs/11060387844)
- changes as to AS, which is stylistically better
=> chore(_dev): Fix annotation warnings

package.json, yarn.lock
=> chore: bump next to 14.2.14

packages/fxa-admin-server/src/scripts/restore-rk.mjs
- We'd like to avoid having to rerun the main query
- Adds ability to run of users file
- Generate users file
=> task(admin): Support reading from flat file in restore-rk.mjs

packages/fxa-settings/src/lib/hooks/useNavigateWithQuery/index.tsx
- This should not have been committed
- Remove stray console log and debugger statement
=> remove stray console log and debugger

packages/fxa-admin-server/src/scripts/restore-rk.mjs
- We want to conduct a couple final sanity checks
- Adds a check that looks for restored keys that should not have been restored due to password reset or recovery key delete operation
- Adds sanity check that compares DB snapshot before remediation. 
=> task(admin): Add sanity checks to restore-rk script

packages/fxa-auth-server/lib/db.ts, packages/fxa-shared/db/models/auth/session-token.ts
Because:
* We want to see db changes in graphs to identify odd behavior.
This commit:
* Adds metrics to most db methods with tags indiciating result.
=> feat: add metrics to db methods

packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-webchannel-v1.js, packages/fxa-content-server/app/tests/spec/models/auth_brokers/oauth-webchannel-v1.js
Because:
* We are not sending this command for desktop oauth, meaning our sync merge warning is not shown from email-first
This commit:
* Roughly lifts beforeSignIn from fx-sync-channel and applies to oauth-webchannel-v1 if that auth_broker is used and the UA matches FF desktop
fixes FXA-10597
---
You can test this following instructions in dev-launcher for oauth desktop on latest Nightly. Throw a debugger or a console log to see `command` and `data` [here](https://github.com/mozilla/fxa/blob/093aaac33e71ababaa979d29b5db95b2345b2ad7/packages/fxa-content-server/app/scripts/lib/channels/senders/web-channel.js#L29), and see that before this patch, nothing is sent on email-first when signing into an account through oauth desktop and then signing into a different account through oauth desktop. …
=> fix(sync): Send can_link_account web channel message for oauth desktop on email-first

packages/fxa-settings/src/pages/Signin/SigninUnblock/container.tsx
- We had reports that some users were getting logged out of sync after signing in.
- We had FF logs that indicated this occurred when `keyFetchToken` was provided but `unwrapBKey` was not.
- We found a couple Sentry reports indicating the aforementioned state, and they all were coming through SignInUnblock.
- Makes sure the response from `beginSignIn` is augmented with the correct `unwrapBKey`
- Handles possibility that the request to `getCredentialStatus` fails. 
Closes: FXA-10641
This is a quick patch for a train-295 release. There will be another patch to follow that'll add some test coverage and deal with any potential merge conflicts on main.
=> Uplift fix missing unwrap bkey

packages/fxa-auth-server/scripts/delete-inactive-accounts/get-inactive-account-uids.ts
Because:
- the script to get the inactive account uids list was only using the accounts table for the initial set of accounts
This script:
- reduces the number of accounts in the initial set by using the timestamps in the emails, securityEvents, and sessionTokens table
=> chore(scripts): update inactive uid script for more sql

packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/container.tsx
- When  `oauth_webchannel_v1` is used for fxa_desktop_context, the user was not signed into sync after a password reset.
- The redirect uri provided to sync was being navigated to, and this is not a valid URI for navigation.
- Makes sure the `firefox.fxaOAuthLogin` web channel message is sent.
- Makes sure the redirect provided by sync isn't navigated to.
Closes: FXA-10710
I never saw an error message in nightly like the ticket suggested, but it certainly failed. For me the browser would just hang after clicking finish, and the user would never be signed into sync. 
The main issue seemed to be that the URI provided by sync was being redirected to directly. I'm …
=> bug(settings): Fix sync signin after password reset

libs/accounts/recovery-phone/src/lib/recovery-phone.errors.ts, libs/accounts/recovery-phone/src/lib/recovery-phone.manager.in.spec.ts, libs/accounts/recovery-phone/src/lib/recovery-phone.manager.ts, libs/accounts/recovery-phone/src/lib/recovery-phone.repository.ts
- We want to get able to retrieve and remove recovery phone numbers
- Adds the additional methods to the RecoveryPhoneManager lib
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10344
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10442
=> feat(phone): Add `getConfirmedPhoneNumber` and `removePhoneNumber` functions

packages/fxa-auth-server/scripts/delete-inactive-accounts/enqueue-inactive-account-deletions.ts, packages/fxa-auth-server/scripts/delete-inactive-accounts/get-inactive-account-uids.ts, packages/fxa-auth-server/scripts/delete-inactive-accounts/lib.ts
Because:
- we need a script to find inactive accounts and start the deletion process by sending a notification email
This commit:
- scaffolds the script without enqueuing any emails
=> feat(scripts): add script to find and notifiy inactive accounts

libs/accounts/recovery-phone/src/lib/recovery-phone.service.spec.ts, libs/accounts/recovery-phone/src/lib/recovery-phone.service.ts
- We want to add ability to send codes via sms
- Adds a sendCode method to the recovery phone service
Closes:FXA-10351
=> task(recovery-phone): Add sendCode method

.github/workflows/after-circle-ci.yml
=> fix(actions): Try fixing "A mapping was not expected" error

packages/fxa-auth-server/lib/metrics/glean/index.ts, packages/fxa-auth-server/lib/metrics/glean/server_events.ts, packages/fxa-auth-server/lib/routes/recovery-phone.ts, packages/fxa-auth-server/test/local/metrics/glean.ts, packages/fxa-auth-server/test/local/routes/recovery-phone.js, packages/fxa-auth-server/test/remote/recovery_phone_tests.js, packages/fxa-shared/metrics/glean/fxa-backend-metrics.yaml
- We need a route for confirming recovery phone setup
- Adds a route /recovery-phone/confirm
- Adds glean metrics
- Adds tests
Closes: FXA-10356
=> task(auth): Setup /recovery-phone/confirm

packages/fxa-auth-server/lib/routes/recovery-phone.ts, packages/fxa-auth-server/test/local/routes/recovery-phone.js
- We want to send a code to a recovery phone to verify it
- Adds a new route `/recovery-phone/send_code`
Closes: https://mozilla-hub.atlassian.net/browse/FXA-10357
@dschom Tagged you for review since this will use some of the Glean metrics in https://github.com/mozilla/fxa/pull/18067
=> feat(phone): Add route for /recovery-phone/send_code

apps/payments/next/auth.ts
Clarifying a comment, and removing a commented-outline of code
=> clean up comment

libs/payments/cart/src/lib/cart.service.spec.ts, libs/payments/cart/src/lib/cart.service.ts
- We want to easily consume our custom errors and apply them as cart error reason IDs
- Creates a home for which to do that transformation, and wraps many of our existing methods in this wrapper.
Closes FXA-10627
=> feat(payments-cart): cart error handling wrapper

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/senders/email.js
Options from https://www.nodemailer.com/smtp/#connection-options
=> feat(email): Expose configuration for SMTP timeouts

packages/functional-tests/tests/oauth/signinTokenCode.spec.ts, packages/fxa-auth-server/config/dev.json
This fixes a playwright test as well as reverts an auth-server dev.json config update.
=> fix(tests): Revert recent auth-server dev.json updates, fix playwright test

packages/fxa-auth-server/lib/payments/capability.ts
Because:
* We want to be able to write a routine to automatically check all plan eligibility permutations.
This commit:
* Refactors getPlanEligibility to have a second method that can be passed arbitrary subscribed stripe/IAP plans and check their eligibility.
=> feat: refactor elibility check for use without uid

packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountFirstWarning/en.ftl
Fix incorrect ftl id (duplicate)
=> fix duplicate ftl id added for FXA-10636

packages/fxa-auth-server/lib/routes/totp.js
- Evidently we can't reference `@fxa/` here...
- Uses the relative path
=> task(auth): Fix prod build error

packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountSecondWarning/en.ftl, packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountSecondWarning/index.mjml, packages/fxa-auth-server/lib/senders/emails/templates/inactiveAccountSecondWarning/index.txt
Noticed by a localizer. (Thanks whoever you are!)
=> fix(l10n): Fix l10n placeholder reference

packages/fxa-auth-server/test/mail_helper.js
- We want to easily access sms codes sent
- Updates mailer_helper to print the codes only once
Closes: https://mozilla-hub.atlassian.net/browse/FXA-11042
=> fix(testing): Update mail helper to print sms codes

packages/functional-tests/lib/testAccountTracker.ts, packages/functional-tests/tests/oauth/oauthPermissionsSignup.spec.ts, packages/functional-tests/tests/oauth/signin.spec.ts, packages/functional-tests/tests/react-conversion/oauthSignin.spec.ts, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/lib/routes/session.js, packages/fxa-auth-server/test/client/api.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/remote/account_create_tests.js, packages/fxa-auth-server/test/remote/account_destroy_tests.js, packages/fxa-auth-server/test/remote/email_validity_tests.js
- We want to fix some broken test tear downs
-  Fixes issues tearing down accounts
=> Fix broken destroy tests

packages/fxa-settings/src/pages/ResetPassword/ResetPasswordWithRecoveryKeyVerified/container.tsx
- Sync is special and not like any other RP, we don't want to take users to the `reset_password_verified` where it would tell them to 'Continue to Sync'.
- We don't want users to be stuck on a RP page that has the redirect url `urn:ietf:wg:oauth:2.0:oob:oauth-redirect-webchannel` which goes no where.
- Since this is a niche code path and we don't have a good story now how to handle these flows, lets go straight to settings.
Closes: FXA-11073
Without this change, the user lands on this page after an unload event and the redirect button does not take them anywhere.
=> fix(settings) - Navigate to settings in a password-reset/sync flow

packages/fxa-auth-server/lib/payments/processing-tasks-setup.ts, packages/fxa-auth-server/scripts/cleanup-old-carts.ts, packages/fxa-auth-server/scripts/cleanup-old-carts/cleanup-old-carts.ts, packages/fxa-auth-server/test/scripts/cleanup-old-carts.ts
- We want to be able to clean up and/or anonymize old carts from the DB
- Adds a cart anonymization script
Closes FXA-10478
=> feat(auth): cleanup old carts script

packages/fxa-auth-server/tsconfig.json
- We keep getting burned by '@fxa/' requires & imports
- Targets js files in tsconfig
=> task(auth): Have typescript target more files.

packages/fxa-auth-server/lib/routes/recovery-phone.ts
* Body text should be added to SMS in addition to code
* Fix the formatted message retrieval
Closes: #FXA-11151
=> fix(auth): SMS message did not include body text

packages/db-migrations/bin/patcher.mjs
- The current version of this script only logs errors. It would be nice to include informational logging for better debugging and testing.
- Adds informational logging for the db-migrations patcher script.
Closes: # N/A
=> feat(db-migrations): improved logging in patcher.mjs

packages/fxa-settings/src/pages/Signin/SigninRecoveryChoice/container.tsx
* ftlMsgResolver and navigateWithQuery useEffect dependencies were causing re-renders
* Simplify the data fetching in useEffect and extract navigation resulting from data or errors
* Omit ftlMsgResolver from dependency array
Closes: #FXA-11153
=> fix(settings): Fix infinite re-render on SigninRecoveryChoice page

packages/fxa-admin-panel/src/components/PageAccountDelete/index.tsx
=> fix a typo

apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/error/page.tsx, apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/needs_input/page.tsx, apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/processing/page.tsx, apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/start/page.tsx, apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/success/page.tsx, apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(successLayout)/success/page.tsx, apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(upgradeLayout)/error/page.tsx, apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(upgradeLayout)/needs_input/page.tsx, apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(upgradeLayout)/processing/page.tsx, apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(upgradeLayout)/start/page.tsx
* Browser and SEO best practices include using header title and descriptions for pages on our site.
* Adds header titles and descriptions to the subplat web pages
Closes: #FXA-8226
=> feat(next): Add metadata titles and descriptions to checkout pages

apps/payments/next/app/[locale]/[offeringId]/[interval]/landing/route.ts, libs/payments/events/src/lib/emitter.factories.ts, libs/payments/events/src/lib/emitter.service.spec.ts, libs/payments/events/src/lib/emitter.service.ts, libs/payments/events/src/lib/emitter.types.ts, libs/payments/ui/src/lib/nestapp/app.ts
- Add statsd metrics to track rollout redirects
- Add new statsd metric sp3_rollout
Closes: FXA-10969
=> feat(next): record rollout statsd metrics

packages/fxa-settings/src/components/Settings/FlowSetupRecoveryPhoneConfirmCode/en.ftl, packages/fxa-settings/src/components/Settings/FlowSetupRecoveryPhoneConfirmCode/index.test.tsx, packages/fxa-settings/src/components/Settings/FlowSetupRecoveryPhoneConfirmCode/index.tsx, packages/fxa-settings/src/components/Settings/PageRecoveryPhoneSetup/index.test.tsx, packages/fxa-settings/src/components/Settings/SubRow/en.ftl, packages/fxa-settings/src/components/Settings/SubRow/index.test.tsx, packages/fxa-settings/src/components/Settings/SubRow/index.tsx
* Content updates were recommended
* Updates a few strings and l10n
`six-digit` updated to `6-digit`
`easier` changed to `easiest`
=> fix(settings): Update a few content strings for recovery phone

packages/fxa-settings/src/components/Settings/FlowSetupRecoveryPhoneSubmitNumber/index.stories.tsx, packages/fxa-settings/src/lib/glean/index.test.ts, packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/container.tsx, packages/fxa-settings/src/pages/Signin/SigninRecoveryPhone/en.ftl, packages/fxa-shared/metrics/glean/web/index.ts
* We want to show a message to users on successful signin
* Adds alert bar message with Glean metric
Closes: FXA-11204
=> fix(settings): Add recovery phone signin success message

libs/payments/iap/.eslintrc.json, libs/payments/iap/.swcrc, libs/payments/iap/README.md, libs/payments/iap/jest.config.ts, libs/payments/iap/package.json, libs/payments/iap/project.json, libs/payments/iap/src/index.ts, libs/payments/iap/src/lib/apple/apple-iap.client.config.ts, libs/payments/iap/src/lib/apple/apple-iap.client.spec.ts, libs/payments/iap/src/lib/apple/apple-iap.client.ts, libs/payments/iap/src/lib/apple/apple-iap.error.ts, libs/payments/iap/src/lib/constants.ts, libs/payments/iap/src/lib/google/google-iap.client.config.ts, libs/payments/iap/src/lib/google/google-iap.client.spec.ts, libs/payments/iap/src/lib/google/google-iap.client.ts, libs/payments/iap/src/lib/google/google-iap.error.ts, libs/payments/iap/src/lib/iap-purchase.repository.spec.ts, libs/payments/iap/src/lib/iap-purchase.repository.ts, libs/payments/iap/src/lib/types.ts, libs/payments/iap/tsconfig.json, libs/payments/iap/tsconfig.lib.json, libs/payments/iap/tsconfig.spec.json
- We want a centralized place for housing IAP interactions
- Creates a new IAP library for interacting with Google and Apple IAP
Closes FXA-7836
=> feat(payments-iap): create payments-iap library

packages/fxa-settings/src/pages/Index/container.tsx
Because:
* We are not allowing users to sign up with a different account
This commit:
* Deletes the 'email' query param before email-first navigation
fixes FXA-11318
=> fix(react): Remove 'email' param before email-first navigation

libs/shared/metrics/glean/src/registry/subplat-backend-metrics.yaml
* We have an incomplete subplat-backend-metrics.yaml file
This commit:
* Adds references to the data review ticket for the fields in the glean schema
Closes: N/A
=> task(data-review): Update data review glean yaml file

libs/payments/ui/src/lib/client/components/Header/en.ftl, libs/payments/ui/src/lib/client/components/Header/index.tsx
- FTL file unintentionally skipped l10n review due to the file initially being mislabled and not flagged for review. As an unfortunate consequence some mistakes were introduced that needed fixing.
- Fixes l10n issues with the Header component
Closes: FXA-11365
=> fix(next): fix header component ftl

libs/payments/iap/src/lib/google/constants.ts, libs/payments/iap/src/lib/google/google-iap-purchase.manager.spec.ts, libs/payments/iap/src/lib/google/google-iap-purchase.manager.ts, libs/payments/iap/src/lib/google/google-iap-purchase.repository.spec.ts, libs/payments/iap/src/lib/google/google-iap-store.manager.ts, libs/payments/iap/src/lib/google/google-iap.client.config.ts, libs/payments/iap/src/lib/google/google-iap.client.spec.ts, libs/payments/iap/src/lib/google/google-iap.client.ts, libs/payments/iap/src/lib/google/google-iap.error.ts, libs/payments/iap/src/lib/google/subscription-purchase.ts
- We want to be able to interact with google iap through libraries and apps
- Ports legacy google IAP code over to our new libraries setup
Closes FXA-10714
=> feat(iap): create GoogleIapPurchaseManager

packages/fxa-settings/src/pages/Index/container.test.tsx, packages/fxa-settings/src/pages/Signin/container.test.tsx
* We want to test the container
* Add unit test coverage for the index container
Closes: FXA-11316
=> tests(settings): Add container tests for react index page

libs/payments/cart/src/lib/cart.service.spec.ts, libs/payments/cart/src/lib/cart.service.ts, libs/payments/cart/src/lib/checkout.service.spec.ts
- there was a build issue
-  swaps mozlogger for winston logger and resolved the failing build
Closes: N/A
=> fix(payments-next): fix build issue with logger on cart service

packages/fxa-auth-server/lib/db.ts
- we want to avoid missing any logging around account deletions
- replaces trace with an info level logger call in deleteAccount() 
Closes: FXA-11278
Would also love a review on this commit/PR style to make sure I'm matching the existing guidelines, thanks!
=> task(auth-server): use log.info instead of .trace for deleteAccount()

packages/fxa-settings/src/components/Settings/UnitRowTwoStepAuth/en.ftl, packages/fxa-settings/src/components/Settings/UnitRowTwoStepAuth/index.tsx
* We want to link to a new article
* Update link in 2FA row
Closes: FXA-10918
=> task(settings): Update SUMO link about 2FA value

packages/fxa-admin-server/package.json, packages/fxa-auth-client/package.json, packages/fxa-auth-server/package.json, packages/fxa-content-server/package.json, packages/fxa-event-broker/package.json, packages/fxa-graphql-api/package.json, packages/fxa-shared/package.json
=> Revert "chore(deps): bump the npm_and_yarn group across 7 directories with 2 updates"

.circleci/config.yml, packages/functional-tests/lib/sms.ts, packages/functional-tests/tests/settings/recoveryPhone.spec.ts
* Recovery phone tests were not running
* Enable the tests
* Update configuration for testing on CircleCI
Closes: FXA-11462
=> task(tests): Enable recovery phone functional tests

.github/dependabot.yml
* Unrelated dependencies were bundled in PRs
* Ignored deps were not ignored when bundled with other deps
* We want to ignore mailparser updates
* Update config
=> fix(deps): Update dependabot config to prevent unrelated grouping

packages/fxa-auth-server/package.json, yarn.lock
This reverts commit a252194e75bbbb45348f19e56077622ee016a974.
=> Revert "chore(deps): bump web-push from 3.4.4 to 3.6.7"

packages/fxa-auth-server/scripts/delete-inactive-accounts/enqueue-inactive-account-deletions.ts
The inactive account cloud task enqueuing script wasn't closing statsd to flush the remaining metrics before terminating.
=> fix(scripts): wait for statsd.close on inactive accts script

docs/adr/0045-testing-updates-and-recommendations.md
- There are areas we can invest in to improve the developer experience with testing and standards.
- Adds an ADR with a few potential paths to improve that experience!
=> docs(adr): Testing Standards and Experience

.github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/glean-probe-scraper.yml, .github/workflows/l10n-gettext-extract.yml, .github/workflows/pull-legal-docs.yml, .github/workflows/tag-release.yml, .github/workflows/upload-assets-to-cdn.yml, .github/workflows/zizmor.yml
Zizmor is a Static Analysis tool for GitHub Actions https://woodruffw.github.io/zizmor/usage/#use-in-github-actions
Ran Zizmor locally to fix up any open issues on existing GitHub Actions. There are some caching features which were disabled based on https://woodruffw.github.io/zizmor/audits/#cache-poisoning
=> feat(zizmor): Add Zizmor Static Analysis

packages/functional-tests/README.md, packages/functional-tests/lib/fixtures/standard.ts
- Traces are sometimes blank on failed functional tests, specifically for `sync sign in` tests.
- Captures the second browser's trace for sync sign-in functional tests and saves to a unique location
Closes: FXA-11526
Here is a "failed" test in Circle that uploaded a new trace `syncTrace.zip`
=> fix(functional-tests): empty trace for failed syncBrowserPages tests

libs/accounts/rate-limit/.eslintrc.json, libs/accounts/rate-limit/README.md, libs/accounts/rate-limit/jest.config.ts, libs/accounts/rate-limit/package.json, libs/accounts/rate-limit/project.json, libs/accounts/rate-limit/src/index.ts, libs/accounts/rate-limit/src/lib/config.ts, libs/accounts/rate-limit/src/lib/error.ts, libs/accounts/rate-limit/src/lib/models.ts, libs/accounts/rate-limit/src/lib/rate-limit.in.spec.ts, libs/accounts/rate-limit/src/lib/rate-limit.spec.ts, libs/accounts/rate-limit/src/lib/rate-limit.ts, libs/accounts/rate-limit/src/lib/util.ts, libs/accounts/rate-limit/tsconfig.json, libs/accounts/rate-limit/tsconfig.lib.json, libs/accounts/rate-limit/tsconfig.spec.json, tsconfig.base.json
- We want to explore replacing the customs server
- Creates a lib that could be used to replace customs server
Closes: FXA-11396
This is just a POC. Looking for feedback on basic implementation.
=> poc(customs): Simplified customs approach.

packages/fxa-auth-server/test/scripts/bulk-mailer.js
Reverts mozilla/fxa#18812
Unfortunately the changes broke a couple tests.
=> Revert "fix(feat): Shell command built from environment values"

libs/payments/ui/src/lib/client/components/CouponForm/index.tsx
- After applying an invalid coupon code, the font color of the input value remained red while changing it and the error message remained.
- ensures the border and font color of the coupon code are no longer red when updated
- removes the error message when the input value is changed
Closes: FXA-11570
=> fix(payments-ui): Fix CouponForm when invalid

.github/workflows/tag-release.yml
- Tag release worlflow failed during execution
- Removed additional whitespace in variable
=> fix(ci): tag-release failed during git config

.github/workflows/tag-release.yml
=> Revert "fix(ci): tag-release failed during git config"

packages/fxa-settings/public/index.html
- Lighthouse suggested doing this. 
- The main bundle is already deferred, and this script is included before, so this should be acceptable.
- Adds the 'defer' attribute to the `query-fix` script
Closes: FXA-11615
If this doesn't help, we might have to consider how to include this in the main bundle; however, there were some reasons why we wanted this to load first...
=> task(settings): Add 'defer' to query fix script

libs/accounts/rate-limit/src/lib/rate-limit.in.spec.ts, libs/accounts/rate-limit/src/lib/rate-limit.spec.ts, libs/accounts/rate-limit/src/lib/rate-limit.ts
- We want to track blocks
- We want to track unblocks
- Adds statsd metrics for blocks
- Adds statsd metrics for unblocks
Closes: FXA-11611
The `auth-server` also metrics, and during rollout of the new rate limiting approach we will continue to support the previous metrics format. The metrics added here are still useful, however, and are structured in slightly better manner. As we phase out the old customs server, these metrics can eventually take over. It's also convenient that these metrics are emitted from the library itself. This way if we want to use this service elsewhere, we don't have to recreate the metrics.
=> task(libs/rate-limit): Add metrics

packages/fxa-admin-server/src/gql/cart.module.ts
- A recent change added a new dependency to the CartManager.
- Adds the missing dependency to CartManager.
=> fix(admin-server): add missing cartmanager deps

libs/payments/cart/src/lib/cart.service.ts
Because:
* the getCart action has a p95 latency of 1.3 seconds
This commit:
* reworks the promise resolution parallelization to allow the promises to resolve concurrently
* adjusts the actions service to return unresolved promises where possible, to prevent double-resolution of the promises
Closes #FXA-11756
=> feat(payments-next): improve getCart response time

packages/fxa-auth-server/lib/routes/password.ts
=> polish(auth): Remove stray console.log

nx.json, package.json, yarn.lock
- We want to cache our CI steps for better performance
- Enables Nx caching against our own bucket
- Uses GCS's S3 compat for now
Closes: FXA-9413
=> chore(nx): custom nx cache

packages/functional-tests/tests/oauth/loginHint.spec.ts, packages/fxa-content-server/app/scripts/models/reliers/oauth.js, packages/fxa-settings/src/models/integrations/data/data.ts, packages/fxa-settings/src/models/pages/signin/oauth-query-params.ts
Maybe bad timing with github issues, doesn't appear that new build got triggered when I did point release. Gonna try to manually merge branch and then retag.
=> Train 312 uplift patch to retrigger builds

libs/accounts/rate-limit/README.md, libs/accounts/rate-limit/src/lib/config.ts, libs/accounts/rate-limit/src/lib/models.ts, libs/accounts/rate-limit/src/lib/rate-limit.in.spec.ts, libs/accounts/rate-limit/src/lib/rate-limit.spec.ts, packages/fxa-auth-server/config/rate-limit-rules.txt, packages/fxa-auth-server/lib/customs.js, packages/fxa-auth-server/lib/routes/account.ts, packages/fxa-auth-server/lib/routes/emails.js, packages/fxa-auth-server/lib/routes/password.ts, packages/fxa-auth-server/lib/routes/session.js, packages/fxa-auth-server/lib/routes/totp.js, packages/fxa-auth-server/lib/routes/utils/signin.js, packages/fxa-auth-server/test/local/customs.js, packages/fxa-auth-server/test/local/routes/account.js, packages/fxa-auth-server/test/local/routes/emails.js, packages/fxa-auth-server/test/local/routes/session.js, packages/fxa-auth-server/test/local/routes/totp.js, packages/fxa-auth-server/test/local/routes/utils/signin.js, packages/fxa-auth-server/test/mocks.js, packages/fxa-graphql-api/src/config/rate-limit-rules.txt
- We want to avoid inadvertent blocks on emails
- Switches to using ip_email or ip_uid for more checks
- Add policies for ip only violations
- Adds ability to block on ip_uid. (_It became apparent this was needed to maintain symmetry with ip_email rules._)
Closes: FXA-8589
=> bug(auth): Users email getting blocked

packages/fxa-auth-server/lib/customs.js
- Noticed a stray log statement and unspecified error
- Removes console.log
- Uses AppError
=> polish(auth): Remove stray console.log and fix error type thrown.

.circleci/config.yml
* ci tests were failing with skip cache
* re-add run-many
=> fix failing ci tests

apps/payments/next/app/[locale]/[offeringId]/[interval]/checkout/[cartId]/layout.tsx, apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(mainLayout)/layout.tsx, apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(startLayout)/layout.tsx, apps/payments/next/app/[locale]/[offeringId]/[interval]/upgrade/[cartId]/(startLayout)/start/page.tsx, libs/payments/ui/src/lib/client/components/Banner/index.tsx, libs/payments/ui/src/lib/constants.ts, libs/payments/ui/src/lib/server/components/SignedIn/index.tsx
- we should utilize the Banner component for consistent UX
- updates the SignedIn component to use the Banner component on Checkout
- adds the SignedIn component to Upgrade flow
Closes: FXA-11959
**Mobile / Tablet**
_Start page - mobile_
_Start page - tablet_
_Start page - desktop_
_Processing page_
_Success page_
_Start page - mobile_
_Start page - tablet_
_Start page - desktop_
_Processing page_
_Success page_
=> chore(payments-next): Update SignedIn component on Checkout and add to Upgrade flow

packages/functional-tests/tests/resetPassword/oauthResetPassword.spec.ts
- We want to note the other associated bug
- Updates comment to note other issue
=> chore(functional-tests): add link to bug in fixme comment

packages/functional-tests/tests/signin/signinCached.spec.ts, packages/fxa-settings/src/components/Settings/index.test.tsx, packages/fxa-settings/src/components/Settings/index.tsx
Reverts mozilla/fxa#19086
quickfix for FXA-12035, underlying bug and re-implementation will be fixed in #19144
=> Revert "bug(settings): Don't allow access to /settings if session isn't verified."

packages/fxa-auth-server/lib/senders/email.js, packages/fxa-auth-server/lib/senders/emails/global.scss, packages/fxa-auth-server/lib/senders/emails/templates/_versions.json, packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/en.ftl, packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/includes.json, packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/index.mjml, packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/index.stories.ts, packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/index.txt, packages/fxa-auth-server/test/local/senders/emails.ts
* We want to match the latest Figma design
* Update the template and test
Closes: FXA-12043
=> fix(emails): Update content of postAddTwoStepAuthentication email

apps/payments/next/.env, apps/payments/next/app/route.ts, apps/payments/next/config/index.ts, apps/payments/next/middleware.ts
- Do not show sub manage pages when feature flag is false
- Adds a feature flag
- If feature flag is disabled, middleware redirects to not-found page for all routes starting with /subscriptions
Closes: #FXA-11228
=> feat(next): add sub manage feature flag

packages/functional-tests/tests/subscription-tests/checkout.spec.ts, packages/functional-tests/tests/subscription-tests/subscription.spec.ts
- These tests have been intermittently failing
- Disables the tests
=> chore(functional-tests): disable flaky functional tests

packages/fxa-content-server/server/config/local.json-dist
- We want to enable the new flow by default in local env
- add flag in local.json-dist
=> enable new inline recovery setup flow by default in local env

packages/functional-tests/tests/cms/cms-2fa.spec.ts, packages/functional-tests/tests/cms/cms.spec.ts, packages/fxa-settings/src/components/AppLayout/index.test.tsx, packages/fxa-settings/src/components/AppLayout/mocks.tsx
- Missed some review comments
- Adds review comments in
Closes: https://mozilla-hub.atlassian.net/browse/FXA-12222
=> fix(issues): Add feedback from PR comments

packages/fxa-auth-server/lib/routes/totp.js, packages/fxa-auth-server/test/local/routes/totp.js
Because:
* Some accounts are in a state where 2fa is 'enabled', but not 'verified'. The accounts trying to begin this flow would fail 2fa setup against the valid code check because the redis secret was not getting read
This commit:
* Checks for this state and reads the secret from redis. The token gets replaced further down the flow
closes FXA-12145
---
To reproduce the issue, create an account and set up 2FA normally.
Currently not sure how to get into this state by going through our UI. Run `select * from totp;` to see our totp token rows, and run `UPDATE totp SET verified = 0 WHERE id = 1;` where the ID matches what you want to update (ping me or Valerie to get 2 emails/UIDs that are seeing this problem to check in admin-panel that the states match), then update the Settings page to …
=> fix(2fa): Handle 2fa setup with bad 2fa token state

packages/fxa-content-server/server/config/local.json-dist
- Commited a typo
- Fixes typo
=> fix(config): Fix typo in local.json-dist

packages/fxa-auth-server/lib/payments/stripe.ts, packages/fxa-auth-server/lib/routes/subscriptions/mozilla.ts
- Current errors thrown during price info fetching do not provide enough information to effectively investigate the specific issue.
- Adds relevant information to the errors to allow further investigation.
Closes: #PAY-3237
=> fix(payments): add context to price info errors

packages/fxa-settings/src/components/Banner/index.tsx
- l10n id was incorrect
- fix id
=> fix(l10n): Banner l10n id mismatch

packages/fxa-settings/src/components/Settings/DropDownAvatarMenu/index.test.tsx, packages/fxa-settings/src/components/Settings/DropDownAvatarMenu/index.tsx, packages/fxa-settings/src/lib/cache.ts
- We want to clear the MFA cache on signout
- Clears MFA cache on sign out
Closes: FXA-12399
=> polish(settings): Clear MFA cache on sign out

packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/routes/auth-schemes/hawk-fxa-token.js, packages/fxa-auth-server/lib/routes/auth-schemes/verified-session-token.js, packages/fxa-auth-server/lib/routes/mfa.ts, packages/fxa-auth-server/lib/routes/password.ts, packages/fxa-auth-server/lib/routes/recovery-codes.js, packages/fxa-auth-server/lib/routes/recovery-key.js, packages/fxa-auth-server/lib/routes/recovery-phone.ts, packages/fxa-auth-server/lib/routes/totp.js, packages/fxa-auth-server/lib/server.js, packages/fxa-auth-server/test/local/routes/auth-schemes/verified-session-token.js, packages/fxa-auth-server/test/local/routes/recovery-phone.js
- We are adding an additional authentication strategy
- Add the strategy and apply to applicable endpoints
=> task(auth): Add additional authentication strategy

packages/functional-tests/tests/settings/changeEmail.spec.ts, packages/functional-tests/tests/settings/changeEmailBlocked.spec.ts, packages/fxa-auth-client/lib/client.ts, packages/fxa-auth-server/docs/swagger/emails-api.ts, packages/fxa-auth-server/lib/routes/emails.js, packages/fxa-graphql-api/src/gql/account.resolver.spec.ts, packages/fxa-graphql-api/src/gql/account.resolver.ts, packages/fxa-settings/src/components/Settings/UnitRowSecondaryEmail/index.test.tsx, packages/fxa-settings/src/components/Settings/UnitRowSecondaryEmail/index.tsx, packages/fxa-settings/src/models/Account.ts
- we want mfa for sensitive actions
- wraps change primary email action with MFA guard
Closes: FXA-12226
=> feat(mfa): wrap change primary email action with MFA guard

packages/fxa-auth-server/config/dev.json, packages/fxa-auth-server/config/index.ts, packages/fxa-auth-server/lib/oauth/db/index.js, packages/fxa-auth-server/lib/oauth/db/mysql/index.js, packages/fxa-auth-server/lib/oauth/token.js, packages/fxa-auth-server/test/oauth/api.js, packages/fxa-auth-server/test/oauth/db/index.js, packages/fxa-event-broker/src/jwtset/jwtset.service.ts, packages/fxa-event-broker/src/jwtset/set.interface.ts, packages/fxa-event-broker/src/pubsub-proxy/pubsub-proxy.controller.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.spec.ts, packages/fxa-event-broker/src/queueworker/queueworker.service.ts, packages/fxa-event-broker/src/queueworker/service-notification.interface.ts, packages/fxa-event-broker/src/queueworker/sqs.dto.ts
Reverts mozilla/fxa#19530
We want to keep Pocket code around a bit longer.
=> Revert "feat(pocket): Remove Pocket back-end code"
