mozilla/fxa

- packages/fxa-graphql-api/src/gql/gql.module.ts
Because:
- immediately sending response after setting HTTP 415 causes a server
error as other middleware will try to set headers on the response
This commit:
- set the HTTP 415 by passing an error into next()
Closes: #7274
> fix(gql-api): don't send response after setting HTTP 415

- packages/fxa-settings/.license.header
- packages/fxa-settings/.rescriptsrc.js
- packages/fxa-settings/package.json
- packages/fxa-settings/public/locales/en-US/settings.ftl
- packages/fxa-settings/src/components/Nav/en-US.ftl
- packages/fxa-settings/src/components/Nav/index.tsx
- packages/fxa-settings/src/components/PageDisplayName/en-US.ftl
- packages/fxa-settings/src/components/PageTwoStepAuthentication/en-US.ftl
- packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx
- yarn.lock
Because:
- we want to use .ftl files that are located alongside the components
in which they are used for better DX
This commit:
- use Webpack to watch and merge small .ftl files into a combined file
that's served to the client
- add small .ftl files as examples
Closes: #7253
> chore(settings): use small .ftl files

- _scripts/base-docker.sh
In case the `npx yarn install` command fails because of a module installation, the actual error output is stored in `/tmp/xfa-XYZ/build.log` files which are not easily accessible afterwards. This makes troubleshooting of the build process unnecessarily complicated and time consuming.
Fixes the already existing code to dump out these build logs whenever they exist and whenever the script `_scripts/base-docker.sh` exits (with whatever exit code).
During Docker image builds using the script `_scripts/build-builder.sh`, the resulting `artifacts/fxa-builder.log` will then also contain this output for further inspection.
Closes: n/a
> Fix base-docker.sh print out of build error logs

- packages/fxa-payments-server/server/config/index.js
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- We want to implement Paypal support without deploying to production until it's ready, and it's a good idea in general to put new features behind a flag in case there are unforeseen problems.
- Adds a PayPal feature flag for the front-end that is disabled by default.
- Currently, an empty `<div>` is rendered in the `SubscriptionCreate` component if the flag is enabled.
Closes: #7271
> feat(payments): Add feature flag for PayPal UI

- packages/fxa-payments-server/README.md
- FxA root uses yarn workspaces which npm LTS doesn't currently support. Also test commands had extra '--' in them that caused them to fail.
- Replaces `npm run` with `yarn` and modifies testing commands, so that they work.
No issue on file
> chore(docs): Replace npm with yarn commands in payments README

- packages/fxa-content-server/app/scripts/views/index.js
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/components/Checkbox/index.test.tsx
- packages/fxa-settings/src/components/Checkbox/index.tsx
- packages/fxa-settings/src/components/InputText/index.tsx
- packages/fxa-settings/src/components/PageChangePassword/index.test.tsx
- packages/fxa-settings/src/components/PageDeleteAccount/index.stories.tsx
- packages/fxa-settings/src/components/PageDeleteAccount/index.test.tsx
- packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
- packages/fxa-settings/src/components/PageSettings/index.test.tsx
- packages/fxa-settings/src/components/PageSettings/index.tsx
- packages/fxa-settings/src/constants/index.tsx
- packages/fxa-settings/src/lib/auth.test.tsx
- packages/fxa-settings/src/lib/auth.ts
- packages/fxa-settings/src/lib/test-utils.ts
- Add the delete account page to beta/settings
- small change to remove `errorTooltipClass` from `packages/fxa-settings/src/components/InputText/index.tsx` as it's not being used anywhere
- refs #5180
- fixes #4983
- fixes #4981
- fixes #4980
- fixes #4984
Opening this up before I finish tests and RTL adjustments so I can maybe get some feedback on spacing and style tweaks
> feat(fxa-settings): add delete account page

- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/config/index.ts
Because:
* We want to disable paypal APIs when not configured.
This commit:
* Adds an enabled flag to default paypal to an off state.
Closes #7265
> feat(auth-server): add paypal enabled option

- packages/fxa-auth-server/lib/metrics/amplitude.js
- packages/fxa-auth-server/lib/metrics/events.js
- packages/fxa-auth-server/test/local/metrics/amplitude.js
- packages/fxa-shared/metrics/amplitude.js
The token verify metric began including location data in 196 because it started using the auth-server metrics code path. Although seemingly a benign addition, due to how the location got used further down the ETL pipeline it got integrated into the rollup 'fxa - activity' event unexpectedly. Since a large portion of the verify events originate at the profile server this overwrote the user's actual location with our server's geoip.
This commit adds a `minimal` option to the amplitude metrics code that only logs the data originally submitted before 196 for the two oauth specific metrics.
fixes #7298
> fix(metrics): fixed 'fxa - activity' metric

- packages/fxa-react/components/Head/index.tsx
- packages/fxa-settings/public/locales/en-US/settings.ftl
- packages/fxa-settings/src/components/App/en-US.ftl
- packages/fxa-settings/src/components/PageChangePassword/index.tsx
Because:
- we should localize the page title
This commit:
- localize the page title in the Head component
- add en-US strings
Closes: #5059
> feat(settings): localize page title

- packages/fxa-auth-server/.vscode/launch.json
- packages/fxa-auth-server/.vscode/tasks.json
These tweaks got the mocha command running for auth-server remote tests for me in vscode.
> chore(auth-server): add ability to run remote tests with mocha vscode

- README.md
Was passing by and noticed some packages were missing links to their docs.
miss u fxa
> chore(docs): Add missing package README links

- packages/fxa-shared/db/models/auth/index.ts
- packages/fxa-shared/db/models/auth/paypal-ba.ts
- packages/fxa-shared/test/db/models/auth/helpers.ts
- packages/fxa-shared/test/db/models/auth/index.spec.ts
- packages/fxa-shared/test/db/models/auth/paypal-ba.sql
Because:
* We want to track billing agreement IDs used by customers using PayPal
over time, and Stripe metadata is only used to track the currently
active billing agreement ID to use.
This commit:
* Adds model commands and a model to use the existing paypalCustomers
table that handle basic CRUD operations.
Closes #7032
> feat(shared): add paypal BA model commands

- packages/fxa-settings/public/locales/en-US/settings.ftl
- packages/fxa-settings/src/components/PageSecondaryEmailAdd/en-US.ftl
- packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.tsx
- packages/fxa-settings/src/components/PageSecondaryEmailVerify/en-US.ftl
- packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.tsx
- we want to localize the Add Secondary Email page and Verify Secondary Email page
- localizes both pages
- adds en-US strings
Closes: #5063
> localize the secondary email page

- packages/fxa-auth-server/lib/routes/password.js
- packages/fxa-auth-server/test/remote/password_change_tests.js
Because:
- a 2fa verified session becomes unverified after a successful password
change, leading to several dead ends on the client side
This commit:
- copy the previous session's verification method to the new session on
password change
Closes: #4257, #4753
This is a follow-up to https://github.com/mozilla/fxa-auth-server/issues/2313 (https://github.com/mozilla/fxa-auth-server/pull/2437), and fixes #4257 and #4753.  More specifically, it addresses rfk's comment at https://github.com/mozilla/fxa/issues/4257#issuecomment-590518611: 
> ... it does not correctly copy the 2FA verification status
I interpreted that comment to mean that we should copy the verification status.
https://github.com/mozilla/fxa/issues/7288 is a related issue; its comment …
> fix(auth): copy session verification method on password change

- packages/fxa-react/components/Footer/index.test.tsx
- packages/fxa-react/components/Footer/index.tsx
- packages/fxa-settings/public/locales/en-US/settings.ftl
- packages/fxa-settings/src/components/App/en-US.ftl
- packages/fxa-settings/src/components/HeaderLockup/en-US.ftl
- packages/fxa-settings/src/components/HeaderLockup/index.tsx
- we want to localize the header and footer
- localizes the header and footer :-)
- Note: I feel a little weird about putting the strings for the footer (which lives in fxa-react) over in the fxa-settings App component's ftl file. This is in keeping with the approach from #7327 and I can't think of a better approach, but other suggestions welcome!
- [Update: regular casing restored.] ~~Also note: I've used SpOnGeBoB cAsInG to convince myself that the l10n transforms are actually getting applied. But nobody else is doing that in the other l10n commits, so I can revert to normal casing if that's preferred.~~ 
Closes: #5058
Any other information that is important to …
> localize settings header and footer

- packages/fxa-payments-server/.storybook/preview-head.html
- packages/fxa-payments-server/server/config/index.js
- packages/fxa-payments-server/server/lib/csp.test.js
- packages/fxa-payments-server/server/lib/csp/blocking.js
- packages/fxa-payments-server/server/lib/server.js
- packages/fxa-payments-server/src/lib/config.test.ts
- packages/fxa-payments-server/src/lib/config.ts
- packages/fxa-payments-server/src/routes/Product/PayPalButton/index.stories.tsx
- packages/fxa-payments-server/src/routes/Product/PayPalButton/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- We want to provide the option to pay with PayPal on the Subscribe page.
- Adds a `PaypalButton` React component that renders if the PayPal feature is enabled (Issue #7271 ), and the customer is a new customer.
Closes: #7097 
- To see the button, the PayPal feature must be enabled, see #7271 .
- i.e. `FEATURE_USE_PAYPAL_UI_BY_DEFAULT=true pm2 restart payments --update-env`
- There is one CSP error that still needs to be handled by #7350 .
- The button needs to be shown conditionally based on whether there is any saved payment information. Currently, it is shown only if there is no saved Stripe payment information. After #7115 , #7098 will handle checking for saved …
> feat(payments): Add PayPal button to Subscribe page

- packages/fxa-settings/public/locales/en-US/settings.ftl
- packages/fxa-settings/src/components/Avatar/en-US.ftl
- packages/fxa-settings/src/components/Avatar/index.tsx
- packages/fxa-settings/src/components/PageAvatar/Add.tsx
- packages/fxa-settings/src/components/PageAvatar/Capture.tsx
- packages/fxa-settings/src/components/PageAvatar/Change.tsx
- packages/fxa-settings/src/components/PageAvatar/en-US.ftl
I added localization for everything except the error handling on the Add page, which isn't wired up yet.
The strings are namespaced so that there won't be any l10n refactoring needed when merging stuff back into a single parent page for #7334.
- we want to localize the Avatar page
- localizes the Avatar page and Avatar component
- adds en-US strings
Closes: #5065
> feat(settings): Localize the Avatar page

- .github/dependabot.yml
- We're not keeping up with dependency updates
- Increases the open PR count
> Up the dependabot limit to 6

- packages/fxa-auth-server/lib/payments/paypal-client.ts
- packages/fxa-auth-server/lib/payments/paypal.ts
- packages/fxa-auth-server/test/local/payments/paypal-client.js
- packages/fxa-auth-server/test/local/payments/paypal.js
- We need Billing Agreement from PayPal before charging customer
- Adds billing agreement method to PayPalHelper
Closes: #7235
> feat(auth-server): adds createBillingAgreement method to PayPalHelper

- packages/fxa-settings/src/components/PageChangePassword/index.tsx
- packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
- packages/fxa-settings/src/components/PageDisplayName/index.tsx
- packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx
- packages/fxa-settings/src/index.tsx
- packages/fxa-settings/src/lib/auth.test.tsx
- packages/fxa-settings/src/lib/auth.ts
- packages/fxa-settings/src/lib/firefox.ts
- packages/fxa-settings/src/models/Account.ts
This implements the desktop firefox version of browser/page messaging for the new settings. It's loosely based on the content-server [channels](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/app/scripts/lib/channels) but only includes aspects required for the settings page. Implementation for the mobile browsers on iOS and Android can be done in future PRs.
> browser comms for new settings on desktop

- packages/fxa-auth-server/lib/routes/subscriptions/index.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- packages/fxa-auth-server/test/local/senders/email.js
- Moving to new paradigm of Container means that paypalHelper is not passed into createRoutes.
- Fixes the createRoutes method to check the config, not expect a passed in PayPalHelper
> fix(auth-server): Correct checks in createRoutes

- packages/fxa-admin-panel/package.json
- packages/fxa-payments-server/package.json
- packages/fxa-payments-server/src/lib/test-utils.tsx
- packages/fxa-react/package.json
- packages/fxa-settings/package.json
- yarn.lock
https://github.com/mozilla/fxa/pull/7399 with a couple corrections on `jest.requireActual` calls
> chore(deps-dev): bump @types/jest from 24.9.1 to 26.0.20 but with green CI

- packages/fxa-settings/src/lib/firefox.ts
- Firefox iOS needs to know about changes to settings
- Accounts for the difference in message format for firefox-ios
- Verifying the messages are handled by fx-ios from the new settings page requires a custom build to change the settings url to beta.
- Unlike desktop the browser's message handler is only enable via the built-in account menu UI, loading the new settings page in a tab does not enable the browser end of the channel.
- I manually verified the messages are handled via the xcode debugger.
- The previous `fx_ios_v1` context from content-server is no longer in use.
closes #7378
> feat(settings): support firefox-ios in new settings browser comms

- packages/fxa-settings/public/locales/en-US/settings.ftl
- packages/fxa-settings/src/components/PageChangePassword/en-US.ftl
- packages/fxa-settings/src/components/PageChangePassword/index.tsx
Because:
- something wasn't localized
This commit:
- localize!
Closes: #7322
> chore(settings): localize the common password hint

- packages/fxa-content-server/tests/functional/lib/helpers.js
- packages/fxa-content-server/tests/functional/settings_v2/change_password.js
- packages/fxa-content-server/tests/functional/settings_v2/display_name.js
- we want to be sure the browser is notified on these state changes
closes #7376
> chore(tests): add browser comm assertions to new settings functional tests

- packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx
- It takes a tick to load the qr code
closes #6891
> fix(settings): reserve vertical space for QR code

- packages/fxa-settings/src/lib/firefox.ts
Apparently oldish ios safari won't let you extend EventTarget
- uses a mock for those browsers
> fix(settings): fix startup error on some legacy browsers

- packages/fxa-settings/src/lib/gql.test.ts
- packages/fxa-settings/src/lib/gql.ts
- packages/fxa-shared/db/models/auth/index.ts
- The new settings page started showing the blank "Application Error" page when the sessiontoken was no longer valid.
- fixes it to redirect to signin
> fix(settings): when gql-api switched to nestjs the auth error changed

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* We want to process invoices for Paypal customers when the invoice
is opened to attempt a first charge.
This commit:
* Will process invoices upon stripe webhook reception.
Closes #7428
> feat(auth-server): handle stripe invoice open events

- packages/fxa-settings/src/styles/ctas.scss
- packages/fxa-settings/src/styles/tailwind.scss
- iOS is weird about `hover` effects
- uses a `@media` query to set the hover styles
fixes #6371
> fix(settings): only set hover css when supported

- README.md
- _scripts/legal-md-to-pdf.sh
- packages/fxa-content-server/grunttasks/clean.js
- packages/fxa-content-server/grunttasks/copy.js
- packages/fxa-content-server/grunttasks/remarkable.js
- packages/fxa-content-server/grunttasks/replace.js
- packages/fxa-content-server/grunttasks/yeoman.js
- packages/fxa-content-server/package.json
- packages/fxa-content-server/server/lib/configuration.js
- packages/fxa-content-server/server/lib/legal-templates.js
- yarn.lock
- update scripts to account for legal-docs repo changes coming in https://github.com/mozilla/legal-docs/pull/1502
Closes: #6902 
For testing you'll need to update the `legal-docs` dependency to point to the restructured commit, linked above.
> task(fxa-content-server): account for legal-docs new format

- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-payments-server/src/lib/apiClient.test.ts
- packages/fxa-payments-server/src/lib/apiClient.ts
- packages/fxa-payments-server/src/lib/test-utils.tsx
- packages/fxa-payments-server/src/routes/Product/PayPalButton/index.stories.tsx
- packages/fxa-payments-server/src/routes/Product/PayPalButton/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- We want to initialize the PayPal transaction when the user clicks the PayPal button.
- Adds a `createOrder` handler to the `PaypalButton` component, which creates a new customer if one doesn't already exist and posts to a new `fxa-auth-server` route to get a Paypal checkout token.
- Fixes some Paypal feature flag tests that were passing despite the Paypal button not rendering in the tests. For some reason, the below assertion was passing even when `queryByTestId('paypal-button')` was `null`:
```js
waitForExpect(() =>
expect(queryByTestId('paypal-button')).toBeInTheDocument()
);
```
Closes: #7269 
- The `PaypalButton` is mocked in the tests, since it is ordinarily a third-party React component rendered in a cross-origin iframe.
- This PR adds two …
> feat(payments): Add createOrder handler to PayPal button

- packages/fxa-auth-server/lib/payments/paypal-client.ts
- packages/fxa-auth-server/lib/payments/paypal.ts
- packages/fxa-auth-server/lib/routes/account.js
- packages/fxa-auth-server/test/local/payments/fixtures/paypal/ba_update_success.json
- packages/fxa-auth-server/test/local/payments/paypal.js
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-auth-server/test/mocks.js
Because:
* We want to ensure any remaining billing agreements and customer
data for PayPal users is deleted upon account delete.
This commit:
* Cancels all billing agreements that are not already in a terminal
state.
* Deletes the billing agreement rows from the database.
Closes #7071
> feat(auth-server): cleanup paypal data on delete

- packages/fxa-content-server/tests/functional/lib/selectors.js
- packages/fxa-settings/public/locales/en-US/settings.ftl
- packages/fxa-settings/src/components/DataBlock/en-US.ftl
- packages/fxa-settings/src/components/DataBlock/index.test.tsx
- packages/fxa-settings/src/components/DataBlock/index.tsx
- packages/fxa-settings/src/components/GetDataTrio/index.tsx
- packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.tsx
- packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.test.tsx
- packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx
- packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx
Because:
- there is no feedback to users when they download/copy/print codes
This commit:
- display a tooltip when a user download/copy/print
- remove the copy feature from DataBlock
- it's confusing? why have that and the copy feature in
GetDataTrio?
- it's not obvious that it's a button and there's no feedback so
users wouldn't know they copied something
- it uses a different separator for arrays than GetDataTrio
- update DataBlock to include GetDataTrio by default
- they are always used together already
- we need to display the tooltip in DataBlock on an action in
GetDataTrio
Closes: #7026
> feat(settings): display success tooltip on datablock action

- packages/fxa-auth-server/lib/payments/paypal-client.ts
- packages/fxa-auth-server/lib/payments/paypal.ts
- packages/fxa-auth-server/test/local/payments/fixtures/paypal/transaction_search_success.json
- packages/fxa-auth-server/test/local/payments/paypal-client.js
- packages/fxa-auth-server/test/local/payments/paypal.js
Because:
* We want to search transactions for a given user/invoice.
This commit:
* Adds a paypal transaction search API command.
Closes #7238
> feat(auth-server): add transaction search to paypal

- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- packages/fxa-payments-server/src/components/PaymentConfirmation/index.stories.tsx
- packages/fxa-payments-server/src/components/PaymentConfirmation/index.test.tsx
- packages/fxa-payments-server/src/components/PaymentForm/index.stories.tsx
- packages/fxa-payments-server/src/lib/mock-data.tsx
- packages/fxa-payments-server/src/routes/Product/index.stories.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/index.stories.tsx
- packages/fxa-payments-server/src/store/types.tsx
- We want to vary pieces of UI based on the user's payment provider...
- Adds a `payment_provider` to the Customer object
Closes: #7115 
> feat(auth-server): add 'payment_provider' property to Customer object

- packages/fxa-auth-server/lib/payments/paypal-client.ts
- packages/fxa-auth-server/lib/payments/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/test/local/payments/paypal-client.js
- packages/fxa-auth-server/test/local/payments/paypal.js
- packages/fxa-payments-server/src/lib/apiClient.test.ts
- packages/fxa-payments-server/src/lib/apiClient.ts
- packages/fxa-payments-server/src/routes/Product/PayPalButton/index.stories.tsx
- packages/fxa-payments-server/src/routes/Product/PayPalButton/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- We need to pass through the currency from the selected plan to paypal
- Makes the currency code configurable on the paypal-client SetExpressCheckout and follows back down the chain of calls adding the currencyCode as appropriate.
Closes: #7471
> (feat)auth-server: Add define-able currencies to paypal checkout

- packages/fxa-graphql-api/src/auth/session-token.strategy.spec.ts
- packages/fxa-graphql-api/src/auth/session-token.strategy.ts
- packages/fxa-settings/src/lib/gql.ts
There's a special token status of `mustVerify` that requires the session to be verified before it can be used at all. We need to reject any requests from unverified sessions when it is set.
The frontend should redirect to the `signin_token_code` page when this happens.
fixes #6240
ref https://github.com/mozilla/fxa/blob/67c3afa3ea38826d7b4b9f78fa3d706cfa07ecca/packages/fxa-auth-server/lib/routes/emails.js#L175-L181
> fix(settings): account for sessionToken.mustVerify in new settings

- packages/fxa-settings/src/components/PageAvatar/index.tsx
- react-easy-crop style injection was being blocked for security
- Loads the styles for react-easy-crop in a more sane way
- fixes #7507
> task(fxa-settings): load styles for react-easy-crop

- packages/fxa-settings/src/components/UnitRowWithAvatar/index.tsx
- Fixes the alignment of the add/change avatar button on the main settings view
- fixes #7410
> fix(fxa-settings): add/change avatar button alignment

- packages/fxa-settings/src/components/ConnectedServices/index.tsx
- packages/fxa-settings/src/components/Modal/index.tsx
- packages/fxa-settings/src/components/ModalVerifySession/index.tsx
The `Modal` and `ModalVerifySession` components were incidentally calling the `onDismiss` callback with the dom event argument from their originating element. This happened to break the `ConnectedServices` component which was using a fn that accepted optional parameters as the callback.
This commit ensures the callbacks are called with no arguments.
fixes #7509
> fix(settings): ensure modal callbacks adhere to the defined type

- packages/fxa-auth-server/lib/payments/paypal-client.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/test/local/payments/paypal-client.js
- paypal requires uppercased currencyCode
- adds it at the client level 
- and at the handler validation
> fix(auth-server): Paypal requires uppercased currencyCode

- packages/fxa-payments-server/src/lib/apiClient.test.ts
- packages/fxa-payments-server/src/lib/apiClient.ts
- packages/fxa-payments-server/src/lib/test-utils.tsx
- packages/fxa-payments-server/src/routes/Product/PayPalButton/index.stories.tsx
- packages/fxa-payments-server/src/routes/Product/PayPalButton/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- We want to process a successful PayPal authorization during Checkout.
- Adds an `onApprove` handler to the `PaypalButton` component, which posts to a new `fxa-auth-server` route to perform a bunch of tasks (see [PayPal Checkout ladder diagram](https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-sub-platform#paypal-checkout)), including creating a new subscription and attempting to capture the first payment.
Closes: #7420 
> feat(payments): Add onApprove handler to PayPal button

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx
- packages/fxa-payments-server/src/components/PaymentForm/index.tsx
- packages/fxa-payments-server/src/components/PaymentLegalBlurb/index.tsx
- packages/fxa-payments-server/src/routes/Product/PayPalButton/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.scss
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- The create subscription screen did not match the user tested designs
- adds centered headings
- reorganizes form code, now that payment is more complicated
- updates the paypal button
- updates the privacy policy links
- moves the test for legal text to the createSubscription tests
Closes: #7449
Before:
After:
Design should roughly be [panel 288 from here](https://www.figma.com/file/AvdKdmts8KN8HK6d1VCMTH/Paypal_Checkout_Concept(B)?node-id=0%3A1) - jess cook can provide more guidance.
Note that the paypal button is delivered automatically from paypal. despite the docs (https://developer.paypal.com/docs/business/checkout/reference/style-guide/#size) it does not want to give us a button with a P logo in it. My current best guess for this is that the …
> (feat)payments-server: update create subscription page for paypal designs

- packages/fxa-auth-server/lib/payments/paypal-client.ts
- packages/fxa-auth-server/lib/payments/paypal.ts
- packages/fxa-auth-server/test/local/payments/paypal-client.js
Because:
* We want to gauge response times from PayPal and track client errors.
This commit:
* Adds an event emitter similar to Stripes so that the paypal helper
can augment it with metric reporting.
Closes #7522
> feat(auth-server): add metrics for paypal client

- packages/fxa-settings/src/components/PageDeleteAccount/en-US.ftl
- packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
Fixes #7443.
- it would be nice to close out the 'delete account' epic
- the button text splits across two lines on android
- shortens the text from "delete account" to "delete"
Closes: #7443
> fix(settings): Shorten 'delete account' button string to fit

- packages/fxa-settings/src/components/PageChangePassword/index.test.tsx
- packages/fxa-settings/src/components/PageChangePassword/index.tsx
Fixes #5173.
- we'd like to get metrics parity across old and new settings
- adds a missing event logged when the change password page is viewed
Closes: #5173
> fix(settings): Add page view event for PageChangePassword metrics parity

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- PayPal as a brand has a capital "P" for both Ps. This is a follow-up from #7449 .
- Creates a Fluent [placeable](https://www.projectfluent.org/fluent/guide/placeables.html) for the PayPal brand name, replacing "Paypal" with "PayPal" in main.ftl.
Closes: mozilla/fxa-content-server-l10n#471
Changes to `SubscriptionCreate` component
Before
After
> fix(payments): Use brand name PayPal in localized strings.

- packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/en-US.ftl
- packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.tsx
- packages/fxa-settings/src/components/PageChangePassword/en-US.ftl
- packages/fxa-settings/src/components/PageChangePassword/index.test.tsx
- packages/fxa-settings/src/components/PageChangePassword/index.tsx
- packages/fxa-settings/src/components/PageDisplayName/en-US.ftl
- packages/fxa-settings/src/components/PageDisplayName/index.test.tsx
- packages/fxa-settings/src/components/PageDisplayName/index.tsx
- packages/fxa-settings/src/components/PageRecoveryKeyAdd/en-US.ftl
- packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.test.tsx
- packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx
- packages/fxa-settings/src/components/PageSecondaryEmailVerify/en-US.ftl
- packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.test.tsx
- packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.tsx
- we're supposed to show an alert bar in the settings page after completing tasks in individual sub-pages
- the sub-pages sometimes try to show an alert, but it isn't displayed before the user navigates away
- updates all sub-pages to use `alertTextExternal` to display a notification in the base settings page
- a couple of tests still need to be updated (this work has been deferred to #7596)
Closes: #7030
> Show alert bar after completing tasks

- packages/fxa-content-server/app/scripts/models/support-form.js
- packages/fxa-content-server/app/scripts/templates/support.mustache
- packages/fxa-content-server/app/scripts/views/support.js
Because:
- there are various issues with l10n on the subscription support form
This commit:
- use translated strings directly in templates
- stop lowercasing translated strings with JS
Closes: #7591, #7592 (l10n issues: https://github.com/mozilla/fxa-content-server-l10n/issues/430 and https://github.com/mozilla/fxa-content-server-l10n/issues/423)
> fix(l10n): fix support form l10n

- packages/fxa-auth-server/lib/routes/attached-clients.js
> feat(settings): replace connected service display name for Mac OS X with macOS on retrieval

- packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.tsx
- packages/fxa-settings/src/components/PageAvatar/index.tsx
- packages/fxa-settings/src/components/PageChangePassword/index.test.tsx
- packages/fxa-settings/src/components/PageChangePassword/index.tsx
- packages/fxa-settings/src/components/PageDisplayName/index.tsx
- packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx
- packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.tsx
- packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.test.tsx
- packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.tsx
- packages/fxa-settings/src/components/PageTwoStepAuthentication/index.test.tsx
- packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx
- packages/fxa-settings/src/components/Profile/index.tsx
- packages/fxa-settings/src/components/ScrollToTop/index.tsx
- packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx
- packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
- packages/fxa-settings/src/components/UnitRowWithAvatar/index.tsx
Ready for review. To ensure we scroll to the right spot in the page, we could do something fancy, complex, and brittle, like storing the scroll distance when navigating to a page, then restoring the scroll location if the user goes back. However, the intent of the bug is to not get thrown to the top of the screen when backing out of a sub-page, and the simplest approach is to add `id`s to each of the rows, then just navigate to that hash instead of using `history.back()`. 
This ran into a little bit of complexity, because reach router doesn't handle hashes, but hacking around that was easy enough and well-contained.
Fixes #7020.
> 7020 scroll position

- packages/fxa-content-server/server/bin/fxa-content-server.js
- packages/fxa-content-server/server/config/production.json
- subroutes currently 404 on a hard refresh in stage / prod
- subroutes of /beta/settings should serve the SPA index.html
> serve beta settings subroutes the index.html page in production

- packages/fxa-auth-server/lib/payments/currencies.ts
- packages/fxa-auth-server/lib/payments/paypal.ts
- packages/fxa-auth-server/test/local/payments/currencies.js
- packages/fxa-auth-server/test/local/payments/paypal.js
- We were just converting the stripe AmountInCents to a string causing paypal customers to be charged 100x more than intended.
- Paypal has a lot of finicky rules around currency
- Implements a function to convert amountInCents to a string as per paypal specs
- Restricts currency support to a list of paypal supported currencies
Closes: #7563
> fix(auth-server): Correctly format paypal AMT string

- packages/fxa-auth-server/lib/payments/paypal-client.ts
- packages/fxa-auth-server/lib/payments/paypal-error-codes.ts
- packages/fxa-auth-server/lib/payments/paypal-processor.ts
- packages/fxa-auth-server/lib/payments/paypal.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal-notifications.ts
- packages/fxa-auth-server/lib/sentry.js
- packages/fxa-auth-server/package.json
- packages/fxa-auth-server/scripts/paypal-processor.ts
- packages/fxa-auth-server/test/local/payments/fixtures/paypal/create_billing_agreement_failure.json
- packages/fxa-auth-server/test/local/payments/fixtures/paypal/do_reference_transaction_failure.json
- packages/fxa-auth-server/test/local/payments/fixtures/paypal/set_express_checkout_failure.json
- packages/fxa-auth-server/test/local/payments/paypal-client.js
- packages/fxa-auth-server/test/local/payments/paypal-processor.js
- packages/fxa-auth-server/test/local/payments/paypal.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js
Because:
* We want to ensure invoices paid via PayPal are processed when their
initial attempt fails or payments are pending then completed later.
This commit:
* Adds a paypal-processor script intended to be run on an hourly basis
that queries open invoices paid via paypal to process them as needed.
Closes #7452
> feat(auth-server): add paypal invoice processor

- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
Because:
* The paypal invoice open handler was not linked into the webhook
routing to actually run.
This commit:
* Adds a case statement for `invoice.finalize` which triggers when
the invoice becomes open to process the invoice with PayPal if
needed.
> fix(auth-server): link invoice handler to webhook

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/PaymentProcessing/index.scss
- packages/fxa-payments-server/src/components/PaymentProcessing/index.stories.tsx
- packages/fxa-payments-server/src/components/PaymentProcessing/index.test.tsx
- packages/fxa-payments-server/src/components/PaymentProcessing/index.tsx
- packages/fxa-payments-server/src/index.scss
- packages/fxa-payments-server/src/routes/Product/PayPalButton/index.stories.tsx
- packages/fxa-payments-server/src/routes/Product/PayPalButton/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.stories.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- packages/fxa-payments-server/src/routes/Product/index.test.tsx
- We want to give the user feedback about the status of their paypal payments
- Adds a processing view to the paypal payment flow
- fixes #7450
> feat(fxa-payments-server): add processing view to checkout

- packages/fxa-auth-server/lib/payments/paypal-client.ts
- packages/fxa-auth-server/lib/payments/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/test/local/payments/paypal-client.js
- packages/fxa-auth-server/test/local/payments/paypal.js
* PayPal has additional fraud protections requiring ip address pass
through in a similar manner to Stripe.
* Adds the ip address of the remote user when present to PayPal.
Closes #7590
My other PR #7664 should be merged first.
> feat(auth-server): pass ip through to paypal

- packages/fxa-auth-server/lib/payments/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/payments/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* We want to cancel the paypal billing agreement and remove it from
the customer when they no longer have active/past_due subscriptions
being paid for with paypal.
This commit:
* Hooks into the subscription cancellation event to determine if its the
last one paid by paypal, and cancels/removes the billing agreement if
that's the case.
Closes #7103
> feat(auth-server): remove paypal BA and cancel at end

- packages/fxa-payments-server/src/components/PaymentForm/index.tsx
- packages/fxa-payments-server/src/routes/Product/PayPalButton/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/PayPalButton/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- We want users to return to the first step of Checkout if they close the PayPal window (see [design spec](https://www.figma.com/file/ejDMYaKpm5bsYL5YvhItur/Payment-Integration?node-id=519%3A5608)). This is a follow-up from #7450 .
- Replaces the `PayPalButton` `onClick` handler with calling `setTransactionInProgress` in its `onApprove` method. This means the `PaymentProcessing` screen is only shown after successul authorization while we are waiting for the `POST /oauth/subscription/active/new-paypal` request to return.
Closes: #7677 
Before
After
* Also remove autofocus from the Name field on the Stripe widget, since it's no longer the only interactive element on the screen.
> feat(payments): Show processing screen onApprove for PayPalButton

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx
- packages/fxa-payments-server/src/components/PaymentLegalBlurb/index.tsx
- packages/fxa-payments-server/src/components/PaymentProcessing/index.scss
- packages/fxa-payments-server/src/components/PaymentProcessing/index.stories.tsx
- packages/fxa-payments-server/src/components/PaymentProcessing/index.test.tsx
- packages/fxa-payments-server/src/components/PaymentProcessing/index.tsx
- packages/fxa-payments-server/src/index.scss
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- We need to show the legal terms at every stage of the checkout process
- Adds the legal copy and links for the payment provider to the processing page and confirmation page.
- fixes #7614
> task(fxa-payments-server): add legal snippet to checkout flow

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/payments/paypal-client.ts
- packages/fxa-auth-server/lib/payments/paypal.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal-notifications.ts
- packages/fxa-auth-server/test/local/payments/fixtures/paypal/refund_transaction_success.json
- packages/fxa-auth-server/test/local/payments/paypal-client.js
- packages/fxa-auth-server/test/local/payments/paypal.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js
- There is no way to cancel the pending transaction, we want to listen for the successful transaction IPN and refund the transaction for invoice with uncollectible status.
- Adds refund transaction method in PayPal client and helper to refund successful merchant payment with uncollectible invoice found in IPN.
Closes: #7615
> feat(auth-server): refund paypal transaction

- packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.tsx
- packages/fxa-settings/src/components/PageChangePassword/index.tsx
- packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
- packages/fxa-settings/src/components/PageDisplayName/index.tsx
- packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx
- packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.tsx
- packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.tsx
- packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx
- The goBack and goHome functions need to be searched and replaced with the goHome and alertSuccessAndGoHome function names throughout the Page components in the fxa-settings package.
- Replace `goBack` and `goHome` with `goHome` and `alertSuccessAndGoHome` respectively.
Closes: #7679 7630
> Refactor goHome/goBack

- packages/fxa-shared/l10n/supportedLanguages.json
Fixes #7455.
- we actually do have translations for Hindi: our l10n code copies 'hi-HI' to 'hi', and firefox offers 'hi', but our supportedLanguages only included 'hi-HI'
- adds 'hi' locale to the list of supported languages
Closes: #7455
You can verify the fix by adding Hindi as the primary language in about:preferences, then try loading this branch in localhost:3030 and you'll see the form in Hindi. Compare to staging, where you'll see English, not Hindi.
> fix(l10n): Add 'hi' locale support

- packages/fxa-auth-server/config/dev.json
Because:
* Sandbox credentials for paypal were accidentally comitted.
This commit:
* Removes them.
> fix: remove sandbox credentials

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/event_credit_note_created.json
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* We want to allow support to refund paypal users.
This commit:
* Listens for credit note events on invoices and refunds a paypal
transaction on the invoice if one has completed with the same
amount.
Closes #7324
> feat(auth-server): add credit note listener

- packages/fxa-payments-server/src/routes/Subscriptions/index.scss
- We want vertical positioning to be consistent.
- Vertically centers the resubscribe blurb in relation to the resubscribe button.
Closes: #7692 
> feat(payments): Fix alignment of resubscribe <p> in sub. management

- packages/fxa-settings/src/components/Nav/index.stories.tsx
- packages/fxa-settings/src/components/Nav/index.test.tsx
- packages/fxa-settings/src/components/Nav/index.tsx
- Similar change was made to current settings in https://github.com/mozilla/fxa-content-server/pull/6882
- I'd like to restart the effort to upstream China specific changes behind feature flags, starting with the newer `fxa-settings`
- Remove the "Email Communications" link if it's set to an empty url in configuration
Closes: not filed
> feat(settings): hide email communications link if set to empty url

- packages/fxa-payments-server/src/lib/amplitude.test.ts
- packages/fxa-payments-server/src/lib/amplitude.ts
- packages/fxa-payments-server/src/lib/apiClient.test.ts
- packages/fxa-payments-server/src/lib/apiClient.ts
- packages/fxa-shared/metrics/amplitude.js
We should have metrics parity between Stripe and PayPal checkout events and we should be able to distinguish between them.
Adds pings to the `apiCapturePaypalPayment` call.
Closes: #7073
> feature: Add a new event property to Checkout related Amplitude events

- packages/fxa-auth-server/lib/error.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- packages/fxa-content-server/tests/functional/subscriptions.js
- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/App.tsx
- packages/fxa-payments-server/src/components/PaymentErrorView/index.tsx
- packages/fxa-payments-server/src/lib/errors.test.tsx
- packages/fxa-payments-server/src/lib/errors.ts
- packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
- We need to display multi-currency errors to users
- Updates the getErrorMessage function to handle a variety of error message
Closes: #7467 
To test:
Make sure your server's running with:
a) paypal enabled and 
b) update auth-server config so that currenciesToCountries is:
```
default: {
USD: ['US', 'GB', 'NZ', 'MY', 'SG', 'CA', 'AS', 'GU', 'MP', 'PR', 'VI'],
EUR: ['FR', 'DE'],
},
```
Steps:
* Go to localhost:8080, subscribe to Euro plan
* Use a paypal account that's configured for the US as it's country
Steps:
* Go to localhost:8080, subscribe to Euro plan
* Use normal stripe card 4242 4242 4242 4242 etc.
Alternatively, subscribe to a USD plan and use a, for example, french credit card (https://stripe.com/docs/testing#international-cards) 
Steps:
* …
> feat(payments-server): Display currency restrictions errors on front-end.

- packages/fxa-content-server/app/scripts/lib/router.js
Because settings is a separate js app we need to ensure navigating from the content-server app passes along flow parameters.
closes #7586
Note: this patch is against the /beta/settings route and will need a slight change for /settings when it becomes the default
> chore(metrics): ensure flow params are passed to settings

- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/index.tsx
Fixes #7740.
- The new settings page is always getting shown in English
- Actually passes in navigator.languages so that our translations can be displayed
> fix(l10n): Pass navigator.languages into the new settings page

- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/scripts/paypal-processor.ts
Because:
* fxa-auth-server only works as import path during tests and in some dev
conditions.
This commit:
* Uses a proper relative import.
> fix(auth-server): use proper relative import

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/PaymentErrorView/index.test.tsx
- packages/fxa-payments-server/src/components/PaymentErrorView/index.tsx
- packages/fxa-payments-server/src/lib/errors.ts
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- We descoped the [Returning Checkout story](https://jira.mozilla.com/browse/FXA-3078) for PayPal customers for the initial launch, and we want a descriptive placeholder screen for the small number of users who may be affected in the meantime.
- Shows `PaymentErrorView` in Checkout for returning PayPal customers with a descriptive message.
- Updates `PaymentErrorView` to show a different button for this error with the label "Manage my subscription" instead of "Try again" that takes the user to Subscription Management instead of SubscriptionCreate on click (the latter would have effectively been a noop).
- Localizes `PaymentErrorView` default "Try again" button label.
- Adds `TermsAndPrivacy` to `PaymentErrorView` for consistency with the rest of our Checkout screens.
Closes: #7726 
_Put …
> feat(payments): Add Checkout error screen for returning PayPal customers

- packages/fxa-auth-server/lib/payments/paypal-processor.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/scripts/paypal-processor.ts
- packages/fxa-auth-server/test/local/payments/paypal-processor.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js
Because:
* We want to alert users when processing invoices
if the payment failed.
This commit:
* Adds email sending of payment failed messages
when invoice processing fails.
Closes #7594
> feat(auth-server): send emails for invoicing

- packages/fxa-auth-server/lib/routes/validators.js
Because:
* We validate responses, and the optional property for paypal error
messages wasn't added to the validator.
This commit:
* Adds the optional property to the validator so an internal error
will not be thrown.
> fix(auth-server): allow payment error out

- packages/fxa-content-server/tests/server/routes/get-well-known-change-password.js
- This is a failing test in the new settings
- I can't really pinpoint why this test is starting to fail with moving to new settings, possibly `got` request library might not be following the redirect, but...
- I've tested this functionality locally and it does follow the redirect, so it is very little risk
- Fixes test by removing it lol, nah I pulled the redirect url assert into a different part
Closes: #7834
> fix(test): update well-known change password test

- packages/fxa-auth-server/lib/payments/paypal-client.ts
- packages/fxa-auth-server/lib/payments/paypal.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- when creating a new billing agreement we want to make sure the billing address information is copied to the Stripe Customer
- expands existing PayPal handler to retrieve billing address from Billing Agreement
Closes: #7693
> feat(auth-server): copy billing address info to Stripe customer

- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
* We can only do the currency check when a payment method id is
provided. The Stripe createSubscriptionWithPMI intentionally
allows no paymentMethodId to be provided to handle SCA which the
check did not account for.
This commit:
* Only verifies currency matches when a payment method id is provided.
> fix(auth-server): skip currency check without pmi

- packages/fxa-settings/src/components/PageAvatar/index.tsx
- packages/fxa-settings/src/lib/file-utils.tsx
- Avatar uploading from iOS doesn't always work as expected
- Taking a picture via camera on Firefox and Safari creates an image with different offsets (290px), so they will look different
- Removes auto rotation when uploading an image, `react-easy-cropper` allows the user the ability to rotate the image as needed
- When taking a photo from the camera, the user is taken to the cropper page to finalize the picture before saving
Closes: #7703
> fix(avatar): Avatar upload tweaks for new settings

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/PaymentErrorView/index.test.tsx
- packages/fxa-payments-server/src/components/PaymentLegalBlurb/index.tsx
- packages/fxa-payments-server/src/components/PaymentProcessing/index.test.tsx
- packages/fxa-payments-server/src/components/SubscriptionTitle/index.test.tsx
- packages/fxa-payments-server/src/components/SubscriptionTitle/index.tsx
- packages/fxa-payments-server/src/lib/errors.ts
- @peiying2 noticed some problems with the ftl file for payments
* Treats 'Stripe' as an untranslated brand, similar to how we handle 'Paypal'
* Corrects a typo (occured vs occurred)
* Replaces 3 periods with ellipses (thankfully this change doesn't require updating the l10n string IDs)
Closes: #mozilla/fxa-content-server-l10n#480.
> bug(l10n): Minor fixes to payments l10n

- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/scripts/paypal-processor.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* We cannot mark send_invoice subscriptions as incomplete when an
initial payment fails to require another payment attempt before
activating the subscription.
* We should send subscription failed emails when processing an invoice
via webhook.
This commit:
* Updates the checkout flow code so that the billing agreement and
subscription are removed if the PayPal transaction fails. This allows
the user to choose a new payment option and prevents temporary
subscription entitlements.
* Adds error handling for invoice processing in the stripe webhook
triggered invoice processing to ensure the customer is notified should
the invoice fail to get paid.
Closes #7852
Co-authored-by: Se Yeon Kim <say-yawn@users.noreply.github.com>
> fix(auth-server): handle failed checkout payments

- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-shared/db/models/auth/index.ts
We weren't accounting for token ttl when fetching the session token from the gql-api server, which would cause the frontend to think it was ok, but the auth-server would 401/110 the requests for data, triggering a GAE error.
This is a temporary fix for #7876
> fix(settings): fix session ttl in settings

- packages/fxa-settings/src/components/UnitRow/index.tsx
-
- removes the right margin class from the Link inside the UnitRow Component 
Closes: #7687 
before            |  after
:-------------------------:|:-------------------------:
before            |  after
:-------------------------:|:-------------------------:
> fix(settings): buttons are correctly  aligned to right

- packages/fxa-content-server/app/scripts/views/mixins/signed-in-notification-mixin.js
- packages/fxa-content-server/app/scripts/views/ready.js
A few spots in the recovery / reset flow navigated to settings URLs, but
because the settings app is now external to the backbone app, it's
necessary to navigateAway, otherwise attempts to navigate will appear to
do nothing.
Fixes #7815.
> fix(content-server): Navigate to settings as an external app

- packages/fxa-content-server/app/scripts/templates/pair/auth_complete.mustache
- Shouldn't redirect to old settings pages
- Updates the link on pairing complete
Closes: #7872
> fix(pair): update pairing complete link to point to new settings

- packages/fxa-settings/src/components/Profile/index.tsx
-
- removes date from `Localized` inside the `UnitRow` component in the `/settings/change_password` route
Closes: 
#7761 
> fix(settings): Remove time from password change

- packages/fxa-settings/src/components/DropDownAvatarMenu/index.tsx
- Returning null removes the component and avatar from the header
- Don't return null when session destroy is completed, redirect will take user to correct location
Closes: #6918
> fix(signout): Fix missing avatar when signing out

- packages/fxa-settings/src/components/Profile/en-US.ftl
Noticed this while working on other PRs.
> fix(l10n): Fix profile-heading l10n label typo.

- packages/fxa-payments-server/src/components/TermsAndPrivacy/index.test.tsx
- packages/fxa-payments-server/src/components/TermsAndPrivacy/index.tsx
- packages/fxa-payments-server/src/lib/formats.ts
Because:
- the frontend should use the new legal docs redirect endpoint so that
future metadata values of "localizeable" urls would work
This commit:
- update the ToS link to use the redirect endpoint
Closes: #7850
> chore(subscriptions): update ToS link to use redirect URL

- packages/fxa-auth-server/lib/routes/subscriptions/paypal-notifications.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js
- we want to document any IPN we are not handling for
- sends a "Unhandled Ipn message" error with the IPN's txn_type to Sentry
Closes: #7792
> feat(auth-server): send uncaught IPN type to Sentry

- packages/fxa-settings/src/components/PageAvatar/index.tsx
- packages/fxa-settings/src/lib/canvas-utils.tsx
- Avatar would not be set correctly on iOS devices and safari
- Cherry-picked @dannycoates [commit](https://github.com/mozilla/fxa/pull/7924/commits/1e73748e411d77ed8c644f2f8729610ee57f0cf5) which simpifes our `getCroppedImg` logic
- Set aspect ratio to 1 on cropper since it made testing a little easier
Closes: #7555
Closes: #7705
To test, open iOS simulator and goto settings page. Select and set image.
> fix(settings): Fix avatar black image on iOS

- packages/fxa-settings/src/lib/metrics.ts
Without the useRef the returned functions are new each time and therefore will get called for each render inside a useEffect.
fixes #7793
> fix(settings): useMetrics needs to useRef

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
Because:
* Invoices can remain open for non-currenct subscriptions and we should
only process invoices for current subscriptions.
This commit:
* Restricts the invoices located to be fulfilled to subscriptions that
are in an active status.
Closes #7941
> fix(auth-server): restrict invoices to currenct subs

- packages/fxa-payments-server/src/styles/_mixins.scss
Because:
- some text in the checkout process use a different, lighter, shade of
grey
This commit:
- change the grey to the same shade we've been using for checkout
Closes: #7810
> style(subscriptions): use the same shade of grey in checkout

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* The next_payment_attempt attribute of invoices is only for those that
Stripe charges for, resulting in a null for invoiced subscriptions.
This commit:
* Uses the proper created attribute of the invoice to reflect the actual
next invoice billing date.
Closes #7874
> fix: use created date on reactivate

- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
Fix `Error: Cannot find module 'fxa-auth-server/lib/payments/paypal-client'` while running in stage
> fix(import): Use relative import for production

- packages/fxa-payments-server/src/components/PaymentProviderDetails/index.scss
- We want the American Express logo to show up on the subscription confirmation and subscription information pages
- Adds a CSS rule to make the American Express logo visible
Closes: #7904 
.
> feature(payments): Fix missing American Express logo

- packages/fxa-shared/nestjs/sentry/sentry.plugin.ts
Because:
* ApolloErrors are user facing already and don't need to be reported to
Sentry.
This commit:
* Updates the error check to ensure the originalError is not an instance
of ApolloError.
Fixes #7647
> fix(gql): dont report apollo errors

- packages/fxa-auth-server/README.md
- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/test/local/senders/email.js
- packages/fxa-auth-server/test/remote/subscription_tests.js
- We have localized PDFs for legal documents, and there is a new redirect endpoint (#7688 ). The payments server links were updated in #7850 for this, and we should also update links in transactional emails.
- Updates legal URLs (links to product terms of service and privacy policy documents) in transactional emails.
- Removes one of the "Testing" sections in the README and updates a command/note for remote tests.
Closes: #7690 
> chore(auth): Update legal URLs in transactional emails

- packages/fxa-admin-panel/package.json
- packages/fxa-payments-server/package.json
- packages/fxa-react/package.json
- packages/fxa-settings/package.json
- yarn.lock
Going to try this PR again. I think it failed before because I tried submitting it from my own fork, but Storybook stuff needs to happen on the main repo.
Because:
- A major version upgrade to Storybook v6 requires more work
to migrate webpack customizations
This commit:
- reverts commit 37522c5a6c6a35a79c1da953c8995a43e8e665b9.
> chore(deps-dev): downgrade @storybook/react from 6.1.21 to 5.3.19

- packages/fxa-auth-server/lib/metrics/amplitude.js
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal-notifications.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/templates/_versions.json
- packages/fxa-auth-server/lib/senders/templates/subscriptionPaymentProviderCancelled.html
- packages/fxa-auth-server/lib/senders/templates/subscriptionPaymentProviderCancelled.txt
- packages/fxa-auth-server/lib/senders/templates/subscriptionsPaymentProviderCancelled.html
- packages/fxa-auth-server/lib/senders/templates/subscriptionsPaymentProviderCancelled.txt
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js
- packages/fxa-auth-server/test/local/senders/email.js
- packages/fxa-auth-server/test/mocks.js
Because:
- we should let a customer when their payment method for active
subscriptions has a problem
This commit:
- send an email on a billing agreement cancelled event from PayPal
This commit also changes the declarative email tests from a Map to an
array.  A previous patch (mistakenly) treated the tests as an array, and
this patch changes that list of tests to match.  The change to an array
allows multiple tests of the same mailer method, which we need in this
patch.
Closes: #7784
> feat(emails): add email for payment method cancellation

- packages/fxa-content-server/app/tests/spec/views/mixins/signed-in-notification-mixin.js
- packages/fxa-content-server/tests/functional.js
- packages/fxa-content-server/tests/functional/sign_up_with_code.js
Hitting the back button at the end of this particular test flow leaves you at the settings page, not the confirm page.
Fixes #7991.
> fix(tests): fix and re-enable sign_up_with_code.js

- packages/fxa-content-server/tests/functional.js
- packages/fxa-content-server/tests/functional/cookies_disabled.js
- packages/fxa-content-server/tests/functional/lib/helpers.js
Fixes #7980.
The error selector has been updated to the new-settings AlertBar, but sometimes we do hit an error on the sign in or sign up pages, as happened here. Might be worth extracting into lib/selectors?
> fix(tests): correct error selector in cookies_disabled test

- packages/fxa-content-server/tests/functional.js
* We have bugs filed for specific test failures, but most tests did pass
in the test run. Let's just re-enable everything except the broken
stuff.
* Since we are going back to a mostly-complete standard test run, also
stop running the smoke tests in the main suite.
> fix(tests): re-enable all but the broken functional tests

- packages/fxa-payments-server/src/components/AlertBar/index.scss
Because:
- the alert bar extends beyond the width of the content and would
overlap the Firefox Accounts heading
This commit:
- matches the width of the alert bar to the content, thus reducing the
potential overlaps
Note that this was not a bug; the alert bar has been styled that way
prior to the recent Subscription Platform changes.  Furthermore, there
will be follow-up changes to update the styles of the notifications.  In
other words, this change is likely fairly short-lived.
Closes: #7903
> style(subscriptions): match alert bar width to content

- packages/fxa-content-server/tests/functional.js
- packages/fxa-content-server/tests/functional/sign_in.js
- We want to get our functional tests passing
* Updated the sign out flow in one test
* Replaced a couple instances of querySelectorAll-based checks with
testElementExists checks. Seems like using QSA while the browser is
still navigating to the react settings app can trigger a crash in the
webdriver session :-\
Fixes #7985.
> fix(tests): get sign_in functional tests passing

- packages/fxa-content-server/tests/functional/settings_v2/display_name.js
- packages/fxa-settings/src/components/App/en-US.ftl
- packages/fxa-settings/src/components/BentoMenu/en-US.ftl
- packages/fxa-settings/src/components/BentoMenu/index.test.tsx
- packages/fxa-settings/src/components/BentoMenu/index.tsx
- packages/fxa-settings/src/components/DropDownAvatarMenu/en-US.ftl
- packages/fxa-settings/src/components/DropDownAvatarMenu/index.test.tsx
- packages/fxa-settings/src/components/DropDownAvatarMenu/index.tsx
- DropDownAvatarMenu and BentoMenu  were not localized
- Localizes them
Closes: #7939
Closes: #7938
> fix(l10n): Localize DropDownAvatarMenu and BentoMenu component

- packages/fxa-auth-server/lib/senders/templates/passwordChangeRequired.html
- packages/fxa-auth-server/lib/senders/templates/passwordChangeRequired.txt
- Improves the styling of the email template (passwordChangeRequired)
Closes #8011
> fix(fxa-auth-server): change email template

- packages/fxa-auth-client/lib/client.ts
- packages/fxa-settings/scripts/test-ci.sh
- packages/fxa-settings/src/components/ModalVerifySession/index.tsx
- packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.tsx
- packages/fxa-settings/src/components/PageChangePassword/index.tsx
- packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.tsx
- packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.tsx
- packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx
- packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx
- packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx
- packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
- packages/fxa-settings/src/lib/auth.ts
Because when auth-server sends mail it includes the geoip of the client in the message. Proxying through graphql caused it to use the server's ip address.
fixes #8038
> fix(settings): call direct to auth-server for changes that send email

- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/templates/postVerify.txt
- Changes "Setup " (which is a noun ) to "Set up" (which is a verb) in the post verify email template
Fixes #8012
> refactor(fxa-auth-server): update postVerify email template

- packages/fxa-content-server/tests/functional.js
This passes locally for me, not sure if there is a bug here.
Closes #7977.
> fix(tests): re-enable reset_password test

- packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
-
- Adds the correct redirection link for when the user clicks on 'Replacing your recovery codes' 2FA link in the Security section of Settings page
Closes: #8092 
> fix(Settings): Add correct 'Replacing your recovery codes' 2FA link

- packages/fxa-react/configs/tailwind.js
- packages/fxa-settings/src/components/Nav/index.tsx
* Indicates current user's location
* Adds grey background for blue category text
* Changes padding of that category
Closes: https://github.com/mozilla/fxa/issues/7757
> fix(fxa-settings): add background in menu category

- packages/fxa-auth-server/lib/error.js
- packages/fxa-auth-server/lib/payments/paypal.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-shared/subscriptions/stripe.ts
Because:
- a customer using PayPal as the payment provider should be able to
subscribe to more than one product
This commit:
- update the API to allow the frontend to create a new subscription
without creating a PayPal billing agreement first
This commit maintains the same API surface and branches on the now
optional PayPal payment token request payload value to
`/oauth/subscriptions/active/new-paypal`.
Closes: #7589
> feat(subscriptions): create subscriptions for existing PayPal customer

- packages/fxa-settings/src/components/InputPassword/index.tsx
- packages/fxa-settings/src/components/InputText/index.tsx
- To make the interface consistent
- Makes eye icon focus behavior consistent with Sign in page
Closes: https://github.com/mozilla/fxa/issues/8025
> fix(fxa-settings): make eye behavior for password consistent

- _scripts/clone-l10n.sh
The current script has quite some functional errors and shortcomings.
...fixes some functional issues, introduces new functionality useful for testing/debugging.
More specifically:
* fix checkout to a specific commit - with existing environment variable `FXA_L10N_SHA`
* fix script errors/warnings as reported by `shellcheck` and unify code style
New features:
* specify a different branch - env var `FXA_L10N_BRANCH`
* override Git repository URL (e.g. a fork for testing) - env var `FXA_L10N_REPO`
* support to just use a local directory as-is (existing clone) - env var `FXA_L10N_COPY_FROM`
* override directory into which the content is cloned/linked into - env var `FXA_L10N_DOWNLOAD_PATH`
Closes: #7767 
Output of `shellcheck -ax` of the existing script:
```
In _scripts/clone-l10n.sh line 9: …
```
> Enhance L10N handling

- packages/fxa-settings/src/components/BentoMenu/index.tsx
- Needed to add a focus effect on the Bento icon
- Adds the focus effect
Closes: #7706
> fix(fxa-settings): add focus effect to Bento icon

- packages/fxa-content-server/server/lib/csp/blocking.js
- packages/fxa-content-server/tests/server/csp.js
- packages/fxa-graphql-api/src/backend/profile-client.service.spec.ts
- packages/fxa-graphql-api/src/backend/profile-client.service.ts
- packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
- packages/fxa-graphql-api/src/gql/account.resolver.ts
- packages/fxa-profile-server/lib/db/mysql/index.js
- packages/fxa-profile-server/lib/routes/avatar/_shared.js
- packages/fxa-profile-server/lib/routes/avatar/default.js
- packages/fxa-profile-server/lib/routes/avatar/get.js
- packages/fxa-profile-server/lib/routes/profile.js
- packages/fxa-profile-server/lib/routing.js
- packages/fxa-profile-server/test/api.js
- packages/fxa-settings/src/components/Avatar/index.tsx
- packages/fxa-settings/src/components/PageAvatar/buttons.tsx
- packages/fxa-settings/src/components/PageAvatar/index.tsx
- packages/fxa-settings/src/components/PageDisplayName/index.tsx
- packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx
- packages/fxa-settings/src/lib/cache.ts
- packages/fxa-settings/src/models/Account.test.ts
- packages/fxa-settings/src/models/Account.ts
- packages/fxa-settings/src/models/_mocks.tsx
When an account has no avatar set we attempt to create a default avatar using the first letter of either display name or email address. These avatars use theme colors within the Firefox native UI and a neutral grey in web content and are served by the profile server.
To test with theme colors in Firefox change `svg.context-properties.content.enabled` to `true` in `about:config`.
> Default monogram avatar

- packages/fxa-auth-server/lib/payments/paypal.ts
- PayPal requests that result in errors need to be correctly tagged for metrics/alerting.
- Correctly sets the `error` type for the response timing metric to be `true` when there is an error in the PayPal response.
Closes: # No issue on file
> fix(auth): flip true/false value for errors on PayPal request metrics.

- packages/fxa-settings/src/components/Modal/index.tsx
- To fix the padding on Remove Recovery Key Modal
- Deletes the previous padding from body of recovery model.
- Adds padding to the modal container.  px-6 tablet:px-10
- Proper padding appears on all devices when checked with dev tools.
Closes: #7762
> fixed modal padding

- packages/fxa-react/configs/tailwind.js
- packages/fxa-settings/src/components/PageAvatar/buttons.tsx
-"Save" button changed its size during the saving process
-Removes strict padding
-Adds specific width
Closes:  https://github.com/mozilla/fxa/issues/7702
> fix(fxa-settings): make "Save" button stable

- packages/fxa-settings/src/components/PageAvatar/buttons.tsx
- Names of the buttons are too close to the icons
- Add margin-top to the button names
Closes: https://github.com/mozilla/fxa/issues/7413
> fix(fxa-settings): change Add Photo and Take photo buttons' styling

- packages/fxa-content-server/scripts/test-ci.sh
This would be helpful in tracking down circle ci errors
> fxa(chore): echo firefox version when running circle ci tests

- _dev/docker/circleci/Dockerfile
Attempting to build the circle-ci docker image locally, by going to `_dev/docker/circleci/` and doing `docker build -t "mozilla/fxa-circleci:latest" .`, fails because pip doesn't install properly.
@dannycoates pointed out that the installation process does work if we obtain pip from apt-get instead of easy_install 🧙, so let's make that change permanent
> fix(ci): The docker image should get pip from apt, not easy_install

- packages/fxa-settings/src/components/GetDataTrio/index.tsx
- Browser might not be able to open the file or detect the wrong file type
- Includes the email in the filename
Closes: #8180
> fix(bug): include email in filename for recovery keys/codes

- packages/fxa-content-server/tests/functional/settings_v2/connected_services_oauth_clients.js
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/components/ScrollToTop/index.tsx
- Open manage devices link from Firefox is broken (From within the Sync Tabs submenu)
- Adds a redirect from the legacy url `/settings/clients` to the new url `/settings#connected-services`
Closes: #8047
> fix(bug): Redirect to client/services page from legacy link

- packages/fxa-settings/src/components/PageDeleteAccount/en-US.ftl
- packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
- Dashboard in delete account on first step instead of button Cancel we had Close
- Change button Close to button Cancel
Closes: #7414
https://user-images.githubusercontent.com/76935202/113955314-d6060a80-985e-11eb-8b40-926ca21dd0db.mov
macOS Catalina
Google Chrome
> fix(fxa-settings):change Close button to Cancel in delete

- _dev/docker/mono/Dockerfile
I've noticed quite frequent complete server failures in a self-hosted environment (on Kubernetes) the last log messages containing:
```
Error: spawn ping ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
at onErrorNT (internal/child_process.js:465:16)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
Just makes sure that the `ping` utility is available in the Docker image, which solved the issue completely.
Closes: #7539
> [docker] Include the ping command

- packages/fxa-payments-server/server/lib/csp.test.js
- packages/fxa-payments-server/server/lib/csp/blocking.js
Because:
- payments server's CSP was blocking the new default avatar that's served
from the profile server
This commit:
- add the profile server to payments server's CSP's img-src directive
Closes: #8157
> fix(avatar): add profile server to payments img-src CSP

- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/templates/layouts/fxa.html
- Registration email pre-header is not very informative.
- Add a pre-header option to email template.
- Use the pre-header in the verify short code email. 
Closes: #7973
Hey folks, I have some questions about the changes. 
1. I didn't change the `.txt` file, because I didn't know if it was necessary. 
2. Should I add pre-headers in other emails? 
3. I was reading in this [blog post](https://www.activecampaign.com/blog/email-preheader) about pre-headers and it says it is good if the pre-header has 40-130 characters long. 
Should I add validation around this? 
Cheers!
> feat(email): add a pre-header option to email template

- packages/fxa-settings/src/components/GetDataTrio/index.tsx
- clicking on download button should display focus border, just like copy and print buttons
- add focus border to the recovery key download button, just like the copy and the print buttons
Closes: #8117 
> fix(fxa-settings): add focus border to download button

- packages/fxa-content-server/tests/functional.js
- packages/fxa-content-server/tests/functional/confirm.js
Fixes #7987.
The first test was failing the MX record check for restmail.dev.lcip.org, so I changed the email domain to restmail.net. Doesn't seem to break anything 🤷 
Also updated a success check to check for the old-style success element. Really looking forward to improving this API in #7882.
> fix(tests): fix and re-enable confirm.js functional test

- packages/fxa-content-server/tests/functional.js
- packages/fxa-content-server/tests/functional/sign_up.js
Updating the old sign out selector to the `signOut` helper seems to have fixed the bugs here.
Fixes #7988.
> fix(tests): fix and re-enable sign_up.js functional test

- packages/fxa-auth-server/lib/payments/paypal-error-codes.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
Because:
* We were rejecting Stripe payloads that exceeded 16Kb, some were as
large as 22Kb.
* Stripe webhooks that sent emails to customers who deleted their
account were throwing errors that Stripe keeps retrying.
This commit:
* Updates the maxBytes for the Stripe webhook to accomodate the larger
payload sizes observed.
* Adds error catching to the email calls in the webhooks to capture and
report errors that we expect (account deleted), but returns a proper
200 to Stripe.
Fixes #7203
> fix(auth-server): fix stripe webhook errors

- package.json
- A lot of the sign-in/sign-up functional tests go through various flows in new settings so we should ensure that both suites of tests run when a change occurs in either project
- Makes fxa-settings and fxa-content-server tests dependent on each other
Closes: NA
> fix(tests): Make fxa-settings and fxa-content-server tests dependent on each other

- packages/fxa-auth-server/lib/server.js
The error is being logged in Sentry for quite some time and very often:
```
TypeError: Cannot read property 'trim' of undefined
File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/server.js", line 180, col 35, in null.<anonymous>
.map((address) => address.trim())
?, in Array.map
File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/server.js", line 180, col 10, in null.<anonymous>
.map((address) => address.trim())
File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/server.js", line 377, col 17, in Object.get
value = getter();
File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/server.js", line 187, col 46, in null.<anonymous>
const remoteAddressChain = request.app.remoteAddressChain;
File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/server.js", …
```
> [fxa-auth-server]: Fix "Cannot read property 'trim' of undefined"

- packages/fxa-content-server/tests/functional.js
- packages/fxa-content-server/tests/functional/fx_desktop_handshake.js
- These tests were disabled after migrating to new settings
- Re-enables most of them however the others are broken because of https://github.com/mozilla/fxa/issues/8244
Closes: #7978
> fix(tests): Fix firefox handshake functional tests

- packages/fxa-settings/src/components/GetDataTrio/index.tsx
- 2FA icons do not have states
- Adds hover to the download/copy/print icons
Related: https://github.com/mozilla/fxa/issues/7025
> fix(fxa-settings): add 2FA icons states

- .vscode/settings.json
Because:
* The prod package build works different from stage in terms of yarn workspaces and namespaces.
This commit:
* Prevents VSCode from automatically using absolute imports in this situation.
> fix: Use relative imports within the same package.

- packages/fxa-shared/nestjs/sentry/reporting.ts
- packages/fxa-shared/nestjs/sentry/sentry.interceptor.ts
Because:
* We relay the exact response back from the RP we deliver to, and
the HttpException test only triggers if the data is present.
This commit:
* Changes the HttpException property testing to check if the properties
exist rather than their value.
Fixes #7067
> fix(auth-server): handle empty responses

- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/test/local/senders/email.js
Because:
- the url query parameter for the legal docs redirect endpoint links in
the subscription emails was not encoded correctly
This commit:
- encode the url query param as a URI component
Closes: #8268
> fix(emails): encode the legal docs redirect url query param correctly

- packages/fxa-auth-server/lib/metrics/events.js
Metrics flow ID's are usually not available (and not very helpful) for internal system-to-system communication.
Adds some fxa-auth-server resource paths commonly used by autonomous (and external-to-FxA) HTTP clients to the list of ignored paths for missing-metrics-flow logging:
* `/` - the root doesn't have any functionality other than presenting the version
* `/__version__` - fetching the version with `curl` shouldn't log an error
* `/__heartbeat__` - integrating health checks (Docker, Kubernetes, ...)
* `/__lbheartbeat__` - integrating health checks (Docker, Kubernetes, ...)
* `/jwks` - queried by the tokenserver (at least in self-hosted environments)
* `/introspect` - standard integration resource for external clients
Closes: #8234
> [fxa-auth-server] Avoid logging errors for missing metrics flow

- packages/fxa-auth-server/test/local/mailer_locales.js
- packages/fxa-react/lib/AppLocalizationProvider.tsx
- packages/fxa-shared/l10n/supportedLanguages.json
Because:
- we are using en-GB messages for en-CA even though we have
translations for en-CA
This commit:
- remove en-CA from the list of locales that falls back to en-GB
- add en-CA to the list of supported languages
Closes: #8204
> fix(l10n): use en-CA not en-GB for settings and payments

- packages/fxa-content-server/tests/functional.js
- packages/fxa-content-server/tests/functional/oauth_webchannel.js
- These tests were disabled
- Enables all oauth webchannel tests except the one test that is dependent on changes from https://github.com/mozilla/fxa/issues/8244
Closes: #7981
> fix(tests): Fix oauth webchannel tests

- packages/fxa-content-server/tests/functional.js
- packages/fxa-content-server/tests/functional/lib/selectors.js
- packages/fxa-content-server/tests/functional/oauth_permissions.js
Fixes 2 of 3 broken tests in #7983.
The remaining broken test is ` oauth permissions for untrusted reliers - signin with new permission available b/c of new account information`, moved into followup bug #8281.
> fix(tests): update selectors in oauth_permissions tests

- packages/fxa-auth-server/lib/payments/paypal-client.ts
- packages/fxa-auth-server/test/local/payments/paypal-client.js
Because:
* The default message for PayPalClientError doesn't provide any specific information about the error.
This commit:
* Adds the PayPal error code to the default PayPalClientError message.
Closes #8266
> chore(auth): append PayPalClientError message with PayPal error code

- packages/fxa-shared/nestjs/sentry/sentry.interceptor.ts
Because:
* Apollo Errors are already internally processed and used for control
flow. They should not be reported to Sentry as the underlying error
was already reported.
This commit:
* Properly ignores ApolloError's in the interceptor.
This is from Sentry: https://sentry.prod.mozaws.net/operations/fxa-graphql-prod/issues/10391832/
An issue was not filed.
> fix: stop reporting apollo errors

- packages/fxa-content-server/tests/functional/oauth_permissions.js
- packages/fxa-content-server/tests/functional/settings_v2/lib/helpers.js
- packages/fxa-settings/src/lib/cache.ts
- packages/fxa-settings/src/models/Account.ts
Ummmmmm. Local storage is not a good way to handle oauth permission prompts but fixing that is much different than fixing the test case.
fixes #8281
> fix(test): fix oauth functional test

- .circleci/config.yml
- we've got too many test failures due to slow rendering
> chore(ci): increase test-content-server-remote task to a large instance

- packages/fxa-content-server/tests/intern.js
- packages/fxa-settings/src/models/hooks.ts
Because the ModalVerifySession has a useEffect that depends on the session to send a verification email. Without this it could send multiple emails.
> fix(settings): ensure the object returned from useSession is stable

- packages/fxa-auth-server/config/index.ts
- This should actually be a regex value instead of a string
- Updates the default value be what is needed in the functional tests
Closes: NA
> fix(config): use a regex for default config values instead of string

- packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js
- packages/fxa-content-server/app/tests/spec/models/auth_brokers/oauth-redirect.js
Because:
* We want to retain UTM parameters through the OAuth flow.
This commit:
* Extracts URL keys beginning with utm_ to include on the final
redirect.
Closes #3412
> fix(content-server): retain utm_ parameters

- packages/fxa-profile-server/lib/routes/profile.js
- packages/fxa-profile-server/test/api.js
- packages/fxa-profile-server/test/profileCache.js
We weren't dropping the profileCache when the avatar was changing so subsequent requests would also think the avatar needed to change and would write to the db until something else triggered the cache to be updated.
This change ensures the cache is dropped when the avatar changes.
> fix(profile): drop profileCache if the avatar changes

- packages/fxa-settings/src/components/PageDeleteAccount/index.test.tsx
- packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
- “Delete account” button from Step 2 Delete account page enables when the password length is one or greater than one
- Intends to fix the above-mentioned issue by setting the minimum length of the password to be 8 for the button to get enabled
Closes: #7419
I'm creating a draft PR since I'm supposed to add tests for this issue which I will once I get my queries cleared.
> fix(Settings): Enable 'Delete Account' button when the password lenth is 8 or more

- packages/fxa-auth-server/lib/senders/templates/layouts/subscription.html
- packages/fxa-auth-server/test/local/senders/email.js
Because:
- we should use Mozilla's privacy notice page in the footer
subscription emails
This commit:
- update the url for the privacy notice link in the footer of
subscription emails
Closes: #8031
> fix(emails): use site privacy notice url not product privacy notice

- packages/fxa-content-server/tests/functional/lib/helpers.js
`data-shown` is no longer relevant to this function. The `reset_password` tests use it but there's no need to remove the attribute anymore.
closes #7882
> chore(settings): remove unused functional helper code

- packages/fxa-auth-server/README.md
- packages/fxa-auth-server/lib/verification-reminders.js
- packages/fxa-auth-server/test/local/db.js
- packages/fxa-auth-server/test/local/payments/stripe.js
I want to run test locally without the need to run databases at the developer machine.
Fixes some issues in tests for the fxa-auth-server package that prevented from configuring remote databases such as:
* MySQL
* Redis
* Memcached
Provides documentation about which concrete environment variables to export when running the tests.
Also fixed the many times (thousands at least) of these:
```
➤ YN0000: [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
➤ YN0000:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```
Caused by the verification reminder which always initialized Redis, no matter if an actual configuration was there or not.
Closes: #8316 
Documentation added for how to configure basic settings related to this.
Verified using Docker …
> Allow to use non-localhost databases

- packages/fxa-settings/src/components/HeaderLockup/en-US.ftl
- packages/fxa-settings/src/components/HeaderLockup/index.tsx
- The page header is at plural - 'Firefox Accounts' - has to be single "Firefox Account"
- Change plural header to single
Closes: #7676 
macOS Catalina
Google Chrome
> fix(fxa-settings):change plural header to single

- packages/fxa-payments-server/src/components/AppLayout/index.scss
Because:
- there was not enough contrast between the grey cancel button
background and the white spinner image
This commit:
- use another spinner image
Closes: #7898
> style(subscriptions): use different spinner in cancel btn

- package.json
- packages/123done/Procfile
- packages/123done/README.md
- packages/123done/config-local.json
- packages/123done/config-stage-untrusted.json
- packages/123done/config-stage.json
- packages/123done/config.js
- packages/123done/oauth.js
- packages/123done/package.json
- packages/123done/server.js
- yarn.lock
- 123done config is a bit outdated to support heroku
- If we go the route of hosting this service in heroku we will need to update AWS to point to new [trusted](stage-123done.herokuapp.com/) and [untrusted](http://stage-123done-untrusted.herokuapp.com/) versions.
- Exposes config the same way other services work
- Add docs for pushing 123done to heroku
Closes: #8491
> Update 123Done and add support for heroku

- packages/fxa-graphql-api/package.json
- yarn.lock
Reverts mozilla/fxa#8489
Connects to https://github.com/mozilla/fxa/issues/8493
> Revert "chore(deps): bump graphql-query-complexity from 0.8.0 to 0.8.1"

- packages/fxa-content-server/app/scripts/views/mixins/password-mixin.js
- Tooltip always has "Show" regardless of state
- Updates to say show or hide depending on tooltip state
Closes: #8068
> fix(tooltip): Show the correct hide/show tooltips on login pages

- packages/fxa-content-server/scripts/test-ci-remote.sh
- packages/fxa-content-server/tests/functional/lib/helpers.js
- packages/fxa-content-server/tests/functional/oauth_query_param_validation.js
- packages/fxa-content-server/tests/functional/settings/connected_services_oauth_clients.js
- packages/fxa-content-server/tests/functional_regression.js
- Paired with jbuck to get 123done setup properly in stage
- Our oauth tests were disabled for regression testing
- Re-enables oauth tests
Closes: #5291
> Re-enable oauth regression testing in stage

- packages/fxa-content-server/app/scripts/views/post_verify/cad_qr/scan_code.js
- packages/fxa-content-server/app/tests/spec/views/post_verify/cad_qr/scan_code.js
- Sms page wasn't loading on the Scan code page
- Moves attaching `click` events in the backbone initalize function
- Fixes a tiny edge case where page wouldn't generate QR if using unverified session
Closes: #8448 
> fix(sms): Fix sms link on QR CAD page

- packages/fxa-content-server/tests/functional/settings/change_email.js
- packages/fxa-content-server/tests/intern.js
- packages/fxa-settings/scripts/test-ci.sh
- Re-running failed test will better help confirm that the test is not flake
- Test failing in the `beforeEach` for functional tests were not marked as failures
- Re-runs those tests
- Marks `beforeEach` as failures
Closes: #8527
> fix(tests): rerun settings functional tests on failure and mark beforeEach as failure

- packages/fxa-auth-server/scripts/paypal-refund-fixer.ts
Because:
* Credit notes issued as account balance aren't refunded in paypal
correctly.
This commit:
* Locates invoices since launch that had a credit note applied that was
credited to the balance instead of refunded and fixes the balance,
issues a paypal refund, and cancels the subscription.
Closes #8544
> fix(auth-server): paypal customer fix script

- packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
fixes #7417
- Delete button on the page 2 of 2 of Delete Account page has a primary(blue) color.
- changes the color of the delete button
- adds cta-caution to delete button, similar to delete account link.
- has a proper display on all screen widths
Closes: #7417 
> fix(fxa-settings): changes the color of Delete Button

- packages/fxa-auth-db-mysql/lib/db/patch.js
- packages/fxa-auth-db-mysql/lib/db/schema/patch-115-116.sql
- packages/fxa-auth-db-mysql/lib/db/schema/patch-116-115.sql
- packages/fxa-auth-server/lib/metrics/amplitude.js
- packages/fxa-auth-server/lib/payments/processing-tasks-shared.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/payments/subscription-reminders.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/templates/_versions.json
- packages/fxa-auth-server/package.json
- packages/fxa-auth-server/scripts/paypal-processor.ts
- packages/fxa-auth-server/scripts/subscription-reminders.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/payments/subscription-reminders.js
- packages/fxa-shared/db/models/auth/sent-email.ts
- packages/fxa-shared/subscriptions/types.ts
- packages/fxa-shared/test/db/models/auth/sent-emails.spec.ts
Because:
* There is a legal requirement to send a reminder email two weeks before a subscription for a plan longer than 180 days is renewed.
This commit:
* Adds a new `subscription-reminder` script intended to be run on a (bi-)daily basis that queries active subscriptions with longer plan lengths and sends renewal reminder emails as needed.
* Adds `subscriptionRenewalReminder` emailType to `EmailTypes` table with forward and reverse migrations.
* The template for this email will be added in #8223.
Closes #8224
Co-authored-by: Barry Chen <chenba@gmail.com>
> feat(auth): create script to send subscription renewal reminder emails

- packages/fxa-auth-server/lib/senders/templates/subscriptionPaymentFailed.html
- packages/fxa-auth-server/lib/senders/templates/subscriptionPaymentFailed.txt
- packages/fxa-auth-server/test/local/senders/email.js
Because:
- the grace period mentioned in the failed payment email is no longer
accurate
This commit:
- update the failed payment email copy
Closes: #8355
> chore(emails): update copy for failed payment email

- packages/fxa-payments-server/server/lib/routes/legal-docs.js
Because:
- express's response's redirect function is not chainable and calls
end() within itself
This commit:
- stop chaining end to redirect
Closes: #8562
> fix(legal-docs): stop calling end on undefined

- packages/fxa-auth-server/lib/db/index.js
- packages/fxa-auth-server/lib/routes/attached-clients.js
- packages/fxa-auth-server/lib/routes/devices-and-sessions.js
- packages/fxa-auth-server/test/local/routes/attached-clients.js
- packages/fxa-auth-server/test/mocks.js
- Previously, the only time the "last access" value on a session token was updated was on the `/certification/sign` route which leads to confusing last accessed time
- Calls the `db.touchSessionToken` in the `/account/attach_devices` route to update the last used time
- This route is a lower volume route and should allow us to test out the overall performance
Closes: #7039
> fix(session): Update sessionToken data in redis when used by route

- packages/fxa-auth-server/bin/email_notifications.js
- The implementation of DB.connect changed in https://github.com/mozilla/fxa/pull/7652
> fix(auth): fixed email_notifications startup

- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
- users who are not authenticated should be allow to access product
plans
This commit:
- stop requiring an access token on the plans endpoint
Closes: #8598
> feat(subscriptions): allow plans list access without auth

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/payments/subscription-reminders.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/templates/subscriptionRenewalReminder.html
- packages/fxa-auth-server/lib/senders/templates/subscriptionRenewalReminder.txt
- packages/fxa-auth-server/scripts/write-emails-to-disk.js
- packages/fxa-auth-server/test/local/payments/subscription-reminders.js
- packages/fxa-auth-server/test/local/senders/email.js
Because:
* There is a legal requirement to send a reminder email two weeks before a subscription for a plan longer than 180 days is renewed.
This commit:
* Adds a new subscriptionRenewalReminder email template
* Sends the new email for a qualifying subscription as determined by #8224
Closes #8223
> feat(emails): add email for subscription renewal reminder

- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
fix(auth-server): refund deleted users
Because:
* We want to be able to refund users on PayPal even if they deleted
their account.
* We want to report an error if a credit note is issued as account
balance.
This commit:
* Ignores whether the Stripe user was deleted, and refunds the PayPal
transaction.
* Reports sentry error if the credit note is against account balance.
Closes #8715, #8714
> fix(auth-server): refund deleted users

- release-feature-branch.sh
- release.sh
Because:
* The release script was filtering updated GitHub issues for the past week rather than past two weeks (our current sprint length).
* The SubPlat team uses the `qa+` and `qa-` labels for QA rather than `needs:qa`
This commit:
* Replaces `A_WEEK_AGO` with `TWO_WEEKS_AGO`.
* Adds another QA section with a different GitHub link for the `qa+` label, since GitHub doesn't support the logical OR operator.
Closes # No ticket on file
> fix(release): fix Bugzilla template to filter issues for past two weeks

- packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js
- packages/fxa-content-server/app/scripts/models/reliers/relier.js
- packages/fxa-content-server/app/tests/spec/models/auth_brokers/oauth-redirect.js
- We want to retain flow parameters through the OAuth flow.
##This commit:
Extracts the flow params to include on the fina redirect.
> feat(content-server): return flow params to relier party

- packages/fxa-content-server/app/scripts/lib/payment-server.js
- packages/fxa-content-server/app/scripts/views/subscriptions_product_redirect.js
- packages/fxa-content-server/app/tests/spec/lib/payment-server.js
- packages/fxa-content-server/app/tests/spec/views/subscriptions_product_redirect.js
- packages/fxa-content-server/server/lib/configuration.js
Because:
- we want to enable people to sign up and subscribe on Payments in a
new checkout flow
This commit:
- allow unauthenticated redirects to the product route on Payments from
content-server
- add a feature flag to toggle the behavior (default is off)
Closes: #8571
> feat(subscriptions): allow redirects to Payments without token

- packages/fxa-auth-server/lib/push.js
- packages/fxa-auth-server/lib/routes/session.js
- packages/fxa-auth-server/test/local/routes/session.js
- packages/fxa-auth-server/test/mocks.js
-  We need a way for a user to trigger sending a push notification to verify a login
- Adds basic support for sending the login verificatio push notification
- Passes location, UA, IP as url params because this will allow us from having to add a new push notifiation type on desktop client
Closes: https://github.com/mozilla/fxa/issues/4778
> feat(push): Add basic support for verifying a login via push

- packages/fxa-auth-server/lib/db/index.js
- packages/fxa-auth-server/lib/luaScripts/touchSessionToken_1.lua
- packages/fxa-auth-server/lib/routes/attached-clients.js
- packages/fxa-auth-server/test/local/redis.js
- packages/fxa-auth-server/test/local/routes/attached-clients.js
- packages/fxa-auth-server/test/remote/db_tests.js
- Active sessions in device manager is showing "Boardman, OR, United States" for some devices, this is an AWS server that the gql request is coming from
- ~~Targeting as a point release on train 207 since it is a regression~~ Changin to main branch and will do a cherry pick to train-207
- Add support to only update the last access time property of a session token
Closes: TBD
> fix(sessions): Add support for touchSessionToken to only update the lastAccess session property

- packages/fxa-auth-server/lib/db/index.js
- packages/fxa-auth-server/test/local/db.js
- packages/fxa-shared/db/models/auth/account-reset-token.ts
- packages/fxa-shared/db/models/auth/account.ts
- packages/fxa-shared/db/models/auth/auth-base.ts
- packages/fxa-shared/db/models/auth/device.ts
- packages/fxa-shared/db/models/auth/key-fetch-token.ts
- packages/fxa-shared/db/models/auth/password-change-token.ts
- packages/fxa-shared/db/models/auth/password-forgot-token.ts
- packages/fxa-shared/db/models/auth/recovery-key.ts
- packages/fxa-shared/db/models/auth/session-token.ts
- packages/fxa-shared/db/models/auth/totp-token.ts
- packages/fxa-shared/db/mysql.ts
This is a continuation of #7652. It moves where the create and delete queries are executed from the auth-db-server to the auth-server via fxa-shared.
> refactor(db): move more auth-db functions into fxa-shared

- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.scss
- packages/fxa-payments-server/src/routes/Product/index.tsx
- we need to allow users to view the upgrade page in a non broken way :)
- updated Product/SubscriptionCreate/index.scss to account for layout
differences with the `grid` rule. We needed different ratios based on
whether `.subscription-title` section was present or not.
Closes: #5369 
Closes: #7805
product page desktop
product page mobile
upgrade page desktop
upgrade page mobile
> fix(fxa-payments-server): fix upgrade view layout

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
- This patch aims to eliminate any language around "upgrading" or
"downgrading" plans or products. This allows more flexibility for
user's changing plans/products without creating extra complexity for us
in determining which UI to show.
- `upgrade` 👉 `change`
Closes: #5521
> task(fxa-payments-server): update to change copy

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
Because:
- some Stripe webhook requests were failing because their payload size
larger than our endpoint's limit
This commit:
- make the payload limit configurable
- set the default to 1MB
Closes: #8861
> fix(subscriptions): increase webhook payload limit

- docs/adr/0024-upgrade-templating-toolset-of-auth-server-emails.md
- We want to revamp `fxa-auth-server` emails as the current templating stack doesn't allow us to include logic and the styling is done using inline styles.
- This PR contains an architectural document enlisting the alternatives that we could use for our templating stack to eliminate the cumbersome nature of emails.
Closes: #8600 
> docs(adrs): proposal for "Upgradation of Auth server email templating toolset"

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/taxRateDe.json
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/taxRateFr.json
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* We want to have tax rates available to add to subscriptions when
they're created.
This commit:
* Adds a tax rate helper function to StripeHelper.
Closes #8893
> feat(auth): add tax rate retrieval functions

- packages/fxa-graphql-api/src/gql/account.resolver.ts
- packages/fxa-graphql-api/src/gql/session.resolver.ts
- packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx
- packages/fxa-settings/src/lib/auth-errors/auth-errors.ts
- packages/fxa-settings/src/lib/auth-errors/en-US.ftl
- We didn't show a localized rate limit in the new settings
- Add support to localize our rate limit when creating a recovery key
Closes: #9322
> Localize our rate limit on adding recovery key in new settings

- packages/fxa-react/configs/tailwind.js
-Check shade/opacity of confirmation pointer thingy
-solves the above bug
Closes: #9156
- [x ] My commit is GPG signed.
> Bug No. 7766 is resolved

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/server/config/index.js
- packages/fxa-payments-server/src/components/PaymentErrorView/index.test.tsx
- packages/fxa-payments-server/src/components/PaymentErrorView/index.tsx
- packages/fxa-payments-server/src/components/SubscriptionTitle/index.test.tsx
- packages/fxa-payments-server/src/components/SubscriptionTitle/index.tsx
- packages/fxa-payments-server/src/lib/errors.ts
- packages/fxa-payments-server/src/lib/test-utils.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionChangeRoadblock/index.stories.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionChangeRoadblock/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionChangeRoadblock/index.tsx
- packages/fxa-payments-server/src/routes/Product/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/index.tsx
- packages/fxa-shared/subscriptions/stripe.ts
- packages/fxa-shared/subscriptions/types.ts
- packages/fxa-shared/test/subscriptions/stripe.ts
Because:
- we want to allow upgrades between plans of the same "product set"
This commit:
- determine subscription plan upgrade eligibility with the coalesced
product+plan metadata, where
- the plans must have the same 'productSet' value
- the plans must have different 'productOrder' values
- the new plan must have a higher 'productOrder' than the existing
plan
- remove the subscription upgrade feature flag and the roadblock screen
- add roadblock screen for plan changes that are not upgrades
Closes: #9351
> feat(subscriptions): update sub plan upgrade eligibility logic

- packages/fxa-content-server/app/scripts/lib/experiment.js
- packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/index.js
- packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/push.js
- packages/fxa-content-server/app/scripts/views/mixins/push-login-experiment-mixin.js
- packages/fxa-content-server/app/scripts/views/mixins/signin-mixin.js
- packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/index.js
- packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/push.js
- packages/fxa-content-server/app/tests/spec/views/mixins/signin-mixin.js
- packages/fxa-content-server/app/tests/test_start.js
- packages/fxa-content-server/tests/functional.js
- packages/fxa-content-server/tests/functional/lib/selectors.js
- packages/fxa-content-server/tests/functional/push.js
- We need to be able to control the rollout of this feature
- To test, log into sync with new FF profile, then in new FF profile open http://localhost:3030/?context=fx_desktop_v3&entrypoint=fxa_discoverability_native&action=email&service=sync&forceExperiment=pushLogin&forceExperimentGroup=treatment and login with same account
- Adds a feature flag and rollout config
- Adds supporting functional tests
Closes: https://github.com/mozilla/fxa/issues/9580
> Add feature flag for 2FA via push

- packages/fxa-auth-server/lib/payments/currencies.ts
- Adds CHF to hardcoded paypal currency
- Targetted as point release for 208. Needs to be merged and tag before we tag 209 train
Closes: TBD
> fix(stripe): Enable CHF currency in paypal

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
* We want to apply tax rates to subscriptions based on the subcribers
billing country.
This commit:
* Uses the country code looked up to find a Stripe tax rate for the
country and apply it to the subscription.
Closes #9388
> feat(auth): add tax rate on sub create

- packages/fxa-auth-server/lib/routes/session.js
- As is the case with `/recovery_email/resend_code` this is unnecessary
> fix(auth): don't resend session otp codes when totp is enabled

- packages/fxa-auth-server/lib/senders/emails/partials/appBadges.ts
- packages/fxa-auth-server/lib/senders/emails/partials/button.ts
- packages/fxa-auth-server/lib/senders/emails/preview-in-maidev.ts
- packages/fxa-auth-server/lib/senders/emails/render-to-disk.ts
- packages/fxa-auth-server/lib/senders/emails/renderer.ts
- packages/fxa-auth-server/lib/senders/emails/styles.ts
- packages/fxa-auth-server/lib/senders/emails/templates/cadReminder.ts
- packages/fxa-auth-server/lib/senders/emails/templates/index.ts
- packages/fxa-auth-server/package.json
- yarn.lock
- In regards to the decision taken in the [ADR](https://github.com/mozilla/fxa/blob/main/docs/adr/0024-upgrade-templating-toolset-of-auth-server-emails.md), we wanted to setup a new templating stack for our auth-server emails
- Includes packages and scripts for the new templating toolkit that could be used to develop emails
Closes: #9689 
> feat(auth-server) : Setup EJS+MJML templating solution in fxa-auth-server

- packages/fxa-auth-server/lib/senders/email.js
- The Mozilla VPN 'Quicker to Value' team needs to better understand what contributes to subscriber turnover. They've created a new exit survey and would like subscription cancellation emails to point to this new survey.
- Updates the link in subscription cancellation emails (`link.cancellationSurveyUrl`) to the new exit survey.
An issue wasn't filed for this change 
> feat(emails) - Update VPN exit survey URL

- packages/fxa-content-server/app/scripts/views/subscriptions_product_redirect.js
- packages/fxa-content-server/app/tests/spec/views/subscriptions_product_redirect.js
Because:
- we allow people to check out without signing in so that they can sign
up during checkout, but we also need to have a way for current users
to sign in
This commit:
- add a query param to signal to the checkout link to force sign in
Closes: #9759
> feat(subscriptions): add query param to force sign in on checkout link

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/templates/subscriptionFirstInvoice.html
- packages/fxa-auth-server/lib/senders/templates/subscriptionFirstInvoice.txt
- packages/fxa-auth-server/lib/senders/templates/subscriptionSubsequentInvoice.html
- packages/fxa-auth-server/lib/senders/templates/subscriptionSubsequentInvoice.txt
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/event_invoice_paid_with_vat.json
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/senders/email.js
Because:
* VAT customers need a receipt that includes a VAT breakdown.
This commit:
* Adds a link to the invoice emails to view the Stripe hosted invoice
that includes VAT information.
Closes #9329
> feat(auth): include invoice link in emails

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/features.js
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/test/local/features.js
- We need a feature flag to quickly and easily test the new mjml rendered email templates
- Allows you to specify which email template and which emails get the feature
Closes: https://github.com/mozilla/fxa/issues/9252
> feat(emails): Add mjml feature flag

- packages/fxa-payments-server/src/components/PayPalButton/index.stories.tsx
- packages/fxa-payments-server/src/components/PayPalButton/index.test.tsx
- packages/fxa-payments-server/src/components/PayPalButton/index.tsx
- packages/fxa-payments-server/src/lib/AppContext.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
Because:
- the idempotency key used for Stripe requests was not updated
between PayPal subscription attempts
This commit:
- refresh the idempotency key in the PayPal button callback
Closes: #9345
> fix(subscriptions): update idempotency key on PayPal btn callback

- packages/fxa-payments-server/src/App.tsx
- packages/fxa-payments-server/src/components/PlanErrorDialog/index.stories.tsx
- packages/fxa-payments-server/src/components/PlanErrorDialog/index.test.tsx
- packages/fxa-payments-server/src/components/PlanErrorDialog/index.tsx
- packages/fxa-payments-server/src/lib/plan.ts
- packages/fxa-payments-server/src/lib/test-utils.tsx
- packages/fxa-payments-server/src/lib/types.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.scss
- packages/fxa-payments-server/src/routes/Checkout/index.stories.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.test.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.stories.tsx
- packages/fxa-payments-server/src/routes/Product/index.stories.tsx
- packages/fxa-payments-server/src/routes/Product/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/index.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/index.tsx
- packages/fxa-payments-server/src/store/sequences.ts
Because:
* We are creating a [passwordless flow](https://mozilla-hub.atlassian.net/browse/FXA-3486) for new users to sign up for a subscription.
This commit:
* Creates a new {payments-server}/checkout/:productid route; this is where the new flow ([designs](https://www.figma.com/file/cOIAuHIIbrPbAlAIcpejNM/%F0%9F%8E%A1MVP-Subscription-Optimization-Flow?node-id=400%3A2098)) will live.
Closes #9701
To try this out, you can go to http://localhost:3031/checkout/{productId}. It's just an empty page right now that will display the `selectedPlan` if available, else a plan error.
> feat(payments): create new Checkout route for unauthenticated users

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
* We want to add a tax ID to customer invoices.
This commit:
* Adds the tax id as a custom field so it will show up on customers
in VAT countries such using currency such as EUR and CHF.
Closes #9825
> feat(auth): add tax ID to customer invoices

- packages/fxa-auth-server/.storybook/main.js
- packages/fxa-auth-server/.storybook/preview.js
- packages/fxa-auth-server/bin/mjml-server.ts
- packages/fxa-auth-server/lib/senders/emails/partials/appBadges.ts
- packages/fxa-auth-server/lib/senders/emails/partials/button.ts
- packages/fxa-auth-server/lib/senders/emails/preview-in-maildev.ts
- packages/fxa-auth-server/lib/senders/emails/render-to-disk.ts
- packages/fxa-auth-server/lib/senders/emails/renderer.ts
- packages/fxa-auth-server/lib/senders/emails/storybook-email.ts
- packages/fxa-auth-server/lib/senders/emails/styles.ts
- packages/fxa-auth-server/lib/senders/emails/templates/cadReminder/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/cadReminder/index.ts
- packages/fxa-auth-server/package.json
- yarn.lock
- We want a state previewing solution for our fxa-auth-sever emails
- Aims to include packages and files that could be used to preview the email templates with Storybook
Closes: #9244 
> feat(fxa-auth-server): Setup storybook to preview auth-sever emails

- packages/fxa-auth-db-mysql/lib/db/patch.js
- packages/fxa-auth-db-mysql/lib/db/schema/patch-117-118.sql
- packages/fxa-auth-db-mysql/lib/db/schema/patch-118-117.sql
- packages/fxa-auth-server/lib/metrics/amplitude.js
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/templates/_versions.json
- packages/fxa-auth-server/lib/senders/templates/subscriptionFailedPaymentsCancellation.html
- packages/fxa-auth-server/lib/senders/templates/subscriptionFailedPaymentsCancellation.txt
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
- packages/fxa-auth-server/test/local/senders/email.js
- packages/fxa-auth-server/test/mocks.js
Because:
- we should let a customer know that their subscription was canceled
due to failed payments
This commit:
- send an email on a subscription deleted event if the deletion is not
from an account deletion or customer initiated cancelation
Closes: #9172
> fix(emails): send email for cancelation due to failed payments

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
- a change in Stripe API removed subscriptions from a retrieved
customer
This commit:
- expand 'subscriptions' on a customer when `expandResource` is used to
retrieve a Stripe customer
Closes: #9837
> fix(subscriptions): include subscriptions when retrieving a customer

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/scripts/populate-vat-taxes.ts
Because:
* The tax ID may change, requiring all customers to get the new default
custom field.
* An incorrect tax rate might be deployed causing new customers to have
the wrong tax added to their subscription.
This commit:
* Will check the prior tax id value to the current one so updates will
be made if they don't match.
* Checks the current tax on the subscription and updates it if
necessary.
> fix(auth): update vat populate script to handle change

- packages/fxa-content-server/tests/functional/lib/helpers.js
Because:
- a functional test was expecting the user to sign in and be redirected
to the specified product page on Payments, but in some environments
we allow user to continue to Payments without signing in first,
causing Payments to take the user to Settings.
This commmit:
- fix the test by forcing the user to sign in before going to Payments
> fix(tests): force signin on subscription functional tests

- packages/fxa-content-server/app/scripts/lib/router.js
- packages/fxa-content-server/app/scripts/lib/validate.js
- packages/fxa-content-server/app/scripts/models/verification/set-password.js
- packages/fxa-content-server/app/scripts/templates/post_verify/finish_account_setup/set_password.mustache
- packages/fxa-content-server/app/scripts/views/post_verify/finish_account_setup/set_password.js
- packages/fxa-content-server/app/tests/spec/views/post_verify/finish_account_setup/set_password.js
- packages/fxa-content-server/app/tests/test_start.js
- packages/fxa-content-server/server/lib/routes/get-frontend.js
- We need need a dedicated view for users to set the password on accounts created without a password
- Adds new screens
- Checks for valid query params
- token (password forgot token)
- code (account reset code)
- email
- redirectUrl
- If email are not valid redirects to standard account create page
Closes: https://github.com/mozilla/fxa/issues/9301
Based on UX at https://www.figma.com/file/cOIAuHIIbrPbAlAIcpejNM/%F0%9F%8E%A1MVP-Subscription-Optimization-Flow
While all the parts to the passwordless account creation is not completed, we can still test the set password bits with these steps.
* Create an account but do not verify it
* Initiate a password reset flow and get the reset url
* Copy the `token=sometoken&code=somecode` bits from the reset url
* Open url …
> feat(passwords): Add initial view for finishing setup of passwordless accounts

- packages/fxa-payments-server/src/App.tsx
- packages/fxa-payments-server/src/index.tsx
- packages/fxa-payments-server/src/lib/AppContext.test.tsx
- packages/fxa-payments-server/src/lib/AppContext.tsx
- packages/fxa-payments-server/src/lib/hooks.tsx
- packages/fxa-payments-server/src/lib/test-utils.tsx
- packages/fxa-payments-server/src/routes/Product/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/index.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/index.test.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/index.tsx
Because:
- we want some routes in Payments to be accessible without a valid
access token
This commit:
- stop immediately redirecting to Settings when there is no valid
access token on a Payments page load
- store the access token in the AppContext
- check for a valid access token in the products and subscriptions
routes and redirect to the correct content-server route (instead of
Settings)
Closes: #9792
> refactor(payments): check for access token in routes

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/db/index.js
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/routes/account.js
Enables subscription services to create an account without a password.
closes #9327
> feat(auth): add /account/stub route

- packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.tsx
- packages/fxa-settings/src/lib/auth-errors/en-US.ftl
- We were not localizing text in add secondary email page
- Passes the `retryAfter` value to fluent
- Also updates our comment to mention the momentjs automatically adds the `in` string when a timestamp is in the future. Ref https://momentjs.com/docs/#/displaying/fromnow/
Closes: https://github.com/mozilla/fxa/issues/9874
> fix(errors): Fix issue where rate limit was not being localized

- packages/fxa-auth-db-mysql/lib/db/patch.js
- packages/fxa-auth-db-mysql/lib/db/schema/patch-118-119.sql
- packages/fxa-auth-db-mysql/lib/db/schema/patch-119-118.sql
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/metrics/amplitude.js
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/templates/_versions.json
- packages/fxa-auth-server/lib/senders/templates/partials/paymentPlanDetails.html
- packages/fxa-auth-server/lib/senders/templates/subscriptionAccountFinishSetup.html
- packages/fxa-auth-server/lib/senders/templates/subscriptionAccountFinishSetup.txt
- packages/fxa-auth-server/test/local/senders/email.js
- Users should recieve an email with information on how to finsh setting up their account (create new password)
- Adds the email template based on https://www.figma.com/file/cOIAuHIIbrPbAlAIcpejNM/%F0%9F%8E%A1MVP-Subscription-Optimization-Flow?node-id=315%3A12945
- Added migration for new template `subscriptionAccountFinishSetup`
Closes: https://github.com/mozilla/fxa/issues/9330
Current template
> feat(emails): Add the finish account setup email for passwordless accounts

- docs/adr/0026-expand-subscription-platform-metadata.md
Because:
* we want to use more metadata than the limit Stripe placed on its
metadata
This commit:
* add an ADR to document our choices and decisions
> chore(adr): add ADR for expanding subplat metadata

- packages/fxa-payments-server/src/components/NewUserEmailForm/index.stories.tsx
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
- We need to validate the new user email
- Adds validation checks to the email input on new user form
- Adds a check to ensure the confirm input matches the original email value
Closes: #9354
Luckily our email validation method was in `fxa-shared` which saved a lot of time.
> task(fxa-payments-server) Add email validation

- packages/fxa-content-server/app/scripts/templates/post_verify/finish_account_setup/set_password.mustache
Matches how we use `Continue to ...` in our other views.
Fixes https://github.com/mozilla/fxa/issues/9937
> fix(l10n): Update `continue to ...` text to match other usages

- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-auth-server/test/local/routes/validators.js
- `fetchAllPlans` won't return a `plan` if it fails validation, and we have a `plan` in prod with no `product:privacyNoticeDownloadURL`.
- Uplift a patch that ensures all prod plans are correctly returned by cherry-picking a patch that makes this property optional.
Closes: (See original PR: #9927 )
> Train 211.1 uplift

- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/firestore-db.ts
- packages/fxa-auth-server/lib/payments/google-iap.ts
- packages/fxa-auth-server/lib/types.ts
- packages/fxa-auth-server/package.json
- packages/fxa-auth-server/test/local/payments/google-iap.js
- yarn.lock
Because:
* We want to support Google IAP data using Firestore.
This commit:
* Sets up a Google IAP service class that uses Firestore.
Closes #9878
> feat(auth): add google iap service class

- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/docs/api.md
- packages/fxa-auth-server/lib/payments/firestore-types.ts
- packages/fxa-auth-server/lib/payments/google-iap.ts
- packages/fxa-auth-server/lib/routes/subscriptions/google.ts
- packages/fxa-auth-server/lib/routes/subscriptions/index.ts
- packages/fxa-auth-server/lib/types.ts
- packages/fxa-auth-server/test/local/payments/google-iap.js
- packages/fxa-auth-server/test/local/routes/subscriptions/google.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
* We want to provide the available plans for Android clients.
This commit:
* Adds an unauthenticated endpoint for Android clients to use that will
fetch a maintained list of available subscription plans.
> feat(auth): add google plans endpoint

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.stories.tsx
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
- packages/fxa-payments-server/src/components/fields/index.tsx
- We want to know if a user in this flow has an account and just isn't signed in.
- Adds the check for the user input email to see if they have an existing account.
- (Sign up link in error tooltip will be added in https://mozilla-hub.atlassian.net/browse/FXA-3664)
Closes: #9385
Additional Information:
- This builds on https://github.com/mozilla/fxa/pull/9913, so is dependent on that being merged first
- The commit with relevant changes 👉 https://github.com/mozilla/fxa/pull/9924/commits/678c6f720874c250ed293fdad252bf2c05d97c17
> 9385 check account existance

- packages/fxa-auth-server/lib/senders/email.js
- We'd like to gather information from people who have cancelled their VPN subscription and use that information to inform future product improvements and feature development.
- Changes the survey link in subscription exit emails to point to a newly created survey
Closes: No issue was filed for this change
>  feat(emails)- Update exit survey link in subscription exit emails

- packages/fxa-content-server/app/scripts/lib/payment-server.js
- packages/fxa-content-server/app/scripts/views/subscriptions_product_redirect.js
- packages/fxa-content-server/app/tests/spec/lib/payment-server.js
- packages/fxa-content-server/app/tests/spec/views/subscriptions_product_redirect.js
Because:
* There is a new Checkout route on the payments server for unauthned users that will create a FxA account (if none exists) at the same time as creating a new subscription.
This commit:
* Conditionally sets the redirectPath for redirecting to the payments server based on a user's authn state and the subscriptionsConfig.allowUnauthenticatedRedirects flag.
* The latter will ensure that we do not redirect unauthned users in prod to the new checkout route until we are ready to do so.
Closes #9793
I filed [FXA-3790](https://mozilla-hub.atlassian.net/browse/FXA-3790) to set `allowUnauthenticatedRedirects` to `true` in `prod` as it is [currently only enabled in `dev` and `stage`](https://github.com/mozilla-services/cloudops-deployment/pull/4335) for …
> feat(content): redirect to new checkout route for unauthenticated users

- packages/fxa-admin-panel/tsconfig.json
- packages/fxa-auth-server/lib/routes/emails.js
- packages/fxa-auth-server/test/local/routes/emails.js
- Users should not be able to change their primary email if the account has no password set. In practice I don't think this flow would be accessible, but wouldn't hurt to be explict in the endpoint.
- Checks that user has set password else throws errro
- Renames variables to make things clearer on what is happening
Closes: https://github.com/mozilla/fxa/issues/9730
> feat(passwords): Ensure password set on account before changing primary

- packages/fxa-content-server/app/scripts/models/account.js
- packages/fxa-content-server/app/tests/spec/models/account.js
- Only fair to fix some sentry errors if we will be adding some 
- Adds `ifNoneMatch` when no anon id is set
- From [here](https://github.com/mozilla/fxa/blob/f88701a3a7978557236a4fbe41f3fe156d4d6379/packages/fxa-auth-server/lib/routes/account.ts#L1480) it seems like we need to specify `*` to fail on any exisitng id
Closes: https://github.com/mozilla/fxa/issues/9106
> fix(sentry): Add ifNoneMatch when setting new anonId

- packages/fxa-content-server/app/scripts/views/inline_totp_setup.js
This sentry event https://sentry.prod.mozaws.net/operations/fxa-content-client-prod/issues/10992802/events/3323a6cddda74ce2b23852828b802b65/
is caused by a session being in an unverified state when the flow first starts. Here we were checking for the sessionToken and navigating, but also continuing to execute the sessionVerificationStatus which threw and error. It was benign but still sent it to sentry.
> fix(content): fix inline totp edge case

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/routes/subscriptions/utils.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- packages/fxa-auth-server/test/local/routes/support.js
- packages/fxa-auth-server/test/remote/subscription_tests.js
- packages/fxa-content-server/server/lib/configuration.js
- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/server/config/index.js
- packages/fxa-payments-server/server/lib/server.js
- packages/fxa-payments-server/src/lib/account.test.ts
- packages/fxa-payments-server/src/lib/account.ts
- packages/fxa-payments-server/src/lib/amplitude.test.ts
- packages/fxa-payments-server/src/lib/amplitude.ts
- packages/fxa-payments-server/src/lib/apiClient.test.ts
- packages/fxa-payments-server/src/lib/apiClient.ts
- packages/fxa-payments-server/src/lib/config.test.ts
- packages/fxa-payments-server/src/lib/config.ts
- packages/fxa-payments-server/src/lib/errors.ts
- packages/fxa-payments-server/src/lib/stripe.test.ts
- packages/fxa-payments-server/src/lib/stripe.ts
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.stories.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- packages/fxa-shared/oauth/constants.js
Because:
- we need to create an account and then subscribe to a plan for a new
Payments route
This commit:
- add the Payments OAuth client id as a config
- add functions for creating the passwordless account and setting the
access token for the API client
- add a function that can be used in callbacks to create an account and
then subscribe to a plan with Stripe payments
part of #9358
> feat(subscriptions): create acct and subscribe with Stripe

- packages/fxa-auth-server/lib/routes/subscriptions/utils.ts
Not sure how I missed that one spot.  But the subscription management scope was moved into a shared constant and renamed, and somehow I changed just one of two instances it in a particular file.
> chore(subscriptions): fix a scope rename that should've been in 3ced8935b

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/lib/apiClient.test.ts
- packages/fxa-payments-server/src/lib/apiClient.ts
- packages/fxa-payments-server/src/lib/config.test.ts
- packages/fxa-payments-server/src/lib/config.ts
- packages/fxa-payments-server/src/lib/errors.ts
- packages/fxa-payments-server/src/lib/newsletter.test.ts
- packages/fxa-payments-server/src/lib/newsletter.ts
Because:
-  When a new user is subscribing to a product, we want to provide an easy way for them to sign up for our products newsletter at the same time.
This commit:
- Adds the handleNewsletterSignup helper function and apiSignupForNewsletter method to the payments client.
- This function will be called in the Stripe and Paypal onSubmit handlers to be added to the new Checkout route in #9358.
part of #9786 
While this PR has no dependencies, ultimately closing #9786 depends on #9750 and #9358 , as I will need to do the following in the Checkout route in a subsequent patch:
* Add a `useState` hook to the newsletter sign up checkbox in `NewUserEmailForm`
* Pass the state update function down into `NewUserEmailForm` (to be included in the route in #9750 ) and
* Conditionally call …
> feat(payments): add newsletter signup helper functions and config

- packages/fxa-payments-server/src/components/PayPalButton/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
Because:
- we need a way to create a Firefox account before the PayPal button
gets the PayPal checkout token
This commit:
- add an optional callback to PayPalButton's props that's called at the
start of its createOrder function
part of #9358; follows #10007
> feat(subscriptions): add an optional cb called in PayPal's createOrder

- packages/fxa-content-server/app/scripts/templates/complete_reset_password.mustache
- packages/fxa-content-server/app/scripts/templates/reset_password.mustache
- Some users might be confused about subscriptions and reset password
- Updates reset password copy to mention what happens to subscriptions
Closes: https://github.com/mozilla/fxa/issues/9900
> chore(copy): Update reset password copy

- packages/fxa-payments-server/src/components/NewUserEmailForm/index.stories.tsx
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
- packages/fxa-payments-server/src/components/PayPalButton/index.scss
- packages/fxa-payments-server/src/components/PayPalButton/index.stories.tsx
- packages/fxa-payments-server/src/components/PayPalButton/index.test.tsx
- packages/fxa-payments-server/src/components/PayPalButton/index.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx
- We need to disable the paypal button if the consent checkbox is not checked
- Add styling for the disabled paypal button
- watches for changes and disables/enables the paypal button
Closes: #9361
> task(fxa-payments-server): paypal button disable

- packages/fxa-auth-server/README.md
- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/fluent-localizer.ts
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.ts
- packages/fxa-auth-server/lib/senders/emails/partials/appBadges/index.ts
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
- auth-server email docs needed a little update and there were some formatting nits pending
- Updates the docs and corrects the formatting
Closes: #10064 
> style(auth-server): update docs and formatting nits

- packages/fxa-payments-server/src/routes/Checkout/index.tsx
Because:
* If we are going to pass along a plan queryParam for signInURL in the Checkout route, it should not be undefined.
This commit:
* Omits the plan queryParam if it is undefined.
* Note: If the plan queryParam is undefined, selectedPlan will be the first plan in the list of plans for the given product ID.
Closes #10076
> fix(payments): ensure plan is never undefined in Checkout signInURL

- packages/123done/static/index.html
- packages/123done/static/js/123done.js
- packages/fxa-metrics-processor/src/lib/amplitude/transforms/event-properties.ts
- packages/fxa-metrics-processor/src/lib/amplitude/transforms/types.ts
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.stories.tsx
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
- packages/fxa-payments-server/src/lib/amplitude.test.ts
- packages/fxa-payments-server/src/lib/amplitude.ts
- packages/fxa-payments-server/src/lib/flow-event.ts
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
- packages/fxa-shared/metrics/amplitude.js
- packages/fxa-shared/test/metrics/amplitude.js
- New password less payment pages need telemetry
- Adds P1 metrics from https://docs.google.com/document/d/1x0lYak98rM8ickwDciTn99Sd9-r1j6PmvAa8SP7CxGg/edit#heading=h.yzcz14jk0h70
- Adds support for emitting metrics on the new create account payments view (`fxa_pay_account_setup - view`, `fxa_pay_account_setup - engage`)
- Adds new event property `checkout_type`, which can be empty (regular flow), without_account
- Adds support in 123Done to initiate the passwordless flow, goto http://localhost:8080/ click `Subscribe to Pro (Passwordless)`. This will also generate unique flowIds and append to url.
Closes: https://github.com/mozilla/fxa/issues/9791
Example of metrics going through the passwordless flow from (123Done).
```
30|content  | 2021-08-11T13:57:52: INFO …
```
> feat(metrics): Emit metric when viewing account create form in payments

- packages/fxa-auth-server/bin/mjml-server.ts
- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/emails/fluent-localizer.ts
- packages/fxa-auth-server/lib/senders/emails/global.scss
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.txt
- packages/fxa-auth-server/lib/senders/emails/load-ftl-files.ts
- packages/fxa-auth-server/lib/senders/emails/partials/cadReminder/index.scss
- packages/fxa-auth-server/lib/senders/emails/partials/support/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/support/index.txt
- packages/fxa-auth-server/lib/senders/emails/renderer.ts
- packages/fxa-auth-server/lib/senders/emails/storybook-email.ts
- packages/fxa-auth-server/lib/senders/emails/templates/index.ts
- packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/index.ts
- packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
- We want to convert lowRecoveryCodes template to new stack
- Converts the said email template to new templating stack
Closes: #9269 
> feat(fxa-auth-server): Convert lowRecoveryCodes template to new stack

- docs/adr/0027-document-store-for-payments.md
Because:
* We need a flexible document store for payment data in auth-server.
This commit:
* Creates an ADR for using Firestore to hold payment data, initially for
Google IAP work.
> docs(adr): add firestore payment data adr

- packages/fxa-payments-server/.storybook/components/MockApp.tsx
Because:
- some routes in Payments need an access token
This commit:
- prevent a redirect to sign in Storybook by adding an access token in
the mocked app context
> fix(storybook): add access token to app context in Payments storybook

- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
- Users already recieve 2 subscription emails when they signup via the passwordless account flow, don't need another one
- Only sends download subscription email if it is an existing account
Closes: https://github.com/mozilla/fxa/issues/10099
> fix(emails): Don't send download subscription for passwordless accounts

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
- packages/fxa-payments-server/src/components/PayPalButton/index.tsx
- packages/fxa-payments-server/src/lib/apiClient.ts
- packages/fxa-payments-server/src/lib/errors.ts
- packages/fxa-payments-server/src/lib/mock-data.tsx
- packages/fxa-payments-server/src/lib/stripe.ts
- packages/fxa-payments-server/src/lib/test-utils.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.test.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- packages/fxa-payments-server/src/routes/Product/index.test.tsx
Because:
- we need to create passwordless subscriptions
This commit:
- handles the checkout form submission to create a FxA account and a
subscription with either Stripe or PayPal
Closes: #9358 
Follows #10007, #10051
Part of #9366
> feat(subscriptions): handle passwordless subscriptions

- packages/fxa-auth-server/lib/routes/subscriptions/account.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/account.js
Because:
- we should send an finish account setup email after a successful
passwordless subscription with PayPal
This commit:
- move the finish setup email sending code into a function
- send the email after a passwordless PayPal subscription
Closes: #10063
NOTE that this is duplicate of PR #10115 but with the branch on mozilla instead of my fork, because CI env var differences.
> feat(subscriptions): send finish setup email for PayPal subscriptions

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/PaymentForm/index.scss
- packages/fxa-payments-server/src/components/PaymentForm/index.tsx
- packages/fxa-payments-server/src/components/PaymentLegalBlurb/index.scss
- packages/fxa-payments-server/src/components/PaymentLegalBlurb/index.tsx
- packages/fxa-payments-server/src/components/TermsAndPrivacy/index.scss
- packages/fxa-payments-server/src/components/TermsAndPrivacy/index.stories.tsx
- packages/fxa-payments-server/src/components/TermsAndPrivacy/index.test.tsx
- packages/fxa-payments-server/src/components/TermsAndPrivacy/index.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.scss
- packages/fxa-payments-server/src/routes/Checkout/index.test.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
- packages/fxa-shared/subscriptions/metadata.ts
- packages/fxa-shared/subscriptions/types.ts
- packages/fxa-shared/test/subscriptions/metadata.ts
- Adds legal links for products and fxa to the payment form on checkout page.
Closes: #9794
> task(fxa-payments-server): add legal links to checkout form

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/AlertBar/index.scss
- packages/fxa-payments-server/src/components/PaymentErrorView/index.test.tsx
- packages/fxa-payments-server/src/components/PaymentErrorView/index.tsx
- packages/fxa-payments-server/src/components/TermsAndPrivacy/index.scss
- packages/fxa-payments-server/src/components/TermsAndPrivacy/index.tsx
- packages/fxa-payments-server/src/lib/account.ts
- packages/fxa-payments-server/src/lib/errors.ts
- packages/fxa-payments-server/src/lib/mock-data.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.test.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionSuccess/index.tsx
**Important:** This PR is based on Dave's PR #10074 for FXA-3715; it should not be merged until that PR merges. Only the second commit is new.
Because:
* The new passwordless checkout flow adds two new types of errors (account creation and newsletter signup) that we need to handle, and there is a previously unhandled error related to loading the success page.
* These errors should all be caught, and we should display an appropriate and relevant error message to the user when they occur if possible.
This commit:
* Makes sure we handle the following errors in the new passwordless flow and display error messages based on the MVP designs.
- FxA account creation
- Subscription creation/payment
- Newsletter signup
- Success screen loading
Closes #9366
Note: …
>  feat(payments): handle new/previously unhandled errors in passwordless checkout

- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/subscriptions/account.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-auth-server/test/local/routes/subscriptions/account.js
- packages/fxa-auth-server/test/local/senders/email.js
- packages/fxa-content-server/app/scripts/lib/fxa-client.js
- packages/fxa-content-server/app/scripts/lib/validate.js
- packages/fxa-content-server/app/scripts/lib/vat.js
- packages/fxa-content-server/app/scripts/models/account.js
- packages/fxa-content-server/app/scripts/models/verification/set-password.js
- packages/fxa-content-server/app/scripts/views/post_verify/finish_account_setup/set_password.js
- packages/fxa-content-server/app/tests/spec/views/post_verify/finish_account_setup/set_password.js
Instead of using the existing password reset flow, where the `passwordForgotToken` expires, this method creates a jwt that can be used until a password is set on the account.
closes #10043
> Use JWT for finish_setup

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/payments/google-play/play-billing.ts
- packages/fxa-auth-server/test/local/payments/google-play/play-billing.js
Because:
* We want to use consistent Google service account configuration.
This commit:
* Allows use of private key files for Google Play API access.
> fix: allow Play config with private key

- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/test/local/senders/email.js
Because:
* The subscriptionAccountFinishSetup and subscriptionFirstInvoice emails previously had the same subject. This can cause confusion, since we send both after a subscription is successfully created.
This commit:
* Renames the subject of the subscriptionAccountFinishSetup email per the MVP spec to 'Welcome to %(productName)s: Please set your password.'
Closes #10152
> fix(auth): rename subject of subscriptionAccountFinishSetup email

- packages/fxa-auth-server/lib/routes/auth-schemes/pubsub.js
Because:
* We're using a newer version of hapi that expects the key function to
be Promise based.
This commit:
* Uses the async hapiJwt2KeyAsync function instead of the older callback
version.
> fix(auth): use proper jwks key plugin

- packages/fxa-auth-server/README.md
- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/fluent-localizer.ts
- packages/fxa-auth-server/lib/senders/emails/partials/button/index.ts
- packages/fxa-auth-server/lib/senders/emails/partials/manageAccount/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/manageAccount/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/index.ts
- packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
- We have setup new templating stack in fxa auth server
- Converts postRemoveSecondary email template to new stack 
Closes: #9273 
> feat(auth-server): Convert postRemoveSecondary template to new stack

- packages/fxa-auth-server/lib/routes/subscriptions/account.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/account.js
Because:
- Stripe uses seconds instead of milliseconds for timestamps
This commit:
- update the finish stub account setup email to use a function that
handle those timestamps
Closes: #10166
> fix(emails): handle Stripe timestamps that are in seconds

- packages/fxa-auth-server/lib/routes/subscriptions/google.ts
Because:
* The token handler should be used for the token endpoint.
This commit:
* Uses the correct handler for the token endpoint.
Closes #10195
> fix(auth): use token handler for token endpoint

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/global.scss
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.scss
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.ts
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.txt
- packages/fxa-auth-server/lib/senders/emails/partials/appBadges/index.scss
- packages/fxa-auth-server/lib/senders/emails/partials/appBadges/index.ts
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailNoAction/index.scss
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailNoAction/index.ts
- packages/fxa-auth-server/lib/senders/emails/partials/cadReminder/index.ts
- packages/fxa-auth-server/lib/senders/emails/partials/verificationReminder/index.ts
- packages/fxa-auth-server/lib/senders/emails/partials/verificationReminder/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/cadReminderFirst/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/index.ts
- packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/index.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postVerify/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postVerify/index.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postVerify/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/index.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
- We have setup new templating stack in fxa auth server
- Converts verificationReminderFirst and verificationReminderSecond email templates to new stack
Closes: #9281 and #9285 
> feat(auth-server): Convert verificationReminder templates to new stack

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/lib/errors.ts
- fixes 
- Syntax for fluent variable was incorrect
- updated fluent id 
Closes: #10169
> fix(fxa-payment-server): fluent syntax typo in error message

- packages/fxa-auth-server/lib/routes/subscriptions/google.ts
- packages/fxa-auth-server/lib/routes/subscriptions/utils.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/google.js
- packages/fxa-shared/oauth/constants.js
Because:
* We should use a narrowly scoped permission for IAP token registration.
This commit:
* Adds a new scope for IAP access and applies it to the token
registration endpoint.
Closes #10202
> fix(auth): use IAP scope for token register

- packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
- passes `accountExists` to TermsAndPrivacy showFXALinks prop, to that we don't show to existing users.
Closes: #10171
> fix(fxa-payments-server): do not show fxa terms to existing users

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/PaymentLegalBlurb/index.tsx
- We hadn't updated one of the paypal privacy links, this pr addresses that
Closes: #10164
> fix(fxa-payments-server): fix skipped paypal legal link

- packages/fxa-payments-server/src/components/PaymentForm/index.scss
Because:
* There was no whitespace between the last input element and the buttons.
This commit:
* Adds the standard 32px whitespace.
Closes #10191
> fix(payments): add margin-top to PaymentUpdateForm action buttons

- packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.test.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
Because:
- we need to keep the query params when an existing user use the
sign-in link on the passwordless flow
This commit:
- copy the query params from the checkout page into the sign-in link
Closes: #10223
> fix(subscriptions): copy query params into sign-in link

- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/lib/payments/google-play/subscription-purchase.ts
- packages/fxa-auth-server/test/local/payments/google-play/subscription-purchase.js
Because:
* We need the userid in the merged subscription purchase.
This commit:
* No longer skips the userid when copying firestore data to the purchase
object.
Fixes #10236
> fix(auth): retain userid in subsription purchase copy

- packages/fxa-auth-server/lib/payments/capability.ts
- packages/fxa-auth-server/lib/routes/subscriptions/google.ts
- packages/fxa-auth-server/lib/routes/subscriptions/index.ts
- packages/fxa-auth-server/lib/routes/subscriptions/play-pubsub.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/google.js
Because:
* Validating a Google IAP token should immediately grant access to
the purchased product.
This commit:
* Checks product ids before and after registering a token to see if
access has changed, and removes profile cache if so.
Closes #10242
> fix(auth): refresh profile if needed

- packages/fxa-auth-server/lib/routes/subscriptions/play-pubsub.ts
Because:
* While using a strategy string for auth is valid for hapi, we have
custom hapi code that attempts to assign to it as if it was an
object.
This commit:
* Reverts to using an object.
> fix(auth): use object only for auth

- packages/fxa-auth-server/lib/payments/google-play/purchase-manager.ts
- packages/fxa-auth-server/lib/routes/auth-schemes/pubsub.js
- packages/fxa-auth-server/lib/routes/subscriptions/play-pubsub.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/play-pubsub.js
Because:
* Handlers need to return something other than undefined.
* JWT plugin looks at locations other than the header for the
token, which has a field called token that isn't the right token.
* Missing user lookups should not error the handler.
This commit:
* Returns data for a proper 200 instead of undefined.
* Restricts the JWT plugin to only search the authorization header.
* Catches user lookups and reports them to sentry while returning a 200.
Closes #10249
> fix(auth): use header only for jwt and return data

- packages/fxa-auth-server/.storybook/preview.js
- packages/fxa-auth-server/bin/mjml-server.ts
- packages/fxa-auth-server/lib/senders/emails/storybook-email.ts
- packages/fxa-auth-server/lib/senders/emails/storybook.css
- packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/index.stories.ts
- We want to display plaintext versions of emails in storybook
- Passes along the plaintext rendered version of the email through the MJML server up to Storybook
- Updates the Storybook layout of emails so that plaintext is displayed alongside the HTML version
- Cosmetic tweaks
- Moves the usage of the ltr/rtl Storybook context value out of a decorator and down into the Story rendering so that it doesn't also target Story rendering UI (like the header element)
Closes: #10217
> feat(auth-server): start rendering plaintext emails alongside html in storybook

- packages/123done/static/index.html
- packages/123done/static/js/123done.js
- packages/fxa-content-server/tests/functional/lib/helpers.js
- packages/fxa-content-server/tests/functional/lib/selectors.js
- packages/fxa-content-server/tests/functional/subscriptions.js
- We should have functional tests that cover these flows
- Adds functiona tests that subscribes using the passwordless account flow, sets password from email, logins in
Closes: #9888
> fix(tests): Add functional test for passwordless flows

- packages/fxa-content-server/app/scripts/lib/channels/receivers/web-channel.js
- packages/fxa-content-server/app/tests/spec/lib/channels/receivers/web-channel.js
- These errors are sent by FF browser are not really info level. Unfortunatley, the majority (if not all) of them would need to be fixed by landing code in FF.
- Removes all info based sentry logging for the content-server
- Marks them as sentry errors instead of info
Closes: https://github.com/mozilla/fxa/issues/9470
> fix(logging): Report webchannel errors as sentry errors

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/global.scss
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.scss
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailNoAction/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/location/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/location/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/location/index.scss
- packages/fxa-auth-server/lib/senders/emails/partials/location/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/verify/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/verify/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/verify/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verify/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
- We have setup new templating stack in fxa auth server
- Converts verify email template to new stack
Closes: #9289 
> feat(fxa-auth-server): Convert verifyEmail Template to new stack

- packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
Because:
- the upgrade checkout page does not display the correct payment
provider information when the customer uses PayPal
This commit:
- use an existing component to show a customer's current payment
provider info
Closes: #9957
> fix(subscriptions): show correct payment provider info for upgrades

- packages/fxa-content-server/server/lib/configuration.js
- packages/fxa-content-server/tests/functional/sign_up.js
Because:
* We have deployed the [passwordless flow feature](https://mozilla-hub.atlassian.net/browse/FXA-3486) to production, and it has been QA-verified.
* Therefore, we can safely enable the feature via this flag in all environments, which we have done everywhere except in the content server config file.
This commit:
* Sets SUBSCRIPTIONS_UNAUTHED_REDIRECTS to true by default to make this behavior the default in the content server config file; this saves the step of setting the flag and restarting the content server for local development.
Closes #10234
> chore(content): set SUBSCRIPTIONS_UNAUTHED_REDIRECTS to true by default

- packages/fxa-shared/metrics/amplitude.js
- packages/fxa-shared/test/metrics/amplitude.js
Because:
* We want to support patch versions > 9.
This commit:
* Changes the last reference to version checking for > 9.
> fix: allow patch version > 9

- packages/fxa-auth-server/config/index.ts
Because:
* We need to set these to values in staging
This commit:
* Creates two env vars: one for mjml enabled email addresses, and one for mjml templates
> feat(auth-server): Add env vars for MJML addresses/templates

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/event_customer_subscription_updated.json
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
- maybe at some point the plan in a subscription updated event's
'previous_attributes' changed so it no long has a product id that we
need
This commit:
- use a plan id to get a plan that has a product id and use that
product id to find the product needed for the emails
Closes: #9958
> fix(subscriptions): fix product fetching for up/downgrade email

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/fluent-localizer.ts
- packages/fxa-auth-server/lib/senders/emails/global.scss
- packages/fxa-auth-server/lib/senders/emails/templates/verifySecondaryCode/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/verifySecondaryCode/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/verifySecondaryCode/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verifySecondaryCode/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/verifyShortCode/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/verifyShortCode/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/verifyShortCode/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verifyShortCode/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
- We need to convert the templates for verifyShortCode and verifySecondaryCode to our new MJML stack
- Converts them to the new stack
- Updates fluent localizer to strip excessive line breaks in plaintext emails
Closes: #9302
Closes: #9297
> feat(auth-server): convert verifyShortCode and verifySecondaryCode templates to new stack

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailChangePassword/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailChangePassword/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailChangePassword/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/newDeviceLogin/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/newDeviceLogin/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/newDeviceLogin/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/newDeviceLogin/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
- We need to convert the template for newDeviceLogin to our new MJML stack
- Converts it to the new stack
- Moved `text-footer-automatedEmail` to global styles for re-use
Closes: #9264
> feat(auth-server): convert newDeviceLogin template to new stack

- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
- we get errors in Sentry and Stripe when there's an email complaint
error while handling a webhook event
This commit:
- ignore the email complaint error so that Stripe stops retrying the
webhook event
Closes: #9906
> fix(subscriptions): ignore email complaint errors on webhooks

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
Because:
- capitalization of "require" was not matching Figma
This commit:
- capitalize "require"
- add L10n for "Required"
Closes: #10241
> fix(subscriptions): capitalize "required" on checkout page

- packages/123done/static/js/123done.js
- packages/fxa-payments-server/server/lib/routes/post-metrics.js
- packages/fxa-payments-server/src/index.tsx
- packages/fxa-payments-server/src/lib/amplitude.ts
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
- FxA might not log utm params properly
- FxA should log the uid in metrics when the stub user account is created
- Fixes those issues
Closes: https://github.com/mozilla/fxa/issues/10375
With utms params passed through all flows and the `user_id` set on the success and complete events
```
31|payments  | 2021-09-07T14:21:22: INFO fxa-payments-server.amplitudeEvent: {"op":"amplitudeEvent","event_type":"fxa_pay_account_setup - view","time":1631038882350,"device_id":"6a77ed01d32b4a6b9ac088bdae51cd45","session_id":1631038827645,"app_version":"214.0","os_name":"Mac OS X","os_version":"10.15","event_properties":{"plan_id":"plan_GqM9N6qyhvxaVk","product_id":"prod_GqM9ToKK62qjkK","checkout_type":"without-account"},"user_properties":{"flow_id":"c46d9c61217878c6b67a297e0260304a0564cba0f08638e033a7ac9 …
```
> fix(metrics): Update new payment flow metrics to support utm and append uid

- packages/fxa-auth-server/bin/mjml-server.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/emails/fluent-localizer.ts
- packages/fxa-auth-server/lib/senders/emails/global.scss
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/button/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/cadReminder/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/cadReminder/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/cadReminder/index.txt
- packages/fxa-auth-server/lib/senders/emails/partials/location/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/verificationReminder/index.mjml
- packages/fxa-auth-server/lib/senders/emails/renderer.ts
- packages/fxa-auth-server/lib/senders/emails/storybook-email.ts
- packages/fxa-auth-server/lib/senders/emails/templates/cadReminderFirst/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/cadReminderFirst/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/lowRecoveryCodes/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/newDeviceLogin/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/passwordReset/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postVerify/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderFirst/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/verificationReminderSecond/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verify/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verifySecondaryCode/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verifyShortCode/index.stories.ts
- There were a few areas where we were passing strings to the template for rendering, when they weren't necessary (most can be derived from Fluent now)
- I noticed a few other spots where we could tighten up some of the code
- The big one is reducing the need to define template-level strings anywhere but the Fluent file (and in the templates themselves as fallbacks). This includes:
- No longer needing to define a `subject` in any Storybook story, this is now automatically passed down in the localizer
- No longer needing to define `headerText` or `bodyText` in CAD Storybook stories or pass them down as variables in the mailer, these are now automatically passed down in the localizer
- No longer needing to pass down `title`, `description`, and `subDescription` in the Verification Reminder …
> feat(auth-server): refactor email storybook, renderer, and localizer to be more dry

- packages/123done/static/js/123done.js
- packages/fxa-payments-server/server/lib/routes/post-metrics.js
- packages/fxa-payments-server/src/index.tsx
- packages/fxa-payments-server/src/lib/amplitude.ts
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
- FxA might not log utm params properly
- FxA should log the uid in metrics when the stub user account is created
- Fixes those issues
Closes: https://github.com/mozilla/fxa/issues/10375
With utms params passed through all flows and the `user_id` set on the success and complete events
```
31|payments  | 2021-09-07T14:21:22: INFO fxa-payments-server.amplitudeEvent: {"op":"amplitudeEvent","event_type":"fxa_pay_account_setup - view","time":1631038882350,"device_id":"6a77ed01d32b4a6b9ac088bdae51cd45","session_id":1631038827645,"app_version":"214.0","os_name":"Mac OS X","os_version":"10.15","event_properties":{"plan_id":"plan_GqM9N6qyhvxaVk","product_id":"prod_GqM9ToKK62qjkK","checkout_type":"without-account"},"user_properties":{"flow_id":"c46d9c61217878c6b67a297e0260304a0564cba0f08638e033a7ac9 …
```
> fix(metrics): Update new payment flow metrics to support utm params and append uid on success

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/global.scss
- packages/fxa-auth-server/lib/senders/emails/partials/appBadges/index.scss
- packages/fxa-auth-server/lib/senders/emails/templates/passwordChanged/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/passwordChanged/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/passwordChanged/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/passwordChanged/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/passwordReset/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/unblockCode/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/unblockCode/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/unblockCode/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/unblockCode/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/verifySecondary/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/verifySecondary/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/verifySecondary/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verifySecondary/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/verifySecondaryCode/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/verifyShortCode/index.mjml
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
- We need to convert email templates to the new MJML stack
- Converts the `verifySecondary`, `passwordChanged`, and `unblockCode` templates to our new MJML stack
Closes: #9294
Closes: #9308
Closes: #9262
> feat(auth-server): convert verifySecondary, passwordChanged, and unblockCode templates to new mjml stack

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/routes/auth-schemes/shared-secret.js
- packages/fxa-auth-server/lib/routes/subscriptions/support.ts
- packages/fxa-auth-server/lib/server.js
- packages/fxa-auth-server/test/local/routes/auth-schemes/shared-secret.js
- packages/fxa-auth-server/test/local/routes/support.js
- packages/fxa-auth-server/test/local/server.js
Because:
- Guardian wants to submit support tickets on the behalf of users
This commit:
- update the support ticket endpoint to
- allow authn through a shared secret
- look up a user by email from the payload
Closes: #10177
> feat(subscriptions): accept Guardian submitted support tickets

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/routes/subscriptions/support.ts
- packages/fxa-auth-server/test/local/routes/support.js
Because:
- we need two more support ticket fields for product platform and
version
This commit:
- adds support ticket fields for product platform and version
Closes: #10178
> chore(subscriptions): add two more support ticket fields

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/routes/subscriptions/support.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- packages/fxa-auth-server/test/local/routes/support.js
- packages/fxa-auth-server/test/local/server.js
Because:
- other services might want to include debugging info in the support
tickets
This commit:
- increase the payload limit on the support ticket endpoint
Closes: #10419
> chore(subscriptions): increase support ticket payload limit

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
Because:
- it was misleading people to think they are signing up for an account
for an @mozilla.com email address
This commit:
- remove the placeholder text for the email address input
Closes: #10422
> chore(subscriptions): remove email input placeholder text

- packages/fxa-payments-server/src/components/NewUserEmailForm/index.scss
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
Because:
- absolute positioning the "already have an account" message cause
layout issues with certain languages
This commit:
- move the message to its own line(s)
Closes: #10192
> style(subscriptions): move the "already have an acct" message

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/templates/passwordResetAccountRecovery/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/passwordResetAccountRecovery/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/passwordResetAccountRecovery/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/passwordResetAccountRecovery/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/postAddAccountRecovery/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postAddAccountRecovery/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postAddAccountRecovery/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postAddAccountRecovery/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
- We need to convert email templates to the new MJML stack
- Converts the `passwordResetAccountRecovery` and `postAddAccountRecovery` templates to our new MJML stack
Closes: #9271
Closes: #9268
> feat(auth): convert passwordResetAccountRecovery and postAddAccountRecovery emails to new mjml stack

- packages/fxa-payments-server/package.json
- packages/fxa-react/package.json
- packages/fxa-settings/package.json
- yarn.lock
Reverts mozilla/fxa#10432
Things be [broken](https://github.com/mozilla/fxa/pull/10432#issuecomment-919422417).
> Revert "chore(deps): bump @fluent/react from 0.13.1 to 0.14.0"

- packages/fxa-auth-server/package.json
- packages/fxa-metrics-processor/package.json
- packages/fxa-shared/package.json
- yarn.lock
This reverts commit 21ec92aa66bea2732e3c1efc586110e9999bb0e8.
Dependabot just loves breaking main today.
> Revert "chore(deps): bump ajv from 6.12.6 to 8.6.3"

- packages/fxa-support-panel/src/app.module.ts
- packages/fxa-support-panel/src/app/app.controller.spec.ts
- packages/fxa-support-panel/src/app/app.controller.ts
- packages/fxa-support-panel/src/config.ts
- packages/fxa-support-panel/src/database/database.module.ts
- packages/fxa-support-panel/src/database/database.service.spec.ts
- packages/fxa-support-panel/src/database/database.service.ts
- packages/fxa-support-panel/src/remote-lookup/remote-lookup.service.spec.ts
- packages/fxa-support-panel/src/remote-lookup/remote-lookup.service.ts
- packages/fxa-support-panel/src/remote-lookup/remote-responses.dto.ts
- yarn.lock
fxa-auth-db-mysql is deprecated. this converts the support-panel to use fxa-shared and with direct db access.
closes #9724
config PR https://github.com/mozilla-services/cloudops-deployment/pull/4373
> refactor(support): convert support panel to direct db access

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/templates/newDeviceLogin/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/passwordResetAccountRecovery/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postAddAccountRecovery/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveAccountRecovery/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveAccountRecovery/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveAccountRecovery/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveAccountRecovery/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveTwoStepAuthentication/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveTwoStepAuthentication/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveTwoStepAuthentication/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveTwoStepAuthentication/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/postVerifySecondary/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postVerifySecondary/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postVerifySecondary/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postVerifySecondary/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Because:
* We're converting all of our email templates to a new MJML stack
This commit:
* Converts postRemoveAccountRecovery, postRemoveTwoStepAuthentication, and postVerifySecondary email templates, adds tests and stories
* Removes a couple of FTL references we don't need, updates others to use the manageAccount partial or for consistent casing
fixes #9295
fixes #9300
fixes #9303
> feat(auth-server): Convert postRemoveAccountRecovery, postRemoveTwoStepAuthentication, & postVerifySecondary to new email stack

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/emails/global.scss
- packages/fxa-auth-server/lib/senders/emails/templates/passwordChangeRequired/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/passwordChangeRequired/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/passwordChangeRequired/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/passwordChangeRequired/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/postChangePrimary/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postChangePrimary/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postChangePrimary/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postChangePrimary/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/postConsumeRecoveryCode/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postConsumeRecoveryCode/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postConsumeRecoveryCode/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postConsumeRecoveryCode/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/postNewRecoveryCodes/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postNewRecoveryCodes/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postNewRecoveryCodes/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postNewRecoveryCodes/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Updates the following email to our MJML stack:
- postAddTwoStepAuthentication
- postChangePrimary
- postConsumeRecoveryCode
- postNewRecoveryCodes
- passwordChangeRequired
Closes #9313
Closes #9290
Closes #9286
Closes #9280
Closes #9275
> feat(auth): convert various email templates to new mjml stack

- packages/fxa-auth-server/lib/senders/emails/renderer.ts
- packages/fxa-auth-server/package.json
Discovered by Danny, this just adds the `emails-scss` command to the build command in the auth server. This should resolve the sending issues in stage.
Confirmed that this works for me locally when sending emails using the dist auth server - and after understanding the solution was able to effectively repro the issue.
(The auth server build command copies everything from the lib folder, and I had been manually running that command so it was including the compiled CSS already, which is why I wasn't seeing it locally when trying to repro.)
> fix(auth): include emails-scss in build command

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/templates/recovery/en-US.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/recovery/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/recovery/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/recovery/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
fixes #10478
- We're converting all emails over to the new stack
- * Converts 'recovery' to new stack
Closes: #10478
> feat(auth): Convert 'recovery' email to mjml stack

- packages/fxa-shared/nestjs/sentry/reporting.spec.ts
- packages/fxa-shared/nestjs/sentry/reporting.ts
- packages/fxa-shared/package.json
- yarn.lock
Because:
* QueryParams in Sentry is not just a string, it can be an array of
arrays or an object. Using replace on them throws an error when
attempting to report an error which obscures legitimate errors.
This commit:
* Properly handles all the QueryParams types.
Closes #9963
> feat(shared): handle more query object types

- packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
- packages/fxa-payments-server/src/components/fields/index.tsx
Because:
- the input cursor moves the end when the user types in the email
address field on the passwordless checkout page
This commit:
- save and restore the cursor position after the field update re-render
This patch fixes the symptom of the issue by restoring the cursor
position.  It's not perfect: sometimes you can see that the cursor
flashes at the end of the input value before it moves back.
Closes: #10233
> fix(subscriptions): restore input cursor position post async render

- packages/fxa-payments-server/server/config/index.js
- packages/fxa-payments-server/src/App.tsx
Because:
* This feature flag is no longer used.
This commit:
* Removes the unnecessary useSCAPaymentUIBeDefault flag.
Closes: #9070
> chore(payments): remove useSCAPaymentUIByDefault feature flag

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/PaymentLegalBlurb/index.stories.tsx
- packages/fxa-payments-server/src/components/PaymentLegalBlurb/index.tsx
Because:
* We would like to have storybook coverage for react components.
This commit:
* Adds a storybook component for all three cases: paypal, stripe, default.
Closes #10102
> chore(payments): create storybook for PaymentLegalBlurb

- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postVerifySecondary/index.mjml
- I noticed this when checking some emails in staging - secondary email should not be hard-coded, whoops. The text files are both fine as-is.
- References the dynamic variable rather than hard-coded value
> fix(auth-server): Update x2 hard-coded email addresses in new email templates

- packages/fxa-auth-server/lib/senders/email.js
Because:
* We want to know when a user is blocked from logging in because they can't receive FxA emails.
This commit:
* Records the email template name when we fail to send an email, so we can filter for the emails which must be opened before the user can sign in (enumerated in #10527).
Closes: #10527
I am confirming with @jbuck that we can pull in log data from the auth server into Grafana, as ultimately, this data needs to go into a new panel. Otherwise, I will resubmit this PR using a StatsD metric.
> chore(auth): add email template name to log.error if sending email fails

- _dev/pm2/infrastructure.config.js
- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/bounces.js
- packages/fxa-auth-server/lib/payments/processing-tasks-setup.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/index.js
- packages/fxa-auth-server/pm2.config.js
- packages/fxa-auth-server/scripts/bulk-mailer/index.js
- packages/fxa-auth-server/scripts/sms/send.js
- packages/fxa-auth-server/scripts/write-emails-to-disk.js
- packages/fxa-auth-server/test/local/bounces.js
- packages/fxa-auth-server/test/local/senders/email.js
- packages/fxa-auth-server/test/local/senders/index.js
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
- packages/fxa-auth-server/test/mock-sns.js
- packages/fxa-shared/db/models/auth/email-bounce.ts
- I'd like to deprecate email-service
- Adds the nodemailer SES transport
- The AWS config is set by the environment and is used when no SMTP user:password are set
- We _could_ use liveConfig to run a subset of addresses through direct SES vs email-service
- https://github.com/mozilla/fxa/blob/auth-ses/packages/fxa-auth-server/lib/senders/select_email_services.js#L18
- Gets used 100% when email-service has been configed off with `EMAIL_CONFIG_USE_REDIS=false`
- Resurrects some old code from https://github.com/mozilla/fxa-auth-server/pull/1934 🧟 🧙
After this we'll have 3 ways to send via SES: API direct, SMTP, fxa-email-service. The goal is to use API direct and eliminate fxa-email-service, with an SMTP "backup" in case we need to support other providers.
Closes: #9725
> feat(auth): enable nodemailer SES transport

- packages/fxa-settings/src/components/PageSecondaryEmailAdd/en-US.ftl
- packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.tsx
- packages/fxa-settings/src/components/PageSecondaryEmailVerify/en-US.ftl
- packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.tsx
feature: fxa-settings
The secondary field popup is inconsistent with other multi-step popups. 
adds the wording "Step 1 of 2" and "Step 2 of 2" in the secondary email popup.
Closes: # FXA-3829
> Added Step x of x wording to Secondary Email

- packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.tsx
* the current text says step 1 of 1 instead of 1 of 2
* fixes the wording
Closes:  #10572
> bug(settings): fixed wording for step 1 of secondary email

- packages/fxa-payments-server/.storybook/components/MockApp.tsx
- packages/fxa-payments-server/README.md
- packages/fxa-payments-server/server/config/index.js
- packages/fxa-payments-server/src/lib/hooks.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.test.tsx
Because:
* This UI is enabled by default for all environments, it is no longer necessary for local/dev.
This commit:
* Removes the feature flag, removes references to it, and updates the README
Closes #10531
> chore(payments): remove usePaypalUIByDefault feature flag

- packages/fxa-email-service/src/api/send/mod.rs
- we hit a error with the `subscriptionAccountFinishSetup` email being too large for email-service after adding metrics in #10516
- increases the limit to 128kb
fixes #10573
> fix(email-service): increase /send body size limit

- packages/fxa-auth-server/lib/senders/emails/templates/passwordChanged/index.mjml
- we are seeing html tags in the reset password email header
- adds '<' to the html tag so it is no longer rendered as test
Closes: #10575
> fix(auth): wrap span in '<' in the reset password email 

- packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
Because:
* We would like UI that only displays errors on user input
This commit:
* Hides the error state unless there is an error due to user input
Closes: #10448
> fix(payments): do not show error message on empty confirm email input 

- packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionSuccess/index.test.tsx
Because:
* MDN requested to have the email address appeneded to the download link as a query param
This commit:
* URI encodes the email address of the user and appends to the download link on a successful subscription
Closes #10489
> feat(payments): add email address to download link

- packages/fxa-auth-server/lib/payments/stripe-firestore.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/payments/capability.js
- packages/fxa-auth-server/test/local/payments/google-play/play-billing.js
- packages/fxa-auth-server/test/local/payments/google-play/purchase-manager.js
- packages/fxa-auth-server/test/local/payments/google-play/user-manager.js
- packages/fxa-auth-server/test/local/payments/paypal-processor.js
- packages/fxa-auth-server/test/local/payments/paypal.js
- packages/fxa-auth-server/test/local/payments/stripe-firestore.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/payments/subscription-reminders.js
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-auth-server/test/local/routes/subscriptions/google.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/play-pubsub.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
* We want to keep firestore copies of Stripe docs up to date.
* We want to use our firestore copy of Stripe data instead of
hitting Stripe frequently.
This commit:
* Uses the stripe webhook to populate Firestore with up-to-date
objects from Stripe.
* Uses Firestore first when possible to fetch Stripe documents
when expanding the resourcce.
Closes #10530
> feat(auth): store stripe docs in firestore

- README.md
- package.json
Because:
* We should document the basic process for new contributors.
This commit:
* Adds a new "Connecting to a local MySQL DB" section to the root project README.
Closes #No issue
> docs(db): update root README on how to connect to local FxA MySQL DBs

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* We dont want to claim a webhook was not handled when the firestore
handler did handle it.
This commit:
* Records whether the firestore handler can process the webhook and will
not report it if so.
Closes #10681
> fix(auth): ignore handled webhook events

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.scss
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionReactivation/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionReactivation/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionReactivation/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionReactivation/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
- We're actively converting old FxA emails to our new modernized stack.
- Converts the `subscriptionReactivation` subscription platform email to the new stack.
Closes: #9288
> feat(auth-server): convert subscriptionReactivation email template to stack

- .circleci/config.yml
- packages/fxa-auth-server/bin/key_server.js
- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/index.ts
- packages/fxa-auth-server/pm2.config.js
- packages/fxa-auth-server/scripts/clean-up-old-ci-stripe-customers.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- packages/fxa-auth-server/test/scripts/bulk-mailer.js
- packages/fxa-auth-server/test/scripts/dump-users.js
- packages/fxa-auth-server/test/scripts/verification-reminders.js
- packages/fxa-auth-server/test/scripts/write-emails-to-disk.js
- packages/fxa-auth-server/test/test_server.js
Because:
* Having a toggle to deactivate use of Firestore drastically increases
code complexity.
This commit:
* Requires Firestore for running auth-server and uses the emulator for
local running.
Closes #10710
> feat(auth): require auth firestore usage

- packages/fxa-auth-server/lib/payments/capability.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/subscriptions/account.ts
- packages/fxa-auth-server/lib/routes/subscriptions/index.ts
- packages/fxa-auth-server/lib/routes/subscriptions/mozilla.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/utils.ts
- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/mozilla.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- packages/fxa-auth-server/test/local/routes/validators.js
- packages/fxa-shared/subscriptions/metadata.ts
- packages/fxa-shared/subscriptions/types.ts
- packages/fxa-shared/test/subscriptions/metadata.ts
Because:
- some clients might need to know that a customer has IAP subscriptions
This commit:
- add a new endpoint to include Google Play subscriptions as well as
Stripe subscriptions
- the response is a superset of the response from
/oauth/subscriptions/customer
Closes: #10095
> feat(subscriptions): add endpoint for billing details and IAP & Stripe subscriptions

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
* We have leftover functions from prior iterations that make it
hard to determine code flow and use.
This commit:
* Removes several obviously dead functions that had no callers.
Closes #10737
> refactor(auth): remove dead functions and code

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
- there's existing code that expect the "expanded" subscriptions list
on a customer
This commit:
- include the empty subscriptions list from Firestore on a customer, to
match the previous behavior of expanding the subscriptions when
retrieving a customer from Stripe
Closes: #10866
> fix(subscriptions): include empty subscriptions list for customer

- .circleci/config.yml
- _dev/docker/builder/Dockerfile
- _dev/docker/mono/Dockerfile
Test stability has dropped with the change to node 16. Until we can resolve it we're reverting to 14. Local dev will continue on 16 in order to be able to fix the problems.
> are tests more stable on node 14?

- packages/fxa-payments-server/src/components/PlanDetails/index.scss
- packages/fxa-payments-server/src/index.scss
- packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.scss
Because:
* Subscription upgrade page layout for tablets introduces a horizontal
scroll bar, that cuts off the edges of the upgrade container.
This commit:
* Updates grid widths to accommodate for grid-column-gap
* Updates width of grid column, to accommodate for Always showing scroll
bars.
Closes #
[Issue 9955](https://github.com/mozilla/fxa/issues/9955)
> fix(subscriptions): update sub upgrade layout

- packages/fxa-content-server/app/scripts/templates/post_verify/cad_qr/ready_to_scan.mustache
- packages/fxa-content-server/app/scripts/templates/post_verify/cad_qr/scan_code.mustache
- packages/fxa-content-server/app/scripts/views/connect_another_device.js
- packages/fxa-content-server/app/tests/spec/views/connect_another_device.js
- packages/fxa-content-server/app/tests/spec/views/post_verify/cad_qr/ready_to_scan.js
- packages/fxa-content-server/app/tests/spec/views/post_verify/cad_qr/scan_code.js
- packages/fxa-content-server/tests/functional/oauth_sync_sign_in.js
- packages/fxa-content-server/tests/functional/sign_in_cached.js
- packages/fxa-content-server/tests/functional/sync_v3_force_auth.js
- packages/fxa-content-server/tests/functional/sync_v3_settings.js
- packages/fxa-content-server/tests/functional/sync_v3_sign_in.js
- SMS is currently disabled in production, we shouldnt have any links to the page
- Disable the QR code page from connect another device because it has been a source of confusion for users
- Removes sms links
- Disables qr code cad
Closes: https://github.com/mozilla/fxa/issues/10891
> fix(chore): Remove links to sms page from qr code page

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/validators.js
Because:
- Stripe's default behavior of not returning canceled subscription no
longer applies now that we get subscriptions from Firestore
This commit:
- explicitly filtering for subscriptions with one of the active
statuses for the endpoint that returns billing info and subscriptions
Closes: #10893
> fix(subscriptions): filter canceled subscriptions

- packages/fxa-auth-server/lib/payments/stripe-firestore.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* Firestore merge is not a depth merge, it will not properly remove
nested values in a merge.
This commit:
* Uses a non-merge update, and removes partial inserts entirely.
Closes #10905
> fix(auth): dont merge records

- packages/fxa-auth-server/lib/payments/stripe-firestore.ts
- packages/fxa-auth-server/test/local/payments/stripe-firestore.js
Because:
* Stripe would only return non-cancelled subscriptions when they
were expanded.
This commit:
* Updates Firestore to only return active subscriptions to match
Stripe behavior.
Issue #10893
> fix(auth): only return active subs

- packages/fxa-auth-server/lib/routes/subscriptions/account.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/account.js
Because:
- we did not pass the account locale for the new account+subscription
email
This commit:
- pass in the account locale for the new account+subscription email
Closes: #10906
> fix(emails): pass language for new sub/stub acct email

- packages/fxa-auth-server/lib/payments/stripe-firestore.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/event_payment_method_detached.json
- packages/fxa-auth-server/test/local/payments/stripe-firestore.js
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* We query payment methods on emails which can hit Stripe APIs
extensively for data that rarely changes.
This commit:
* Stores the payment method object in Firestore.
Closes #10746
> feat(auth): store payment methods in firestore

- packages/fxa-auth-server/lib/payments/stripe-firestore.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* Webhooks may come out of order, or be triggered by requests we perform
without storing the latest object.
This commit:
* Always stores the latest object from stripe in firestore.
Closes #10904
> fix(auth): always fetch latest stripe object to store

- packages/fxa-auth-server/lib/senders/email.js
This reverts commit db7322e0d92882554e4b7e25af2325d43e1ceb01.
- We still need the old survey url
- revert db7322e so that the app uses the old url
> Revert "chore(auth): update survey url (#10815)"

- packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
Because:
* The "Sign In" button in the "account exists" error message does not
trigger the event fxa_pay_account_setup - other
This commit:
* Adds the onClick function to the Sign In button, which will trigger
the event.
Closes #
[10838](https://github.com/mozilla/fxa/issues/10838)
> feat(subscription): emit event on error sign in

- packages/fxa-content-server/app/scripts/templates/confirm_signup_code.mustache
- packages/fxa-content-server/app/scripts/templates/partial/firefox-family-services.mustache
- packages/fxa-content-server/app/scripts/templates/ready.mustache
- packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache
- l10n wanted a couple comments for localizers
- Misspelled across 
- Fixes those issues
Closes: https://github.com/mozilla/fxa/issues/10935
> fix(chore): Fix spelling and a few other l10n issues

- packages/fxa-auth-server/config/index.ts
Because:
- the fields only accept certain values, which the Support Form is not
currently sending
This commit:
- revert the Zendesk field ids until we can fully support the new
fields
This reverts PR #10785
> fix(support): revert Zendesk field ids

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/AppLayout/index.tsx
- packages/fxa-payments-server/src/components/PlanDetails/index.scss
- packages/fxa-payments-server/src/components/PlanDetails/index.tsx
Because:
* Total price wraps around for certain languages and prices.
This commit:
* Adds lang to the AppLayout div.
* Ensures the price stays on a single line.
* Adds a title to the price.
Closes #
[10920](https://github.com/mozilla/fxa/issues/10920)
Example in a non-English language, showing smaller total price text (Also showing default title text, if no translation is available)
Example in a non-English language, showing smaller total price text (Also showing default title text, if no translation is available)
Example in English, showing normal total price text, without change.
This change requires a translation update to include attribute `title`.
> fix(subscriptions): layout issue for 6m sub prices

- packages/fxa-auth-server/lib/payments/capability.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/subscriptions/google.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal-notifications.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/play-pubsub.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/payments/capability.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-auth-server/test/local/routes/subscriptions/google.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal-notifications.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/play-pubsub.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- packages/fxa-auth-server/test/remote/subscription_tests.js
Because:
* We don't want to maintain multiple local caches now that
we store copies in Firestore.
* It's more efficient to only manage one cache of Stripe data
instead of maintaining multiple caches.
* Some methods were using customer functions that did not actually
need the cached data, or all the data we fetched and cached.
This commit:
* Removes Redis caching of the customer object.
* Replaces customer calls with the appropriate underlying fetchCustomer
call with the proper expansions in place as needed to reduce
cache lookups.
* Replaces some customer calls with a db lookup to fetch the Stripe
customer ID instead of a cache call.
Closes #10747
> feat(auth): remove redis customer caching

- packages/fxa-auth-server/lib/sentry.js
- packages/fxa-auth-server/package.json
- packages/fxa-shared/nestjs/sentry/sentry.service.ts
- yarn.lock
Because:
* We'd like to know details of nested objects deeper than the default
of 3.
* Auth server was not attaching extra non-native exception attributes.
This commit:
* Extends the depth of sentry object capture to 6 instead of 3.
* Adds the ExtraErrorData integration to auth-server to capture
non-native properties.
> fix: sentry depth filtering

- packages/fxa-auth-server/lib/routes/emails.js
- packages/fxa-auth-server/test/local/routes/emails.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
Because:
* Some cached customer references were remaining which are no longer
used.
This commit:
* Removes the cached customer refresh calls.
Closes #10987
> fix(auth): remove remaining cache references

- packages/fxa-auth-server/lib/payments/processing-tasks-setup.ts
- packages/fxa-auth-server/lib/sentry.js
- packages/fxa-auth-server/scripts/paypal-processor.ts
- packages/fxa-auth-server/scripts/subscription-reminders.ts
Because:
* We want to emit metrics to know when our cron jobs start/stop.
* The processName for sentry errors in our scripts wasn't accurate
making it hard to determine cron job errors from auth-server errors.
This commit:
* Adds metrics to subscription-reminders for start/stop.
* Makes the auth-server processName conifugrable when sentry is setup
and carries the correct processName in for each subPlat script.
Closes #10991
> fix(auth): add sentry process name and sub reminder stats

- packages/fxa-content-server/app/scripts/templates/ready.mustache
- packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache
TIL you can't have comments in the `unsafeTranslate` tag, it gets added as part of the string to localize 🥲
> fix(l10n): Move l10n comments out of `unsafeTranslate` tag

- packages/fxa-payments-server/server/lib/routes/legal-docs.js
- packages/fxa-payments-server/server/lib/routes/legal-docs.test.js
Because:
- the supported languages for translated FxA and Subscription Platform
web content do not cleanly map to the translated legal docs for
subscription products
This commit:
- remove the supported language check from the legal docs redirect
Closes: #11027
> feat(legal-docs): remove supported lang check on redirect

- packages/fxa-auth-server/lib/payments/capability.ts
- packages/fxa-auth-server/lib/payments/google-play/subscriptions.ts
- packages/fxa-auth-server/lib/payments/paypal-processor.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/index.ts
- packages/fxa-auth-server/lib/routes/subscriptions/mozilla.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-auth-server/scripts/paypal-refund-fixer.ts
- packages/fxa-auth-server/test/local/payments/capability.js
- packages/fxa-auth-server/test/local/payments/google-play/subscriptions.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/mozilla.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- packages/fxa-auth-server/test/local/routes/validators.js
- packages/fxa-auth-server/test/test_server.js
- packages/fxa-support-panel/src/app/app.controller.spec.ts
- packages/fxa-support-panel/src/app/app.controller.ts
- packages/fxa-support-panel/src/config.ts
- packages/fxa-support-panel/src/remote-lookup/remote-lookup.service.spec.ts
- packages/fxa-support-panel/src/remote-lookup/remote-lookup.service.ts
- packages/fxa-support-panel/src/remote-lookup/remote-responses.dto.ts
- packages/fxa-support-panel/views/index.hbs
Because:
- support agent might want to know whether a customer has IAP
subscriptions
This commit:
- replaced the endpoint that the Support Panel used to get a list of
subscriptions with one that also includes Google Play subscriptions
- update the Support Panel to use the new endpoint and display the
Google Play subscriptions
Fixes: #10542
> feat(support-panel): add Play subscriptions to support-panel

- packages/fxa-settings/src/lib/cache.ts
- If you navigate to setting when you have multiple accounts logged in, the correct account might not load
- If `uid` is specified in url, load that user in settings if that have a valid local account
> fix(settings): load the user specified in url on settings

- .circleci/modules-to-test.js
- package.json
to use the `workspace:*` dependencies to make it easier to keep up to date
> chore(ci): update modules-to-test.js 

- packages/fxa-admin-panel/package.json
- packages/fxa-settings/package.json
- yarn.lock
- jest-watch-typeahead was converted to a native ES module which cannot be 'required()' as it is by @jest/core (v26). While we use jest v27 and jest-watch-typeahead dropped support for v26, we are currently using the latest version of react-scripts (4.0.3) which explicitly requires jest v26. Upgrading to v1 of jest-watch-typeahead breaks the ability to run tests on the payments package.
- This reverts commit 54b697535e6ac75d304b70f330ed437fca506241.
> Revert "chore(deps-dev): bump jest-watch-typeahead from 0.6.5 to 1.0.0 (#10961)"

- packages/fxa-settings/src/lib/auth-errors/en-US.ftl
* On incorrect secondary email verification code, english message is
shown instead of country translation.
* Adds error code translation for secondary email verification code.
Closes #
[9209](https://github.com/mozilla/fxa/issues/9209)
> fix(settings): l10n for email verif. error code

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/PayPalButton/index.tsx
- packages/fxa-payments-server/src/components/PaymentMethodHeader/index.scss
- packages/fxa-payments-server/src/components/PaymentMethodHeader/index.stories.tsx
- packages/fxa-payments-server/src/components/PaymentMethodHeader/index.test.tsx
- packages/fxa-payments-server/src/components/PaymentMethodHeader/index.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.scss
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
Because:
* The Paypal button should only be active once the consent checkbox is
selected.
This commit:
* Moves the consent form in the existing user subscription flow to the
top of the screen. Matches behaviour and look of new user flow.
Closes #
[10652](https://github.com/mozilla/fxa/issues/10652)
Without consent checked
With consent checked
> fix(subscription): enable paypal on consent

- packages/fxa-admin-panel/package.json
- packages/fxa-admin-panel/src/App.test.tsx
- packages/fxa-admin-panel/src/components/AccountSearch/Account/index.test.tsx
- packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
- packages/fxa-admin-panel/src/components/AccountSearch/index.test.tsx
- packages/fxa-admin-panel/src/components/AccountSearch/index.tsx
- packages/fxa-admin-panel/src/setupTests.js
- packages/fxa-admin-server/package.json
- packages/fxa-admin-server/pm2.config.js
- packages/fxa-admin-server/src/app.module.ts
- packages/fxa-admin-server/src/graphql.ts
- packages/fxa-admin-server/src/schema.gql
- yarn.lock
- We currently manually define our GraphQL Typescript types, but we shouldn't need to 
- Generate them automatically, use them
- Bonus: adds the nest cli as a dev dependency so you don't need it installed on your system to call it
- Bonus: makes use of setupTests feature of Jest to import jest-dom globally
> refactor(admin): use autogenerated ts types

- packages/fxa-auth-server/lib/payments/google-play/subscriptions.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/subscriptions/mozilla.ts
- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-auth-server/test/local/payments/google-play/subscriptions.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-auth-server/test/local/routes/subscriptions/mozilla.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/validators.js
- packages/fxa-auth-server/test/mocks.js
- packages/fxa-auth-server/test/remote/subscription_tests.js
- packages/fxa-graphql-api/src/gql/model/subscription.ts
- packages/fxa-payments-server/src/lib/mock-data.tsx
- packages/fxa-shared/subscriptions/types.ts
Because:
* We should show the 'Paid Subscriptions' link in FxA Settings for Google IAP subscribers.
* Currently, FxA Settings determines if a user has active subscriptions from the /account endpoint on the auth server.
* This endpoint previously only checked for subscriptions on the Stripe customer (what we call 'web subscriptions'), but a Google IAP subscriber with no web subscriptions won't have a Stripe customer.
This commit:
* Updates the /account route to return both IAP and web subscriptions.
Closes: #10725
This PR should not be merged before #10948 . Only the last commit is new.
> feat(auth): return IAP and web subscriptions in /account route

- packages/fxa-settings/src/components/UnitRowSecondaryEmail/en-US.ftl
- packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx
This applies to primary/secondary email fields.
- In some languages, the translation of 'none' can differ depending on the context.
- In this case the translation of none as a default for primary email would not be the same as the translation of none as a default  for secondary email.
- Introduces a distinct translation for 'none' when used in the context of secondary email.
closes #9126, closes mozilla/fxa-content-server-l10n/issues/472
> fix(settings): support contextual  translation of  'None'

- packages/fxa-event-broker/pm2.config.js
- packages/fxa-graphql-api/pm2.config.js
- packages/fxa-support-panel/pm2.config.js
There's a few cases where the 'nest' command might not be in the PATH when pm2 tries to run the script, and you end up with `/bin/bash: nest: command not found`. One example is starting a single service with `yarn workspace fxa-graphql-api start`. If we resolve the path we don't need to worry about what environment the command gets run in.
> fix(pm2): resolve nest cli path in pm2 configs

- package-scripts.js
- package.json
- packages/123done/package.json
- packages/browserid-verifier/package.json
- packages/fortress/package.json
- packages/functional-tests/scripts/test-ci.sh
- packages/fxa-admin-panel/package.json
- packages/fxa-admin-server/package.json
- packages/fxa-auth-server/package.json
- packages/fxa-content-server/package.json
- packages/fxa-content-server/scripts/test-ci.sh
- packages/fxa-customs-server/package.json
- packages/fxa-event-broker/package.json
- packages/fxa-graphql-api/package.json
- packages/fxa-payments-server/package.json
- packages/fxa-profile-server/package.json
- packages/fxa-react/package.json
- packages/fxa-settings/package.json
- packages/fxa-shared/package.json
- packages/fxa-support-panel/package.json
I've noticed ci failures where the services don't even get started up completely happening more frequently. During the brief time that circleci showed resource graphs the pm2 startup pegged both cpu and memory. If we wait for the services that have a lot of building at startup to finish before starting the next service maybe we'll have better stability.
> slow down pm2 startup

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-auth-server/lib/sentry.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* We want to update plans when the product information changes.
* We want more details about validation errors in product/plan
information rather than just the first error.
This commit:
* Uses fetchAllPlans rather than the cached plans to ensure it can
revalidate all of them when the product changes.
* Uses a new validation error Sentry reporter that extracts complete
details of validation failures with abortEarly set to false so that
all validation errors are included at once.
Closes #10826
> feat(auth): include validation details for product/plan

- packages/fxa-content-server/app/scripts/views/support.js
- packages/fxa-content-server/app/tests/spec/views/support.js
- packages/fxa-shared/subscriptions/metadata.ts
Because:
- IAP subscribers should be able to use the web support form
This commit:
- handle Google Play IAP subscriptions for the support form by using
the SKU as the plan id in metrics events
- (the access to the form was granted as a side effect of adding the
Google Play subscriptions to /account endpoint response)
Closes: #10865
> feature(subscriptions): allow IAP subscribers to use Support Form

- packages/fxa-auth-server/lib/routes/index.js
- packages/fxa-auth-server/lib/routes/subscriptions/index.ts
- packages/fxa-auth-server/lib/routes/subscriptions/mozilla.ts
- packages/fxa-auth-server/lib/routes/support-panel.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/mozilla.js
- packages/fxa-auth-server/test/local/routes/support-panel.js
- packages/fxa-support-panel/src/config.ts
Because:
- the auth-server route for the Support Panel to fetch subscriptions
was not in an intuitive location
This commit:
- rename and move the route
This is a follow-up to PR #10948 based on https://github.com/mozilla/fxa/pull/10964#discussion_r751507150
> refactor(support-panel): move support panel subscriptions route

- packages/fxa-auth-server/lib/senders/emails/auth.ftl
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/newDeviceLogin/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postAddAccountRecovery/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionsPaymentExpired/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionsPaymentExpired/index.mjml
Because:
* Per our legal counsel, "Firefox Cloud" should be treated as a brand for now
* There is additional feedback in the l10n PR
This commit:
* Adds new product term, expands on comments for clarity, incorporates feedback
--
Hopefully the last round here. This is the branch I'm running [this script](https://github.com/LZoog/po-translations-to-ftl) (will tweak this later for reuse) on to generate [this PR](https://github.com/mozilla/fxa-content-server-l10n/pull/527). Once that PR is merged I'll merge this, and it'll close #10600
> chore(auth-server): Additional FTL tweaks based on feedback

- packages/fxa-content-server/app/scripts/lib/email-domain-validator.js
- packages/fxa-content-server/app/scripts/views/behaviors/navigate.js
- packages/fxa-content-server/app/scripts/views/form.js
- packages/fxa-content-server/app/scripts/views/tooltip.js
- packages/fxa-content-server/app/tests/spec/views/behaviors/navigate.js
- packages/fxa-settings/src/components/ModalVerifySession/en-US.ftl
- packages/fxa-settings/src/components/PageSecondaryEmailAdd/en-US.ftl
* Various error and notification texts are not rendered in the browsers
lanugage.
* Updated ftl's with missing error codes.
* Updated showValidationError to translate texts with string
placeholders.
* Update navigate behavior to translate success texts.
Closes #
[9860](https://github.com/mozilla/fxa/issues/9860)
[10151](https://github.com/mozilla/fxa/issues/10151)
[9230](https://github.com/mozilla/fxa/issues/9230)
[9207](https://github.com/mozilla/fxa/issues/9207)
> fix(content): l10n for texts in settings+content

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/event_tax_rate_created.json
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/event_tax_rate_updated.json
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* We want to reduce API calls to Stripe to avoid being rate limited.
* Similar to Stripe Plans and Products (#10518), Tax Rates don't change very often.
* Tax rates are unnecessarily fetched from Stripe every time a subscription is created with a TTL of 10 minutes.
This commit:
* Caches tax rates in Redis (effectively) indefinitely.
* Refreshes the cache on tax_rate.created or tax_rate.updated webhooks.
Closes #10745
> refactor(auth): cache tax rates in Redis (effectively) indefinitely

- _dev/pm2/infrastructure.config.js
- _dev/pm2/start.sh
- _scripts/check-url.sh
- package-scripts.js
On M1 we currently sometimes need to 'yarn restart services' after a 'yarn start' before things start working. Maybe if we wait for the containers to be responsive before starting services we can avoid this. The important one seems to be mysql.
> chore(dev): wait for containers on 'yarn start'

- packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.scss
* Title on subscription upgrade page isn't displayed when height is
<= 480px and width >= 768px.
* Always display title on subscription upgrade page.
Closes #
[9956](https://github.com/mozilla/fxa/issues/9956)
Before change for width 1058 x 480
After change for width 1058 x 480
> fix(subscriptions): always show title on upgrade

- packages/fxa-auth-server/lib/payments/capability.ts
- packages/fxa-auth-server/lib/routes/account.ts
Because:
- CapabilityService uses StripeHelper without checking relevant feature
flags, leading to https://github.com/mozilla/fxa/issues/10123, whose
fix was broken by
https://github.com/mozilla/fxa/commit/878a991ce489e4b28d289734933e0b945a506eb7
This commit:
- update the temporary fix in
https://github.com/mozilla/fxa/commit/3f5880ee168889c5d243c40846c533576144675c
due to a change how CapabilityService uses StripeHelper
> fix(configs): fix CapabilityService's dep on StripeHelper again

- packages/fxa-settings/README.md
- We're going to be converting payments server styles over to Tailwind soon and could use another example
- Adds an alternative in our docs for keeping rtl styles nested within a parent class
---
smol PR, just wanted to quickly document this because it came in handy when working on the [switch UI rtl styles](https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/styles/switch.scss).
> chore(docs): Add parent selector example to rtl styles

- .github/dependabot.yml
- packages/fxa-admin-panel/package.json
- packages/fxa-settings/package.json
- yarn.lock
- Adding the detailed explanation from @IvoJP in #11045 below.
- jest-watch-typeahead was converted to a native ES module which cannot be 'required()' as it is by @jest/core (v26). While we use jest v27 and jest-watch-typeahead dropped support for v26, we are currently using the latest version of react-scripts (4.0.3) which explicitly requires jest v26. Upgrading to v1 of jest-watch-typeahead breaks the ability to run tests on the payments package.
- Reverts mozilla/fxa#11123
- Adds an "Ignore" to dependabot.yml for `jest-watch-typeahead`
> Revert "chore(deps-dev): bump jest-watch-typeahead from 0.6.5 to 1.0.0"

- packages/fxa-content-server/server/lib/validation.js
- packages/fxa-content-server/tests/server/flow-event.js
- packages/fxa-content-server/tests/server/routes/get-metrics-flow.js
- Our auth-server and content-server have different validation for the service param. Ref https://github.com/mozilla/fxa/blob/e81f5e077cee59ec0c0bbc5bcd78931358b7be18/packages/fxa-auth-server/lib/routes/validators.js#L96
- Updates content-server to use auth-server validaiton which is more generic
Closes: #https://github.com/mozilla/fxa/issues/11130
We will probably want to put this on a point release if it is a blocker for metrics analysis.
> fix(metrics): update content-server regex to match the auth-server regex

- packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/index.tsx
* During subscription upgrade under certain screen sizes the regular and
the mobile `Review your change` headings are shown.
* Ensures that only one of the headings is shown.
Closes #
#9956 
> fix(subscriptions): sub upgrade remove dup heading

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/lib/sentry.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/sentry.js
Because:
* RPs may enter invalid product/plan metadata into Stripe, and the only feedback are Sentry errors in #fxa until a better solution is made following FXA-3655.
* The Sentry error message is currently not descriptive regarding what the issue is, and RPs may not have access to Sentry to view more error details.
This commit:
* Includes as much actionable information in the Sentry error message about the validation error as possible, up to the ~100 character limit.
Closes #10827 
The error message limited to around 100 characters in Slack, and given that a product or plan id can have around 30 characters, this doesn't leave much room for more descriptive messages.
E.g. a plan update with multiple validation errors would have a Sentry message like: …
> feat(auth): include product/plan validation details in Sentry message

- packages/fxa-auth-server/scripts/bulk-mailer/normalize-user-records.js
- packages/fxa-auth-server/test/scripts/bulk-mailer/normalize-user-records.js
- `getUTCMonth` is 0 based
- `setUTCMonth` rolls over if the day of the month beforehand is larger than the target can handle
> fix(bulk-mailer): date normalization was wrong

- packages/fxa-admin-panel/package.json
- packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
- yarn.lock
Because:
* The Account History table was styled locally but did not appear styled in production
This commit:
* Converts Material-UI styles to Tailwind classes
Closes #11100
Material-UI is being used in one other component (fxa-settings - PageAvatar), and therefore the MUI dependency cannot yet be fully removed.
> feat(admin-panel): account history table styles not working

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/bounces.js
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/test/local/bounces.js
- We don't want to stop user from getting access to their account because of a bounced email
- Skips the bounce checks if it is a login verification emaill, password reset email, rate limiting unblock email or subscription service finish account setup email
Closes https://github.com/mozilla/fxa/issues/11047
> Don't bounce emails that might stop user access

- packages/fxa-auth-server/lib/metrics/amplitude.js
- packages/fxa-auth-server/lib/metrics/events.js
- packages/fxa-auth-server/test/local/metrics/amplitude.js
- We were overriding hapi request artifacts when setting metrics uid to be used later
- Adds the uid to object
Closes: https://github.com/mozilla/fxa/issues/11209
Targeted as a point release on train-220.
> fix(metrics): Don't override hapi request artifacts

- packages/fxa-auth-server/package.json
- yarn.lock
Reverts mozilla/fxa#11200
because we don't support react-router-dom 6.0.0 yet
we should be able to upgrade after #11188
> Revert "chore(deps-dev): bump @storybook/addon-toolbars from 6.3.12 to 6.4.2"

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Because:
* We are actively converting old FxA emails to our new modernized stack.
This commit:
* Converts the `subscriptionUpgrade` subscription platform email to the new stack.
Closes #9293
> feat(auth-server): convert subscriptionUpgrade email template to stack

- packages/fxa-settings/src/components/ModalVerifySession/en-US.ftl
- packages/fxa-settings/src/components/PageSecondaryEmailAdd/en-US.ftl
- packages/fxa-settings/src/lib/auth-errors/en-US.ftl
- Current location of auth errors creates new sections in settings.ftl.
- Moves all auth-error-xxx messages to common location.
> fix(settings): move auth errors to common file

- packages/fxa-settings/src/components/DataBlock/index.test.tsx
- packages/fxa-settings/src/components/DataBlock/index.tsx
- packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.test.tsx
- packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.tsx
- packages/fxa-settings/src/components/PageTwoStepAuthentication/index.test.tsx
- packages/fxa-settings/src/components/PageTwoStepAuthentication/index.tsx
- packages/fxa-settings/src/lib/totp.ts
* When a user would manually copy recovery codes, codes would be mashed together without any newline or white space to separate them.
- Introduces a trailing whitespace on recovery codes, which allows copy and paste to be more user friendly.
- Hijacks onCopy event, which allows white space to be converted to newlines.
Closes #11042
> fix(settings): fix copy and paste of recovery codes

- package-scripts.js
- packages/fxa-dev-launcher/bin/fxa-dev-launcher
- packages/fxa-dev-launcher/bin/fxa-dev-launcher.mjs
- packages/fxa-dev-launcher/index.js
- packages/fxa-dev-launcher/package.json
- packages/fxa-dev-launcher/profile.mjs
- yarn.lock
- fxa-dev-launcher module uses `chalk` dep, which was updated to be an esm module, this caused fxa-dev-launcher to break because it couldn't use commonJS and esm syntax
- Updates fxa-dev-launcher to use new esm syntanx
- Removes audit filter checks sicne we don't that use that anymore
Closes: #
> chore(deps): Update fxa-dev-launcher to use esm

- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml
Because:
* `subscriptionUpgrade` email was generating incorrect footer text
This commit:
* Fixes footer text in `subscriptionUpgrade`, and it should generate the correct footer text when `subscriptionDowngrade` is created
Closes #11252
Old email template with correct footer text
Converted template - before
Converted template - after
> fix(auth-server): fix email footer text in subscriptionUpgrade

- packages/fxa-auth-server/lib/sentry.js
- packages/fxa-auth-server/test/local/sentry.js
- Logging hard email bounces to sentry is unnecessary.
- Adds a constant, IGNORED_ERROR_NUMBERS, that contains a set of error numbers to ignore that will not be reported to sentry.
Closes: #10679
> fix(auth): do not log hard email bounces to sentry

- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailChangePassword/index.txt
- packages/fxa-auth-server/lib/senders/emails/partials/automatedEmailResetPassword/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/newDeviceLogin/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/newDeviceLogin/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/newDeviceLogin/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/postChangePrimary/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postChangePrimary/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveSecondary/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/postVerifySecondary/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/verifySecondaryCode/index.txt
Because:
* variables were not replaced with the corresponding data in plaintext version of templates
This commit:
* fixes the plaintext templates
Closes #11236
> fix(auth-server): variables are not replaced in new email templates

- packages/fxa-auth-server/lib/oauth/db/index.js
- packages/fxa-auth-server/lib/oauth/token.js
- packages/fxa-auth-server/test/lib/oauth-test.json
- packages/fxa-auth-server/test/oauth/api.js
- packages/fxa-auth-server/test/oauth/db/index.js
- For legacy reasons, we still need to allow expired pocket tokens to fetch a users profile, regardless of expiration
- Skips expriation check for pocket client ids
Closes: #11250
> fix(tokens): Don't check expiration dates for pocket access token on profile server

- .github/workflows/upload-assets-to-cdn.yml
- CODEOWNERS
- Uploading assets to the CDN is currently a manual process.
- Github action that will upload assets to stage/prod CDNs when changes to assets/product-icons assets/legal are merged to main. 
This has been tested in stage but the role has not been created in production yet.
> Automatic asset upload

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/en.ftl
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.txt
- packages/fxa-auth-server/lib/senders/emails/partials/cancellationSurvey/en.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/cancellationSurvey/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/cancellationSurvey/index.txt
- packages/fxa-auth-server/lib/senders/emails/storybook-email.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
feat(auth-server): convert subscriptionAccountDeletion email template to stack
Because:
This commit:
* Converts the `subscriptionAccountDeletion` subscription platform email to the new stack.
Closes #9270
Old template
New template
Just wanted to call out that there are a few new additions other than the converted `subscriptionAccountDeletion` email templates. Please see below:
(1) The plaintext in the old email template has `Cancel subscription` in its footer, while the HTML has `Reactivate subscription`. As this is a cancellation email, both HTML and plaintext should reflect `Reactivate subscription`. Therefore, the following files needed to be updated:
* …
> feat(auth-server): convert subscriptionAccountDeletion email template to stack

- packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/index.txt
Because:
* plaintext version of template contained incorrect text
This commit:
* reflects the revised text
Closes: #11221 
> fix(auth-server): [new email templates] postAddTwoStepAuthentication

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/en.ftl
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.txt
- packages/fxa-auth-server/lib/senders/emails/partials/cancellationSurvey/en.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/cancellationSurvey/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/cancellationSurvey/index.txt
- packages/fxa-auth-server/lib/senders/emails/storybook-email.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
We merged these into a separate branch at first while we worked on #11249 to help the l10n team out, but I've got it working locally now and will get the l10n PR (unopened at present, but [here's the branch](https://github.com/mozilla/fxa-content-server-l10n/compare/subplat-email-templates))  merged by Friday (when our cron job occurs), so it's fine to get these merged into `main` for the train.
> Merge subscriptionUpgrade and subscriptionAccountDeletion into main

- .circleci/config.yml
Ever since circleci released their resources panel (or thereabout) we've been getting a lot of these from settings-react:
```
The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
```
In order to unblock PRs this increases the size to large so we won't run out of memory until we can investigate further.
> chore(ci): increase content-server tests to large size

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionDowngrade/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionDowngrade/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionDowngrade/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionDowngrade/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Because:
This commit:
* Converts the `subscriptionDowngrade` subscription platform email to the new stack.
Closes: #9274
Old template
New template
A revision  of the following file is needed to include the `Terms and cancellation policy` link when emails have the `productNameNew` variable instead of `productName`.
* `emails/layouts/subscription/index.txt`
Please note, `emails/layouts/subscription/index.mjml` was  revised in #11253.
> feat(auth-server): convert `subscriptionDowngrade`

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Because:
This commit:
* Converts the `subscriptionCancellation` subscription platform email to the new stack.
Closes #9272
Old template
New template
In addition to the `subscriptionCancellation` email templates, the apostrophes in the following 3 files have also been updated:
* `emails/templates/subscriptionAccountDeletion/en.ftl `
* `emails/templates/subscriptionAccountDeletion/index.mjml `
* `emails/templates/subscriptionAccountDeletion/index.txt `
> feat(auth-server): convert `subscriptionCancellation`

- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/unblockCode/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verify/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verifySecondary/index.stories.ts
This commit:
* Modifies a few email Storybook docs
* Changes 'Firefox Account' to 'Firefox account', uses the ftl placeholder
Because:
* Some descriptions could be more accurate
* We recently decided to use "account" rather than "Account", this follows our new pattern set in emails
> chore(auth-server): Update email storybook docs, update Fx 'Account' to Fx 'account'

- packages/fxa-auth-server/lib/payments/stripe-formatter.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/lib/types.ts
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/invoice_preview_tax.json
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/invoice_preview_tax_discount.json
- packages/fxa-auth-server/test/local/payments/stripe-formatter.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/payments/util.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- packages/fxa-shared/dto/auth/payments/invoice.ts
- packages/fxa-shared/index.ts
- packages/fxa-shared/package.json
- yarn.lock
Because:
* We want to preview coupon code application to an invoice in the
checkout flow.
This commit:
* Adds an invoice preview route that takes promotion codes and returns
an invoice preview suitable for the checkout display.
Closes #10856
> feat(auth): add invoice preview route

- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountDeletion/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionCancellation/index.txt
Because:
* opening single quotes were used instead of closing quotes.
This commit:
* replaces opening quotes with closing ones.
> fix(auth-server): revise emails to update apostrophes

- packages/fxa-auth-server/lib/error.js
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
* We want to accept promotion codes when creating a new subscription.
This commit:
* Updates the new subscription routes for stripe and paypal to validate
the coupon for the plan and apply it when creating the subscription.
Closes #10854
> feat(auth): add coupon to new sub api

- packages/fxa-auth-server/lib/routes/subscriptions/support.ts
Because:
* The location may not be defined in some scenarios, such as local
testing, which a prior commit made optional as a result.
This commit:
* Uses optional chaining for properties that may not be present.
> fix(auth): fix location optional

- _dev/docker/docker-compose.yml
- db-migrations script failed to work on mysql 5.6
- update mysql server to 5.7
Issue #10526
Here already using mysql server 5.7
https://github.com/mozilla/fxa/blob/9cda83496a410ad4df414a6730872e6aa0ef793f/_scripts/mysql.sh#L25
> chore(dev): update dev docker-compose mysql server to 5.7

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/partials/updateBilling/en.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/updateBilling/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/updateBilling/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionPaymentFailed/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionPaymentFailed/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionPaymentFailed/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionPaymentFailed/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionsPaymentExpired/index.mjml
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Because:
This commit:
* Converts the `subscriptionPaymentFailed` subscription platform email to the new stack
Closes: #9282 
Old template
New template
The following files were added to create the `updateBilling` partial:
* `emails/partials/updateBilling/en.ftl`
* `emails/partials/updateBilling/index.mjml`
* `emails/partials/updateBilling/index.txt`
In addition, the whitespace was revised in the following file:
* `emails/templates/subscriptionsPaymentExpired/index.mjml`
> feat(auth-server): convert `subscriptionPaymentFailed`

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionPaymentProviderCancelled/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionPaymentProviderCancelled/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionPaymentProviderCancelled/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionPaymentProviderCancelled/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Because:
This commit:
* Converts the `subscriptionPaymentProviderCancelled` subscription platform email to the new stack.
Closes: #9284 
Old template
New template
> feat(auth-server): convert `subscriptionPaymentProviderCancelled`

- README.md
- packages/functional-tests/pages/settings/layout.ts
- packages/functional-tests/tests/prod.smoke.spec.ts
- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/lib/db/index.js
- packages/fxa-auth-server/lib/routes/recovery-codes.js
- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-auth-server/test/local/routes/recovery-codes.js
- packages/fxa-auth-server/test/local/routes/validators.js
- packages/fxa-auth-server/test/mocks.js
- packages/fxa-content-server/server/config/local.json-dist
- packages/fxa-content-server/server/lib/beta-settings.js
- packages/fxa-content-server/server/lib/configuration.js
- packages/fxa-content-server/tests/functional/settings/two_step_auth.js
- packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/en-US.ftl
- packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.test.tsx
- packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.tsx
- packages/fxa-settings/src/lib/config.ts
- packages/fxa-settings/src/lib/random.test.ts
- packages/fxa-settings/src/lib/random.ts
- packages/fxa-settings/src/models/Account.ts
- When generating new recovery codes, there was no confirmation step, which might make it easy for a user to overlook the fact they should download / record their recovery codes.
- Introduces the same dialog, which existed in the initial 2FA flow, that prompted a user for at least one recovery code as a way to validate users had recorded them
- Introduces the same dialog, which existed in the initial 2FA flow, that prompted a user for at least one recovery code as a way to validate users had recorded them
- Introduces back end support for creating and updating recovery codes as a two step process
- Shifts recovery code generation to client, relocating crypto/random.ts to fxa-shared, so it's accessible
- Adds validation for recovery codes being updated
- Exposes recovery code length / …
> fix(settings): add confirm recovery code modal

- packages/db-migrations/bin/patcher.mjs
- packages/db-migrations/databases/development.json
- packages/db-migrations/package.json
- yarn.lock
- Currently, db-migrations script hard coded database configurations.
- Support reading configurations from environment or json configuration files.
Issue: #10526
It would be useful for self hosting.
> chore(db-migrations): support database configurations for db-migrations script.

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/auth.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/paymentProvider/en.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/paymentProvider/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/paymentProvider/index.txt
- packages/fxa-auth-server/lib/senders/emails/partials/viewInvoice/en.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/viewInvoice/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/viewInvoice/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoice/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoice/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoice/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoice/index.txt
- packages/fxa-auth-server/scripts/write-emails-to-disk.js
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Because:
This commit:
* Converts the `subscriptionFirstInvoice` subscription platform email to the new stack
Closes: #8276
Old template
New template - PayPal
New template - Stripe
Two new partials were created - `paymentProvider` and `viewInvoice`
* `emails/partials/paymentProvider/en.ftl`
* `emails/partials/paymentProvider/index.mjml`
* `emails/partials/paymentProvider/index.txt`
* `emails/partials/viewInvoice/en.ftl`
* `emails/partials/viewInvoice/index.mjml `
* `emails/partials/viewInvoice/index.txt`
Draft pull request due to the following:
~~* PayPal placeholder (WIP)~~
~~* Link to use for `invoiceLink` in `emails/partials/viewInvoice/en.ftl`?~~
~~* Failing test - link to view …
> feat(auth-server): convert `subscriptionFirstInvoice`

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionsPaymentProviderCancelled/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionsPaymentProviderCancelled/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionsPaymentProviderCancelled/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionsPaymentProviderCancelled/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Because:
This commit:
* Converts the `subscriptionsPaymentProviderCancelled` subscription platform email to the new stack.
Closes: #9299 
Old template
New template
* The `Terms and cancellation policy` link has been added to the footer of emails with multiple subscriptions.
* The Storybook layout for multiple products has been updated.
> feat(auth-server): convert `subscriptionsPaymentProviderCancelled`

- packages/functional-tests/tests/prod.smoke.spec.ts
- packages/fxa-settings/src/components/ConnectedServices/index.tsx
- packages/fxa-settings/src/lib/firefox.ts
- packages/fxa-settings/src/models/Account.ts
- packages/fxa-shared/db/models/auth/device.ts
- A test started failing that was destroying attached devices
- Coerces device.sessionTokenId from a buffer into a hex string for comparison
- Coerces device.refreshTokenId from a buffer into a hex string for comparison
closes #11011
> bug(auth): destroying attached client would fail

- packages/fxa-auth-server/lib/senders/emails/auth.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/paymentProvider/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionsPaymentProviderCancelled/en.ftl
Fixes strings mentioned in [merge strings for train 36061](https://github.com/mozilla/fxa-content-server-l10n/pull/541)
> fix(auth-server): revised strings for brand names

- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
Because:
* We want to capture additional billing details for PayPal users based
on their IP for tax compliance.
This commit:
* Captures the general location via the IP on the request and adds it to
the Stripe customer record.
Closes #11068
> feat(auth): add ip geo data when it matches billing country for paypal

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/global.scss
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.scss
- packages/fxa-auth-server/lib/senders/emails/partials/button/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/button/index.scss
- packages/fxa-auth-server/lib/senders/emails/partials/icon/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/paymentPlanDetails/en.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/paymentPlanDetails/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/paymentPlanDetails/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountFinishSetup/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountFinishSetup/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountFinishSetup/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountFinishSetup/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionDowngrade/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoice/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionPaymentFailed/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionReactivation/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionSubsequentInvoice/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionUpgrade/index.mjml
- packages/fxa-auth-server/lib/senders/templates/subscriptionAccountFinishSetup.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Because:
This commit:
* Converts the `subscriptionAccountFinishSetup` subscription platform email to the new stack.
Closes: #10225
Old template
New template - Full details
New template - Invoice Number
New template - Invoice Date & Invoice Total
New template - Next Invoice
Per @LZoog 's request, update `1xl` to `2xl` in the following files:
* `emails/global.scss`
* `emails/layouts/subscription/index.scss`
Revisions to button partial - do not affect FxA email templates
* `emails/partials/button/index.mjml`: Added conditional `className` to button
* `emails/partials/button/index.scss`: Removed unnecessary import that affected the format of entire email
Added `icon` partial:
* …
> feat(auth-server): convert `subscriptionAccountFinishSetup`

- packages/fxa-auth-server/package.json
Because:
* When you check into a branch with new or updated FTL strings and you run storybook-mjml, strings will be missing since the file hasn't been concatenated locally yet
This commit:
* Adds 'grunt merge-ftl' to the start of 'storybook-mjml' script
> chore(auth-server): Add 'merge-ftl' to 'storybook-mjml' command

- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountReminderSecond/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountReminderSecond/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountReminderSecond/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountReminderSecond/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Because:
This commit:
* Converts the `subscriptionAccountReminderSecond` subscription platform email to the new stack.
Closes: #10911
Old template
New template
Note, `subscriptionAccountReminderSecond` is already included in `dev.json`
I have added the update of the button from "Create a password" to "Create Password" to the Confirmation Needed doc.
> feat(auth-server): convert `subscriptionAccountReminderSecond`

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/partials/subscriptionSupportContact/en.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/subscriptionSupportContact/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/subscriptionSupportContact/index.txt
- packages/fxa-auth-server/lib/senders/emails/partials/subscriptionUpdateBillingEnsure/en.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/subscriptionUpdateBillingEnsure/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/subscriptionUpdateBillingEnsure/index.txt
- packages/fxa-auth-server/lib/senders/emails/partials/subscriptionUpdateBillingTry/en.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/subscriptionUpdateBillingTry/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/subscriptionUpdateBillingTry/index.txt
- packages/fxa-auth-server/lib/senders/emails/partials/updateBilling/en.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/updateBilling/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionPaymentFailed/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionPaymentFailed/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionRenewalReminder/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionRenewalReminder/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionRenewalReminder/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionRenewalReminder/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Because:
This commit:
* Converts the `subscriptionRenewalReminder` subscription platform email to the new stack.
Closes #10227
Old template
New template
Added `subscriptionSupportContact` partial:
* `emails/partials/subscriptionSupportContact/en.ftl`
* `emails/partials/subscriptionSupportContact/index.mjml`
* `emails/partials/subscriptionSupportContact/index.txt`
Added `subscriptionUpdateBillingEnsure` partial:
* `emails/partials/subscriptionUpdateBillingEnsure/en.ftl`
* `emails/partials/subscriptionUpdateBillingEnsure/index.mjml`
* `emails/partials/subscriptionUpdateBillingEnsure/index.txt `
Revised `updateBilling` partial to `subscriptionUpdateBillingTry` to avoid confusion:
* …
> feat(auth-server): convert `subscriptionRenewalReminder`

- packages/fxa-auth-server/config/dev.json
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFailedPaymentsCancellation/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFailedPaymentsCancellation/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFailedPaymentsCancellation/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFailedPaymentsCancellation/index.txt
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Because:
This commit:
* Converts the `subscriptionFailedPaymentsCancellation` subscription platform email to the new stack.
Closes: #10226 
New Template:
Old Template:
> feat(auth): convert subscriptionFailedPaymentsCancellation email templates

- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
- there's no email in the request
This commit:
- switch to use ip only check with customs
> fix(subscriptions): use ip only customs check on invoicePreview

- packages/fxa-auth-server/lib/senders/emails/templates/postVerifySecondary/index.txt
Because:
* Text in plain version of postVerifySecondary template was different than HTML version and old template
This commit:
* Revises the plain text to reflect correct wording
Closes: #11350
> fix(auth-server): text in plain version of postVerifySecondary template

- packages/fxa-payments-server/server/config/index.js
- packages/fxa-payments-server/src/components/CouponForm/index.stories.tsx
- packages/fxa-payments-server/src/components/CouponForm/index.test.tsx
- packages/fxa-payments-server/src/components/CouponForm/index.tsx
- packages/fxa-payments-server/src/components/PlanDetails/index.tsx
- packages/fxa-payments-server/src/lib/apiClient.test.ts
- packages/fxa-payments-server/src/lib/apiClient.ts
- packages/fxa-payments-server/src/routes/Checkout/index.scss
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.scss
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx
- The apply button should validate the coupon entered by the user
- Calls the invoice preview endpoint with the priceId and coupon code
when the Apply button is pressed.
Closes: #10850
>  feat(Coupon): add backend call to coupon apply btn 

- packages/fxa-payments-server/src/components/CouponForm/index.tsx
Because:
* We dont want to display the hard-coded test code if a coupon is present on page load
This commit:
* Uses the couponCode property of the coupon for display purposes
Closes #11426
> fix(payments): remove hard-coded test coupon code

- README.md
Because:
* We removed the `mysql_servers.json` file but didn't remove this link
This commit:
* Removes the link
Fixes #9235
> docs(readme): fix a broken link

- packages/fxa-auth-server/scripts/delete-account.js
- packages/fxa-auth-server/test/scripts/delete-account.js
Because:
- the script was erroring due to
- missing dependencies
- change in the account routes export
This commit:
- add the ProfileClient Firestore deps to the Container
- fix account routes init
- add a test
>  fix(scripts): add deps and fix route init for delete acct script

- .circleci/config.yml
Last time node 16 seemed to cause higher test instability so we rolled it back but maybe we've fixed enough kinks now.
> chore(ci): use node 16 in circleci

- packages/fxa-auth-server/scripts/delete-account.js
* The accountRoutes function has some new args that need to be added to
the delete account script.
* Adds the missing deps to the account script.
> fix(scripts): add new deps to delete acct script

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
- there's a mismatch between an event type in Stripe's SDK types and
docs and what's actually sent
This commit:
- update the type to the one that's actually in the payload
Closes: #11335
> fix(subscriptions): update a payment method webhook event type

- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/emails/fluent-localizer.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveTwoStepAuthentication/en.ftl
- packages/fxa-auth-server/test/local/senders/email.js
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
> fix(auth-server): subject for 2FA email template is different

- packages/fxa-payments-server/src/components/PlanDetails/index.test.tsx
- packages/fxa-payments-server/src/components/PlanDetails/index.tsx
* Plan total price interval is not being translated.
* Reverts localized id to previous value so that it uses existing
translations
Closes: #11493 
Before the change (Notice total price interval didn't translate and reads  "Gesamt $1.00 daily")
After fix (The interval is now translated as expected. In this case "pro Woche")
> fix(coupon): plan total price interval translation

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
- we need the Stripe customer's location for tax purposes
This commit:
- on a new subscription or a payment method update, set the customer's
location with the available country and postal code
Closes: #11069
> feat(subscriptions): set customer location with payment info

- packages/fxa-auth-server/lib/payments/stripe-firestore.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-auth-server/test/local/payments/stripe-firestore.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- packages/fxa-auth-server/test/local/routes/validators.js
- packages/fxa-shared/subscriptions/types.ts
Because:
- the payments frontend need to know, for metrics, the promo code value
a subscription with which it was created
This commit:
- switch the subscription creation to use a promotion code instead of a
coupon so that the promotion code is associated with the
subscription's discount
- there is a one to many relationship from a coupon to promotion
codes, so if we create a subscription with a coupon looked up by a
promotion code, we wouldn't know which promotion code was
originally used
- include the promotion code value in the subscriptions list for the
frontend
Closes: #11376
> feat(subscriptions): create subs with promo codes

- packages/fxa-auth-server/lib/routes/util.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-metrics-processor/src/lib/amplitude/transforms/event-properties.ts
- packages/fxa-metrics-processor/src/lib/amplitude/transforms/types.ts
- packages/fxa-payments-server/src/components/CouponForm/index.tsx
- packages/fxa-payments-server/src/lib/amplitude.ts
- packages/fxa-payments-server/src/lib/apiClient.test.ts
- packages/fxa-payments-server/src/lib/apiClient.ts
- packages/fxa-shared/metrics/amplitude.js
- We want to add new coupon metrics for view, engage, submit, fail and
success.
- Update existing payment metrics to include coupon code if used.
- Adds the new event type as well as event functions.
- Trigger event functions in Coupons components (TODO)
- Update existing payments events with coupon codes.
Closes: #11361
> feat(coupons): add coupon metrics

- packages/fxa-auth-server/lib/senders/emails/templates/postVerifySecondary/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/postVerifySecondary/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postVerifySecondary/index.txt
The old template reflects the word as 'for' instead of 'from'.
Note: this fix creates a new ftl ID, `postVerifySecondary-content`.
Closes: #11513
> fix(auth-server): Text difference in postVerifySecondary template

- packages/fxa-payments-server/src/lib/amplitude.ts
- packages/fxa-payments-server/src/lib/apiClient.test.ts
- packages/fxa-payments-server/src/lib/apiClient.ts
- packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.test.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/Cancel/CancelSubscriptionPanel.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx
- packages/fxa-payments-server/src/store/actions/api.ts
- packages/fxa-payments-server/src/store/sequences.test.ts
- packages/fxa-payments-server/src/store/sequences.ts
Because:
- we need to include a subscription's promotion code in the
subscription cancellation metrics events
This commit:
- add the subscription's promotion code as an event property to the
cancellation events
Closes: #11378
> feat(metrics): include promo code for cancel sub events

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/index.txt
- packages/fxa-auth-server/lib/senders/templates/subscriptionFirstInvoiceDiscount.html
- packages/fxa-auth-server/lib/senders/templates/subscriptionFirstInvoiceDiscount.txt
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/invoice_paid_subscription_create_discount.json
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
- packages/fxa-auth-server/test/mocks.js
- The discount amount and original price needs to be included in the
first invoice email.
- Adds Subtotal and One-time discount fields to the first invoice email.
Closes: #11341 
Existing account - first invoice
Passwordless flow - first invoice
Passwordless flow - initial email (no changes made to this)
> feat(coupons): add discount to 1st invoice email

- packages/fxa-auth-server/bin/email_notifications.js
- packages/fxa-auth-server/lib/payments/processing-tasks-setup.ts
Because:
* Our cron job scripts weren't running, as StripeHelper now requires
AppConfig to be setup.
This commit:
* Sets AppConfig for the Container for the scripts to start correctly.
Closes #11519
> fix(auth): setup appconfig where needed for scripts

- packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
- packages/fxa-settings/src/constants/index.tsx
- Firefox lockwise is no longer valid.
- Removes the link for firefox lockwise on the Delete Account page
Closes: #11421
> bug(settings): Remove firefox lockwise from Delete Account page

- packages/fxa-auth-server/lib/senders/emails/fluent-localizer.ts
- packages/fxa-auth-server/test/local/senders/emails/fluent-localizer.ts
##Because:
- Failing on a missing l10n id was probably too aggressive at the moment
##This commit:
- Comments out the error that requires all data-l10n-ids to be present in the en bundle
Closes: #11523
We are seeing some failing emails on stage despite all tests passing. This needs a bit more investigation.
> bug(auth): Don't fail when l10n id is missing from en bundle

- packages/fxa-auth-server/lib/payments/customer-locations.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
- accounting only need the province/state for CA and US customers
This commit:
- skips the address lookup on new subscription or payment method update
when the customer is not from CA or US
Co-authored-by: Bianca Danforth <bdanforth@mozilla.com>
> fix(subscriptions): do addr lookup for only US and CA

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/event_coupon_created.json
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* We want to know if coupons are created with product
requirements as we enforce them differently.
This commit:
* Reports a product restriction on a coupon to Sentry if one is
created in Stripe.
Closes #11427
> feat(auth): add coupon validation

- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* Some cleanups were missed in the prior PR.
This commit:
* Adds remaining clean-ups for FXA-4356.
Ugh, failed to push before merging the prior PR after adding some of your nit clean-ups @biancadanforth .
> feat(auth): followup cleanup for FXA-4356

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/PaymentMethodHeader/index.stories.tsx
- packages/fxa-payments-server/src/components/PaymentMethodHeader/index.test.tsx
- packages/fxa-payments-server/src/components/PaymentMethodHeader/index.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
- Hard coded prefix can't be translated for different locales.
- Removes hard coded prefix from header, and instead provides a new
message that can be translated by.
Closes: #11560
> fix(subscriptions): l10n fix payment method header

- packages/fxa-auth-server/lib/senders/email.js
fixes #11575
The SES SMTP connections were hanging out too long so SES would disconnect them. By reducing the `maxMessages` from the default 100 to 10 we shouldn't be holding onto the connections long enough to "expire".
> fix(email): lower the maxMessages sent via nodemailer before creating a new connection

- packages/fxa-auth-server/lib/payments/stripe-firestore.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe-firestore.js
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
- we need a sure way of finding the applied promotion code for a
subscription
- subscription.discount is null when a one time coupon is used
This commit:
- save the applied promotion code to the subscription metadata
Closes: #11378
> feat(subscriptions): save promo code to subscription metadata

- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/en.ftl
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.txt
Closes: #11498
Legal, Privacy, and Privacy notice links have been added into the plaintext version of the email templates, as reflected in the HTML version. 
Please note, as there is already an existing ftl ID for `subplat-privacy-plaintext` for the string `Privacy notice`, the ID created for the `Privacy` in the plaintext version is `subplat-privacy-website-plaintext` as the link is `https://www.mozilla.org/privacy/websites/`.
Additional minor updates have been included in this PR (missing colons that are included in previously created ftl IDs).
> fix(auth-server): Legal and Privacy links are not displayed in the plaintext version of the templates

- packages/fxa-admin-panel/package.json
- packages/fxa-content-server/package.json
- packages/fxa-settings/package.json
- yarn.lock
Reverts mozilla/fxa#11601 because the newer version has a dependency of a postcss plugin that's incompatible.
> Revert "chore(deps): bump autoprefixer from 9.8.8 to 10.4.2"

- packages/fxa-payments-server/README.md
- Latest versions of Storybook builds are no longer published to Github
pages.
- Update docs to indicate new location where Storybooks are published.
Closes: #11468
> chore(docs): update storybook publish links

- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountReminderFirst/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountReminderSecond/index.txt
Closes #11554
This pull request updates the `subscriptionAccountReminderFirst` and `subscriptionAccountReminderSecond` emails so that the new email templates matches the old email templates. This revision removes the line "If you did not change it, please reset your password now at (resetPasswordLink)" in the plaintext of its partial.
Note: We are aware and have noted that the fine print and footer links are different between the HTML and plaintext version of the email templates.
Previously:
Update made within this PR:
`subscriptionAccountReminderFirst`
Old template
New template
`subscriptionAccountReminderSecond`
Old template
New template
> fix(auth-server): updated template to match old email template

- packages/fxa-auth-server/lib/senders/emails/partials/paymentPlanDetails/en.ftl
- packages/fxa-auth-server/lib/senders/emails/partials/paymentPlanDetails/index.txt
Closes: #11553
`Payment details:` has been added to the plaintext version in the partial. The formatting of the plaintext has also been updated within this pull request.
Previous:
Fixed within this PR:
> fix(auth-server): small difference between plaintext and HTML

- packages/fxa-content-server/app/scripts/templates/complete_reset_password.mustache
- packages/fxa-content-server/app/scripts/templates/reset_password.mustache
- packages/fxa-settings/src/components/PageDeleteAccount/en-US.ftl
- packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
- Pocket isn't changed when you reset password or delete account
- Updates our text based on their recommendations
Closes: https://github.com/mozilla/fxa/issues/11572
> fix(pocket): Update password reset and delete account notice to mention pocket

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* Our code was using the invoice object rather than the latest version
in some parts.
* We didn't check if the invoice was in draft state before finalizing.
This commit:
* Ensures the latest version of the object is always fetched before
running the webhook handler.
* Only finalizes invoices if they're in draft state.
Closes #10934
> feat(auth): use latest stripe object with proper invoice close

- packages/fxa-auth-server/lib/senders/emails/templates/verifyLogin/index.txt
Closes: #11642
The email title in the plaintext version should be "New sign-in to Firefox" instead of "Activate the Firefox family of products".
Note: While this error was reflected in emails using `yarn write-emails`, this error was not reflected in Storybook.
Old 
New
> fix(auth-server): wrong email title in plaintext version of verifyLogin template

- packages/fxa-content-server/server/templates/pages/src/index.html
- We shouldnt show this banner because if FxA is opened in a webview in another app, the user would be take to Firefox iOS to continue signup/signin which is confusing
- Removes the Firefox iOS banner
Closes: https://github.com/mozilla/fxa/issues/11648
> fix(ios): Don't show Firefox iOS banner when loading signup/signin views

- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/images.mjml
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
- The images partial includes the App Store and Google Play badges, and it passes the `productName` variable for image alt text. As there are both FxA and SubPlat emails that either should have Firefox set to `productName` or do not have a `productName` variable (reminder emails to finish account setup, payment emails, etc), a conditional needs to be added so the templates do not break. While this affects all templates, the following emails are currently not loading within Storybook:
- `subscriptionAccountReminderFirst`
- `subscriptionAccountReminderSecond`
- `subscriptionsPaymentExpired`
- `subscriptionsPaymentProviderCancelled`
- Fixes the issue by applying the conditional within the `images` partial.
Closes: #11678
> fix(auth-server): revise `images` partial

- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
- `Privacy notice` link should be displayed in the footer of subplat emails with multiple products
- Revises the conditional to include the `Privacy notice` link in the footer of subplat emails with multiple products.
- Adds spot tests to check Privacy notice is included in emails
Closes: #11677
> fix(auth-server): add Privacy notice link to subplat emails with multiple products

- packages/fxa-content-server/tests/functional/lib/helpers.js
- packages/fxa-content-server/tests/intern.js
#Because:
- Tests in CI exhibited flakiness
- Addresses edge cases where the document could be caught in an unloaded state when running querySelector
- Increases allowed pageLoadTimeout. When flakiness does occur, it appears to be due to resource constraints in the CI runner. Allowing a little more time for things to settle reduces the chance something fails due to a random slow down.
Closes: #11223
Reproducing flakiness seen in the CI can be tricky to do locally. To accomplish this I used cgroups and did several experiments with different memory limits in place. Ultimately, it seems like flakiness is correlated to available system resources, which has more or less been the suspicion all along. When there are plenty of resources and things are running …
> fix(content-server): Decrease flakiness of content server tests

- packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
- We are working on listing more than just sessions, but also connected services.
- Changes the wording to reflect that services are being listed
Closes: #11088
> chore(admin): Rename Current Session to Connected Services

- .circleci/config.yml
Because:
* builds are failing
This commit:
* increases the storybook container size
> chore(circleci): increase container size

- .circleci/config.yml
Because:
* The convenience images are expiring on Feb 7
This commit:
* Updates to use the new images
> chore(circleci): Update expiring images

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* Payment methods aren't always attached to a user when they're
added to Stripe.
This commit:
* Ignores payment method changes for unattached payment methods.
Closes #11611
> feat(auth): update webhook for payment method

- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
* We already have payment methods on file for repeat customers,
so there's no reason to report a sentry error as no PMI is included.
This commit:
* Updates the sentry reporting to require a payment method to exist.
Closes #11615
> feat(auth): dont report location set on repeat customers

- packages/fxa-auth-server/lib/routes/subscriptions/account.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/account.js
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
Because:
- on the "passwordless" subscription flow, when a user retries after a
failed subscription attempt due to a payment failure, the old invoice
of the failed subscription is used
- the finish setup email for the new FxA "stub" account was sent even
when the payment for the subscription failed
This commit:
- update the payments frontend to stop retrying the old invoice of the
failed subscription when the user is in the passwordless flow
- send the finish setup email only when the subscription is active
Closes: #11198
> fix(subscriptions): stop retry w/ old invoice; stop sending welcome email

- packages/fxa-auth-server/lib/google-maps-services.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/google-maps-services.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
* The Geocode API could return multiple address results for a given zipcode.
* Those results may have a unique state, so we shouldn't error until we've checked.
This commit:
* Checks for a unique state when multiple results are returned.
Closes #11661
----
Because:
* Sentry was treating each error as unique, when they should be grouped.
This commit:
* Removes the customer id from some Sentry error messages, so they can be correctly grouped.
Closes #11650
I'm fixing a small one-pointer in this same PR; each ticket has its own commit.
> FXA-4454 fix(auth): check for unique state on multiple results from Geocoding API

- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-auth-server/test/local/routes/validators.js
Because:
- the subscriptions endpoint for the admin-panel was returning 500s for
customers with Google Play subscriptions
This commit:
- fix the response validation that was the source of the 500s
Closes: #11491
> fix(admin-panel): update resp validation for Play subs

- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/index.js
- packages/fxa-auth-server/scripts/write-emails-to-disk.js
- packages/fxa-auth-server/test/local/senders/email.js
- packages/fxa-auth-server/test/local/senders/index.js
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
Because:
* Users that have opted out of metrics collection shouldn't have UTM params attached to links in emails
This commit:
* Passes 'metricsEnabled' into the mailer via metricsOptOutAt, which then checks for this value before adding UTM params to links
fixes #10874
---
Thankfully I over-complicated this with my first pass (re: my comments in the bug), with some fresh eyes it wasn't so bad 😛
Running `COMMON_METRICS_OPT_OUT_TESTS` for _every_ template seemed unnecessary, but I can easily add more if preferred.
> feat(auth-server): Don't include email UTM params for metrics opted out users

- packages/fxa-auth-server/lib/senders/emails/fluent-localizer.ts
- packages/fxa-auth-server/lib/senders/emails/templates/unblockCode/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/verifyLoginCode/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/verifyLoginCode/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/verifyLoginCode/index.stories.ts
- packages/fxa-auth-server/test/local/senders/mjml-emails.ts
- the HTML did not match plaintext for `verifyLoginCode` template
includes the following updates:
- As the string of the subject of the email was updated, a new ftl ID was created:
- `fxa-auth-server/lib/senders/emails/fluent-localizer.ts`
- `fxa-auth-server/lib/senders/emails/templates/verifyLoginCode/en.ftl`
- `fxa-auth-server/lib/senders/emails/templates/verifyLoginCode/index.stories.ts`
- The mjml file was updated to match the string values of the ftl IDs:
- `fxa-auth-server/lib/senders/emails/templates/verifyLoginCode/index.mjml`
- Adds the test:
- `fxa-auth-server/test/local/senders/mjml-emails.ts `
Closes: ##11696
The mjml file for the `unblockCode` email included another email title's ftl ID. Please note, both email titles have the same string …
> fix(auth-server): wrong HTML version displayed for `verifyLoginCode` template

- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.scss
While I unable to reproduce the bug within the issue, the revised stylesheet sets the font color of `li` items to match the rest of the `div`.
Closes: #11759
Old
Current
> fix(auth-server): `subscriptionAccountFinishSetup` email has strings in purple

- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountReminderFirst/index.txt
> fix(auth-server): wrong apostrophe in plaintext of `subscriptionAccountReminderFirst`

- packages/fxa-auth-server/lib/senders/emails/fluent-localizer.ts
- packages/fxa-auth-server/lib/senders/emails/localizer-bindings-node.ts
- packages/fxa-auth-server/lib/senders/emails/localizer-bindings.ts
- packages/fxa-auth-server/package.json
- packages/fxa-auth-server/test/local/senders/emails/fluent-localizer.ts
- packages/fxa-react/lib/AppLocalizationProvider.tsx
- packages/fxa-shared/l10n/otherLanguages.ts
Because:
* For Fluent translations, we pull in ftl files from public/locales, which wasn't present in dist
* Fluent was attempting to load bundles from 'OTHER_EN_LOCALES' which was causing "missing translation" errors
* We were attempting to load English dialects that may not have been correct, e.g. showing 'en-CA' dialect to US users, due to the Fluent strategy
This commit:
* Adds 'public' dir to fxa-auth-server copy list on build
* Tells the bundler to load 'en-GB' if the user locale matches one in 'OTHER_EN_LOCALES', moved into 'fxa-shared' to share with Payments and renamed to EN_GB_LOCALES
* Changes the Fluent strategy from 'filtering' to 'matching'
* Adds tests
fixes #11745
---
I think unfortunately when we work on #11529 is the right time to add the tests for this.
To repro …
> fix(auth): Copy 'public' to dist, don't load non-existent Fluent bundles, Fluent strategy tweak

- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
- packages/fxa-payments-server/package.json
Because:
- while handling a product or plan webhook event, we try to use the
product or plan from the cache; however, the products and plans in
the cache are updated through webhook events, so no product or plan
can ever be added or updated
This:
- exclude product and plan/price from the types that require fetching
the latest object during webhook event handling
Closes: #11750
> fix(subscriptions): fix product/plan webhook event handling

- .github/CODEOWNERS
- CODEOWNERS
Because:
- we shouldn't depend on humans to remember to request a PR review from
mozilla/fxa-devs
This commit:
- update and move CODEOWNERS so that mozilla/fxa-devs is the owner of
the entire repo
> chore(repo): set fxa-devs to own all things

- packages/fxa-auth-server/lib/payments/stripe.ts
Because:
- a mismatch between two Stripe type lists led to false negatives on
resource expansion
This commit:
- update the valid expand resource types to base on the Stripe object
to types map
> fix(subscriptions): match expandable resource type to Stripe obj type list

- packages/fxa-profile-server/lib/config.js
- We want to increase the mysql connection limit
- Adds an option to configure the mysql connection limit (and the queue limit just in case)
> feat(config): Add options for connection pool limit & queue limit

- packages/fxa-auth-server/config/index.ts
- packages/fxa-content-server/server/lib/configuration.js
- packages/fxa-payments-server/server/config/index.js
Because:
- we want a feature flag to control the source of the product and plan
configurations, toggling between Stripe metadata (false) and
Firestore (true)
This commit:
- add a feature flag config to the auth, payments, and content servers
Closes: #10354
> feat(subscriptions): add feature flag for Firestore product configs

- packages/fxa-auth-server/lib/senders/emails/templates/postRemoveAccountRecovery/index.txt
- “This recovery key can no longer be used…“ should be displayed after the Manage account link.
- Fixes the plaintext version
Closes: #11770
New:
> fix(auth-server): different order of text in plaintext version of `postRemoveAccountRecovery`

- .github/workflows/upload-assets-to-cdn.yml
Because:
* the /other/ directory doesn't get uploaded for some reason
This commit:
* adds it to the upload script
Closes #4478
-------------------
Looking for a review from @dlactin or @jbuck .  I noticed the original script was specifically *excluding* the other directory, so, aside from a review for if this will work or not, I want to make sure this is what we want.  Lastly, I noticed it's supposed to be sending a notice to the slack channel, but I'm not sure I've ever seen that notice -- is that hooked up properly?
> chore(scripts): Add 'other' assets directory to upload script

- packages/fxa-content-server/app/scripts/models/auth_brokers/web.js
- packages/fxa-content-server/app/tests/spec/models/auth_brokers/web.js
Because:
* The green message displayed should be "Password reset successfully"
This commit:
* Revises success message of `afterResetPasswordConfirmationPoll`
Closes: #11740
> fix(settings): wrong green successful message is displayed when user resets password

- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.scss
- packages/fxa-auth-server/lib/senders/emails/partials/paymentProvider/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/paymentProvider/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionSubsequentInvoice/index.txt
- Payment method value is missing after label
- Moves "Payment method: " label within conditional (`fxa-auth-server/lib/senders/emails/partials/paymentProvider/index.mjml`)
- Refactors and cleans up spacing in plaintext to match HTML version
- `fxa-auth-server/lib/senders/emails/partials/paymentProvider/index.txt `
- `fxa-auth-server/lib/senders/emails/templates/subscriptionSubsequentInvoice/index.txt `
- Revises comment with more detail
- `fxa-auth-server/lib/senders/emails/layouts/subscription/index.scss`
Closes: #11786
Old - HTML
Old - plaintext
New - German
New - English
> fix(auth-server): Payment method not displayed for subscriptionSubsequentInvoice template

- packages/fxa-settings/src/components/ConnectedServices/index.test.tsx
- packages/fxa-settings/src/components/ConnectedServices/index.tsx
- packages/fxa-settings/src/lib/gql.ts
Because:
* Since we display only unique client/service names in the UI, users were having to click 'Sign out' multiple times before the session appeared to be cleared if they had multiple sessions of the same service name
This commit:
* Uses Promise.all to disconnect all clients associated with the selected client if multiple sessions exist
fixes #11559
fixes #11658
---
One way to reproduce this and the fix locally, assuming your Nightly version doesn't match FF:
1. On `main`, create/login to an account locally on Nightly
1. Open a private window in Nightly and login to that account - this creates two sessions under one name
1. Log in on FF (not Nightly). Click "sign out" for the Nightly session. Refresh the page, and see that the Nightly session is still present
To verify the fix:
* On …
> fix(settings): Disconnect all associated clients/sessions for given client name on sign out

- packages/123done/static/js/123done.js
- packages/fxa-content-server/app/scripts/models/reliers/relier.js
- packages/fxa-content-server/app/tests/spec/models/reliers/relier.js
- packages/fxa-content-server/server/config/local.json-dist
- The service value was not being sent to the auth server
- Populates the `service` param correctly so that it can be sent to the auth-server
Closes: https://github.com/mozilla/fxa/issues/10839
> fix(metrics): Populate relier `service` value if param exists

- packages/fxa-auth-server/lib/server.js
Because:
* Train 224 saw huge spikes in DB calls/oauth connections and we're attempting to see if this line is causing the performance problems
This commit:
* Disables setting the uid from oauth
---
Maybe probably hopefully this is it? Either way we'll need a follow up to re-enable this if there's no change or figure out how we can better cache this or hit this case.
I believe the downside to disabling this is that users with an oauth token will not have their metrics opt-out preference taken into account if they've opted out.
> fix(auth): Temporarily disable isMetricsEnabled db calls for oauth clients

- packages/fxa-auth-server/lib/payments/capability.ts
- packages/fxa-auth-server/lib/payments/google-play/subscriptions.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/capability.js
- packages/fxa-auth-server/test/local/payments/google-play/subscriptions.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/remote/subscription_tests.js
Because:
* Prior code grabbed capabilities from all the prices under a users
subscribed product, rather than just the capabilities for the
specific price the user subscribed to.
This commit:
* Revamps the capability service to use price id's and merge the
capabilities of the subscribed price with only its product when
determining a users capabilities.
Closes #11804
> feat(auth): use capabilities of subscribed price, not all prices

- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-auth-server/test/local/routes/validators.js
Because:
* We were throwing an error on the account reply for IAP
purchases.
This commit:
* Allows price_id in the response.
> fix(auth): allow price_id in response

- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.scss
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml
- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.scss
- packages/fxa-auth-server/lib/senders/emails/partials/appBadges/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/appBadges/index.scss
- packages/fxa-auth-server/lib/senders/emails/partials/icon/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/images.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/cadReminderFirst/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/postVerify/index.mjml
- per [MJML documentation](https://documentation.mjml.io/#mj-image), a `<mj-image>` tag displays a responsive center-aligned image in an email and, if no width is provided, the image will use the parent column width. When the `<mj-image>` tag is translated into HTML, the image is nested within a `<td>` tag, which utilizes the width attribute set in the `<mj-image>` tag. While the width of the image can be set in a `css-class`, it only sets the image width and not the width of the `<td>` it is nested in. Therefore, it is best practice to also include and set the width attribute when using a `<mj-image>` tag.
Note: The header image within the FxA email templates did not appear at 100% width in the Mail app, as it was written in HTML within a `<mj-raw>` tag and no `<mj-image>` tags were …
> fix(auth-server): subplat email images are at 100% width using the Mail app

- packages/fxa-auth-server/lib/senders/emails/partials/paymentProvider/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/paymentProvider/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/index.stories.ts
Because:
* cardType and lastFour are undefined when the user pays for the entire cost with a coupon
This commit:
* Checks for cardType and lastFour truthiness before displaying them
fixes #11861
> fix(emails): Add conditional around payment method

- packages/fxa-admin-panel/src/components/AccountSearch/Account/index.test.tsx
- packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
- Device row displays a blank value when a session belongs to a desktop device.
- Updates to display 'Desktop' when `uaDeviceType` is null
Closes: #11089
Before
After
> fix(admin-panel): FXA-4231 - missing Device type for desktop sessions

- packages/fxa-auth-server/lib/redis.js
-  The command `yarn workspace fxa-auth-server build` was failing
- Switching to require statements in redis.js file clears typescript error saying the 'default export was not defined'.
> fix(auth): Fixes build error in CI.

- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/lib/db/index.js
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/linked-accounts.ts
- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-auth-server/test/local/routes/linked-accounts.js
- packages/fxa-auth-server/test/mocks.js
- packages/fxa-graphql-api/src/gql/account.resolver.spec.ts
- packages/fxa-graphql-api/src/gql/account.resolver.ts
- packages/fxa-graphql-api/src/gql/model/account.ts
- packages/fxa-graphql-api/src/gql/model/linkedAccount.ts
- packages/fxa-shared/db/models/auth/account.ts
- packages/fxa-shared/db/models/auth/linked-account.ts
- packages/fxa-shared/test/db/models/auth/index.spec.ts
- This adds support to disconnect a linked Google account from an FxA account
- Creates a new endpoint `/linked_account/unlink` that removes association between Google and FxA accounts
- Updates graphql server to return linked accounts
- Does not revoke sessions created by a Google account, a user can manually revoke this session in the `Connected services` in section. Follow up issue https://github.com/mozilla/fxa/issues/11886
Closes: #11316
> feat(google): Add backend support to disconnect google linked account

- packages/fxa-settings/src/components/Profile/en-US.ftl
- packages/fxa-settings/src/components/Profile/index.tsx
- packages/fxa-settings/src/components/Security/en-US.ftl
- packages/fxa-settings/src/components/Security/index.test.tsx
- packages/fxa-settings/src/components/Security/index.tsx
- Move change password to under security section in settings
Closes: https://github.com/mozilla/fxa/issues/11888
> fix(settings): Move change password to under security section in settings

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/server.js
Because:
* We want these values to be configurable for easy changes on the ops side to investigate recent auth-server performance problems
* We temporarily disabled db calls for oauth clients to see if that was the problem, but it hasn't changed much
This commit:
* Creates SMTP_MAX_MESSAGES and SMTP_MAX_CONNECTIONS env vars with defaults to what we currently have
* Removes the previously commented out line temporarily disabling db calls for oauth clients
fixes #11799, or at least hopefully we can hand it off to ops to experiment with 🤞
> feat(mailer): Add maxConnection and maxMessages env vars, re-enable isMetricsEnabled oauth client db calls

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- it appears the email template on staging includes the variable name `{ $productPaymentCycleOld }`, when `productPaymentCycleOld` and `productPaymentCycleNew` are the same (e.g., the plan is upgraded from a monthly subscription to another monthly subscription). However, there is no issue when the two variables are different (e.g., the plan is upgraded from a monthly subscription to an annual subscription) - see screenshots below.
- sets `productPaymentCycleOld` to the current plan's interval value (`productPaymentCycleNew`), if there is no interval value from the plan's `previous_attribute` object.
Closes: #11848
Currently on staging - month to month upgrade:
Currently on staging - month to year upgrade:
> fix(auth-server): subscriptionUpgrade email includes variable when value is missing

- packages/fxa-auth-server/lib/senders/emails/partials/location/mocks.ts
- packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/passwordChangeRequired/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/postChangePrimary/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verify/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/verifySecondaryCode/index.stories.ts
- while the `location` mock included date, device, IP, location, time, the `location` partial also included `primaryEmail`. In addition, not all email templates include all of the information in the `location` partial.
- the description of a few templates included an update of its current state
- revises the `location` mock to include the three variations that are utilized among all email templates.
- `MOCK_LOCATION` (which was not revised) includes date, device, IP, location, and time
- All other email templates, with the exception of `verify` and `verifySecondaryCode` utilize this mock
- `MOCK_LOCATION_TRUNCATED` (which was added) includes information within `MOCK_LOCATION` with the exception of date and time
- The only email template that utilizes this mock is `verify`
- …
> fix(auth-server): revise email template stories in Storybook

- packages/fxa-auth-client/lib/client.ts
- packages/fxa-settings/src/components/App/en-US.ftl
- packages/fxa-settings/src/components/LinkedAccounts/LinkedAccount.tsx
- packages/fxa-settings/src/components/LinkedAccounts/en-US.ftl
- packages/fxa-settings/src/components/LinkedAccounts/google.svg
- packages/fxa-settings/src/components/LinkedAccounts/index.stories.tsx
- packages/fxa-settings/src/components/LinkedAccounts/index.test.tsx
- packages/fxa-settings/src/components/LinkedAccounts/index.tsx
- packages/fxa-settings/src/components/LinkedAccounts/mocks.ts
- packages/fxa-settings/src/components/Nav/index.test.tsx
- packages/fxa-settings/src/components/Nav/index.tsx
- packages/fxa-settings/src/components/PageSettings/index.tsx
- packages/fxa-settings/src/models/Account.ts
- packages/fxa-settings/src/models/mocks.tsx
- A user needs the ability to see what third party accounts are linked to their FxA account
- A user needs to be able to disconnect a linked account
- Adds a new settings section `Linked Accounts`
- Displays the provider logo and an option to unlink
- Some parts mention Google directly, I plan on updating when we add support for Apple
Closes: https://github.com/mozilla/fxa/issues/11317
> feat(google): Add settings section for linked accounts

- packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
Because:
- when a user encounters an error during their first subscription
attempt on the passwordless flow, they could end up getting the
account exists message and will be forced to "reset" (but actually
create) their FxA password and signin
This commit:
- memoize the existing account check result to prevent account exists
message on subscription retries
- this is a partial fix for retries after the user dismissed the
error message; it will not work if the user refreshes the checkout
page
Closes: #11197
> fix(subscriptions): memoize existing account check result

- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/test/local/senders/emails.ts
- `date` and `time` are properties that are not actually passed into the `message` object. They are created with `constructLocalTimeString` and passed into the email templates.
- Reverts parameters of `constructLocalTimeString` to its original parameters of `timeZone` and `acceptLanguage` ([see pull request](https://github.com/mozilla/fxa/pull/8114/files))
- Adds tests to check that the `constructLocalTimeString` function returns expected results
- Revises tests for emails to check that date and time are within email templates
- Note: The tests to check that a specific time is included in the email templates failed because the seconds did not match (e.g 8:02:11AM and 8:02:16AM). Therefore, the tests have been revised to check that the time merely exists in the email templates.
- Also …
> fix(auth-server): time is not expressed based on user's location in emails

- .github/workflows/upload-assets-to-cdn.yml
The upload action will fail trying to interact with GitHub's OIDC token endpoint
Adds the permissions required to query the endpoint and get AWS credentials to upload.
Failing GitHub action: https://github.com/mozilla/fxa/actions/runs/1853703627
> Added missing permissions needed to interact with GitHub's OIDC Token endpoint

- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountFinishSetup/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountFinishSetup/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountFinishSetup/index.txt
- packages/fxa-auth-server/test/local/senders/emails.ts
Because:
- Not all subscription products are "downloadable"
This commit:
- Update the content of the finish setup email to not mention
downloading
Closes: #11158
> chore(emails): update finish setup email with more generic language

- packages/fxa-auth-server/lib/routes/subscriptions/account.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/account.js
- packages/fxa-payments-server/src/routes/Checkout/index.test.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
- packages/fxa-payments-server/src/routes/Product/index.tsx
- yarn.lock
Because:
- customers who use credit cards that require the additional SCA step
won't receive the welcome/finish setup email (if they used the
passwordless flow), and they might encounter a front end error even
though their subscription was successful
This commit:
- send the finish setup email to new users with an 'incomplete'
subscription that has a payment intent that 'requires_action' (the
SCA approval)
- add a couple workarounds to reduce the probability of the customer
encountering a front end error despite a successful subscription
- context: on the front end, we fetch the customer's subscriptions on
a successful subscription creation response, however, over time,
due to Stripe rate limit mitigation, we stopped directly querying
the source of truth, Stripe, for the list of …
> fix(subscriptions): send email and reduce errors for SCA flow

- packages/fxa-payments-server/server/config/index.js
- packages/fxa-payments-server/server/lib/amplitude.js
Because:
- the "Amplitude" event transform function in the payments was not
initialized with an OAuth client ids to service names map, so
'service' in the metric event properties is always 'undefined_oauth'
This commit:
- add an OAuth client ids to names map and initialize the metrics
transform function with it
Closes: #11897
There is also a related PR to add the config for stage and prod at https://github.com/mozilla-services/cloudops-infra/pull/3830
> fix(metrics): add oauth client ids to names config

- packages/123done/static/index.html
- packages/123done/static/js/123done.js
- packages/fxa-auth-server/lib/routes/linked-accounts.ts
- packages/fxa-content-server/app/scripts/lib/fxa-client.js
- packages/fxa-content-server/app/scripts/models/account.js
- packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js
- packages/fxa-content-server/app/scripts/models/user.js
- packages/fxa-content-server/app/scripts/views/mixins/google-auth-mixin.js
- packages/fxa-content-server/app/tests/spec/models/auth_brokers/oauth-redirect.js
- packages/fxa-content-server/app/tests/spec/views/mixins/google-auth-mixin.js
- Pocket needs to know the associated google user to update their database
- Returns the google id when the user completes the oauth flow
Closes: https://github.com/mozilla/fxa/issues/11963
> feat(google): return provider user id to the oauth client

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/emails/partials/paymentProvider/index.mjml
- packages/fxa-auth-server/lib/senders/emails/partials/paymentProvider/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoice/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionSubsequentInvoice/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionSubsequentInvoiceDiscount/index.stories.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/senders/emails.ts
- When a discount is applied that results in a zero dollar invoice, do
not display the Payment Method in emails sent to the customer, since
no payment was processed.
- Hides the payment method from the relevant emails.
Closes: #11993
> fix(coupon): In email hide pay method on 0 invoice

- packages/fxa-content-server/app/scripts/lib/constants.js
- packages/fxa-content-server/app/scripts/templates/index.mustache
- packages/fxa-content-server/app/scripts/templates/partial/account-suggestion.mustache
- packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache
- packages/fxa-content-server/app/scripts/views/index.js
- packages/fxa-content-server/app/scripts/views/mixins/account-suggestion-mixin.js
- packages/fxa-content-server/app/scripts/views/mixins/pocket-migration-mixin.js
- packages/fxa-content-server/app/scripts/views/sign_in_password.js
- packages/fxa-content-server/app/styles/_state.scss
- packages/fxa-content-server/app/tests/spec/views/mixins/account-suggestion-mixin.js
- packages/fxa-content-server/app/tests/test_start.js
- yarn.lock
- We need to let Pocket users why they are migrating over to Firefox accounts
- Adds a FAQ tooltip to our signin and email first pages
Closes: https://github.com/mozilla/fxa/issues/11842
> feat(pocket): Add FAQ tool tip for pocket migration

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/senders/email.js
Because:
* We're getting 451 errors from SES saying there is too much time
between requests.  This is an attempt to fix that
This commit:
* Removes pooling so every email gets its own request.
Closes #11939
> fix(email): remove pooling to fix delivery failures

- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
- Cancelled subscriptions cause the subsequent invoice API to return a
500 status code.
- Does not attempt to retrieve a subsequent invoice for subscriptions
that have already been cancelled.
Closes: #12071
> fix(subscriptions): sub invoice api 500 on cancel

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
- yarn.lock
Because:
* We were using a sources retrieve for a card instead of the card
retrieve for card fetching in the stripe webhook.
This commit:
* Removes card as a source expansion resource and custom loads it
for the stripe webhook.
Closes #11872
> feat(auth): get cards with card API

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* Extra white space in the metadta values should be ignored.
This commit:
* Trims whitespace on metadata.
Closes #11932
> feat(auth): trim whitespace off metadata

- package.json
- packages/fxa-content-server/app/scripts/lib/router.js
- yarn.lock
- We were not emitting login events on mobile devices
- Through manual testing, adding a slight delay before navigating to next screen allows our metrics to be sent
- Without the delay iOS blocks these requests....for reasons? I'm guessing something privacy related since this issue just poped up
- This is a bit hard to test locally, so I got a screen grab of before and after
Closes: https://github.com/mozilla/fxa/issues/11917
Before:
After:
> fix(metrics): Attempt to fix login complete events for mobile

- packages/fxa-admin-server/src/database/database.service.ts
- packages/fxa-auth-server/lib/oauth/db/index.js
- packages/fxa-auth-server/lib/oauth/db/mysql/index.js
- packages/fxa-shared/connected-services/accessors.ts
- packages/fxa-shared/db/index.ts
- packages/fxa-shared/db/mysql.ts
- packages/fxa-shared/db/redis.ts
- packages/fxa-shared/test/db/mysql.ts
- We need more visibility into how Redis is starting up.
- Previous canary didn't go through cleanly due to bad log statement causing runtime error. 
- Add more logging around Redis during initialization.
- Removes random doubly awaited database calls.
- Doctored up some log messages to make them easier to query for.
- Fixes bad log statement in fxa-auth-server/lib/oauth/db/mysql/index.js
- Removes stray console.log statement in fxa-shared/test/db/mysql.ts
> task(auth,shared): Logging improvements after observing last canary

- packages/fxa-auth-server/lib/payments/configuration/plan.ts
- packages/fxa-auth-server/lib/payments/configuration/product.ts
Because:
* #12040 failed CI after being merged into main due to TS errors.
* I'm not sure why the TS errors surfaced here and not in #12005, as #12040
did not modify these classes that are causing errors (though it did modify
other parts of the files).
This commit:
* Fixes those TS errors.
Closes #No issue
FWIW we have a maintenance ticket, #11545 that I added to our [Train 230 maintenance sprint](https://mozilla-hub.atlassian.net/browse/FXA-4659) to ensure we find and fix TS errors in the PR before merging.
> fix(auth): address TS errors in ProductConfig and PlanConfig classes

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- yarn.lock
Because: 
* #10857 changed how we process recurring PayPal payments to use the paypal-processor rather than the invoice.finalized Stripe webhook.
* Our mozilla-subscriptions/customer/billing-and-subscriptions endpoint was wrongly returning a PayPal "funding_source" error to the front-end, because the 'getBillingDetailsAndSubscriptions' helper was only checking if an invoice was open -- not whether we've actually tried to pay it.
This commit:
* Checks the 'paymentAttempts' metadata on any open invoices for active subscriptions before returning a PayPal funding source error to the client.
Closes #11992
There's a second commit here related to a yarn.lock change that came up after I `yarn install`ed. Another miss with dependabot?
> fix(auth): check paymentAttempts before returning a funding source error

- packages/fxa-content-server/app/scripts/templates/index.mustache
- packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache
- packages/fxa-content-server/app/scripts/views/index.js
- packages/fxa-content-server/app/scripts/views/mixins/pocket-migration-mixin.js
- packages/fxa-content-server/app/scripts/views/sign_up_password.js
- yarn.lock
- We only need to show this for new accounts
- Removes the account suggestion for signin and puts it only in the signup view
Closes: https://github.com/mozilla/fxa/issues/12138
> fix(pocket): Only show pocket account suggestion when creating an account

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-payments-server/src/components/PayPalButton/index.tsx
- packages/fxa-payments-server/src/lib/customer.test.ts
- packages/fxa-payments-server/src/lib/customer.ts
- packages/fxa-payments-server/src/lib/mock-data.tsx
- packages/fxa-payments-server/src/lib/stripe.ts
- packages/fxa-payments-server/src/lib/test-utils.tsx
- packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.test.tsx
- packages/fxa-payments-server/src/store/types.tsx
- packages/fxa-shared/subscriptions/types.ts
- The web app does not create a Stripe customer when a customer with an
existing IAP subscription signs up via the Web Application.
- Improves the check if a Stripe customer exists, to support customers
with a existing IAP subscriptions.
Closes: #12003
> fix(subscriptions): create customer for iap sub

- packages/123done/static/index.html
- packages/123done/static/js/123done.js
- packages/fxa-content-server/app/scripts/lib/constants.js
- packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache
- packages/fxa-content-server/app/scripts/views/mixins/third-party-auth-mixin.js
- packages/fxa-content-server/app/scripts/views/sign_in_password.js
- packages/fxa-content-server/app/tests/spec/views/mixins/third-party-auth-mixin.js
- Pocket needs to be able to open the third party auth from their homepage
- Adds support to deeplink directly into an Apple or Google login flow
- Fix to use right FAQ for Pocket
Note that is will be targetted as a point release on train 228.
Closes: https://github.com/mozilla/fxa/issues/12176 https://github.com/mozilla/fxa/issues/12175
> fix(google): Pocket third party auth fixes, FAQ link fix

- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
- the front end does not need the promotion codes
This commit:
- remove the promotion codes from the plans
Closes: #12181
> fix(subscriptions): remove promo codes from plans

- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoice/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoice/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoice/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/index.txt
Because:
- some products do not require downloading software
This commit:
- remove mention of download instructions from first invoice emails
Closes: #12215
> fix(emails): remove more "download" language from emails

- packages/fxa-content-server/tests/server/validation.js
- The documentation URL for metrics for relying parties changed, causing
the content-server validation tests to fail
- Updates the URL in the test to the new URL.
> fix(content): fix validation tests

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/payments/fixtures/stripe/event_payment_method_updated.json
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* We want to properly reflect the VAT if the customer change countries
within a tax region.
This commit:
* Updates the subscription tax rates based on the payment method country
when a payment method update webhook event occurs.
Closes #11881
> feat(auth): update payment method tax rates on payment change

- packages/fxa-admin-server/src/graphql.ts
- A previous merge inadvertently reverted the generated code's formatting.
- Restores original formatting.
This is mostly annoyance. When the graphql api starts up, it will generate this file. Previously, prettier formatting was applied to this file which changed the white space and quote characters. As a result, every time the graphql api was run locally, this file would end up showing changes in git. This fix undoes the prettier formatting and goes with the default code gen formatting, which fixes the issue. The file was prettier ignored in a previous PR, so this has already been taken care.
> fix(graphql): Fixes formatting on codegen file.

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/CouponForm/index.stories.tsx
- packages/fxa-payments-server/src/components/CouponForm/index.tsx
- packages/fxa-payments-server/src/components/PaymentConfirmation/index.stories.tsx
- packages/fxa-payments-server/src/components/PlanDetails/index.stories.tsx
- packages/fxa-payments-server/src/components/PlanDetails/index.test.tsx
- packages/fxa-payments-server/src/components/PlanDetails/index.tsx
- packages/fxa-payments-server/src/lib/coupon.test.ts
- packages/fxa-payments-server/src/lib/coupon.ts
- packages/fxa-payments-server/src/lib/hooks.test.tsx
- packages/fxa-payments-server/src/lib/hooks.tsx
- packages/fxa-payments-server/src/lib/mock-data.tsx
- packages/fxa-shared/dto/auth/payments/coupon.ts
- Once a coupon is successfully applied, we need to show an appropriate
message depending on coupon type.
- Adds a new hook to determine if a message should be shown and what the
message should be.
Closes: #11439
> feat(coupon): update info box for coupon type

- packages/fxa-auth-server/package.json
- packages/fxa-auth-server/scripts/populate-firestore-customers.ts
- packages/fxa-auth-server/scripts/populate-firestore-customers/firestore-populator.ts
- packages/fxa-auth-server/scripts/populate-firestore-customers/rate-limit-observer.ts
Because:
* We want to backfill all stripe customers that have had a subscription
into Firestore.
This commit:
* Iterates through all stripe customers as fast as possible that have
valid firefox accounts to load them into firestore.
Closes #12070
> feat(auth): add firestore stripe populator

- packages/123done/static/js/123done.js
- packages/fxa-auth-client/lib/client.ts
- packages/fxa-auth-server/lib/routes/linked-accounts.ts
- packages/fxa-content-server/app/scripts/lib/fxa-client.js
- packages/fxa-content-server/app/scripts/models/account.js
- packages/fxa-content-server/app/scripts/views/mixins/third-party-auth-mixin.js
- packages/fxa-content-server/app/scripts/views/sign_in_password.js
- packages/fxa-content-server/app/tests/spec/views/mixins/third-party-auth-mixin.js
- packages/fxa-content-server/server/lib/amplitude.js
- packages/fxa-shared/metrics/amplitude.js
- We need to define these metrics and call out any issues
-  The events that are emitted are defined in https://docs.google.com/document/d/1fTEduCVtuPXorsi9AIc9_GL-bYTN67UepJhku2eahHI/edit# along with the corresponding screens
- Adds basic amount of metrics for the third party auth login flow
Closes: https://github.com/mozilla/fxa/issues/12223
> feat(auth): Add third party auth metrics

- packages/fxa-auth-server/tsconfig.json
Because:
* We dynamically import an includes.ts file if the template needs logic based on a template value to determine 'subject' or 'action' and TS was not transpiling this file
This commit:
* Adds the path to tsconfig.json
fixes #12228
---
I double checked this worked as expected by running `yarn build` before and after the change.
An alternative approach instead of this is to just [import the file](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/senders/renderer/index.ts#L128) at the top instead of course, but meh we'd be unnecessarily importing it most of the time since the `lowRecoveryCodes` email doesn't get sent much.
> fix(tsconfig): Transpile email templates includes.ts files

- packages/fxa-admin-panel/constants/index.ts
- packages/fxa-admin-panel/interfaces/index.ts
- packages/fxa-admin-panel/pm2.config.js
- packages/fxa-admin-panel/server/config/index.ts
- packages/fxa-admin-panel/server/lib/client-config/index.test.ts
- packages/fxa-admin-panel/server/lib/client-config/index.ts
- packages/fxa-admin-panel/server/lib/server.ts
- packages/fxa-admin-panel/src/App.test.tsx
- packages/fxa-admin-panel/src/App.tsx
- packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
- packages/fxa-admin-panel/src/components/AccountSearch/index.tsx
- packages/fxa-admin-panel/src/components/Nav/index.tsx
- packages/fxa-admin-panel/src/components/Permissions/index.test.tsx
- packages/fxa-admin-panel/src/components/Permissions/index.tsx
- packages/fxa-admin-panel/src/index.tsx
- packages/fxa-admin-panel/src/lib/config.spec.ts
- packages/fxa-admin-panel/src/lib/config.ts
- packages/fxa-admin-server/README.md
- We need a way to see / test how the admin panel will behave with different user groups.
- Adds support to the config for setting the default user group via an environment variable. These config settings are only used for development. Once deployed these values will come from our headers.
- Creates a type for UserInfo that holds the current user's email and group. This info will be set from the current request headers, or fall back to values held in the application config.
- Sends this info down to client via a meta field in the header.
- Adds a UI widget to give visibility into the user who is currently signed in and their user group.
Closes: #11102
> feature(admin-panel): Add support for user group spoofing

- packages/fxa-auth-server/lib/routes/linked-accounts.ts
- packages/fxa-shared/db/models/auth/linked-account.ts
- Provider name in email needs to have the right case
- Adds map to provider names
Closes: https://github.com/mozilla/fxa/issues/12214
> fix(email): Use uppercase provider name in email

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionFirstInvoiceDiscount/index.txt
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionSubsequentInvoiceDiscount/en.ftl
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionSubsequentInvoiceDiscount/index.mjml
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionSubsequentInvoiceDiscount/index.stories.ts
- packages/fxa-auth-server/lib/senders/emails/templates/subscriptionSubsequentInvoiceDiscount/index.txt
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
- packages/fxa-auth-server/test/local/senders/emails.ts
Because:
* We want the invoice emails to indicate the duration of the applied subscription discount
This commit:
* Extracts necessary info from the invoice and retreives it if necessary, and passes it to the email templates
Closes #12030 
> feat(auth): add Coupon Duration Info to Invoice Emails

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* Stripe fails to send customer.updated webhooks when it updates customer.currency for PayPal users.
* This causes our cached customer in Firestore to be stale, with PayPal customers potentially having a customer.currency of null.
This commit:
* Updates the customer in Firestore on customer.subscription.created events, since that's when Stripe updates customer.currency.
Closes #12289
> fix(auth): update cached customer on customer.subscription.created

- .circleci/config.yml
- packages/fxa-auth-server/lib/payments/configuration/manager.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/lib/routes/validators.js
- packages/fxa-auth-server/scripts/stripe-products-and-plans-to-firestore-documents.ts
- packages/fxa-auth-server/scripts/stripe-products-and-plans-to-firestore-documents/stripe-products-and-plans-converter.ts
- packages/fxa-auth-server/scripts/test-ci.sh
- packages/fxa-auth-server/test/local/payments/configuration/manager.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/scripts/stripe-products-and-plans-converter.js
- packages/fxa-auth-server/test/test_server.js
- packages/fxa-shared/dto/auth/payments/plan-configuration.ts
- packages/fxa-shared/subscriptions/configuration/base.ts
- packages/fxa-shared/subscriptions/configuration/plan.ts
- packages/fxa-shared/subscriptions/configuration/product.ts
- packages/fxa-shared/subscriptions/configuration/utils.ts
- packages/fxa-shared/subscriptions/types.ts
- packages/fxa-shared/test/subscriptions/configuration/plan.ts
- packages/fxa-shared/test/subscriptions/configuration/product.ts
- packages/fxa-shared/test/subscriptions/configuration/utils.ts
- packages/fxa-shared/test/subscriptions/metadata.ts
Because:
- we want the front end to be able to use the Firestore document based
configurations
This commit:
- add the 'configuration' property to the plans returned from the all
plans endpoint
- move some models into fxa-shared
- refactor the configuration manager so that its users do not need to
manually initialize the product and plan config lists prior to
accessing them
closes #10239
> feat(subscriptions): add Firestore based config to plans

- packages/fxa-auth-server/lib/senders/renderer/index.ts
Because:
* This check should have been '!== undefined' instead of checking for truthiness so when a user attempted to use their last remaining recovery code, numberRemaining was 0 and it caused the fallback to happen, requiring includes.json, which doesn't exist for lowRecoveryCodes template. We don't need this check at all because numberRemaining should never be undefined if the email template is lowRecoveryCodes
This commit:
* Removes checking for numberRemaining truthiness before returning includes.ts
> fix(recovery-codes): Remove context.numberRemaining check in getGlobalTemplateValues

- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
- When a Stripe customers legacy card source is deleted, Stripe sends a
payment_method.detached webhook with the card id. This causes the
expand resource stripe helper method to fail, since it expects a
payment method ID for event object payment_method, not a card id.
- Since we currently don't handle payment_method.detached events, except
in the firestore handler, we can skip the expand resource for this
event type.
> fix(subscriptions): no expand on payment detach

- packages/fxa-content-server/app/scripts/lib/channels/web.js
- packages/fxa-content-server/app/scripts/models/auth_brokers/fx-sync-web-channel.js
- packages/fxa-content-server/app/tests/spec/lib/channels/web.js
- fxaccounts:verified  is no longer a message sent by the FF.
- Removes  support for the fxaccounts:verified command
Closes: #9389
> maintenance(content): Remove fxaccounts:verified webchannel msg

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-payments-server/src/components/CouponForm/index.stories.tsx
- packages/fxa-payments-server/src/components/CouponForm/index.test.tsx
- packages/fxa-payments-server/src/components/PaymentConfirmation/index.stories.tsx
- packages/fxa-payments-server/src/components/PaymentConfirmation/index.test.tsx
- packages/fxa-payments-server/src/components/PlanDetails/index.test.tsx
- packages/fxa-payments-server/src/lib/apiClient.test.ts
- packages/fxa-payments-server/src/lib/mock-data.tsx
- packages/fxa-shared/dto/auth/payments/coupon.ts
- The coupon details api endpoint was only checking if a coupon is valid
and was not also checking the promotion code.
- Verify's that the coupon and promotion code are valid. If either is
invalid, return the appropriate information so that the UI can display
the correct error message.
Closes: #11524
> feat(coupons): coupon detail api check valid promo

- packages/fxa-auth-server/package.json
- packages/fxa-shared/package.json
- yarn.lock
Because:
* We want to use the latest types for Stripe.
This commit:
* Updates stripe to the 8.215.0.
Closes #12265
> feat(auth): upgrade stripe dependency

- packages/fxa-payments-server/.vscode/launch.json
- packages/fxa-payments-server/README.md
Because:
* We want to be able to debug payments tests from vs code
This commit:
* Add a launch.json and updates the documentaion
Closes #12284
> feat(payments): add Launch Config for Debugging Payments Tests

- packages/fxa-payments-server/package.json
- packages/fxa-settings/package.json
- yarn.lock
Reverts mozilla/fxa#12395
This update does not appear to work and will need manual updating.
> Revert "chore(deps): bump postcss-import from 12.0.1 to 14.1.0"

- package.json
- packages/fxa-auth-server/lib/payments/paypal/processor.ts
- packages/fxa-auth-server/scripts/paypal-processor.ts
- packages/fxa-auth-server/test/local/payments/paypal-processor.js
- yarn.lock
Because:
- we could easily end up running two instances of the paypal-processor
during a deploy
This commit:
- use a redis based distributed lock to ensure only one
paypal-processor can run per env
- add script options to control the lock name and duration, as well as
completely bypassing the lock
Closes: #12126
> feat(scripts): use redlock to prevent >1 instance of paypal-processor

- docs/adr/0030-disable-squash-and-merge.md
Because:
* Squash and merge introduced a few problems and the team prefers to disable the option for now. We can revisit the topic as our processes are improved and the problems laid out can be alleviated through other means.
This commit:
* Adds a new ADR to capture a summary of why squash and merge causes problems for us and why we want to disable it
fixes #11721 
---
I tried to keep this short and sweet while covering all of the major points. If I've missed anything or if you think I can expound on anything further please feel free to comment about it.
We have a [separate ticket](https://github.com/mozilla/fxa/issues/12166) to update our development process docs, where we can better spell out git workflow recommendations, that were also discussed in In Ivo's [A Tale of Two …
> chore(docs): ADR for disabling squash and merge

- packages/fxa-payments-server/src/lib/hooks.test.tsx
- Expected and actual values could be off by a few milliseconds causing
the test to fail
- Reduce the granularity of the date check.
> fix(payments): fix flaky test with different dates

- packages/fxa-payments-server/src/lib/test-utils.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionItem.tsx
- The subsequent invoice not found message is shown when a subscription
has a 0 total amount. This can happen when a subscription has a 100
percent disount applied.
- Allow 0 values for total amount.
Closes: #12308
> fix(Subscriptions): Sub manage zero sub amount

- packages/fxa-auth-server/lib/payments/paypal/error.ts
- packages/fxa-auth-server/lib/payments/paypal/helper.ts
- packages/fxa-auth-server/lib/payments/paypal/index.ts
- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/payments/paypal.js
- packages/fxa-auth-server/test/local/payments/stripe.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* We want to update the invoice for support if the paypal refund
is refused.
This commit:
* Updates the credit note webhook handler so that if the paypal refund
is refused, the invoice metadata will be updated to reflect why.
Closes #11592
> fix(auth): handle paypal refused errors

- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* We want to notify a user that their subscriptions have been deleted when they delete their fx account
This commit:
* Updates the stripe event handler to send emails to accounts that have been deleted
Closes #12262
> fix(auth): send Subscription Delete Email When User Deletes Fx Account

- packages/fxa-content-server/app/scripts/lib/fxa-client.js
- packages/fxa-content-server/app/scripts/models/account.js
- packages/fxa-content-server/app/tests/spec/models/account.js
- We needed to unset the `originalLoginEmail` param after successfully logging in otw the user would be shown the old primary email
- unsets `originalLoginEmail` after login and sets the `email` to the actualy primary email
Closes: https://github.com/mozilla/fxa/issues/12109
> fix(email): Fixes issue where the user could not login when switching primary email

- packages/fxa-content-server/app/scripts/lib/router.js
- packages/fxa-content-server/tests/functional/settings/delete_account.js
- We never honored the `redirect_to` param that was set from the GQL server
- Updates our settings redirect to allow going to a specific section in settings
Closes: https://github.com/mozilla/fxa/issues/12392
> fix(redirect): Fix issue where users could not redirect to a specific settings section

- packages/fxa-admin-panel/server/lib/csp/blocking.ts
- A csp warning was showing up.
- Fixes a typo in the csp config
> fix(admin-panel): Fix sentry csp warning

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
Because:
* Duplicate processor runs or close payment conditions can trigger
invoice processing to occur in duplicate such that an invoice is
marked as paid twice, throwing an error.
This commit:
* Ignores already paid errors.
Closes #11409
> fix(auth): ignore already paid invoice errors

- packages/fxa-auth-server/README.md
Because:
* Our auth-server documentation on emails was out of date. Updated docs were written and moved into ecosystem-platform instead
This commit:
* Updates fxa-auth-server README
closes #10617
---
The PR containing the actual updates can be [found here](https://github.com/mozilla/ecosystem-platform/pull/197).
I originally wrote the L10n section here for the auth-server README, but also pulled it into the emails page in that PR. I might end up moving it into the Localization page instead later.
> chore(docs): Update auth-server README around emails

- packages/fxa-event-broker/scripts/test-ci.sh
- packages/fxa-event-broker/src/firestore/firestore.service.spec.ts
Because:
* Firestore tests run slow in the CI environment.
This commit:
* Updates the test timetouts for 30s on firestire tests.
Closes #9236
> fix(broker): update test timeouts

- packages/fxa-event-broker/scripts/test-ci.sh
Because:
* Workspace focus commands needs to be run to use appropriate CLI
programs.
This commit:
* Adds the workspaces focus to the test-ci script for event-broker.
> fix(broker): use workspace focus first

- packages/fxa-admin-server/scripts/email-bounce.ts
- A command like `email-bounce --email test@example.com --count 3` would fail to connect to the db.
- Fixes the connection string. It should have referenced config.database.fxa, which appears to be collateral damage from a previous refactor.
Closes: #12507
> fix(admin-sever): fix broken connection in email-bounce script

- packages/fxa-react/configs/tailwind.js
- packages/fxa-settings/src/components/Security/index.tsx
- packages/fxa-settings/src/components/UnitRow/index.tsx
Because:
* Since all other UnitRow components in the Security section have
refresh buttons, the Password row CTA button seems out of alignment.
This commit:
* Adds a descriptive prop so that the user can align the CTA within a
UnitRow with buttons that have a refresh button.
Closes #11972
Before:
After: 
RTL (before changes):
Styles deliberately do not have the `rtl` prefix, as the position of the buttons does not change when the text direction of the page changes, as shown in the above screenshot. Has been tested in Arabic and Hebrew.
> fix(fxa-settings): align password CTA

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- Currently monthly repeating coupons can be used even though they could
be applied to only part of the plan interval. (eg. Coupon duration of
3 months, applied to a 6 month plan.) This leads to possible confusion
for the customer, and should not be allowed.
- Checks if the coupon duration will apply to the entire interval for
a given plan
- If the coupon duration does not apply to the entire interval, report an
error to Sentry.
Closes: #12015 
> feat(coupons): check coupons apply entire plan interval

- package.json
Because:
- `yarn ports` was not working
This commit:
- get `yarn ports` working
> chore(yarn): fix yarn ports

- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* Deleting a customer causes events that trigger a sentry report
even though things are operating properly.
This commit:
* Ignores update events if the customer was deleted.
Closes #12627
> fix(auth): dont report error on deleted customers

- packages/fxa-auth-server/lib/routes/oauth/authorization.js
Because:
* If the devices or notify fails, the authorizationHandler promise
will become unhandled, which is the most likely cause of the
sentry bug as there's no other caller of this code in the code-base
which could lose the stack.
This commit:
* awaits the authorization handler to avoid an unhandled exception.
Closes #12625
> fix(auth): wait for auth to avoid unhandled exc

- packages/fxa-admin-server/nest-cli.json
- packages/fxa-admin-server/src/app.module.ts
- The schema.gql file wasn't updating properly.
- Updates the nestjs config so as to ensure the schema.gql file is copied to dist
- Updates the nestjs config so as to ensure the schema.gql is auto updated after changes to models.
Closes: #12642
> fix(admin-server): Fix watch on schema.gql

- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/lib/routes/utils/account.ts
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-auth-server/test/local/routes/subscriptions/paypal.js
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe.js
Because:
* We want to remove the stub account on the passwordless flow when the subscription fails so that it does not present the user with an error that the
account already exists
This commit:
* Catches any error from the function for creating the subscription, deletes the account if it is unverified and has no active subscriptions, then throws
the error to resume normal flow
Closes #11936
> fix(auth): delete Stub Account When Subscription Fails

- packages/fxa-content-server/app/scripts/models/account.js
- packages/fxa-content-server/app/tests/spec/models/user.js
- There was a regression in the last maintenance sprint when removing the ecosystemAnonId.
- Adds a collection of ​​DEPRECATED_KEYS that represent keys which may exist on legacy account data and need to be gracefully removed.
- Adds a test to make sure that a known deprecated field is handled and does not result in an error state.
- Adds a test to make sure that errors are still thrown for invalid keys.
Closes: #12630
> fix(content-server): Fix issue on login with legacy accounts

- packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
```
#10 242.8 ➤ YN0000: [fxa-admin-panel]: Process started
#10 251.8 ➤ YN0000: [fxa-admin-panel]: src/components/AccountSearch/Account/index.tsx(554,24): error TS2304: Cannot find name 'styleClasses'.
#10 251.8 ➤ YN0000: [fxa-admin-panel]: src/components/AccountSearch/Account/index.tsx(556,28): error TS2304: Cannot find name 'styleClasses'.
#10 251.9 ➤ YN0000: [fxa-admin-panel]: ERROR: "build:client" exited with 1.
#10 251.9 ➤ YN0000: [fxa-admin-panel]: Process exited (exit code 1), completed in 9s 156ms
```
- fixes the style from the recent push/merge - https://github.com/mozilla/fxa/pull/12637 - where:
-  `styleClasses.li` becomes `account.li`
- `styleClasses.result` is no longer utilized.
> fix(admin-panel): revise style

- packages/fxa-admin-panel/constants/index.ts
- packages/fxa-admin-panel/server/lib/client-config/index.test.ts
- packages/fxa-admin-panel/src/App.test.tsx
- packages/fxa-admin-panel/src/components/AccountSearch/Account/index.test.tsx
- packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
- packages/fxa-admin-panel/src/components/Guard/index.test.tsx
- packages/fxa-admin-panel/src/components/Permissions/index.test.tsx
- packages/fxa-admin-panel/src/lib/config.ts
- packages/fxa-admin-server/README.md
- packages/fxa-admin-server/package.json
- packages/fxa-admin-server/src/app.module.ts
- packages/fxa-admin-server/src/auth/user-group-header.decorator.ts
- packages/fxa-admin-server/src/auth/user-group-header.guard.spec.ts
- packages/fxa-admin-server/src/auth/user-group-header.guard.ts
- packages/fxa-admin-server/src/config.ts
- packages/fxa-admin-server/src/gql/account/account.resolver.ts
- packages/fxa-admin-server/src/gql/email-bounce/email-bounce.resolver.ts
- packages/fxa-shared/guards/AdminPanelGuard.ts
- packages/fxa-shared/guards/Guard.ts
- packages/fxa-shared/test/guard/AdminPanelGuard.ts
- packages/fxa-shared/test/guard/Guard.ts
- packages/fxa-shared/test/l10n/determineLocale.ts
- yarn.lock
- We want to restrict access to certain data.
- Introduces nest js gaurd based on remote-group header
- Fixes issue where the remote-group header wasn't relayed properly in development mode.
- Cleans up readme file. REMOTE-GROUPS header name changed to REMOTE-GROUP
- Added a couple more AdminPanelFeature: UnLinkAccount, LinkedAccounts, AccountHistory
- Renames AdminPanelFeature.UnVerifyAccounts to This pull AdminPanelFeature.UnVerifyEmail
- Moves constants for USER_GROUP_HEADER and USER_EMAIL_HEADER to AdminPanelGaurds.ts
Closes: #11104,  Closes: #11105 
> feature(admin-panel): Add guard to serverside

- packages/fxa-auth-server/lib/devices.js
- packages/fxa-auth-server/lib/routes/attached-clients.js
- packages/fxa-auth-server/lib/routes/devices-and-sessions.js
- packages/fxa-auth-server/lib/routes/emails.js
- packages/fxa-auth-server/lib/routes/idp.js
- packages/fxa-auth-server/lib/routes/newsletters.js
- packages/fxa-auth-server/lib/routes/oauth/authorization.js
- packages/fxa-auth-server/lib/routes/oauth/authorized-clients/destroy.js
- packages/fxa-auth-server/lib/routes/oauth/authorized-clients/list.js
- packages/fxa-auth-server/lib/routes/oauth/client/get.js
- packages/fxa-auth-server/lib/routes/oauth/destroy.js
- packages/fxa-auth-server/lib/routes/oauth/id_token_verify.js
- packages/fxa-auth-server/lib/routes/oauth/introspect.js
- packages/fxa-auth-server/lib/routes/oauth/jwks.js
- packages/fxa-auth-server/lib/routes/oauth/key_data.js
- packages/fxa-auth-server/lib/routes/oauth/token.js
- packages/fxa-auth-server/lib/routes/oauth/verify.js
- packages/fxa-auth-server/lib/routes/password.js
- packages/fxa-auth-server/lib/routes/recovery-codes.js
- packages/fxa-auth-server/lib/routes/recovery-key.js
- packages/fxa-auth-server/lib/routes/security-events.js
- packages/fxa-auth-server/lib/routes/session.js
- packages/fxa-auth-server/lib/routes/sign.js
- packages/fxa-auth-server/lib/routes/totp.js
- packages/fxa-auth-server/lib/routes/unblock-codes.js
- packages/fxa-auth-server/lib/routes/util.js
```
/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/devices.js:7
import DESCRIPTION from '../docs/swagger/shared/descriptions';
^^^^^^
SyntaxError: Cannot use import statement outside a module
at compileFunction (<anonymous>)
at Object.compileFunction (node:vm:352:18)
at wrapSafe (node:internal/modules/cjs/loader:1032:15)
at Module._compile (node:internal/modules/cjs/loader:1067:27)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at module.exports (/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/routes/index.js:27 …
```
> fix(swagger): SyntaxError: Cannot use import statement outside a module

- .dockerignore
- We can't deploy Train 231 to stage
- Fixes the Docker image build to include the Swagger API descriptions
> fix(swagger): Copy .ts files into Docker image

- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/linked-accounts.ts
- packages/fxa-auth-server/lib/routes/subscriptions/google.ts
- packages/fxa-auth-server/lib/routes/subscriptions/mozilla.ts
- packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts
- packages/fxa-auth-server/lib/routes/subscriptions/play-pubsub.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts
- packages/fxa-auth-server/lib/routes/support-panel.ts
> fix(swagger): import for .ts files, require for .js files

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/payments/configuration/manager.ts
- packages/fxa-auth-server/test/local/payments/configuration/manager.js
- packages/fxa-auth-server/test/scripts/stripe-products-and-plans-converter.js
- packages/fxa-shared/subscriptions/configuration/base.ts
- packages/fxa-shared/subscriptions/configuration/plan.ts
- packages/fxa-shared/subscriptions/configuration/product.ts
- packages/fxa-shared/test/subscriptions/configuration/plan.ts
- packages/fxa-shared/test/subscriptions/configuration/product.ts
- We need to validate that webIcon, termsOfServiceDownload and
privacyNoticeDownload URLs start with a specific value, set in config.
- Add a value to the auth-sever configuration to set valid URL.
- Update productConfig classes to include valid URL regex from config.
Closes: #12063
> feat(auth): stripe metadata expansion validate url

- packages/fxa-auth-server/lib/payments/iap/iap-config.ts
Because:
* A refactor accidentally changed the collection name.
This commit:
* Restores the collection name without the duplicate prefix.
Closes #12727
> fix(auth): fix collection prefix for iap

- packages/fxa-settings/src/components/LinkedAccounts/LinkedAccount.tsx
- In Account Settings, in the "Linked Accounts" section, if the logged-in account has a linked account (either Apple or Google) then the label for that account ("Google", for example) will not line up with the icon for that linked account in mobile. Please see attached screenshots.
- We add the class `justify-center` onto one of the divs wrapping the label. This causes no changes in desktop, and centers the label appropriately in mobile.
Closes: #12009
Before (desktop):
Before (mobile):
After (desktop):
After (mobile):
**If you have third-party auth set up in your local**, you can view the original state by starting on the `main` branch, and logging into a user account with a linked account and visiting `localhost:3030/settings`. If you scroll down to …
> fix(fxa-settings) fix label vertical centering in mobile

- packages/fxa-auth-server/lib/senders/renderer/bindings-node.ts
- Auth-server output gets noisey with mjml warnings
- Updates the render to specify options for mjml
Closes: https://github.com/mozilla/fxa/issues/12737
@xlisachan @LZoog You mind taking a look at this when you get a moment? I believe these are the right configs for mjml render but I am not super familiar with it.
> fix(mjml): Use `minifyOptions` instead of `minify` for mjml templates

- packages/fxa-settings/src/components/UnitRow/index.tsx
- The changes in this former PR addressed aligning a button on `fxa-settings`. The margin change should have been limited to sizes larger than mobile portrait (mobile landscape and up.) This limits the margin change accordingly.
- Adds `mobileLandscape:` before the classname that adds the margin.
Closes: # 12704
Before (desktop):
Before (mobile landscape):
Before (mobile portrait) (regression from last PR):
After (desktop):
After (mobile landscape):
After (mobile portrait) (regression repaired):
- To test this PR, run `fxa-settings` locally. 
- Create and sign into a user account. 
- Scroll down through settings until you see the Password section. 
- In desktop, the `Change` button should be slightly spaced out from the right border, keeping it even …
> fix(fxa-settings): limit button margin adjustment to mobile portrait

- packages/fxa-admin-panel/server/lib/client-config/index.ts
- packages/fxa-admin-server/src/auth/user-group-header.guard.spec.ts
- packages/fxa-admin-server/src/auth/user-group-header.guard.ts
- We're trying to get more insight into errors related to the headers coming into the admin panel in stage.
- Adds logging for the headers and then adds mock logger to tests so that they will still pass.
Closes: # n/a
> fix(fxa-admin-panel) temporarily add logging to debug on staging

- packages/fxa-auth-server/lib/payments/stripe.ts
- packages/fxa-auth-server/test/local/payments/stripe.js
- The incorrect next invoice date is shown in the subsequent invoice
email
- For a subscription upgrade, the Stripe invoice can have a line item
for the previous and current subscription. The existing logic assumes
there is only one invoice line item.
- Use the invoice line item with type "subscription" to determine the
correct next invoice date.
Closes: #12690
> fix(subscriptions): on upgrade use correct invoice line

- packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/stripe-webhooks.js
Because:
* We want to ensure upgrades and other subscription updates result in
events sent to relying parties if changes are needed.
This commit:
* Always calls the stripe capability service to communicate subscription
changes.
Closes #12705
> fix(auth): always broadcast stripe sub changes

- packages/fxa-content-server/app/styles/modules/_custom-rows.scss
* Github issue #12281 asks for "at least 4 pixels" more spacing between
third party auth buttons
* Raises the "margin-bottom" style on ".third-party-auth .login-button"
from 5px to 10px
Closes # 11281
Before (desktop):
Before (mobile):
After (desktop):
After (mobile):
> fix(fxa-content-server): add spacing bn 3rd party auth buttons

- packages/fxa-admin-panel/src/components/AccountSearch/index.tsx
Because:
* When copying and pasting values into the search bar, it's easy to accidentally include whitespace either before or after the copied value. Currently, this will result in the search not returning a result (as it will search for the entire input, including whitespace.)
This pull request:
* Trims the search input value before we submit it to the search (in the `handleSubmit` action, in the input length check that determines whether or not to show suggestions, and also in the search that returns suggested matching emails.) There is a slightly simpler way to this -- we could just trim
"event.target.value" before it's set into state using `setSearchInput`, but this could result in the user trying to type
in the input (with spaces, for example) and thinking they couldn't interact with …
> fix(admin-panel): trim whitespace from admin panel search bar

- packages/fxa-auth-server/lib/l10n/auth.ftl
- packages/fxa-auth-server/lib/senders/emails/layouts/fxa/en.ftl
- packages/fxa-payments-server/public/locales/en-US/main.ftl
Not exactly sure if this is enough, hopefully tests are not looking for specific text.
CC @clouserw 
I tried running a linter on source files, and a few issues:
* Group comment should have a space before and after, and be followed by at least a string. I move the one about "email content" in the following file to avoid that problem.
* Strings should use `’` and not `'`.
> Fix group comments and apostrophes

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/PaymentLegalBlurb/index.tsx
- packages/fxa-payments-server/src/components/TermsAndPrivacy/index.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/index.tsx
- We want to use LinkExternal in payments for all external links
- Replaces a tags with rel="noopener noreferrer” with LinkExternal component
Closes: #12468
N/A
N/A
> feat(payments): replace <a> external link to <LinkExternal> component

- packages/fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx
- We want to maintain consistent design and UX throughout the site
- Removes tailwind class adding extra white-space
Closes: #10585
N/A
N/A
> style(settings): remove extra white-space before and after "Resend verification code" text

- packages/fxa-settings/src/components/App/index.test.tsx
- packages/fxa-settings/src/components/App/index.tsx
- packages/fxa-settings/src/components/UnitRow/index.tsx
- packages/fxa-settings/src/components/UnitRowRecoveryKey/index.test.tsx
- packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx
- packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.test.tsx
- packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
- packages/fxa-settings/src/models/Account.ts
- packages/fxa-settings/src/models/mocks.tsx
- With third party oauth, we might enter into a state where the user has authenticated, but has not supplied a password yet. In this case, setting up recovery codes or 2FA isn’t applicable.
- Introduces hasPassword flag on account model
- Guards routes associated to 2FA and recovery codes in the event the account does not have a password
- Disables 2FA and recovery code action buttons in the event a user’s account has no password set.
- Provides a tooltip hint on the disabled action button that a password must be set in order to use certain features or sync.
Closes: #12774
To test this state, login with a third party oauth account (apple or google) for the first time. This will result in a state where you have been authenticated, but haven't set a …
> task(settings): Disable 2FA and Recovery Code actions when account has no password

- packages/fxa-settings/src/components/PageDeleteAccount/en-US.ftl
- packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
Reverts mozilla/fxa#12790. Copy changes are being delayed while we wait for other work to be completed. This PR is being reverted because mozilla/fxa#12731 is being reverted for the above reason.
> Revert "fix(fxa-settings): update string id on updated string"

- packages/fxa-settings/src/components/PageDeleteAccount/en-US.ftl
- packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
- packages/fxa-settings/src/constants/index.tsx
Reverts mozilla/fxa#12731. Copy changes are being delayed while we wait for other work to be completed.
> Revert "fix(fxa-settings) remove static list of feature from account deletion…"

- packages/fxa-auth-server/lib/payments/capability.ts
- packages/fxa-auth-server/test/local/payments/capability.js
Because:
* We want to include capabilities for a user defined in firestore
with the payment config manager or on Stripe during our transition.
This commit:
* Updates the capability service to load capabilities from the payment
config manager if its configured.
Closes #10358
> feat(auth): load capabilities from the payment config manager

- packages/fxa-graphql-api/README.md
- packages/fxa-graphql-api/src/gql/gql.module.ts
- packages/fxa-graphql-api/src/main.ts
- Graphql playground broke
- Only applies security headers when in prod and not development
Closes: https://github.com/mozilla/fxa/issues/9101
> fix(graphql): Fix graphql playground

- packages/fxa-settings/src/components/ConnectedServices/index.tsx
- packages/fxa-settings/src/components/DataCollection/index.tsx
- We want to maintain consistent design and UX throughout the site
- Updates h2 classes to align all headers
Closes: #9324
N/A
Also corrected alignment for "Data Collection and Use"
> style(settings): fix alignment of headers on Settings page

- packages/fxa-content-server/app/styles/modules/_marketing.scss
- We want to maintain consistent design and UX throughout the site
- Updates styles for Firefox Relay icon position
Closes: #11310
N/A
N/A
> style(content): fix alignment of "Firefox Relay" icon on sign-in page

- packages/fxa-react/components/Footer/index.test.tsx
- packages/fxa-react/components/Footer/index.tsx
- packages/fxa-react/components/Head/index.tsx
- packages/fxa-settings/src/components/BentoMenu/index.test.tsx
- packages/fxa-settings/src/components/BentoMenu/index.tsx
- packages/fxa-settings/src/components/DropDownAvatarMenu/index.test.tsx
- packages/fxa-settings/src/components/DropDownAvatarMenu/index.tsx
- packages/fxa-settings/src/components/GetDataTrio/index.tsx
- packages/fxa-settings/src/components/HeaderLockup/index.test.tsx
- packages/fxa-settings/src/components/HeaderLockup/index.tsx
- packages/fxa-settings/src/components/PageAvatar/buttons.tsx
- packages/fxa-settings/src/components/PageAvatar/index.test.tsx
- packages/fxa-settings/src/components/PageAvatar/index.tsx
- packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
- packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx
- packages/fxa-settings/src/components/Security/index.test.tsx
- packages/fxa-settings/src/components/UnitRowRecoveryKey/index.test.tsx
- packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx
- packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.test.tsx
- packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
Because:
* We must provide fallback text when pulling strings from Fluent since at the moment, we don't deploy en/en-US strings and rely on fallback text
This commit:
* Adds the default text to several l10n.getString calls, updates some tests
fixes #12857
fixes #12858
fixes #12859
---
I started adding tests for all of these and then realized we were missing quite a few and some tests might take a bit longer to write. If you see something in particular feel free to call it out.
At the time of writing, without further investigation I don't know why these ever rendered correctly, we've been relying on fallback text for English for all of our strings and we even had tests to check for FTL IDs rendered rather than the English text. 
This makes me eager to work on [this …
> fix(settings): Add default text to several l10n.getString calls

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/routes/linked-accounts.ts
- packages/fxa-auth-server/package.json
- packages/fxa-auth-server/test/local/routes/linked-accounts.js
- yarn.lock
Because:
* Apple only requires the generated token to be updated every six months
This commit:
* Generates the JWT for the client secret on each request as a better approach
Closes #12391
> fix(apple): Generate JWT for client secret on each request

- packages/fxa-admin-panel/interfaces/index.ts
- packages/fxa-admin-panel/server/config/index.ts
- packages/fxa-admin-panel/server/lib/client-config/index.test.ts
- packages/fxa-admin-panel/server/lib/client-config/index.ts
- packages/fxa-admin-panel/src/App.test.tsx
- packages/fxa-admin-panel/src/App.tsx
- packages/fxa-admin-panel/src/components/AccountSearch/Account/index.test.tsx
- packages/fxa-admin-panel/src/components/AccountSearch/Subscription/index.test.tsx
- packages/fxa-admin-panel/src/components/Guard/index.test.tsx
- packages/fxa-admin-panel/src/components/Guard/index.tsx
- packages/fxa-admin-panel/src/components/Permissions/index.test.tsx
- packages/fxa-admin-panel/src/components/Permissions/index.tsx
- packages/fxa-admin-panel/src/hooks/GuardContext.ts
- packages/fxa-admin-panel/src/lib/config.ts
- packages/fxa-admin-server/README.md
- packages/fxa-admin-server/src/auth/user-group-header.guard.ts
- packages/fxa-admin-server/src/config.ts
- packages/fxa-shared/guards/AdminPanelGuard.ts
- packages/fxa-shared/guards/Guard.ts
- packages/fxa-shared/test/guard/AdminPanelGuard.ts
- packages/fxa-shared/test/guard/Guard.ts
- The remote group was not resolved correctly which rendered the admin panel useless.
- Targets the correct header, 'remote-groups', which was previously 'REMOTE-GROUP'. This small thing was really the crux of the problem.
- Does some cleanup and removes magic strings for header keys.
- Makes the AdminPanelGuard aware of the current environment. This ended up being the bulk of the changes, and was necessary since user groups are environment specific, and therefore the guard needs to be able to distinguish this. I.e. A user user could be part of an ldap group that has admin privileges on stage, but not part of the ldap group that has admin privileges on prod. 
- Resolves the correct user group for the current environment. For example, when both stage and prod ldap groups are provided in …
>  fix(admin-panel): Fix remote group resolution

- packages/fxa-auth-server/lib/error.js
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-content-server/app/scripts/lib/email-domain-validator.js
- packages/fxa-content-server/app/tests/spec/lib/email-domain-validator.js
- packages/fxa-content-server/server/lib/routes/validate-email-domain.js
- packages/fxa-content-server/tests/server/routes/validate-email-domain.js
- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.stories.tsx
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.test.tsx
- packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx
- packages/fxa-payments-server/src/lib/apiClient.ts
- packages/fxa-payments-server/src/routes/Checkout/index.test.tsx
- packages/fxa-payments-server/src/routes/Checkout/index.tsx
- packages/fxa-shared/email/emailValidatorErrors.ts
- packages/fxa-shared/email/topEmailDomains.ts
- packages/fxa-shared/email/validateEmail.ts
Because:
* We want to prevent subscriptions created for fraudulent purposes that use invalid email domains
This commit:
* As a temp solution refactors the email domain check used by content server and piggy-backs off the account status check to return information about the validity of the email domain
Closes https://github.com/mozilla/fxa/issues/12406
This is a temporary solution until we evaluate alternatives in #12405 and determine what a more permanent solution will be. I wanted this to be minimally invasive in how things currently work and as easily to remove/revert as possible later.
> feat(payments): add Email Verification to Passwordless Flow

- packages/fxa-auth-server/lib/payments/subscription-reminders.ts
- packages/fxa-auth-server/lib/senders/email.js
- packages/fxa-auth-server/test/local/payments/subscription-reminders.js
Because:
* The email sender defaults to the VPN's privacy and ToS links in the email footer, we need to pass the product/plan specific metadata
This commit:
* passes the metadata from the formattedSubscription object to the message received by the email sender
Closes #12655
> fix(auth): pass Product/Plan Metadata to Email Sender

- packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
- These were not being translated
- Adds defaults for the checkboxes
Closes: https://github.com/mozilla/fxa/issues/12900
This will need to be uplifted to train 232, cc @chenba
> fix(strings): Add default string for delete account checkbox

- packages/fxa-payments-server/public/locales/en-US/main.ftl
- packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.test.tsx
- packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.tsx
- packages/fxa-payments-server/src/components/PaymentMethodHeader/index.test.tsx
- packages/fxa-payments-server/src/lib/formats.ts
- This variable is not being used anywhere. The linter is broken on localization files.
- Removes the unused variable
Closes: # 12726
> chore(payments): Missing markup in payment-confirm string

- packages/fxa-admin-panel/src/components/Permissions/index.test.tsx
- packages/fxa-admin-panel/src/components/Permissions/index.tsx
- Currently, a user can be confused as to whether they have a given permission or not, because the negative symbol is `x`. We use clearer positive/negative symbols to indicate permission status.
- Replaces the symbols with more vivid unicode symbols (`U+2705`:  ✅ and `U-274C`: ❌)
Closes: #12743 
Before (user has permissions):
Before (user does not have permissions):
After (user has permissions):
After (user does not have permissions):
To test:
With the `fxa-admin-panel` app running in local, visit `http://localhost:8091/permissions` and observe the permissions for your user. I don't know how to change the permissions for the logged in user, but to view the opposite of whatever permissions you're seeing, switch the values in the ternary …
> fix(fxa-admin-panel) use clearer icons to indicate permission status

- packages/fxa-payments-server/src/components/PaymentLegalBlurb/index.tsx
- The fallback text in the payments legal blurb returned a string with
html components.
- Replaces the string with React components, which will correctly render
as html.
Closes: #12926
> fix(payments): fallback text in legal blurb

- _dev/docker/builder/Dockerfile
- our deploy-packages job is failing now due to python 2 not 3 being installed
> chore(build): switch to python3 in builder docker deps

- packages/fxa-settings/src/components/App/en-US.ftl
- packages/fxa-settings/src/components/Security/en-US.ftl
- packages/fxa-settings/src/components/Security/index.tsx
- packages/fxa-settings/src/components/UnitRowRecoveryKey/index.test.tsx
- packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx
- packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.test.tsx
- packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx
Firefox Sync should not be treated as a feature name anymore (starting with Firefox 89)
https://mana.mozilla.org/wiki/pages/viewpage.action?spaceKey=FIREFOX&title=Word+List#WordList-sync
> Don't treat Firefox Sync as a feature name

- packages/fxa-auth-server/lib/payments/iap/apple-app-store/apple-iap.ts
- packages/fxa-auth-server/lib/routes/subscriptions/apple.ts
- packages/fxa-auth-server/lib/routes/subscriptions/index.ts
- packages/fxa-auth-server/test/local/routes/subscriptions/apple.js
Because:
* We want to support iOS App Store purchase registration.
This commit:
* Adds an app-store registration endpoint to register transactions
to a users account.
Closes #10314
> feat(auth): add app store registration endpoint

- packages/fxa-shared/l10n/supportedLanguages.json
- we don't need to support sr-LATN anymore
- removes it
Closes: #12950
> feat(l10n): remove sr-LATN support. Fix FXA-5126

- packages/fxa-admin-panel/.eslintrc.json
- packages/fxa-admin-panel/package.json
- the .storybook/ folder wasn't getting linted.
- Moves the ESLint config from package.json into .eslintrc.json
- Explicitly lints .storybook/ as well (I guess ESLint ignores hidden files/folders by default)
> chore(lint): Tweak ESLint config for fxa-admin-panel

- packages/fxa-settings/.eslintrc.json
- packages/fxa-settings/package.json
- linting currently fails hard due to missing "lint:sass" script.
- removes reference to undefined "lint:sass" script
- moves the ESLint config from the package.json into the more standard/consistent .eslintrc.json file
- lints the hidden .storybook/ folder
Closes: #12933
> chore(lint): Fix linting in fxa-settings package

- packages/fxa-payments-server/src/lib/coupon.test.ts
- Tests for functions that manipulate the current date, are flaky since
the expected date in test doesn't always match the date used in the
function.
- For these tests match on the date by seconds instead of miliseconds.
Closes: #
> chore(payments): fix flaky test with date matching

- packages/fxa-admin-server/src/gql/account/account.resolver.ts
- Auto complete during account search was very slow
- Uses the normalizedEmail column which is optimized for search.
- Also fixes an unlikely but possible non-lowercased email query in accountByEmail.
Closes: #12346
> fix(admin-panel): Fix slow autocomplete in account search

- packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.scss
- We want to maintain consistent design, UX and a11y in emails
- Adds font-size to create whitespace between text and underline
Closes: #12600
N/A
N/A
> style(auth): add space to alt text and underline

- packages/fxa-auth-server/lib/profile/client.js
- packages/fxa-auth-server/lib/routes/index.js
- packages/fxa-auth-server/lib/routes/linked-accounts.ts
- packages/fxa-auth-server/lib/types.ts
- packages/fxa-profile-server/lib/routes/display_name/post-from-auth-server.js
- packages/fxa-profile-server/lib/routing.js
- packages/fxa-profile-server/test/api.js
- Currently, when a user creates a new FXA account via 3rd party authentication, we have access to profile data provided from the 3rd party authenticator. We don't currently do anything with that data. This PR takes the display name used in the 3rd party and applies it to the FXA account on creation. This provides a pattern to follow in future PRs when applying other pieces of data.
- Creates a new route on the profile server for updating a profile name from the auth server. We need a new route because the auth server authenticates via a secretBearerToken (and not oauth, as the existing profile name route expects.) 
- Adds a test for the new route
- Makes that route available on the profile client (which is used by the auth server to hit the profile server.)
- Adds the Profile Client to …
> feat(fxa-auth-server) 3rd party authentication sets default profile display name

- .gitignore
- packages/fxa-admin-server/package.json
- packages/fxa-admin-server/pm2.config.js
- packages/fxa-admin-server/src/config/development.json
- There were issues starting the admin-server.
- Introduces a development.json to solve issues with missing dev settings.
- Make sure the dist folder is actually cleaned. It was possible that a stale config.js file could cause problems.
- Make sure build runs without error and config/*.json files are copied over.
Trying to address [CI](https://app.circleci.com/pipelines/github/mozilla/fxa/30574/workflows/dce7b0cf-e47f-4eb8-b902-2e340bd0c2eb/jobs/336521/steps) failure, and issues other developers had starting admin-server.
> fix(admin-server): Fix broken build command

- packages/fxa-auth-server/test/local/routes/linked-accounts.js
- packages/fxa-auth-server/test/mocks.js
- Profile Client was added to the linked accounts route.
- Adds a profile mock to the linked account routes tests to prevent some
tests from failing.
Without this fix, these are the tests that fail for me.
> chore(auth): add profile mock to tests

- package.json
- yarn.lock
Because:
* Lodash needs an update
This commit:
* Updates lodash via resolutions
---
Updated per [these docs](https://mozilla.github.io/ecosystem-platform/reference/team-processes/triage-process#security-warnings).
> chore(deps): Upgrade lodash

- packages/fxa-auth-server/package.json
- yarn.lock
Reverts mozilla/fxa#12874
p-retry 5 uses ESM, we can't use ESM yet.
> Revert "chore(deps): bump p-retry from 4.6.2 to 5.1.1"

- package.json
- yarn.lock
Reverts mozilla/fxa#13001
This appeared to have broke the ability to build content-server. Putting up a revert to test if this fixes it.
> Revert "chore(deps): Upgrade lodash"

- _scripts/pm2-all.sh
- `fxa-auth-client` doesn't get updated if no deps changed
- Might be a better way to do this, ~~but it worked locally for me~~
- Updates `yarn start` to build shared or dependent code (fxa-shared, fxa-auth-client, fxa-react)
- ~~I tried doing `yarn workspaces foreach run build` but that builds everything and took 15mins~~
Closes: https://github.com/mozilla/fxa/issues/12903
> fix(configs): Build shared projects on `yarn start`

- packages/fxa-payments-server/src/components/DialogMessage/index.tsx
- packages/fxa-payments-server/src/routes/Subscriptions/index.tsx
- We want ensure all user interactions meet accessibility standards
- Adds a11y attributes to modal close button svg
Closes: #12921
N/A
The `<svg>` can be hidden from screen readers since the parent `<button>` already has an aria-label associated with it, and `<svg>` is being used strictly for visual purposes.
> fix(a11y): add a11y to modal close button svg

- packages/fxa-content-server/package.json
- We already have a root [.nvmrc](https://github.com/mozilla/fxa/blob/main/.nvmrc) file, so having similar [but very outdated] information is confusing.
-
Closes: #12895 
> chore(package): Remove node/npm engines from fxa-content-server/package.json

- .github/CODEOWNERS
- localization team should be notified for changes to Fluent files, so that review can happen during development instead of after landing
- updates CODEOWNERS with l10n project owners
Both flod (@flodolo ) and I (@bcolsson) may also need to be added as contributor to this repository. According to the docs we believe "read" access should be enough (or would we need "write"?).
> chore(repo): set l10n drivers as owners of .ftl files

- packages/fxa-settings/.storybook/main.js
- packages/fxa-settings/.storybook/preview.js
- packages/fxa-settings/package.json
- packages/fxa-settings/src/components/Nav/index.stories.tsx
- packages/fxa-settings/src/components/PageSettings/index.stories.tsx
- yarn.lock
chore(storybook) add LinkedAccounts to stories
chore(storybook) refactor nav stories
fix(storybook) use addon to get ltr/rtl in storybook
- Styles in storybook did not match what we were seeing in prod/local/staging. Also, some cases were missing from demos of the Settings page and nav.
- Adds in additional cases (specifically, an account with Linked Accounts) and also adds a storybook addon to enable ltr/rtl specific styles
Closes: #12848 
Before (no linked accounts stories):
After (with linked accounts stories):
Before (without rtl/ltr addon):
After (with rtl/ltr addon):
The reason why the styles in storybook looked wrong, even thought they looked fine when rendered outside of storybook, is because some of our styles were only being applied in the …
> chore(storybook) update storybook format and add ltr/rtl support

- packages/fxa-settings/src/components/ConnectedServices/en-US.ftl
- Current comment is single message only so localizers will be unable to see comment for all applicable strings where variable is used
- Changes existing comment from single message only  to group-level comment
> chore(strings): fix comment issue in fxa-settings ftl file

- packages/fxa-auth-server/config/index.ts
- packages/fxa-auth-server/lib/db/index.js
- packages/fxa-auth-server/lib/payments/subscription-reminders.ts
- packages/fxa-auth-server/lib/routes/account.ts
- packages/fxa-auth-server/lib/routes/linked-accounts.ts
- packages/fxa-auth-server/lib/tokens/session_token.js
- packages/fxa-auth-server/test/client/index.js
- packages/fxa-auth-server/test/local/routes/account.js
- packages/fxa-auth-server/test/local/routes/linked-accounts.js
- packages/fxa-auth-server/test/local/routes/session.js
- packages/fxa-auth-server/test/local/routes/utils/signin.js
- packages/fxa-auth-server/test/local/tokens/session_token.js
- packages/fxa-auth-server/test/mocks.js
- packages/fxa-content-server/app/scripts/views/push/confirm_login.js
- packages/fxa-shared/db/models/auth/base-auth.ts
- packages/fxa-shared/db/models/auth/base-token.ts
- packages/fxa-shared/db/models/auth/session-token.ts
- We no longer use `tokenVerificationCode` to verify sessions
- Note that in orginal issue we called out removing `tokenVerificationId`, however this is still being used to verify sessions
- Removing references and code that use this value
- Stop writing this value to the database
Closes: https://github.com/mozilla/fxa/issues/12489
> chore(db): Cleanup and remove `tokenVerificationCode`

- packages/fxa-payments-server/src/components/AppLayout/index.tsx
- We want to improve UX and a11y
- White space improves user focus and readability, delineates sections, and reduces noise, especially with before footer content
- Adds margin bottom to subscriptions card, consistent with the amount of space after the last card in Account Settings
Closes: #8952
N/A
N/A
> style(payments): add bottom margin to subscriptions page

- packages/fxa-event-broker/package.json
- packages/fxa-event-broker/src/queueworker/service-notification.interface.ts
- packages/fxa-event-broker/src/queueworker/sqs.dto.ts
- yarn.lock
- the `typesafe-joi` dependency utilizes `@hapi/joi` v15.x, which is deprecated
- revises `joi<Literal>`s to regular Typescript
Closes: #13021
> refactor(event-broker): Remove typesafe-joi dependency

- packages/fxa-auth-server/lib/sentry.js
- packages/fxa-auth-server/test/local/sentry.js
- The error messages going to sentry are often the WError: Internal Server Error, which don't contain enough info.
- Reports the actual error to sentry instead the WError.
- Does this by binding to the server events in a slightly different way.
Closes: #11864
> fix(auth): Report actual error to Sentry

- packages/fxa-content-server/package.json
- yarn.lock
Fixes https://github.com/mozilla/fxa/issues/13192
> chore(deps): bump xmlhttprequest from 1.5.1 to 1.8.0

- packages/fxa-content-server/package.json
- packages/fxa-payments-server/package.json
- yarn.lock
Fix https://mozilla-hub.atlassian.net/browse/FXA-5279
> chore(deps): bump jquery-modal from 0.7.1 to 0.9.2

- packages/fxa-content-server/package.json
- yarn.lock
Fixes https://github.com/mozilla/fxa/issues/13196
> chore(deps): bump ua-parser-js from 0.7.10 to 1.0.2

- packages/fxa-content-server/package.json
- packages/fxa-payments-server/package.json
- yarn.lock
Because:
* The upgrade of jquery-modal broke resubscribing in Subscription Management.
This commit:
* Reverts commit 8df9ba3552f02a70cea1613b5b5c77369fc48008.
Closes #13226
> Revert "chore(deps): bump jquery-modal from 0.7.1 to 0.9.2"

- packages/fxa-content-server/server/lib/routes/get-openid-configuration.js
- packages/fxa-content-server/tests/server/routes/get-openid-configuration.js
- The /v1/verify end point was not included in the /.well-known/openid-configration response.
- Adds the /v1/verify endpoint to the openid-configration
Closes: #13185
> fix(content): Add verify endpoint to well-known list

- packages/fxa-payments-server/src/lib/account.test.ts
- packages/fxa-payments-server/src/lib/account.ts
- packages/fxa-payments-server/src/lib/errors.ts
- Currently when the stub account creation throws an error that the
account already exists, it is reported to Sentry.
- Due to recent changes, it has become very difficult for this situation
to happen, and usually only occurs when non-standard steps are
performed. For example, the user has 2 tabs open.
- Does not report to Sentry when the Stub Account creation returns with
and error that the Account already exists.
Closes: #10344
> fix(payments): do not report account exist error

- .github/workflows/upload-assets-to-cdn.yml
- Environment variables were not being consumed properly with `$VARNAME` syntax. 
- Partially moved to context property syntax `${{ VARNAME }}` but the context was missing `${{ env.VARNAME }}`
- Adds the context to the environment variables used in the slack notification for the cdn-upload workflow 
> Using context property syntax for variables in slack notifcation
